### ISSUE TITLE
Facet_wrap should support margins

### ISSUE THREAD

**Issue by hadley** [tidyverse/ggplot2#110]

**Comment by lionel-** [comment]
@hadley Could this be reconsidered?

Margins are great for exploring the effect of conditioning on a variable.

**Comment by thomasp85** [comment]
Can you describe how you expect this to work for `facet_wrap()`? If it's not too demanding I'll consider it in the facet rewrite

**Comment by lionel-** [comment]
Thanks! I would expect it to work like `facet_grid()` for consistency. The margin facets (there can be multiple ones with `+` formulas) would be added at the end. 

Hopefully some of the code for grid facet margins can be extracted and reused for wrap facets.

**Comment by thomasp85** [comment]
Ok - so not row and column based (which I couldn't make sense of in my head)
