### ISSUE TITLE
Immutable flag for ggproto objects

### ISSUE THREAD

**Issue by hadley** [tidyverse/ggplot2#1237]
Would be useful to make it explicit that most ggproto objects (with the exception of ranges) are immutable. Could add extra class that has `$<-.ggimmutable` method defined to throw error

**Comment by wch** [comment]
For immutable objects, it might be possible to simply use a list instead of environment as the underlying storage object. Actually, it wouldn't exactly be immutable, but rather copy-on-write like most R objects.

I think there are only a couple places in the ggproto code that expect an environment; most of it should work fine with both environments and lists.

**Comment by hadley** [comment]
That would be more elegant but would also be a lot of work for little practical gain

**Comment by hadley** [comment]
I discovered a nice approach:

```R
Immutable <- ggproto("Immutable", NULL)
#' @export
`$<-.Immutable` <- function(x, i, value) {
  stop("This object is immutable", call. = FALSE)
}
```

and then `Geom` etc inherits from Immutable rather than NULL.

I breaks two functions: `update_geom_defaults()` and `update_stat_defaults()`, which let the user modify the properties of default geoms. Maybe I can fix those my making those functions create new geom objects in the current environment.

**Comment by hadley** [comment]
Oh that doesn't work because (e.g.) `GeomPoint` uses a fixed reference - it doesn't search up environments for a named object.

**Comment by wch** [comment]
I also realized that although using a list makes the underlying object immutable (and copy-on-write), the R interface makes it look mutable. For example:

```R
x <- list()
x$a <- 1
```

In this case, `x` is first an empty list. After assigning `x$a`, `x` actually points to a different list object in the underlying implementation. But R makes it look like `x` has changed. So even if a ggproto object was backed by a list, you'd still need to define `$<-.Immutable`.

**Comment by hadley** [comment]
Given that this issue is >2 years old and it doesn't seem to be causing practical problems, I'm closing.
