### ISSUE TITLE
Create GeomCustom that uses a list-column of grobs

### ISSUE THREAD

**Issue by baptiste** [tidyverse/ggplot2#1399]
[I thought I'd raised this before, but can't find it anywhere so maybe I didn't.]

Currently `annotation_custom` and `annotation_raster` don't allow specifying a particular facet, they're always drawn on each facet, but that's often not the desirable behaviour. See [this recent example](http://stackoverflow.com/q/32807665/471093)

For the raster, one can always use a new `geom_raster` layer as a workaround, but there's no layer equivalent for `annotation_custom`, so one is left with no option but post-processing the plot.

I believe there's an easy fix (see my answer in that same thread), but I'm not very up-to-date with the inner workings of ggplot2.

**Comment by hadley** [comment]
I think this is fundamental to the nature of annotations - they appear on every facet. Perhaps what is needed is a `geom_grob()` layer? I think now that you can write your own top level geoms in packages, it would be better to go in another package than in ggplot2 (that way someone can be more aggressive about maintaining it)

**Comment by janschulz** [comment]
see hrbrmstr/ggalt#4 for more discussion on this

**Comment by baptiste** [comment]
for future reference it looks like list-columns can help create a geom_ version of annotation_custom, where separate facets can get different grobs.

```
library(ggplot2)
library(tibble)
library(gridExtra)


d <- tibble(x=rep(1:3, 4), f=rep(letters[1:4], each=3))

GeomCustom <- ggproto(
  "GeomCustom",
  Geom,
  setup_data = function(self, data, params) {
    data <- ggproto_parent(Geom, self)$setup_data(data, params)
    data
  },
  
  draw_group = function(data, panel_scales, coord) {
    vp <- grid::viewport(x=data$x, y=data$y)
    g <- editGrob(data$grob[[1]], vp=vp)
    ggplot2:::ggname("geom_custom", g)
  },
  
  required_aes = c("grob","x","y")
  
)



geom_custom <-  function(mapping = NULL,
           data = NULL,
           stat = "identity",
           position = "identity",
           na.rm = FALSE,
           show.legend = NA,
           inherit.aes = FALSE,
           ...) {
    layer(
      geom = GeomCustom,
      mapping = mapping,
      data = data,
      stat = stat,
      position = position,
      show.legend = show.legend,
      inherit.aes = inherit.aes,
      params = list(na.rm = na.rm, ...)
    )
}

library(grid)

gl <- lapply(1:4, function(c) rectGrob(gp=gpar(fill=c), width=0.2, height=0.2))
dummy <- tibble(f=letters[1:4], grob = gl )

ggplot(d, aes(x,x)) +
  facet_wrap(~f) +
  geom_custom(data=dummy, aes(grob=grob), inherit.aes = FALSE,
              x = 0.5, y=0.5)

gl <- list(tableGrob(iris[1:2,1:3]), 
           tableGrob(iris[1:4,1:3]),
           tableGrob(iris[1:3,1:3]),
           tableGrob(iris[1:2,1:2]))
dummy <- tibble(f=letters[1:4], grob = gl )

ggplot(d, aes(x,x)) +
  facet_wrap(~f) +
  theme_bw() +
  geom_custom(data=dummy, aes(grob=grob), x = 0.5, y = 0.5)
```

would still need to work out the proper way to handle coordinates but that doesn't sound problematic.

<img width="1051" alt="screen shot 2017-09-30 at 5 10 23 pm" src="https://user-images.githubusercontent.com/18970/31042387-5900fa6e-a603-11e7-8cd4-3ecd4d377b79.png">

**Comment by hadley** [comment]
Nice!

**Comment by hadley** [comment]
My sense now is that this best handled in an extension packing, so I'm tagging in @hrbrmstr and @thomasp85.
