### ISSUE TITLE
outlier.colour in geom_boxplot

### ISSUE THREAD

**Issue by ThierryO** [tidyverse/ggplot2#146]
outlier.colour from geom_boxplot() does not work with mapping

```
library(ggplot2)
dataset <- expand.grid(x = factor(c("A", "B")), y = c(rep(1, 50), 10), z = factor(c("C", "D")))
dataset$y <- rnorm(nrow(dataset), mean = with(dataset, y * as.numeric(x)), sd = as.numeric(dataset$z))
ggplot(dataset, aes(x = x, y = y, colour = z)) + geom_boxplot()
ggplot(dataset, aes(x = x, y = y, colour = z)) + geom_boxplot(outlier.colour = "red")
ggplot(dataset, aes(x = x, y = y, colour = z)) + geom_boxplot(aes(outlier.colour = z))
```

**Comment by sthelen** [comment]
This ticket is confusing. There are answers on stack exchange, such as http://stackoverflow.com/a/16035956, that suggest this feature has been available in the past. But at least in the current 1.0.0 version it does not work for me, and hadley's comment above indicates that no work has been done on this feature.
