### ISSUE TITLE
Using `margin` to adjust `legend.text`?

### ISSUE THREAD

**Issue by Henrik-P** [tidyverse/ggplot2#1502]
In [issue  #1435](https://github.com/hadley/ggplot2/issues/1435) on adjusting `element_text`, we find that "`vjust` and `hjust` no longer work. Instead, use the `margin()` parameter of `element_text()`". Does this apply also for `legend.text`?

I have a plot in which I want to adjust the `legend.text` horizontally.

```
df <- data.frame(x = c("a", "b"), y = 1)

p <- ggplot(df, aes(x = x, y = y, fill = x)) +
   geom_bar(stat = "identity") +
   ggtitle("My plot")
p
```

I followed the suggestion in #1435: "if you're having problems understanding the layout, try `debug = TRUE`":

```
p + theme(text = element_text(debug = TRUE))
```

I am not entirely sure I interpret the "debugging plot" correctly, but I thought it indicated all text elements which could be adjusted. Here, areas corresponding to `axis.text`, `axis.title`, and `plot.title`, are highlighted, but seemingly not those for `legend.text` (nor for `legend.title`).

I have tried to "push" and "pull" the `legend.text` horizontally using

```
p + theme(legend.text = element_text(margin = margin(l =  , r =  )))
```

...with various combinations of `l` and `r`, to no avail.

Thus my question: is `legend.text` (and `legend.title`) not included among the `element_text` elements which can be adjusted using `margin`? Which is the current ''official' way to adjust these elements?

**Comment by hadley** [comment]
Could you explain in a bit more detail what you're trying to do? Currently the margin only applies to title elements.

**Comment by hadley** [comment]
Hmmm, this looks like an oversight - I seem to be doing something special for legends so they follow the usual process to get a `titleGrob()`

**Comment by hadley** [comment]
Re-opening - because of the way the way themes, legends, and margins interact, this is going to require considerably more thought.

**Comment by adefazio** [comment]
Is there a workaround for this in the meantime? Other than padding the actual text with spaces.

**Comment by Huimincheng2015** [comment]
I met the same problem, everything is ok when I apply margin() for axis.title.x, axis.title.y, plot.margin, plot.title and legend.margin, but there seems to be something wrong with legend.text and legend.title.
So till now is there any way to settle this problem?

**Comment by R-Joe** [comment]
I have a similar problem. I have a legend located at the bottom of a plot and the legend’s title positioned on top, and I want to increase the spacing between the legend keys and the legend title.
To do this I tried changing values in `title.vjust`, in the `guides` function, but nothing happens.
Is there already a solution for this issue?
Bellow I provide a reproducible example:

```
library(ggplot2)

ggplot(data=PlantGrowth, 
 aes(x=group, fill=group)) +
     geom_bar() +
 theme(legend.position="bottom")+
 guides(fill=guide_legend(title.position="top",
                          title.hjust=0.5,
                          title.vjust=10)) # nothing happens when changing values in title.vjust
```

**Comment by fcturner** [comment]
This is also asked on StackOverflow with unsatisfactory advices: https://stackoverflow.com/questions/11366964/is-there-a-way-to-change-the-spacing-between-legend-items-in-ggplot2

A solution like 
```r
p + theme(legend.text = element_text(margin = margin(r = 24, unit = "pt")))
```
after using `legend.position = "top"` would be highly appreciated 😉 

To give an example where I would like to use this (please ignore my other theming):
![image](https://user-images.githubusercontent.com/7526559/27865263-2fdeabb4-6192-11e7-8690-96b9345f1e2e.png)

**Comment by ptoche** [comment]
padding text labels with space seems to be the only option that does not involve manipulating the grobs directly...

**Comment by hadley** [comment]
Deleting the comments unrelated to the body of the problem.

**Comment by hadley** [comment]
Neither hjust not margins appear to work:

``` r
library(ggplot2)
df <- data.frame(x = c("a", "bbbbbbbbbbbbb"))

ggplot(df, aes(x = x, fill = x)) +
  geom_bar() +
  theme(legend.text = element_text(hjust = 1))
```

![](https://i.imgur.com/Ppy7TFI.png)

``` r

ggplot(df, aes(x = x, fill = x)) +
  geom_bar() +
  theme(legend.text = element_text(margin = margin(l = 50)))
```

![](https://i.imgur.com/F1tXMKR.png)

**Comment by hadley** [comment]
The basic problem is that I have no idea how the legend code works any more, and it's extremely complex due to the many possible places that theme settings can come from.

**Comment by karawoo** [comment]
I looked into this a bit at the end of the summer but never figured out the legend code enough to tackle it 😞 . I think the approach would need to be similar to what we did for strip labels, but I remember it being still more complicated for legends.

**Comment by clauswilke** [comment]
I think I've got this working now (see: https://github.com/tidyverse/ggplot2/pull/2556), except for a minor problem with the default `hjust` setting.

```{r}
library(ggplot2)
df <- data.frame(x = c("a", "bbbbbbbbbbbbb"))

ggplot(df, aes(x = x, fill = x)) +
  geom_bar() +
  theme(legend.text = element_text(margin = margin(l = 50), hjust = 0))
```
<img width="487" alt="screen shot 2018-05-07 at 12 32 17 am" src="https://user-images.githubusercontent.com/4210929/39686420-8131263a-518e-11e8-8f2c-793f9c84408c.png">
