### ISSUE TITLE
Scale types overhaul

### ISSUE THREAD

**Issue by hadley** [tidyverse/ggplot2#1526]
- Make sure all scales work with dates/datetimes
- Better colour/fill scales for ordered factors
- Warn when mapping factor to size
- Consider different viridis scales (using viridisLite) for fill/colour
- Better default breaks for log axes
- Document how to extend with your own S3 classes
- Consider support for percentage, proportion, and likert s3 types
- Could we have a `jitter_na()` type for position scales?

**Comment by zeehio** [comment]
Hi,

Sorry to bother you, I believe I found an issue related to this commit:

It seems that functions defined in [`R/zxx.R`](https://github.com/hadley/ggplot2/blob/master/R/zxx.r#L16) such as `scale_colour_datetime` do not accept common scale arguments such as `name=`.

```r
ggplot(data.frame(x=c(1,2,3),
                  y=c(2,5,6),
                  color = as.Date(c(1,2,3), origin="2015-01-01"))) + 
   geom_point(aes(x=x, y=y, color=color))  +
   scale_colour_datetime(name="a")
```

    Error in scale_colour_datetime(name = "a") : unused argument (name = "a")

Found as of:

     ggplot2               * 2.1.0   2016-03-01 CRAN (R 3.2.5) 

It seems this is work in progress, so I don't want to step in too much... I hope that reporting this small issue is useful.

Best and thanks for your awesome work!

**Comment by hadley** [comment]
@zeehio please file a separate issue instead of adding a comment to an unrelated one

**Comment by huftis** [comment]
@hadley Regarding your last point, ‘different colour scales for fill/colour’: If you’re thinking about the *continuous* colour scales, I recommend watching this (fascinating!) [video about the new default colour scale in matplotlib](http://matplotlib.org/style_changes.html). (There’s also [an R implementation](https://cran.r-project.org/web/packages/viridis/vignettes/intro-to-viridis.html).)

**Comment by hadley** [comment]
@huftis yup I'm aware of viridis, and I'm considering making it the default.

**Comment by hadley** [comment]
One hacky way of better display for missing values:

```R
add_na <- function(x, prop = 0.1) {
  x[sample(seq_along(x) <= prop * length(x))] <- NA
  x
}

df <- tibble(
  x = letters[1:3] %>% sample(100, replace = TRUE) %>% add_na(),
  y = rnorm(100) %>% add_na()
)

ggplot(df, aes(x, y)) +
  geom_point()

miss <- df %>% filter(is.na(y))

# Jittering and display at one end of the scale is an old idea
# Andreas Buja and was implemented in XGobi/GGobi

ggplot(df, aes(x, y)) +
  geom_point(na.rm = TRUE) +
  geom_jitter(aes(y = 3.5), data = miss, width = 0.05, height = 0.05, colour = "darkred") +
  geom_hline(yintercept = 2.8, size = 10, colour = "white") +
  scale_y_continuous(
    breaks = c(-2, -1, 0, 1, 2, 3.5),
    labels = c(-2, -1, 0, 1, 2, "NA")
  )
```

**Comment by hadley** [comment]
Mostly done by @karawoo
