### ISSUE TITLE
Add asymmetrical `expand` argument to continuous and discrete scales

### ISSUE THREAD

**Issue by huftis** [tidyverse/ggplot2#1669]
This is a feature request for an asymmetrical `expand` argument to the `scale_continuous` and `scale_discrete` scales. A typical use case would be for bar plots that touch the _x_ axis but still have some space above them. For example

```
ggplot(mtcars) + 
  geom_bar(aes(x = cyl))
```

has some space above the bars, but also an annoying spaces below it. Now,

```
ggplot(mtcars) + 
  geom_bar(aes(x = cyl)) +
  scale_y_continuous(expand = c(0, 0))
```

gets rid of the space below the bars, but also the space above the bars. To keep the space above the bars, one has to use a hack with a manually calculated value:

```
ggplot(mtcars) + 
  geom_bar(aes(x = cyl)) +
  scale_y_continuous(expand = c(0, 0)) +
  annotate("blank", x = 6, y = 14.7)
```

(And this doesn’t work well with more complicated plots, e.g. involving facets with `free_y` &c.)

Suggested feature/syntax: Change the `expand` argument from

```
expand = c(a, b)
```

to

```
expand = c(a, b, c, d)
```

where `a` is the multiplier for the lower limit, `b` is the additive term for the lower limit, and `c` and `d` are the corresponding multiplier and additive term for the upper limit. If `c` is missing, use the value of `a`, and if `d` is missing, use the value of `b`. This way, all old code would continue to work.

See http://stackoverflow.com/questions/34623780/asymmetric-expansion-of-limits-ggplot2-2-0 for more information. This post also has suggested code for an asymmetrical `expand` feature, but this does not work for complicated facet grids, nor with `coord_flip()`.

**Comment by steveharoz** [comment]
Have a look at the `expand_limits` function

```
ggplot(mtcars) + 
  geom_bar(aes(x = cyl), width = 1) +
  scale_y_continuous(expand = c(0,0)) +
  expand_limits(y=25)
```

**Comment by huftis** [comment]
@steveharoz `expand_limits()` is a wrapper for `geom_blank()`, but still requires one to manually calculate the limits. This feature request is for an expansion of `expand` to handle separate values for the lower and upper limits, for *automatic* determining the correct limits. For this example, the new syntax would be:

    ggplot(mtcars) +
      geom_bar(aes(x = cyl), width = 1) +
      scale_y_continuous(expand = c(0, 0, 0.05, 0))

**Comment by huftis** [comment]
This doesn’t seem too difficult to add. I’ll try to create a patch and a pull request.

**Comment by hadley** [comment]
Hmmm, I'm not convinced I want this. Would you mind including a couple of before and after plots?

**Comment by huftis** [comment]
@hadley Sure.

First, note that this does not change the default look of ggplot2 graphs **at all**. So a simple before and after plot would look identical.

It gives the user the *option* of **asymmetrical** automatic range expansion for the *x* and *y* scales. This is most useful for bar charts (but there may be other uses). In almost all programs, the bars are attached to an axis, with no gap. Illustration: https://www.google.no/search?q=bar+chart&tbm=isch

However, in ggplot2 there is a gap, making the hover above the *x* axis

![ggplot2-default](https://cloud.githubusercontent.com/assets/100251/17300554/37f9918a-5813-11e6-81fa-0fb695baf1b2.png)

or the *y* axis

![ggplot2-flip](https://cloud.githubusercontent.com/assets/100251/17300583/49f66d86-5813-11e6-8da1-862dbae4003e.png)

One can use the `expand` argument to remove the gap (`scale_*_continuous(expand = c(0,0))`, but this also removes the gap above / to the right of the bars, which looks bad:

![ggplot2-expand-sym](https://cloud.githubusercontent.com/assets/100251/17300626/8274fdc6-5813-11e6-9a50-a23527681bb6.png)

One *can* use a `geom_blank()` hack or `expand_limits()`, but then one have to **manually** calculate the new limits, and this doesn’t work with faceting.

This pull request adds a feature for asymmetric range expansion. By default (and if one only specifies a length 2 expansion), everything works as before, with symmetric range expansion. But one can now also specify separate expansion constants for the lower and upper limits. This can be used to remove the gap in bar charts (while still leaving some space above / to the right of the bars):

![ggplot2-expand-asym](https://cloud.githubusercontent.com/assets/100251/17300795/297ccdc4-5814-11e6-900b-7d9079eaaa23.png)

I think many will find this a useful addition to ggplot2. Evidence:

1. https://stackoverflow.com/questions/22480052/how-to-expand-axis-asymmetrically-with-ggplot2-without-setting-limits-manually?noredirect=1&lq=1
2. https://stackoverflow.com/questions/34623780/asymmetric-expansion-of-limits-ggplot2-2-0
3. https://stackoverflow.com/questions/34342386/pad-expand-only-the-top-of-continuous-scale-in-ggplot2?noredirect=1&lq=1

(The last link illustrates a use case for a different type of graph than a bar chart.)

**Comment by hadley** [comment]
Hmmmm, that looks really weird to my eyes. I think ideally you want to have about the same margin in each dimension. The default ggplot2 margins aren't perfect (because of the additive/multiplicative) nature, but this makes it even worse.

**Comment by thomasp85** [comment]
I personally think it has some merit for bar charts, but agree that it looks weird with the default theme. A style where only the y-axis is drawn and with a white background serves it better...

**Comment by huftis** [comment]
Yes, that wasn’t an attempt to make a ‘perfect bar chart’ *at all*. (Firstly, I wouldn’t use the default theme, but typically one with a transparent background. And I would get rid of the tick marks. And the horizontal grid lines. And add some (symmetrical!) space (using `expand`) on the *other* axis. And follow Stephen Few’s latest [latest recommendations on bar widths and the spaces between them](http://www.perceptualedge.com/articles/visual_business_intelligence/bar_widths.pdf) (and yes, he *does* use asymmetrical ‘range expansion’).)

**Comment by thomasp85** [comment]
@hadley Can we either close or discuss the preferred API for setting asymmetric expansion. I'm personally *for* this feature for the single use case of bar charts (have personally done it manually with expand_limits a couple of times), but it is added complexity...

**Comment by hadley** [comment]
It still looks weird to me, but I'd accept a PR that fixed it. @huftis would you be willing take another shot at it?  To produce cleaner code, you'll need to setup a basic system of S3 classes that insulate the complexity of the new approach into a central location.

**Comment by huftis** [comment]
@hadley Sure, I’ll take a new look at creating a PR.

**Comment by hadley** [comment]
@huftis are you still interested? We'll be making a release candidate of ggplot2 in one week, so it'll need to be done by then if you want it in the next version of ggplot2.

**Comment by huftis** [comment]
Yes, still interested. Been a bit busy lately, but I’ll *try* to find time to get it done in the coming week.

**Comment by huftis** [comment]
@hadley I have a simplified (mostly) working version, but I’m really puzzled by some existing code in `scale-discrete-.r` (https://github.com/hadley/ggplot2/blob/master/R/scale-discrete-.r). This maintains separate continuous and discrete scales, and the `dimension()` function at around line 109 does separate calculations for discrete and continuous scales. That’s OK. But for a *combined* continuous/discrete scale (which is what you actually get even for a simple `ggplot(mtcars, aes(x = factor(cyl))) + geom_bar()`), the following is returned:

```r
range(
  expand_range(c_range, expand[1], 0 , 1),
  expand_range(c(1, length(d_range)), 0, expand[2], 1)
)
```

My understanding of this is: First an expanded range is calculated for the continuous scale, but only using the *multiplicative* constant (i.e. setting the additive constant to zero). And then an expanded range is calculated for the discrete scale, but only using the *additive* constant (i.e. setting the multiplicative constant to zero). And then the interval enclosing both these ranges are returned. What is the logic behind this?

**Comment by thomasp85** [comment]
Try to update to the latest version - this should have been fixed...

**Comment by huftis** [comment]
@thomasp85 I am using the latest version. That’s where I copied this piece of code from.

**Comment by thomasp85** [comment]
Oh, sorry - was thinking about something else slightly related (a few lines up)

**Comment by thomasp85** [comment]
Actually it is related - it is an oversight from when we fixed the other... Thanks for catching that

**Comment by huftis** [comment]
I think I understand it a bit better, but I still think it looks strange.

For

```r
ggplot(mtcars, aes(x = factor(cyl))) + geom_bar()
```
  
there will be three vertical bars, and c(1, length(d_range)) will be c(1,3). The continuous scale takes the bar widths into account, and so will be c(1-.9/2, 3+.9/2) == c(0.55, 3.45) (with the default bar width of .9). The range displayed must cover both, with a little extra space on each side.

Now, internally, this will be a discrete scale, so will have the default expansion of c(0, .6), i.e. add .6 on each side. The `expand_range(c(1, length(d_range)), 0, expand[2], 1)` code actually does this if the user hasn’t specified an `expand` argument. If the user has specified an `expand` argument, only the additive part is used (`expand[2]`).

For the continuous part, the calculation is `expand_range(c_range, expand[1], 0 , 1)`. By default, the multiplicative part in c(0, .6) is 0, so this has no effect *at all*. But if a custom `expand` argument is used, the multiplicative part is used, while the additive part is ignored.

I guess this can be useful for data like

```r
ggplot(mtcars, aes(factor(cyl), mpg)) + geom_jitter()
```

where `expand_range(c_range, expand[1], 0 , 1)` ensures that all the values are shown. But it would work just as well if it was replaced by just `c_range`. Note that in both cases parts of the data points may be hidden, e.g. for:

```r
ggplot(mtcars, aes(factor(cyl), mpg)) + geom_jitter(width=10)
```

I guess what you *really* want is to choose separate `expand` values for the discrete and continuous geoms. So that for instance the bar geom in a bar plot will have (by default) a .6 units space on either side while the point geom would have (by default) 5% extra space on either siude. But this is not currently possible, since 1) a combined scale is internally a discrete scale, and is only passed the `c(0, .6)` `expand` argument, not the `c(0.05, 0)` `expand` argument used for continuous scales, 2) it’s not possible for the user supply separate `expand_cont` and `expand_discrete` values.

However, if one wants to use a multiplicative constant for the continuous scale (but no additive constant) *and* an additive constant for the discrete part (but no multiplicative constant), one can use the (*undocumented*) workaround `scale_x_discrete(expand=c(.05, .6))`. And I guess that’s the idea behind the code(?).

**Comment by huftis** [comment]
I’ve now added a new pull request. The code has been simplified, and all the calculations now happen in a `expand_range4()` utility function. Most of the diff is just changes in the documentation. :)

**Comment by dzion** [comment]
Has this somehow been implemented yet? I generally agree with @huftis on the usefulness in bar plots, but also with @hadley on the inelegance of the solution provided here.... 
May I suggest to solve this analogous to the `limits()` solution, where `NA` can be specified as one of the parameters. This would provide perfect downward compatibility and is very easy to understand rather than adding 2 additional parameters to `expand()`
Providing `NA` would allow for R to use the default for one of the `expand()` parameters, while the other one could be specified. This would allow for automatic rescaling of one of the limits, while setting the other one to a fixed valued. 
Unfortunately I am pretty busy right now otherwise I would take a stab at this myself.

**Comment by huftis** [comment]
@dzion I haven’t have time to implement it yet, but will do so (though obviously not in time for the next ggplot2 release). It will probably have the syntax `expand = expand_scale(mult=c(0, .1), add=c(0,0))` or something similar (which could be easily extended if ggplot2 is ever updated to support three scales/axes, i.e. 3D plots).

**Comment by dzion** [comment]
@huftis Don't you feel that simply adding the `NA` option would provide a good enough workaround, without adding further options, that would generally solve the problem in many of the cases?
I agree, that specifying a multiplicative value for expand instead of an additive value is more straight forward and for my case usually what is needed, but sometimes simply providing an absolute value (seems to be the norm for ggplot2 in other instances) can also be nice - thus I like your solution a lot!
However if you are implementing your solution and find the time, I think implementing an `NA` option in `expand()` could benefit users as well, as it is easy to understand and in line with currently existing syntax.
Thanks for tackling this issue

**Comment by thomasp85** [comment]
I would suggest adding the parameters `expand_lower` and `expand_upper` to the scale constructor. If provided they take precedence over the value passed to `expand` and you can provide only one of them to only override one side. This will also ensure backward compatibility...

**Comment by hadley** [comment]
We already have a reasonable API (that I like) in the PR, so I don't think we need to discuss it further.

**Comment by thomasp85** [comment]
Ok - didn't know the API was settled. I'll show myself out then🙂

**Comment by Gnossos** [comment]
I think similar issues arise with area plots. They should sit on the horizontal axis and kiss the left and right borders. One can do this with the current expand(), but then the area plots bump their heads.

**Comment by dhimmel** [comment]
I'm also excited for the bar plot use case. For example, I'd love to expand every side besides the bottom in the plot below:

![barplot-expand](https://cloud.githubusercontent.com/assets/1117703/25680763/f94e1e34-301f-11e7-9976-dde364b1f4c3.png)

Thanks @huftis and @hadley for their work on https://github.com/tidyverse/ggplot2/pull/1805.

**Comment by zgzhao** [comment]
Add a blank geom_text layer to expand the upper limit of barchart. For example:

`ggplot(mtcars, aes(x=factor(cyl), y=mpg)) +
geom_bar(stat="identity", position="dodge") +
facet_wrap(~gear, scales="free_y") +
scale_y_continuous(expand = c(0, 0)) +
geom_text(aes(y=mpg * 1.1, label=""))`
