### ISSUE TITLE
clarify geom_pointrange handling of NAs in ymax / ymain

### ISSUE THREAD

**Issue by helmingstay** [tidyverse/ggplot2#1761]
For a given row / observation, when either or both of ymax & ymin are NA, the whole row is removed.  

This is (obviously) a minor issue that's easy to work around, e.g. with geom_point + geom_linerange.  The behavior was counter to my expectations - the text of na.rm refers to "missing values".  Here we have, in essence, tuples rather than single values, where "incomplete" tuples are removed. Not sure if this warrants a note in the docs, but I figured I'd point it out :)
[pointrange_ex.R.txt](https://github.com/hadley/ggplot2/files/481599/pointrange_ex.R.txt)

**Comment by hadley** [comment]
Can you please provide an inline minimal reprex?

**Comment by hadley** [comment]
I've closed this issue due to lack of requested reprex. If you still care about this bug, please open a new issue with a reprex.
