### ISSUE TITLE
Add the possibilty for show.legend to be a vector

### ISSUE THREAD

**Issue by Tutuchan** [tidyverse/ggplot2#1798]
In `geom_*` functions, the `show.legend` parameter can be either TRUE or FALSE and applies to the whole layer.

When TRUE (the default), lines appear in the legends for `factor(vs)` (`colour`) and `factor(am)` (`linetype`):

``` r
library(ggplot2)

ggplot(mtcars) +
  geom_point(aes(mpg, qsec, colour = factor(vs), shape = factor(am))) + 
  geom_line(aes(mpg, qsec, colour = factor(vs), linetype = factor(am)))
```

![image](https://cloud.githubusercontent.com/assets/5540005/18944932/52acf86c-8628-11e6-8b7a-c010900c31ba.png)

When FALSE, lines do not appear in the legend at all:

``` r
ggplot(mtcars) +
  geom_point(aes(mpg, qsec, colour = factor(vs), shape = factor(am))) + 
  geom_line(aes(mpg, qsec, colour = factor(vs), linetype = factor(am)), show.legend = FALSE)
```

![image](https://cloud.githubusercontent.com/assets/5540005/18944970/89ab8a40-8628-11e6-8f4f-736dc91bc764.png)

The idea would be to provide a named logical vector to `show.legend` in order to specify which aesthetic are shown in the legend for this layer, like so, where lines appear in the legend for `factor(am)` but not for `factor(vs)`:

``` r
ggplot(mtcars) +
    geom_point(aes(mpg, qsec, colour = factor(vs), shape = factor(am))) + 
    geom_line(aes(mpg, qsec, colour = factor(vs), linetype = factor(am)), 
              show.legend = c(colour = FALSE))
```

![image](https://cloud.githubusercontent.com/assets/5540005/18945081/08bf9aec-8629-11e6-9fe6-676fcbe1230e.png)

Please let me know if you think this could be a useful addition. I tried my hand at implementing this ([see here](https://github.com/Tutuchan/ggplot2/commit/c573efa42cab1fab3429b76599121bb633cf54b0)) and this works (except when using `color` instead of `colour`) but I'm sure there is a better way if you decide to implement it.

**Comment by hadley** [comment]
This seems like a good idea, but unfortunately it's not high enough on my priority list that I will implement it myself. However, I'd be happy to review a PR.
