### ISSUE TITLE
Consider using viridis for default continuous color scale

### ISSUE THREAD

**Issue by behrman** [tidyverse/ggplot2#1823]
[This page](https://cran.r-project.org/web/packages/viridis/vignettes/intro-to-viridis.html) has a comparison of viridis with the current default ggplot2 continuous color scale.

viridis does much better than the current default for many different forms of color blindness.

For those without color blindness, in my opinion, viridis is better than the current default for distinguishing levels and is more aesthetically pleasing.

I would consider making viridis the default continuous color scale, or at least making it an option within ggplot2.

**Comment by hadley** [comment]
Can do so using viridisLite.  Need to think about how to preserve backward compatible behaviour.

**Comment by hadley** [comment]
Moved in to #1526
