### ISSUE TITLE
Legends have lost spacing

### ISSUE THREAD

**Issue by hadley** [tidyverse/ggplot2#1871]
``` R
dat <- data.frame(x = LETTERS[1:3], y = 1)
p2 <- ggplot(dat, aes(x, y, fill = x, colour = 1:3)) +
  geom_bar(stat = "identity") +
  guides(color = "colorbar") +
  theme(legend.background = element_rect(colour = "black"))
p2 + theme(legend.position = c(.5, .5))
```

**Comment by hadley** [comment]
@thomasp85 do you remember what might've caused this? It's the spacing between the an individual legend and its border.

**Comment by thomasp85** [comment]
Due to our wish to put legends flush with the top of the plotting area we removed the default margins around each legend - you can get it back by setting `legend.margin` e.g.

```r
dat <- data.frame(x = LETTERS[1:3], y = 1)
p2 <- ggplot(dat, aes(x, y, fill = x, colour = 1:3)) +
  geom_bar(stat = "identity") +
  guides(color = "colorbar") +
  theme(legend.background = element_rect(colour = "black"), legend.margin = margin(1,1,1,1, 'cm'))
p2 + theme(legend.position = c(.5, .5))
```

**Comment by hadley** [comment]
But we decided against aligning them to the top, so I think we should change back to the default

**Comment by thomasp85** [comment]
My personal reason for keeping it was that it would avoid surprises when aligning to the top. It is easier to reason about margins when you can see them (e.g. When placed in plot area) vs when they are invisible (e.g. placed in gutter with same background colour.

Nothing I feel strongly about though

**Comment by hadley** [comment]
In general, I agree, but I think in this case it's better to stay backward compatible.
