### ISSUE TITLE
dup_axis() does not properly duplicate the axis name

### ISSUE THREAD

**Issue by clauswilke** [tidyverse/ggplot2#1877]
The following code should duplicate the x axis, including the name. However, that doesn't happen. The name is not duplicated.

```
p1 <- ggplot(mtcars, aes(mpg, disp)) + geom_line(colour = "blue")
p1 + scale_x_continuous(sec.axis = dup_axis())
```

Output:
![image](https://cloud.githubusercontent.com/assets/4210929/19746566/9a939cce-9b9c-11e6-8e7e-b5123641101a.png)

The problem seems to lie in the `derive()` function. The following also doesn't work:

```
p1 + scale_x_continuous(sec.axis = dup_axis(name = derive()))
```

(The output is exactly the same, so I'm not going to paste it again.)

**Comment by thomasp85** [comment]
This was an intended shortcoming of derive (it worked if you specified the scale name in the constructor e.g. `scale_x_continuous('mpg', sec.axis = dup_axis())`)

I've just made a PR that removes this restriction...

**Comment by clauswilke** [comment]
Yes, I can see that one could argue both ways. In many scenarios, maybe one wants the axis copied but not the axis name.

In either case, if you want the name to be missing by default, then I think having a default setting of `name = ''` in `dup_axis()` would be the cleaner implementation.
