### ISSUE TITLE
Rotated axis labels are not properly aligned

### ISSUE THREAD

**Issue by clauswilke** [tidyverse/ggplot2#1878]
In the following figure, the axis tick labels along the top x axis are not properly aligned. They all sit completely to the left of the axis tick rather than centered:

```
mtcars2 <- mtcars[1:15, ]
mtcars2$name <- row.names(mtcars2)
ggplot(mtcars2, aes(x = name, y = mpg, fill = name)) + 
  geom_bar(stat = 'identity', position = "identity") + 
  scale_y_reverse() +
  guides(fill = FALSE) +
  theme(axis.text.x = element_text(angle = 90, hjust=0)) +
  scale_x_discrete(position = "top")
```

![image](https://cloud.githubusercontent.com/assets/4210929/19747216/f87c57b0-9b9f-11e6-9ebb-9b906ffd5fc4.png)

No setting of `vjust` that I can add changes this, as far as I can tell. E.g., the following code creates the exact same output:

```
ggplot(mtcars2, aes(x = name, y = mpg, fill = name)) + 
  geom_bar(stat = 'identity', position = "identity") + 
  scale_y_reverse() +
  guides(fill = FALSE) +
  theme(axis.text.x = element_text(angle = 90, vjust=0.5, hjust=0)) +
  scale_x_discrete(position = "top")
```

As does any other `vjust` setting, including completely crazy ones such as -10 or 10.

**Comment by hadley** [comment]
Is this new in 2.2.0?

**Comment by clauswilke** [comment]
I think it's new to 2.2.0, because `vjust=0.5` works fine if I keep the x axis at the bottom of the plot (and different `vjust` settings move the text left and right in this case):

```
ggplot(mtcars2, aes(x = name, y = mpg, fill = name)) + 
     geom_bar(stat = 'identity', position = "identity") + 
     scale_y_reverse() +
     guides(fill = FALSE) +
     theme(axis.text.x = element_text(angle = 90, vjust=0.5, hjust=1))
```
![image](https://cloud.githubusercontent.com/assets/4210929/19748502/a937e932-9ba7-11e6-8e1c-e5ae1c067ccd.png)

```
ggplot(mtcars2, aes(x = name, y = mpg, fill = name)) + 
     geom_bar(stat = 'identity', position = "identity") + 
     scale_y_reverse() +
     guides(fill = FALSE) +
     theme(axis.text.x = element_text(angle = 90, vjust=0, hjust=1))
```

![image](https://cloud.githubusercontent.com/assets/4210929/19748512/d4b07642-9ba7-11e6-90b9-c69d84319bfa.png)

**Comment by hadley** [comment]
Thanks, makes sense. This one's for you @thomasp85

**Comment by thomasp85** [comment]
This is not a bug per se, but rather an inconvenience fostered by a wish for both theme inheritance and nice defaults...

`axis.text.x.top` inherits from `axis.text.x`, but in order to look good by default it sets margin and just explicitly deferent from `axis.text.x` and these are thus not inherited when `axis.text.x` is set in a call to `theme()`. Setting it directly (`theme(axis.text.x.top = element_text(vjust = 0.5))`) solves your problem...

**Comment by clauswilke** [comment]
Perfect, thanks. Is this explained somewhere in the documentation?

**Comment by apuhegde** [comment]
That works for labels on the top. However, I'm facing this exact issue when I have labels on the bottom x-axis. Is there a solution to that? 
Thanks!
