### ISSUE TITLE
incompatibility of theme_void with theme_update

### ISSUE THREAD

**Issue by zkamvar** [tidyverse/ggplot2#1880]
I noticed some odd behavior that may be a bug (or a feature). Using `theme_update()` to modify axis labels messes with `theme_void()`:

``` r
library('ggplot2')
theme_update(axis.text.x = element_text(angle = 90))
p <- ggplot(mtcars) + geom_point(aes(x = wt, y = mpg,
     colour = factor(gear))) + facet_wrap(~am)
p + theme_void()
## Error in unit(rep(yp, n), "npc") : 'x' and 'units' must have length > 0
```

**Comment by hadley** [comment]
(Please don't include session info unless it's explicitly asked for, or you've used `reprex::reprex(..., si = TRUE)` to hide it away. I've deleted it from your issue to avoid cluttering up the discussion)

**Comment by hadley** [comment]
I think that's due to the way that theme inheritance works. 

Fixing it seems like a good idea, but unfortunately it's not high enough on my priority list that I will implement it myself. However, I'd be happy to review a PR.
