### ISSUE TITLE
stack order & legend position

### ISSUE THREAD

**Issue by danwwilson** [tidyverse/ggplot2#1886]
With the new stack order in `2.1.0.9001` it matches the legend order when the legend is on the right of the chart. When the legend is positioned at the bottom of the chart the ordering of the legend and the stacks don't seem to complement any more. 

Example:
```r
p1 <- ggplot(diamonds)
p1 <- p1 + geom_col(aes(x = cut, y = price, fill = color))
p1 <- p1 + theme(legend.position="bottom")
p1
```
Would it be more practical to reverse either the stack order or the legend order when the legend is set to the top or bottom so that the legend reads left to right and the stack goes bottom to top?

**Comment by Eluvias** [comment]
Is this what you are after?
```{r}
p1 <- ggplot(diamonds)
p1 <- p1 + geom_col(aes(x = cut, y = price, colour = color, fill = color))
p1 <- p1 + theme(legend.position="bottom")
p1 + guides(col = guide_legend(ncol =8))
```

![gg](https://cloud.githubusercontent.com/assets/22600883/19952450/4bece492-a15d-11e6-8b42-ad25660763e8.png)

**Comment by danwwilson** [comment]
While it makes it neater in this example keeping the legend on a single line, it doesn't address my concern.

Based on the stacking of the chart (J at the bottom and D at the top) I would prefer to see the legend go from J (on the left) to D on the right. Or alternately if the legend stays ordered D to J, then change the stacking of the chart to have D on the bottom and J on top.

Hope that makes things clearer.

**Comment by Eluvias** [comment]
In that case,  you need to reverse the levels. 

```{r r}
diamonds %>% dplyr::mutate(color = forcats::fct_rev(color))-> diamonds 

p1 <- ggplot(diamonds)
p1 <- p1 + geom_col(aes(x = cut, y = price, colour = color, fill= color))
p1 <- p1 + theme(legend.position="bottom")

p1 + guides(col = guide_legend(ncol= 8))
```
![gg4](https://cloud.githubusercontent.com/assets/22600883/19953317/6fa4c876-a164-11e6-827c-c4c190813ad5.png)

**Comment by danwwilson** [comment]
by reordering you've change both the stacking and the legend. My concern is that the far left item in the legend should associate with the item at the bottom of the stack. The item on the far right of the legend should sit on top of the stack.

**Comment by Eluvias** [comment]
Just figured it out.

**Comment by Eluvias** [comment]
I had tried `guides(col = guide_legend(reverse = TRUE))`, didn't work.

**Comment by has2k1** [comment]
```R
guides(col = guide_legend(reverse = TRUE), fill = guide_legend(reverse = TRUE))
```

**Comment by danwwilson** [comment]
approach from @has2k1 addresses this concern
