### ISSUE TITLE
Margins don't affect strip.text

### ISSUE THREAD

**Issue by Eluvias** [tidyverse/ggplot2#1887]
ggplot version: `2.1.0.9001`
```{r }
p <- ggplot(mpg, aes(displ, cty)) + geom_point() + facet_grid(. ~ cyl)
p + theme(strip.text = element_text(margin = margin(l=5, b = -5)))
  ```
![gg1](https://cloud.githubusercontent.com/assets/22600883/19952652/e50a01ae-a15e-11e6-8195-739ad37d486d.png)

The `hjust`  hack still works:
```{r g1}
p + theme(strip.text = element_text(hjust=0.055))
```
![gg2](https://cloud.githubusercontent.com/assets/22600883/19952658/ec2703f6-a15e-11e6-90d8-b4bf3edbf165.png)
__ref:__ #1502

**Comment by hadley** [comment]
What's the problem here?

**Comment by Eluvias** [comment]
Is the `margin()`  parameter of `element_text()` working in `strip.text`?  How do we achieve  horizontal/vertical adjustment ?


```{r t}
# only hjust works
p + theme(strip.text = element_text(hjust=0.055, vjust = -1))

# doesn't work
p + theme(strip.text = element_text(margin = margin(l=5, b = -5))
```

**Comment by hadley** [comment]
What do you expect a negative margin to do? But I see that there is a problem. Here's a better reprex:

```R
ggplot(mpg, aes(displ, cty)) + 
  facet_wrap(~ cyl) + 
  theme(strip.text = element_text(margin = margin(b = 100)))
```

**Comment by Eluvias** [comment]
re negative margin : similar to this example. 

```{r 8}
ggplot(mpg, aes(displ, cty)) + 
  facet_wrap(~ cyl) + 
  theme(plot.title = element_text(margin = margin( b = -15)))+
  ggtitle("Title")
```

![gg5](https://cloud.githubusercontent.com/assets/22600883/19964815/d263fe26-a1bb-11e6-829c-9565b0a1bd15.png)

**Comment by hadley** [comment]
It's just a coincidence that that works. It should be an error.

**Comment by Eluvias** [comment]
If we want  to adjust the `strip.text` and get it closer to the bar columns, what is the preferred approach?
The old approch was via `vjust`.  

See this pic.:

![gg5](https://cloud.githubusercontent.com/assets/22600883/19964999/ccc85740-a1bc-11e6-8e6a-1a95cae46917.png)

**Comment by Eluvias** [comment]
I opened a  separate issue re `vjust` in ` strip.text.x` #1892 .

**Comment by EmanuelContreras** [comment]
Hi, I pull a request: A fix
https://github.com/tidyverse/ggplot2/pull/2025

**Comment by karawoo** [comment]
Margins actually do work in strip text if you specify `strip.text.x` or `strip.text.y`:

``` r
ggplot(mpg, aes(displ, cty)) + 
  facet_wrap(~ cyl) + 
  theme(strip.text.x = element_text(margin = margin(b = 100)))
```

![](http://i.imgur.com/0X0nfG7.png)

**Comment by karawoo** [comment]
This is more or less the same issue as in #2175: `strip.text.x` and `strip.text.y` inherit from `strip.text` in theory, but the default themes set the margins for `strip.text.x` and `strip.text.y` directly.
