### ISSUE TITLE
option to turn off warnings?

### ISSUE THREAD

**Issue by tdhock** [tidyverse/ggplot2#1888]
Dear ggplot2 developers, is there any option available to turn off warnings? For example

```r
> options(warn=-1)
> ggplot()+geom_point(aes(Sepal.Width, Petal.Length, showSelected=Species), chunk_vars=c("Species"), data=iris)
Warning: Ignoring unknown parameters: chunk_vars
Warning: Ignoring unknown aesthetics: showSelected
> 
```

I tried using the default R mechanism, from `help(options)` it says "If ‘warn’ is negative all warnings are ignored." but that did not work for me.

Even better, could you please introduce some way to ignore all ggplot2-specific warnings? like `options(ggplot2.warn=-1)`

**Comment by tdhock** [comment]
hey @hadley could you please consider adding support for the `ggplot2.warn` option?

**Comment by hadley** [comment]
I think options of this nature are a bad idea because they operate globally.
