### ISSUE TITLE
Title not cetered after x axis switch

### ISSUE THREAD

**Issue by garcialeo** [tidyverse/ggplot2#1891]
![rplot](https://cloud.githubusercontent.com/assets/23257338/20001668/93c03596-a27d-11e6-9937-0086e8910cee.png)
Hi, 
Maybe it's not a major bug...but I just discovered that when switching x axes to the top, the title is not centered...
```{r}
  ggplot(mpg, aes(displ, hwy)) + 
  geom_point() + 
  scale_x_continuous(position = "top") + 
  scale_y_continuous(position = "right") +
  labs(title = "Mpg centering")
```
and after trying other things, it seems that labs() doesn't center titles anymore, event without switching axes.
It's strange because in your examples it seems to work well !

Thanks if you have solution !

Leo

**Comment by garcialeo** [comment]
...and after trying other things, it seems that labs() doesn't center titles anymore, event without switching axes...

**Comment by Eluvias** [comment]
That will be the default in v2.2.0 - see [NEWS](https://github.com/tidyverse/ggplot2/blob/master/NEWS.md)
