### ISSUE TITLE
Documentation of geom_boxplot: How does the weight aesthetic work?

### ISSUE THREAD

**Issue by luke-a** [tidyverse/ggplot2#1893]
I did not find anything on how the `weight` aesthetic in `geom_boxplot` / `stat_boxplot` is working. Is it missing? Or did I look at the wrong place? 

```
library(ggplot2)
library(gridExtra)
grid.arrange(
  p1 <- ggplot(mpg, aes(class, hwy)) + geom_boxplot(),
  p2 <- ggplot(mpg, aes(class, hwy)) + geom_boxplot(aes(weight=displ))
)
cbind(ggplot_build(p1)$data[[1]][,"middle"], ggplot_build(p2)$data[[1]][,"middle"])
```

**Comment by hadley** [comment]
It weights the computation of the quantiles.

**Comment by luke-a** [comment]
Thanks

**Comment by JackWzh** [comment]
@hadley I read several plot codes with the weight aesthetic, but I still couldn't figure out how this aesthetic works exactly.  So could you explain it more specifically or point where the weight aesthetic's source code lies? Thx : )
