### ISSUE TITLE
error during installation  on a fresh new install

### ISSUE THREAD

**Issue by VincentGuyader** [tidyverse/ggplot2#1898]
On a totaly new fresh R installation 

                   
platform       x86_64-w64-mingw32          
arch           x86_64                      
os             mingw32                     
system         x86_64, mingw32             
status                                     
major          3                           
minor          3.2                         
year           2016                        
month          10                          
day            31                          
svn rev        71607                       
language       R                           
version.string R version 3.3.2 (2016-10-31)
nickname       Sincere Pumpkin Patch 

```
list.files(.libPaths()[1]) # character(0)

if(!require(devtools)){install.packages("devtools")}

devtools::install_github("tidyverse/ggplot2")
```

`

it return an error
```

             * installing *source* package 'ggplot2' ...
             ** R
             ** data
             *** moving datasets to lazyload DB
             ** inst
             ** tests
             ** preparing package for lazy loading
             Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
             namespace 'scales' 0.4.0 is being loaded, but >= 0.4.1 is required
             ERROR: lazy loading failed for package 'ggplot2'
             * removing 'C:/Users/ib/Documents/R/win-library/3.3/ggplot2'
             Error: Command failed (1)
             > 
```

Regards

**Comment by hadley** [comment]
You're just in an awkward time during the CRAN release process. Please try again in a day or two

**Comment by Abuamany** [comment]
we have same problem, 

Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  namespace ‘scales’ 0.4.0 is being loaded, but >= 0.4.1 is required
ERROR: lazy loading failed for package ‘ggplot2’
* removing ‘/Library/Frameworks/R.framework/Versions/3.2/Resources/library/ggplot2’
Warning in install.packages :
  installation of package ‘ggplot2’ had non-zero exit status

The downloaded source packages are in
	‘/private/var/folders/vw/w79x893j5lb2yjcq_51vpfbr0000gn/T/RtmpWSmgPU/downloaded_packages’

**Comment by hadley** [comment]
@Abuamany `install.packages("scales")`

**Comment by Abuamany** [comment]
We have been install "scales" packages and the same result.

**Comment by Abuamany** [comment]
![screen shot 2017-01-28 at 8 22 25 am](https://cloud.githubusercontent.com/assets/16170999/22393091/ea4883c0-e533-11e6-8903-7ade50ee5a3a.png)

**Comment by MehnazAsh** [comment]
Hi,
Even I have the problem with "scales".How do we ensure that right version is installed?Help is appreciated.

**Comment by irudnyts** [comment]
Try to install `scales` directly from github: firstly install devtools (if not yet) and than call:
`devtools::install_github("hadley/scales")`
It helped me in my case. I also couldn't install `scales` 0.4.1 from CRAN (only 0.4.0).

**Comment by hadley** [comment]
@irudnyts there is no need to install it with devtools. You are probably using a bad CRAN mirror, as it's definitely on CRAN: https://cran.r-project.org/web/packages/scales/index.html

**Comment by irudnyts** [comment]
@hadley yes, very likely. Because after the installation by `install.packages()` I checked the version in `installed.packages()`, and it was still 0.4.0.

**Comment by irudnyts** [comment]
@hadley yes, very likely. Because after the installation by `install.packages()` I checked the version in `installed.packages()`, and it was still 0.4.0.

**Comment by MehnazAsh** [comment]
Thanks everyone for your help.I tried using different mirrors but no luck. As the error says that  ggplot2 requires scales 0.4.1 version ,I explicitly installed that package from [https://cran.r-project.org/web/packages/scales/index.html].It did the trick.
Thanks once again.
