### ISSUE TITLE
Need theme setting for right/top ticks

### ISSUE THREAD

**Issue by hadley** [tidyverse/ggplot2#1899]
So you can do (e.g.)

```
ggplot(mpg, aes(displ, hwy)) +
  geom_point() +
  geom_hline(yintercept = 235 / l_breaks, colour = "pink") +
  scale_y_continuous(
    "mpg",
    sec.axis = sec_axis(~ 235 / ., name = "l / 100 km", breaks = l_breaks)
  ) +
  theme(
    axis.text.y.right = element_text(colour = "pink"), 
    axis.ticks.y.right = element_line(colour = "pink")
  )
```

**Comment by thomasp85** [comment]
Yeah, I ran into something similar a couple of days ago (not pink though😊)

**Comment by joe-bh** [comment]
I also ran into a situation where the right/top axis and ticks need some customization.
Looking forward to see this feature in ggplot2 :+1:

**Comment by duttashi** [comment]
@hadley I am not able to reproduce the above code. I get the following error,  `Error in data.frame(yintercept = yintercept) :  object 'l_breaks' not found`
is there something I'm missing with? My environment variables are `> version
platform       x86_64-w64-mingw32          
arch           x86_64                      
os             mingw32                     
system         x86_64, mingw32             
status                                     
major          3                           
minor          3.1                         
year           2016                        
month          06                          
day            21                          
svn rev        70800                       
language       R                           
version.string R version 3.3.1 (2016-06-21)
nickname       Bug in Your Hair`
