### ISSUE TITLE
Ordering within facets

### ISSUE THREAD

**Issue by drsimonj** [tidyverse/ggplot2#1902]
[This post](https://drsimonj.svbtle.com/ordering-categories-within-ggplot2-facets) discusses a method for differently ordering categories that appear in multiple facets with different values on a continuous variable. As far as I'm aware, there isn't a simple method for achieving this, and @dgrtwo suggested it could be useful for others to have a neat wrapper function or new stat option to handle it.

Here's a small reproducible example to explain the problem:

``` r
library(ggplot2)
library(dplyr)

d <- data.frame(
  f = rep(c("f1", "f2"), each = 3),
  x = rep(c("a", "b", "c"), 2),
  y = c(1, 2, 3, 3, 2, 1)
)

# No easy way to order categories within facets
ggplot(d, aes(x, y)) +
  geom_col() +
  facet_wrap(~ f)
```

![unnamed-chunk-1-1](https://cloud.githubusercontent.com/assets/11235783/20249159/91f185a4-aa47-11e6-9b94-9085cf1082a2.png)

``` r
# This will handle the ordering
d <- d %>% 
  ungroup() %>%   # As a precaution / handle in a separate .grouped_df method
  arrange(f, y) %>%   # arrange by facet variables and continuous values
  mutate(.r = row_number()) # Add a row number variable

ggplot(d, aes(.r, y)) +  # Use .r instead of x
  geom_col() +
  facet_wrap(~ f, scales = "free") +  # Should free scales (though could be left to user)
  scale_x_continuous(  # This handles replacement of .r for x
    breaks = d$.r,     # notice need to reuse data frame
    labels = d$x
  )
```

![unnamed-chunk-1-2](https://cloud.githubusercontent.com/assets/11235783/20249161/9b346884-aa47-11e6-89ce-8b89e507697e.png)

Although this example handles bars, it seems generally applicable to other geoms (e.g., points). Some options for making this readily accessible for users:

- Include a wrapper function for the data ordering, and leave the plotting up to them.
- Add an option in the `facet` functions.
- Add something like an `order_by` argument to `scale_x/y_discrete`

I've created [new fork](https://github.com/drsimonj/ggplot2) to see what works.

**Comment by has2k1** [comment]
@drsimonj, I am surprised that your solution works. The scales do not know about the partitioning of the data done by the facets. So it is by happenstance that when you pass full size vectors as `breaks` and `labels` that they align with the parts created by the facets.

**Comment by drsimonj** [comment]
@has2k1 I could be wrong (you'll have a better understanding), but this unusual happenstance was behind my thinking! By combing `arrange` by facet variable and then adding `row_number`, we can be certain that a unique range of integers will correspond to each facet group. Therefore, the full vectors match perfectly.

For example, take a look at the example I give in [this post](https://drsimonj.svbtle.com/ordering-categories-within-ggplot2-facets) where the scales are not set to "free". The x-axis is defined by the full `row_number` vector. The data for each facet, however, is contained within a unique range (i.e., no overlap). We're then replacing this full integer vector for the full category label vector. `scales = "free"` hides this from us.

For completeness sake, here's the above example **without** `scales = "free"` without and then with the full integer vector being replaced with the labels:

```r
# Before label replacement
ggplot(d, aes(.r, y)) +
  geom_col() +
  facet_wrap(~ f)  # NO freeing of scales
```

![unnamed-chunk-1-3](https://cloud.githubusercontent.com/assets/11235783/20249876/f9a4876e-aa56-11e6-9f46-cb634ca47f94.png)

```r
# After label replacement
ggplot(d, aes(.r, y)) +
  geom_col() +
  facet_wrap(~ f) +  # NO freeing of scales
  scale_x_continuous(
    breaks = d$.r,
    labels = d$x
  )
```

![unnamed-chunk-1-3](https://cloud.githubusercontent.com/assets/11235783/20249865/c85f3f28-aa56-11e6-932e-ba6f32397ef3.png)

**Comment by has2k1** [comment]
Indeed it does work, I was just not sure how stable of a solution it is. [Here]( 
https://github.com/tidyverse/ggplot2/blob/f442f321094a73a24224ef349d28f59f4e8ef7b4/R/scale-.r#L251-L258) the part in the code that hints at what may be edge cases. That is, the solution is relying on the alignment of `NA`s created at that instance because of facetting yet `NA`s may come from missing values or bad statistical computations.

That said, I think it should be fine if one is not looking for pathological ways to trip it up.

**Comment by drsimonj** [comment]
Ah, I see what you mean. Thanks for the link! Perhaps there will be a way to handle it.

I'd prefer to find a more robust and generalizable solution if possible.

**Comment by hadley** [comment]
This is absolutely an edge case and I would be extremely nervous about relying on it in the long term.

**Comment by drsimonj** [comment]
Maybe there isn't a straightforward and reliable solution in that case. I'll play around with it and use my little hack for specific cases in the meantime.

**Comment by has2k1** [comment]
@drsimonj, I think your goal of facets with x-axis categorical values placed so as to show ascending/descending bar heights is common enough to warrant a general solution. I think the solution will be one of:

1. A function passed to the scale that does the reordering
2. An option to the facet to do the reordering
3. A new hook into the system that could be used for the reordering

Given the current state of the internals, I think options 1 and 2 would fall short. You would probably encounter labelling glitches. The third is the more general purpose and the most vague, as in, it is not apparent where the hook should be and how cleanly it can be implemented.

To get a sense of where the pain points lay and also get some insight on how to proceed, l would suggest:

- Create a new `geom` that inherits from that which you wish to use(in this case `geom_col`) and implement the `setup_data` method. In the method, you simply do the reordering.
- Or, create a new `facet` that inherits from `facet_wrap` implement the `setup_data` method in which
you reorder the values.

Both of these while likely to be insufficient, should at the very least reveal what would make a proper solution difficult. My guess is that it may require refactoring some aspect of the scales.

**Comment by drsimonj** [comment]
Thanks @has2k1  for such great advice! I've made a start on the `geom` option. Will post updates with anything of value/potential.

**Comment by drsimonj** [comment]
UPDATE that far more experienced ggplot2 contributors might be able to advise on.

I've started by attempting to order data **within a single panel** (not facetting just yet). Here's what I've tried:

**Tried and failed**

1. _New Geom_. I found it relatively easy to create a new Geom that would order data (in `setup_data`), but not axis labels.
2. _New Coord_. In an attempt to solve (1), I created a new Coord that would order the axis labels, but not the data (or at least not in a reasonable way).

So the challenge I've encountered is to influence geom AND coord.

**One Approach**

After some playing (as a ggplot2 source-code novice), I realized that we could pass a new aesthetic, `order`, than can manipulate data in `layer()`, which is then propagated to geoms and coords. One obvious problem is that this involves a new/undefined aesthetic that isn't used in the way aesthtics typically are. Nonetheless, by matching an `order` aesthtic with Geom-specific ordering methods in `layer()`, you can do things like the following:

```r
    # No ordering
    ggplot(mpg, aes(manufacturer, hwy)) + geom_col()
```

![fig-unnamed-chunk-2-1](https://cloud.githubusercontent.com/assets/11235783/20372645/f0e6ca30-acc0-11e6-86b7-5659080221df.png)


```r
    # Ordering by same variable as y-axis
    ggplot(mpg, aes(manufacturer, hwy, order = hwy)) + geom_col()
```

![fig-unnamed-chunk-2-2](https://cloud.githubusercontent.com/assets/11235783/20372652/f4b882ca-acc0-11e6-929b-8289fd3da378.png)


```r
    # Ordering reversed
    ggplot(mpg, aes(manufacturer, hwy, order = -hwy)) + geom_col()
```

![fig-unnamed-chunk-2-3](https://cloud.githubusercontent.com/assets/11235783/20372653/f869d932-acc0-11e6-8f7e-036f8ab1a22a.png)


```r
    # With points
    ggplot(mpg, aes(manufacturer, hwy, order = hwy)) + geom_point()
```

![fig-unnamed-chunk-2-4](https://cloud.githubusercontent.com/assets/11235783/20372654/fba96612-acc0-11e6-8e7c-f2a1210feea8.png)


```r
    # Ordered by a different continuous variable and axis
    ggplot(mpg, aes(hwy, manufacturer, order = displ, color = displ)) + geom_point()
```

![fig-unnamed-chunk-2-5](https://cloud.githubusercontent.com/assets/11235783/20372657/ff1a825e-acc0-11e6-9ec2-c232ff3e0647.png)

Code for achieving this exists on the current [`feature/ordering` branch of my fork](https://github.com/drsimonj/ggplot2/tree/feature/ordering).

Any thoughts/advice is very welcome!

**Comment by has2k1** [comment]
@drsimonj, You bring back memories. There used to be an `order` aesthetic that didn't work well and it met a [death-by-refactor](https://github.com/tidyverse/ggplot2/commit/f809b7b1f47325e713272cfe03b306d2dc56bd8c#diff-b6a51c1de2e5c72523422829ed3adaa6).

**Comment by hadley** [comment]
But `order` never affected the scales

**Comment by drsimonj** [comment]
Thanks, @has2k1. I'm showing my (lack of) experience with that! Still, I can see that the previous `order_groups` just executed `data[order(data$order), ]`, which will order the rows but not the plot. What I've done converts non-numeric x or y to a factor with ordered levels (therefore being taken into account by scales, as @hadley pointed out). Do you think this is a direction worth pursuing?

**Comment by has2k1** [comment]
Yes it is worth pursuing. I think you should create a PR out of what you have so far that we can have an easy place to discuss the implementation. I have a suggestion on that front.

**Comment by hadley** [comment]
This seems like a good approach: https://github.com/dgrtwo/drlib/blob/master/R/reorder_within.R

**Comment by afflorezr** [comment]
Nice !! work to me.

**Comment by wmayner** [comment]
Thanks for the tip, @hadley, and the code, @dgrtwo.

Any chance this could be added to `ggplot2` proper? It's a problem I frequently run into.
