### ISSUE TITLE
Regression with width aesthetic in documentation

### ISSUE THREAD

**Issue by gfiumara** [tidyverse/ggplot2#1904]
A warning is omitted when using the `width` aesthetic, but still seems to produce identical plots.

Example from ggplot2 documentation for `geom_tile`:
[2.1 Documentation](http://docs.ggplot2.org/current/geom_tile.html), [Dev Documentation](http://docs.ggplot2.org/dev/geom_tile.html)

```
library(ggplot2)
df <- data.frame(
  x = rep(c(2, 5, 7, 9, 12), 2),
  y = rep(c(1, 2), each = 5),
  z = factor(rep(1:5, each = 2)),
  w = rep(diff(c(0, 4, 6, 8, 10, 14)), 2)
)
ggplot(df, aes(x, y)) +
  geom_tile(aes(fill = z, width = w), colour = "grey50")
```

ggplot2 2.2:
> Warning: Ignoring unknown aesthetics: width

ggplot2 2.1:
> *No output*

**Comment by hadley** [comment]
And

```R
library(tidyverse)

df <- tibble(
  x = c("F1","F2","Overall"),
  y = c(0.4,0.5,0.42), 
  w = c(1,1,2) * 0.5
)

ggplot(df, aes(x, y)) + 
  geom_col(aes(width=w))
```

**Comment by hadley** [comment]
This is trickier than I thought. I think the key is that `width` and `height` are alternative parameterisations for these geoms — they're not necessary, but the `setup_data()` method will use them if available. It seems like adding a new `alternative_aes` should fix this, but when I plumb it up, setting the width as an aesthetic no longer works.

When I come back to this, I have work in local "alternative-aes" branch

**Comment by has2k1** [comment]
Isn't that what the "slightly hacky" `extra_params` is for? It is not properly checked against for the case of aesthetic mappings.

```sh
grep -r extra_params
```

**Comment by hadley** [comment]
@has2k1 that's subtly different, I think, and I suspect wiring it up with parameters will have the same problems.

**Comment by yutannihilation** [comment]
This issue seems fixed already. Can we close this?

``` r
library(ggplot2)
df <- data.frame(
  x = rep(c(2, 5, 7, 9, 12), 2),
  y = rep(c(1, 2), each = 5),
  z = factor(rep(1:5, each = 2)),
  w = rep(diff(c(0, 4, 6, 8, 10, 14)), 2)
)
ggplot(df, aes(x, y)) +
  geom_tile(aes(fill = z, width = w), colour = "grey50")
```

![](https://i.imgur.com/Ahrykzk.png)

<sup>Created on 2019-02-14 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by yutannihilation** [comment]
Fixed by this commit: https://github.com/tidyverse/ggplot2/commit/a11f786d2728785c945f923beb40131dfff53e3d
