### ISSUE TITLE
2.2.0 breaks xmin aesthetic

### ISSUE THREAD

**Issue by TomWien** [tidyverse/ggplot2#1905]
2.2.0 appears to not like the xmin aesthetic.  The following code works fine in 2.1.0 but fails in 2.2.0:

`
library("ggplot2")

t=data.frame(Name=c("Tom","Dick","Harry"), Start=c(4,5,6), End=c(7,8,9)   )

ggplot(t, aes(y=factor(Name), colour=Name)) +

geom_segment( aes(x=Start, xend=End, y=Name, yend=Name, xmin = 1 ), size=5, lineend="round" )
 `

The error message is: 
`Warning: Ignoring unknown aesthetics: xmin`

The resulting plot ignores the xmin specification.

Thanks so much for such a wonderful graphics library.

Tom

**Comment by hadley** [comment]
`geom_segment` doesn't use `xmin`?
