### ISSUE TITLE
facet_grid 'switch' move the strip in between axis line and axis text

### ISSUE THREAD

**Issue by zz77zz** [tidyverse/ggplot2#1906]
Hi, 
it seems the switch does not work as nicely in the latest version of ggplot2 (2.2.0) as in the previous ones (2.1.x). I get the strip in between axis line and axis text (see the example below).
```
library(ggplot2)
ggplot(iris, aes(x = Sepal.Length, y = Sepal.Width)) +
  facet_grid(Species ~ ., switch = "y") +
  geom_point()
```
![rplot](https://cloud.githubusercontent.com/assets/19784084/20277672/df19c670-aaa1-11e6-815c-12a62cb70925.png)

**Comment by baptiste** [comment]
`theme(strip.placement = "outside")`

**Comment by zz77zz** [comment]
OK, thanks. And sorry, that was not an issue!

**Comment by colinbrislawn** [comment]
I found this after googling "facet_grid labels switch outside."

Thank you @baptiste! This is why I love the tidyverse. 💯
