### ISSUE TITLE
Using `fortify` with `SpatialPolygonsDataFrame`

### ISSUE THREAD

**Issue by samuel-rosa** [tidyverse/ggplot2#1908]
I am using `fortify` with a `SpatialPolygonsDataFrame` so that I can plot the polygons on top of a gridded image. However, when I call `fortify`, I always get the following error:

    Error in get("rgeos", envir = .MAPTOOLS_CACHE) : object 'rgeos' not found

The error is gone if I load the `maptools`-package. I wonder why this is happening.

**Comment by hadley** [comment]
It's probably from some downstream package that ggplot2 uses.
