### ISSUE TITLE
Warning when unsetting an aesthetic that's not used by a geom

### ISSUE THREAD

**Issue by wch** [tidyverse/ggplot2#1909]
If you add a geom that uses a different data set, and it does *not* use an aesthetic set in the `ggplot()` call,

In the example below, I'm adding a `geom_linerange()` which uses a different data set from the one specified in the `ggplot()` call. The linerange doesn't have a `y` aesthetic. Its data set, `d2`, also doesn't have the `yval` column which was used in the aesthetic mapping for `y` at the top level.

If I map `aes(y=NULL)` in the `geom_linerange`, it gives a warning that it's ignoring `y`. If I don't map `y`, then it errors because it still tries to evaluate the `y=yval` mapping even though it's not used for that geom.

```R
library(ggplot2)

d <- data.frame(
  xval = 1:2,
  yval = 1:2
)

d2 <- data.frame(
  xval = 3:4,
  yval2 = 3:4
)

p <- ggplot(d, aes(x=xval, y=yval)) +
  geom_point()

p + geom_linerange(aes(y = NULL, ymin = yval2, ymax = yval2+1), data = d2)
#> Warning: Ignoring unknown aesthetics: y

p + geom_linerange(aes(ymin = yval2, ymax = yval2+1), data = d2)
#> Error in eval(expr, envir, enclos) : object 'yval' not found
```

**Comment by hadley** [comment]
Hmmm, maybe it should not warn for aesthetics set to `NULL`?

**Comment by wch** [comment]
Is it possible to have it not try to evaluate the unused aesthetic? I think that would be preferable.

**Comment by hadley** [comment]
I don't see how that work work and still preserve the intent of flagging problems like `aes(colur = blah)`

**Comment by andbarker** [comment]
+1 for not warning when the aes is null.
Mainly because it forces you to explicitly stated when there's a dummy aes.

**Comment by hadley** [comment]
@wch maybe I misunderstood your question - there's no need to evaluate the aesthetics because `identical(quote(NULL), NULL)` is TRUE.
