### ISSUE TITLE
switch in facet_grid violates axis labels

### ISSUE THREAD

**Issue by modche** [tidyverse/ggplot2#1911]
When I use switch="x" the facet labels are placed on the left hand side of the graph but between the axis labels and the graph. This isnt done on purpose, is it?
![screen shot 2016-11-16 at 13 50 10](https://cloud.githubusercontent.com/assets/13642619/20348027/eaf05c4e-ac03-11e6-948c-b4439b14e6f8.png)

**Comment by tsilver83** [comment]
I'm having the same issue.  Even if I use the example at http://docs.ggplot2.org/current/facet_grid.html:

data <- transform(mtcars,
                  am = factor(am, levels = 0:1, c("Automatic", "Manual")),
                  gear = factor(gear, levels = 3:5, labels = c("Three", "Four", "Five"))
)
p <- ggplot(data, aes(mpg, disp)) + geom_point()
p + facet_grid(am ~ gear, switch = "both")

I get 
![image](https://cloud.githubusercontent.com/assets/7350152/20396340/178c8c1a-aca3-11e6-8d58-4d8abf1d013f.png)

**Comment by modche** [comment]
Yes, I tested some other cases, all the same, for me it is looking like a bug. I downgrade to ggplot 2.1 for now...

**Comment by thomasp85** [comment]
As per the news file and docs the placement of the strip is now controlled with the `strip.placement` theme argument e.g. `theme(strip.placement = 'outside')`

**Comment by modche** [comment]
Ok, thanks, please consider to use `'outside'` as standard (as before).
