### ISSUE TITLE
Faceting causes error using ggplot2 2.2.0 : 

### ISSUE THREAD

**Issue by Myles12345** [tidyverse/ggplot2#1914]
When trying to facet_wrap, I am receiving the following error:
Error: 'as_tibble' is not an exported object from 'namespace:tibble'

Code below:

> library("ggplot2")
> 
> ggplot(diamonds, aes(carat, price)) + 
> geom_hex(bins = 20) + 
> facet_wrap(~cut_number(depth, 6))
> Error: 'as_tibble' is not an exported object from 'namespace:tibble'

**Comment by hadley** [comment]
You'll need to upgrade the tibble package.
