### ISSUE TITLE
The titles are off center in all my plots now

### ISSUE THREAD

**Issue by crj32** [tidyverse/ggplot2#1918]
Hi this simple code (and all my scripts from this morning) has started giving me a off center title in ggplot2

Ubuntu version: 16.04 R studio version: Version 0.99.896 R version: 3.3.2 GGPLOT2 version: 2.2.0

I have freshly installed the above this morning to try and fix this....

dat <- data.frame(
time = factor(c("Lunch","Dinner"), levels=c("Lunch","Dinner")),
total_bill = c(14.89, 17.23)
)

# Add title, narrower bars, fill color, and change axis labels
ggplot(data=dat, aes(x=time, y=total_bill, fill=time)) + 
  geom_bar(colour="black", fill="#DD8888", width=.8, stat="identity") + 
  guides(fill=FALSE) +
  xlab("Time of day") + ylab("Total bill") +
  ggtitle("Average bill for 2 people")

![bugplot](https://cloud.githubusercontent.com/assets/4405372/20428431/fccc78f2-ad80-11e6-97b2-70c7bec17947.png)

**Comment by crj32** [comment]
If you can reply to me on chris.r.john86@gmail.com

**Comment by thomasp85** [comment]
This is a documented change in v2.2.

**Comment by 0LEI0** [comment]
I also meet the same problem, and don't konw what to do! Have you solved the problem?

**Comment by 0LEI0** [comment]
use ... + theme(plot.title = element_text(hjust = 0.5))
this is a method that work

**Comment by cderv** [comment]
@0LEI0 it is not a problem. It is on purpose in the last version v2.2 of ggplot2 as it was said. 
Have a look at the documentation [on the new website](http://ggplot2.tidyverse.org/articles/releases/ggplot2-2.2.0.html) for more info and other changes. 
The method you found is the good and documented one : 

> The plot title is now aligned to the left by default. To return to the previous centered alignment, use theme(plot.title = element_text(hjust = 0.5)).

**Comment by 0LEI0** [comment]
@cderv  thank you very much! ggplot2 is a very powerful plot machine!
