### ISSUE TITLE
does not work when column name has space

### ISSUE THREAD

**Issue by liuyadong** [tidyverse/ggplot2#1919]
A minimal example here,
```r
data <- tibble(x = 1:5, 'y space' = 1:5)
data %>% ggplot(aes(x, 'y space')) + geom_point()
```
the output is
![rplot](https://cloud.githubusercontent.com/assets/7848019/20453411/308db746-ae67-11e6-804d-09be92cdefaa.png)

**Comment by hadley** [comment]
You need to use backticks not single quotes

**Comment by liuyadong** [comment]
Aha, Thank you hadley! @hadley
