### ISSUE TITLE
Working with geom_polygon and distribution charts

### ISSUE THREAD

**Issue by johnmutuma5** [tidyverse/ggplot2#1926]
@hadley, while creating choropleth maps and using geom_polygon to visualize spatial data, I have been looking for a way to use ggplot2 to draw a bar/pie chart at the centroids of each/selected polygons with `stat = "identity"`

```
library(dplyr)
library(ggplot2)
df <- data.frame(Region.ID = LETTERS[1:5],
                 Population.mill = sample(15:21, 5),
                 Male = sample(8:12, 5))
df <- df %>%
  mutate(Female = Population.mill - Male)
head(df)
```

For instance, in this data df, how would you add a pie/bar to show Male against Female for each/selected observation(s)? I know that I could play around with the base function `plot()` and a few other `packages` but my goal is to harness on the power and flexibility of ggplot2 to achieve the same.

**Comment by hadley** [comment]
I'm not planning to add better pie chart support to ggplot2, so pursuing in a separate package (as you are doing) is the way to go.
