### ISSUE TITLE
facet_grid(a ~ a) produces an error

### ISSUE THREAD

**Issue by vnijs** [tidyverse/ggplot2#1928]
FYI The example from #1153 now produces the error below and does not create a plot

```r
ggplot(data.frame(a = letters[1:3], y = rnorm(3))) + geom_point(aes(y, y)) + facet_grid(a~a)

> Error in scale_apply(layer_data, x_vars, "train", SCALE_X, x_scales) : 
```

**Comment by hadley** [comment]
@thomasp85 can you please take a look?  I don't think we need to make this work, but it should give a more informative error message.
