### ISSUE TITLE
Angled Axis labels Can Extend Beyond Plot But Perpendicular Labels Never Do

### ISSUE THREAD

**Issue by DarioS** [tidyverse/ggplot2#1930]
The example below shows that long axis labels which are on a slope may be partly outside of the plotting areas. But, no matter how long the perpendicular axis labels are made to be (e.g. try `rpois(10, 1000000000)` instead), the plot adjusts to ensure they are always completely visible. Could this work for both kinds of angles by default? The example should be viewed in an approximately square plotting window.

    library(ggplot2)
    aDataset <- data.frame(ID = paste("AsurprisinglyLongIdentifier", 1:10, sep = ''),
                           score = rpois(10, 100))
    ggplot(aDataset, aes(x = ID, y = score)) + labs(x = NULL, y = NULL) + geom_point() +
           theme(axis.text.x = element_text(angle = 45, hjust = 1))

**Comment by hadley** [comment]
Unfortunately it's unlikely that I will ever have to work on this
This seems like a good idea, but unfortunately it's not high enough on my priority list that I will implement it myself. However, I'd be happy to review a PR.
