### ISSUE TITLE
gam in geom_smooth doesn't use s() when manually specified:

### ISSUE THREAD

**Issue by Ax3man** [tidyverse/ggplot2#1931]
Consider:

    ggplot(diamonds, aes(price, carat)) + geom_smooth()

    ##`geom_smooth()` using method = 'gam'

![rplot](https://cloud.githubusercontent.com/assets/15309336/20689775/4476be26-b5c7-11e6-9194-5742d664d0f9.png)

But with manual specification of the method:

    ggplot(diamonds, aes(price, carat)) + geom_smooth(method = "gam")

![rplot04](https://cloud.githubusercontent.com/assets/15309336/20689786/5887be74-b5c7-11e6-860e-432bc5ed5eb4.png)

Something seems to off with the default formula, since

    ggplot(diamonds, aes(price, carat)) + geom_smooth(method = "gam", formula = y ~ s(x, bs = "cs"))

produces same as the first plot. Is this intentional? For what it is worth, this behavior was already there in v1.0.0.

**Comment by hadley** [comment]
Will be fixed by #1951

**Comment by tjmahr** [comment]
This particular issue still happens.

```r
library(ggplot2)

iris2 <- iris[sample(seq_len(nrow(iris)), 1000, replace = TRUE), ]

ggplot(iris2) + 
  aes(x = Sepal.Length, y = Sepal.Width) + 
  stat_smooth() + 
  ggtitle("stat_smooth()")

# gam
ggplot(iris2) + 
  aes(x = Sepal.Length, y = Sepal.Width) + 
  stat_smooth(method = "gam") + 
  ggtitle("stat_smooth(method = \"gam\")")

# gam with formula
ggplot(iris2) + 
  aes(x = Sepal.Length, y = Sepal.Width) + 
  stat_smooth(method = "gam", formula = y ~ s(x, bs = "cs"))+ 
  ggtitle("stat_smooth(method = \"gam\", formula = y ~ s(x, bs = \"cs\")")
```


![image](https://user-images.githubusercontent.com/1890315/40849841-9a48311e-6588-11e8-91a9-438866363b28.png)

![image](https://user-images.githubusercontent.com/1890315/40849827-926c4ca0-6588-11e8-8944-a763a803afce.png)

![image](https://user-images.githubusercontent.com/1890315/40849809-881d959c-6588-11e8-883b-7975a06bf7e0.png)


```
 package     * version    date       source                            
 ggplot2     * 2.2.1.9000 2018-05-29 Github (tidyverse/ggplot2@4299917)
```

**Comment by batpigandme** [comment]
Isn't it applying the same formula?
``` r
library(ggplot2)

iris2 <- iris[sample(seq_len(nrow(iris)), 1000, replace = TRUE), ]

ggplot(iris2) + 
  aes(x = Sepal.Length, y = Sepal.Width) + 
  stat_smooth() + 
  ggtitle("stat_smooth()")
#> `geom_smooth()` using method = 'gam' and formula 'y ~ s(x, bs = "cs")'
```

![](https://i.imgur.com/jpA8LO0.png)

``` r

# gam
ggplot(iris2) + 
  aes(x = Sepal.Length, y = Sepal.Width) + 
  stat_smooth(method = "gam") + 
  ggtitle("stat_smooth(method = \"gam\")")
```

![](https://i.imgur.com/PGrVzCz.png)

``` r

# gam with formula
ggplot(iris2) + 
  aes(x = Sepal.Length, y = Sepal.Width) + 
  stat_smooth(method = "gam", formula = y ~ s(x, bs = "cs"))+ 
  ggtitle("stat_smooth(method = \"gam\", formula = y ~ s(x, bs = \"cs\")")
```

![](https://i.imgur.com/pmVayyK.png)

Created on 2018-06-01 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by batpigandme** [comment]
Oh, I see what you're saying. I thought the problem was that the first and last were the same – what you're saying is that the behaviour that occurs when _no_ method is specified should occur when "gam" is given, and it's currently happening when either _no method_ is given or gam and formula are given.

``` r
library(ggplot2)

iris2 <- iris[sample(seq_len(nrow(iris)), 1000, replace = TRUE), ]

ggplot(iris2) + 
  aes(x = Sepal.Length, y = Sepal.Width) + 
  stat_smooth() + 
  ggtitle("stat_smooth()")
#> `geom_smooth()` using method = 'gam' and formula 'y ~ s(x, bs = "cs")'
```

![](https://i.imgur.com/ARdWZuN.png)

``` r

ggplot(iris2) + 
  aes(x = Sepal.Length, y = Sepal.Width) + 
  stat_smooth(method = "gam") + 
  ggtitle("stat_smooth(method = \"gam\")")
```

![](https://i.imgur.com/8B6Xtvx.png)

``` r

ggplot(iris2) + 
  aes(x = Sepal.Length, y = Sepal.Width) + 
  stat_smooth(method = "loess") + 
  ggtitle("stat_smooth(method = \"loess\")")
```

![](https://i.imgur.com/50bxNAk.png)

Created on 2018-06-01 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by hadley** [comment]
This behaviour is correct; we report the formula but do not automatically change it. That's up to you.

**Comment by clauswilke** [comment]
Maybe it would help to be a bit more explicit in the documentation about how to manually switch to gam for arbitrary sample sizes. E.g.:

> If you want to use the default `gam` model for a dataset with fewer than 1,000 observations, set `method = "gam", formula = y ~ s(x, bs = "cs")`.

I also noticed that the documentation still says `formula = y ~ mgcv::s(x, bs = "cs")` and that needs to be modified to  `formula = y ~ s(x, bs = "cs")`.
