### ISSUE TITLE
geom_smooth() warning about ymin/ymax

### ISSUE THREAD

**Issue by Mait22** [tidyverse/ggplot2#1939]

**Comment by hadley** [comment]
Please provide a reproducible example. There are three things you need to include to make your example reproducible: required packages, data, and code.

1.  **Packages** should be loaded at the top of the script, so it's easy to
    see which ones the example needs. This is a good time to check that you're
    using the latest version of each package: it's possible you've discovered
    a bug that been fixed since you installed the package.

1.  The easiest way to include **data** in a question is to use `dput()` to 
    generate the R code to recreate it. For example, to recreate the `mtcars` 
    dataset in R, I'd perform the following steps:
  
    1. Run `dput(mtcars)` in R
    2. Copy the output
    3. In my reproducible script, type `mtcars <- ` then paste.
    
    Try and find the smallest subset of your data that still reveals
    the problem.

1.  Spend a little bit of time ensuring that your **code** is easy for others to
    read:

    * Make sure you've used spaces and your variable names are concise, yet
      informative.
    
    * Use comments to indicate where your problem lies.
    
    * Do your best to remove everything that is not related to the problem.  
      The shorter your code is, the easier it is to understand, and the 
      easier it is to fix.

Finish by checking that you have actually made a reproducible example by starting a fresh R session and copying and pasting your script in.

**Comment by simonrolph** [comment]
I have also encountered this issue, here's an example:

```
#library
library("dplyr")
library("ggfortify")
library("ggplot2") # version 2.20
library("gridExtra") # version 2.2.1
library("ggthemes") # version 3.3.0

#make linear model
m1 <- lm(data = mtcars, mpg~wt)

#create dataframe of x values to compute new values for
newX <- expand.grid(wt = seq(from = 1, to = 5, length = 10))

#predict the y values based of the x values
newY <- predict(m1, newdata = newX, interval = "confidence")

# combine into one dataframe
addThese <- data.frame(newX,newY)

# change header name
names(addThese)[2] <- "mpg"

# plot the original data, plus the new 'addThese' data, this plots correctly however we get "Warning: Ignoring unknown aesthetics: ymin, ymax"
ggplot(mtcars, aes(x = wt, y = mpg))+
  geom_point(colour = "blue")+
  geom_smooth(data = addThese, aes(ymin = lwr, ymax = upr), stat = "identity")

#output:
Warning: Ignoring unknown aesthetics: ymin, ymax

R.version

```  
  _                           
platform       x86_64-w64-mingw32          
arch           x86_64                      
os             mingw32                     
system         x86_64, mingw32             
status                                     
major          3                           
minor          3.1                         
year           2016                        
month          06                          
day            21                          
svn rev        70800                       
language       R                           
version.string R version 3.3.1 (2016-06-21)
nickname       Bug in Your Hair

**Comment by simonrolph** [comment]
Just tried it (on a different computer) with ggplot2 2.1.0 and got no error, then with ggplot2 2.2.0 and got the error.

**Comment by hadley** [comment]
Can you please provide a _minimal_ example. You should be able to recreate the problem with ~4 lines of code

**Comment by simonrolph** [comment]
```
library("ggplot2")
test_data <- data.frame(col1 = 1:10,col2 = 1:10, col3 = 3:12, col4 = 4:13) 
ggplot(test_data, aes(x = col1, y = col2))+
  geom_smooth(data = test_data, aes(ymin = col3, ymax = col4), stat = "identity")
```

**Comment by izahn** [comment]
@simonrolph it's a warning, not an error. And it does work despite the warning, correct?

The warning is annoying though.

**Comment by hadley** [comment]
I've cleaned up the issue title/comment thread to focus on key components of problem. Thanks for the correspondence so far :smile:
