### ISSUE TITLE
facet_grid wrong

### ISSUE THREAD

**Issue by gaodianzhuo** [tidyverse/ggplot2#1941]
R version 3.3.2 (2016-10-31) -- "Sincere Pumpkin Patch"
Copyright (C) 2016 The R Foundation for Statistical Computing
Platform: i386-w64-mingw32/i386 (32-bit)

> library(ggplot2)
> p <- ggplot(mpg, aes(displ, cty)) + geom_point()
> 
> p + facet_grid(. ~ cyl)
错误: 'as_tibble'不是'namespace:tibble'内的出口对象：

**Comment by hadley** [comment]
I can't read Chinese, but I'm guessing you need to update the tibble package.
