### ISSUE TITLE
Changed order in geom_bar in comparison with ggplot2 v1

### ISSUE THREAD

**Issue by Martin119** [tidyverse/ggplot2#1942]
Hello, this small example produces chart with different order of items with ggplot2  1.0.1 and 2.2.0

Cannot see the reason - the old one seems correct the newer unexpected (legend is the same)

library(ggplot2)
library(data.table)

c1 <- c(1,2)
c2 <- c("first","second")
c2 <- factor(c2, levels = c("first","second"))
c3 <- c(0.7,0.3)
ct <- data.table(c1,c2,c3)

ggplot(ct, aes(x=1,y=c3,fill=c2))+geom_bar(stat="identity")

**Comment by cderv** [comment]
Look at the changes in new v2.2.0 version of ggplot2. It is explained what changed. 
The website for documentation of v2.2 release [here](http://ggplot2.tidyverse.org/articles/releases/ggplot2-2.2.0.html). Look at the part on *Stacking Bars*

> position_stack() and position_fill() now stack values in the reverse order of the grouping, which makes the default stack order match the legend.

**Comment by Martin119** [comment]
Thank you for explanation.

I am not happy with this kind of changes.

**Comment by hadley** [comment]
@cderv thanks for helping people out with these issues, it's much appreciated!

**Comment by cderv** [comment]
@hadley No problem ! I am glad I can be helpful.  And if it is appreciated I will continue to do so! 
If you need more from me, do not hesitate.
