### ISSUE TITLE
ggplot 2.2.0 throws 'could not find function "facet_train_layout"' error

### ISSUE THREAD

**Issue by twolodzko** [tidyverse/ggplot2#1944]
In R 3.3.2 on Ubuntu linux ggplot 2.2.0 throws the following error on `example(ggplot)` and basically at any attempt to plot anything:

```
Error in ggint$train_layout(panel, plot$facet, layer_data, plot$data) : 
  could not find function "facet_train_layout"
```

This error occurs when using from RStudio and after restarting R, clearing the environment, detaching all other packages etc. It appears also when running R from console from fresh session (no other libraries loaded etc.). It does _not_ appear only when launching from `R --vanilla`.

**Comment by hadley** [comment]
You probably need to reinstall something. Sorry I can't be more specific 😞
