### ISSUE TITLE
geom_bar on r 3.3.2, inverted order ?

### ISSUE THREAD

**Issue by matsepp** [tidyverse/ggplot2#1945]
Hi,

I don't think this has been reported already...

Using R version 3.3.2 (on osx sierra) , compared to oldest version

the geom_bar categories are stacked from top to bottom instead of bottom to top... the following code

```require(ggplot2)
df <- data.frame(a=c(1,1,1,2,2,2,3,3,3),
                 b=c(1,2,3,4,5,6,7,8,9),
                 c=c('a','b','c','a','b','c','a','b','c'))
figure <- ggplot() + geom_bar(aes(x=a, y=b, fill=c), stat="identity", data=df)
plot(figure)
```
gives these two different results:

<img width="1074" alt="screen shot 2016-12-05 at 21 44 45" src="https://cloud.githubusercontent.com/assets/20416725/20901725/1fc62ca2-bb34-11e6-8412-4e77e7fbdefb.png">

Best

Mat

**Comment by hadley** [comment]
Please see the release notes, blog post, etc.
