### ISSUE TITLE
stacked barplot - heights add up inaccurately

### ISSUE THREAD

**Issue by mbuttner** [tidyverse/ggplot2#1947]
I want to the explained variance of a principal component analysis as bars - y-axis depicts the explained variance per component (and it is scaled by square root). Then, I computed how each PC correlates to a certain factor, i.e. I want to split the bars into two parts and after stacking, they are supposed to have exactly the same height than a single (non-split) stack.   
However, what happens is that ggplot scales the bars (in sqrt-scale) AND stacks them afterwards, which leads to
![stacked_barplot_inaccurate_heights](https://cloud.githubusercontent.com/assets/24408322/20967590/8adf1920-bc80-11e6-8b01-38b6229fba7b.png)

Instead, when we stacked and scaled the bars manually, we adjusted the height of our second bar, that is stacked onto the smaller one such that the total sum adds up coherently. 
![stacked_barplot_accurate_heights](https://cloud.githubusercontent.com/assets/24408322/20967588/8acf26a0-bc80-11e6-90a2-48280a1e257b.png)

**Comment by hadley** [comment]
Please provide a reproducible example. There are three things you need to include to make your example reproducible: required packages, data, and code.

1.  **Packages** should be loaded at the top of the script, so it's easy to
    see which ones the example needs. This is a good time to check that you're
    using the latest version of each package: it's possible you've discovered
    a bug that been fixed since you installed the package.

1.  The easiest way to include **data** in a question is to use `dput()` to 
    generate the R code to recreate it. For example, to recreate the `mtcars` 
    dataset in R, I'd perform the following steps:
  
    1. Run `dput(mtcars)` in R
    2. Copy the output
    3. In my reproducible script, type `mtcars <- ` then paste.
    
    Try and find the smallest subset of your data that still reveals
    the problem.

1.  Spend a little bit of time ensuring that your **code** is easy for others to
    read:

    * Make sure you've used spaces and your variable names are concise, yet
      informative.
    
    * Use comments to indicate where your problem lies.
    
    * Do your best to remove everything that is not related to the problem.  
      The shorter your code is, the easier it is to understand, and the 
      easier it is to fix.

Finish by checking that you have actually made a reproducible example by starting a fresh R session and copying and pasting your script in.
