### ISSUE TITLE
Should strip.placement use default when set to unknown value?

### ISSUE THREAD

**Issue by infotroph** [tidyverse/ggplot2#1950]
```
library(ggplot2)
p = ggplot(head(diamonds), aes(color, price)) +
    geom_point() +
    facet_wrap(~cut) +
    scale_x_discrete(position="top")
```

In 2.2.0 the default strip placement appears to be "inside": 

```
p + theme(strip.placement=NULL) # or just "p"
```

![screen shot 2016-12-08 at 12 50 07 pm](https://cloud.githubusercontent.com/assets/1256435/21021040/e8b4f726-bd44-11e6-9690-c3969b6b55e8.png)

But setting `strip.placement` to any value other than "inside" produces an outside placement:

```
p + theme(strip.placement="arbitrary")
```

![screen shot 2016-12-08 at 12 51 40 pm](https://cloud.githubusercontent.com/assets/1256435/21021099/18f7ff32-bd45-11e6-8a39-346ee1f0ce57.png)

Is this intentional? If not, would it be better for consistency to make unknown values produce the same placement as when it's left unset?

**Comment by hadley** [comment]
This seems like a good idea, but unfortunately it's not high enough on my priority list that I will implement it myself. However, I'd be happy to review a PR.
