### ISSUE TITLE
Overlapping points in exporting via ggsave

### ISSUE THREAD

**Issue by robertamezquita** [tidyverse/ggplot2#1953]
Saving as a PDF, ggplot2 exports all layers in the plot. While this usually is a good thing, in the case of very dense scatter plots this presents an issue of overplotting, and slows any vector graphics suite down to a crawl when there thousands of points. Might there be a way to simplify a dense scatter plot such that it only draws the top-most layers? Probably too specific of an issue that could break other things, but just wanted to point this out to see if anyone has any workarounds.

**Comment by hadley** [comment]
I'd recommend using `geom_hex()` or similar instead.
