### ISSUE TITLE
Error in plotting scatter plot using GGally package

### ISSUE THREAD

**Issue by minoo77777** [tidyverse/ggplot2#1955]
I want to plot a scatterplot using GGally package. My data frame contains these numbers

```
152861.1277	0.751206523	2013	1.35E+239	6.29E+03	2.00E-01	24.75857978	0.001103093	8.35E+04
127194.554	0.691661805	694	2.84E+238	6.29E+03	2.00E-01	14.97627887	0.000379999	5.26E+03
6.06E+04	5.34E-01	3.28E+02	5.16E+237	6.28E+03	2.00E-01	18.07714174	1.80E-04	1.01E+03
40410.08303	0.479646356	271	3.32E+237	6.28E+03	2.00E-01	32.25630782	0.000148763	1.89E+03
[example.txt](https://github.com/tidyverse/ggplot2/files/649959/example.txt)

```
I wrote these code:

```
library(GGally)

    ggscatmat(df,alpha=0.8)  + 
  theme(legend.position="none")+
  labs(title = "Scatterplot")

```
but I faced this error
```

Error in if ((w[1] * sm + w[2] * cm + w[3] * dm + w[4]) < best$score) break : 
  missing value where TRUE/FALSE needed
```
I would be really grateful for your kind help.

**Comment by minoo77777** [comment]
@schloerke Sorry to mentioned you, But I think you can help me to solve this problem.

**Comment by schloerke** [comment]
@minoo77777 np!  Go ahead and close this issue here as the problem lies with ggscatmat

Can you resubmit it to github.com/ggobi/ggally/issues ?  I'll take a look at it tonight or tomorrow. 

Thank you

**Comment by minoo77777** [comment]
@schloerke I resubmitted it. Thanks a lot.
