### ISSUE TITLE
layer quietly renames certain parameters

### ISSUE THREAD

**Issue by nteetor** [tidyverse/ggplot2#1959]
Motivated by exercise 2 under section "Creating a new stat" of the "Extending ggplot2" vignette.
> 2. Modify the final version of StatDensityCommon to allow the user to specify the min and max parameters. You’ll need to modify both the layer function and the compute_group() method.

### case 1 (no warning generated)

Parameters named col, color, pch, cex, lty, lwd, srt, adj, bg, fg, min, or max (see `ggplot2:::.base_to_ggplot`) are renamed without warning when passed to layer(). Values do get passed to methods such as `setup_params()`, but as the renamed names. See the following example,

```R
library(ggplot2)

# create an example Stat which passes along data without
# modification, but outputs information to the console
StatExample <- ggproto(
  'StatExample', Stat,

  setup_params = function(data, params) {
    cat('\n`params` includes:\n')
    print(params)
    params
  },

  # here is where we use ymin, ymax, and fill instead of min, max, and bg
  # to work around the internal renaming
  compute_group = function(data, scales, ymin, ymax, fill, extra) {
    data
  }
)

# create a new stat function
stat_example <- function(mapping = NULL, data = NULL, geom = 'point',
                      position = 'identity', na.rm = FALSE, show.legend = NA,
                      inherit.aes = TRUE, min = 'min arg', max = 'max arg',
                      bg = 'dodgerblue', extra = 'still extra', ...) {
  layer(
    stat = StatExample, mapping = mapping, data = data, geom = geom,
    position = position, show.legend = show.legend, inherit.aes = inherit.aes,
    params = list(na.rm = na.rm, min = min, max = max, bg = bg, extra = extra,
                  ...)
  )
}

d <- data.frame(
  x = 1:5,
  y = 1:5
)

# runs without error, but we knew to name the arguments
# ymin, ymax, and fill, see console output below
ggplot(d, aes(x = x, y = y)) +
  stat_example()
```

console output,
```
> d <- data.frame(
+     x = 1:5,
+     y = 1:5
+   )
> ggplot(d, aes(x = x, y = y)) +
+     stat_example()

`params` includes:
$na.rm
[1] FALSE

$ymin
[1] "min arg"

$ymax
[1] "max arg"

$fill
[1] "dodgerblue"

$extra
[1] "still extra"
```

### proposal 1

I am unsure what to propose as a solution. But, I would like to propose an update to the ggproto vignette. I suggest adding a note of caution to the ggproto vignette about using "min" or "max" as parameter names in `stat_density_common()`. Especially if no change is made, the reader will know to work around the problem by using different parameter names in `stat_density_common()` or use the prediction gimmick from above in the `StatDensityCommon` methods.

### case 2 (warning generated)

In addition to the above bug, there is an interesting case when *not* predicting the internal renaming i.e. in the `compute_group()` method use "min" or "max" instead of "ymin" or "ymax". See the following example,

```R
library(ggplot2)

# recreate the Stat from above, but with a small, key change
StatExample <- ggproto(
  'StatExample', Stat,

  setup_params = function(data, params) {
    cat('\n`params` includes:\n')
    print(params)
    params
  },

  # this time use min, max, and bg instead of ymin, ymax,
  # or fill as we did above
  compute_group = function(data, scales, min, max, bg, extra) {
    
    # min, max, and bg will all be missing, see console output below
    if (missing(min) && missing(max) && missing(bg)) {
      cat('In `compute_group`, missing arguments min, max, and bg')
    }
    data
  }
)

# create the stat function
stat_example <- function(mapping = NULL, data = NULL, geom = 'point',
                      position = 'identity', na.rm = FALSE, show.legend = NA,
                      inherit.aes = TRUE, min = 'min arg', max = 'max arg',
                      bg = 'dodgerblue', extra = 'still extra', ...) {
  layer(
    stat = StatExample, mapping = mapping, data = data, geom = geom,
    position = position, show.legend = show.legend, inherit.aes = inherit.aes,
    params = list(na.rm = na.rm, min = min, max = max, bg = bg, extra = extra,
                  ...)
  )
}

d <- data.frame(
  x = 1:5,
  y = 1:5
)

# runs without error again, but produces a somewhat confusing warning
# see console output below
ggplot(d, aes(x = x, y = y)) +
  stat_example()
```

console output,
```
> d <- data.frame(
+     x = 1:5,
+     y = 1:5
+   )
> ggplot(d, aes(x = x, y = y)) +
+     stat_example()
Warning: Ignoring unknown parameters: ymin, ymax

`params` includes:
$na.rm
[1] FALSE

$extra
[1] "still extra"

In `compute_group`, missing arguments min, max, and bg
```

### ~proposal 2

In this case `params` does not include the problematically named values and I believe lines [136 and following](https://github.com/tidyverse/ggplot2/blob/cb3bdde0e0ba65be3042083092eb397057af8e3f/R/stat-.r#L136-L145) may be responsible for this. As a result the arguments are missing within `compute_group()`. Additionally, in this case a warning is raised, but the warning cryptically only mentions "ymin" and "ymax" and not "fill". This "proposal" is more of a heads up.

**Comment by hadley** [comment]
I think the right solution is to add a note to the vignette. This behaviour is important and long-standing and it's too late to change now.  Do you want to do a PR?

**Comment by nteetor** [comment]
Certainly, I will put together a PR. 

In the vignette, would you prefer an annotation or aside or an inline word of caution about the problematic names?

**Comment by hadley** [comment]
Just a brief aside should be adequate
