### ISSUE TITLE
Time plot renders differently under 2.2.0

### ISSUE THREAD

**Issue by simonspr** [tidyverse/ggplot2#1961]
I have a important plot which used to render nicely in ggplot 2.1.0, but renders differently under the latest version 2.2.0. I'm running R 3/3/2, all other packages updated .Please take a look please advise if I can still render the same type of graph using ggplot 2.2.0.

Here's the R data.

```R
df <-
structure(list(day = structure(c(1L, 1L, 1L, 1L, 1L, 1L, 1L, 
1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 
2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 
2L, 2L, 2L, 2L, 2L, 2L), .Label = c("17-10 Mon", "18-10 Tue"), class = "factor"), 
    dur = c(7.744, 0.323, 0.174, 0.547, 0.177, 1.452, 0.031, 
    0.034, 0.405, 0.475, 0.776, 0.362, 0.13, 0.373, 0.56, 0.356, 
    0.607, 0.993, 0.545, 0.159, 0.463, 0.103, 0.692, 0.102, 0.207, 
    0.081, 0.625, 0.087, 0.381, 0.13, 0.372, 7.224, 0.383, 0.534, 
    0.216, 0.241, 0.233, 0.082, 0.224, 0.455, 0.613, 0.375, 1.052, 
    0.276, 0.455, 0.595, 0.568, 0.237, 0.579, 0.529, 0.309, 0.254, 
    0.667, 0.18, 0.406, 0.346, 0.292, 0.154, 0.452, 0.071, 0.512
    ), type = structure(c(1L, 3L, 2L, 4L, 2L, 3L, 2L, 5L, 2L, 
    5L, 2L, 5L, 2L, 6L, 7L, 2L, 4L, 2L, 4L, 2L, 5L, 2L, 5L, 2L, 
    5L, 2L, 5L, 2L, 3L, 2L, 8L, 1L, 7L, 2L, 5L, 2L, 5L, 2L, 5L, 
    2L, 5L, 2L, 5L, 2L, 5L, 2L, 7L, 2L, 4L, 2L, 4L, 2L, 4L, 2L, 
    5L, 2L, 6L, 2L, 9L, 2L, 9L), .Label = c("off", "idle", "foot", 
    "bones", "skull", "throat", "torso", "arm", "hip"), class = "factor")), .Names = c("day", 
"dur", "type"), row.names = c(NA, 61L), class = "data.frame")

col = c("#FFFFFF", "#BEBEBE", "#003478", "#0066A1", "#7BA4D9", "#024731", "#983222", "#22505F", "#1E9D8B") 
names(col) = levels(df$type)
x11(); ggplot(data=df, aes(x=day,y=dur,fill=type)) + geom_bar(stat="identity") + scale_fill_manual(name="type", values=col) + theme(panel.background = element_blank()) + scale_y_continuous(expand = c(0, 0), limits=c(0, 24), breaks=seq(1, 24, 1)) + coord_flip()
```

This gives the plot below under ggplot 2.1.0. Note the bars are kept separate and are not aggregated, allowing me to show timed activity.

Inline images 1
![image](https://cloud.githubusercontent.com/assets/24670629/21347559/114a93a2-c6a1-11e6-9685-4cb6689a79cb.png)

This gives the plot below under ggplot 2.1.0. Note the bars are kept separate and are not aggregated, allowing me to show timed activity.

Now if I plot the same graph using ggplot 2.2.0, I now get, which looses the timing information I want to show:

Inline images 2
![image](https://cloud.githubusercontent.com/assets/24670629/21347571/1f4172f0-c6a1-11e6-8d4c-83fc99f76e65.png)

Please could you advise as I would like to keep up-to-date with ggplot.

Thanks

Paul

**Comment by hadley** [comment]
You can work around it by adding a unique identifier for each row and grouping by that:

```R
df$id <- 1:nrow(df)

ggplot(df, aes(day, dur, fill = type, group = id)) + 
  geom_col()
```

The default stacking is now more aggressive than it used to be. I need to think about this a bit more.

Here's a minimal reprex:

```R
library(tidyverse)

df <- tribble(
  ~ x, ~ y,
  "a", "a",
  "a", "b",
  "a", "a",
  "b", "a"
)

ggplot(df, aes(x, y = 1, fill = y)) + 
  geom_col()
```

**Comment by simonspr** [comment]
Hi Hadley

Thanks for your reply. We are almost there as applying to my example now
gives:
df$id = 1:nrow(df)
x11(); ggplot(data=df, aes(x=day,y=dur,fill=type, group=id)) + geom_col() +
scale_fill_manual(name="type", values=col) + theme(panel.background =
element_blank()) + scale_y_continuous(expand = c(0, 0), limits=c(0, 24),
breaks=seq(1, 24, 1)) + coord_flip()

[image: Inline images 1]

However, two data points are not represented in the beginning of each day,
which should fill white representing machine off state, from 0:00 until
after 7 o'clock on each day.  e.g. in row 2 the foot exam should start at
7.744 hours and go on for 0.323 hours, but it starts at 0:00. Please see my
original target image.

from the data these related points are:
> df[c(1,2,32),]
         day      dur    type id
1  17-10 Mon 7.744  off  1
2  17-10 Mon 0.323 foot  2
32 18-10 Tue 7.224  off 32

Please can you advise?


PS I am a big fan of ggplot2 and R and R Studio. You are doing great work.

Regards

Paul

**Comment by hadley** [comment]
Can you please format your question using markdown, and work to make it easily reproducible for me? (i.e. transform the plot so it's strikingly obvious what the problem is)

**Comment by simonspr** [comment]
Hi Hadley


Thanks your original answer has showed me what to do, with a little
digging. In my case, I needed to reverse the id to get the representation I
was looking for, So I changed your line:


df$id = 1:nrow(df)


to

df$id = nrow(df):1


and now it works perfectly.


Thanks so much


Regards


Paul
