### ISSUE TITLE
Change stacking behaviour in ggplot2 2.2.0 geom_bar collide with unchanged behaviour of geom_text

### ISSUE THREAD

**Issue by mgruebsch** [tidyverse/ggplot2#1965]
According to the blog https://blog.rstudio.org/2016/11/14/ggplot2-2-2-0/ (and my own observations) the stacking behaviour of geom_bar has been reversed such that the order of items is the same as in the legend.

In some scenarios stacked bar charts (geom_bar) are combined with stacked text labels (geom_text). Because geom_text seems not to be changed accordingly, the charts are wrongly formatted now.

Please change this. I suggest one of the following:

1. revert to the old behaviour of geom_bar
2. add an option to geom_bar to reverse the order (default is behaviour from 2.1.0: reverse = false)
3. the new geom_col function may use the new ordering (default: reverse = true)
4. Alternatively a less invasive change would be to reverse the order of the legend.
5. If 1-3 or 4 are not an option please change geom_text accordingly.

Thank you for your support!

**Comment by hadley** [comment]
Make sure to specifying the `group`ing for the text.

**Comment by mgruebsch** [comment]
Here is an example:

    library(ggplot2)
    
    x <- data.frame(
      a=c("A", "A", "B", "B"),
      b=c("x", "y", "x", "y"),
      m=c(4, 8, 7, 3)
    )
    
    
    # Example 1: label at the top of the bar segment
    
    ggplot(x, aes(x=a, y = m)) + 
      geom_bar(stat="identity", aes(fill=a, alpha=b)) + 
      geom_text(position = "stack", aes(label=m), vjust=-0.3, size = 3) +
      scale_alpha_discrete(range=c(1, 0.5))
    
    
    # Example 2: label at the center of the bar segment
    
    x = x[order(x$a, x$b),]
    x$p = ave(x$m, x$a, FUN = cumsum)
    x$p = x$p - x$m * 0.5
    
    # p is a calculated label pos for the second example such that within each x$a
    # category the labels are centered for the stacked x$b; 
    # e.g x$p[2] = x$m[1] + x$m[2] / 2
    
    ggplot(x, aes(x=a, y = m)) + 
      geom_bar(stat="identity", aes(fill=a, alpha=b)) + 
      geom_text(position = "identity", aes(y=p, label=m), size = 3) +
      scale_alpha_discrete(range=c(1, 0.5))

At least the second example goes wrong with ggplot2 2.2.0 (can't test the first one with 2.2.0 at the moment). Of course it is possible to calculate `x$p` according to the new scheme. However, I do not think that this is intuitively, because in 2.1.0 all `x$m` from the first to the current must be summed up while in 2.2.0 all `x$m` from the last to the current must be regarded. This is not as easy as here, because `x$b` must at first be ordered descending to calculate the label pos and after that it must be reordered ascending to confirm to the new display behaviour of ggplot2 2.2.0.

**Comment by hadley** [comment]
As I said in my very brief comment, all you need to do is make sure that the grouping is consistent across the text and fill layers:

```R
ggplot(x, aes(a, m, group = b)) + 
  geom_col(aes(fill = b)) + 
  geom_text(aes(label = m), position = "stack")
```

**Comment by mgruebsch** [comment]
This works perfectly with the first example; thank you.

However, I don’t see that it is a solution for the second example with centered text labels, because the label positions are precomputed. Is there a simpler way to center the labels without precomputed positions?

**Comment by hadley** [comment]
See the example in `?position_stack`
