### ISSUE TITLE
Add option for range ticks (tick labels between tick marks)

### ISSUE THREAD

**Issue by flying-sheep** [tidyverse/ggplot2#1966]
Achieving this with built-in methods is [pretty hacky](http://stackoverflow.com/a/22221898/247482), and a more generic way on top of ggplot2 still involves combining a special scale and a special theme, none of which make sense in isolation. (the scale has every second tick labeled, and the theme hides the dummy ticks and grid lines.)

Idk how to do this best, as it deviates from the 1:1 relationship between ticks and tick labels – range ticks are associated with the value range between tick marks.

I think the formatting function would get passed either the middle between the tick positions or the previous and next tick position. e.g. for ticks spaced 1, the formatting function would either be passed `(0.5)` or `(0, 1)` for the tick label between the values 0 and 1.

**Comment by hadley** [comment]
I really don't like this style of labelling (what _do_ the labels correspond to), and it would be a lot of work so it's unlikely to ever get implemented.

**Comment by flying-sheep** [comment]
for time, lengths, … you usually have an origin and specify spans and points on the scale as distance from the origin. not so for dates. here you usually say 2017 to address the time span `[2017-01-01Z00:00; 2018-01-01Z00:00)`, and new year point is relatively meaningless for addressing dates. (happy new year by the way 🎉)

to generalise (although i don’t know where else this would be applicable) those ticks are used for continuous ranges where *consecutive unit sections* are the usual way to address instead of *points*.
