### ISSUE TITLE
geom_hex: Add weight parameter [feature request]

### ISSUE THREAD

**Issue by sjackman** [tidyverse/ggplot2#1967]
Please consider adding a weight parameter to `geom_hex`, similar to `geom_bin2d`. Thanks!

**Comment by hadley** [comment]
It's already supported?

**Comment by sjackman** [comment]
Ah, I was confused. Thanks. `weight` is not listed in the aesthetics for neither `geom_bin2d` nor `geom_hex`. Should it be?
http://docs.ggplot2.org/current/geom_bin2d.html
http://docs.ggplot2.org/current/geom_hex.html

**Comment by hadley** [comment]
Yes! Want to do a PR?

**Comment by sjackman** [comment]
Sure. Can do.
