### ISSUE TITLE
ggplot2::waiver throws a warning on r-devel

### ISSUE THREAD

**Issue by bgoodri** [tidyverse/ggplot2#1968]
The recent R commit r71841 deprecates what `ggplot2::waiver` does. In the development version of R,
```
ggplot2::waiver()
```
yields

> Warning message:
In structure(NULL, class = "waiver") :
  Calling 'structure(NULL, *)' is deprecated, as NULL cannot have attributes.
  Consider 'structure(list(), *)' instead.

This is leading to some largely spurious test failures in other packages that use `testthat::expect_silent()` but end up calling something in ggplot2 that calls `waiver` internally.

**Comment by bbolker** [comment]
just to follow up:

- occurs [here](https://github.com/tidyverse/ggplot2/blob/cb3bdde0e0ba65be3042083092eb397057af8e3f/R/utilities.r#L149)
- being discussed on `r-pkg-devel` [here](https://stat.ethz.ch/pipermail/r-package-devel/2016q4/001228.html)
