### ISSUE TITLE
wrong dates with a simple plot.

### ISSUE THREAD

**Issue by Monduiz** [tidyverse/ggplot2#1969]
With a simple serie of dates, ggplot is wrongly plotting the entries after conversion to date. I am not sure I understand this behavior.

```
library(lubridate)
library(ggplot2)
obs <- c("obs1", "obs1", "obs1", "obs1")
month <- c("2016-08-01","2016-09-30", "2016-10-30", "2016-11-30")
num <- c(23260, 23878, 25017, 26107)

d <- data.frame(obs, month, num) 
d$month <- ymd(d$month)

g <- ggplot(d, aes(month, num))
g <- g + geom_bar(stat = "identity")
```

Shouldn't the entries appear correctly? A month is skipped and data points appear at the wrong date.
However, is using month(d$month), then it will work. Why cant the actual date be used in the plot? There is something I am missing.

**Comment by EmanuelContreras** [comment]
You have to change the datatype of "month" in ggplot() as character:
```
library(lubridate)
library(ggplot2)
obs <- c("obs1", "obs1", "obs1", "obs1")
month <- c("2016-08-01","2016-09-30", "2016-10-30", "2016-11-30")
num <- c(23260, 23878, 25017, 26107)

d <- data.frame(obs, month, num) 
d$month <- ymd(d$month)

 ggplot(d, aes(x=as.character(month), y=num)) + geom_bar(stat = "identity")
```
![rplot08](https://cloud.githubusercontent.com/assets/22753863/21531266/9877ba98-cd14-11e6-95ae-524add898039.png)

**Comment by Monduiz** [comment]
So the plot can only use characters or factors in this case?

**Comment by infotroph** [comment]
You're specifying a continuous x-axis—Despite the name, "month" is actually a date with precision down to the day. This is no problem for geom_bar, but it doesn't do any rounding, so the second bar is centered on September 30th, exactly where the data specify!

To get the plot you were expecting, change `d$month <- ymd(d$month)` to `d$month <- month(d$month)`, optionally with `label=TRUE`.

**Comment by hadley** [comment]
The problem is that you have fat bars and coarse breaks on the x-axis:

```R
ggplot(d, aes(month, num)) + 
  geom_col(width = 1) + 
  scale_x_date(date_breaks = "14 days", date_labels = "%d/%m")
```
