### ISSUE TITLE
Implement geom_auto

### ISSUE THREAD

**Issue by hadley** [tidyverse/ggplot2#1974]
Should be S3 generic that dispatches on the type of the `data` argument, which will need to come first.

Helpful for forecast (@robjhyndman) and sf objects.

**Comment by hadley** [comment]
Possibly should be `auto_geom()` or `auto_layer()` since arguments will be rather different to most geoms.

**Comment by robjhyndman** [comment]
We are using `autolayer()` in the forecast package (github version). Could change to `auto_layer()` if you prefer, but we need to decide soon to avoid broken code down the track. I plan to push a new CRAN version of the forecast package in about a month.

**Comment by mitchelloharawild** [comment]
Note that I used `autolayer()` for consistency with `autoplot()`.
Happy for it to be `auto_layer()`, but if this is used, I'd suggest a similar change for `auto_plot()`.

**Comment by hadley** [comment]
You're right that it should be `autolayer()` for consistency. Want to do a PR?
