### ISSUE TITLE
Export and document scale_type

### ISSUE THREAD

**Issue by hadley** [tidyverse/ggplot2#1975]
So others can use it for there list-columns (and other S3 types)

**Comment by bearloga** [comment]
Hoping for a new version of ggplot2 to be published on CRAN soon because unfortunately @thomasp85's ggraph (the version on CRAN) cannot be loaded since ggplot2 2.2.1 (published 2016-12-30) does not have this fix anyone not using the dev version currently gets:

```
> library(ggraph)
Loading required package: ggplot2
Error: package or namespace load failed for ‘ggraph’:
 object ‘scale_type’ is not exported by 'namespace:ggplot2'
```
