### ISSUE TITLE
Change way themes are added

### ISSUE THREAD

**Issue by thomasp85** [tidyverse/ggplot2#1981]
I've created a `textboxGrob` that allows for automatic wrapping of text etc. I'm trying to create an `element_textbox` as a subclass of `element_text` to allow people to use it for titles etc, but there are some problems in how themes are added that makes it impossible to subclass elements.

Specifically the class of the added elements are dropped if the element is already present, since `add_theme` is merely modifying the slots of the original element rather than using the added element as the base.

Will you be willing to consider a PR that flipped this behaviour so that `add_theme` would use the added element as base and modify the `NULL` slots of this?

**Comment by baptiste** [comment]
sounds similar to https://github.com/tidyverse/ggplot2/issues/1240

**Comment by hadley** [comment]
Yes, I would be willing to consider a PR.
