### ISSUE TITLE
> library(tmap) Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) :    there is no package called ‘digest’ Error: package or namespace load failed for ‘tmap’

### ISSUE THREAD

**Issue by elina800** [tidyverse/ggplot2#1982]
hey there.. R studio even if it can install tmap package cannot specifies and loads library.. I upadated all the packages in case of but without any desired result

Any suggestions?

Thnx

**Comment by hadley** [comment]
I'm not sure why you're asking here. This is the ggplot2 repo.
