### ISSUE TITLE
aspect() for sf is assuming longitude/latitude

### ISSUE THREAD

**Issue by mdsumner** [tidyverse/ggplot2#1985]
It's not appropriate to use the cosine-latitude-hack for projections that aren't in angular units, and currently we have to use `coord_sf()` manually to fix it.  

Here's an example where the defaults give catastrophic results (map is flipped). (I haven't explored enough to know if this will behave with sensible defaults given other work that's going in. )

The following code gives a "y-flipped" map in ff80b239

```R
library(ggplot2)
library(maptools)
library(sf)

data(wrld_simpl)

m <- st_transform(st_as_sf(subset(wrld_simpl, NAME %in% c("Australia", "New Zealand"))), 
                  "+proj=laea +y_0=1.3e6 +lon_0=155 +lat_0=-30 +ellps=WGS84 +no_defs")

ggplot(m) + geom_sf(aes(geometry = geometry)) 

## tell it not to do that
ggplot(m) + geom_sf(aes(geometry = geometry)) + coord_sf(lat_lon = FALSE)
```

Personally I think the cosine hack does more harm than good  (providing a kind of expectation that working with angular coordinates in a planar context is "fine"), it's really from a legacy age when projecting was computationally expensive and inaccessible. 

I'm confused about why it's a default, but then maybe I'm picking at this too early.

**Comment by hadley** [comment]
For in progress PRs, it'd be more useful to comment on the PR itself. This problem is now fixed.
