### ISSUE TITLE
geom_violin draw_quantiles option does not match data (or geom_boxplot)??

### ISSUE THREAD

**Issue by svannoy** [tidyverse/ggplot2#1986]
I'm trying to resolve a discrepancy between the lines drawn in geom_violin when the draw_quantiles=c(.25, .5, .75) option is used.

From the example below, the quantiles of my data are 1, 3, and 7 respectfully. The violin plot draws them at approximately 2, 4, and 7; the boxplot overlay in the second graph lines up with expectations (1, 3, 7).

Not sure if this is a bug or if I'm doing something wrong....

 ```
 dput(demoDf)
structure(list(scores = c(4L, 7L, 4L, 5L, 0L, 0L, 1L, 5L, 1L, 
12L, 2L, 0L, 3L, 18L, 7L, 2L, 0L, 5L, 5L, 1L, 4L, 0L, 9L, 21L, 
1L, 1L, 3L, 0L, 8L, 0L, 2L, 3L, 7L, 2L, 3L, 8L, 2L, 4L, 1L, 2L, 
1L, 8L, 11L, 3L, 22L, 0L, 5L, 4L, 8L, 8L)), .Names = "scores", row.names = c(NA, 
-50L), class = "data.frame")

  quantile(demoDf$scores, c(.25, .5, .75))

  demoPlot <- ggplot(data=demoDf, aes(x=1, y=scores)) +  
    geom_violin(draw_quantiles = c(.25, .5, .75)) +  
    scale_y_continuous(breaks = seq(from=0, to=27, by=1)) 
  print(demoPlot)
  
  print(demoPlot+geom_boxplot(width=.1))

```
![violin_demo](https://cloud.githubusercontent.com/assets/8680680/21681758/9fd618ce-d31e-11e6-8777-33474c939a48.jpeg)
![violin_box_demo](https://cloud.githubusercontent.com/assets/8680680/21681768/a79ec506-d31e-11e6-8de3-5ad01def1187.jpeg)

**Comment by wch** [comment]
The difference probably occurs because the quantiles for the violin plot are computed on the density estimate, whereas the quantiles for boxplots are computed on the actual data.

**Comment by svannoy** [comment]
That makes sense.

Thanks
S


Peace is every moment
