### ISSUE TITLE
Feature request: Integrated Dendrograms

### ISSUE THREAD

**Issue by ckuenne** [tidyverse/ggplot2#1987]
Hi,

first of all thanks for the beautiful ggplot2 package! You really brought plotting to a different level.

Now, I recently wanted to switch from heatmap.2 to ggplot2 for drawing heatmaps, but found that the latter does not natively support dendrograms. I am aware of a few hacks/packages including roughly arranging multiple plot layers or viewports to produce something like this, but that is not really flexible/exact enough for what I'm trying to do.

Are there plans to natively support integrated dendrograms as part of the ggplot2 grammar in the future? This would not just be a valuable feature to improve heatmaps, but could be used for a variety of plots to denote similarity.

Best,
Carsten

**Comment by hadley** [comment]
Unfortunately this is out of scope for ggplot2.
