### ISSUE TITLE
Rounded line ends not working under Mac OSX

### ISSUE THREAD

**Issue by jcrada** [tidyverse/ggplot2#1995]
Hi,

first of all, thanks for the amazing library.

The problem I have is that the 'rounded' line ends are not working correctly in MacOSX Sierra under R 3.3.2 and 3.3.1. I have confirmed it works fine under Ubuntu Linux 16.

Given a `ggplot` with `aes` property `lineend='round'`
Then I expect the plot to have rounded line ends
But I get `butt` (or `square`) line ends

For example, 
```R
library('ggplot2')

x = seq(0,1,length=500)

term.triangle = function(x, a, b, c){
  if (x < a | x > c)
    0.0
  else if (x == b)
    1.0
  else if (x < b)
    (x - a) / (b - a)
  else
    (c - x) / (c - b)
}

triangle.df = data.frame(x, y=sapply(x, term.triangle, min(x), average, max(x)))
triangle.plot = ggplot(triangle.df, aes(x,y, size=2, lineend='round')) + geom_line() + ylab(expression(mu(x))) 

ggsave(triangle.plot, '/tmp/x.pdf')
```

Produces:

![rplot](https://cloud.githubusercontent.com/assets/303131/21925855/2c2d61b2-d9e4-11e6-9e10-6e2fc14d3c74.png)

**Comment by hadley** [comment]
If this doesn't work only on the mac, it's likely to be due to the graphics device, which is unfortunately outside of my control.
