### ISSUE TITLE
geom_bar() needs example of position_stack(reverse = TRUE)

### ISSUE THREAD

**Issue by mgruebsch** [tidyverse/ggplot2#2001]
The stacking behaviour of geom_bar has been reversed such that the order of items is the same as in the legend. This seems not to be suitable when bars are horizontal orientated (apply coord_flip()).

    library(ggplot2)
    
    x <- data.frame(
      a=c("A", "B", "A", "B"),
      b=c("x", "x", "y", "y"),
      m=c(4, 8, 7, 3)
    )
    
    ggplot(x, aes(x=a, y = m)) + geom_col(aes(x = a, y = m, fill = b)) + coord_flip()

Moreover, if the legend direction is horizontal too, we are back to the old confusing dis-alignment of items in the bar and the legend:

    library(ggplot2)
    
    x <- data.frame(
      a=c("A", "B", "A", "B"),
      b=c("x", "x", "y", "y"),
      m=c(4, 8, 7, 3)
    )
    
    ggplot(x, aes(x=a, y = m)) + geom_col(aes(x = a, y = m, fill = b)) + coord_flip() + theme(legend.position="bottom",  legend.direction = "horizontal")

To reverse the order of factors seems not to be a solution in this case.

Is there any other solution?

**Comment by hadley** [comment]
Use `position = position_stack(reverse = TRUE)`.  I need to add this to the examples.

**Comment by mgruebsch** [comment]
Works perfectly. Thanks!
