### ISSUE TITLE
Customizing legend key for geom_text and geom_label

### ISSUE THREAD

**Issue by alberthkcheng** [tidyverse/ggplot2#2004]
Currently, the legend key is fixed to "a" because of the following code in legend-draw.r:

```
draw_key_text <- function(data, params, size) {
  textGrob("a", 0.5, 0.5,....
```

What i need to do is, when my label is showing numbers only, i would like to have a number, e.g. "1" on the legend key instead of "a".

I tried to use the following but it does not look beautiful (in terms of code clarity):
```
draw_key_text <- function(data, params, size) {
  textGrob(params$legend.key, 0.5, 0.5,....
}

geom_text <- function(....
                      key.legend = "a",..){
.... layer(....params = list(...key.legend = key.legend,...))
}
```

Is there any suggestion?

**Comment by hadley** [comment]
This seems like a good idea, but unfortunately it's not high enough on my priority list that I will implement it myself. However, I'd be happy to review a PR. The key challenge will be finding the right way to get the information to the legend - I suspect that the `guide_legend()` function would be the right place to set it.
