### ISSUE TITLE
Eror : x must be length 1 or X

### ISSUE THREAD

**Issue by dipenpatel235** [tidyverse/ggplot2#2006]
Hello...
i am using shiny R and get error when try to used pie chart
Eror : x must be length 1 or X

Below is mine code

`   this_base <- "fig02-05_three-dimensional-pie-data-two-dimensional-pie-chart"
    
    my_data <- data.frame(
      variable = c("A", "B", "C", "D"),
      value = c(0.2, 0.2, 0.2, 0.4))
    
    p <- ggplot(my_data, aes(x = factor(1), y = value, fill = variable)) +
      geom_bar(width = 1, colour = "black", stat = "identity") + 
      coord_polar(theta = "y") +
      guides(fill = FALSE) + 
      scale_fill_manual(values = c('grey40', 'grey20', 'white', 'grey80')) +
      ggtitle("Fig 2.5 Three-Dimensional Pie Data:\nTwo Dimensional Pie Chart") + 
      theme_bw() + 
      theme(panel.grid.major = element_blank(), 
            panel.border = element_blank(),
            plot.title = element_text(size = rel(1.5), face = "bold"),
            axis.title = element_blank(), 
            axis.text = element_blank(),
            axis.ticks = element_blank())
    
    p`

**Comment by hadley** [comment]
Can you please make your example more minimal? You have a lot going on there.

**Comment by hadley** [comment]
Thanks for providing some code that illustrates the problem — it's a great start 😄 However, your code is currently a bit too complicated: there's quite a bit of extraneous stuff in there that doesn't seem directly related to the problem. Can you please try and simplify your example some more? The more minimal you can make the reprex, the faster I can identify the problem and fix it.

**Comment by dipenpatel235** [comment]
ok..let me paste complete code. you just need to run this code

`library(shiny)
library(plotly)
library(ggplot2)

ui <- fluidPage(
  plotlyOutput("plot"),
  verbatimTextOutput("event")
)

server <- function(input, output) {
  
output$plot <- renderPlotly({
    df <- data.frame(
      group = c("Male", "Female", "Child"),
      value = c(25, 25, 50)
    )
    head(df)
    p <- ggplot(df, aes(x=1, y=value, fill=group)) +
      ggtitle("How I've spent my PhD hours this week") +
      coord_polar(theta='y')
    p <- p +
      geom_bar(stat="identity", color='black') +
      guides(fill=guide_legend(override.aes=list(colour=NA)))
    p
  })
  
  output$event <- renderPrint({
    d <- event_data("plotly_hover")
    if (is.null(d)) "Hover on a point!" else d
   })
 }
shinyApp(ui, server)`

**Comment by hadley** [comment]
GitHub issues use [markdown](https://guides.github.com/features/mastering-markdown/) and they're much easier to read if you learn a little bit about it. The most important thing is to put your R code inside a block that starts with ```` ```R ```` and ends with ```` ``` ````.

**Comment by hadley** [comment]
This reprex worked fine for me:

```R
library(shiny)
library(ggplot2)

df <- data.frame(
  group = c("Male", "Female", "Child"),
  value = c(25, 25, 50)
)

shinyApp(
  fluidPage(plotOutput("plot"))
  function(input, output) {
  output$plot <- renderPlot({
    ggplot(df, aes(1, value, fill = group)) +
      geom_col() +
      coord_polar(theta='y')
  })
})
```

**Comment by dipenpatel235** [comment]
Yes...but you have used renderplot
We are looking for renderplotly ..

Because we want hover event on that graph value..

And using render plot we get only x, y coordinate using hover ...

**Comment by hadley** [comment]
Then it sounds like a bug with ggplotly.

**Comment by dipenpatel235** [comment]
Yes...then it is bug of ggplotly..

Anyway do u know any solutions using ggplot with pie chart with hover event
?

Thanks...

**Comment by hadley** [comment]
Unfortunately I don't know anything about ggplotly. I'd recommend asking one of the developers - @cpsievert might be able to help you out.

**Comment by dipenpatel235** [comment]
Okay.. thanks.

**Comment by cpsievert** [comment]
ggplotly() doesn't currently support a plot like this, but its on our TODO list
