### ISSUE TITLE
Error in match.fun(FUN) : object 'scale_clone' not found

### ISSUE THREAD

**Issue by achalaacharya** [tidyverse/ggplot2#2007]
I run this code and have been getting the 'object  scale_clone not found ' error. I have tried reinstalling ggplot2 and its dependencies and that did not work. 

ggplot(df.plot, aes(x = decile)) + scale_x_discrete() + 
    scale_y_continuous("Lift") + geom_line(aes(y = train), 
    colour = "red4", linetype = 3, size = 1) + geom_point(aes(y = train), 
    colour = "red4", shape = 18, size = 4) + geom_line(aes(y = test), 
    colour = "palegreen4", linetype = 6, size = 1) + geom_point(aes(y = test), 
    colour = "palegreen4", shape = 18, size = 4) + labs(title = paste(sLabel, 
    "Lift"), x = "Ntile") + theme_bw() + theme(plot.title = element_text(size = 14, 
    face = "bold"))

**Comment by vistep** [comment]
I encountered the same error when I wanted to make a plot of a map which was downloaded with ggmap

**Comment by hadley** [comment]
Unfortunately I can't reproduce the problem.
