### ISSUE TITLE
problem with test for monotonous transformation (secondary axis)?

### ISSUE THREAD

**Issue by hansvancalster** [tidyverse/ggplot2#2008]
```{r}
testdat <- data.frame(x = runif(11),
                      y = seq(0,1,0.1))

# NOT OK
ggplot(data = testdat, aes(x = x, y = y)) + 
  geom_point() + 
  scale_y_continuous(sec.axis = sec_axis(trans = ~ .^0.5))

#  OK
ggplot(data = testdat[testdat$y > 0, ], aes(x = x, y = y)) + 
  geom_point() + 
  scale_y_continuous(sec.axis = sec_axis(trans = ~ .^0.5))
```

**Comment by hadley** [comment]
I've cleaned up the issue title/comment thread to focus on key components of problem. Thanks for the correspondence so far :smile:

**Comment by hadley** [comment]
This is the same root cause as #980 — the problem is that the transformation has to be monotonous over the range of the scales, not the range of the data.   You can work around it by eliminating the scale expansion:

``` r
library(ggplot2)
df <- data.frame(x = runif(5), y = seq(0,1, length = 5))

ggplot(df, aes(x, y)) + 
  scale_y_continuous(
    sec.axis = sec_axis(trans = ~ .^0.5), 
    expand = c(0, 0)
  )
```

![](http://i.imgur.com/JQ7Is3V.png)

**Comment by hansvancalster** [comment]
Thanks! That explains what happened and the work-around is OK.
