### ISSUE TITLE
Legend columns and rows

### ISSUE THREAD

**Issue by DasHammett** [tidyverse/ggplot2#2009]
Hi, 

Customizing legend number of rows and columns as outlined [here](http://docs.ggplot2.org/current/guide_legend.html) is not working as expected.

Reproducible example:
```
library(dplyr)
library(ggplot2)
iris %>%
    ggplot(.,aes(Petal.Length,Sepal.Length,colour=Species))+
       geom_point()+
       guides(col = guide_legend(nrow=1))
```
The code above works as expected

```
library(dplyr)
library(ggplot2)
iris %>%
   ggplot(.,aes(Petal.Length,Sepal.Length,fill=Species))+
      geom_bar(stat="identity")+
      guides(col = guide_legend(nrow=1))
```
The code above does not produce a 1 row legend as expected

Does it have to do with the `geom` used? Or the difference between `fill`and `colour` arguments to `aes()`?

R: 3.3.2
ggplot2: 2.2.1

**Comment by hadley** [comment]
You need to set the guide for the `colour` or `fill` legends as appropriate
