### ISSUE TITLE
update_labels fails for "color" but works for "colour"

### ISSUE THREAD

**Issue by aphalo** [tidyverse/ggplot2#2010]
```{r}
p <-
  ggplot(data = mtcars, aes(x = disp, y = hp, color = factor(cyl), shape = factor(cyl))) +
       geom_point() +
       labs(x = "Engine displacement)",
              y = "Gross horsepower",
             color = "Number of\ncylinders",
             shape = "Number of\ncylinders")

update_labels(p, list(x = "Cilindrada",
                      y = "Potencia bruta (caballos de fuerza)",
                      color = "no. de\ncilindros",
                      shape = "no. de\ncilindros"))
```
![image](https://cloud.githubusercontent.com/assets/2743159/22174026/5827ee2e-dfdc-11e6-91de-8a33b292120e.png)

The output is correct when using "colour" instead of "color" both in `aes()` and `update_labels()`.
This is with ggplot2 2.2.1.9000 (installed minutes ago).

**Comment by hadley** [comment]
Thanks for providing some code that illustrates the problem — it's a great start 😄 However, your code is currently a bit too complicated: there's quite a bit of extraneous stuff in there that doesn't seem directly related to the problem. Can you please try and simplify your example some more? The more minimal you can make the reprex, the faster I can identify the problem and fix it.

**Comment by hadley** [comment]
I've closed this issue due to lack of requested reprex. If you still care about this bug, please open a new issue with a reprex.
