### ISSUE TITLE
annotate with geoms "hline" and "vline" does not add a line

### ISSUE THREAD

**Issue by aphalo** [tidyverse/ggplot2#2011]
I demonstrate the problem here only for `geom_hline`, but the same problem affects `geom_vline`.

```
ggplot(data.frame(x = 0:5, y = 0:5), aes(x, y)) +
     geom_point() +
     annotate(geom = "hline",
                     yintercept = 2.5)
```
![rplot](https://cloud.githubusercontent.com/assets/2743159/22178330/08da8416-e03c-11e6-916a-84462bd66447.png)

Adding an `y` argument produces the expected output, with a warning:
Warning: Ignoring unknown aesthetics: y

```
ggplot(data.frame(x = 0:5, y = 0:5), aes(x, y)) +
    geom_point() +
    annotate(geom = "hline",
                    yintercept = 2.5, y = 2.5)
```
![rplot01](https://cloud.githubusercontent.com/assets/2743159/22178332/0e0c1cd8-e03c-11e6-956e-c0218a7294df.png)

There is something odd going on: when y is present, the hline is plotted at the yintercept position, but the "ignored" unknown aesthetics still affects the scale limits.

```
ggplot(data.frame(x = 0:5, y = 0:5), aes(x, y)) +
     geom_point() +
     annotate(geom = "hline",
                     yintercept = 2.5, y = 100)
```

![rplot02](https://cloud.githubusercontent.com/assets/2743159/22178334/143b6c12-e03c-11e6-99c8-6c73ebf3d06d.png)

ggplot2 2.2.1.9000 installed minutes ago.

Hope this helps diagnose the problem.

**Comment by hadley** [comment]
Yes, unfortunately vline and hline are weird geoms that "self" annotate - just do `geom_hline(yintercept = 2.5)`
