### ISSUE TITLE
coord_flip() seems to lose coord_cartesian() specifications when geom_bar() is present.

### ISSUE THREAD

**Issue by JohnMount** [tidyverse/ggplot2#2013]
The simple graphs that show the behavior may seem silly so I am outlining a use case here.

Use case:

I was building a presentation with a facet-wrap where the units of each facet were different (say classifier measures such as accuracy, AUC, deviance, and so on ).  So I thought the best was to express that was to make sure there was a sale on each facetted element.  The only way I know how to do that is to set the facet_scale to some variation of "free".  I also wanted the presentation with bars left to right, and the way I know how to do that is a coord_flip().

The issue:

I noticed the desired/expected coord_cartesian() effect is lost after the coord_flip() if there is a geom_bar() in the plot.  scale_*_continuous() seems to work (not sure if it does in all cases), and removing the geom_bar() (leaving only the geom_point()) also seems to work.  Below are some simplified graphs (which obviously are not themselves convincing use cases, which is why I explained by use case above).

Examples (with expected behavior, and differing observed behavior):

```
library("ggplot2")

#> packageVersion('ggplot2')
#[1] '2.2.0'

d <- data.frame(x=0.5,
                y=0.7,
                g=c('a','b'), 
                stringsAsFactors = FALSE)

# Example graph that works.
# Expected behavior limits are obeyed:
# plot 1 face_wrap(scale='free') obeys 
# coord_cartesian(ylim=c(0,1), xlim=c(0,1))
# obeys limits as expected.
ggplot(data=d,mapping=aes(x=x,y=y)) +
  geom_point() + geom_bar(stat='identity') + 
  coord_cartesian(ylim=c(0,1), xlim=c(0,1)) +
  facet_wrap(~g, scale='free')

# Very similar graph (differs only in coord_flip()) that
# has unexpected behavior.
# Expected behavior limits are obeyed:
# plot 1 face_wrap(scale='free') obeys 
# coord_cartesian(ylim=c(0,1), xlim=c(0,1)).
# Observe: graph extent does not obey limits.
ggplot(data=d,mapping=aes(x=x,y=y)) +
  geom_point() + geom_bar(stat='identity') + 
  coord_cartesian(ylim=c(0,1), xlim=c(0,1)) +
  facet_wrap(~g, scale='free') + 
  coord_flip()


# graph pair that works
ggplot(data=d,mapping=aes(x=x,y=y)) +
  geom_point() + geom_bar(stat='identity') +  
  scale_x_continuous(limits = c(0, 1)) +
  scale_y_continuous(limits = c(0, 1)) +
  facet_wrap(~g, scale='free')
# related graph that also works.
ggplot(data=d,mapping=aes(x=x,y=y)) +
  geom_point() + geom_bar(stat='identity') + 
  scale_x_continuous(limits = c(0, 1)) +
  scale_y_continuous(limits = c(0, 1)) +
  facet_wrap(~g, scale='free') +
  coord_flip()
```

**Comment by hadley** [comment]
Yes unfortunately the overriding coord knows nothing about the coord it replaces. You can, however, supply `xlim` and `ylim` to `coord_flip()`
