### ISSUE TITLE
ggplot_gtable() throws error "zero-length inputs cannot be mixed with those of non-zero length"

### ISSUE THREAD

**Issue by UweBlock** [tidyverse/ggplot2#2018]
With version 2.2.1 of `ggplot2`, `ggplot_gtable()` throws an error.
Reproducible example:

```R
library(ggplot2)
ggplot_gtable(ggplot(mtcars, aes(mpg, disp)) + geom_point())
#> Error in mapply(FUN = f, ..., SIMPLIFY = FALSE) : 
#>  zero-length inputs cannot be mixed with those of non-zero length
```

**Comment by hadley** [comment]
(Please don't include session info unless it's explicitly asked for, or you've used `reprex::reprex(..., si = TRUE)` to hide it away. I've deleted it from your issue to avoid cluttering up the discussion)

**Comment by hadley** [comment]
I'm fairly certain that it always has - you have to call `ggplot_build()` first.
