### ISSUE TITLE
Issues with extending ggplot2 in a package

### ISSUE THREAD

**Issue by SteveMillard** [tidyverse/ggplot2#2019]
# Tips for Adding ggplot2 Functions to an R Package

1. In the vignette [Extending ggplot2](https://cran.r-project.org/web/packages/ggplot2/vignettes/extending-ggplot2.html), under the definition of the function `stat_chull`, you will see the text:

> (Note that if you are writing this in your own package, you will either need to call `ggplot2::layer()` explicitly, or import the `layer()` function into your package namespace.)

An important bit of information that is not present in the vignette is that if you are writing your own package, you need to call `ggplot2::ggproto` and `ggplot2::Stat` explicitly in the definition of the function `StatChull`.  Also in both your `stat` and `Stat` functions, you will need to call any other ggplot2 functions explicitly that you use, for example, `ggplot2::unit`.

2. When you use `package.skeleton` to start creating your new package, any `Stat` functions you have created will be placed under the **data** folder with the extension _.rda_ instead of under the **R** folder with the extension _.R_.  This is because once a `Stat `function has been created in an R workspace, R considers it a data object instead of a function.  If you just leave things as is, then when you build your package you will get the message that you need to create a help file for the `Stat` data objects that were created, and R will expect you to use the form of the help file that is appropriate for a data object.  To remedy this situation, after you have run `package.skeleton`, delete the `Stat `data objects under the **data** folder, and place the ACSII files that contain the `Stat `function definitions under the **R** directory.  These files should have the name _Statname_.R; for example, the file containing the definition of the function `StatChull `given as an example in the vignette should have the name StatChull.R.

3. You may want to export your `Stat `functions (i.e., using the `export `function in the NAMESPACE file) so that they are visible to the user.  If you do export them, you will have to create help files for them.  If you just want the user to be able to see them so that advanced users can easily see the code but you do not want users in general to know about them and you do not want to write help files for them, you can include the `Stat `functions in the help file _packagename_-internal.Rd, where _packagename_ is the name of your package.

**Comment by hadley** [comment]
You should _never_ use `package.skeleton()` to create a package for just reason. 

I think most of your comments are outside the scope of this vignette. I'm assuming you already understand namespaces, but it might be adding a note on when you should export the Stat __objects__ that you create.

**Comment by SteveMillard** [comment]
Hi Hadley,  Thanks for your reply! 

- It would be great if you could update the vignette with the information in comment 1.  

- Regarding comment 2 and what to use to create a package, I think a lot of people still use `package.skeleton` (I used it because I created my package quite a while ago and had not had any issues with using it until I ran into this problem).  There are numerous posts and books telling people to use `package.skeleton` to create a package.  It would be great if there were well-advertised documentation explaining why one should not use `package.skeleton`.

- Regarding comment 3, the last sentence 
 
> However, currently the way ggplot2 is set up, you cannot export `Stat` functions because they are no longer functions when read into R, but rather data objects.

is not correct.  R was throwing an error but of course it turned out to be my fault and I fixed things so it works fine now.  I will edit the comment.
