### ISSUE TITLE
geom_smooth behaves like geom_path

### ISSUE THREAD

**Issue by izahn** [tidyverse/ggplot2#2028]
I noticed that `geom_smooth` behaves like `geom_path` rather than `geom_line`. For example,

```
library(ggplot2)

ggplot(transform(mtcars, 
                 pred.mpg = predict(lm(mpg ~ poly(hp, 2), 
                                       data = mtcars), 
                                    interval = "confidence"))) + 
  geom_smooth(aes(x = hp,
                  y = pred.mpg.fit, 
                  ymin = pred.mpg.lwr, 
                  ymax = pred.mpg.upr), 
              stat = "identity")
```

produces
![smooth_example](https://cloud.githubusercontent.com/assets/321235/22558177/cab9539e-e93a-11e6-8738-3364e1467fd4.png)

Whereas ordering by the x-axis variable produces the desired result:

```
ggplot(transform(mtcars, 
                 pred.mpg = predict(lm(mpg ~ poly(hp, 2), 
                                       data = mtcars), 
                                    interval = "confidence"))[order(mtcars$hp), ]) + 
  geom_smooth(aes(x = hp,
                  y = pred.mpg.fit, 
                  ymin = pred.mpg.lwr, 
                  ymax = pred.mpg.upr), 
              stat = "identity")
```
![smooth_example2](https://cloud.githubusercontent.com/assets/321235/22558263/12bcc69e-e93b-11e6-9c4a-382a8b90298e.png)

I looked at the `geom_smooth` code, but I don't understand why it behaves this way. It looks like `GeomSmooth` calls `GeomLine`, and `GeomLine` does 

```{r}
  setup_data = function(data, params) {
    data[order(data$PANEL, data$group, data$x), ]
  }
```
so I would have thought ordering the data myself would make no difference.

**Comment by hadley** [comment]
It probably just calls the draw method, not the `setup_data()` method.

**Comment by izahn** [comment]
Thanks, I've submitted https://github.com/tidyverse/ggplot2/pull/2029 to address this.
