### ISSUE TITLE
Warning when plot via plot_grid whith French Accent

### ISSUE THREAD

**Issue by hedjour** [tidyverse/ggplot2#2032]
Hello
When I run this code :
ggplot(data.frame(a=1:5, b = 1:5), aes(a,b)) + geom_point() + labs(title = "é")

No problem
But this one make a Warning :
    toto<- ggplot(data.frame(a=1:5, b = 1:5), aes(a,b)) + geom_point() + labs(title = "é")
    plot_grid(toto)

Why ?
I use this in a knitr file and can not ignore them
Thank you for any help

**Comment by hadley** [comment]
`plot_grid()` isn't a ggplot2 function. I'd suggest filing an issue with whatever package provides that function.

**Comment by hedjour** [comment]
Sorry it's a Cowplot function.
