### ISSUE TITLE
[enhancement] equal position_dodge for incomplete factor combinatios

### ISSUE THREAD

**Issue by DSLituiev** [tidyverse/ggplot2#2033]
It has been often asked on stackoverflow and elsewhere how to plot bars /columns/ boxplots of even width when grouped by `x` and `fill` with some factor combinations missing, e.g. in following figure one wishes to have all bars of the same width:

![uneven width](https://cloud.githubusercontent.com/assets/8426290/22670165/d8baafd4-ec7c-11e6-9683-0fd3730195e5.png)
)

http://stackoverflow.com/questions/11020437/consistent-width-for-geom-bar-in-the-event-of-missing-data
http://stackoverflow.com/questions/15367762/include-space-for-missing-factor-level-used-in-fill-aesthetics-in-geom-boxplot?noredirect=1&lq=1
http://stackoverflow.com/questions/41968652/changing-geom-bar-widths-on-ggplot?noredirect=1&lq=1
http://stackoverflow.com/questions/38101512/the-same-width-of-the-bars-in-geom-barposition-dodge
http://howtodevelop.eu/question/r-ggplot2-changing-geom-bar-widths-on-ggplot,135411

etc, etc...

Some of recipes suggested work pretty well, but I wonder if this should be a default behaviour or at least some of these recipes can be incorporated as, let us say `position_equal_dodge` option?

**Comment by hadley** [comment]
I implemented this 10 days ago 😄 

#1935
