### ISSUE TITLE
cut_number breaks issue

### ISSUE THREAD

**Issue by Pomido** [tidyverse/ggplot2#2039]
Hello.
I'm trying to make my own function which is similar to cut_number but I cant understand what actually 'breaks' is and how it works.
Could you please explain or provide some reference? Thx.
```
cut_number <- function(x, n = NULL, ...) {
  brk <- breaks(x, "n", n)
  if (anyDuplicated(brk))
    stop("Insufficient data values to produce ", n, " bins.", call. = FALSE)
  cut(x, brk , include.lowest = TRUE, ...)
}
```

**Comment by hadley** [comment]
Please ask questions on the ggplot2 mailing list.
