### ISSUE TITLE
Convert contributing.md to pull request template

### ISSUE THREAD

**Issue by hadley** [tidyverse/ggplot2#2044]
Convert each top-level task into a to do list

<https://github.com/blog/2111-issue-and-pull-request-templates>

**Comment by phoebewong** [comment]
Hi @hadley, I'm interested in working on this. Can you further elaborate on the conversion that you are looking for? Did you mean to add a pull request template section on contributing.md?

https://help.github.com/articles/creating-a-pull-request-template-for-your-repository/

**Comment by hadley** [comment]
@phoebewong yes, exactly!  Would you be interested in doing a PR along these lines?

**Comment by hadley** [comment]
I'm going to close this for now - we'll tackle in a tidyverse wide way later in the year.
