### ISSUE TITLE
mapping behaviour of complex columns, i.e. sf geometry

### ISSUE THREAD

**Issue by mdsumner** [tidyverse/ggplot2#2045]
Using `sf` geometry column for a mapping has varied errors/warnings, and similar for other list columns. 

```R
library(sf)
nc <- sf::st_read(system.file("shape/nc.shp", package = "sf"), quiet = TRUE)
ggplot(nc, aes(fill = geometry)) + geom_sf()
#Error in grDevices::col2rgb(colour, TRUE) : 
 # invalid color name 'list(list(c(-81.4727554321289, -81.5408401489258, -81.5619812011719, #-81.6330642700195, -81.7410736083984, -81.6982803344727, -81.7027969360352, 
#...
```

```R
ggplot(nc, aes(colour = geometry)) + geom_sf()
#There were 50 or more warnings (use warnings() to see the first 50)
#> warnings()
#Warning messages:
#1: In grid.Call.graphics(L_path, x$x, x$y, index, switch(x$rule,  ... :
 # supplied color is neither numeric nor character
```

Should ggplot2 detect these cases and warn/stop? Are there other cases where a list-col could be used in a mapping?  

Note that the active "sf_column" attribute name is accessed with `attr(nc, "sf_column")`, also there's potential future changes regarding multiple geometry columns:  https://github.com/edzer/sfr/issues/183

**Comment by hadley** [comment]
I think this is currently out of scope. It's unusual, and it's not clear to me how/where/ we'd fix it.
