### ISSUE TITLE
Suggestion: glmmTMB compatibility

### ISSUE THREAD

**Issue by MichaelRatajczak** [tidyverse/ggplot2#2046]
Hi, 

There is a new package, currently in beta, used for generalised linear mixed effects modelling -- glmmTMB (https://github.com/glmmTMB/glmmTMB). I was wondering if you could make ggplot2 compatible with it?

Kind regards,
Michael

**Comment by hadley** [comment]
I don't really understand what you want, but a package can supply it's own `fortify()` etc methods.  If every package needed me to add ggplot2 support, it would never happen.
