### ISSUE TITLE
`geom_bar` inconsistently handling date values

### ISSUE THREAD

**Issue by nteetor** [tidyverse/ggplot2#2047]
Description
===========

There are unexpected plot results when specifying the fill aesthetic in `geom_bar` when the `x` aesthetic is a Date or POSIXct value. Below I have listed examples using Date and POSIXct objects, respectively. Similar data represented with these two classes results in rather different plots, see below.

Date Examples
=============

The following examples use Date objects produced with `make_date()`.

1 month with 2 fill values
--------------------------

In this example January fill values are TRUE and FALSE, February and March fill values are only FALSE.

``` r
library(ggplot2)
library(lubridate)

d1 <- data.frame(
  dates = rep(make_date(year = 2017, month = 1:3), each = 2),
  highlight = c(TRUE, FALSE, FALSE, FALSE, FALSE, FALSE)
)

# this unexpectedly changes the width of one of January's bars
ggplot(d1, aes(x = dates)) +
  geom_bar(aes(fill = highlight))
```

    ## Warning: position_stack requires non-overlapping x intervals

![unnamed-chunk-1-1](https://cloud.githubusercontent.com/assets/3228369/22983239/85c7973e-f36f-11e6-9678-979aa5a9da1a.png)

1 month with distinct fill value
--------------------------------

In this example January fill values are only TRUE, both February and March are only FALSE.

``` r
library(ggplot2)
library(lubridate)

d2 <- data.frame(
  dates = make_date(year = 2017, month = 1:3),
  highlight = c(TRUE, FALSE, FALSE)
)

# only one bar for January, but as above it is thin
ggplot(d2, aes(x = dates)) +
  geom_bar(aes(fill = highlight))
```

![unnamed-chunk-2-1](https://cloud.githubusercontent.com/assets/3228369/22983226/7f9afcde-f36f-11e6-9013-0d726fe40db1.png)

3+ fill values
--------------

This example introduces a third fill value to the highlight column.

``` r
library(ggplot2)
library(lubridate)

d3 <- data.frame(
  dates = make_date(year = 2017, month = 1:3),
  highlight = c(1, 2, 3)
)

# all bars are now equally thin, additional breaks added to x-axis
ggplot(d3, aes(x = dates)) +
  geom_bar(aes(fill = factor(highlight)))
```

![unnamed-chunk-3-1](https://cloud.githubusercontent.com/assets/3228369/22983219/79dfa8f8-f36f-11e6-9096-281dbf9f3a29.png)

POSIXct Examples
================

The following examples use POSIXct objects produced with `make_datetime()`.

1 month with distinct fill value
--------------------------------

In this example, when January fill is only FALSE, February and March are only TRUE, the January bar does not show. The bar may be too thin to see.

``` r
library(ggplot2)
library(lubridate)

d4 <- data.frame(
  datetimes = make_datetime(year = 2017, month = 1:3),
  highlight = c(TRUE, FALSE, FALSE)
)

# January bar is no longer thin, instead missing 
ggplot(d4, aes(x = datetimes)) +
  geom_bar(aes(fill = highlight))
```

![unnamed-chunk-4-1](https://cloud.githubusercontent.com/assets/3228369/22983215/72d436aa-f36f-11e6-910a-77da404f6447.png)

3+ fill values
--------------

Similar the 3+ fill value example above, however in this example the bars are not equally thin, they are all missing.

``` r
library(ggplot2)
library(lubridate)

d5 <- data.frame(
  datetimes = make_datetime(year = 2017, month = 1:3),
  highlight = c(1, 2, 3)
)

# no bars
ggplot(d5, aes(x = datetimes)) +
  geom_bar(aes(fill = factor(highlight)))
```

![unnamed-chunk-5-1](https://cloud.githubusercontent.com/assets/3228369/22983198/6403b560-f36f-11e6-904f-eaacd4e36319.png)

Conclusion
==========

The `geom_bar` fill aesthetic is not properly handling Date and POSIXct objects. I am not weighing in yet on whether bars ought to be thin or wide, rather I am hoping to iron out `geom_bar` so Date and POSIXct values are handled consistently. I hope I have not misunderstood how `geom_bar` is intended to handle date values.

I will look under the hood to try and identify the problem. For now I am not sure of a work around.

**Comment by hadley** [comment]
Would you mind consistently using `lubridate::make_date()` and `lubridate::make_datetime()` in your examples? That will make the differences easier to see.

**Comment by nteetor** [comment]
Sure thing, I will start making those changes now.

**Comment by nteetor** [comment]
It occurred to me GitHub may not notify when a comment is updated. 

The examples have been updated. Let me know if any other changes would be helpful.

**Comment by hadley** [comment]
Looks good - thanks.  In the first plot, also note that the gap between the bars is not constant.

(I've deleted the comment thread since it's now no longer relevant)

**Comment by nteetor** [comment]
I started poking around and stumbled upon another case. This also has to do with the first plot's inconsistent gaps you pointed out. 

```R
library(ggplot2)
library(lubridate)

d6 <- data.frame(
  dates = rep(make_date(year = 2017, month = 1:3), each = 2),
  highlight = c(TRUE, FALSE, TRUE, FALSE, FALSE, FALSE)
)

ggplot(d6, aes(x = dates)) +
  geom_bar(aes(fill = highlight))
```

![unnamed-chunk-4-1](https://cloud.githubusercontent.com/assets/3228369/23080534/14a1e094-f51f-11e6-8cbd-8a1dbeb9c42b.png)

**Comment by jensenerik0** [comment]
I think I have a minimal example of the same bug that doesn't use dates.

```
library(ggplot2)

x <- c(0, 0, 2, 1)
x_shift <- x+1
y_bool <- c(TRUE, TRUE, TRUE, FALSE)

df <- data.frame(
  x, x_shift, y_bool
  )

#This plot returns:
#Warning message:
#position_stack requires non-overlapping x intervals
ggplot(data=df,aes(x=x,fill=y_bool))+geom_bar()
```
![image](https://user-images.githubusercontent.com/22398742/28879434-24dbf534-7770-11e7-8fc9-80ba0a38fda6.png)

```
#This plot gives no error and looks as expected
ggplot(data=df,aes(x=x_shift,fill=y_bool))+geom_bar()
```
![image](https://user-images.githubusercontent.com/22398742/28879443-2dd2291a-7770-11e7-99cd-dedef62bddf7.png)

Manually setting "width" in geom_bar can make the issue appear or disappear in both cases.

**Comment by hadley** [comment]
Minimal reprex:

``` r
library(ggplot2)

df <- data.frame(
  x = c(0, 0, 2, 1), 
  fill = c(TRUE, TRUE, TRUE, FALSE)
)

ggplot(df, aes(x, fill = fill)) + geom_bar()
#> Warning: position_stack requires non-overlapping x intervals
```

![](https://i.imgur.com/kqMYlst.png)

``` r
ggplot(df, aes(x, fill = fill)) + geom_bar(width = 0.9)
```

![](https://i.imgur.com/aN8AV4G.png)


I think the root cause is that `stat_count()` is computing the width based on the resolution of an individual group rather than the full dataset.

**Comment by thibautjombart** [comment]
For what it is worth, this bugs results in issues with the RECON package [incidence](http://www.repidemicsconsortium.org/incidence/):

``` r

library(incidence)

set.seed(1)

dates <- as.Date("2018-01-01") + sample(1:20, 100, replace = TRUE)
dates_posix <- as.POSIXct(dates)

plot(incidence(dates))
```

![](https://i.imgur.com/NH0N2xP.png)

``` r

plot(incidence(dates_posix))
```

![](https://i.imgur.com/ZsyEVWn.png)

**Comment by hadley** [comment]
To be clear, are you stating that this is not a problem with the released version of ggplot2?

**Comment by woodwards** [comment]
It seem to be an issue with geom_col and geom_bar, not dates or facets as such.

``` r
library(ggplot2)
ggplot(mtcars) +
  geom_col(mapping=aes(x=disp, y=mpg)) +
  geom_point(mapping=aes(x=disp, y=mpg))
```

![](https://i.imgur.com/QDgac51.png)

Created on 2018-08-08 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by peterfine** [comment]
This problem @hadley, as per you example in https://github.com/tidyverse/ggplot2/issues/2047#issuecomment-387900464 and per my own difficulty in plotting similar data, does still exist in ggplot2 3.2.1

**Comment by avallecam** [comment]
This issue have return in the new released version of ggplot 3.3.0 available in CRAN

![image](https://user-images.githubusercontent.com/21230390/76797036-a8a17700-679a-11ea-8429-169652eda3ff.png)

> 
> 
> For what it is worth, this bugs results in issues with the RECON package [incidence](http://www.repidemicsconsortium.org/incidence/):
> 
> ```r
> library(incidence)
> 
> set.seed(1)
> 
> dates <- as.Date("2018-01-01") + sample(1:20, 100, replace = TRUE)
> dates_posix <- as.POSIXct(dates)
> 
> plot(incidence(dates))
> ```
> 
> ![](https://camo.githubusercontent.com/0895bff1fb42a16450fb7f2b191c2de8d5848928/68747470733a2f2f692e696d6775722e636f6d2f4e48304e3278502e706e67)
>

**Comment by hadley** [comment]
@avallecam that's a different problem. Please open a new issue with a reprex.

**Comment by thibautjombart** [comment]
I think it is indeed another issue. I have posted a reprex already in [this issue](https://github.com/tidyverse/ggplot2/issues/3873).

**Comment by stragu** [comment]
The report above, which Kara closed, is a duplicate.

So, moving forward: how could the `compute_group` element of the `stat_count` ggproto take the whole original vector rather than just the values of the group currently handled, in order to compute the bar's `width`?

https://github.com/tidyverse/ggplot2/blob/ac2b5a7bb460179e0cc8c4b3204795317dcfb9b8/R/stat-count.r#L76

**Comment by thomasp85** [comment]
The basic issue here is that the group aesthetic is derived from fill meaning that the resolution of the second group is computed to be much higher... Setting `group` fixes this

``` r
library(ggplot2)

df <- data.frame(
  x = c(0, 0, 2, 1), 
  fill = c(TRUE, TRUE, TRUE, FALSE)
)

ggplot(df, aes(x, fill = fill, group = x)) + geom_bar()
```

![](https://i.imgur.com/lbXJwNT.png)

<sup>Created on 2021-04-13 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

I think we can safely move the `resolution(x)` call into setup_params to fix this, so that default width is group-independent, but maybe someone is relying on this behaviour?

**Comment by thomasp85** [comment]
hmm, actually... a question then arrises on whether the width should be calculated per-panel or globally.
