### ISSUE TITLE
Throw warning when using fixed coordinates with free scales?

### ISSUE THREAD

**Issue by cpsievert** [tidyverse/ggplot2#2049]
The `coord_fixed()` bit in the example below is silently ignored. 

```r
library(ggplot2)
ggplot(mtcars) + 
  geom_point(aes(wt, mpg)) + 
  facet_wrap(~vs, scales = "free") + 
  coord_fixed()
```

I'm not sure whether ggplot2 should allow for fixed coordinates in conjunction with free scales, but assuming the answer is "no", maybe we should add a message/warning/error?

**Comment by hadley** [comment]
Want to have a go at a PR? I think free scales probably should default to a warning, except for coords where it words (IIRC only `coord_cartesian()` and `coord_flip()`)
