### ISSUE TITLE
'vjust' in theme() doesn't work properly for angled axis text

### ISSUE THREAD

**Issue by domiden** [tidyverse/ggplot2#2050]
First of all, many thanks for your great package!

# Description
There are unexpected plot results when specifying the x-axis text in `theme()` when the text angle is 90°. The axis text don't seems to centre vertically regardless of the default setting (`vjust = .5`). This behaviour seems to happen independently from horizontal justification, however, not from the position of the axis. This might be a bug. Below I add an example.

I use the latest version of the ggplot2 package (-> 2.2.1).

# Data Example
```r
# Create a distance matrix from a random sampling of iris dataset
dist.tidy <- 
  data.frame(
    Sepal.Length = c(6.3, 6.3, 6.4, 6.2, 6.3, 5.5, 5.4, 7.1, 6.4, 4.8),
    row.names = c("virginica.1", "setosa.2", "virginica.3", "virginica.4", 
                  "versicolor.5", "setosa.6", "versicolor.7", "versicolor.8", 
                  "versicolor.9", "setosa.10")) %>%
  dist() %>%
  broom::tidy()
```

# Plot Example
```r
library(ggplot2)

# Generate a sort of matrix plot using 'geom_point'
p <- dist.tidy %>%
  ggplot(aes(x = item2, y = item1)) +
  geom_point(aes(colour = distance, size = distance))
p
```

## Axis position at the bottom (Default)
```r
# Seems fine to me.
p <- p + theme(axis.text.x = element_text(angle = 90, hjust = 1, debug = TRUE))
p
```
![test-plot-axis-text-90degree-vjust-position-bottom](https://cloud.githubusercontent.com/assets/24540355/23174034/613382ac-f85b-11e6-8302-4dce05d13f64.png)

## Axis position at the top
```r
# The default is 'vjust = 0.5'. However, the setting appears to be 'vjust = 0' 
# when setting the angle to 90° . 'hjust' seems to have no influence on 'vjust'.
p <- p + scale_x_discrete(position = "top") +
  theme(axis.text.x = element_text(angle = 90, hjust = 0, debug = TRUE))
p
```
![test-plot-axis-text-90degree-vjust](https://cloud.githubusercontent.com/assets/24540355/23173554/d299fc02-f859-11e6-9656-0e2cb26d2bfb.png)

This is my first bug report. So, hopefully, I didn't miss anything.

**Comment by domiden** [comment]
There is a similar report (#1878)—I missed—describing the same issue. I understand this issue is an inconvenience.

As @thomasp85 explained:
> This is not a bug per se, but rather an inconvenience fostered by a wish for both theme inheritance and nice defaults...
`axis.text.x.top` inherits from `axis.text.x`, but in order to look good by default it sets margin and just explicitly deferent from `axis.text.x` and these are thus not inherited when `axis.text.x` is set in a call to `theme()`.

However, I think there is quite a number of people like me who struggling with the same problem. Wouldn’t it be preferable to change the default behaviour for this setting, so it would react comparable to the bottom position?

**Comment by domiden** [comment]
There is a similar report (#1878) —I missed the day before— describing the same issue. So, this issue report can be closed. Thanks.

**Comment by apuhegde** [comment]
Having the same issue with the bottom x-axis as well. R version 3.4.3.
