### ISSUE TITLE
Proportion in geom_bar() with no fill

### ISSUE THREAD

**Issue by elinw** [tidyverse/ggplot2#2051]
I'm not sure if this a bug in the code or a lack of clarity in the documentation.

The documentation of geom_bar() indicates that there are two calculated values "count"  and "prop".   However, when making a bar plot with just one variable it seems to not be possible to use `..prop..` unless you use a workaround to create a single stacked bar with the variable as fill. 

This is what I expected to be able to use:  
`ggplot(mpg, aes(x=class)) + geom_bar(aes(y = ..prop..))`

to create a plot like this:  

`ggplot(mpg, aes(x=class)) + geom_bar(aes(y = (..count..)/sum(..count..)))`

I believe that when there is no fill, the prop calculation is using the n for each attribute as the denominator rather than the n for all of x. Hence the proportions are always 1.00.   

Examples 4, 6 and 8 below are the only ones with correct proportions. 

```r
# 1. Basic bar
ggplot(mpg, aes(x=class)) + geom_bar()
# 2. Explicitly request count
ggplot(mpg, aes(x=class)) + geom_bar(aes(y = ..count..))
# 3. Explicitly request prop
ggplot(mpg, aes(x=class)) + geom_bar(aes(y = ..prop..))
# 4. Calculate prop, what we are aiming for
ggplot(mpg, aes(x=class)) + geom_bar(aes(y = (..count..)/sum(..count..)))
# 5. Pretend that there is an x factor and the y is the fill stacked
ggplot(mpg, aes(x=factor(0))) + geom_bar(aes(y = ..prop.., fill=class))
# 6. Pretend there is an x factor, y is fill, position fill, correct calculations
ggplot(mpg, aes(x=factor(0))) + geom_bar(aes(fill=class), position ="fill")
# 7. Pretend that there is an x factor and y is the fill dodge
ggplot(mpg, aes(x=factor(0))) + geom_bar(aes(y = ..prop.., fill=class), position ="dodge")
# 8. Aes with fill, but request prop
ggplot(mpg, aes(x=factor(0))) + geom_bar(aes(fill=class, y = ..prop..))

```
I've seen this kind of plot requested on Stackoverflow so I know I'm not the only one who ever needs it, but I think that just clarifying the documentation would be good.  I'm happy to work on a PR if that would be helpful.

I do think that probably in principle, the stack _is_ the preferred visualization when showing percents that add up to 100.

**Comment by hadley** [comment]
It's a group wise proportion, so it's likely you'll need to set the group aesthetic to override the default.

**Comment by elinw** [comment]
Yes, thank you you are correct, this works

`ggplot(mpg, aes(class)) + geom_bar(aes(group=factor(0), y = ..prop..))`
