### ISSUE TITLE
geom_bar stacking order change messes up horizontal layouts

### ISSUE THREAD

**Issue by pbreheny** [tidyverse/ggplot2#2053]
The ordering for stacked bar charts was changed in version 2.2 so that it matches the legend:

```
df <- data.frame(x=c(1,1,1,2,2,2,3,3,3),
                 y=c(1,2,3,4,5,6,7,8,9),
                 z=c('a','b','c','a','b','c','a','b','c'))
ggplot(df) + geom_bar(aes(x, y, fill=z), stat="identity")
```
![a](https://cloud.githubusercontent.com/assets/1858089/23238687/b9d869f4-f928-11e6-9dba-ae11972d51f6.png)

We can both agree that this is better.  However, when this switch was made, it now screws up the ordering for horizontal layouts:

```
ggplot(df) + geom_bar(aes(x, y, fill=z), stat="identity") +
  coord_flip() + theme(legend.position="top")
```
![b](https://cloud.githubusercontent.com/assets/1858089/23238713/e6750b84-f928-11e6-979a-79d16171907b.png)

This used to work correctly (chart matched legend) and now it doesn't.  Not the most important problem in the world, but ideally, the ordering would be matched correctly in both cases.

**Comment by hadley** [comment]
Use `position = position_stack(reverse = TRUE)`

**Comment by pbreheny** [comment]
Great, thanks!
