### ISSUE TITLE
geom_histogram has wrong counts

### ISSUE THREAD

**Issue by RemmyGuo** [tidyverse/ggplot2#2054]
First, forgive me for my  poor English. I will try my best to describe accurately.
The issue is when I use geom_histogram to draw a  histogram, I find the count of some bins is wrong, and this problem is not appear in ggplot2.1.0.1. I will give the code which can reproduct the issue.
This HTML is other people talk about problems may have some relationship with my issue.

Except for your reply, thank you so much!
```r

library(ggplot2)
library(plotyly)
set.seed(1234)
df <- data.frame(var1 = sample(1:100, 20))

p <- ggplot(df, aes(var1)) + geom_histogram(aes(y = ..count..), binwidth = 5,color = 'white') 
ggplotly(p)
# the count of (10,15] should be 0, but in the graph it is 1.why?
```

**Comment by hadley** [comment]
I'm not sure I understand the problem - the bars in that histogram are centered around 5. Maybe you want `origin = 0`?
