### ISSUE TITLE
theme_set() breaks theme_void() if axis.text.x or axis.text.y is modified

### ISSUE THREAD

**Issue by crsh** [tidyverse/ggplot2#2058]
Hi, I'm having trouble with one of my custom themes since a recent update (I have tried with version 2.2.1 and the current snapshot from this repository). When I change the settings of `axis.text.x` or 
`axis.text.y` in a theme that is set as default using `theme_set()`, `theme_void()` throws an error. This causes trouble when I try to use `cowplot::plot_grid()` (see my [previous bug report](https://github.com/wilkelab/cowplot/issues/60)).

```r
library("ggplot2")

df <- data.frame(
    gp = factor(rep(letters[1:3], each = 10))
    , y = rnorm(30)
)
theme_set(theme_classic() + theme(axis.text.x = element_text()))

test <- ggplot(df, aes(gp, y)) + geom_point()

test # works
test + theme_void() # doesn't work
```

```
Error in element_grob.element_text(el, ...) : 
  Text element requires non-NULL value for 'angle'.
```

If I set `angle` and `debug` in `element_text()` it works.

```r
test + theme_void() + theme(axis.text.x = element_text(angle = 0, debug = FALSE)) # works
```

Is this intended behavior?

**Comment by thomasp85** [comment]
I don't really think this is a bug - you need to specify the angle the text should be written in. Usually this is derived from the root text element but since this is `element_blank` in `theme_void()` you'll need to specify it when you modify child elements...

**Comment by crsh** [comment]
What is very surprising to me is that I don't make any changes to `theme_void()`. I modify `theme_classic()` and set that modified version as default. Still this causes problems with `theme_void()`. I came across this behavior working with a custom theme of my own where I modify axis text margins. I don't make any changes to the angle and I don't  touch `theme_void()`.

Moreover, if I nevertheless set `angle` to any value, I get the following error

```
Error in if (debug) { : Argument has length 0
```

which is why in my continued example I also set `debug = FALSE`.

Also, I played a little more with this and when I make changes to, e.g., `axis.title.x` I get the same angle-error, but when I do set `angle` explicitly I get a new error:

```r
theme_set(theme_classic() + theme(axis.title.x = element_text(angle = 0)))

test <- ggplot(df, aes(gp, y)) + geom_point()

test # works
test + theme_void() # doesn't work
```

```
Error in unit(rep(xp, n), "npc") : 'x' and 'units' must have length > 0
```

**Comment by has2k1** [comment]
I think it is a bug. `theme_void()` is a `complete` theme so whatever the default theme (the one set with `theme_set`) is should not affect it.

**Comment by thomasp85** [comment]
Yeah, I can see that now. I'll look into it

**Comment by gilliganondata** [comment]
I've run into this a couple of times and wind up back on this issue each time. The thing I keep forgetting is that this does _not_ cause an issue if simply `axis.title()` is set. It only seems to come into play (for me) when I'm trying to set `axis.text.x()` or `axis.text.y()` explicitly. With that in mind, I've been able to find various workarounds.

**Comment by crsh** [comment]
Hooray for the fix. Thanks!
