### ISSUE TITLE
the xlim/ylim ranges in stat_binhex are sometimes exclusive instead of inclusive

### ISSUE THREAD

**Issue by DavyLandman** [tidyverse/ggplot2#2061]
I've been loving ggplot and the hexogonal plots for quite a while, but recently I looked back at a scatterplot of my data and noticed a line close to the x-axis of my chart, that wasn't there in the hexogonal plot of it.

Some trails led me to the insight that the ylim and xlim ranges can have quite an unpredictable impact on which data is plotted. Similarly the size and ratio of the plot.

I understand that the size and ratio has an effect on the size of the hexagons, yet it shouldn't change the limits.

Here are some examples of the confusion:

```R
set.seed(42)
dt4 = data.frame(
  x = c(rep(1, 100), rnorm(10000, mean = 10, sd = 2), rep(18,100)),
  y = c(rep(2, 100), rnorm(10000, mean = 10, sd = 2), rep(19,100))
)
```

some random data with two points in the corners

```R
hex_base = ggplot(dt4, aes(x=x, y=y)) +
  geom_hex() +
  theme_bw() +
  scale_fill_gradientn(colours=c("grey90","black"))

png(filename = "/tmp/nolimits.png", width=600, height=480)
hex_base
dev.off()
```

the base ggplot figure, which looks like this:

![nolimits](https://cloud.githubusercontent.com/assets/179603/23376469/74d16768-fd2c-11e6-9da8-ec224b6f60bc.png)

```R
png(filename = "/tmp/withxlim.png", width=600, height=480)
hex_base + xlim(1,18)
dev.off()
```

Changing the xlim to still fit the data, we loose the bottom left point:

![withxlim](https://cloud.githubusercontent.com/assets/179603/23376549/cd71219c-fd2c-11e6-9c4c-96ddaf500af8.png)
 
Okay, maybe the xlim is not inclusive as we would expect.

```R
png(filename = "/tmp/withxlim2.png", width=600, height=480)
hex_base +
  xlim(0,18)
dev.off()
```

now we loose the top right point:

![withxlim2](https://cloud.githubusercontent.com/assets/179603/23376578/ea7448d2-fd2c-11e6-8c1a-1edd702d695b.png)

let's look at ylim.

```R
png(filename = "/tmp/withylim.png", width=600, height=480)
hex_base +
  ylim(2,19) 
dev.off()
```

okay as expected, both points still showup:

![withylim](https://cloud.githubusercontent.com/assets/179603/23376612/0a85706a-fd2d-11e6-82d3-4da6c419db79.png)

what you most likely use:

```R
png(filename = "/tmp/withxylim.png", width=600, height=480)
hex_base +
  xlim(1,18) +
  ylim(2,19) 
dev.off()
```

again, the left bottom point drops out:

![withxylim](https://cloud.githubusercontent.com/assets/179603/23376633/252982f8-fd2d-11e6-8464-b23498bfbab8.png)

```R
png(filename = "/tmp/withxylim2.png", width=600, height=480)
hex_base +
  xlim(0,18) +
  ylim(2,19) 
dev.off()
```

and again, we switch to dropping the right top point.
![withxylim2](https://cloud.githubusercontent.com/assets/179603/23376676/578ef5b6-fd2d-11e6-8269-cd6c5b1defab.png)

with different random data set's i've seen the exact opposite, the `ylim` is dropping points around the edges. and it can't always be solved by making the ranges wider.

Now for reference, let's look at the underlying function `hexbin`:

```R
png(filename="/tmp/manual.png", width=600, height=480)
hexbinplot(y~x,dt4, xlim=c(1,18))
dev.off()
```
okay, that's a very  literal limit, but at least it's consistent.

![manual2](https://cloud.githubusercontent.com/assets/179603/23376739/936b8b1c-fd2d-11e6-804d-aa4cbfc4ed2f.png)

another work around is to use subset.

```R
png(filename="/tmp/manual.png", width=600, height=480)
hexbinplot(y~x,subset(dt4, x >= 1 & x <= 18 & y >= 2 & y <= 19))
dev.off()
```

![manual](https://cloud.githubusercontent.com/assets/179603/23376784/c68ab784-fd2d-11e6-827a-c4113886a5e3.png)

I hope this is not a too long/wordy issue, but I think this is at the very least  confusing behaviour.

**Comment by hadley** [comment]
The limits are applied to the raw data, not the hexagons. You might want `coord_cartesian()` instead.

**Comment by DavyLandman** [comment]
that's why I included the example with the hexbinplot called directly with a subset.

**Comment by DavyLandman** [comment]
there is some interaction with the calls to hexbin, for example the same limits but with geom_point:

```
png(filename = "/tmp/geompoint.png", width=600, height=480)
ggplot(dt4, aes(x=x, y=y)) +
  geom_point(pch=20) + 
  theme_bw() +
  xlim(1,18) +
  ylim(2,19)+
  scale_fill_gradientn(colours=c("grey90","black"))
dev.off()
```
![geompoint](https://cloud.githubusercontent.com/assets/179603/23377478/7137ea24-fd30-11e6-8697-2af68148018e.png)

**Comment by hadley** [comment]
Oh maybe the limits get applied to both the raw data and the hexes. Regardless, the solution is likely to be `coord_cartesian`

**Comment by DavyLandman** [comment]
the reason I didn't use `coord_cartesian` is that it doesn't work if you want to zoom into a part of the data. as you get the hexbins on the full data, and only after calculating the hexagonals is the scale limited.

**Comment by hadley** [comment]
Yeah, in that case you're better off subsetting the data. Unfortunately this is a suboptimal design choice that would be too hard to change now
