### ISSUE TITLE
geom_raster() not rendering correctly under 3.3.2

### ISSUE THREAD

**Issue by jarrod-dalton** [tidyverse/ggplot2#2064]
Running R 3.3.2 on RStudio 1.0.136, and ggplot2 2.10.0

I just tried to run a stock `geom_raster()` example from http://docs.ggplot2.org/current/geom_tile.html, and the plot is not rendering correctly. 

```r
library(ggplot2)

df <- expand.grid(x = 0:5, y = 0:5)
df$z <- runif(nrow(df))
# default is compatible with geom_tile()
ggplot(df, aes(x, y, fill = z)) + geom_raster()

```

![image](https://cloud.githubusercontent.com/assets/11472793/23562595/22dccce4-0011-11e7-8208-500e4d6a4d1b.png)

**Comment by hadley** [comment]
Works for me. Something is probably misconfigured in your R session/graphics viewer.
