### ISSUE TITLE
Cannot remove panel.grid (graticules) from ggplot + geom_sf()

### ISSUE THREAD

**Issue by tiernanmartin** [tidyverse/ggplot2#2071]
I would like to completely remove the graticule lines from my plot, but it is unclear which argument in `theme()` controls the graticule lines.

#### Reprex
``` r
library(sf) 
library(ggplot2)

nc = st_read(system.file("gpkg/nc.gpkg", package = "sf")) 

ggplot(nc) + 
  geom_sf(data = nc, aes(fill = AREA)) + 
  coord_sf(crs = st_crs(nc)) + 
  theme(
    panel.ontop = TRUE,   ## Note: this is to make the panel grid visible in this example
    panel.grid = element_blank(), 
    line = element_blank(), 
    rect = element_blank(), 
    text = element_blank(), 
    plot.background = element_rect(fill = "black"))
```
![](http://i.imgur.com/TvwG19Z.png)

**Comment by LucasPuente** [comment]
Looks like a bug. 

One trick I discovered to solve this is to set the color of the `panel.grid.major` equal to the background color. In your example, this would mean `+  theme(panel.grid.major = element_line(colour = "black"))`.

I call this a bug because `theme(panel.grid.major = element_blank())` is not working.

**Comment by mdsumner** [comment]
Another use-case where it's important not to have the graticule is when the crs is NA. Currently there's a test for `is.na(crs)` in `CoordSf` that can fails, which could be replaced with 

```R
identical(sf::NA_crs_, crs)
```

I started a PR but can't test the outcome of this fix fully since the graticule logic doesn't work. An example is

```R
nc <- sf::st_read(system.file("shape/nc.shp", package = "sf"), quiet = TRUE)

nc_na <- sf::st_set_crs(nc, NA)
ggplot(nc_na) + coord_sf()
#Error in if (st_is_longlat(crs)) bb = trim_bb(bb, margin) : 
#  missing value where TRUE/FALSE needed

```

Happy to help explore more and create examples if that helps but the overall solution escapes me atm.

**Comment by tiernanmartin** [comment]
@LucasPuente or perhaps  `+ theme(panel.grid.major = element_line(colour = 'transparent'))` - this would allow the plot to be saved without any panel background.

**Comment by jsta** [comment]
In the interest of search engine results, I figured I would describe what I think is a related graticule drawing error:

> Error in apply(dxdy, 1, function(x) atan2(x[2], x[1]) * 180/pi) : 
  dim(X) must have a positive length

Plots fail to draw when using a UTM projection and I think I've tracked it down to the graticule drawing routines. This map may be a clue.

![](https://i.imgur.com/BWseL55.png)

**Comment by hadley** [comment]
@jsta can you please file a minimal reprex in a new issue? I will delete the comment here to keep the discussion focussed.

**Comment by edzer** [comment]
This requires `coord_sf(datum = NA)`, e.g.
```r
library(sf) 
library(ggplot2)

nc = st_read(system.file("gpkg/nc.gpkg", package = "sf")) 

ggplot(nc) + 
  geom_sf(data = nc, aes(fill = AREA)) + 
  coord_sf(crs = st_crs(nc), datum = NA) + 
  theme(
    panel.ontop = TRUE,   ## Note: this is to make the panel grid visible in this example
    panel.grid = element_blank(), 
    line = element_blank(), 
    rect = element_blank(), 
    text = element_blank(), 
    plot.background = element_rect(fill = "black"))
```
and still gives two warnings that need to be solved in `ggplot2`.
![x](https://user-images.githubusercontent.com/520851/28733572-0f1c6d46-73dd-11e7-9c63-0feaba7b5549.png)

**Comment by edzer** [comment]
https://github.com/r-spatial/sf/commit/812cdff1ed299513bebb3c8101892d7889efd4ec now removes the need to patch ggplot2.

**Comment by jsta** [comment]
Note that the solution provided above will not hide the graticules if `coord_sf` is called **before** `geom_sf`.
