### ISSUE TITLE
Secondary axis doesn't work with coord_polar

### ISSUE THREAD

**Issue by Henrik-P** [tidyverse/ggplot2#2072]
When adding a secondary axis (`dup_axis` / `sec_axis`) to a plot with polar coordinates (`coord_polar`), the labels and the tick marks doesn't show up. The `name` appears though. 

```r
ggplot(mtcars, aes(x = factor(cyl))) +
  geom_bar() +
  coord_polar() +
  scale_y_continuous(sec.axis = dup_axis())

ggplot(mtcars, aes(x = factor(cyl))) +
  geom_bar() +
  coord_polar() +
  scale_y_continuous(sec.axis = sec_axis(~. * 0.1, name = "sec count"))
```
-----
See also [this post on SO](http://stackoverflow.com/questions/42732144/ggplot2-v2-21-9-sec-axis-in-polar-plot).

**Comment by thomasp85** [comment]
Can you try this with the development version? It is potentially fixed

**Comment by Henrik-P** [comment]
Nope, didn't work for me with `ggplot2_2.2.1.9000`.

**Comment by thomasp85** [comment]
Ok - then please provide a reproducible example

**Comment by Henrik-P** [comment]
Sorry if I was unclear - in my original post I used the current CRAN version (`2.2.1`). I then followed your suggestion and tried the same (reproducible) code using current development version `2.2.1.9000` , with the same result as in my first attempt.

`R version 3.3.3`, `Platform: i386-w64-mingw32/i386 (32-bit)`.

**Comment by thomasp85** [comment]
I'm really just too tired and mixed the conversations. Your example is fine thanks
