### ISSUE TITLE
aes(colour="myname") doesn't like "myname" in UTF-8

### ISSUE THREAD

**Issue by sTeamTraen** [tidyverse/ggplot2#2078]
---

Brief description of the problem

This program explores the relation between correlation coefficients and regression coefficients for various combinations of correlations between the variables.

The correct output is three curves (red, blue, green), with a horizontal line of the same colour that intercepts the curve at the Y-axis.
The incorrect output has the horizontal line in a colour that does not match.

The issues appears to be caused by
  geom_line(aes(colour=...))
not liking the colour names being UTF-8 (versus ANSI) strings.  But that's the extent of my expertise.  Maybe this is even a limitation that is documented somewhere, but I searched around 
Please briefly describe your problem and what output you expect. If you have a question, please don't use this form, but instead ask on the mailing list <https://groups.google.com/forum/#!forum/ggplot2> or stackoverflow <http://stackoverflow.com>.

Please include a minimal reprex. The goal of a reprex is to make it as easy as possible for me to recreate your problem so that I can fix it. If you've never heard of a reprex before, start by reading <https://github.com/jennybc/reprex#what-is-a-reprex>, and follow the advice further down the page. Do NOT include session info unless it's explicitly asked for, or you've used `reprex::reprex(..., si = TRUE)` to hide it away.  

```r
# Written by Nick Brown (nick.brown@free.fr), March 2017.

# Possible bug in ggplot2?
# Correct output: three curves (red, blue, green), with a horizontal line of the same colour
#  that intercepts the curve at the Y-axis.
# Incorrect output: horizontal line colour does not match.
# Note that UTF-8 encoding is required.

rm(list=ls(all=TRUE))

library("ggplot2")

rYX1 <- 0.17         # first predictor-outcome correlation
rYX2 <- 0.08         # second predictor-outcome correlation
rmin <- -0.85        # lowest negative predictor-predictor correlation to include
rmax <- 0.92         # highest positive predictor-predictor correlation to include
detail <- 200        # number of points; increase for slightly smoother curves
col.X1 <- "#0000FF"
col.X2 <- "#00FF00"
col.Rsq <- "#FF0000"

baseRsq <- -99.0
prevRsq <- 0.0

crX1X2 <- c()
cbeta1 <- c()
cbeta2 <- c()
cRsq <- c()

r12min <- round(rmin * detail)
r12max <- round(rmax * detail)
for (r12 in r12min:r12max) {
  rX1X2 <- r12 / detail
  denom <- 1 - (rX1X2 ^ 2)
  beta1 <- (rYX1 - (rYX2 * rX1X2)) / denom
  beta2 <- (rYX2 - (rYX1 * rX1X2)) / denom
  Rsq <- (rYX1 * beta1) + (rYX2 * beta2)

  if (r12 == 0) {
    baseRsq <- Rsq         # remember R-squared when rX1X2 is zero, so we can detect it again later
  }

  crX1X2 <- c(crX1X2, rX1X2)      # Please don't write to tell me this is inefficient
  cbeta1 <- c(cbeta1, beta1)
  cbeta2 <- c(cbeta2, beta2)
  cRsq <- c(cRsq, Rsq)

  prevRsq <- Rsq
}

my.breaks <- c("b1", "b2", "Rsq")
# >>>>>>>>>> To produce the "bug", uncomment the next line <<<<<<<<<<
#my.breaks <- c("β1", "β2", "R²")
# Note: if you don't see two occurrences of the Greek letter beta, and one of the "squared" symbol,
# in the above line, then something has gone wrong with the encoding at some point.

df <- as.data.frame(cbind(crX1X2, cbeta1, cbeta2, cRsq))
names(df) <- c("rX1X2", "beta1", "beta2", "Rsq")

gg <- ggplot(df, aes(x=rX1X2)) +
  scale_x_continuous(breaks=(seq(-0.5, 1.0, 1) / 10)) +
  scale_y_continuous(name="betas and Rsq", breaks=(seq(-1.0, 1.0, 2) / 10)) +
  geom_line(aes(y=beta1, colour=my.breaks[1])) +
  geom_line(aes(y=beta2, colour=my.breaks[2])) +
  geom_line(aes(y=Rsq, colour=my.breaks[3])) +
  scale_colour_manual(
    paste("rYX1=", rYX1, "  \n", "rYX2=", rYX2, sep=""),
    breaks=my.breaks,
# A workaround is to use the ANSI version of  "my.breaks" and add a labels clause here, e.g.:
#    labels=c("β1", "β2", "R²"),
    values=c(col.X1, col.X2, col.Rsq)
  ) +
  geom_hline(aes(yintercept=rYX1), colour=col.X1) +
  geom_hline(aes(yintercept=rYX2), colour=col.X2) +
  geom_hline(aes(yintercept=baseRsq), colour=col.Rsq) +
  geom_hline(aes(yintercept=0.0)) +
  geom_vline(aes(xintercept=0.0))

gg

```

**Comment by hadley** [comment]
Thanks for providing some code that illustrates the problem — it's a great start 😄 However, your code is currently a bit too complicated: there's quite a bit of extraneous stuff in there that doesn't seem directly related to the problem. Can you please try and simplify your example some more? The more minimal you can make the reprex, the faster I can identify the problem and fix it.

(I'd also recommend using the reprex package, which will also handle including the plot for you)

**Comment by sTeamTraen** [comment]
### Here is some simpler code, with straight-line output. :)
### I tried to drag an R file here, but the site doesn't support that.  So I'll paste the code.

# Written by Nick Brown (nick.brown@free.fr), June 2017.

# Possible bug in ggplot2?
# Correct output: three diagonal lines (red, blue, green),
#  which intercept a horizontal line of the same colour at X=1.
# Incorrect output: horizontal line colour does not match diagonal line colour.
# The bug appears to depend on the labels in the scale_colour_manual() call,
#  which contain the characters "β" (beta) and "²" (squared).
# To toggle between bug and OK, uncomment the single line below.
# Note that UTF-8 encoding is required (e.g., File/Save with Encoding... in RStudio).

rm(list=ls(all=TRUE))

library("ggplot2")

Y1 <- 0.6
Y2 <- 0.4
Y3 <- 0.2
col.Y1 <- "#0000FF"
col.Y2 <- "#00FF00"
col.Y3 <- "#FF0000"

cXaxis <- c(0, 1)
cY1 <- c(0, Y1)
cY2 <- c(0, Y2)
cY3 <- c(0, Y3)

my.breaks <- c("b1", "b2", "b3")
# To reveal the "bug", uncomment the next line
#my.breaks <- c("β1", "β2", "R²")

df <- as.data.frame(cbind(cXaxis, cY1, cY2, cY3))
names(df) <- c("Xaxis", "Y1", "Y2", "Y3")

gg <- ggplot(df, aes(x=Xaxis)) +
  geom_line(aes(y=Y1, colour=my.breaks[1])) +
  geom_line(aes(y=Y2, colour=my.breaks[2])) +
  geom_line(aes(y=Y3, colour=my.breaks[3])) +
  scale_colour_manual(
    "Legend",
    breaks=my.breaks,
    values=c(col.Y1, col.Y2, col.Y3)
  ) +
  geom_hline(aes(yintercept=Y1), colour=col.Y1) +
  geom_hline(aes(yintercept=Y2), colour=col.Y2) +
  geom_hline(aes(yintercept=Y3), colour=col.Y3) +
  geom_hline(aes(yintercept=0.0))

gg

### The bug is interesting in that it seems to only occur if there is a beta *and* a squared symbol in the list of break labels. If there if only one or the other, the problem doesn't occur.

![bug](https://cloud.githubusercontent.com/assets/14923399/26693080/390d630a-4703-11e7-907d-0c48e8cf033b.png)
![ok](https://cloud.githubusercontent.com/assets/14923399/26693081/391e6a7e-4703-11e7-97ef-67eac1bf30f4.png)

**Comment by sTeamTraen** [comment]
First image is the bug, second is how it should look (i.e., where the diagonal line intercepts the horizontal line, the colours should be identical).  The only difference between the runs is the text in the break labels, as determined by whether or not you uncomment the relevant line of code.

Thanks!

**Comment by hadley** [comment]
GitHub issues use [markdown](https://guides.github.com/features/mastering-markdown/) and they're much easier to read if you learn a little bit about it. The most important thing is to put your R code inside a block that starts with ```` ```R ```` and ends with ```` ``` ````. I've done that for you here, but I'd really appreciate it if you would format it yourself in the future.

**Comment by sTeamTraen** [comment]
Thanks for the tips - I will try to use markdown in future.  But why does the UTF-8 encoding change the behaviour of breaks?

**Comment by hadley** [comment]
It's not the UTF-8 encoding - it's the ordering of "B" vs "β"

**Comment by sTeamTraen** [comment]
Aaahhhhh. Sorry for your wasted time. *slaps self with wet fish*
