### ISSUE TITLE
From 

### ISSUE THREAD

**Issue by laurareads** [tidyverse/ggplot2#2082]
When using the function listed in this repo: grid_arrange_shared_legend, the updated version of R throws this error: 
Error in gList(list(grobs = list(list(x = 0.5, y = 0.5, width = 1, height = 1,  : 
  only 'grobs' allowed in "gList"

From this SO post, it seems that grid.arrange does not have a main parameter anymore: 
http://stackoverflow.com/questions/34838870/grid-arrange-from-gridextras-exiting-with-only-grobs-allowed-in-glist-afte/34839064

Would be helpful to update this function to reflect the R version. 

Reproducible example (from the SO post). 
This does not work: 
library(ggplot2)
p1 = qplot(1:10,rnorm(10))
p2 = qplot(1:10,rnorm(10))
library(gridExtra)
grid.arrange(p1, p2, ncol=2,**main**="Main Title")

This works, by changing from "main" to "top": 
library(ggplot2)
p1 = qplot(1:10,rnorm(10))
p2 = qplot(1:10,rnorm(10))
library(gridExtra)
grid.arrange(p1, p2, ncol=2,**top**="Main Title")

**Comment by hadley** [comment]
This isn't a ggplot2 function, so you need to file with gridExtra.
