### ISSUE TITLE
Provide option to draw graticule, or fail gracefully?

### ISSUE THREAD

**Issue by cpsievert** [tidyverse/ggplot2#2084]
There are projections where `plot()` still produces (an arguably wrong) result when a `st_graticule()` fails. Would it make sense to replicate that behavior of failing "gracefully"? Or maybe even something like `coord_sf(graticule = FALSE)` since it might also help out with #2071?

```r
library(sf)
library(mapdata)
w <- st_as_sf(maps::map("world", plot = FALSE, fill = TRUE))
wt <- st_transform(w, "+proj=aea +lat_1=55 +lat_2=65 +lat_0=50 +lon_0=-154 +x_0=0 +y_0=0 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs")
plot(wt)
```

![screen shot 2017-03-24 at 6 58 08 pm](https://cloud.githubusercontent.com/assets/1365941/24317309/da0a4bae-10c3-11e7-9e44-c776c14f19ee.png)

```r
 st_graticule(wt)
#> Error code: 6
#> Error in CPL_transform(x, crs$proj4string, crs$epsg) : OGR error
```

```r
ggplot() + geom_sf(data=wt)
#> Error code: 6
#> Error in CPL_transform(x, crs$proj4string, crs$epsg) : OGR error
```

**Comment by edzer** [comment]
This now works with sf devel (and probably also 0.5-1):

![x](https://user-images.githubusercontent.com/520851/27625996-bb711812-5be6-11e7-8628-368e1dee54af.png)
