### ISSUE TITLE
geom_sf: xlim, ylim misbehaviour?

### ISSUE THREAD

**Issue by espinielli** [tidyverse/ggplot2#2090]
```r
library(rnaturalearth)
library(sf)
library(ggplot2) # with support for geom_sf

w <- ne_countries(returnclass = "sf")
gg2 <- ggplot(data = w) +
  geom_sf(fill = "grey", colour = "black") +
  coord_sf(crs = crs, xlim = c(-42, 52), ylim = c(12, 84))
gg2
```

I would expect the code above to show only the black rectangle part of the whole world, i.e. the rectangle in projected coordinates containing the polygon defined by `xlim`, `ylim`.

![image](https://cloud.githubusercontent.com/assets/891692/24417275/1ae0eb98-13e8-11e7-9210-428493eb73a5.png)

What I get instead is:

![image](https://cloud.githubusercontent.com/assets/891692/24442255/987d689a-145d-11e7-9579-1fe866eae8fa.png)

I am using

```
 ggplot2            * 2.2.1.9000 2017-03-21 Github (tidyverse/ggplot2@08e135e)         
 rnaturalearth      * 0.1.0      2017-03-27 Github (ropenscilabs/rnaturalearth@475064f)
 sf                 * 0.4-1      2017-03-27 Github (edzer/sfr@f1c6d45)                 

```

**Comment by davben** [comment]
The suitable coordinates for `xlim` and `ylim` depend on the projection/coordinate system you choose for the map. As it is, your MWE produces an error, because we don't know what you've specified for `crs`.

Without any changes, the projection setting of the natural earth data is
    
    > st_crs(w)
    $epsg
    [1] 4326

    $proj4string
    [1] "+proj=longlat +datum=WGS84 +no_defs"

    attr(,"class")
    [1] "crs"
and that produces the desired section of the world map using your lat/long limits:

    gg2 <- ggplot(data = w) +
      geom_sf(fill = "grey", colour = "black") +
      # not specifying crs here, coord_sf will use the CRS defined in the first layer = "+proj=longlat +datum=WGS84 +no_defs"
      coord_sf(xlim = c(-42, 52), ylim = c(12, 84)) 
    gg2

![rplot](https://cloud.githubusercontent.com/assets/8489251/24443990/27f7af38-1465-11e7-9604-fa77830c28bf.png)

However, if you use a different map projection the underlying coordinates may change. For example, with Lambert Azimuthal Equal Area (http://spatialreference.org/ref/sr-org/28/)

    w2 <- st_transform(w, crs = "+proj=laea +lat_0=45.5 +lon_0=-114.125 +x_0=0 +y_0=0 +a=6371007.181 +b=6371007.181 +units=m +no_defs")

you can see from the bounding box that the coordinate system has changed:

    > st_bbox(w)
          xmin       ymin       xmax       ymax 
    -180.00000  -90.00000  180.00000   83.64513 
    > st_bbox(w2)
         xmin      ymin      xmax      ymax 
    -12019954 -12503720  12152326  11003723

You can probably use something like `proj4::ptransform()` to convert your values for `xlim`and `ylim` between projections or simply go by trial and error.

**Comment by espinielli** [comment]
Oooops, I forgot to add `crs` value

```
crs <- "+proj=laea +lat_0=52 +lon_0=10 +x_0=4321000 +y_0=3210000 +datum=WGS84 +units=m +no_defs"
```
I also *failed* to pass my message, maybe the following image will provide better understanding.

I would like to obtain a map in my projection, with above `crs`, that fits the blue "bounding box" (you can think of it as a polygon defined by the 4 corners of the `xlim` and `ylim`)

![image](https://cloud.githubusercontent.com/assets/891692/24504461/b313817c-1556-11e7-856b-50598a8bed90.png)

I will have a look at `proj4::ptransform()`. Thanks!

**Comment by espinielli** [comment]
Solution found! 
Thanks to @davben who inspired me to think about the bounding box in the new projection!


The points mentioned in the code are the A, B, C, D in the following plot
![image](https://cloud.githubusercontent.com/assets/891692/24506941/6e0fa6ec-155f-11e7-8537-a41813b946d0.png)

Here is the code:
```
library(rnaturalearth)
library(sf)
library(ggplot2) # with support for geom_sf

# all countries at scale 10m
ctrys <- ne_countries(scale = 10, type = "countries", returnclass = "sf")

crsLONGLAT <- "+proj=longlat +datum=WGS84 +no_defs"
crsLAEA <- "+proj=laea +lat_0=52 +lon_0=10 +x_0=4321000 +y_0=3210000 +datum=WGS84 +units=m +no_defs"

# the bouding box polygon in long/lat projection, i.e. axis-aligned
bb <- st_sfc(
  st_polygon(list(cbind(
    c(-42, 52, 52, -42, -42), # x-coordinates (longitudes) of points A,B,C,D
    c(12, 12, 84, 84, 12)     # y-coordinates (latitudes) of points A,B,C,D
    ))),
  crs = crsLONGLAT)


# now in in LAEA projection
laeabb <- st_transform(bb, crs = crsLAEA)

# the extent of the bounding box in the new projection
b <- st_bbox(laeabb)
b

gg2 <- ggplot(data = ctrys) +
  geom_sf(fill = "grey", colour = "black") +
  coord_sf(crs = crsLAEA, xlim = c(b["xmin"], b["xmax"]), ylim = c(b["ymin"], b["ymax"]))
gg2
```

...and the plot

![image](https://cloud.githubusercontent.com/assets/891692/24507579/178839a4-1561-11e7-8fba-a99c64f4db54.png)
