### ISSUE TITLE
Adding geom_hline with boolean logic in facet_wrap causes failure

### ISSUE THREAD

**Issue by billdenney** [tidyverse/ggplot2#2091]
When I have logic in the equation for facet_wrap (like `facet_wrap(~(Z < 0.5))`), it works fine without a geom_hline modifier, but with the modifier, it gets an error that "object 'Z' not found.

```r
  library(ggplot2)
  d <- data.frame(X=rnorm(10),
                  Y=rnorm(10),
                  Z=rnorm(10))
  ggplot(d, aes(x=X, y=Y)) +
    geom_point() +
    facet_wrap(~(Z < 0.5))
  # Plot appears as expected
  ggplot(d, aes(x=X, y=Y)) +
    geom_point() +
    facet_wrap(~(Z < 0.5)) +
    geom_hline(yintercept=0)
  # Error in eval(expr, envir, enclos) : object 'Z' not found
```

**Comment by has2k1** [comment]
Try this `geom_hline(yintercept=0, inherit.aes=TRUE)`

**Comment by billdenney** [comment]
`geom_hline` doesn't appear to have an inherit.aes argument though it is mentioned in the documentation (perhaps that's another bug?):

```r
library(ggplot2)
d <- data.frame(X=rnorm(10),
                Y=rnorm(10),
                Z=rnorm(10))
ggplot(d, aes(x=X, y=Y)) +
  geom_point() +
  facet_wrap(~(Z < 0.5))
# Plot appears as expected
ggplot(d, aes(x=X, y=Y)) +
  geom_point() +
  facet_wrap(~(Z < 0.5)) +
  geom_hline(yintercept=0, inherit.aes=TRUE)
# Warning: Ignoring unknown parameters: inherit.aes
# Error in eval(expr, envir, enclos) : object 'Z' not found
```

**Comment by has2k1** [comment]
What about this `stat_identity(yintercept=0, geom='hline', inherit.aes=TRUE)`

**Comment by billdenney** [comment]
`stat_identity` works and is a reasonable work-around.  Thanks for the suggestion!

If possible, it would be nice to have `geom_hline` work directly in the next version of ggplot2.

**Comment by hadley** [comment]
I don't think there's any way to do what you want without huge changes to ggplot2. But a slightly better approach is to make a data frame and use that with `geom_hline()`.

``` r
library(ggplot2)
d <- data.frame(X=rnorm(10), Y=rnorm(10), Z=rnorm(10))
lines <- data.frame(intercept = 0, Z = c(0, 1))

ggplot(d, aes(x=X, y=Y)) +
  geom_point() +
  geom_hline(aes(yintercept = intercept), data = lines) +
  facet_wrap(~(Z < 0.5))
```

![](https://i.imgur.com/Qh84K7T.png)

**Comment by billdenney** [comment]
Fair that this is too large a change to make now.  Since expressions work in areas other than facets, can you please add an error like "Expressions are not allowed in facet formula" or similar since it's not obvious that they are allowed in some parts of ggplot but not facets?

**Comment by hadley** [comment]
They do work in facets; it's the combination with `geom_hline()` that's the problem.   If you think carefully about the `lines` data frame above, I think you'll see why.
