### ISSUE TITLE
map_data( ) not using arguments passed to map( )

### ISSUE THREAD

**Issue by danfulop** [tidyverse/ggplot2#2108]
I'm trying to use the "world" map from the maps package. I'm using map_data to make a ggplot-friendly DF of the map.

I want the map to _not_ have country borders, so I tried to pass interior=FALSE from map_data() to map(). However, when I try that the map still has the country borders.

---

Brief description of the problem

```r
# insert reprex here
library(ggplot2)
library(ggalt)

map('world', interior=F) # map without country borders

# example code with map_data() failing to exclude country borders
world <- map_data("world", interior=F)
world <- world[world$region != "Antarctica",]
gg <- ggplot()
gg <- gg + geom_cartogram(data=world, map=world, aes(x=long, y=lat, map_id=region))
gg <- gg + coord_proj("+proj=wintri")
gg
```

**Comment by hadley** [comment]
Unfortunately this seems to be a limitation of the `maps()` function - `interior` has no effect when `fill = TRUE`, and `map_data()` needs to set `fill = TRUE` in order to get complete polygons rather than individual lines.
