### ISSUE TITLE
borders() should support color=

### ISSUE THREAD

**Issue by adrfantini** [tidyverse/ggplot2#2109]
A small consistency fix.

In most ggplot functions, `color` and `colour` are synonyms. Not in `borders()`, where the only possible color specification is `colour`; `color` simply does nothing.

This is on ggplot 2.2.1

**Comment by hadley** [comment]
This seems like a good idea, but unfortunately it's not high enough on my priority list that I will implement it myself. However, I'd be happy to review a PR.
