### ISSUE TITLE
Automatically fill in x for univariate boxplot

### ISSUE THREAD

**Issue by hadley** [tidyverse/ggplot2#2110]
i.e. make this work

```R
ggplot(mtcars, aes(y = disp)) + geom_boxplot()
```

**Comment by foo-bar-baz-qux** [comment]
Presumably the output would look the same as if x was the same for all y then?
```r
ggplot(mtcars, aes(x = '1', y = disp)) + geom_boxplot()
```

**Comment by rpruim** [comment]
Ideally, the output should not be exactly like this:

``` r
library(ggplot2)
ggplot(mtcars, aes(x = "1", y = disp)) + geom_boxplot()
```

![](https://i.imgur.com/3CrDcdl.png)

There is no reason for the labeling of the x-axis in such a plot (neither the x nor the 1 should be there.)

**Comment by dannyparsons** [comment]
I like the simplified syntax but now the x axis has a numeric scale, which seems unnecessary and potentially confusing. Could there be no labelling as @rpruim suggests? `ggplot(mtcars, aes(x = "", y = disp)) + geom_boxplot()` almost does this apart from the `x` label.

```{r}
ggplot(mtcars, aes(y = disp)) + geom_boxplot()
```
![image](https://user-images.githubusercontent.com/11214914/43075805-ca154c00-8e79-11e8-8d63-fc648d753e45.png)

**Comment by ptoche** [comment]
So we're back to ``ggplot(mtcars, aes(y = disp, x = factor(""))) + geom_boxplot() + theme(axis.ticks.x = element_blank())``

**Comment by rpruim** [comment]
No need for the x aesthetic now (and better to omit it):
``` r
library(ggplot2)
ggplot(mtcars, aes(y = disp)) + geom_boxplot() + 
  theme(axis.ticks.x = element_blank(), axis.text.x = element_blank())
```

![](https://i.imgur.com/ASDiM1J.png)

Created on 2018-07-24 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

I suppose it would be nice to avoid the theme stuff -- but how often does one use a single boxplot anyway?

**Comment by ptoche** [comment]
This produces undesired vertical grid lines, which is why is put ``x = factor("")``.

**Comment by clauswilke** [comment]
The default x value provided by `geom_boxplot()` is 0. I think it should be `factor(0)` or `factor("")`. Boxplots don't normally have a continuous x axis.

**Comment by ptoche** [comment]
@rpruim  The vertical grid lines are a consequence of ``x`` being treated as numeric. My interpretation of dannyparsons' comment is that a more appropriate default would be to treat ``x`` as a factor instead. Oh and as I write this, clauwilke seems to think so too. It should be easy to fix.

**Comment by ptoche** [comment]
Possibly this commit: https://github.com/tidyverse/ggplot2/pull/2292/commits/42c86d5d9e0cbdd2363e8f71695afd36e22f847a

and these lines:
https://github.com/tidyverse/ggplot2/blob/510b4b4b3eae992255ddca86de63d1fada2221ca/R/stat-boxplot.r#L48

https://github.com/tidyverse/ggplot2/blob/510b4b4b3eae992255ddca86de63d1fada2221ca/R/stat-boxplot.r#L59
