### ISSUE TITLE
stat_sf(geom = "text")

### ISSUE THREAD

**Issue by cpsievert** [tidyverse/ggplot2#2111]
I'd expect something like this to work

```r
library(ggplot2)
library(sf)
library(albersusa)
usa_sf <- st_as_sf(usa_composite("laea"))
centroids <- st_centroid(usa_sf)

ggplot() + 
  geom_sf(data = usa_sf) + 
  stat_sf(data = centroids, aes(geometry = geometry, label = name), geom = "text")
```

**Comment by hadley** [comment]
@edzer is there an obvious way to do this with `st_as_grob()`? I don't think there is.

**Comment by edzer** [comment]
No, as `sf:::st_as_grob.POINT` simply calls `grid::pointGrob`. We could modify it such that it takes a `label` argument and then calls `grid::textGrob`; alternatively you could get the coordinates (as 2-column matrix) in ggplot by 
```r
> head(st_coordinates(centroids))
           X            Y
1 -1071416.4 -1116201.262
2   690503.2 -1091192.221
3 -1707964.5  -667016.439
4  -479407.9  -650634.740
5  2215964.8    -1222.643
6  1960178.5  -403145.999
```

**Comment by hadley** [comment]
I had a go at implementing this but ultimately it seemed like it was going to overload `geom_sf()` with too many options. I think for this case it's probably better to extract x and y into their own columns and use `geom_text()` directly.
