### ISSUE TITLE
label.size in geom_label is ignored when printing to pdf

### ISSUE THREAD

**Issue by FabianRoger** [tidyverse/ggplot2#2114]
It seem like the `label.size` attribute is ignored in `geom_label` when the plot is saved as `pdf`. In particular, I set `label.size = 0` so it doesn't draw a border. It works as expected when saving as `png` but when I save it as `pdf` the label get's drawn anyway. 

reproducible example:

    library(ggplot2)
    data("iris")

    plot1 <- 
      ggplot(data = iris, aes(x = Sepal.Length, y = Sepal.Width))+
      geom_point()+
      annotate("label", x = 7, y = 4, label = "Iris Data", label.size = 0,)

    ggsave("testplot.png") # works as expected
    ggsave("testplot.pdf") # draws border of label

PNG:
![testplot](https://cloud.githubusercontent.com/assets/5137092/25481064/cb0247ea-2b4b-11e7-963c-d4f153904c45.png)

PDF:
![testplot_pdf](https://cloud.githubusercontent.com/assets/5137092/25481121/09cb3400-2b4c-11e7-9917-89d469bb58b7.png)

**Comment by ptoche** [comment]
same behaviour observed with:

    geom_label(aes(x = 7, y = 4, label = "Iris Data"), colour = 'black', label.size = 0)

**Comment by hadley** [comment]
Use `NA` instead of 0.
