### ISSUE TITLE
coord_proj() is superior to coord_map() and could be included in the default ggplot

### ISSUE THREAD

**Issue by adrfantini** [tidyverse/ggplot2#2117]
`coord_proj()` from package `ggalt` is a superior way of projecting map data in `ggplot2` compared to `coord_map()`. [The function](https://github.com/hrbrmstr/ggalt/blob/master/R/coord_proj.r) uses industry-standard CRS codes and the under the hood calculation uses the yet again industry-standard (and pretty awesome) PROJ.4 library. The advantage of using standard CRS codes instead of the definitely non-standard values from `mapproj` allows for better automation and less manual fiddling for finding which values correspond to which CRS parameters.

A more detailed reasoning (not mine, but from the author of `ggalt`) can be found [here](https://rud.is/b/2015/07/24/a-path-towards-easier-map-projection-machinations-with-ggplot2/).

I believe a kind of `coord_proj()` could be included directly in the default `ggplot2` as a superior alternative to `coord_map()`.

EDIT: I see that `coord_sf()` already works quite a bit better then `coord_map()` from this point of view, at least. Can you implement the same nice working lines and labels into `coord_proj()`?

**Comment by hadley** [comment]
We're moving towards `coord_sf()` and away from `coord_map()`. 

Please file specific issues (with reprexes created by the reprex package) if you have issues with `corod_sf()`.
