### ISSUE TITLE
Labels can overlap in coord_sf()

### ISSUE THREAD

**Issue by adrfantini** [tidyverse/ggplot2#2119]
Labels in `coord_sf()` sometimes overlap. This happens when one of the grid lines has some part inside of the plot, but intersect an axis outside of the plot.

See reprex below, look at the bottom left corner, 80W and 82W overlap.

```
nc <- sf::st_read(system.file("shape/nc.shp", package = "sf"), quiet = TRUE)
ggplot(nc) +
  geom_sf(aes(fill = AREA)) +
  coord_sf(crs="+proj=lcc")
```

**Comment by hadley** [comment]
Can you please create your reprex with the reprex package?

**Comment by adrfantini** [comment]
@hadley I cannot because:
```
> reprex({nc <- sf::st_read(system.file("shape/nc.shp", package = "sf"), quiet = TRUE); ggplot2::ggplot(nc) + ggplot2::geom_sf(ggplot2::aes(fill = AREA)) + ggplot2::coord_sf(crs="+proj=lcc")})
Error in reprex_(r_file) : 
Cannot render this code.
Error in UseMethod("xmlApply") : 
  no applicable method for 'xmlApply' applied to an object of class "raw"
```
I don't have time to gid through it. However just copypasting the code results in [this](http://imgur.com/a/mC4yG
). This is with the gitHub version of `ggplot2` of course.

**Comment by edzer** [comment]
Thanks; I can see what goes wrong; we need to check whether this needs to be solved on the `ggplot2` side or on the `sf` side -- `sf::st_graticule` is used to compute the graticules and their labels.

Also, I see a 38N (or 38N and 36N overplotted?) at the top left that is placed wrongly as well.

**Comment by adrfantini** [comment]
Thanks Edzer, yes something is wrong at the top left as well. Thanks for taking a look at it, this is currently preventing me from using `geom_sf()` for publication-ready graphics.

**Comment by edzer** [comment]
You'll need this [PR](https://github.com/tidyverse/ggplot2/pull/2151), along with a fresh sf checkout.
