### ISSUE TITLE
it would be nice to have date_breaks('0.2 sec')

### ISSUE THREAD

**Issue by randomgambit** [tidyverse/ggplot2#2120]
Hello there,

What can I say? The great `ggplot2`! 

It would be nice if one could define `date_breaks` with units smaller than 1 second. say 0.5 seconds or the like. Right now, I am doing that manually with 

`minor_breaks = seq(from = ymd_hms('2000-01-01 08:29:58'), to =  ymd_hms('2000-01-01 08:30:10'), by = 0.5)`

but this is a pain... What do you think?

Thanks!

**Comment by has2k1** [comment]
This should be posted at https://github.com/hadley/scales.

**Comment by randomgambit** [comment]
ha sorry guys... im tidylost in the tidyverse hehehe
