### ISSUE TITLE
Restore icons on reference web page

### ISSUE THREAD

**Issue by dantonnoriega** [tidyverse/ggplot2#2121]
One of my favorite things about the olds docs.ggplot2.org website were the little visual representations of each geom.  The new website is great, but the little visual references were, in my opinion, a superior way for me to quickly and easily determine the graphs I was aiming to make.

For example, I didn't really understand what `geom_rug` produced, even with the current written description "Rug plots in the margins". To find out, I need to click the link and see the examples. 

Not the end of the world, but it was a cool website feature that used to exist that I think is worth bringing back (maybe a separate page?).

**Comment by hadley** [comment]
Now back! 🎉 📈
