### ISSUE TITLE
(feature request) Changing facet_wrap strip colour based on variable in data frame

### ISSUE THREAD

**Issue by philstraforelli** [tidyverse/ggplot2#2126]
I was wondering if there's any possibility in allowing the user to have the colour of the `facet_wrap` strip change based on a variable in the data set, as per this SO Q&A: http://stackoverflow.com/questions/19440069/ggplot2-facet-wrap-strip-color-based-on-variable-in-data-set

The answer, while it works, is quite cumbersome. It would be fantastic if there was the possibility of converting the SO answer to something like `facet_wrap(~ fruit, aes(strip_fill = fruit))`.

**Comment by hadley** [comment]
This seems like a good idea, but unfortunately it's not high enough on my priority list that I will implement it myself.
