### ISSUE TITLE
geom_density with groups of 1 or 2 elements

### ISSUE THREAD

**Issue by LSanselme** [tidyverse/ggplot2#2127]
Hello,

I am struggling with `geom_density` when groups consist on fewer than 3 elements. 
For a group of 1 element, the density plot consists on a single line of length 1. For a group of 2 elements, this is a rectangle of height 0.5.
Since this does not depends on the _y_ scale, the interpretation of the area under the curves breaks down. This problem becomes obvious when changing coordinates on the _x_ axis (_eg_ unit conversion).

This reproducible example illustrates my point.
This is the density of the measurements of `Speed`, for the 5 experiments. Each consists on 20 runs.

```r
library(tidyverse)
library(MASS)

michelson %>%
  ggplot(aes(x = Speed, fill = Expt)) +
  geom_density(alpha = 0.5)
```
![image](https://cloud.githubusercontent.com/assets/10049355/25946761/ce5a35ae-364c-11e7-95f9-5af4138e1add.png)

The density of the measurements, for the 5 experiments when we re-normalize the speed. As expected, the only changes are in the axis texts.

```r
michelson %>%
  mutate(Speed = Speed / mean(Speed)) %>%
  ggplot(aes(x = Speed, fill = Expt)) +
  geom_density(alpha = 0.5)
```
![image](https://cloud.githubusercontent.com/assets/10049355/25946798/ee373aac-364c-11e7-8216-0bbc8bfff12e.png)

The problem arises when the groups are small,
so we modify the data for the last group to consist on only two runs.
```r
michelson_modif <- michelson
michelson_modif$Expt[83:100] <- 2

michelson_modif %>%
  ggplot(aes(x = Speed, fill = Expt)) +
  geom_density(alpha = 0.5)
```

![image](https://cloud.githubusercontent.com/assets/10049355/25946983/b396509e-364d-11e7-980a-7e60c3546585.png)

```r
michelson_modif %>%
  mutate(Speed = Speed / mean(Speed)) %>%
  ggplot(aes(x = Speed, fill = Expt)) +
  geom_density(alpha = 0.5)

```
![image](https://cloud.githubusercontent.com/assets/10049355/25946991/c3c0481c-364d-11e7-99eb-a7e590754a6b.png)

The two graphs are no longer similar.

Do I miss something here? Is it possible to force the behaviour of `geom_density` to be similar (_ie_ smooth curves) for all the groups, regardless of the number of elements in them?

Thanks a lot!

**Comment by LSanselme** [comment]
This might be linked to the closed issue https://github.com/tidyverse/ggplot2/issues/595 discussed between @wch and @hadley, or to the closed issue https://github.com/tidyverse/ggplot2/issues/676.

**Comment by hadley** [comment]
It looks like I messed up this special case in `compute_density()`:

```R
  if (nx < 3) {
    return(data.frame(
      x = x,
      density = w / sum(w),
      scaled = w / max(w),
      count = 1,
      n = nx
    ))
  }
```

**Comment by LSanselme** [comment]
Thanks @karawoo!
