### ISSUE TITLE
facet_grid changes values

### ISSUE THREAD

**Issue by JWilb** [tidyverse/ggplot2#2128]
---

Hello, 
_(this is my first time on github, raising an issue. I'm grateful for recommendations on improvement.)_

I have a strange problem with `facet_grid()`: Values appear to be changed. Consider this data

 ```  
Species Set 	Type 	Size 	Val
No1   	A 	auto    1 	3.5
No1   	A 	 man    1 	2.8
No1   	B 	auto    1 	2.5
No1   	B 	 man    1	2.4
No2   	A 	auto    5 	2.5
No2   	A 	 man    5 	3.8
No2   	B 	auto    5 	3.5
No2   	B 	 man    5 	3.4
No3   	A 	auto    3 	2.0
No3   	A 	 man    3 	0.8
No3   	B 	auto    3 	3.0
No3   	B 	 man    3 	3.9
```
with three `Species` with a specific `Size`, where `Values` have been inferred under two conditions (`Set`) using two methods (`Type`).
I expect that when I plot `Size` against `Value` the size remains the same (i.e., all values for species No1 map to size 1) under any faceting-condition (no facet, facet with one variable, facet with two variables). However, faceting appears to move data points where they not belong. This is illustrated with the figures below.

``` r
library(ggplot2)        
                                                                          
Species <- c("No1", "No1", "No1", "No1", "No2", "No2", "No2", "No2", "No3", "No3", "No3", "No3")  
Set <- c("A", "A", "B", "B", "A", "A", "B", "B", "A", "A", "B", "B")                              
Type <- c("auto", "man", "auto", "man", "auto", "man", "auto", "man","auto", "man", "auto", "man")
Size <- c(1, 1, 1, 1, 5, 5, 5, 5, 3, 3, 3, 3)                                                     
Val <- c(3.5, 2.8, 2.5, 2.4, 2.5, 3.8, 3.5, 3.4, 2, 0.8, 3, 3.9)                                  
df = data.frame(Species, Set, Type, Size, Val)                                                    
```

**Create plots**
First one with correct results: All points of one color (`Species`) are of the same `Size`.

``` r
ggplot(df, aes(x=df$Size, y=df$Val)) +                                                            
geom_point(aes(colour = Species, shape = Type))                                                   
```

![](http://i.imgur.com/J64NfWM.png)

then two versions of the same data with wrong results (points show up at wrong positions, mixed in different ways)

``` r
ggplot(df, aes(x=df$Size, y=df$Val)) +                                                            
geom_point(aes(colour = Species, shape = Type)) +                                                 
facet_grid(Type ~ .)                                                                              
```

![](http://i.imgur.com/PLBj059.png)

``` r
ggplot(df, aes(x=df$Size, y=df$Val)) +                                                            
geom_point(aes(colour = Species, shape = Type)) +                                                 
facet_grid(Type ~ Set)                                                                            
```

![](http://i.imgur.com/4qGEVh8.png)

I would be very happy to know what is going on here.
Thank you and best wishes!

**Comment by wch** [comment]
The problem is that you're using `aes(x=df$Size, y=df$Val)`, but you should be using `aes(x=Size, y=Val)`. When you use `df$Size`, it always grabs the data from the original `df` data frame, instead of from the data that has been split up for faceting.

**Comment by JWilb** [comment]
Thank you so much!! *relief*
