### ISSUE TITLE
Border between strip and panel becomes too thick

### ISSUE THREAD

**Issue by powestermark** [tidyverse/ggplot2#2129]
When using facets with a theme with borders, e.g. theme_bw, the border between the strip and panel becomes twice as thick as all other borders, which is seriously distracting for the graph. It's because the strip rectangle "sits on top of" the panel. I don't think it's possible to rectify this using standard ggplot theming code.

I've exaggerated the border thicknesses in the code example, just to drive the point home.   

```r
library(ggplot2)

ggplot(iris, aes(x = Sepal.Length, y = Sepal.Width)) +
  facet_wrap(~ Species, ncol=1) +
  geom_point() + theme_bw() +
  theme(
    panel.border=element_rect(size=2),
    strip.background=element_rect(size=2)
  )
```
![rplot](https://cloud.githubusercontent.com/assets/28629554/26255153/0943a21e-3cb9-11e7-8819-d4e74f48ce77.png)

**Comment by hadley** [comment]
I agree this doesn't look great, but it would be time consuming to fix, and the pay off isn't great. For that reason, it's unlikely to ever get high enough up on the todo list to get fixed.
