### ISSUE TITLE
geom_sf seems to break when used with ggmap

### ISSUE THREAD

**Issue by Yeedle** [tidyverse/ggplot2#2130]
This might be an issue with `ggmap` or an issue with how `geom_sf` handles inherited aesthetic mappings. I'm not sure, so I'm submitting it here and to [`ggmap`](https://github.com/dkahle/ggmap/issues/160)
``` r
library(sf)
library(ggmap)

nc_map <- get_map(c(-81, 35), zoom = 6) 
#> Map from URL : http://maps.googleapis.com/maps/api/staticmap?center=35,-81&zoom=6&size=640x640&scale=2&maptype=terrain&language=en-EN&sensor=false
ggmap(nc_map)
```
![](http://i.imgur.com/JaCRzUG.png)

``` r
nc <- st_read(system.file("shape/nc.shp", package="sf"))
ggplot(nc) + geom_sf()
```
![](http://i.imgur.com/rS13QWT.png)

``` r
ggmap(nc_map) + geom_sf(data = nc)
#> Error in FUN(X[[i]], ...): object 'lon' not found
```

**Comment by hadley** [comment]
I think this is a design infelicity in ggmap. Really it should provide `geom_ggmap()` which works similar to `geom_sf()`.
