### ISSUE TITLE
qplot gives warnings for unknown parameters when following example code qplot

### ISSUE THREAD

**Issue by JoFAM** [tidyverse/ggplot2#2134]
qplot has the ... argument to pass aesthetics into each layer. If I follow the example code from http://ggplot2.org/book/qplot.pdf , ggplot2 version 2.2.1 throws a warning about unknown parameters.

This problem occurs when different layers are constructed by eg using multiple geoms, and using the dots argument to pass extra arguments to those. The arguments are used correctly, but nevertheless a warning is thrown.

```r
set.seed(1410) # Make the sample reproducible
dsmall <- diamonds[sample(nrow(diamonds), 100), ]
qplot(carat, price, data = dsmall, geom = c("point", "smooth"),
      span = 0.2)
```
Throws a warning but gives a correct plot. The warning can be emulated by explicitly writing this out as:

```r
ggplot(dsmall, aes(x = carat, y = price)) +
  geom_point(span = 0.2) +
  geom_smooth(span = 0.2)
```

The help page says that ... should be *aesthetics* passed into each layer, but it clearly passes any extra argument to all layers constructed, not just aesthetics. So the help page could use an update as well.

**Comment by hadley** [comment]
The old behaviour of `qplot()` has been deprecated because it made the code more complex, and we want to encourage people to use explicit layers.

**Comment by JoFAM** [comment]
Thank you for answering, and I understand your point. But it would make sense to update the documentation. When my students run the examples from the documentation, they do expect this to work without problems.

**Comment by hadley** [comment]
Where is this in the docs? I don't see it in `?qplot`

**Comment by has2k1** [comment]
@JoFAM  is referring to http://ggplot2.org/book/qplot.pdf

**Comment by hadley** [comment]
Ah, ok, obviously the first edition of the book isn't going to change, but it's been updated in the 2nd edition.
