### ISSUE TITLE
legends combining point shapes and linetypes are illegible

### ISSUE THREAD

**Issue by danprec** [tidyverse/ggplot2#2135]
Plots with aesthetic combining different linetypes (with geom_line or geom_smooth) and shapes for geom_point are illegible: Size of the point is too small and ends up hidden by the lines, making the legend quite useless, as it is not possible to discriminate the conditions. 

It doesn't seem to be possible to manually manipulate the legend to increase the size of the points without affecting the lines. using override.aes(size=x) changes the size of both the points and lines, making it even more illegible.

**Comment by ptoche** [comment]
you can do all these things. Check stackoverflow for examples. 

Please provide code for your problem. But I suspect stackoverflow can answer your questions.

Just a quick search:

http://stackoverflow.com/questions/25007324/can-ggplot2-control-point-size-and-line-size-lineweight-separately-in-one-lege/34304453#34304453

http://stackoverflow.com/questions/34893760/how-to-scale-the-size-of-line-and-point-separately-in-ggplot2/35213634#35213634

**Comment by hadley** [comment]
See `override.aes` in `guide_legend()`, e.g. http://ggplot2.tidyverse.org/reference/guide_legend.html

**Comment by AaronRendahl** [comment]
It seems you can do this only by editing the underlying grid system (the first link in ptoche's response), or by separating the legends (the second link); I've looked on stackoverflow elsewhere and haven't found other solutions. The OP tried `override.aes`, and the trouble is that both the point and the line respond to the `size` argument, you can't set them separately.
