### ISSUE TITLE
scale_discrete not listening to 'breaks' arg

### ISSUE THREAD

**Issue by schloerke** [tidyverse/ggplot2#2137]
`scale_x_discrete`  and `scale_y_discrete` are not listening to the `breaks` argument.  The example below should reverse the order of the box plots.

``` r
library(ggplot2)

dt <- data.frame(letter = rep(letters[1:3], each = 10), value = rnorm(30) + 
  rep(c(10, 20, 50), each = 10))

# should have groups (a,b,c)
ggplot(dt, aes(letter, value)) + geom_boxplot() + scale_x_discrete(breaks = letters[1:3])
```

![](http://i.imgur.com/YVJ2txX.png)

``` r

# should have reverse groups (c,b,a)
ggplot(dt, aes(letter, value)) + geom_boxplot() + scale_x_discrete(breaks = rev(letters[1:3]))
```

![](http://i.imgur.com/JIk4rhy.png)

**Comment by karawoo** [comment]
I think the more common way to change the order of discrete scales is with the `limits` argument rather than `breaks`:

``` r
ggplot(dt, aes(letter, value)) + geom_boxplot() + scale_x_discrete(limits = rev(letters[1:3]))
```

![](http://i.imgur.com/dY33FW3.png)

**Comment by schloerke** [comment]
Yes, you are correct.    This is changed behavior from what it was in earlier versions.  

With earlier versions, the plots below would have both been like the second plot.  Now they differ.

Thank you for the clarification.

``` r
library(ggplot2)
data(diamonds)
p <- ggplot(data = diamonds, mapping = aes(x = clarity)) + geom_bar(mapping = aes(fill = cut))
# order doesn't matter. display all original groups
p + scale_x_discrete(breaks = c("SI2", "I1", "SI1"))
```

![](http://i.imgur.com/hDHnqEi.png)

``` r
# order matters. display subset of original group
p + scale_x_discrete(limits = c("SI2", "I1", "SI1"))
#> Warning: Removed 30940 rows containing non-finite values (stat_count).
```

![](http://i.imgur.com/lOFt1Lc.png)
