### ISSUE TITLE
Add minor ticks to axes

### ISSUE THREAD

**Issue by batuff** [tidyverse/ggplot2#2144]
I think this is not a new request, but It would be great to have minor tick marks along with major tick marks for the axes. Tick management could mirror the way panel.grid.major and panel.grid.minor are managed. In a relevant number of plots published in scientific journals, major and minor tick marks are commonly used, while major and minor grids are rarely used.

**Comment by hadley** [comment]
This seems like a good idea, but unfortunately it's not high enough on my priority list that I will implement it myself. However, I'd be happy to review a PR.
