### ISSUE TITLE
geom_point border and fill portions of the point overlap

### ISSUE THREAD

**Issue by wdsteck** [tidyverse/ggplot2#2152]
---
Using ggplot2 with R3.3.3 on windows.

The border and the fill areas of a point are overlapping. I understand from other issue posts that stroke should not be affected by alpha, but on points, it is. When the point has an alpha of .5 and the stroke is set rather large (say 15), you see an overlap of the border and the point. I am plotting points like this (with alpha = .5 to show density) and since the overlap is happening, the overlap section of the point is much darker than the rest of the point. This is not aesthetically pleasing.

The code below produces 2 points of the same size fill area. They appear (by my crude screen measures) to be the same size (fill area) as they should, but it appears that the fill area on the point with stroke = 15 has been drawn larger and is assuming that the border will mask the difference. With alpha = .5, this doesn't happen.

So, either the point border should not be impacted by alpha or, preferably, the point border and fill should not overlap.

```r
ggplot(data.frame(x = c(0, 1)), aes(x = x, y = 0)) +
  geom_point(size=15,
             fill = "red",
             colour = "black",
             shape = 21,
             stroke = c(0, 15),
             alpha = .5) +
  scale_size_identity()
![rplot](https://user-images.githubusercontent.com/19614636/26906752-13f62d9a-4bbd-11e7-900a-eda613c7942a.png)
```

**Comment by hadley** [comment]
This is a fundamental limitation of the underlying graphics system so there's nothing we can do about it unfortunately.
