### ISSUE TITLE
Facetting leads to faulty x values for position_dodge(preserve="single")

### ISSUE THREAD

**Issue by has2k1** [tidyverse/ggplot2#2153]
``` r
library(ggplot2)

ggplot(mtcars, aes(factor(cyl), fill=factor(vs))) +
  geom_bar(position=position_dodge(preserve = "single")) +
  facet_wrap(~ am)
```

![](http://i.imgur.com/gmMg0Zp.png)

The width of the bars is wrong. The problem is [here](https://github.com/tidyverse/ggplot2/blob/eedaa81b72d1ae56b86c04397455c8f0c6c84bd2/R/position-dodge.r#L85)..

**Comment by karawoo** [comment]
The new `position_dodge2()` function improves this by centering each group of bars (or boxes, etc.) at their x position.
