### ISSUE TITLE
geom_bin has white dots on the borders

### ISSUE THREAD

**Issue by idavydov** [tidyverse/ggplot2#2157]
When creating `geom_bin` plot, white dots are introduced between the bins. Is it possible to get rid of those?

The same is reproduced in the current master (f84e3158b4c38e33d279181c031bf82f8c69ec17) & current cran (2.2.1) versions on the latest R (3.4.0).

```r
library(ggplot2)
N=1000
d <- data.frame(x=rnorm(N), y=rnorm(N))
## png('hex.png')
ggplot(d, aes(x, y)) + geom_hex()
## dev.off()
```

![hex](https://user-images.githubusercontent.com/671660/27130702-aabd98e0-5107-11e7-8b63-6bc8afcd82da.png)

**Comment by idavydov** [comment]
While this looks like a bug to me, it seems there's a workaround. You can add border of the same color:

```r
library(ggplot2)
N=1000
d <- data.frame(x=rnorm(N), y=rnorm(N))
## png('hex.png')
ggplot(d, aes(x, y)) + geom_hex(col=..count..)
## dev.off()
```
![hex](https://user-images.githubusercontent.com/671660/27135547-0c317590-5119-11e7-8c31-32b21cfc85ad.png)

**Comment by karawoo** [comment]
I can't reproduce the white dots. When I run the first example I get a consistent light border around all the hexagons:

![hex](https://user-images.githubusercontent.com/4452678/27150294-82a8e83e-50fb-11e7-9c4f-9db3d81fb744.png)

**Comment by idavydov** [comment]
@karawoo I think it is OS and device specific.
It is reproduced on GNU/Linux with X11 or png device (two different machines, one with R 3.4.0, another with 3.2.3). But it cannot be reproduced if the pdf() device is used.
1. Could you reproduce this with GNU/Linux+X11?
2. If it is device specific, can this be an expected behavior for some devices?

**Comment by hadley** [comment]
Yeah, this is an issue with your graphics device so there's nothing ggplot2 can do about it.
