### ISSUE TITLE
Embedded fonts in PDF output

### ISSUE THREAD

**Issue by thvasilo** [tidyverse/ggplot2#2163]
Not sure if this is the correct place to report this, but thought I should mention it.

In many publication venues it is required that all PDF files have the fonts being used embedded in the PDF files themselves.

AFAIK the PDF files output from `ggsave` do not have their fonts embedded, requiring us to perform [an extra step](https://tex.stackexchange.com/a/109460) to ensure every figure (and consequently the final paper) has its fonts embedded in the file.

Is the PDF output part of  gpplot, or this is a more general problem with R graphics output?

**Comment by wch** [comment]
It's the behavior with graphics generated by R. If you have a document with many figures, and embed fonts in every figure, it can result in a very large document.

The `embedFonts` function can make this easier. Also see the `embed_fonts` function in the [extrafont](https://github.com/wch/extrafont) package.
