### ISSUE TITLE
ggplot legend for shape not displaying as expected

### ISSUE THREAD

**Issue by mjbock** [tidyverse/ggplot2#2167]
We appear to have found an issue with the legends for shapes. In the legend the shape four 'Source' appears but the shape for 'sample' does not appear in the output window. However, when we save to pdf the shape does appear as intended. If we save to png it does not. 
R version 3.4.0 (2017-04-21) -- "You Stupid Darkness"
Copyright (C) 2017 The R Foundation for Statistical Computing
Platform: i386-w64-mingw32/i386 (32-bit)
attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] ggplot2_2.2.1
Minimal example:
`library(ggplot2)
Dat<-data.frame(PC1=c(1,2,3,4,5),PC2=c(1,2,3,4,5),sz=c(1,2,3,4,5),Matrix=c(1,1,1,2,2),
  shp=c("Sample","Source","Sample","Source","Sample"))
  

p1a<-ggplot(Dat,aes(x=PC1,y=PC2,group=Matrix,size=sz,fill=Matrix,label=Matrix,shape=shp))+
  theme_bw()+geom_point(color="black",alpha=0.7) +#geom_text(color='grey20',alpha=0.60,size=2,hjust=0,vjust=0)+
  scale_size(guide=FALSE,range=c(2,4))+scale_shape_manual(values=c(24,21)) +
  guides(fill = guide_legend(override.aes = list(shape=21,size=3)))

p1a`

**Comment by karawoo** [comment]
I can't reproduce this issue; I see the shape for `Sample` the output window and in the png. Can you try creating another reproducible example (reprex) with the [reprex](https://github.com/tidyverse/reprex) package? If you need help, start by reading "[What is a reprex](https://github.com/jennybc/reprex#what-is-a-reprex)", and follow the advice further down the page.

**Comment by mjbock** [comment]
library(ggplot2)
Dat<-data.frame(PC1=c(1,2,3,4,5),PC2=c(1,2,3,4,5),sz=c(1,2,3,4,5),Matrix=c(1,1,1,2,2),
                shp=c("Sample","Source","Sample","Source","Sample"))

p1a<-ggplot(Dat,aes(x=PC1,y=PC2,group=Matrix,size=sz,fill=Matrix,label=Matrix,shape=shp))+
  theme_bw()+geom_point(color="black",alpha=0.7) +#geom_text(color='grey20',alpha=0.60,size=2,hjust=0,vjust=0)+
  scale_size(guide=FALSE,range=c(2,4))+scale_shape_manual(values=c(24,21)) +
  guides(fill = guide_legend(override.aes = list(shape=21,size=3)))

p1a

**Comment by mjbock** [comment]
In RStudio:
I pasted the reprex output above but the plot in the viewer has the triangles for samples.
The viewer window does not have the triangles but exports from the viewer do
In the RGui (not in R Studio):
The figure has no triangle. I export to png has no triangle, and export to pdf now has the triangle.

This is a very confusing issue. The png is attached (I think)
![temp](https://user-images.githubusercontent.com/4323192/27348974-cc2bbc44-55c3-11e7-9524-cea3136f7eb5.png)

**Comment by hadley** [comment]
This sounds like a problem with the device driver, which is unfortunately outside our remit.
