### ISSUE TITLE
Is it possible to add reverse= to position_dodge()?

### ISSUE THREAD

**Issue by jflycn** [tidyverse/ggplot2#2171]
Currently position_stack() has the reverse parameter to change the order of stacking, but this feature is not available in position_dodge().

One would need to reverse the order of dodging in a group bar chart when it is a horizontal bar chart with the vertical axis starts from the top to the bottom.

**Comment by hadley** [comment]
@karawoo maybe this would be worthwhile to add once you've finished this round of dodge changes?

**Comment by karawoo** [comment]
Yeah, I _think_ that everything is set up to handle this already and it'll just be a matter of adding the argument to `position_dodge()` and `position_boxdodge()`.
