### ISSUE TITLE
ggsave() for svg filetype does not work on MacOS Sierra

### ISSUE THREAD

**Issue by jzadra** [tidyverse/ggplot2#2177]
I'm trying to use ggsave() for a ggplot to save as an svg. When I do so, I get a fontconfig error. I have installed and updated both svglite and gdtools packages.

I'm on MacOS Sierra.

```
ggplot(diamonds, aes(x = cut, y = price)) + geom_boxplot() %>% 
ggsave(filename = "diamonds.svg")

Saving 11.6 x 5.32 in image
Error in match_family_(font, bold, italic) : 
  Fontconfig error: unable to match font pattern
```

**Comment by karawoo** [comment]
This seems like an issue with gdtools not being able to find system fonts. If you run `gdtools::sys_fonts()` is there any output? Have you tried any of the suggestions on [this thread](https://groups.google.com/forum/#!topic/reporters-package/9WP5uqP2hr8)? I can't reproduce the problem, but you might have better luck filing an issue with gdtools.

**Comment by jzadra** [comment]
Hi, sorry I forgot to update.  You are correct - there was no output, and this was solved by cleaning and pruning homebrew (already had it installed), then uninstalled cairo, reinstalled cairo, and deleting/reinstalling gdtools. It now lists all my system fonts and ggsave works perfectly for svg. Thank you!

https://stackoverflow.com/questions/44687409/ggsave-as-svg-fontconfig-error/44704015#44704015
