### ISSUE TITLE
scale_x_date passes NAs to the label function

### ISSUE THREAD

**Issue by ggrothendieck** [tidyverse/ggplot2#2182]
When using `scale_x_date(..., label = fun)`  it can be that NAs are passed to `fun` which adds undesirable complexity to the definition of the function.

See this example:
https://stackoverflow.com/questions/44616530/prevent-showing-the-year-several-times-unnecessarily-with-time-series/44751923#44751923

where this line had to be added to avoid errors even though the NAs do not actually correspond to breaks:

    b[is.na(b)] <- Sys.Date()

Any date could have been used in place of `Sys.Date()` since it seems that the date itself is not actually used if the passed break is NA.

**Comment by karawoo** [comment]
Could you please provide a minimal reproducible example using the [reprex](https://github.com/tidyverse/reprex) package? I'm having trouble reproducing the example from that SO link.

**Comment by ggrothendieck** [comment]
This fails with an error message.; howver, if you uncomment the line containing `Sys.Date()` then it works.  The problem seems to be that ggplot2 passes an NA to the `lab` function and one must provide a valid label for it even though ggplot2 never uses it.  ggplot2 should not pass these NA values to the label function.

````
    library(ggplot2)
    library(scales)

    # test input
    rng <- as.Date(c("1719-08-10", "1720-11-25"))
    dates <- seq(rng[1], rng[2], "day")
    df <- data.frame(Date = dates, value = seq_along(dates))

    lab <- function(b) {
      # b[is.na(b)] <- Sys.Date()
      format(b, ifelse(as.POSIXlt(b)$mon == 0, "%Y", "%b"))
    }

    ggplot(df, aes(Date, value)) + 
       geom_line() +
       scale_x_date(date_breaks = "month", labels = lab)
````

**Comment by hadley** [comment]
The root cause is that the breaks algorithm generates breaks that are outside of the limits, and these get converted to NAs.  It would be possible to fix this problem but it would require modifying code that I no longer understand and is probably not terribly well tested. Given that there's an existing work around (make sure your labelling function can handle NAs), unfortunately I don't think it's worthwhile to try and fix this bug.
