### ISSUE TITLE
geom_curve curvature argument as an aesthetic rather than as an argument

### ISSUE THREAD

**Issue by aetiologicCanada** [tidyverse/ggplot2#2183]
Currently geom_curve accepts an argument of curvature which is static within that function call. 
e.g: geom_curve(aes(... ) curvature=0.5)

It is also possible to imagine curvature as an aesthetic - thus something which could vary within a function call, e.g.

geom_curve(aes(x=Xvar, y=Yvar, xend=X2var, yend=Y2var, curvature=alive))

in this example were alive=0 for a record, this would yield a straight line between(Xvar, Yvar) and ( X2var, Y2var), and where alive=1 the line would be curved.

**Comment by hadley** [comment]
This seems like a good idea, but unfortunately it's not high enough on my priority list that I will implement it myself. However, I'd be happy to review a PR.
