### ISSUE TITLE
labs() doesn't inherit the dataframe

### ISSUE THREAD

**Issue by jenitivecase** [tidyverse/ggplot2#2185]
I find myself wanting to include summary statistics for the dataframe in the caption, but labs() doesn't inherit the dataframe. Here's an illustrative (albeit meaningless) example. 

An illustration of the mean:
```r
diamonds %>%
  group_by(carat) %>%
  summarize(ncolor = length(unique(color))) %>%
  ggplot(aes(x = ncolor)) + 
  geom_histogram(binwidth = 1) +
  geom_vline(aes(xintercept = mean(ncolor)))
```

But calculating the mean fails within labs():
```r
diamonds %>%
  group_by(carat) %>%
  summarize(ncolor = length(unique(color))) %>%
  ggplot(aes(x = ncolor)) + 
  geom_histogram(binwidth = 1) +
  geom_vline(aes(xintercept = mean(ncolor))) +
  labs(caption = paste0("Average Number of Colors for a Carat Amt  = "), mean(ncolor))
```

As this shows, geoms inherit the dataframe, making calculations of summary statistics from inherited variables possible, but labs() does not.

**Comment by hadley** [comment]
Yeah, you'll need to do the computation outside of `labs()`. I don't have any plans to add support for this in the near future.

**Comment by brianwdavis** [comment]
This has a fairly simple solution.

https://stackoverflow.com/questions/45088454/how-do-i-access-the-data-frame-that-has-been-passed-to-ggplot/45088522#45088522
