### ISSUE TITLE
Single colour specification, e.g. aes(..), colour = "black", overrides legend appearance

### ISSUE THREAD

**Issue by arthur-st** [tidyverse/ggplot2#2191]
Even if you specify just a single fill to have a coloured border, the legend will show all fills as having that border. Please find the reprex and the plot output below. R 3.4.0 (64-bit), RStudio 1.0.143, ggplot2 2.2.1.

```r
library(ggplot2)
library(lubridate)

txhm <- add_column(txhousing, dttm = date_decimal(txhousing$date, tz = "UTC"))

normal.plot <- txhm %>%
  ggplot(aes(x=dttm)) +
  geom_col(aes(y = listings, fill = "listings")) +
  geom_col(aes(y = sales, fill = "sales"))
normal.plot

blank.plot <- txhm %>%
  ggplot(aes(x=dttm)) +
  geom_col(aes(y = listings, fill = "listings")) +
  geom_col(aes(y = sales, fill = "sales"), colour = "black")
blank.plot
```
normal.plot:
![image](https://user-images.githubusercontent.com/29796606/27833037-a7ff551c-60d9-11e7-90d4-9f1acf5e9705.png)

overridden.plot:
![image](https://user-images.githubusercontent.com/29796606/27833045-b525c8ac-60d9-11e7-8d9b-2fdf621f1cb2.png)

**Comment by hadley** [comment]
For various reasons, this is unfortunately so complicated to fix that we'll never have time to do it.
