### ISSUE TITLE
`geom_sf()` return values of latitude and longitude for data in a projected coordinate system

### ISSUE THREAD

**Issue by Nowosad** [tidyverse/ggplot2#2200]
`geom_sf()` works well in case of data in a geographic coordinate systems - I give graticules and values of latitude and longitude. However, for data in a projected coordinate system, I would expect a plot with values in units of measurement (in this case in meters).
I think that as a default it should return graticules and values of latitude and longitude for data in a geographic coordinate systems and values in units of measurement for data in a projected coordinate system. Additionally, there should be an argument to change it.

``` r
library(sf)                                            
#> Linking to GEOS 3.5.0, GDAL 2.1.2, proj.4 4.9.2
library(ggplot2)                                       
                                                       
# decimal degrees                                      
nc = st_read(system.file("shape/nc.shp", package="sf"))
#> Reading layer `nc' from data source `/home/jn/R/x86_64-redhat-linux-gnu-library/3.4/sf/shape/nc.shp' using driver `ESRI Shapefile'
#> Simple feature collection with 100 features and 14 fields
#> geometry type:  MULTIPOLYGON
#> dimension:      XY
#> bbox:           xmin: -84.32385 ymin: 33.88199 xmax: -75.45698 ymax: 36.58965
#> epsg (SRID):    4267
#> proj4string:    +proj=longlat +datum=NAD27 +no_defs
                                                       
ggplot() +                                             
geom_sf(data = nc)                                     
```

![](http://i.imgur.com/Mf6aZDf.png)

``` r
                                                       
# meters                                               
nc_2163 = st_transform(nc, 2163)                       
                                                       
ggplot() +                                             
geom_sf(data = nc_2163)                                
```

![](http://i.imgur.com/BUTdZu2.png)

**Comment by hadley** [comment]
IIRC the labels just come from `sf::st_graticule()` so I think this change would have to happen there. Does that sound right @edzer?

**Comment by edzer** [comment]
I need to give this a bit more thought on what is the right user interface; this feels a bit like a hack. 

But right now, 
```r
ggplot() + geom_sf(data = nc_2163) + coord_sf(datum = st_crs(2163))
```
gives you
![x](https://user-images.githubusercontent.com/520851/28190746-bd6c4e00-682c-11e7-8a26-84c003c223a1.png)

I think it is not so bad this takes more effort to get, as, in contrast to long/lat, units of this kinds are pretty much meaningless to most people. Maybe it is easier if `datum=FALSE` or `datum=NULL` (or both) result in this kind of plot.

**Comment by hadley** [comment]
@edzer if you think this is a reasonable default, and there's already a work around, then I'm happy to leave as is.

BTW did you notice that the labels are getting formatted individually instead of collectively? (i.e. 2e+06 vs 1800000)

**Comment by edzer** [comment]
I think I'll go for the NULL or FALSE for `datum`, and will update the `coord_sf` documentation accordingly.

For the labels I used `as.character(values)` - what should I use instead?

**Comment by hadley** [comment]
`format()` might be better, but are you sure there's one call to `as.character()`? It looks like the result of `sapply(x, as.character)` vs `as.character(x)` to me

**Comment by edzer** [comment]
`as.character` on the whole vector (actually, on both) see https://github.com/r-spatial/sf/blob/master/R/graticule.R#L146

using `format` gives the one below, looks identical to me:
![xx](https://user-images.githubusercontent.com/520851/28217619-0ba6744a-68b6-11e7-8bf2-8ee8759ecc3a.png)

doing `c(format(lon), format(lat))` doesn't make things any better.

**Comment by hadley** [comment]
Oh, you're right! That's super weird:

```R
as.character(7:11 * 2e5)
#> [1] "1400000" "1600000" "1800000" "2e+06"   "2200000"
```

`format()` seems to help for me though:

```R
format(7:11 * 2e5)
#> [1] "1400000" "1600000" "1800000" "2000000" "2200000"
```

**Comment by edzer** [comment]
the parse loop to digest the degree symbols was the trouble maker.
