### ISSUE TITLE
Add model II regression with lmodel2 to stat_smooth

### ISSUE THREAD

**Issue by ewallace** [tidyverse/ggplot2#2201]
In ggplot2 it is very easy for me to plot a standard linear regression with lm, also with loess, glm etc.

```r
library(ggplot2)
ggplot(mpg, aes(displ, hwy)) +
  geom_point() +
  geom_smooth(method="lm")
```

However, I would like to just as easily be able to do model II regression when both x and y variables are noisy, like this:

```r
library(lmodel2)
ggplot(mpg, aes(displ, hwy)) +
  geom_point() +
  geom_smooth(method="lmodel2")
```

This doesn't work. As the wiki says, "Calculation is performed by the (currently undocumented) predictdf generic and its methods."

If predictdf could be implemented for lmodel2, that would be great. Alternatively, if you were able to document predictdf and how to write a predictdf method, I would do that in a fork and put in a pull request. And it would be easy for others to add methods in the future.

Thanks,
Edward

**Comment by hadley** [comment]
I don't think I want to support additional model methods for predictdf. I think it's generally better to fit the model outside of ggplot2 and generate the predictions yourself.

**Comment by ewallace** [comment]
Thanks for checking. It is a pity not to have a model ii regression fit easily accessible in ggplot.
