### ISSUE TITLE
geom_dotplot "count" axis is meaningless

### ISSUE THREAD

**Issue by pelotom** [tidyverse/ggplot2#2203]
`geom_dotplot` produces a "count" axis which as far as I can tell is meaningless; it just ranges from 0 to 1.

```r
ggplot(mtcars, aes(hp)) + geom_dotplot(binwidth = 10)
```

![dotplot1](https://user-images.githubusercontent.com/128019/28145245-909a986c-6725-11e7-9f5f-850bafbe04cc.png)

If rendering to a taller device, the rendered geometry stays the same but the y scale expands:

![dotplot2](https://user-images.githubusercontent.com/128019/28145281-df2804ba-6725-11e7-91ea-fda03a66af46.png)

This makes sense from the standpoint that we are rendering circular points whose diameter is determined by the `bindwidth` argument. But it's unfortunate that the y scale has no intrinsic meaning. It's inconsistent with histograms, where "count" means the number of items in a bin:

```r
ggplot(mtcars, aes(hp)) + geom_histogram(binwidth = 10)
```

![histogram](https://user-images.githubusercontent.com/128019/28145333-5fdcea12-6726-11e7-864d-68344ba34d76.png)

Couldn't the "count" scale for dotplots be used to mean how many dots are in a given column?

**Comment by has2k1** [comment]
For meaningful `dotplots`, the dimensions (height:width ratio of the panel) of the plot would have to be determined after the statistical computations.

A probable solution would be a warning in `geom_dotplot` that prints out the right ratio when the current ratio is wrong. The user would then change the panel dimensions accordingly. This is finicky stuff.

**Comment by wch** [comment]
From `?geom_dotplot`:

> When binning along the x axis and stacking along the y axis, the numbers on y axis are not meaningful, due to technical limitations of ggplot2. You can hide the y axis, as in one of the examples, or manually scale it to match the number of dots.

**Comment by kjhnav** [comment]
+ ylim(0,10) 
or something like that

**Comment by drwilkins** [comment]
Is this seriously not possible to fix? What a severe limitation...

**Comment by hnlmarcus** [comment]
The y-axis can be fixed by hackinging breaks and labels. If you get an integer number of dots to fit into the existing 4 breaks, you can just relabel them depending on the number of dots that fit. The length of y you can change by changing the binwidth and also you can redefine dot size and overlap.
