### ISSUE TITLE
Wrong SO link on website

### ISSUE THREAD

**Issue by nipunbatra** [tidyverse/ggplot2#2205]
SO links to: http://ggplot2.tidyverse.org/so
The link on the Github Readme is correct though.

<img width="1277" alt="screenshot 2017-07-14 12 39 09" src="https://user-images.githubusercontent.com/60985/28202133-a54fec5e-6891-11e7-8b63-b528060741e0.png">

**Comment by karawoo** [comment]
The [ggplot2-docs](https://github.com/tidyverse/ggplot2-docs) repo needs to be updated. @hadley what's the best way to do that? Run pkgdown within the ggplot2 repo, copy the results over into ggplot2-docs, and commit?

**Comment by hadley** [comment]
It's probably easiest for me to do. I'll add to my todo list

**Comment by andrewnguyen42** [comment]
Related: can the [themes link](https://github.com/tidyverse/ggplot2/wiki/Themes) get updated in the wiki?
