### ISSUE TITLE
`stat_summary_bin` expects some binning arguments (e.g., `bins`) but not others (e.g., `breaks`)

### ISSUE THREAD

**Issue by jwdink** [tidyverse/ggplot2#2214]
I'd like to pass "breaks" to stat_summary_bin, but this doesn't seem to work as expected, despite other binning arguments working.

``` r
set.seed(32)
library("ggplot2")
df <- data.frame(x = rnorm(1000), y = rnorm(1000))

ggplot(df, aes(x = x, y = y)) + stat_summary_bin(breaks = seq(-3, 3, by = 0.5))
#> Warning: Ignoring unknown parameters: breaks
#> No summary function supplied, defaulting to `mean_se()
#> Warning: Removed 1 rows containing missing values (geom_pointrange).
```

![](http://i.imgur.com/4RyrrSn.png)

``` r
ggplot(df, aes(x = x, y = y)) + stat_summary_bin(bins = 12)
#> No summary function supplied, defaulting to `mean_se()
```

![](http://i.imgur.com/D3jnHet.png)

**Comment by karawoo** [comment]
[`StatSummaryBin`](https://github.com/tidyverse/ggplot2/blob/331977e1d477a5e866b038fb2dd05e28ba86e50d/R/stat-summary-bin.R#L42-L45) takes `bins` and `binwidth` arguments, but not `breaks`. A workaround could be:

``` r
ggplot(df, aes(x = cut_width(x, 0.5, center = 0), y = y)) +
  stat_summary_bin()
```

![](http://i.imgur.com/FBEvKef.png)
