### ISSUE TITLE
Position = 'dodge' and stat = 'identity'

### ISSUE THREAD

**Issue by seancaodo** [tidyverse/ggplot2#2229]
t1 = tibble(type = c('a', 'b', 'c', 'a', 'a'), Quantity = c(100, 200, 150, 50, 75), fill=c('1','1','1','2','2'))
t1%>% ggplot() + geom_bar(aes(type, Quantity, fill=fill), stat='identity', alpha=0.5, position='dodge')  

Hi,

I would like to plot a dodge graph where bar height is the sum of _Quantity_ variable, it works when position is left to stack in one column for each _type_  

![image](https://user-images.githubusercontent.com/27996155/28867143-fa71eb8a-776c-11e7-9551-5b125f76a572.png)

but the two line sample codes above will show how it does not for position = 'dodge'. There are overlapping columns in _type_ 'a'.

![image](https://user-images.githubusercontent.com/27996155/28867162-099f8bda-776d-11e7-9a00-37029f140610.png)

How do I create the plot without overlapping columns in this case?

Many thanks,

Sean Do

**Comment by karawoo** [comment]
There's a new position function, `position_dodge2()` that will fix this issue. 

``` r
t1 %>%
  ggplot() +
  geom_bar(
    aes(type, Quantity, fill = fill),
    stat = 'identity',
    alpha = 0.5,
    position = 'dodge2'
  )
```

![](http://i.imgur.com/oNnsrMR.png)

See the `padding` and `preserve` arguments to `position_dodge2()` if you want to remove the space between bars or make the `b` and `c` bars take up more space.

**Comment by karawoo** [comment]
Forgot to mention that you'll need the development version of ggplot2 to use this.

```r
devtools::install_github("tidyverse/ggplot2")
```

**Comment by seancaodo** [comment]
Hi Kara,

Thanks for your reply, just finished the evening chores. I was hoping to get the two blue bars in _type_ a to stack up when they are in dodge position. I think that would make more sense for my particular case but I just realised now that no one would probably build such function..

**Comment by seancaodo** [comment]
So the other idea is to _group_by_, _summarise_ and _geom_col_

Kind regards,

Sean Do

**Comment by karawoo** [comment]
Ah I see, for that you'll need to calculate the values before passing them to ggplot.

```r
t2 <- t1 %>%
  group_by(type, fill) %>%
  summarize(Quantity = sum(Quantity))

ggplot(t2) +
  geom_bar(aes(type, Quantity, fill = fill), stat = 'identity', alpha = 0.5, position = 'dodge2')
```

**Comment by seancaodo** [comment]
That's correct. Thanks very much Kara 👍
