### ISSUE TITLE
Removed 1 rows containing missing values with log10 scale and correct limits

### ISSUE THREAD

**Issue by idavydov** [tidyverse/ggplot2#2234]
If I use scale_x_log10 with limits set, I get a warning message "Removed 1 rows containing missing values", even when all the values are in range.

```r
library(ggplot2)
qplot(runif(1000, 1, 10)) + scale_x_log10(limits=c(1e-10,1000))
#> `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
#> Warning: Removed 1 rows containing missing values (geom_bar).
```

**Comment by has2k1** [comment]
A bin at either end of the limit range is created with the `min` or `max` value that is outside the limits. Maybe you can influence this process with the `center` parameter. e.g.

```R
qplot(runif(1000, 1, 10), center=0) + scale_x_log10(limits=c(1e-10,1000))
```

**Comment by idavydov** [comment]
@has2k1 it seems you're right. And it also happens in a non-log scale:

```r
qplot(runif(1000, 1, 10), xlim=c(-1,1000))
```

Isn't it a bug in bin location estimation?

**Comment by has2k1** [comment]
> Isn't it a bug in bin location estimation?

Maybe considered so, but I think the solution would be elsewhere.

The limits are used to generate data that is outside the limits. Later on that data gets culled because it is outside the limits!

**Comment by idavydov** [comment]
@has2k1 sorry I don't quite understand.

In [this](https://github.com/tidyverse/ggplot2/issues/2234#issuecomment-321003623) code data is clearly within the limits: data is uniform [1;10], xlim is [-1;1000]. What exactly do you mean by saying "The limits are used to generate data that is outside the limits"?

**Comment by has2k1** [comment]
> The limits are used to generate data that is outside the limits

The data generated are the bins. e.g if your limits are `c(-1, 1000)` and you want 1000 bins, you may get the first bin as `(-1.5, 0.5]`, -1.5 is outside the limits.

**Comment by idavydov** [comment]
@has2k1 thanks. That's exactly what I mean when I write "bug in bin location estimation".

IMHO, if you have range `c(-1, 1000)`, the bins should be something like `seq(-1, 1000, length.out=bins)`, and should never go beyond these limits.

**Comment by has2k1** [comment]
>  the bins should be something like seq(-1, 1000, length.out=bins)

Other considerations and architecture make it more complicated, hence the edge-case that is this bug. But it is made avoidable by the `center` parameter of the `stat_bin`. Or you could use the `expand` parameter of the `scale` class.

**Comment by idavydov** [comment]
@has2k1 thanks a lot for your time & explanations.

Just two more things.
1. Sometimes `center` behaves non-intuitively. E.g.

```r
qplot(runif(1000, 1, 10), xlim=c(-1,1000), center=-1)
```

The warning message is gone, but the data is not plotted at all. I can open a separate bug.
![bug-ggplot-center](https://user-images.githubusercontent.com/671660/29121323-5ec5dd34-7d0e-11e7-89a9-f78b4c86a285.png)


2. If someone will stumble upon this behavior, I think you can also use `boundary=lower.limit`, not only `center`. Although in both cases I do not know how to compute the `center` value beforehand; perhaps the easiest is to use `breaks`:

```r
qplot(runif(1000, 1, 10), xlim=c(-1,1000), breaks=seq(-1, 1000, length.out=nbins+1))
```

And the same is possible in log-scale (although more tricky).

```r
qplot(runif(1000, 1, 10), breaks=seq(log10(1e-2), log10(1000), length.out=nbins+1)) +
    scale_x_log10(limits=c(1e-2,1000))
```

**Comment by karawoo** [comment]
This behavior is a bit confusing, but I think it is not a bug for the reasons @has2k1 described. Setting the `breaks` parameter with `seq()` seems like the right approach here.
