### ISSUE TITLE
geom_errorbar linetype overrides line types in legend

### ISSUE THREAD

**Issue by wkristan** [tidyverse/ggplot2#2236]
The problem occurs with multi-layer line graphs, in which the color and linetype are both
mapped to the same factor. If you plot without specifying a line type for the error bars
the legend correctly displays the combination of color and line type, but
the error bars are plotted using the line types, which doesn't look good.
Setting a solid linetype for the error bars makes them plot correctly, but then all of the line types
in the legend are solid, even though the plot still uses different line types. 

An example data set:

data <- data.frame(Day = rep(c(0,1,2,3,4), 4), mean = c(-0.06, 0.19, 0.38, 0.54, 0.67, 0.00, 0.18, 0.37, 0.51, 0.37, 0.00, 0.20, 0.42, 0.69, 1.17, 0.00, 0.08, 0.35, 0.44, -0.37),
                   combined = as.factor(c(rep("A",5), rep("B",5), rep("C",5), rep("D",5))))

data$lower <- data$mean - 0.1
data$upper <- data$mean + 0.1
                   

This first example doesn't set a line type for the error bars, 
which causes the error bars to use the line types of the lines. Dotted lines in error bars aren't desirable.

ggplot(data, aes(x = Day, y = mean, color = combined, linetype = combined)) +
  geom_line() +
  geom_errorbar(aes(ymin = lower, ymax = upper), width = 0.2) +
  theme_bw()

Setting the line type for the error bars makes them plot with solid lines, but then this
overrides the line types in the legend.

ggplot(data, aes(x = Day, y = mean, color = combined, linetype = combined)) +
  geom_line() +
  geom_errorbar(aes(ymin = lower, ymax = upper), width = 0.2, linetype = 1) +
  theme_bw()

The desired behavior is to have solid error bars, but legend entries that show the correct
line types. This can be achieved by overriding the line types with a guides() statement, like so:

ggplot(data, aes(x = Day, y = mean, color = combined, linetype = combined)) +
  geom_line() +
  geom_errorbar(aes(ymin = lower, ymax = upper), width = 0.2, linetype = 1) +
  theme_bw() +
  guides(linetype = guide_legend(override.aes = list(linetype = c(1,2,3,4))))

However, this should be unnecessary - line types of the error bars shouldn't 
override the line type of the lines.

**Comment by smouksassi** [comment]
why not avoid using a global aesthetics if you already know it does not apply to all layers?
see how below you can tell it to linetype specifically the geom_line  and to avoid coming up with a legend for errorbar by using show.legend=FALSE
```r
ggplot(data, aes(x = Day, y = mean, color = combined)) +
  geom_line(aes(linetype=combined)) +
  geom_errorbar(aes(ymin = lower, ymax = upper), width = 0.2, show.legend = FALSE) +
  theme_bw()
```

**Comment by karawoo** [comment]
@smouksassi's suggestion is the right way to approach this, in my opinion. If you only want the lines to have different line types, then that aesthetic should be set in `geom_line()`, not globally in the call to `ggplot()`. 

Incidentally though, setting `show.legend = FALSE` in `geom_errorbar()` also works in your last example, and eliminates the need for `guides()`.

I'm closing this as I think the current behavior is expected.

**Comment by wkristan** [comment]
I appreciate the alternative solutions, but this doesn't make sense to me.
I can understand that I erred in setting the linetype globally, but I don't
understand why then setting a linetype for the error bars affected the
legend. I've never seen error bar properties reflected in a legend before,
only properties of the data series. It seems that not showing error bar
properties in the legend should be the default (default to show.legend =
FALSE, not NA). If a user wants to reflect error bar properties in a legend
for some reason it would still be possible to do so, but I can't think of a
case in which I would want to.

**Comment by has2k1** [comment]
> It seems that not showing error bar
properties in the legend should be the default

There is a package level consistency that minimises surprises for every day users. `geoms` default to creating layers with `show.legend = TRUE`, and `annotations` create layers with `show.legend = FALSE`.
