### ISSUE TITLE
Proposal: theme-altering shortcuts

### ISSUE THREAD

**Issue by jonocarroll** [tidyverse/ggplot2#2237]
I love the thought that's gone into making `theme()` work so well - the inheritance, the structure, it's all really sophisticated and mature. 

I also forget how to change common things most of the time. I don't think I'm alone in having to look up how to rotate the `x` axis labels. Part of the reason for this is that the structure works against ease of use (we're supposed to be making it easier for the human, right?). RStudio will help a little way in auto-completing, but I still need to know that 

    theme(axis.text.x = element_text(angle = 90, vjust = 0.5))

is what I am aiming for. No doubt this is a hurdle to adoption for new users.

My proposal: a (likely quite long) list of shortcuts (in the style of the `magrittr` aliases listed under `?magrittr::extract`) to easily achieve 'common' recipes. In the case of the above example, a starting point might be

```
theme_label_x_vertical <- function(angle = 90, vjust = 0.5) {
  theme(axis.text.x = element_text(angle = angle, vjust = vjust))
}
```

This is certainly a) near trivial, and b) easily implemented in another package, but I would like to suggest that having this native in `ggplot2` would be of the most benefit. This would:

 - be available to the auto-complete system (with the right naming patterns)
 - have sensible argument defaults, but ones that can be specified if desired
 - be easier to recall
 - be available to be inspected in the console (not a method) to see exactly what it does.

Food for thought if nothing else. If it's not suitable for `ggplot2` then I'll put together an extension package.

**Comment by hadley** [comment]
I think this would be a great extension package!
