### ISSUE TITLE
old version installed

### ISSUE THREAD

**Issue by janvanoeveren** [tidyverse/ggplot2#2238]
We run install.packages("ggplot2") today (running R-3.2.2 on linux) and got some error messages and now we see it installed an old version 1.0.1
Any clue why this is?

**Comment by karawoo** [comment]
Did the errors occur when you ran `install.packages("ggplot2")`, or later?

**Comment by janvanoeveren** [comment]
Later, when trying to run minion_QC which requires ggplot2

**Comment by janvanoeveren** [comment]
fixed - ICT had set specific package version
