### ISSUE TITLE
I can't install packages demography 

### ISSUE THREAD

**Issue by bouch-ra** [tidyverse/ggplot2#2241]
> library(demography)
Loading required package: forecast
This is forecast 8.1 
  Crossvalidated is a great place to get help on forecasting issues:
  http://stats.stackexchange.com/tags/forecasting.
Loading required package: ftsa
Loading required package: rainbow
Loading required package: MASS
Loading required package: pcaPP
Error: package or namespace load failed for ‘rainbow’ in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):
 there is no package called ‘mime’
Error: package ‘rainbow’ could not be loaded

**Comment by karawoo** [comment]
This is the issue tracker for the ggplot2 package; it doesn't look like your issue is related to ggplot2, so I'm not sure I can help you very much. Have you tried `install.packages("mime")`?
