### ISSUE TITLE
ggplot2 hangs with byte strings

### ISSUE THREAD

**Issue by Enchufa2** [tidyverse/ggplot2#2243]
The other day I hit some kind of infinite loop while trying to plot a dataset with city names. I've found that the problem has something to do with the encoding, because it was a CSV created on Windows and, instead of `"París"` (in Spanish, with accent), the R data frame shows `"Par\xeds"`. I had no time to dig around, so I'm not sure what's going on here, but the reprex is pretty simple:

```r
ggplot2::qplot(x, y, data=data.frame(x="Par\xeds", y=1))
# the process hangs
```

**Comment by hadley** [comment]
This appears to be a grid issue. Minimal reprex:

```R
descentDetails(textGrob("Par\xeds"))
```

I'll pass it on to Paul Murrell
