### ISSUE TITLE
Same position_dodge2() for different width geom_bar() and geom_errorbar() doesn't match

### ISSUE THREAD

**Issue by ray-p144** [tidyverse/ggplot2#2251]
When using the same `position_dodge2()` with a `geom_bar()` and a `geom_errorbar()` that have different widths, the `geom_errorbar()` does not line up correctly with the `geom_bar()` like the first `position_dodge()` does. Not a major issue because increasing `padding` in the `position_dodge2()` of `geom_errorbar()`  produces the desired behavior. It makes sense that it is behaving this way because of the way everything is collapsed toward the middle, so please close this if it was expected behavior. 

```r
library(ggplot2)
packageVersion("ggplot2")
# [1] ‘2.2.1.9000’

df <- data.frame(
    trt = factor(c(1, 1, 2, 2, 2)),
    resp = c(1, 5, 3, 4, 5),
    group = factor(c(1, 2, 1, 2, 3)),
    upper = c(1.1, 5.3, 3.3, 4.2, 5.5),
    lower = c(0.8, 4.6, 2.4, 3.6, 4.4)
)

dodge2 <- position_dodge2(width = 0.9)

p <- ggplot(df, aes(trt, resp, fill = group, ymin = lower, ymax = upper))

# Using the same position_dodge2() with different width geom_bar() and geom_errorbar()
p +
    geom_col(position = dodge2) +
    geom_errorbar(aes(ymin = lower, ymax = upper), position = dodge2, width = 0.5)
```
![conflict](https://user-images.githubusercontent.com/16431187/29733615-44e91cd8-89ab-11e7-8b44-4294f3df7d78.png)

```r
# Increased padding with same width geom_bar() and geom_errorbar()
p +
    geom_col(position = dodge2) +
    geom_errorbar(aes(ymin = lower, ymax = upper), position = position_dodge2(width = 0.9, padding = .6))
```
![padded](https://user-images.githubusercontent.com/16431187/29733634-53b41b32-89ab-11e7-81d6-1bd8ba578596.png)

**Comment by karawoo** [comment]
Argh yeah, that is annoying and I don't think there is an easy way to force them to line up with `position_dodge2()` other than changing the padding.

**Comment by ray-p144** [comment]
No worries! Perhaps a note can be added in the documentation or in an example?

**Comment by hadley** [comment]
@karawoo would you have time to do a little example for the docs?

**Comment by karawoo** [comment]
Yeah will do!
