### ISSUE TITLE
facet_wrap() with geom_boxplot() not printing all combinations present in data frame

### ISSUE THREAD

**Issue by melohr** [tidyverse/ggplot2#2254]
### Description
When trying to plot a series of boxplots generated by `facet_wrap()`, not all combinations are present in the final graph. Complete code and data is provided in txt file.

### Incomplete Plot
``` r
# real dataset (buggyData)
ggplot(buggyData) + geom_boxplot(aes_string(x=factor(buggyData$Par2), y=buggyData$Var, fill="Par3"), na.rm=TRUE) + labs(x="", y="", title="Complete dataset with facet_wrap") + theme_bw() + ylim(c(0.7, 1.0)) + facet_wrap(~ buggyData$Par1)
```
![1234 buggydata facet_wrap variant 1](https://user-images.githubusercontent.com/31324076/29773703-d33ab618-8bfe-11e7-8d9e-d08c1e8e993c.png)

### Expected Plot
``` r
# artificial dataset (cleanData)
ggplot(cleanData) + geom_boxplot(aes_string(x=factor(cleanData$Par2), y=cleanData$Var, fill="Par3"), na.rm=TRUE) + labs(x="", y="", title="Complete dataset (cleanData) with facet_wrap") + theme_bw() + ylim(c(0.7, 1.0)) + facet_wrap(~ cleanData$Par1)
```
![1234 cleandata facet_wrap](https://user-images.githubusercontent.com/31324076/29773901-c0a677b6-8bff-11e7-8cb7-663675dad3c3.png)

### reprex code file
[ggplot2-boxplot-facet_wrap-bug.txt](https://github.com/tidyverse/ggplot2/files/1256750/ggplot2-boxplot-facet_wrap-bug.txt)

**Comment by smouksassi** [comment]
how about using this code
```r
ggplot(buggyData) + 
  geom_boxplot(aes_string(x="as.factor(Par2)", y="Var", fill="Par3"), na.rm=TRUE) +
  labs(x="", y="", title="Complete dataset with facet_wrap") + 
  theme_bw() + ylim(c(0.7, 1.0)) +
  facet_wrap(~ Par1)
```
you should not use data$var in ggplot2

**Comment by melohr** [comment]
Ups, you're completely right! In principle, I'm aware of this but in this case, for whatever reason, I missed it. This completely solves my problem.

However, this said, I still wonder why identical calls to ggplot result in the graphs shown above with two identical (in structure) and at the same time different (in terms of values) datasets. For my superficial insight, this exhibits at least _some_ kind of inconsistency and perhaps ugly pitholes for unaware users or careless mistakes.
In general, I personally must have absolute faith in the (statistics) tools I use. In this case, the difference is obvious. But I don't feel really comfortable having whatever doubt, the tool could deliver inconsistent results (better nothing/error than the former). Perhaps someone with more insight could have a deeper look and make this incredibly powerful and great package a bit more fail-safe.
