### ISSUE TITLE
unwanted reordering of facets

### ISSUE THREAD

**Issue by eeenilsson** [tidyverse/ggplot2#2257]
When using the method below to add an "all" facet to a facet_wrapped plot, the facets are reordered alphabetically and do not appear in the same order as the levels of the wrapping variable.

It would be good if there was some way to control the order of the facets in this situation (for example, one may prefer to have the "all" facet appear first.

```r
library(ggplot2)

p <- qplot(displ, hwy, data = transform(mpg, cyl = as.character(cyl)))
cyl6 <- subset(mpg, cyl == 6)
p + geom_point(data = transform(cyl6, cyl = "7"), colour = "red") +
  geom_point(data = transform(mpg, cyl = "all"), colour = "blue") +
  facet_wrap(~ cyl)

```
The method above was from : https://stackoverflow.com/questions/18933575/easily-add-an-all-facet-to-facet-wrap-in-ggplot2

**Comment by eeenilsson** [comment]
A workaround is to revalue the levels of the wrapping variable to alphabetically correspond to the desired order and then use a labeller function to recover the original labels to be displayed. See: https://stackoverflow.com/questions/3472980/ggplot-how-to-change-facet-labels

**Comment by smouksassi** [comment]
Here is the workaround on this example.
you are using three independent datasets so below I name the "all" zero so it comes first and then relabel with the labeller
```r
cyl6   <- subset(mpg, cyl == 6)
cyl6   <- transform(cyl6, cyl = "7")
cylall <- transform(mpg, cyl = "0")
cyl_values <- c(
  `0` = "all",
  `4` = "4",
  `5` = "5",
  `6` = "6",
  `7` = "7",
  `8` = "8"
)

ggplot(mpg, aes(displ, hwy) )+
  geom_point(data = cylall, colour = "blue") +
  geom_point() +
  geom_point(data = cyl6, colour = "red") +
  facet_wrap(~ cyl ,labeller = labeller(cyl = cyl_values))
```
another way to do the same plot  it will allow you to reorder across all datasets you want to use since you combine these datasets first. Also you will have a legend that you can supress if you don't want it.
```r
cyl6   <- subset(mpg, cyl == 6)
cyl6   <- transform(cyl6, cyl = "7")
cylall <- transform(mpg, cyl = "all")
plotdata<- rbind(cylall,mpg,cyl6)
plotdata$cyl <- factor(plotdata$cyl,levels=c("all","4","5","6","7","8"))
ggplot(plotdata, aes(displ, hwy,colour=cyl  ) )+
  geom_point() +
#geom_point(show.legend = FALSE) 
  scale_color_manual(values=c("blue","black","black","black","red","black","black"))+
  facet_wrap(~ cyl )+
  labs(colour="")
```

**Comment by hadley** [comment]
Just make a factor with the right levels

```R
library(ggplot2)
library(dplyr)

cyl_factor <- function(x) {
  factor(x, c("all", "4", "6", "7", "8"))
}

mpg <- mpg %>% mutate(cyl = cyl_factor(cyl))
mpg6 <- mpg %>% filter(cyl == 6)

ggplot(mpg, aes(displ, hwy)) + 
  geom_point() + 
  geom_point(data = mutate(mpg6, cyl = cyl_factor("7")), colour = "red") +
  geom_point(data = mutate(mpg6, cyl = cyl_factor("all")), colour = "blue") +
  facet_wrap(~ cyl)
```
