### ISSUE TITLE
Problems with plot area scaling in serial print

### ISSUE THREAD

**Issue by gordocabron** [tidyverse/ggplot2#2259]
Hi,

I just did a serial print of ggplot2 graphics and noted that depending on the letters used in the headline the plot area is scaled differently. If the title contains characters that drop below the baseline (e.g. "g" or "y") the plot area will begin a few points lower than with a title like "abc". For a serial print this is a somewhat undesired behaviour as this is easily noted when scroling through a set of slides with these serial plots on it.

```r
X <- data_frame(x = 1:10, y = 1:10)
p1 <- ggplot(X, aes(x = x, y = y)) + ggtitle("abc")
p2 <- ggplot(X, aes(x = x, y = y)) + ggtitle("abcefg")

p1
p2 ## <- plot area begins a few points lower than in p1
```

**Comment by hadley** [comment]
Unfortunately I can't see anyway to work around this problem.
