### ISSUE TITLE
legend.spacing.y error "only one operand may be a unit"

### ISSUE THREAD

**Issue by tjmahr** [tidyverse/ggplot2#2260]
This problem was first reported to us at stan-dev/bayesplot#106 for a user using a dev version of ggplot2 (tidyverse/ggplot2@c592e32). I troubleshooted the problem and came up with the following minimal example.

```r
library(ggplot2)
ggplot(iris) + 
  aes(Sepal.Length, Sepal.Width, color = Species) + 
  geom_point() +
  theme(legend.spacing.y = unit(1, "cm"))
#> Error in Ops.unit(theme$legend.spacing.y %||% 0.5, unit(title_height,  : 
#>  only one operand may be a unit
```

Adding ` theme(legend.spacing.x = unit(1, "cm"))` to the plot instead does not yield an error though.

**Comment by clauswilke** [comment]
This bug still exists for continuous color scales:

```
library(ggplot2)
ggplot(iris, aes(x=Sepal.Length, y=Sepal.Width, color=Petal.Width)) + 
  geom_point() +
  theme(legend.spacing.y = grid::unit(0.5, "cm"))

#  Error in Ops.unit(theme$legend.spacing.y %||% 0.5, unit(title_height,  : 
#   only one operand may be a unit 
```

The offending line is [here,](https://github.com/tidyverse/ggplot2/blob/505e4bfb9b9bd7b31f78c273963c46631895257a/R/guide-colorbar.r#L302) and the solution is the same (parentheses need to be added around the `0.5 * unit(title_height, "cm"`). I will prepare a pull request.
