### ISSUE TITLE
stri_unescape_unicode() with labels - Unicode characters problem

### ISSUE THREAD

**Issue by adambajguz** [tidyverse/ggplot2#2263]
There is a problem with subscripts, superscripts and maybe more Unicode characters added to: axis labels, titels, etc. using `stri_unescape_unicode()`.

When the default *sans* font (TT Arial) is used subscripts are change to rectangles. Also the *mono* font (TT Courier New) does not work correctly, here problem is even bigger, becuase also superscrips are not working. However, when the font was changed to *serif* (TT Times New Roman) everything works fine - as it is seen on second image.

---
**Example of buggy code:**
``` r

library(ggplot2)
library(stringi) #stri_unescape_unicode()

data(mpg, package="ggplot2")

y_label <- "\\u2082\\U2082\\u2083\\U2083\\U0042"

plot <- ggplot(mpg, aes(cty, hwy)) + geom_point() +
        labs(x = stri_unescape_unicode(gsub("\\U", "\\u", "\\u0041\\u2082\\U2082\\u2082\\U2076\\u2078", fixed = T)),
             y = stri_unescape_unicode(gsub("\\U", "\\u", y_label, fixed = T)) )

print(plot) # rectangles instead of subscripts
```
![](https://i.imgur.com/KAWQ78P.png)

``` r

plot <- plot + theme(text=element_text(family="serif"))
print(plot) # ok
```
![](https://i.imgur.com/EqtYY0i.png)

``` r

plot <- plot + theme(text=element_text(family="mono"))
print(plot) # rectangles instead of substripts & superscripts
```
![](https://i.imgur.com/DcaTRCw.png)

---

**Additional info:**
 * ggplot package version:	 2.2.1
 * stringi package version:  1.1.5
 * R version:                3.4.1
 * Platform:                 x86_64-w64-mingw32/x64 (64-bit)
 * Fonts used:
    ``` r
    windowsFonts()
    #> $serif
    #> [1] "TT Times New Roman"
    #>
    #> $sans
    #> [1] "TT Arial"
    #>
    #> $mono
    #> [1] "TT Courier New"
    ```

**Comment by hadley** [comment]
This is because the font you're using doesn't have glyphs for those code points. Unfortunately there's nothing that ggplot2 can do about of it.
