### ISSUE TITLE
Clarify the documentation of breaks in scale_*_date

### ISSUE THREAD

**Issue by jrvianna** [tidyverse/ggplot2#2268]
Just a small suggestion. The documentation of `scale_*_date` says that the `breaks` argument takes "A numeric vector of positions". Actually, if you provide a numeric vector there will be an error (`Error: Invalid input: date_trans works with objects of class Date only`). Naively, I tried vectors such as `c(2011, 2012)` or `c("2011-01-01", "2012-01-01") %>% as.Date %>% as.numeric` 🤦‍♂️.

The expected input for this argument is a Date vector (or I imagine a POSIXct or hms vector for other time scales). Surely with a few minutes of thinking and testing, this error can easily be solved, but I thought that if the documentation were clearer it could save some people some time. Thanks for the great package!

**Comment by foo-bar-baz-qux** [comment]
Agreed, the documentation should specify that `breaks` can be a vector of the same type as the x-values. It looks like it can also take the [same kind of string argument as `date_breaks`](https://github.com/tidyverse/ggplot2/blob/32e699e0bb6ff2be9212e32ad1f6b126bf225f18/R/scale-date.r#L239) for backwards compatibility.
