### ISSUE TITLE
Breaks Are Not Always Provided with log-scale

### ISSUE THREAD

**Issue by billdenney** [tidyverse/ggplot2#2269]
Y-axis scales are often unusable when the values are tight together and log-scaled.  In the example below, the first shows one tick mark, but someone who is looking at the figure would have no idea of the scale of the data.  In the second figure, due to the data, no breaks are shown, so the reader cannot have any idea of the scale.

Can the log-scale breaks (and any breaks) please ensure that at least two values are shown and preferably matching the number of breaks requested?

``` r
library(ggplot2)
# Not a very useful scale (is the top 10.1 or 90)?
ggplot(mtcars, aes(x = cyl, y = mpg)) + scale_y_log10() + geom_point()
```

![](https://i.imgur.com/yvjTleE.png)

``` r
mtcars_mod <- mtcars
mtcars_mod$mpg <- 10 + 80 * (mtcars_mod$mpg - 10)/max(mtcars_mod$mpg - 10)
# Y scale is missing
ggplot(mtcars_mod, aes(x = cyl, y = mpg)) + scale_y_log10() + geom_point()
```

![](https://i.imgur.com/WOVBPvx.png)

``` r
mtcars_mod2 <- mtcars
mtcars_mod2$mpg <- 10 + 0.01 * (mtcars_mod2$mpg - 10)/max(mtcars_mod2$mpg - 
  10)
# Y scale is missing, and looks identical to the above example even though
# the values are ~100-fold different.
ggplot(mtcars_mod, aes(x = cyl, y = mpg)) + scale_y_log10() + geom_point()
```

![](https://i.imgur.com/yPoddv8.png)

**Comment by has2k1** [comment]
This happens when all the data falls well between two powers of 10; i.e the ranges [(1, 10), (10, 100), (100, 1000), ...]. The real issue is in the scales package, specifically the interaction between `log_breaks` and `log_format` functions.
