### ISSUE TITLE
geom_jitter() adding more noisy points

### ISSUE THREAD

**Issue by Leoloh** [tidyverse/ggplot2#2271]
When I used geom_jitter() to handle overlapping points:
ggplot(data, aes(x = X ,y = Y)) + geom_point()+ **geom_jitter()**
the plot added more noisy points;

For example, the total observation of data was 20,  while the jittered plot gave 30 dotted points.

**Comment by smouksassi** [comment]
You added the points two times with geom_point and then with geom_jitter try to remove the call to geom_point
