### ISSUE TITLE
ggplot2 ERROR on solaris

### ISSUE THREAD

**Issue by tdhock** [tidyverse/ggplot2#2273]
Hey there, it seems that ggplot2 on CRAN has an ERROR on solaris https://www.r-project.org/nosvn/R.check/r-patched-solaris-x86/ggplot2-00check.html because of a test about date scales that does not pass. Do you have any plan to fix?

This is an issue for me because I have a package that imports ggplot2, and I would like to use rhub to check it on solaris before submitting it to CRAN. However rhub can not perform the check because the ggplot2 package is not available on solaris. Here is the related issue at rhub https://github.com/r-hub/rhub/issues/83

**Comment by hadley** [comment]
Probably not, since solaris is going away.
