### ISSUE TITLE
geom_path should support intermediate arrows

### ISSUE THREAD

**Issue by eamoncaddigan** [tidyverse/ggplot2#2280]
`geom_path()` supports the arrow argument, but this only adds an arrow to the end of the path.

```r
library(ggplot2)
set.seed(660124238)
plotDF <- data.frame(x = runif(6), y = runif(6))
ggplot(plotDF, aes(x, y)) + 
  geom_path(arrow = arrow())
```

If this geom supported intermediate arrows, it would be trivial to use ggplot2 to create [connected scatterplots](https://eagereyes.org/papers/the-connected-scatterplot-for-presenting-paired-time-series). It's currently possible--but cumbersome--to create connected scatterplots with `geom_segment()`.

```r
ggplot(plotDF, aes(x, y)) + 
  geom_segment(aes(xend = dplyr::lead(x), yend = dplyr::lead(y)),
               arrow = arrow())
```

If folks agree that this change is worth making, I'm not sure if it would be cleaner to implement this by passing a vector of arrow objects to the geom's arrow argument, or through changes to the arrow function.

**Comment by hadley** [comment]
This out of scope for ggplot2 since it would require a lot of work - it would be better to implement in an extension package instead.

**Comment by mikejacktzen** [comment]
I came across this same feature wish while making network plots

https://mikejacktzen.wordpress.com/portfolio/be-a-bigballr-in-rstats/

I guess an intermediate solution would be if `geom_segment()` or `geom_curve()` could return a set of discretized coordinates of the curve 

```
curve_id, x_1, y_1
```

that way the user can post process outside of ggplot2 to figure out which point in the set of coordinates they can use to add another geom layer 

In this case, pluck out the mid point and add a triangle or something
