### ISSUE TITLE
geom_density error when all groups are dropped

### ISSUE THREAD

**Issue by stla** [tidyverse/ggplot2#2282]
Hello, 

```
library(ggplot2)
dat <- structure(list(include = c(TRUE, TRUE, TRUE, TRUE, TRUE, TRUE
), Petal_Width = c(0.1234567, 1.4321, 1.5, 1.5, 1.3, 1.5), Species = c("setosa", 
"versicolor", "versicolor", "versicolor", "versicolor", "versicolor"
), Date = structure(c(1484524800, 1484611200, 1484697600, 1484784000, 
1484870400, 1485043200), class = c("POSIXct", "POSIXt"), tzone = "UTC")), .Names = c("include", 
"Petal_Width", "Species", "Date"), class = c("tbl_df", "tbl", 
"data.frame"), row.names = c(NA, -6L))
ggplot(dat, aes(x=Petal_Width)) + geom_density() + facet_wrap("Date")
```
This generates this error:
```
Error: Discrete value supplied to continuous scale
In addition: Warning messages:
1: Groups with fewer than two data points have been dropped. 
2: Groups with fewer than two data points have been dropped. 
3: Groups with fewer than two data points have been dropped. 
4: Groups with fewer than two data points have been dropped. 
5: Groups with fewer than two data points have been dropped. 
6: Groups with fewer than two data points have been dropped.
```

In fact, all groups are dropped. Then I think the error message is not very appropriate.

**Comment by karawoo** [comment]
In your example all of the groups (dates) only have a single data point, so I think the warning messages are accurate.

**Comment by stla** [comment]
Yes, exactly, the warnings are accurate, but not the error message.

**Comment by hadley** [comment]
Thanks for providing some code that illustrates the problem — it's a great start 😄 However, your code is currently a bit too complicated: there's quite a bit of extraneous stuff in there that doesn't seem directly related to the problem. Can you please try and simplify your example some more? The more minimal you can make the reprex, the faster I can identify the problem and fix it.

**Comment by hadley** [comment]
Minimal reprex:

```R
df <- data.frame(x = 1)
ggplot(df, aes(x)) + geom_density()
```

**Comment by hadley** [comment]
Fixed in https://github.com/tidyverse/ggplot2/commit/49619b77e25b51aed01ce1ab8967dfb090286e90
