### ISSUE TITLE
Coloured geom_dotplot Overlaps Dots

### ISSUE THREAD

**Issue by DarioS** [tidyverse/ggplot2#2285]
If colours are applied, then some dots are completely overlapping with other. Consider

```
plotData <- data.frame(group = rep(LETTERS[1:2], 3), score = rep(1:3, 2))
ggplot(plotData, aes(x = score, colour = group)) + geom_dotplot()
```

Simply changing `colour = group` to `colour = NULL` reveals that the plot contains six data points, not three. Also, the default y-axis title of "count" doesn't make sense since the y-axis values are decimals and not integers.

**Comment by ptoche** [comment]
I don't know. A quick look at the manual suggested: ``geom_dotplot(stackgroups = TRUE)``

Somewhat helpful: ``geom_dotplot(position = "dodge")`` 

http://ggplot2.tidyverse.org/reference/geom_dotplot.html

This one is pretty:

    ggplot(mtcars, aes(x = mpg, fill = factor(cyl))) +
      geom_dotplot(stackgroups = TRUE, binwidth = 1, binpositions = "all")

**Comment by wch** [comment]
From the `?geom_dotplot`:

> **binpositions**  When method is "dotdensity", "bygroup" (default) determines positions of the bins for each group separately. "all" determines positions of the bins with all the data taken together; this is used for aligning dot stacks across multiple groups.
>
> **stackgroups** should dots be stacked across groups? This has the effect that position = "stack" should have, but can't (because this geom has some odd properties).
>
>
> When binning along the x axis and stacking along the y axis, the numbers on y axis are not meaningful, due to technical limitations of ggplot2. You can hide the y axis, as in one of the examples, or manually scale it to match the number of dots.

The reason that it behaves differently from other geoms is because the dot stacking is relative to the visual width instead of the width in the data space, so it doesn't fit cleanly into the normal ggplot2 data processing pipeline.

**Comment by crispinhiley** [comment]
stackdir = "centerwhole"
