### ISSUE TITLE
API to get theme element

### ISSUE THREAD

**Issue by flying-sheep** [tidyverse/ggplot2#2287]
It would be great to have an exposed API that retrieves elements a from themes the same way as ggplot does, e.g.:

```r
theme_get_element(theme_get(), 'axis.title.x.top', 'color')
↓
t$axis.title.x.top$color %||%
t$axis.title.x$color %||%
t$axis.text$color %||%
t$text$color %||%
'black'
```

**Comment by hadley** [comment]
Would you be interested in doing a PR?

**Comment by flying-sheep** [comment]
i would if i knew how the fallback process works exactly. do you have any pointers?

**Comment by hadley** [comment]
No 😢 Presumably it is implemented somewhere already and it's just a matter of exposing it.

**Comment by flying-sheep** [comment]
OK, i’ll look for it, thank you

**Comment by hadley** [comment]
Looks like it's called `calc_element()` and it's already exported 😄

**Comment by flying-sheep** [comment]
great, thank you!
