### ISSUE TITLE
Boxplot is too narrow when used with facetting

### ISSUE THREAD

**Issue by Nekochef** [tidyverse/ggplot2#2290]
Boxplot is too narrow when used with faceting, and this issue never appears in 2.2.1 release.
I encountered this issue with a dataset similar to below:
```
va <- c(rnorm(10, 1, 1))
vb <- c(rnorm(10, 3, 1))
vc <- c(rnorm(10, 2, 1))
vd <- c(rnorm(10, 3, 1))

tf <- data.frame(
                 factor1 = rep(c('A', 'B'), each = 20,times=4),
                 factor2 = rep(c('A', 'B', 'A', 'B'), each = 10, times = 4),
                 factor3 = rep(c(LETTERS[1:4]), each = 40),
                 value = rep(c(va, vb, vc, vd), times = 4)
                 )

```
The plot below is with a discrete x-axis and a continuous y-axis:
```
ggplot(tf, aes(factor1, value)) +
    geom_boxplot(aes(fill = factor2)) +
    facet_wrap(~factor3, ncol = 2) +
    theme(aspect.ratio = 2 / 3)
```
And the plot produced:
![image](https://user-images.githubusercontent.com/22209183/31448897-1cc38886-aed8-11e7-9932-66c913611436.png)
The width of each boxplot is too narrow. This also happens when I use `facet_grid()`:
```
ggplot(tf, aes(factor1, value)) +
    geom_boxplot(aes(fill = factor2)) +
    facet_grid(.~factor3) +
    theme(aspect.ratio = 2 / 3)
```

![image](https://user-images.githubusercontent.com/22209183/31449051-7cabecc0-aed8-11e7-9c2c-2ffd827dd449.png)

If I remove `facet_wrap()`, the plot looks good:
```
ggplot(tf, aes(factor1, value)) +
    geom_boxplot(aes(fill = factor2)) +
    theme(aspect.ratio = 2 / 3)
```
![image](https://user-images.githubusercontent.com/22209183/31449255-01c21902-aed9-11e7-8e11-59ea80bb85d7.png)
If I increase `width`, the boxes are off the ticks:
```
ggplot(tf, aes(factor1, value)) +
    geom_boxplot(aes(fill = factor2), width = 2) +
    facet_wrap(~factor3, ncol = 2) +
    theme(aspect.ratio = 2 / 3)
```
![image](https://user-images.githubusercontent.com/22209183/31449403-6761c4a6-aed9-11e7-99bc-9ec66d64c7a9.png)

I don't know if it is a bug, or something internal changed from the 2.2.1 release. My original code works fine on release version, but has this issue on the dev version.

**Comment by karawoo** [comment]
This looks like a bug with the new `position_dodge2()` function that controls box plot placement in the dev version 😞 . A workaround is to use the `preserve = "total"` argument:

``` r
ggplot(tf, aes(factor1, value)) +
    geom_boxplot(aes(fill = factor2), position = position_dodge2(preserve = "total")) +
    facet_wrap(~factor3, ncol = 2)
```

![](https://i.imgur.com/h8GUDab.png)

**Comment by Nekochef** [comment]
Thanks! That solved the issue, Hoping for further improvement

**Comment by hadley** [comment]
@karawoo any ideas on the source of the bug? I can take a look if you can point me in the right direction.

**Comment by karawoo** [comment]
Actually I think it's not really a bug, but just a consequence of the fact that `position_dodge2()`'s `preserve` argument defaults to `"single"` whereas `position_dodge()` uses `"total"` by default. We could change the default for `position_dodge2()` to match `position_dodge()`. However this makes the default value incompatible with variable-width box plots, which need `preserve = "single"`.

**Comment by karawoo** [comment]
@hadley do you have an opinion on what the default behavior should be here? I can put together a PR.

**Comment by hadley** [comment]
The facetting shouldn’t affect the width - I think there should be enough information to avoid that? (But maybe I’m forgetting something)
