### ISSUE TITLE
Second axis doesn't appear when used with coord_map()

### ISSUE THREAD

**Issue by Nekochef** [tidyverse/ggplot2#2291]
This issue appears when I'm trying to plot a map with axes on all the sides.
Here is an example:
```
if (require("maps"))
    states <- map_data("state")
    arrests <- USArrests
    names(arrests) <- tolower(names(arrests))
    arrests$region <- tolower(rownames(USArrests))

    choro <- merge(states, arrests, sort = FALSE, by = "region")
    choro <- choro[order(choro$order),]
    ggplot(choro, aes(long, lat)) +
    geom_polygon(aes(group = group, fill = assault)) +
    coord_map("rectangular", 38) +
    scale_y_continuous(sec.axis = dup_axis()) +
    scale_x_continuous(sec.axis = dup_axis())

```
And the map looks like:
![image](https://user-images.githubusercontent.com/22209183/31492084-1bea1f48-af7c-11e7-8915-d48bb99fd137.png)
As you can see, the second axes only appear with their names but not their labels and ticks. 

It seems that this issue exists not only with coord_polar:> #2072.

And if I change `coord_map()` to `coord_quickmap()`:
```
if (require("maps"))
    states <- map_data("state")
    arrests <- USArrests
    names(arrests) <- tolower(names(arrests))
    arrests$region <- tolower(rownames(USArrests))

    choro <- merge(states, arrests, sort = FALSE, by = "region")
    choro <- choro[order(choro$order),]
    ggplot(choro, aes(long, lat)) +
    geom_polygon(aes(group = group, fill = assault)) +
    coord_quickmap() +
    scale_y_continuous(sec.axis = dup_axis()) +
    scale_x_continuous(sec.axis = dup_axis())
```
The code works fine:
![image](https://user-images.githubusercontent.com/22209183/31492410-69f9c7c8-af7d-11e7-9d61-2d16edcb817a.png)

**Comment by hadley** [comment]
Unforunately, dual axes are currently only supported with Cartesian coordinate systems.
