### ISSUE TITLE
Data with close points causes out of memory in geom_raster()

### ISSUE THREAD

**Issue by byapparov** [tidyverse/ggplot2#2294]
There is a problem in the `geom_raster` code where size of the raster matrix is calculated:

`x_pos <- as.integer((data$x - min(data$x)) / resolution(data$x, FALSE))`

Possible solution would be to force rounding of the x/y values to 2 or 3 digits, see:

https://stackoverflow.com/questions/46736309/r-ggplot-cant-allocate-big-vector/46737000#46737000

**Comment by hadley** [comment]
I think a fuller solution would consider non-gridded values in more details, and is currently out of scope.
