### ISSUE TITLE
Feature Request: Variable Width (Mekko ?) Bar Chart

### ISSUE THREAD

**Issue by timothyslau** [tidyverse/ggplot2#2298]
In Excel, there's a way to make the width of the bars vary with data in addition to the height:
https://www.dundas.com/Support/support-center/support-articles/data-visualizations/chart/how-to-create-a-variable-width-column-chart

I've found no straightforward way to do this in ggplot. This would add a functionality is common in business descriptive charts.

**Comment by karawoo** [comment]
This is doable with `geom_rect()`. Using the example from the blog post you listed:

``` r
library("ggplot2")

dat <- data.frame(
  Name = LETTERS[1:6],
  StartX = c(0, 82, 103, 115, 138, 145),
  EndX = c(82, 103, 115, 138, 145, 152),
  StartY = c(0),
  EndY = c(35, 22, 15, 14, 8, 7)
)

ggplot(dat, aes(fill = Name)) +
  geom_rect(aes(xmin = StartX, xmax = EndX, ymin = StartY, ymax = EndY))
```

![](https://i.imgur.com/JY9wxME.png)
