### ISSUE TITLE
Feature request: simple geom_boxplot 

### ISSUE THREAD

**Issue by ptoche** [tidyverse/ggplot2#2303]
I introduced a simple boxplot to students today and had to restrict myself to plain R boxplots, because the ``ggplot2`` syntax I know is IMHO too roundabout. 

The simplest boxplot appears to be something like this:

    x = 1:15
    df <- data.frame(x = x)
     ggplot(data = df, aes(x = factor(""), y = x)) +
     geom_boxplot() + 
     theme_minimal() + xlab(NULL)  #  simplify

By contrast, a decent boxplot in plain R can be obtained with:

    boxplot(x)

Questions: 

  **1. Is there a simple way to obtain a simple geom_boxplot()?**
  **2. May I suggest adding a "minimal boxplot" feature, if it is not currently available?**

Perhaps analogous to ``qplot`` something like ``qboxplot`` that would have the following syntax

    qboxplot(x, data = df)

Or allowing to set ``aes(x=x)`` without having to set an ``x`` value, and automagically removing the unwanted theme elements, e.g.:

    ggplot(data = df, aes(y = x)) + geom_boxplot(stat = "identityx")

(I know ``stat="identity"`` is already in use, so not sure if it can be recycled easily like that)

**Comment by foo-bar-baz-qux** [comment]
1) I think the example you have posted is about as simple as it currently allows. Setting x to a single factor is probably the simplest workaround:
```r
ggplot(mtcars, aes(x = '1', y = disp)) + geom_boxplot()
```

2) I've submitted a pull request to remove the requirement of an x aesthetic in `geom_boxplot()` that should help simplify the syntax for univariate box plots: #2110 and #2292.

**Comment by ptoche** [comment]
Great pull request! I agree with the points you make. One workaround might be to invoke the following theme elements every time a univariate boxplot is created: 

      theme(axis.ticks.x = element_blank(),
          panel.grid.major.x =  element_blank(),
          panel.grid.minor.x =  element_blank())
