### ISSUE TITLE
feature request: increase_fontsize()

### ISSUE THREAD

**Issue by BarkleyBG** [tidyverse/ggplot2#2308]
I'm requesting a function (e.g. `increase_fontsize()` or `bigger_text()`) that can be used interactively to quickly increase the font size of a graph. This could be extended for programmatic usage (explored below).

### Motivation

The motivating issue is when you plot your first graph and want to play with the font sizes and make the text bigger. I imagine that the most-often used way to do this is:
```
d <- ggplot(diamonds, aes(carat, price)) + 
   geom_point()

## works well, but not quick for the coder
d + theme( axis.title = element_text(size = 12))
```
This could be made a lot quicker. (How does one even know that the default theme size is 11 without [S/O ](https://stackoverflow.com/questions/11955229/how-to-change-the-default-font-size-in-ggplot2)?)

Perhaps better for quick workflow would be:
```
## make all titles, legends, axis text, etc one unit bigger
d + increase_fontsize()
```

### Implementation

The `increase_fontsize()` function would take in the values of the text sizes supplied by `d` and increase the font sizes by 1. I think this would be doable with `theme_set()` or `theme_update()`. Sorry, I'm not a ggplot2 wiz, so I can't say I have a solution for this right now.

### Optional arguments

Here's some examples of how this function could be made even more useful:
```
## make all titles, legends, axis text, etc 2 units bigger
d + increase_fontsize(by= 2)

## increase only the size of the titles
d + increase_fontsize(what = `titles`)
```

### Extension to programmatic usage

It is not necessarily the goal of the grammar of graphics to supply a hacky workaround for quick coding like I'm suggesting. But I think there's a good chance that this could be extended with the use of a second function that can be used to re-implement this programmatically. I'm calling this function `return_theme()`:

``` 
> d + increase_fontsize() + return_theme()
#
# function(){
#   theme(
#     axis.text.x = element_text(size=12),
#     axis.text.y = element_text(size=12),
#     legend.title = element_text(size = 12),
#     legend.text = element_text(size = 12),
#     ...[etc]...
#     axis.title.x = element_text(size=12),
#     axis.title.y = element_text(size=12)
#   ) 
# }
```

In this example, `return_theme()` is like `xtable()` in that it returns textual output. the user should copy-paste this output into a script and save it for later use. (NB: `return_theme()` could instead be a closure which returns a customized `theme()` function, but I don't know if this is as applicable for programmatic usage)

#### Possible new workflow?

Now, with these proposed functions, the user can initially find a "pretty good" text size by specifying relative sizes with `increase_fontsize()`. Then, once the user feels pretty good, they can output those settings with `return_theme()` and save it as a new function `my_theme()`. Of course, the thematic options in the guts of `my_theme()` could be adjusted at a later time if desired. 

As an example:

``` 
p1 <- d + increase_fontsize(by = 2) + 
    increase_fontsize(by = 2, what = "titles") + 
    increase_fontsize(by = 1, what = "axes") +
    increase_fontsize(by = 4, what = "caption")

p1 

## Looks good, so save the theme for later use

p1 + return_theme()
```

I would imagine that there are other great ways to make it easier for the user to quickly find the settings they're looking for, change them, and repeat programmatically. Perhaps this is food for thought? Thanks for reading!

**Comment by hadley** [comment]
The font size is already a parameter of the theme functions, so I don't think this belongs in ggplot2 itself, but would be great as an extension package.

**Comment by BarkleyBG** [comment]
Thanks for the feedback! 

Do you think `update_theme()` would be a good place to start? Or is there good documentation on working with the "guts" of ggplot2?

**Comment by hadley** [comment]
I think you'd be better of just using `theme()` and manually managing your own lists of font sizes.
