### ISSUE TITLE
ggsave does not pass units to dev() when device is passed as a function

### ISSUE THREAD

**Issue by cryanking** [tidyverse/ggplot2#2311]
ggsave intercepts the arguments dpi and units, but then does not pass them on to dev(). As a result, specified units are ignored and the device's default is used (eg width is in pixels). It works correctly when a text string is used for device instead of the function. 

 xdat <- data.frame(x=seq(10)/10, y= seq(10)/10)
gps <- ggplot(data=xdat, aes(x=x, y=y)) + geom_point()
ggsave(filename = "example1.jpg", plot = gps, width=5, height=5, units="in", dpi=150) ## works correctly
ggsave(filename = "example2.jpg", plot = gps, device="jpeg", width=5, height=5, units="in", dpi=150) ## works 
ggsave(filename = "example3.jpg", plot = gps, device=jpeg, width=5, height=5, units="in", dpi=150) ## 5 pixels wide

**Comment by hadley** [comment]
Could you please rework your reproducible example to use the [reprex package](http://reprex.tidyverse.org) ? That makes it easier to see both the input and the output, formatted in such a way that I can easily re-run in a local session.

**Comment by foo-bar-baz-qux** [comment]
Related to #2276.

**Comment by cryanking** [comment]
My bug is the same as #2276.

``` r
library('ggplot2')
xdat <- data.frame(x=seq(10)/10, y= seq(10)/10)
gps <- ggplot(data=xdat, aes(x=x, y=y)) + geom_point()
ggsave(filename = "example1.jpg", plot = gps, width=5, height=5, units="in", dpi=150) ## works correctly
ggsave(filename = "example2.jpg", plot = gps, device="jpeg", width=5, height=5, units="in", dpi=150) ## works
ggsave(filename = "example3.jpg", plot = gps, device=jpeg, width=5, height=5, units="in", dpi=150) ## 5 pixels wide
#> Warning in dev(file = filename, width = dim[1], height = dim[2], ...):
#> 'width=5, height=5' are unlikely values in pixels
```
![example1](https://user-images.githubusercontent.com/32458850/32190218-144cb266-bd7b-11e7-8420-58394a0f10b4.jpg)
![example2](https://user-images.githubusercontent.com/32458850/32190219-145dba84-bd7b-11e7-8fdf-27e46d72d182.jpg)
![example3](https://user-images.githubusercontent.com/32458850/32190220-1468bcae-bd7b-11e7-9620-9bc9785a8e8c.jpg)
