### ISSUE TITLE
aes() not working with +- Inf

### ISSUE THREAD

**Issue by christianhomberg** [tidyverse/ggplot2#2318]
Given a data.frame df:
`df <- data.frame(x = rnorm(10), y = rnorm(10))`

1) This works:

`ggplot(df) +
  geom_rect(ymin = -Inf, ymax = Inf,
            xmin = 1,
            xmax = 2)`

2) so does this:

`ggplot(df) +
  geom_rect(data = data.frame(ymin = 1, ymax = Inf,
                              xmin = 1,
                              xmax = 2),
            mapping = aes(ymin = ymin, xmin = xmin, ymax = ymax, xmax = xmax))`

3) but not this (i.e. it does not add the rectangle):

`ggplot(df) +
  geom_rect(data = data.frame(ymin = -Inf, ymax = Inf,
                              xmin = 1,
                              xmax = 2),
            mapping = aes(ymin = ymin, xmin = xmin, ymax = ymax, xmax = xmax))`

I can use `ymin = -Inf, ymax = Inf` if I put it directly into `geom_rect` but not if I put it in `aes`. I think both should work because they do slightly different things. For me this is problematic because `plotly` can't work with code 1) and complains that `xmin` can't be found. This looks like a bug in `plotly` which I don't expect to be solved anytime soon.

```
> sessionInfo()
R version 3.4.2 (2017-09-28)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 17.10

[1] plotly_4.7.1.9000    RPostgreSQL_0.6-2    DBI_0.7              scales_0.5.0.9000    gridExtra_2.3        gplots_3.0.1        
 [7] RColorBrewer_1.1-2   ggplot2_2.2.1.9000   zoo_1.8-0            DT_0.2               jsonlite_1.5         dplyr_0.7.4.9000    
[13] stringr_1.2.0        magrittr_1.5         data.table_1.10.4-3  shinyjs_0.9.1        shinydashboard_0.6.1 shiny_1.0.5  ```

**Comment by hadley** [comment]
That's because they do differently things - when set, +/- infinite refer to the bounds of the plot.
