### ISSUE TITLE
fillable shapes in legend always black

### ISSUE THREAD

**Issue by ulo** [tidyverse/ggplot2#2322]
In a scatterplot, when I map shape and fill as aesthetics (using fillable shapes, i.e. 21 to 25), the generated legend for fill is always black and does not represent the fill colors used in the plot.

```r
library(ggplot2)
d = data.frame(a=c(1,2), b=c('e','f'), c=c('x','y'))
ggplot(d, aes(x=a, y=a)) + 
  geom_point(aes(fill=b, shape=c), size=4) + 
  scale_shape_manual(values = c(21,22))
```
![index](https://user-images.githubusercontent.com/859893/32338907-658e1b42-bff6-11e7-8f6d-23307c701f13.png)

I would expect the legend for 'b' to be red and blue instead of all black.
Note: Setting the shape to 21 instead of mapping as aesthetic, the legend for fill works as expected.

I am using the latest version of ggplot2 (2.2.1), and I tend to believe that this was possible before, but maybe I am wrong.

**Comment by ptoche** [comment]
You haven't mapped color. Also you probably want factors if you don't want a color gradient. If I am not misunderstanding the issue, try omething like this:

    library(ggplot2)
    d = data.frame(a=factor(c(1,2)), b=c('e','f'), c=c('x','y'))
    ggplot(d, aes(x=a, y=a)) + 
        geom_point(aes(fill=b, shape=c, color=a), size=4) + 
        scale_shape_manual(values = c(21,22))

![rplot](https://user-images.githubusercontent.com/6339274/32479139-624f8198-c3c3-11e7-9fa3-f519a34f16b4.png)

**Comment by ulo** [comment]
Hi ptoche,
thanks for your input.
I use only fill because I want to keep the black border on the fillable shapes (for readability). Also, in your example, while you do get a proper color guide, the fill guide is still all black as in my original post.
I am totally happy with the plot in my original post, the problem is only that the legend does not reflect the fill aesthetics!

In the meantime, I did find I workaround by using a custom fill-guide definition with override.aes on shape:
```r
library(ggplot2)
d = data.frame(a=c(1,2), b=c('e','f'), c=c('x','y'))
ggplot(d, aes(x=a, y=a)) + 
  geom_point(aes(fill=b, shape=c), size=4) + 
  scale_shape_manual(values = c(21,22)) +
  guides(fill = guide_legend(override.aes=list(shape=21)))
```
![rplot](https://user-images.githubusercontent.com/859893/32484976-ff2f6d74-c3a1-11e7-82cf-3bb312fdab3f.png)

Looks like ggplot uses a non-fillable circle (probably shape 19) as default in the legend. When I manually override this to a fillable shape (e.g. shape 21) the fill values are reflected in the legend as well.

I still think this is a bug. Whenever fill is used as aesthetics in geom_point, this should happen automatically. This actually works automatically if I do not use shape as aesthetics, but only if I map both (fill and shape) the guide will use a non-fillable shape...

**Comment by ptoche** [comment]
In my reply I was only addressing the mapping, not trying to make a fully customized plot. I find getting the legends right very difficult as soon as you have several mapping at work. For instance, today I asked the following question: https://stackoverflow.com/questions/47155673/ggplot-legend-geom-abline-interference

Not fully happy with the hacking either, but most people make simple scatter diagrams and extending the ggplot capabilities is a lot of work.

**Comment by hadley** [comment]
This is technically a bug, but fixing it is extremely difficult because it's at a complicated intersection of concerns, so I think the best work around is what you've already figured out - manually override the shape used in the legend. 

Note that it already works if you set the shape, it's only the interaction with `scale_shape_manual()` that causes the problem:

``` r
library(ggplot2)
d <- data.frame(a = c(1, 2), b = c("e", "f"), c = c("x", "y"))
ggplot(d, aes(a, a)) +
  geom_point(aes(fill = b), size = 4, shape = 21)
```

![](https://i.imgur.com/u9JIqHT.png)
