### ISSUE TITLE
nudge_x works incorrectly with hjust="inward" or "outward"

### ISSUE THREAD

**Issue by mcol** [tidyverse/ggplot2#2329]
It seems that nudge_x doesn't respect the justification of the text, when this occurs with "inward" or "outward".

Here is without nudging:
```r
df <- data.frame(x = c(0, 2, 6), y = c(0, 4, 6), lab = c("Here is some text", 
  "Here is some other text", "And here some more text"))

ggplot(data = df, aes(x = x, y = y, label = lab)) +
   geom_line() +
   geom_text(hjust = "inward")
```
![](https://i.imgur.com/pJGsmy8.png)

And here with some horizontal nudge: for point at (6,6) I was expecting the text to be moved to the left, rather than to the right, as now it intersects the line:
``` r
ggplot(data = df, aes(x = x, y = y, label = lab)) +
   geom_line() +
   geom_text(hjust = "inward", nudge_x = 0.5)
```

![](https://i.imgur.com/srbQDoa.png)

**Comment by hadley** [comment]
I think technically this is correct because `nudge_x` moves 0.5 units to the right. Unfortunately I don't see any easy way specify that you want to nudge in the direction of the justification, so I think you'll have to do it yourself.

```R
df <- data.frame(x = c(0, 2, 6), y = c(0, 4, 6), lab = c("Here is some text", 
  "Here is some other text", "And here some more text"))

ggplot(data = df, aes(x = x, y = y, label = lab)) +
   geom_line() +
   geom_text(aes(x = x + ifelse(x > mean(x), -0.5, 0.5)), hjust = "inward")
```

Thanks for the reprex!
