### ISSUE TITLE
Lower limit to size argument in geom_path and geom_line (line thickness)

### ISSUE THREAD

**Issue by RafaRafa** [tidyverse/ggplot2#2330]
Similar question to #2275

When trying to make the line as thin as possible:
 ```
m <- ggplot(economics, aes(unemploy/pop, psavert))
m + geom_path(size = 0.05) ## same as below
m + geom_path(size = 0.5)  ## same as above
```
It seems we run into a lower limit.

**Comment by hadley** [comment]
They look different to me:

``` r
library(ggplot2)
m <- ggplot(economics, aes(unemploy/pop, psavert))
m + geom_path(size = 0.05) ## same as below
```

![](https://i.imgur.com/VUWXhtP.png)

``` r
m + geom_path(size = 0.5)  ## same as above
```

![](https://i.imgur.com/1HPmkrk.png)

That suggests the problem is with your graphics device/viewer.
