### ISSUE TITLE
Allow 'jitter' for position argument in geom_sf

### ISSUE THREAD

**Issue by rlionheart92** [tidyverse/ggplot2#2332]
Would it be possible to find add to allow 'jitter' for the position argument on geom_sf, specifically for 
points.

I have been working on a data set, where I am attempting to show the position and quality rating of different medical centres over a geographic map. Some of the centres share the same address, and therefore the points overlap. A slight jitter to the position of the points would be helpful in this case. I could potentially imagine other use cases where this might be of additional use.

When I try using the argument it returns the following error:

```r
map %>% 
+   ggplot() + 
+   geom_sf() +
+   geom_sf(data = ratings, aes(colour = overallRating),
+           position = 'jitter')

#> Error: position_jitter requires the following missing aesthetics: x, y
#> In addition: Warning messages:
#>  1: In min(x, na.rm = na.rm) :
#>  no non-missing arguments to min; returning Inf
#> 2: In max(x, na.rm = na.rm) :
#>   no non-missing arguments to max; returning -Inf
#> 3: In min(diff(sort(x))) : no non-missing arguments to min; returning Inf
#> 4: In min(x, na.rm = na.rm) :
#>   no non-missing arguments to min; returning Inf
#> 5: In max(x, na.rm = na.rm) :
#>   no non-missing arguments to max; returning -Inf
#> 6: In min(diff(sort(x))) : no non-missing arguments to min; returning Inf
```

**Comment by hadley** [comment]
Unfortunately this is out of scope for `geom_sf()` support. You'll need to manually jitter the points.
