### ISSUE TITLE
shiny R gantt chart with ggplotly configuration

### ISSUE THREAD

**Issue by sachinbanugariya** [tidyverse/ggplot2#2333]
i implemented ggplotly gantt chart, i need to do some changes i.e below:
- for ggplot y axis we want labels inside plot and at the end of every gantt bar, i tried using label parameter, but issue was because of long x axis period not seems whole name at the end and seems overlapped name.
- need to add scroll bar for gantt chart ggplotly, because we want to show all days of months at axis on x, so because of much data it will be overlapped and not seems good, so need to add scroll bar at bottem like data table view.

actually we are trying to make same gantt chart as same as like redmine gantt.

please suggest me how can i do this two things with ggplotly ASAP. 
thanks

**Comment by batpigandme** [comment]
Hi @sachinbanugariya,

This isn't really an issue so much as a question, which means it would be better fielded over on the RStudio Community site or any of the places listed in the [Where to ask](https://www.tidyverse.org/help/#where-to-ask) section of the tidyverse help page.

I also think this is more of a _plotly_ question than a ggplot2 one, so it's a bit out of scope here. Thanks!
