### ISSUE TITLE
ggplotly based gantt chart responce time is too much slow

### ISSUE THREAD

**Issue by sachinbanugariya** [tidyverse/ggplot2#2335]
hello,
we implement gantt chart based on ggplotly,
but the issue is its take too much time for give output for plot,
can anyone suggest how can we improve the responce time of ggplotly gantt chart.
thanks.

**Comment by batpigandme** [comment]
Hi @sachinbanugariya.
This would actually be a question for the maintainers of the R package for plotly! 
https://github.com/ropensci/plotly
That said, unless it's a bug in the package itself, you might have better luck asking about it over on StackOverflow or on community.rstudio.com!

Hopefully this helps.

I'll be closing the issue, as it's out of scope!
