### ISSUE TITLE
How can I force ggplot to show more levels on the legend?

### ISSUE THREAD

**Issue by skanskan** [tidyverse/ggplot2#2339]
I'm trying to create a complex ggplot plot but some things don't work as expected.

I have extracted the problematic part, the creation of points and its associated legend.

    library(data.table)
    library(ggplot2)
    lev <- c("A", "B", "C", "D") # define levels.
    bb <- c(40, 30,20,10,5)/100 # define breaks.
    ll <- c("40%","30%","20%","10%","5%") # labels.
    # Create data
    nodos <- data.table(event = c("A", "B", "D", "C", "D"), ord = c(1, 2, 3, 3, 4),
    NP = c(0.375, 0.25, 0.125, 0.125, 0.125))

    
    ggplot() + geom_point(data=nodos,aes(x=ord, 
     y=event, size=NP), color="black", shape=16) +
     ylim(lev)  + scale_size_continuous(name="Prop.",
     breaks=bb, labels=ll, range=c(0,6))+ 
     scale_x_continuous(limits=c(0.5, 4.5),
     breaks=seq(1,4,1))

![plot](https://i.stack.imgur.com/kVIgo.jpg)

As you can see, no matter what breaks and labels I use I'm not able to force ggplot to paint a legend containing 0% or 10%. 
scale_size_continuous keeps creating just two elements.  
And the smaller points are very badly scaled.

I have also tried with scale_scale_area, but it doesn't work either.

I'm using R 3.4.2 and ggplot2 2.2.1 (also tried the latest github version).

How can I get it?

I have also asked this at 
https://stackoverflow.com/questions/47335132/how-can-i-force-ggplot-to-show-more-levels-on-the-legend

And somebody told me to use a trick, convert the size to factor.  That generates the legend but the size of the points is not related to the value anymore.
ggplot() + geom_point(data=nodos,aes(x=ord, y=event, size=factor(NP)), color="black", shape=16).

**Comment by hadley** [comment]
You need to set the breaks, not the limits.

This sort of question is a better fit for <https://community.rstudio.com>. I'd recommend asking over there for similar questions in the future (You might want to read <https://www.tidyverse.org/help/> first to maximise your chances of getting a good answer)

**Comment by skanskan** [comment]
Yes, I've set the breaks, but they are ignored.
