### ISSUE TITLE
geom_vline() behavior when using coord_trans() with custom transformation

### ISSUE THREAD

**Issue by gjabel** [tidyverse/ggplot2#2340]
I am trying to use a [log-modulus transformation](https://blogs.sas.com/content/iml/2014/07/14/log-transformation-of-pos-neg.html) in my plot...

```r
library(tidyverse)
library(scales)

log_modulus_trans <- function() 
  trans_new(name = "log_modulus", 
            transform = function(x) sign(x) * log(abs(x) + 1), 
            inverse = function(x) sign(x) * ( exp(abs(x)) - 1 ))

# fake data
set.seed(1)
d <- data_frame(
  tt = rep(1:10, 3),
  cc = rep(LETTERS[1:3], each = 10),
  xx = c(rnorm(10, mean = 100, sd = 10), 
         rnorm(10, mean = 0, sd = 10),
         rnorm(10, mean = -100, sd = 10)))

ggplot(data = d, 
       mapping = aes(x = tt, y = xx, group = cc)) +
  geom_line() + 
  coord_trans(y = "log_modulus")
```
![rplot01](https://user-images.githubusercontent.com/2735201/32956997-76abbb72-cbf5-11e7-97ac-ef1194522b68.png)
When I tried to add a geom_vline() things got weird...
![rplot](https://user-images.githubusercontent.com/2735201/32957033-87402a40-cbf5-11e7-89c9-b4e8e5a3e3ae.png)

**Comment by has2k1** [comment]
Related to #2149.
