### ISSUE TITLE
Feature request: like a violin plot but a histogram

### ISSUE THREAD

**Issue by traversc** [tidyverse/ggplot2#2341]
I'd like something like this:

![histogram](https://i.stack.imgur.com/HrtS7.png)

From here: https://stackoverflow.com/questions/15846873/symmetrical-violin-plot-like-histogram

I have data that is discrete rather than continuous, so I'd like to visualize it as a histogram rather than a density.

**Comment by hadley** [comment]
Unforuntately ggplot2 is no longer adding new geoms, but what you want looks very similar to a letter value plot which can be drawn with https://cran.r-project.org/web/packages/lvplot/index.html
