### ISSUE TITLE
Feature Request: Two  legends with sizes

### ISSUE THREAD

**Issue by skanskan** [tidyverse/ggplot2#2342]
Please, add the ability to properly have two legends with the same concept, for example two legends related to the size.

If I run this simple code
```
DF <- data.frame(x=c(1,2,3,4), y=c(1,2,3,4), 
z=c(3.4,1.2,1.1,0.5))
ggplot() + geom_segment(data=DF, aes(x=x, y=y, 
xend=x+1, yend=y+1, size=z/10 ), colour="blue") +
geom_point(data=DF,aes(x=x, y=y, size=z)) +   
scale_size_continuous(name="size")
```
I get the legend for two variables that define sizes but they overlap and they are unusable.
![Example](https://i.imgur.com/k9JMaps.jpg)

I have also tried using 
`+scale_size_continuous(name="size1") + scale_size_continuous(name="size2")`
But it generates an error.

**Comment by hadley** [comment]
This sort of question is a better fit for <https://community.rstudio.com>. Do you mind asking it over there? (You might want to read <https://www.tidyverse.org/help/> first to maximise your chances of getting a good answer)

**Comment by skanskan** [comment]
OK, but I don't understand what does it have to do with rstudio, I thought this is ggplot2's github page.

**Comment by batpigandme** [comment]
What you've described is possible with ggplot2. By no means do you _have_ to go to the community site to get help, it's just one place where you _can_. This is described in more detail in the [Where to Ask](https://www.tidyverse.org/help/#where-to-ask) portion of the help section on tidyverse.org (which hadley referenced above as well). 

I just sent you a few references to help over on the community site. Hopefully these will get you rolling in the right direction. 👍
