### ISSUE TITLE
Update NSE to rlang so quosures work

### ISSUE THREAD

**Issue by alistaire47** [tidyverse/ggplot2#2347]
Hi! It would be really useful if we could write:

``` r
library(ggplot2)

plot_stuff <- function(data, x, y){
    x <- enquo(x)
    y <- enquo(y)
    
    ggplot(data, aes(x = !!x, y = !!y)) + geom_point()
}
```
instead of
```r
plot_stuff <- function(data, x, y){
    ggplot(data, aes_(substitute(x), substitute(y))) + geom_point()
}

plot_stuff(data.frame(foo = 1:10, bar = 1:10), foo, bar)
```
which becomes particularly important if the function also uses quosure-enabled parts of the tidyverse in it as well, as mixing NSE systems gets more than a little confusing for users.

A look at `aes.r` shows that it defines its own NSE system with `match.call` and an S3 class called `uneval`. Refactoring the code to create the `uneval` object with rlang would pretty much only require altering `aes.R`, assuming the structure of that object remains a list of atomic expressions. As a side benefit, `aes_`, `aes_q`, and `aes_string` would all become unnecessary, though it seems wise not to deprecate `aes_string`.

**Comment by alistaire47** [comment]
A proposal:
```r
aes <- function(x, y, ...) {
  x <- if (!missing(x)) list(x = rlang::quo_expr(rlang::enexpr(x)))
  y <- if (!missing(y)) list(y = rlang::quo_expr(rlang::enexpr(y)))
  dots <- rlang::exprs(...)
  
  aes <- structure(c(x, y, dots), class = "uneval")

  rename_aes(aes)
}
```

Details: 
- The `missing` structure is necessary to handle when `x` or `y` is missing
- `list` is to maintain explicit `NULL`s
- `rlang::quo_expr` is to convert any quosures passed in into expressions
- `c` is to flatten the `x` and `y` lists (or `NULL`s, if they're not passed) into the list created by `rlang::exprs`

It functions well as far as I've tested it, including passing all the tests in `test-aes.r`. (One of the tests in `test-stat-bin.R` fails, but that seems to be because the `out` function defined on line 17 has an extra `x` parameter that isn't supplied.)

Limitations:
- Because `x` and `y` are handled separately, unquote-splicing only works in `...`. Thus far I haven't found a way around that while keeping `x` and `y` parameters.

Proper documentation and testing of the new unquoting possibilities should be added, too. If this is the way the maintainers want to go, I'm happy to assemble it into a proper pull request.

**Comment by hadley** [comment]
Yes, this is on the todo list, no need for an issue.  It's a big change because it requires fixes to evaluation throughout ggplot2.
