### ISSUE TITLE
Inverted y-axis strip text angle with facet_grid(...switch = "both")

### ISSUE THREAD

**Issue by grantmcdermott** [tidyverse/ggplot2#2356]
I'm running the latest dev version of ggplot2 (2.2.1.9000). Going straight from the [docs](http://ggplot2.tidyverse.org/reference/facet_grid.html):

```r
data <- transform(mtcars,
  am = factor(am, levels = 0:1, c("Automatic", "Manual")),
  gear = factor(gear, levels = 3:5, labels = c("Three", "Four", "Five"))
)
p <- ggplot(data, aes(mpg, disp)) + geom_point()
p + facet_grid(am ~ gear, switch = "both")
```
This gives me the following, where you can see that the y-axis facet strip text ("Automatic" and "Manual") is inverted compared to the documented example.

![inverted_strip_text](https://user-images.githubusercontent.com/10285037/33541954-eebc93e2-d885-11e7-9cd4-9ad215dda4a5.png)

Of course, an easy manual fix  is to simply add ` + theme(strip.text.y = element_text(angle = 90))` to the above. I imagine that the previous behaviour is still the desired default, though.

**Comment by karawoo** [comment]
This is a bug introduced in the [titleGrob() refactor](https://github.com/tidyverse/ggplot2/pull/2232/) – the strips labels are no longer having their angle adjusted in `build_strip()`. I'll PR a fix.
