### ISSUE TITLE
scale color gradient bar too short for all values

### ISSUE THREAD

**Issue by andzandz11** [tidyverse/ggplot2#2360]
The maximum value tick is outside of the colour bar.
I don't know why though. Other users executing the same code have a different outcome.
I tried RStudio and Rgui.

```r
library(ggplot2)

conf <- c(0, 1, abs(rnorm(1000, mean = 0.65, sd = 0.1)))
conf <- conf[conf <= 1]
fam <- sample(1:50, length(conf), replace = T)
dat <- cbind.data.frame(fam = fam, conf = conf)

ggplot(dat=dat,aes(x=fam,group=fam)
) + geom_jitter(
  aes(y=conf,color=conf)
) + scale_color_gradientn (
  colors=c("red","blue")
) + theme (
legend.background = element_rect(colour="red",fill="black"),
legend.text= element_text(colour="white",size=10),
)




```
![clipboard01](https://user-images.githubusercontent.com/19622117/33671141-21646a7c-daa7-11e7-8b06-fd279eb3087f.jpg)

for another example see: https://github.com/tidyverse/ggplot2/issues/2359#issuecomment-349662555

R version 3.4.2 (2017-09-28)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 16299)

executing this code for example gives me:
https://github.com/tidyverse/ggplot2/issues/2359#issuecomment-349677043

![clipboard01](https://user-images.githubusercontent.com/19622117/33671394-c8b5e378-daa7-11e7-8712-f99940f5a5b3.jpg)

Maybe a Windows issue? All packages are up to date. This issue persits if i export as pdf(...) for example.

**Comment by batpigandme** [comment]
This should be fixed by https://github.com/tidyverse/ggplot2/pull/2346
