### ISSUE TITLE
add alpha levels to scale_*_gradientn

### ISSUE THREAD

**Issue by andzandz11** [tidyverse/ggplot2#2361]
---
I fail to add alpha to a gradient legend scale. I think that would be a useful feature to support alpha=x inside a legend definition or inherit it from aes. Thanks!

```r
conf <- c(0, 1, abs(rnorm(1000, mean = 0.65, sd = 0.1)))
conf <- conf[conf <= 1]
fam <- sample(1:50, length(conf), replace = T)
dat <- cbind.data.frame(fam = fam, conf = conf)

ggplot(dat=dat,aes(x=fam,group=fam)
) + geom_jitter(
  aes(y=conf,color=conf,alpha=0.05),
  alpha=0.05
) + scale_color_gradientn (
  colors=alpha(c("#00007F", "blue", "#007FFF", "red","#7F0000"),0.05)
) + theme (
legend.background = element_rect(colour="red",fill="black"),
legend.text= element_text(colour="white",size=10),
) 

```

![clipboard01](https://user-images.githubusercontent.com/19622117/33674215-23991722-daaf-11e7-866d-fe43a2f4b907.jpg)

**Comment by batpigandme** [comment]
Related to #2345

**Comment by batpigandme** [comment]
@andzandz11 , closing this as it's covered in #2345

**Comment by clauswilke** [comment]
I don't think this is related to #2345. (I'm the poster of that issue.) The real problem is that `scale_color_gradientn()` strips the alpha information from the provided colors. This can be traced to a default setting in `scales::colour_ramp` of `alpha = FALSE` that I think should be changed to `alpha = TRUE`.

Example:

```
# change the default setting of scales::colour_ramp:
assignInNamespace("colour_ramp", function(colors, na.color = NA, alpha = TRUE){
  if (length(colors) == 0) {
    stop("Must provide at least one color to create a color ramp")
  }
  colorMatrix <- grDevices::col2rgb(colors, alpha = alpha)
  structure(function(x) {
    scales:::doColorRamp(colorMatrix, x, alpha, ifelse(is.na(na.color), 
                                              "", na.color))
  }, safe_palette_func = TRUE)
}, "scales")

# make plot with gradient colors that have alpha values
conf <- c(0, 1, abs(rnorm(1000, mean = 0.65, sd = 0.1)))
conf <- conf[conf <= 1]
fam <- sample(1:50, length(conf), replace = T)
dat <- cbind.data.frame(fam = fam, conf = conf)

ggplot(dat=dat,aes(x=fam,group=fam)) + 
  geom_jitter(aes(y=conf, color=conf)) + 
  scale_color_gradientn(colors=alpha(c("#00007F", "blue", "#007FFF", "red","#7F0000"), 0.5)) + 
  theme(legend.background = element_rect(colour="red",fill="black"),
        legend.text= element_text(colour="white",size=10)) 
```

<img width="633" alt="screen shot 2017-12-19 at 10 53 55 am" src="https://user-images.githubusercontent.com/4210929/34168745-f6537eb4-e4aa-11e7-917d-8ccf7da61169.png">

I frequently set alpha values directly in the colors, since that give me more flexibility in many contexts than the ggplot2 `alpha` option provides, so this is an issue that has bugged me for a long time. I hope it can be addressed.

**Comment by batpigandme** [comment]
Ah, thanks for clearing this up, @clauswilke! So the `alpha` arg exists and works in those other cases, but _not_ in their scales bc of the import from `scales` (the package). OK, I'm gonna reopen this, as it sounds distinct! Thanks.

**Comment by clauswilke** [comment]
> Issue to scales, instead? 

Yes, I think the default should be `alpha = TRUE` in the line you highlight. Alternatively a similar `alpha` argument could be added to the functions that end up calling `color_ramp()`, but that seems more effort than is worth. I don't see any obvious downsides from by default respecting alpha values when they are provided. Most people don't provide alpha values in colors anyways.

**Comment by clauswilke** [comment]
I opened an issue for scales, with a clearer example case.
https://github.com/hadley/scales/issues/108

**Comment by clauswilke** [comment]
I also provided a pull request, but it turns out there's some subtleties that need to be thought through carefully. Should `colour_ramp()` always return RGBA? Or should it make a smart guess about what is expected? https://github.com/hadley/scales/pull/109

**Comment by clauswilke** [comment]
I think all the conceptual issues for the pull request are resolved, and now the remaining question is whether it causes any downstream problems. I *think* there won't be any problems, but it would be good to have some independent verification.

Specifically, do the ggplot2 visual tests pass with the patched scales library? They don't pass on my machine even with scales 0.5.0, so I can't certify that nothing will break.

My patched version of scales is available [here](https://github.com/clauswilke/scales) if anybody wants to try it. Install with

```
devtools::install_github("clauswilke/scales")
```

With the patched scales library, this command:
```
ggplot(iris, aes(Sepal.Length, fill = as.numeric(Species), group = Species)) + 
  geom_density() +
  scale_fill_gradientn(colors = c("#00FF00FF", "#008000B0", "#0000FF20"))
```
should result in this image:

<img width="661" alt="screen shot 2017-12-19 at 7 00 09 pm" src="https://user-images.githubusercontent.com/4210929/34186265-45b7d3d4-e4f0-11e7-9786-8da3ff8645eb.png">

**Comment by clauswilke** [comment]
This has now been fixed in scales.
https://github.com/r-lib/scales/commit/98bbd09e8f57aa6b2a8581828f0bfbe9500f2146
