### ISSUE TITLE
very long geom_bar computation time with iso-8859-1 encoded character in aes fill

### ISSUE THREAD

**Issue by dirkschumacher** [tidyverse/ggplot2#2373]
While reading in an `ISO-8859-1` encoded csv file, I noticed a strange behaviour when plotting certain columns as a bar plot. `geom_bar` enters an infinte loop (or at least takes unreasonaby long to compute) if the column used for `fill` in `aes_string` ends with a special character (German Umlaut).

Takes forever:
```r
library(ggplot2)
data <- data.frame(
  a = "a",
  b = iconv("Some_prefix_ä", "utf8", "iso-8859-1")
)
ggplot(data) +
  geom_bar(aes_string("a", fill = "b"))
```

Works as expected:
```r
library(ggplot2)
data <- data.frame(
  a = "a",
  b = iconv("ä", "utf8", "iso-8859-1")
)
ggplot(data) +
  geom_bar(aes_string("a", fill = "b"))
```

Also this works as expected (seems the length of the prefix must be greater than 1):
```r
library(ggplot2)
data <- data.frame(
  a = "a",
  b = iconv("aä", "utf8", "iso-8859-1")
)
ggplot(data) +
  geom_bar(aes_string("a", fill = "b"))
```

Tested on a mac with R `3.4.2` and observed on a ubuntu shiny server with the same R version. Used ggplot2 `v2.2.1`

**Comment by hadley** [comment]
More minimal reprex:

```R
x <- iconv("Some_prefix_ä", "utf8", "iso-8859-1")
ggplot2:::titleGrob(x, 0.5, 0.5, 0.5, 0.5)
```

Breaking it and looking at a traceback reveals:

```
6: getNamespace("grDevices")
5: grid.Call(C_stringMetric, as.graphicsAnnot(x$label))
4: descentDetails.text(text_grob)
3: descentDetails(text_grob) at margins.R#73
2: title_spec(label, x = x, y = y, hjust = hjust, vjust = vjust, 
       angle = angle, gp = gp, debug = debug) at margins.R#185
1: titleGrob(x, 0.5, 0.5, 0.5, 0.5)
```

So this is likely to be a bug in `C_stringMetric`.

Someone needs to make a simpler reprex (i.e. no use of ggplot2) and send to @pmur002

**Comment by clauswilke** [comment]
More basic reprex, using only grid. Problem still exists in R 3.5.0.
cc @pmur002 

```{r}
library(grid)
x <- iconv("Some_prefix_ä", "utf8", "iso-8859-1")
g <- textGrob(x)
descentDetails(g)
# R hangs
```

Traceback:
```
4: getNamespace("grDevices")
3: grid.Call(C_stringMetric, as.graphicsAnnot(x$label))
2: descentDetails.text(g)
1: descentDetails(g)
```

**Comment by pmur002** [comment]
These are now running for me in r-devel (r74740) - can anyone else confirm that ?

**Comment by clauswilke** [comment]
Thanks @pmur002! Unfortunately I don't have a working r-devel setup right now and don't have the bandwidth to set one up. Maybe somebody else can check?

**Comment by lionel-** [comment]
Confirmed that both the grid and ggplot reprexes work well with r-devel.

**Comment by hadley** [comment]
Thanks @pmur002!
