### ISSUE TITLE
grouped_df should not require a ".group" variable for data on the other layers

### ISSUE THREAD

**Issue by yutannihilation** [tidyverse/ggplot2#2378]
Due to the change in response to #2351, a grouped_df now creates a variable called `.group`. This may be problematic because ggplot2 treats the first layer so special as all the following layers are required to contain all mapped variables except when another mapping is specified individually. Here is an example:

``` r
reprex::reprex_info()
#> Created by the reprex package v0.1.1.9000 on 2017-12-22

library(dplyr, warn.conflicts = FALSE)
library(ggplot2)

df <- data.frame(
  x = 1:10,
  y = 1:10,
  type = rep(c("a", "b"), 5),
  stringsAsFactors = FALSE
) %>%
  group_by(type)

df_labels <- data.frame(
  x = 1,
  y = 2,
  text = "foo!"
)

ggplot(df, aes(x, y)) +
  geom_point(aes(colour = type)) +
  geom_label(data = df_labels, aes(label = text))
#> Error in FUN(X[[i]], ...): object '.group' not found

ggplot(ungroup(df), aes(x, y)) +
  geom_point(aes(colour = type)) +
  geom_label(data = df_labels, aes(label = text))
```

![](https://i.imgur.com/GHZwsYn.png)

Though I'm not sure this is just a bug, I'm afraid #2351 needs a bit more considerations (better error messages, at least).

**Comment by mjskay** [comment]
What about some opt-in syntax for this? Since it implicitly adds a `.group` column now, one could simply not also set the group aesthetic and allow users to do this to "opt-in":

```{r}
ggplot(some_grouped_df, aes(..., group = .group)) +
  ...
```

Which would avoid breaking existing code that has been passing grouped data frames into ggplot, and make the use of the grouping explicit rather than implicit. (I'll admit bias towards the explicit approach as this issue came to my attention by simultaneously breaking a bunch of my plots).

**Comment by hadley** [comment]
Yeah, this has a much bigger impact that I had thought. I like @mjskay's suggestion to make it more opt-in.

**Comment by yutannihilation** [comment]
I like the idea! For the notation, I feel it's good if more explicit one like `calc()` is introduced. `.group` seems a new `...var...`, I'm a bit afraid it would be hard to find what it is and how it is special.

**Comment by yutannihilation** [comment]
But, it's far better than the status quo. I'm OK with explicit `.group` (at least, for now).
