### ISSUE TITLE
Feauture request: Custom ribbon for geom_abline

### ISSUE THREAD

**Issue by benediktclaus** [tidyverse/ggplot2#2381]
Hi,

in psychology there is a simple method for assessing clinical significance. Therefore the pre treatment score of an instrument (e.g. questionnaire) for every patient is plotted against the post treatment score. In the example below, all points that fall below the center diagonal show an improvement. But the instrument used has an error of measurement, indicated by the surrounding diagonals.

The workaround for this is a little annoying so it would be extremely helpful to create a custom ribbon for a `geom_abline` with manual specifications for `ymin` and `ymax`. Thus the area of interest would be shaded and could have a legend entry.

```r
library(ggplot2)

# Some example data, scores on a questionnaire per patient before and after treatment
pre.x <- rnorm(70, mean = 24, sd = 4)
post.x <- rnorm(70, mean = 12, sd = 4)
clinical.data <- data.frame(pre.x, post.x)

# This tells us that changes from pre to post within 3.2 points
# fall into the error of measurement of that questionnaire
error.measurement <- 3.2

# Plot
clinical.significance.plot <- ggplot(clinical.data, aes(x = pre.x, y = post.x)) +
  geom_point() +
  geom_abline(slope = 1, intercept = 0) +
  geom_abline(slope = 1, intercept = -error.measurement) +
  geom_abline(slope = 1, intercept = +error.measurement) +
  coord_cartesian(xlim = c(0,40), ylim = c(0,40))
clinical.significance.plot
```

**Comment by smouksassi** [comment]
Another workaround for you would be like this 
```r
ribbondata<- data.frame(x=c(-50, pre.x, 50),
                        ymin=c(  -50 - error.measurement,
                               pre.x - error.measurement,
                                  50 - error.measurement),
                        ymax=c(  -50 + error.measurement,
                               pre.x + error.measurement,
                                  50 + error.measurement)
                        )

ggplot(clinical.data, aes(x = pre.x, y = post.x)) +
  geom_point() +
  geom_abline(slope = 1, intercept = -error.measurement) +
  geom_abline(slope = 1, intercept = +error.measurement) +
  geom_ribbon(data=ribbondata, aes(x=x,ymin=ymin,ymax=ymax, fill="error of measurement"),
  inherit.aes = FALSE, alpha = 0.2) +
  geom_abline(slope = 1, intercept = 0) +
  coord_cartesian(xlim = c(0, 40), ylim = c(0, 40))+
  labs(fill="")
```
![ablineshade](https://user-images.githubusercontent.com/5131281/34461433-e3e63b94-edf7-11e7-83be-2f60932826c8.png)

**Comment by hadley** [comment]
Given that geom_ribbon() is more general, and the transformation required is simple, I don’t think a specialised geom would be a good fit for ggplot2. It would be a better fit for a separate package.
