### ISSUE TITLE
Controlling graticule appearance  with geom_sf

### ISSUE THREAD

**Issue by GillesSanMartin** [tidyverse/ggplot2#2389]
The control of the appearance (color, linewidth, linetype...) of the graticule produced with geom_sf  is quite counter-intuitive and something seems to be wrong.

For the examples below I used the latest ggplot2 version from github reinstalled today (2.2.1.9000) and sf 0.5-4 (with R version 3.4.3 - Ubuntu 16.04.3 LTS).
This issue was initially posted on the [sf github repository](https://github.com/r-spatial/sf/issues/610#issuecomment-356028830)

I expected to be able to control for example the color and linetype of the graticule with panel.grid but these commands seem to be ignored
```r
library(ggplot)
library(sf)
nc = st_read(system.file("gpkg/nc.gpkg", package = "sf")) 

ggplot() + 
    geom_sf(data = nc) + 
    theme(panel.grid = element_line(color = "red", linetype = 2))
```
![rplot001](https://user-images.githubusercontent.com/4679586/34680588-d1278334-f499-11e7-8bec-f8ed84b375d8.png)

It works as expected with `panel.grid.major` (but I would expect that panel.grid.major will inherit from panel.grid)

```r
ggplot() + 
    geom_sf(data = nc) + 
    theme(panel.grid.major = element_line(color = "red", linetype = 2))
```
![rplot001](https://user-images.githubusercontent.com/4679586/34680627-e7fc0e4a-f499-11e7-8392-3c4eeefa2758.png)

If you want to change only -say- the x grid color with panel.grid.major.x both x and y are changed : 

```r
ggplot() + 
    geom_sf(data = nc) + 
    theme(panel.grid.major.x = element_line(color = "red", linetype = 2))
```
![rplot001](https://user-images.githubusercontent.com/4679586/34680669-044fc8b6-f49a-11e7-9adf-52e5e126a975.png)

If you want to change both x and y in different ways nothing happens : 

```r
ggplot() + 
    geom_sf(data = nc) + 
    theme(panel.grid.major.x = element_line(color = "red", linetype = 2),
          panel.grid.major.y = element_line(color = "blue", linetype = 3))
```

![rplot001](https://user-images.githubusercontent.com/4679586/34680738-268b7880-f49a-11e7-87c2-8e2ecb1e935a.png)

Each example works as intended when I use another geom : 

```r
d <- data.frame(x = rnorm(10), y = rnorm(10))
p <- ggplot(d, aes(x,y)) + geom_point()
p + theme(panel.grid = element_line(color = "red",  linetype = 2))
p + theme(panel.grid.major = element_line(color = "red",  linetype = 2))
p + theme(panel.grid.major.x = element_line(color = "red",  linetype = 2))
p + theme(panel.grid.major.x = element_line(color = "red", linetype = 2),
          panel.grid.major.y = element_line(color = "blue", linetype = 3))
```

By the way, if I'm not wrong, a few weeks ago (30 november) the default color of the graticule was also much lighter and less conspicuous (better to my taste)

**Comment by cpsievert** [comment]
Looks like this regression was introduced in caca650c2a7891fdc7d7f14c377845bce46673f4.

There's a chance that it has other unintended consequences due to the fact that `ggplot2:::plot_theme(qplot(1:10))$panel.grid.major` is now `NULL`

**Comment by hadley** [comment]
Thanks - I must be accessing directly rather than using the theme inheritance system.
