### ISSUE TITLE
space reserved for facet strip text does not respect strip text length/size

### ISSUE THREAD

**Issue by smouksassi** [tidyverse/ggplot2#2391]
The strip text is not allocated enough space to prevent it from being cut. Used an example from @karawoo when working on strip.text angle issues.

``` r
df <- data.frame(
  x = 1:3,
  y = 1:3,
  g = c("b", "bbbb", "bbbbbbbbbohnogettingcut")
)
library(ggplot2)
base <- ggplot(df, aes(x, y)) + 
  geom_point() +
  facet_grid(g ~ .) 
base +
  theme(
    strip.text.y = element_text(size=24))
```

![](https://i.imgur.com/mXKRRl1.png)

**Comment by hadley** [comment]
This is by design - the size of the strip is determined by the facet specification/data, not the theme.
