### ISSUE TITLE
geom_dotplot binwidth Parameter Can Change Plot Range

### ISSUE THREAD

**Issue by DarioS** [tidyverse/ggplot2#2395]
Choosing different values of `binwidth` changes the numeric range of the plot. `binwidth` is not documented as having an effect on the plot boundaries and I wouldn't intuitively expect it to, so I think it's a bug. Try:

```
plotData <- data.frame(measurement = c(2.76, 16.60, 1.12, 13.81),
                       class = factor(c("Bad", "Bad", "Good", "Good")))
ggplot(plotData, aes(x = class, y = measurement)) +
       geom_dotplot(binaxis = "y", stackdir = "center", position = "dodge", aes(colour = class), binwidth = 1)
```

Now, remove the `binwidth = 1` setting. The 0 position on the y-axis vanishes.

**Comment by batpigandme** [comment]
I _believe_ this is what you're describing (for future reference [reprex](http://reprex.tidyverse.org/) is especially helpful with visualization stuff, since it automatically generates the figures as well):
 
``` r
library(ggplot2)
plotData <- data.frame(measurement = c(2.76, 16.60, 1.12, 13.81),
                       class = factor(c("Bad", "Bad", "Good", "Good")))
ggplot(plotData, aes(x = class, y = measurement)) +
  geom_dotplot(binaxis = "y", stackdir = "center", position = "dodge", aes(colour = class), binwidth = 1)
```

![](https://i.imgur.com/FpluCiL.png)

``` r

ggplot(plotData, aes(x = class, y = measurement)) +
  geom_dotplot(binaxis = "y", stackdir = "center", position = "dodge", aes(colour = class))
#> `stat_bindot()` using `bins = 30`. Pick better value with `binwidth`.
```

![](https://i.imgur.com/MHTy9xk.png)

Created on 2018-01-11 by the [reprex package](http://reprex.tidyverse.org) (v0.1.1.9000).

**Comment by wch** [comment]
The range changes to accommodate the bins. This is the same as with `geom_histogram`.

``` r
library(ggplot2)
ggplot(mtcars, aes(wt)) + geom_histogram()
#> `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
```

![](https://i.imgur.com/vwTHOBB.png)

``` r
ggplot(mtcars, aes(wt)) + geom_histogram(binwidth = 0.5)
```

![](https://i.imgur.com/NakcUCh.png)

**Comment by DarioS** [comment]
It makes sense but wasn't obvious to me because dots have an unexpectedly large margin between them and the axis.
