### ISSUE TITLE
The colorbar guide (guide_colourbar) converts units into cm and then uses them as mm

### ISSUE THREAD

**Issue by clauswilke** [tidyverse/ggplot2#2398]
The colorbar guide (`guide_colourbar`) converts units into cm and then uses them as mm. Reproducible example:

```
library(ggplot2)
p1 <- ggplot(iris, aes(Sepal.Width, Sepal.Length, color = Petal.Width)) + geom_point() +
  scale_color_distiller(name = "gap width = 1cm") +
  theme(legend.spacing.x = grid::unit(1, "cm"),
        legend.position = "top")
p2 <- ggplot(iris, aes(Sepal.Width, Sepal.Length, color = Petal.Width)) + geom_point() +
  scale_color_distiller(name = "gap width = 10cm") +
  theme(legend.spacing.x = grid::unit(10, "cm"),
        legend.position = "top")
p3 <- ggplot(iris, aes(Sepal.Width, Sepal.Length, color = Petal.Width)) + geom_point() +
  scale_color_distiller(name = "gap width = 50cm") +
  theme(legend.spacing.x = grid::unit(50, "cm"),
        legend.position = "top")

cowplot::plot_grid(p1, p2, p3, nrow = 1)
```
<img width="1313" alt="screen shot 2018-01-11 at 11 47 13 am" src="https://user-images.githubusercontent.com/4210929/34838858-3f533e70-f6c5-11e7-99b6-f2c5a02544e3.png">

The problem exists for both `legend.spacing.x` and `legend.spacing.y` but cannot be shown for `legend.spacing.y` because of issue #2260, which has not yet been fixed for `guide_colourbar`.

The relevant lines in the code are [here](https://github.com/tidyverse/ggplot2/blob/3fb3fb00555bab5b270b3467a1ddd90341a62886/R/guide-colorbar.r#L301) (convert `legend.spacing.x` and `legend.spacing.y` into cm) and [here](https://github.com/tidyverse/ggplot2/blob/3fb3fb00555bab5b270b3467a1ddd90341a62886/R/guide-colorbar.r#L434) (use all widths and heights as mm values.)

**Comment by batpigandme** [comment]
If `./tests/figs/deps.txt` can be trusted, it looks like Freetype 2.7.0 (obviously worth waiting for hadley to confirm/deny)
https://github.com/tidyverse/ggplot2/blob/bf9255e50cb8333e26133cc81927e5baff986d2a/tests/figs/deps.txt#L2
