### ISSUE TITLE
Tidy evaluation

### ISSUE THREAD

**Issue by hadley** [tidyverse/ggplot2#2412]
Work occurring in tidyeval branch

```R
df <- data.frame(x = 0, y = 0)
ggplot(df, aes(x, y)) + geom_point()

z1 <- new_quosure(expr(z), env(z = 1))
z2 <- new_quosure(expr(z), env(z = 1:2))
aes(!!z1, !!z2)

ggplot(df, aes(x, y)) + geom_point()
ggplot(df, aes(!!z1, y)) + geom_point()
ggplot(df, aes(x, y)) + geom_point(aes(!!z1))
```

Need to figure out how to represent facetting spec using quosures

Small fixes :
 * [x] make sure aes_() and aes_string() preserve existing interface
 * [x] why did scales_add_defaults() need tryapply()? what breaks by removing it?
 * [x] does using globalenv() instead of plot_env in find_scale cause problems? => tests assume find_scale can find local scales
 * [x] test that subset still works

**Comment by lionel-** [comment]
I don't think so, would you like me to?

**Comment by hadley** [comment]
Yeah, it’d be helpful to spend an hour or two on, in total.

**Comment by lionel-** [comment]
Sure thing, will do tomorrow morning.

**Comment by lionel-** [comment]
The `tryapply()` seems to have been there from the start of revision history:
https://github.com/tidyverse/ggplot2/commit/6198457400c66d0774006c75353a1e7f1dd2806a#diff-70a17f07da991e42a800284db537be0aR106. You probably used it just to be on the safe side? It seems to make sense to just evaluate plainly though.


`subset` appears to have stopped working with the 2.0 rewrite: https://stackoverflow.com/questions/34588232/subset-parameter-in-layers-is-no-longer-working-with-ggplot2-2-0-0/34588455#34588455

**Comment by hadley** [comment]
Ok, I'll remove `subset` argument since it's clearly been broken for a while, and `tryapply()` since it no longer seems necessary.
