### ISSUE TITLE
qplot(x) stored in a variable gets modified when modifying x

### ISSUE THREAD

**Issue by ddiez** [tidyverse/ggplot2#2419]
When passing a vector (e.g. *x*) to `qplot()` (to produce e.g. a histogram) and storing the plot into a variable (e.g. *p1*), if the variable *x* is modified the plot *p1* gets also modified. This does not happen if the data is passed as a `data.frame()`

```r
# Generate random vector.
x <- rnorm(100, mean = 0)
p1 <- qplot(x)
p1

# Modify variable x (either of these options replicate the behavior).
x <- rnorm(100, mean = 10)
x <- x + 10
# Now p1 plots a histogram centered at 10, the data in p1 has been modified.
p1

# This however works as expected:
d <- data.frame(x = rnorm(100, mean = 0))
p1 <- qplot(x, data = d)
p1

d <- data.frame(x = rnorm(100, mean = 10))
# Modifying d does not cause p1 to be modified.
p1
```

I found this in ggplot2_2.2.1.9000 on my computer (sessionInfo below) but also could replicate it with ggplo2 2.2.1 testing it with the rocker/rstudio image.

```r
> sessionInfo()
R version 3.4.3 (2017-11-30)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS High Sierra 10.13.2

Matrix products: default
BLAS: /Library/Frameworks/R.framework/Versions/3.4/Resources/lib/libRblas.0.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.4/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] ggplot2_2.2.1.9000

loaded via a namespace (and not attached):
 [1] labeling_0.3      colorspace_1.3-2  scales_0.5.0.9000 compiler_3.4.3   
 [5] lazyeval_0.2.1    plyr_1.8.4        withr_2.1.1.9000  pillar_1.1.0     
 [9] gtable_0.2.0      tibble_1.4.2      Rcpp_0.12.15      grid_3.4.3       
[13] rlang_0.1.6.9003  munsell_0.4.3    
```

**Comment by ddiez** [comment]
One possible source for the problem is in the following line in `qplot()`:

```r
x <- eval(aesthetics$x, data, env)
```

*aesthetics$x* is a refObject. This tries to obtain the *x* aesthetics from data. But when *x* is passed as a vector to `qplot` the data slot is empty. Therefore it picks up the variable in the global environment. Because it access it as a reference then the data gets modified when the variable *x* is modified in .GlobalEnv.

```r
x <- 1:10
qplot(x)$data
data frame with 0 columns and 0 rows
```

This does not happen when the data is passed in a `data.frame`.

```r
qplot(x, data = data.frame(x = x))$data
    x
1   1
2   2
3   3
4   4
5   5
6   6
7   7
8   8
9   9
10 10
```

When the argument *data*  is passed there is an attempt to create a `data.frame` considering facets if specified.

```r
if (missing(data)) {
        data <- data.frame()
        facetvars <- all.vars(facets)
        facetvars <- facetvars[facetvars != "."]
        names(facetvars) <- facetvars
        facetsdf <- as.data.frame(mget(facetvars, envir = env))
        if (nrow(facetsdf)) 
            data <- facetsdf
    }
```
But when no facets are found then an empty data.frame results. Maybe there is where a fix should go? If no facets are specify construct a data.frame with the vars *x* (and *y* when passed).

This of course unless I misunderstood the whole problem from the beginning...

**Comment by hadley** [comment]
Yes, this is the downside of `qplot()`, and one reason you shouldn't use it.

**Comment by ddiez** [comment]
OK, understood. Note that using `ggplot()` in the following way seems to lead to the same problem:

```r
p <- ggplot(mapping = aes(x)) + geom_histogram()
```

I know this is not the way it is intended to be used. Maybe it is necessary to print a warning about the unintended behavior when wrongly using this (or qplot)? Or a note in the documentation. Anyway, I learned a lot from this!
