### ISSUE TITLE
geom_bar with position = "fill",  y-axis label is count, but value is a proportion

### ISSUE THREAD

**Issue by mentalplex** [tidyverse/ggplot2#2421]
This example is from [r4ds chapter 3.8: Position Adjustments](http://r4ds.had.co.nz/data-visualisation.html#position-adjustments)

---
## Observed behavior:
When geom_bar is called with aesthetic mappings for two categorical variables AND a position value of "fill", the actual statistic represented visually by the height of a plot element on the y axis is a proportion (the cumulative proportion of b.a in a), but the y axis is labeled "count". 

To describe this using the actual example from the r4ds chapter: in the diamonds data set, when plotting a bar chart of cut grouped by clarity, if we use the position = "fill" value, the actual statistic on the y axis is the proportion of a given cut level that is comprised of each clarity level. The y axis is labeled "count".

## Expected behavior:
The y-axis would be labeled "proportion", or "cumulative proportion of clarity in cut"

## reprex
```r
library(ggplot2)
# directly from the book:
ggplot(data = diamonds) + 
  geom_bar(mapping = aes(x = cut, fill = clarity), position = "fill")
```
![image](https://user-images.githubusercontent.com/3392948/35311862-0ebe9a42-0076-11e8-870c-f23b6261613d.png)

## Comment
Presumably behind the scenes position = "fill" tells geom_bar to calculate the proportion (clarity.cut/ cut) for each value of cut, and to do that it uses the count statistic, but the actual value represented by the cumulative height of the different color bars is not a count.

**Comment by has2k1** [comment]
> Presumably behind the scenes position = "fill" tells geom_bar to calculate the proportion (clarity.cut/ cut) ...

That is not what happens, the statistic and position operate independently; so this issue may be hard to fix in a nice way.

**Comment by hadley** [comment]
Yeah, unfortunately there's no way to fix this problem. You need to manually re-label the axis.
