### ISSUE TITLE
Feature Request: facet_grid strip Widths (and Heights) Span Appropriate Panels

### ISSUE THREAD

**Issue by billdenney** [tidyverse/ggplot2#2423]
When `facet_grid` has more than one column or row in order of facets that the value covers, it would be helpful to have the strip cover all appropriate columns so that the data are more logically grouped.

In the example below, it would help if the "1" spanned the first two columns of facets and the "2" spanned the last two columns.  That way, the data would be visually grouped more clearly.

The feature should apply to both rows and columns of facets and only look within a group.  E.g. if the A=2, B=3 column didn't exist in the example below, then the strip labels should look something like:

```
[   1   ] [2]
[3]   [4] [4]
```

Not like the below (or maybe there is an option to enable the below behavior, but it isn't the default):

```
[   1   ] [2]
[3] [   4   ]
```

``` r
library(ggplot2)
d <- expand.grid(A = 1:2, B = 3:4)
d$C <- 1:nrow(d)
d$D <- nrow(d):1

ggplot(d, aes(x = C, y = D)) + facet_grid(~A + B) + geom_point()
```

![](https://i.imgur.com/ikadyNK.png)
```

**Comment by smouksassi** [comment]
linking to this might help:
https://stackoverflow.com/questions/40316169/nested-facets-in-ggplot2-spanning-groups

Having this supported would be a great addition

**Comment by thomasp85** [comment]
This has been discussed before e.g. in #1922. It is really outside the scope of ggplot2 to offer this, but absolutely doable using the extension system. My suggestion would be to open a feature request in a suitable extension package, e.g. ggalt or ggforce...

**Comment by billdenney** [comment]
@smouksassi, Thanks for the link!

@thomasp85, Why is it out of scope for ggplot2?  (And, the discussion in #1922 seemed to focus on the question of "Why did the grob structure change with 2.2.0?" rather than a request to implement this feature in `facet_grid`.  But maybe I missed some of the conversation there.)

**Comment by thomasp85** [comment]
Faceting is generally hard to maintain and some of the more complicated pieces to wrap your head around. Adding this feature would add a large development/maintenance burden with mainly a cosmetic gain... this is why such a feature is better suited for an extension so the maintenance can be spread out to others...

That’s my 2c anyway

**Comment by billdenney** [comment]
@thomasp85, Thanks for the explanation.  While I agree that it is cosmetic, I think that it is structurally cosmetic and aids in speed and fluidity of understanding.

The way that the strips show now, there is no indication if faceted rows and columns are grouped together or arbitrarily ordered.  The proposed feature request would make it clear when `facet_grid` columns are grouped.

In tables, these types of groups are commonly used to rapidly orient the reader to columns that are grouped together (and sometimes for rows).

On top of these, it allows more information to be displayed in a strip since data will not be duplicated and double the visual real estate would be available.  (Said a bit tongue in cheek, it would be a more tidy layout. :) )

(All of that said, I don't see the way to implement it, so I don't want to minimize the effort to continue maintaining it.)

**Comment by thomasp85** [comment]
I didn’t mean to imply that the cosmetic part was without utility. I can absolutely see the use for this. Then again, many useful features are being implemented as part of extensions. In general (I think) that new features that are included in ggplot2 falls into two categories: 1) low maintenance with general applicability, and 2) essential missing features.

E.g. the addition of captions and subtitles would fall into 1, while the coming addition of `sf` support falls into 2.

**Comment by batpigandme** [comment]
@billdenney have you played around with egg for this?  There's nothing precisely matching your goal at this point, but it seems like it might give you some flexibility with panel placement (though, of course @baptiste would be the one to ask). 
https://github.com/baptiste/egg

**Comment by billdenney** [comment]
@thomasp85, Thanks for the clarification.  FYI, I find that in my workflow I need this type of solution relatively often (to the point that I recently helped develop [topiclongtable](/paolobrasolin/topiclongtable) to overcome issues with row grouping in LaTeX tables spanning pages).

As I look through the code, I think that this could be as simple (**WARNING**, someone who has never dived into the ggplot2 code said something is simple; he is wrong but doesn't know why) as modifying ggstrip to look at a new `theme` item called something like `strip.grouping` to horizontally or vertically combine the height/width elements accounting for the number of margins spanned and drop elements when combined.  On top of that, the feature would need to be made accessible-- perhaps making it part of the `theme` is enough, perhaps additional options would need to be added to functions like facet_grid.  The change would be needed around the following lines: https://github.com/tidyverse/ggplot2/blob/401511e76578e7a35e4a8f9eb9fb68b6d79c95a3/R/labeller.r#L615

Were I to make/test/provide a PR for this, do you think it would be accepted?

@batpigandme, Thanks to the pointer to egg.  The title of the package gives me pause; "fragile" is not a word I like associated with code.  I'll take a look.

**Comment by thomasp85** [comment]
I really can’t say - @hadley would have to chime in

**Comment by hadley** [comment]
I agree with @thomasp85 that this is better of at least starting in an extension mechanism. Facetting code is tricky to get right, and the long release process for ggplot2 means that it's no longer a good place for exploration. I'd recommend experimenting elsewhere, and then if you get something useful and robust, I'd consider a PR.

**Comment by baptiste** [comment]
@billdenney For clarification: egg is 'fragile' but so are all ggplot2 extension packages that implement features relying on low-level functions and/or internal ggplot2 structure. A custom facetting function would be in this category, so the burden of repairing it would fall onto the extension package's maintainer whenever ggplot2 introduces a breaking update (and note that internal changes typically aren't documented). Anyway, this is a bit off-topic since I don't see how egg would help implement this specific feature.

**Comment by thomasp85** [comment]
FWIW I’ll welcome an issue in ggforce were we can further discuss a possible inclusion of it there...

**Comment by teunbrand** [comment]
I know this feature request is not very new, but I thought I'd share that I made a `facet_nested()` function over [here](https://github.com/teunbrand/ggh4x/blob/master/R/facet_nested.R) that people are welcome to try out. If ggforce or ggplot2 at some point would want to adopt this, I'll be glad to share/migrate the code.
