### ISSUE TITLE
ggsave is not rendering alpha in device=png output files

### ISSUE THREAD

**Issue by cregouby** [tidyverse/ggplot2#2424]
`ggsave` is not rendering `alpha=` of the `ggplot` object as expected in the png files: 
png file obtained from `ggsave` contains non-alpha objects only. i.e. `geom_lines` are rendered by default theme color (black in the case of theme_void() ) , where png files output from rstudio --> export --> save as Image or rstudio--> export --> copy to clipboard render the alpha as expected i.e light gray lines.

```r
gg<-ggplot(iris, aes(x=Sepal.Length,group=Species)) + geom_density(size=.1,alpha=.1) + theme_void()
ggsave(gg, filename = "gg.png", device = "png", width = 1, height = 1)
```

**Comment by wch** [comment]
What platform are you on? My first thought is that the graphics device that `ggsave` is using by default on your platform doesn't support transparency .

**Comment by cregouby** [comment]
I'm running on x86_64-pc-linux-gnu (ubuntu 16-04). Is there any way to collect which is, or change the default graphic device from `ggsave` options ?

**Comment by wch** [comment]
Here's one way to see what it does when R uses the default device for generating PNG files:

```
gg<-ggplot(iris, aes(x=Sepal.Length,group=Species)) + geom_density(size=.1,alpha=.1) + theme_void()

png("gg.png")
print(gg)
dev.off()
```

The `capabilities()` function will tell you more about the available renders for PNGs and other files. For example, here's what my machine (a mac) gives:

```
> capabilities()
       jpeg         png        tiff       tcltk         X11        aqua    http/ftp 
       TRUE        TRUE        TRUE        TRUE       FALSE        TRUE        TRUE 
    sockets      libxml        fifo      cledit       iconv         NLS     profmem 
       TRUE        TRUE        TRUE        TRUE        TRUE        TRUE        TRUE 
      cairo         ICU long.double     libcurl 
       TRUE        TRUE        TRUE        TRUE 
```

If you look at `?png` and look at the documentation for the `type` argument, that will give more information about finding out what is used for rendering by default.

**Comment by cregouby** [comment]
Thanks a lot for this explaination : 
my own `capabilities()` includes `cairo = TRUE` as well, and according to `png`, I do have
``` {r}
> getOption("bitmapType")
[1] "cairo"
```
which is used as default `type=` for `png()` function that does not correctly render the alpha according to your example (with `size=1` for the alpha result to clearly display), i.e. I still get black lines in the plot , whatever the `type=` configured within png() function
Anyway, your example using `png()`

**Comment by cregouby** [comment]
You pointed out the right topic. It could e that Cairo::cairo has issues with alpha treatment, where cairoDevice::Cairo_png do not. So I turned the config into 
```{r}
library(cairoDevice)
gg<-ggplot(iris, aes(x=Sepal.Length,group=Species)) + geom_density(size=.1,alpha=.1) + theme_void()
ggsave(gg, filename = "gg.png", device = Cairo_png, width = 1, height = 1)
```
wich render the alpha correctly as expected in the gg.png file
Thank a lot for your help.
