### ISSUE TITLE
Using `margin` to adjust `axis.text.x` when position is top

### ISSUE THREAD

**Issue by QuentinRoy** [tidyverse/ggplot2#2425]
`margin` seems to be unresponsive when trying to modify labels on top of a graph.
I often remove the ticks and as a result, find the labels a bit too low or too high.

For example the code below does not seem to have any effect:
```r
ggplot(data, aes(x = Question, y = Response)) +
  geom_boxplot() +
  theme(
    axis.text.x = element_text(margin=margin(t=-10))
  ) +
  scale_x_discrete(position="top")
```

**Comment by hadley** [comment]
Same problem as #1502
