### ISSUE TITLE
Strange behaviour of geom_smooth and splines::ns

### ISSUE THREAD

**Issue by glennstone** [tidyverse/ggplot2#2426]
The following example produces two different smooths where I believe they should be the same.
 (This is a simulation based on a rather larger real data set)

The only difference in the geom_smooth is the use of splines::ns versus ns

If using R 3.4.3 on windows and ggplot2 version 2.2.1

```r
require(splines)
require(ggplot2)

set.seed(12345)
dat = data.frame(claim=rbinom(1000,1,0.5))
mns = c(3.4,3.6)
sds = c(0.24, 0.35)
dat$wind = exp(rnorm(nrow(dat), mean=mns[dat$claim+1], sd=sds[dat$claim+1]))
dat = dat[order(dat$wind),]

ggplot(dat, aes(wind,claim))+geom_point()+
  geom_smooth(method = "glm",
              method.args = list(family = binomial), 
              formula = y ~ splines::ns(x, df=5))+
  geom_smooth(method = "glm",
              method.args = list(family = binomial), 
              formula = y ~ ns(x, df=5))
```

**Comment by batpigandme** [comment]
In the future, if's useful to have such issues as a self-contained [reprex](http://reprex.tidyverse.org/) (short for minimal **repr**oducible **ex**ample). One of the best features is that it deals with generating and uploading the plots for you, so it's especially useful for graphics-related issues.

If you've never heard of a reprex before, you might want to start by reading the tidyverse.org [help page](https://www.tidyverse.org/help/). The [reprex dos and don'ts](http://reprex.tidyverse.org/articles/reprex-dos-and-donts.html) are also useful.

``` r
library(splines)
library(ggplot2)

set.seed(12345)
dat <- data.frame(claim = rbinom(1000, 1, 0.5))
mns <- c(3.4, 3.6)
sds <- c(0.24, 0.35)
dat$wind <- exp(rnorm(nrow(dat), mean = mns[dat$claim + 1], sd = sds[dat$claim + 1]))
dat <- dat[order(dat$wind), ]

ggplot(dat, aes(wind, claim)) + geom_point() +
  geom_smooth(
    method = "glm",
    method.args = list(family = binomial),
    formula = y ~ ns(x, df = 5)
  ) +
  geom_smooth(
    method = "glm",
    method.args = list(family = binomial),
    formula = y ~ splines::ns(x, df = 5),
  )
```

![](https://i.imgur.com/myNwbim.png)

Created on 2018-01-28 by the [reprex package](http://reprex.tidyverse.org) (v0.1.1.9000).

In the one below, I've separated out the two methods so it's clear which is which. 

``` r
library(splines)
library(ggplot2)

set.seed(12345)
dat <- data.frame(claim = rbinom(1000, 1, 0.5))
mns <- c(3.4, 3.6)
sds <- c(0.24, 0.35)
dat$wind <- exp(rnorm(nrow(dat), mean = mns[dat$claim + 1], sd = sds[dat$claim + 1]))
dat <- dat[order(dat$wind), ]

ggplot(dat, aes(wind, claim)) + geom_point() +
  geom_smooth(
    method = "glm",
    method.args = list(family = binomial),
    formula = y ~ ns(x, df = 5)
  ) +
  ggtitle("y ~ ns edition")
```

![](https://i.imgur.com/cIRcBG1.png)

``` r

ggplot(dat, aes(wind, claim)) + geom_point() +
  geom_smooth(
    method = "glm",
    method.args = list(family = binomial),
    formula = y ~ splines::ns(x, df = 5),
  ) +
  ggtitle("splines::ns edition")
```

![](https://i.imgur.com/r6Nd3yQ.png)

Created on 2018-01-28 by the [reprex package](http://reprex.tidyverse.org) (v0.1.1.9000).

**Comment by hadley** [comment]
Even better is to draw them in one plot with labels:

```R
ggplot(dat, aes(wind, claim)) + 
  geom_point() +
  geom_smooth(
    method = "glm",
    method.args = list(family = binomial),
    formula = y ~ splines::ns(x, df = 5),
    aes(color = "splines::ns"),
    se = FALSE
  ) +
  geom_smooth(
    method = "glm",
    method.args = list(family = binomial),
    formula = y ~ ns(x, df = 5),
    aes(color = "ns"),
    se = FALSE
  )
```

It is utterly mystifying to me why these should be returning different results.

**Comment by hadley** [comment]
If I instrument the code to print the model, I see:

```R
            (Intercept) splines::ns(x, df = 5)1 splines::ns(x, df = 5)2 splines::ns(x, df = 5)3 
              0.5194712              -0.8687737              -0.6803954               4.0838947 
splines::ns(x, df = 5)4 splines::ns(x, df = 5)5 
              2.3908674               4.1564128 

   (Intercept) ns(x, df = 5)1 ns(x, df = 5)2 ns(x, df = 5)3 ns(x, df = 5)4 ns(x, df = 5)5 
     0.5194712     -0.8687737     -0.6803954      4.0838947      2.3908674      4.1564128 
```

So it certainly looks like the fitted model is identical.

**Comment by hadley** [comment]
This doesn't seem to be a bug in ggplot2, and I've posted to r-devel to see if we can learn more.

**Comment by glennstone** [comment]
Thanks for your efforts!

**Comment by hadley** [comment]
To close this out, it's definitely a bug in `glm()`, and it'll be fixed in the next version of R.

**Comment by huftis** [comment]
And for anyone’s interested, here’s the thread on r-devel where the bug is discussed: https://stat.ethz.ch/pipermail/r-devel/2018-April/075889.html
