### ISSUE TITLE
Bad link on "Creating a New Geom" wiki page

### ISSUE THREAD

**Issue by ndphillips** [tidyverse/ggplot2#2427]
The link http://code.google.com/p/ggextra/source/browse/trunk/demos/geom-field-test.r shown on https://github.com/tidyverse/ggplot2/wiki/Creating-a-new-geom leads to an empty page.

Is this code available elsewhere?

![image](https://user-images.githubusercontent.com/8480980/35520392-316de1a6-0517-11e8-8168-e78cc4a3a9be.png)

**Comment by jemus42** [comment]
The code for `ggExtra` lives [here](https://github.com/daattali/ggExtra), but I couldn't find any demos :/

**Comment by ndphillips** [comment]
Thanks @jemus42! I think I have the code I need now from ggExtra. But it would still be nice to see the self contained .R file for the code on https://github.com/tidyverse/ggplot2/wiki/Creating-a-new-geom.

**Comment by batpigandme** [comment]
Hi @ndphillips, per the [wiki home,](https://github.com/tidyverse/ggplot2/wiki):
> The ggplot2 wiki is no longer maintained, please use the ggplot2 website instead!
There isn't a means by which to sunset the material that's there, and, because it's a wiki, it's not developer-generated content/not tested as packages evolve.
