### ISSUE TITLE
Order of colors in case variable is 'character'

### ISSUE THREAD

**Issue by manuelreif** [tidyverse/ggplot2#2429]
Hi!

I am using ggplot2 quite often, and I ran into a problem concerning the ordering of colors. So I am setting the breaks and the color values in `scale_fill_manual()`, and I would expect that the first color "black" would be assigned to the first break ('small') and so on. This seems to happen when the grouping variable is data type = character. I suppose you transform the variable into a factor internally, or something like that. 
Is this the intended behaviour, because for me this is really confusing?!

```r
test <- data.frame(a=as.character(gl(n = 4, length = 8, k = 2, labels = letters[1:4])), 
                   b=as.character(gl(n = 2, length = 8, k = 1, labels = c("small",  "big"))),
                   values = sample(10:300, 8))


pl1 <- ggplot(test, aes(x=a, y=values, fill=b))
pl1 + geom_bar(stat="identity", position="dodge") + 
scale_fill_manual("test", breaks=c("small", "big") , values = c("black","tomato2"))

```

Thank you!!
Manuel

**Comment by MajoroMask** [comment]
`ggplot2` use factors to solve this. Try `test$b <- factor(test$b, levels = unique(test$b))` before plotting. `ggplot2` actrually did this for you with default `levels` argument, which is sorting the atomic vector alphabetically.

**Comment by manuelreif** [comment]
I am using ggplot2 for years now, and I never had this problem, apparently because the variables have always been factors. So, to be honest, I am not very happy with this behaviour, because ggplot is doing something for me, which I am not aware about. I think a warning would have helped a lot to save my time.

Wouldn´t it be more sensible to set the levels to the breaks I submitted by `scale_fill_manual()` ? I don´t know whether this is possible or not.

Thanks.

**Comment by hadley** [comment]
Minimal reprex:

```R
library(ggplot2)

df <- data.frame(x = c("red", "black"))

ggplot(df, aes(x, 1, fill = x)) + 
  geom_col() +
  scale_fill_manual(breaks = c("red", "black"), values = c("red", "black"))
```

**Comment by clauswilke** [comment]
Not sure this is a bug, since it behaves exactly as documented:

> `values`—a set of aesthetic values to map data values to. If this is a named vector, then the values will be matched based on the names. If unnamed, values will be matched in order (usually alphabetical) with the limits of the scale. Any data values that don't match will be given na.value.

Importantly, the documentation also explains how to make this work, by using a named vector:
``` r
library(ggplot2)
test <- data.frame(a=as.character(gl(n = 4, length = 8, k = 2, labels = letters[1:4])), 
                   b=as.character(gl(n = 2, length = 8, k = 1, labels = c("small",  "big"))),
                   values = sample(10:300, 8))


ggplot(test, aes(x = a, y = values, fill = b)) +
  geom_bar(stat = "identity", position = "dodge") + 
  scale_fill_manual(
    "test",
    breaks = c("small", "big"),
    values = c("small" = "black", "big" = "tomato2")
  )
```

![](https://i.imgur.com/Dbgsvni.png)

However, there is a small modification one could make to make the scale behavior more intuitive: Check if `values` is a named vector, and if not *and* `breaks` are provided, use the breaks as names for `values`, in order.

**Comment by clauswilke** [comment]
I was proposing to implement this *only* for manual scales.

**Comment by clauswilke** [comment]
This is object-oriented programming, so what you'd want to do is make a ggproto object that derives from `ScaleDiscrete()` and then reimplements `map()`, just like `ScaleDiscretePosition()` is implemented: https://github.com/tidyverse/ggplot2/blob/1f9ef732d766583c4a0d3ddf035ba0c0333ae00e/R/scale-discrete-.r#L79

I'll let @hadley chime in whether the feature would be welcome or not. In my own use of `scale_manual()`, I have certainly struggled with getting the values assigned to the correct breaks and getting the breaks into the right order in the legend. The named-list approach would have helped, but I didn't know it exists and I don't think it is widely known even though it's in the docs.

**Comment by mikmart** [comment]
Okay, I see! A new class for manual scales would also mean that the `map()` method in `ScaleDiscrete` could be cleaned up a bit, as it would no longer have to deal with named palettes, right?

Regarding the feature itself, I was just recently reading the ggplot2 book, and this quote from the scales chapter came to mind:

> To distinguish breaks from limits, remember that breaks affect what appears
on the axes and legends, while limits affect what appears on the plot.

Using `breaks` for the aesthetic mapping for manual scales would be an exception to this logic. Perhaps this would be better addressed with changes in the documentation? The help text for `values` is already quite long, but perhaps it would help to add emphasis by mentioning sooner that it is the `limits` that will be used for creating the mapping, if names are not specified?
