### ISSUE TITLE
Export set_last_plot

### ISSUE THREAD

**Issue by thomasp85** [tidyverse/ggplot2#2432]
I have been running into problems with getting `ggsave` to work flawlessly with patchwork, mainly because the default call to `last_plot()` make people expect that the function *just work*

Would it be possible to export `set_last_plot()` so patchwork can register the created plots correctly?

**Comment by hadley** [comment]
Sure. PR?

**Comment by thomasp85** [comment]
I’ll find a break tomorrow for it🙂

**Comment by hadley** [comment]
Still interested?

**Comment by thomasp85** [comment]
Yes. I simpelt forgot abort it. Ill do a PR

**Comment by thomasp85** [comment]
Weird - I made the fix on the 1st of February but forgot to submit the PR... Oh well...
