### ISSUE TITLE
`solid` and non-`solid` shapes in scale_shape: nonsensical shapes and inconsistent removal of points

### ISSUE THREAD

**Issue by Henrik-P** [tidyverse/ggplot2#2435]
`scale_shape` has the `solid` argument:

> `solid`: Should the shapes be solid, `TRUE`, or hollow, `FALSE`?

Although "solid" and "hollow" are not clearly defined in the help text, I believe that most people have a general idea about how the respective shapes would look like. At the very least, one would expect shapes corresponding to `TRUE` and `FALSE` to differ. However, this is not the case.

In addition, `scale_shape` has a rule for when an aesthetic is "difficult to discriminate", with a corresponding _removal_ of points, which is _inconsistent_ with other aesthetics.

Here's an example with three plots: (a) `solid = TRUE`, (b) `solid = FALSE`, and (c) an example of points which I would percieve as "hollow". 

``` r
                                                                   
d <- data.frame(x = factor(1:10), y = 1)                           
library(ggplot2)                                                   
library(cowplot)                                                   
                                                                   
                                                                   
p <- ggplot(d, aes(x = x, y = y, shape = x)) +                     
geom_point(size = 8) +                                             
scale_shape_discrete(solid = TRUE,                                 
guide = guide_legend(ncol = 2)) +                                  
annotate(geom = "text", x = 1, y = 1.2,                            
label = 'solid = TRUE, "non-hollow"', hjust = 0) +                 
ylim(0.8, 1.2)                                                     
                                                                   
d$shape <- ggplot_build(p)$data[[1]][ , "shape"]                   
solid <- p + geom_text(data = d, aes(y = y + 0.1, label = shape))  
                                                                   
p <- ggplot(d, aes(x = x, y = y, shape = x)) +                     
geom_point(size = 8) +                                             
scale_shape_discrete(solid = FALSE,                                
guide = guide_legend(ncol = 2)) +                                  
annotate(geom = "text", x = 1, y = 1.2,                            
label = 'solid = FALSE, "hollow"', hjust = 0) +                    
ylim(0.8, 1.2)                                                     
                                                                   
d$shape <- ggplot_build(p)$data[[1]][ , "shape"]                   
hollow <- p + geom_text(data = d, aes(y = y + 0.1, label = shape)) 
                                                                   
p <- ggplot(d, aes(x = x, y = y, shape = x, fill = x)) +           
geom_point(size = 6) +                                             
scale_shape_manual(values = c(0, 1, 2, 5, 6, 21:25),               
guide = guide_legend(ncol = 2)) +                                  
annotate(geom = "text", x = 1, y = 1.2,                            
label = "Hollow?", hjust = 0) +                    
ylim(0.8, 1.2)                                                     
                                                                   
d$shape <- ggplot_build(p)$data[[1]][ , "shape"]                   
hollow2 <- p + geom_text(data = d, aes(y = y + 0.1, label = shape))
                                                                   
p <- plot_grid(solid, hollow, hollow2, nrow = 3, align = "v")      
save_plot("solid.png", p, base_height = 7)                         
```
![solid](https://user-images.githubusercontent.com/3583910/35782175-b520736a-09f4-11e8-9e54-9679ac09b0c7.png)

-----

# The problems:
1. In the '`solid = TRUE`, "non-hollow"' points (a), `pch` 3, 7, and 8 don't seem very "solid"
2. In the '`solid = FALSE`, "hollow"' points (b), `pch` 3, and 8 don't seem very "hollow"
3. `pch` 3, 7 and 8 appear in _both_ `solid = TRUE` and `solid = FALSE`. I consider this a bug. Why have an argument where `TRUE` and `FALSE` alternatives don't differ?
4. The code for both plot (a) and (b) generates warnings, and removes points:

> Warning messages:
1: The shape palette can deal with a maximum of 6 discrete values
because more than 6 becomes difficult to discriminate; you have 10.
Consider specifying shapes manually if you must have them. 

...which in turn leads to:
> 2: Removed 4 rows containing missing values (geom_point). 

This is inconsistent with the behaviour of other `aes`sthetics. Compare with e.g. `color`/`fill`/`alpha`, where you can map to "as many values you want", with an indistinguishable appearance as a result, _without_ warning or removal of points (see below). If anything, a warning would suffice for the shapes. On the other hand, if you start producing warnings for all cases of poor visualisation, where to stop? 
    
    d <- data.frame(x = factor(1:100), y = 1)
    ggplot(data = d, aes(x = x, y = y, color = x)) + geom_point()

![rplot02](https://user-images.githubusercontent.com/3583910/35736145-3da20aa2-0827-11e8-8f55-785c7bf62773.png)

---------

Thanks a lot for your tremendous work with the package!

**Comment by hadley** [comment]
You points are well made, but at this point any change to key scales is not tenable because it will cause many people to be unhappy.
