### ISSUE TITLE
ggplot2 produces axes with fewer than 2 labeled ticks

### ISSUE THREAD

**Issue by JohnMount** [tidyverse/ggplot2#2439]
To extract quantitative information from a graph a viewer needs at least two labeled ticks per axis.

Below is a simple example where ggplot2, with default settings, produces axes zero and one labeled ticks.

``` r
library("ggplot2")

ggplot(data.frame(x = c(7, 7), y = c(0.5, 0.6)), 
       aes(x = x, y = y)) + 
  geom_point() +
  scale_y_log10() + 
  scale_x_log10()
```

![](https://i.imgur.com/p0yvw4S.png)

Similar data produces a very different graph.

``` r
library("ggplot2")

ggplot(data.frame(x = c(7, 7.01), y = c(0.5, 0.6)), 
       aes(x = x, y = y)) + 
  geom_point() +
  scale_y_log10() + 
  scale_x_log10()
```

![](https://i.imgur.com/5tu1PPc.png)

**Comment by Ax3man** [comment]
In this case, a viewer would need three ticks to recognize the log transformation. 

FWIW, this is happening because the `scale_*_log10` functions will only show breaks at natural powers of ten, but won't expand the axis far enough to reach there. Solutions involve manual tinkering, either to increase `limit` or `expand`, or to supply your own `breaks`.

**Comment by JohnMount** [comment]
I have been experimenting with falling back to coord_trans() if the data does not have enough range.

``` r
library("ggplot2")

ggplot(data.frame(x = c(7, 7), y = c(0.5, 0.6)), 
       aes(x = x, y = y)) + 
  geom_point() +
  coord_trans(x = "log10", y = "log10")
```

![](https://i.imgur.com/2QNUCPL.png)

The user may or may not be able to tell there is a log transform in effect, but at least they can pick some quantitative facts off the data.

**Comment by billdenney** [comment]
This is the same as #2269 (and thanks for the solution using `coord_trans`).
