### ISSUE TITLE
Secondary axis tick behaviour

### ISSUE THREAD

**Issue by Ilia-Kosenkov** [tidyverse/ggplot2#2441]
---
Secondary axis tick labels (values) are calculated properly, but tick positions are significantly off and seem to suffer either from poor interpolation or from issues with floating point operations.
The  `x` variable values cover range of the actual data which produced this issue for the first time.

```r
library(tidyverse)
x = 10 ^ (seq(-27, -23, length.out = 100) + runif(100, 0, 1))
t = 1:100

p = tibble(x, t) %>%
        ggplot(aes(t, x)) +
        geom_point() +
        scale_y_log10(sec.axis = sec_axis(~log10(.*100)))

print(p)

```
One should expect that right y axis ticks perfectly align with grid lines, but label values are 100 larger (e.g. 1e-25 on the left corresponds to 1e-23 on the right precisely).
However, the output looks like this:

![1](https://user-images.githubusercontent.com/8782986/35855863-0ad919a8-0b3d-11e8-8c16-b98794644a9c.png)

Two labels even overlap - I guess it is the 1e-23 and 1e-24.
Also, right axis tick positions do not align well with lines drawn by e.g. `annotate(geom="segment", x = 95, xend = 100, y = 10^(-26:-24), yend = 10^(-26 : -24))` suggesting tick positions on the right are really off.

**Comment by thomasp85** [comment]
Thanks for providing a well explained and reproducible issue. Fortunately, the reported problem have already been solved in the development version and will be fixed on CRAN on the next ggplot2 release. In the meantime you can access the fixed version by installing from GitHub (`devtools::install_github('tidyverse/ggplot2')`)
