### ISSUE TITLE
Wrong order of colours in scale_fill_manual (single barplot)

### ISSUE THREAD

**Issue by mikgh** [tidyverse/ggplot2#2443]
---

Hi,

Thank you very much for the tidyverse-contribution - I use it extensively!
However, I am getting a puzzling result when I try to create a stacked single barplot (see code below).
Specifically, it seems to reverse the colours as input using scale_fill_manual. In the example below, male should be yellow and female red.

I apologize for overlooking solutions to this problem - or whether it is a known issue or entirely my own stupidity :). But could I please ask for a bit of guidance?

```r
df <- data.frame(sex = c("Male", "Female"), mean = c(0.359, 0.641)) %>%
			mutate(pos = cumsum(mean) - 0.5*mean)
plotdf <- ggplot(df, aes(x = 1, y = mean*100, fill = sex, label = sex)) +
			geom_bar(stat = "identity") +
			geom_text(aes(y = pos*100, label = paste(round(mean*100, 0), " %", "\n", sex))) +
			scale_fill_manual(values = ifelse(df$sex == "Male", "#CDA000", "#A7172B")) +
			coord_flip() +
			theme(axis.title = element_blank(),
				axis.text.y = element_blank())
plotdf
```

Best regards,
Mikkel

**Comment by mikgh** [comment]
As a slight extension to the issues I am having above:
If I sort the tibble by the variable "mean" in descending order, the geom_text is reversed but now the colours are correct.

```
df <- data.frame(sex = c("Male", "Female"), mean = c(0.359, 0.641)) %>%
			arrange(desc(mean)) %>%
			mutate(pos = cumsum(mean) - 0.5*mean,
					sex = factor(sex, sex))
plotdf <- ggplot(df, aes(x = 1, y = mean*100, fill = sex, label = sex)) +
			geom_bar(stat = "identity") +
			geom_text(aes(y = pos*100, label = paste(round(mean*100, 0), " %", "\n", sex))) +
			scale_fill_manual(values = ifelse(df$sex == "Male", "#CDA000", "#A7172B")) +
			coord_flip() +
			theme(axis.title = element_blank(),
					axis.text.y = element_blank())
plotdf
```

**Comment by DarioBoh** [comment]
I don't think this is a misbehavior
First, `scale_fill_manual(c("#CDA000", "#A7172B"))` should give you expect. In fact, you want to pass to `values` a vector of your color palette. Those colors are then associated to the levels of `sex` after coercing to a factor (thus alphabetically by default).

**Comment by ptoche** [comment]
As far as I know, the order will be the order of the factors. Female is first (I guess because F<M).

    df <- data.frame(sex = c("Male", "Female"), mean = c(0.359, 0.641))
    str(df)
    'data.frame':	2 obs. of  2 variables:
     $ sex : Factor w/ 2 levels "Female","Male": 2 1
     $ mean: num  0.359 0.641
