### ISSUE TITLE
Feature Request: factet_page

### ISSUE THREAD

**Issue by kmace** [tidyverse/ggplot2#2444]
#One thing I would love to stop doing is wrapping a ggplot call inside a for loop to get multiple plots (one per page).

I imagine it would be easy to implement a `facet_page` function that worked similarly to `facet_wrap` but would output the plots to separate pages, not wrapped on the same page. 

`facet_wrap` example:
```
mtcars %>% ggplot(aes(x = mpg, y = disp)) + geom_point() + facet_wrap(~cyl)
```
Desired `facet_page` example:
```
mtcars %>% ggplot(aes(x = mpg, y = disp)) + geom_point() + facet_page(~cyl) 
```

**Comment by smouksassi** [comment]
Dear Kmace,
are you aware of ggforce ?
https://cran.r-project.org/web/packages/ggforce/vignettes/Visual_Guide.html 
it provides:

```r
facet_grid_paginate
facet_wrap_paginate
```

**Comment by kmace** [comment]
I was not. Exactly what I was looking for. thank you.

**Comment by kmace** [comment]
This solved my issue: https://github.com/tidyverse/ggplot2/wiki/Share-a-legend-between-two-ggplot2-graphs
