### ISSUE TITLE
Zooming plot above certain resolution gives "invalid width"

### ISSUE THREAD

**Issue by kenbeek** [tidyverse/ggplot2#2448]
I'm using a 3440x1440 21:9 screen and displaying a plot in a too large window gives an "invalid width" error. I can't be sure of the exact threshold since I'm dragging the window border with my mouse but it seems to occur somewhere around a width of 2800-3000px.

Minimal repex:

```r
library(datasets)
library(ggplot2)
data(iris)

ggplot(iris, aes(x = Sepal.Length, y = Sepal.Width)) +
  geom_point()
```
Then click the "zoom" button in Rstudio and maximize the window on a screen with a sufficiently high resolution. The window will display an "invalid width" message instead of the plot.

Tested on Ubuntu 16.10 and in MacOS 10.13.3. 
R version 3.4.3 in both cases
ggplot2 version 2.2.1 in both cases

Is this intentional? Considering the increasing prevalence of 4k screens this seems relevant.

Thanks in advance.

**Comment by batpigandme** [comment]
I think this might be a graphics device issue. Pictured below is on a 27" 4k screen…
![image](https://user-images.githubusercontent.com/831732/36098669-cbb585dc-0fcd-11e8-9348-38a5f42e7ada.png)

**Comment by kenbeek** [comment]
Hi,

I was too quick in making this an issue. It also occurs with the R default plotting method, so this is not a ggplot2 issue.

Thanks.
