### ISSUE TITLE
setting height argument 0 (zero) in geom_jitter can be really vital :)

### ISSUE THREAD

**Issue by cankutcubuk** [tidyverse/ggplot2#2453]
Setting height argument always 0 (zero) in geom_jitter can be life saving :)
For the data which have zero variance it is better to use always height=0  in geom_jitter function.
Otherwise the results are not correctly visualized. 

Please see below;

**without height = 0**
```
#rm(list=ls())
library(ggplot2)
mpg$hwy <- 1
p2 <- ggplot(mpg, aes(class, hwy))
p2 <- p2 + geom_boxplot()
p2 <- p2 + geom_boxplot() + geom_jitter(width = 0.2)
p2
```

![rplot](https://user-images.githubusercontent.com/17905535/36211327-3bea7856-11a1-11e8-940c-4d12bfd6e41d.jpeg)

**Now with height = 0**
```
library(ggplot2)
mpg$hwy <- 1
p2 <- ggplot(mpg, aes(class, hwy))
p2 <- p2 + geom_boxplot()
p2 <- p2 + geom_boxplot() + geom_jitter(width = 0.2, height = 0)
p2
```
![rplot01](https://user-images.githubusercontent.com/17905535/36211469-96a82414-11a1-11e8-9cb6-cff6c6082ad0.jpeg)

**Comment by hadley** [comment]
Yes, `geom_jitter` has to guess the default amounts and you will often need to override.
