### ISSUE TITLE
position dodge doesn't actually dodge

### ISSUE THREAD

**Issue by MarauderPixie** [tidyverse/ggplot2#2455]
Similar to issue #2106 
Since it was flagged as fixed back then: my current ggplot version is `2.2.1.9000`; I tried using the CRAN as well as the current github version.

```r
library(tidyverse)

df <- tibble(x = rep(factor(2006:2015), 2), 
             y = rnorm(20, .5, .15),
             z = rep(c("A", "B"), 10))

ggplot(df, aes(x, y, fill = z)) +
  geom_col(position = "dodge", alpha = .4)
```

![rplot](https://user-images.githubusercontent.com/16045982/36352606-b4878a8e-14bb-11e8-8252-3d003adb1bff.png)

**Comment by batpigandme** [comment]
Hi @MarauderPixie,

I guess I'm unclear as to which (if any) of these matches your expected outcome. I think you might want `position = "dodge2"`, but that's just a guess, really.

``` r
library(tidyverse)

df <- tibble(x = rep(factor(2006:2015), 2), 
             y = rnorm(20, .5, .15),
             z = rep(c("A", "B"), 10))

ggplot(df, aes(x, y, fill = z)) +
  geom_col(position = "dodge", alpha = .4)
```

![](https://i.imgur.com/rGm17EL.png)

``` r

ggplot(df, aes(x, y, fill = z)) +
  geom_col(alpha = .4)
```

![](https://i.imgur.com/59yCIVT.png)

``` r

ggplot(df, aes(x, y, fill = z)) +
  geom_col(position = "dodge2", alpha = .4)
```

![](https://i.imgur.com/aSx3rRq.png)


Created on 2018-02-19 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by MarauderPixie** [comment]
Hi, thank you, that's it! Just when I thought I had ggplot figured out quite well... m)
