### ISSUE TITLE
Error: Found object ("histogram") is not a geom, says update_geom_defaults()

### ISSUE THREAD

**Issue by DesiQuintans** [tidyverse/ggplot2#2456]
I was trying to set the default aesthetics for a `geom_histogram()`, so I naturally typed:

```r
library("ggplot2")
update_geom_defaults("histogram", list(fill = "tomato"))

# Error: Found object is not a geom.
```

But then I guessed that `geom_histogram()` must be shorthand for `geom_bar(stat = "bin")`, and that worked fine. 

```r
update_geom_defaults("bar", list(fill = "tomato"))
qplot(data = diamonds, x = price, geom = "histogram")
```

Maybe "histogram" can be recognised by `update_geom_defaults()` to save future ggplotonauts some confusion? Perhaps warn that it's actually `geom_bar` being edited?

**Comment by rmcd1024** [comment]
+1 
I just got caught by trying to specify "histogram"

**Comment by hadley** [comment]
This function is for advanced use only, and generally I don't think it's a good idea to rely on it. For this reason, the current behaviour will stay, even though I agree that it's suboptimal.
