### ISSUE TITLE
ggplot2 installation issue?

### ISSUE THREAD

**Issue by sgoodm8** [tidyverse/ggplot2#2461]
Hey everyone,

New programmer here working on a school project. I thought I had successfully installed ggplot2 but it doesn't seem to be working. As a result, library(caret) doesn't load properly either which I also need. I checked to make sure I was running the most updated version and I am. The error message is below.

> library(ggplot2)
Error: package or namespace load failed for ‘ggplot2’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 namespace ‘pillar’ 1.0.1 is being loaded, but >= 1.1.0 is required

If anyone has any suggestions/knowledge on how to solve this it would be much appreciated!

**Comment by batpigandme** [comment]
Hi @sgoodm8 ,

From looking quickly above, it looks like you need to update your installation of pillar. However, this sort of question is generally a better fit for https://community.rstudio.com. Do you mind asking it over there? (You might want to read https://www.tidyverse.org/help/ first to maximise your chances of getting a good answer!)

**Comment by Elham-Rahmani** [comment]
install ggplot2 by the following command. I had the same problem it solved after this command:

**devtools::install_github("tidyverse/ggplot2")**
