### ISSUE TITLE
Error in UseMethod("margin") :    no applicable method for 'margin' applied to an object of class "c('double', 'numeric')"

### ISSUE THREAD

**Issue by Dilini-Sewwandi-Rajapaksha** [tidyverse/ggplot2#2462]
I get this error when I am trying to plot the interpretations from the lime algorithm using ggplot. 
Could you please tell me how to fix this error

**Comment by batpigandme** [comment]
This sort of question is a better fit for https://community.rstudio.com. Do you mind asking it over there? (You might want to read https://www.tidyverse.org/help/ first to maximise your chances of getting a good answer, which will, undoubtedly involve your including a [reprex](http://reprex.tidyverse.org/) (short for minimal **repr**oducible **ex**ample).

If you've never heard of a reprex before, the [reprex dos and don'ts](http://reprex.tidyverse.org/articles/reprex-dos-and-donts.html) are also useful.)
