### ISSUE TITLE
Documentation request: using `..quantile..` to map aesthetics with geom_quantile()

### ISSUE THREAD

**Issue by tzoltak** [tidyverse/ggplot2#2463]
I think it will be useful to add an example of using `..quantile..` to map easthetics with `geom_quantile()` to the documentation of this function:

```r
# You can use ..quantile.. to change the look of lines describing different quantiles
ggplot(mpg, aes(displ, 1 / hwy)) +
  geom_quantile(aes(linetype = factor(..quantile..))) +
  scale_linetype_discrete("quantile")
```

**Comment by hadley** [comment]
I'd accept a PR that added this to the documentation, but I'm unlikely to do it myself, since styling computed variables is a general principle that applies across all stats.
