### ISSUE TITLE
Legend title is incorrectly aligned when horizontal

### ISSUE THREAD

**Issue by hadley** [tidyverse/ggplot2#2465]
``` r
library(ggplot2)

df <- data.frame(z = 1:5)
p <- ggplot(df, aes(1, 1, colour = z)) + geom_point()

# Title should be centered with legend
p + theme(legend.position = "top")
```

![](https://i.imgur.com/a4niJZg.png)

**Comment by hadley** [comment]
@clauswilke have you seen this too? I quickly skimmed through your PRs but I didn't see anything that addressed this explicitly

**Comment by clauswilke** [comment]
I haven't addressed or modified this in any way. What is happening is that the title is centered relative to the entire legend:

```{r}
p + theme(legend.position = "top") + 
  theme(legend.spacing.y = grid::unit(50, "cm")) # 50 cm equals to 5 cm because of issue #2398
```
<img width="580" alt="screen shot 2018-05-01 at 5 49 25 pm" src="https://user-images.githubusercontent.com/4210929/39497334-7267c3cc-4d68-11e8-9761-5ce18a673fc1.png">

**Comment by clauswilke** [comment]
Note that `guide_legend()` behaves exactly the same:
```{r}
df <- data.frame(z = 1:5)
p <- ggplot(df, aes(1, 1, colour = factor(z))) + 
  geom_point() + 
  scale_color_discrete(guide = guide_legend(label.position = "bottom"))

# Title should be centered with legend
p + theme(legend.position = "top") + theme(legend.spacing.y = grid::unit(5, "cm"))
```
<img width="580" alt="screen shot 2018-05-01 at 5 56 08 pm" src="https://user-images.githubusercontent.com/4210929/39497446-ff881e5a-4d68-11e8-88bc-567959ffabc2.png">

**Comment by hadley** [comment]
Oh so this probably isn't a regression

**Comment by clauswilke** [comment]
The bigger issue, in my mind, is that there is no simple workaround, because the `vjust` setting is ignored. I'm showing this here with both a discrete and a continuous scale, to show that they behave the same:

```{r}
library(ggplot2)
p <- ggplot(mtcars, aes(hp, disp, color = mpg, shape = factor(cyl))) +
  geom_point(size = 2) +
  scale_shape_discrete(guide = guide_legend(label.position = "bottom")) + 
  theme(legend.position = "top")
p
```
<img width="647" alt="screen shot 2018-05-06 at 3 14 39 pm" src="https://user-images.githubusercontent.com/4210929/39677440-636d62f6-5140-11e8-9102-67aa50f2a27b.png">


```{r}
p + theme(legend.title = element_text(vjust = 1, colour = "red"))
```
<img width="647" alt="screen shot 2018-05-06 at 3 14 29 pm" src="https://user-images.githubusercontent.com/4210929/39677441-69fcf5aa-5140-11e8-9353-e417458b71da.png">
(I've colored the legend title red to show that styling the legend title works, only the justification arguments are ignored.)

I'll see if there's a simple way to fix this that doesn't require touching much code. In the long run, I think the legend drawing code needs to be rethought from the ground up, but that's not for 2.3.0.

**Comment by ptoche** [comment]
Workaround of sorts:

``` r
library(ggplot2)
ggplot(mtcars, aes(hp, disp, color = mpg, shape = factor(cyl))) +
    geom_point(size = 2) +
    theme(legend.position = "top") +
    guides(shape = guide_legend(label.position = "bottom", title.position = "left", title.vjust = 0.8), color = guide_legend(label.position = "top", title.position = "right", title.vjust=0.4))
```

![](https://i.imgur.com/QT2BcPC.png)

Created on 2018-05-07 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by clauswilke** [comment]
I now see that there are (at least) two separate issues. One is that `vjust` and `hjust` can't be set in the theme but can be set via the guide function. It is a simple fix to allow setting via the theme as well. The second is that the margin settings in `legend.title` are ignored. This is a problem because if we set `vjust` to a number other than 1 then the text is moved different amounts for grobs of different heights. I guess the workaround could be to manually fiddle with the `title.vjust` settings for each guide function until things look right, but if margins could be set that would be better I think.

```{r}
library(ggplot2)
ggplot(mtcars, aes(hp, disp, color = mpg, shape = factor(cyl))) +
  geom_point(size = 2) + theme(legend.position = "top") +
  guides(color = guide_colorbar(title.vjust = .8),
         shape = guide_legend(title.vjust = .8)) +
  theme(legend.title = 
          element_text(
            debug = TRUE,
            margin = margin(10, 0, 0, 0, "pt") # margin setting is ignored
          )
       )
```
<img width="626" alt="screen shot 2018-05-06 at 5 57 52 pm" src="https://user-images.githubusercontent.com/4210929/39678731-4cf7185c-5157-11e8-9260-af6ba95472ec.png">

**Comment by karawoo** [comment]
The latter issue about the margins for legend text/titles has been raised in #1502. I tried to tackle that after reworking `titleGrob()` last year, but wasn't able to wrap my head around the legend code enough to make any headway at the time.

**Comment by clauswilke** [comment]
@karawoo I just opened a pull request (https://github.com/tidyverse/ggplot2/pull/2556) that provides a partial fix for this issue. I hadn't seen https://github.com/tidyverse/ggplot2/issues/1502 previously and will take a look. My fix for legend titles would likely work for legend text as well.

**Comment by ptoche** [comment]
@clauswilke ,

    packageDescription("ggplot2")
    Package: ggplot2
    Version: 2.2.1
    Title: Create Elegant Data Visualisations Using the
          Grammar of Graphics
    Description: A system for 'declaratively' creating
          graphics, based on "The Grammar of Graphics".
          You provide the data, tell 'ggplot2' how to map
          variables to aesthetics, what graphical
          primitives to use, and it takes care of the
          details.
    Authors@R: c( person("Hadley", "Wickham", ,
          "hadley@rstudio.com", c("aut", "cre")),
          person("Winston", "Chang", ,
          "winston@rstudio.com", "aut"), person("RStudio",
          role = c("cph")) )
    Depends: R (>= 3.1)
    Imports: digest, grid, gtable (>= 0.1.1), MASS, plyr
          (>= 1.7.1), reshape2, scales (>= 0.4.1), stats,
          tibble, lazyeval
    Suggests: covr, ggplot2movies, hexbin, Hmisc, lattice,
          mapproj, maps, maptools, mgcv, multcomp, nlme,
          testthat (>= 0.11.0), quantreg, knitr, rpart,
          rmarkdown, svglite
    Enhances: sp
    License: GPL-2 | file LICENSE
    URL: http://ggplot2.tidyverse.org,
          https://github.com/tidyverse/ggplot2
    BugReports:
          https://github.com/tidyverse/ggplot2/issues
    LazyData: true
    Collate: 'ggproto.r' 'aaa-.r' 'aes-calculated.r' .....
    VignetteBuilder: knitr
    RoxygenNote: 5.0.1.9000
    NeedsCompilation: no
    Packaged: 2016-12-30 17:10:52 UTC; hadley
    Author: Hadley Wickham [aut, cre], Winston Chang
          [aut], RStudio [cph]
    Maintainer: Hadley Wickham <hadley@rstudio.com>
    Repository: CRAN
    Date/Publication: 2016-12-30 22:45:17
    Built: R 3.5.0; ; 2018-04-24 09:35:46 UTC; unix

**Comment by flying-sheep** [comment]
Also if you fiddle with `title.vjust`, the bounding box is unaffected. If you title is higher than the legend, this results in some seriously wrong spacing:

![grafik](https://user-images.githubusercontent.com/291575/49646625-e18f5f80-fa1f-11e8-9bf6-c0ab327201e5.png)

this is `title.vjust = 5` to make the bar line up with the second line of the title.

**Comment by ThomasDelSantoONeill** [comment]
Dear @clauswilke and @hadley 
I was wondering how to position the legend title on top of an horizontal scale_colour_gradient key. Is this possible at all? Also it seems that the key does not fill completely.
Cheers in advance!!! :)

![image](https://user-images.githubusercontent.com/43112803/79671050-4683c980-81bf-11ea-9376-80540762100f.png)

```
ggraph(lay.ggraph) +
  geom_edge_link0(aes(color = links$weight), width = links$weight*10, lineend = "round") + 
  scale_edge_color_gradient(name = "Link Strength", low = "#6495ED85", high = "#C1403D85") +
  geom_node_point(shape = 21, fill = "#D3D3D3", 
                  color = "#808080", size = 15, stroke = 2) +
  foodweb_theme +
  theme(legend.position = c(0.9, 0.1),
        legend.direction = "horizontal") +
  labs(y = "TL")
```

**Comment by ThomasDelSantoONeill** [comment]
Hi again, 

I did find a workaround solution. Only a bit of merging trickery was needed between `ggraph` and `ggplot2`. Basically everything missing needed to be inserted in the `guide = guide_edge_colorbar(...)` argument within `scale_edge_color_gradient`. For the "not enterly filled colorbar" key I set the upper limit a bit more than 1 (*i.e.* 1.1). Code:

```
ggraph(lay.ggraph) + 
  geom_edge_link0(aes(edge_colour = links$weight), edge_width = links$weight*10, lineend = "round") +
  scale_edge_color_gradient(name = "Link Strength", low = "#6495ED85", high = "#C1403D85",
                            limits = c(0,1.01),
                            guide = guide_edge_colorbar(title = "Link Strength", title.position = "top",
                                                        title.hjust = 0.5, ticks = TRUE, label = TRUE,
                                                        frame.colour = "black", barwidth = 7.5)) +
  geom_node_point(shape = 21, fill = "#D3D3D3", color = "#808080", size = 15, stroke = 2) +
  labs(y = "TL") +
  foodweb_theme
```
This produces:

![image](https://user-images.githubusercontent.com/43112803/79689945-dcffcb80-824f-11ea-8d6f-195f20e237e2.png)

All the absolute best!

**Comment by teunbrand** [comment]
I essentially think this is fixed now as you can tweak justification and margin settings as you please. The remaining issue now is that key-title alignment is uncomfortable, which is tracked in #1903. I'll close this for now, but feel free to re-open if there is a remaining part of this issue that isn't covered in #1903.
