### ISSUE TITLE
Error when the color argument has 0 levels

### ISSUE THREAD

**Issue by llrs** [tidyverse/ggplot2#2468]
This is related to a call to have more informative errors in tidyverse. It wasn't hard to track but it can be improved too. 
When an argument to color is passed as a factor with 0 levels it returns a non informative error. 
```r
p <- ggplot(iris, aes( Sepal.Length,  Sepal.Width, color = as.factor(NA)))
p
Error in seq.default(h[1], h[2], length.out = n) : 
  'to' must be a finite number
```
It could be nice to either have a nice error message or handle this case as without any color. 

I'm not able to judge which one would be easier or if handling this cases as proposed would break anything. The user could check before passing the argument but sometimes we don't :'(

**Comment by hadley** [comment]
(Please don't include session info unless it's explicitly asked for, or you've used `reprex::reprex(..., si = TRUE)` to hide it away. I've deleted it from your issue to avoid cluttering up the discussion)

**Comment by hadley** [comment]
Moved to https://github.com/hadley/scales/issues/113
