### ISSUE TITLE
Misspelled stats in ggplot2.pdf

### ISSUE THREAD

**Issue by cooknl** [tidyverse/ggplot2#2470]
I was accomplishing the R4DS exercise on geom stat pairs and came across some missing underscores for bin_2d, density_2d, and bin_hex.

Are these mistakes? If not, they are confusing, since there doesn't see to be a consistent naming pattern.

| geom_      | default stat   |
|:-----------|:---------------|
| bin2d      | bin2d          |
| density_2d | density2d      |
| hex        | binhex         |

| stat_       | default geom   |
|:------------|:---------------|
| bin_2d      | tile           |
| density_2d  | density_2d     |
| bin_hex     | hex            |

**Comment by hadley** [comment]
They are not mistakes unfortunately; and it's now too hard to change these mistakes.

**Comment by cooknl** [comment]
No worries, just surprised since the other conventions in the tidyverse are so consistent. We all have things that are "beyond fixing," though. :smile:
