### ISSUE TITLE
facet_grid uses unexpected environment to evaluate I(.) (AsIs) -- trouble with ad-hoc faceting

### ISSUE THREAD

**Issue by MichaelChirico** [tidyverse/ggplot2#2474]
I'm trying to facet by an ad-hoc column like so:

```
library(ggplot2)
NN = 100
DF = data.frame(x = rnorm(NN), grp1 = runif(NN) > .3, grp2 = runif(NN))
ggplot() + 
  geom_density(data = DF, aes(x = x, group = grp1)) +
  facet_grid(. ~ I(grp2 > .6))
# Error in structure(x, class = unique(c("AsIs", oldClass(x)))) : 
#   object 'grp2' not found

# compare to (works as expected, only difference is
#   grp2_break was ad-hoc above, explicitly
#   defined here)
DF$grp2_break = DF$grp2 > .6
ggplot() + 
  geom_density(data = DF, aes(x = x, group = grp1)) +
  facet_grid(. ~ grp2_break)
```

That is, my code fails saying `grp2` not found. But it seems to still have `DF` in scope (i.e., it's not that I've suddenly introduced a new column), as seen in the latter snippet where we add the ad-hoc column, which works as expected.

My current workaround is to call `DF` directly, but this is unworkable if the `data` input is dynamic/subsetted/any case where a direct call to `DF` is impossible:

```
ggplot() + 
  geom_density(data = DF, aes(x = x, group = grp1)) +
  facet_grid(. ~ I(DF$grp2 > .6))
```

Is this expected behavior? It should be documented if so, since this differs from the expected `formula` functionality.

------

FWIW this came up when I was trying to facet the hours of the day into a 4x6 grid; the way I thought to do this is `facet_grid(I(hour %% 4) ~ I(hour %/%4))`. Neither of those quantities makes sense to store as a new variable, they're simply dummies to trick `facet_grid` into giving me what I want. It doesn't solve the issue presented above (which rears its head in other forms as well), but I'm open to other suggestions to accomplish this as well.

**Comment by thomasp85** [comment]
What happens if you simply remove I()?

**Comment by MichaelChirico** [comment]
Fails with the same error; anyway, if the intended behavior is, say `I(grp2 + 1)`, or `I(100*proportion)`, this can't work within a formula due to special interpretation of operators.

**Comment by hadley** [comment]
Could you please rework your reproducible example to use the [reprex package](http://reprex.tidyverse.org) ? That makes it easier to see both the input and the output, formatted in such a way that I can easily re-run in a local session.

**Comment by MichaelChirico** [comment]
@hadley sorry I don't understand what exactly you're after... I updated my comment so that all of the relevant code is in a single code block, and copy-pasted the error message, in case that helps.

**Comment by hadley** [comment]
The problem is that you're supplying the data to the individual layer - facetting data typically needs to go to the plot.

``` r
library(ggplot2)
NN = 100
DF = data.frame(x = rnorm(NN), grp1 = runif(NN) > .3, grp2 = runif(NN))
ggplot(DF) + 
  geom_density(aes(x = x, group = grp1)) +
  facet_grid(. ~ (grp2 > .6))
```

![](https://i.imgur.com/AYr3KEh.png)

Created on 2018-05-09 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).
