### ISSUE TITLE
hjust inconsistent in strip.text: text is still self-centered

### ISSUE THREAD

**Issue by econandrew** [tidyverse/ggplot2#2478]
This may be the same underlying issue as #1892 but I don't think the explanation there covers this consequence:

![Example](https://i.imgur.com/5oanmU5.png)

```r
library(ggplot2)

p <- ggplot(mtcars, aes(cyl, mpg)) +
  geom_point() +
  theme(strip.text.x = element_text(hjust = 0))

# hjust correctly aligns the text block
p + facet_wrap(~ am, labeller = as_labeller(c(
    `0` = "This is manual. Or is it auto?",
    `1` = "This is auto. Or is it manual?"
  )))

# but it doesn't align the text itself, visible when there's a line break
p + facet_wrap(~ am, labeller = as_labeller(c(
    `0` = "This is manual.\nOr is it auto?",
    `1` = "This is auto. Or is it manual?"
  )))

# Unlike other themed elements
p + xlab(paste0(
    "This is probably the number of cylinders, and you have to wonder\n",
    "if anyone ever made a car with an odd number of cylinders"
  )) +
  theme(axis.title.x = element_text(hjust = 0))
}
```

**Comment by karawoo** [comment]
This is fixed in the development version of ggplot2, which you can install with `devtools::install_github("tidyverse/ggplot2")`.

``` r
library(ggplot2)

p <- ggplot(mtcars, aes(cyl, mpg)) +
  geom_point() +
  theme(strip.text.x = element_text(hjust = 0))

p + facet_wrap(~ am, labeller = as_labeller(c(
  `0` = "This is manual.\nOr is it auto?",
  `1` = "This is auto. Or is it manual?"
)))
```

![](https://i.imgur.com/KI1CiWH.png)

Created on 2018-03-09 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by batpigandme** [comment]
Since you're having trouble with reprex, I ran it for you. I'm a little confused about what you're expecting vs. what's happening, so if you wouldn't mind just stating that plainly that would be great (I'm sure I could parse it with careful attention to the referenced issue, and the code comments, but it'll make your issue more skimmable— or I'm missing something obvious, always a possibility).
``` r
library(ggplot2)

p <- ggplot(mtcars, aes(cyl, mpg)) +
  geom_point() +
  theme(strip.text.x = element_text(hjust = 0))

# hjust correctly aligns the text block
p + facet_wrap(~ am, labeller = as_labeller(c(
  `0` = "This is manual. Or is it auto?",
  `1` = "This is auto. Or is it manual?"
)))
```

![](https://i.imgur.com/lbbz6V0.png)

``` r

# but it doesn't align the text itself, visible when there's a line break
p + facet_wrap(~ am, labeller = as_labeller(c(
  `0` = "This is manual.\nOr is it auto?",
  `1` = "This is auto. Or is it manual?"
)))
```

![](https://i.imgur.com/cxQvNVz.png)

``` r

# Unlike other themed elements
p + xlab(paste0(
  "This is probably the number of cylinders, and you have to wonder\n",
  "if anyone ever made a car with an odd number of cylinders"
)) +
  theme(axis.title.x = element_text(hjust = 0))
```

![](https://i.imgur.com/O2Zng9Q.png)

Created on 2018-03-09 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by batpigandme** [comment]
@econandrew, also, FYI: Messerschmitt KR200, among others (Ford Fiesta Ecoboost one year, at least)… 😏
https://en.wikipedia.org/wiki/Messerschmitt_KR200
