### ISSUE TITLE
Possible aesthetics width and lwd not documented

### ISSUE THREAD

**Issue by JoFAM** [tidyverse/ggplot2#2479]
In order to produce a plot with error bars, I discovered the aesthetics "width" in the examples here : http://ggplot2.tidyverse.org/reference/geom_linerange.html

Trying to locate this in the help pages for my class, I found out that width is mentioned nowhere. Also the possible aesthetic lwd (which also works in geom_errorbar() ) is not documented. If you tell me where this goes best, I can fork and add the information to the help pages.

**Comment by hadley** [comment]
Those are just aliases for the size aesthetic.

**Comment by JoFAM** [comment]
Thanks for the info. I did spend quite some time trying to locate that information though. Wouldn't it make more sense to use the appropriate aesthetic in the examples instead of undocumented aliases? That could save the next one stumbling upon that a wild goosehunt for more information.

**Comment by hadley** [comment]
Oh, if you want to fix those examples, that would be great!

**Comment by JoFAM** [comment]
I wanted to (forked), but apparently width is not an alias of size, only lwd. If you tell me where to document width, I'll add it.
```

reprex({
  library(ggplot2)
  df <- data.frame(
    trt = factor(c(1, 1, 2, 2)),
    resp = c(1, 5, 3, 4),
    group = factor(c(1, 2, 1, 2)),
    upper = c(1.1, 5.3, 3.3, 4.2),
    lower = c(0.8, 4.6, 2.4, 3.6)
  )
  
  p <- ggplot(df, aes(trt, resp, colour = group))
  p + geom_errorbar(aes(ymin = lower, ymax = upper), width = 0.2)
  p + geom_errorbar(aes(ymin = lower, ymax = upper), size = 0.2)
  p + geom_errorbar(aes(ymin = lower, ymax = upper), width = 0.2, size = 2)
  
}, outfile = "E:/Temp/reprex"
)

```

**Comment by hadley** [comment]
Rather than documenting the rarely use aliases, I think it would be better to just eliminate their use in the examples.

**Comment by JoFAM** [comment]
@hadley But `width` and `size` do not do the same thing. I agree on `lwd`, that shouldn't be used instead of `size`. Yet, in `geom_errorbar()` size defines the line width and `width` defines the width of the whiskers. So one can't really replace it, unless there's another documented aesthetic that controls the whisker width.

That's why I proposed adding it to the documentation. Which I'm still willing to do btw
