### ISSUE TITLE
A possible geom_table

### ISSUE THREAD

**Issue by aphalo** [tidyverse/ggplot2#2484]
I am the author and maintainer of 'ggpmisc'. In the Bitbucket version of 'ggpmisc' at "aphalo/ggpmisc" I have defined a `geom_table` that uses almost the same syntax as `ggplot2::geom_text` but accepts tibbles mapped to `label`. The code relies on package 'gtable' for much of actual work.

For this to work tibbles need to be handled by 'ggplot2' as such all the way through to geoms. This is the case for 'ggplot2' 2.2.1.9000. This has been working as far back as May 2017, but I think it was made possible by a commit even earlier in 2017.

So, I have two questions:
1) Is this something you would like to add to 'ggplot2'? (would add a dependency on 'gtable').
2) If it seems preferable to keep `geom_table` in 'ggpmisc', do you have any idea of when 'ggplot2' 2.2.2 will make it to CRAN? (this is related to deciding on whether to delay the next update to 'ggpmisc' until the release of 'ggplot2' 2.2.2 or create a branch without this geom for CRAN.

A example follows:
```
library(tibble)
library(ggplot2)
library(ggpmisc)

tb <- tibble("alpha" = c("x[2]~\"=\"~a^2", "sqrt(y)"), 
             "beta" = c("x[2]~\"=\"~b^2", "sqrt(1/y)"))
my.tb <- tibble(x = 0, y = 0, tb = list(tb))
ggplot(my.tb, aes(x, y, label = tb)) +
  geom_table(parse = TRUE)
```
![image](https://user-images.githubusercontent.com/2743159/37509889-eeba5d12-2901-11e8-956a-60d78ff03bc8.png)

package    * version     date       source                            
 assertthat   0.2.0       2017-04-11 CRAN (R 3.4.0)                    
 backports    1.1.2       2017-12-13 CRAN (R 3.4.3)                    
 base       * 3.4.3       2017-12-15 local                             
 callr        2.0.2       2018-02-11 CRAN (R 3.4.3)                    
 colorspace   1.3-2       2016-12-14 CRAN (R 3.4.0)                    
 compiler     3.4.3       2017-12-15 local                             
 crayon       1.3.4       2017-09-16 CRAN (R 3.4.1)                    
 datasets   * 3.4.3       2017-12-15 local                             
 debugme      1.1.0       2017-10-22 CRAN (R 3.4.2)                    
 devtools     1.13.5      2018-02-18 CRAN (R 3.4.3)                    
 digest       0.6.15      2018-01-28 CRAN (R 3.4.3)                    
 evaluate     0.10.1      2017-06-24 CRAN (R 3.4.0)                    
 ggplot2    * 2.2.1.9000  2018-02-24 Github (tidyverse/ggplot2@39e4a3b)
 ggpmisc    * 0.2.16.9003 2017-11-07 local                             
 glue         1.2.0       2017-10-29 CRAN (R 3.4.2)                    
 graphics   * 3.4.3       2017-12-15 local                             
 grDevices  * 3.4.3       2017-12-15 local                             
 grid         3.4.3       2017-12-15 local                             
 gridExtra    2.3         2017-09-09 CRAN (R 3.4.1)                    
 gtable       0.2.0       2016-02-26 CRAN (R 3.4.0)                    
 htmltools    0.3.6       2017-04-28 CRAN (R 3.4.0)                    
 httpuv       1.3.6.2     2018-03-02 CRAN (R 3.4.3)                    
 jsonlite     1.5         2017-06-01 CRAN (R 3.4.0)                    
 knitr        1.20        2018-02-20 CRAN (R 3.4.3)                    
 labeling     0.3         2014-08-23 CRAN (R 3.4.0)                    
 lazyeval     0.2.1       2017-10-29 CRAN (R 3.4.2)                    
 magrittr     1.5         2014-11-22 CRAN (R 3.4.0)                    
 memoise      1.1.0       2017-04-21 CRAN (R 3.4.0)                    
 methods    * 3.4.3       2017-12-15 local                             
 mime         0.5         2016-07-07 CRAN (R 3.4.0)                    
 miniUI       0.1.1       2016-01-15 CRAN (R 3.4.0)                    
 munsell      0.4.3       2016-02-13 CRAN (R 3.4.0)                    
 pillar       1.2.1       2018-02-27 CRAN (R 3.4.3)                    
 plyr         1.8.4       2016-06-08 CRAN (R 3.4.0)                    
 purrr        0.2.4       2017-10-18 CRAN (R 3.4.2)                    
 R6           2.2.2       2017-06-17 CRAN (R 3.4.0)                    
 Rcpp         0.12.16     2018-03-13 CRAN (R 3.4.3)                    
 reprex       0.1.2       2018-01-26 CRAN (R 3.4.3)                    
 rlang        0.2.0.9000  2018-02-24 Github (tidyverse/rlang@b6b6df5)  
 rmarkdown    1.9         2018-03-01 CRAN (R 3.4.3)                    
 rprojroot    1.3-2       2018-01-03 CRAN (R 3.4.3)                    
 rstudioapi   0.7         2017-09-07 CRAN (R 3.4.1)                    
 scales       0.5.0.9000  2017-09-01 Github (hadley/scales@d767915)    
 shiny      * 1.0.5       2017-08-23 CRAN (R 3.4.1)                    
 shinyjs      1.0         2018-01-08 CRAN (R 3.4.3)                    
 stats      * 3.4.3       2017-12-15 local                             
 stringi      1.1.7       2018-03-12 CRAN (R 3.4.3)                    
 stringr      1.3.0       2018-02-19 CRAN (R 3.4.3)                    
 tibble     * 1.4.2       2018-01-22 CRAN (R 3.4.3)                    
 tools        3.4.3       2017-12-15 local                             
 utils      * 3.4.3       2017-12-15 local                             
 vdiffr       0.2.2       2018-02-01 CRAN (R 3.4.3)                    
 whisker      0.3-2       2013-04-28 CRAN (R 3.4.0)                    
 withr        2.1.1.9000  2018-02-24 Github (jimhester/withr@5d05571)  
 xtable       1.8-2       2016-02-05 CRAN (R 3.4.0)                    
 yaml         2.1.18      2018-03-08 CRAN (R 3.4.3)

**Comment by thomasp85** [comment]
There is no problem with the gtable dependency as ggplot2 relies heavily on gtable itself.

I personally think that such a geom belongs in an extension package such as ggpmisc as it, while certainly useful, is a niche feature. Hadley is the one deciding that though.

**Comment by aphalo** [comment]
o.k., let's wait for Hadley's thoughts. There is no hurry about this. As for usefulness one example is adding ANOVA tables to plots which is no doubt a niche feature in the sense of the grammar of graphics. I do not show it in the example, but 'hjust', 'vjust' and 'angle' are also implemented, as well as 'x' and 'y', and the list of tibbles mapped to `label` can be of length > 1. One nice feature in 'gtable' is also available: not all cells need to contain strings that can be parsed even if `parse = TRUE` is used. One advantage of including it in 'ggplot2' would be easier integration of the 'ggtable' themes. By looking at some recent commits here, it seems that 'ggplot2' 2.2.2 will make this easier anyway.
We can also keep this decision open, and decide about a possible _migration_ of `geom_table` to 'ggplot2' in the future as a migration would be very unlikely to break any user code.

**Comment by hadley** [comment]
This would be much better in an extension package.

**Comment by aphalo** [comment]
o.k., thanks! Just wanted to make sure.
