### ISSUE TITLE
Warning message: package ‘ggplot2’ was built under R version 3.4.4 

### ISSUE THREAD

**Issue by RawanRadi** [tidyverse/ggplot2#2486]
I'm tried to install ggplot2 in R but when I used it i get this warning

`> library("ggplot2")
Warning message:
package ‘ggplot2’ was built under R version 3.4.4`

this when I install ggplot2 library

`> install.packages('ggplot2', dependencies = TRUE)
Installing package into ‘C:/Users/COMNET/Documents/R/win-library/3.4’
(as ‘lib’ is unspecified)
also installing the dependencies ‘curl’, ‘openssl’, ‘checkmate’, ‘htmlwidgets’, ‘rstudioapi’, ‘zoo’, ‘rex’, ‘httr’, ‘withr’, ‘Formula’, ‘latticeExtra’, ‘acepack’, ‘gridExtra’, ‘data.table’, ‘htmlTable’, ‘viridis’, ‘sp’, ‘mvtnorm’, ‘TH.data’, ‘sandwich’, ‘praise’, ‘SparseM’, ‘MatrixModels’, ‘Rcpp’, ‘gdtools’, ‘covr’, ‘ggplot2movies’, ‘hexbin’, ‘Hmisc’, ‘mapproj’, ‘maps’, ‘maptools’, ‘multcomp’, ‘testthat’, ‘quantreg’, ‘knitr’, ‘svglite’

trying URL 'https://cloud.r-project.org/bin/windows/contrib/3.4/curl_3.1.zip'
Content type 'application/zip' length 3470563 bytes (3.3 MB)
downloaded 3.3 MB

trying URL 'https://cloud.r-project.org/bin/windows/contrib/3.4/openssl_1.0.1.zip'
Content type 'application/zip' length 3572840 bytes (3.4 MB)
downloaded 3.4 MB

trying URL 'https://cloud.r-project.org/bin/windows/contrib/3.4/checkmate_1.8.5.zip'
Content type 'application/zip' length 628308 bytes (613 KB)
downloaded 613 KB

trying URL 'https://cloud.r-project.org/bin/windows/contrib/3.4/htmlwidgets_1.0.zip'
Content type 'application/zip' length 852831 bytes (832 KB)
downloaded 832 KB

trying URL 'https://cloud.r-project.org/bin/windows/contrib/3.4/rstudioapi_0.7.zip'
Content type 'application/zip' length 129988 bytes (126 KB)
downloaded 126 KB

trying URL 'https://cloud.r-project.org/bin/windows/contrib/3.4/zoo_1.8-1.zip'
Content type 'application/zip' length 915521 bytes (894 KB)
downloaded 894 KB

trying URL 'https://cloud.r-project.org/bin/windows/contrib/3.4/rex_1.1.2.zip'
Content type 'application/zip' length 102532 bytes (100 KB)
downloaded 100 KB

trying URL 'https://cloud.r-project.org/bin/windows/contrib/3.4/httr_1.3.1.zip'
Content type 'application/zip' length 301911 bytes (294 KB)
downloaded 294 KB

trying URL 'https://cloud.r-project.org/bin/windows/contrib/3.4/withr_2.1.2.zip'
Content type 'application/zip' length 123720 bytes (120 KB)
downloaded 120 KB

trying URL 'https://cloud.r-project.org/bin/windows/contrib/3.4/Formula_1.2-2.zip'
Content type 'application/zip' length 164600 bytes (160 KB)
downloaded 160 KB

trying URL 'https://cloud.r-project.org/bin/windows/contrib/3.4/latticeExtra_0.6-28.zip'
Content type 'application/zip' length 2069681 bytes (2.0 MB)
downloaded 2.0 MB

trying URL 'https://cloud.r-project.org/bin/windows/contrib/3.4/acepack_1.4.1.zip'
Content type 'application/zip' length 91520 bytes (89 KB)
downloaded 89 KB

trying URL 'https://cloud.r-project.org/bin/windows/contrib/3.4/gridExtra_2.3.zip'
Content type 'application/zip' length 1084663 bytes (1.0 MB)
downloaded 1.0 MB

trying URL 'https://cloud.r-project.org/bin/windows/contrib/3.4/data.table_1.10.4-3.zip'
Content type 'application/zip' length 1576742 bytes (1.5 MB)
downloaded 1.5 MB

trying URL 'https://cloud.r-project.org/bin/windows/contrib/3.4/htmlTable_1.11.2.zip'
Content type 'application/zip' length 245706 bytes (239 KB)
downloaded 239 KB

trying URL 'https://cloud.r-project.org/bin/windows/contrib/3.4/viridis_0.5.0.zip'
Content type 'application/zip' length 1714241 bytes (1.6 MB)
downloaded 1.6 MB

trying URL 'https://cloud.r-project.org/bin/windows/contrib/3.4/sp_1.2-7.zip'
Content type 'application/zip' length 1538269 bytes (1.5 MB)
downloaded 1.5 MB

trying URL 'https://cloud.r-project.org/bin/windows/contrib/3.4/mvtnorm_1.0-7.zip'
Content type 'application/zip' length 233555 bytes (228 KB)
downloaded 228 KB

trying URL 'https://cloud.r-project.org/bin/windows/contrib/3.4/TH.data_1.0-8.zip'
Content type 'application/zip' length 5213315 bytes (5.0 MB)
downloaded 5.0 MB

trying URL 'https://cloud.r-project.org/bin/windows/contrib/3.4/sandwich_2.4-0.zip'
Content type 'application/zip' length 1243028 bytes (1.2 MB)
downloaded 1.2 MB

trying URL 'https://cloud.r-project.org/bin/windows/contrib/3.4/praise_1.0.0.zip'
Content type 'application/zip' length 17942 bytes (17 KB)
downloaded 17 KB

trying URL 'https://cloud.r-project.org/bin/windows/contrib/3.4/SparseM_1.77.zip'
Content type 'application/zip' length 968526 bytes (945 KB)
downloaded 945 KB

trying URL 'https://cloud.r-project.org/bin/windows/contrib/3.4/MatrixModels_0.4-1.zip'
Content type 'application/zip' length 202855 bytes (198 KB)
downloaded 198 KB

trying URL 'https://cloud.r-project.org/bin/windows/contrib/3.4/Rcpp_0.12.16.zip'
Content type 'application/zip' length 4372188 bytes (4.2 MB)
downloaded 4.2 MB

trying URL 'https://cloud.r-project.org/bin/windows/contrib/3.4/gdtools_0.1.7.zip'
Content type 'application/zip' length 3420279 bytes (3.3 MB)
downloaded 3.3 MB

trying URL 'https://cloud.r-project.org/bin/windows/contrib/3.4/covr_3.0.1.zip'
Content type 'application/zip' length 121127 bytes (118 KB)
downloaded 118 KB

trying URL 'https://cloud.r-project.org/bin/windows/contrib/3.4/ggplot2movies_0.0.1.zip'
Content type 'application/zip' length 1250506 bytes (1.2 MB)
downloaded 1.2 MB

trying URL 'https://cloud.r-project.org/bin/windows/contrib/3.4/hexbin_1.27.2.zip'
Content type 'application/zip' length 684761 bytes (668 KB)
downloaded 668 KB

trying URL 'https://cloud.r-project.org/bin/windows/contrib/3.4/Hmisc_4.1-1.zip'
Content type 'application/zip' length 1820136 bytes (1.7 MB)
downloaded 1.7 MB

trying URL 'https://cloud.r-project.org/bin/windows/contrib/3.4/mapproj_1.2-5.zip'
Content type 'application/zip' length 85464 bytes (83 KB)
downloaded 83 KB

trying URL 'https://cloud.r-project.org/bin/windows/contrib/3.4/maps_3.2.0.zip'
Content type 'application/zip' length 3631295 bytes (3.5 MB)
downloaded 3.5 MB

trying URL 'https://cloud.r-project.org/bin/windows/contrib/3.4/maptools_0.9-2.zip'
Content type 'application/zip' length 1823866 bytes (1.7 MB)
downloaded 1.7 MB

trying URL 'https://cloud.r-project.org/bin/windows/contrib/3.4/multcomp_1.4-8.zip'
Content type 'application/zip' length 633403 bytes (618 KB)
downloaded 618 KB

trying URL 'https://cloud.r-project.org/bin/windows/contrib/3.4/testthat_2.0.0.zip'
Content type 'application/zip' length 1197792 bytes (1.1 MB)
downloaded 1.1 MB

trying URL 'https://cloud.r-project.org/bin/windows/contrib/3.4/quantreg_5.35.zip'
Content type 'application/zip' length 2129187 bytes (2.0 MB)
downloaded 2.0 MB

trying URL 'https://cloud.r-project.org/bin/windows/contrib/3.4/knitr_1.20.zip'
Content type 'application/zip' length 919796 bytes (898 KB)
downloaded 898 KB

trying URL 'https://cloud.r-project.org/bin/windows/contrib/3.4/svglite_1.2.1.zip'
Content type 'application/zip' length 642589 bytes (627 KB)
downloaded 627 KB

trying URL 'https://cloud.r-project.org/bin/windows/contrib/3.4/ggplot2_2.2.1.zip'
Content type 'application/zip' length 2786010 bytes (2.7 MB)
downloaded 2.7 MB

package ‘curl’ successfully unpacked and MD5 sums checked
package ‘openssl’ successfully unpacked and MD5 sums checked
package ‘checkmate’ successfully unpacked and MD5 sums checked
package ‘htmlwidgets’ successfully unpacked and MD5 sums checked
package ‘rstudioapi’ successfully unpacked and MD5 sums checked
package ‘zoo’ successfully unpacked and MD5 sums checked
package ‘rex’ successfully unpacked and MD5 sums checked
package ‘httr’ successfully unpacked and MD5 sums checked
package ‘withr’ successfully unpacked and MD5 sums checked
package ‘Formula’ successfully unpacked and MD5 sums checked
package ‘latticeExtra’ successfully unpacked and MD5 sums checked
package ‘acepack’ successfully unpacked and MD5 sums checked
package ‘gridExtra’ successfully unpacked and MD5 sums checked
package ‘data.table’ successfully unpacked and MD5 sums checked
package ‘htmlTable’ successfully unpacked and MD5 sums checked
package ‘viridis’ successfully unpacked and MD5 sums checked
package ‘sp’ successfully unpacked and MD5 sums checked
package ‘mvtnorm’ successfully unpacked and MD5 sums checked
package ‘TH.data’ successfully unpacked and MD5 sums checked
package ‘sandwich’ successfully unpacked and MD5 sums checked
package ‘praise’ successfully unpacked and MD5 sums checked
package ‘SparseM’ successfully unpacked and MD5 sums checked
package ‘MatrixModels’ successfully unpacked and MD5 sums checked
package ‘Rcpp’ successfully unpacked and MD5 sums checked
package ‘gdtools’ successfully unpacked and MD5 sums checked
package ‘covr’ successfully unpacked and MD5 sums checked
package ‘ggplot2movies’ successfully unpacked and MD5 sums checked
package ‘hexbin’ successfully unpacked and MD5 sums checked
package ‘Hmisc’ successfully unpacked and MD5 sums checked
package ‘mapproj’ successfully unpacked and MD5 sums checked
package ‘maps’ successfully unpacked and MD5 sums checked
package ‘maptools’ successfully unpacked and MD5 sums checked
package ‘multcomp’ successfully unpacked and MD5 sums checked
package ‘testthat’ successfully unpacked and MD5 sums checked
package ‘quantreg’ successfully unpacked and MD5 sums checked
package ‘knitr’ successfully unpacked and MD5 sums checked
package ‘svglite’ successfully unpacked and MD5 sums checked
package ‘ggplot2’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\COMNET\AppData\Local\Temp\RtmpqmbJUE\downloaded_packages

`

**Comment by batpigandme** [comment]
The warning is just a warning - everything should work just fine. Looks like the installations were successful as well.
