### ISSUE TITLE
Odd binning in geom_dotplot() -- but or feature?

### ISSUE THREAD

**Issue by rpruim** [tidyverse/ggplot2#2495]
The bins in the example below appear to be centered at `(0, 2, 4, 6, 8, 11, 14, 16)/10`.  The seems odd an undesirable.  Bug?  Side-effect of fuzzy binning? 

``` r
library(ggplot2)
D <- data.frame(prop = (0:8) / 50)
ggplot() + geom_dotplot(aes(x = prop), binwidth = 1/50, dotsize = 0.5, data = D)
```

![](https://i.imgur.com/HTMSgaS.png)

Created on 2018-03-22 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by wch** [comment]
I suspect it's due to rounding error inherent in those values.

```R
0:8/50
#> [1] 0.00 0.02 0.04 0.06 0.08 0.10 0.12 0.14 0.16
diff(0:8/50)
#> [1] 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02
diff(diff(0:8/50))
#> [1]  0.000000e+00 -3.469447e-18  6.938894e-18  0.000000e+00 -1.387779e-17
#> [6]  2.775558e-17 -2.775558e-17
```

With divisors other than 50, the doubled-up location can be different:

```R
library(ggplot2)
x <- 10
prop <- 0:8/x
diff(diff(prop))
#> [1]  0.000000e+00 -2.775558e-17  5.551115e-17 -5.551115e-17  0.000000e+00
#> [6]  0.000000e+00  1.110223e-16
D <- data.frame(prop = prop)
ggplot() + geom_dotplot(aes(x = prop), binwidth = 1/x, dotsize = 0.5, data = D)
```
![image](https://user-images.githubusercontent.com/86978/37811039-9623c00c-2e25-11e8-8a03-3469c84b466e.png)


With a nice power of 2, like 32, there's no rounding error, and the plot comes out as expected.

```R
library(ggplot2)
x <- 32
prop <- 0:8/x
diff(diff(prop))
#> [1] 0 0 0 0 0 0 0
D <- data.frame(prop = prop)
ggplot() + geom_dotplot(aes(x = prop), binwidth = 1/x, dotsize = 0.5, data = D)
```
![image](https://user-images.githubusercontent.com/86978/37811089-e68aab6e-2e25-11e8-9672-64d1da67a366.png)

**Comment by rpruim** [comment]
But why do the doubled up dots not show up in what would seem to be the natural bin location?  Does dot plot place dots at places other than the centers of bins?

**Comment by rpruim** [comment]
Things do seem to work better if we use "histodot".  But it still seems odd that things that are dust away from 0.10 and 0.12 (due to machine precision) plot at 0.11 in the original plot.  Is it the fact that each is shaded a bit toward 0.11 that causes them to plot there?


``` r
library(ggplot2)
D <- data.frame(prop = (0:8) / 50)
ggplot() + geom_dotplot(aes(x = prop), binwidth = 1/50, method = "histodot", dotsize = 0.5, data = D)
```

![](https://i.imgur.com/oaAJNWc.png)

Created on 2018-03-23 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by wch** [comment]
With the dot-density algorithm, the bin positions are determined by the data. Wilkinson's paper explains it clearly:
  https://www.cs.uic.edu/~wilkinson/Publications/dotplots.pdf

Here's an image from the paper:
![image](https://user-images.githubusercontent.com/86978/37811705-c9ef8a20-2e29-11e8-8b67-9d6c490673db.png)
