### ISSUE TITLE
No errors when size and color are not constant over the line and linetype is dotted / dashed

### ISSUE THREAD

**Issue by irudnyts** [tidyverse/ggplot2#2496]
The code below
`
ggplot(mtcars) +
  geom_line(aes(mpg, wt, colour = factor(cyl),
                linetype = factor(am), size = gear))
` 
produces the following error: 
`
Error: geom_path: If you are using dotted or dashed lines, colour, size and linetype must be constant over the line
`

However, this code works without throwing the error message: 

`
ggplot(mtcars) +
  geom_line(aes(mpg, wt, colour = factor(cyl),
                linetype = factor(am), size = factor(gear)))
`

even though the color and size are not constant over the line. As well as those snippets: 

`
ggplot(mtcars) +
  geom_line(aes(mpg, wt, colour = factor(cyl), size = factor(gear)), linetype = 2)

ggplot(mtcars) +
  geom_line(aes(mpg, wt, colour = factor(cyl)), linetype = 2)

ggplot(mtcars) +
  geom_line(aes(mpg, wt, size = factor(cyl)), linetype = 2)
`

It seems that either 1) the error message is wrong and should change "constant" to "discrete" because the error is thrown only in case continuous variables or 2) just a bug.

**Comment by batpigandme** [comment]
Could you please turn this into a self-contained [reprex](http://reprex.tidyverse.org/) (short for minimal **repr**oducible **ex**ample)? It will help us help you if we can be sure we're all working with/looking at the same stuff.

If you've never heard of a reprex before, you might want to start by reading the tidyverse.org [help page](https://www.tidyverse.org/help/).

**Comment by hadley** [comment]
There are three lines, not one, because using a discrete aesthetic automatically groups the data.
