### ISSUE TITLE
facet_wrap() giving error in development version

### ISSUE THREAD

**Issue by tbradley1013** [tidyverse/ggplot2#2497]
Hi, 

I updated to the development versions of `rlang` and `ggplot2` and ran into an issue with `facet_wrap`. I re-installed the CRAN versions of both and `facet_wrap` works under the CRAN version. I have attached a `reprex` of the problem below:

```
library(ggplot2)

# getting error using either the formula method or vars()
# when trying to use facet_wrap
ggplot(iris, aes(Sepal.Length, Sepal.Width)) + 
  facet_wrap(~Species) + 
  geom_point()
#> Error: `predicate` must be a closure or function pointer

# same thing but with vars()
ggplot(iris, aes(Sepal.Length, Sepal.Width)) + 
  facet_wrap(vars(Species)) + 
  geom_point()
#> Error: `predicate` must be a closure or function pointer

# facet_grid works
ggplot(iris, aes(Sepal.Length, Sepal.Width)) + 
  facet_grid(vars(Species)) + 
  geom_point()
```

![image](https://user-images.githubusercontent.com/23705496/37834933-5f8521ca-2e85-11e8-9a05-3bc39f87c607.png)

```r
ggplot(iris, aes(Sepal.Length, Sepal.Width)) + 
  facet_grid(~ Species) + 
  geom_point()
```
![image](https://user-images.githubusercontent.com/23705496/37834963-6c5f4d62-2e85-11e8-98a2-dbd40bb1fedb.png)

#' Created on 2018-03-23 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by tbradley1013** [comment]
I just restarted my computer and reinstalled `rlang` and `ggplot2` from github and now the facet_wrap works. I am not sure what changed. It seemed like the issue may have something to do with the `flatten_if()` call [here](https://github.com/tidyverse/ggplot2/blob/master/R/facet-wrap.r#L117), but since it is no longer happening I will close the issue.

**Comment by JoGall** [comment]
I'm experiencing the same error (R 3.4.1, Windows 10).

I've reinstalled `ggplot2` from GitHub as well as reinstalling dependencies `rlang`, `withr`, `svglite`, and `scales`, all without error.

Reprex:
```
ggplot(iris, aes(Sepal.Length, Sepal.Width)) +
  geom_point() +
  facet_wrap(~Species)
```

**Comment by batpigandme** [comment]
@JoGall did you install ggplot2 from GitHub? Based on @tbradley1013's answer, it looks like the fix was in the dev version.

``` r
# devtools::install_github("tidyverse/ggplot2")
library(ggplot2)
ggplot(iris, aes(Sepal.Length, Sepal.Width)) +
  geom_point() +
  facet_wrap(~Species)
```

![](https://i.imgur.com/HoXeuBo.png)

Created on 2018-04-10 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by JoGall** [comment]
Thanks for the quick reply @batpigandme.

Just updated R to 3.4.4 and reinstalled `ggplot2` from GitHub but I'm still getting the same error.

Interestingly, just realised `facet_grid` still works as expected though 🤔

**Comment by batpigandme** [comment]
@tbradley1013 just to double check, this is no longer true for you, correct?

**Comment by JoGall** [comment]
FYI: Just tried re-installing `ggplot2` from CRAN and `facet_wrap` works fine for me.

**Comment by tbradley1013** [comment]
I definitely got it to work after I first filed the issue but I had since reverted back to the CRAN versions of the packages. However, after just installing the latest dev versions from Github, I am getting the error again for facet_wrap with both the `~` and `vars()` approaches

**Comment by batpigandme** [comment]
OK, thanks @tbradley1013 — I'll reopen. I could be wrong, but I'm pretty sure that, based on the [release notes](https://github.com/tidyverse/ggplot2/blob/master/NEWS.md) this shouldn't be happening.

**Comment by lionel-** [comment]
rlang is in Remotes so if you install the dev version of `ggplot2` with its dependencies it should work out of the box. How did you install it?

**Comment by tbradley1013** [comment]
I installed it using the current CRAN release of devtools. In addition, I always have to first install `rlang` and then` ggplot2` because I get an error about not being able to replace the current version of `rlang` when I install via `ggplot2` dependency.

**Comment by lionel-** [comment]
> I always have to first install rlang and thenggplot2 because I get an error about not being able to replace the current version of rlang when I install via ggplot2 dependency.

Does it work after restarting the session?

**Comment by tbradley1013** [comment]
I created a new packrat project and installed the CRAN version of `devtools` followed by the dev version of `ggplot2` (with dependencies) and the `facet_wrap` issue is not happening for me anymore. 

As for installing of `rlang` via `ggplot2`, it worked in the packrat environment. But I normally restart my R sessions when I install packages so I would imagine I tried that when I got that error but can't say for sure.

**Comment by AdeelH** [comment]
This issue is still happening. 

The culprit is the following call to `rlang::flatten_if`added in (https://github.com/tidyverse/ggplot2/commit/3c9c504fdb2f2c6b70a98d5a02f6cdf2c8cc62c9#diff-8b0f5dd209eb5cd8b4184145460503f6R117) in the definition of facet_wrap():
`facets <- rlang::flatten_if(facets_list, is.list)`

`facet_grid()` works as normal because it does not call `faltten_if()`.

The error 
```
Error: `predicate` must be a closure or function pointer
```
can be reproduced with `rlang::flatten_if(list(), is.list)`. 

I would suggest changing the line to 
`facets <- rlang::flatten_if(facets_list, rlang::is_list)`
