### ISSUE TITLE
Better pipe support

### ISSUE THREAD

**Issue by foldager** [tidyverse/ggplot2#2506]
ggplot uses addition between the different elements. I see the argument against using a the pipe operator, especially because ggplot does not use function composition. However, I find piping into ggplot a  a bit awkward, and I propose that a kind of sum function is added that makes piping cleaner. The piping is especially awkward when the return value is piped further on.

In the examples below I use print as a placeholder function, this could be a function that handled saving the plot.

    plotting_function <- print

Example using plain ggplot. Note the ugly parentheses needed because of the precedence of pipe over plus operators.

    # Parentheses needed. Ends after ggtitle()
    (mtcars %>% 
        ggplot() +
            aes(x=hp, y=mpg) +
            geom_point() +
            geom_smooth() +
            ggtitle('Fantastic Plot')) %>%
        plotting_function()

Example implementation:

    ggplot_sum <- function(data, ...){
        p <- ggplot(data)
        args = list(...)
        for (arg in args){
            p <- p + arg
        }
        return (p)
    }

Which allow you to nicely group the ggplotting

    mtcars %>% 
        ggplot_sum(
            aes(x=hp, y=mpg),
            geom_point(),
            geom_smooth(),
            ggtitle('Fantastic Plot')) %>%
        plotting_function()

I think it is a good call to not include the pipe operator as rejected in #2326, but I still think the interaction with the tidyverse could be improved. An alternative to the above is to use `add` from `magrittr`

    mtcars %>% 
        ggplot() %>%
        add(aes(x=hp, y=mpg)) %>%
        add(geom_point()) %>%
        add(geom_smooth()) %>%
        add(ggtitle('Fantastic Plot')) %>%
        plotting_function()

I think the `ggplot_sum` is much cleaner and I like how it groups plotting elements together.

**Comment by batpigandme** [comment]
Please see Hadley's explanation here:
https://community.rstudio.com/t/why-cant-ggplot2-use/4372/7
