### ISSUE TITLE
theme_gray() default settings broken ggplot version 2.2.1

### ISSUE THREAD

**Issue by statsandthings** [tidyverse/ggplot2#2511]
*I'm using R version 3.4.3 and ggplot2 version 2.2.1.* 

The theme_gray() default major gridlines (for me) used to be something like `size 1` and `color white`. The default *minor* gridlines were something like `size rel(0.25)` and `color grey95`. At some point in time these default settings stopped, and now my *major* and *minor* gridlines are identical. See output below.

I want my old defaults back for theme_gray() and all the themes for that matter. And what bug caused them to swap to the settings below? I don't save any environments and always start R fresh (following reproducible guidelines) yet this problem persists. Themes don't carryover session to session anyways so it shouldn't matter. I'm stumped.

```r
library(ggplot2)
#> Warning: package 'ggplot2' was built under R version 3.4.4
theme_get()$panel.grid.major
#> List of 6
#>  $ colour       : chr "white"
#>  $ size         : NULL
#>  $ linetype     : NULL
#>  $ lineend      : NULL
#>  $ arrow        : logi FALSE
#>  $ inherit.blank: logi TRUE
#>  - attr(*, "class")= chr [1:2] "element_line" "element"
theme_get()$panel.grid.minor
#> List of 6
#>  $ colour       : chr "white"
#>  $ size         : num 0.25
#>  $ linetype     : NULL
#>  $ lineend      : NULL
#>  $ arrow        : logi FALSE
#>  $ inherit.blank: logi TRUE
#>  - attr(*, "class")= chr [1:2] "element_line" "element"
```

**Comment by batpigandme** [comment]
https://github.com/tidyverse/ggplot2/blob/master/NEWS.md#themes
> Themes now set default grid colour in panel.grid rather than individually in panel.grid.major and panel.grid.minor individually. This makes it slightly easier to customise the grid (#2352).

It should still have the same relative contrast (see changeset here)
https://github.com/tidyverse/ggplot2/commit/caca650c2a7891fdc7d7f14c377845bce46673f4

The change from grey95 to white seems to be in a commit from August 2015
https://github.com/tidyverse/ggplot2/commit/9641250133d39c6eaf931165d9ae16fc4a3c6d8e#diff-9029508150cd2b9e8ac2a30f5e5b799aL109
``` r
library(ggplot2)
p <- ggplot(mtcars) + geom_point(aes(x = wt, y = mpg,
                                     colour = factor(gear))) + facet_wrap(~am)
p + theme_gray() +
  ggtitle("Current theme_gray")
```

![](https://i.imgur.com/XHHZW2j.png)

``` r

theme_get()$panel.grid
#> List of 6
#>  $ colour       : chr "white"
#>  $ size         : NULL
#>  $ linetype     : NULL
#>  $ lineend      : NULL
#>  $ arrow        : logi FALSE
#>  $ inherit.blank: logi TRUE
#>  - attr(*, "class")= chr [1:2] "element_line" "element"

p + theme_gray() +
  ggtitle("Adjusted to reflect Aug. 2015 theme_gray") +
  theme(panel.grid.minor =   element_line(colour = "grey95", size = 0.25))
```

![](https://i.imgur.com/tdVFhH7.png)
Created on 2018-04-04 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by statsandthings** [comment]
I tried the new `$panel.grid` you mention and I receive NULL feedback. Is something else going on here?

```
library(ggplot2)
#> Warning: package 'ggplot2' was built under R version 3.4.4
theme_get()$panel.grid
#> NULL
```

If I run your reprex (part 1) I still have the same issue. I will use karawoo's code as a temporary band-aid. Thanks for that.

```
library(ggplot2)
p <- ggplot(mtcars) + geom_point(aes(x = wt, y = mpg,
                                     colour = factor(gear))) + facet_wrap(~am)
p + theme_gray() +
  ggtitle("Current theme_gray")
```

[![current.png](https://s9.postimg.org/w2u3j2m4v/current.png)](https://postimg.org/image/9e4wji4qz/)

Part 2 of your reprex works as expected.

```
theme_get()$panel.grid
#> NULL

p + theme_gray() +
  ggtitle("Adjusted to reflect Aug. 2015 theme_gray") +
  theme(panel.grid.minor =   element_line(colour = "grey95", size = 0.25))
```

[![adjusted.png](https://s9.postimg.org/tlicbthnz/adjusted.png)](https://postimg.org/image/ozm83gw4r/)

**Comment by batpigandme** [comment]
The null is because you ran it before plotting anything and, thus, have no theme to get. It's all one reprex, the plots just show up as they come. As noted in the title, the first plot is as ggplot2 is now, and the latter uses the settings as they were in 2015 - @karawoo is using the same code (theme_gray as it was in Aug 2015), the theme parameters are just  put _before_ the ggplot2 code using `theme_set()`.  `theme_set()` will also have the benefit of propagating across your session. You could even build your own custom theme to apply, if you so choose. Your "as expected" is no longer the default behaviour of ggplot2.

**Comment by statsandthings** [comment]
This issue seems to be isolated to Windows operating systems. Originally I had the issues on a Windows 7 system. I later tried to duplicate the issue on a Linux box and could not. Then I tried to recreate the issue on a Windows 10 system and was able to first try. I updated to the development version of ggplot2 on all systems, unfortunately that didn't change anything. And they're all running the same versions of R and R Studio. I finally got that theme_get() to work by following batpigandme's advice and the output is below (Windows systems).

```
theme_get()$panel.grid
#> List of 6
#>  $ colour       : chr "white"
#>  $ size         : NULL
#>  $ linetype     : NULL
#>  $ lineend      : NULL
#>  $ arrow        : logi FALSE
#>  $ inherit.blank: logi TRUE
#>  - attr(*, "class")= chr [1:2] "element_line" "element"
```

**Comment by batpigandme** [comment]
@karawoo, at least for me, if you start in a fresh session, load ggplot2 and do `theme_get()` _before_ your first call to ggplot, it's NULL. This makes sense to me, since nothing really has a theme yet. Is this not the intended behaviour?
If that's an issue worth troubleshooting, I think it makes sense to open a fresh thread, since it's distinct from the aesthetics of the grid lines.
