### ISSUE TITLE
Setting color for axis.line no longer works

### ISSUE THREAD

**Issue by mattwilliamson13** [tidyverse/ggplot2#2512]
---
I have been generating a series of plots with black backgrounds and white annotation. This worked for most of the day (image of successfully created plot attached)
![numlt](https://user-images.githubusercontent.com/6482513/38339747-24222b26-382d-11e8-8d86-cea13ec664ef.jpeg)
; however, in the last hour the color control of axis.line seems to have stopped working. I have pasted a an example of the problem using the example from ggplot below. This renders a black plot with no axis lines. 

```r
df <- data.frame(
  gp = factor(rep(letters[1:3], each = 10)),
  y = rnorm(30)
)
ds <- plyr::ddply(df, "gp", plyr::summarise, mean = mean(y), sd = sd(y))

ggplot(df) +
  geom_point(aes(gp, y)) +
  geom_point(data = ds, aes(gp, mean), colour = 'red', size = 3)  +
  theme(legend.position="none", text=element_text(size=20,  
                                                  family="Times New Roman"),
        plot.background = element_rect(fill = 'black', colour = 'black'), 
        panel.background = element_rect(fill = 'black', colour = 'white'),
        axis.text = element_text(size=20, family="Times New Roman", colour="white"),
        axis.title = element_text(size=20, family="Times New Roman", colour="white"),
        axis.line = element_line(colour="white"))
```

**Comment by mattwilliamson13** [comment]
This actually seems to result from some sort of conflict with `cowplot`.  The plot renders as expected if I do not load `cowplot`

**Comment by ptoche** [comment]
close this?
