### ISSUE TITLE
no applicable method for 'depth' applied to an object of class "NULL"

### ISSUE THREAD

**Issue by berkorbay** [tidyverse/ggplot2#2514]
This is not exactly a reproducible problem on my side but it is displayed after an "overuse" of ggplot. The exact error is given below.

```
Error in UseMethod("depth") : 
  no applicable method for 'depth' applied to an object of class "NULL"
```
When I restart R session or do a `gc()` the plot is displayed properly. Sometimes before I get the error I get a distorted plot. It almost feels like the system cannot use the required resources. 

It happened to me with different versions of ggplot2 (both github and cran) and on different computers/OSes and settings. I also somehow couldn't find a similar question on SO, here or elsewhere. 

Sorry if I couldn't offer much info about the problem I had but I am having it repeatedly. Here is the version info of the system where I had the latest incident.

```
platform       x86_64-apple-darwin15.6.0   
arch           x86_64                      
os             darwin15.6.0                
system         x86_64, darwin15.6.0        
status                                     
major          3                           
minor          4.3                         
year           2017                        
month          11                          
day            30                          
svn rev        73796                       
language       R                           
version.string R version 3.4.3 (2017-11-30)
nickname       Kite-Eating Tree            
```

**Comment by student-t** [comment]
I also have the same problem. New bugs in ggplot?

**Comment by berkorbay** [comment]
A small update. I can bypass the error by assigning the plot to an object and then running the object on the console instead of running the plot directly. Unfortunately, I still cannot provide a healthy reproducible example.

```r
#Instead of
ggplot(data,aes(x=x_axis,y=y_axis) + geom_point()

# This works
the_plot <- ggplot(data,aes(x=x_axis,y=y_axis) + geom_point()
the_plot
```

**Comment by clauswilke** [comment]
`depth` is a grid function. I wonder whether this is related to #2252. I've seen both problems randomly pop up when using R Studio. If I repeat what I just did the problem always goes away.

**Comment by slyrus** [comment]
I see this problem too when I resize the window in which my plots appear.

**Comment by mine-cetinkaya-rundel** [comment]
I ran into this issue when building a pkgdown site for a package where the examples contain ggplots. When I rebuilt the site, the error went away. I'm on `ggplot2_3.0.0`.

**Comment by eogoodwin** [comment]
> traceback()
16: depth(path)
15: upViewport(depth(vp), recording = FALSE)
14: popgrobvp.viewport(x$vp)
13: popgrobvp(x$vp)
12: postDraw.grob(x)
11: postDraw(x)
10: drawGTree(x)
9: recordGraphics(drawGTree(x), list(x = x), getNamespace("grid"))
8: grid.draw.gTree(x$children[[i]], recording = FALSE)
7: grid.draw(x$children[[i]], recording = FALSE)
6: drawGTree(x)
5: recordGraphics(drawGTree(x), list(x = x), getNamespace("grid"))
4: grid.draw.gTree(gtable)
3: grid.draw(gtable)
2: print.ggplot(x)
1: function (x, ...) 
   UseMethod("print")(x)

**Comment by jakehosen** [comment]
This has been a routine problem for me when using macos. I've had this problem on a number of machines with a number of different version of macos (10.11-10.14), but it appears to have increased in frequency over the last couple months (currently occurs almost every time I call ggplot). As with other folks, the code executes properly the second time or if a quartz window is currently open.
Here's the traceback:
12: depth(path)
11: upViewport(depth(vp), recording = FALSE)
10: popgrobvp.viewport(x$vp)
9: popgrobvp(x$vp)
8: postDraw.grob(x)
7: postDraw(x)
6: drawGTree(x)
5: recordGraphics(drawGTree(x), list(x = x), getNamespace("grid"))
4: grid.draw.gTree(gtable)
3: grid.draw(gtable)
2: print.ggplot(x)
1: function (x, ...) 
   UseMethod("print")(x)

**Comment by r2evans** [comment]
This happens to me almost every time a `ggplot2` plot window is up and I connect to my external monitor. To me, it seems like a situation where Windows is shifting window-sizes around (perhaps imperceptibly?), and it often completely crashes R. (Yay windows.)

**Comment by wilkox** [comment]
I've hit this error a few times running testthat tests that involve plotting. The test code runs fine in an interactive session, but fails (sometimes) with this error during automated testing. Adding

```r
grid::current.viewport()
```

to the top of the testthat scripts has worked to prevent the error.

**Comment by r2evans** [comment]
Since this won't get much attention without a reprex, and R crashing leaves it rather difficult to grab `traceback()`, does somebody know of a good way to capture enough information to help narrow down the problem?

**Comment by beansrowning** [comment]
For me, this has been an issue when using `CairoWin` with faceted plots.

**Comment by r2evans** [comment]
To round it out, for me it's always base-R graphics window (`windows()`, since I'm on win-10).

**Comment by NunoSempere** [comment]
It just experienced the same error after running a program for 1.12 hours, using *a lot* of memory. The program outputted the desired result, though.

Because I wasn't using ggplot2, I'm lead to think that the error might have more to do with the computer running out of memory, rather than anything ggplot2-specific.

**Comment by r2evans** [comment]
I haven't found any correlation between memory-usage or plot complexity and the crash: some plots were rather simple (and R usage low-volume).

**Comment by JuanMauricio97** [comment]
> 
> 
> A small update. I can bypass the error by assigning the plot to an object and then running the object on the console instead of running the plot directly. Unfortunately, I still cannot provide a healthy reproducible example.
> 
> ```r
> #Instead of
> ggplot(data,aes(x=x_axis,y=y_axis) + geom_point()
> 
> # This works
> the_plot <- ggplot(data,aes(x=x_axis,y=y_axis) + geom_point()
> the_plot
> ```

This worked for me. Thanks!
