### ISSUE TITLE
facet_wrap not working in dev version

### ISSUE THREAD

**Issue by andbarker** [tidyverse/ggplot2#2518]
Ive just installed the dev version of ggplot (2.2.1.9000), and facet_wrap now returns an error:

> Error: `predicate` must be a closure or function pointer

---

Here's an example where facet_grid works, but facet_wrap fails:

```r
# devtools::install_github("tidyverse/ggplot2")
library(ggplot2)

df <- mtcars

p <- ggplot(df, aes(x = mpg, y = disp)) +
  geom_point()

#Works
p + facet_grid(.~carb)

# Error: `predicate` must be a closure or function pointer
p + facet_wrap(~carb)


```

**Comment by batpigandme** [comment]
Thanks. I'm closing, since this is a duplicate of https://github.com/tidyverse/ggplot2/issues/2497
