### ISSUE TITLE
The new 'exprs' function has conflicts with some bioconductor packages

### ISSUE THREAD

**Issue by qinzhu** [tidyverse/ggplot2#2520]
I noticed in version 2.2.1.9000 there is a new "exprs" fucntion. This cause some bioconductor packages not function properly because "exprs" is also exported from Biobase and is very widely used. I'm wondering if the name of the function can be changed to some less common name in future releases? Otherwise I may have to wait for the bioconductor package authors to add "Biobase::" to every "expr" or override functions myself.

**Comment by renozao** [comment]
Duplicate issue of #2509.
I agree this is extremely disruptive and hope it will be fixed quickly.
