### ISSUE TITLE
Possible to get coef to behave in geom_boxplot like range behaves in boxplot?

### ISSUE THREAD

**Issue by pschloss** [tidyverse/ggplot2#2522]
The `coef` argument in `geom_boxplot` doesn't behave like the `range` argument like `boxplot`. It seems that these two arguments are meant to be the same thing. I would like the whiskers to extend to the extremes of the distribution. With base `boxplot` setting `range=0` will do this, but `range` won't work with `geom_boxplot`. Setting `coef` to 0 in `geom_boxplot` gets you no whiskers at all. One could set `coef` to an absurdly large number to achieve the goal, but if the IQR is 0, then it won't work. I see in the `geom_boxplot` example the other workaround is to populate the 5 cardinal values of the boxplot, but that's a lot for what seems like a simple goal.

```r
d <- diamonds[ sample(nrow(diamonds), 1000), ] %>% select(carat, cut)
garbage <- tibble(cut="garbage", carat=c(rep(0, 195), 1, 1.2, 2.3, 2.4, 3))
d_garbage <- rbind(d, garbage)

p <- ggplot(d_garbage, aes(x = cut, y = carat))
p + geom_boxplot()
p + geom_boxplot(range=0) #Warning: Ignoring unknown parameters: range
p + geom_boxplot(coef=0) #No whiskers
p + geom_boxplot(coef=10000) #Whiskers extend to extremes for everything but "garbage"

boxplot(d_garbage$carat ~ d_garbage$cut) #Output similar to p + geom_boxplot()
boxplot(d_garbage$carat ~ d_garbage$cut, range=0) #Desired output
```

**Comment by batpigandme** [comment]
Would you mind turning this into a [reprex](http://reprex.tidyverse.org/) (short for minimal **repr**oducible **ex**ample)? It's especially helpful for ggplot2, since it automatically generates and uploads the plots (or lack thereof), which makes it much easier to go through at a glance.

If you've never heard of a reprex before, you might want to start by reading the tidyverse.org [help page](https://www.tidyverse.org/help/).

Right now the best way to install reprex is:
```r
# install.packages("devtools")
devtools::install_github("tidyverse/reprex")
```
If you run into problems with access to your clipboard, you can specify an outfile for the reprex, and then copy and paste (or drag and drop) the contents here.

```r
reprex::reprex(input = "fruits_stringdist.R", outfile = "fruits_stringdist.md")
```

Thanks

**Comment by pschloss** [comment]
Seems I'll need to file a `reprex` bug report.

```
> reprex(input="reprod.R", outfile="reprod.md")
Preparing reprex as .R file to render:
  * reprod_reprex.R
Rendering reprex...
Error in (opts_knit$get("upload.fun"))(x) : 
  failed to upload reprod_reprex_files/figure-markdown_strict/reprex-body-1.png
```

**Comment by pschloss** [comment]
``` r
library(tidyverse)
d <- diamonds[ sample(nrow(diamonds), 1000), ] %>% select(carat, cut)
garbage <- tibble(cut="garbage", carat=c(rep(0, 195), 1, 1.2, 2.3, 2.4, 3))
d_garbage <- rbind(d, garbage)

p <- ggplot(d_garbage, aes(x = cut, y = carat))
p + geom_boxplot()
```

![](https://i.imgur.com/AMTGQcD.png)

``` r
p + geom_boxplot(range=0) #Warning: Ignoring unknown parameters: range
#> Warning: Ignoring unknown parameters: range
```

![](https://i.imgur.com/wTlkfB7.png)

``` r
p + geom_boxplot(coef=0) #No whiskers
```

![](https://i.imgur.com/9Kxcglt.png)

``` r
p + geom_boxplot(coef=10000) #Whiskers extend to extremes for everything but "garbage"
```

![](https://i.imgur.com/hlxpGzY.png)

``` r

boxplot(d_garbage$carat ~ d_garbage$cut) #Output similar to p + geom_boxplot()
```

![](https://i.imgur.com/4oxnVjU.png)

``` r
boxplot(d_garbage$carat ~ d_garbage$cut, range=0) #Desired output
```

![](https://i.imgur.com/TvamXP1.png)

Created on 2018-04-14 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by ptoche** [comment]
I understand your question. I was just looking for differences in the code to see if it would be easy/desirable to implement. In base R, the key lines of code are inside ``boxplot.stats`` (you can inspect the code by typing just that in the console). There, there is the conditional

    if (coef == 0) 
            do.out <- FALSE

where ``do.out`` is used to return ``out``, as in this line in the return statement: 

    out = if (do.out) x[out & nna] else numeric()

So when you set ``coef = 0``, ``boxplot.stats`` returns ``0`` for out. That value is then used in the ``boxplot`` formula. See [boxplot.r](https://raw.githubusercontent.com/wch/r-source/af7f52f70101960861e5d995d3a4bec010bc89e6/src/library/graphics/R/boxplot.R) . Then (unless I'm mistaken), it appears to be used in ``z$yout`` to set ``ylim`` (see the computation of the range). 

So it appears that the difference is that ``boxplot`` has a conditional on ``coef == 0``, which ``geom_boxplot`` does not have. 

Whether it's desirable to have, not sure...

**Comment by hadley** [comment]
I don't think setting `coef = 1` is a good idea in any circumstances, so I'm not motivated to make `stat_boxplot()` more complicated to handle this scenario.
