### ISSUE TITLE
install still fails after trying reinstalling R/load from local

### ISSUE THREAD

**Issue by wxlu718** [tidyverse/ggplot2#2523]
Hi I have issue installing ggplot2 for multiple tries. Was having version 3.4.3, it gave a warning message ---

package ‘ggplot2’ is not available (for R version 3.4.3) 

or 

package ‘tidyverse’ is not available (for R version 3.4.4) 

I also tried downloading the ggplot zip file from CRAN and loading package from my local directory. Then it gave the following messages ---

> utils:::menuInstallLocal()
ERROR: dependencies 'digest', 'gtable', 'plyr', 'reshape2', 'scales', 'tibble', 'lazyeval' are not available for package 'ggplot2'
* removing 'C:/Users/Wenxiao/Documents/R/win-library/3.4/ggplot2'
In R CMD INSTALL
Warning messages:
1: running command '"C:/PROGRA~1/R/R-34~1.4/bin/i386/R" CMD INSTALL -l "C:\Users\Wenxiao\Documents\R\win-library\3.4" "C:/Users/Wenxiao/Downloads/ggplot2_2.2.1.tar.gz"' had status 1 
2: In install.packages(files[tarballs], .libPaths()[1L], repos = NULL,  :
  installation of package ‘C:/Users/Wenxiao/Downloads/ggplot2_2.2.1.tar.gz’ had non-zero exit status

I even uninstalled R and have updated to the latest version (3.4.4). Same issue with same messages. I guess there must be something fundamental I miss there?

**Comment by batpigandme** [comment]
How are you installing ggplot2 initially? 
```r
install.packages("ggplot2")
```
or

```
# install.packages("devtools")
devtools::install_github("tidyverse/ggplot2")
```
If the first, try adding the `dependencies = TRUE` argument.

**Comment by wxlu718** [comment]
@batpigandme Tried that too. Also tried install from local path (download ggplot2 tar file separately). Both give the following messages ---

> install.packages("ggplot2",dependencies = TRUE)
Installing package into ‘C:/Users/Wenxiao/Documents/R/win-library/3.4’
(as ‘lib’ is unspecified)
Warning: unable to access index for repository https://cran.wu.ac.at/src/contrib:
  cannot open URL 'https://cran.wu.ac.at/src/contrib/PACKAGES'
Warning: unable to access index for repository http://www.stats.ox.ac.uk/pub/RWin/src/contrib:
  cannot open URL 'http://www.stats.ox.ac.uk/pub/RWin/src/contrib/PACKAGES'
Warning: unable to access index for repository https://cran.wu.ac.at/bin/windows/contrib/3.4:
  cannot open URL 'https://cran.wu.ac.at/bin/windows/contrib/3.4/PACKAGES'
Warning: unable to access index for repository http://www.stats.ox.ac.uk/pub/RWin/bin/windows/contrib/3.4:
  cannot open URL 'http://www.stats.ox.ac.uk/pub/RWin/bin/windows/contrib/3.4/PACKAGES'
Warning message:
package ‘ggplot2’ is not available (for R version 3.4.4) 

My suspicion is I don't have a valid CRAN mirror? I tried to select a few mirrors, get the error message all the time no matter what mirror I chose ---

> chooseCRANmirror()
Warning: failed to download mirrors file (cannot open URL 'https://cran.r-project.org/CRAN_mirrors.csv'); using local file 'C:/PROGRA~1/R/R-34~1.4/doc/CRAN_mirrors.csv'
Warning message:
In download.file(url, destfile = f, quiet = TRUE) :
  InternetOpenUrl failed: ''

Not sure if the two issues are related.

**Comment by ptoche** [comment]
This seems very localized. I suggest you close this issue.

**Comment by xiaojunwang195** [comment]
@wxlu718 Hello, I also met the same question, please ask how you solved this in the end.

**Comment by wxlu718** [comment]
@xiaojunwang195 Sorry still haven't come up with an solution :-(
