### ISSUE TITLE
Export Layout or create_layout

### ISSUE THREAD

**Issue by thomasp85** [tidyverse/ggplot2#2527]
As part of the rewrite of `gganimate` I'll need to reimplement `ggplot_build()` in order to insert additional steps. Apart from the call to `create_layout()`

https://github.com/tidyverse/ggplot2/blob/3c9c504fdb2f2c6b70a98d5a02f6cdf2c8cc62c9/R/plot-build.r#L44

everything else can be reimplemented with the current exports. `create_layout()` is a rather simple subclassing of the `Layout` class, so exporting either `create_layout()` or `Layout` (with internal keyword) would help me a lot in developing the new animation API.

I do understand the internal nature of these objects but I hope a more powerful animation API is worth the tradeoff

**Comment by thomasp85** [comment]
Thinking about this some more, I think it would probably be best to simply export the `Layout` class rather than `create_layout()` as users are much more unlikely to begin messing around with bare ggproto objects than with a function that has a somewhat alluring name...

**Comment by hadley** [comment]
Want to do this too?

**Comment by thomasp85** [comment]
Absolutely
