### ISSUE TITLE
inconsistency of color's alpha in plot and legend for geom_ribbon and geom_rect

### ISSUE THREAD

**Issue by ptoche** [tidyverse/ggplot2#2529]
I have struggled to use transparent colors with ``geom_rect`` and ``geom_ribbon``. I haven't been able to find a consistent way to get the legend colors match the fill color in the plot. I haven't measured the inconsistency though, it's based on my visual impression, but let me know if you notice the problem too. My workaround has been to tweak the value of alpha with ``override.aes`` inside ``guide_legend``, but it's not ideal. Is there a better workaround?

In the plot below, something between  ``guides(fill = guide_legend(override.aes = list(alpha = 0.1)))`` and  ``guides(fill = guide_legend(override.aes = list(alpha = 0.2)))`` seems to give a better result. Am I seeing this properly?

Note that below I have used ``adjustcolor()`` function, but the same problem is the same if I use ``"#FF000080"`` and ``"#0000FF80"``, which are obtained from blue and red by setting an alpha to 0.5.  I checked online that the hex values are correct.

``` r
library(ggplot2)
ggplot() + theme_bw() +
    geom_ribbon(aes(x = 0:5, ymin = 5, ymax = 0, fill = "red")) +
    geom_ribbon(aes(x = 5:10, ymin = 5, ymax = 10, fill = "red")) +
    geom_ribbon(aes(x = 0:5, ymin = 5, ymax = 10, fill = "blue")) +
    geom_ribbon(aes(x = 5:10, ymin = 0, ymax = 5, fill = "blue")) +
    scale_fill_manual(name = NULL, 
        values = adjustcolor(c("red", "blue"), alpha.f = 0.5)) +
    guides(fill = guide_legend(override.aes = list(alpha = 0.5))) 
```

![](https://i.imgur.com/egpU5zj.png)

Created on 2018-04-21 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by hadley** [comment]
Every layer gets an entry in the legend, so you need to turn some off:

```R
library(ggplot2)
ggplot() + theme_bw() +
    geom_ribbon(aes(x = 0:5, ymin = 5, ymax = 0, fill = "red")) +
    geom_ribbon(aes(x = 5:10, ymin = 5, ymax = 10, fill = "red"), show.legend = FALSE) +
    geom_ribbon(aes(x = 0:5, ymin = 5, ymax = 10, fill = "blue"), show.legend = FALSE) +
    geom_ribbon(aes(x = 5:10, ymin = 0, ymax = 5, fill = "blue"), show.legend = FALSE) +
    scale_fill_manual(name = NULL, 
        values = adjustcolor(c("red", "blue"), alpha.f = 0.5)) +
    guides(fill = guide_legend(override.aes = list(alpha = 0.5))) 
```

**Comment by ZelinC** [comment]
Hello, I am new to geom_ribbon, just a little bit confused with your code and the output graph. 
I read this code
`geom_ribbon(aes(x = 0:5, ymin = 5, ymax = 0, fill = "red")) `
 as fill area (0:5, 5:0) red, but it is blue in your plot?
Could you explain why? Many thanks!!

**Comment by ptoche** [comment]
Try ``geom_ribbon(aes(x = 0:5, ymin = 5, ymax = 0), fill = "red")`` and play around with putting things like ``color`` and ``fill`` inside the ``aes()`` function versus outside! :-)
