### ISSUE TITLE
"Scales" argument on facet_grid does not have any effect

### ISSUE THREAD

**Issue by SomeUser999** [tidyverse/ggplot2#2530]
Despite the following example in the "facet_grid" documentation, the "Scales" argument has no effect, regardless of it being "free" or "free_y/x". 

# Free scales -------------------------------------------------------
     # You can also choose whether the scales should be constant
     # across all panels (the default), or whether they should be allowed
     # to vary
     mt <- ggplot(mtcars, aes(mpg, wt, colour = factor(cyl))) +
       geom_point()
     
     mt + facet_grid(. ~ cyl, scales = "free")

Is there a solution to force facet_grid to have free scales?

**Comment by ptoche** [comment]
1. You have not explained the problem clearly. 2. If you run the example on the line immediately below at http://ggplot2.tidyverse.org/reference/facet_grid.html, you will see that ``free`` and ``fixed`` have very different output. 3. If you still want to pursue this issue, you should give a full ``reprex`` example and explain clearly what you expect and what you see, together with info about package versions, etc.. 

In the meantime, I suggest you close this issue.
