### ISSUE TITLE
Enable User Defined Theme Elements

### ISSUE THREAD

**Issue by nhamilton1980** [tidyverse/ggplot2#2540]
This issue is at the suggestion of Hadley, based on the following: 

https://github.com/tidyverse/ggplot2/pull/2305

I am the author of the [ggtern](http://ggtern.com) package, which requires a whole bunch (50+) of new theme elements outside of the standard ggplot2 themes defined in the non-exported `.element_tree` object.

In this issue I will speak of my experience with ggtern, however, it is possible that any extension author may face the same problem.

The complexity of ggtern (and its sensitivity to changes within ggplot2) can be HUGELY reduced if there was a mechanism for extension authors such as myself to be able to create their own theme elements, and add them to the `.element_tree`. The solution I had proposed within the above link (via use of R6 class) had resolved this, with no impinging effect or risk to existing ggplot2 functionality.

Because I cannot add new theme elements, this means that I need to duplicate the `.element_tree` within the ggtern package, and add my new theme elements / hierarchies. This in turn means that many of the plot construction routines also needs to be held as a duplicate inside the ggtern library, leading to fragilities and vulnerabilities to changes within base ggplot2, which happens almost every year. I am trying to remove these fragilities.

To me it seems very logical for extension authors to be able to create their own theme elements. At the moment there is no way to do this to my knowledge other than the method used in ggtern, which is far from ideal. The theme element tree offered by ggplot2 is quite substantial, but by no means is it exhaustive, as has been demonstrated in ggtern, requiring dozens more for it to function properly.

**Comment by clauswilke** [comment]
I have reviewed your pull request. If I understand correctly what you need for ggtern, your proposed solution seems way overengineered. In particular, adding a whole new class model (R6) to ggplot2 doesn't seem warranted. I'd also like to point out that your code doesn't follow the tidyverse style guide (http://style.tidyverse.org/), in particular with respect to spaces around `if`, `else`, `{`, and after commas.

If all you need is the ability to add new theme elements, that functionality can be achieved with one new function, `add_element()`. The only issue is that direct assignment to `.element_tree` is not possible, so it'd have to be stuck into an environment, like so:

```{r}
element_env <- new.env(parent = emptyenv())
element_env$element_tree <- list()

add_element <- function(key, element_def) {
  if (is.null(element_env$element_tree[[key]])) {
    element_env$element_tree <- c(
      element_env$element_tree,
      setNames(list(element_def), key)
    )
  } else {
    warning("trying to redefine existing element.")
  }
}
```

Now, we can do:
```{r}
add_element("text", ggplot2:::el_def("element_text"))
add_element("title", ggplot2:::el_def("element_text", "text"))
add_element("text", ggplot2:::el_def("element_line"))
# Warning message:
# In add_element("text", ggplot2:::el_def("element_line")) :
#   trying to redefine existing element.

element_env$element_tree[["text"]]
# $class
# [1] "element_text"
# 
# $inherit
# NULL
# 
# $description
# NULL
```
Not sure why you would need all the other features you make available, such as overwriting theme elements on the fly. Would you ever have the situation where a theme element's definition would change after the initial package setup?

**Comment by hadley** [comment]
Is this the same as #1730?

**Comment by nhamilton1980** [comment]
Yes, seems so.
--
Nicholas Hamilton, PhD
School of Materials Science and Engineering
University of New South Wales (Australia)
--
www.ggtern.com<http://www.ggtern.com>

On 10 May 2018, at 8:53 am, Hadley Wickham <notifications@github.com<mailto:notifications@github.com>> wrote:


Is this the same as #1730<https://github.com/tidyverse/ggplot2/issues/1730>?

**Comment by nhamilton1980** [comment]
Claus,

Thanks, sure perhaps my proposed solution was a bit over the top, I am really not too fussed how the end goal is achieved. Your solution seems simpler, I agree, however I wanted to make sure the base set of theme elements couldn’t get messed around with, whist still providing the ability for users to add new elements.

--
Nicholas Hamilton, PhD
School of Materials Science and Engineering
University of New South Wales (Australia)
--
www.ggtern.com<http://www.ggtern.com>

On 10 May 2018, at 12:40 am, Claus Wilke <notifications@github.com<mailto:notifications@github.com>> wrote:


I have reviewed your pull request. If I understand correctly what you need for ggtern, your proposed solution seems way overengineered. In particular, adding a whole new class model (R6) to ggplot2 doesn't seem warranted. I'd also like to point out that your code doesn't follow the tidyverse style guide (http://style.tidyverse.org/), in particular with respect to spaces around if, else, {, and after commas.

If all you need is the ability to add new theme elements, that functionality can be achieved with one new function, add_element(). The only issue is that direct assignment to .element_tree is not possible, so it'd have to be stuck into an environment, like so:

element_env <- new.env(parent = emptyenv())
element_env$element_tree <- list()

add_element <- function(key, element_def) {
  if (is.null(element_env$element_tree[[key]])) {
    element_env$element_tree <- c(
      element_env$element_tree,
      setNames(list(element_def), key)
    )
  } else {
    warning("trying to redefine existing element.")
  }
}


Now, we can do:

add_element("text", ggplot2:::el_def("element_text"))
add_element("title", ggplot2:::el_def("element_text", "text"))
add_element("text", ggplot2:::el_def("element_line"))
# Warning message:
# In add_element("text", ggplot2:::el_def("element_line")) :
#   trying to redefine existing element.

element_env$element_tree[["text"]]
# $class
# [1] "element_text"
#
# $inherit
# NULL
#
# $description
# NULL


Not sure why you would need all the other features you make available, such as overwriting theme elements on the fly. Would you ever have the situation where a theme element's definition would change after the initial package setup?

**Comment by clauswilke** [comment]
Nicholas,

> I wanted to make sure the base set of theme elements couldn’t get messed around with, whist still providing the ability for users to add new elements.

That would be the case with my proposed approach, since theme elements can be added but only if the name isn't taken yet. Is this sufficient for you, or do you need additional features?

**Comment by nhamilton1980** [comment]
Yes that would be fine.

Sent from my iPhone

On 10 May 2018, at 1:55 pm, Claus Wilke <notifications@github.com<mailto:notifications@github.com>> wrote:


Nicholas,

I wanted to make sure the base set of theme elements couldn’t get messed around with, whist still providing the ability for users to add new elements.

That would be the case with my proposed approach, since theme elements can be added but only if the name isn't taken yet. Is this sufficient for you, or do you need additional features?

**Comment by clauswilke** [comment]
I think a solution along those lines can be found. However, unfortunately I think it's too late for 2.3.0. I think a reasonable goal would be to try to add the extension functionality ggtern needs into the next version after 2.3.0, so that bug reports such as https://github.com/nicholasehamilton/ggtern/issues/16 and https://github.com/wilkelab/cowplot/issues/88 can be closed.

**Comment by nhamilton1980** [comment]
Fantastic. This will be extremely beneficial to me.

**Comment by clauswilke** [comment]
See also #2649 for a different problem that requires a similar technical fix: a currently hard-coded list needs to become user-configurable.

**Comment by clauswilke** [comment]
@hadley I'm happy to take this one on. One question: We'll need an environment to store the element tree. We already have an environment to store the current theme: https://github.com/tidyverse/ggplot2/blob/3d022edf35a580e875213dacafe5ced00ef6b884/R/theme-current.R#L3-L4
We'll also need an environment to address issue #2649. Do you want all these environments to be separate with their own names, or would it make sense to consolidate and have one environment (e.g. `ggplot_global` or `ggplot_env`) in which we store all these global settings. My own preference would be to consolidate.

**Comment by clauswilke** [comment]
@hadley I tried to moved the element tree into the theme itself, as you suggested [here.](https://github.com/tidyverse/ggplot2/pull/2741#pullrequestreview-135245264) However, I ran into an issue that I can't resolve without making things rather ugly: How does the `theme()` function know about the element tree it should validate against?

Specifically, consider the following example. Let's say I have defined a theme `theme_custom()` that defines an element tree with a nonstandard element `element_box()`. Now I want to modify that theme by changing the color of a box:
``` r
theme_custom() + theme(some.box = element_box(color = "red)) 
```
I don't see how the `theme()` call in this example can have access to the element tree defined in `theme_custom()`. The whole themeing system is predicated on the idea that we can generate incomplete themes and then add them together via `+` or `%+replace%`.

We could let `theme()` take an argument providing the element tree or the theme to be modified, but that seems rather inelegant and cumbersome to the end user.

**Comment by hadley** [comment]
Hmmmm good point. 

Could we move the inheritance into the elements? i.e. every `element_()` would gain an `inherits` argument? That would make creating a new theme considerably more complicated, but would make inheritance much simpler.

**Comment by nhamilton1980** [comment]
Gentlemen, 

Thankyou very much for considering and working on this. 

Could the element tree be a stored at the plot level? Which would enable something like this:

```
ggplot() + 
   theme_add_element(new_axisA = .el_def("element_line", "axis.line", description="Axis 1"),
                                      new_axisB = .el_def("element_line", "axis.line", description="Axis 2")) +
   theme_custom() +
   theme(new_axisA = element_line(size=2)
``` 

Each plot would start with the default ggplot2 element tree.

It is up to the plot (or package) creator to define their new elements each time ggplot2 (or their dependent package) is used.

**Comment by clauswilke** [comment]
@nhamilton1980 I think your proposal would suffer from the same problem as making the element tree part of the theme: The blank theme function `theme()` wouldn't know about what has been defined at the plot level. I'll see if Hadley's suggestion about defining inheritance in the elements themselves is viable.

**Comment by nhamilton1980** [comment]
@clauswilke sorry, but wouldn't it be handled inside the `add_ggplot(...)` function found inside `plot-construction.r`? In which case the `theme()` function doesn't need to know what has or hasn't been added previously.

**Comment by clauswilke** [comment]
@nhamilton1980 No, themes can be added to each other, without having a ggplot object:

``` r
> theme(text = element_text(size = 10)) + theme(text = element_text(colour = "black"))
List of 1
 $ text:List of 11
  ..$ family       : NULL
  ..$ face         : NULL
  ..$ colour       : chr "black"
  ..$ size         : num 10
  ..$ hjust        : NULL
  ..$ vjust        : NULL
  ..$ angle        : NULL
  ..$ lineheight   : NULL
  ..$ margin       : NULL
  ..$ debug        : NULL
  ..$ inherit.blank: logi FALSE
  ..- attr(*, "class")= chr [1:2] "element_text" "element"
 - attr(*, "class")= chr [1:2] "theme" "gg"
 - attr(*, "complete")= logi FALSE
 - attr(*, "validate")= logi TRUE
```

**Comment by nhamilton1980** [comment]
@clauswilke I see. Good point.

**Comment by clauswilke** [comment]
@hadley I think adding inheritance info to each element will create a huge amount of trouble for existing 3rd-party theme code. I have an alternative idea, going back to keeping the inheritance info in the theme itself: What about verifying the theme only right before plot construction, when all parts of the theme are available? This means I'd be able to construct an inconsistent theme using just `theme()` functions, but once I tried to use that inconsistent theme in a plot I'd get an error.

**Comment by clauswilke** [comment]
@nhamilton1980 This issue is now addressed. See [here](https://github.com/tidyverse/ggplot2/pull/2784#issuecomment-545268881) for an example of how you can now define new theme elements and add them to the default theme. This should simplify the ggtern implementation a lot.

**Comment by clauswilke** [comment]
I'm currently substantially revising how new theme elements can be defined, via PR #3678. Will post an example here once that code is merged.

**Comment by clauswilke** [comment]
As I said in my previous comment, I made one more change to the API for creating new theme elements. It is now explained in the documentation to the function `register_theme_elements()`.

From the examples section of the documentation to that function:

``` r
library(ggplot2)

# define a new coord that includes a panel annotation
coord_annotate <- function(label = "panel annotation") {
  ggproto(NULL, CoordCartesian,
          limits = list(x = NULL, y = NULL),
          expand = TRUE,
          default = FALSE,
          clip = "on",
          render_fg = function(panel_params, theme) {
            element_render(theme, "panel.annotation", label = label)
          }
  )
}

# register a new theme element `panel.annotation`
register_theme_elements(
  panel.annotation = element_text(color = "blue", hjust = 0.95, vjust = 0.05),
  element_tree = list(panel.annotation = el_def("element_text", "text"))
)

df <- data.frame(x = 1:3, y = 1:3)
ggplot(df, aes(x, y)) +
  geom_point() +
  coord_annotate("annotation in blue")
```

![](https://i.imgur.com/LgckVog.png)

``` r

# revert to original ggplot2 settings
reset_theme_settings()
```

<sup>Created on 2020-01-03 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by hadley** [comment]
@clauswilke this made me realise that we should probably recommend that extension authors prefix any new theme settings with the name of their package in order to avoid clashes across packages.

**Comment by clauswilke** [comment]
Just so I understand exactly what you're suggesting: In the above example, if the panel annotation was part of package **ggxyz**, would you suggest to name the theme element `ggxyz.panel.annotation`?

**Comment by hadley** [comment]
Yes

**Comment by clauswilke** [comment]
Final demonstration of the new API, with recommended naming scheme for package developers.

``` r
library(ggplot2)

# Let's assume a package `ggxyz` wants to provide an easy way to add annotations to
# plot panels. To do so, it registers a new theme element `ggxyz.panel.annotation`
register_theme_elements(
  ggxyz.panel.annotation = element_text(color = "blue", hjust = 0.95, vjust = 0.05),
  element_tree = list(ggxyz.panel.annotation = el_def("element_text", "text"))
)

# Now the package can define a new coord that includes a panel annotation
coord_annotate <- function(label = "panel annotation") {
  ggproto(NULL, CoordCartesian,
          limits = list(x = NULL, y = NULL),
          expand = TRUE,
          default = FALSE,
          clip = "on",
          render_fg = function(panel_params, theme) {
            element_render(theme, "ggxyz.panel.annotation", label = label)
          }
  )
}

# Example plot with this new coord
df <- data.frame(x = 1:3, y = 1:3)
ggplot(df, aes(x, y)) +
  geom_point() +
  coord_annotate("annotation in blue")
```

![](https://i.imgur.com/W2psLju.png)

``` r

# Revert to the original ggplot2 settings
reset_theme_settings()
```

<sup>Created on 2020-01-03 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by nhamilton1980** [comment]
@clauswilke @hadley Thankyou both so much for this, I will integrate into the next ggtern release.

**Comment by clauswilke** [comment]
@nhamilton1980 As you prepare the next release of ggtern, please keep an eye out for other core components of ggplot2 that you have to duplicate or overwrite to make things work. Maybe we can address those in future releases of ggplot2. The goal should be that ggtern works entirely with the exported ggplot2 API, otherwise there'll always be headaches.

(A recent example: This bug is caused by a change to the internal `Layer` object in ggplot2:
https://bitbucket.org/nicholasehamilton/ggtern/issues/9/stat_sf-requires-the-following-missing )

**Comment by nhamilton1980** [comment]
I can think of one immediately.

In the plot construction routines, I think there should be hooks so that the layer can be rendered a) prior and b) after any coordinate transformations.

Many people have asked me to make ggrepel available, but it is difficult because that particular layer works almost exclusively in the cartesian space. I could make it work if I could somehow force it to operate on the data AFTER the simplex transformations have been performed.

**Comment by nhamilton1980** [comment]
I have mentioned before (I think leading up to my publication in JSS), that the required aesthetics / coordinates are not exclusively a function of the layer, but a layer in combination with the coordinate system. For example, A point in 1D requires x, in 2D requires x,y, in 3D requres x,y,z, and no I am not suggesting that ggplot2 should introduce 3d plotting, I am simply demonstrating that the required coordinates are a function of the layer operating in the specific coordinate system.

**Comment by clauswilke** [comment]
Please open separate issues for each of these items.

The issue of the relationship between position aesthetics and coords also recently came up in the context of geospatial data, see here: https://github.com/tidyverse/ggplot2/pull/3659#issuecomment-562964986. It's definitely something we need to look into further.
