### ISSUE TITLE
Relative positioning of `annotate` -- extend the documentation

### ISSUE THREAD

**Issue by Demetrio92** [tidyverse/ggplot2#2547]
I think the documentation of `ggplot2::annotate` should be extended with explanation of how to use `hjust` and `vjust` to position the output **relatively** to the plot boundaries.
At least one example should be added as well. 

-----
Background:

In the usual scenario where I use `ggplot2::annotate` I do not want to position the text at the exact XY location. I rather care about something like "top-right-corner". I strongly believe this is the case for most users. 
The documentation of `ggplot2::annotate` however is very much focused on the XY positioning, including a bunch of examples. 

According to [this answer on SO](https://stackoverflow.com/a/27777562/3494126) it's actually quite easy to position the text relatively to the plot box. 
The usage should also be obvious to an advanced ggplot user. However, I still think it belongs into the documentation. I am not sure how exactly `hjust` and `vjust` work here, so I cannot provide examples myself.

**Comment by hadley** [comment]
Those are both properties of `geom_text()`

I don't think it's possible to describe how to do a large set of annotations in the documentation for `annotate()`. A vignette would be more suitable, but I am unlikely to have time to write it.

**Comment by Demetrio92** [comment]
@hadley right not the docstring to the function has

```Rmd
#' @inheritParams layer
```
in it, which in my freshly github-installed version of ggplot2 results in: 
```Rmd
...     Other arguments passed on to layer(). These are often aesthetics, used to set an aesthetic to a fixed value, like color = "red" or size = 3. They may also be parameters to the paired geom/stat.
```

Which is probably correct, but I'd prefer if it pointed out to `geom_text` which in great details explains how alignment works. 
Do you think it would be a good idea to swap `layer` for `geom_text`?, i.e.
```Rmd
#' @inheritParams geom_text
```

Otherwise, I would add it just as a text into `@details`. In any case, expect a PR :)

**Comment by hadley** [comment]
You can use `annotate()` with any geom, not just text.

**Comment by Demetrio92** [comment]
I see.
