### ISSUE TITLE
qplot() ignores xlab and ylab arguments

### ISSUE THREAD

**Issue by gwarnes-mdsol** [tidyverse/ggplot2#2551]
For example:
```r
x <- rnorm(100)
y <- rnorm(100, mean=x, sd=1/4)

qplot(x, y, xlab="x label", ylab="y label")
```
yields:
![image](https://user-images.githubusercontent.com/22243578/39480231-910a9a3a-4d35-11e8-904d-72dc86b810f6.png)
instead of:
![image](https://user-images.githubusercontent.com/22243578/39480273-b41b50fa-4d35-11e8-9e72-86e5083347d1.png)

A pair of minor changes to https://github.com/tidyverse/ggplot2/blob/master/R/quick-plot.r will resolve this issue.  At [line 86](https://github.com/tidyverse/ggplot2/blob/2495ba23ee34ecd57330a3e8af1f9d089a5f3374/R/quick-plot.r#L86)
```r
xlab <- rlang::quo_name(exprs$x)
```
to 
```r
if(missing(xlab)) xlab <- rlang::quo_name(exprs$x)
```
and at [lines 88-91](https://github.com/tidyverse/ggplot2/blob/2495ba23ee34ecd57330a3e8af1f9d089a5f3374/R/quick-plot.r#L86-L91):
```r
if (rlang::quo_is_null(exprs$y)) {
        ylab <- "NULL"
    }
    else {
        ylab <- rlang::quo_name(exprs$y)
    }
```
to
```
if(missing(ylab)) {
  if (rlang::quo_is_null(exprs$y)) {
          ylab <- "NULL"
      }
      else {
          ylab <- rlang::quo_name(exprs$y)
      }
}
```

**Comment by hadley** [comment]
Would you like to do a PR?

**Comment by gwarnes-mdsol** [comment]
Normally, I would be glad to do so, but I'm deep in another project right
now.

On Tue, May 1, 2018 at 11:59 AM Hadley Wickham <notifications@github.com>
wrote:

> Would you like to do a PR?
>
> —
> You are receiving this because you authored the thread.
>
>
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_tidyverse_ggplot2_issues_2551-23issuecomment-2D385708294&d=DwMCaQ&c=fi2D4-9xMzmjyjREwHYlAw&r=PUo6rYTmGeWkBJepZc1UHw629PctwMWQF8I3RzhQlL8&m=Svel5P7Nst9E2Ol9J1lQaLJl5NiF29mQ--V4sP8S-GI&s=RNTa-mSCz4youe5kB_Y5kuUPcD8pEmRTcAf07ICiI5g&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AVNo-2DiuoNSf7YydMAvScKqE5FZd-5FWRlUks5tuIZogaJpZM4TuHsm&d=DwMCaQ&c=fi2D4-9xMzmjyjREwHYlAw&r=PUo6rYTmGeWkBJepZc1UHw629PctwMWQF8I3RzhQlL8&m=Svel5P7Nst9E2Ol9J1lQaLJl5NiF29mQ--V4sP8S-GI&s=PQXNSnVt37plc8v2Wc-0uHVmSpMqnflaX5js4WoYqcM&e=>
> .
>
-- 
If this message is urgent please contact me via Hangouts or by phone:
585-678-6661.
