### ISSUE TITLE
Review documentation of most visited webpages

### ISSUE THREAD

**Issue by hadley** [tidyverse/ggplot2#2553]
* [x] Find out top 20 pages from google analytics

**Comment by dpseidel** [comment]
Top 20 most visited ggplot2 pages as of 6/11/18.

- [ ] [Create Elegant Data Visualisations Using the Grammar of Graphics • ggplot2](ggplot2.tidyverse.org)
- [ ] [Function reference • ggplot2](http://ggplot2.tidyverse.org/reference/index.html)
- [ ] [Bar charts — geom_bar • ggplot](http://ggplot2.tidyverse.org/reference/geom_bar.html)
- [ ] [Modify axis, legend, and plot labels — labs • ggplot2](http://ggplot2.tidyverse.org/reference/labs.html)
- [ ] [Points — geom_point • ggplot2](http://ggplot2.tidyverse.org/reference/geom_point.html)
- [ ] [Text — geom_label • ggplot2](http://ggplot2.tidyverse.org/reference/geom_text.html)
- [ ] [Modify components of a theme — theme • ggplot2](http://ggplot2.tidyverse.org/reference/theme.html)
- [ ] [Position scales for continuous data (x & y) — scale_continuous • ggplot2](http://ggplot2.tidyverse.org/reference/scale_continuous.html)
- [ ] [Smoothed conditional means — geom_smooth • ggplot2](http://ggplot2.tidyverse.org/reference/geom_smooth.html)
- [ ] [Lay out panels in a grid — facet_grid • ggplot2](http://ggplot2.tidyverse.org/reference/facet_grid.html)
- [ ] [Histograms and frequency polygons — geom_freqpoly • ggplot2](http://ggplot2.tidyverse.org/reference/geom_histogram.html)
- [ ] [Gradient colour scales — scale_colour_gradient • ggplot2](http://ggplot2.tidyverse.org/reference/scale_gradient.html)
- [ ] [Legend guide — guide_legend • ggplot2](http://ggplot2.tidyverse.org/reference/guide_legend.html)
- [ ] [A box and whiskers plot (in the style of Tukey) — geom_boxplot • ggplot2](http://ggplot2.tidyverse.org/reference/geom_boxplot.html)
- [ ] [Reference lines: horizontal, vertical, and diagonal — geom_abline • ggplot2](http://ggplot2.tidyverse.org/reference/geom_abline.html)
- [ ] [Save a ggplot (or other grid object) with sensible defaults — ggsave • ggplot2](http://ggplot2.tidyverse.org/reference/ggsave.html)
- [ ] [Create your own discrete scale — scale_manual • ggplot2](http://ggplot2.tidyverse.org/reference/scale_manual.html)
- [ ] [Set scale limits — lims • ggplot2](http://ggplot2.tidyverse.org/reference/lims.html)
- [ ] [Create an annotation layer — annotate • ggplot2](http://ggplot2.tidyverse.org/reference/annotate.html)
- [ ] [Sequential, diverging and qualitative colour scales from colorbrewer.org — scale_colour_brewer • ggplot2](http://ggplot2.tidyverse.org/reference/scale_brewer.html)

**Comment by dpseidel** [comment]
Definitely need documentation improvements for at least:

- [ ] themes
- [ ] gradient colour scales
- [ ] manual scales
- [ ] legends
- [ ] limits 

These will be done in separate PRs.
