### ISSUE TITLE
Default values for alpha

### ISSUE THREAD

**Issue by thomasp85** [tidyverse/ggplot2#2558]
Working on gganimate I came upon a little problem. For GeomPolygon and related geoms the alpha value is set to `NA` rather than 1, which is in practice the same. This results in bad transitions as transitioning into NA is ill-defined.

I could hack around this in tweenr/gganimate, but wondered whether you would be interested in a fix here instead.

**Comment by hadley** [comment]
Seems reasonable to fix here

**Comment by thomasp85** [comment]
Is the visual tests up and running now? I think this is one of the places where they will be nice to have even though I don't expect any problems `scales::alpha()` treats `NA` as 1

**Comment by hadley** [comment]
Yup visual tests are up and running.
