### ISSUE TITLE
font size in legend title theme is not inherited

### ISSUE THREAD

**Issue by clauswilke** [tidyverse/ggplot2#2576]
When setting the title theme via `guide_legend()` the fontsize is not inherited. This causes weird spacing issues because the fontsize is used for spacing calculations if `legend.spacing.x` and `legend.spacing.y` are not set (the default). Reprex:

``` r
library(ggplot2)
df <- data.frame(x = c(1, 2, 3))
ggplot(df, aes(x, x, colour = x)) + geom_point() +
  scale_color_continuous(guide = guide_legend())
```

![](https://i.imgur.com/fgOBWUy.png)

``` r

ggplot(df, aes(x, x, colour = x)) + geom_point() +
  scale_color_continuous(guide = guide_legend(title.theme = element_text()))
```

![](https://i.imgur.com/4uF5bER.png)

The fix is to replace this line:
```{r}
title_fontsize <- title.theme$size
```
with this line:
```{r}
title_fontsize <- title.theme$size %||% calc_element("legend.title", theme)$size
```
here: https://github.com/tidyverse/ggplot2/blob/4463da6abc9b8ff7a2451686b9685de36933b358/R/guide-colorbar.r#L345
and here: https://github.com/tidyverse/ggplot2/blob/4463da6abc9b8ff7a2451686b9685de36933b358/R/guide-legend.r#L348

The subsequent check for `NULL` could be replaced by another `%||%` statement in the same line.

**Comment by hadley** [comment]
Is this a regression?

**Comment by clauswilke** [comment]
I think so. Version 2.2.1 used a hard-coded length as default unit for the spacing, and I thought it would make more sense to tie the default spacing to the font size. But that means I need to do everything I can to retrieve a meaningful font size. The fix is trivial, and I'll do it while figuring out the rotated text issue.

**Comment by hadley** [comment]
Ok, thanks!
