### ISSUE TITLE
Simplify the usage of fortify() in ggplot()

### ISSUE THREAD

**Issue by yutannihilation** [tidyverse/ggplot2#2578]
`ggplot.grouped_df()` was implemented in response to #2351. I feet, this is a kind of "fortifying" and at first thought implementing this was enough

```r
fortify.grouped_df <- function(data, ...) {
  data$.group <- dplyr::group_indices(data)
  data
}
```

so that the `ggplot.default()` calls this:

https://github.com/tidyverse/ggplot2/blob/4463da6abc9b8ff7a2451686b9685de36933b358/R/plot.r#L80

But, my guess was wrong. Since a `grouped_df` is also a `data.frame`, `ggplot.data.frame()` is actually dispatched, where `fortify()` won't happen.

I wonder if it is possible to remove `ggplot.data.frame()` and change `ggplot.default()` to bellow to let `fortify()` always happen:

``` r
ggplot.default <- function(...) {
  data <- fortify(data)

  # (the current implementation of ggplot.data.frame comes here)
}
```

IMHO, it is a bit beneficial to implement the "fortifying" process as a method of `fortify()` since then the process is more transparent to the users. If this looks ok, I will try to make a PR.

**Comment by hadley** [comment]
@yutannihilation any chance you'd have time to do a PR on this today? (if not, no problem, I'll do it later)

**Comment by yutannihilation** [comment]
@hadley Thanks, I will!
