### ISSUE TITLE
Separate aesthetic mappings for geoms and for stats

### ISSUE THREAD

**Issue by clauswilke** [tidyverse/ggplot2#2579]
This issue was first brought up in #2570 but it's really a separate issue: In the current ggplot2, mappings for geoms and stats are muddled together. This works great 90% of the time and causes big frustrations the other 10%. The most obvious case is that we need separate stats in a horizontal and vertical context. They are identical except with `x` and `y` flipped. For example, this works:
```r
ggplot(iris, aes(x = Sepal.Length, y = calc(density), color = Species)) + 
  geom_line(stat="density")
```
but this does not:
```r
ggplot(iris, aes(y = Sepal.Length, x = calc(density), color = Species)) +
  geom_line(stat="density")
```
Not very intuitive to the user, in my opinion.

A possible future extension could be to have the option of explicitly naming mappings only for the geom and only for the stat, like so:
```r
ggplot(iris,
       mapping_stat = aes(x = Sepal.Length),
       mapping_geom = aes(y = Sepal.Length, x = calc(density), color = Species)) + 
  geom_line(stat="density")
```
For backwards compatibility and ease of use, the default `mapping` argument could make an educated guess of how the mappings should be split up between the two.

The devils in the details, though, and I'm not sure whether the syntax should be as above, or rather:
```r
ggplot(iris,
       mapping_stat = aes(x = Sepal.Length),
       mapping_geom = aes(y = Sepal.Length, x = density, color = Species)) + 
  geom_line(stat="density")
```
or
```r
ggplot(iris,
       mapping_stat = aes(x = Sepal.Length),
       mapping_geom = aes(y = x, x = density, color = Species)) + 
  geom_line(stat="density")
```
 (I.e., mapping in the geom works directly from the column names provided by the stat.)

Finally, this raises the question whether it should be possible to chain stats together before handing the results to the geom. E.g., first run `stat_density()` to calculate density curves, then chain it to a stat that finds the maximum, and then feed into `geom_point()` to draw a point at the top of the density curve. I think this would be very useful, similar to the pipe operator in dplyr, but I'm not sure what a good user interface would be that gracefully extends the current ggplot2 syntax.

**Comment by hadley** [comment]
I think this is just too big to justify — I agree that it's a good idea, but implementing now would be a huge amount of work for a (relatively) small gain.
