### ISSUE TITLE
the comman ggplot under ggplot2 package doesn#t work any more

### ISSUE THREAD

**Issue by stephankraut** [tidyverse/ggplot2#2581]
This is my error message:
library(ggplot2)

In addition: Warning message:
Paket ‘ggplot2’ wurde unter R Version 3.4.4 erstellt 
> colours = c(Female = "Red", Male = "Green")
> bar <-ggplot(teachingMethodData)
Error in ggplot(teachingMethodData) : **# could not find function **"ggplot"****
Could anybody help?

**Comment by batpigandme** [comment]
This sort of question is a better fit for https://community.rstudio.com. Do you mind asking it over there? (You might want to read https://www.tidyverse.org/help/ first to maximise your chances of getting a good answer.)
