### ISSUE TITLE
feature request: remove layers using -

### ISSUE THREAD

**Issue by vnijs** [tidyverse/ggplot2#2582]
@yonicd's idea in ggedit to remove layers from existing plots using - is quite convenient. Is this a feature that could be added to ggplot2 as well?

See [example](https://github.com/metrumresearchgroup/ggedit/issues/21#issuecomment-354387117) and [code](https://github.com/metrumresearchgroup/ggedit/commit/35b9bb58c40274fd06df989523a7ae9fa4a71a63)

**Comment by thomasp85** [comment]
Is there any reason why you can’t use the implementation provided in ggedit? 

In general I think there should be very strong reasons for porting functionality already available in extension packages into ggplot2

**Comment by batpigandme** [comment]
Since @hadley's been quite clear on this (e.g. https://community.rstudio.com/t/why-cant-ggplot2-use/4372/10), I'm going to close. If I've erred in the wrong direction, we can reopen.
