### ISSUE TITLE
Symbol Issue ggplot2

### ISSUE THREAD

**Issue by toouggy** [tidyverse/ggplot2#2583]
---

I am trying to generate a box plot and when I add different symbols everything works except in some of the groups I get a symbol duplication with a solid symbol rather than the assigned symbol to most of the data.  The output PDF files are attached.  I can also submit the R and csv files if needed.

```r
##########################################################################################
##   Purpose: Reproduce Potential Bug in Geom_Boxplot   ##################################
##   Date:  May 13, 2018   ###############################################################
##########################################################################################

#  Loading libraries for analysis

library(ggplot2)
library(latticeExtra)
library(reprex)
suppressMessages(library(tidyverse))

#  Getting information about environment.
sessionInfo()

#  Setting Theme for ggplot package
theme_set(theme_bw(16) + theme(panel.grid.major = element_blank(),
                               panel.grid.minor = element_blank(),
                               axis.line.x = element_line(colour = "black"),
                               axis.line.y = element_line(colour = "black"),
                               panel.border = element_blank(),
                               legend.background = element_rect(fill = "transparent"),
                               legend.key = element_blank(),
                               plot.title = element_text(hjust = 0.5),
                               plot.subtitle = element_text(hjust = 0.5)))

#  Setting Options for data.table package
options(datatable.print.nrows = Inf, max.print = 999999, dplyr.print_max = Inf)

#  Fixing MASS and dplyr incompatibility
select <- dplyr::select

##########################################################################################
##   READING DATA INTO R   ###############################################################
##########################################################################################

#  Read original data
d <- read.csv("data.csv", stringsAsFactors = FALSE, na.strings=c("", ".", " ", "0", "NA"))

#  Selecting the data

d.id <- d %>%
    mutate(Group.Gender = factor(paste(group, sex, sep = "."),
                                 levels = c("Control.F", "AREDS_1_2.F", "AREDS_3.F",
                                            "GA.F", "iwAMD.F", "wAMD.F",
                                            "Control.M", "AREDS_1_2.M", "AREDS_3.M",
                                            "GA.M", "iwAMD.M", "wAMD.M"))) %>%
    select(group, gender = sex, Group.Gender, age) %>%
    mutate(group = factor(group, levels = c("Control", "AREDS_1_2", "AREDS_3", "GA",
                                            "iwAMD", "wAMD")))

##########################################################################################
##   BoxPlots Age by group and group gender   ############################################
##########################################################################################

#  By Group
(Age_Boxplot <- ggplot(d.id, aes(group, age, color = group)) +
     geom_boxplot(fill = "lightyellow", na.rm = TRUE) +
     geom_violin(fill = "lightblue", draw_quantiles = NULL, trim = FALSE,
                 alpha = 0.1) +
     geom_point(aes(shape = group), position = position_jitter(width = 0.2), size = 2,
                na.rm = TRUE) +
     theme(legend.justification = c(0, 1), legend.position = "none",
           legend.background = element_rect(fill = "transparent")) +
     labs(y = expression(Age~(years)),
          x = "Group",
          title = expression(Age~(years))))

#  Issue:  In group GA, iwAMD and wAMD there are circles and repeated values with the
#          correct symbol

#  By Group and Gender
(Age_Boxplot1 <- ggplot(d.id, aes(group, age, shape = group)) +
        geom_boxplot(fill = "lightyellow", na.rm = TRUE) + facet_grid(. ~ gender) +
        geom_violin(fill = "lightblue", draw_quantiles = NULL, trim = FALSE,
                    alpha = 0.1) +
        geom_point(position = position_jitter(width = 0.1),
                   aes(color = group), size = 2, na.rm = TRUE) +
        theme(axis.text.x = element_text(angle = 20, hjust = 1, vjust = 1, size = 10),
              legend.justification = c(0, 1), legend.position = "none",
              legend.background = element_rect(fill = "transparent")) +
        labs(y = expression(Age~(years)),
             x = "Group",
             title = expression(Age~(years))))

#  Issue:  In group iwAMD (F and M) and wAMD (only M) there are circles and repeated
#          values with the correct symbol

pdf("boxplots_age.pdf", width = 7.5, height = 10)

Age_Boxplot
Age_Boxplot1

dev.off()

```
[BoxPlot_Issue.pdf](https://github.com/tidyverse/ggplot2/files/1999269/BoxPlot_Issue.pdf)
[boxplots_age.pdf](https://github.com/tidyverse/ggplot2/files/1999270/boxplots_age.pdf)

**Comment by thomasp85** [comment]
You’ll probably need to set `useDingbats = TRUE` in the pdf device

**Comment by batpigandme** [comment]
In addition to trying @thomasp85's suggestion, it would be best if you could provide us with a self-contained [reprex](http://reprex.tidyverse.org/) (short for minimal **repr**oducible **ex**ample).

If you've never heard of a reprex before, you might want to start by reading the tidyverse.org [help page](https://www.tidyverse.org/help/). The [reprex dos and don'ts](http://reprex.tidyverse.org/articles/reprex-dos-and-donts.html) are also useful.

Right now the best way to install reprex is:

```r
# install.packages("devtools")
devtools::install_github("tidyverse/reprex")
```

**Comment by toouggy** [comment]
I run a reprex and the output is below:

BoxPlot_Issue_Reprex_20180515.R
FJL

Tue May 15 10:01:14 2018

require(ggplot2)
## Loading required package: ggplot2
require(tidyverse)
## Loading required package: tidyverse
## ── Attaching packages ──────────────────────────────────────────────────────── tidyverse 1.2.1 ──
## ✔ tibble  1.4.2     ✔ purrr   0.2.4
## ✔ tidyr   0.8.0     ✔ dplyr   0.7.4
## ✔ readr   1.1.1     ✔ stringr 1.3.1
## ✔ tibble  1.4.2     ✔ forcats 0.3.0
## ── Conflicts ─────────────────────────────────────────────────────────── tidyverse_conflicts() ──
## ✖ dplyr::filter() masks stats::filter()
## ✖ dplyr::lag()    masks stats::lag()
age <- as.numeric(c(61, 61, 62, 64, 64, 64, 65, 66, 67, 67, 67, 67, 68, 69, 70, 70, 71,
                     72, 73, 73, 76, 77, 77, 78, 79, 79, 80, 81, 81, 82, 84, 86, 89, 60,
                     65, 65, 67, 68, 70, 73, 73, 76, 76, 78, 82, 89, 67, 75, 87, 87, 64,
                     73, 73, 74, 75, 75, 75, 78, 78, 78, 79, 79, 79, 80, 81, 82, 82, 85,
                     85, 85, 86, 86, 86, 87, 56, 70, 72, 76, 79, 79, 80, 82, 84, 85, 85,
                     85, 87, 87, 87, 89, 89, 63, 63, 71, 72, 72, 74, 74, 75, 76, 77, 77,
                     77, 77, 78, 78, 78, 78, 78, 79, 79, 79, 80, 80, 81, 81, 81, 81, 82,
                     83, 83, 83, 83, 84, 84, 85, 86, 86, 86, 87, 88, 88, 88, 89, 89, 89,
                     91, 93, 67, 72, 75, 76, 76, 77, 77, 77, 78, 79, 79, 80, 80, 80, 81,
                     81, 81, 81, 81, 81, 81, 82, 82, 83, 83, 83, 84, 84, 85, 85, 85, 86,
                     87, 88, 90, 91))

sex <- c("F", "F", "F", "M", "F", "M", "F", "M", "F", "F", "F", "M", "F", "M", "F", "F",
          "F", "F", "F", "F", "F", "M", "F", "M", "F", "M", "M", "M", "F", "F", "M", "M",
          "M", "M", "F", "F", "F", "F",  "F", "M", "F", "F", "M", "F", "F", "M", "F", "F",
          "F", "F", "F",  "F", "M", "F", "F", "F", "F", "F", "F", "F", "F", "F", "M", "F",
          "F", "F", "F", "M", "F", "F", "F", "F", "F", "F", "M", "F", "M",  "F", "F", "F",
          "M", "F", "F", "F", "F", "M", "F", "F", "F", "M",  "F", "F", "F", "F", "F", "F",
          "F", "F", "M", "F", "F", "F", "F",  "F", "M", "M", "F", "F", "F", "F", "F", "F",
          "M", "M", "F", "F",  "F", "F", "F", "F", "F", "F", "F", "M", "F", "F", "F", "F",
          "F", "F", "F", "F", "M", "M", "M", "F", "F", "F", "F", "M", "F", "F",  "M", "M",
          "F", "F", "F", "F", "F", "M", "M", "M", "M", "M", "F",  "F", "F", "M", "M", "F",
          "F", "F", "F", "F", "M", "M", "M", "M", "M", "F", "F", "F", "F", "F")

group <- c("Control", "Control", "Control", "Control", "Control", "Control",
            "Control", "Control", "Control", "Control", "Control", "Control",
            "Control", "Control", "Control", "Control", "Control", "Control",
            "Control", "Control", "Control", "Control", "Control", "Control",
            "Control", "Control", "Control", "Control", "Control", "Control",
            "Control", "Control", "Control", "AREDS_1_2", "AREDS_1_2", "AREDS_1_2",
            "AREDS_1_2", "AREDS_1_2", "AREDS_1_2", "AREDS_1_2", "AREDS_1_2",
            "AREDS_1_2", "AREDS_1_2", "AREDS_1_2", "AREDS_1_2", "AREDS_1_2",
            "AREDS_1_2", "AREDS_1_2", "AREDS_1_2", "AREDS_1_2", "AREDS_3",
            "AREDS_3", "AREDS_3", "AREDS_3", "AREDS_3", "AREDS_3", "AREDS_3",
            "AREDS_3", "AREDS_3", "AREDS_3", "AREDS_3", "AREDS_3", "AREDS_3",
            "AREDS_3", "AREDS_3", "AREDS_3", "AREDS_3", "AREDS_3", "AREDS_3",
            "AREDS_3", "AREDS_3", "AREDS_3", "AREDS_3", "AREDS_3", "GA",
            "GA", "GA", "GA", "GA", "GA", "GA", "GA", "GA", "GA", "GA", "GA",
            "GA", "GA", "GA", "GA", "GA", "wAMD", "wAMD", "wAMD", "wAMD",
            "wAMD", "wAMD", "wAMD", "wAMD", "wAMD", "wAMD", "wAMD", "wAMD",
            "wAMD", "wAMD", "wAMD", "wAMD", "wAMD", "wAMD", "wAMD", "wAMD",
            "wAMD", "wAMD", "wAMD", "wAMD", "wAMD", "wAMD", "wAMD", "wAMD",
            "wAMD", "wAMD", "wAMD", "wAMD", "wAMD", "wAMD", "wAMD", "wAMD",
            "wAMD", "wAMD", "wAMD", "wAMD", "wAMD", "wAMD", "wAMD", "wAMD",
            "wAMD", "wAMD", "wAMD", "iwAMD", "iwAMD", "iwAMD", "iwAMD", "iwAMD",
            "iwAMD", "iwAMD", "iwAMD", "iwAMD", "iwAMD", "iwAMD", "iwAMD",
            "iwAMD", "iwAMD", "iwAMD", "iwAMD", "iwAMD", "iwAMD", "iwAMD",
            "iwAMD", "iwAMD", "iwAMD", "iwAMD", "iwAMD", "iwAMD", "iwAMD",
            "iwAMD", "iwAMD", "iwAMD", "iwAMD", "iwAMD", "iwAMD", "iwAMD",
            "iwAMD", "iwAMD", "iwAMD")

d.id <- data.frame(group = group, gender = sex, age = age) %>%
    mutate(Group.Gender = factor(paste(group, gender, sep = "."),
                                 levels = c("Control.F", "AREDS_1_2.F", "AREDS_3.F",
                                            "GA.F", "iwAMD.F", "wAMD.F",
                                            "Control.M", "AREDS_1_2.M", "AREDS_3.M",
                                            "GA.M", "iwAMD.M", "wAMD.M")),
           group = factor(group, levels = c("Control", "AREDS_1_2", "AREDS_3", "GA",
                                            "iwAMD", "wAMD")))

(Age_Boxplot <- ggplot(d.id, aes(group, age, color = group)) +
        geom_boxplot(fill = "lightyellow", na.rm = TRUE) +
        geom_violin(fill = "lightblue", draw_quantiles = NULL, trim = FALSE,
                    alpha = 0.1) +
        geom_point(aes(shape = group), position = position_jitter(width = 0.2), size = 2,
                   na.rm = TRUE) +
        theme(legend.justification = c(0, 1), legend.position = "none",
              legend.background = element_rect(fill = "transparent")) +
        labs(y = expression(Age~(years)),
             x = "Group",
             title = expression(Age~(years))))


#  Issue:  In group GA, iwAMD and wAMD there are circles and repeated values with the
#          correct symbol

(Age_Boxplot1 <- ggplot(d.id, aes(group, age, shape = group)) +
        geom_boxplot(fill = "lightyellow", na.rm = TRUE) + facet_grid(. ~ gender) +
        geom_violin(fill = "lightblue", draw_quantiles = NULL, trim = FALSE,
                    alpha = 0.1) +
        geom_point(position = position_jitter(width = 0.1),
                   aes(color = group), size = 2, na.rm = TRUE) +
        theme(axis.text.x = element_text(angle = 20, hjust = 1, vjust = 1, size = 10),
              legend.justification = c(0, 1), legend.position = "none",
              legend.background = element_rect(fill = "transparent")) +
        labs(y = expression(Age~(years)),
             x = "Group",
             title = expression(Age~(years))))


#  Issue:  In group iwAMD (F and M) and wAMD (only M) there are circles and repeated
#          values with the correct symbol
[BoxPlot_Issue_Reprex_20180515.docx](https://github.com/tidyverse/ggplot2/files/2005969/BoxPlot_Issue_Reprex_20180515.docx)
[BoxPlot_Issue_Reprex_20180515.pdf](https://github.com/tidyverse/ggplot2/files/2005970/BoxPlot_Issue_Reprex_20180515.pdf)

**Comment by clauswilke** [comment]
The duplicated points are outliers generated by `geom_boxplot()`. This report highlights how important it is to generate a *minimal* reprex. There's so much going on in the original example that it's hard to find the root issue.

A minimal reprex follows, plus a possible workaround (`outlier.colour = "transparent"`), though I would argue the original code works as expected.

``` r
library(ggplot2)
set.seed(123)
ggplot(mpg, aes(factor(cyl), hwy)) + 
  geom_boxplot() +
  geom_jitter(aes(shape = factor(cyl)), height = 0, colour = "lightblue") +
  theme_bw()
```

![](https://i.imgur.com/Cy0iKgh.png)

``` r

set.seed(123)
ggplot(mpg, aes(factor(cyl), hwy)) + 
  geom_boxplot(outlier.colour = "transparent") +
  geom_jitter(aes(shape = factor(cyl)), height = 0, colour = "lightblue") +
  theme_bw()
```

![](https://i.imgur.com/Ofsbc2Y.png)

Created on 2018-05-22 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).
