### ISSUE TITLE
Identify revdep issues

### ISSUE THREAD

**Issue by hadley** [tidyverse/ggplot2#2584]
There are 229 new failures, listed below. This is too many, and suggests that we've accidentally broken something important (hopefully we've only broken 1 or 2 things that are used heavily not a bunch of small things). The first step is to find the common themes in the failures.

@tidyverse/ggplot2 can you please let me know if you have time this week to read some fraction of the failure reports (in <revdep/README.md>) and report back? I'll split the packages up over everyone  who's willing to help.

Googlesheet of failures at https://docs.google.com/spreadsheets/d/1UZIFwt3j3XjnRGOMNJZvpal_CAj7Hz8aNXJt41m3JjM/edit#gid=0 — when you start exploring a failure, first put your name in the "who" column to make sure multiple people don't try understanding the same package at the same time.

**Comment by batpigandme** [comment]
I can read. At the very least, I can do some winnowing down before more expert eyes are needed. 🙂

**Comment by thomasp85** [comment]
I can put in some time

**Comment by yutannihilation** [comment]
FWIW, my package (gghighlight) fails because it assumes an aes mapping consists of symbols, not quosures. (But, I'm OK because I plan to overhaul the implementation after the release of this ggplot2 2.3.0.)

**Comment by karawoo** [comment]
I can read some as well.

**Comment by thomasp85** [comment]
Maybe a google sheet where people can group issues into possible duplicates and others can begin tackling them...

**Comment by hadley** [comment]
Duh, yes, googlesheet is perfect

**Comment by hadley** [comment]
Googlesheet at https://docs.google.com/spreadsheets/d/1UZIFwt3j3XjnRGOMNJZvpal_CAj7Hz8aNXJt41m3JjM/edit#gid=0 — when you start exploring a failure, first put your name in the "who" column to make sure multiple people don't try understanding the same package at the same time. 

@batpigandme can you please work on marking the packages with the "dplyr-ggplot2 vars clash"?

**Comment by hadley** [comment]
@lionel- @batpigandme Now tracking potential fix ideas for vars clash at #2585

**Comment by hadley** [comment]
Another common problem: looks like we accidental broke geom look up in `qplot()`. So any issue with `could not find function "geom_text"` (or similarly) is likely to be #2586

**Comment by clauswilke** [comment]
I see several warnings about an openMP clash, e.g.: 
```
    > # Use image as plot background
    > p <- ggplot(iris, aes(x = Sepal.Length, fill = Species)) + geom_density(alpha = 0.7)
    > ggdraw() +
    +   draw_image("http://jeroen.github.io/images/tiger.svg") +
    +   draw_plot(p + theme(legend.box.background = element_rect(color = "white")))
    OMP: Error #15: Initializing libomp.dylib, but found libomp.dylib already initialized.
    OMP: Hint: This means that multiple copies of the OpenMP runtime have been linked into the program. That is dangerous, since it can degrade performance or cause incorrect results. The best thing to do is to ensure that only a single OpenMP runtime is linked into the process, e.g. by avoiding static linking of the OpenMP runtime in any library. As an unsafe, unsupported, undocumented workaround you can set the environment variable KMP_DUPLICATE_LIB_OK=TRUE to allow the program to continue to execute, but that may cause crashes or silently produce incorrect results. For more information, please see http://www.intel.com/software/products/support/.
```
This seems to happen with packages that work with images, and it may be a problem with the testing environment rather than indicating a real problem?

**Comment by hadley** [comment]
@clauswilke Yeah, I think it's safe to ignore those

**Comment by hadley** [comment]
Maybe we need a column "can ignore" or similar?

**Comment by batpigandme** [comment]
Seeing quite a few (38 based on just a simple raw count):
```
variables…have non standard format: "~foo".  Please rename the columns or make a new column.
```

**Comment by hadley** [comment]
@batpigandme Is it possible all those errors come downstream from GGally? Would you mind trying to reproduce one or two more and seeing if `make_ggmatrix_plot_obj()` is in the traceback?

**Comment by batpigandme** [comment]
On it.

**Comment by batpigandme** [comment]
Nailed it! 

At least 12 have `make_ggmatrix_plot_obj()` directly in their error reports https://raw.githubusercontent.com/tidyverse/ggplot2/master/revdep/problems.md
and then I found a few others in their vignettes and examples, and so far they've all traced to `make_ggmatrix_plot_obj()`. And, it looks like that's ~ the same thing when there are [`ggpairs()`](https://github.com/ggobi/ggally/blob/0dc3283acfbf84da8882575b04e3db90607183c0/R/ggpairs.R)-related failures, too.

**Comment by thomasp85** [comment]
There's a bunch of errors that happens because `eval_tidy` doesn't allow duplicate column names. I would argue that this is fair and it is up to the package developers to clean their data, so I won't open an issue here. I'll mark the relevant package in the sheet

**Comment by hadley** [comment]
@thomasp85 would you mind writing a paragraph for inclusion in the news?

**Comment by thomasp85** [comment]
Sure

**Comment by hadley** [comment]
@lionel- We also need a paragraph for the breaking changes section describing how the internal structure of `aes()` has changed.

**Comment by batpigandme** [comment]
Do we have an issue going for the `forecast::autolayer()` `ggplot2::autolayer()` namespace collision?

**Comment by karawoo** [comment]
I don't think so. There are also a number of `ggplot2::calc()`/`raster::calc()` issues.

**Comment by batpigandme** [comment]
There are also seven packages with `undefined columns selected` errors — is that due to a change in tidyselect?

**Comment by hadley** [comment]
`forecast::autolayer()` will be resolved by forecast developers since @mitchelloharawild requested it

How many `raster::calc()` conflicts are there? If there's a lot we might need to change `calc()` to something else.

Can someone give me a traceback for 2-3 `undefined columns selected` errors?

**Comment by batpigandme** [comment]
From plotROC
```
5. | stop("undefined columns selected")
-- | --
4. | `[.data.frame`(ggroc_p$data, , paste(ggroc_p$mapping$m))
-- | --
3. | ggroc_p$data[, paste(ggroc_p$mapping$m)]
-- | --
2. | export_interactive_roc(ggroc, ...)
-- | --
1. | plot_interactive_roc(basicplot)
```
Where `basicplot` is
``` r
library(plotROC)
#> Loading required package: ggplot2
set.seed(2529)
D.ex <- rbinom(200, size = 1, prob = .5)
M1 <- rnorm(200, mean = D.ex, sd = .65)
M2 <- rnorm(200, mean = D.ex, sd = 1.5)

test <- data.frame(D = D.ex, D.str = c("Healthy", "Ill")[D.ex + 1], 
                   M1 = M1, M2 = M2, stringsAsFactors = FALSE)
basicplot <- ggplot(test, aes(d = D, m = M1)) + geom_roc()
basicplot
```

![](https://i.imgur.com/BdYj8UX.png)

Created on 2018-05-15 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by karawoo** [comment]
I count 10 packages with `raster::calc()` conflicts: biomod2, bossMaps, diffeR, dtwSat, EcoGenetics, esmisc, paleofire, prism, rsMove, and zonator.

**Comment by hadley** [comment]
@batpigandme hmmmm, the first case is because we've changed the structure of `aes()`: `paste()`ing it (which was never a good idea), no longer yields useful strings. It's hard to see what the problem is in the second case. Maybe we need another issue to track this? Would you mind creating?

@karawoo hmmmmm, I'll ask on twitter

**Comment by hadley** [comment]
@thomasp85 can you please take a look at BloodCancerMultiOmics2017? It fails with `"plot.tag" is not a valid theme element name.`

**Comment by hadley** [comment]
Phew, looks like we've done them all! Thanks for all your help! If you spotted an issue that affected multiple (i.e. >3 packages) can you please make sure it's tracked in an issue?  

I think the next deadline is to try and get all issues fixed by Friday so we can kick off another round of revdeps this weekend.

**Comment by thomasp85** [comment]
ggmosaic fails due to changes made in the last version. Specifically it passes a list into x and y, which throws an error because x and y are checked for finite values during transformations.

I'm unsure whether why should even allow positional data to be lists..?

**Comment by thomasp85** [comment]
I'm clocking out and won't have as much time to go bug hunting in the coming days - feel free to tag me into issues that you think makes sense and I'll try to create the fixes, but I won't be filling in empty cells in the sheet for a couple of days

**Comment by batpigandme** [comment]
It appears that there are five cases of `theme$panel.ontop) { : argument is of length zero`.

**Comment by karawoo** [comment]
> It appears that there are five cases of theme$panel.ontop) { : argument is of length zero.

A lot of packages have defined themes with `complete = TRUE` that are not actually complete, and since the last release we've gotten stricter about making sure that complete themes don't ever inherit defaults. I think these packages will need to fix their themes.

**Comment by hadley** [comment]
I see quite a few `Error in min(c(x, xmin), na.rm = TRUE) :  invalid 'type' (list) of argument`. @karawoo would you have time to look into? I think it's likely to be related to something we did to scales, and will probably need some digging in the other package source.

**Comment by karawoo** [comment]
I will try to look into it (maybe not today)

**Comment by hadley** [comment]
@karawoo I'll create an issue to track.

Unfortunately I'm teaching a workshop Thursday and Friday, so I'm trying to front-load as much work as possible. I'll try and review PRs during the breaks.

**Comment by hadley** [comment]
Ok, I think the majority of packages are now actually triaged, and we can now concentrate on diagnosing and fixing the issues under https://github.com/tidyverse/ggplot2/milestone/16

**Comment by hadley** [comment]
I'm going to close this issue because I think we've successfully identified all the revdep issues for this round. All going well we'll have another much smaller round on Monday, and I'll open a new issue for that.
