### ISSUE TITLE
docs.ggplot2.org redirect?

### ISSUE THREAD

**Issue by oneilsh** [tidyverse/ggplot2#2587]
This may not be the best place to post this, but: It seems that http://ggplot2.org now redirects to http://ggplot2.tidyverse.org/

Could a similar redirect be added for http://docs.ggplot2.org? I think lots of things link there (and some are in print, and so harder to adjust links for).

**Comment by hadley** [comment]
Oops I think I somehow broke that redirect when adding ggplot2.org

**Comment by hadley** [comment]
And it's back 😄
