### ISSUE TITLE
unused argument (output)

### ISSUE THREAD

**Issue by hadley** [tidyverse/ggplot2#2597]
Revdeps fail for clustree, colorplaner, fiftystater, ggraph

**Comment by hadley** [comment]
@thomasp85 you noted that you fixed this for ggraph. Can you explain the root cause? (This might just need a paragraph in NEWS)

**Comment by clauswilke** [comment]
I think this is my fault, see this comment: https://github.com/tidyverse/ggplot2/pull/2555#issuecomment-386741688

It's already listed under the breaking changes:
> The function guide_train() now has an optional parameter aesthetic that allows you to override the aesthetic setting in the scale. This change will only affect code that implements custom guides (@clauswilke).

Should I expand that bullet point and explain how to do the fix?

**Comment by clauswilke** [comment]
How about:

The function `guide_train()` now defines an optional parameter `aesthetic` that can override the aesthetic setting in the scale. This change affects code that implements custom guides, which usually reimplement `guide_train()`. Code that doesn't have the required change will create an error in function `guide_train()` stating: `unused argument (output)`.

To make the required fix, you first have to add the appropriate argument to the function signature. For example, `guide_train.legend()` was changed from:
```
guide_train.legend <- function(guide, scale) {...}
```
to
```
guide_train.legend <- function(guide, scale, aesthetic = NULL) {...}
```

Then, inside the function, wherever you may have written `scale$aesthetics[1]`, you should write `aesthetic %||% scale$aesthetics[1]`. (The `%||%` operator is defined in the rlang package.) For example, in `guide_train.legend()`, the code was changed from this:
```
setNames(list(scale$map(breaks)), scale$aesthetics[1])
```
to this:
```
setNames(list(scale$map(breaks)), aesthetic %||% scale$aesthetics[1])
```

**Comment by hadley** [comment]
Thanks!
