### ISSUE TITLE
Strip placement (bottom, outside) and empty slots

### ISSUE THREAD

**Issue by zz77zz** [tidyverse/ggplot2#2622]
---

[issue raised at https://stackoverflow.com/questions/50385053/ggplot2-unexpected-vapply-error]

In some situations, empty slots in a row together with the "bottom" parameter lead to the following error:

"Error in vapply(row_axes, is.zero, logical(length(row_axes))) : values must be length 3, but FUN(X[[1]]) result is length 1"

```r
library(ggplot2)

zzz <- data.frame(gp = c("a","b","c","d","e","f","g"), 
                  c1 = c(1,1,1,1,1,1,1), 
                  c2 = c(1,1,1,1,1,1,1))

ggplot(zzz, aes(x = c1, y = c2)) +
  facet_wrap(~ gp, scales = "free", nrow = 3, strip.position = "bottom") +
  geom_point() +
  theme(
    aspect.ratio = 1,
    strip.background = element_blank(),
    strip.placement = "outside"
  )
```

**Comment by batpigandme** [comment]
reprex with working example without `strip.position = "bottom"` and one with `strip.position = "left"` (works with others as well):
``` r
library(ggplot2)

zzz <- data.frame(gp = c("a","b","c","d","e","f","g"), 
                  c1 = c(1,1,1,1,1,1,1), 
                  c2 = c(1,1,1,1,1,1,1))

# without strip position argument
ggplot(zzz, aes(x = c1, y = c2)) +
  facet_wrap(~ gp, scales = "free", nrow = 3) +
  geom_point() +
  theme(
    aspect.ratio = 1,
    strip.background = element_blank(),
    strip.placement = "outside"
  )
```

![](https://i.imgur.com/pxBOsVn.png)

``` r

ggplot(zzz, aes(x = c1, y = c2)) +
  facet_wrap(~ gp, scales = "free", nrow = 3, strip.position = "bottom") +
  geom_point() +
  theme(
    aspect.ratio = 1,
    strip.background = element_blank(),
    strip.placement = "outside"
  )
#> Error in vapply(row_axes, is.zero, logical(length(row_axes))): values must be length 2,
#>  but FUN(X[[1]]) result is length 1
```
```r
# works for other positions
ggplot(zzz, aes(x = c1, y = c2)) +
  facet_wrap(~ gp, scales = "free", nrow = 3, strip.position = "left") +
  geom_point() +
  theme(
    aspect.ratio = 1,
    strip.background = element_blank(),
    strip.placement = "outside"
  )
```
![](https://i.imgur.com/RQ7O61J.png)

Created on 2018-05-17 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by batpigandme** [comment]
n.b. also works when total number of facets is divisible by the row number
``` r
library(ggplot2)

zzz <- data.frame(gp = c("a","b","c","d","e","f"), 
                  c1 = c(1,1,1,1,1,1), 
                  c2 = c(1,1,1,1,1,1))

ggplot(zzz, aes(x = c1, y = c2)) +
  facet_wrap(~ gp, scales = "free", nrow = 3, strip.position = "bottom") +
  geom_point() +
  theme(
    aspect.ratio = 1,
    strip.background = element_blank(),
    strip.placement = "outside"
  )
```

![](https://i.imgur.com/t3bgec6.png)

Created on 2018-05-17 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by clauswilke** [comment]
I can't say I understand the code in question, but one way or another this line looks suspicious:
https://github.com/tidyverse/ggplot2/blob/4b609fb22215ce497d22df9d4fd9c70b47d01bdc/R/facet-wrap.r#L300

There's a similar line a little further down, though I wasn't able to create a crash at that position:
https://github.com/tidyverse/ggplot2/blob/4b609fb22215ce497d22df9d4fd9c70b47d01bdc/R/facet-wrap.r#L307

The problem with these lines is the last argument to `vapply()`, e.g. `logical(length(row_axes))`. When `row_axes` holds more than one grob, `logical(length(row_axes))` will be a vector of bools, but `is.zero()` will always return only a single bool, hence the error message. I suspect the correct code would be `vapply(row_axes, ggplot2:::is.zero, logical(length(1)))`.

Reprex to show what I mean:
``` r
library(grid)
library(ggplot2)

row_axes <- list(zeroGrob(), textGrob("test"))
vapply(row_axes, ggplot2:::is.zero, logical(length(1)))
#> [1]  TRUE FALSE
vapply(row_axes, ggplot2:::is.zero, logical(length(row_axes)))
#> Error in vapply(row_axes, ggplot2:::is.zero, logical(length(row_axes))): values must be length 2,
#>  but FUN(X[[1]]) result is length 1
```

Created on 2018-05-17 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by thomasp85** [comment]
It seems to be a simple matter of me messing up the the apply call...

The reason @clauswilke can't provoke an error on the second instance is that it is not possible to have more than a single unfinished row
