### ISSUE TITLE
Manual scales for specific levels only

### ISSUE THREAD

**Issue by Freguglia** [tidyverse/ggplot2#2627]
As an example: 
```
library(ggplot2)
ggplot(iris,aes(x=Petal.Length,y=Petal.Width,color=Species)) +
  geom_point() + 
  scale_color_manual(values=c("versicolor" = "pink",
                              "virginica" = "red",
                              "setosa" = "green"))
```
This piece of code works fine, but let's say I want to have `pink` color for `versicolor` and I really don't care what color is picked for the others. There could be some kind of "auto-completion" for manual scales so that when I try something like the code below, the levels I don't care about have their color value automatically picked (possibly with a warning). Right now an incomplete manual color scale throws an error. This might be specially useful if (a) you're too lazy to type too many color names you don't really care or (b) the number of levels may vary but there is always one you're most interested in.
```
library(ggplot)
ggplot(iris,aes(x=Petal.Length,y=Petal.Width,color=Species)) +
  geom_point() + 
  scale_color_manual(values=c("versicolor" = "pink"))
```

**Comment by clauswilke** [comment]
I would speak out against this proposal. It will lead to some really ugly plots. Picking colors that work well with an existing color scale is even more difficult than just creating an entire color scale from scratch, so whoever would use this functionality would unlikely have the skills to actually pick appropriate colors.

If somebody wants to implement this in an extension package they are free to do so. But even there, I think what would be needed is a highlight scale that allows the user to define the highlighted categories and then picks all the colors, both highlighted and not.

**Comment by Freguglia** [comment]
I built an extension package as @clauswilke suggested. In case someone else is interested: https://github.com/Freguglia/ggfocus

**Comment by clauswilke** [comment]
@Freguglia I think this is a good idea. I would encourage you, however, to think whether you can implement this within the regular grammar rather than providing a special function that wraps the entire plot. Is there any reason why you can't simply write a `scale_focus()` scale that takes a list of aesthetics as an argument?

**Comment by Freguglia** [comment]
Yes, I do agree that the regular grammar would be a better option. I was first trying to implement `color_scale_focus()` for example until I realized that in order to create the appropriate color scale I would need to access the data. The idea was requiring the typing for levels of interested only, but the other levels names are necessary to create the appropriate color scale. 

In short, the function wraps the entire plot because I can't figure out how to (a) create the color scale without the complete list of levels or (b) access the data from the function without having the plot as an argument. But I will think more about it to see if I can figure out a solution with the regular grammar.

**Comment by clauswilke** [comment]
You may have to reimplement the `train_df()` or `train()` functions for your scale.
https://github.com/tidyverse/ggplot2/blob/1f9ef732d766583c4a0d3ddf035ba0c0333ae00e/R/scale-.r#L44-L57

**Comment by Freguglia** [comment]
@clauswilke Do you think creating a new class, `ggf` for example, writing that `scale_focus()` function returning an object of this class and then modifying `"+.ggf"()` to return the function that wraps everything (only when one argument is a `ggplot` and the other is a `ggf`) is a valid approach to implement the regular grammar?

If built appropriately, the regular grammar would work, as calling a `ggplot` + a `ggf` would be exactly the same as calling the function that wraps everything, but this seems a 'hacky' solution.

**Comment by clauswilke** [comment]
You should probably coordinate with @yutannihilation's gghighlight: 
https://github.com/yutannihilation/gghighlight

**Comment by hadley** [comment]
Closing, since development seems to be happening in an extension package.
