### ISSUE TITLE
Change the default estimation method for gam in geom_smooth()

### ISSUE THREAD

**Issue by clauswilke** [tidyverse/ggplot2#2630]
As recommended by the maintainer of the mgcv package, Simon Wood, it might be better to set `method = "REML"` in the `gam()` call for `geom_smooth()`. I quote:

> REML smoothing parameter estimation is less prone to occasional under-smoothing than GCV (e.g. `gam(..., method="REML")`)

**Comment by clauswilke** [comment]
One more comment from Simon Wood:
> Theoretically REML will undersmooth relative to GCV in the large sample limit and have slightly worse MSE performance, but for me the finite sample performance trumps this: Reiss and Ogden, 2009, JRSSB give some theory for why.

The Reiss and Ogden paper is available here: http://www.jstor.org/stable/40247585

`gam(..., method = "REML")` will work for mgcv versions >=1.5-0, March 2009.

**Comment by hadley** [comment]
This should be a straightforward tweak to the existing code, and just needs a news bullet. It is likely to create small changes in some existing plots, but I don't think the differences should be too serious (although it might cause visual tests to fail)
