### ISSUE TITLE
ggsave: option to open on complete

### ISSUE THREAD

**Issue by diplodata** [tidyverse/ggplot2#2636]
It would be nice if an `open = FALSE` option could be added to ggsave, just wrapping `browseURL(filename)` as an extra call on-complete.  Big plots are often much quicker to render to file than in the R console, so my scripts end up with lots of lines like:

    fn = "plotx.png"; ggsave(x, filename = fn, w=w, h=h); browseURL(fn)

It would be nice if they could just be:

    ggsave(x, filename = "plotx.png", w=w, h=h, open=T)

**Comment by hadley** [comment]
This feels out of scope to me; you can always write your own wrapper function.
