### ISSUE TITLE
Add ability for multiple independent axis 

### ISSUE THREAD

**Issue by Maschette** [tidyverse/ggplot2#2647]
Within a number of sciences there are world standards on how to plot data such as Conductivity Temperature and Depth (CTD) data in oceanography or rainfall with elevation in hydrology. The biggest barrier for using ggplot2 is the inability to make plots with multiple independent axis. 

Is this a feature that can be added/is there a way to do this that is just not obvious from the documentation? 

I know you can do multiple axis but sec_axis wants a scaling of the first axis and as far as I can tell doesn't allow them to be independent. 
![ctd-plot-500](https://user-images.githubusercontent.com/14663215/40334852-a69e19ca-5da3-11e8-81a6-5bbf154123ed.jpg)

**Comment by batpigandme** [comment]
This sort of question might be a better fit for https://community.rstudio.com to crowdsource some options. Do you mind asking it over there? (You might want to read https://www.tidyverse.org/help/ first to maximise your chances of getting a good answer.)

**Comment by Maschette** [comment]
I will, but I still think it should be an option in ggplot, base has it, lattice has it ggplot doesn't (and base and lattice are ugly).
