### ISSUE TITLE
The pkgdown page for `geom_sf()` shows only the last plot

### ISSUE THREAD

**Issue by yutannihilation** [tidyverse/ggplot2#2662]
The Examples section of `geom_sf()` has many plots, but only the last one gets plotted.

http://ggplot2.tidyverse.org/reference/ggsf.html#examples

I guess this is because the code is wrapped with `if (requireNamespace("sf", quietly = TRUE)) { ... }` so some tweak is needed here.

**Comment by hadley** [comment]
There's no known work around for this unfortunately.

**Comment by yutannihilation** [comment]
😢
