### ISSUE TITLE
`mblm()` (Theil-Sen estimator) fails as method for `geom_smooth()` 

### ISSUE THREAD

**Issue by eliocamp** [tidyverse/ggplot2#2678]
The function mblm from the package of the same name fits a linear model based on the Theil-Sen estimator but it fails in `geom_smooth()`
``` r
library(ggplot2)

set.seed(42)
df <- data.frame(x = rnorm(100), y = rnorm(100))

ggplot(df, aes(x, y)) +
   geom_point() +
   geom_smooth(method = mblm::mblm)
#> Warning: Computation failed in `stat_smooth()`:
#> unused argument (weights = weight)
```

![](https://i.imgur.com/iHeeThX.png)

The problem is that `mblm` doesn't have a `weights` argument. But if one bypass it, it works perfectly.

``` r
sen <- function(..., weights = NULL) {
   mblm::mblm(...)
}

ggplot(df, aes(x, y)) +
   geom_point() +
   geom_smooth(method = sen)
```

![](https://i.imgur.com/Smk9fYY.png)
I believe that an easy solution is to modify this line: 
https://github.com/tidyverse/ggplot2/blob/54de616213d9811f422f45cf1a6c04d1de6ccaee/R/stat-smooth.r#L132 
to first check the arguments of the function and only add `weights` if needed.

```r
if (is.na(pmatch("weights", names(formals(method))))) {
   base.args <- list(quote(formula), data = quote(data))   
} else {
   base.args <- list(quote(formula), data = quote(data), weights = quote(weight))
}
```
 The check can also be used to build a more informative error message.

**Comment by hadley** [comment]
Rather than tweaking `geom_smooth()` (which might require any number of changes to support other modelling functions), I think you should just provide your own wrapper that ignores weights.

**Comment by eliocamp** [comment]
OK, I think that's sensible, since making a wrapper function is easy enough. 
Would you consider expanding the documentation or the error message so it is clear to the user which arguments the function is expected to take?

**Comment by hadley** [comment]
No because I think `geom_smooth()` is just a simple helper, it's not designed to work with every type of model.
