### ISSUE TITLE
If ggsave() overwrites a file, the timestamp is not updated

### ISSUE THREAD

**Issue by andygarcia** [tidyverse/ggplot2#268]
When ggsave() writes over an existing file, it doesn't seem to update the timestamp.

I usually am looking at timestamps to see outputs being updated.

Is this R or gg?

Andy

**Comment by helix123** [comment]
Just found this old post. Problem is still present in
R version 3.2.2 (2015-08-14)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1
stats     graphics  grDevices utils     datasets  methods   base
ggplot2_1.0.1

Did nobody file a bug with R?
