### ISSUE TITLE
Label y-axis geom_bar() when position is 'fill'

### ISSUE THREAD

**Issue by EdwinTh** [tidyverse/ggplot2#2690]
The label on the y-axis for `geom_bar()`, when not specified, is *count*.

```r
library(ggplot2)
pl <- ggplot(mtcars, aes(as.factor(cyl), fill = as.factor(vs)))
pl + geom_bar()
```

Which is sensible, except when `position = fill`.

```r
pl + geom_bar(position = "fill")
```
Now proportions are shown, not counts. I think the default label should be changed to *prop* or *proportion* under these settings .

**Comment by hadley** [comment]
Yes, that would definitely be nice, but unfortunately due to the design of ggplot2, it's basically impossible.
