### ISSUE TITLE
Error in calc() : could not find function "calc"  (ggplot2_2.2.1.9000)

### ISSUE THREAD

**Issue by taraskaduk** [tidyverse/ggplot2#2695]
Loading the latest version of ggplot2, it doesn't seem to find the `calc()` function

Taking an example from http://ggplot2.tidyverse.org/reference/calc.html

```r
library(ggplot2)

ggplot(mpg, aes(displ)) +
    geom_histogram(aes(y = calc(count / max(count))))
```

Returns this:
`Error in calc(count/max(count)) : could not find function "calc"`

A call without `calc()` runs fine:

```r
ggplot(mpg, aes(displ)) +
    geom_histogram()
```

Lookups such as `?calc` `?ggplot2::calc` return no results

---
ggplot2 version is installed from GitHub and is ggplot2 `2.2.1.9000`

**Comment by thomasp85** [comment]
`calc()` was renamed to `stat()` in #2620 in order to avoid a nameclash

**Comment by taraskaduk** [comment]
OK, that's great. Feels like updating the ggplot pages would be helpful: http://ggplot2.tidyverse.org/reference/calc.html and others on http://ggplot2.tidyverse.org/ 

Looks like the source files already reflect the change, but it is not published.

**Comment by batpigandme** [comment]
That's because it's not yet on CRAN. The source files in your install reflect your installation (the dev version).

**Comment by karawoo** [comment]
I agree it's confusing that the docs site currently doesn't reflect either the dev or CRAN versions of ggplot2, since it was updated a month ago and a few things like `calc()`/`stat()` have changed since then. But as we're actively working on the next release it should all get cleared up soon.

**Comment by batpigandme** [comment]
@karawoo yep, we're also working on a better system for having CRAN and dev pkgdown sites in simultaneous existence in a way that is clear to the user! 🙏

**Comment by taraskaduk** [comment]
@batpigandme, thank you! By "source files" I meant the alleged source for http://ggplot2.tidyverse.org/. Like, the source for http://ggplot2.tidyverse.org/reference/calc.html is https://github.com/tidyverse/ggplot2/blob/master/R/aes-calculated.r

The latter link reflects `stat()` while the former still says `calc()`. My guess is that some has already update the source file for this `calc()`/`stat()` page, but the changes haven't been published yet.

I totally understand the pain points. Thank you for the explanation
