### ISSUE TITLE
inherit.aes ignored in geom_{ab,h,v}line

### ISSUE THREAD

**Issue by adrfantini** [tidyverse/ggplot2#2696]
The documentation for [geom_abline](http://ggplot2.tidyverse.org/reference/geom_abline.html) says that `inherit.aes` is a valid parameter for this geom: ` If specified and inherit.aes = TRUE (the default)...`, but it seems not: `Warning: Ignoring unknown parameters: inherit.aes`:

Example:
```R
p <- ggplot(mtcars, aes(wt, mpg)) + geom_point()

# Fixed values
p + geom_vline(xintercept = 5)
p + geom_vline(xintercept = 5, inherit.aes = TRUE)
#Warning: Ignoring unknown parameters: inherit.aes
```

**Comment by ppanko** [comment]
Seems like this is a case of an old behavior updated by #482 as `inherit.aes` is no longer passed to `layer` where it is hard-coded to `FALSE`. The documentation for `geom_*line` may need to be updated to reflect this.

**Comment by yutannihilation** [comment]
This is purely a documentation issue, and it seems fixed now; `inherit.aes` no more exists in the documentation of `geom_abline()` and the reason is explained clearly:

> Unlike most other geoms, these geoms do not inherit aesthetics from the plot default, because they do not understand x and y aesthetics which are commonly set in the plot. They also do not affect the x and y scales.

**Comment by yutannihilation** [comment]
Ah, true. Sorry...
