### ISSUE TITLE
annotation-logticks documentation contains errors, no plots

### ISSUE THREAD

**Issue by dpseidel** [tidyverse/ggplot2#2703]
example plots are not drawn due to "polygon edge not found" error.
http://ggplot2.tidyverse.org/reference/annotation_logticks.html

**Comment by dpseidel** [comment]
The docs were fixed by the rebuild in tidyverse/ggplot2-docs@e48e0b4 . As this an intermittent error, we might still want to consider changing the example unless/until the root cause is fixed. The source is not the annotation logticks themselves but rather the `scales::math_format()` labels.

**Comment by teunbrand** [comment]
This has been fixed somewhere along the way, so I'll mark this as completed.
