### ISSUE TITLE
coord_flip Discards Axis Limits

### ISSUE THREAD

**Issue by DarioS** [tidyverse/ggplot2#2705]
Is it by design that `coord_flip` discards already set axis limits? It's probably not what the user would expect before they saw the Usage section of the documentation.

```r
plotData <- data.frame(x = 1:3, y = 3:1)
aPlot <- ggplot(plotData, aes(x = x, y = y)) + geom_point() + coord_cartesian(ylim = c(0, 10))
aPlot + coord_flip()
```

It's also unclear from the parameter descriptions if `xlim` and `ylim` refer to the axes before or after flipping is completed. It turns out they are applied to the axes before they are flipped, so `ylim`actually controls the horizontal axis of the resultant plot.

**Comment by hadley** [comment]
You have completely replaced the coordinate system; the new coordinate system knows nothing about the old one.
