### ISSUE TITLE
Feature Request:  Make Missing mapping Errors More Informative

### ISSUE THREAD

**Issue by billdenney** [tidyverse/ggplot2#2706]
When generating a plot recently, I accidentally left out the mapping.  When running the code, I got an uninformative error indicating that the mapping was missing.  Can the errors for missing mappings be improved to indicate something similar to "No mapping provided for required aesthetic 'x'" (and similar)?

``` r
library(ggplot2)         
ggplot(data.frame(A=1)) +
geom_line()              
#> Error in order(data$PANEL, data$group, data$x): argument 3 is not a vector
```

**Comment by Ax3man** [comment]
This error is specific to `geom_line` it seems.

**Comment by hadley** [comment]
Yes, this is already done in general; but `geom_line()` seems to have slipped through the cracks.

**Comment by dpseidel** [comment]
This is a variant of the same issue documented in #2637.  The error is caused because `Geom*$setup_data` runs before `check_required_aes()`  in `layer$compute_geom_1()`. I'm testing the fix and should have a PR shortly.
