### ISSUE TITLE
Filling density histograms with multiple colors

### ISSUE THREAD

**Issue by rpruim** [tidyverse/ggplot2#2707]
It doesn't appear to be possible to create a density histogram with multiple colors (say to indicate a tail of the distribution).  `stat(density)` seems to be computing densities separately for each fill rather than once for all.  `group = 1` doesn't seem to change that behavior.

Is there any way to achieve the desired plot?  Is it possible to create a custom use of `stat()` to do this, or will the computations always be done separately within the different fills?

``` r
# this works as expected
library(ggplot2)
ggplot(data = iris) + 
  geom_histogram(aes(Sepal.Length, fill = Sepal.Length > 7))
#> `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
```

![](https://i.imgur.com/zZAqvr0.png)

``` r
# This distorts the relative proportions
ggplot(data = iris) + 
  geom_histogram(aes(Sepal.Length, y = stat(density), fill = Sepal.Length > 7))
#> `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
```

![](https://i.imgur.com/GUsEU8E.png)

``` r
# group = 1 doesn't seem to do anything
ggplot(data = iris) + 
  geom_histogram(aes(Sepal.Length, y = stat(density), fill = Sepal.Length > 7), group = 1)
#> `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
```

![](https://i.imgur.com/05r6Fgh.png)

Created on 2018-06-20 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by clauswilke** [comment]
This is maybe a bit counter-intuitive when you see it for the first time. You'll have to fill based on the x value calculated by the stat rather than the original variable mapped along the x axis.
``` r
library(ggplot2)
ggplot(data = iris) + 
  geom_histogram(aes(Sepal.Length, y = stat(density), fill = stat(x) > 7))
#> `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
```

![](https://i.imgur.com/mTARJy4.png)

Created on 2018-06-20 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by rpruim** [comment]
Thanks.

Is `stat(x)` the center of each bin?

**Comment by clauswilke** [comment]
Yes. You can use `xmin` or `xmax` to get the left or right edge of the bins, respectively.

**Comment by rpruim** [comment]
Is there a way to get the statified data returned (as  data frame) or any other way to inspect what is going on and what things are called?

**Comment by clauswilke** [comment]
Yes. Look into the `layer_data()` function.
