### ISSUE TITLE
Aligning geoms with preserve = "single" appears impossible

### ISSUE THREAD

**Issue by Ax3man** [tidyverse/ggplot2#2712]
I want to plot a geom without with together with a geom that does have width, e.g. points and boxplots. 

Not all factor combinations are present.

The default of adjusting the width (`preserve = 'total'`) works fine. But when maintaining the box widths with `preserve = 'single'` I can no longer do the same for the points.

``` r
library(ggplot2)

ggplot(mtcars, aes(factor(gear), mpg, fill = factor(am))) + 
  geom_boxplot(position = position_dodge(preserve = 'total')) +
  geom_point(position = position_dodge(0.75, preserve = 'total'))
```

![](https://i.imgur.com/TJWY0Kl.png)

``` r

ggplot(mtcars, aes(factor(gear), mpg, fill = factor(am))) + 
  geom_boxplot(position = position_dodge(preserve = 'single')) +
  geom_point(position = position_dodge(0.75, preserve = 'total'))
```

![](https://i.imgur.com/WB3HoXJ.png)

``` r

ggplot(mtcars, aes(factor(gear), mpg, fill = factor(am))) + 
  geom_boxplot(position = position_dodge(preserve = 'single')) +
  geom_point(position = position_dodge(0.75, preserve = 'single'))
#> Warning in max(table(panel$xmin)): no non-missing arguments to max;
#> returning -Inf
```

![](https://i.imgur.com/ti0hIG5.png)

Created on 2018-06-24 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by batpigandme** [comment]
I don't think this (below) is what you're going for, but you might want to try playing around with [`position_dodge2()`](https://ggplot2.tidyverse.org/reference/position_dodge.html).
``` r
library(ggplot2)

ggplot(mtcars, aes(factor(gear), mpg, fill = factor(am))) + 
  geom_boxplot(position = position_dodge2(0.75, preserve = 'single')) +
  geom_point(position = position_dodge2(0.75, preserve = 'single'))
```

![](https://i.imgur.com/qLod72Y.png)

Created on 2018-06-24 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by Ax3man** [comment]
Yes ok, this solves it:
```
ggplot(mtcars, aes(factor(gear), mpg, fill = factor(am))) + 
  geom_boxplot(position = position_dodge2(0.75, preserve = 'single')) +
  geom_point(position = position_dodge(0.75, preserve = 'total'))
```
![rplot08](https://user-images.githubusercontent.com/15309336/41846280-7e407a02-7876-11e8-8ce9-137d9eb3aa76.png)


I didn't expect that one needs to pass different positions to the two geoms for them to line up, but I guess it makes sense to always use dodge2 for geoms that have width and dodge for geoms that don't.
