### ISSUE TITLE
scale_*_continuous trans and limits combination leading to blank plot

### ISSUE THREAD

**Issue by igordot** [tidyverse/ggplot2#2715]
I noticed an odd behavior for `scale_*_continuous` `limits` parameter. I think it would be easiest to show an example rather than try to explain.

Set up the plot.

```r
library("ggplot2")
df <- data.frame(trt = c("a", "b", "c"), outcome = c(2.3, 1.9, 3.2))
p <- ggplot(df, aes(trt, outcome)) + geom_col()
```

Start adjusting `scale_y_continuous()`.

```r
p + scale_y_continuous(trans = "log", limits = c(1, 5))
```
![image](https://user-images.githubusercontent.com/6363505/41882288-211ce302-78b6-11e8-919b-ae41aeaf3d0c.png)

```r
p + scale_y_continuous(trans = "log1p", limits = c(1, 5))
```
![image](https://user-images.githubusercontent.com/6363505/41882297-2c5cbc24-78b6-11e8-8981-965499033ad2.png)

```r
p + scale_y_continuous(trans = "log1p", limits = c(0, 5))
```
![image](https://user-images.githubusercontent.com/6363505/41882301-33cdd0f6-78b6-11e8-93e8-3dc6603431db.png)

The first and third plots are expected, but why is the middle empty? There is no error or warning.

I am using R 3.4.4 with ggplot2 2.2.1.

**Comment by clauswilke** [comment]
Bars are not shown unless they fit entirely within the specified limits. This is expected behavior. However, I agree that there probably should be a warning.

Simpler reprex (the transformation is irrelevant):
``` r
library(ggplot2)
df <- data.frame(trt = c("a", "b", "c"), outcome = c(2.3, 1.9, 3.2))
ggplot(df, aes(trt, outcome)) + geom_col() + scale_y_continuous(limits = c(1, 4))
```

![](https://i.imgur.com/xenQwUq.png)

Created on 2018-06-25 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by igordot** [comment]
@clauswilke Isn't the transformation still relevant? My first two examples have the same limits, but only one is visible.

**Comment by clauswilke** [comment]
I think the question is why are bars shown in the first plot, not why are they absent in the second. `log(0)=-Inf`, so the bars should extend to minus infinity (and hence outside the set limits).

**Comment by igordot** [comment]
@clauswilke Good point. I guess what I really meant is there is a discrepancy between the first and second.

Regardless, there should probably be a warning if the data is outside the limits on either end. For example, there is a warning if the upper bound is lowered:
```
> p + scale_y_continuous(trans = "log1p", limits = c(0, 5))
> p + scale_y_continuous(trans = "log1p", limits = c(0, 1.5))
Warning message:
Removed 3 rows containing missing values (position_stack). 
```

**Comment by clauswilke** [comment]
I understand what is happening now. First the data are transformed using the transformation provided to the scale, and then `geom_col()` draws a column from 0 in the transformed space to whatever value is given in the transformed space. This explains why the bars start at 1 in the case of the log transform and at 0 in the case of the log1p transform, and this behavior is correct. (In log space, bars should start at 1.)

The only remaining question is where in the code bars are excluded when they don't fit entirely within the scale limits and how we could produce a warning for this case. Maybe @hadley can point me in the right direction here.

**Comment by hadley** [comment]
I have a vague recollection that we've tried to make this an error or warning in the past, and the obvious thing doesn't work. That's probably not much help 😞

**Comment by clauswilke** [comment]
Yes, the problem is that warnings are generated early in the processing pipeline and here the zero value is injected at a later stage. I'll see if I can come up with something.

**Comment by clauswilke** [comment]
I've figured it out. The issue is that the `required_aes` values for `GeomCol()` (and `GeomBar()`, which has the same issue) are different from those of `GeomRect()`, but `GeomRect()` is used for drawing. Therefore, the coordinates created by `GeomCol()` are ignored when missing values are evaluated. The fix is to define `non_missing_aes` appropriately. Will do a PR momentarily.

``` r
library("ggplot2")
df <- data.frame(trt = c("a", "b", "c"), outcome = c(2.3, 1.9, 3.2))
p <- ggplot(df, aes(trt, outcome)) + geom_col()

p + scale_y_continuous(trans = "log1p", limits = c(1, 5))
#> Warning: Removed 3 rows containing missing values (geom_col).
```

![](https://i.imgur.com/7zSVPCH.png)

Created on 2018-06-26 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).
