### ISSUE TITLE
geom_area with missing data issue

### ISSUE THREAD

**Issue by space-echo** [tidyverse/ggplot2#2720]
Hey,

I think I found an issue with geom_area. I think it relates to this issue  #https://github.com/tidyverse/ggplot2/issues/280, although the problem looks like it might be different to the previous problem. Have used the same dataframe as from issue above.

You can see that although the bar plot shows nothing for g = B at point x = 3, the area plot seems to make it look like it's actually g = A that is missing data. See chart and code below.

<img width="709" alt="screen shot 2018-06-27 at 23 53 17" src="https://user-images.githubusercontent.com/40328393/41978626-8f2eb482-7a65-11e8-9782-eacc63a3245d.png">

``` sh
dat <- data.frame(
  g=rep(LETTERS[1:3], each=4),
  x=rep(1:4, 3),
  y=rep(3:14))

# Remove row with g=B, x=3 
dat <- dat[!(dat$g == "B" & dat$x == 3), ] 

g <- ggplot(dat, aes(x=x, y=y, fill=g)) 

p1 <- g + geom_bar(stat = "identity")
p2 <- g + geom_area(stat = "identity")

output <- gridExtra::grid.arrange(p1, p2, ncol = 2)

```

**Comment by batpigandme** [comment]
As noted in the thread to which you referred, the problem here is one of automatic interpolation — obviously this isn't the desired behaviour, but the area chart is, in effect, treating your x-axis as continuous.

**Comment by clauswilke** [comment]
`geom_area()` is drawing exactly the data it is given, so the behavior is correct. To get the plot you want, you'll have to set the y value of the missing cases to 0.

``` r
library(ggplot2)
dat <- data.frame(
  g=rep(LETTERS[1:3], each=4),
  x=rep(1:4, 3),
  y=rep(3:14))

dat[dat$g == "B" & dat$x == 3, ]$y <- 0 
ggplot(dat, aes(x=x, y=y, fill=g)) + geom_area(stat = "identity")
```

![](https://i.imgur.com/F5GgDnr.png)

Created on 2018-06-29 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).
