### ISSUE TITLE
Cannot set legend.box.background with theme_void()

### ISSUE THREAD

**Issue by clauswilke** [tidyverse/ggplot2#2723]
It doesn't seem possible to set the `legend.box.background` theme setting under `theme_void()`. Other legend settings work.

Reprex:
``` r
library(ggplot2)
df <- data.frame(x = 1:3)
ggplot(df, aes(x, x, color = factor(x))) +
  geom_point() +
  theme_void() +
  theme(legend.background = element_rect(fill = "gray80"))
```

![](https://i.imgur.com/OqMv7T4.png)

``` r

df <- data.frame(x = 1:3)
ggplot(df, aes(x, x, color = factor(x))) +
  geom_point() +
  theme_void() +
  theme(legend.box.background = element_rect(fill = "gray80"))
#> Warning in if (theme$legend.box == "horizontal") {: the condition has
#> length > 1 and only the first element will be used
#> Warning in if (theme$legend.box == "vertical") {: the condition has length
#> > 1 and only the first element will be used
#> Error in gtable_add_cols(guides, theme$legend.box.margin[4], pos = 0): is.gtable(x) is not TRUE
```

Created on 2018-06-28 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by clauswilke** [comment]
Also, this works without `theme_void()`, of course:

``` r
library(ggplot2)
df <- data.frame(x = 1:3)
ggplot(df, aes(x, x, color = factor(x))) +
  geom_point() +
  #theme_void() +
  theme(legend.box.background = element_rect(fill = "gray80"))
```

![](https://i.imgur.com/DVGFKr0.png)

Created on 2018-06-28 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by ptoche** [comment]
works for me:
sessionInfo()
R version 3.5.0 (2018-04-23)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS High Sierra 10.13.4

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils    
[5] datasets  methods   base     

other attached packages:
[1] ggplot2_2.2.1

loaded via a namespace (and not attached):
 [1] labeling_0.3     colorspace_1.3-2
 [3] scales_0.5.0     compiler_3.5.0  
 [5] lazyeval_0.2.1   plyr_1.8.4      
 [7] tools_3.5.0      pillar_1.2.3    
 [9] gtable_0.2.0     tibble_1.4.2    
[11] yaml_2.1.19      Rcpp_0.12.17    
[13] grid_3.5.0       digest_0.6.15   
[15] rlang_0.2.1      munsell_0.5.0

**Comment by batpigandme** [comment]
I'm able to reproduce this with the latest dev. build.

**Traceback**
```
9: stop(msg, call. = FALSE, domain = NA)
8: stopifnot(is.gtable(x))
7: gtable_add_cols(guides, theme$legend.box.margin[4], pos = 0)
6: guides_build(ggrobs, theme)
5: build_guides(plot$scales, plot$layers, plot$mapping, position, 
       theme, plot$guides, plot$labels)
4: ggplot_gtable.ggplot_built(data)
3: ggplot_gtable(data)
2: print.ggplot(x)
1: function (x, ...) 
   UseMethod("print")(x)
```

**Comment by clauswilke** [comment]
It's probably related to the changes in the theme inheritance code in the latest version. Some edge case that wasn't considered.

**Comment by clauswilke** [comment]
I've figured it out. The immediate cause is a missing `legend.box` element in the theme:

``` r
library(ggplot2)
df <- data.frame(x = 1:3)
ggplot(df, aes(x, x, color = factor(x))) +
  geom_point() +
  theme_void() +
  theme(
    legend.box = "horizontal",
    legend.box.background = element_rect(fill = "gray80")
  )
```

![](https://i.imgur.com/txtDe6e.png)

Created on 2018-06-28 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

The ulterior reason is this `if`--`else` sequence:
https://github.com/tidyverse/ggplot2/blob/348b26f38c3f8a44731f23013091d51bcf1d10e6/R/guides-.r#L251-L280

It contains no default if `legend.box` is neither "horizontal" nor "vertical". I think this line:
https://github.com/tidyverse/ggplot2/blob/348b26f38c3f8a44731f23013091d51bcf1d10e6/R/guides-.r#L266
should be turned into an unconditional `else`.

**Comment by karawoo** [comment]
The easiest I guess would be to change `theme$legend.box %||% "vertical"` to `theme[["legend.box"]] %||% "vertical"`. Agreed on the other points though.

**Comment by clauswilke** [comment]
@karawoo I'm moving that discussion to separate issue #2724.
