### ISSUE TITLE
Strange facet_* error with column names

### ISSUE THREAD

**Issue by tstev** [tidyverse/ggplot2#2730]
I was trying to build a `facet_grid` plot of my data when I kept encountering the following error:

`Error in scale_apply(layer_data, x_vars, "train", SCALE_X, x_scales) : `

Below a reproducible example that tries to simulate my data. Firstly, I upgraded `ggplot` from `2.2.0` to `3.0.0` but it didn't help. While trying to figure out how to solve the issue I by chance copied the data into a reduced `data.table` with different column names. To my surprise it then did work. Seems strange to me that the column name has such influence. I was wondering if it's just a freak error on my system (`sessionInfo()` attached). Unfortunately, I cannot test on multiple systems.

``` r
library(data.table)
#> Warning: package 'data.table' was built under R version 3.4.4
library(ggplot2)
#> Warning: package 'ggplot2' was built under R version 3.4.4

set.seed(42)
dat <- data.table(VALUE = sample(seq(0, 0.5, by = 0.001), 100, replace = TRUE),
                  PANEL = c("A","B")[sample(c(1, 2), 100, replace = TRUE)])
ggplot(dat, aes(VALUE)) + 
  geom_density(trim = TRUE) +
  facet_grid(. ~ PANEL)
#> Error in scale_apply(layer_data, x_vars, "train", SCALE_X, x_scales):

setnames(dat, "PANEL", "GRP")

ggplot(dat, aes(VALUE)) + 
   geom_density(trim = TRUE) +
  facet_grid(. ~ GRP)

sessionInfo()
#> R version 3.4.0 (2017-04-21)
#> Platform: x86_64-w64-mingw32/x64 (64-bit)
#> Running under: Windows 10 x64 (build 17134)
#> 
#> Matrix products: default
#> 
#> locale:
#> [1] LC_COLLATE=English_United States.1252 
#> [2] LC_CTYPE=English_United States.1252   
#> [3] LC_MONETARY=English_United States.1252
#> [4] LC_NUMERIC=C                          
#> [5] LC_TIME=English_United States.1252    
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> loaded via a namespace (and not attached):
#>  [1] compiler_3.4.0  backports_1.1.2 magrittr_1.5    rprojroot_1.3-2
#>  [5] tools_3.4.0     htmltools_0.3.6 yaml_2.1.19     Rcpp_0.12.17   
#>  [9] stringi_1.1.7   rmarkdown_1.10  knitr_1.20      stringr_1.3.1  
#> [13] digest_0.6.15   evaluate_0.10.1
```

![](https://i.imgur.com/YPNsNDQ.png)

Created on 2018-07-04 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by hadley** [comment]
Yes, unfortunately PANEL is a special variable name used internally by the facetting system.

**Comment by tstev** [comment]
Right, sorry - useless issue then. I was not aware of this.
