### ISSUE TITLE
object ‘enexprs’ is not exported by 'namespace:rlang'

### ISSUE THREAD

**Issue by agarwal-peeush** [tidyverse/ggplot2#2732]
I've installed "ggplot2" package successfully. But when I try to load "ggplot2" library, I get error, as shown below:

```r
library(ggplot2)
#> Warning: package 'ggplot2' was built under R version 3.4.4
#> Error: package or namespace load failed for 'ggplot2':
#>  object 'enexprs' is not exported by 'namespace:rlang'
```

**Comment by hadley** [comment]
You'll need to update rlang.

@dpseidel can you please bump the dependency version of rlang to the latest on CRAN?

**Comment by tcash21** [comment]
+1 installing the latest version of rlang fixed this issue for me as well.
