### ISSUE TITLE
ggplot_add.by()

### ISSUE THREAD

**Issue by lawremi** [tidyverse/ggplot2#2734]
`ggplot_add()` lacks a method for "by" objects. Unfortunately, "by" objects do not have "list" in their class attribute, so `ggplot_add.default()` is hit instead of `ggplot_add.list()`. Given the prevalent use of `by()`, is it worth adding a method?

**Comment by hadley** [comment]
Sure, but what you imagine the method doing?

**Comment by lawremi** [comment]
Just calling the list method.

**Comment by hadley** [comment]
This just needs something like 

```R
ggplot_add.by <- function(object, plot, object_name) {
  ggplot_add.list(object, plot, object_name)
}
```

I don't think it needs a formal unit test — we should be able to tell by inspection (plus a single local test) whether or not it's correct.
