### ISSUE TITLE
Automatic y range with geom_boxplot doesn't include outliers

### ISSUE THREAD

**Issue by wch** [tidyverse/ggplot2#274]
This example should include the range -8000 to 8000, but it only goes from about -4000 to 4000. This is enough to include the whiskers but not the outliers.

``` R
dat <- data.frame(x=1, y=c(-(1:20)^3, (1:20)^3) )
ggplot(dat, aes(x,y)) + geom_boxplot()
```

Test code:

``` R
test_that("geom_boxplot range includes all outliers", {
  dat <- data.frame(x=1, y=c(-(1:20)^3, (1:20)^3) )
  p <- ggplot_build(ggplot(dat, aes(x,y)) + geom_boxplot())

  miny <- p$panel$ranges[[1]]$y.range[1]
  maxy <- p$panel$ranges[[1]]$y.range[2]

  expect_true(miny <= min(dat$y))
  expect_true(maxy >= max(dat$y))
})
```

**Comment by fdp2012** [comment]
I'm having a similar problem with scatterplots (combination of points and smooth)...when using "wrap" some values in one of the groups are not shown...any ideas??
