### ISSUE TITLE
Stat for ploting sf data as label and text

### ISSUE THREAD

**Issue by yutannihilation** [tidyverse/ggplot2#2742]
According to #2111, ggplot2 decided not to implement `stat_sf(geom = "text")` to avoid complexity.
But, I face the necessity to plot labels and texts on sf maps so often that I'm urged to make [a package](https://yutannihilation.github.io/ggsflabel/index.html)...

IIUC, it's not so complicated to implement a stat that retrieves the coordinates from a sf object and map the computed variables `X` and `Y`. Do you feel it's ok for this to live in ggplot2? If yes, I'm happy to make a PR. (If no, I will develop my package and submit it to CRAN.)

Here's an example implementation:

``` r
library(ggplot2)

StatSfCoordinates <- ggproto(
  "StatSfCoordinates", Stat,
  setup_params = function(data, params) {
    if (is.null(params$fun.geometry)) {
      params$fun.geometry <- sf::st_point_on_surface
    }
    params
  },
  compute_group = function(data, scales, fun.geometry) {
    points_sfc <- fun.geometry(data$geometry)
    coordinates <- sf::st_coordinates(points_sfc)
    data <- cbind(data, coordinates)
    
    data
  },
  
  default_aes = aes(x = stat(X), y = stat(Y)),
  required_aes = c("geometry")
)

nc <- sf::st_read(system.file("shape/nc.shp", package = "sf"), quiet = TRUE)
ggplot(nc[1:3, ]) +
  geom_sf(aes(fill = AREA)) +
  geom_label(aes(geometry = geometry, label = NAME), stat = "sf_coordinates")
#> Warning in st_point_on_surface.sfc(data$geometry): st_point_on_surface may
#> not give correct results for longitude/latitude data
```

![](https://i.imgur.com/9P52UNW.png)

Created on 2018-07-08 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by thomasp85** [comment]
I’ve been thinking about this as well, and can’t see how much of extra complexity it would add. If it’s decided not to be put in ggplot2 I would welcome it in ggforce

**Comment by hadley** [comment]
If you think you can implement it without adding a bunch of extra options (and default aesthetics) to `geom_sf()`, I'd be happy to consider a PR. But maybe `geom_sf_label()` would be better?

**Comment by yutannihilation** [comment]
Thanks! Actually, `geom_sf_label()` (and `geom_sf_text()`) are what I've had in my mind :)

c.f. https://yutannihilation.github.io/ggsflabel/reference/geom_sf_label.html

I expect implementing them doesn't affect `geom_sf()`.

**Comment by hadley** [comment]
Yeah that sounds good and I’d be happy to review a PR. I’d probably suggest documenting with geom_sf

**Comment by yutannihilation** [comment]
Sure!

@thomasp85 
Are you interested in including `geom_sf_label_repel()` and `geom_sf_text_repel()` in ggforce? If so, I'll abandon my package.

**Comment by thomasp85** [comment]
Yes

**Comment by clauswilke** [comment]
@yutannihilation Maybe you can talk to the maintainer of ggrepel whether they can be added there directly? Seems like the more logical place.

**Comment by yutannihilation** [comment]
@clauswilke Agreed, thanks!

**Comment by adrfantini** [comment]
This is also a feature I use from time to time, thanks to taking the time to add it!
