### ISSUE TITLE
ggmosaic::geom_mosaic breaks with version 3.0.0

### ISSUE THREAD

**Issue by jpgoldberg** [tidyverse/ggplot2#2746]
It appears that among the breaking changes in 3.0.0 is something that breaks [ggmosaic 0.1.2](https://github.com/haleyjeppson/ggmosaic). I understand that this issue for ggmosaic, I but I am referencing [that ggmosaic issue](https://github.com/haleyjeppson/ggmosaic/issues/9) here for cross tracking. I am also hoping that the ggplot2 developers be able to offer some help or insight on the ggmosaic issue.

```
> packageVersion("ggplot2")
[1] ‘3.0.0.9000’
> library(ggmosaic)
Loading required package: ggplot2
Loading required package: productplots
[...]
> example(geom_mosaic)
[...]
gm_msc> ggplot(data=titanic) +
gm_msc+   geom_mosaic(aes(weight=Freq, x=product(Class), fill=Survived))
Hit <Return> to see next plot: 
Error in is.finite(x) : default method not implemented for type 'list'
```

When using ggplot 2.2.1, geom_mosaic works without error.
```r
# insert reprex here
```

**Comment by batpigandme** [comment]
Could you please turn this into a self-contained reprex, or use a built-in dataset? I don't have `titanic` (I loaded the package titanic, which has `Titanic`, but that creates a different error, due to the data format — see below), and want to make sure I'm reproducing the error you're seeing correctly.
``` r
library(tidyverse)
library(ggmosaic)
#> Loading required package: productplots
#> 
#> Attaching package: 'ggmosaic'
#> The following objects are masked from 'package:productplots':
#> 
#>     ddecker, hspine, mosaic, prodcalc, spine, vspine
library(titanic)

ggplot(data = Titanic) +
  geom_mosaic(aes(weight = Freq, x = product(Class), fill = Survived))
#> Error: `data` must be a data frame, or other object coercible by `fortify()`, not an S3 object with class table
```
Created on 2018-07-09 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by batpigandme** [comment]
The example from the ggmosaic vignette (which requires the NHANES package) seems to work using the development version of ggmosaic, and the most recent version of ggplot2.
``` r
library(tidyverse)
library(ggmosaic)
#> Loading required package: productplots
#> 
#> Attaching package: 'ggmosaic'
#> The following objects are masked from 'package:productplots':
#> 
#>     ddecker, hspine, mosaic, prodcalc, spine, vspine
library(NHANES)

ggplot(data = NHANES) +
  geom_mosaic(aes(weight = Weight, x = product(SleepHrsNight), fill=factor(SleepHrsNight)), na.rm=TRUE)
```

![](https://i.imgur.com/6EOH04J.png)

Created on 2018-07-09 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by batpigandme** [comment]
Just realized you were using the example – this also works with the devel verison of ggmosaic.
``` r
library(tidyverse)
library(ggmosaic)
#> Loading required package: productplots
#> 
#> Attaching package: 'ggmosaic'
#> The following objects are masked from 'package:productplots':
#> 
#>     ddecker, hspine, mosaic, prodcalc, spine, vspine

example("geom_mosaic")
#> 
#> gm_msc> data(Titanic)
#> 
#> gm_msc> titanic <- as.data.frame(Titanic)
#> 
#> gm_msc> titanic$Survived <- factor(titanic$Survived, levels=c("Yes", "No"))
#> 
#> gm_msc> ggplot(data=titanic) +
#> gm_msc+   geom_mosaic(aes(weight=Freq, x=product(Class), fill=Survived))
```

![](https://i.imgur.com/NUUTwIq.png)

    #> 
    #> gm_msc> # good practice: use the 'dependent' variable (or most important variable)
    #> gm_msc> # as fill variable
    #> gm_msc> 
    #> gm_msc> # or turn the dependent variable on explicitly (note the difference in the
    #> gm_msc> # labelling of the y axis)
    #> gm_msc> ggplot(data=titanic) +
    #> gm_msc+   geom_mosaic(aes(weight=Freq, x=product(Class), y=product(Survived),
    #> gm_msc+                   fill=Survived))

![](https://i.imgur.com/rVFGjxO.png)

    #> 
    #> gm_msc> ggplot(data=titanic) +
    #> gm_msc+   geom_mosaic(aes(weight=Freq, x=product(Class, Age), fill=Survived))

![](https://i.imgur.com/W2qkPDm.png)

    #> 
    #> gm_msc> # we can change where we define variables
    #> gm_msc> ggplot(data=titanic, aes(weight = Freq, fill=Survived, x=product(Class, Age))) +
    #> gm_msc+   geom_mosaic()

![](https://i.imgur.com/qQM41xK.png)

    #> 
    #> gm_msc> ggplot(data=titanic) +
    #> gm_msc+   geom_mosaic(aes(weight=Freq, x=product(Class), conds=product(Age), fill=Survived))

![](https://i.imgur.com/uUXucCF.png)

    #> 
    #> gm_msc> ggplot(data=titanic) +
    #> gm_msc+   geom_mosaic(aes(weight=Freq, x=product(Survived, Class), fill=Age))

![](https://i.imgur.com/3SMoONO.png)

    #> 
    #> gm_msc> ## Not run: 
    #> gm_msc> ##D data(happy, package="productplots")
    #> gm_msc> ##D 
    #> gm_msc> ##D ggplot(data = happy) + geom_mosaic(aes(x=product(happy)), divider="hbar")
    #> gm_msc> ##D ggplot(data = happy) + geom_mosaic(aes(x=product(happy))) +
    #> gm_msc> ##D   coord_flip()
    #> gm_msc> ##D # weighting is important
    #> gm_msc> ##D ggplot(data = happy) +
    #> gm_msc> ##D   geom_mosaic(aes(weight=wtssall, x=product(happy)))
    #> gm_msc> ##D ggplot(data = happy) + geom_mosaic(aes(weight=wtssall, x=product(health), fill=happy)) +
    #> gm_msc> ##D   theme(axis.text.x=element_text(angle=35))
    #> gm_msc> ##D ggplot(data = happy) +
    #> gm_msc> ##D   geom_mosaic(aes(weight=wtssall, x=product(health), fill=happy), na.rm=TRUE)
    #> gm_msc> ##D ggplot(data = happy) +
    #> gm_msc> ##D   geom_mosaic(aes(weight=wtssall, x=product(health, sex, degree), fill=happy),
    #> gm_msc> ##D   na.rm=TRUE)
    #> gm_msc> ##D 
    #> gm_msc> ##D # here is where a bit more control over the spacing of the bars is helpful:
    #> gm_msc> ##D # set labels manually:
    #> gm_msc> ##D ggplot(data = happy) +
    #> gm_msc> ##D   geom_mosaic(aes(weight=wtssall, x=product(age), fill=happy), na.rm=TRUE, offset=0) +
    #> gm_msc> ##D   scale_x_productlist("Age", labels=c(17+1:72))
    #> gm_msc> ##D # thin out labels manually:
    #> gm_msc> ##D labels <- c(17+1:72)
    #> gm_msc> ##D labels[labels %% 5 != 0] <- ""
    #> gm_msc> ##D ggplot(data = happy) +
    #> gm_msc> ##D   geom_mosaic(aes(weight=wtssall, x=product(age), fill=happy), na.rm=TRUE, offset=0) +
    #> gm_msc> ##D   scale_x_productlist("Age", labels=labels)
    #> gm_msc> ##D ggplot(data = happy) +
    #> gm_msc> ##D   geom_mosaic(aes(weight=wtssall, x=product(age), fill=happy, conds = sex),
    #> gm_msc> ##D   divider=mosaic("v"), na.rm=TRUE, offset=0.001) +
    #> gm_msc> ##D   scale_x_productlist("Age", labels=labels)
    #> gm_msc> ##D # facetting works!!!!
    #> gm_msc> ##D ggplot(data = happy) +
    #> gm_msc> ##D   geom_mosaic(aes(weight=wtssall, x=product(age), fill=happy), na.rm=TRUE, offset = 0) +
    #> gm_msc> ##D   facet_grid(sex~.) +
    #> gm_msc> ##D   scale_x_productlist("Age", labels=labels)
    #> gm_msc> ##D 
    #> gm_msc> ##D ggplot(data = happy) +
    #> gm_msc> ##D   geom_mosaic(aes(weight = wtssall, x = product(happy, finrela, health)),
    #> gm_msc> ##D   divider=mosaic("h"))
    #> gm_msc> ##D ggplot(data = happy) +
    #> gm_msc> ##D   geom_mosaic(aes(weight = wtssall, x = product(happy, finrela, health)), offset=.005)
    #> gm_msc> ##D 
    #> gm_msc> ##D # Spine example
    #> gm_msc> ##D ggplot(data = happy) +
    #> gm_msc> ##D  geom_mosaic(aes(weight = wtssall, x = product(health), fill = health)) +
    #> gm_msc> ##D  facet_grid(happy~.)
    #> gm_msc> ## End(Not run)
    #> gm_msc> 
    #> gm_msc> 
    #> gm_msc>

Created on 2018-07-09 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by jpgoldberg** [comment]
@batpigandme, please check which version of ggplot2 you get with `library(tidyverse)`. ggmosaic works fine if that is loading ggplot2 version 2.2.1 (as it does in my case). The problem is with ggplot2 3.0.0.

My apologies for failing to make it clear that I was testing with `example(geom_mosaic)` which loads all of the data required for running the example.

**Comment by batpigandme** [comment]
This is with ggplot2 3.0.0
``` r
library(ggplot2)
library(ggmosaic)
#> Loading required package: tibble
#> Loading required package: productplots
#> 
#> Attaching package: 'ggmosaic'
#> The following objects are masked from 'package:productplots':
#> 
#>     ddecker, hspine, mosaic, prodcalc, spine, vspine

example("geom_mosaic")
#> 
#> gm_msc> data(Titanic)
#> 
#> gm_msc> titanic <- as.data.frame(Titanic)
#> 
#> gm_msc> titanic$Survived <- factor(titanic$Survived, levels=c("Yes", "No"))
#> 
#> gm_msc> ggplot(data=titanic) +
#> gm_msc+   geom_mosaic(aes(weight=Freq, x=product(Class), fill=Survived))
```

![](https://i.imgur.com/M4X83gQ.png)

    #> 
    #> gm_msc> # good practice: use the 'dependent' variable (or most important variable)
    #> gm_msc> # as fill variable
    #> gm_msc> 
    #> gm_msc> # or turn the dependent variable on explicitly (note the difference in the
    #> gm_msc> # labelling of the y axis)
    #> gm_msc> ggplot(data=titanic) +
    #> gm_msc+   geom_mosaic(aes(weight=Freq, x=product(Class), y=product(Survived),
    #> gm_msc+                   fill=Survived))

![](https://i.imgur.com/1SgpvGg.png)

    #> 
    #> gm_msc> ggplot(data=titanic) +
    #> gm_msc+   geom_mosaic(aes(weight=Freq, x=product(Class, Age), fill=Survived))

![](https://i.imgur.com/7YO8dJi.png)

    #> 
    #> gm_msc> # we can change where we define variables
    #> gm_msc> ggplot(data=titanic, aes(weight = Freq, fill=Survived, x=product(Class, Age))) +
    #> gm_msc+   geom_mosaic()

![](https://i.imgur.com/eQ7JDmq.png)

    #> 
    #> gm_msc> ggplot(data=titanic) +
    #> gm_msc+   geom_mosaic(aes(weight=Freq, x=product(Class), conds=product(Age), fill=Survived))

![](https://i.imgur.com/5uOThWX.png)

    #> 
    #> gm_msc> ggplot(data=titanic) +
    #> gm_msc+   geom_mosaic(aes(weight=Freq, x=product(Survived, Class), fill=Age))

![](https://i.imgur.com/NyMGqTp.png)

    #> 
    #> gm_msc> ## Not run: 
    #> gm_msc> ##D data(happy, package="productplots")
    #> gm_msc> ##D 
    #> gm_msc> ##D ggplot(data = happy) + geom_mosaic(aes(x=product(happy)), divider="hbar")
    #> gm_msc> ##D ggplot(data = happy) + geom_mosaic(aes(x=product(happy))) +
    #> gm_msc> ##D   coord_flip()
    #> gm_msc> ##D # weighting is important
    #> gm_msc> ##D ggplot(data = happy) +
    #> gm_msc> ##D   geom_mosaic(aes(weight=wtssall, x=product(happy)))
    #> gm_msc> ##D ggplot(data = happy) + geom_mosaic(aes(weight=wtssall, x=product(health), fill=happy)) +
    #> gm_msc> ##D   theme(axis.text.x=element_text(angle=35))
    #> gm_msc> ##D ggplot(data = happy) +
    #> gm_msc> ##D   geom_mosaic(aes(weight=wtssall, x=product(health), fill=happy), na.rm=TRUE)
    #> gm_msc> ##D ggplot(data = happy) +
    #> gm_msc> ##D   geom_mosaic(aes(weight=wtssall, x=product(health, sex, degree), fill=happy),
    #> gm_msc> ##D   na.rm=TRUE)
    #> gm_msc> ##D 
    #> gm_msc> ##D # here is where a bit more control over the spacing of the bars is helpful:
    #> gm_msc> ##D # set labels manually:
    #> gm_msc> ##D ggplot(data = happy) +
    #> gm_msc> ##D   geom_mosaic(aes(weight=wtssall, x=product(age), fill=happy), na.rm=TRUE, offset=0) +
    #> gm_msc> ##D   scale_x_productlist("Age", labels=c(17+1:72))
    #> gm_msc> ##D # thin out labels manually:
    #> gm_msc> ##D labels <- c(17+1:72)
    #> gm_msc> ##D labels[labels %% 5 != 0] <- ""
    #> gm_msc> ##D ggplot(data = happy) +
    #> gm_msc> ##D   geom_mosaic(aes(weight=wtssall, x=product(age), fill=happy), na.rm=TRUE, offset=0) +
    #> gm_msc> ##D   scale_x_productlist("Age", labels=labels)
    #> gm_msc> ##D ggplot(data = happy) +
    #> gm_msc> ##D   geom_mosaic(aes(weight=wtssall, x=product(age), fill=happy, conds = sex),
    #> gm_msc> ##D   divider=mosaic("v"), na.rm=TRUE, offset=0.001) +
    #> gm_msc> ##D   scale_x_productlist("Age", labels=labels)
    #> gm_msc> ##D # facetting works!!!!
    #> gm_msc> ##D ggplot(data = happy) +
    #> gm_msc> ##D   geom_mosaic(aes(weight=wtssall, x=product(age), fill=happy), na.rm=TRUE, offset = 0) +
    #> gm_msc> ##D   facet_grid(sex~.) +
    #> gm_msc> ##D   scale_x_productlist("Age", labels=labels)
    #> gm_msc> ##D 
    #> gm_msc> ##D ggplot(data = happy) +
    #> gm_msc> ##D   geom_mosaic(aes(weight = wtssall, x = product(happy, finrela, health)),
    #> gm_msc> ##D   divider=mosaic("h"))
    #> gm_msc> ##D ggplot(data = happy) +
    #> gm_msc> ##D   geom_mosaic(aes(weight = wtssall, x = product(happy, finrela, health)), offset=.005)
    #> gm_msc> ##D 
    #> gm_msc> ##D # Spine example
    #> gm_msc> ##D ggplot(data = happy) +
    #> gm_msc> ##D  geom_mosaic(aes(weight = wtssall, x = product(health), fill = health)) +
    #> gm_msc> ##D  facet_grid(happy~.)
    #> gm_msc> ## End(Not run)
    #> gm_msc> 
    #> gm_msc> 
    #> gm_msc>
    
    devtools::session_info()
    #> Session info -------------------------------------------------------------
    #>  setting  value                       
    #>  version  R version 3.4.4 (2018-03-15)
    #>  system   x86_64, darwin15.6.0        
    #>  ui       X11                         
    #>  language (EN)                        
    #>  collate  en_US.UTF-8                 
    #>  tz       America/New_York            
    #>  date     2018-07-09
    #> Packages -----------------------------------------------------------------
    #>  package      * version    date      
    #>  assertthat     0.2.0.9000 2018-06-27
    #>  backports      1.1.3      2018-05-15
    #>  base         * 3.4.4      2018-03-15
    #>  bindr          0.1.1      2018-03-13
    #>  bindrcpp       0.2.2.9000 2018-04-03
    #>  colorspace     1.3-2      2016-12-14
    #>  compiler       3.4.4      2018-03-15
    #>  crayon         1.3.4      2018-05-25
    #>  data.table     1.11.4     2018-05-27
    #>  datasets     * 3.4.4      2018-03-15
    #>  devtools       1.13.6     2018-06-27
    #>  digest         0.6.15     2018-01-28
    #>  dplyr          0.7.6      2018-06-29
    #>  evaluate       0.10.1     2017-06-24
    #>  ggmosaic     * 0.1.2.9000 2018-07-09
    #>  ggplot2      * 3.0.0      2018-07-03
    #>  glue           1.2.0.9000 2018-06-20
    #>  graphics     * 3.4.4      2018-03-15
    #>  grDevices    * 3.4.4      2018-03-15
    #>  grid           3.4.4      2018-03-15
    #>  gtable         0.2.0      2016-02-26
    #>  htmltools      0.3.6.9001 2018-06-20
    #>  htmlwidgets    1.2.1      2018-06-22
    #>  httr           1.3.1      2017-08-20
    #>  jsonlite       1.5        2017-06-01
    #>  knitr          1.20       2018-02-20
    #>  labeling       0.3        2014-08-23
    #>  lazyeval       0.2.1.9000 2018-03-20
    #>  magrittr       1.5        2014-11-22
    #>  memoise        1.1.0      2018-03-20
    #>  methods      * 3.4.4      2018-03-15
    #>  munsell        0.5.0      2018-06-12
    #>  pillar         1.2.4      2018-07-09
    #>  pkgconfig      2.0.1      2017-03-21
    #>  plotly         4.7.1.9000 2018-07-09
    #>  plyr           1.8.4      2016-06-08
    #>  productplots * 0.1.1      2016-07-02
    #>  purrr          0.2.5      2018-05-29
    #>  R6             2.2.2      2017-06-17
    #>  Rcpp           0.12.17    2018-05-18
    #>  rlang          0.2.0.9001 2018-07-08
    #>  rmarkdown      1.10       2018-06-11
    #>  rprojroot      1.3-2      2018-01-03
    #>  scales         0.5.0.9000 2018-07-09
    #>  stats        * 3.4.4      2018-03-15
    #>  stringi        1.2.3      2018-06-12
    #>  stringr        1.3.1      2018-05-10
    #>  tibble       * 1.4.2.9003 2018-07-09
    #>  tidyr          0.8.1      2018-05-18
    #>  tidyselect     0.2.4.9000 2018-05-29
    #>  tools          3.4.4      2018-03-15
    #>  utils        * 3.4.4      2018-03-15
    #>  viridisLite    0.3.0      2018-02-01
    #>  withr          2.1.2      2018-06-27
    #>  yaml           2.1.19     2018-05-01
```
Created on 2018-07-09 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).
