### ISSUE TITLE
ggsave is not working when executed via Rscript. 

### ISSUE THREAD

**Issue by abeeCrombie** [tidyverse/ggplot2#2752]
sorry this is a bit above my pay grade but I just spent all afternoon trying to figure out why a script I run wasnt working. I loaded the new ggplot package yesterday and now all my scripts that I run via task scheduler dont execute the ggsave command. 

here is the error message I got
`Error in (function (file = if (onefile) "Rplots.pdf" else "Rplot%03d.pdf",  : 
  cannot open file 'Rplots.pdf'
Calls: ggsave ... withVisible -> eval -> eval -> <Anonymous> -> <Anonymous>
Execution halted`

code works fine in Rstudio and R command but not via Rscript.exe. 

I see there were some recent commits. Hopefully you guys are smarter than me to figure out why its not working

**Comment by baptiste** [comment]
Sometimes I find that the pdf reader (e.g. Adobe reader) prevents other programs from changing the file; presumably some locking mechanism. Maybe try another filename.

**Comment by clauswilke** [comment]
Can you please provide a minimal reproducible example? From what you have provided in your issue description it's impossible to guess what's going on.

**Comment by abeeCrombie** [comment]
clauswilke, unfortunatly I already reinstalled the old version of ggplot2 on my machine so the issue is fixed. 

What I can say is try running any script that contains a creating of standard ggplot2 chart from a file, and do so running via task scheduler / Rscript.exe. That is basically what I did and still go the same error. The issue was only about plotting

I am on a windows 10 machine. Hope that helps. 

`
library(ggplot2)

set.seed(1234)
df <- data.frame(
  sex=factor(rep(c("F", "M"), each=200)),
  weight=round(c(rnorm(200, mean=55, sd=5), rnorm(200, mean=65, sd=5)))
)
p = ggplot(df, aes(x=weight)) + geom_histogram()
ggsave("C:/myDirectory/myFile.png", plot = p, width = 5, height = 5, units = "in")

`

**Comment by clauswilke** [comment]
Could you run a script that contains the following one line of code and see if it triggers the error?

``` r
grDevices::dev.set(1)
```

**Comment by clauswilke** [comment]
Also, I assume that as a workaround, adding the following to the script should prevent the error:
``` r
setwd("C:/myDirectory/")
```

I don't run Windows, so I can't debug this directly.

**Comment by abeeCrombie** [comment]
setting the directory hasnt been a problem, as long as the output file has a complete path + file name. 

Its probably more related to the dev.set(1). 

I just ran on a version of R with ggplot2 new version and with the older version, and got the same results. Old ggplot 2 worked, new ggplt didnt

If I set the grDevices::dev.set(1) the file does not run via Rscript.exe, even using the old ggplot2 package. Hope that is clear.

Sorry I can't be of more help. But let me me know if there is something else I can do to troubleshoot this isse

the full code uused to produce the file

`library(ggplot2)

set.seed(1234)
df <- data.frame(
  sex=factor(rep(c("F", "M"), each=200)),
  weight=round(c(rnorm(200, mean=55, sd=5), rnorm(200, mean=65, sd=5)))
)
p = ggplot(df, aes(x=weight)) + geom_histogram()
#grDevices::dev.set(1)
ggsave("D:/RFiles/myFile.png", plot = p, width = 5, height = 5, units = "in")`

**Comment by clauswilke** [comment]
@abeeCrombie We need to be systematic about things. Please try the following two tests:

1. Make a file that contains one single line of code, `grDevices::dev.set(1)`, and nothing else. What happens when you run this file? Do you get any error messages? If yes, please let me know what they say.

2. Please take the original script that caused you trouble, add `setwd("C:/myDirectory/")` (or whatever the correct working directory is for your project) to the top of the script, and run with ggplot2 3.0.0. Does this change anything? I realize that you can save files directly with absolute paths. That's not what this is testing.

**Comment by clauswilke** [comment]
Actually, and one more test. What happens if you place `pdf(NULL)` immediately before the `ggsave()` command. Does this fix things?

**Comment by isteves** [comment]
@clauswilke I ran a few tests on my Windows machine with the script above (& @dpseidel 's guidance).  Hopefully this can help clarify the problem discussed above:

When I ran `Rscript myscript.r` using the script above, I got the following outputs to my folder:
![image 1](https://user-images.githubusercontent.com/25118334/42646908-401d7b50-85d0-11e8-9374-b4a5a6a6a5bd.png)

Using `R CMD BATCH myscript.R`, I get 2 extra files
![image](https://user-images.githubusercontent.com/25118334/42646904-3cd2736a-85d0-11e8-9d47-c6d4b6b79b7e.png)

For both, I get the same behavior with `grDevices::dev.set(1)` and `pdf(NULL)` 

- `grDevices::dev.set(1)` in myscript.r gives me the message `null device 1` but no error
- `pdf(NULL)` gives me the same output minus the RPlots.pdf file

@dpseidel suspects that it might be something to do with looping/the task scheduler, possibly unrelated to Windows/Mac (I think she got similar results)

**Comment by abeeCrombie** [comment]
my mistake. That simple script is working on both ggplot versions. 
It must be something with my specific plot that isnt working. I will try to show a reproducible code, it just a long script & complicated chart and I didnt think it mattered

Sorry to bother everyone.

**Comment by abeeCrombie** [comment]
or magically the windows update my PC did last night solved the issue ;-)

**Comment by dpseidel** [comment]
Great, closing this now.

**Comment by clauswilke** [comment]
I made a PR that will likely fix this issue. It would be great if somebody could test. See here:
https://github.com/tidyverse/ggplot2/issues/2363#issuecomment-404962952

**Comment by mfansler** [comment]
I just want to confirm that @clauswilke's [PR(2758)](https://github.com/tidyverse/ggplot2/pull/2758) fixes a related issue I am seeing with `ggsave` as of ggplot2 v3.0.0.  Namely, on CentOS 7 lacking an X11 device, a common workaround is to set `options(bitmapType = 'cairo')`.  However, when `ggsave` v3.0.0 restores the previous device, it attempts to default back to an X11 device, which results in the error:

    Error in .External2(C_X11, d$display, d$width, d$height, d$pointsize,    : 
      unable to start device X11

A simple workaround is to set an available device before calling `ggsave`, for instance, 

    options(bitmapType = 'cairo', device = 'png')

Not that big a deal, but having @clauswilke's fix merged to master would be preferable.
