### ISSUE TITLE
rlang dependency ahead of rlang itself

### ISSUE THREAD

**Issue by jonocarroll** [tidyverse/ggplot2#2759]
Current dependence on `rlang` is >= 0.2.1

https://github.com/tidyverse/ggplot2/blob/79e8b459e6576784a574bde736290aa6456ef30b/DESCRIPTION#L29

but `rlang` master branch is currently only at 0.2.0.9001

https://github.com/r-lib/rlang/blob/b4f810f1fba2e192ae09921b51441ac6a182970b/DESCRIPTION#L2

Needless to say, this breaks GitHub installs.

Is the intention to depend on another branch of `rlang` or is there a mismatch between DESCRIPTION file commits somewhere? The `release-0.2.1` branch of `rlang` is actually much further out of date.

**Comment by jonocarroll** [comment]
And now I see it's a known issue due to https://github.com/tidyverse/ggplot2/pull/2735 and noted in https://github.com/r-lib/rlang/issues/549.

**Comment by jonocarroll** [comment]
Thank you for the ⚡ fast fix. Greatly appreciated.

**Comment by lionel-** [comment]
It actually comes 20 days late, thanks to @batpigandme for the reminder 😓
