### ISSUE TITLE
geom_edge_arc still not honoring show.legend=FALSE

### ISSUE THREAD

**Issue by mikesafar** [tidyverse/ggplot2#2760]
I'm still having a problem mentioned in earlier issues with show.legend not being honored for continuous variables.  In particular:

```{r}
geom_edge_arc(aes(edge_alpha = VARIABLE), show.legend=c(edge_alpha=FALSE), curvature = .10)
```

It's still showing the legend for correlation.  Other geom_* are working correctly.   

As you can see, i even tried the new specifier, but the show.legend=FALSE also does not work.

**Comment by thomasp85** [comment]
This issue really belong in thomasp85/ggraph

Can I get you to repost it there along with a reprex?
