### ISSUE TITLE
Format multiple geom_sf legends

### ISSUE THREAD

**Issue by Janewyx** [tidyverse/ggplot2#2763]
I am dealing with multiple sf geometries in ggplot and would like to display legend in the form of a point, a line, and a square (for the polygon). However, geom_sf legend combines my geometry features (i.e. combining line and point) displayed below:

```r
library(ggplot2)
library(sf)

poly1 <- cbind(lon = c(5, 6, 7, 5), lat = c(52, 53, 51, 52))

poly <- st_sf(st_sfc(st_polygon(list(poly1))))
line <- st_sf(st_sfc(list(st_linestring(cbind(lon = c(5.5, 4.5), lat = c(53.5, 54.5))))))
point <- st_sf(st_sfc(st_point(cbind(lon = 5.5, lat = 52.7))))

ggplot() +
  geom_sf(data = poly, aes(fill = "A")) +
  geom_sf(data = point, aes(colour = "B"), show.legend = "point") +
  geom_sf(data = line, aes(colour = "C"), show.legend = "line") +
  scale_fill_manual(values = c("A" = "yellow")) +
  scale_colour_manual(values = c("B" = "pink", "C" = "purple")) +
  theme_minimal()
```

![](https://i.stack.imgur.com/2VofC.png)

Would it be possible to have a single yellow square, a pink point, and a purple line on the same image illustrated below? It is only the case when I plot individual geometry but not the combination of three.

![](https://i.stack.imgur.com/i6TfB.png)

![](https://i.stack.imgur.com/fCGqw.png)

![](https://i.stack.imgur.com/WCdct.png)

**Comment by batpigandme** [comment]
Have you tried using [`guides()`](https://ggplot2.tidyverse.org/reference/guides.html)?

**Comment by Janewyx** [comment]
Thank you very much for your suggestion, guide_legend() works perfectly:

```r
library(ggplot2)
library(sf)

poly1 <- cbind(lon = c(5, 6, 7, 5), lat = c(52, 53, 51, 52))

poly <- st_sf(st_sfc(st_polygon(list(poly1))))
line <- st_sf(st_sfc(list(st_linestring(cbind(lon = c(5.5, 4.5), lat = c(53.5, 54.5))))))
point <- st_sf(st_sfc(st_point(cbind(lon = 5.5, lat = 52.7))))

ggplot() +
  geom_sf(data = poly, aes(fill = "A")) +
  geom_sf(data = point, aes(colour = "B"), show.legend = "point") +
  geom_sf(data = line, aes(colour = "C"), show.legend = "line") +
  scale_fill_manual(values = c("A" = "yellow"), 
                    guide = guide_legend(override.aes = list(linetype = "blank", shape = NA))) +
  scale_colour_manual(values = c("B" = "pink", "C" = "purple"),
                      guide = guide_legend(override.aes = list(linetype = c("blank", "solid"), 
                                                               shape = c(16, NA)))) +
  theme_minimal() 
```
Product:
![image](https://user-images.githubusercontent.com/14840520/42839283-15c37666-89b8-11e8-8f42-f887260ba9d4.png)

Inspired by [this post](https://stackoverflow.com/questions/26587940/ggplot2-different-legend-symbols-for-points-and-lines)

**Comment by batpigandme** [comment]
Woohoo!
