### ISSUE TITLE
aesthetics error if only argument is an expression

### ISSUE THREAD

**Issue by emrichter** [tidyverse/ggplot2#2764]
I'm trying to dynamically generate a ggplot-object from within a function. For this, I save a parameter name like "color" or "fill" (dependent on the geom) as an expression and I unquote it within aes(). 
As long as I leave the x and y in the geom-function everything works. If I move them to ggplot() though, I get an error.
What am I missing?

Here a repex:

```r
library(ggplot2)
library(rlang)

arg <- expr(color)

#working
ggplot(data = mpg) +
  geom_point(aes(displ, cty, !!arg := manufacturer))

#not working
ggplot(data = mpg, aes(displ, cty)) +
  geom_point(aes(!!arg := manufacturer))
```

**Comment by clauswilke** [comment]
I believe this is the same issue as #2675.

**Comment by emrichter** [comment]
Thanks a lot. So I'll wait till it's solved : )

**Comment by batpigandme** [comment]
@emrichter yes. I'll close this, since it's the same issue, though.

**Comment by hadley** [comment]
BTW there's an easy work around in the mean time:

```R
ggplot(data = mpg, aes(displ, cty)) +
  geom_point(aes(,, !!arg := manufacturer))
```
