### ISSUE TITLE
Inconsistent behaviour with geom_boxplot `width` 

### ISSUE THREAD

**Issue by dpseidel** [tidyverse/ggplot2#2777]
This bug was discovered as a part of fixing #2281 and initially discussed there. I am breaking this out into a separate issue. 

In `geom_boxplot()` and associated geoms, `width` is typically a computed variable - not one often specified by the user. But in the original issue the poster specified `width = 1` in their reprex, and as I was playing around fixing the resulting bug with `scales::expand_range()`, I noticed strange behaviour if `width` is ever set above 1.  Specifically, when plotting multiple boxplots,  it seems to no longer specify the width of each individual boxplot but instead the width of all plotted boxplots, resulting in axis ticks that don't line up.

Any thoughts on where this is coming from would be most appreciated. If I get time in the next couple weeks, I'll dig into this more.

## Walk through reprex:

Default behavior, computed `width`, expected result:
``` r
library(ggplot2)
library(dplyr)

diamonds %>%
  ggplot(aes(clarity, price)) +
  geom_boxplot()
```

![](https://i.imgur.com/WvJytSY.png)

`width` set to 1. Individual boxplots get wider, each with a width of 1 now:
``` r
diamonds %>%
  ggplot(aes(clarity, price)) +
  geom_boxplot(width = 1)
```

![](https://i.imgur.com/LXifBe1.png)

`width` > 1, entire plot shrinks, axis ticks do not line up. All of the boxplots now fit within the designated `width` of 1.1.

``` r
diamonds %>%
  ggplot(aes(clarity, price)) +
  geom_boxplot(width = 1.1)
```

![](https://i.imgur.com/JPWSuwi.png)

Any `width` value greater than 1 except 8 (the number of groups) will return a plot with misaligned labels. 

Perhaps this is the expected behaviour of `width` and it's just acting unexpectedly for values ≤ 1 ? Or this is just a scales issue where we need to make sure our break points respect width alignment? Or maybe we shouldn't allow `width` specification at all?

**Comment by karawoo** [comment]
There's been some previous discussion of this in #2331. We decided it was okay as-is, but if it keeps being an issue maybe we should revisit.

**Comment by dpseidel** [comment]
Oh thnx @karawoo! I didn't do a full search of closed issues.

Should we close this then?
