### ISSUE TITLE
geom_area position_stack order appears to have changed

### ISSUE THREAD

**Issue by ptoche** [tidyverse/ggplot2#2778]
The default order of the data in ``geom_area()`` has changed.  The order is no longer the order shown in the manual https://ggplot2.tidyverse.org/reference/position_stack.html

Was that intended? Is it documented?

``` r
series <- data.frame(
    time = c(rep(1, 4),rep(2, 4), rep(3, 4), rep(4, 4)),
    type = rep(c('a', 'b', 'c', 'd'), 4),
    value = rpois(16, 10)
)
library(ggplot2)
ggplot(series, aes(time, value)) +
    geom_area(aes(fill = type))
```

![](https://i.imgur.com/NpXQMMb.png)

``` r

ggplot(series, aes(time, value)) + 
    geom_area(aes(fill = type), position = position_stack(reverse = TRUE))
```

![](https://i.imgur.com/CNyR2F5.png)

Created on 2018-07-26 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

Compare the above with the relevant part of the manual:

    # Stacking is also useful for time series
    series <- data.frame(
      time = c(rep(1, 4),rep(2, 4), rep(3, 4), rep(4, 4)),
      type = rep(c('a', 'b', 'c', 'd'), 4),
      value = rpois(16, 10)
    ) 
    ggplot(series, aes(time, value)) +
      geom_area(aes(fill = type))

https://ggplot2.tidyverse.org/reference/position_stack-5.png

**Comment by ptoche** [comment]
compare with the relevant part of the manual:

# Stacking is also useful for time series
series <- data.frame(
  time = c(rep(1, 4),rep(2, 4), rep(3, 4), rep(4, 4)),
  type = rep(c('a', 'b', 'c', 'd'), 4),
  value = rpois(16, 10)
)
ggplot(series, aes(time, value)) +
  geom_area(aes(fill = type))

https://ggplot2.tidyverse.org/reference/position_stack-5.png

**Comment by ptoche** [comment]
An example from plots I made a couple of years ago. 

Before:

![figure_1_1_old](https://user-images.githubusercontent.com/6339274/43382662-c8913808-93d8-11e8-8fee-3bd81f25e48f.png)


After:

![figure_1_1_new](https://user-images.githubusercontent.com/6339274/43382681-d759b2e8-93d8-11e8-96e7-ae9c5f5618da.png)

**Comment by karawoo** [comment]
It looks the same in the manual to me?

<img width="1552" alt="screen shot 2018-07-30 at 8 30 31 am" src="https://user-images.githubusercontent.com/4452678/43407191-e07bbf70-93d2-11e8-80d4-03e9e689e0ca.png">

I do think the stack order changed at some point but it was a while ago in [2.2.1](https://github.com/tidyverse/ggplot2/blob/master/NEWS.md#stacking).

**Comment by ptoche** [comment]
My plots are from February 2015, so this may well be an old change. 

The example from the manual confused me because I got a plot that looked quite different and assumed it was a common cause. The real reason is that the data used in the example is random. It might be useful to set a seed before the data is created to make it clearer, e.g.

    set.seed(1)
    series <- data.frame(
        time = c(rep(1, 4),rep(2, 4), rep(3, 4), rep(4, 4)),
        type = rep(c('a', 'b', 'c', 'd'), 4),
        value = rpois(16, 10)
    )
    ggplot(series, aes(time, value)) +
        geom_area(aes(fill = type))
