### ISSUE TITLE
preserve = "single" has no effect for continuous axes

### ISSUE THREAD

**Issue by karawoo** [tidyverse/ggplot2#2783]
#2774 made me realize that the `preserve = "single"` argument to `position_dodge()` and `position_dodge2()` has no effect when the x axis is continuous:

``` r
library("ggplot2")

df <- data.frame(
  x = c(4, 5, 6, 4, 6),
  y = c("A", "A", "A", "B", "B")
)

ggplot(df, aes(x = x)) +
  geom_bar(position = position_dodge2(preserve = "single")) +
  facet_wrap(~ y)
```

![](https://i.imgur.com/9SoqBJK.png)

Compare to the version with a discrete x axis:

``` r
ggplot(df, aes(x = factor(x))) +
  geom_bar(position = position_dodge2(preserve = "single")) +
  facet_wrap(~ y)
```

![](https://i.imgur.com/J0hctPt.png)

Created on 2018-07-27 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

Like @clauswilke said on the other issue, I'm not sure what the expectation should be for continuous axes, but maybe we should at least document that `preserve` only works for discrete axes.

**Comment by tungmilan** [comment]
Saw this on SO. Not sure if this is related. If not please move it wherever appropriate. 

**geom_text not properly positioned when using position_dodge(preserve=“single”) in bar plot**
https://stackoverflow.com/q/51813898/786542

```
v1 <- LETTERS[1:2]
v2 <- letters[1:2]
v3 <- c("x","y")
g <- expand.grid(v1,v2,v3)
val=c(sample(10,8))
df<- data.frame(g,val)
df<- df[-8,]


    df %>% ggplot() +
      geom_bar(aes(x=Var2, y=val, fill=Var3, group=Var3), 
               stat="identity", 
               position=position_dodge(preserve="single"))+
      geom_text(aes(x=Var2, y=val+1, label=val, group=Var3), 
                position=position_dodge(width=1))+
  facet_grid(Var1~Var2, scale="free_x")
```

![](https://i.stack.imgur.com/o5yRj.png)

Using position_dodge2 alignes the bar with the labelling (however, the bar is the then centered and not aligned with the bars in the other facets).

```
df %>% ggplot() +
  geom_bar(aes(x=Var2, y=val, fill=Var3, group=Var3), stat="identity", 
           position=position_dodge2(preserve="single"))+
  geom_text(aes(x=Var2, y=val+1, label=val, group=Var3), 
            position=position_dodge2(width=1))+
  facet_grid(Var1~Var2, scale="free_x")
```

**Comment by teunbrand** [comment]
I think this has been fixed somewhere along the way, so I'm gonna mark this as completed.

``` r
library(ggplot2)

df <- data.frame(
  x = c(4, 5, 6, 4, 6),
  y = c("A", "A", "A", "B", "B")
)

ggplot(df, aes(x = x)) +
  geom_bar(position = position_dodge2(preserve = "single")) +
  facet_wrap(~ y)
```

![](https://i.imgur.com/cSq4T7N.png)

<sup>Created on 2023-06-25 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
