### ISSUE TITLE
unexpected behavior for alpha in geom_rect() -- possible bug

### ISSUE THREAD

**Issue by rpruim** [tidyverse/ggplot2#2790]
I'm trying to figure out why `alpha` is ignored by `geom_rect()` in the second example below.  Is this a bug?

``` r
library(ggplot2)
# this works as expected
p <- ggplot() + geom_point(aes(y = eruptions, x = waiting), data = faithful)
p
```

![](https://i.imgur.com/37gcTvw.png)

``` r
p + geom_rect(aes(ymin = 2, ymax = 3, xmin = 50, xmax = 80), alpha = 0.2, 
              fill = "red")
```

![](https://i.imgur.com/pPD6oIm.png)

``` r

# this ignores alpha for some reason
q <- 
  ggplot(aes(y = eruptions, x = waiting), data = faithful) + 
  geom_point()
q
```

![](https://i.imgur.com/UCmwXvu.png)

``` r
q + geom_rect(aes(ymin = 2, ymax = 3, xmin = 50, xmax = 80), alpha = 0.2, 
              fill = "red")
```

![](https://i.imgur.com/rJ9tdPm.png)

``` r

p$mapping
#> Aesthetic mapping: 
#> <empty>
q$mapping
#> Aesthetic mapping: 
#> * `x` -> `waiting`
#> * `y` -> `eruptions`
```

Created on 2018-07-31 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by hadley** [comment]
You’re plotting one rectangle for each row 😉

**Comment by rpruim** [comment]
OK.  I guess that makes sense.  

But supposing `q` already exists (perhaps created by some slick plotting routine in an extension package) and I want to add just one rectangle.  What's the easiest solution?  I tried `data = NULL` and `data = NA`.  

I confirmed that this works:
```r
q + geom_rect(aes(ymin = 2, ymax = 3, xmin = 50, xmax = 80), alpha = 0.2,
                fill = "red", data = faithful[1,])
```

And if I don't have access to the data used to construct the plot?  Then I guess I can (a) make up a meaningless data frame with 1 row and (b) use `inherit.aes = FALSE`.  

Is there something more elegant?

**Comment by rpruim** [comment]
Interestingly, I see that a data frame with 0 rows and 0 columns does produce 1 rectangle:

```r
q + geom_rect(aes(ymin = 2, ymax = 3, xmin = 50, xmax = 80), alpha = 0.2,
              fill = "red", data = data.frame(), inherit.aes = FALSE)
```
So that's better than making up data that don't get used.  Is that my best option?

**Comment by hadley** [comment]
Yup.
