### ISSUE TITLE
geom_boxplot + geom_jitter documentation clarity

### ISSUE THREAD

**Issue by igordot** [tidyverse/ggplot2#2793]
In the documentation for `geom_boxplot`, there is an example:
```r
p <- ggplot(mpg, aes(class, hwy))
p + geom_boxplot() + geom_jitter(width = 0.2)
```
This is useful if you want to see all the points. What is not entirely obvious is that the command retains both the outlier and jitter points. Thus, you may end up with more plotted points then data points. You can see this more easily by coloring one of them:
```r
p + geom_boxplot(outlier.colour = "red") + geom_jitter(width = 0.2)
```
I am not sure what the proper fix would be since this is not really an error, but the documentation should probably clarify this situation.

**Comment by dpseidel** [comment]
Sure I still have a couple open docs PRs, I can slip this in.

**Comment by dpseidel** [comment]
Alright - the adjustment has been made and this issue will close once that PR is merged.
