### ISSUE TITLE
Regression: ggsave in ggplot2 3.0.0 opens a device window

### ISSUE THREAD

**Issue by klmr** [tidyverse/ggplot2#2794]
In interactive mode (in command line R), executing `ggsave` creates a visible device window. This is a regression: no such window was created in ggplot2_2.2.1, and this is very much the desired behaviour )(see https://twitter.com/henrikbengtsson/status/1024565925658480651).

``` r
library(ggplot2)
gg = ggplot(mtcars, aes(mpg, wt)) + geom_point()
dev.list()
#> quartz_off_screen 
#>                 2
ggsave(tempfile(fileext = '.png'), gg)
#> Saving 7 x 5 in image
dev.list()
#> quartz_off_screen 
#>                 2
```

Created on 2018-08-01 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

<details>

<summary>Session info</summary>

``` r
sessionInfo()
#> R version 3.4.4 (2018-03-15)
#> Platform: x86_64-apple-darwin16.7.0 (64-bit)
#> Running under: macOS Sierra 10.12.6
#> 
#> Matrix products: default
#> BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
#> LAPACK: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libLAPACK.dylib
#> 
#> locale:
#> [1] en_GB.UTF-8/en_GB.UTF-8/en_GB.UTF-8/C/en_GB.UTF-8/en_GB.UTF-8
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> other attached packages:
#> [1] ggplot2_3.0.0
#> 
#> loaded via a namespace (and not attached):
#>  [1] Rcpp_0.12.18     bindr_0.1.1      knitr_1.20       magrittr_1.5    
#>  [5] tidyselect_0.2.4 munsell_0.5.0    colorspace_1.3-2 R6_2.2.2        
#>  [9] rlang_0.2.1      stringr_1.3.1    plyr_1.8.4       dplyr_0.7.6     
#> [13] tools_3.4.4      grid_3.4.4       gtable_0.2.0     withr_2.1.2     
#> [17] htmltools_0.3.6  assertthat_0.2.0 yaml_2.2.0       lazyeval_0.2.1  
#> [21] rprojroot_1.3-2  digest_0.6.15    tibble_1.4.2     crayon_1.3.4    
#> [25] bindrcpp_0.2.2   purrr_0.2.5      glue_1.3.0       evaluate_0.11   
#> [29] rmarkdown_1.10   labeling_0.3     stringi_1.2.4    compiler_3.4.4  
#> [33] pillar_1.3.0     scales_0.5.0     backports_1.1.2  pkgconfig_2.0.1
```

</details>

Unfortunately the above reprex is unrepresentative: in an interactive session, the actual output on macOS is:

```r
> dev.list()
NULL
> ggsave('test.png', gg)
Saving 7 x 7 in image
> dev.list()
quartz
     2
```

Under ggplot2_2.2.1, the same code yields:

```r
> dev.list()
NULL
> ggsave('test.png', gg)
Saving 7 x 7 in image
> dev.list()
NULL
```

/cc @HenrikBengtsson, @ilarischeinin

**Comment by thomasp85** [comment]
My guess is that it is related to the new text calculations. grid seems to require an open device for some of its dimension calculations... unsure how to fix it without backtracking on the titleGrob alignments

**Comment by clauswilke** [comment]
I bet it's the same problem as #2363 (see also #2752, #2787).

@klmr, could you try this branch:
`devtools::install_github("clauswilke/ggplot2@issue-2363-ggsave")` and see if it fixes the issue?

**Comment by ilarischeinin** [comment]
@clauswilke, It did for me at least.

**Comment by klmr** [comment]
Ah *that’s* where this broken `Rplots.pdf` in my PWD is from! Yes, very much related, and your PR solves the issue for me, too.

**Comment by klmr** [comment]
It just occurred to me that {reprex} is doing something really weird above. @jennybc, could you have a look? Why is the initial `dev.list()` not `NULL`? Is this a bug in {reprex}?

**Comment by klmr** [comment]
@jennybc Yup, I’m not surprised the results are *different* but I’d expect the list of graphics devices, specifically, to be empty in a fresh session: no matter how I try to invoke R (interactive, `R CMD BATCH`, `Rscript`, {callr}), `dev.list()` is `NULL`.

**Comment by jennybc** [comment]
@klmr I can reproduce it in various ways, including in a barebones `.Rmd` with a single chunk containing `dev.list()`. So wherever this `quartz_off_screen` device is coming from, it looks like a larger knitr/rmarkdown phenomenon that reprex inherits.
