### ISSUE TITLE
Making Two Plots Same Width No Longer Works

### ISSUE THREAD

**Issue by DarioS** [tidyverse/ggplot2#2795]
The [technique depending on `ggplot_gtable` and `unit.pax`](https://stackoverflow.com/a/49937994) used by many StackOverflow answers to make two plots have the same width no longer works in version 3.0.0 (but does in version 2.2.1). The only news items mentioning such functionality which I notice are

> `ggplot_build()` and `ggplot_gtable()` are now generics, so ggplot-subclasses can define additional behavior during the build stage.

and

> ... Also, the object returned from `ggplot_build()` now has the class `"ggplot_built"`.

so I don't think that a change to the visuals is intended.

**Comment by clauswilke** [comment]
I think this is a case of stackoverflow giving bad advice. I think manipulating gtables should always be a solution of last resort, when nothing else is available, and then it's important to understand what the gtable manipulation actually does.

In this case, the function `align_plots()` in the cowplot package does what you want: 
``` r
library(dplyr)
library(tidyr)
library(purrr)
library(ggplot2)

# make plots
df <- iris %>%
  bind_rows(
    iris %>% mutate(Species = paste0(Species, "_", Species)), .id = "gr"
  ) %>%
  group_by(gr, Species) %>% 
  summarise(y = mean(Sepal.Length)) %>% 
  nest(-gr) %>%   
  mutate(
    plots = map(
      data,
      ~ggplot(data = .x, aes(Species, y)) + geom_point() + coord_flip()
    )
  )
#> Warning in bind_rows_(x, .id): binding factor and character vector,
#> coercing into character vector
#> Warning in bind_rows_(x, .id): binding character and factor vector,
#> coercing into character vector

# align plots with cowplot align_plots() function
aligned = cowplot::align_plots(plotlist = df$plots, align = 'v')

cowplot::ggdraw(aligned[[1]])
```

![](https://i.imgur.com/SXcazuK.png)

``` r
cowplot::ggdraw(aligned[[2]])
```

![](https://i.imgur.com/t47RLdq.png)

``` r

# save plots
ggsave("test1.png", cowplot::ggdraw(aligned[[1]]))
#> Saving 7 x 5 in image
ggsave("test2.png", cowplot::ggdraw(aligned[[2]]))
#> Saving 7 x 5 in image
```

However, if you want to manipulate the gtable directly, that's also possible, you just need to make sure you adjust all relevant columns. A safe bet is to adjust all of them. (But that may cause problems with legends or faceted plots. Again, the `align_plots()` function can handle all these cases.)
```
gp1 <- ggplot_gtable(ggplot_build(df$plots[[1]]))
gp2 <- ggplot_gtable(ggplot_build(df$plots[[2]]))
maxWidths = grid::unit.pmax(gp1$widths, gp2$widths)

gp1$widths <- maxWidths
gp2$widths <- maxWidths
cowplot::ggdraw(gp1)
```

![](https://i.imgur.com/dnEFuiC.png)

``` r
cowplot::ggdraw(gp2)
```

![](https://i.imgur.com/Kj0lLXu.png)

Created on 2018-08-01 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by DarioS** [comment]
I'm sold on cowplot!
