### ISSUE TITLE
coord_fixed warning about coordinate system change cannot be turned off

### ISSUE THREAD

**Issue by dracodoc** [tidyverse/ggplot2#2799]
I'm using `coord_fixed` to zoom my plots in shiny app. My special user case is I defined a package function to plot some data, then in shiny app I used that function, also enabled zoom for it

- the package function can be used independently, so it need `coord_fixed()` to assure aspect ratio
- in app zoom is implemented by add another `coord_fixed` call with xlim, ylim. Now the plot have 2 coord_fixed calls so there is this warning after upgraded to 3.0.0:

> Coordinate system already present. Adding new coordinate system, which will replace the existing one.

It seemed that `coord_cartesian` has a parameter to turn off this warning, but `coord_fixed` don't have it.

```r
library(ggplot2)
ggplot(mtcars, aes(mpg, wt)) + geom_point() + 
  coord_fixed() +
  coord_fixed(xlim = c(10, 20))

```

**Comment by clauswilke** [comment]
Workaround:
``` r
library(ggplot2)

ggplot(mtcars, aes(mpg, wt)) + geom_point() + 
  coord_fixed() +
  coord_fixed(xlim = c(10, 20))
#> Coordinate system already present. Adding new coordinate system, which will replace the existing one.
```

![](https://i.imgur.com/HQ4AyiK.png)

``` r

cf <- coord_fixed()
cf$default <- TRUE

ggplot(mtcars, aes(mpg, wt)) + geom_point() + 
  cf +
  coord_fixed(xlim = c(10, 20))
```

![](https://i.imgur.com/Pkgqb46.png)

Created on 2018-08-03 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by dracodoc** [comment]
I saw the code responsible for the warning message, but didn't realize I can use this to work around the message. Thanks!
