### ISSUE TITLE
stat_summary transforms first before applying summary function (rather than vice versa)

### ISSUE THREAD

**Issue by coolbutuseless** [tidyverse/ggplot2#2804]
I expected `stat_summary` to summarise data first then transform the summary for display. 

What actually happens: the data is transformed **and then** the summary is calculated.

In the reprex below, the mean at x=0 is definitely 1, but when you use a transformed axis, the mean of the transformed values doesn't match that (because the mean of the transformed data is different from the transform of the mean of the data).

Is my expectation wrong here on the order of operations?  Should I be doing something completely different to achieve my goal?  

Is this is a ggplot2 bug? a feature? a limitation of the architecture/grammar-of-graphics? Or am I just doing the wrong thing?

``` r

library(tidyverse)

plot_df <- data.frame(
  x = rep(1:3, each=7),
  y = c(0, 0, 0, 0, 1, 1, 5,    1, 1, 1, 1, 2, 2, 2,      2, 3, 4, 5, 6, 7, 8)
)


p <- ggplot(plot_df, aes(x, y)) +
  geom_point(alpha=0.4) +
  stat_summary(fun.y = mean, geom='line') +
  theme_bw()


# The linear version correctly shows mean at x=0 is 1
p + scale_y_continuous(breaks=1:9) +
  ggtitle("Using stat_summary to draw a mean line\nNote: at x=1 mean=1 (correct)")
```

![](https://i.imgur.com/EHLL4VW.png)

``` r

# Transformed axis version has incorrect mean at x=0
p + scale_y_sqrt(breaks=1:9) +
  ggtitle("Using stat_summary to draw a mean line\nNow with transformed y axis\nNote: at x=1  mean != 1 (incorrect)")
```

![](https://i.imgur.com/NBIsf6t.png)

Created on 2018-08-05 by the [reprex
package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by eliocamp** [comment]
I think that for that case you need to apply the transform in the coordinated, not on the scales. This seems to work. 

``` r
library(ggplot2)

plot_df <- data.frame(
  x = rep(1:3, each=7),
  y = c(0, 0, 0, 0, 1, 1, 5,    1, 1, 1, 1, 2, 2, 2,      2, 3, 4, 5, 6, 7, 8)
)


p <- ggplot(plot_df, aes(x, y)) +
  geom_point(alpha=0.4) +
  stat_summary(fun.y = mean, geom='line') +
  theme_bw()

p + coord_trans(y = "sqrt")
```

![](https://i.imgur.com/7TaNTyM.png)

Created on 2018-08-05 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by coolbutuseless** [comment]
I was just about to update this issue with that plot :)

I don't want the curved lines that this gives.  Which makes me think I should stick with my current custom geom/stat.

But I'm interested to see if there's a way to switch the transform/summary ordering, or if the maintainers are interested in such a PR.

**Comment by eliocamp** [comment]
Mh, that's a tough one. 
I think the curved line is technically a more correct representation of the data, but I can see why you might want to have it straight. In that case, you might have to compute the summary yourself first an then do it by hand? If you have enough ggplot2 mad skillz then a custom geom/stat might do the trick, yes. 

The idea that statistics are computed on the scaled data seems to be part of the foundations of the Grammar of Graphics, so I think it's unlikely that this would change. 
This is from Wilkinson's book:
![image](https://user-images.githubusercontent.com/8617595/43682534-00985e88-984e-11e8-90d4-20f0b0df5b0b.png)

Of course, I can't speak on behalf of the ggteam so I'll let them answer.

**Comment by coolbutuseless** [comment]
@eliocamp I thought that might be the case - i.e. the order of ops is set by the grammar of graphics which means that the thing I want to do is "disallowed" 

In my custom stat/geom I've worked around it by asking `ggplot2::transform_df()` function to keep the original values as well as the transformed ones.  Then I use a flag to ask stat_summary to calculate on the original values rather than the transformed ones.

This probably wrecks the purity of the grammar workflow

**Comment by clauswilke** [comment]
You could always use a summary function that undoes the coordinate transformation. Though I would probably just summarize beforehand using dplyr. In any case, I don't see the need for changes in the ggplot2 code base.

``` r
library(ggplot2)

plot_df <- data.frame(
  x = rep(1:3, each=7),
  y = c(0, 0, 0, 0, 1, 1, 5,    1, 1, 1, 1, 2, 2, 2,      2, 3, 4, 5, 6, 7, 8)
)

ggplot(plot_df, aes(x, y)) +
  geom_point(alpha=0.4) +
  stat_summary(fun.y = function(x) sqrt(mean(x^2)), geom='line') +
  scale_y_sqrt(breaks=1:9) +
  theme_bw()
```

![](https://i.imgur.com/cGXXv8K.png)

Created on 2018-08-05 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by coolbutuseless** [comment]
Hi @clauswilke 

Summarising beforehand in dplyr isn't convenient when you may be facetting/grouping and drawing multiple lines.  It then means you have to keep your dplyr group_by/summarisation code in sync with your ggplot facetting/grouping code - which will be error prone.

And the idea of a function that undoes the coordinate transform is what I (sort of) currently do, but this fails when the transform creates infinities (which are thrown away by default in compute_layer).

e.g. if we do a log transform on the y axis, then all the zeros become infinities and are removed from the stat calculation, and we get the incorrect mean at x=1 is  (5+1+1)/3 = 2.3

``` r
library(ggplot2)

plot_df <- data.frame(
  x = rep(1:3, each=7),
  y = c(0, 0, 0, 0, 1, 1, 5,    1, 1, 1, 1, 2, 2, 2,      2, 3, 4, 5, 6, 7, 8)
)


ggplot(plot_df, aes(x, y)) +
  geom_point(alpha=0.4) +
  stat_summary(fun.y = function(x) log10(mean(10^x)), geom='line') +
  scale_y_log10(breaks=1:9) +
  theme_bw()
#> Warning: Transformation introduced infinite values in continuous y-axis

#> Warning: Transformation introduced infinite values in continuous y-axis
#> Warning: Removed 4 rows containing non-finite values (stat_summary).
```

![](https://i.imgur.com/0Wt47MA.png)

Created on 2018-08-06 by the [reprex
                              package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by hadley** [comment]
You’re asking for a fundamental change to the way that ggplot2 works for a fairly small enhancement that can be achieved with dplyr. The cost-benefit ratio of this proposed change means that it’s not a good fit for ggplot2.

**Comment by coolbutuseless** [comment]
Hi @clauswilke, @hadley 

Fair enough.

Would you be open to considering a small change in an internal data structure which would allow 3rd parties to access the original untransformed data in custom Stats/Geoms?

Something like this change in `scales_transform_df` which would keep the original data during the scaling process?

```r
scales_transform_df <- function(scales, df) {
  if (ggplot2:::empty(df) || length(scales$scales) == 0) return(df)

  transformed <- unlist(lapply(scales$scales, function(s) s$transform_df(df = df)),
    recursive = FALSE)

  # Keep copies of original/untransformed vars
  varnames <- names(transformed)
  orig <- df[varnames]
  colnames(orig) <- paste(varnames, "orig", sep='.')

  plyr::quickdf(c(transformed, df[setdiff(names(df), names(transformed))], orig))
}
```
