### ISSUE TITLE
Function geom_sf does not exist.

### ISSUE THREAD

**Issue by ccpsilva** [tidyverse/ggplot2#2809]
When I search the ggplot2 package using ls("package:ggplot2"), geom_sf is not listed in the library files.

the geom_sf function was excluded from the ggplot2 package? or was it renamed?

All the problems I have to solve have already tried without success.

**Comment by batpigandme** [comment]
I'm not sure what the syntax you're showing is supposed to do, but if you run `?ggplot2::geom_sf` it'll bring up the help file for `geom_sf()`. It's definitely in ggplot2:
https://github.com/tidyverse/ggplot2/blob/17b45f906c3a55d187915f4f3010836a804051ae/R/sf.R#L219
