### ISSUE TITLE
Hide bar border

### ISSUE THREAD

**Issue by royfrancis** [tidyverse/ggplot2#2811]
The border around bars are not hidden when size is set to zero. This is the problem.

```
library(ggplot2)
dfr <- data.frame(x=c("A","B","C"),y=c(4,5,6))

ggplot(dfr,aes(x,y))+
  geom_bar(stat="identity",colour="red",size=0)+
  theme_minimal()
```

![f1](https://user-images.githubusercontent.com/5083500/43844528-3e64d4ce-9b2a-11e8-9746-99ce1b24e1fa.png)

The way to hide it is by specifying colour as NA.

```
ggplot(dfr,aes(x,y))+
  geom_bar(stat="identity",colour=NA,size=0)+
  theme_minimal()
```

![f2](https://user-images.githubusercontent.com/5083500/43844592-69b3aede-9b2a-11e8-9a64-aada1fb116a5.png)

I am not sure why the colour parameter is used to turn off line thickness. When using a shiny app and the colour for the border is input through a widget like [colourInput()](https://www.rdocumentation.org/packages/shinyjs/versions/0.9.1/topics/colourInput), it has to be a colour and NA is not an option. So this means it is not straight-forward to completely remove border from bars. 

Using `ggplot2_2.2.1`.

**Comment by clauswilke** [comment]
I cannot reproduce this with ggplot2 3.0.0.

``` r
library(ggplot2)
dfr <- data.frame(x = c("A", "B", "C"), y = c(4, 5, 6))

ggplot(dfr, aes(x,y))+
  geom_bar(stat = "identity", colour = "red", size = 0) +
  theme_minimal()
```

![](https://i.imgur.com/TdbCKFZ.png)

Created on 2018-08-08 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by royfrancis** [comment]
Interesting! I just upgraded to ggplot2 3.0.0 and still get the borders. I was viewing in the RStudio plot viewer. I also tried to export the plots to various devices.

```
ggsave("test.png",p)
ggsave("test.tiff",p)
ggsave("test.jpeg",p)
ggsave("test.pdf",p)
```

and I still have the border in all of them.

```
> sessionInfo()
R version 3.5.0 (2018-04-23)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_United Kingdom.1252 
[2] LC_CTYPE=English_United Kingdom.1252   
[3] LC_MONETARY=English_United Kingdom.1252
[4] LC_NUMERIC=C                           
[5] LC_TIME=English_United Kingdom.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods  
[7] base     

other attached packages:
[1] ggplot2_3.0.0

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.17     withr_2.1.2      dplyr_0.7.5     
 [4] assertthat_0.2.0 grid_3.5.0       plyr_1.8.4      
 [7] R6_2.2.2         gtable_0.2.0     magrittr_1.5    
[10] scales_0.5.0     pillar_1.2.3     rlang_0.2.1     
[13] lazyeval_0.2.1   bindrcpp_0.2.2   labeling_0.3    
[16] tools_3.5.0      glue_1.2.0       purrr_0.2.5     
[19] munsell_0.5.0    yaml_2.1.19      compiler_3.5.0  
[22] pkgconfig_2.0.1  colorspace_1.3-2 tidyselect_0.2.4
[25] bindr_0.1.1      tibble_1.4.2    
```

**Comment by karawoo** [comment]
I can't reproduce this on Mac. I see you're on Windows; if it's inconsistent between the two platforms my first thought is that it's a graphics device issue, which is probably outside our control.
