### ISSUE TITLE
stat_summary + mean_sdl doesn't plot confidence interval

### ISSUE THREAD

**Issue by jar1karp** [tidyverse/ggplot2#2814]
I have previously used code similar to the example below to plot the average and confidence interval of some series. This still works with older versions, e.g. ggplot2 v2.2.1.

```r
dat <- data.frame(x = rep(1:10, each = 12), y = rnorm(10 * 12))
library(ggplot2)
ggplot(dat, aes(x, y)) + stat_summary(fun.data = 'mean_sdl',
                                      fun.args = list(mult = 1),
                                      geom = 'smooth')
```

With ggplot2 v3.0.0 the above code only plots the average as blue line, but the gray area representing the confidence interval is not plotted at all.

**Comment by clauswilke** [comment]
Since 3.0.0, you need to turn on the confidence band explicitly by setting `se = TRUE`. See also https://github.com/tidyverse/ggplot2/pull/2567.

``` r
dat <- data.frame(x = rep(1:10, each = 12), y = rnorm(10 * 12))
library(ggplot2)
ggplot(dat, aes(x, y)) + 
  stat_summary(fun.data = 'mean_sdl',
               fun.args = list(mult = 1),
               geom = 'smooth', se = TRUE)
```

![](https://i.imgur.com/oNjszys.png)

Created on 2018-08-09 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).
