### ISSUE TITLE
Feature Request: ggplotly() like function for ggvis

### ISSUE THREAD

**Issue by jtelleria** [tidyverse/ggplot2#2819]
Plotly R Package (https://cran.r-project.org/web/packages/plotly/index.html) has a wonderful function which converts ggplot plot objects to plotly objects, which is great for Rmarkdown Documents / Shiny Web Apps:

https://www.rdocumentation.org/packages/plotly/versions/4.7.1/topics/ggplotly

My question is: Is it worth it to create a similar function for the tidyverse which converts to ggplot plot objects to HTML ready ggvis objects?

https://cran.r-project.org/web/packages/ggvis/index.html

This would be great, as it would allow to create ggvis objects using the well-known by the community ggplot2 syntax.

Any thoughts on the topic?

**Comment by thomasp85** [comment]
Irrespective of whether ggvis is dormant, I think it is fair to say that this functionality should not be part of ggplot2, but ggvis or some other wrapper package...

**Comment by jtelleria** [comment]
The point is that people does not seem to use ggvis for interactive graphics, only plotly.

Maybe because the syntax changes?

But ggvis could have a lot of potential as an enabler of HTML graphics using ggplot2 syntax!

Just see how easy is to use the ggplot2() function :)

E.g.: https://plot.ly/ggplot2/geom_bar/

If I have a scatterplot chart with clusters in it, it is always nice to see an interactive chart for being able to see the values of each of the data points :) Easily doable with ggplot2, but it is not part of the tidyverse :S

**Comment by thomasp85** [comment]
As Mara said, ggvis has never been completed and is currently dormant, which goes a long way to explain why people are not using it.

No matter the utility of such a converter it has no place in ggplot2, but should reside in another package (either ggvis or something else)

**Comment by jtelleria** [comment]
Here is plotly's "magic" function:

https://github.com/ropensci/plotly/blob/master/R/ggplotly.R
