### ISSUE TITLE
geom_text - Math expression  label annotation - color and parsing problem

### ISSUE THREAD

**Issue by MarioClueless** [tidyverse/ggplot2#2825]
Hello, 

Two issues actually! 

1st : I have a dataset where I'm incrementing colour by a variable in the aes. I then annotate an expression on the graph which i want to force to plain old simple black ( If I don't force it my geom_text inherits the coloring of the aes. I'm forced to inherit the aes as when I tried to define a custom aes for that layer I have an error saying that the color variabile is not recognized) 

Here's an example 
`reprex.data= data.frame(x= c(4.5, 3,3,3.5,3.5,4,4,0), y= c(4.5, 3,3,3.5,3.5,4,4,0), color= c("A","A","A","A","B","B","A","A"))
{windows(width = 8, height = 5)
  ggplot(reprex.data, aes(x=x,y=y, colour= color, shape = color )) + 
    geom_point() +
    geom_text(aes(label="Alpha[qq]%~~%10^10", x=1.5, y=-3), parse=T, colour= "black", size = 7)+
    scale_color_viridis(option="B", discrete = TRUE, begin = 0.0, end = 0.85, direction = 1)
}}`
If you look closely to the annotation text you'll notice that there seem to be 2 colours overlapping or 2 layers overlapping ? Is this a double print ?
At least it's the case in my R 3.4.3

the second problem has to to with geom_text: 

This works:
`    geom_text(aes(label="Alpha[qq]%~~%10^10", x=1.5, y=-3), parse=T, colour= "black", size = 7)+
`

but as soon as I write an expression like

`"Alpha[qq]%~~%10^10 A"`

It fails. I need to be able to write the unit after my number. Any ideas ?

Thanks!
M.

**Comment by batpigandme** [comment]
This sort of question is a better fit for https://community.rstudio.com. Do you mind asking it over there? (You might want to read https://www.tidyverse.org/help/ first to maximise your chances of getting a good answer).

If it turns out to be a bug in ggplot2, we can always reopen the thread here. Thanks.
