### ISSUE TITLE
Provide a function to properly plot borders with geom_sf

### ISSUE THREAD

**Issue by adrfantini** [tidyverse/ggplot2#2827]
This is a feature request.
Now that `sf` objects are tightly integrated into `ggplot2`, I feel like a function for adding borders to a `sf` plot is would be useful, especially to newcomers. 
`borders()` is useful but, as stated in the documentation, it's a bit crude:

- resets the scale limits instead of inheriting them from the `sf` object plotted
- supports only data from the `maps` package and not, for example, `rworldxtra`, which provides a much higher res world
- uses `geom_polygon`, not `geom_sf`

```R
nc <- sf::st_read(system.file("shape/nc.shp", package = "sf"), quiet = TRUE)
ggplot(nc) + borders("usa") + geom_sf(aes(fill = AREA))
```
![screenshot_20180814_093337](https://user-images.githubusercontent.com/12826141/44077827-21210da4-9fa5-11e8-9094-7579f3cf4aad.png)

`map_data()` requires instead to transform to `sf`, at which point one might as well go through `maps::map` directly, imho.

What I usually do to add borders is:
```R
nc <- sf::st_read(system.file("shape/nc.shp", package = "sf"), quiet = TRUE)
library(rworldxtra)
data(countriesHigh) #Very high-res data, can be slow
countriesHigh = st_as_sf(countriesHigh) %>% st_transform(st_crs(nc))
bbox = st_bbox(nc)
borders = countriesHigh %>% st_crop(bbox + c(-2, -2, 2, 2))
#we leave a bit of margin so we do not see the effects of the crop on the polygons
ggplot(nc) +
        geom_sf(aes(fill = AREA)) +
        geom_sf(
            data = borders,
            fill=NA, colour="red",
            size=1,
            inherit.aes=FALSE
        ) +
        coord_sf(
            crs=st_crs(nc),
            xlim = bbox[c(1,3)],
            ylim = bbox[c(2,4)],
            expand=0
        )
```

![screenshot_20180814_100051](https://user-images.githubusercontent.com/12826141/44079289-ed8a4056-9fa8-11e8-90f2-cc8cdfee6eed.png)

This works well but is a bit complicated, especially for newcomers.
A single function to automate all this (or at least to add borders data without having to crop them and reset the borders afterwards) would be welcome.

**Comment by clauswilke** [comment]
I don't understand what exactly the proposed function would do. The two plots in your reprex look entirely different. In any case, I suspect this is more appropriate for an extension package, in particular if this function needs external data to work (e.g. from rworldxtra).

**Comment by hadley** [comment]
I agree with @clauswilke that this would be better off an extension package - there are a lot of details to get right, and the data that `borders()` uses is far from optimal.
