### ISSUE TITLE
ggsave always opens a graphics window after upgrading to ggplot2 version3.0.0

### ISSUE THREAD

**Issue by alireza08** [tidyverse/ggplot2#2830]
Hello,
ggsave() opens a graphics window in R after I upgraded ggplot2 to version 3.0.0.
Function has width and height parameters, but it still opens up and it is very ugly inside a package.
How can I supress this graphic device?

```r
p1 <- ggplot()
ggsave(plot= p1, filename = '/home/home/Desktop/Folder/plot.png', width = 5, height = 5)
```

**Comment by clauswilke** [comment]
This should be fixed in master (see #2758). Please reopen if that's not the case for you.
