### ISSUE TITLE
`legend.key.size` distorts vertical justification in bottom-aligned legends

### ISSUE THREAD

**Issue by andrewheiss** [tidyverse/ggplot2#2843]
With ggplot2 3.0, when using `legend.key.size` (specifically any changes along the y-axis, like with `legend.key.height`), the verticial justification of legend titles and legend elements becomes unaligned.

Here's a plot with the labels aligned:

```r
ggplot(mtcars, aes(x = hp, y = mpg, fill = as.factor(cyl))) +
  geom_hex() +
  guides(fill = guide_legend(title = "Title goes here")) + 
  theme(legend.position = "bottom")
```

![correct-alignment](https://user-images.githubusercontent.com/73663/44358087-298a7680-a471-11e8-918e-3d9261d020be.png)

Here's a plot with the labels unaligned after legend keys are shrunk (shrunk by a ton for the sake of highlighting the issue). The 4, 6, and 8 are no longer vertically aligned with the title and kind of float above the baseline:
  
```r
ggplot(mtcars, aes(x = hp, y = mpg, fill = as.factor(cyl))) +
  geom_hex() +
  guides(fill = guide_legend(title = "Title goes here")) + 
  theme(legend.position = "bottom") +
  theme(legend.key.size = unit(0.2, "lines"))
```

![incorrect-alignment](https://user-images.githubusercontent.com/73663/44358092-3018ee00-a471-11e8-9919-b1aa7a1a308e.png)

**Comment by andrewheiss** [comment]
Current workaround is to add a tiny bit of negative margin to the top of the legend title, but it'd be nice if legend titles and legend keys could automatically share the same vertical justification

```r
ggplot(mtcars, aes(x = hp, y = mpg, fill = as.factor(cyl))) +
  geom_hex() +
  guides(fill = guide_legend(title = "Title goes here")) + 
  theme(legend.position = "bottom") +
  theme(legend.key.size = unit(0.2, "lines"),
        legend.title = element_text(margin = margin(t = -0.15, unit = "lines")))
```

![image](https://user-images.githubusercontent.com/73663/44358493-686cfc00-a472-11e8-9b15-05b31d261e59.png)

**Comment by clauswilke** [comment]
This happens because the legend key is shrunk to the point where it's only has high as the legend text, and that text is in a smaller font than the legend title. Better workarounds would be to (i) use the same font size for text and title or (ii) set the key width and height separately. Solving this problem in a general way will likely require much improved text and table formatting code.

``` r
library(ggplot2)
ggplot(mtcars, aes(x = hp, y = mpg, fill = as.factor(cyl))) +
  geom_hex() +
  guides(fill = guide_legend(title = "Title goes here")) + 
  theme(
    legend.position = "bottom",
    legend.key.size = unit(.2, "lines"),
    legend.text = element_text(size = rel(1))
  )
```

![](https://i.imgur.com/tdh6uA5.png)

``` r

ggplot(mtcars, aes(x = hp, y = mpg, fill = as.factor(cyl))) +
  geom_hex() +
  guides(fill = guide_legend(title = "Title goes here")) + 
  theme(
    legend.position = "bottom",
    legend.key.width = unit(.2, "lines"),
    legend.key.height = unit(12, "pt")
  )
```

![](https://i.imgur.com/2DfjBmZ.png)

Created on 2018-08-20 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by clauswilke** [comment]
Also, note that in any case you're center-aligning two pieces of text with different heights, so you would never expect the baselines to align. This problem is visible in your first example also, just to a lesser extent.

**Comment by andrewheiss** [comment]
Ah, thanks, I'd missed the misalignment in the first figure (likely because I had the viewport too small on my machine)

By default, then, `legend.text` uses `vjust = 0.5`, correct?

Explicitly setting the font size in `legend.text` works great. Doing other things, like `legend.text = element_text(vjust = 0)` moves all the text to the bottom, but not the keys, creating more vertical misalignment:

<img width="560" alt="image" src="https://user-images.githubusercontent.com/73663/44364418-2cdb2d80-a484-11e8-849f-59e088d72d42.png">

So without adding something like `legend.key.just` (which would manipulate key position), it's probably all fine how it is now—keeping everything vertically centered and relying on users to ensure font sizes are the same for the title and key labels.
