### ISSUE TITLE
Feature Request: Allow `labs()` to Use Input Data

### ISSUE THREAD

**Issue by billdenney** [tidyverse/ggplot2#2845]
When creating many figures simultaneously, I often want to create the labels from the data itself automatically.  In my current need, I want to create a title for a figure based on a clinical study title.  In other cases, I want to create the x- and y-axis labels using a combination of a column naming the measurement and its units.

My current method requires external processing prior to `ggplot()`:

``` r
library(ggplot2)
my_data <- data.frame(x=1:4, y=5:8, study=paste("Study", 1:2))
my_data_1 <- my_data %>% filter(study %in% "Study 1")
study_number <- unique(my_data_1$study)
ggplot(my_data_1, aes(x=x, y=y)) + geom_point() + labs(title=study_number)
```

A (nonworking) example of my thought on how this could be implemented is:

``` r
my_data <- data.frame(x=1:4, y=5:8, study=paste("Study", 1:2))
my_data_1 <- my_data %>% filter(study %in% "Study 1")
ggplot(my_data_1, aes(x=x, y=y)) + geom_point() + labs(title=aes(title=unique(study)))
```

**Comment by smouksassi** [comment]
Is what the new gganimate implement similar to what you need ?

https://github.com/thomasp85/gganimate/blob/master/README.md

You can have something like:

labs(title = 'Year: {frame_time}', x = 'GDP per capita', y = 'life expectancy')

**Comment by billdenney** [comment]
@smouksassi, at a glance, that's just what I need.

I think that with gganimate, I could do the following.  Is that correct?  (I am having some trouble installing it right now.)

``` r
ggplot(my_data_1, aes(x=x, y=y)) + geom_point() + labs(title=aes(title="{study}"))
```

**Comment by hadley** [comment]
Making the labels depend on the plot data is going to introduce complicated dependencies, for relatively little gain (given that you can already wrap up this pattern with your own function).

**Comment by billdenney** [comment]
@hadley, My hope was that it would work similarly to the way that facet_wrap currently works to generate strip headers or alternatively that it could be an aesthetic.  Either way, I would expect the requirement that it collapse to a scalar that is interpretable (which as far as I know means either a character scalar or an expression).

I'm not nearly familiar enough with the inner workings of ggplot2 to know the complexity of my request.

**Comment by smouksassi** [comment]
The gganimate way only work with animated ggplots maybe we should bring this up with @thomasp85 for it to be part of ggforce and ask for it to be possible in any ggplot not only those animated.

**Comment by thomasp85** [comment]
It is unlikely to be feasible as an extension in eg ggforce. The only reason it is possible with gganimate is that I redefine the whole build process

**Comment by clauswilke** [comment]
To me, aesthetic mapping only makes sense when there's (at least in principle) more than one value to map. Since there can only ever be one title in a static plot, aesthetic mapping seems the wrong paradigm. What's wrong with extracting the title from the data set on the fly? (And, as @hadley said, you could always write a function to automate this.)

``` r
library(ggplot2)
library(dplyr)
#> Warning: package 'dplyr' was built under R version 3.5.1
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
my_data <- data.frame(x=1:4, y=5:8, study=paste("Study", 1:2))
my_data_1 <- my_data %>% filter(study %in% "Study 1")
ggplot(my_data_1, aes(x=x, y=y)) + geom_point() + labs(title=unique(my_data_1$study))
```

![](https://i.imgur.com/7AbdBbp.png)

Created on 2018-08-23 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by yutannihilation** [comment]
Technically, I think it's not so difficult to implement a function that creates labels from the plot data as we have `ggplot_add()` now, though.

``` r
library(ggplot2)
library(dplyr, warn.conflicts = FALSE)

ggtitle_glue <- function(x) {
  structure(x, class = "ggtitle_glue")
}

ggplot_add.ggtitle_glue <- function(object, plot, object_name) {
  title <- glue::glue(object, .envir = plot$data)
  plot + ggtitle(title)
}

my_data <- data.frame(x=1:4, y=5:8, study=paste("Study", 1:2))
my_data_1 <- my_data %>% filter(study %in% "Study 1")

ggplot(my_data_1, aes(x=x, y=y)) +
  geom_point() + 
  ggtitle_glue("{unique(study)}")
```

But, I strongly agree with hadley. I don't think this is very useful when you want to generate multiple plots. I recommend purrr for this purpose. For example:

``` r
library(ggplot2)

my_data <- data.frame(x=1:4, y=5:8, study=paste("Study", 1:2))

my_data_list <- split(my_data, my_data$study)

p <- purrr::imap(
  my_data_list,
  ~ ggplot(.x, aes(x=x, y=y)) +
    geom_point() + 
    labs(title = .y)
)

egg::ggarrange(plots = p)
```

![](https://i.imgur.com/omhQBX4.png)

Created on 2018-09-04 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by billdenney** [comment]
I’d not seen the simplicity of `ggplot_add()` before, thanks for the example!

I understand the desire to keep things separated, but by keeping them separate, it adds more steps to my common process:

I could split the data (step 1) and generate the plot with something like the `ggplot_add()` method (step 2).

Or, I could split the data prior to plotting it (step 1), generate the title prior to plotting (step 2), write a function for generating the plot (step 3), and plot it (step 4).

**Comment by hadley** [comment]
Sorry, I forgot to close this earlier - I didn't mean to give the impression that this is a feature we want to consider in ggplot2. As I said earlier, I don't think the cost of implementing this is worth the reward. @billdenney you have been
