### ISSUE TITLE
properly formatting a two-line caption in ggplot2

### ISSUE THREAD

**Issue by IndrajeetPatil** [tidyverse/ggplot2#2848]
I had raised this issue on StackOverflow (https://stackoverflow.com/questions/51976537/properly-formatting-a-two-line-caption-in-ggplot2) but I've gotten 0 responses there. So I am raising this issue on GitHub instead.

I am writing a custom function where I want to add two-line captions to plots. The basic idea is that I want the caption to be formatted properly no matter what the user might choose to enter. I have created a toy example below where I illustrate two problems with the way I've implemented this function right now-

1. When the caption is not `NULL`, the two lines are not aligned to the right.
2. When an expression is entered, the concatenated caption gets completely mangled.

``` r

# needed libraries
library(ggplot2)

# custom function to prepare a caption
caption_maker <- function(caption) {
  # if caption is not null then add line separator
  if (!is.null(caption)) {
    caption <- paste(caption, "; \n", sep = "")
  }

  # prepare the caption with additional info
  caption <- base::substitute(
    expr =
      paste(y,
            "In favor of null: ",
            "log"["e"],
            "(BF"["01"],
            ") = ",
            bf),
    env = base::list(y = caption,
                     bf = 123)
  )

  # return the message
  return(caption)
}

# custom function to add labels to the plot
plot_maker <-
  function(xlab = NULL,
           ylab = NULL,
           title = NULL,
           caption = NULL) {
    caption.text <- caption_maker(caption = caption)

    plot <- ggplot(mtcars, aes(wt, mpg)) + geom_point() +
      ggplot2::labs(
        x = xlab,
        y = ylab,
        title = title,
        caption = caption.text
      )

    # return the plot
    return(plot)
  }

# this works just fine
plot_maker(caption = NULL)
```

![](https://i.imgur.com/u0Mc1VM.png)

``` r

# this works but the caption is not aligned properly
plot_maker(caption = "This is mtcars dataset")
```

![](https://i.imgur.com/jS6yqXD.png)

``` r

# this works but the caption is all mangled
plot_maker(caption =
             expression(paste(italic("Note"), ": This is mtcars dataset")))
```

![](https://i.imgur.com/MEJqduo.png)

Created on 2018-08-23 by the [reprex package](https://reprex.tidyverse.org) (v0.2.0.9000).

**Comment by ptoche** [comment]
have you experimented with adding a ``\n`` at the position where you want the line break? something like ``caption = "This is the mtcars dataset\nIn favor of blabla" (I'm not on my laptop now, not sure if my comment is relevant).
