### ISSUE TITLE
Feature Request:  Allow geom_text to Follow a Line Segment

### ISSUE THREAD

**Issue by billdenney** [tidyverse/ggplot2#2852]
Currently, `geom_text()` (and `geom_label()`) have an `angle` aesthetic that controls the absolute angle of the text added.  I'm working with data where I want to have the angle of the text align with the angle of a line segment in the data as in the reprex below.

This is straightforward to calculate when the x/y coordinate ratio is known in advance, but it is more complex when the coordinate ratio is not known in advance (e.g. when not forcing the coordinates using one of the `coord_` functions).

What do you think of adding a `slope` aesthetic to `geom_text()` and `geom_label()` that would internally calculate the angle based on `slope` and the coordinate `aspect.ratio`?  It would be an error to specify both `angle` and `slope` to prevent ambiguity.

P.S. I feel like I've been asking a lot in terms of feature requests in the `tidyverse` recently, so if this is of interest, I'll give a shot at a PR.  (I think that the main functions to change would be the `draw_panel` method for `GeomText`, but it's not clear to me where to put the check to confirm that both `angle` and `slope` are not given at the same time.)

``` r
library(ggplot2)
#> Warning: package 'ggplot2' was built under R version 3.4.4
my_data <- data.frame(x = 0:1, y = 0:1)

p <- ggplot(my_data, aes(x = x)) + stat_ecdf() + geom_segment(data = data.frame(x = 0.5, 
  xend = 0.2, y = 0.5, yend = 0.9), mapping = aes(x = x, xend = xend, y = y, 
  yend = yend), arrow = arrow(angle = 25, length = unit(0.3, units = "cm"), 
  ends = "last"), inherit.aes = FALSE) + geom_text(data = data.frame(x = 0.35, 
  y = 0.7, label = "Better"), mapping = aes(x = x, y = y, label = label), 
  hjust = 0.5, vjust = -0.2, angle = -45, inherit.aes = FALSE)
p
```

![](https://i.imgur.com/3oCPMnw.png)

``` r
p + coord_equal(ratio = 3)
```

![](https://i.imgur.com/37IOBJX.png)

**Comment by thomasp85** [comment]
Fwiw a general solution that allows labels to follow a line segment even during resizing of the plot has been implemented in ggraph for edge labels, but it is rather involved and I don’t know whether it is relevant to have in ggplot2

**Comment by hadley** [comment]
This seems out of scope for ggplot2 to me - it will be complex to implement, and people will then naturally want the ability for text to follow a curve.
