### ISSUE TITLE
change bandwidth approach in stat_density2d to match stat_density

### ISSUE THREAD

**Issue by kendonB** [tidyverse/ggplot2#2860]
`stat_density` currently has the `adjust` parameter which defaults to 1 and scales whatever the default bandwidth would be. `stat_density2d` uses `h`, a length-2 vector which is directly passed to the underlying function in the units of the data.

**Comment by hadley** [comment]
I think this is a relatively straightforward fix if you have a little experience with geoms/stats:

* Add `adjust` parameter to `stat_density_2d()` and pass along in `params`. It would default to `c(1, 1)`

* Add `adjust` parameter to `StatDensity2d$compute_group`. It would affect the computation of `h` when it's `NULL`
