### ISSUE TITLE
geom_dotplot() default y axis is wrong 

### ISSUE THREAD

**Issue by justinjunge** [tidyverse/ggplot2#2868]
geom_dotplot() displays a y axis labeled "count" and scaled 0 to 1.  

The y axis currently has no correspondence to the data plotted.   If the range is 0 to 1, then the label should be "frequency" or "relative frequency" or "proportion" AND the height of the stacked dots should scale with ncount.   

A quick temporary fix is to completely remove/suppress the y axis as default.  This is better than defaulting to display a mistake.

**Comment by karawoo** [comment]
This is due to technical limitations and documented in `?geom_dotplot`, unfortunately there is not much else we can do.

> When binning along the x axis and stacking along the y axis, the numbers on y axis are not meaningful, due to technical limitations of ggplot2. You can hide the y axis, as in one of the examples, or manually scale it to match the number of dots.

**Comment by justinjunge** [comment]
@karawoo Thanks for the quick reply!   To be clear, the default y-axis is currently wrong 100% of the time.  It would be better to display nothing on the y-axis than to display the wrong label and scale every time.    

The simple solution here is to change the default to suppress the y-axis label and scale.  If this is not possible, please explain why.   

I understand the difficulties of a full fix that would automatically display the correct y-axis label and scale.  It's not impossible, but it makes sense to postpone addressing this issue until someone more competent than me is able to do it.

**Comment by hadley** [comment]
@justinjunge your comment has come across as rather demanding. There are many demands on ggplot2 and it is necessary for us to prioritise features with a high ratio to reward to cost. Correcting the axis label on a dot plot is not such a feature.

**Comment by justinjunge** [comment]
@hadley I agree with you both that the y axis issue is low priority.  My apologies if the comments came across as demanding.  The intent was to communicate clearly that the issue is not resolved.  Closing the ticket and saying "unfortunately there is not much else we can do" came across as dismissive of a real, if small, problem.  Shouldn't it remain open until the highlighted mistake is removed or fixed sometime in the future?  Thanks for all the work you do to make ggplot so valuable!  I'm a big fan.
