### ISSUE TITLE
geom_line not ignoring NA values

### ISSUE THREAD

**Issue by billdenney** [tidyverse/ggplot2#2877]
The documentation for `geom_line()` indicates that NA values are always ignored (and that the only difference with `na.rm` or not is if ignoring NA comes with a warning.  They don't currently appear to be ignored as the break the lines in the first two figures below.

``` r
library(ggplot2)
d_fake <- data.frame(
  x=1:5,
  y=c(0, NA, 1, NA, 0))

ggplot(d_fake, aes(x=x, y=y)) +
  geom_point() + geom_line() +
  scale_y_log10()
#> Warning: Transformation introduced infinite values in continuous y-axis

#> Warning: Transformation introduced infinite values in continuous y-axis
#> Warning: Removed 2 rows containing missing values (geom_point).
```

![](https://i.imgur.com/LsMEXin.png)

``` r

ggplot(d_fake, aes(x=x, y=y)) +
  geom_point(na.rm=TRUE) + geom_line(na.rm=TRUE) +
  scale_y_log10()
#> Warning: Transformation introduced infinite values in continuous y-axis
#> Warning: Transformation introduced infinite values in continuous y-axis
```

![](https://i.imgur.com/8HzzPef.png)

``` r

ggplot(d_fake[!is.na(d_fake$y),],
       aes(x=x, y=y)) +
  geom_point(na.rm=TRUE) + geom_line(na.rm=TRUE) +
  scale_y_log10()
#> Warning: Transformation introduced infinite values in continuous y-axis

#> Warning: Transformation introduced infinite values in continuous y-axis
```

![](https://i.imgur.com/rfgcvqt.png)

Created on 2018-09-03 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by clauswilke** [comment]
It seems to me the behavior is exactly as documented.
https://github.com/tidyverse/ggplot2/blob/6e545dc4746085d87382a828e45b0f7e58a7578f/R/geom-path.r#L60

**Comment by billdenney** [comment]
The primary documentation doesn't say that, though:

https://github.com/tidyverse/ggplot2/blob/6e545dc4746085d87382a828e45b0f7e58a7578f/man/geom_path.Rd#L61-L62

**Comment by yutannihilation** [comment]
`na.rm` matters only when the `NA`s are in the beginning or the end of the line. 

``` r
library(ggplot2)

d <- data.frame(x = 1:3, y = c(1:2, NA))
ggplot(d) + geom_line(aes(x, y))
#> Warning: Removed 1 rows containing missing values (geom_path).
```

![](https://i.imgur.com/NwrMIoV.png)

``` r
ggplot(d) + geom_line(aes(x, y), na.rm = TRUE)
```

![](https://i.imgur.com/Ugr3amV.png)

Created on 2018-09-04 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

In case that `NA`s are in the middle, there will be no warnings. So, I agree that the sentence "NAs break the line. Use na.rm = T to suppress the warning message" should be fixed.

https://github.com/tidyverse/ggplot2/blob/6e545dc4746085d87382a828e45b0f7e58a7578f/R/geom-path.r#L128-L141

**Comment by yutannihilation** [comment]
Clarification.

> The documentation for `geom_line()` indicates that `NA` values are always ignored

`NA`s are not "ignored"; they always are removed, but sometimes are "considered"; in this case, `NA`s are treated as breaks between lines. You cannot change this behaviour by `na.rm` or other options. So, I consider this issue as a feature request to add a new option that determines whether to let `NA`s break lines or not.

I feel it's natural that one might want this kind of option. But, adding a new option is adding a new complexity, so I'm not sure it should be implemented or not.

Apart form the main point above, this comment seems very confusing, if not incorrect.

> ` # NAs break the line. Use na.rm = T to suppress the warning message `

So, I created #2878 to address this.

**Comment by billdenney** [comment]
For my purposes, either a documentation or a feature change are ok.  I understand the downstream changes that a feature change would bring, so a doc update makes sense to me.

**Comment by yutannihilation** [comment]
Thanks. If you feel #2878 is enough, I'm fine :)

**Comment by billdenney** [comment]
Thank you!
