### ISSUE TITLE
ggplot removing data without warnings

### ISSUE THREAD

**Issue by statsandthings** [tidyverse/ggplot2#2879]
Here's a data frame with dates and some random data.

    library(tidyverse)
    dat <- tibble(
      date = as.Date(40100:40129, origin = "1899-12-30"), 
      rainfall = rnorm(30, 4)
    )

When you plot the data the 30th value is not included on the graph. Once you execute the code notice that there is no bar above the date 2009-11-12. I'd also expect a warning in my console that data was removed from the plot, not sure why I don't get one.

    ggplot(dat, aes(date, rainfall)) + 
      geom_bar(stat = "identity", fill = "white", color = "grey35") + 
      theme_minimal() + 
      theme(axis.title.x = element_blank(), axis.text.x = element_text(angle=90)) + 
      scale_x_date(
        date_breaks = "1 day",
        limits = c(min(dat$date), max(dat$date))
      ) +  
      NULL

**Comment by clauswilke** [comment]
If it is related to #2715 then the warning was added only after 3.0.0 was released.

**Comment by clauswilke** [comment]
Reprex of the original code example. There's a warning in the current development branch.

``` r
library(tidyverse)
#> Warning: package 'dplyr' was built under R version 3.5.1
dat <- tibble(
  date = as.Date(40100:40129, origin = "1899-12-30"), 
  rainfall = rnorm(30, 4)
)

ggplot(dat, aes(date, rainfall)) + 
  geom_bar(stat = "identity") + 
  scale_x_date(
    date_breaks = "1 day",
    limits = c(min(dat$date), max(dat$date))
  )
#> Warning: Removed 2 rows containing missing values (geom_bar).
```

![](https://i.imgur.com/xJ4Fqht.png)

Created on 2018-09-04 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by yutannihilation** [comment]
Ah, thanks! I didn't notice the change...
