### ISSUE TITLE
Tag positioning not working?

### ISSUE THREAD

**Issue by anhttdang** [tidyverse/ggplot2#2882]
Hello,

I used `hjust` and `vjust` for `plot.tag` but it didn't seem to work. Is it an intended behavior? How can I move the tag away from the plot region especially when placing it on the `right`?

Thank you!

``` r

library(dplyr)
library(ggplot2)

mpg <- mpg %>% 
  filter(cyl == 4 | cyl == 8)

p <- ggplot(mpg, aes(displ, cty)) + 
  geom_point() +
  facet_grid(cols = vars(cyl)) +
  labs(tag = 'A)') +
  theme_minimal() +
  theme(plot.caption = element_text(size = 14)) +
  theme(plot.margin = margin(t = 20, r = 20, b = 20, l = 20))

p1 <- p +
  labs(caption = "top") +
  theme(plot.tag.position = 'top')

p2 <- p +
  labs(caption = "top, vjust = 1, hjust = 1") +
  theme(plot.tag.position = 'top',
        plot.tag = element_text(vjust = 1, hjust = 1))

p3 <- p +
  labs(caption = "right") +
  theme(plot.tag.position = 'right')

p4 <- p +
  labs(caption = "right, vjust = 1, hjust = 1") +
  theme(plot.tag.position = 'right',
        plot.tag = element_text(vjust = 1, hjust = 1))

library(patchwork)
(p1 | p2)
```

![](https://i.imgur.com/MPHMMzB.png)

``` r
(p1 | p3) / (p2 | p4)
```

![](https://i.imgur.com/PhGeku0.png)

**Comment by anhttdang** [comment]
@batpigandme thank you for checking! What I meant was that can we move the tag around after we specify its position? For example: moving the tag away or up/down the right border of the plot when use `plot.tag.position`  to make it look better

``` r
library(dplyr)
library(ggplot2)

mpg <- mpg %>% 
  filter(cyl == 4 | cyl == 8)

p <- ggplot(mpg, aes(displ, cty)) + 
  geom_point() +
  facet_grid(cols = vars(cyl)) +
  labs(tag = 'A)') +
  theme_bw() +
  theme(plot.caption = element_text(size = 14)) +
  theme(plot.margin = margin(t = 20, r = 20, b = 20, l = 20))
```

``` r
p3 <- p +
  labs(caption = "right") +
  theme(plot.tag.position = 'right')
p3
```

![](https://i.imgur.com/Olv32iR.png)

**Comment by clauswilke** [comment]
Apparently not. I suspect this is a bug that can be fixed. In the mean time, you can specify the tag position via a two-dimensional numerical vector, just like the legend position, and that should allow you to move the tag anywhere you want.

**Comment by batpigandme** [comment]
Ah! OK. I see what you mean now. 

Yeah, this was something that came up in the PR thread (@clauswilke just beat me to it, as I was finding his old comment):
https://github.com/tidyverse/ggplot2/pull/2405#issuecomment-359144564

**Comment by anhttdang** [comment]
@clauswilke : could you post a working example? I couldn't get it to work for `plot.tag.position = 'right'`. Thank you!

``` r

library(dplyr)
library(ggplot2)

mpg <- mpg %>% 
  filter(cyl == 4 | cyl == 8)

p <- ggplot(mpg, aes(displ, cty)) + 
  geom_point() +
  facet_grid(cols = vars(cyl)) +
  labs(tag = 'A)') +
  theme_bw() +
  theme(plot.caption = element_text(size = 14)) +
  theme(plot.margin = margin(t = 20, r = 20, b = 20, l = 20))

p3 <- p +
  labs(caption = "right") 

p3 + theme(plot.tag.position = c(0.5, 0.5))
```

![](https://i.imgur.com/l52EeLH.png)

``` r
p3 + theme(plot.tag.position = c(1.1, 0.75))
```

![](https://i.imgur.com/ozLkUR8.png)

``` r
p3 + theme(plot.tag.position = c(8, 25))
```

![](https://i.imgur.com/3BV9MS7.png)

**Comment by clauswilke** [comment]
The numbers have to be between 0 and 1, just like for `legend.position`.

**Comment by anhttdang** [comment]
@clauswilke : wouldn't it place the tag inside the facet with the value being from 0 to 1?

**Comment by clauswilke** [comment]
I'm worried that the main point of this issue is getting lost, so I'm showing it here in a minimal reprex:
``` r
library(ggplot2)

p <- ggplot() + labs(tag = "A") +
  theme(plot.tag.position = "right")

# vjust setting cannot be used to move the
# label vertically by a meaningful amount
p + theme(plot.tag = element_text(vjust = 0))
```

![](https://i.imgur.com/4Yg1mst.png)

``` r
p + theme(plot.tag = element_text(vjust = 1))
```

![](https://i.imgur.com/k0AhJNX.png)

Created on 2018-09-06 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

Similar problems exist for tags at the top or bottom of a plot and the `hjust` parameter.

**Comment by anhttdang** [comment]
Is there any update on this issue? Thank you!

**Comment by thomasp85** [comment]
you can use the margin argument in `element_text()` for this:

```r
p3 <- p +
  labs(caption = "right") +
  theme(
    plot.tag.position = 'right', 
    plot.tag = element_text(margin = margin(l = 12))
  )
```
