### ISSUE TITLE
Feature request: Argument 'drop' for stat_count() and other similar functions

### ISSUE THREAD

**Issue by hzarkoob** [tidyverse/ggplot2#2884]
I suggest to add the argument _drop_ (currently available in the stat_*_discrete functions) also to stat_count() and other similar functions such as stat_summary(), geom_bar(), etc. This helps to provide an option to keep the unused factor levels.

Below please find a simplified example:

```r
myLetters = factor(c("A", "A", "B", "C"), levels = LETTERS)
data1 = data.frame(myLetters)
```

Here, `data1` is a simple data frame that contains a selected set of English letters. The goal is to plot the count of **all 26 English letters** in the above vector.  One natural approach to try is:

```r
ggplot(data1, aes(x = myLetters)) + stat_count() 
```

The output will be:
![image](https://user-images.githubusercontent.com/7562230/45192757-29bf9b80-b1ff-11e8-8ab9-4865e09e4681.png)

But, as mentioned above, I expect to see zero count for all English letters that are not available in the above list. 

I understand that this can be achieved using the following code:
```r
data2 = data.frame(table(myLetters))
ggplot(data2, aes(x = myLetters, y = Freq)) + geom_col() 
```

which results in the (desired) output:
![image](https://user-images.githubusercontent.com/7562230/45192827-8c189c00-b1ff-11e8-9f11-038b2c224dde.png)

But please note that the above alternative approach is easy to implement for the above simplified example. In more complex settings, the argument _drop_ seems to be necessary and the natural solution for this problem.

Also please note that this feature request applies to a variety of other functions such as stat_summary(), geom_bar(), etc.

Thank you for your attention.

**Comment by hadley** [comment]
It's a scale option:

```R
ggplot(data1, aes(x = myLetters)) + 
  stat_count() + 
  scale_x_discrete(drop = FALSE)
```

**Comment by hzarkoob** [comment]
Thank you for your response. I think I was confused when posing the above question, but still there is a point to be made here. To help illustrate this, let me use the geom `point` in the above example using the `scale_x_discrete(drop = FALSE)` addition that you suggested:

``` r
ggplot(data1, aes(x = myLetters)) + 
stat_count(geom = "point") +
scale_x_discrete(drop = FALSE)
```
The result would be:
![image](https://user-images.githubusercontent.com/7562230/45236476-cbdb9400-b290-11e8-8023-5c3c4255f5f4.png)

However, the desired output is:
![image](https://user-images.githubusercontent.com/7562230/45236521-e7469f00-b290-11e8-90f1-c85d5d721d98.png)

which explicitly shows zero for letters with a zero count.

I think it more has to do with how the function `length` is applied to unused factor levels; whether it returns NA or 0. If this sounds fine with you, I am going to open a new feature request that specifically asks for the `length' function and the stat `count` to return 0 for the unused factor levels.

**Comment by hzarkoob** [comment]
@yutannihilation Thank you for your comment. But I am not convinced that it is an impossible thing. Below please find more details. 

First, please note that the 2d version of stat_summary(), i.e., [stat_summary_2d()](https://ggplot2.tidyverse.org/reference/stat_summary_2d.html), already has a drop argument whose function is to control the code behavior when the function output is NA. Let's for a second assume that a similar argument is added to the stat_summary() too.

With that said, I think all what we need to do to resolve the issue is to give the unused factor levels in aes `x` a chance to go through the function in stat_summary(). If they result in NA, which in many cases they probably do, then nothing should be depicted for them. However, if in some cases they result in a non-NA value, like in the case of `length` function where the result is 0, then there shouldn't be any reason for not returning a visualization/geometry for them.

Having that said, I understand that this is probably not a very high priority issue given that there are some straightforward ways to go around it. But I think it still should be considered as an action-item in the ggplot roadmap that helps to streamline manipulation of unused factor levels as well as behavior of stat_summary() when the function output is NA.
