### ISSUE TITLE
How to automatically adjust the width of each facet for facet_wrap?

### ISSUE THREAD

**Issue by YinLiLin** [tidyverse/ggplot2#2891]
Hi! Dear managers,

I want to plot a boxplot using ggplot2, and i have more than one facet, each facet has different terms, as  follows:
![p](https://user-images.githubusercontent.com/12557293/45555183-a5a68d00-b86a-11e8-8b95-f68a1bcff3b6.png)
as showed, the width of box in different facet is not the same, is there any way to adjust all the box at a same scale?

Thanks

**Comment by hadley** [comment]
This sort of question is a better fit for <https://community.rstudio.com>. Do you mind asking it over there? (You might want to read <https://www.tidyverse.org/help/> first to maximise your chances of getting a good answer)

(Hint: run the `facet_grid()` examples)
