### ISSUE TITLE
Dots get cut off when I set axes' origins to zero in scatterplots

### ISSUE THREAD

**Issue by chrismp** [tidyverse/ggplot2#2892]
When I set the X and Y axes origins to 0 on a scatterplot, dots on the edges of the chart get cut off. 

```r
ggplot(
    data = cars,
    aes(
      x = speed,
      y = dist
    )
  ) +
  geom_point(
    size = 3
  ) +
  scale_x_continuous(
    breaks = seq(
      from = 0,
      to = max(cars$speed),
      by = 5
    )
  ) + 
  scale_y_continuous(
    breaks = seq(
      from = 0,
      to = max(cars$dist),
      by = 5
    ),
    expand = c(0,0)
  )
```

The code above produces this in RStudio viewer

![rplot](https://user-images.githubusercontent.com/7936571/45603012-6ce6ef00-b9f5-11e8-9c6d-c750f4230977.png)

How do I set my chart's origin to zero but still see every dot in full?

**Comment by ptoche** [comment]
This is not an issue at this stage. Please discuss on https://community.rstudio.com/ or 
https://stackoverflow.com/ first. Also, clarify what you expect to see. What's wrong with simply removing ``expand = c(0,0)``?

See: https://stackoverflow.com/questions/44170871/how-does-ggplot-scale-continuous-expand-argument-work

**Comment by batpigandme** [comment]
To close the loop on this, here's the example from above without `expand`
``` r
library(tidyverse)

ggplot(
  data = cars,
  aes(
    x = speed,
    y = dist
  )
) +
  geom_point(
    size = 3
  ) +
  scale_x_continuous(
    breaks = seq(
      from = 0,
      to = max(cars$speed),
      by = 5
    )
  ) +
  scale_y_continuous(
    breaks = seq(
      from = 0,
      to = max(cars$dist),
      by = 5
    ),
  )
```
![](https://i.imgur.com/oWxjLgv.png)
<sup>Created on 2018-09-17 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

**Comment by smouksassi** [comment]
``` r
require(ggplot2)
#> Loading required package: ggplot2
ggplot(
  data = cars,
  aes(
    x = speed,
    y = dist
  )
) +
  geom_point(
    size = 3
  ) +
  scale_x_continuous(
    breaks = seq(
      from = 0,
      to = max(cars$speed),
      by = 5
    )
  ) + 
  scale_y_continuous(
    breaks = seq(
      from = 0,
      to = max(cars$dist),
      by = 5
    ),
    expand = c(0,0)
  )+
  coord_cartesian(clip="off")
```

![](https://i.imgur.com/Kn2Gk8n.png)

Created on 2018-09-17 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).
