### ISSUE TITLE
geom_boxplot with stat="identity" cannot recognize width parameter

### ISSUE THREAD

**Issue by artidata** [tidyverse/ggplot2#2893]
These 2 plots should be the same:
```r
set.seed(240193)
df1 <- data.frame(person=rep(c("a","b"),each = 10),
                  score=c(rnorm(10,8,1),rnorm(10,6,1.5)))

ggplot(df1)+
  geom_boxplot(aes(x=person,y=score),width=0.1)
```
![image](https://user-images.githubusercontent.com/20266094/45624832-fd890200-babd-11e8-9792-739be3f5479e.png)

```r
df2 <- cbind(person = c("a","b"),
             as.data.frame(matrix(c(boxplot.stats(df1[1:10,2])$stats,
                                    boxplot.stats(df1[11:20,2])$stats),nrow=2,byrow=T)))

ggplot(df2)+
  geom_boxplot(aes(x = person,
                   ymin = V1,
                   lower = V2,
                   middle = V3,
                   upper = V4, 
                   ymax = V5),
               stat= "identity",width=0.1)
```
![image](https://user-images.githubusercontent.com/20266094/45624773-ddf1d980-babd-11e8-98f7-5b6c8f8ddd12.png)

Instead I got this message = "Warning: Ignoring unknown parameters: width"

**Comment by tjebo** [comment]
Curiously, I found the same issue yesterday just a few hours later... https://stackoverflow.com/questions/52376663/width-parameter-and-stat-identity-in-geom-boxplot?noredirect=1&lq=1 
Maurits Evers (@mevers ?) has found that the width changes 'correctly', but with warning, when putting the width parameter into the aes-call

**Comment by clauswilke** [comment]
Yes, `geom_boxplot()` is not properly declaring the `width` parameter. I just made a PR.

``` r
library(ggplot2)
set.seed(240193)
df1 <- data.frame(
  person = rep(c("a", "b"), each = 10),
  score = c(rnorm(10, 8, 1), rnorm(10, 6, 1.5))
)

ggplot(df1) +
  geom_boxplot(aes(x = person, y = score), width = 0.1)
```

![](https://i.imgur.com/1kFB0Ex.png)

``` r

df2 <- cbind(
  person = c("a", "b"),
  as.data.frame(matrix(c(
    boxplot.stats(df1[1:10, 2])$stats,
    boxplot.stats(df1[11:20, 2])$stats
  ), nrow = 2, byrow = T))
)

ggplot(df2) +
  geom_boxplot(aes(
    x = person,
    ymin = V1,
    lower = V2,
    middle = V3,
    upper = V4,
    ymax = V5
  ),
  stat = "identity", width = 0.1
  )
```

![](https://i.imgur.com/TeoJmPS.png)

Created on 2018-09-18 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).
