### ISSUE TITLE
Allow hms object in breaks argument to scale_*_date

### ISSUE THREAD

**Issue by thomasp85** [tidyverse/ggplot2#2894]
This came out of our talks about how to specify breaks in sec_axis() for date/datetime scales and what to do with the date_breaks argument... Couldn't a simple solution be to allow `hms` objects as break specifications in both `scale_*_[date|datetime]()` and `sec_axis()`

eg.

```r
last_month <- Sys.Date() - 0:29
df <- data.frame(
  date = last_month,
  price = runif(30)
)
base <- ggplot(df, aes(date, price)) +
  geom_line() + 
  scale_x_date(breaks = hms(days = 7))
```

just a thought...

**Comment by ptoche** [comment]
This would be great. I was looking for a good way to handle time durations (as opposed to dates), expressed in units of days/hours/minutes/seconds, and wasn't sure what the best approach was. I ended up with something like the following. Anything easier would be very welcome. 

    library(hms)  # as.hms()
    df <- data.frame(x = 1:30,
                     duration = as.hms(as.difftime(50*round(60*60*runif(30),0), units = "secs")))
    library(ggplot2)
    ggplot(df, aes(x = x, y = duration)) +
        geom_point() +
        scale_y_time(breaks = hms(seq(0, 30, 1)*60*60*24-8*60*60),
                     labels = function(x) strftime(x, "%d:%H"))

Probably not optimal even in the current implementation...

**Comment by hadley** [comment]
I don't think this is the right approach because `hms` produces a duration (measured in seconds), when you really want a period. With hms there's no way to produce a break that occurs once a month, and even `hms::days(1)` is dangerous during the switch to daylight savings time.
