### ISSUE TITLE
Error using theme_bw() with parameters depending on base_size

### ISSUE THREAD

**Issue by lhunsicker** [tidyverse/ggplot2#2897]
I get an error using theme_bw() whenever I insert a base_line_size or base_rect_size that uses the calculation based on base_line_size. E.g.,

> test10 <- theme_bw(base_line_size = base_size/11)

The error is:

> Error in structure(list(colour = colour, size = size, linetype = linetype, :
> object 'base_size' not found

This error occurs not only with theme_bw, but with all the other themes I tested.

To get a reproducible error, I ran the simple command:

> test10 <- theme_bw(base_line_size = base_size/11)

This command gives the above error whenever I insert a parameter that depends on base_size. It gives no error if I insert a base_line_size = 0.5. Debugging theme_bw suggests to me that the problem is due to a data_frame problem, but I am not good enough to fix it. The simple work around is, if you have to set base_line_size or base_rect_size, to use an absolute number and not the calculation based on base_size.
Larry Hunsicker

**Comment by clauswilke** [comment]
This is a basic misunderstanding of how R works. If you want to use a variable `base_size` in a function call, you need to define it first.

``` r
library(ggplot2)
test10 <- theme_bw(base_line_size = base_size/11)
#> Error in structure(list(colour = colour, size = size, linetype = linetype, : object 'base_size' not found

base_size <- 11
test10 <- theme_bw(base_size = base_size, base_line_size = base_size/11)
```

Created on 2018-09-18 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).
