### ISSUE TITLE
upper case PANEL has unexpected behavior.

### ISSUE THREAD

**Issue by schloerke** [tidyverse/ggplot2#2904]
Originally reported in https://github.com/ggobi/ggally/issues/289 by @sbihorel

When an xvar (idk about yvar) is equal to PANEL, the values do not split as expected.

``` r
library(ggplot2)

gdata <- data.frame(
  age = rnorm(100,40,2),
  sexf = factor(sample(0:1, 100, replace = TRUE)),
  panel = factor(sample(1:3, 100, replace = TRUE)),
  study = factor(sample(1:3, 100, replace = TRUE))
)

# expected
ggplot(gdata, aes(panel, age)) + geom_boxplot()
```

![](https://i.imgur.com/WtzxIF1.png)

``` r

gdata_upper <- gdata
names(gdata_upper) <- toupper(names(gdata_upper))

# NOT expected
ggplot(gdata_upper, aes(PANEL, AGE)) + geom_boxplot()
```

![](https://i.imgur.com/3GItSoA.png)

> Created on 2018-09-20 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by clauswilke** [comment]
The cause of the bug is that ggplot2 uses an internal variable named `PANEL` and that variable is added to the input data *before* aesthetic mappings are evaluated:
https://github.com/tidyverse/ggplot2/blob/daddf74fb2550376f18ce92f338f62b85ca39cb9/R/plot-build.r#L42-L48

Not sure there is an easy fix.

**Comment by ptoche** [comment]
renaming ``PANEL`` to some unlikely name? like ``PaNeL`` or ``PANEL.INTERNAL`` ?

**Comment by clauswilke** [comment]
I think a better approach would be to keep it out of the data frame initially and instead hand it to `compute_aesthetics()` as a separate argument. In either case, this is a tricky modification with all sorts of implications for downstream packages.

**Comment by ptoche** [comment]
You're right, that was a bad suggestion.

**Comment by hadley** [comment]
This is a known issue, and can not be easily resolved. Just don't call your variables `PANEL`.

@smouksassi I think that sort of code is a terribly bad idea. It's much better to do complex data manipulation outside of ggplot2.
