### ISSUE TITLE
Datetime scales should accept oob argument

### ISSUE THREAD

**Issue by yutannihilation** [tidyverse/ggplot2#2906]
Since datetime scales are basically continuous scales, I feel they should allow users to specify `oob`. I don't see the reason they shouldn't accept `oob` (Sorry if I'm missing something).

`oob` may be useful when we want to prevent Geoms from being removed. Here's an example:

``` r
library(ggplot2)

set.seed(10)
df <- data.frame(x = rep(Sys.Date() + 0:9, each = 10), y = runif(100))

p <- ggplot(df, aes(x, y, group = x)) +
  geom_boxplot()

p + scale_x_date(limits = range(df$x[1:40]))
#> Warning: Removed 60 rows containing missing values (stat_boxplot).
#> Warning: Removed 1 rows containing missing values (geom_segment).

#> Warning: Removed 1 rows containing missing values (geom_segment).
```

![](https://i.imgur.com/B0am3U3.png)

``` r

p + scale_x_date(limits = range(df$x[1:40]), oob = scales::squish)
#> Error in scale_x_date(limits = range(df$x[1:40]), oob = scales::squish): unused argument (oob = scales::squish)
```

<sup>Created on 2018-09-21 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by thomasp85** [comment]
wouldn't you simply set the limits in the coord instead to avoid removing anything?

**Comment by yutannihilation** [comment]
Aw, thanks. I thought `oob` would fix the problem, but it seems it doesn't help much, sorry.

``` r
library(ggplot2)

set.seed(10)
df <- data.frame(x = rep(Sys.Date() + 0:9, each = 10), y = runif(100))

df2 <- dplyr::mutate(df, x = as.integer(x))

ggplot(df2, aes(x, y, group = x)) +
  geom_boxplot() +
  scale_x_continuous(limits = range(df2$x[1:40]), oob = scales::squish)
```

![](https://i.imgur.com/QnvINOz.png)

<sup>Created on 2019-04-13 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>
