### ISSUE TITLE
Allow flipping panel.grid theme elements with coord_flip()

### ISSUE THREAD

**Issue by mikmart** [tidyverse/ggplot2#2908]
Currently it's difficult to create a custom theme that has gridlines only along the primary baseline axis. This is mostly an issue with horizontal bar charts, where you would only want to have vertical gridlines (vs. almost any other plot where you'd only have horizontal gridlines):

``` r
library(ggplot2)

theme_set(theme_bw() + theme(
  panel.grid.minor = element_blank(),
  panel.grid.major.x = element_blank()
))

ggplot(mpg, aes(cut_interval(cty, 5))) + geom_bar()
```

![](https://i.imgur.com/Z0xh6OR.png)

``` r
ggplot(mpg, aes(class)) + geom_bar() + coord_flip()
```

![](https://i.imgur.com/JPVyBei.png)

To match the theme of the first plot, a workaround requires a theme adjustment to exchange `panel.grid.major.x` and `panel.grid.major.y`.

``` r
ggplot(mpg, aes(class)) +
  geom_bar() +
  coord_flip() +
  theme(
    panel.grid.major.y = element_blank(),
    panel.grid.major.x = calc_element("panel.grid.major.y", theme_get())
  )
```

![](https://i.imgur.com/gV9W8ns.png)

The other coordinate system that changes axis positions (`coord_polar()`) already behaves such that the `panel.grid` elements are applied to the matching aesthetic mappings (i.e. `panel.grid.major.x` always controls gridlines for the variable mapped to the `x` aesthetic). Applying the same logic to `coord_flip()` would fix the above theming issue.

Would this change be feasible? It seems like a simple change, but could break some plot code that's been written around this behaviour. Alternatively there could be an option in `coord_flip()` to control this behaviour, defaulting to the current behaviour for backwards compatibility.

Created on 2018-09-24 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0.9000).

**Comment by ptoche** [comment]
If I understand correctly, the theme elements are associated with x and y axes relative to an absolute reference, while the scales are in relative reference, which is inconsistent. To put it in words, if you set an x theme and flip, the theme now gets applied to the current x axis (formerly known as y), but if you set an x scale and flip, the scale gets applied to the current y axis (formerly known as x). I noticed this a while back. It's an oddity, but easy to work around. This can be seen by playing around with:

    library(ggplot2)
    theme_set(theme_bw() + theme(
        panel.grid.major.x = element_line(color="red"),
        panel.grid.major.y = element_line(color="blue")
    ))
    ggplot(mpg, aes(cut_interval(cty, 5))) + geom_bar() + scale_x_discrete(breaks=NULL) -> p

    p
    p + coord_flip()

The blue lines are always horizontal and the red lines always vertical (absolute y and x). Setting ``breaks`` to ``NULL`` in the scale removes the blue, horizontal lines or red, vertical lines, depending on whether ``coord_flip()`` is turned on or off.

**Comment by mikmart** [comment]
@ptoche yeah, I'm proposing to change that; or at least to add an option to `coord_flip()` for controlling the behaviour.

This only makes a difference when you have an asymmetric panel grid with respect to the coordinate axes and then flip them; and, at least in my use cases, I almost always want to also flip the panel grid with the coordinates.

**Comment by mikmart** [comment]
Here's also a reprex demonstrating the asymmetry in behaviour between `coord_flip()` and `coord_polar()` (as changing the axis to map to angle is basically equivalent to a coordinate flip):

``` r
library(ggplot2)

theme_set(theme_linedraw() + theme(
  panel.grid.minor = element_blank(),
  panel.grid.major.x = element_line(colour = "red"),
  panel.grid.major.y = element_line(colour = "blue")
))

bar <- ggplot(mtcars, aes(am, fill = factor(cyl))) +
  geom_bar(width = 1, position = "fill", alpha = 0.5) +
  scale_fill_grey()

plots <- list(
  bar,
  bar + coord_flip(),
  bar + coord_polar(theta = "x"),
  bar + coord_polar(theta = "y")
)

cowplot::plot_grid(plotlist = plots)
```

![](https://i.imgur.com/rCmyx69.png)

Created on 2018-09-25 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0.9000).

**Comment by ptoche** [comment]
Or perhaps add a new ``axes_flip()`` function that flips the themes and scales as well as the coordinates. If we take the meaning of ``coord_flip()`` as "flip coordinates", that is all it should do. That is, ``coord_flip()`` should stop flipping axes scales while ``axes_flip()`` should flip all of coordinates, axes scales and axes themes.

**Comment by ptoche** [comment]
Also: Leaving ``coord_flip()`` as is and introducing a new ``axes_flip()`` would not break anything.

**Comment by clauswilke** [comment]
Flipping the theme elements in the coord would be possible. However, I'd be hesitant to make it the default, since tons of existing code depends on the current implementation. So it'd have to be an optional parameter. But then, why not simply define appropriate themes for horizontal and vertical grids? That's what I have done for my dataviz book, and it works great.

The themes are in the development version of cowplot and will be released eventually: https://github.com/wilkelab/cowplot/blob/374c3e9bffb45fe39c753633af6b606d868b38cb/R/themes.R#L219
https://github.com/wilkelab/cowplot/blob/374c3e9bffb45fe39c753633af6b606d868b38cb/R/themes.R#L239

**Comment by mikmart** [comment]
Yeah I agree that for the sake of compatibility it would need to be optional. Having separate horizontal/vertical themes definitely works, but I can quickly think of at least 3 downsides/inconveniences:

1. When applying `coord_flip()`, have to remember to update the theme, too: so have to update code in at least 2 places. (Worse if you've `theme_set()` a modified version of the theme.)
2. Have to maintain 2 versions of a theme: goes against DRY. (Arguably trivial as one could be defined solely in terms of the other.)
3. Can't directly reuse existing themes with asymmetric grid layouts (e.g. **ggthemes** has a few).

From a personal perspective, separate themes also just doesn't *feel* quite as nice (obv. heavily personal preference); and the discrepancy with `coord_polar()` is not great.

**Comment by hadley** [comment]
I think this is a sufficiently large amount of work for a relatively small gain, that we are unlikely to ever implement it, and so I am closing the issue in recognition of that fact.

You could also use `ggstance::geom_barh()` to avoid the flipping.
