### ISSUE TITLE
Move ggplot2 pkgdown site to this repo form ggplot2_docs

### ISSUE THREAD

**Issue by batpigandme** [tidyverse/ggplot2#2909]
Since it's a minor release, but will probably have a site rebuild https://github.com/tidyverse/ggplot2/issues/2890, thought this might be a good moment to nudge the movement of the ggplot2 site to be built from this repo, rather than https://github.com/tidyverse/ggplot2-docs.

LMK if I can help with this at all, @hadley, though I'm not sure I have the necessary permissions. 😬

**Comment by hadley** [comment]
This is on my todo list, but keep pinging me about it.
