### ISSUE TITLE
Error in re-installing ggplot2

### ISSUE THREAD

**Issue by JessicaGarzke** [tidyverse/ggplot2#2910]
Hello,
After updating all my R packages, my ggplot2 was gone. I tried to re-install ggplot2 but run into issues. I re-installed lazyeval as this was recommended in some other issues, but this doesn't fix my installation problem.

The output is as follows:
> install.packages("ggplot2")

  There is a binary version available but the source version is
  later:
        binary source needs_compilation
ggplot2  2.2.1  3.0.0             FALSE

installing the source package ‘ggplot2’

trying URL 'https://cran.rstudio.com/src/contrib/ggplot2_3.0.0.tar.gz'
Content type 'application/x-gzip' length 2847050 bytes (2.7 MB)
==================================================
downloaded 2.7 MB

Warning in strptime(xx, f <- "%Y-%m-%d %H:%M:%OS", tz = tz) :
  unknown timezone 'zone/tz/2018e.1.0/zoneinfo/America/Vancouver'
* installing *source* package ‘ggplot2’ ...
** package ‘ggplot2’ successfully unpacked and MD5 sums checked
** R
** data
*** moving datasets to lazyload DB
** inst
** preparing package for lazy loading
Error : object ‘enexprs’ is not exported by 'namespace:rlang'
ERROR: lazy loading failed for package ‘ggplot2’
* removing ‘/Library/Frameworks/R.framework/Versions/3.3/Resources/library/ggplot2’
Warning in install.packages :
  installation of package ‘ggplot2’ had non-zero exit status

The downloaded source packages are in
	‘/private/var/folders/w4/tx4xr0cs1b120fgjl5hnb3340000gn/T/Rtmp6N0hPd/downloaded_packages’

I also recognized that the strptime warning occurred several times during the package updating process.

**Comment by batpigandme** [comment]
This sort of question is a better fit for https://community.rstudio.com. Do you mind asking it over there? (You might want to read https://www.tidyverse.org/help/ first to maximise your chances of getting a good answer.)
