### ISSUE TITLE
ggsave missing edges with some shapes in svg format

### ISSUE THREAD

**Issue by andrewmarx** [tidyverse/ggplot2#2915]
I'm trying to save some plots in the svg format, but edges are not being outputted for some symbols in the svg file. They show up fine in the plot pane, png image, and pdf vector image (I generally prefer pdf images, but need svg for Rmarkdown compatibility). 

Potentially useful info:
- Completely removed R and associated packages and did a fresh install of 3.4.4. 
- Tried it with the svglite package both installed and completely removed
- Ubuntu based operating system (16.04LTS)
- Attached plots (in zip file because svg files cannot be attached)

``` r
library("ggplot2")

dat <- data.frame(x = c(1,2,3),
                  y = c(1,2,3),
                  grp = c("a", "b", "c"))

ggplot(dat) +
  geom_point(aes(x = x, y = y, fill = grp, shape = grp)) +
  scale_shape_manual(values = c(21,22,23)) # Also happens for shapes 24 and 25
```

![](https://i.imgur.com/X7dxtmN.png)

``` r

ggsave("plot.png")
#> Saving 7 x 5 in image
ggsave("plot.svg")
#> Saving 7 x 5 in image
ggsave("plot.pdf")
#> Saving 7 x 5 in image
```

[plots.zip](https://github.com/tidyverse/ggplot2/files/2428522/plots.zip)

<sup>Created on 2018-09-28 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by hadley** [comment]
Is this the problem you see?

<img width="33" alt="screen shot 2018-09-28 at 10 32 08 am" src="https://user-images.githubusercontent.com/4196/46218244-c3afcb00-c309-11e8-934c-16f4d1ec670a.png">

**Comment by andrewmarx** [comment]
Yes it is

**Comment by hadley** [comment]
Can you please file an issue on the svglite repo instead? If you have time, a reprex that only uses `plot()` instead of ggplot2, would be much appreciated.

**Comment by andrewmarx** [comment]
Opened issue in the svglite repo: [](https://github.com/r-lib/svglite/issues/92)
