### ISSUE TITLE
Error in grid.newpage(): could not open file 'Rplot001.png'

### ISSUE THREAD

**Issue by amhedberg** [tidyverse/ggplot2#2917]
Error in grid.newpage(): could not open file 'Rplot001.png'
Topic 7 days ago in Kaggle Forum
0 responses

I am getting this error message: 
ERROR while rich displaying an object: Error in grid.newpage(): could not open file 'Rplot001.png' 
when running this [Kernel](https://www.kaggle.com/amhedberg/ny-biodiversity) on Kaggle. The same code runs fine when I run it in RStudio on my laptop. I have run ggplot2 successfully before on Kaggle. Any suggestions? Thanks.

[Link](https://www.kaggle.com/amhedberg/discussion) to the same issue as documented on Kaggle.

**Comment by batpigandme** [comment]
This sort of question is a better fit for https://community.rstudio.com. Do you mind asking it over there? (You might want to read https://www.tidyverse.org/help/ first to maximise your chances of getting a good answer.)
