### ISSUE TITLE
Enhancement: drop=FALSE should result in inclusion of unused factor levels in BOTH compution and visualization aspects of the analysis.

### ISSUE THREAD

**Issue by hzarkoob** [tidyverse/ggplot2#2918]
Suppose someone is interested in including unused factor levels (in a discrete x aes) in the analysis, and thus, she sets drop = FALSE in the scale_x_discrete(). This helps to **visually** include the unused factor levels in the graphs, but it seems that those factors will never be used for any type of computation. If a user shows interest in including unused factor levels in the analysis, then she is probably interested to see their effects in all aspects of the analysis, both computation and visualization aspects.

Here is an example,

```r
myLetters = factor(c("A", "A", "B", "C"), levels = LETTERS)
data1 = data.frame(myLetters)

ggplot(data1, aes(x = myLetters)) + 
stat_count(geom = "point") +
scale_x_discrete(drop = FALSE)
```
The resulting output is:
![image](https://user-images.githubusercontent.com/7562230/46241284-33a26d80-c36b-11e8-9a1e-a1b4ce66b3ee.png)

But the desired output is:

![image](https://user-images.githubusercontent.com/7562230/46241289-3dc46c00-c36b-11e8-9529-c17f009db4f7.png)

which explicitly shows 0 as the output of the length() function applied to the unused factor levels.

PS. As the title suggests it is just an enhancement and is not a must-have feature.

Thank you for looking into this!

**Comment by thomasp85** [comment]
This may be better suited for the vizdat package as it deals specifically with visualising "missing-ness"
