### ISSUE TITLE
Allow user to use colour and fill in stat_smooth formula

### ISSUE THREAD

**Issue by Bisaloo** [tidyverse/ggplot2#2928]
Currently, it is not possible to use colour or fill in `stat_smooth` `formula`. I'd like to request this feature. It would allow users to specify more complex formula, and in particular remove the interaction and get the same slope for all groups, as seems often requested:

https://stackoverflow.com/q/36459967

https://stackoverflow.com/q/4251294

https://stackoverflow.com/q/49191606

https://stackoverflow.com/q/23722905

https://stackoverflow.com/q/44703546

https://stackoverflow.com/q/31903606

```r
library(tidyverse)

data(diamonds)

diamonds %>%
  filter(color == "G") %>%
  ggplot(aes(x = carat, y = price, col = cut)) +
    geom_point() +
    geom_smooth(method = "glm", formula = y ~ x + colour)
```

I tried to have a look to propose a PR myself but I quickly got lost as I am not familiar at all with the codebase and tidy eval.

**Comment by hadley** [comment]
Unfortunately, I think this is a fundamentally bad idea — as soon as you get to this level of modelling complexity, you need to do it outside of ggplot2.
