### ISSUE TITLE
Feature Request: Warning message and support for non-uniform tile sizes in geom_raster

### ISSUE THREAD

**Issue by baderstine** [tidyverse/ggplot2#2932]
Feature Request:
(a) add warning in geom_raster() when tiles are NOT all the same size
(b) handle irregularly sized tiles better in geom_raster()

a) sometimes you think that your data are all regularly gridded and then you run geom_raster() and rows appear to be missing from your raster.  In this case, a warning message would be a super helpful alert to the user that they've violated one of the underlying assumptions of geom_raster.

Either in geom-raster.R -> GeomRaster() or in utilities-resolution.R -> resolution(), run a quick check:

```r
if( length( unique( diff( unique(data$x) ) ) ) != 1 ) 
  warning("tiles not all of uniform size in x dimension") 

if( length( unique( diff( unique(data$y) ) ) ) != 1 ) 
  warning("tiles not all of uniform size in y dimension") 

```

b) Special case where entire rows/cols are different height/width.  If there is a way to do this without massively negatively impacting the performance of geom_raster... handle differently sized rows/cols better (e.g., fall back on geom_tile and calculate height/width from the data).  

Pseudo code in GeomRaster(), setup_data() : 

```r

ydiffs <- diff( unique(data$y) )
if( length( unique( ydiffs ) ) != 1 ) {
  warning("tiles not all of uniform size in y dimension") 
  diffvec <- data.frame(y = unique(data$y),
                                       h = c(ydiffs[1], ydiffs))
  h <- diffvec$h[match(data$y, diffvec$y)]
} else {
  h <- resolution(data$y, FALSE)
}

```

**Comment by thomasp85** [comment]
I think it makes sense to throw better errors but not to make geom_raster handle bad input data...

An error directing the user at geom_tile should be enough
