### ISSUE TITLE
Add `space` argument to facet_wrap? 

### ISSUE THREAD

**Issue by mkoohafkan** [tidyverse/ggplot2#2933]
`facet_grid` provides the argument `space` which allows facets to be sized proportionally to their data range. e.g.:
```
ggplot(mtcars) + aes(x = disp, y = qsec) + geom_point() + 
  facet_grid(am~., scales = "free_y", space = "free_y")
```

However, `facet_wrap` does not have the `space` argument, so it is not possible to do e.g.

```
ggplot(mtcars) + aes(x = disp, y = qsec) + geom_point() + 
  facet_wrap(~am, ncol = 1, scales = "free_y", space = "free_y")
```
which would be identical to the first plot but with the facet labels **above** the facets, rather than on the facet sides.

Any chance of bringing the `space` argument to `facet_wrap`? 

Alternatively, I wonder if there is a place for something like `facet_row` and `facet_col`. These functions could operate like `facet_grid` but provide simple facet label placement thanks to the single row/column constraint.

**Comment by baptiste** [comment]
free space would make sense with facet_row/col I think, but not so much with facet_wrap (unclear what the layout should be, with more than one row/col)

**Comment by mkoohafkan** [comment]
I agree, I can't think of a good way to implement the `space` argument in `facet_wrap` in cases where you have multiple rows and columns, unless the only possible argument values were `"free_x"` or `"free_y"` (but not just `"free"`) and the `space` got defined based on the largest panel in the entire row or column. But then there are issues with how it will work with the `scales` argument and at that point we're basically  implementing `facet_grid` all over again.

90% of the time I use `facet_wrap` I set `nrow` or `ncol` as 1, so `facet_row` or `facet_col`  would be convenient shorthand anyway.

**Comment by ilarischeinin** [comment]
I second the wish for a `facet_col()`.

Or well, what I would like is the ability to combine facet labels on the top with `space = "free_y"`, for a one-column layout, regardless of whether the implementation was by introducing a `facet_col()` or by modifying either `facet_grid()` or `facet_wrap()`.

**Comment by thomasp85** [comment]
Is there any reason for not using `facet_grid(. ~ <some_var>)` for these cases? it gives you all you want...

**Comment by ilarischeinin** [comment]
Maybe I am misunderstanding something, but that gives a a one-row layout, not one-column? Below is a reprex showing first the two plots from the original post, and this as the third.

``` r
library(ggplot2)
p <- ggplot(mtcars) + aes(x = disp, y = qsec) + geom_point()

# Issue: labels not on top, but on the side:
p + facet_grid(am ~ ., scales = "free_y", space = "free_y")
```

![](https://i.imgur.com/gvaMalf.png)

``` r

# Issue: panel size not proportional (no parameter space = "free_y"):
p + facet_wrap(~ am, ncol = 1, scales = "free_y")
```

![](https://i.imgur.com/1RUzu7n.png)

``` r

# Issue: layout is one-row, not one-column.
p + facet_grid(. ~ am, scales = "free_y", space = "free_y")
```

![](https://i.imgur.com/ECHGtZA.png)

<sup>Created on 2019-01-09 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by ilarischeinin** [comment]
The proportional panel sizes for the first plot above is maybe not that clear, so here's the same thing with a discrete `y` variable.

What me and @mkoohafkan are after is the first plot, but with the facet labels on top.

``` r
library(tidyverse)

p <-
  mtcars %>%
  rownames_to_column() %>%
  ggplot(aes(x = disp, y = rowname)) + geom_point()

# Issue: labels not on top, but on the side:
p + facet_grid(carb ~ ., scales = "free_y", space = "free_y")
```

![](https://i.imgur.com/kt5u7AE.png)

``` r

# Issue: panel size not proportional (no parameter space = "free_y"):
p + facet_wrap(~ carb, ncol = 1, scales = "free_y")
```

![](https://i.imgur.com/e04Ov8n.png)

``` r

# Issue: layout is one-row, not one-column.
p + facet_grid(. ~ carb, scales = "free_y", space = "free_y")
```

![](https://i.imgur.com/tofgw3l.png)

<sup>Created on 2019-01-09 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by thomasp85** [comment]
Thanks - makes sense... I think it would make sense to change this issue to something like: "Add facet_col/facet_row"

That being said, it may have a better chance at being posted in e.g. [ggforce](https://github.com/thomasp85/ggforce)

**Comment by ilarischeinin** [comment]
Just stating it here for completeness and future reference, that this has now been implemented in `geforce` by @thomasp85 (thanks!):

``` r
library(tidyverse)

p <-
  mtcars %>%
  rownames_to_column() %>%
  ggplot(aes(x = disp, y = rowname)) + geom_point()

p + ggforce::facet_col(vars(carb), scales = "free_y", space = "free")
```

![](https://i.imgur.com/BJWbR5i.png)

<sup>Created on 2019-08-12 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
