### ISSUE TITLE
Trouble with axis-text aligning when y-axis position is on the right

### ISSUE THREAD

**Issue by kimmagnusb** [tidyverse/ggplot2#2937]
I have trouble aligning the y-axis text with tick marks when y-axis is on the right side of the plot, and the text in an angle. The ```hjust``` seem to be ignored (while ```vjust``` works as expected). Seems to work fine when the yaxis is on the normal (left) side. Thanks . 

```r
# library(ggplot2)
varx<-runif(100,1,100)
vary<-runif(100,1,100)
df<-data.frame(varx,vary)

p1 <- ggplot(df,aes(varx, vary)) + 
  geom_point() +
  scale_y_continuous(position="right")+
  theme(axis.text.y = element_text(angle = 270,hjust=0.5))
  
  
p2 <- ggplot(df,aes(varx, vary)) + 
  geom_point() +
  theme(axis.text.y = element_text(angle = 270,hjust=0.5))  

```

**Comment by batpigandme** [comment]
To modify the positioning of text for the y axis when you have `position = "right"`, you need to use `theme(axis.text.y.right = element_text(...))`
``` r
library(ggplot2)
varx <- runif(100, 1, 100)
vary <- runif(100, 1, 100)
df <- data.frame(varx, vary)

ggplot(df, aes(varx, vary)) +
  geom_point() +
  scale_y_continuous(position = "right") +
  theme(axis.text.y.right = element_text(angle = 270, hjust = 0.5))
```

![](https://i.imgur.com/xeQVkM9.png)

<sup>Created on 2018-10-12 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>
