### ISSUE TITLE
using `stat_ydensity` with `geom = "density"`---scaling the density line similar to `geom_violin`

### ISSUE THREAD

**Issue by mkoohafkan** [tidyverse/ggplot2#2947]
I originally posted this on [SO](https://stackoverflow.com/q/52862039/2375551) thinking it was user error, but it seems that perhaps the functionality I'm looking for has not been implemented in `ggplot2`. I am currently using a modified version of `geom_violin` to achieve the plot below, but it seems overkill to maintain a separate geometry that is so close to existing capabilities in `ggplot2`. 

![sideways density plot](https://i.stack.imgur.com/f6GIp.png)

Essentially, I am looking to plot the left or right outline of a `geom_violin`. I presumed that this would be possible using `stat_ydensity` through the argument `geom = 'density` or perhaps `geom = 'path'` but that seems to not be the case, i.e. the following code will not produce the above plot:
```
ggplot(res.plot, aes(x = time, y = x,group = run)) + theme_bw() +
  geom_line(alpha = 0.1) +
  stat_ydensity(aes(group = time), data = res.select, 
    geom = "density", color = "red")
```
![attempt using stat_ydensity](https://i.stack.imgur.com/QH7Kf.png)

I'm guessing that the important difference between how `geom = 'density'` and `geom = 'violin'` are plotted with `stat_ydensity` is that `geom_violin` computes a variable `violinwidth` which is used to scale the violins on the x-axis. I am wondering if something similar could be implemented in `stat_ydensity`/`geom = 'density'` or similar, perhaps by using the argument `width` or some other scaling argument (e.g. a relative width argument `relwidth`).

If it's not feasible to implement this addition, I would like to instead suggest a new argument `sides` for `geom_violin` that allow users to plot either the left, right, or both sides of the violins.

reproducible example datasets:

```
library(tidyr)
library(ggplot2)
library(dplyr)
# markov chain parameters
mu = 8                           # cm/hr
sigma = 4                        # cm/sqrt(hr)
x0 = 3                           # initial condition
tmax = 200                       # end time
deltat = 10                      # time increment (hrs)
reps = 300                       # number of realizations

random_walk = function() 
  c(0, cumsum(mu*deltat + sigma*rnorm(n, sd = deltat))) + x0

# simulate random walks
n = tmax/deltat
res = cbind.data.frame(seq(0,tmax, by = deltat), replicate(reps, random_walk()))
names(res) = c("time", paste("run", seq(1, ncol(res) - 1)))
# format the data for plotting
res.plot = gather(res, run, x, -time)
# extract specific times to compute marginal densities
res.select = filter(res.plot, time %in% c(50, 150))
```

**Comment by thomasp85** [comment]
You may have luck with the ggridges package... @clauswilke is this something that is possible?

**Comment by clauswilke** [comment]
Not sure it can be done right now, but I agree ggridges is the right place. @mkoohafkan, please file an issue there. https://github.com/clauswilke/ggridges And please use the reprex package to produce your reproducible example. Thanks!
