### ISSUE TITLE
Deprecated wiki still looks active and is attracting Google hits

### ISSUE THREAD

**Issue by jdrum00** [tidyverse/ggplot2#2951]
Followup to [tidyverse/ggplot2#2396](https://github.com/tidyverse/ggplot2/issues/2396); here are the most relevant comments.

[tidyverse/ggplot2#2396 (comment)](https://github.com/tidyverse/ggplot2/issues/2396#issuecomment-357103469)
[tidyverse/ggplot2#2396 (comment)](https://github.com/tidyverse/ggplot2/issues/2396#issuecomment-358417494)

I Googled straight in to the page in question, and I'm afraid it wasn't clear to me at all that the wiki was being retired. I don't see any notation anywhere that it's not current. Tried the second example, got the error, was about to report it, and found the existing issue. See full-page screenshot below, in case some warning is supposed to be showing up but isn't (Firefox 62.0.3 Mac).

Thanks!

https://github.com/tidyverse/ggplot2/wiki/Align-two-plots-on-a-page

![bad-wiki-page](https://user-images.githubusercontent.com/8507813/46917441-f35b0600-cf8c-11e8-89ed-2b76d5615eee.png)

**Comment by batpigandme** [comment]
@hadley should we delete wiki pages?

**Comment by hadley** [comment]
Maybe add a big header saying it's out of date?

**Comment by batpigandme** [comment]
From the looks of things, this would have to be to the individual pages (which is fine). Downside: Will continue to be indexed by Google, presumably. 

Another option would be to do something to this effect where you keep an archive of the wiki that once was in its own repo, thereby making it clear throughout (by way of the name of the repo itself) that its archived/not current.
https://github.com/calagator/wiki-archive

**Comment by batpigandme** [comment]
Per discussion with @hadley, I've added the deprecation notice to each existing page of the wiki, and closed it from further contribution. Unfortunately, GitHub does not allow custom robots.txt, so there is no way to prevent it from being indexed without deleting all of the content.

**Comment by jdrum00** [comment]
That's just fine -- you don't control the internet. Just clearly saying that it's out of date solves the problem for me. Thanks!
