### ISSUE TITLE
Remove NA values from bar plot

### ISSUE THREAD

**Issue by neoworld77** [tidyverse/ggplot2#2952]
Hi there,

The issue is pretty straightforward. 

I am trying to generate a bar plot containing GDP per capita for several countries. The data is incomplete as some of the values are missing. 

For instance, for year 1960, I only have data for 3 countries. 

When I plot the data, the graph that is returned includes NAs, which I would like to exclude from the plot.

Please see an example below:

```r

GDP <- ggplot(data, aes(country, `1960`)) + geom_bar(stat = 'identity', na.rm = T)

```
Please note that in this case, each column represents a year. The first column of the data frame consists of the name of the countries. 

If it helps, please see the attached screenshot. 

<img width="1098" alt="screen shot 2018-10-21 at 11 55 27 pm" src="https://user-images.githubusercontent.com/25991602/47269790-d629c700-d58c-11e8-88fd-ddb592dd0208.png">

Thanks.

**Comment by batpigandme** [comment]
This sort of question is a better fit for https://community.rstudio.com. Do you mind asking it over there? (You might want to read https://www.tidyverse.org/help/ first to maximise your chances of getting a good answer.)

**Comment by batpigandme** [comment]
This sort of question is a better fit for https://community.rstudio.com. Do you mind asking it over there? (You might want to read https://www.tidyverse.org/help/ first to maximise your chances of getting a good answer.)
