### ISSUE TITLE
Feature Request: Adding text/values to gheatmap layers

### ISSUE THREAD

**Issue by Adri1CIRAD** [tidyverse/ggplot2#2958]
Hi there,

I would find very useful if it would be possible to add values to gheatmap cells.
The gheatmap function allows to easily display a matrix of cells colored from values taken in a dataframe. However, I can't find a way to display the values from which the colors are drawn. As an example, the regular heatmap.2 function include the "cellnote =" argument which read a list of strings that will be displayed within each color cell. 

Looking forward to hear back from this suggestion. Let me know if this require more details.

All the best, and thanks for the great work you guys are doing.

Adrien

**Comment by yutannihilation** [comment]
`gheatmap()` seems a ggtree's function. Maybe ggtree's repo is the right place to ask?

https://github.com/GuangchuangYu/ggtree

**Comment by batpigandme** [comment]
Agreed, better solved in the host package! 🙂
