### ISSUE TITLE
geom_curve with curvature aesthetic

### ISSUE THREAD

**Issue by danielsjf** [tidyverse/ggplot2#2964]
The function geom_curve takes an argument curvature, but this is not accepted as an aesthetic.

The use case I would like to use it for is similar to geom_jitter. Sometimes multiple lines are shown on top of other lines. Using slight random curvatures, it would be possible to see those lines separately.

```r
library(tibble)
library(dplyr)
library(ggplot2)
library(plotly)

data_points <- tibble(Node = c(1,2,3), X = c(1,2,1.5), Y = c(4,5,6))
data_segments <- tibble(From = c(1,2,3,2), To = c(2,3,1,3), label = c('Line 1: 800', 'Line 2: 1600', 'Line 3: 400', 'Line 2: 2400'))
data <- data_segments %>% 
  left_join(data_points %>% rename(From = Node, X_from = X, Y_from = Y)) %>% 
  left_join(data_points %>% rename(To = Node, X_to = X, Y_to = Y))

p <- ggplot(data) + 
  geom_point(aes(x = X_from, y = Y_from)) + 
  geom_segment(aes(x = X_from, y = Y_from, xend = X_to, yend = Y_to))
ggplotly(p)
```

Two lines (2 and 4) overlap, but this is not visible from the chart.

**Comment by thomasp85** [comment]
This is better suited for an extension package. Currently grid does not accept multiple different curvature values in `curveGrob` so it would require a fair bit of work to support it along with a measurable hit in performance
