### ISSUE TITLE
feature request: transforming coordinate system

### ISSUE THREAD

**Issue by phmarek** [tidyverse/ggplot2#2965]
Hi,

I've got some data that roughly follows some `f(x)`. To now show the *difference* against that function, I'd like to transform the coordinate system, so that the `f(x)` line becomes the horizontal x-axis, and the (previously horizontal) y-grid lines become curves that are labelled on the right and left side of the diagram (like height lines on a map).

I looked at `coord_trans`, but that only allows to give single-parameter functions for x and y transformations; I'd like some way to specify eg. `1-exp(-x)` should become the x-axis line, so the new y-coordinates depend on x as well.
The graph data (points and/or lines) and grid should get transformed as well, of course.

Is that already possible? Would it be enough to pass the x coordinate to the y transformer function as well to use it for coordinate translation?

**Comment by batpigandme** [comment]
This sort of question is a better fit for https://community.rstudio.com. Do you mind asking it over there? (You might want to read https://www.tidyverse.org/help/ first to maximise your chances of getting a good answer.)

**Comment by phmarek** [comment]
Hi batpigandme,

thanks for the quick answer!

> This sort of question is a better fit for https://community.rstudio.com
Ugh, another forum to subscribe to...

I thought that it ain't be possible right now, so I wanted to ask "the developers" first.


Regards,

Phil

**Comment by batpigandme** [comment]
OK, please reformat to clarify that this is a feature request and include a link to the thread you opened on community with @thomasp85's response (same devs different platform).

**Comment by phmarek** [comment]
thomasp85 wrote:
> The short answer is “no” - it is not possible to transform coordinate systems in that way in ggplot2. I will not rule out that it is doable to write a Coord class that could perform this, but I think it is much more viable to simply subtract the function value from your data and plot the results. In the end you’d get the same plot but it would probably be easier for people to interpret compared to a plot with some strange coordinate transformation...

**Comment by thomasp85** [comment]
This sort of functionality is better suited for an extension package. If you are not interested in creating one yourself you could open a feature request in an existing and fitting extension package such as e.g. [ggalt](https://github.com/hrbrmstr/ggalt) or [ggforce](https://github.com/thomasp85/ggforce)
