### ISSUE TITLE
Limiting the range of colours in a featureplot

### ISSUE THREAD

**Issue by fereshtehizadi** [tidyverse/ggplot2#2967]
Hi,

I have plotted the below tSNE  plot by Seurat R package

[

![](https://image.ibb.co/jbEJbV/Rplot16.png)
](url)
I want to change the range of my colours to a `8-18 , 18-28, 28-38, 38-48` range in a blue to yellow gradient instead of this wide range of colours, I mean something like this picture

[

![](https://image.ibb.co/d5UyAq/68747470733a2f2f696d6167652e6962622e636f2f6868424356552f612e706e67.png)
](url)

Please somebody help me to fo that

Thanks a lot for any help

**Comment by batpigandme** [comment]
This sort of question is a better fit for https://community.rstudio.com. Do you mind asking it over there? (You might want to read https://www.tidyverse.org/help/ first to maximise your chances of getting a good answer.)

**Comment by fereshtehizadi** [comment]
Sorry,


But I need help 😞


Help me please


Rstudio community put my activity on hold


Long time I am struggling with this question


________________________________

**Comment by thomasp85** [comment]
The easiest thing would probably be to bin your colour variable before plotting. Look into the documentation of `cut` for how to do that
