### ISSUE TITLE
scale_x_discrete with numeric drops axis with no warning

### ISSUE THREAD

**Issue by ptoche** [tidyverse/ggplot2#2970]
Discrete scales are not designed to work with numeric data, this is clear. However, a careless/naive user could attempt to apply a discrete scale to continuous data. I suggest issuing a warning when a discrete scale is applied to continuous data.  

Use case: I absent-mindedly tried to apply ``scale_x_discrete`` to a continuous scale (the data was intended to be discrete, but was actually numeric) and discovered that the axis was dropped altogether and no warning issued. I hadn't noticed the problem until I used ``expand_scale`` inside the ``scale_x_discrete``. Before that I was able to set limits inside ``scale_x_discrete`` without losing the axis, so alarm bells hadn't sounded.  A warning would save time debugging and/or potentially avoid producing an incorrect plot. 

``` r
library(ggplot2)

# factor/character + scale_x_discrete + expand_scale 
ggplot(mpg, aes(as.factor(hwy), displ)) +
    geom_point() +
    scale_x_discrete(expand = expand_scale(add = c(5, 5))) 
```

![](https://i.imgur.com/1CsZQd6.png)

``` r

# num/int + scale_x_discrete + expand_scale : drops the x axis
ggplot(mpg, aes(hwy, displ)) +
    geom_point() +
    scale_x_discrete(expand = expand_scale(add = c(5, 5))) 
```

![](https://i.imgur.com/Z7d5Bw1.png)

``` r

# num/int + scale_x_continuous + expand_scale
ggplot(mpg, aes(hwy, displ)) +
    geom_point() +
    scale_x_continuous(expand = expand_scale(add = c(10, 10))) 
```

![](https://i.imgur.com/k0g9Ylj.png)

Created on 2018-10-30 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by hadley** [comment]
This appears to be a deliberate choice: https://github.com/tidyverse/ggplot2/blob/6c2fe76e77a50aae5935935a8d17e404a8100871/R/scale-discrete-.r#L115 — so it would require extremely careful analysis to determine if this was always a false positive or is actually needed for existing plots in the wild. It's my sense that this analysis would be sufficiently time consuming as not to be worthwhile, given the payoff.
