### ISSUE TITLE
CODE_OF_CONDUCT.md missing from master so links in GOVERNANCE readme are broken

### ISSUE THREAD

**Issue by dan-booth** [tidyverse/ggplot2#2979]
_Will skip the regex as not code related_

I noticed while reading the [Governance doc](https://github.com/tidyverse/ggplot2/blob/master/GOVERNANCE.md#core-developers) that references to the *code of conduct* are broken.

Not sure if you are just using that link as a hold and still waiting to up, or if you mean to reference [this](https://github.com/tidyverse/ggplot2/blob/c1878e4a8cf2f224035466aa64feead594b03832/.github/CODE_OF_CONDUCT.md) instead (I doubt it, but found it on a repo search)

Thanks for all your work on ggplot2.

**Comment by dpseidel** [comment]
Thanks. There is already an open PR to fix it, see #2973
