### ISSUE TITLE
Feature request: Coordinate transformation = "log(1+x)"

### ISSUE THREAD

**Issue by skanskan** [tidyverse/ggplot2#2980]
Could you add the option to use more coordinates transformations, please?
For example it would be useful to be able to use log(1+x), sometimes refered as log1p.
I've tried to use scale_y_continuous(trans = "log1p") but it doesn't do anything.

**Comment by batpigandme** [comment]
You need to use `coord_trans()`. [`log1p_trans()`](https://scales.r-lib.org/reference/log1p_trans.html) is already part of scales!
``` r
library(ggplot2)

ggplot(diamonds, aes(carat, price)) +
  geom_point() +
  coord_trans(y = "log1p")
```

![](https://i.imgur.com/lm27pLP.png)

``` r

scales::log1p_trans()
#> Transformer:  log1p
```

<sup>Created on 2018-11-05 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>
