### ISSUE TITLE
I got a problem when I try to install ggplot2 but I don't konw how to fix it

### ISSUE THREAD

**Issue by gangstertiny** [tidyverse/ggplot2#2982]
Here is error message: 

* installing *source* package 'ggplot2' ...
** package 'ggplot2' successfully unpacked and MD5 sums checked
** R
** data
*** moving datasets to lazyload DB
** inst
** preparing package for lazy loading
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  namespace 'scales' 0.4.1 is being loaded, but >= 0.5.0 is required
ERROR: lazy loading failed for package 'ggplot2'
* removing 'D:/soft/R/R-3.2.3/library/ggplot2'

I tried to update scales but I can't find  its latest version.

**Comment by romunov** [comment]
`scales` version on CRAN is 1.0.0. Note that the latest version of R is 3.5.1. Unless you're maintaining a reproducible pipeline with fixed tools, you should probably upgrade.

**Comment by gangstertiny** [comment]
> `scales` version on CRAN is 1.0.0. Note that the latest version of R is 3.5.1. Unless you're maintaining a reproducible pipeline with fixed tools, you should probably upgrade.

Thank you!
