### ISSUE TITLE
Should we compact facet grid specs?

### ISSUE THREAD

**Issue by lionel-** [tidyverse/ggplot2#2986]
This would make it easier to program with facets.

From https://stackoverflow.com/questions/53218152/ggplot2-facet-grid-with-conditional-facets-and-tidy-evaluation

```r
plot_iris <- function(df_in, facet_var = NULL){
  ggplot(df_in) +
    geom_point(aes(Sepal.Length, Sepal.Width)) +
    facet_grid(vars(!!enquo(facet_var)), vars(idx))
}
```

**Comment by hadley** [comment]
That would be consistent with https://github.com/tidyverse/principles/issues/24
