### ISSUE TITLE
nudging stacked bars changes bar heights?

### ISSUE THREAD

**Issue by kdarras** [tidyverse/ggplot2#2992]
In the following reprex, inserting the position_nudge argument in the first or second geom_bar line changes the heights of the bars. I have no idea why.

This is test.dt
`abundance,Habitat,Occurrence
0.964285714285714,"Forest
upland",Overall
0.25,"Forest
upland",Overall
9.71428571428571,"Forest
riparian",Overall
0.535714285714286,"Forest
riparian",Overall
5.45833333333333,"Oil palm
upland",Overall
5.20833333333333,"Oil palm
upland",Overall
8.83333333333333,"Oil palm
riparian",Overall
3.16666666666667,"Oil palm
riparian",Overall
2.25,"Rubber
upland",Overall
0.178571428571429,"Rubber
upland",Overall
3.92857142857143,"Rubber
riparian",Overall
0.428571428571429,"Rubber
riparian",Overall
0.0714285714285714,"Forest
upland",Common
0,"Forest
upland",Common
0.0714285714285714,"Forest
riparian",Common
0,"Forest
riparian",Common
3.33333333333333,"Oil palm
upland",Common
4,"Oil palm
upland",Common
6.16666666666667,"Oil palm
riparian",Common
2.91666666666667,"Oil palm
riparian",Common
0.821428571428571,"Rubber
upland",Common
0.0357142857142857,"Rubber
upland",Common
2.82142857142857,"Rubber
riparian",Common
0.107142857142857,"Rubber
riparian",Common
0.892857142857143,"Forest
upland",Rare
0.214285714285714,"Forest
upland",Rare
9.07142857142857,"Forest
riparian",Rare
0.464285714285714,"Forest
riparian",Rare
2,"Oil palm
upland",Rare
1.04166666666667,"Oil palm
upland",Rare
1.95833333333333,"Oil palm
riparian",Rare
0.208333333333333,"Oil palm
riparian",Rare
1.42857142857143,"Rubber
upland",Rare
0.142857142857143,"Rubber
upland",Rare
1,"Rubber
riparian",Rare
0.25,"Rubber
riparian",Rare`

library(data.table)
ggplot(test.dt,aes(Habitat,abundance,fill=Occurrence))+
  geom_bar(data=abundance_plot_occurrence[Occurrence=="Overall"],stat="identity",position = position_nudge(x=0.1))+
  geom_bar(data=abundance_plot_occurrence[Occurrence!="Overall"],stat="identity")

**Comment by clauswilke** [comment]
Please provide a reprex. This should help you get started:
https://reprex.tidyverse.org/articles/articles/magic-reprex.html

**Comment by kdarras** [comment]
Oh sorry, I thought reprex was just an abbreviation.
I installed reprex but it fails to capture the code in my clipboard, and R also fails to install the packages reprex says it needs (xclip and xsel).
I prepared a more easily reproducible example, please note the different bar plots:

library(data.table)
iris=data.table(iris)
iris2=melt(iris)
iris3=iris2[,.(value=mean(value)),.(Species,variable)]

ggplot(iris3,aes(Species,value,fill=variable))+
  geom_bar(data=iris3[variable=="Sepal.Length"],stat="identity",position = position_nudge(x=0.1))+
  geom_bar(data=iris3[variable!="Sepal.Length"],stat="identity")

ggplot(iris3,aes(Species,value,fill=variable))+
  geom_bar(data=iris3[variable=="Sepal.Length"],stat="identity")+
  geom_bar(data=iris3[variable!="Sepal.Length"],stat="identity",position = position_nudge(x=0.1))

**Comment by IndrajeetPatil** [comment]
@kdarras This is still not a `reprex`. Check this out on how to make a reprex:
https://maraaverick.rbind.io/2018/06/reprexcellence/

**Comment by yutannihilation** [comment]
@kdarras 
I guess you are complaining about bars won't stack when you specify `position_nudge()`. But, to stack bars, you need to specify `position_stack()`, which is the default position of `geom_bar()` (and `geom_col()`). You cannot have two positions at the same time.

``` r
library(ggplot2)

d <- data.frame(group = c("a", "b", "c"),
                value = 1:3,
                colour = alpha(c("red", "blue", "green"), 0.3),
                stringsAsFactors = FALSE)

ggplot(d) +
  geom_col(aes(0, value, colour = colour),
           fill = "transparent",
           size = 10) +
  scale_color_identity() +
  ylim(0, 6) +
  theme_bw()
```

![](https://i.imgur.com/Kb39LqD.png)

``` r

ggplot(d) +
  geom_col(aes(0, value, colour = colour),
           fill = "transparent",
           size = 10,
           position = "nudge") +
  scale_color_identity() +
  ylim(0, 6) +
  theme_bw()
```

![](https://i.imgur.com/jJBkopd.png)

<sup>Created on 2018-11-30 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>
