### ISSUE TITLE
Rd warnings

### ISSUE THREAD

**Issue by IndrajeetPatil** [tidyverse/ggplot2#2999]
When I download `ggplot2`, it produces the following `.Rd` warnings. From user's point-of-view, this is not at all important. But I am trying to get to the source of why such warnings are generated in the first place and what can be changed in the `roxygen2` skeleton to get rid of such warnings.
```r
Rd warning: C:/Users/inp099/AppData/Local/Temp/RtmpIL6A2X/R.INSTALL1f709765163/ggplot2/man/tidyeval.Rd:23: file link 'syms' in package 'rlang' does not exist and so has been treated as a topic
Rd warning: C:/Users/inp099/AppData/Local/Temp/RtmpIL6A2X/R.INSTALL1f709765163/ggplot2/man/tidyeval.Rd:25: file link 'expr' in package 'rlang' does not exist and so has been treated as a topic
Rd warning: C:/Users/inp099/AppData/Local/Temp/RtmpIL6A2X/R.INSTALL1f709765163/ggplot2/man/tidyeval.Rd:25: file link 'quo' in package 'rlang' does not exist and so has been treated as a topic
Rd warning: C:/Users/inp099/AppData/Local/Temp/RtmpIL6A2X/R.INSTALL1f709765163/ggplot2/man/tidyeval.Rd:28: file link 'exprs' in package 'rlang' does not exist and so has been treated as a topic
Rd warning: C:/Users/inp099/AppData/Local/Temp/RtmpIL6A2X/R.INSTALL1f709765163/ggplot2/man/tidyeval.Rd:29: file link 'quos' in package 'rlang' does not exist and so has been treated as a topic
Rd warning: C:/Users/inp099/AppData/Local/Temp/RtmpIL6A2X/R.INSTALL1f709765163/ggplot2/man/tidyeval.Rd:31: file link 'enexpr' in package 'rlang' does not exist and so has been treated as a topic
Rd warning: C:/Users/inp099/AppData/Local/Temp/RtmpIL6A2X/R.INSTALL1f709765163/ggplot2/man/tidyeval.Rd:31: file link 'enquo' in package 'rlang' does not exist and so has been treated as a topic
Rd warning: C:/Users/inp099/AppData/Local/Temp/RtmpIL6A2X/R.INSTALL1f709765163/ggplot2/man/tidyeval.Rd:35: file link 'enexprs' in package 'rlang' does not exist and so has been treated as a topic
Rd warning: C:/Users/inp099/AppData/Local/Temp/RtmpIL6A2X/R.INSTALL1f709765163/ggplot2/man/tidyeval.Rd:35: file link 'enquos' in package 'rlang' does not exist and so has been treated as a topic
```

**Comment by hadley** [comment]
I think this just requires a bump in the required version of rlang in DESCRIPTION

**Comment by yutannihilation** [comment]
I don't think updating rlang will help, this seems a roxygen2's problem to me, if you think this is actually a problem. The warnings come from [here in `src/library/tools/R/Rd2HTML.R`](https://github.com/wch/r-source/blob/0e2f9217f965eaba5c68f4013ddbf2cb5fd6a958/src/library/tools/R/Rd2HTML.R#L360-L388
); it seems R doesn't feel comfortable with the form of `\link[pkg]{topic}` and prefers these forms:

```r
 ## ----------------- \link[pkg]{file} and \link[pkg:file]{bar}
```

(I see this warnings too many times here and there so I don't even think this is actually a warning... Thanks for the chance to dig into the R's source code... :P)

**Comment by IndrajeetPatil** [comment]
Whoa! Thanks @yutannihilation for digging into the code to figure this one out. I have been getting similar `warnings` and thought this issue was specific to the pipe operator (https://github.com/r-lib/usethis/issues/478), but this seems to be a much general issue with `roxygen2`.

**Comment by yutannihilation** [comment]
Oh, curious, it seems not everyone sees this warning. Anyway, I don't think ggplot2's repo is the right place to discuss. Maybe this issue is?

https://github.com/klutometis/roxygen/issues/707
