### ISSUE TITLE
Error: Can't find `stat` called “identity”

### ISSUE THREAD

**Issue by cystein** [tidyverse/ggplot2#3000]
I didn't find any results on my internet search. How to fix this error is caused?

My codes;

```
> library(ggplot2)
> 
> ggplot(data = mtcars, aes(x=disp , y=wt)) + geom_point(stat = "identity")
```

result;

`Error: Can't find `stat` called "identity"`

My sessionInfo()

```
R version 3.5.1 (2018-07-02)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.1 LTS

Matrix products: default
BLAS: /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.7.1
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.7.1

locale:
 [1] LC_CTYPE=tr_TR.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=tr_TR.UTF-8        LC_COLLATE=tr_TR.UTF-8    
 [5] LC_MONETARY=tr_TR.UTF-8    LC_MESSAGES=tr_TR.UTF-8   
 [7] LC_PAPER=tr_TR.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=tr_TR.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] ggplot2_3.1.0 shiny_1.2.0  

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.0         pillar_1.3.0       compiler_3.5.1    
 [4] cellranger_1.1.0   RColorBrewer_1.1-2 later_0.7.5       
 [7] plyr_1.8.4         bindr_0.1.1        forcats_0.3.0     
[10] tools_3.5.1        digest_0.6.18      viridisLite_0.3.0 
[13] jsonlite_1.5       tibble_1.4.2       gtable_0.2.0      
[16] pkgconfig_2.0.2    rlang_0.3.0.1      ggplotgui_1.0.0   
[19] rstudioapi_0.8     yaml_2.2.0         haven_1.1.2       
[22] bindrcpp_0.2.2     withr_2.1.2        stringr_1.3.1     
[25] httr_1.3.1         dplyr_0.7.8        htmlwidgets_1.3   
[28] hms_0.4.2          grid_3.5.1         tidyselect_0.2.5  
[31] data.table_1.11.8  glue_1.3.0         R6_2.3.0          
[34] plotly_4.8.0       readxl_1.1.0       readr_1.1.1       
[37] tidyr_0.8.2        purrr_0.2.5        magrittr_1.5      
[40] scales_1.0.0       promises_1.0.1     htmltools_0.3.6   
[43] assertthat_0.2.0   xtable_1.8-3       mime_0.6          
[46] colorspace_1.3-2   httpuv_1.4.5       stringi_1.2.4     
[49] lazyeval_0.2.1     munsell_0.5.0      crayon_1.3.4


```

**Comment by romunov** [comment]
`stat` doesn't make sense for points as there are no statistics being calculated based on those points. This makes sense in the context of plotting e.g. bar plots (compare `geom_bar`, `geom_col`). Just omit this argument from `geom_point`.

**Comment by cystein** [comment]
> I believe something is wrong on your computer and not in your code. Can you try to reinstall `ggplot2` and restart your session

Yeah, I think the problem is on my computer. Although I uninstall and install the software, the result is the same :(

**Comment by thomasp85** [comment]
What do you get if you type `stat_identity()`in the console

**Comment by batpigandme** [comment]
Can you please render this as a [reprex](https://reprex.tidyverse.org/) with "Append session info" selected? [Magic reprex](https://reprex.tidyverse.org/articles/articles/magic-reprex.html) from the documentation will give you a nice overview of how it works, if you're not familiar.

Once you have the code on your clipboard, you can use the reprex add-in to select "Append session info" (see the selections below):
![image](https://user-images.githubusercontent.com/831732/48477492-c12d0600-e7cf-11e8-952d-0d14da5ded63.png)

``` r
library(ggplot2)

ggplot(data = mtcars, aes(x = disp, y = wt)) +
  geom_bar(stat = "identity")
```

![](https://i.imgur.com/68pDBnI.png)

<sup>Created on 2018-11-14 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

<details>

<summary>Session info</summary>

``` r
devtools::session_info()
#> ─ Session info ──────────────────────────────────────────────────────────
#>  setting  value                       
#>  version  R version 3.5.1 (2018-07-02)
#>  os       macOS Sierra 10.12.6        
#>  system   x86_64, darwin15.6.0        
#>  ui       X11                         
#>  language (EN)                        
#>  collate  en_US.UTF-8                 
#>  ctype    en_US.UTF-8                 
#>  tz       America/New_York            
#>  date     2018-11-14                  
#> 
#> ─ Packages ──────────────────────────────────────────────────────────────
#>  package     * version     date       lib
#>  assertthat    0.2.0       2017-04-11 [1]
#>  backports     1.1.2       2017-12-13 [1]
#>  base64enc     0.1-3       2015-07-28 [1]
#>  callr         3.0.0.9001  2018-11-13 [1]
#>  cli           1.0.1.9000  2018-11-13 [1]
#>  colorspace    1.3-2       2016-12-14 [1]
#>  crayon        1.3.4       2018-10-31 [1]
#>  curl          3.2.9000    2018-11-13 [1]
#>  debugme       1.1.0       2017-10-22 [1]
#>  desc          1.2.0       2018-11-13 [1]
#>  devtools      2.0.1       2018-10-26 [1]
#>  digest        0.6.18      2018-10-10 [1]
#>  dplyr         0.7.99.9000 2018-11-13 [1]
#>  evaluate      0.12        2018-10-09 [1]
#>  fs            1.2.6       2018-08-23 [1]
#>  ggplot2     * 3.1.0.9000  2018-11-13 [1]
#>  glue          1.3.0       2018-10-29 [1]
#>  gtable        0.2.0.9000  2018-11-13 [1]
#>  highr         0.7         2018-06-09 [1]
#>  htmltools     0.3.6       2017-04-28 [1]
#>  httr          1.3.1       2017-08-20 [1]
#>  knitr         1.20.21     2018-11-13 [1]
#>  labeling      0.3         2014-08-23 [1]
#>  lazyeval      0.2.1       2017-10-29 [1]
#>  magrittr      1.5         2014-11-22 [1]
#>  memoise       1.1.0       2017-04-21 [1]
#>  mime          0.6         2018-10-05 [1]
#>  munsell       0.5.0       2018-06-12 [1]
#>  pillar        1.3.0.9001  2018-10-17 [1]
#>  pkgbuild      1.0.2.9000  2018-11-13 [1]
#>  pkgconfig     2.0.2       2018-08-16 [1]
#>  pkgload       1.0.2       2018-10-29 [1]
#>  plyr          1.8.4       2016-06-08 [1]
#>  prettyunits   1.0.2       2015-07-13 [1]
#>  processx      3.2.0       2018-08-16 [1]
#>  ps            1.2.1       2018-11-06 [1]
#>  purrr         0.2.5       2018-05-29 [1]
#>  R6            2.3.0       2018-10-04 [1]
#>  Rcpp          1.0.0       2018-11-07 [1]
#>  remotes       2.0.2       2018-10-30 [1]
#>  rlang         0.3.0.9000  2018-11-05 [1]
#>  rmarkdown     1.10        2018-06-11 [1]
#>  rprojroot     1.3-2       2018-01-03 [1]
#>  scales        1.0.0.9000  2018-11-13 [1]
#>  sessioninfo   1.1.1       2018-11-05 [1]
#>  stringi       1.2.4       2018-07-20 [1]
#>  stringr       1.3.1       2018-05-10 [1]
#>  testthat      2.0.1       2018-10-13 [1]
#>  tibble        1.4.99.9005 2018-11-13 [1]
#>  tidyselect    0.2.5       2018-10-11 [1]
#>  usethis       1.4.0.9000  2018-10-29 [1]
#>  withr         2.1.2.9000  2018-11-13 [1]
#>  xfun          0.4         2018-10-23 [1]
#>  xml2          1.2.0       2018-01-24 [1]
#>  yaml          2.2.0       2018-07-25 [1]
#>  source                            
#>  CRAN (R 3.5.0)                    
#>  CRAN (R 3.5.0)                    
#>  CRAN (R 3.5.0)                    
#>  Github (r-lib/callr@be7707d)      
#>  Github (r-lib/cli@56538e3)        
#>  CRAN (R 3.5.0)                    
#>  Github (r-lib/crayon@0398b12)     
#>  Github (jeroen/curl@5e56197)      
#>  CRAN (R 3.5.0)                    
#>  Github (r-lib/desc@7c12d36)       
#>  CRAN (R 3.5.1)                    
#>  CRAN (R 3.5.0)                    
#>  Github (tidyverse/dplyr@e177d27)  
#>  CRAN (R 3.5.0)                    
#>  CRAN (R 3.5.0)                    
#>  Github (tidyverse/ggplot2@b4b725e)
#>  Github (tidyverse/glue@35c61e9)   
#>  Github (r-lib/gtable@cdbf7c0)     
#>  CRAN (R 3.5.0)                    
#>  CRAN (R 3.5.0)                    
#>  CRAN (R 3.5.0)                    
#>  Github (yihui/knitr@7ae1db5)      
#>  CRAN (R 3.5.0)                    
#>  CRAN (R 3.5.0)                    
#>  CRAN (R 3.5.0)                    
#>  CRAN (R 3.5.0)                    
#>  CRAN (R 3.5.0)                    
#>  CRAN (R 3.5.0)                    
#>  Github (r-lib/pillar@c5bf622)     
#>  Github (r-lib/pkgbuild@6e4ebdf)   
#>  CRAN (R 3.5.0)                    
#>  CRAN (R 3.5.1)                    
#>  CRAN (R 3.5.0)                    
#>  CRAN (R 3.5.0)                    
#>  CRAN (R 3.5.0)                    
#>  CRAN (R 3.5.0)                    
#>  CRAN (R 3.5.0)                    
#>  CRAN (R 3.5.0)                    
#>  CRAN (R 3.5.0)                    
#>  CRAN (R 3.5.1)                    
#>  Github (r-lib/rlang@f6a719a)      
#>  CRAN (R 3.5.0)                    
#>  CRAN (R 3.5.0)                    
#>  Github (r-lib/scales@06d46e1)     
#>  CRAN (R 3.5.0)                    
#>  CRAN (R 3.5.0)                    
#>  CRAN (R 3.5.0)                    
#>  CRAN (R 3.5.0)                    
#>  Github (tidyverse/tibble@6d53680) 
#>  CRAN (R 3.5.1)                    
#>  Github (r-lib/usethis@44dd72c)    
#>  Github (r-lib/withr@be57595)      
#>  CRAN (R 3.5.0)                    
#>  CRAN (R 3.5.0)                    
#>  CRAN (R 3.5.0)                    
#> 
#> [1] /Library/Frameworks/R.framework/Versions/3.5/Resources/library
```

</details>

**Comment by cystein** [comment]
`> stat_identity()
Hata: Can't find `position` called "identity"`

**Comment by cystein** [comment]
Mara Hi,

When I give the command to the R, I get this error.

`> reprex::reprex()
No input provided and clipboard is not available.
Rendering reprex...
Clipboard on X11 requires 'xclip' (recommended) or 'xsel'.
Unable to put result on the clipboard. How to get it:
  * Capture what `reprex()` returns.
  * Consult the output file. Control via `outfile` argument.
Path to `outfile`:
  * /tmp/Rtmpl2sHbh/reprex46211800f71/reprex_reprex.md`

**Comment by batpigandme** [comment]
If you run into problems with access to your clipboard, you can specify an infile and an outfile for the reprex, and then copy and paste the contents here.

```r
reprex::reprex(input = "foot.R", outfile = "foo.md")
```
In your case you'll also want to add `si = opt(TRUE)` to that, since we'll want the session info.

**Comment by yutannihilation** [comment]
What's curious about this error is that `ggplot2:::check_subclass()` did find `GeomPoint`, but failed with `PositionIdentity`.

> ``stat_identity() Error: Can't find `position` called "identity"``

I know nothing about Turkish, but might it matter to capitalize "i" that it has [dotted and dotless I](https://en.wikipedia.org/wiki/Dotted_and_dotless_I)...? (although I couldn't reproduce the error even if I set `Sys.setlocale(locale = "tr_TR.UTF-8")` on Mac)

**Comment by cystein** [comment]
I know nothing about Turkish, but might it matter to capitalize "i" that it has [dotted and dotless I](https://en.wikipedia.org/wiki/Dotted_and_dotless_I)...? (although I couldn't reproduce the error even if I set `Sys.setlocale(locale = "tr_TR.UTF-8")` on Mac)

Hi Hiroaki,

You're right. This problem seems to be related to language settings. After logging in, I run "ggplot" without problems when I issue the following command.

`> Sys.setlocale(locale = "en_GB.UTF-8")
[1] "LC_CTYPE=en_GB.UTF-8;LC_NUMERIC=C;LC_TIME=en_GB.UTF-8;LC_COLLATE=en_GB.UTF-8;LC_MONETARY=en_GB.UTF-8;LC_MESSAGES=tr_TR.UTF-8;LC_PAPER=tr_TR.UTF-8;LC_NAME=C;LC_ADDRESS=C;LC_TELEPHONE=C;LC_MEASUREMENT=tr_TR.UTF-8;LC_IDENTIFICATION=C"`

and then;

`> stat_identity()
geom_point: na.rm = FALSE
stat_identity: na.rm = FALSE
position_identity `

Thank you..

**Comment by yutannihilation** [comment]
Oh, no... Thanks for confirmation!

Until we find out the universal version of `toupper()` (which is used [here](https://github.com/tidyverse/ggplot2/blob/4380cb97d55a91b6ef430d5b23327fab5c421b27/R/utilities.r#L320)), please set the locale other than `tr_TR` as a workaround. Sorry for inconvenience.

Let me confirm one more thing. In the locale of `tr_TR.UTF-8`, the code below returns `İ` (U+0130, LATIN CAPITAL LETTER I WITH DOT ABOVE), right?

```r
toupper("i")
````

**Comment by cystein** [comment]
`> sessionInfo()
R version 3.5.1 (2018-07-02)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.1 LTS

Matrix products: default
BLAS: /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.7.1
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.7.1

locale:
 [1] LC_CTYPE=tr_TR.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=tr_TR.UTF-8        LC_COLLATE=tr_TR.UTF-8    
 [5] LC_MONETARY=tr_TR.UTF-8    LC_MESSAGES=tr_TR.UTF-8   
 [7] LC_PAPER=tr_TR.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=tr_TR.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods  
[7] base     

other attached packages:
[1] RMySQL_0.10.15 DBI_1.0.0     

loaded via a namespace (and not attached):
[1] compiler_3.5.1 tools_3.5.1    yaml_2.2.0    
> toupper("i")
[1] "İ"`

Correct, thak you..

**Comment by yutannihilation** [comment]
Thanks!

**Comment by yutannihilation** [comment]
@cystein 
Could you confirm #3011 fixes the problem? You can install it by `install_github()`:

```r
devtools::install_github("tidyverse/ggplot2#3011")
```

**Comment by cystein** [comment]
> devtools::install_github("tidyverse/ggplot2#3011")
Hata: HTTP error 422.
  No commit found for SHA: fix-turkish-dotted-i

  Rate limit remaining: 52/60
  Rate limit reset at: 2018-11-21 12:28:51 UTC

**Comment by yutannihilation** [comment]
@cystein 
Ah, sorry, I already deleted the branch. Now that it is merged into master, you can just

```r
devtools::install_github("tidyverse/ggplot2")
```

**Comment by cystein** [comment]
Oh, thank you very much. It is working now..

**Comment by yutannihilation** [comment]
Yay, nice to hear that. Thanks :)
