### ISSUE TITLE
geom_sf layers do not align

### ISSUE THREAD

**Issue by PaulLantos** [tidyverse/ggplot2#3007]
Hi,
 I am plotting two layers in geom_sf. They align perfectly in ArcGIS, in fact one (the blue) was made by clipping using the other (the black), and they are in the same coordinate system. However when I plot them in geom_sf I get this:

![image](https://user-images.githubusercontent.com/32649719/48677250-f030d800-eb3f-11e8-8bf8-5b75c9a9e354.png)

Thanks for any help!

**Comment by clauswilke** [comment]
Please provide a reprex:
https://reprex.tidyverse.org/articles/articles/magic-reprex.html

**Comment by PaulLantos** [comment]
How do I share the data? It's from two shapefiles.
