### ISSUE TITLE
Faceting error in ggplot2/ggrepel: Viewport has zero dimension(s)

### ISSUE THREAD

**Issue by efehandanisman** [tidyverse/ggplot2#3010]
Hello,

I am using this script every week to produce some plots and again received error mentioned at the title. When I replace geom_text_repel with geom_text, problem is solved but then plot does not look like as I wish since I want to move text slight over the line bar.

What console says as an error with repex is ggplot function does not found(in Turkish below) while it is actually there.

I am adding the sessionInfo as well in case needed.

This is my first issue here so I hope I am clear enough to explain it. I checked the previous issues as well however none of them solves my problem.

---

Here is my dummy data to reproduce
```r
head(df,3)
 DATE     CASE_R CASE_C FILE         
  <chr>     <dbl>  <dbl> <chr>        
1 42         3333   5555 var1         
2 43         3333   5555 var1         
3 44         2222   5555 var1 


ggplot(transform(facet45, FILE = factor(FILE, levels = c("var1", 
    "var2", "var3"))), aes(x = DATE, 
    group = 1)) + geom_line(aes(y = CASE_C, col = "CASE_C"), 
    size = 1.5) + geom_line(aes(y = CASE_R, col = "CASE_R"), size = 1.5) + 
    facet_grid(~FILE) + ylab("FILE NUMBER") + ylim(1000, 6000) + 
    geom_text_repel(aes(y = CASE_C, label = CASE_C), size = 5.5, 
        fontface = "bold") + geom_text_repel(aes(y = CASE_R, label = CASE_R), 
    size = 5.5, fontface = "bold") + theme_bw() + theme(panel.grid.major = element_blank(), 
    panel.grid.minor = element_blank(), strip.text.y = element_text(size = 18, 
        face = "bold"), strip.text.x = element_text(size = 18, 
        face = "bold"), axis.text.x = element_text(size = 16, 
        angle = 30, hjust = 1, face = "bold"), axis.text.y = element_text(size = 18), 
    axis.title.x = element_blank(), axis.title.y = element_text(size = 12), 
    legend.title = element_blank(), legend.text = element_text(size = 20, 
        face = "bold")) + scale_colour_manual(values = c("darkblue", 
    "red"))

#> Error in ggplot(transform(facet45, DOSYA = factor(DOSYA, levels = c("Şikayet", : "ggplot" fonksiyonu bulunamadı. (Means ggplot function does not found)

R version 3.5.0 (2018-04-23)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=Turkish_Turkey.1254  LC_CTYPE=Turkish_Turkey.1254    LC_MONETARY=Turkish_Turkey.1254 LC_NUMERIC=C                   
[5] LC_TIME=Turkish_Turkey.1254    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] reprex_0.2.1    scales_0.5.0    ggrepel_0.8.0   forcats_0.3.0   stringr_1.3.0   dplyr_0.7.4     purrr_0.2.4     readr_1.1.1     tidyr_0.8.0    
[10] tibble_1.4.2    ggplot2_3.0.0   tidyverse_1.2.1 readxl_1.1.0   
```

**Comment by batpigandme** [comment]
> #> Error in ggplot(transform(facet45, DOSYA = factor(DOSYA, levels = c("Şikayet", : "ggplot" fonksiyonu bulunamadı. (Means ggplot function does not found)

Have you loaded ggplot2 in the session. Could you please try reproducing this using the [reprex package](https://reprex.tidyverse.org/)? Your example will need to be _self-contained_, so your objects and libraries should be created and attached, respectively.

Also, please make your example a bit more minimal by paring down the features that aren't relevant to the problem at hand (e.g. text size and face, theme changes, etc.).

**Comment by efehandanisman** [comment]
Yes it is loaded and working perfectly with other ggplot functions at my script. Also same script worked with similar data last week, I just changed some values. 
I produced the example using reprex function before my ggplot function, is not it the correct practice? Also adding the code without theme parts. 

``
ggplot(transform(facet45, FILE = factor(FILE, levels = c("var1", 
    "var2", "var3"))), aes(x = DATE, group = 1)) + 
   geom_line(aes(y = CASE_C, col = "CASE_C"), 
    size = 1.5) + 
    geom_line(aes(y = CASE_R, col = "CASE_R"), size = 1.5) + 
    facet_grid(~FILE) + ylab("FILE NUMBER") + ylim(1000, 6000) + 
    geom_text_repel(aes(y = CASE_C, label = CASE_C), size = 5.5, 
    fontface = "bold")+
    geom_text_repel(aes(y = CASE_R, label = CASE_R), 
    size = 5.5, fontface = "bold") 
``
#> Error in ggplot(transform(facet45, FILE = factor(FILE , levels = c("var1", : "ggplot" fonksiyonu bulunamadı(means ggplot function not found)

**Comment by hadley** [comment]
@efehandanisman please carefully read the advice on creating a reprex. Until you supply some code that we can easily run, we can not help you.

**Comment by efehandanisman** [comment]
Sorry for the incorrect reprex.

Here is what I get from the reprex to the clipboard. What makes it interesting is error is not produced anymore and plot is created as I wanted. Nonetheless reprex is giving me "ggplot can not found error" and I copied below what is copied to clipboard. Since issue is solved, this can be closed but still I would like to share the steps of the solution which I found accidentally.

1- With theme part of the code error is reproduced first.
2- Then I deleted theme code and plot created.
3- Then when I re-add the theme, plot is created again too.

``` r
ggplot(transform(facet45,FILE=factor(FILE, levels=c("var1","var2","var3"))), aes(x=DATE,group=1))+
  geom_line(aes(y=CASE_C,col="CASE_C"), size=1.5)+
  geom_line(aes(y=CASE_R, col="CASE_R"), size=1.5)+
  facet_grid(~FILE)+
  ylab("FILE")+
  ylim(1750,5500)+
  geom_text_repel(aes(y=CASE_C,,label=CASE_C,), size=5.5, fontface="bold")+
  geom_text_repel(aes(y=CASE_R, label=CASE_CR), size=5.5, fontface="bold")+
  scale_colour_manual(values = c("darkblue","red"))+
  theme_bw()+
  theme(panel.grid.major = element_blank(),panel.grid.minor = element_blank(),strip.text.y=element_text(size=18, face="bold"), strip.text.x=element_text(size=18, face="bold"), axis.text.x =element_text(size=16,angle=30, hjust=1,face="bold"),axis.text.y=element_text(size=18), axis.title.x=element_blank(),axis.title.y=element_text(size=12), legend.title=element_blank(),legend.text=element_text(size=20,face="bold"))
#> Error in ggplot(transform(facet45, DOSYA = factor(DOSYA, levels = c("var1", : "ggplot" fonksiyonu bulunamadı
#> Error in ggplot(transform(facet45, DOSYA = factor(DOSYA, levels = c("var1", : "ggplot" fonksiyonu bulunamad?
```

<sup>Created on 2018-11-20 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>
.

**Comment by hadley** [comment]
That probably means you didn't include `library(ggplot2)` in your reprex.
