### ISSUE TITLE
Regression: stat_ellipse() broken

### ISSUE THREAD

**Issue by clauswilke** [tidyverse/ggplot2#3014]
I just noticed that `stat_ellipse()` has stopped working. I guess we don't have a regression test for it.
``` r
library(ggplot2)

ggplot(faithful, aes(waiting, eruptions)) +
  geom_point() +
  stat_ellipse()
#> Warning: Computation failed in `stat_ellipse()`:
#> Elements must be named
```

![](https://i.imgur.com/8HBhzVg.png)

<sup>Created on 2018-11-25 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

It is still working in ggplot2 3.1.0. However, it is shown broken in the documentation: https://ggplot2.tidyverse.org/reference/stat_ellipse.html

**Comment by thomasp85** [comment]
This seems to be the new data frame constructor... I'll fix it and add an ellipsis unit test

**Comment by powerguo** [comment]
Any ideas when this fix will be in master or when the next update of ggplot2 will be with this fix? 

Thanks!

**Comment by powerguo** [comment]
> @powerguo
> 
> > Any ideas when this fix will be in master
> 
> This issue is closed because this is already fixed in master. Do you mean you are still seeing the similar problems with the latest development version of ggplot2? If so, please file a new issue with the reprex. Thanks.

Oh sorry that's not what I meant. I haven't tried to install the latest dev version of ggplot2 yet. I was just curious if I can find the fix in the latest version. Thank you for confirming!
