### ISSUE TITLE
Invalid filename error with ggsave after saving in a folder with a percentage sign (%)

### ISSUE THREAD

**Issue by danielsjf** [tidyverse/ggplot2#3016]
When using `ggsave`, I get an invalid filename error on Windows 7 when I include a percentage in the filename.

```r
library(ggplot2)

# create a temporary folder
folder <- tempdir()

# create a plot
p <- ggplot(mtcars, aes(x = mpg, y = cyl)) +
  geom_point()

# save the plot in the temporary folder
ggsave(file.path(folder, "test.png"), p)
#> Saving 7 x 5 in image

# create folder with percentage (%) in the name
folder_perc <- file.path(folder, "perc%")
dir.create(folder_perc)

# show error in this new subfolder
ggsave(file.path(folder_perc, "test.png"), p)
#> Saving 7 x 5 in image
#> Error in grDevices::png(..., res = dpi, units = "in"): invalid 'filename'
```

**Comment by hadley** [comment]
You need to use `%%` 

We need to document this, adapting the text from (e.g.) `png()`

> the name of the output file. The page number is substituted if a C integer format is included in the character string, as in the default. (The result must be less than PATH_MAX characters long, and may be truncated if not. See postscript for further details.) Tilde expansion is performed where supported by the platform.

**Comment by clauswilke** [comment]
I would not have been able to figure this out from the description in the `png()` documentation. I suggest we write something more explicit, e.g.:

> Filenames with page numbers can be generated by including a C integer format expression, such as `%03d` (as in the default file name for most R graphics devices, see e.g. [`png()`]). Thus, `filename = "figure%03d.png"` will produce successive filenames `figure001.png`, `figure002.png`, `figure003.png`, etc. Write `%%` if you want a filename to contain the % sign. For example, `filename = "figure-100%%.png"` will produce the filename `figure-100%.png`.

**Comment by danielsjf** [comment]
While it might be documented, it is not very discoverable, even if it was documented under ggsave. Would it not be possible to capture this behaviour and just output the normal %? Alternatively, a more helpful error message could be a way out.

**Comment by hadley** [comment]
@danielsjf people likely depend on this behavour; so no. Generally, putting `%` in a file name is a bad idea anyway.
