### ISSUE TITLE
Typo in error message for ggplot and pipes 

### ISSUE THREAD

**Issue by chambox** [tidyverse/ggplot2#3020]
.

---
The problem is simple, just a typo in the error message. Notice that the error reads: Anonymouse functions myst be parentherized. It should be must. Thanks once again for ggplot!!!!

```r
train_%>%ggplot(aes(x=target%>%function(x)x^2%>%log()))+geom_histogram(bins=120)
Error: Anonymous functions myst be parenthesized
```

**Comment by karawoo** [comment]
It looks right to me in your example, it says "anonymous", not "anonymouse". Either way, that error is coming from magrittr, not ggplot2: https://github.com/tidyverse/magrittr/blob/0a76de20e67cfeb1c811d6119c55c781951d8410/R/split_chain.R#L37

**Comment by karawoo** [comment]
Oh whoops, I misread where the typo was. Regardless, it's been fixed in magrittr already. You might want to update your packages to see the fix.
