### ISSUE TITLE
Allow ggsave to create directory if path doesn't exist

### ISSUE THREAD

**Issue by wongjingping** [tidyverse/ggplot2#3021]
Motivation: when handed over code, sometimes users have a separate directory for chart outputs that isn't version controlled. That could cause scripts to fail unexpectedly in other environments when the project is pulled, because the charts folder doesn't get created when git pulls it. Example directory structure illustrating problem:
```
my_project (local)
 - charts (not version controlled)
 - scripts (version controlled)

my_project (new environment from a git clone/pull)
 - scripts (version controlled)
```
While there are other solutions to enforce directory structures, I was thinking a relatively painless solution is to allow `ggsave` to have an argument that would allow users to create a path if the path doesn't exist and then export the chart image there. Sounds good?

I can implement this, should be a fairly quick patch :)

**Comment by ptoche** [comment]
Wouldn't that potentially create a whole hierarchy of directories in an environment where it wasn't intended to be? Also, perhaps, adds overhead? You could create your own ``ggsave2()`` and overwrite ``ggsave`` for those projects where you want to create directories automatically?

**Comment by romunov** [comment]
I think each user should be responsible for creating the appropriate folder structure. There are many workflow packages available to aid in this, if `dir.create()` is too much to type.

**Comment by wongjingping** [comment]
sounds good, thanks!
