### ISSUE TITLE
geom_raster plots differently than geom_tile

### ISSUE THREAD

**Issue by sebneus** [tidyverse/ggplot2#3025]
geom_raster plots differently than geom_tile
---
R version 3.4.4 
ggplot2 version 3.1.0

geom_raster spreads out to factors which are not included in the data set but in the levels. geom_tile does it correctly.

```r
library(tidyverse)
library(ggplot2)

p <- tibble(x = factor(c("A", "D", "G"), levels = LETTERS), 
            y = factor(c("b", "e", "z"), levels = letters), 
            fill = 1:3) %>% 
ggplot(aes(x, y, fill = fill)) + 
scale_x_discrete(drop = F) + 
scale_y_discrete(drop = F)

p + geom_raster() + labs(title="raster")
p + geom_tile() + labs(title="tile")
```
![grafik](https://user-images.githubusercontent.com/45633379/49526404-0795f200-f8b0-11e8-8527-623adf03a255.png)
![grafik](https://user-images.githubusercontent.com/45633379/49526440-17153b00-f8b0-11e8-8e05-fbe02c42cd78.png)

**Comment by yutannihilation** [comment]
Here's a more minimal reprex.

``` r
library(ggplot2)

d <- data.frame(x = factor(letters[1:4]))

p <- ggplot(data.frame(), aes(x, x, fill = x)) + 
   geom_raster() +
   scale_x_discrete(drop = F) + 
   scale_y_discrete(drop = F) +
   scale_fill_discrete(drop = F)

patchwork::wrap_plots(
   p %+% d,
   p %+% d[c(1,3), , drop = FALSE]
)
```

![](https://i.imgur.com/MJowz4w.png)

<sup>Created on 2018-12-06 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

Currently, `geom_raster()` assumes all elements are placed side by side and there's no empty line. I come up with a fix for this, but it may be tricky... Maybe this should be left as a limitation?

https://github.com/tidyverse/ggplot2/blob/4a607caeffcb52c686597b651d99fc0252ff8786/R/geom-raster.r#L70-L77

**Comment by thomasp85** [comment]
`geom_raster` assumes evenly spaced points so it makes sense that it does what it does... I don't think this geom is provided for use with anything but true raster data as the requirements are quite strict. You should use `geom_tile` whenever you don't have a complete and even grid...

**Comment by yutannihilation** [comment]
Honestly, I want to make geom_tile() throw errors for discrete data. But, I'm afraid the change would break many existing codes. So, if we keep allowing discrete values, I want to stop raster cells overflow to the neighbourings at least.

**Comment by thomasp85** [comment]
Yeah - erring out would probably be most sensible... but in liue of that I can understand the motivation for #3028

**Comment by dan-reznik** [comment]
i just spent 2hrs trying to figure out why geom_raster was filling blanks between unlisted pixels... i guess the above is the reason

**Comment by thomasp85** [comment]
Just wondered whether it would make sense to make a fill_blanks stat for this..?

I generally think that the raster geom does the right thing. It is intended for fast plotting of larger raster data and should thus do minimal work on the data...

**Comment by dan-reznik** [comment]
thomas i think it would be more natural for geom_raster accept a logical parameter (full_grid) which would switch it into a mode that did not assume a full_grid is specified

**Comment by yutannihilation** [comment]
> Just wondered whether it would make sense to make a fill_blanks stat for this..?

Sounds nice. Using Stats seems the right direction to me (though I'm not immediately sure if this is acceptable in terms of implementation).

**Comment by teunbrand** [comment]
This case now throws the warning:

``` r
#> Warning: Raster pixels are placed at uneven horizontal intervals and will be shifted
#> ℹ Consider using `geom_tile()` instead.
```

And I think that suffices to alert users to potential problems.
