### ISSUE TITLE
theme axis.line does nothing

### ISSUE THREAD

**Issue by hwt** [tidyverse/ggplot2#3027]
This does nothing in ggplot2_3.1.0 (also tried in an older installation with version 2.2.1 where it works as intended):

p1 <- ggplot(mtcars, aes(wt, mpg)) +
  geom_point() +
  labs(title = "Fuel economy declines as weight increases")

p1 + theme(axis.line = element_line(size = 3, colour = "red"))

**Comment by yutannihilation** [comment]
This worked for me. Could you provide a [reprex](https://reprex.tidyverse.org/articles/articles/learn-reprex.html)?

``` r
library(ggplot2)

p1 <- ggplot(mtcars, aes(wt, mpg)) +
  geom_point() +
  labs(title = "Fuel economy declines as weight increases")

p1 + theme(axis.line = element_line(size = 3, colour = "red"))
```

![](https://i.imgur.com/YVhthE3.png)

<sup>Created on 2018-12-06 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by hwt** [comment]
Sorry, you are right. If I restart R it works no problem. Must be one of the other loaded packages in the session that is causing the problem. I have closed the issue. 

Best regards,
Hanni

**Comment by yutannihilation** [comment]
Thanks for confirming!

BTW, reprex package is really helpful for these kind of troubleshooting since it runs code on a fresh session. Please consider using this next time you report a issue :)

https://reprex.tidyverse.org/articles/articles/learn-reprex.html
