### ISSUE TITLE
scale_shape_identity doesn't work with guide = 'legend'

### ISSUE THREAD

**Issue by caayala** [tidyverse/ggplot2#3029]
Related to issue #402 and #2112, `scale_shape_identity` works with a continues variable but with the legend attribute, it doesn't.

``` r
library(ggplot2)

df2 <- data.frame(x = 1:5 , y = 1:10, z = 1:10)
s <- ggplot(df2, aes(x = x, y = y))
s + 
  geom_point(aes(shape = z), size = 4) + 
  scale_shape_identity(guide = 'legend')
#> Error: Continuous value supplied to discrete scale
```

![](https://i.imgur.com/DWMRD1X.png)

<sup>Created on 2018-12-07 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by clauswilke** [comment]
Looks like a typo in line 84: https://github.com/tidyverse/ggplot2/blob/4a607caeffcb52c686597b651d99fc0252ff8786/R/scale-identity.r#L82-L84

For a continuous scale, the last argument should be `super = ScaleContinuousIdentity`.

As a workaround, use `scale_continuous_identity()`:

``` r
library(ggplot2)

df2 <- data.frame(x = 1:5 , y = 1:10, z = 1:10)
s <- ggplot(df2, aes(x = x, y = y))
s + 
  geom_point(aes(shape = z), size = 4) + 
  scale_continuous_identity(aesthetics = 'shape', guide = 'legend')
```

![](https://i.imgur.com/Zpp2oKf.png)

<sup>Created on 2018-12-07 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by malcolmbarrett** [comment]
I'll work on this
