### ISSUE TITLE
Errorbars are not drawn if they extend outside of limits

### ISSUE THREAD

**Issue by martin-ueding** [tidyverse/ggplot2#3032]
ggplot2 version: 3.1.0

---

When I start with a plot with errorbars, it works just fine:

```r
library(ggplot2)

data = data.frame(x = 1:10, y = 1:10, dy = 1:10)

plot = ggplot(data, aes(x = x, y = y)) +
    geom_point() +
    geom_errorbar(aes(ymin = y - dy, ymax = y + dy))
```

![plot-unrestricted](https://user-images.githubusercontent.com/976924/49748109-25df6180-fca5-11e8-9ddf-b62976c5635e.png)

But when I restrict the limits of the plot, the errorbars which would extent outside of the plot region vanish:

```
plot2 = plot +
    ylim(0, 10)
```

![plot-restricted](https://user-images.githubusercontent.com/976924/49748116-28da5200-fca5-11e8-864c-8618ca1f8421.png)

I would expect to still see the errorbars. We often have plots where some points have really small errors, and when the horizontal cross-bar is smaller than the point marker, one cannot distinguish points with vanishing error and from points with extremely large errors.

For reference, this is how Matplotlib does the same plot:

```python
import matplotlib.pyplot as pl
import numpy as np

x = np.arange(1, 11)
y = x
dy = x

pl.errorbar(x, y, dy, marker='o', linestyle='none')
pl.ylim(0, 10)
pl.savefig('plot-matplotlib.png')
```

![plot-matplotlib](https://user-images.githubusercontent.com/976924/49748435-efeead00-fca5-11e8-9ba7-94d59bb4abcf.png)

I would wish that ggplot does this similarly.

**Comment by clauswilke** [comment]
This is working as designed. See e.g. the bottom right corner of the ggplot2 cheatsheet:
https://www.rstudio.com/wp-content/uploads/2015/03/ggplot2-cheatsheet.pdf
