### ISSUE TITLE
unwanted line overlapping x-axis produced by geom_density line plot

### ISSUE THREAD

**Issue by foehnwind** [tidyverse/ggplot2#3036]
When using geom_density line plot, an unwanted line overlapping x-axis is shown. This "issue", reprex and workarounds have been described in great detail at https://stackoverflow.com/questions/49593634/unintended-line-across-x-axis-of-density-plot-r thanks to the original poster and answerer, hence no reprex is shown here. It can be reproduced with ggplot2 v3.1.0. 

Here, I wonder if this behavior is indeed an issue, or a feature by design. Thanks.

**Comment by yutannihilation** [comment]
This is by design, as answered on SO:

> `geom_density()` creates a polygon, not a line.

**Comment by foehnwind** [comment]
@clauswilke, very neat solution! Thanks.
