### ISSUE TITLE
geom_tile borders missing notch at top left corners

### ISSUE THREAD

**Issue by DanielReedOcean** [tidyverse/ggplot2#3037]
This is an issue that has been discussed over at Stackoverflow. The original problem can be found [here](https://stackoverflow.com/questions/53767758/geom-tile-border-missing-at-corners). A minimal reprex is included below.

I have the following data frame:

    # Dummy data frame
    df <- expand.grid(x = 1:3, y = 1:3)
    
I would like to plot it as a `geom_tile` using `ggplot2` like so:

    # Tile plot
    ggplot(df) + 
      geom_tile(aes(x = x, y = y), 
                fill = NA, colour = "red", size = 3, width = 0.7, height = 0.7)

which gives, 

![rplot](https://user-images.githubusercontent.com/11167566/50006121-1735ca80-ff83-11e8-8d6c-9101faf1613b.png)

Notice that in the top left corner of each tile the border has a notch missing and that the corner doesn't dovetail nicely like the other corners. The outcome I expected was a square around each tile, perhaps something like this:

![rplot01](https://user-images.githubusercontent.com/11167566/50006285-a3e08880-ff83-11e8-82e0-8ececb039454.png)

A solution offered [here](https://stackoverflow.com/a/53778706/1552004)  by Z. Lin in that Stackoverflow thread suggests that `linejoin` and `lineend` for `geom_tile` are switched to `mitre` and `square`, respectively. Or, that they are at least offered as parameters in the `geom` so that the user can choose for themselves. Hopefully, this demonstrates my issue adequately, but please let me know if I can clarify any aspect.

**Comment by yutannihilation** [comment]
> Or, that they are at least offered as parameters in the geom so that the user can choose for themselves.

Thanks, agreed.

**Comment by ptoche** [comment]
Just a comment in passing. Ignore if off topic. 

from https://github.com/tidyverse/ggplot2/blob/master/R/geom-tile.r

the first few lines:

#' `geom_rect` and `geom_tile` do the same thing, but are
#' parameterised differently: `geom_rect` uses the locations of the four
#' corners (`xmin`, `xmax`, `ymin` and `ymax`), while
#' `geom_tile` uses the center of the tile and its size (`x`,
#' `y`, `width`, `height`).

which is precisely the problem with ``geom_title``. 

Can you achieve your goal with ``geom_rect`` instead?

**Comment by yutannihilation** [comment]
I don't think it matters.

``` r
library(ggplot2)

df <- expand.grid(x = 1:3, y = 1:3)
width <- 0.7
height <- 0.7

df$xmin <- df$x - width / 2
df$xmax <- df$x + width / 2
df$ymin <- df$y - height / 2
df$ymax <- df$y + height / 2

ggplot(df) + 
  geom_rect(aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax), 
            fill = NA, colour = "red", size = 3)
```

![](https://i.imgur.com/ANVvzDw.png)

<sup>Created on 2018-12-16 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by thomasp85** [comment]
The problem is that the rectangles gets converted to polygons in closed form (first point gets repeated in the end), whereas polygonGrob expect an open representation... should be fairly easy to fix here:

https://github.com/tidyverse/ggplot2/blob/9eae13b3d17bde26cf9df649887b4a6bb2ac92ce/R/geom-rect.r#L75-L80

Note that this line also need to be adapted 
https://github.com/tidyverse/ggplot2/blob/9eae13b3d17bde26cf9df649887b4a6bb2ac92ce/R/geom-rect.r#L42

**Comment by thomasp85** [comment]
On that note I don't think it makes sense to add a lineend parameter to the geoms as they should be closed, while adding linejoin is sensible...

@yutannihilation can you update #3050 to create the correct polygon spec and remove lineend? I'm pretty sure it will break some visual tests, but it'll be more correct

**Comment by yutannihilation** [comment]
> whereas polygonGrob expect an open representation... 

Opps, I didn't notice... Thanks, it makes sense. I will update so.

**Comment by thomasp85** [comment]
It's a weird bug... probably a leftover from when the other representation made sense... recall anything @hadley ?

**Comment by karawoo** [comment]
FYI it also seems to be inconsistent, I can't reproduce with the reprex provided

``` r
df <- expand.grid(x = 1:3, y = 1:3)
library("ggplot2")
ggplot(df) +
  geom_tile(aes(x = x, y = y),
            fill = NA, colour = "red", size = 3, width = 0.7, height = 0.7)
```

![](https://i.imgur.com/65quZMg.png)

<sup>Created on 2019-01-15 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by ptoche** [comment]
I (too) get this:

<img width="1193" alt="plot" src="https://user-images.githubusercontent.com/6339274/51193078-f87c7800-1922-11e9-9286-cbe629b38d3b.png">

Specs summary:
ggplot2_3.1.0.9000
grid_3.5.2
gtable_0.2.0
R version 3.5.2 (2018-12-20) -- "Eggshell Igloo"
Platform: x86_64-apple-darwin15.6.0 (64-bit)

**Comment by DanielReedOcean** [comment]
In response to the original SO question, someone else commented that they couldn't reproduce the issue on macOS either. @karawoo are you running on macOS, too?

**Comment by yutannihilation** [comment]
Curious. Visual tests pass even on my Windows, so I guess this is a problem on Windows' graphic device?

**Comment by yutannihilation** [comment]
It seems we still need `lineend` even after fixing the polygon representation. Here's the result after https://github.com/tidyverse/ggplot2/pull/3050/commits/43eafa85634156fe35901e5c732ee3900c5c0449:

``` r
library("ggplot2")

ggplot(data.frame(x = 1)) +
  geom_tile(aes(x, x),
            fill = NA, colour = "red", size = 10,
            width = 1, height = 1) +
  coord_equal()
```

![](https://i.imgur.com/91qTvaU.png)

<sup>Created on 2019-01-25 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by thomasp85** [comment]
o_O - that does not make any sense at all... maybe this is a windows issue (assuming that you're on windows...

what do you get if you run:

```r
grid::grid.rect(width = unit(.5, 'npc'), height = unit(0.5, 'npc'), gp = grid::gpar(lwd = 20, linejoin = 'mitre'))
```

**Comment by yutannihilation** [comment]
Oh... Here's the result.

``` r
library(grid)
grid.rect(width = unit(.5, 'npc'), height = unit(0.5, 'npc'), gp = gpar(lwd = 20, linejoin = 'mitre'))
```

![](https://i.imgur.com/C4GPogi.png)

<sup>Created on 2019-01-25 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by thomasp85** [comment]
ok, that is not what I get (i.e. I get even corners all around)

This is a grid bug (or even a windows device bug) - @pmur002 do you have any idea where this comes from..?

**Comment by yutannihilation** [comment]
Hmm, thanks. Sorry that I haven't noticed this is the problem on Windows more earlier...

**Comment by pmur002** [comment]
I see it (only on Windows).  This appears to be a bug (or at least a poor design choice) in *graphapp* (that underlies the Windows device).  graphapp's rectangle drawing draws a polyline, so what we are seeing is a line being drawn from the top-left corner around the perimeter of the rectangle.  So the rounded top-left corner is round because of the rounded line start and end.  You can work around the problem by specifying "square" lineend for the rectangle (which you should not have to do) - is that a possibility ?  Code below shows what I mean for the simple grid.rect() demonstration 

```
library(grid)
grid.rect(width = unit(.5, 'npc'), height = unit(0.5, 'npc'), gp = gpar(lwd = 20, linejoin = 'mitre', lineend = 'square'))
```

**Comment by yutannihilation** [comment]
Thanks!

> You can work around the problem by specifying "square" lineend for the rectangle (which you should not have to do) - is that a possibility?

I think it's possible, since we already specify `lineend` for rect (from [the very beginning](https://github.com/tidyverse/ggplot2/commit/a916e7d9fcd1e20234ccb1bc1012624d3fb72853#diff-5288042192750f1f50324d84423ac538R29)), we can just change this to `"square"`.

https://github.com/tidyverse/ggplot2/blob/256b26ab70c87d760d92ceadd67b549dae74a06a/R/geom-rect.r#L61
