### ISSUE TITLE
theme(x, y) versus theme(x) + theme(y)

### ISSUE THREAD

**Issue by ptoche** [tidyverse/ggplot2#3039]
I had always assumed that the following were equivalent. They are not. Is it a feature of theming that all the options must be set in ``theme()`` in one pass? 

If so, may I suggest adding an example like below to: https://ggplot2.tidyverse.org/reference/theme.html

``` r
library(reprex)

library(ggplot2)
ggplot(mtcars, aes(wt, mpg)) +
    geom_point() +
    theme_void() + 
    theme(axis.line.x = element_line(color = "blue"),
          axis.ticks.x = element_line(color = "red"),
          axis.ticks.length = unit(1, "cm")) 
```

![](https://i.imgur.com/MT2ctVw.png)

<sup>Created on 2018-12-15 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

``` r
library(reprex)
library(ggplot2)
ggplot(mtcars, aes(wt, mpg)) +
    geom_point() + 
    theme_void() + 
    theme(axis.line.x = element_line(color = "blue")) +
    theme(axis.ticks.x = element_line(color = "red")) +
    theme(axis.ticks.length = unit(1, "cm")) 
```

![](https://i.imgur.com/K86sagq.png)

<sup>Created on 2018-12-15 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by ptoche** [comment]
Perhaps the same issue: To display the axis line, I need to set ``axis.ticks.length``. Change ``unit(1, "cm")`` to ``unit(0, "cm")`` or drop that last line altogether and the axis line disappears. 

    ggplot(mtcars, aes(wt, mpg)) +
        geom_point() +
        theme_void() + 
        theme(axis.line.x = element_line(color = "blue"),
               axis.ticks.length = unit(1, "cm"))

**Comment by clauswilke** [comment]
This is a bug with `theme_void()`. It declares itself to be a complete theme but misses elements. This keeps coming up in various ways and the correct way to fix it is to define all theme elements in `theme_void()`. See e.g. #2723.

``` r
library(ggplot2)
p1 <- ggplot(mtcars, aes(wt, mpg)) +
  geom_point() +
  theme_classic() + 
  theme(axis.line.x = element_line(color = "blue"),
        axis.ticks.x = element_line(color = "red"),
        axis.ticks.length = unit(1, "cm")) 

p2 <- ggplot(mtcars, aes(wt, mpg)) +
  geom_point() + 
  theme_classic() + 
  theme(axis.line.x = element_line(color = "blue")) +
  theme(axis.ticks.x = element_line(color = "red")) +
  theme(axis.ticks.length = unit(1, "cm")) 

cowplot::plot_grid(p1, p2)
```

![](https://i.imgur.com/YSASI5y.png)

<sup>Created on 2018-12-15 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by clauswilke** [comment]
Third time is a charm. I think I've found the real culprit: `theme_void()` sets `line = element_blank()`, and that means if downstream elements try to inherit from `line` they don't get reasonable defaults. It's actually surprising that the first example works, and I'm still not sure why. In any case, if `line` is defined appropriately things work as one would expect:

``` r
library(ggplot2)
ggplot(mtcars, aes(wt, mpg)) +
  geom_point() + 
  theme_void() +
  theme(line = element_line(size = 0.5, linetype = 1, lineend = "butt", color = NA)) +
  theme(axis.line.x = element_line(color = "blue")) +
  theme(axis.ticks.x = element_line(color = "red")) +
  theme(axis.ticks.length = unit(1, "cm")) 
```

![](https://i.imgur.com/kcvAG3b.png)

<sup>Created on 2018-12-15 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

This still means `theme_void()` needs to be rethought. I think it should define a standard line element and then set the downstream elements (`axis.line()`, `axis.ticks()`, etc.) to `element_blank()`.

**Comment by clauswilke** [comment]
There seem to be multiple issues at play here. There clearly is a difference between `theme(x, y)` and `theme(x) + theme(y)`, and there shouldn't be.

``` r
library(ggplot2)
p1 <- ggplot(mtcars, aes(wt, mpg)) +
  geom_point() + 
  theme_light() + 
  theme(axis.line.x = element_line(color = "blue")) +
  theme(axis.ticks.x = element_line(color = "red")) +
  theme(axis.ticks.length = unit(1, "cm"))

p2 <- ggplot(mtcars, aes(wt, mpg)) +
  geom_point() + 
  theme_light() + 
  theme(axis.line.x = element_line(color = "blue"),
        axis.ticks.x = element_line(color = "red"),
        axis.ticks.length = unit(1, "cm"))

cowplot::plot_grid(p1, p2)
```

![](https://i.imgur.com/zqs72a2.png)

<sup>Created on 2018-12-15 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by clauswilke** [comment]
The fundamental problem here is that adding themes to the plot object doesn't behave the same as adding themes to each other and seems buggy. Specifically, adding additional theme elements seems to convert parts of an incomplete theme into parts of a complete theme in the plot building process.

``` r
library(ggplot2)

t1 <- theme_light() + 
  theme(axis.line.x = element_line(color = "blue")) +
  theme(axis.ticks.x = element_line(color = "red"))

t2 <- theme_light() + 
  theme(axis.line.x = element_line(color = "blue"),
        axis.ticks.x = element_line(color = "red"))

identical(t1, t2)
#> [1] TRUE

p <- ggplot(mtcars, aes(wt, mpg)) + geom_point()
p1 <- p + theme_light() + 
  theme(axis.line.x = element_line(color = "blue")) +
  theme(axis.ticks.x = element_line(color = "red"))

p2 <- p + theme_light() +
  theme(axis.line.x = element_line(color = "blue"),
        axis.ticks.x = element_line(color = "red"))

identical(p1$theme, p2$theme)
#> [1] FALSE

p1$theme$axis.line.x$inherit.blank # incorrect
#> [1] TRUE
p2$theme$axis.line.x$inherit.blank # correct
#> [1] FALSE

p1
```

![](https://i.imgur.com/v8ju7lA.png)

``` r
p1$theme$axis.line.x$inherit.blank <- FALSE
p1
```

![](https://i.imgur.com/uJCy0r6.png)

<sup>Created on 2018-12-15 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by clauswilke** [comment]
I've tracked it down. When themes are added to the plot the function that is used is `update_theme()`:
https://github.com/tidyverse/ggplot2/blob/9292832e5446d5b0d75875aa0fb607ab40b91f4f/R/plot-construction.r#L103-L105

But when two themes are added together directly, the function is `add_theme()`:
https://github.com/tidyverse/ggplot2/blob/868fdb7c9176be685850a3a698af7acb5e890a4a/R/plot-construction.r#L51

The two functions have different logic, because `update_theme()` pulls in information from the default theme if otherwise missing: 
https://github.com/tidyverse/ggplot2/blob/442108d9d4da34c2e396554cd36f61b41b719602/R/theme.r#L470

I think the right logic would be to first add all the theme parts together with `add_theme()` during plot construction, and only fill in the missing pieces once the plot is built. This fits logically with the changes discussed in PR #2784.

**Comment by ptoche** [comment]
I think we agree this is a bug. How can I add a "bug" label to this issue? Do I need special rights or I have missed the icon on which to click? Currently it says "Labels: 'None yet'". Thanks.
