### ISSUE TITLE
cut_width should be able to take ... for cut.default

### ISSUE THREAD

**Issue by cderv** [tidyverse/ggplot2#3055]
From a question in [community.rstudio.com](https://community.rstudio.com/t/cut-width-labels-false-returns-unused-argument-error/20675) it seems like `cut_width` is the [only one](https://ggplot2.tidyverse.org/reference/cut_interval.html) of the three functions to not take `...` to pass it to `cut.default`

In particular, `labels` argument can not be used with `cut_width`. Just adding `...` would allow this
```r
> cut_width(runif(1000), 0.1, center = 0, labels= FALSE)
  [1]  2  6  9 10  8  7 11  6  6  3 11 11  5  6 10  3  4  8  8 11  2  3  5  2  3  6  8  7  4  6  7 11 10  4 10 11
 [37]  6  5  6  1  3  6  7  1  9  9  3  2  9 11  8  3  8  6 11 10  6  9  4  3  1  8  6  6  5 10  6  9  9  9  8  4
 [73] 11  2  2 10  4  8  9  3  3  3 11 11  4  2  8 11  8 10  5  7 10  2  1  2  6  3  2  2
 [ reached getOption("max.print") -- omitted 900 entries ]
```
or to change labels if the call (could always be done afterward using `forcats`)

I open the issue to reference the question and see if it worth doing. Seems quite easy to be consistent between those three `cut_*` helper in lubridate.

If you're interested I'll do a PR.

**Comment by yutannihilation** [comment]
Thanks, sounds good to me.

`cut_width()` is the last one of the three `cut_*()` functions, implemented by this commit: https://github.com/tidyverse/ggplot2/commit/de18a6ba272c1d883f9d6982844e90d5b5038391. From the commit and the current source code, I see no reason that `cut_width()` cannot take `...`. A PR would be very welcome!

**Comment by cderv** [comment]
Do you want it now or maybe a good fit for <a href="https://github.com/search?q=is%3Aissue+label%3A%22tidy-dev-day+%3Anerd_face%3A%22"><img src="https://github.com/tidyverse/dev-day-2019/raw/master/img/tidy-dev-day-issue-label.png" style="height:24px;border:0;" alt-text="tidy-dev-day" aria-label="Tidyverse Developer Day rstd.io/tidy-dev-day"></a> ? 😉

**Comment by yutannihilation** [comment]
Ah, I'm not the one to label "tidy-dev-day 🤓," but I agree it's a good fit. Let's wait for the review...

https://github.com/tidyverse/dev-day-2019/issues/12

**Comment by thomasp85** [comment]
tidy verse dev day has come and gone so this is up for grabs... @cderv do you want in?

**Comment by cderv** [comment]
Yep I can jump in on this. Count me in !
