### ISSUE TITLE
Possible bug with geom_histogram

### ISSUE THREAD

**Issue by tcastrosantos** [tidyverse/ggplot2#3058]
I want to generate a histogram with data of 2 classes (Event=0 vs. Event=1). In my case I have only one case where Event=0. The histogram plots correctly if I do not invoke the 'fill=' aesthetic, but drops the Event=0 case when I do invoke 'fill'. The problem goes away when I scale Y continuous, but I want to use the log10 scale. To demonstrate (I am using current versions of R, RSTudio, and associated packages):
```r
# insert reprex here

library(ggplot2)

Dur<-c(200,200,200,200,10,20,30)
Event<-c(0,1,1,1,1,1,1)
a<-data.frame(cbind(Dur,Event))
a$Event1<-as.character(a$Event)

p<-ggplot(data=a,aes(x=Dur,fill=Event1))+
  geom_histogram(color='black')+
  scale_fill_manual(values=c("red","blue"),name='Censor')+
  scale_y_log10()+
  labs(title='Attempt Duration: WAL',x="Duration (s)")
p

#Note the difference if we drop the fill aesthetic:

p<-ggplot(data=a,aes(x=Dur))+
  geom_histogram(color='black')+
  scale_fill_manual(values=c("red","blue"),name='Censor')+
  scale_y_log10()+
  labs(title='Attempt Duration: WAL',x="Duration (s)")
p

#Dropping the y-log scale also works, as does including a second case where Event==0


Dur<-c(200,200,200,200,10,20,30)
Event<-c(0,0,1,1,1,1,1)
a<-data.frame(cbind(Dur,Event))
a$Event1<-as.character(a$Event)

p<-ggplot(data=a,aes(x=Dur,fill=Event1))+
  geom_histogram(color='black')+
  scale_fill_manual(values=c("red","blue"),name='Censor')+
  scale_y_log10()+
  labs(title='Attempt Duration: WAL',x="Duration (s)")
p

```

**Comment by clauswilke** [comment]
Could you please run this through the reprex package and post the result? I don't see any problems when I run your code on my machine.

**Comment by tcastrosantos** [comment]
I am a novice on github and apologize if I am not formatting correctly .  It would help if I could post the figures I am getting.  

I have not used reprex before, but I ran it and it produced this (but note the errors because it doesn't recognize the ggplot library which is loaded).  When I add library(ggplot2) I get an error.   First, here it is with ggplot loaded in RStudio, but not invoked explicitly here:


Dur<-c(200,200,200,200,10,20,30)
Event<-c(0,1,1,1,1,1,1)
a<-data.frame(cbind(Dur,Event))
a$Event1<-as.character(a$Event)

p<-ggplot(data=a,aes(x=Dur))+#For somereason this: ,fill=Event1 causes the histogram to drop the one censored observation.  Very annoying.
  geom_histogram(color='black')+
  scale_fill_manual(values=c("red","blue"),name='Censor')+
  scale_y_log10()+
  labs(title='Attempt Duration: WAL',x="Duration (s)")
#> Error in ggplot(data = a, aes(x = Dur)): could not find function "ggplot"
p
#> Error in eval(expr, envir, enclos): object 'p' not found

#Note difference in histogram when I invoke fill=
p<-ggplot(data=a,aes(x=Dur,fill=Event1))+
  geom_histogram(color='black')+
  scale_fill_manual(values=c("red","blue"),name='Censor')+
  scale_y_log10()+
  labs(title='Attempt Duration: WAL',x="Duration (s)")
#> Error in ggplot(data = a, aes(x = Dur, fill = Event1)): could not find function "ggplot"
p
#> Error in eval(expr, envir, enclos): object 'p' not found



Then if I add library(ggplot2) or require(ggplot2) I get this error:

Rendering reprex...
Error in loadNamespace(name) : there is no package called 'httr'

**Comment by tcastrosantos** [comment]
OK I managed to get reprex to work (needed additional packages)...but now am not sure how paste the output.  Here I have printed to a pdf and embedded the pdf...
[reprex output.pdf](https://github.com/tidyverse/ggplot2/files/2729833/reprex.output.pdf)

Those warnings are to be expected because of the empty bins.....the problem I am having shows in the plots.

**Comment by clauswilke** [comment]
I see now what you are concerned about, and the simple answer is that what you're trying to do can't be done in a meaningful way. Fundamentally, the problem is that log(x) + log(y) is not the same as log(x+y), therefore it matters whether you first log transform and then add (as you do when filling by color) or add first and then log transform (as you do when you don't fill).

I strongly recommend that you don't use a log y scale for stacked histograms.

**Comment by tcastrosantos** [comment]
So if I understand your response correctly, it seems to suggest that the stacked item is out of scale because of how ggplot transforms the values, e.g. log(1) = 0 so if it adds that to the 3 event=1 cases it adds zero instead of bringing the value up to log(4)?.    You have convinced me about the folly of logging stacked histograms.
