### ISSUE TITLE
add `plot(last_plot())` in function examples to make pkgdown website more vivid

### ISSUE THREAD

**Issue by dongzhuoer** [tidyverse/ggplot2#3064]
pkgdown's biggest feature is including output of examples, which is especially useful for ggplot.

But only plots which are automatically printed can be displayed in the pkgdown website. For some cases, like https://ggplot2.tidyverse.org/reference/borders.html

```r
if (require("maps")) {

    ggplot() + ...

    ggplot() + ... + ...

    ggplot() + ... + ...
}
```

only the last plot (returned by `if` statement) is displayed
![image](https://user-images.githubusercontent.com/15871952/51069083-22a01280-1663-11e9-866d-7cf4783651cd.png)

**Comment by dongzhuoer** [comment]
I suggest that in `@examples`, use

```r
if (require("maps")) {

    ggplot() + ...
    plot(last_plot())

    ggplot() + ... + ...
    plot(last_plot())

    ggplot() + ... + ...
    plot(last_plot())

    NULL
}
```

so that reader can see every output.

**Comment by sowla** [comment]
I'd like to claim this :)
