### ISSUE TITLE
Consistent values of default aes in stats and geoms

### ISSUE THREAD

**Issue by ptoche** [tidyverse/ggplot2#3065]
Default aes, as defined inside ``default_aes`` is not entirely consistent across the different stats and geoms found In ``stat-*.r`` and ``geom-*.r``. For instance, ``geom-smooth`` uses ``alpha = 0.4`` while ``scale-viridis.r`` uses ``alpha = 1``.  Many other geoms, however, set a default ``alpha = NA``. 

Examples: ``"geom-path.r"``, ``"geom-segment.r"``, ``"geom-curve.r"``, ``"geom-abline.r"`` set 

    default_aes = aes(colour = "black", size = 0.5, linetype = 1, alpha = NA)

**Is there a case for being consistent?**

Does anyone feel there should be a guideline about "preferred" values? Or even a "global" ``gg_default_aes`` that stats and geoms could refer to? 

If I extend an existing stat or geom to accept ``alpha``, is there a preference for setting ``alpha = NA`` or may I set anything I like, e.g. ``alpha = 0.35``?

If I create a new stat or geom, (when/why) should I feel bound by ``size = 0.5`` or ``colour = "black"``? How about the popular ``fill = grey20``? 

Here are example of different values in default ``fill``: 

 - ``"geom-polygon.r"`` has ``default_aes = aes(colour = "NA", fill = "grey20", size = 0.5, linetype = 1, alpha = NA)``
 - ``"geom-rect.r"`` has ``aes(colour = NA, fill = "grey35", size = 0.5, linetype = 1, alpha = NA)``

Both ``"geom-polygon.r"`` and ``"geom-rect.r"`` define "fundamental" geoms. Yet they use different default ``fill`` values. 

Together with an unusual default for ``alpha``, ``"geom-smooth.r"`` uses an unusual default ``fill``:

 - ``"geom-smooth.r"`` has ``default_aes = aes(colour = "#3366FF", fill = "grey60", size = 1, linetype = 1, weight = 1, alpha = 0.4)``

It also sets a line of ``size = 1``, which is twice the usual size. 

Other examples: 

 -  ``"geom-boxplot.r"`` has: ``colour = "grey20", fill = "white"``
 - ``"geom-tile.r"`` has: ``fill = "grey20", colour = NA, size = 0.1, linetype = 1``
- ``"geom-contour.r"`` has: ``colour = "#3366FF"``
- ``"geom-quantile.r"`` has ``colour = "#3366FF"``

**Comment by thomasp85** [comment]
There is no intention in ggplot2 to keep the defaults consistent across geoms/stats. The defaults are chosen out of consideration for each geom and it makes little sense to make them all the same

**Comment by ptoche** [comment]
Thanks. So no guidelines or suggestions at all? 

For instance, if I extend an existing geom that currently supports only ``colour`` (default ``colour = "black"``) with a ``fill`` and ``alpha``, which would you recommend I choose:

   ..., fill = "grey20", alpha = 0.4, ...

   ..., fill = "grey20", alpha = NA,...

   ..., fill = NA, alpha = NA,...

No preference at all?

Thanks.

**Comment by yutannihilation** [comment]
I too think it totally depends on the type of Geom/Stat what default values are visually sound. For example, 

> is there a preference for setting `alpha = NA` or may I set anything I like, e.g. `alpha = 0.35`?

this depends on your preference to draw it untransparent, or half-transparent, or not to draw. We cannot recommend you any default values until we hear what geom you are to implement.

To be fair, I agree some of your examples might be actually inconsistent, and we might be able to make it better, but I'm sure the changing defaults would break existing codes. I don't feel this is worth changing.

**Comment by ptoche** [comment]
Thanks Thomas, thanks Hiroaki.

Think of the geom as a special case of a ``GeomPolygon``, say. 

My preference would be to set ``fill = "grey20", alpha = 0.5``, because then I can just call ``geom_*(fill = "red")`` to get a transparent fill, instead of needing to set ``alpha`` explicitly, as in ``geom_*(fill = "red", alpha = 0.5)``.  Reasonable?

Unless there is a discussion over the next couple of days, feel free to close.

**Comment by clauswilke** [comment]
I agree with Thomas that different geoms can have different defaults. At the same time, I'd like to point to PR #2749, which is an effort to set geom defaults more systematically as part of a theme.

**Comment by dpseidel** [comment]
Yes thanks Claus, I was going to mention 2749 as well. I'm hoping to make fresh progress on it next week in time for tidyverse dev day.

**Comment by ptoche** [comment]
I'm closing since #2749 addresses the problem. Thanks to all for your comments.
