### ISSUE TITLE
data.frame override hinders local development

### ISSUE THREAD

**Issue by karawoo** [tidyverse/ggplot2#3067]
One consequence of `data.frame()` being overridden to throw an error (#2994) is that if I've loaded ggplot2 with `devtools::load_all()` I can't run any reprexes that use `data.frame()`. So if I'm working on a bug and have been given the following reprex:

```r
library("ggplot2")
dat <- data.frame(x = c("a", "b"), y = 1:6)
ggplot(dat, aes(x = x)) +
  geom_bar()
```

I can't check my bug fix by running the reprex without changing the call to `data.frame()` and rewriting the code to avoid recycling. 

I definitely see the value of avoiding any use of `data.frame()` _within_ the ggplot2 codebase, but it would be really nice for interactive development to not have to rewrite all reprex code that uses `data.frame()`. Is there a good way around this?

**Comment by clauswilke** [comment]
Does `base::data.frame()` work?

Or:
``` r
library("ggplot2")
data.frame <- base::data.frame
...
```
?

**Comment by karawoo** [comment]
oh duh 🤦‍♀️ yes it does
