### ISSUE TITLE
Should facet + empty spec be a noop?

### ISSUE THREAD

**Issue by lionel-** [tidyverse/ggplot2#3070]
Should these be equivalent to `ggplot(mtcars)` instead of failing?

```r
ggplot(mtcars) + facet_wrap(vars())
#> Error: Can't subset with `[` using an object of class NULL.

ggplot(mtcars) + facet_wrap(NULL)
#> Error: Must specify at least one variable to facet by
```

Allowing empty specs would make sense in functions:

```r
my_plot <- function(.data, .mapping, ...) {
  ggplot(.data, .mapping) +
    geom_point() +
    facet_wrap(vars(...))
}
```

Then both of these would work, instead of just the latter:

```r
my_plot(starwars, aes(mass, height / 100))

my_plot(starwars, aes(mass, height / 100), gender)
```

**Comment by thomasp85** [comment]
I think the error messages should be better but I don’t think facet_wrap should change itself to facet_null if the input is lacking.

**Comment by lionel-** [comment]
Why is an error better? I think it makes sense not to error because NULL/empty facets should only occur in programmatic cases. Handling the empty case sensibly makes the layer more composable and generally useful.

**Comment by yutannihilation** [comment]
I think this makes sense, considering `facet_grid()` generates at least 1 row/col even when there are no variables for row/col.

**Comment by thomasp85** [comment]
But in `facet_grid` you ask for this explicitly by providing a `.` at either side of the formula...

I think my major gripe is that this can lead to situation where users mistype the name of the faceting variable and then get this single panel view without any errors or warnings... but @Hadley should be the judge of that...

**Comment by thomasp85** [comment]
Ah - this is purely for `NULL`...

**Comment by thomasp85** [comment]
I don't think 

```r
my_plot <- function(.data, .mapping, ...) {
  facet_vars <- vars(...)
  p <- ggplot(.data, .mapping) +
    geom_point()

  if (length(facet_vars) != 0) {
    p <- p + facet_wrap(facet_vars)
  }
  p
}
```

is too complicated, but of course accepting NULL will be more magical. I just tend to dislike objects changing class (FacetWrap -> FacetNull) based on the input data... ¯\_(o_O)_/¯

**Comment by lionel-** [comment]
I don't think it's changing class. An empty FacetWrap behaves as a FacetNull, which makes sense to me. Just like `character(0)` behaves as `NULL` in some contexts such as concatenation.

**Comment by thomasp85** [comment]
For all intend and purpose it will change class as it will behave just like FacetNull... I'd expect FacetWrap to create panels with strips etc., which will not happen as there is not anything to put in them...

I dunno... I'm against, but not vehemently, so if anyone else weighs in in favour I'll concede...

**Comment by yutannihilation** [comment]
> But in `facet_grid` you ask for this explicitly by providing a `.` at either side of the formula...

You know, it's "for compatibility with the classic interface" as the doc says. Now we have `rows` and `cols` and their defaults are `NULL`.

**Comment by thomasp85** [comment]
fair point...
