### ISSUE TITLE
Broken bibtex on site

### ISSUE THREAD

**Issue by wrightaprilm** [tidyverse/ggplot2#3071]
I have a package in review at [JOSE](https://jose.theoj.org/). Editor @labarba caught during the final renders that it looks like the bibtex entry on the site should be 

@Book{,
  author = {Hadley Wickham},
  title = {ggplot2: Elegant Graphics for Data Analysis},
  publisher = {Springer-Verlag New York},
  year = {2016},
  isbn = {978-3-319-24277-4},
  url = {https://ggplot2.tidyverse.org},
}

but is listed as 

@Book{,
  author = {Hadley Wickham},
  title = {ggplot2: Elegant Graphics for Data Analysis},
  publisher = {Springer-Verlag New York},
  year = {2016},
  isbn = {978-3-319-24277-4},
  url = {https://ggplot2.org},
}

I would have made a pull request to fix it, but it's also an issue when the citation() function is called, and I wasn't sure if they were both drawing the info from the same place.

Thanks!

**Comment by dpseidel** [comment]
Oh great! Yes, we'd welcome a PR. I wonder however if, given this is a citation for the book not the package, perhaps the link should be to https://github.com/hadley/ggplot2-book? or perhaps https://www.springer.com/gp/book/9783319242750? @hadley, what do you think?

**Comment by hadley** [comment]
I think the main website is probably best

**Comment by hadley** [comment]
Data comes from `inst/CITATION` IIRC

**Comment by JamesCuster** [comment]
I will work on this for tidyverse dev day 2019
