### ISSUE TITLE
not-run example in labeller() depends on unimported plyr

### ISSUE THREAD

**Issue by clauswilke** [tidyverse/ggplot2#3083]
When @thomasp85 removed plyr, an example was changed so it doesn't run anymore. Since the example is in `\donttest{}`, the problem doesn't get flagged in automated testing.

The problematic line is here:
https://github.com/tidyverse/ggplot2/blob/f0da3d0cb8d6859976339bdf245f21b48991d640/R/labeller.r#L401

The formatted code in the example looks like this:
``` r
# In the following example, we rename the levels to the long form,
# then apply a wrap labeller to the columns to prevent cropped text
msleep$conservation2 <- revalue(msleep$conservation, conservation_status)
p3 <- ggplot(msleep, aes(x = sleep_total, y = awake)) + geom_point()
p3 +
  facet_grid(vore ~ conservation2,
    labeller = labeller(conservation2 = label_wrap_gen(10))
  )
```
I see three possible fixes. Not sure which one is best:

1. Add `plyr::` back in to that line of code. This would mean plyr has to be listed as suggested package.

2. We write `ggplot2:::revalue()` instead of `revalue()`.

3. We change or delete the example.

**Comment by connorlewis** [comment]
After speaking with @thomasp85, I will fix this issue by changing the example to use base R, instead of any dependency on plyr.
