### ISSUE TITLE
Add  position_voronoi

### ISSUE THREAD

**Issue by eliocamp** [tidyverse/ggplot2#3093]
I saw [this tweet](https://twitter.com/thosjleeper/status/1086763155164983298) about a clever algorithm for labeling points and agreed that an R implementation would be nice. I thought that a natural place to be would be in ggplot2 andcame up with this:

``` r
library(ggplot2)
library(magrittr)

position_voronoi <- ggproto("Position", Position,
   compute_panel =  function(self, data, params, scales) {
     del <- with(data, deldir::deldir(x, y, z = group))$summary
     del$index <- seq_len(nrow(del))
     
     points <- vapply(split(del, del$z), 
                      function(x) x$index[which.max(x$dir.area)], 1)
     data[points, ]
     }
)
```

It computes the voronoi tessellation and for each group selects the point
associated with the biggest area.
As an example:

``` r
d <- data.frame(x = rnorm(30), y = rnorm(30), group = letters[1:3])

d %>% 
  ggplot(aes(x, y)) +
  geom_point(aes(color = group)) + 
  ggrepel::geom_label_repel(aes(color = group, label = group),
                            position = position_voronoi)
#> 
#>      PLEASE NOTE:  The components "delsgs" and "summary" of the
#>  object returned by deldir() are now DATA FRAMES rather than
#>  matrices (as they were prior to release 0.0-18).
#>  See help("deldir").
#>  
#>      PLEASE NOTE: The process that deldir() uses for determining
#>  duplicated points has changed from that used in version
#>  0.0-9 of this package (and previously). See help("deldir").
```

![](https://i.imgur.com/TUc66H1.png)

If you think is a good fit for ggplot2, I can make a PR. If not, where should
it be?

<sup>Created on 2019-01-20 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

**Comment by clauswilke** [comment]
I think there's three possible places this could go:

1. ggplot2
2. ggforce
3. ggrepel

@hadley will have to make the decision regarding ggplot2.

**Comment by hadley** [comment]
I think ggrepel would be the best fit, because you could implement the full algorithm since ggrepel can do layout at draw time.

**Comment by thomasp85** [comment]
ggrepel is certainly an obvious choice, but I guess it would require a new dependency on deldir... ggforce already has this dependency so if @slowkow don't want to have it it will be natural there...

**Comment by slowkow** [comment]
I agree with @thomasp85:
- ggplot2 and ggrepel do not depend on deldir.
- ggforce depends on deldir, so it is a natural place to put more functions that depend on deldir.

---

I believe the feature we are discussing is **labeling groups of data points**.

It is already done in directlabels:

<details>
<summary>directlabels</summary>

<h2>directlabels</h2>

[directlabels] does this well with `geom_dl()`. It offers many options for customization. I think this package needs clearer documentation, and then more exposure so people can find it.

``` r
library(ggplot2)
library(directlabels)

ggplot(iris, aes(Petal.Length, Sepal.Width, color = Species)) +
  geom_point() +
  geom_dl(aes(label = Species), method = "smart.grid")
```

![](https://i.imgur.com/uYpSLST.png)

<sup>Created on 2019-01-24 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>
</details>

<br>

Elio found a way to use deldir to do it in ggrepel:

<details>
<summary>ggrepel with deldir</summary>

<h2>ggrepel with deldir</h2>

@eliocamp found a clever way to use ggrepel to do the same.

Note: This code fails when the data has duplicates.

``` r
library(ggrepel)
#> Loading required package: ggplot2

set.seed(42)

is.voronoi_max <- function(x, y, group) {
  x <- scales::rescale(x, c(0, 1))
  y <- scales::rescale(y, c(0, 1))
  rw <-  c(range(x), range(y))
  del <- deldir::deldir(x, y, z = group, rw =  rw,
                        suppressMsge = TRUE)
  del_summ <- del$summary
  del_summ$index <- seq_len(nrow(del_summ))

  index <- vapply(split(del_summ, del_summ$z),
                  function(x) x$index[which.max(x$dir.area)], 1)
  seq_len(length(x)) %in% index
}

ggplot(iris, aes(Petal.Length, Sepal.Width, color = Species)) +
  geom_point() +
  geom_text_repel(aes(
    label = ifelse(
      is.voronoi_max(Petal.Length, Sepal.Width, Species),
      as.character(Species),
      ""
    )
  ))
#> Warning in deldir::deldir(x, y, z = group, rw = rw, suppressMsge = TRUE): There were different z "weights" corresponding to
#> duplicated points.

#> Warning in deldir::deldir(x, y, z = group, rw = rw, suppressMsge = TRUE): There were different z "weights" corresponding to
#> duplicated points.
```

![](https://i.imgur.com/2AbNcCm.png)

<sup>Created on 2019-01-24 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>
</details>

<br>

I found a way to do it in ggrepel without deldir:

<details>
<summary>ggrepel without deldir</summary>

<h2>ggrepel without deldir</h2>

``` r
library(ggrepel)
#> Loading required package: ggplot2

seen <- function(x) {
  o <- order(x)
  duplicated(x[o])[order(o)]
}

ggplot(iris, aes(Petal.Length, Sepal.Width, color = Species)) +
  geom_point() +
  geom_text_repel(aes(
    label = ifelse(!seen(Species), as.character(Species), "")
  ))
```

![](https://i.imgur.com/u7YNhG8.png)

<sup>Created on 2019-01-24 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

</details>

[directlabels]: http://directlabels.r-forge.r-project.org/

**Comment by eliocamp** [comment]
I also agree that directlabels seems like a better place, implemented as an alternative `method`. I still like the implementation as a positional function because it makes the method portable to any geom. I see no reason why don't have it both. [insert meme here]

If it's ok with everyone, after I return from vacation, I'll add something like `position_voronoi()` (name pending) to ggforce and also try to learn how to implement the full algorithm in directlabels. I will also probably offer to improve it's documentation.
