### ISSUE TITLE
Feature Request: "facet_wrap" Argument which creates Multiple Plots (Instead of 1 with Subplots)

### ISSUE THREAD

**Issue by jtelleria** [tidyverse/ggplot2#3097]
If I want to divide a plot into subplots based on the values of one or more discrete values, the easiest way is through faceting:

```r
t <- ggplot(mpg, aes(cty, hwy)) + geom_point()

t+facet_wrap(~fl)
```

But If I want to generate multiple plots at once, that is, divide previous subplots in plots by themselves, I would need to do the following:

```r
for(i in unique(mpg$fl)){

     mpg_filtered <- mpg %>%
          filter(fl == i)

     t <- ggplot(mpg_filtered, aes(cty, hwy)) + geom_point()

     print(t)
}
```

Would it be possible that facet_wrap() function gains an argument that allows to generate easily multiple plots based on multiple discrete values, instead of subplots?

```r
function (facets, nrow = NULL, ncol = NULL, scales = "fixed", 
    shrink = TRUE, labeller = "label_value", as.table = TRUE, 
    switch = NULL, drop = TRUE, dir = "h", strip.position = "top") 
{
    scales <- match.arg(scales, c("fixed", "free_x", "free_y", 
        "free"))
    dir <- match.arg(dir, c("h", "v"))
    free <- list(x = any(scales %in% c("free_x", "free")), y = any(scales %in% 
        c("free_y", "free")))
    if (!is.null(switch)) {
        .Deprecated("strip.position", old = "switch")
        strip.position <- if (switch == "x") 
            "bottom"
        else "left"
    }
    strip.position <- match.arg(strip.position, c("top", "bottom", 
        "left", "right"))
    if (identical(dir, "v")) {
        nrow_swap <- ncol
        ncol_swap <- nrow
        nrow <- sanitise_dim(nrow_swap)
        ncol <- sanitise_dim(ncol_swap)
    }
    else {
        nrow <- sanitise_dim(nrow)
        ncol <- sanitise_dim(ncol)
    }
    labeller <- check_labeller(labeller)
    facets_list <- as_facets_list(facets)
    facets <- rlang::flatten_if(facets_list, rlang::is_list)
    ggproto(NULL, FacetWrap, shrink = shrink, params = list(facets = facets, 
        free = free, as.table = as.table, strip.position = strip.position, 
        drop = drop, ncol = ncol, nrow = nrow, labeller = labeller, 
        dir = dir))
}
<bytecode: 0x000002403afa6360>
<environment: namespace:ggplot2>
```

This would be useful, for example, if we want to print plots with lots of subplots, that do not fit in a single PDF page for example.

**Comment by yutannihilation** [comment]
The idea might be interesting, so it can be an external package, but I think this is outside of the scope of ggplot2.

Creating multiple plots are not so difficult, you can split the data and apply functions. For example:

``` r
library(ggplot2)

d <- split(mpg, mpg$fl)
p <- lapply(d, function(d) ggplot(d, aes(cty, hwy)) + geom_point())

patchwork::wrap_plots(p)
```

![](https://i.imgur.com/jheqKHf.png)

<sup>Created on 2019-01-23 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by thomasp85** [comment]
this is already available with `ggforce::facet_wrap_paginate()`

**Comment by jtelleria** [comment]
After checking ggforce package, `r ggforce::facet_wrap_paginate` does not do the same, as puts the plots within a single graphics device.

Instead, previous lapply code works:

```r
library(ggplot2)

d <- split(mpg, mpg$fl)
p <- lapply(d, function(d) ggplot(d, aes(cty, hwy)) + geom_point())
```

**Comment by thomasp85** [comment]
Unsure about what you mean regarding `facet_wrap_paginate()` as it allows you to put each page wherever you want (you are free to use whatever method you prefer of course)

I'm going to close, as it appears to be resolved

**Comment by jtelleria** [comment]
Thank you for the answers
