### ISSUE TITLE
Allow scale_alpha_continuous(guide = 'colourbar')

### ISSUE THREAD

**Issue by flying-sheep** [tidyverse/ggplot2#3103]
Currently this raises an error, although I don’t see a reason why. A continuous alpha should by default be represented by a alpha gradient as legend, not sample swatches.

Maybe `guide_colourbar` should have been called `guide_gradientbar`, but that’s not a big problem.

**Comment by thomasp85** [comment]
The reason is that it hasn't been implemented. My guess is the major stumbling block has been to figure out a correct way to merge alpha and colour guides in the same way as done for `guide_legend` as it is not always that alpha affects the same part of the geom (sometimes fill, sometimes colour)

**Comment by flying-sheep** [comment]
Until then: How can I fake it and create a custom colourbar legend manually?

**Comment by thomasp85** [comment]
you could fake an alpha scale by passing transparent colour into a colour scale:

```r
ggplot(mtcars) + 
  geom_point(aes(disp, mpg, colour = hp)) + 
  scale_color_gradient(low = "#00000000", high = '#000000FF')
```

**Comment by flying-sheep** [comment]
Why did you close this? This is not fixed.

**Comment by thomasp85** [comment]
because there are many technical reason to why this cannot be done as it currently stand and we are trying to prune out in the issues to better focus development

**Comment by flying-sheep** [comment]
This is still a valid issue, and closing it makes it impossible to find later.

Why not add a backlog label or milestone and put it in there? Then you can hide it from sight but it’s still tracked as “not solved”.

**Comment by thomasp85** [comment]
any feature request is valid even if we decide to not implement it... that doesn't mean it should stay in the issue list in perpetuity. Closing it marks it as a *won't-fix*

**Comment by flying-sheep** [comment]
Then I misunderstood you.

I thought you meant “won’t fix until we’ve cleared our technical debt and there’s no longer anything preventing it”
