### ISSUE TITLE
Multipanel plots

### ISSUE THREAD

**Issue by x1o** [tidyverse/ggplot2#3105]
Would it be possible to add support for multipanel plots in ggplot2?

I have bar charts faceted by stock symbol name:

![barchart-faceted-by-symbol](https://i.stack.imgur.com/HYad8.png)

Now, I would like to be able to add a little "subplot" of an indicator below each plot, similar to how it is done in `quantmod` package (with base graphics, I believe):

![quantmod-subplot](https://i.stack.imgur.com/GT5Fn.png)

Secondary axis won't work in this case, because most often there is no linear relation between the main plot axis and the indicator axis.

I've decided to make the suggestion because this kind of plots arises *naturally* and *very often* in the context of portfolio theory and finance in general. Yet currently it seems that there is no way they could be done using the stock ggplot2 functionality.

**Comment by ptoche** [comment]
Do you mean something like [this](https://stackoverflow.com/questions/14817006/ggplot-version-of-charts-performancesummary)?

**Comment by x1o** [comment]
@ptoche, yes, AND faceted by a variable (symbol name).

And in 5--10 lines, not 157.

**Comment by thomasp85** [comment]
This is not something that will be added to ggplot2, but you could write your own faceting class or use one of the packages available for assembling plots, like patchwork or cowplots

**Comment by x1o** [comment]
@thomasp85, why not?

**Comment by thomasp85** [comment]
Being one of the developers I can attest that the cost of a new feature is much more driven by maintaining it than by doing the initial development — this is doubly true for facets due to their complexity

**Comment by x1o** [comment]
Thanks Thomas, I am happy using ggplot owing almost entirely to the effort and dedication of the dev team. ~~Despite the fact that it isn't really suitable for any serious finance as of now.~~
