### ISSUE TITLE
geom_sf does not interact with scale_fill_gradient2 properly

### ISSUE THREAD

**Issue by cschwarz-stat-sfu-ca** [tidyverse/ggplot2#3107]
geom_sf doesn't deal with scale_fill_gradient2 properly. Rather than taking the "mean" or some other central value, it appears to assume that mid=0. For example, in the first example, there is no color spread. In the second example, I subtracted the approximate middle value and it works properly.

```r
nc <- sf::st_read(system.file("shape/nc.shp", package = "sf"), quiet = TRUE)
ggplot(nc) +
    geom_sf(aes(fill = AREA)) + geom_sf(data = sf::st_centroid(nc), pch = 20)+
  scale_fill_gradient2(low='darkred', mid="white", high='darkblue')

ggplot(nc) +
    geom_sf(aes(fill = AREA-.15)) + geom_sf(data = sf::st_centroid(nc), pch = 20)+
  scale_fill_gradient2(low='darkred', mid="white", high='darkblue')

```

**Comment by clauswilke** [comment]
That is literally how the scale works, as described in the documentation:

> `midpoint` The midpoint (in data value) of the diverging scale. Defaults to 0.

The scale can't guess what you want the midpoint to be. You have to either tell it or transform the data so the midpoint lies at 0. Setting the midpoint to 0 is the only reasonable default assumption for a diverging scale.
