### ISSUE TITLE
Introduce new alpha parameter for lines of geom_density(), geom_bar(), and so on

### ISSUE THREAD

**Issue by MaximOtt** [tidyverse/ggplot2#3112]
(It's my first time, and I am really sorry if I waste someones time to close and delete this, but I am kinda confident, that it is the right place.)

I open this issue (again), because as I read it, the last time no real solution was agreed upon, and the confusing behavior is not (easily) resolved. The issue in question can be found here:

https://github.com/tidyverse/ggplot2/issues/1371

The discussion is very informative, so I will only quote the basic problem:

"When I draw a chart with alpha, I expect that the whole layer, the line and fill, will become transparent. But the line stays clear red."

I would argue, that this is extermely counterintuitive, and apparently some people agree (See link).

Because (of course) some peoples code would be broken by a proposed change, the suggested change has been reverted, and the workaround is to change the color manually with `colour=alpha("red", 0.1)`.

The problem with this solution, is that I can not longer use automatic color picking to highlight a group with `color=MyGroupVar, alpha=ifelse(MyGroupVar=="GroupA",0.2,1)`. I personally think it is very inconvenient, but as I understand the debate, a possible compromise would be to introduce a new parameter `alpha_line` or something.

Or am I missing a very simple solution for this? (In any case something more "official" than just a workaround of any kind would be nice ^^)

Below is a simple example:

```
mtcars$cyl = as.factor(mtcars$cyl)
ggplot(data=mtcars, aes(x=disp,fill=cyl, color=cyl, alpha=ifelse(cyl!=6,0.2,1))) +
  geom_bar(width=5,position=position_dodge(preserve = "single"))+
  guides(alpha=FALSE)
```

![image](https://user-images.githubusercontent.com/7224880/51992730-d7349380-24ad-11e9-989a-a1eac2e3a676.png)

**Comment by batpigandme** [comment]
If you want the border to have the same behaviour as the fill, you could just eliminate the border line:
``` r
suppressPackageStartupMessages(library(tidyverse))
mtcars$cyl = as.factor(mtcars$cyl)
ggplot(data=mtcars, aes(x=disp,fill=cyl, color=cyl, alpha=ifelse(cyl!=6,0.2,1))) +
  geom_bar(width=5,position=position_dodge(preserve = "single"), linetype = "blank")+
  guides(alpha=FALSE)
#> Warning: position_dodge requires non-overlapping x intervals
```
![](https://i.imgur.com/xIk8vgO.png)
<sup>Created on 2019-01-30 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by MaximOtt** [comment]
Goddamit, sometimes its just so easy. I spent a day on this, thanks a lot!

**Comment by batpigandme** [comment]
Happens to the best of us! I'm gonna go ahead and close this, since I think compelling arguments have already been made in the threads you cited. 🙂
