### ISSUE TITLE
geom_density displays a distribution with non-zero variance for a group containing only zeros

### ISSUE THREAD

**Issue by brfitzpatrick** [tidyverse/ggplot2#3118]
`geom_density( )` appears to be estimating a variance for a group that contains only values of zero.

```r
library(tidyverse)

n <- 100

Test.tb <- tibble(Group = c(rep('A', n), rep('B', n)), Value = c(rnorm(n = n), rep(0, n)))

ggplot(data = Test.tb, aes(x = Value)) +
  geom_density(aes(colour = Group))
```

![2_densities](https://user-images.githubusercontent.com/6220438/52428274-ec3ea180-2b01-11e9-86f2-623997b62fcf.png)

However when supplied with just the data from the group that only contains entries of zeros `geom_density( )` displays a point mass at zero.

```r
filter(.data = Test.tb, Group == 'B') %>%
  ggplot(data = ., aes(x = Value)) +
    geom_density()                                                                              
```

![1_density](https://user-images.githubusercontent.com/6220438/52428388-1ee89a00-2b02-11e9-8dc6-c904d407a32d.png)

**Comment by clauswilke** [comment]
That's because the default for `trim` is `FALSE`, which facilitates stacking of densities. For non-stacked densities, `trim = TRUE` is arguably better.

``` r
library(tidyverse)

n <- 100
Test.tb <- tibble(Group = c(rep('A', n), rep('B', n)),
                  Value = c(rnorm(n = n), rep(0, n)))

ggplot(data = Test.tb, aes(x = Value)) +
  geom_density(aes(colour = Group), trim = TRUE)
```

![](https://i.imgur.com/wXFq1nn.png)

<sup>Created on 2019-02-07 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by brfitzpatrick** [comment]
Thank you for your reply, it's good to know how to disable this behaviour. 
Is it not of concern though that a group containing only repeats of a single unique value is displayed as having a distribution dispersed about this value?

**Comment by karawoo** [comment]
I don't think so? I think that is true whenever you calculate density beyond the exact range of the data. In ggplot2 the default is to use the range of the entire dataset (again to facilitate stacking), but the default behavior of `stats::density()`, which ggplot2 uses to calculate density, also does this:

``` r
plot(density(rep(0, 100)))
```

![](https://i.imgur.com/C5v5OzA.png)

<sup>Created on 2019-02-07 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

You can always change the density calculations to your liking by changing the `trim` parameter, bandwidth, kernel, etc. in your call to `geom_density()`, but I think the default behavior is reasonable.

**Comment by clauswilke** [comment]
Yes, I agree. At some point, the onus is on the person preparing the plot to ensure the plot makes sense. We cannot protect against every possible way in which density plots may be misleading. If, say, we added a check for groups with zero variation, then the next question would be why we don't also check for groups with only two distinct values (see example below). Ultimately, these are known potential problems with density plots and anybody using density plots needs to accept some responsibility for appropriate use.

``` r
library(tidyverse)

n <- 100
Test.tb <- tibble(Value = c(rep(0, n), rep(1, n)))

# this plot is highly misleading
ggplot(data = Test.tb, aes(x = Value)) + geom_density()
```

![](https://i.imgur.com/6NK1QWO.png)

<sup>Created on 2019-02-07 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by brfitzpatrick** [comment]
Ok, thank you both for taking the time to discuss this issue.  That's a good point about it being important to check that the output of `geom_density( )` makes sense. In the original example comparing boxplots produced for each group to density plots produced for each group would quickly highlight the group containing only zeros and a user could then make a decision about the use of the `trim` argument.
