### ISSUE TITLE
How to have duplicate label for each row and column in facet_wrap

### ISSUE THREAD

**Issue by bdschwartzkopf** [tidyverse/ggplot2#3119]
Hi,
Is there a way to repeat both the x and y title in facet_wrap for each row and column? 
This is the original plot 

![test_facet](https://user-images.githubusercontent.com/34198424/52504446-61ab8000-2b9d-11e9-80ca-6eafcf126e82.jpeg)

And this is how I would like the plot to look (labels added manually with another program)
![test_facet copy](https://user-images.githubusercontent.com/34198424/52504466-72f48c80-2b9d-11e9-8309-ecd77e9765db.jpeg)

**Comment by ptoche** [comment]
Would this question be suited for stackoverflow? In any case, make a minimal example with a dataset like ``mtcars`` and, on github, present it with the ``reprex()`` package.

**Comment by yutannihilation** [comment]
> Is there a way to repeat both the x and y title in facet_wrap for each row and column?

No.

I take this issue as a feature request for a kind of per-facet labels, but I don't think ggplot2 will support it (except for the current "strip label"). Probably, you'll need to split data, and make one plot per one split, and combine them nicely, which I guess will be able to be done nicely with @thomasp85's [patchwork](https://github.com/thomasp85/patchwork) (someday).

At the moment, you will get better answers on SO as @ptoche suggests, or on [RStudio Community](https://community.rstudio.com/).
