### ISSUE TITLE
GPL license clarification

### ISSUE THREAD

**Issue by gophercall** [tidyverse/ggplot2#3125]
If I use this library in my code, does this mean my code also needs to be released under GPL?

I can see lots of people using ggplot2 but not releasing their code under GPL, so it would be good to have clarification.

**Comment by thomasp85** [comment]
If you include code from ggplot2 (ie. copy code from the implementation into your code-base) you'll need to use a GPL compliant license - if you merely call functions from ggplot2, you have no obligations for that
