### ISSUE TITLE
differing behaviour using "color = NA" in Linux and Windows

### ISSUE THREAD

**Issue by JayVii** [tidyverse/ggplot2#3129]
During a project, I used following snippet to draw a completely transparent hexbin map:

```r
  plot <- ggplot(data, aes(x = lon, y = lat, z = marks)) +
      coord_fixed(ratio = width/height) +
      stat_summary_hex(binwidth = c(width * scale, height * scale),
                       color = NA, show.legend = FALSE, size = border_width)
      scale_fill_gradient(low = "#00000000", high = "#00000000") +
      theme_void()
```

Note the color argument in `stat_summary_hexbin()` is set to `NA`. This worked fine on Linux and produced a transparent hexbin layer. However on Windows the same script produced a completely black hexbin layer (eventhough `scale_fill_gradient()` is set to transparent colors). This persisted when trying to use Cairo to render the output graphic under Windows.

Explicitly specifying the plot to be transparent via `fill = transparent` in `stat_summary_hexbin()` fixed the issue on Windows.

The point still stands, that `NA` as filling color seems to be treated differently across different OSes, if I interpreted this issue correctly.

**Comment by batpigandme** [comment]
Could you please turn this into a self-contained [reprex](http://reprex.tidyverse.org/) (short for minimal **repr**oducible **ex**ample)? It will help us help you if we can be sure we're all working with/looking at the same stuff.

If you've never heard of a reprex before, you might want to start by reading the tidyverse.org [help page](https://www.tidyverse.org/help/).

You can install reprex by running (you may already have it, though, if you have the tidyverse package installed):
```r
install.packages("reprex")
```

Thanks

**Comment by clauswilke** [comment]
Gradients with transparency were only recently introduced in the scales package. My hunch is that the scales package on the windows system is too old. Could you check which version you have there? Start a new R session, and then enter:
``` r
library(scales)
sessionInfo()
```

**Comment by JayVii** [comment]
@batpigandme 
> Could you please turn this into a self-contained [reprex](http://reprex.tidyverse.org/) (short for minimal **repr**oducible **ex**ample)? It will help us help you if we can be sure we're all working with/looking at the same stuff.

`reprex` seems not very helpful in this case, as the above code-snipped is part of a much more complicated function and a rather large dataset. But here is a simplified version as produced with `reprex()`:

``` r
library(ggplot2)
data <- data.frame(lon = c(1, 2, 3), lat = c(1, 2, 3), marks = c(0, 1, 0))
myplot <- ggplot(data, aes(x = lon, y = lat, z = marks)) +
    stat_summary_hex(color = NA, show.legend = FALSE) +
    scale_fill_gradient(low = "#00000000", high = "#00000000") +
    theme_void()
myplot
```

![](https://i.imgur.com/fstbF4M.png)

<sup>Created on 2019-02-11 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>


@clauswilke 
> Gradients with transparency were only recently introduced in the scales package. My hunch is that the scales package on the windows system is too old. Could you check which version you have there? 

Indeed, scales is at 1.0.0 on the Linux machine and 0.5.0 on the Windows box. I only checked ggplot2 and hexbin versions before. Thanks for the hint!

**Comment by clauswilke** [comment]
Fixed in current release of scales.

**Comment by batpigandme** [comment]
> But here is a simplified version as produced with `reprex()`

That's the very goal of a reprex, to make a minimal version of the issue you're encountering — the "minimal" part just isn't in the portmanteau. Glad to hear it's fixed in scales!
