### ISSUE TITLE
feature: stat_summary_bin size argument should accept functions

### ISSUE THREAD

**Issue by hyiltiz** [tidyverse/ggplot2#3130]
`stat_summary_bin` takes `size` as one of the function argument but its value can only be set to a fixed value. It should take functions for `size` as well just like `fun.y` could. A use case would be that, given continuous `x` and `y`, we'd like to bin and plot `geom_point` whose size scales linearly/logarithmicly as a function of who many points fell within a bin, `count()`. For a consistent API, we could call it `fun.size`.

```r
set.seed(1)
library("ggplot2")
df <- data.frame(x = rnorm(1000), y = rnorm(1000))

ggplot(df, aes(x = x, y = y)) + stat_summary_bin(fun.y="mean", geom="point", bins=5)

# One of the following should work, where the size of each point under each bin should 
# be set as a function of x falling within the bin
# ggplot(df, aes(x = x, y = y)) + stat_summary_bin(fun.y="mean", geom="point", size="count", bins=5)
# ggplot(df, aes(x = x, y = y)) + stat_summary_bin(fun.y="mean", geom="point", size=count(), bins=5)
# ggplot(df, aes(x = x, y = y)) + stat_summary_bin(fun.y="mean", geom="point", size=log(1+count()), bins=5)
```

**Comment by hadley** [comment]
In principle, we could make `stat_summary_bin()` take bin specifications in as many ways as `geom_histogram()`, but practically I think you're better off just using dplyr (or another specialised data summary tool) once you move beyond the basics of `stat_summary_bin()`.

**Comment by hyiltiz** [comment]
I get your point. But it is quite a common practice to scale the point size w.r.t. some function so it is easier to interpret (`sqrt` is a common option as its area is meaningful and the dots won't easily get too large). I'd think this practice is common enough that it would be practical to require a convenient syntax sugar.
