### ISSUE TITLE
Export predictdf

### ISSUE THREAD

**Issue by hadley** [tidyverse/ggplot2#3132]
Message from CRAN:

---

Package complmrob exports predictdf.complmrob.part with comment

>  The sole reason that this function is visible is because the
>  \code{\link[ggplot2]{ggplot}} function \code{predictdf} is not
>  exported and thus this function could not be used for
>   \code{complmrob.part} objects if it was not exported.

Given that relying on finding S3 methods on the search path is not a
good thing: Hadley, perhaps you could export predictdf() (but show as
internal and hence keep uncodumented)?

**Comment by yutannihilation** [comment]
It seems we've been considering to export it at some point.

https://github.com/tidyverse/ggplot2/blob/344bfea39aaadbb90c455570f7fdf30d33a1a4fd/R/geom-smooth.r#L8-L9

But, as we don't export it yet, it sounds it's just complmrob relies on ggplot2's unofficial API. Do we need to support it?

**Comment by yutannihilation** [comment]
@hadley Can we close this? I believe we don't want to let `predictdf()` be extended. Considering broom package (or parsnip, or whatever package for tidy prediction) now provides more standardised methods, I don't think `predictdf()` is the right place to be an interface between prediction methods.

(I expect tidymodels will provide some nice alternative to `geom_smooth()` eventually. https://github.com/sinhrks/ggfortify/issues/196 might be a related issue.)

**Comment by hadley** [comment]
Yeah, but we need to follow up with the complmrob telling them what they need to do.

**Comment by yutannihilation** [comment]
I have zero knowledge about the package. Maybe they need to implement `fortify()` and `autolayer()`?

**Comment by clauswilke** [comment]
I think most importantly, we need to tell them that `geom_smooth()` is not meant to be used the way they do. We have given the same answer to people who complained that their preferred model was not supported for some reason or another. They could copy the `geom_smooth()` code and implement their own version, e.g. `geom_complmrob_smooth()`. Alternatively, `autolayer()` would be an option also, though almost nobody seems to be aware of it and/or use it.

**Comment by yutannihilation** [comment]
> I think most importantly, we need to tell them that `geom_smooth()` is not meant to be used the way they do.

Agreed.

This seems the code in question:

``` r
            p <- p + ggplot2::stat_smooth(method = complmrob.wrapper, se = se, level = conf.level,
                                 method.args = list(complmrob.model = x,
                                                    transform = (scale == "percent")),
                                 size = lineStyle$width, color = lineStyle$color,
                                 fill = seBandStyle$color, alpha = seBandStyle$alpha)
```
https://github.com/cran/complmrob/blob/e968bd97eed171add28c7189da04e8379581df2a/R/plot-methods.R#L123-L127

They just use `stat_smooth()` internally, so it turns out `fortify()` and `autolayer()` are not needed. I think they can fortify the data by themselves and compose arbitrary geoms.

**Comment by thomasp85** [comment]
@hadley can you reach out to the maintainer and ask them to change practice? or close if this is already fixed...

**Comment by hadley** [comment]
Emailed the maintainer.

**Comment by yutannihilation** [comment]
Thanks Hadley!
