### ISSUE TITLE
Add argument to coord_polar() to connect first and last dot

### ISSUE THREAD

**Issue by fmmattioni** [tidyverse/ggplot2#3136]
This is related to https://github.com/tidyverse/ggplot2/issues/80. Any updates on that? It would be nice for coord_polar() to have an extra argument to let us connect the two ends of the line.

``` r
library(ggplot2)

d <- structure(list(angle = c(0, 22.5, 45, 67.5, 90, 112.5, 135, 157.5,
                              180, 202.5, 225, 247.5, 270, 292.5, 315, 337.5), value = c(4.465849387,
                                                                                         1.22591944, 1.22591944, 1.663747811, 1.663747811, 0.963222417,
                                                                                         1.838879159, 3.327495622, 4.028021016, 0.963222417, 0.788091068,
                                                                                         0.175131349, 0.963222417, 1.576182137, 4.378283713, 4.553415061
                              )), .Names = c("angle", "value"), class = "data.frame", row.names = c(NA,
                                                                                                    16L))
ggplot(d, aes(x = angle, y = value)) +
  geom_line() + 
  geom_point() + 
  coord_polar() +
  scale_x_continuous(limits = c(0, 360))
```

![](https://i.imgur.com/OZf5luT.png)

<sup>Created on 2019-02-13 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by thomasp85** [comment]
You can get this by using `geom_polygon` with `fill = NA` instead of `geom_point`

**Comment by fmmattioni** [comment]
That is true! Thank you!

**Comment by dannykwells** [comment]
Just fyi, geom_polygon and geom_line plot differently, so this is not really a replacement. It would be nice to have this option.

**Comment by thomasp85** [comment]
if that work-around doesn't work for various reasons you should consider subclassing either geom_path or geom_polygon to behave as you need. It is not the responsibility of the coordinate system to change the semantics of geoms
