### ISSUE TITLE
Feature request: Approximation for massive number of observations

### ISSUE THREAD

**Issue by jsekamane** [tidyverse/ggplot2#3137]
Hi. I regularly find myself working with huge datasets in R and in need of a "quick" way to visualise the data. In these instances it would be helpful with approximations that speed things up. 

![Example](https://user-images.githubusercontent.com/1207156/52709506-348c1280-2f8d-11e9-988e-b6b5858f770e.png)
**Fig 1. – _[Strip plot](https://vega.github.io/vega-lite/examples/tick_strip.html)_ example showing observations overlap and gaps between observations. Millions of observations, it toke approximately 15 minutes to create and the PDF is 35 MB!**

Additionally, when plotting millions of observations, many points/objects inevitably cluster and overlap. That is, a lot of resources end up being "wasted" with an _"exact"_ plot, since this approach plots overlapping objects that the human eye cannot visually distinguish (see example in figure 1). The _approximation_ should try to reduce such redundancies.

_Inspiration_: [MapBox use _hierarchical greedy clustering_](https://blog.mapbox.com/clustering-millions-of-points-on-a-map-with-supercluster-272046ec5c97) to plot millions of data points on maps in seconds. Perhaps a similar approach can be used for approximations in _ggplot2_ (the "zoom levels" would be determined by the size of the device/pdf/png – similarly to how text and lines scale with the size of the device).

**Comment by thomasp85** [comment]
This is in general a good idea, but not something ggplot2 controls... Once the plot reaches the graphic device, ggplot2's job is done and any response to resizing is purely grid.

It is possible to construct new grid grobs that do the same as mapbox (and it might be a good idea), but this is outside the scope of ggplot2
