### ISSUE TITLE
Feature Suggestion/Discussion for geom_histogram

### ISSUE THREAD

**Issue by ptoche** [tidyverse/ggplot2#3147]
Does it make sense for the ``breaks`` option of ``geom_histogram()`` to not only set the bin limits but also set tick marks and labels?

The pros are that it's likely to be what a user wants.

The cons are that it may add some overhead to maintenance. 

Putting it out there to see reactions.

``` r
library("reprex")
library("ggplot2")

breaks = seq(10, 35, 3)
ggplot(mtcars, aes(x = mpg)) +
    geom_histogram(breaks = breaks, col = "white") +
    labs(title = "geom_histogram(breaks = seq(10, 35, 3))")
```

![](https://i.imgur.com/ANLWumc.png)

Could geom_histogram do the work of scale_x_continuous?

``` r


ggplot(mtcars, aes(x = mpg)) +
    geom_histogram(breaks = breaks, col = "white") +
    scale_x_continuous(breaks = breaks) +
        labs(title = "geom_histogram(breaks = seq(10, 35, 3))\n + scale_x_continuous(breaks = seq(10, 35, 3))")
```

![](https://i.imgur.com/F4YyE7y.png)

<sup>Created on 2019-02-17 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by thomasp85** [comment]
This will break a fundamental part of how ggplot2 works - geoms should not control scales. If you want this sort of behaviour with less typing the upcoming `scale_x_binned` will give you that

**Comment by ptoche** [comment]
That makes sense, thanks.
