### ISSUE TITLE
Feature Request: geom_points colored by density.

### ISSUE THREAD

**Issue by bjreisman** [tidyverse/ggplot2#3150]
One geom/stat which would be very useful is a hybrid between geom_density_2d and geom_point, where points are colored by their density. This would help avoid overcome overplotting by mapping the density to the color aesthetic, while preserving the individual points in areas of low density. This type of visualization is very common in flow cytometry, but could be useful elsewhere as well. 

@slowkow has an excellent example of how to achieve the desired effect [here](https://slowkow.com/notes/ggplot2-color-by-density/), but it requires computing the density at each point prior to plotting, which becomes burdensome for faceted plots. 

I was able to modify the `stat_density_2d` function slightly using @slowkow's code as a guide to make a new `stat_density_point_2d` function which worked well in my hands(example below), but I had trouble writing the corresponding geom.  Is this something that could be considered for inclusion in ggplot2?

```r
library(ggplot2)
dat <- data.frame(
  x = c(
    rnorm(1e4, mean = 0, sd = 0.1),
    rnorm(1e3, mean = 0, sd = 0.1)
  ),
  y = c(
    rnorm(1e4, mean = 0, sd = 0.1),
    rnorm(1e3, mean = 0.1, sd = 0.2)
  )
)

ggplot(dat, aes(x, y)) +
  stat_identity() +
  scale_color_viridis_c() +
  theme_classic()

```
![stat_identity](https://user-images.githubusercontent.com/22528952/52978301-49eeab80-3396-11e9-9e60-9efcbf1d7261.png)
```r
ggplot(dat, aes(x, y)) +
  stat_density_point_2d() +
  scale_color_viridis_c() +
  theme_classic()
```
![stat_density_point_2](https://user-images.githubusercontent.com/22528952/52978304-53781380-3396-11e9-92f5-3f76984afb0f.png)

**Comment by thomasp85** [comment]
This kind of functionality is better suited in an extension package, eg ggforce or its own

**Comment by bjreisman** [comment]
Thanks for the quick reply! I was actually considering proposing it in ggforce, but wasn't sure which would be more appropriate. I'll propose it there. 👍
