### ISSUE TITLE
Running ggplot2 in webassembly - absurd?

### ISSUE THREAD

**Issue by powerbilayeredmap** [tidyverse/ggplot2#3153]
I am starting an application that needs to run entirely in the browser, without any server components, and I really want to use ggplot2, seems to be the most mature charting package out there. Is there any daylight in possibly compiling R and ggplot2 to webassembly?

**Comment by yutannihilation** [comment]
This is out of scope of the development of ggplot2 itself. This sort of question is a better fit for StackOverflow or RStudio Community.
