### ISSUE TITLE
axis.ticks and axis.text inheritance problem

### ISSUE THREAD

**Issue by ptoche** [tidyverse/ggplot2#3157]
Problem: ``axis.text`` and ``axis.ticks`` are not inherited.

  ``` r

library("reprex")
library("ggplot2")

theme_set(theme_classic())
theme_update(axis.text = element_text(colour = "gray"),
             axis.text.x = element_text(colour = "red"),
             axis.text.y = element_text(colour = "blue"),
             axis.ticks = element_line(colour = "gray"),
             axis.ticks.x = element_line(colour = "red"),
             axis.ticks.y = element_line(colour = "blue"))
          
## as expected:

ggplot(mtcars, aes(x = mpg, y = wt)) +
  geom_point() +
  theme(axis.text.x = element_blank(), axis.ticks.x = element_blank()) +
  theme(axis.text.y = element_blank(), axis.ticks.y = element_blank()) 

  ```

  ![](https://i.imgur.com/sGIMe5F.png)

  ``` r

## expected same output as above:

  ggplot(mtcars, aes(x = mpg, y = wt)) +
      geom_point() +
      theme(axis.text = element_blank(), axis.ticks = element_blank()) 
  ```

  ![](https://i.imgur.com/g5IJBqb.png)

  <sup>Created on 2019-02-21 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by karawoo** [comment]
This is expected behavior. You're overriding the inheritance of `axis.text` and `axis.ticks` by directly setting the `axis.text.x` etc. elements in `theme_update()`.

**Comment by batpigandme** [comment]
To second what @karawoo's saying here, it works by specificity, not by sequential order.
``` r
library(ggplot2)

theme_set(theme_classic())
theme_update(axis.text.x = element_text(colour = "red"),
             axis.text = element_blank())

ggplot(mtcars, aes(x = mpg, y = wt)) +
  geom_point()
```

![](https://i.imgur.com/JRRxnOA.png)

<sup>Created on 2019-02-21 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

**Comment by ptoche** [comment]
Oh, I see. I had never noticed that. Thanks for your prompt reply!

**Comment by ptoche** [comment]
I see. So you need to know the sequence of theme updates (I noticed the behaviour above while I was updating a theme repeatedly while experimenting). And when you create a theme, you should not set a property twice in the same inheritance branch? (as in setting colour in both ``axis.text`` and ``axis.text.x``)

The reported behaviour, which is expected:

``` r
library("reprex")
library("ggplot2")

# You must keep track of which elements of theme have been set
theme_set(theme_bw())
theme_update(axis.text.x = element_text(colour = "blue"))
theme_update(axis.text = element_blank()) # will not blank x-axis
ggplot(mtcars, aes(x = mpg, y = wt)) +
    geom_point()
```

![](https://i.imgur.com/mkKnI0J.png)

``` r

# Incorrect way to create a theme:
theme_test <- function(base_size = 16) {
    theme_bw(base_size = base_size) %+replace%
        theme(
            axis.text = element_text(colour = "red"),   # set one or the other
            axis.text.x = element_text(colour = "red"), # but not both
            complete = TRUE
        )
}

# you wouldn't know it was bad:
theme_set(theme_test())
ggplot(mtcars, aes(x = mpg, y = wt)) +
    geom_point()
```

![](https://i.imgur.com/W9Qu8A6.png)

``` r

# it seems to work:
theme_set(theme_test())
theme_update(axis.text.x = element_text(colour = "blue"))
ggplot(mtcars, aes(x = mpg, y = wt)) +
    geom_point()
```

![](https://i.imgur.com/PkBdEK2.png)

``` r

# now I'm in real trouble
theme_set(theme_test())
theme_update(axis.text.x = element_text(colour = "blue"))
theme_update(axis.text = element_blank())
ggplot(mtcars, aes(x = mpg, y = wt)) +
    geom_point()
#> Error in unit(rep(just$vjust, n), "npc"): 'x' and 'units' must have length > 0
```

![](https://i.imgur.com/3mw8r1v.png)

<sup>Created on 2019-02-22 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by karawoo** [comment]
> And when you create a theme, you should not set a property twice in the same inheritance branch? (as in setting colour in both `axis.text` and `axis.text.x`)

I do not think this is true. Inheritance lets you set some consistent defaults without having to repeat a bunch of code, and then make specific tweaks as needed. It's perfectly reasonable to set `axis.text` to whatever you _generally_ want the axis text to be, but change `axis.text.x` (or `axis.text.x.bottom` or whatever) to something else.

**Comment by ptoche** [comment]
Thanks Kara, the key idea is that setting ``axis.text`` in a ``theme_update()`` doesn't "spill" over to ``axis.text.x`` or ``axis.text.y`` if the latter have been set before, something I'll try to remember.

**Comment by ptoche** [comment]
@karawoo ,

I just came across a possibly related issue. You write 

> It's perfectly reasonable to set `axis.text` to whatever you _generally_ want the axis text to be, but change `axis.text.x` (or `axis.text.x.bottom` or whatever) to something else.

I would expect that to be true of `strip.text` and `strip.text.x`, right? The manual explicitly states

> `strip.text.x` [...] inherit from strip.text or can be specified separately

So why is the following generating an error? What am I doing wrong? Thanks!

    library("ggplot2")
    theme_update(strip.text = element_blank()) 
    theme_update(strip.text.x = element_text(color = "red"))

    ggplot(mpg, aes(displ, hwy)) + 
        geom_point() + 
        facet_wrap(~class)

    ## Error in unit(rep(just$hjust, n), "npc") : 
      'x' and 'units' must have length > 0

**Comment by clauswilke** [comment]
@ptoche Could you please file a separate issue for this latest case? Regardless of what we think the intended outcome from the `theme_update()` call should be, it should not error out. And is it possible to trigger the same error without any calls to `theme_update()`?
