### ISSUE TITLE
Feature request: rlang/purrr-style anonymous functions in stat_function

### ISSUE THREAD

**Issue by dkahle** [tidyverse/ggplot2#3159]
It'd be nice to be able to specify __rlang__/__purrr__ style anonymous functions in `stat_function()`:
```r
df <- data.frame(x = 1:10, y = (1:10)^2)
ggplot(df, aes(x, y)) + 
  geom_point() +
  stat_function(fun = ~ .x^2)
```
Associated pull request forthcoming.

**Comment by yutannihilation** [comment]
@hadley @thomasp85 @clauswilke 
Because of the popularity of rlang-style lambda notation among tidyverse packages, I think it's natural to accept this proposal. (I'm going to make similar changes all over the places in ggplot2 where the users can use functions). Any concerns?

**Comment by clauswilke** [comment]
Other than the comments I made, no concerns.
