### ISSUE TITLE
Request: Convert ggplot to static image

### ISSUE THREAD

**Issue by MCM-Math** [tidyverse/ggplot2#3166]
I'm wondering if there is anything that can be done to a ggplot in-code to convert it to a static image that doesn't rescale itself when put in a grid or anything like that.  Static image, fixed dimensions for everything.  If not, it would be helpful to me, and I'm sure many other people, to introduce such a feature.

**Comment by clauswilke** [comment]
I don't think this is a feature that makes sense in ggplot2. You can already do it with grid:
``` r
library(ggplot2)
library(grid)
p <- ggplot(iris, aes(Sepal.Length, Sepal.Width)) + geom_point()
g <- ggplotGrob(p)
g <- editGrob(g, vp = viewport(width = unit(2, "in"), height = unit(2, "in")))
grid.newpage()
grid.draw(g)
```

![](https://i.imgur.com/t2eCF72.png)

<sup>Created on 2019-02-26 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

It might conceptually make sense in [cowplot,](https://github.com/wilkelab/cowplot) which I think of as a library to draw with and on plots. Feel free to open a feature request there, though I may not get to it particularly quickly.

**Comment by MCM-Math** [comment]
This doesn't work:

`sampleSet <- head(mtcars)

img1 <- ggplot(sampleSet, aes(x=rownames(sampleSet), y=mpg,group=1))+
  geom_bar(stat='identity', aes(fill=mpg),position='dodge')+
  ggtitle("MPG graph") +
  xlab("Car Names") + ylab("mpg") +
  theme(plot.title = element_text(hjust = 0.5))

g <- ggplotGrob(img1)
img2 <- editGrob(g, vp = viewport(width = unit(2, "in"), height = unit(2, "in")))

grid.arrange(img1, grid.arrange(img1, img2, ncol = 2), ncol = 2)`

I'm on a work computer, so it seems I'm not able to include a screenshot, but certain ratios are preserved, a lot is rescaled.  I'm looking for something truly fixed, like a screen shot, but in-code.  This is for an automated process.

**Comment by clauswilke** [comment]
It works as expected if you use `cowplot::plot_grid()`. I don't know what `grid.arrange()` does. It may mess with the viewport, in which case you'd have to wrap the grob into another `grobTree()`.

``` r
library(ggplot2)
library(grid)

sampleSet <- head(mtcars)

img1 <- ggplot(sampleSet, aes(x=rownames(sampleSet), y=mpg,group=1))+
  geom_bar(stat='identity', aes(fill=mpg),position='dodge')+
  ggtitle("MPG graph") +
  xlab("Car Names") + ylab("mpg") +
  theme(plot.title = element_text(hjust = 0.5))

g <- ggplotGrob(img1)
img2 <- editGrob(g, vp = viewport(width = unit(2, "in"), height = unit(2, "in")))

cowplot::plot_grid(img1, cowplot::plot_grid(img1, img2, ncol = 2), ncol = 2)
```

![](https://i.imgur.com/xmrOLUM.png)

<sup>Created on 2019-02-26 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by MCM-Math** [comment]
Again, the graph didn't maintain relative scales like a scaled screenshot: the font sizes are the same, and distances like the legend from the graph are the same.  I'm wondering if there is, or could be, a way to actually convert a ggplot to an image in-code for a table in R Markdown.

**Comment by clauswilke** [comment]
You can always save your graphic as a png and then read it back in if that's what you want.
