### ISSUE TITLE
theme inheritance problem, e.g. strip.text and strip.text.x

### ISSUE THREAD

**Issue by ptoche** [tidyverse/ggplot2#3169]
Probably related to [https://github.com/tidyverse/ggplot2/issues/3157](https://github.com/tidyverse/ggplot2/issues/3157). Filed separately for clarity, as suggested by @clauswilke 

The manual states:

> `strip.text.x` [...] inherit from strip.text or can be specified separately

But the following produces an error.

    library("ggplot2")
    theme_update(strip.text = element_blank()) 
    theme_update(strip.text.x = element_text(color = "red"))

    ggplot(mpg, aes(displ, hwy)) + 
        geom_point() + 
        facet_wrap(~class)

    ## Error in unit(rep(just$hjust, n), "npc") : 
      'x' and 'units' must have length > 0

**Comment by clauswilke** [comment]
Does the same problem arise when you make these changes via `theme()` statements in the actual plot?

**Comment by ptoche** [comment]
Yes, the following produces the same error message:

    library("ggplot2")
    ggplot(mpg, aes(displ, hwy)) + 
        geom_point() + 
        facet_wrap(~class) + 
        theme(strip.text = element_blank(), 
             strip.text.x = element_text(color = "red")) 

    Error in unit(rep(just$hjust, n), "npc") : 
      'x' and 'units' must have length > 0

but each without the other does not.

**Comment by thomasp85** [comment]
The problem is that the `strip.text.x` specification is incomplete... as you have removed the ancestor element the `element_text()` must create a complete specifications including size, margin, etc...
