### ISSUE TITLE
scale_color_grandient2 low option not working

### ISSUE THREAD

**Issue by lpantano** [tidyverse/ggplot2#3178]
Hi,

I think I found a bug, I tried to find if this was already reported but couldn't find it, sorry if I am duplicating the issue.

I was using scale_color_grandient2 to set up low, mid and high colors, but I found that the low option is ignored. When used with high only, it will use white no matters what, when used with high and mid it will use mid as the low value in the plot.

Thanks for this awesome package!

```r
library(ggplot2)
df <- data.frame(
     x = runif(100),
     y = runif(100),
     z1 = rnorm(100),
     z2 = abs(rnorm(100))
 )

# this works
ggplot(df, aes(x, y)) +
     geom_point(aes(colour = z2)) +
     scale_colour_gradient(low = "blue", high = "black")

# this should be blue not white
ggplot(df, aes(x, y)) +
     geom_point(aes(colour = z2)) +
     scale_colour_gradient2(low = "blue", high = "black")

# this seems to put orange as the low calu
ggplot(df, aes(x, y)) +
    geom_point(aes(colour = z2)) +
     scale_colour_gradient2(low = "blue", high = "black", mid = "orange")
```

PS:I hope I did it right and give all the information. I couldn't make reprex working totally.

**Comment by clauswilke** [comment]
You need to set the `midpoint` parameter as appropriate for your data. By default `midpoint = 0`, and that's the lowest value you have in `z2`.

**Comment by lpantano** [comment]
oh well, RTFM, sorry about wasting your time, I spent time reading the
other options and not that one... so used to have the work done for me with
scales.

sorry, and thanks for replying.
