### ISSUE TITLE
Review duplicated examples about multiple notations

### ISSUE THREAD

**Issue by yutannihilation** [tidyverse/ggplot2#3181]
Some functions accept multiple ways of specification. It's useful to show that the multiple notations can generate the same results, but it's not necessary to execute all the examples. In order to reduce the check time, we need to restructure these examples (e.g. commenting out the less promoted notations)

* anonymous functions (`function(x)` vs `~`)
    * `stat_function()`
* facet specs (`vars()` vs `~` vs character)
    * `facet_wrap()`
    * `facet_grid()`

For anonymous functions, I think we should wait for ggplot2 to get support for `~` notation in all the places that accept functions.

**Comment by clauswilke** [comment]
Let's enumerate the functions that this applies to. Of the top of my head, I can think of:

- `stat_function()`
- `facet_wrap()`
- `facet_grid()`

Something else?

**Comment by yutannihilation** [comment]
Thanks. At the moment, they are exactly what I'm thinking about.
