### ISSUE TITLE
scale_colour_manual(palette=foo): cannot coerce type 'closure' to vector of type 'character'

### ISSUE THREAD

**Issue by sjackman** [tidyverse/ggplot2#3182]
Using the `palette` argument of `scale_colour_manual` yields the error:
`Error in as.vector(x, "character"): cannot coerce type 'closure' to vector of type 'character'`

My apologies in advance if it's my error.

\@th4ckl on Twitter says…

> I don't think this works at the moment. `palette` is passed to manual_scale, but it looks like manual_scale always defines a new `pal` that is then passed on to discrete_scale. Looks like a bug to me.

https://twitter.com/th4ckl/status/1104207569034199040

### Reprex

``` r
library(ggplot2)
library(Polychrome)

# Does not work.
alphabet_colors <- function(n) as.vector(Polychrome::alphabet.colors(n))
ggplot(diamonds, aes(x = carat, y = price, colour = clarity)) +
    geom_point() +
    scale_colour_manual(palette = alphabet_colors)
#> Error in as.vector(x, "character"): cannot coerce type 'closure' to vector of type 'character'

# Works!
ggplot(diamonds, aes(x = carat, y = price, colour = clarity)) +
    geom_point() +
    scale_colour_manual(values = as.vector(Polychrome::alphabet.colors(8)))
```

![](https://i.imgur.com/ThetjcJ.png)

<sup>Created on 2019-03-09 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by clauswilke** [comment]
I don't think `scale_colour_manual()` was ever meant to be used this way but I see that the documentation creates this impression. It would be fairly easy to fix this for the manual scales, but now I'm worrying that the problem exists for many other scales also. The fundamental problem is overly eager forwarding of arguments to `discrete_scale()`.

``` r
library(ggplot2)
library(Polychrome)

# Does not work.
alphabet_colors <- function(n) as.vector(Polychrome::alphabet.colors(n))
ggplot(diamonds, aes(x = carat, y = price, colour = clarity)) +
  geom_point() +
  scale_colour_viridis_d(palette = alphabet_colors)
#> Error in as.vector(x, "character"): cannot coerce type 'closure' to vector of type 'character'
```
<sup>Created on 2019-03-10 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by sjackman** [comment]
Settings `values` rather than` `palette` works well enough for me. How is the `palette` argument meant to be used; is there an example in the documentation?

**Comment by clauswilke** [comment]
It's not meant to be used at all. The bug is that `palette` is accessible and mentioned in the documentation.

**Comment by sjackman** [comment]
Great. Thanks for the clarification. Feel free to close this issue if you like.
