### ISSUE TITLE
gplot2 3.1.0 on a fresh setup does not install `hexbin` package

### ISSUE THREAD

**Issue by pachamaltese** [tidyverse/ggplot2#3183]
gplot2 3.1.0 on a fresh setup does not install `hexbin` package

``` r
library(tidyverse)
library(modelr)

diamonds2 <- diamonds %>%
  filter(carat <= 2.5) %>%
  mutate(lprice = log2(price), lcarat = log2(carat))

ggplot(diamonds2, aes(lcarat, lprice)) +
  geom_hex(bins = 50)
#> Warning: Computation failed in `stat_binhex()`:
#> Package `hexbin` required for `stat_binhex`.
#> Please install and try again.
```

![](https://i.imgur.com/VeuS0Ki.png)

<sup>Created on 2019-03-13 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by clauswilke** [comment]
This is on purpose. hexbin is listed as a "suggested" package, which means it's not required for ggplot2 to function but if you have it installed it unlocks additional features.
