### ISSUE TITLE
when using annotation as first layer with x discrete and annotation xmin/xmax = -Inf/Inf error 

### ISSUE THREAD

**Issue by smouksassi** [tidyverse/ggplot2#3184]
Hi developpers ! 
I posted first on Rstudio Community 
https://community.rstudio.com/t/understanding-when-and-why-discrete-value-supplied-to-continuous-scale-happens/26011/5 
but then it was thought of as a potential bug that is maybe related to 
https://github.com/tidyverse/ggplot2/issues/3120
Basically when we want to annotate a plot with discrete x scale edge to edge it errors out unless we have a fake first geom blank
when we specify the levels as xmin or xmax the order get changed  
I am on ggplot2_3.1.0.9000
``` r
require(ggplot2)
#> Loading required package: ggplot2
# geom blank make the scales wider than what we want but it works

ggplot(diamonds, aes(x = cut, y = price)) +
  geom_blank()+
  annotate("rect",
           xmin = -Inf, xmax = Inf,
           ymin = 15, ymax = 15000, fill = "lightblue",
           alpha = .2
  )+
  stat_summary(data=diamonds,fun.y="median",geom="line",mapping = aes(group=1L))
```

![](https://i.imgur.com/C2C1c1I.png)

``` r

ggplot(diamonds, aes(x = cut, y = price)) +
  annotate("rect",
           xmin = -Inf, xmax = Inf,
           ymin = 15, ymax = 15000, fill = "lightblue",
           alpha = .2
  )+
  stat_summary(data=diamonds,fun.y="median",geom="line",mapping = aes(group=1L))
#> Error: Discrete value supplied to continuous scale

#  cut order changed annotation does not start from the edge of plot
ggplot(diamonds, aes(x = cut, y = price)) +
  annotate("rect",
           xmin = "Fair", xmax = "Ideal",
           ymin = 15, ymax = 15000, fill = "lightblue",
           alpha = .2
  )+
  stat_summary(data=diamonds,fun.y="median",geom="line",mapping = aes(group=1L))
```

![](https://i.imgur.com/t4H3Sw3.png)

<sup>Created on 2019-03-13 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by yutannihilation** [comment]
Here's a simpler reprex. This seems a possible bug (?) of guessing the type of scale. For a workaround, you can manually add `scale_x_discrete()` to explicitly specify the type of the X scale.

``` r
library(ggplot2)

d <- data.frame(x = letters[1:10], y = 1:10, stringsAsFactors = FALSE)

ggplot() +
  geom_point(aes(x, y), d) +
  geom_rect(aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax),
            data.frame(xmin = -Inf, xmax = Inf, ymin = 4, ymax = 6))
```

![](https://i.imgur.com/mnfrXw3.png)

``` r

ggplot() +
  geom_rect(aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax),
            data.frame(xmin = -Inf, xmax = Inf, ymin = 4, ymax = 6)) +
  geom_point(aes(x, y), d)
#> Error: Discrete value supplied to continuous scale

ggplot() +
  geom_rect(aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax),
            data.frame(xmin = -Inf, xmax = Inf, ymin = 4, ymax = 6)) +
  geom_point(aes(x, y), d) +
  scale_x_discrete()
```

![](https://i.imgur.com/JvzeInH.png)

<sup>Created on 2019-03-14 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

**Comment by smouksassi** [comment]
I am using annotation as first layer in order for it to be first i.e. in the bacground,  repeated across facets and to avoid affecting scales.
here is few examples.
p1 workaround with geom_blank make scales reflect original data ( can be desirable in some settings)
p2 works as expected after adding scale_x_discrete() ( thanks @yutannihilation )
p3 explicitly stating xmin = "Fair" and xmax = "Ideal" make the scale ignore the order of the cut (unexepected output)
p4 uses numerical values 0/6  but this is affecting the scales maybe due to latest annotation modifications
``` r
library(ggplot2)
library(egg)
#> Loading required package: gridExtra

p1 <- ggplot(diamonds, aes(x = cut, y = price)) +
  geom_blank() +
  annotate("rect",
    xmin = -Inf, xmax = Inf,
    ymin = -Inf, ymax = 2000, fill = "lightblue",
    alpha = .2
  ) +
  stat_summary(data = diamonds, fun.y = "median", geom = "line", mapping = aes(group = 1L))

p2 <- ggplot(diamonds, aes(x = cut, y = price)) +
  annotate("rect",
    xmin = -Inf, xmax = Inf,
    ymin = -Inf, ymax = 2000, fill = "lightblue",
    alpha = .2
  ) +
  stat_summary(data = diamonds, fun.y = "median", geom = "line", mapping = aes(group = 1L)) +
  scale_x_discrete()


p3 <- ggplot(diamonds, aes(x = cut, y = price)) +
  annotate("rect",
    xmin = "Fair", xmax = "Ideal",
    ymin = -Inf, ymax = 2000, fill = "lightblue",
    alpha = .2
  ) +
  stat_summary(data = diamonds, fun.y = "median", geom = "line", mapping = aes(group = 1L)) +
  scale_x_discrete()

p4 <- ggplot(diamonds, aes(x = cut, y = price)) +
  annotate("rect",
           xmin = 0, xmax = 6,
           ymin = -Inf, ymax = 2000, fill = "lightblue",
           alpha = .2
  ) +
  stat_summary(data = diamonds, fun.y = "median", geom = "line", mapping = aes(group = 1L)) +
  scale_x_discrete()

egg::ggarrange(p1,p2,p3,p4,ncol=2)
```

![](https://i.imgur.com/0i0sK0c.png)

<sup>Created on 2019-03-14 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by yutannihilation** [comment]
> to avoid affecting scales.

For this purpose, I recommend using `annotation_raster()`.

``` r
library(ggplot2)

ggplot(diamonds, aes(x = cut, y = price)) +
  annotation_raster(alpha("lightblue", .2),
    xmin = -Inf, xmax = Inf,
    ymin = -Inf, ymax = 2000
  ) +
  stat_summary(data = diamonds, fun.y = "median", geom = "line", mapping = aes(group = 1L))
```

![](https://i.imgur.com/GccrDY2.png)

<sup>Created on 2019-03-14 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>
