### ISSUE TITLE
ggplot match color code column to another column in R dataframe

### ISSUE THREAD

**Issue by Dratt6** [tidyverse/ggplot2#3188]
I have this simple dataframe in the form:

    x    y    tissue    color_code
    1    2    nerve     #EEEE00
    2    3    brain     #33CCCC

There are several thousands rows for each tissue. Each tissue will have the same color_code (e.g. all rows with nerve have a color code of #EEEE00, etc.)

I would like to make a simple line plot of y vs x and color by tissue using the corresponding color code.

---

When I attempt to plot this, the two points are red and black, instead of yellow (#EEEE00) and cyan (#33CCCC).

```r
ggplot(df,aes(x=x,y=y,color=tissue))+
   geom_point()+
   scale_color_manual(values=df$color_code)
```

[Rplot.pdf](https://github.com/tidyverse/ggplot2/files/2972153/Rplot.pdf)

**Comment by batpigandme** [comment]
This sort of question is a better fit for https://community.rstudio.com. Do you mind asking it over there? (You might want to read https://www.tidyverse.org/help/ first to maximise your chances of getting a good answer.)

**Comment by Dratt6** [comment]
Sounds good! I just moved it over there.
