### ISSUE TITLE
geom_quantile does not have fullrange option

### ISSUE THREAD

**Issue by gdkrmr** [tidyverse/ggplot2#3190]
`geom_quantile` does not have an option to plot the regression lines for the entire range of the x-axis as `geom_smooth` has.

**Comment by yutannihilation** [comment]
Comparing `stat_quantile()` and `stat_smooth()`, this feature request doesn't seem difficult to implement, though I don't have enough knowledge to tell if `fullrange` makes sense for `geom_quantile()`...

https://github.com/tidyverse/ggplot2/blob/ae1c8f0e9160ebdc6037273eb6366424009b4d1c/R/stat-quantile.r#L73-L77

https://github.com/tidyverse/ggplot2/blob/ae1c8f0e9160ebdc6037273eb6366424009b4d1c/R/stat-smooth.r#L114-L129

**Comment by smouksassi** [comment]
Not to hijack this thread I always found it strange as well that it does not support Standard errors. The quantreg package predict method can output se and the lattice implementation let us plot quantreg with se's.

**Comment by gdkrmr** [comment]
rename this thread to "feature parity `geom_quantile` and `geom_smooth`"?

**Comment by gdkrmr** [comment]
> Not to hijack this thread I always found it strange as well that it does not support Standard errors. The quantreg package predict method can output se and the lattice implementation let us plot quantreg with se's.

I found it strange that there is a separate `geom_quantile` and not simply `geom_smooth(method = "qr")`.

**Comment by smouksassi** [comment]
predict.rqss or predict.qss  don't allow extrapolation , it incroporate se though:


```r
#if we add this to the StatQuantile supplying quand_pred_se it works making sure
# all parameters are defined also we do not provide the n for length.out
# it is fixed at 100 we can also #make this configurable
... 
rbind_dfs(lapply(quantiles, se = se, level = level,
                                           quant_pred_se, data = data, method = method,
                                           formula = formula, weight = weight, grid = grid, method.args = method.args))

...

quant_pred_se <- function(quantile, data, method, formula, weight, grid,
                       method.args = method.args, se ,level ) {
  args <- c(list(quote(formula), data = quote(data), tau = quote(quantile),
                 weights = quote(weight)), method.args)
  model <- do.call(method, args)
  grid$y <- stats::predict(model, newdata = grid)
  interval = if (se) "confidence" else "none"
  if (se){
    grid$ymin <- predict(model, newdata = grid,interval = interval)[,2]
    grid$ymax <- predict(model, newdata = grid,interval = interval)[,3]
  }
  grid$quantile <- as.factor(quantile)
  grid$group <- paste(data$group[1], quantile, sep = "-")
  grid
}
```
let me know if you would like a PR with se ( no fullrange though)

**Comment by hadley** [comment]
I think this is best handled in an extension package — my memory of quantile regression is hazy, but I think there are sufficiently complex details that it needs its own detailed treatment elsewhere.

**Comment by smouksassi** [comment]
shall I just withdraw this PR by closing it ? https://github.com/tidyverse/ggplot2/pull/3240 
( lattice implement se which I added with few other options), while we should tell the user that we cannot extrapolate qr models via a message or something else.
That was done a while back and it is now failing I can update it if there is a chance to merge.

**Comment by clauswilke** [comment]
I agree with @hadley. When I recently went over `geom_quantile()` to prevent importing of other packages, I felt that the entire code section is out of scope for ggplot2 proper and would better live in a dedicated extension package. I assume it was written before the extension system was in place.

@smouksassi I would recommend so. Have you considered writing an extension package?

**Comment by smouksassi** [comment]
I will consider it I have this geom and geom_km ( now in ggquickeda) and another idea lie geom_line_ribbon from tidybayes but where quantiles are smoothed over the x values thank you
