### ISSUE TITLE
Rebuild the stable version of pkgdown site

### ISSUE THREAD

**Issue by yutannihilation** [tidyverse/ggplot2#3191]
The dev version (https://ggplot2.tidyverse.org/dev/) of the site is fine, but it seems the stable version (https://ggplot2.tidyverse.org/) is based on this halfway commit: 2b00ea7 Probably, the stable version should be based on `v3.1.0` tag.

@hadley @batpigandme Do you know how to do this? We need to tag a new release to invoke a build?

**Comment by batpigandme** [comment]
It looks to me like that was the last commit before Hadley ran a standard web site build in https://github.com/tidyverse/ggplot2/commit/9f1904df332096f9336c663c38980aa718c24a47

I'm not sure if we have a way of retroactively building off of a tag. I think it'd have to be a manual build off of `3.1.0`.

**Comment by yutannihilation** [comment]
Thanks. Then, I'll try to find a nicer way of manual build...

**Comment by hadley** [comment]
@yutannihilation I _think_ it's possible to do by some how checking out an old version of the master branch, and a new version of the gh-pages branch. But I don't know exactly what that involves. If you figure it out, please let us know!

**Comment by yutannihilation** [comment]
Travis let us deploy from other branch than `master` when we set a branch name on `on` condition in `.travis.yml` (c.f. https://docs.travis-ci.com/user/deployment/#conditional-releases-with-on)

So, I guess, something like this would work:

```r
git checkout -b snapshot-v3.1.0 v3.1.0

# edit .travis.yml 
git add .travis.yml
git commit -m "Tweak .travis.yml"

# push tag and invoke a Travis build
git push origin -u snapshot-v3.1.0
```

Anyway I'm experimenting on my forked repo, and will hopefully send a PR!

**Comment by yutannihilation** [comment]
I succeeded to rebuild v3.1.0 site on my repo by tweaking .travis.yml a bit.

diff: https://github.com/yutannihilation/ggplot2/compare/d2a5a8c...v3.1.0-rebuild-site

Would you like me to do the same thing on this repo? Or can I send a PR? I think the latter is safer, but probably you cannot review the whole change because the diff is massive...

https://github.com/tidyverse/ggplot2/compare/gh-pages...yutannihilation:gh-pages?expand=1

**Comment by hadley** [comment]
I was thinking that you would build locally, and just push directly to the gh-pages branch.

**Comment by yutannihilation** [comment]
I'm afraid my Windows is not good at generating high-resolution plots... 🙄 But, OK, I'll do the former.

**Comment by yutannihilation** [comment]
Done! Thanks for the advices. If you find something wrong, please let me know. 

Travis job: https://travis-ci.org/tidyverse/ggplot2/jobs/508262077
commit: https://github.com/tidyverse/ggplot2/commit/5ce070877e36d4325710f56a0e3bc08f707c3499
