### ISSUE TITLE
geom_jitter changes zero values to non-zero values

### ISSUE THREAD

**Issue by sn248** [tidyverse/ggplot2#3193]
`geom_jitter()` changes the `y` values when I think it should not.

```r
df <- data.frame(ID = c(1:10), Y = 0, TYPE = c("Yes","No"))
ggplot(data = df, aes(x = as.factor(TYPE), y = Y)) + geom_jitter()
```
`Y` values are all zero, but employing `geom_jitter()` introduces jitter in the `y` direction, I was only expecting points to be jittered to be along `x` axis.

![image](https://user-images.githubusercontent.com/15050584/54569429-3fcdc600-49b1-11e9-9b8d-427aad97c9a6.png)

`geom_boxplot()` or `geom_point()` do not change the `y` values, as expected.

**Comment by yutannihilation** [comment]
Jittering might be confusing when there's only one value (c.f. #3001), but this is what it is. If you need horizontal jitters only, you can set `height` to `0`.

``` r
library(ggplot2)

df <- data.frame(ID = c(1:10), Y = 0, TYPE = c("Yes","No"))
ggplot(data = df, aes(x = as.factor(TYPE), y = Y)) +
  geom_jitter(height = 0)
```

![](https://i.imgur.com/AOwt7Zm.png)

<sup>Created on 2019-03-19 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>
