### ISSUE TITLE
@import rlang?

### ISSUE THREAD

**Issue by yutannihilation** [tidyverse/ggplot2#3195]
[Lionel said](https://github.com/tidyverse/ggplot2/pull/3161#pullrequestreview-215714849):

> Our default practice is to import the whole rlang package and use the non-qualified form.

If it's a common practice among tidyverse, I think we should follow it. It is probably good for performance (though I'm not sure how much it matters).

**Comment by hadley** [comment]
Agreed

**Comment by yutannihilation** [comment]
OK, then I will do this after the existing big PRs are gets merged.

**Comment by thomasp85** [comment]
@yutannihilation which PRs were you referencing? Can this be done now?

**Comment by yutannihilation** [comment]
Will do. But, I'm sure the PR will conflict with others, and I'm afraid I won't have much time for fixing it immediately this month. Feel free to take over if you feel I'm not responsive!
