### ISSUE TITLE
Can ggplot2 connect scatter points as a fitted style just like excel?

### ISSUE THREAD

**Issue by hoasxyz** [tidyverse/ggplot2#3199]
```
library(tidyverse)

data <- tibble(
  a = c(1, 2, 3, 4, 5),
  b = c(9, 5, 6, 8, 4)
)
ggplot(data, aes(x = a, y = b)) +
  geom_line()
```
![excel](https://github.com/hoasxyz/mdphotos/raw/master/another/excelplot.png)

**Comment by yutannihilation** [comment]
You can use `geom_smooth()` or `ggalt::geom_xspline()`. For future reference, this sort of question is a better fit for StackOverflow or [RStudio Community](https://community.rstudio.com/).

``` r
library(tidyverse)

data <- tibble(
  a = c(1, 2, 3, 4, 5),
  b = c(9, 5, 6, 8, 4)
)

ggplot(data, aes(x = a, y = b, group = 1)) +
  geom_point() +
  ggalt::geom_xspline()
```

![](https://i.imgur.com/Fh6FLRU.png)

<sup>Created on 2019-03-22 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by hoasxyz** [comment]
THX!
