### ISSUE TITLE
default formula for geom_smooth(method = "gam")

### ISSUE THREAD

**Issue by behrman** [tidyverse/ggplot2#3203]
In observing students use `geom_smooth()`, I've seen a large proportion not use `method = "gam"` correctly. Students leave off the `formula` argument and get the equivalent of `method = "lm"`, which is probably not what they intended.

I'd consider having a default `formula` when users don't provide one and use `method = gam`, perhaps the same formula used by `"auto"` when there are more than 1000 observations.

**Comment by clauswilke** [comment]
This was previously discussed in #1931 and addressed via improvements in the documentation in #2681. If people use the `method` argument then at a minimum they should read the documentation for this argument, which now explicitly addresses this point.

**Comment by behrman** [comment]
Those seeking to use `method = "gam"` may not have a good understanding of what formulas are available and be happy with the default used by `"auto"`. Is there any harm is using the same default as used by `"auto"` when the user does not specify a formula to `method = "gam"`? What they are currently getting is same as supplying `method = "lm"`, which is probably not what they intend.

**Comment by clauswilke** [comment]
Why are they specifying `method = "gam"` if they haven't read the documentation and don't understand how gams work?

The problem is that there is a default formula set, `formula = y ~ x`, as you can see in the documentation. So there's no good way to detect whether the user has provided a formula or not.

**Comment by behrman** [comment]
I wish I knew why students supply `method = "gam"` if they don't really understand how it works. I see your point for the current behavior. Thanks for the explanation.

The solution may be for me to better teach our students how `geom_smooth()` works.
