### ISSUE TITLE
Boxplot whiskers using plot vs ggplot2

### ISSUE THREAD

**Issue by jprice80** [tidyverse/ggplot2#3204]
Hi All,

I was putting together some examples and ran across an interesting difference between plot and ggplot2 boxplot whiskers creation.  Please see the reproducible example below.  Results seem to be consistent between plot and ggplot2 for the "ctrl" and "trt2" but the whiskers are quite a bit different for "trt1".  Did I make a mistake?

library("ggplot2")
library("dplyr")
library("datasets")

data("PlantGrowth")

PlantGrowth %>% ggplot(aes(x = group, y = weight)) +
  geom_boxplot()

plot(x=PlantGrowth$group, y=PlantGrowth$weight)

**Comment by ptoche** [comment]
from ``?geom_boxplot``, you can see that there are subtle differences in the way the whiskers are computed. I'm guessing that's the cause. In addition, see below how to produce an example with ``reprex()``. 

> 
> The lower and upper hinges correspond to the first and third quartiles (the 25th and 75th percentiles). This differs slightly from the method used by the boxplot() function, and may be apparent with small samples. See boxplot.stats() for for more information on how hinge positions are calculated for boxplot().
> 
> The upper whisker extends from the hinge to the largest value no further than 1.5 * IQR from the hinge (where IQR is the inter-quartile range, or distance between the first and third quartiles). The lower whisker extends from the hinge to the smallest value at most 1.5 * IQR of the hinge. Data beyond the end of the whiskers are called "outlying" points and are plotted individually.


``` r
library("reprex")
library("ggplot2")
library("dplyr")
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
library("datasets")

data("PlantGrowth")

PlantGrowth %>% ggplot(aes(x = group, y = weight)) +
    stat_boxplot(geom = "errorbar", width = 0.5) +  # add whiskers
    geom_boxplot(width = 0.5)
```

![](https://i.imgur.com/jeWVtEa.png)

``` r

plot(x=PlantGrowth$group, y=PlantGrowth$weight)
```

![](https://i.imgur.com/1rlIIsw.png)

<sup>Created on 2019-03-25 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by yutannihilation** [comment]
Thanks @ptoche.

**Comment by BobMuenchen** [comment]
I ran this data through SAS and SPSS and the boxplots they created match the one created by R's plot function. Has something changed recently in how ggplot creates boxplots?

**Comment by clauswilke** [comment]
One data point is right at the boundary of the upper fence so minor differences in computation can cause the point to be included or excluded. In any case, by my calculation ggplot2 gets it right, at least assuming `quantile()` and `IQR()` are correct.

``` r
library(dplyr)
PlantGrowth %>% 
  filter(group == "trt1") %>%
  mutate(upper_fence = quantile(weight)[4] + 1.5*IQR(weight)) %>%
  filter(weight > upper_fence)
#>   weight group upper_fence
#> 1   5.87  trt1     5.86375
#> 2   6.03  trt1     5.86375
```

<sup>Created on 2019-04-01 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by jprice80** [comment]
Thank you for this insight.  Indeed, if one changes the value from 5.87 to 5.85, the plot becomes nearly identical to that of R's inherent plot function, SAS, and SPSS. It is interesting to see the results swing that much between different software implementations due to change at the hundredths decimal place but this looks to be one of those rare examples.
