### ISSUE TITLE
consider making geom_smooth() formula = "auto" the default

### ISSUE THREAD

**Issue by behrman** [tidyverse/ggplot2#3205]
In observing the code of my students, I can see that many have mental models of `geom_smooth()` that lead them to use it incorrectly. Their mental model is to use the `method` argument to specify the type of smoothing, and this is reasonable. It works fine for `method = "lm"` and `method = "loess"` but not `method = "gam"`, since the default `formula` works well with `"lm"` and `"loess"` but not `"gam"`. Why not have the default `formula` be `"auto"`, which would look at the specified `method` and use `y ~ x` for `"lm"` and `"loess"` and `y ~ s(x, bs = "cs")` for `"gam"`.

I realize that the formula used by `method = "auto"` for `"gam"` is explained in the third paragraph of the help entry for the `method` argument, but in practice this is not connecting with a large proportion of the users I'm seeing.

@skaltman

**Comment by hadley** [comment]
I think it would make sense to default `formula` to `NULL`, and then fill later on where the `method = "auto"` work is done. This would be a great contribution for someone who wanted to contribute to ggplot2 for the first time 😄
