### ISSUE TITLE
Let some wrapper functions not to use `...`

### ISSUE THREAD

**Issue by atusy** [tidyverse/ggplot2#3210]
Related to #3196, using `...` cannot check argument names, and cannot indicate candidate arguments in IDE.
For some wrappers like `scale_x_reverse`, I think user friendly implementations are functions modifying formals.
However, this may not be friendly for developers...
See below for an example.

``` r
library(ggplot2)
library(scales)

scale_x_reverse2 <- scale_x_continuous
formals(scale_x_reverse2)$trans <- alist(trans = reverse_trans())$trans

# Tests

## Misspelling an argument's name gives error
qplot(1:10, 1:10) + 
  scale_x_reverse2(nme = "x is reversed")
#> Error in scale_x_reverse2(nme = "x is reversed"): unused argument (nme = "x is reversed")

## Give name of scale_x_reverse2 implicitly
qplot(1:10, 1:10) + 
  scale_x_reverse2("x is reversed")
```

![](https://i.imgur.com/ANpvXWT.png)

<sup>Created on 2019-03-28 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by yutannihilation** [comment]
Could you join the discussion on #3196? I think this is a possible approach, though I'm not sure how feasible this is.
