### ISSUE TITLE
stat.smooth: Add se.type option for "prediction" interval

### ISSUE THREAD

**Issue by baderstine** [tidyverse/ggplot2#3214]
https://github.com/tidyverse/ggplot2/blob/92d27779e210ce16f441eeec26926b8b045a47a8/R/stat-smooth-methods.r#L14

Suggest something like the following, where interval could take the value "confidence" or "prediction":

    predictdf.default <- function(model, xseq, se, level, se.type="confidence") {
        pred <- stats::predict(model, newdata = new_data_frame(list(x = xseq)), se.fit = se,
    level = level, interval = if (se) se.type else "none")
   ...

**Comment by hadley** [comment]
I think this needs to be handled elsewhere given the generality of `geom_smooth()`, my regrets for adding a standard error by default (since its interpretation is so fraught), and the variation across model fitting methods.
