### ISSUE TITLE
add link to `stat()` in pkgdown website

### ISSUE THREAD

**Issue by dongzhuoer** [tidyverse/ggplot2#3219]
ggplot2 introduces `stat(x)` to replace `..x..` for using [calculated aesthetics](https://ggplot2.tidyverse.org/reference/stat.html). But it such a pity that the pkgdown website, especially [Reference](https://ggplot2.tidyverse.org/reference/index.html) page doesn't include a link to that function.

One day I can't remember the function's name, thus want to check it on pkgdown website. I look around for a while, but just can't find it. Finally Google "ggplot Computed variable" leads me to that page.

So I think the pkgdown website should tell user how to use calculated aesthetics at a proper position.

**Comment by yutannihilation** [comment]
Oh, good catch. Thanks. It seems some more topics are missing from `_pkgdown.yml`...

> Warning: Topics missing from index: expand_scale, stat, stat_sf_coordinates, summarise_plot, vars
(https://travis-ci.org/tidyverse/ggplot2/jobs/512667960#L2175)

**Comment by yutannihilation** [comment]
Since this is about the pkgdown site, I don't think this is a milestone for the next release. Anyway I'll do this.

**Comment by thomasp85** [comment]
You are technically correct :-) I just wanted to make sure this was prioritised... Thanks for making the PR
