### ISSUE TITLE
GGPlot2 Failing Silently in Windows 10

### ISSUE THREAD

**Issue by Atomizer15** [tidyverse/ggplot2#3220]
When I use GGPlot2 in Windows 10, I get the standard grey screen for "ggplot" in the plot console. But when i use geom_* I get no plot and just a list of parameters in the regular console. Also, I should note that if I use the old "plot" function, it works as expected.

> ggplot(data=cars)
> geom_point(mapping = aes (x=speed, y=dist))
mapping: x = ~speed, y = ~dist 
geom_point: na.rm = FALSE
stat_identity: na.rm = FALSE
position_identity

The plot console stays grey and blank. I've tried uninstalling and reinstalling the GGPlot2 and RConsole and R. Am I missing something?

**Comment by batpigandme** [comment]
If this is the exact code you are running, then you're missing the `+` that connects your data and geom (after the ggplot line). Also note that R is case-sensitive, so GGPlot2 and ggplot2 are not equivalent. 

This sort of question is a better fit for https://community.rstudio.com. Do you mind asking it over there? (You might want to read https://www.tidyverse.org/help/ first to maximise your chances of getting a good answer.)

**Comment by Atomizer15** [comment]
No problem. Thank you.
