### ISSUE TITLE
breaks for integer data

### ISSUE THREAD

**Issue by ptoche** [tidyverse/ggplot2#3222]
Any support for the idea that ggplot should only show integer breaks if the data type is ``integer``? If none, please close this issue.

Current default:

``` r
library("reprex")
library("ggplot2")
df = data.frame(x = 0:8, 
                y = 1:9)
ggplot(df, aes(x, y)) 
```

![](https://i.imgur.com/nRFD4vp.png)

The suggestion is that if the data is of integer type, ``ggplot`` would restrict breaks to be at integer values only, e.g..

``` r

library(scales)
ggplot(df, aes(x, y)) + scale_y_continuous(breaks = pretty_breaks())
```

![](https://i.imgur.com/99QJ852.png)

<sup>Created on 2019-04-02 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by thomasp85** [comment]
I think the fact that few users are aware of integer/numeric difference and whether their data is one or the other will make adding this a source of confusion...
