### ISSUE TITLE
transformation formulas give incorrect values for exponents

### ISSUE THREAD

**Issue by matthewParksViome** [tidyverse/ggplot2#3224]
I noticed that the values calculated by the `trans` formula for `sec_axis` are incorrect.

In particular, I want to give the log values and have a `sec_axis` that plots both the log and non-log values.

It seems to be a problem when the `trans` formula has an exponential form other than `exp`.

**Minimal reproducible example:**

```r
df=data.frame(x=seq(from=0,to=-0.95,by=-0.05) , y=rnorm(20))
# just some numbers between [-1,0] on x axis. 
# They are intended to represent logarithmic values, and the the goal
# is to plot the non-logarithmic values as a second y-axis.
# Note the simple change of base to log10

ggplot(data=df , aes( x = x/log(10) , y = y ) ) +
 geom_point() + 
scale_x_continuous(sec.axis = sec_axis(~10^(.)) )
```

Since all `x` values are in `[0,1]`, then by definition, the `sec_axis` should not give any values above `1`.  But it does. Note how the rightmost data point on the x-axis has log value = 0, but on the secondary axis it has value > 1.0.  This is, of course, incorrect since `a^0 = 1` for all numbers `a`.

![Rplot10 pdf](https://user-images.githubusercontent.com/45396124/55564907-e19a2600-56c6-11e9-8df7-f099eb4a7ec4.png)

**Comment by batpigandme** [comment]
I think this is the same bug as https://github.com/tidyverse/ggplot2/issues/2978 [Ticks misaligned for sec_axis with some scale transformations and data](https://github.com/tidyverse/ggplot2/issues/2978 )

**Comment by matthewParksViome** [comment]
@batpigandme  , so it is still unresolved? i.e. the bug remains in the latest version of  ggplot 3.1.0 ?

**Comment by batpigandme** [comment]
Correct. When it's resolved, the issue will be closed.

**Comment by dpseidel** [comment]
If you install PR #3040's branch, this has been patched there. We hope to merge it soon.

**Comment by batpigandme** [comment]
Great. Since This is a dupe for #2978, I'm going to close this as a duplicate issue.
