### ISSUE TITLE
Remove build time code execution

### ISSUE THREAD

**Issue by thomasp85** [tidyverse/ggplot2#3233]
One example:

https://github.com/tidyverse/ggplot2/blob/47d65ddbb92066513578846512f98355d9b5e0d9/R/theme-current.R#L3

but we need to scour the code base for others

**Comment by clauswilke** [comment]
I was planning to rewrite how themes work. This line would be part of that. But I'm not sure I can do it before April 30. May have to wait until after ggplot2 3.2.0.

**Comment by thomasp85** [comment]
yeah... I don't think we can get a whole new theme infrastructure in on this release... The above was just an example — we need to go through it all

**Comment by clauswilke** [comment]
However, I do have a half-finished PR (#2784). I'll spend a few hours to see if it can be brought into a mergeable state.
