### ISSUE TITLE
Unicode text is misaligned in the legend

### ISSUE THREAD

**Issue by lz1nwm** [tidyverse/ggplot2#3260]
I've noticed there is difference between rendering latin and unicode characters in the legend. It seems that unicode characters create additional spaces after the labels. I wonder is it a bug and is there a workaround?

Thanks!

``` r
## ggplot2 3.1.1
library(ggplot2)
p <- 
    ggplot(ToothGrowth, 
           aes(supp, 
               len,
               color = supp)) + 
    geom_point()+
    theme(axis.title = element_blank(),
          legend.title = element_blank())

r1 <- p + 
      scale_colour_manual(label=c('AB CD EF','ab cd ef'),values = c("blue", "red"))
r2 <- p + 
      scale_colour_manual(label=c('AБ ВГ ДЕ','аб вг де'),values = c("blue", "red"))
gridExtra::grid.arrange(r1, r2, ncol=1)
```

![](https://i.imgur.com/DPUgHpB.png)

``` r
b1 <- p + 
      scale_colour_manual(label=c('AB CD EF','ab cd ef'),values = c("blue", "red")) + 
      theme(legend.direction = 'horizontal', legend.position = 'bottom')    
b2 <- p + 
      scale_colour_manual(label=c('аб яя яя','аб яя яя'),values = c("blue", "red")) + 
      theme(legend.direction = 'horizontal', legend.position = 'bottom')    
gridExtra::grid.arrange(b1, b2, ncol=1)
```

![](https://imgur.com/mFNJS6K.png)

**Comment by thomasp85** [comment]
This is likely due to poor support by the graphic device you are rendering to and is outside the control of ggplot2. Can I get you to try the same code using a Cairo device (`png(..., type = 'cairo')` ands if that fixes the problem

**Comment by lz1nwm** [comment]
Thanks @thomasp85, setting `type = 'cairo'` solved my issue. I hope that soon RStudio will make `cairo` default for the Plots pane. My issue is likely related to this one [rstudio/rstudio/#2142](https://github.com/rstudio/rstudio/issues/2142).

**Comment by thomasp85** [comment]
RStudio will use the default device type, which I believe can be set with an option... but I agree that it is a bit annoying - especially on Windows where the default device is horrible...
