### ISSUE TITLE
Implement a better way to get the colours or range from a scale

### ISSUE THREAD

**Issue by flying-sheep** [tidyverse/ggplot2#3266]
`scale_(colour|fill)_gradient`, `scale_(colour|fill)_gradientn`, `scale_(colour|fill)_grey`, `scale_alpha_continuous`, and so on all use opaque functions from the `scales` package instead of some structure that holds their palette/colours.

It would be useful to have a standard way of getting the full input palette/range instead of something like this:

```r
scale_params <- function(scale) {
    proto_env <- environment(scale$palette)
    palette_fun_env <- environment(proto_env$f)
    switch(scale$scale_name,
        gradient =, gradientn = list(colours = palette_fun_env$colours),
        grey = list(colours = scale$palette(2)),  # exec(grey.colors, 2, !!!as.list(palette_fun_env)))
        alpha_c = list(range = palette_fun_env$range),
        ...
    )
}
```

**Comment by hadley** [comment]
You're asking for a major redesign of the scales system with no obvious benefits. I think we're unlikely to do this so I'm going to close the issue.
