### ISSUE TITLE
Use tidy evaluation outside aes with exact values

### ISSUE THREAD

**Issue by bakaburg1** [tidyverse/ggplot2#3268]
A feature request.

It would be nice to have tidy evaluation also outside the aes() calls, especially for layers which have parameters which are not exposed by aes(), like nudges for geom_label, or in scales, themes, etc. Variables passed outside aes() should not be remapped.

The plus of this behavior would be less verbose code, easy manipulation and small bonuses like not having to specify scale_?_identity() when you don't want remapping.

The workaround now is to create an intermediate dataframe or use some magrittr magic:

```r
library(dplyr)
library(ggplot2)

#nonsense example
tibble(
    a = rnorm(100, 5, 3),
    b = rnorm(100, 3, 2),
    labs = 1:100,
    color = rep_len(1:4, 100) %>% factor,
    posy = rep_len(c(-1, -1, 1, 1)/4, 100),
    posx = rep_len(c(1, -1, -1, 1)/4, 100),
) %>% { #magrittr trick to not havin to create an intermediate variable
    DF <- .
    ggplot(DF, aes(a, b, color = color)) +
        geom_point(alpha = .2) +
        geom_text(aes(label = labs), nudge_x = DF$posx, nudge_y = DF$posy) +
        scale_x_continuous(breaks = seq(min(DF$a), max(DF$a), length.out = 5))
}
```

Instead of simply this:

```r
tibble(
    a = rnorm(100, 5, 3),
    b = rnorm(100, 3, 2),
    labs = 1:100,
    color = rep_len(1:4, 100) %>% factor,
    posy = rep_len(c(-1, -1, 1, 1)/4, 100),
    posx = rep_len(c(1, -1, -1, 1)/4, 100),
) %>% 
    ggplot(aes(a, b, color = color)) +
    geom_point(alpha = .2) +
    geom_text(aes(label = labs), nudge_x = posx, nudge_y = posy) +
    scale_x_continuous(breaks = seq(min(a), max(a), length.out = 5))
```

**Comment by thomasp85** [comment]
such a change would require substantial rewrite as well as break a lot of existing code, so I'm going to close

**Comment by moodymudskipper** [comment]
See a few ways to address this below

----------------

### 1 - You could enhance `+.gg`  

```
`+.gg` <- function(e1, e2){
  with(e1$data, ggplot2:::`+.gg`(e1, eval(e2)))
}
```

Because the rhs gets evaluated in the generic we have to quote it (hence the `eval` above)

```
df <- tibble(
  a = rnorm(100, 5, 3),
  b = rnorm(100, 3, 2),
  labs = 1:100,
  color = rep_len(1:4, 100) %>% factor,
  posy = rep_len(c(-1, -1, 1, 1)/4, 100),
  posx = rep_len(c(1, -1, -1, 1)/4, 100),
)

ggplot(df, aes(a, b, color = color)) +
  geom_point(alpha = .2) +
  quote(geom_text(aes(label = labs), nudge_x = posx, nudge_y = posy)) +
  quote(scale_x_continuous(breaks = seq(min(a), max(a), length.out = 5)))
```

-----------------------

### 2 - Same with syntactic sugar   

here we use `Q$`: in front of relevant calls to quote them : 

```
Q <- function(f){
  as.function(c(formals(f), substitute({
    mc <- match.call()
    mc[[1]] <- quote(f)
    mc
  })))
}
class(Q) <- "Q"
`$.Q` <- function(e1,e2) eval(substitute(e1(get(e2))))

  ggplot(df, aes(a, b, color = color)) +
  geom_point(alpha = .2) +
  Q$geom_text(aes(label = labs), nudge_x = posx, nudge_y = posy) +
  Q$scale_x_continuous(breaks = seq(min(a), max(a), length.out = 5)) 
```

----------------------

### 3 - Using `-.gg` instead

If you're not comfortable with overriding `+.gg` you can use `-.gg` as it's not taken and has the same operator precedence : 

```
`-.gg` <- function(e1, e2){
  with(e1$data, e1 + eval(e2))
}

ggplot(df, aes(a, b, color = color)) -
  geom_point(alpha = .2) -
  Q$geom_text(aes(label = labs), nudge_x = posx, nudge_y = posy) -
  Q$scale_x_continuous(breaks = seq(min(a), max(a), length.out = 5)) 
```

-----------------------

### 4 - Using a custom pipe   

Another way would be to create a custom pipe using the package *pipes*. In this case no need to call unexported functions or to do anything funky regarding the `"gg"` class.

```
devtools::install_github("moodymudskipper/pipes")
library(pipes

# see ?new_pipe, this is not obvious :)
`%GG>%` <- new_pipe({
  eval(substitute(with(e1$data, e1 + e2), list(
    e1 = quote(.),
    e2 = quote(BODY)[-2]))) # 1st BODY is `geom_point(., alpha = .2)`
})

ggplot(df, aes(a, b, color = color)) %GG>%
  geom_point(alpha = .2) %GG>%
  geom_text(aes(label = labs), nudge_x = posx, nudge_y = posy) %GG>%
  scale_x_continuous(breaks = seq(min(a), max(a), length.out = 5)) 
```

Because of operator precedence you have to use it on the full chain though, so you might need a "neutral" pipe  as well (which wouldn't use `with`).

```
`%GG0>%` <- new_pipe({
  eval(substitute(e1 + e2, list(
    e1 = quote(.),
    e2 = quote(BODY)[-2])))
})

ggplot(df, aes(a, b, color = color)) %GG0>%
  geom_point(alpha = .2) %GG>%
  geom_text(aes(label = labs), nudge_x = posx, nudge_y = posy) %GG>%
  scale_x_continuous(breaks = seq(min(a), max(a), length.out = 5)) 
```

**Comment by bakaburg1** [comment]
Nice solutions!!!!!

**Comment by bakaburg1** [comment]
> such a change would require substantial rewrite as well as break a lot of existing code, so I'm going to close

If you think it could be a useful change, why not to add it to future changes with low priority? at least it won't get lost.
