### ISSUE TITLE
linend doesn't work as expected for geom_segment()

### ISSUE THREAD

**Issue by zlskidmore** [tidyverse/ggplot2#3273]
According to the documentation for geom_segment(), under the last example:

https://ggplot2.tidyverse.org/reference/geom_segment.html

setting linend="butt" should round off just one side of the segment however this does not seem to occur

```R
ggplot() + geom_segment(aes(x=-1, xend=1, y=1, yend=1), size=10, lineend = "butt") + geom_segment(aes(x=-1, xend=1, y=2, yend=2), size=10, lineend = "square") + geom_segment(aes(x=-1, xend=1, y=3, yend=3), size=10, lineend = "round")
```

It does seem to add padding to the line, just wondering if it should be rounding off one end as well.

**Comment by thomasp85** [comment]
I’m unsure how it is you interpret the example. The lineend setting is symmetric and affect both ends equally

**Comment by zlskidmore** [comment]
okay I thought based on the barchart from `plot()` only one end would be rounded. Looks like i just mis-interpreated the docs.

**Comment by thomasp85** [comment]
Ah - I think you are conflating the clipping that is happening by the plot region with the lineend setting
