### ISSUE TITLE
"bins" option for dotplot to control number of bins

### ISSUE THREAD

**Issue by mluerig** [tidyverse/ggplot2#3274]
I am looking for a way to change the number of bins in a dotplot that has several facets that are on different y-scales. Because of that, binwidth doesn't work for me (e.g. first panel has values from 0-5, second 0 - 0.25, etc.), but dotplot doesn't have a "bins" argument like histogram, and stat_bindot has been removed.

**Comment by hadley** [comment]
Unfortunately that's currently outside of the scope of `geom_dotplot()`, and given the complexity of that function, it's unlikely we'll ever implement it 😞
