### ISSUE TITLE
AppVeyor tests failing

### ISSUE THREAD

**Issue by clauswilke** [tidyverse/ggplot2#3279]
The AppVeyor tests are currently failing, as discussed here: https://github.com/tidyverse/ggplot2/pull/3091#issuecomment-487417282

It's unclear to me what causes this problem. These tests pass on Travis, and also on my local build.

cc @thomasp85

**Comment by thomasp85** [comment]
I’m investigating

**Comment by thomasp85** [comment]
This has now propagated to Travis, indicating that it is a dependency thing... still unsure what is causing it
