### ISSUE TITLE
Histograms y-axes are incorrectly sized (scaled?) when plotting 2 groups of data

### ISSUE THREAD

**Issue by oranwutang** [tidyverse/ggplot2#3325]
---

Hi, 

When I try to plot two overlapped histograms the Y-axis gets adjusted for the highest values group, so both histograms gets about the same size, incorrectly representing data. As you can see in the reprex below, plots p2 and p3 have a correctly limited y-axis, but when you fuse both groups in a unique plot, it seems that group "a" reach counts as high as ~500 (which is not true).

I don't know if it is an error of mine or if this is a bug.

Thanks in advance!

```r
# insert reprex here
``` r
library(tidyverse)
library(magrittr)
#> 
#> Attaching package: 'magrittr'
#> The following object is masked from 'package:purrr':
#> 
#>     set_names
#> The following object is masked from 'package:tidyr':
#> 
#>     extract
library(plotly)
#> 
#> Attaching package: 'plotly'
#> The following object is masked from 'package:ggplot2':
#> 
#>     last_plot
#> The following object is masked from 'package:stats':
#> 
#>     filter
#> The following object is masked from 'package:graphics':
#> 
#>     layout

a <- rnorm(n = 1000)
b <- rnorm(n=5000, mean = 1)
Groups <- c(rep("a", 1000),rep("b", 5000))
Values<-c(a, b)
df2 <- data.frame(Groups, Values)  

p1<-df2 %>% ggplot(aes(Values, fill=Groups))+geom_histogram(alpha=0.3)+
  theme(panel.background = element_rect(fill="white"))

p2<-df2 %>% filter(Groups=="a") %>% 
  ggplot(aes(Values))+geom_histogram()

p3 <- df2 %>% filter(Groups=="b") %>% 
  ggplot(aes(Values))+geom_histogram()
p1
#> `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
```

![](https://i.imgur.com/bKxDaSt.png)

``` r
p2
#> `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
```

![](https://i.imgur.com/LFI3Twm.png)

``` r
p3
#> `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
```

![](https://i.imgur.com/LOg9tc1.png)

<sup>Created on 2019-05-12 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

```

**Comment by clauswilke** [comment]
Please read up on position adjustments here: https://ggplot2.tidyverse.org/reference/#section-layer-position-adjustment

You may also find this book chapter helpful. It explains why the problem you're running into is an inherent perceptual problem of overlapping/stacked histograms: https://serialmentor.com/dataviz/histograms-density-plots.html#multiple-histograms-densities

For further questions on this topic, I suggest you ask on the RStudio Community forums. The ggplot2 software is working as expected and as documented.

**Comment by oranwutang** [comment]
I feel sorry I didn't know about the "position" parameter. Thanks for your quick answer!
