### ISSUE TITLE
Replacing each .stroke by .pt?

### ISSUE THREAD

**Issue by vbuchhold** [tidyverse/ggplot2#3334]
There are two conversion constants in ggplot2: `.pt` converts millimeters to points and `.stroke` converts millimeters to 1/96 inches. According to ggplot2's [documentation](https://ggplot2.tidyverse.org/reference/graphical-units.html), we use `.pt` to convert millimeters to `lwd` units and `.stroke` to convert millimeters to `fontsize` units. However, the grid documentation says that `fontsize` is given in points, thus we should also use `.pt` to convert to `fontsize` units.

Moreover, there are essentially only four occurrences of `.stroke` in the code base:

```
./R/geom-point.r:130:          fontsize = coords$size * .pt + coords$stroke * .stroke / 2,
./R/geom-point.r:131:          lwd = coords$stroke * .stroke / 2
./R/legend-draw.r:38:      fontsize = (data$size %||% 1.5) * .pt + (data$stroke %||% 0.5) * .stroke / 2,
./R/legend-draw.r:39:      lwd = (data$stroke %||% 0.5) * .stroke / 2
```

All of them appear strange to me. In two cases, we set `lwd`. According to ggplot2's documentation, we should use `.pt` in these cases. The other two cases are also strange, because we add two values that are measured in different units (one is given in points and the other in 1/96 inches).

Perhaps I don’t understand the rationale for `.stroke`, but something appears to be inconsistent. According to the [documentation](https://ggplot2.tidyverse.org/articles/ggplot2-specs.html#point), both `size` and `stroke` are given in millimeters. However, as shown above, `stroke` is converted to `lwd` by `.stroke`, and at other places, `size` is converted to `lwd` by `.pt`:

```
./R/geom-ribbon.r:116:        lwd = aes$size * .pt,
./R/geom-segment.r:122:          lwd = coord$size * .pt,
```

Either one of the conversions is incorrect, or `size` and `stroke` cannot be measured in the same unit.

**Comment by thomasp85** [comment]
These are internal constants you shouldn't be concerned with. `.stroke` is used for the width of the pch symbol stroke only which is why it isn't occurring any other place
