### ISSUE TITLE
[feature request] different lineend types at start and end of segment

### ISSUE THREAD

**Issue by bakaburg1** [tidyverse/ggplot2#3335]
It would be nice to be able to specify two different lineend parameters for segment start and end, for example to have a round end at xend and a squared one at x.

Thanks!

**Comment by thomasp85** [comment]
That is unfortunately not technically possible with the grid graphics system

**Comment by bakaburg1** [comment]
I simulated it adding a geom_point on the top of geom_segment; the hard part was to match the sizes which I guess it's easier having access to the graphic generation code.
