### ISSUE TITLE
position_dodge(2) default is "total"

### ISSUE THREAD

**Issue by Alanocallaghan** [tidyverse/ggplot2#3339]
This is counter to previous behaviour and (imo) is a worse default. It also contradicts the documentation.

See: https://ggplot2.tidyverse.org/reference/position_dodge.html

According to the docs and previous behaviour, these should be identical:
``` r
library("ggplot2")
ggplot(mtcars, aes(factor(cyl), fill = factor(vs))) + 
  geom_bar(position = position_dodge())                                                                                                    
```

![](https://i.imgur.com/dGPnnc1.png)

``` r
ggplot(mtcars, aes(factor(cyl), fill = factor(vs))) + 
  geom_bar(position = position_dodge(preserve="single"))
```

![](https://i.imgur.com/3zH889c.png)

<sup>Created on 2019-05-23 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by karawoo** [comment]
I've [fixed the example](https://github.com/tidyverse/ggplot2/pull/3340) in the documentation. The code examples you provided are working as intended, however. `preserve = "total"` has always been the default for `position_dodge()`, which is what you're using above, and we intentionally made it the default for `position_dodge2()` in #2386.

**Comment by Alanocallaghan** [comment]
Fair dues, you're absolutely right. I was sure I'd used before and seen that behaviour.
