### ISSUE TITLE
Place the extreme ticks at the edge of the legend frame without extra padding

### ISSUE THREAD

**Issue by caijun** [tidyverse/ggplot2#3350]
The following example is to illustrate my obsessive feature request. As you see, there is a small amount of padding between the first (or the last) legend tick and legend frame. How could I remove those paddings and make the first or the last legend ticks at the edge of legend frame?
Is there also an `expand` parameter available for colorbar scales?

---

Brief description of the problem

```r
library(ggplot2)
p <- ggplot(mtcars, aes(hp, disp, color = mpg)) + 
  geom_point() + 
  scale_color_continuous(limits = c(10, 35),
                         breaks = seq(10, 35, by = 5),
                         guide = guide_colorbar(
                           direction = "horizontal",
                           title.position = "top", 
                           title.hjust = 0.5, 
                           ticks.colour = "white", 
                           frame.colour = "black", 
                           barwidth = 12)) + 
  theme(legend.position = "top")
p
```

<sup>Created on 2019-06-01 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

![image](https://user-images.githubusercontent.com/2522593/58741681-6ea2f680-844e-11e9-8ead-84941937bae8.png)

**Comment by clauswilke** [comment]
Set the `nbin` parameter to a large value (e.g., `nbin = 1000`). Maybe this should be added to the documentation.

``` r
library(ggplot2)
p <- ggplot(mtcars, aes(hp, disp, color = mpg)) + 
  geom_point() + 
  scale_color_continuous(
    limits = c(10, 35),
    breaks = seq(10, 35, by = 5),
    guide = guide_colorbar(
      direction = "horizontal",
      title.position = "top", 
      title.hjust = 0.5, 
      ticks.colour = "white", 
      frame.colour = "black", 
      barwidth = 12,
      nbin = 1000
    )
  ) + 
  theme(legend.position = "top")
p
```

![](https://i.imgur.com/P4ZnPiY.png)

<sup>Created on 2019-05-31 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by caijun** [comment]
This is exactly what I am looking for. Thank you very much. Before creating this issue, I have searched on the internet for several hours. I totally agree with you that some examples should be added to illustrate the function of `nbin` parameter in the documentation.
