### ISSUE TITLE
Registered S3 methods overwritten by 'ggplot2

### ISSUE THREAD

**Issue by Feelous** [tidyverse/ggplot2#3351]
When I open RStudio, here comes a hint

Registered S3 methods overwritten by 'ggplot2':
  method         from 
  [.quosures     rlang
  c.quosures     rlang
  print.quosures rlang

R version 3.6.0
How to deal with it? Or is there anything wrong to run it?

**Comment by thomasp85** [comment]
This is fixed devel

**Comment by Hugovdberg** [comment]
When will this be fixed on CRAN?

**Comment by thomasp85** [comment]
We are in the middle of release

**Comment by Sweissmann2018** [comment]
This seems to come up (same message) when launching packages like DESeq2, and tidyverse.

**Comment by michaelgmccarthy** [comment]
Do we know what date this will be released?
I'm using R with Power BI and this has broken a number of my reports

**Comment by batpigandme** [comment]
@michaelgmccarthy It's on CRAN now.

**Comment by michaelgmccarthy** [comment]
@batpigandme I'm getting this error with the latest version 3.6.0 on https://cran.r-project.org/
Is it supposed to be resolved on that version?

**Comment by Sweissmann2018** [comment]
What exactly are we suppose to download? was it a problem with ggplot2?

**Comment by clauswilke** [comment]
Install the latest version of ggplot2 with `install.packages("ggplot2")`.

**Comment by michaelgmccarthy** [comment]
I have removed the old version and installed the latest version and I still have this issue

**Comment by batpigandme** [comment]
I can't reproduce this. Can you please make a reprex with session information attached?

If you've never heard of a reprex before, you might want to start by reading the tidyverse.org [help page](https://www.tidyverse.org/help/).

You can install reprex by running (you may already have it, though, if you have the tidyverse package installed):
```r
install.packages("reprex")
```

Thanks

**Comment by clauswilke** [comment]
To elaborate: Please run `reprex::reprex(si = TRUE)`. You can use the example I'm posting below. I can't reproduce the problem either since I've installed v. 3.2.0.

``` r
library(ggplot2)

ggplot(mpg, aes(class, fill = class)) + 
  geom_bar()
```

![](https://i.imgur.com/5OKyuNn.png)

<sup>Created on 2019-06-17 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

<details>

<summary>Session info</summary>

``` r
devtools::session_info()
#> ─ Session info ──────────────────────────────────────────────────────────
#>  setting  value                       
#>  version  R version 3.6.0 (2019-04-26)
#>  os       macOS Mojave 10.14.5        
#>  system   x86_64, darwin15.6.0        
#>  ui       X11                         
#>  language (EN)                        
#>  collate  en_US.UTF-8                 
#>  ctype    en_US.UTF-8                 
#>  tz       America/Chicago             
#>  date     2019-06-17                  
#> 
#> ─ Packages ──────────────────────────────────────────────────────────────
#>  package     * version date       lib source        
#>  assertthat    0.2.1   2019-03-21 [1] CRAN (R 3.6.0)
#>  backports     1.1.4   2019-04-10 [1] CRAN (R 3.6.0)
#>  callr         3.2.0   2019-03-15 [1] CRAN (R 3.6.0)
#>  cli           1.1.0   2019-03-19 [1] CRAN (R 3.6.0)
#>  colorspace    1.4-1   2019-03-18 [1] CRAN (R 3.6.0)
#>  crayon        1.3.4   2017-09-16 [1] CRAN (R 3.6.0)
#>  curl          3.3     2019-01-10 [1] CRAN (R 3.6.0)
#>  desc          1.2.0   2018-05-01 [1] CRAN (R 3.6.0)
#>  devtools      2.0.2   2019-04-08 [1] CRAN (R 3.6.0)
#>  digest        0.6.19  2019-05-20 [1] CRAN (R 3.6.0)
#>  dplyr         0.8.1   2019-05-14 [1] CRAN (R 3.6.0)
#>  evaluate      0.14    2019-05-28 [1] CRAN (R 3.6.0)
#>  fs            1.3.1   2019-05-06 [1] CRAN (R 3.6.0)
#>  ggplot2     * 3.2.0   2019-06-16 [1] CRAN (R 3.6.0)
#>  glue          1.3.1   2019-03-12 [1] CRAN (R 3.6.0)
#>  gtable        0.3.0   2019-03-25 [1] CRAN (R 3.6.0)
#>  highr         0.8     2019-03-20 [1] CRAN (R 3.6.0)
#>  htmltools     0.3.6   2017-04-28 [1] CRAN (R 3.6.0)
#>  httr          1.4.0   2018-12-11 [1] CRAN (R 3.6.0)
#>  knitr         1.23    2019-05-18 [1] CRAN (R 3.6.0)
#>  labeling      0.3     2014-08-23 [1] CRAN (R 3.6.0)
#>  lazyeval      0.2.2   2019-03-15 [1] CRAN (R 3.6.0)
#>  magrittr      1.5     2014-11-22 [1] CRAN (R 3.6.0)
#>  memoise       1.1.0   2017-04-21 [1] CRAN (R 3.6.0)
#>  mime          0.7     2019-06-11 [1] CRAN (R 3.6.0)
#>  munsell       0.5.0   2018-06-12 [1] CRAN (R 3.6.0)
#>  pillar        1.4.1   2019-05-28 [1] CRAN (R 3.6.0)
#>  pkgbuild      1.0.3   2019-03-20 [1] CRAN (R 3.6.0)
#>  pkgconfig     2.0.2   2018-08-16 [1] CRAN (R 3.6.0)
#>  pkgload       1.0.2   2018-10-29 [1] CRAN (R 3.6.0)
#>  prettyunits   1.0.2   2015-07-13 [1] CRAN (R 3.6.0)
#>  processx      3.3.1   2019-05-08 [1] CRAN (R 3.6.0)
#>  ps            1.3.0   2018-12-21 [1] CRAN (R 3.6.0)
#>  purrr         0.3.2   2019-03-15 [1] CRAN (R 3.6.0)
#>  R6            2.4.0   2019-02-14 [1] CRAN (R 3.6.0)
#>  Rcpp          1.0.1   2019-03-17 [1] CRAN (R 3.6.0)
#>  remotes       2.0.4   2019-04-10 [1] CRAN (R 3.6.0)
#>  rlang         0.3.4   2019-04-07 [1] CRAN (R 3.6.0)
#>  rmarkdown     1.13    2019-05-22 [1] CRAN (R 3.6.0)
#>  rprojroot     1.3-2   2018-01-03 [1] CRAN (R 3.6.0)
#>  scales        1.0.0   2018-08-09 [1] CRAN (R 3.6.0)
#>  sessioninfo   1.1.1   2018-11-05 [1] CRAN (R 3.6.0)
#>  stringi       1.4.3   2019-03-12 [1] CRAN (R 3.6.0)
#>  stringr       1.4.0   2019-02-10 [1] CRAN (R 3.6.0)
#>  testthat      2.1.1   2019-04-23 [1] CRAN (R 3.6.0)
#>  tibble        2.1.3   2019-06-06 [1] CRAN (R 3.6.0)
#>  tidyselect    0.2.5   2018-10-11 [1] CRAN (R 3.6.0)
#>  usethis       1.5.0   2019-04-07 [1] CRAN (R 3.6.0)
#>  withr         2.1.2   2018-03-15 [1] CRAN (R 3.6.0)
#>  xfun          0.7     2019-05-14 [1] CRAN (R 3.6.0)
#>  xml2          1.2.0   2018-01-24 [1] CRAN (R 3.6.0)
#>  yaml          2.2.0   2018-07-25 [1] CRAN (R 3.6.0)
#> 
#> [1] /Library/Frameworks/R.framework/Versions/3.6/Resources/library
```

</details>

**Comment by michaelgmccarthy** [comment]
Ok thanks! So I probably didn't give a clear definition of everything i'm using and I can see a solution for my issue. In case anyone has similar issues i'll elaborate.

I’ve built a number of dashboards using the R option in Power BI. These graphs are in essence an in-built version of R in a dashboard with the R scripts running in the background.
Power BI seems to be storing this old version of ggplot2 somehow in the pbix even though my pc only has the latest version. The only way it appears that I can fix this is to rebuild the dashboards with the new version of ggplot2.
I’ve taken one graph using the old script (but in this case as it’s a new report it has the new version of ggplot2) and it works.
