### ISSUE TITLE
Make stroke and line width pt unit consistent with exact pt 

### ISSUE THREAD

**Issue by codetrainee** [tidyverse/ggplot2#3358]
Currently when assigning a lwd or stroke with pt unit, we have to do a calculation to get an exact point shown as below:

```
## .pt <- 72.27 / 25.4
## .stroke <- 96 / 25.4

## line width exact 1 pt 
line_width_1pt <- 1 / (72.27 / 25.4) / (72.27 / 96)

## stroke width exact 1 pt 
stroke_width_1pt <- 1 / (96 / 25.4) / (72.27 / 96) * 2

## These calculations are confirmed with Adobe illustrator.
```

This is just a small thing but I was wondering if we could unify them and make the `pt` consistent with the actual value?

**Comment by thomasp85** [comment]
We can't really... These conversions are happening at the graphic device level and may be device specific. All ggplot2 can do is play nice with grid
