### ISSUE TITLE
geom_ribbon expects an unused y-axis variable to be present

### ISSUE THREAD

**Issue by salmasian** [tidyverse/ggplot2#3364]
Take this example:

```
data <- data.frame(time = 1:10, value = 17 + runif(n = 10) * 4)
ribbon.data <- data.frame(time = data$time, ymin = data$value - 2, ymax = data$value + 2)

ggplot(data, aes(x = time, y = value)) +
  geom_line() +
  geom_ribbon(data = ribbon.data, aes(x = time, ymin = ymin, ymax = ymax), alpha = 0.2)
```

It fails with the following error message: `Error in FUN(X[[i]], ...) : object 'value' not found`

If you arbitrarily define a column named `value` in the `ribbon.data`, it will work without any error. But the value you give to that arbitrary column will affect the Y axis of the output. For example:

```
ggplot(data, aes(x = time, y = value)) +
  geom_line() +
  geom_ribbon(
    data = ribbon.data %>% mutate(value = 1),
    aes(x = time, ymin = ymin, ymax = ymax), alpha = 0.2
  )
```

That will cause the Y-axis to range from 0 to around 26, while this:

```
ggplot(data, aes(x = time, y = value)) +
  geom_line() +
  geom_ribbon(
    data = ribbon.data %>% mutate(value = 100),
    aes(x = time, ymin = ymin, ymax = ymax), alpha = 0.2
  )
```

will cause the Y-axis to range from 0 to 100.

PS: Note that [geom_reboon documentation](https://ggplot2.tidyverse.org/reference/geom_ribbon.html) never mentions the need for the data passed to it to have matching variables with what goes into the parent plot.

**Comment by clauswilke** [comment]
This happens because you're inheriting the aesthetics from the main `ggplot()` call. If you don't want to inherit aesthetics, you need to explicitly say so with `inherit.aes = FALSE`.

``` r
library(ggplot2)
#> Registered S3 methods overwritten by 'ggplot2':
#>   method         from 
#>   [.quosures     rlang
#>   c.quosures     rlang
#>   print.quosures rlang

data <- data.frame(time = 1:10, value = 17 + runif(n = 10) * 4)
ribbon.data <- data.frame(time = data$time, ymin = data$value - 2, ymax = data$value + 2)

# doesn't work
ggplot(data, aes(x = time, y = value)) +
  geom_line() +
  geom_ribbon(
    data = ribbon.data, aes(x = time, ymin = ymin, ymax = ymax), alpha = 0.2
  )
#> Error in FUN(X[[i]], ...): object 'value' not found

# works
ggplot(data, aes(x = time, y = value)) +
  geom_line() +
  geom_ribbon(
    data = ribbon.data, aes(x = time, ymin = ymin, ymax = ymax), alpha = 0.2,
    inherit.aes = FALSE
  )
```

![](https://i.imgur.com/KP69KWM.png)

<sup>Created on 2019-06-16 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
