### ISSUE TITLE
"/n" no longer creates new line in labs

### ISSUE THREAD

**Issue by katieleap** [tidyverse/ggplot2#3386]
Tweaking a plot that I last rendered on May 28th, I discovered that "/n" in the subtitle text no longer makes a new line as it did a month ago. Double checked that all my packages are up to date, reproducible example below.

``` r
library(ggplot2)
ggplot(iris) + geom_boxplot(aes(x=Species, y=Sepal.Width)) +
    labs(subtitle = "Can I have a subtitle /n with a newline?")
```

![](https://i.imgur.com/lKvTJBo.png)

<sup>Created on 2019-07-01 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by smouksassi** [comment]
Isn't it \n

Backslash

**Comment by katieleap** [comment]
Yes! I assumed there weren't any typos because it had worked before.
