### ISSUE TITLE
NULL as default for xlab() and ylab()

### ISSUE THREAD

**Issue by moredatapls** [tidyverse/ggplot2#3393]
When removing axis labels, intuitively, I would just call `xlab()` or `ylab()` without an argument. However, the `label` argument doesn't default to `NULL` (there is no default currently), and instead I have to pass `NULL` every time I want to remove the labels.

Could `NULL` be added as a default for both `*lab()` functions?

``` r
library(ggplot2)
data <- data.frame(x = c(1, 2), y = c(10, 20))
ggplot(data, aes(x, y)) + geom_col() + xlab()
#> Error in rlang::list2(..., title = title, subtitle = subtitle, caption = caption, : argument "label" is missing, with no default
```

**Comment by moredatapls** [comment]
I created PR #3395 if you think that this change is useful.

**Comment by yutannihilation** [comment]
While I feel your suggestion is smart, I'm a bit afraid this might make the semantics of `labs()` a bit confusing. For example, if this would remove axis labels,

``` r
ggplot(data, aes(x, y)) + geom_col() + xlab() + ylab()
```

one might think this would remove all labels,

``` r
ggplot(data, aes(x, y)) + geom_col() + labs()
```

but actually `labs()` does nothing. So, I'd rather stick with the status quo, where we need to specify `NULL` explicitly to remove labels.

**Comment by moredatapls** [comment]
Good point, forgot about `labs()`! Will close this then 👍
