### ISSUE TITLE
`viridis` type for discrete scales ?

### ISSUE THREAD

**Issue by Ahobert** [tidyverse/ggplot2#3428]
I noticed that [`scale_colour/fill_continuous`](https://ggplot2.tidyverse.org/reference/scale_colour_continuous.html) has a `type` option specifying wheter to use `gradient` or `viridis` palettes. in order to enable color blindness friendly visualisation. Is there any particular reason why the same option is not (yet) implemented in `scale_colour/fill_discrete` or [`scale_colour/fill_hue`](https://ggplot2.tidyverse.org/reference/scale_hue.html), respectively?

**Comment by karawoo** [comment]
I think the main reason is that we changed the default behavior for continuous color scales to use viridis, but also kept the ability to use the previous default (gradient). For discrete scales, viridis is less often a good choice unless the number of categories is very small. But you can still use it with discrete data using `scale_colour_viridis_d()`/`scale_fill_viridis_d()`.
