### ISSUE TITLE
ggplot2 legends making no sense.

### ISSUE THREAD

**Issue by abalter** [tidyverse/ggplot2#3433]
## Problem
ggplot is associating the legend entries with the wrong geom elements. The legend is not including both color and shape. Items that should be on one legend are showing on the other.

## Expected behavior:
* A red line from equation 5 + 1.3*x that has squares at the discrete points
* A green line from equation 25 - 0.7*x that has circles at the discrete points
* A black dotted hline at y-interecept 20
* A blue dashed vline at x-intercept 15
* Legend 1
  * titled "Envelopments"
  * red line with square shape with name Vicissitude
  * green line with circle shape with name Mysteriousness
* Legend 2
  * titled Disparities
  * black dotted line with name Discouraged
  * blue dashed line with name Alternative

Note: I've messed around quite a bit with various combinations of where I'm specifying colors relative to the aes and scale_*_(discrete|manual) with values, names, etc.

Nothing I've tried accomplishes my goal.

```r
library(tidyverse)
library(ggplot2)

x = c(0,5, 10, 15, 20)

df = data.frame(
  Deliberation = x,
  Vicissitude = 5 + 1.3*x,
  Mysteriousness = 25 - 0.7*x
)

df %>%
  ggplot() +
  geom_line(aes(x=Deliberation, y=Vicissitude, color='red')) +
  geom_point(aes(x=Deliberation, y=Vicissitude, color='red', shape='square')) +
  geom_line(aes(x=Deliberation, y=Mysteriousness, color='green')) +
  geom_point(aes(x=Deliberation, y=Mysteriousness, color='green', shape='circle')) +
  scale_color_discrete(name='Envelopments', labels=c('Vicissitude', 'Mysteriousness')) +
  geom_hline(aes(yintercept=20, color='black', linetype='Discouraged'), show.legend=T) +
  geom_vline(aes(xintercept=15, color='blue', linetype='Alternative'), show.legend=T) +
  scale_linetype_manual(name='Disparities', values=c('dotted', 'dashed'))
```

![Rplot](https://user-images.githubusercontent.com/5349876/61023555-44066080-a35f-11e9-8585-042e523aa3af.png)

**Comment by clauswilke** [comment]
Thanks for providing a detailed reprex. In looking over the code, I don't see anywhere where ggplot2 does anything unexpected. It looks to me like you're not sufficiently familiar with how aesthetic mappings and scales work, and therefore you are surprised when ggplot2 does exactly what you ask it to do.

I recommend that you read some introductory texts about ggplot2. For example, Kieran Healy's book (http://socviz.co/) is great. It discusses your specific problem in Chapter 3.5: http://socviz.co/makeplot.html#mapping-aesthetics-vs-setting-them

If you have further questions about ggplot2 usage, the R Studio forums would be a more appropriate venue.
