### ISSUE TITLE
Create a rational api for legends.

### ISSUE THREAD

**Issue by abalter** [tidyverse/ggplot2#3434]
# Feature Request

## Issue
Right now, legends are created in an add-hoc way with mysterious non-intuitive sounding layers like `scale_color_manual`. It is very unclear how to create a legend that refers to a specific element.

For instance, if you have 

```
geom_hline(aes(yintercept=10, color='red', linetype='LABEL'), show.legend=T)
```
You don't automatically get a legend. You can do something like

```
scale_linetype_discrete(name='TITLE', values=c('dashed'))
```

and get a legend with title TITLE and a dashed line. But you can't change the color of the line in the legend this way.

## Proposal
I propose a very declarative API as follows:

1. You create legends with a geom `geom_legend`.
2. It has intuitive parameters:
```
geom_legend(title='TITLE', elements=c(el1, el2, el3), <typesetting>, <outlines>, <fills>, ...)
```
3. Other geom elements have a "name" attribute referred to in the legend "elements" attribute.
4. If a "name" is not provided, then the name of the y component of the aes is used.

Using this API, the code below would produce

* A red line from equation 5 + 1.3*x that has squares at the discrete points
* A green line from equation 25 - 0.7*x that has circles at the discrete points
* A black dotted hline at y-interecept 20
* A blue dashed vline at x-intercept 15
* Legend 1
  * titled "Envelopments"
  * red line with square shape with name Vicissitude
  * green line with circle shape with name Mysteriousness
* Legend 2
  * titled Disparities
  * black dotted line with name Discouraged
  * blue dashed line with name Alternative

```r
library(tidyverse)
library(ggplot2)

x = c(0,5, 10, 15, 20)

df = data.frame(
  Deliberation = x,
  Vicissitude = 5 + 1.3*x,
  Mysteriousness = 25 - 0.7*x
)

df %>%
  ggplot() +
  ### Data Lines
  geom_line(aes(x=Deliberation, y=Vicissitude, color='red'), name=) +
  geom_point(aes(x=Deliberation, y=Vicissitude, color='red', shape='square')) +
  geom_line(aes(x=Deliberation, y=Mysteriousness, color='green')) +
  geom_point(aes(x=Deliberation, y=Mysteriousness, color='green', shape='circle')) +

  ### Reference guides
  geom_hline(aes(yintercept=20, color='black', linetype='dotted'), show.legend=T, name='Discouraged') +
  geom_vline(aes(xintercept=15, color='blue', linetype='dashed'), show.legend=T, name="Alternative") +

  ### Legends
  geom_legend(title="Envelopements", elements=c('Vicissitude', 'Mysteriousness')) +
  geom_legend(title="Disparities", elements=c("Discouraged", "Alternative"))
```

This would be super easy to remember and control. Someone reading the code should have no trouble understanding what should be graphed. Changing linetypes, colors, or shapes need only be done in one place that makes total sense.

**Comment by clauswilke** [comment]
See my comments on #3433.
