### ISSUE TITLE
git tag CRAN releases

### ISSUE THREAD

**Issue by cpsievert** [tidyverse/ggplot2#3438]
It appears `git tag` hasn't been used to tag releases since v2.2.1. Having tags would make it easier to track down changes in behavior via `git bisect`

**Comment by yutannihilation** [comment]
> It appears `git tag` hasn't been used to tag releases since v2.2.1

There are tags. Do you mean there are some differences between tagging by `git tag` and tagging by GitHub release?

![image](https://user-images.githubusercontent.com/1978793/61164480-7fb44c80-a550-11e9-8539-1a982c2034bb.png)

**Comment by cpsievert** [comment]
Ah, turns out I just needed to run `git fetch --tag`, sorry! 🤦‍♂
