### ISSUE TITLE
ylim impacts calculation of geom_boxplot stats

### ISSUE THREAD

**Issue by PatrickChodowski** [tidyverse/ggplot2#3447]
Hi, is ylim supposed to work with geom_boxplot?

I noticed that ylim removes observations before the stats of boxplot are calculated (causing heart attacks during new segmentation analysis). If I missed something in documentation about not using ylim,xlim then just please ignore.

example:
```r
library(ggplot2)
df = data.frame(y = c(0:20, 30:35), x = 1)
quantile(df$y)
# median should be 13

ggplot(data=df) + geom_boxplot(aes(x=x,y=y)) #median = 13
ggplot(data=df) + geom_boxplot(aes(x=x,y=y)) + ylim(0,20) #median = 10
```

**Comment by smouksassi** [comment]
ylim is indeed to filter for data between 0 and 20 if you want a zoom effect we have + coord_cartesian(yim...)

**Comment by PatrickChodowski** [comment]
I completely missed that, thank you!
