### ISSUE TITLE
filled arrowhead not showing in legend

### ISSUE THREAD

**Issue by RABxx** [tidyverse/ggplot2#3455]
As discussed here: https://stackoverflow.com/questions/57193353/show-filled-arrow-in-legend-ggplot

I am trying to plot a line segment with an arrow on the end, and make it appear in the legend. I can do this with the following code:

```
# sample data
dat <- data.frame(
  x = as.factor(1:10),
  y = c(20,30,13,37,12,50,31,2,40,30),
  z = rep('a', 10)
)

# basic plot
ggplot(dat) +
  geom_segment(
    aes(x = x, xend = x, y = 0, yend = y+15, linetype = z), 
    arrow = arrow(length = unit(0.25, 'cm'), type = 'closed'),
    size = 0.7
  ) 
```

but the arrowhead is empty, not filled. I tried overriding the `aes` in a `guide_legend` argument, but nothing changed. Is this a bug? Or am I missing something for how to make the arrowhead filled?

output:

![image](https://user-images.githubusercontent.com/48337093/61849944-3ec81a80-aef6-11e9-9ae0-48932c0a0b75.png)

**Comment by clauswilke** [comment]
It's a bug. The legend drawing code doesn't set `fill`:
https://github.com/tidyverse/ggplot2/blob/141c77537ea4f54a7949ed8f23fd02c50172960e/R/legend-draw.r#L138-L143
Unlike the actual line drawing code:
https://github.com/tidyverse/ggplot2/blob/141c77537ea4f54a7949ed8f23fd02c50172960e/R/geom-segment.r#L119-L126

As a workaround, you can copy the legend-drawing code, add a line that sets the `fill` value, and then use that as your custom legend glyph as is possible with the latest ggplot2 release.

**Comment by RABxx** [comment]
thanks for the response. I'm not quite sure how to do that last step though, can you give example code?

**Comment by clauswilke** [comment]
I provided an example on SO.
