### ISSUE TITLE
Option to keep original order

### ISSUE THREAD

**Issue by xmarti6** [tidyverse/ggplot2#3457]
Hi, I know this is an old topic, but just was wondering if it would be feasiable to add a ggplot option to just keep input order (e.g. ko=T). ggplot is widely used within other packages and sometimes is kind of cumbersome to be playing around with factors and levels to keep input data. Would that option have wide colateral effects?

Many thanks

**Comment by teunbrand** [comment]
There are plenty of options to preserve the original order, such as setting factor levels and setting limits.

``` r
library(ggplot2)

df <- data.frame(x = c("B", "A", "C"), y = 1:3)

ggplot(df, aes(forcats::fct_inorder(x), y)) +
  geom_col()
```

![](https://i.imgur.com/kOb4g4q.png)

``` r

f <- function(x) factor(x, as.character(unique(x)))

ggplot(df, aes(f(x), y)) +
  geom_col()
```

![](https://i.imgur.com/AbnkDzc.png)

``` r

ggplot(df, aes(x, y)) +
  geom_col() +
  scale_x_discrete(limits = unique(df$x))
```

![](https://i.imgur.com/sXBSQS5.png)

<sup>Created on 2024-09-12 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

If there a deeper need to preserve orders, then this should be solved in the {scales} package, where range training should then preserve order:

``` r
x <- scales::DiscreteRange$new()
x$train(c("B", "A", "C"))
x$range
#> [1] "A" "B" "C"
```

<sup>Created on 2024-09-12 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

If {scales} decides to allow this option, we can re-open the issue.
