### ISSUE TITLE
draw_key_dotplot : more detailed documentation please (ggplot2 v3.2.0)

### ISSUE THREAD

**Issue by cordphelps** [tidyverse/ggplot2#3460]
---

geom_jitter() with small data points (size=1) results in a legend glyph of the same size and shape. 

I'm trying to use key_glyph = draw_key_dotplot(size=5) to increase the glyph size, but ggplot() complains:

Error in match(x, table, nomatch = 0L) : 
  argument "data" is missing, with no default

```r

points <- data.frame( bc = c (1:3), bpc= c(1:3), cluster=c("red", "green", "blue"))

# works great
ggplot() +
  geom_jitter( data=points, aes(x=bc, y=bpc, fill=cluster), shape=21, size=1)

# fails
ggplot() +
  geom_jitter( data=points, aes(x=bc, y=bpc, fill=cluster), shape=21, size=1, 
               key_glyph=draw_key_dotplot(size=5))

```
The draw_key_* documentation in https://cran.r-project.org/web/packages/ggplot2/ggplot2.pdf is unhelpful regarding parameters "data" and "params". Please provide some examples as to how these are supposed to be used.

Thanks, keep up the good work.

**Comment by yutannihilation** [comment]
They are not intended to be called directly by you, but inside ggplot2. You just can pass the function as it is (or define one by yourself like [this](https://stackoverflow.com/a/57205560/5397672)):

``` r
ggplot() +
  geom_jitter(data = points, aes(x = bc, y = bpc, fill = cluster), shape = 21, size = 1, 
              key_glyph = draw_key_dotplot)
```

I agree this might be a bit confusing. We may need to consider raising an error when `draw_key_*()` is called on the global env...?

And, here's the result what you want; you can tweak the legends via `guides()`.

``` r
library(ggplot2)

points <- data.frame(bc = c (1:3), bpc = c(1:3), cluster = c("red", "green", "blue"))

ggplot() +
  geom_jitter(data = points, aes(x = bc, y = bpc, fill = cluster), shape = 21, size = 1) +
  guides(fill = guide_legend(override.aes = list(size = 5)))
```

![](https://i.imgur.com/LZLkYj8.png)

<sup>Created on 2019-07-28 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by cordphelps** [comment]
thank you @yutannihilation
