### ISSUE TITLE
How can I creat a graph and add a strip like this by using ggplot2?

### ISSUE THREAD

**Issue by qikongwanli** [tidyverse/ggplot2#3466]
---

How can I add a color strip to a graph according to the length of xlim by using ggplot2? 
please help me.   Great thinks!
![Rplot](https://user-images.githubusercontent.com/50703704/62199256-bfcf5800-b3b5-11e9-9c14-843380adbea5.jpg)

```r
# insert reprex here
```

**Comment by smouksassi** [comment]
these type of questions are more suitable for the Rstudio forums.
https://github.com/clauswilke/dataviz/blob/fe4da7abe73699a968d36ed3b5ac993868cf22af/redundant_coding.Rmd#L546
https://serialmentor.com/dataviz/redundant_coding_files/figure-html/temp-ridgeline-colorbar-1.png

**Comment by yutannihilation** [comment]
Yes, this sort of question is a better fit for https://community.rstudio.com. Please ask there.
