### ISSUE TITLE
Jitterdodge and text= aesthetic

### ISSUE THREAD

**Issue by bobidou23** [tidyverse/ggplot2#3476]
The ggplotly package uses the text= aesthetic to control the label that shows up when hovering. Normally this works fine! But I've stumbled upon one case it doesn't: combining with position_jitterdodge, at which point the dodge stops working and it becomes a single-column jitter. This is an issue at the level of ggplot, before transforming it into plotly style. (Changing the position of the aes(text=) doesn't make a difference.)

```
ggplot(district_density,aes(x=cluster, y=dem_margin, colour=region, text=paste("district: ", cd_code))) +
  geom_point(position=position_jitterdodge(jitter.width = 0.5), alpha=0.5)
```

**Comment by clauswilke** [comment]
Please provide a reproducible example, and please use the [reprex package.](https://reprex.tidyverse.org/articles/articles/magic-reprex.html)

**Comment by yutannihilation** [comment]
You need to specify `group`, otherwise the grouping would be the combinations of all discrete variables; `cluster`, `region` and `paste("district: ", cd_code)`.

For future reference, please ask this kind of questions on RStudio Community or SO first. I guess you would have got nicer answer there more quickly.

``` r
library(ggplot2)
district_density <- read.csv("https://raw.githubusercontent.com/plotly/datasets/master/district_density.csv",
                             stringsAsFactors = FALSE)
district_density$cluster <- factor(district_density$cluster, levels=c("Pure urban", "Urban-suburban mix", "Dense suburban", "Sparse suburban", "Rural-suburban mix", "Pure rural"))
district_density$region <- factor(district_density$region, levels=c("West", "South", "Midwest", "Northeast"))
ggplot(district_density,aes(x=cluster, y=dem_margin, colour=region, text=paste("district: ", cd_code), group = paste(cluster, region))) +
  geom_point(position=position_jitterdodge(), alpha=0.5) +
  geom_hline(yintercept=0) +
  theme(axis.text.x = element_text(angle = -30, hjust = 0.1),
        plot.title = element_text(hjust = 0.5)) +
  labs(title = "Democratic performance in the 2018 House elections, by region and density",
       x = "Density Index from CityLab",
       y = "Democratic Margin of Victory/Defeat")
```

![](https://i.imgur.com/F5cMZfI.png)

<sup>Created on 2019-08-27 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by yutannihilation** [comment]
Minimal reprex:

``` r
library(ggplot2)

set.seed(2)
d <- data.frame(
  x = 1,
  y = runif(90),
  g1 = rep(c("a", "b", "c"), each = 30),
  g2 = rep(c("a", "b", "c"), 30)
)

ggplot(d, aes(x, y, colour = g1)) +
  geom_point(aes(x, y), position = position_jitterdodge(seed = 0))
```

![](https://i.imgur.com/9RoerCQ.png)

``` r

ggplot(d, aes(x, y, colour = g1, text = g2)) +
  geom_point(aes(x, y), position = position_jitterdodge(seed = 0))
```

![](https://i.imgur.com/MX3wqom.png)

``` r

ggplot(d, aes(x, y, colour = g1, text = g2, group = paste(x, g1))) +
  geom_point(aes(x, y), position = position_jitterdodge(seed = 0))
```

![](https://i.imgur.com/IqUTxFW.png)

<sup>Created on 2019-08-27 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
