### ISSUE TITLE
Clarify documentation in mpg: very minor

### ISSUE THREAD

**Issue by MaraAlexeev** [tidyverse/ggplot2#3477]
I was working through exercises using mpg in ggplot2 Elegant Graphics for Data Analysis, and I got stuck on trying to figure out what a drive train was. 

I finally realized the variable drv means drive train. Could the documentation be updated to identify drv as meaning drive train? 

Currently: 
drv f = front-wheel drive, r = rear wheel drive, 4 = 4wd

Suggested: 
drv the type of drive train, where f = front-wheel drive, r = rear wheel drive, 4 = 4wd

**Comment by yutannihilation** [comment]
Thanks, sounds good to me. Do you want to try to create a PR? You need to modify `R/data.R` and regenerate the doc by `devtools::document()`.

https://github.com/tidyverse/ggplot2/blob/b8420241309c8eea00d7086002c01cdf38a50eac/R/data.R#L103

**Comment by MaraAlexeev** [comment]
I will! Thanks.
