### ISSUE TITLE
Issue with documentation of stat_summary(_bin) and question about default x-axis position

### ISSUE THREAD

**Issue by japhir** [tidyverse/ggplot2#3480]
I recently [tweeted](https://twitter.com/Japhir/status/1158758152113983488) about an issue with `stat_summary` documentation, and here's the issue for it. 

I intended to use `stat_summary_bin()` with custom breaks with gaps in between on the x-axis. I've tried to illustrate below. From the documentation it was not clear whether this was possible/desired, mostly because I didn't understand what kind of function to pass to `binwidth` from the docs. 

Below I'll explain my thinking so that it hopefully highlights the issue with the docs:

I was wondering if I should I try to write a function which is conditional on x-axis values? That sounds like it should be easier to specify with `breaks`. Also, it looks like the fun.data should operate only on the y-value, and doesn't get passed the x-value. I also tried to define a new group variable using `cut` or `findInterval` and set binwidth, but this still draws lines (most right one) that span the outside of the x-axis values. 

So then, when looking at `breaks`, the docs say that they overrules `center` and `boundary`, but neither of those are defined in these docs and don't point to references elsewhere.

In the end I created a new tibble with the summarized values for plotting.

```
data:            ...              . ... ...        ...               .... .......... . ...

desired summary: |*|              |___*___|        |*|               |_________*_________|

actual summary:  |---*---| |---------*--------| |-----*-----| |-----------*--------------|
```

I created below reprex.
- black dashed lines represent the desired breaks
- red dotted l ines highlight the min/max of each of the intervals
- black pointranges show the default method of doing this
- black vertical lines highlight the desired x-axis value to plot this pointrange at
- red pointranges highlight my grouping attempt, which still draws outside the actual x-axis limits.

``` r
library(ggplot2)
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
library(tibble)

desired_breaks <- c(0, 40, 90)

dat <- tibble(x = c(1:3, 5:10, 15:23, 25:27, 50:86),
              y = rnorm(length(x), mean = seq(1, 10, length.out = length(x)), sd = 6),
              grp = findInterval(x, vec = desired_breaks))

ggplot(dat, aes(x = x, y = y)) +
  geom_point(alpha = .3) +
  stat_summary_bin(geom = "pointrange", fun.data = "mean_cl_normal",
                   breaks = desired_breaks) +
  stat_summary_bin(aes(group = grp), geom = "pointrange",
                   fun.data = "mean_cl_normal",
                   binwidth = 6,
                   colour = "red") +
  geom_vline(xintercept = desired_breaks, linetype = 2) +
  geom_vline(xintercept = c(1, 27, 50, 86),
             colour = "red",
             linetype = 3) +
  geom_vline(xintercept = c((27 - 1) / 2 + 1, (86 - 50) / 2 + 50))
```

![](https://i.imgur.com/yRUYXxi.png)

<sup>Created on 2019-08-11 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

This made me think that the default option of plotting these summary values between the specified breaks is actually undesired, since it should probably be drawn in the middle (or median) of the range of x-values. I.e. if you specify breaks like `c(0, 50, 100)` but your data only goes up to 60, your last summary point will be drawn all the way on the right of the data.

Thanks and kind regards

may be related to #3297

**Comment by yutannihilation** [comment]
> So then, when looking at `breaks`, the docs say that they overrules `center` and `boundary`, but neither of those are defined in these docs and don't point to references elsewhere.

This description is originally for `stat_bin()`, which has `center` and `boundary` arguments. This might be a bit confusing, but it's more difficult to maintain if we have separate description for `stat_summary_bin()`'s `breaks`. Hope this confusion will be solved by adding `center` and `boundary` to `stat_summary_bin()` eventually....

**Comment by yutannihilation** [comment]
Sorry, I can't understand what you are suggesting to improve the documentation... If you want to learn how binning works, you might be able to get better answers on [RStudio Community](https://community.rstudio.com). 

To visualize the actual bins, you can use `geom_errorbarh()` and here's one:

<details>

``` r
library(ggplot2)
library(dplyr, warn.conflicts = FALSE)
#> Warning: package 'dplyr' was built under R version 3.6.1
library(tibble)

set.seed(1)
desired_breaks <- c(0, 40, 90)

dat <- tibble(x = c(1:3, 5:10, 15:23, 25:27, 50:86),
              y = rnorm(length(x), mean = seq(1, 10, length.out = length(x)), sd = 6),
              grp = findInterval(x, vec = desired_breaks))

ggplot(dat, aes(x = x, y = y)) +
  geom_point() +
  stat_summary_bin(geom = "pointrange", fun.data = "mean_cl_normal",
                   breaks = desired_breaks) +
  stat_summary_bin(aes(group = grp), geom = "pointrange",
                   fun.data = "mean_cl_normal",
                   binwidth = 6,
                   colour = "red") +
  geom_vline(xintercept = desired_breaks, linetype = 2) +
  geom_vline(xintercept = c(1, 27, 50, 86),
             colour = "red",
             linetype = 3) +
  geom_vline(xintercept = c((27 - 1) / 2 + 1, (86 - 50) / 2 + 50)) +
  stat_summary_bin(aes(xmin = stat(x - width / 2), xmax = stat(x + width / 2), y = 8, group = grp),
                   geom = "errorbarh",
                   fun.data = mean_cl_normal,
                   binwidth = 6,
                   colour = alpha("purple", 0.6),
                   height = 50,
                   size = 2)
```

</details>

![](https://i.imgur.com/Zr4Mc09.png)
