### ISSUE TITLE
ggplot color=some_factor "need at least two non-NA values to interpolate"

### ISSUE THREAD

**Issue by N1h1l1sT** [tidyverse/ggplot2#3481]
I get the error "need at least two non-NA values to interpolate" whenever I put "color=SomeFactorVar" on a ggplot.
Note that there are no NA values. Neither in the X, Y axes, nor in the Colour variable

```r
#Creating a Dataset representing a simple "OR" gate
XORGate <- tibble(
  X1 = c(0,0,1,1),
  X2 = c(0,1,0,1),
  Label = factor(c(0,1,1,0), levels = c(0, 1), labels = c("False", "True"))
)
ggplot(XORGate, aes(x=X1, y=X2, color=Label)) + geom_point()
```

> Error in interpolate(x, colors[, 1L]) : 
>   need at least two non-NA values to interpolate

ggplot2 3.2.1
R Version: 3.6.0 64bit
Windows 10 1903 18362.267
RStudio 1.1.463

**Comment by batpigandme** [comment]
I'm not able to reproduce this. Can you run a reprex please?

``` r
suppressPackageStartupMessages(library(tidyverse))
XORGate <- tibble(
  X1 = c(0,0,1,1),
  X2 = c(0,1,0,1),
  Label = factor(c(0,1,1,0), levels = c(0, 1), labels = c("False", "True"))
)
ggplot(XORGate, aes(x=X1, y=X2, color=Label)) + geom_point()
```

![](https://i.imgur.com/iS37GPQ.png)

<sup>Created on 2019-08-12 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by N1h1l1sT** [comment]
Thank you batpigandme.
If only I had began with a reprex, I would have realised that I always encounter this error because I load the "ggCorpIdent" in a file that gets sourced on startup. It's ggCorpIdent which causes it, it seems, it's not a ggplot2 bug.
I'll just stop using ggCorpIdent.

I apologise for the post. I'll close this thread.

``` r
library(ggCorpIdent)
#> Loading required package: extrafont
#> Registering fonts with R
#> Loading required package: ggplot2
#> Warning: package 'ggplot2' was built under R version 3.6.1
#> 
#> Attaching package: 'ggCorpIdent'
#> The following objects are masked from 'package:ggplot2':
#> 
#>     ggplot, scale_colour_discrete, scale_fill_discrete
library(tibble)
library(ggplot2)

#Creating a Dataset representing a simple "OR" gate
XORGate <- tibble(
  X1 = c(0,0,1,1),
  X2 = c(0,1,0,1),
  Label = factor(c(0,1,1,0), levels = c(0, 1), labels = c("False", "True"))
)
ggplot(XORGate, aes(x=X1, y=X2, color=Label)) + geom_point()
#> Error in interpolate(x, colors[, 1L]): need at least two non-NA values to interpolate
```

![](https://i.imgur.com/STYWL5l.png)

<sup>Created on 2019-08-12 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by batpigandme** [comment]
No problem!
