### ISSUE TITLE
Feature request: implement sinaplots

### ISSUE THREAD

**Issue by rfarouni** [tidyverse/ggplot2#3484]
Hi,

Many in the computational biology community are starting to appreciate the advantages of sinaplot over boxplots and violin plots to visualize distributions of empirical data. Are there any plans to implement this functionality in ggplot2? There is already an R package. See [here](https://cran.r-project.org/web/packages/sinaplot/vignettes/SinaPlot.html) for more details 

![image](https://user-images.githubusercontent.com/9895004/62947938-70bff480-bdb1-11e9-81d8-f0e666bfd6d8.png)

Thanks!

**Comment by clauswilke** [comment]
It's available in ggforce: 
https://ggforce.data-imaginist.com/reference/geom_sina.html
