### ISSUE TITLE
geom_boxplot using both color and (group or discrete x) aeses 

### ISSUE THREAD

**Issue by CorradoLanera** [tidyverse/ggplot2#3486]
I have described the problem on StackOverflow [here](https://stackoverflow.com/questions/57485779/is-it-possible-to-ggplot-grouped-partial-boxplots-w-o-facets-w-a-single-geom-b) too, where [Calum You](https://stackoverflow.com/users/7028459/calum-you) purposes a workaround for that.

The main problem is related to create a "running grid" of boxplots, without using facets, to track the distributions of some measure (y) in a time-dependent graph (x) on two (or more) characteristics (color) considering a fixed amount of time-points (or all the time points within a given window of time) in each boxplot (cut).

While filtering for a single characteristic, it works well (and maintain the right color!), overall it provides strange results.

There are some issues here between group and color interaction, or the workaround represents the correct approach?

``` r
library(tidyverse)

bar <- tibble(
    time = 1:100,
    group = sample(c("a", "b"), 100, replace = TRUE) %>% as.factor()
) %>% 
    group_by(group) %>% 
    mutate(
        value = rnorm(n()) + 10 * as.integer(group),
        cut = 12.5 * ((time - 1)  %/% 25), # modified this to prevent an extra boxplot
        group_cut = str_c(group, cut)
    ) %>%
    ungroup()


# my natural way of thinking the solution
bar %>%
    ggplot(aes(x = time, y = value, color = group)) + 
    geom_point() +
    geom_smooth(se = FALSE) + 
    geom_boxplot(aes(x = cut))
#> `geom_smooth()` using method = 'loess' and formula 'y ~ x'
```

![](https://i.imgur.com/UhGUOz0.png)

``` r


# using position = "identity"
bar %>%
    ggplot(aes(x = time, y = value, color = group)) + 
    geom_point() +
    geom_smooth(se = FALSE) + 
    geom_boxplot(aes(x = cut), position = "identity")
#> `geom_smooth()` using method = 'loess' and formula 'y ~ x'
```

![](https://i.imgur.com/FBerGPD.png)

``` r


# using group instead of x
bar %>%
    ggplot(aes(x = time, y = value, color = group)) + 
    geom_point() +
    geom_smooth(se = FALSE) + 
    geom_boxplot(aes(group = cut))
#> `geom_smooth()` using method = 'loess' and formula 'y ~ x'
```

![](https://i.imgur.com/mN7qoPG.png)

``` r


# my solution
bar %>%   
ggplot(aes(x = time, y = value, color = group)) + 
    geom_point() +
    geom_smooth(se = FALSE) +
    geom_boxplot(data = filter(bar, group == "a"), aes(group = cut)) +
    geom_boxplot(data = filter(bar, group == "b"), aes(group = cut))
#> `geom_smooth()` using method = 'loess' and formula 'y ~ x'
```

![](https://i.imgur.com/vKfN13x.png)

``` r


# workaround by https://stackoverflow.com/users/7028459/calum-you

bar %>%
    ggplot(aes(x = time, y  = value, colour = group)) +
    geom_point() +
    geom_smooth(se = FALSE) +
    geom_boxplot(aes(group = group_cut), position = "identity")
#> `geom_smooth()` using method = 'loess' and formula 'y ~ x'
```

![](https://i.imgur.com/BUHjsO5.png)

<sup>Created on 2019-08-15 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by yutannihilation** [comment]
> the workaround represents the correct approach?

Yes. It's not a "workaround", but how ggplot2's grouping works.

When you don't specify `group` aesthetic explicitly, ggplot2 guesses the grouping structure from other variables (this time it was `colour`). But, when you specify `group` variable, you need to specify (or calculate) `group` that splits data into actual groups you want; it's you who is responsible for concatenating the two variables.

This doc might help: https://ggplot2.tidyverse.org/reference/aes_group_order.html

Here's a simpler reprex.

``` r
library(tibble)
library(ggplot2)

set.seed(10)
d <- tibble(
  group_x = rep(1:2, each = 10),
  group_y = rep(1:2, times = 10),
  y = group_y + runif(20)
)

ggplot(d, aes(group_x, y, color = factor(group_y))) + 
  geom_boxplot(aes(group = group_x)) +
  geom_point()
```

![](https://i.imgur.com/CKLyJJ2.png)

``` r

ggplot(d, aes(group_x, y, color = factor(group_y))) + 
  geom_boxplot(aes(group = paste(group_x, group_y))) +
  geom_point()
```

![](https://i.imgur.com/UFqHUAN.png)

<sup>Created on 2019-08-17 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

(As a side note, it might be a bit confusing that `StatBoxplot` (and other Stats than `StatIdentity`) silently ignores non-unique variables (`ggplot2:::uniquecols()`). Maybe we can show some warning...?)
