### ISSUE TITLE
grouping in geom_boxplot broken after upgrading from 3.5.2 to 3.6.1

### ISSUE THREAD

**Issue by ovvldc** [tidyverse/ggplot2#3496]
Following the advice in https://ggplot2.tidyverse.org/reference/geom_boxplot.html, I made a box plot with manually created statistics, using:

> geom_boxplot( data = stats, aes(x = x, group = set, ymin = Minimum, lower = Lower_quartile, middle = Median, upper = Upper_quartile, ymax = Maximum, colour = set, fill = set), width = 0.5, stat = "identity", show.legend = FALSE ) +

This worked wonderfully until today, after I upgraded from R 3.5.2 to 3.6.1 and reinstalled and updated my packages. Now this happens:

> print(graph)
Error: Can't draw more than one boxplot per group. Did you forget aes(group = ...)?

Clearly, I did not forget, and it was working fine yesterday. The input data has also not changed.

**Comment by ovvldc** [comment]
I can make both data and full script available, but this is an ongoing research project with personally identifiable data, so I cannot just post it here.

**Comment by ovvldc** [comment]
here is the input data for the box plot at least: [stats.txt](https://github.com/tidyverse/ggplot2/files/3526718/stats.txt)

**Comment by ptoche** [comment]
you should make a fully reproducible example with a dataset such as ``cars``, and even better use ``reprex``.

**Comment by clauswilke** [comment]
This is listed as a breaking change in the [3.2.0 release notes](https://cran.r-project.org/web/packages/ggplot2/news/news.html) (issue #3316). 

While the plot may have worked for you, it was using code whose behavior was undefined. To fix your plot, you'll have to define a `group` aesthetic that has a unique value for each boxplot that should be drawn.

**Comment by ovvldc** [comment]
Problem is that the error message is very unclear and misleading, as I clearly did set a group = in the code, and the release notes also do not specify what stopped working or how the input is supposed to be given now.

**Comment by clauswilke** [comment]
The error message states exactly what the problem is: "Can't draw more than one boxplot per group." You will have to assign a grouping variable that has a unique value for each boxplot you want to see drawn. If you're not sure what that means or how to achieve this, I suggest you ask over on the RStudio forums or on Stackoverflow.
