### ISSUE TITLE
Feature Request - Wouldn't it be cool if ggplot2 recognized `dplyr::group_by()`?

### ISSUE THREAD

**Issue by jhuntergit** [tidyverse/ggplot2#3497]
I've got a feature request to give ggplot2 the ability to recognize `dplyr::group_by()`.

```r
    library(tidyverse)
    library(lubridate)
    library(stringr)
    df <- 
      tibble(Date = as.Date(0:364, origin = "2017-07-01"), Value = rnorm(365)) %>% 
      mutate(Year = str_sub(Date, 1, 4), 
             MoFloor = floor_date(Date, unit = "month")) %>% 
      group_by(Year, MoFloor) %>% 
      mutate(MoAvgValue = mean(Value)) %>% 
      ungroup() %>% 
      group_by(Year) %>% 
      mutate(MinMoFloor = min(MoFloor),
             MaxMoFloor = max(MoFloor),
             YearAvgValue = mean(MoAvgValue))
```    

Let's first plot the data frame above.
   
```r 
    ggplot(df, aes(MoFloor, MoAvgValue, group = Year)) + 
      facet_grid(~Year, scale = "free_x", space = "free_x") + 
      geom_point()
```

[![plot1][1]][1]

In my call to the `facet_grid()` function I added the arguments `scale = "free_x"` and `space = "free_x"` to get rid of empty white space on the plots.

When I go ahead and add `geom_segment()`s based on `group_by()`d data, the `scale = "free_x"` and `space = "free_x"` arguments are negated. The empty white space reappears!

```r
    ggplot(df, aes(MoFloor, MoAvgValue, group = Year)) + 
      facet_grid(~Year, scale = "free_x", space = "free_x") + 
      geom_point() + 
      geom_segment(data = df, 
                   aes(x = min(MinMoFloor), 
                       y = YearAvgValue, 
                       xend = max(MaxMoFloor), 
                       yend = YearAvgValue))
```

[![plot2][2]][2]

My `df` data frame is grouped by `Year`. The `geom_segment()` function does not recognize this when I enter (for example) the `x = min(MinMoFloor)` argument. `geom_segment()` is pulling the `min(MinMoFloor)` from the global column, instead of the grouped column. 

I know I could substitute a modified `geom_hline()` function instead of `geom_segment()` for a working solution, but my lines are sometimes diagonal. And sometimes I'll have 50+ of these facet panels in my visualization, so defining the values manually is not practical either.

Thanks for considering this feature.

  [1]: https://i.stack.imgur.com/23YZ7.png
  [2]: https://i.stack.imgur.com/gETPE.png

**Comment by yutannihilation** [comment]
I don't think ggplot2 can be `group_by()`-aware, You might feel it's convenient if it behaves differently, but someone might feel it's confusing. I'm sure it would break many existing codes (e.g. https://github.com/tidyverse/ggplot2/issues/2378)

That said, I feel there's some need for a `group`-aware Stat in ggplot2. I see this kind of requests and questions are posted periodically.
