### ISSUE TITLE
Confusing behavior when mapping some variables to aes(size) in geom_point and geom_path

### ISSUE THREAD

**Issue by steenharsted** [tidyverse/ggplot2#3500]
I am not sure if this is WAI, but the behavior of the size argument for geom_point and geom_path is quite different if is placed inside or outside of the `aes()` function, and if the variable mapped to size only contains a single unique value.

This behavior makes it difficult to control the size of plots and lines via functions that map variables to the `geom_point(aes(size = ))` and `geom_path(aes(size = )) `

data for reprex:
```
library(tidyverse)

data <- tibble(
  x = c(1, 1, 4, 4, 6, 6, 8, 8),
  y = c(1, 4, 4, 1, 1, 4, 4, 1),
  type = c( "normal",  "normal",  "normal",  "normal",  "bigger", "bigger", "bigger", "bigger" ))
```

Consider the following function, that takes a base point size and a base line size. Both sizes can be scaled by the arguments scalar_point_size and scalar_line_size. 
If the scalars  = 1, the variable mapped inside `aes()` only has one unique value (that value will be equal to the base value).

```r
plot_with_size <-
  function(.data,
           base_point_size,
           scalar_point_size,
           base_line_size,
           scalar_line_size) {
    .data %>%
      mutate(
        point_size = case_when(
          type == "normal" ~ base_point_size,
          type == "bigger" ~ base_point_size * scalar_point_size
        ),
        
        line_size = case_when(
          type == "normal" ~ base_line_size,
          type == "bigger" ~ base_line_size * scalar_line_size
        )
      ) %>%
      ggplot(aes(x = x, y = y)) +
      geom_point(aes(size = point_size)) +
      geom_path(aes(size = line_size), color = "red", alpha = 0.5) +
      ggtitle(
        paste(
          "base_point_size =",
          base_point_size,
          "   scalar_point_size =",
          scalar_point_size,
          "   base_line_size =",
          base_line_size,
          "   scalar_line_size =",
          scalar_line_size
        )
      ) +
      theme(plot.title = element_text(size = 8, face = "bold"))
  }
```

It works as intended when the variables mapped to `aes(size = )` have more than one unique value:
```
data %>%
  plot_with_size(
    base_point_size = 1,
    scalar_point_size = 2,
    base_line_size = 1,
    scalar_line_size = 2
  )
```
![image](https://user-images.githubusercontent.com/40394828/63626042-d9a13b00-c601-11e9-9291-5c7ce124f32f.png)

Changing  `scalar_line_size =1` causes the line size argument to only have one unique value. It still works as intended.
```
data %>%
  plot_with_size(
    base_point_size = 1,
    scalar_point_size = 2,
    base_line_size = 1,
    scalar_line_size = 1
  )
```
![image](https://user-images.githubusercontent.com/40394828/63626279-ba56dd80-c602-11e9-804b-6bd7e6d0be54.png)

Now comes the confusing part. If we also change `scalar_point_size = 1` the lines in geom_path double in size. Please note that the values mapped to geom_path() are the same as before.
```
data %>%
  plot_with_size(
    base_point_size = 1,
    scalar_point_size = 1,
    base_line_size = 1,
    scalar_line_size = 1
  )
```
![image](https://user-images.githubusercontent.com/40394828/63626382-26d1dc80-c603-11e9-9457-f7382a245abe.png)

Is this behavior working as intended? 

Finally, having worked around with various settings and attempts to solve the above I have noticed that the size arguments behave differently wheater they are placed inside or outside of the aes(). Again, I am not sure if this is WAI, but the way it works now is quite confusing to me at least.
Please consider the following plot. The titles contain the settings used to produce them. Code for the plot is below the plot.

![image](https://user-images.githubusercontent.com/40394828/63627099-4f0f0a80-c606-11e9-91cc-ebbdc9a5da77.png)

```
library(patchwork)
base_plot <- data %>%
  ggplot(aes(x = x, y = y))

base_plot+
  geom_point(size = 1) +
  geom_path(size = 1,
            color = "red",
            alpha = 0.5)+
  ggtitle("geom_point(size = 1)+ geom_path(size = 1)")+

base_plot+
  geom_point(aes(size = 1)) +
  geom_path(size = 1,
            color = "red",
            alpha = 0.5)+
  ggtitle("geom_point(aes(size = 1))+ geom_path(size = 1)")+

base_plot+
  geom_point(size = 1) +
  geom_path(aes(size = 1), color = "red", alpha = 0.5)+
  ggtitle("geom_point(size = 1)+ geom_path(aes(size = 1))")+

base_plot+
  geom_point(aes(size = 1)) +
  geom_path(aes(size = 1),
            color = "red",
            alpha = 0.5)+
  ggtitle("geom_point(aes(size = 1))+ geom_path(aes(size = 1))")
```

**Comment by clauswilke** [comment]
Yes, it behaves as intended. If you map `size` via `aes()`, then you also have to define an appropriate scale, and if you don't do that then ggplot2 will make one up, and that scale may not look the way you were expecting.

If you have further questions on this topic, I suggest you post them on the RStudio forums or on Stackoverflow.
