### ISSUE TITLE
segment peeks out from behind arrow

### ISSUE THREAD

**Issue by rcorty** [tidyverse/ggplot2#3502]
When using geom_segment with the parameters below, you can see the line peeking out from behind the arrow, which seems like a minor bug to me.

``` r
ggplot() +
    annotate('segment',
             x = 0, xend = 0,
             y = 0, yend = 1,
             size = 2,
             lineend = 'square',
             linejoin = 'mitre',
             arrow = arrow(length = unit(12, 'pt'), type = 'closed')) +
    theme_void()
#> Error in ggplot(): could not find function "ggplot"
```

<sup>Created on 2019-08-24 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by rcorty** [comment]
![image](https://user-images.githubusercontent.com/718555/63634283-357bbc00-c622-11e9-89af-8f37f39d35fb.png)

**Comment by rcorty** [comment]
Or maybe this is expected behavior and if one doesn't want to see the segment peeking, one should use `lineend = 'butt'`

**Comment by thomasp85** [comment]
Yeah. This is how it is. In any way this is an issue with grid we cannot control
