### ISSUE TITLE
new geom suggestion: separate lines for upper and lower intervals

### ISSUE THREAD

**Issue by weiyangtham** [tidyverse/ggplot2#3503]
I'm wondering if there's room for a new geom that can produce the following graph

```r
library(tidyverse)

# Example data
df <- tibble(y = c(0, 0, 0, 0, 0, 1, 1.5, 1.7, 1.8), 
             upper_y = y + 0.2, 
             lower_y = y - 0.2,
             year = -4:4)

p <- ggplot(df, aes(year, y)) + geom_line()

# geom_errorline would simplify this
p + 
  geom_line(aes(y = upper_y), linetype = 2) +
  geom_line(aes(y = lower_y), linetype = 2)

```

![image](https://user-images.githubusercontent.com/15363607/63652678-e7a1a980-c730-11e9-833a-4a83162ca4fc.png)

So instead of having to use `geom_line` twice, you could instead do

```r
ggplot(df, aes(year, y, ymax = upper_y, ymin = lower_y)) + geom_errorline()

```

and this would fit more neatly into the idea of mapping the upper and lower intervals to the `ymin` and `ymax` aesthetics. 

I imagine there's a way to achieve that same plot with `geom_ribbon` or `geom_area` but I haven't been able to do so so I'm guessing it wouldn't be straightforward even if there is. 

Here is a prototype I wrote a few years ago: [https://github.com/weiyangtham/econothemes](https://github.com/weiyangtham/econothemes)

Thanks!

**Comment by yutannihilation** [comment]
> I imagine there's a way to achieve that same plot with `geom_ribbon` or `geom_area` but I haven't been able to do so so I'm guessing it wouldn't be straightforward even if there is.

I agree with you. I don't come up with some nice idea for now, but this won't be so difficult. e.g.

``` r
library(ggplot2)

# Example data
df <- tibble::tibble(
  y = c(0, 0, 0, 0, 0, 1, 1.5, 1.7, 1.8), 
  upper_y = y + 0.2, 
  lower_y = y - 0.2,
  year = -4:4
)

StatErrorLine <- ggproto("StatErrorLine", Stat,
  required_aes = c("x", "ymin", "ymax"),
  default_aes = aes(y = stat(y)),
  
  compute_group = function(data, scales) {
    idx <- names(data) %in% c("y", "ymin", "ymax")
    data_min <- data_max <- data[!idx]
    data_min$y <- data$ymin
    data_min$group <- paste0(data$group, "-min")
    data_max$y <- data$ymax
    data_max$group <- paste0(data$group, "-max")
    rbind(data_min, data_max)
  }
)

p <- ggplot(df, aes(year, y)) + geom_line()
p + 
  geom_line(aes(ymax = upper_y, ymin = lower_y), linetype = 2, stat = StatErrorLine)
```

![](https://i.imgur.com/wpBWZCi.png)

<sup>Created on 2019-08-29 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by weiyangtham** [comment]
I'd thought of it as a geom since I was thinking the more common use case would be one where the upper/lower bounds are provided in the data (e.g. confidence intervals from a model that has been passed through `broom::tidy(conf.int = TRUE)`) rather than being a transformation. It would also be more directly analogous to the other "interval" geoms like `geom_errorbar` or `geom_ribbon`, and therefore maybe more intuitive?

**Comment by yutannihilation** [comment]
Now I come to wonder if we can just write this with `geom_ribbon()`:

``` r
ggplot(df, aes(year, y)) + geom_line() + 
  geom_ribbon(aes(ymax = upper_y, ymin = lower_y),
              linetype = 2, fill = NA, colour = "black")
```

I mean, it's just an implementational detail that `GeomRibbon` draws polygons, and it might be able to draw lines and polygons separately. For example, https://github.com/tidyverse/ggplot2/commit/017992b8cf94d4ed10c81defc32133c2763dda44:

``` r
devtools::load_all("~/Documents/repo/ggplot2")
#> Loading ggplot2

df <- tibble::tibble(
  y = c(0, 0, 0, 0, 0, 1, 1.5, 1.7, 1.8), 
  upper_y = y + 0.2, 
  lower_y = y - 0.2,
  year = -4:4
)

# can divide the ribbon
df[4, "upper_y"] <- NA 
df[4, "lower_y"] <- NA

ggplot(df, aes(year, y)) + geom_line() + 
  geom_ribbon(aes(ymax = upper_y, ymin = lower_y),
              linetype = 2, fill = "red", alpha = 0.1, colour = "black")
```

![](https://i.imgur.com/TRMLcUF.png)

<sup>Created on 2019-09-02 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

I'm not sure if this really will be an acceptable change, though...

**Comment by weiyangtham** [comment]
Something like this would be great. Is the worry that users might expect `geom_ribbon()` to always draw polygons?

**Comment by yutannihilation** [comment]
> users might expect `geom_ribbon()` to always draw polygons?

I expected there's effectively no such users, but I'm not fully sure... Just curious, have you ever seen such a usage?

**Comment by weiyangtham** [comment]
Just to make sure we're on the same page, are you asking if I've seen someone use `geom_ribbon` with a transparent fill but they still want the polygon? I don't think I've seen that before.

**Comment by yutannihilation** [comment]
Yes, that's what I meant to ask. Thanks.
