### ISSUE TITLE
Feature request: scale_stroke_manual

### ISSUE THREAD

**Issue by RABxx** [tidyverse/ggplot2#3507]
It would be great if there were a `scale_stroke_manual` like we have for the other aesthetics.

Especially when using different symbols like a solid circle and '+', I only really want thicker stroke on the '+'.

**Example:**
```
dat <- data.frame(
  Type = c('A', 'B', 'C'),
  X = 1:3,
  Y = 1:3,
  stringsAsFactors = F
)

ggplot(dat, aes(x = X, y = Y)) +
  geom_point(
    aes(shape = Type), 
    stroke = 2,   # makes the dot look wierd
    size = 5
  ) +
  scale_shape_manual(
    values = c(`A` = 3, `B` = 19, `C` = 4)
  )

ggplot(dat, aes(x = X, y = Y)) +
  geom_point(
    aes(shape = Type),  # makes the cross and plus look too skinny
    size = 5
  ) +
  scale_shape_manual(
    values = c(`A` = 3, `B` = 19, `C` = 4)
  )
```

![image](https://user-images.githubusercontent.com/48337093/63916198-43469c80-ca7b-11e9-8eff-29803e676228.png)

**Comment by clauswilke** [comment]
You can use `scale_discrete_manual()`.

``` r
library(ggplot2)

dat <- data.frame(
  Type = c('A', 'B', 'C'),
  X = 1:3,
  Y = 1:3,
  stringsAsFactors = F
)

ggplot(dat, aes(x = X, y = Y)) +
  geom_point(
    aes(shape = Type, stroke = Type), 
    size = 5
  ) +
  scale_shape_manual(
    values = c(`A` = 3, `B` = 19, `C` = 4)
  ) +
  scale_discrete_manual(
    aesthetics = "stroke",
    values = c(`A` = 2, `B` = 1, `C` = 2)
  )
```

![](https://i.imgur.com/EH4zykU.png)

<sup>Created on 2019-08-29 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by RABxx** [comment]
awesome, thanks! never new I could do that before :)

**Comment by yutannihilation** [comment]
Can we close this?

**Comment by clauswilke** [comment]
I assume so, yes.

**Comment by yutannihilation** [comment]
Thanks.

**Comment by astulaaa** [comment]
Hello, while scale_discrete_manual() definetely solves the stroke problem it adds an additional legend (all black). Can anyone let me know how to deactivate it?
