### ISSUE TITLE
Multiple factor columns, same aesthetic: levels reordered if NAs present

### ISSUE THREAD

**Issue by jkbest2** [tidyverse/ggplot2#3512]
Given two columns with the same factor levels in the same order, using both columns for an aesthetic (e.g. color) reorders the legend for that aesthetic to be alphabetical if `NA`s are present. I expected that if the two columns have the same levels in the same order this would be preserved in the legend ordering.

This does what I expect:

``` r
library(tidyverse)
lvls <- c("b", "a", "c")
df <- tibble(x = rep(1:3, each = 3),
             fct1 = factor(rep(lvls, 3), levels = lvls),
             fct2 = factor(rep(lvls[c(2, 3, 1)], 3), levels = lvls),
             y = rnorm(9))
levels(df$fct1) == levels(df$fct2)
#> [1] TRUE TRUE TRUE
ggplot(df, aes(x = x, y = y, color = fct1)) +
  geom_point(size = 6) +
  geom_point(aes(color = fct2), size = 4)
```

![](https://i.imgur.com/WOozUme.png)

<sup>Created on 2019-08-30 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

This does not (note the  `NA`s in `fct2`):

``` r
library(tidyverse)
lvls <- c("b", "a", "c")
df <- tibble(x = rep(1:3, each = 3),
             fct1 = factor(rep(lvls, 3), levels = lvls),
             fct2 = factor(rep(c(lvls[c(2, 3)], NA), 3), levels = lvls),
             y = rnorm(9))
levels(df$fct1) == levels(df$fct2)
#> [1] TRUE TRUE TRUE
ggplot(df, aes(x = x, y = y, color = fct1)) +
  geom_point(size = 6) +
  geom_point(aes(color = fct2), size = 4)
```

![](https://i.imgur.com/36HwNZr.png)

<sup>Created on 2019-08-30 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

This occurs even if I include `show.legend = FALSE` in the second `geom_point` call or include `NA` in the vector of factor levels.

**Comment by yutannihilation** [comment]
The levels matters only on the order of a variable within a layer. Merging them is done in a character way. For example:

``` r
library(tidyverse)

lvls <- c("b", "a")
df <- tibble(x = rep(1:3, each = 3),
             fct1 = factor("a", levels = lvls),
             fct2 = factor("b", levels = lvls),
             y = rnorm(9))

ggplot(df, aes(x, y)) +
  geom_point(aes(color = fct1), size = 6) +
  geom_point(aes(color = fct2), size = 4)
```

![](https://i.imgur.com/oIazurD.png)

<sup>Created on 2019-09-11 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

So, the problem is the difference of the actual values in each layer, and `NA` matters here because a discrete scale attempts to include `NA` by default. You can specify `na.translate = FALSE` to avoid this, though.

> Unlike continuous scales, discrete scales can easily show missing values, and do so by default. If you want to remove missing values from a discrete scale, specify `na.translate = FALSE`.
 (https://ggplot2.tidyverse.org/reference/discrete_scale.html)

``` r
library(tidyverse)
lvls <- c("b", "a", "c")
df <- tibble(x = rep(1:3, each = 3),
             fct1 = factor(rep(lvls, 3), levels = lvls),
             fct2 = factor(rep(c(lvls[c(2, 3)], NA), 3), levels = lvls),
             y = rnorm(9))

p1 <- ggplot(df, aes(x = x, y = y)) +
  geom_point(aes(color = fct1), size = 4)

p2 <- ggplot(df, aes(x = x, y = y)) +
  geom_point(aes(color = fct2), size = 4)

patchwork::wrap_plots(p1, p2)
```

![](https://i.imgur.com/qWrq4FQ.png)

``` r

ggplot(df, aes(x = x, y = y, color = fct1)) +
  geom_point(size = 6) +
  geom_point(aes(color = fct2), size = 4) +
  scale_colour_hue(na.translate = FALSE)
#> Warning: Removed 3 rows containing missing values (geom_point).
```

![](https://i.imgur.com/29ja5MI.png)

<sup>Created on 2019-09-11 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
