### ISSUE TITLE
Feature request: a quick and dirty custom legend

### ISSUE THREAD

**Issue by mcsiple** [tidyverse/ggplot2#3516]
I'm making plots that have an ifelse() statement in them for determining aesthetics. 

---

I can get the aesthetics I want to appear in the plot, but the legend doesn't look like it should. I think it would be very amazing if there were a **way to make a custom legend as one does in base R**, to add to a `ggplot` object. In the meantime, here is my issue:

- I separate fleets by shape AND color aesthetics
- Observations are empty points, estimates are filled points

These aesthetics show up in the figure but not in the legend.  

Here is some code and the figure it generates:
```r

dat <- data.frame(Year=2016,
                  Fleet=c(rep(c("Artisanal","Industrial"),times=2)), 
                  set = rep(c("Predicted","Observed"),each=2),
                  q5=c(0.8,1.1,NA,NA),
                  q50=c(9.1,14.1,0,0),
                  q95=c(40,50,NA,NA))

dat$set <- as.character(dat$set)
pal <- c("#7bbcb0", "#3a7c89")
pd <- position_dodge(0.2)

p <- ggplot(dat,aes(x=Year,
                      y=q50,
                      shape=factor(Fleet),
                      colour=factor(Fleet),
                      fill=ifelse(set=="Predicted",factor(Fleet),set))) + 
  geom_linerange(aes(ymin=q5,ymax=q95),position=pd,lwd=1.1) +
  geom_point(size=4,position=pd) +
  scale_shape_manual("Fleet",values=c(24,21)) +
  scale_colour_manual("Fleet", values=pal) +
  scale_fill_manual("set",values=c(pal,"white")) +
  scale_x_continuous("Year",breaks=2015:2017) +
  theme_classic(base_size=14) +
  theme(legend.direction="vertical",legend.position="right") +
  ylab("Number dead")

p
```
This produces a plot like the following: 
![test](https://user-images.githubusercontent.com/2936426/64213502-09eaa400-ce62-11e9-8ebd-d28acad3ae99.png)

I would like to be able to have two piece of info in the legend:
1. Open circle = obs; filled circle = estimate
2. Filled shape 1 = Artisanal; Filled shape 2 = Industrial

Thank you!

**Comment by karawoo** [comment]
I'm not sure if fully manual legends are something that we're likely to develop soon, however `override.aes` provides enough manual control that, combining it with manual scale breaks, I do think there's a way to get what you are looking for in this plot:

``` r
library("ggplot2")
dat <- data.frame(Year=2016,
                  Fleet=c(rep(c("Artisanal","Industrial"),times=2)), 
                  set = rep(c("Predicted","Observed"),each=2),
                  q5=c(0.8,1.1,NA,NA),
                  q50=c(9.1,14.1,0,0),
                  q95=c(40,50,NA,NA))

dat$set <- as.character(dat$set)
pal <- c("#7bbcb0", "#3a7c89")
pd <- position_dodge(0.2)

ggplot(
  dat,
  aes(x = Year,
      y = q50,
      shape = factor(Fleet),
      colour = factor(Fleet),
      fill = ifelse(set == "Predicted", factor(Fleet), set))
) + 
  geom_linerange(aes(ymin = q5, ymax = q95), position = pd, lwd = 1.1) +
  geom_point(size = 4,position = pd) +
  scale_shape_manual("Fleet", values = c(24, 21)) +
  scale_colour_manual("Fleet", values = pal) +
  scale_fill_manual(
    "set",
    values = c(pal, "white"),
    breaks = c(1, 2),
    labels = c("Predicted", "Observed")
  ) +
  guides(
    colour = "none",
    fill = guide_legend(
      override.aes = list(shape = 21, fill = list("black", "white"))
    ),
    shape = guide_legend(
      override.aes = list(fill = pal, colour = pal)
    )
  )
#> Warning: Removed 2 rows containing missing values (geom_linerange).
```

![](https://i.imgur.com/efuGtnl.png)

<sup>Created on 2019-09-03 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Does this work for your use case?

**Comment by mcsiple** [comment]
It wooooooorked! Thank you so much. This works for my purpose! I would not have been able to figure it out without you.
