### ISSUE TITLE
Feature request: center panel in image

### ISSUE THREAD

**Issue by MaxBareiss** [tidyverse/ggplot2#3517]
Sometimes when using `ggplot2` images in other software, it would be nice to have the panel centered in the resulting image file. The panel (or group of facet panels) is not normally centered due to the size of the y axis label. This centering can be manually accomplished by adjusting the `theme(plot.margin)` value, but that would involve measuring things and wouldn't be easy to do. Would it be possible to include some `plot.margin` value that automatically centers the panel/facet panels?

```r
test_plot = ggplot(mpg, aes(displ, hwy, color = class)) + geom_point()
ggsave("file.png",plot = test_plot,width=5,height = 3)
```

**Comment by thomasp85** [comment]
This is outside the scope of ggplot2 I would say. There is too many interpretations of what centring means (center only the panels?, include strips? include axes?)
