### ISSUE TITLE
Feature request:  allow different border specification in element_rect and element_text

### ISSUE THREAD

**Issue by karsfri** [tidyverse/ggplot2#3518]
I don't know it's possible to impliment but I would love to be able to write something like:

`element_rect(
    color = c(t = my_color, r = NA, b = my_color, right = NA)
)`

One element vector could apply to all and two element vector could apply for t&b and l&r.

I've felt the need for this on sepperate occations for titles, panels and plot.backrounds.

**Comment by thomasp85** [comment]
This is unfortunately not something that is supported by the underlying graphic engine, unless we begin to stroke each side separately. The amount of trouble this would create makes it unlikely we will ever do that

**Comment by clauswilke** [comment]
Actually, let's tag issue #3373 here. If I get overly ambitious and add more complete CSS support to gridtext then I'll probably add separate border strokes, since that's an inherent component of CSS. It's not going to happen any time soon, though.
