### ISSUE TITLE
What is the meaning of "%|W|%"? Thanks

### ISSUE THREAD

**Issue by microly** [tidyverse/ggplot2#3520]
I see "**%|W|%**" in the code here:

scale$expand **%|W|%** if (scale$is_discrete()) discrete else continuous

https://github.com/tidyverse/ggplot2/blob/7f317d49a5c91aa14b1dac619c368222fe58c41b/R/scale-expansion.r#L107

But I do not know its meaning, and cannot find its definition.
Please help and show me its meaning or definition, thanks!

**Comment by thomasp85** [comment]
It means *take the first object unless it is a waiver in which case take the second*. It is only for internal use

**Comment by yutannihilation** [comment]
It's defined here:

https://github.com/tidyverse/ggplot2/blob/23e324197e0a5ddd764588d42838b0d96da9b68d/R/utilities.r#L14-L16

**Comment by microly** [comment]
Thanks all your kind reply!
Thanks all your hard works to improve ggplot2~ 

@thomasp85 
@yutannihilation
