### ISSUE TITLE
Documentation for plotting bin proportion in geom_histogram

### ISSUE THREAD

**Issue by kuriwaki** [tidyverse/ggplot2#3522]
Showing proportions (instead of counts or density) of a bin in a histogram is a common exercise for a wide range of users, but this is not documented.  Most stackoverflow suggestions are either conflicting or [outdated](https://stackoverflow.com/questions/11766856/normalizing-y-axis-in-histograms-in-r-ggplot-to-proportion). 

The solution below by @clauswilke  in a now-locked thread seems like the best practice. Could this trick as well as the `width` stat be documented in the `geom_histogram` manual and the ggplot website? Happy to start a PR. 

---

``` r
library(ggplot2)

# instead of plotting the count statistic in geom_histogram, 
# plot the proportion of a bin, which is equivalent to the product of the 
# density and the width statistic
ggplot(diamonds, aes(x = carat, y = stat(density*width))) +
  geom_histogram(binwidth = 0.01)
```

![](https://i.imgur.com/07ggGsR.png)

<sup>Created on 2019-09-07 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

> The solution is to use `aes(y = stat(width*density))`. This converts the density back into a percentage. Reprex follows below.

_Originally posted by @clauswilke in https://github.com/tidyverse/ggplot2/issues/2499#issuecomment-448788543_

**Comment by yutannihilation** [comment]
Hmm... I'm wondering if using `stat(width)` is really a part of ggplot2's API; it's not a calculated variable of `StatBin`. I didn't notice `stat()` can access not only to official calculated variables, but also to other internal variables. For other example:

``` r
library(ggplot2)

ggplot(data.frame(x = 1, id = factor(1:3)), aes(x, x)) +
  geom_text(aes(label = stat(PANEL)), size = 20) +
  facet_wrap(vars(id))
```

![](https://i.imgur.com/hW8pLJM.png)

<sup>Created on 2019-09-11 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

In my opinion, `width` is just an internal variable and should not be recommended to use because it can be renamed in future.

@clauswilke
What do you think?

**Comment by clauswilke** [comment]
I'm not sure I understand what "it's not a calculated variable of `StatBin`" means.

These are all the variables that `StatBin` calculates:
https://github.com/tidyverse/ggplot2/blob/7f317d49a5c91aa14b1dac619c368222fe58c41b/R/bin.R#L168-L175
I don't see how `width` is in any way different than, say, `density`.

**Comment by yutannihilation** [comment]
Yes, `width` is a calculated variable in that sense. The reason I thought it's not exposed officially was

1. it's not documented in the Computed Variables section, and
https://github.com/tidyverse/ggplot2/blob/23e324197e0a5ddd764588d42838b0d96da9b68d/R/stat-bin.r#L30-L36

2. it's not included in the data `layer_data()` returns.
``` r
library(ggplot2)

p <- ggplot(diamonds, aes(carat)) +
  geom_histogram()

head(layer_data(p))
#> `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
#>       y count         x       xmin      xmax    density     ncount
#> 1   573   573 0.1658621 0.08293103 0.2487931 0.06404668 0.03769737
#> 2 15200 15200 0.3317241 0.24879310 0.4146552 1.69896944 1.00000000
#> 3  8165  8165 0.4975862 0.41465517 0.5805172 0.91263720 0.53717105
#> 4  6096  6096 0.6634483 0.58051724 0.7463793 0.68137617 0.40105263
#> 5  4138  4138 0.8293103 0.74637931 0.9122414 0.46252208 0.27223684
#> 6  7465  7465 0.9951724 0.91224138 1.0781034 0.83439519 0.49111842
#>     ndensity PANEL group ymin  ymax colour   fill size linetype alpha
#> 1 0.03769737     1    -1    0   573     NA grey35  0.5        1    NA
#> 2 1.00000000     1    -1    0 15200     NA grey35  0.5        1    NA
#> 3 0.53717105     1    -1    0  8165     NA grey35  0.5        1    NA
#> 4 0.40105263     1    -1    0  6096     NA grey35  0.5        1    NA
#> 5 0.27223684     1    -1    0  4138     NA grey35  0.5        1    NA
#> 6 0.49111842     1    -1    0  7465     NA grey35  0.5        1    NA
```

<sup>Created on 2019-09-12 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

But, I don't check this in detail yet. Maybe I'm just confused with the case of `width` as an aesthetic, where we want to hide `width`  from users to avoid confusion... (c.f. https://github.com/tidyverse/ggplot2/pull/3194)

**Comment by clauswilke** [comment]
Weird, I have no idea why `width` doesn't make it into the layer data.

**Comment by yutannihilation** [comment]
IIRC, this is somewhat related to the effort we are trying to treat `width` as a param.

**Comment by thomasp85** [comment]
`width` is not present because it gets dropped between the stat and geom AFAIK.

**Comment by kuriwaki** [comment]
Apologies for not following all the nuances, but does this imply `y = stat(density*width)` is a safe way to generate proportion histograms moving forward?

**Comment by thomasp85** [comment]
It should be safe, but I think it may make sense to provide it explicitly by `stat_bin()`... @clauswilke do you have any input to this

**Comment by clauswilke** [comment]
I think we should document `width` and also add a unit test that uses it to make sure it doesn't randomly disappear at some point in the future.

**Comment by yutannihilation** [comment]
> `width` is not present because it gets dropped between the stat and geom AFAIK.

Sorry, now I think I see the rule behind this a bit clearer now. Let me confirm.

* A computed variable `width` and an aesthetic `width` are two different things.
    * A computed variable `width` is what `stat_bin()` officially provides
    * But, it's not always allowed to map the variable `width` (or any other variable) to an aesthetic `width` of such `Geom` as `geom_bar()` (c.f. https://github.com/tidyverse/ggplot2/issues/3142#issuecomment-464418903)

Is my understanding correct?

**Comment by clauswilke** [comment]
Yes, I think that's correct.

**Comment by yutannihilation** [comment]
Thanks, then I agree with documenting `width` and adding tests.
