### ISSUE TITLE
theme() defines flipped axes differently

### ISSUE THREAD

**Issue by pmarchand1** [tidyverse/ggplot2#3524]
In a plot with `coord_flip`, *x* and *y* refer to the pre-flip coordinates for most functions (`aes`, `scale_...`, etc.), but not when adjusting theme elements. 

```r
library(ggplot2)

ggplot(mtcars, aes(x = as.factor(cyl), y = mpg)) +
    geom_boxplot() +
    coord_flip() +
    scale_y_continuous(limits = c(0, 40)) +
    theme(axis.text.x = element_text(face = "italic"))
```

**Comment by yutannihilation** [comment]
The answer is the same as https://github.com/tidyverse/ggplot2/issues/2908:

> I think this is a sufficiently large amount of work for a relatively small gain, that we are unlikely to ever implement it, and so I am closing the issue in recognition of that fact.
