### ISSUE TITLE
Feature request: compressed TIFF output from ggsave()

### ISSUE THREAD

**Issue by stweb75** [tidyverse/ggplot2#3525]
Some publications set maximum file sizes. The function ggsave() generates uncompressed TIFF files. Compression can achieve a huge reduction in TIFF file sizes.
Example: ggsave(filename="Fig3.tiff", scale=1, width=80, height=60, units="mm", dpi=300)
  The output file size for this simple black and white geom_boxplot() is 1959 KB.
  I opened this TIFF file in Photoshop and then resaved it with LZW compression.
  The compressed file size is 88 KB.
LZW compression is widely supported and now patent free (see: https://en.wikipedia.org/wiki/TIFF and https://en.wikipedia.org/wiki/Lempel%E2%80%93Ziv%E2%80%93Welch).
There could be a "compress" argument for ggsave for which the default is appropriate image compression for the particular output. On this point, I wonder if ggsave() is using image compression for PDF and note that image compression for JPEG is not user adjustable.

**Comment by thomasp85** [comment]
`ggsave()` passes `...` along to the graphic device and `tiff()` indeed has a `compression` argument that you can use to set a range of compression strategies. You could e.g. do `ggsave(filename="Fig3.tiff", scale=1, width=80, height=60, units="mm", dpi=300, compression = "lzw+p")`. See the documentation for `tiff()` for more compression possibilities
