### ISSUE TITLE
Bug in `geom_vline` when passing an object of class `Date` as `xintercept`

### ISSUE THREAD

**Issue by GeospatialDaryl** [tidyverse/ggplot2#3527]
With an existing ggplot object, I want to add an vline for the center of mass for the water year.
```r
      inDF <- GetHydroDF(startDate, endDate)
      plotH <- plotHydrograph_HYYear(inDF)
      if( input$ShowCenterofMass ){
        centerDate <- CalculateCenterofMass(inDF)
        plotH <- plotH + geom_vline(xintercept = centerDate # here centerDate is class `Date`
                                    linetype = "dashed",
                                    color = "red"
                                    )
      }
      plot(plotH)
```
I get a very strange error.  It returns returns:
```
Warning: Error in as.Date.numeric: 'origin' must be supplied
```

After a bunch of different attempts (including coercing the centerDate object with `ymd(centerDate, origin = lubridate::origin)`, I finally tried this:

```r
      inDF <- GetHydroDF(startDate, endDate)
      plotH <- plotHydrograph_HYYear(inDF)
      if( input$ShowCenterofMass ){
        centerDate <- CalculateCenterofMass(inDF)
        plotH <- plotH + geom_vline(xintercept = as.double(centerDate),
                                    linetype = "dashed",
                                    color = "red"
                                    )
      }
      plot(plotH)
```
It works fine.  Is this the expected behavior?  It seems like a bug in the `vline` routine where somewhere it is casting to Double (`as.Date.numeric`) and then back, but with no opportunity to set the origin manually, or pass it down the call.

Thanks for the wonderful goodies! 
Daryl

**Comment by yutannihilation** [comment]
Could you provide a reproducible example by using reprex package?

https://www.tidyverse.org/help/

**Comment by yutannihilation** [comment]
Closing this. Feel free to file a new issue with a reproducible example code.
