### ISSUE TITLE
borders() w/ coord_map()

### ISSUE THREAD

**Issue by EvaMaeRey** [tidyverse/ggplot2#3530]
Using boarders() on its own produces good result, but with coord_map() there are horizontal streaks across the top of the map.   

```r
ggplot() +
  borders() 

ggplot() +
  borders() +
  coord_map()
```

**Comment by clauswilke** [comment]
Reprex below. Looks like a coordinate wrapping problem. In any case, for geospatial plotting, it's probably better to move to `geom_sf()`. And to me, `borders()` seems out of scope of ggplot2 proper, and we should consider deprecating it or at least upgrading it to use sf.

``` r
library(ggplot2)

ggplot() +
  borders() 
```

![](https://i.imgur.com/J1hQB1y.png)

``` r

ggplot() +
  borders() +
  coord_map()
```

![](https://i.imgur.com/lcn6FAO.png)

<sup>Created on 2019-09-14 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by clauswilke** [comment]
This seems to be caused by the specific projection used by `coord_map()`, which is provided by mapproject. In general, I would recommend against using `coord_map()`, since `coord_sf()` is a much better solution to the same problem.

``` r
library(ggplot2)

# works
ggplot() +
  borders() +
  coord_quickmap()
```

![](https://i.imgur.com/d4GodHw.png)

``` r

# works
ggplot() +
  borders() +
  coord_map(projection = "orthographic")
```

![](https://i.imgur.com/WljvlJV.png)

``` r

# doesn't work
ggplot() +
  borders() +
  coord_map(projection = "mollweide")
```

![](https://i.imgur.com/gM2tO8T.png)

<sup>Created on 2019-09-14 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by EvaMaeRey** [comment]
I think I kind of agree that it "seems out of scope of ggplot2 proper".  So I'll use another approach for now.  Thank you for looking into this!

**Comment by clauswilke** [comment]
Here is how you can make a world map using the Robinson projection, which is reasonable.

``` r
library(ggplot2)
library(rworldmap) # for getMap()
#> Loading required package: sp
#> ### Welcome to rworldmap ###
#> For a short introduction type :   vignette('rworldmap')
library(sf)
#> Linking to GEOS 3.6.1, GDAL 2.1.3, PROJ 4.9.3

world_sf <- st_as_sf(getMap(resolution = "low"))

crs_robin <- "+proj=robin +lat_0=0 +lon_0=0 +x0=0 +y0=0"

ggplot(world_sf) + 
  geom_sf(size = 0.5/.pt) +
  coord_sf(crs = crs_robin)
```

![](https://i.imgur.com/MRrRZmP.png)

<sup>Created on 2019-09-15 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

The Winkel Tripel projection would be better, but unfortunately can't be done with a simple projection string. It needs a little more manual work, as shown here:
https://github.com/clauswilke/dataviz/blob/68f455d33eaa2331e3932fde9291803dcf0c989e/coordinate_systems_axes.Rmd#L620-L661

You can see the difference between Robinson and Winkel Tripel here:
https://serialmentor.com/dataviz/coordinate-systems-axes.html#fig:worldmap-four-projections
