### ISSUE TITLE
Regression: geom_sf() is now too aggressive in removing rows

### ISSUE THREAD

**Issue by clauswilke** [tidyverse/ggplot2#3536]
I just encountered this problem where `geom_sf()` removes polygons that are plotted without outline. This is a regression in current ggplot2 master. I assume it's due to #3491.

cc @yutannihilation

``` r
library(ggplot2)
library(sf)
#> Linking to GEOS 3.7.2, GDAL 2.4.2, PROJ 5.2.0

# make outline of the world in robinson coordinates
lats <- c(90:-90, -90:90, 90)
longs <- c(rep(c(180, -180), each = 181), 180)

robin_outline <- 
  list(cbind(longs, lats)) %>%
  st_polygon() %>%
  st_sfc(crs = "+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs") %>% 
  st_sf() %>%
  st_transform(crs = "+proj=robin +lat_0=0 +lon_0=0 +x0=0 +y0=0")

# plot with line
ggplot(robin_outline) +
  geom_sf(fill = "#56B4E950", color = "black")
```

![](https://i.imgur.com/zbEhAa2.png)

``` r

# plot without line
ggplot(robin_outline) +
  geom_sf(fill = "#56B4E950", color = NA)
#> Warning: Removed 1 rows containing missing values (geom_sf).
```

![](https://i.imgur.com/DboQrFr.png)

<sup>Created on 2019-09-22 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by yutannihilation** [comment]
Opps..., I think your analysis is correct. Sorry for the regression. Then, we probably need to define a `handle_na()` that handle NAs differently depending on the type of geometry.

**Comment by clauswilke** [comment]
It seems to me that the true, real, underlying issue is that grid is overly conservative with checking input and doesn't gracefully degrade with missing or `NA` input in many cases.

@thomasp85 Any chance that we can get grid to be more tolerant to missing input, so we don't have to constantly code circles around grid's limitations?

Just one of many such examples:
``` r
library(grid)

grid.points(numeric(0), numeric(0))
#> Error in unit(x, default.units): 'x' and 'units' must have length > 0
```

<sup>Created on 2019-09-22 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by thomasp85** [comment]
I won’t rule that out but the call is ultimately Paul’s — I’ll talk with him about it

**Comment by yutannihilation** [comment]
#3537 is an attempt to fix this. But, I think I don't figure out what to do when the data is of mixed types of geometries. Any ideas...?

> It seems to me that the true, real, underlying issue is that grid is overly conservative with checking input and doesn't gracefully degrade with missing or `NA` input in many cases.

Sorry, I don't get your point. Even if the grid is super-tolerant for `NA`s, I think we still want to exclude missing values on ggplot2's side to set the plot range nicely.
