### ISSUE TITLE
More trouble with scales="free" / space = "free" with facet_grid + coord_flip

### ISSUE THREAD

**Issue by jtr13** [tidyverse/ggplot2#3540]
I know this has been much discussed (https://github.com/tidyverse/ggplot2/issues/95, https://github.com/tidyverse/ggplot2/issues/1393, https://github.com/tidyverse/ggplot2/issues/1492, https://github.com/tidyverse/ggplot2/issues/1848) and addressed (https://github.com/tidyverse/ggplot2/pull/1756, https://github.com/tidyverse/ggplot2/pull/1857) but still having trouble creating Cleveland dot plots with facets. Specifically, with `facet_grid()` (see example below) there is a uniform scale on the x-axis, as one would expect to see with `scales = "fixed"` not `scales = "free"`. I would expect the code to produce axes as shown in the second example using `facet_wrap()`, where the x-axis scale is different for each panel, scaled to the data in that panel.

MWE:

```
df <- data.frame(x = c("a", "b", "c", "d", "e"),
                 y = c("c", "c", "f", "f", "f"),
                 z = c(1, 6, 1000, 1020, 1050))

# scales = "free" doesn't work -- there is a single x-axis scale for all facets
ggplot(df, aes(x, z)) + 
  geom_point() + 
  facet_grid(y ~ ., scales = "free", space = "free") +
  coord_flip()
```

![image](https://user-images.githubusercontent.com/14161912/65474470-f66f9f00-de49-11e9-9f42-8bda04dfbae8.png)

It does work with `facet_wrap()` but want to be able to use `facet_grid()` since there's no `space = "free" ` option for `facet_wrap()`.

```
# this works -- the x-axis scale is different for each panel, and scaled to the data in that panel
ggplot(df, aes(x, z)) + 
  geom_point() + 
  facet_wrap(~y, scales = "free", ncol = 1) + 
  coord_flip()
```

![image](https://user-images.githubusercontent.com/14161912/65474587-64b46180-de4a-11e9-9bb4-33baebaa0f08.png)

**Comment by clauswilke** [comment]
Could you clarify what exactly the problem is? When you say "it works" or "it doesn't work", what exactly are you referring to? And for the case that doesn't work, what result would you like to see?

**Comment by smouksassi** [comment]
this can be solved with ggforce latest release see code
```r
library(ggplot2)
library(ggforce)
df <- data.frame(x = c("a", "b", "c", "d", "e"),
                 y = c("c", "c", "f", "f", "f"),
                 z = c(1, 6, 1000, 1020, 1050))
ggplot(df, aes(z, x)) + 
  geom_point() + 
  ggforce::facet_col(~y, scales = "free", space = "free",strip.position = "right")
 ```

**Comment by jtr13** [comment]
@clauswilke Sorry... I edited to clarify.
