### ISSUE TITLE
nudge_x and nudge_y in geom_text with facet_wrap issue

### ISSUE THREAD

**Issue by shrikantsoni88** [tidyverse/ggplot2#3542]
Hi,
I am trying to use facet_wrap, and passing nudge_x and nudge_y parameters to geom_text. 
My plots are dynamically faceted via my Shiny application based on user inputs. My plot scales are set to "free".

The issue is that setting values for nudge_x and nudge_y seem to affect the y-axis in absolute sense. They are not changing the text positions in relative manner. How can I get the text positions just above my points ? See the attached chart for reference. The text label positions are changing by 0.1 for Aircare, while they hardly seem to change for Baby Care, for whom the y-axis values are significantly higher

Below is the full code I am using to generate the plot

output$trends_plot <- renderPlotly({ ggplotly(ggplot(reactvars$dfsub() , aes(x=  reorder(Fiscal_Month , Month_ID) , y = Value_NIV_Shipment , group = Fiscal_Year , color = Fiscal_Year)) + geom_point() + geom_line()  + xlab("Month") + ylab("Value_NIV_Shipment") + geom_text(aes(label = Value_NIV_Shipment , fontface = "bold") , nudge_x = 0.1 , nudge_y = 0.1  ) +  facet_wrap(. ~ Category , scales = "free" , nrow = 5 , ncol = 2) ) })
  

![geom_text nudge_x issue](https://user-images.githubusercontent.com/55405238/65623166-d2949080-dfe4-11e9-8f0f-11cf2180e3ea.PNG)

**Comment by clauswilke** [comment]
This type of question is better suited for the RStudio forums or stackoverflow.com. The ggplot2 issue tracker is not meant as a place for user support.

In a nutshell, though, you can either calculate appropriate `nudge_x` and `nudge_y` values for the respective subsets of your data or you can use `hjust` and `vjust`.
