### ISSUE TITLE
stat_summary with geom = "boxplot" error even when group aesthetic is supplied

### ISSUE THREAD

**Issue by woodwards** [tidyverse/ggplot2#3544]
ggplot2 recently changed to require a group aesthetic for boxplots. My code using stat_summary(geom = "boxplot") no longer works, even when I provide a group aesthetic. geom = "errorbar" works fine with or without the group aesthetic. (I have asked this on stackoverflow but got no response)

``` r
library(ggplot2)

custombox1 <- function(y){
    data.frame(ymin=quantile(y,0.025),
               lower=quantile(y,0.25),
               middle=quantile(y,0.5),
               upper=quantile(y,0.75),
               ymax=quantile(y,0.975),
               y=y,
               width=0.5,
               row.names = NULL)
}

ggplot(
    data = data.frame(x = sample(letters, 200, replace = TRUE), y = runif(200)),
    mapping = aes(x = x, y = y)
       ) +
    stat_summary(fun.data = custombox1, geom = "errorbar") 
```

![](https://i.imgur.com/Ws2wFmT.png)

``` r

ggplot(
    data = data.frame(x = sample(letters, 200, replace = TRUE), y = runif(200)),
    mapping = aes(group = x, x = x, y = y)
) +
    stat_summary(fun.data = custombox1, geom = "errorbar") +
    stat_summary(fun.data = custombox1, geom = "boxplot")
#> Error: Can't draw more than one boxplot per group. Did you forget aes(group = ...)?
```
<sup>Created on 2019-09-27 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by clauswilke** [comment]
It may look like the first plot works and the second doesn't, but in fact both plots have the same problem. Your `custombox1()` function creates one row per original data point, not one row per group. Thus, you're asking ggplot to draw one errorbar/boxplot per original data point. In the first case, all these errorbars are plotted on top of one another. In the second case, you get an error.

If you have further questions on this topic, the RStudio forums or stackoverflow.com would be more appropriate venues. ggplot works as expected.

``` r
library(ggplot2)

custombox1 <- function(y){
  d <- data.frame(ymin=quantile(y,0.025),
             lower=quantile(y,0.25),
             middle=quantile(y,0.5),
             upper=quantile(y,0.75),
             ymax=quantile(y,0.975),
             y=y,
             width=0.5,
             row.names = NULL)
  d[1, ]
}

ggplot(
  data = data.frame(x = sample(letters, 200, replace = TRUE), y = runif(200)),
  mapping = aes(group = x, x = x, y = y)
) +
  stat_summary(fun.data = custombox1, geom = "errorbar") +
  stat_summary(fun.data = custombox1, geom = "boxplot")
```

![](https://i.imgur.com/UHxzYiA.png)

<sup>Created on 2019-09-26 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by woodwards** [comment]
Thank you so much!
