### ISSUE TITLE
boxplot computation fails when setting scale limits

### ISSUE THREAD

**Issue by cpsievert** [tidyverse/ggplot2#3548]
Before 10fa0014d6be81a7e641b8c2c3b48e1df1b7e2f5, this code produced the following image:

```r
ggplot(PlantGrowth, aes(y = weight)) +
  geom_boxplot() +
  scale_y_continuous(limits = c(5, 7.5))
```

![image](https://user-images.githubusercontent.com/1365941/66005749-f8e97e80-e471-11e9-8075-b36425373914.png)

After 10fa0014d6be81a7e641b8c2c3b48e1df1b7e2f5, it now produces a blank plot with this warning:

```r
Warning message:
Computation failed in `stat_boxplot()`:
missing values and NaN's not allowed if 'na.rm' is FALSE
```

cc @thomasp85

**Comment by rudeboybert** [comment]
I believe the issue is more fundamental than scale limits. Consider the following code:
``` r
library(ggplot2)
library(nycflights13)

ggplot(data = weather, mapping = aes(x = factor(month), y = temp)) +
  geom_boxplot()
```
Using `ggplot2_3.2.1` yields

![](https://i.imgur.com/2X7moIY.png)

whereas using `ggplot2_3.2.1.9000` yields 

![](https://i.imgur.com/o0ZCeQ3.png)
along with the same error message as above:

``` r
#> Warning: Computation failed in `stat_boxplot()`:
#> missing values and NaN's not allowed if 'na.rm' is FALSE
```
cc @ismayc

**Comment by clauswilke** [comment]
I think I found the problem. It's in this line:
https://github.com/tidyverse/ggplot2/blob/10fa0014d6be81a7e641b8c2c3b48e1df1b7e2f5/R/stat-boxplot.r#L55

It should read `vars = "y"`.

Reprex:

``` r
library(ggplot2)
library(rlang)
library(nycflights13)

# doesn't work
ggplot(data = weather, mapping = aes(x = factor(month), y = temp)) +
  geom_boxplot()
#> Warning: Computation failed in `stat_boxplot()`:
#> missing values and NaN's not allowed if 'na.rm' is FALSE
```

![](https://i.imgur.com/DQUkDdi.png)

``` r

# fix setup_data() function of StatBoxplot
StatBoxplot$setup_data <- function(data, params) {
  data <- ggplot2:::flip_data(data, params$flipped_aes)
  data$x <- data$x %||% 0
  data <- ggplot2:::remove_missing(
    data,
    na.rm = FALSE,
    vars = "y",
    name = "stat_boxplot"
  )
  flip_data(data, params$flipped_aes)
}

# now it works
ggplot(data = weather, mapping = aes(x = factor(month), y = temp)) +
  geom_boxplot()
#> Warning: Removed 1 rows containing missing values (stat_boxplot).
```

![](https://i.imgur.com/AnDZo6b.png)

<sup>Created on 2019-10-06 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

cc @thomasp85

**Comment by clauswilke** [comment]
Thomas, while we're at it, is this line correct, or should it read `na.rm = params$na.rm`?
https://github.com/tidyverse/ggplot2/blob/10fa0014d6be81a7e641b8c2c3b48e1df1b7e2f5/R/stat-boxplot.r#L54

It looks like with the current settings it's impossible to suppress the warning about missing values.
``` r
library(ggplot2)
library(rlang)
library(nycflights13)

# fix setup_data() function of StatBoxplot
StatBoxplot$setup_data <- function(data, params) {
  data <- ggplot2:::flip_data(data, params$flipped_aes)
  data$x <- data$x %||% 0
  data <- ggplot2:::remove_missing(
    data,
    na.rm = FALSE,
    vars = "y",
    name = "stat_boxplot"
  )
  flip_data(data, params$flipped_aes)
}

# warning doesn't get suppressed
ggplot(data = weather, mapping = aes(x = factor(month), y = temp)) +
  geom_boxplot(na.rm = TRUE)
#> Warning: Removed 1 rows containing missing values (stat_boxplot).
```

![](https://i.imgur.com/tD3XfQa.png)

``` r

StatBoxplot$setup_data <- function(data, params) {
  data <- ggplot2:::flip_data(data, params$flipped_aes)
  data$x <- data$x %||% 0
  data <- ggplot2:::remove_missing(
    data,
    na.rm = params$na.rm,
    vars = "y",
    name = "stat_boxplot"
  )
  flip_data(data, params$flipped_aes)
}

# now the warning gets suppressed
ggplot(data = weather, mapping = aes(x = factor(month), y = temp)) +
  geom_boxplot(na.rm = TRUE)
```

![](https://i.imgur.com/Lnrg819.png)

<sup>Created on 2019-10-06 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by thomasp85** [comment]
@clauswilke I don't know if it was intended that way (hardcoding the `na.rm`). @karawoo do you remember.

As for the cause of the original issue, it is actually much more complicated and is due to the new `x|y` notation in `required_aes` - will figure out a fix

**Comment by karawoo** [comment]
I think hardcoding `na.rm` was just an oversight, I'll fix it

**Comment by rudeboybert** [comment]
Thank you for fixing this so promptly. I would like to give credit to my student Nouhaila @nouny for finding the error with the `temp` vs `month` boxplot.
