### ISSUE TITLE
coord_flip does not flips slashes in legends

### ISSUE THREAD

**Issue by iago-pssjd** [tidyverse/ggplot2#3559]
I would suggest `coord_flip` include an option to allow flip the orientation of legend.
If, for example, without using it, I apply
```
> ggplot(data=mtcars,aes(x=vs,y=cyl)) +
     geom_bar(stat = "identity", fill="orange",width = 0.5) + 
     geom_hline(aes(yintercept = 20,color="red"), size = 1)
```
I get
![ncf](https://user-images.githubusercontent.com/40892925/66477139-9b6bb800-ea97-11e9-890b-65b5c8772cff.png)
with the slash in the legend in horizontal position, as the line in the plot. But, if I apply `coord_flip`
```
> ggplot(data=mtcars,aes(x=vs,y=cyl)) +
     geom_bar(stat = "identity", fill="orange",width = 0.5) + 
     geom_hline(aes(yintercept = 20,color="red"), size = 1) + coord_flip()
```
I get
![cflip](https://user-images.githubusercontent.com/40892925/66477217-d40b9180-ea97-11e9-83f5-be7b383c9b60.png)
with the line plotted flipped, but not the slash in the legend. I think it would be suitable `coord_flip` flips all the elements related in the plot.

Thank you very much!

**Comment by thomasp85** [comment]
That is unfortunately not possible. On the flip side, with the next version of ggplot2 you'll be able to use geom_bar in horizontal orientation without using coord_flip, so this problem would disappear
