### ISSUE TITLE
Suggestion for more informative error message when () missing from geom_*

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [tidyverse/ggplot2#3571]
If you omit the `()` at the end of a geom, you get the following error:

``` r
library(ggplot2)

ggplot(mtcars, aes(y = mpg, group = vs)) +
  geom_boxplot
#> Error: Don't know how to add geom_boxplot to a plot
```

I think the error would be more informative if it continued on to say _"Did you mean `geom_boxplot()`?"_

**Comment by yutannihilation** [comment]
This has been discussed on https://github.com/tidyverse/ggplot2/pull/3106#issuecomment-457934076 and some of us actually agreed the error message can be improved.

**Comment by mine-cetinkaya-rundel** [comment]
I see, thanks for the link!

This issue wasn't prompted by confusion between `%>%` and `+` or people using functions without `()` in pipelines. In most cases where I've seen code like this it wasn't due to an expectation of `geom_point()` working without the `()`, it was just forgetting to add the parantheses. I, like many others, start teaching with visualization/ggplot2 so there are lots of very newbie mistakes as people are learning the syntax.

I also agree that this is not widespread confusion, but more of a nice-to-have to help the few who struggle.

Note that I have not done a cost-benefit analysis of implementation difficulty vs. benefit of having the improved error in place, so I can't really say if it's "worth it" to make the change.

**Comment by yutannihilation** [comment]
Ah, thanks for the context. I guess it won't be very difficult to add some heuristic here, which is called only when raising this error:

https://github.com/tidyverse/ggplot2/blob/6f5ffea70e80ce3aa076fb9da8a6b0ec7ebfbc51/R/plot-construction.r#L90-L92

**Comment by clauswilke** [comment]
Yes, just check whether `object` is a function, and if it is suggest that they may have forgotten the parentheses.

**Comment by clauswilke** [comment]
Actually, I think this will do it. I can prepare a PR.

``` r
library(ggplot2)

# ggplot_add variant to be added
ggplot_add.function <- function(object, plot, object_name) { 
  stop(
    "Don't know how to add ", object_name, " to a plot. Did you mean ",
    object_name, "()?", call. = FALSE
  ) 
} 

# new error message
ggplot() + geom_point
#> Error: Don't know how to add geom_point to a plot. Did you mean geom_point()?
```

<sup>Created on 2019-10-28 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by clauswilke** [comment]
See #3594.
