### ISSUE TITLE
Point symbols do not appear in the legend [geom_sf]

### ISSUE THREAD

**Issue by kadyb** [tidyverse/ggplot2#3572]
I chose point symbols, they appeared on the map, but didn't appear in the legend.

```r
library("sf")
library("ggplot2")
df = data.frame(x = 1:2, y = 1:2, val = 3:4, shape = factor(1:2))
df = st_as_sf(df, coords = c("x", "y"), crs = 27700)

ggplot(df) +
   geom_sf(aes(color = val, shape = shape))
```
![Imgur](https://i.imgur.com/O5EWu4y.png)

**Comment by clauswilke** [comment]
Apparently the legend type is hardcoded and is not auto-detected:
https://github.com/tidyverse/ggplot2/blob/98708903cf3e76eee3c440c5e06d849d98c4ff02/R/geom-sf.R#L185

Manually setting it to "point" works, but if we could add auto-detection that would be great.

``` r
library("sf")
#> Linking to GEOS 3.7.2, GDAL 2.4.2, PROJ 5.2.0
library("ggplot2")
df = data.frame(x = 1:2, y = 1:2, val = 3:4, shape = factor(1:2))
df = st_as_sf(df, coords = c("x", "y"), crs = 27700)

ggplot(df) +
  geom_sf(aes(color = val, shape = shape), show.legend = "point")
```

![](https://i.imgur.com/eNDFKHE.png)

<sup>Created on 2019-10-16 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by clauswilke** [comment]
With current ggplot2 master:

``` r
library("sf")
#> Linking to GEOS 3.7.2, GDAL 2.4.2, PROJ 5.2.0
library("ggplot2")
df = data.frame(x = 1:2, y = 1:2, val = 3:4, shape = factor(1:2))
df = st_as_sf(df, coords = c("x", "y"), crs = 27700)

ggplot(df) +
  geom_sf(aes(color = val, shape = shape))
```

![](https://i.imgur.com/HCQfJup.png)

<sup>Created on 2019-12-06 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
