### ISSUE TITLE
Bar plot with several categories

### ISSUE THREAD

**Issue by nipnipj** [tidyverse/ggplot2#3577]
Hello!

I would like to plot only the top 10 (highest frequency) categories in a bar plot, not all te categories, in a barplot. is it possible to do this only by using ggplot? I did it by creating a secondary dataframe as follows

```
dd <- data.frame(sort(table(data$x),decreasing=TRUE))[1:10,]
ggplot(dd, aes(x = reorder(Var1, -Freq), y = Freq)) + 
geom_bar() 
```

I was wondering whether this can be done only using by ggplot2 commands.

**Comment by clauswilke** [comment]
This type of question would be more appropriate for the RStudio forums or stackoverflow.com. The ggplot2 issue tracker is meant for bug reports and feature requests.
