### ISSUE TITLE
scales argument not working in facet_grid()

### ISSUE THREAD

**Issue by jzadra** [tidyverse/ggplot2#3578]
Using `scales = "free_y"` with `facet_grid()` is having no effect.

``` r

suppressPackageStartupMessages(require(tidyverse))

#Does not work, all facets have same y scale:
diamonds %>% 
  ggplot(aes(x = carat, y = price)) + geom_point() + facet_grid(cut~clarity, scales = "free_y")
```

![](https://i.imgur.com/nr6cRPB.png)

``` r

#Does work:
diamonds %>% ggplot(aes(x = carat, y = price)) + geom_point() + facet_wrap(cut~clarity, scales = "free_y")
```

![](https://i.imgur.com/hs6rHN2.png)

<sup>Created on 2019-10-18 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by thomasp85** [comment]
It does work, but each row in your data has roughly the same y-range so it appears to have no effect. Try to experiment with a different dataset to see its effect

**Comment by jzadra** [comment]
I posted this example following seeing the issue with a different data set with more pronounced differences but which I cannot share.  However this example with diamonds very clearly shows it.  If you look at the Fair x IF you can see the issue clearly.

**Comment by thomasp85** [comment]
I think you misunderstands what it is supposed to do. In facet_grid all panels in a row share the same y-scale irrespective of the `free` setting. The `free` setting simply controls whether all rows should share the same scale range

**Comment by jzadra** [comment]
Ah I see.  So no way to have a grid with scales free by facet?  obviously the facet_wrap example does this with the data, but the way the facet labels aren't organized into x/y isn't ideal in some cases.

**Comment by thomasp85** [comment]
Not for each panel, no... you’ll need to create your own facet for that

**Comment by jzadra** [comment]
Ok, thanks Thomas!
