### ISSUE TITLE
Report a bug of guide-bins: it cannot work with geom_sf.

### ISSUE THREAD

**Issue by microly** [tidyverse/ggplot2#3582]
The guide-bins seems cannot work with geom_sf.

Some examples:

For geom_point, both "coloursteps" and "bins" guides work well:
```
library(ggplot2)
library(tibble)

ggplot(tibble(x = 1:10, y = x, z = x), aes(x, y, fill = z)) +
    geom_point(shape = 21, size = 10) +
    scale_fill_stepsn(guide = "coloursteps", colours = terrain.colors(10))
```
![p1](https://user-images.githubusercontent.com/18700975/67403472-8be68600-f5e4-11e9-8651-cd3096cdaea4.png)

```
ggplot(tibble(x = 1:10, y = x, z = x), aes(x, y, fill = z)) +
    geom_point(shape = 21, size = 10) +
    scale_fill_stepsn(guide = "bins", colours = terrain.colors(10))
```
![p2](https://user-images.githubusercontent.com/18700975/67403607-c3553280-f5e4-11e9-928d-6ade63238452.png)

But, for geom_sf, only "coloursteps" can work. 
There seems to be a bug in guide-bins.
```
nc <- sf::st_read(system.file("shape/nc.shp", package = "sf"))

ggplot() +
    geom_sf(aes(fill = AREA), data = nc) +
    scale_fill_stepsn(guide = "coloursteps", colours = terrain.colors(10))
```
![p3](https://user-images.githubusercontent.com/18700975/67404233-a4a36b80-f5e5-11e9-831c-a11a6b03b9ce.png)
```
ggplot() +
    geom_sf(aes(fill = AREA), data = nc) +
    scale_fill_stepsn(guide = "bins", colours = terrain.colors(10))

# Error in do.call("cbind", lapply(guide$geoms, function(g) g$data$size/10))[seq_len(n_keys),  : 
# subscript out of bounds
```

**Comment by yutannihilation** [comment]
Thanks, confirmed. The error occurs here when `g$data` doesn't contain `size` column. Probably it should be handled by the next `if` branch before getting subsetted?

https://github.com/tidyverse/ggplot2/blob/6f5ffea70e80ce3aa076fb9da8a6b0ec7ebfbc51/R/guide-bins.R#L321-L327

**Comment by microly** [comment]
OK, thanks for your work~
