### ISSUE TITLE
Remove space for legend title if it doesn't have a title

### ISSUE THREAD

**Issue by steveharoz** [tidyverse/ggplot2#3587]
If a guide has a label, you can make it flush with the edge of a plot:

```r
ggplot(PlantGrowth) + 
  aes(x=group, y=weight, fill=group) +
  geom_boxplot() + 
  theme(
    legend.position="top", 
    legend.justification = "left", 
    legend.margin = margin(0, 0, 0, 0))
```

![image](https://user-images.githubusercontent.com/2257540/67627750-35ad5900-f817-11e9-9a46-5d73e8f97ccb.png)

But if you set the label to NULL, a there is a gap or misalignment that doesn't seem to be removable:

```r
ggplot(PlantGrowth) + 
  aes(x=group, y=weight, fill=group) +
  geom_boxplot() + 
  labs(fill = NULL) + # removes legend title
  theme(
    legend.position="top", 
    legend.justification = "left", 
    legend.margin = margin(0, 0, 0, 0))
```

![image](https://user-images.githubusercontent.com/2257540/67627807-30044300-f818-11e9-8360-72e4b7e774b4.png)

**Comment by clauswilke** [comment]
It looks like a unit of `legend.spacing.x` is inserted even if the name is missing. 
``` r
library(ggplot2)

ggplot(PlantGrowth) + 
  aes(x=group, y=weight, fill=group) +
  geom_boxplot() + 
  labs(fill = NULL) + # removes legend title
  theme(
    legend.position="top", 
    legend.justification = "left", 
    legend.margin = margin(0, 0, 0, 0),
    legend.spacing.x = unit(0, "pt")
  )
```

![](https://i.imgur.com/xGlS9Du.png)

You can work around this issue by placing some spaces before and after the labels, so that setting `legend.spacing.x` to zero doesn't cause problems.

``` r

ggplot(PlantGrowth) + 
  aes(x=group, y=weight, fill=group) +
  geom_boxplot() + 
  scale_fill_hue(
    name = NULL,
    labels = function(x) paste0(" ", x, "   ")
  ) +
  theme(
    legend.position="top", 
    legend.justification = "left", 
    legend.margin = margin(0, 0, 0, 0),
    legend.spacing.x = unit(0, "pt")
  )
```

![](https://i.imgur.com/Inc8aQd.png)

The legend drawing code is a bit of a mess, so I don't see an immediate approach to fixing this more generally.

**Comment by steveharoz** [comment]
Thanks for the workaround!

**Comment by clauswilke** [comment]
Actually, here is a better approach. Just set the margins of `legend.text` appropriately.

In general, I'd like to get rid of `legend.spacing.*` altogether and just use margins on legend title and text to format the legend, but that requires different settings depending on whether the legend is laid out horizontally or vertically.

``` r
library(ggplot2)

ggplot(PlantGrowth) + 
  aes(x=group, y=weight, fill=group) +
  geom_boxplot() + 
  labs(fill = NULL) + # removes legend title
  theme(
    legend.position="top", 
    legend.justification = "left", 
    legend.margin = margin(0, 0, 0, 0),
    legend.spacing.x = unit(0, "pt"),
    legend.text = element_text(size = rel(0.8), margin = margin(0, 11, 0, 5.5))
  )
```

![](https://i.imgur.com/wh2gabD.png)

<sup>Created on 2019-10-27 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by brunomioto** [comment]
+1!

**Comment by mcanouil** [comment]
I believe the extra spacing can be removed with `legend.box.spacing = unit(0, "pt")`.
