### ISSUE TITLE
Example of flipped aes on geom_area() needs orientation?

### ISSUE THREAD

**Issue by yutannihilation** [tidyverse/ggplot2#3590]
The third figure on [the examples section of `geom_ribbon`/`geom_area`](https://ggplot2.tidyverse.org/dev/reference/geom_ribbon.html#examples) seems a bit confusing to me.

cc @thomasp85 

The comment says

> ```
> # Change orientation be switching the mapping
> ```

and I expected the left one below, but actually got the right one. Is the figure intended? Or, is this an example of failure to show the necessity of explicitly setting `orientation = "y"`? 

``` r
library(ggplot2)

huron <- data.frame(year = 1875:1972, level = as.vector(LakeHuron))

# expected one?
p1 <- ggplot(huron) +
  geom_area(aes(x = year, y = level)) +
  coord_flip() +
  ggtitle("flipped by coord")

# orientation = "y"?
p2 <- ggplot(huron) +
  geom_area(aes(x = level, y = year)) +
  ggtitle("flipped by aes")

patchwork::wrap_plots(p1, p2)
```

![](https://i.imgur.com/25qCTmx.png)

<sup>Created on 2019-10-27 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by thomasp85** [comment]
Good catch
