### ISSUE TITLE
reverse dodge order works differently in position_jitterdodge() vs., for example position_dodge2()

### ISSUE THREAD

**Issue by davebraze** [tidyverse/ggplot2#3610]
Reversing the order of dodged elements using position_dodge2(), one passes in `reverse=TRUE`. To reverse dodged element positions in position_jitterdodge(), it is necessary to use a negative value to `dodge.width=-.75`; there is no 'reverse' argument.  This is undocumented in position_jitterdodge and inconsistent with other dodge functions.

**Comment by clauswilke** [comment]
Please provide a [reprex.](https://reprex.tidyverse.org/articles/reprex-dos-and-donts.html)

**Comment by smouksassi** [comment]
davebraze is asking why there is no reverse argument for jitterdodge or at least document negative width behavior

``` r
library(ggplot2)
ggplot(mtcars,aes(as.factor(cyl),mpg,fill=as.factor(vs),color=as.factor(vs)  ))+
  geom_boxplot(position = position_dodge2(reverse = TRUE),color="black")+
  geom_point(position =position_jitterdodge(dodge.width = -0.75))
#> Warning: position_jitterdodge requires non-overlapping x intervals
```

![](https://i.imgur.com/BF0qdMy.png)

<sup>Created on 2019-11-07 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by joelgautschi** [comment]
the same is true for `position_dodge()` with `geom_point()`: position_dodge(width = -0.5) gives a warning. However, the order is reversed as I had hoped. 

``` r
library(tidyverse)

df <- tribble(~dimension, ~group, ~value,
              "dim 1", "A", 0.6,
              "dim 1", "B", 0.75,
              "dim 1", "C", 0.25,
              "dim 2", "A", 0.4,
              "dim 2", "B", 0.4,
              "dim 2", "C", 0.5)

plot <- ggplot(data = df,
               mapping = aes(x = dimension,
                             y = value,
                             color = group)) 

# warning
plot +  
  geom_point(position = position_dodge(width = -0.5))
#> Warning: position_dodge requires non-overlapping x intervals
```

![](https://i.imgur.com/8QLJaIf.png)

<sup>Created on 2021-01-26 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>


The question remains whether this is 'good practice' or if it is better to use an approach like `color = fct_rev(group)` within `aes()` to reverse the order.
