### ISSUE TITLE
coord_flip() reverses discrete axis scale direction

### ISSUE THREAD

**Issue by jzadra** [tidyverse/ggplot2#3616]
`coord_flip()` causes what was going left to right on the x-axis to go bottom to top on the now y-axis.  Since we (most of us) read left to right and top down, this behavior is unexpected and unwanted.

**Comment by clauswilke** [comment]
`coord_flip()` is equivalent to swapping the `x` and `y` aesthetics.

``` r
library(ggplot2)

p <- ggplot(iris, aes(color = Species)) +
  geom_point()

p + aes(x = Sepal.Length, y = Sepal.Width)
```

![](https://i.imgur.com/OEOrsDn.png)

``` r

p + aes(x = Sepal.Length, y = Sepal.Width) + coord_flip()
```

![](https://i.imgur.com/JgTkRIv.png)


``` r

p + aes(y = Sepal.Length, x = Sepal.Width)
```

![](https://i.imgur.com/0ZAIy5c.png)
<sup>Created on 2019-11-06 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by jzadra** [comment]
I'm using it for discrete x bar charts.  Is there a more appropriate way to rotate to get horizontal bars?

**Comment by smouksassi** [comment]
you can easily do flipped barcharts 
https://www.r-graph-gallery.com/218-basic-barplots-with-ggplot2.html
control ordering and more

**Comment by jzadra** [comment]
> you can easily do flipped barcharts
> https://www.r-graph-gallery.com/218-basic-barplots-with-ggplot2.html
> control ordering and more

Yes, that's exactly what I'm doing.  But note that the y-axis in that example starts at E and goes to A

**Comment by jzadra** [comment]
maybe we need a coord_transpose

**Comment by smouksassi** [comment]
You can reverse the scale 
Or specify the reverse order yourself
Hard to help without a reprex

**Comment by jzadra** [comment]
Yeah I saw that I can use fct_rev, however it just seems like an unexpected behavior for a discrete scale.  Perhaps I should file feature request? for a coord flip/transpose that is mean for discete?

**Comment by clauswilke** [comment]
In the next version of ggplot2, `coord_flip()` is equivalent to swapping out the aesthetics even in the case of bar plots and other directional geoms:

``` r
library(ggplot2)

ggplot(mpg, aes(x = class)) + 
  geom_bar() + coord_flip()
```

![](https://i.imgur.com/5OGNfJm.png)

``` r

ggplot(mpg, aes(y = class)) + 
  geom_bar()
```

![](https://i.imgur.com/BMbY4HB.png)

You can reverse the order with `fct_rev()`, or in numerous other ways including explicitly setting scale limits etc.

``` r

ggplot(mpg, aes(y = forcats::fct_rev(class))) + 
  geom_bar()
```

![](https://i.imgur.com/c2DR9tD.png)

Not sure what a meaningful feature request might be. Maybe to support reverse ordering for discrete scales?
