### ISSUE TITLE
Duplicated aesthetics on some documentations of Geom/Stat

### ISSUE THREAD

**Issue by yutannihilation** [tidyverse/ggplot2#3618]
Probably due to the change of the specification of `required_aes` (#3506), some documentations of Geom/Stat now show both **"x or y"** and, **"x"** and **"y"** separately on their Aesthetics section. This seems a bit confusing, so it's nice if we can fix this.

For example, https://ggplot2.tidyverse.org/dev/reference/geom_linerange.html#aesthetics:

<img width="712" alt="screenshot of `geom_linerange.html`" src="https://user-images.githubusercontent.com/1978793/68562551-8ebef300-048d-11ea-95cb-66b96468bee4.png">

**Comment by carywreams** [comment]
Is this a matter of modifying ```R/utilities-help.r``` to remove any parameter found in ```x$requires_aes``` from ```x$aesthetics()```  prior to, or in conjunction with, the ```union()``` operation ?

### from
```
rd_aesthetics_item <- function(x) {
  req <- x$required_aes
  req <- sub("|", "} \\emph{or} \\code{", req, fixed = TRUE)
  all <- union(req, sort(x$aesthetics()))

  ifelse(all %in% req,
    paste0("\\strong{\\code{", all, "}}"),
    paste0("\\code{", all, "}")
  )
}
```

### to
```
rd_aesthetics_item <- function(x) {
  req <- x$required_aes
  req <- sub("|", "} \\emph{or} \\code{", req, fixed = TRUE)
# req_aes <- parse req to handle "|" spec and create list of distinct required parameters
# optional_aes <- setdiff(req_aes,x$aesthetics())
  all <- union(req, sort(optional_aes))

  ifelse(all %in% req,
    paste0("\\strong{\\code{", all, "}}"),
    paste0("\\code{", all, "}")
  )
}
```

If I'm on the right track, let me know and I'll start figuring out how to do this.
Guidance/Ideas on the "parse req..." stage appreciated.

**Comment by carywreams** [comment]
Seems ```unlist(strsplit(self$required_aes, "|", fixed = TRUE))``` is used already to pull apart the "|" specs. So perhaps my previous question is answered.

I found that technique in ```R/stat-.r::aesthetics``` function definition, which appears to be where the individual required parameters are added into consideration (and thus duplicated for documentation) in ```R/utilities-help.r::rd_aesthetics_item()```, as part of the ```union()``` call (see above comment).

While I'm tempted to suggest correcting it in ```R/stat-.r::aesthetics```, some customers of that function  may continue to expect required parameters (specified as "x|y" in required aesthetics) to appear as individual items when retrieving the list of aesthetics. 

Changing the behavior in ```R/utilities-help.r::rd_aesthetics_item()``` to remove the duplicates may only affect documentation.

**Comment by carywreams** [comment]
Promising (at least on the documentation front)

```
diff --git a/man/geom_linerange.Rd b/man/geom_linerange.Rd
index 16fed3db..a0e073d1 100644
--- a/man/geom_linerange.Rd
+++ b/man/geom_linerange.Rd
@@ -134,12 +134,6 @@ This geom treats each axis differently and, thus, can thus have two orientations
 \item \code{group}
 \item \code{linetype}
 \item \code{size}
-\item \code{x}
-\item \code{xmax}
-\item \code{xmin}
-\item \code{y}
-\item \code{ymax}
-\item \code{ymin}
 }
 Learn more about setting these aesthetics in \code{vignette("ggplot2-specs")}.
 }
```

**Comment by carywreams** [comment]
appears to only affect these files:
```
#       modified:   geom_bar.Rd
#       modified:   geom_boxplot.Rd
#       modified:   geom_linerange.Rd
#       modified:   geom_ribbon.Rd
```

**Comment by carywreams** [comment]
testthat runs produce identical results on master branch and the branch with my candidate mod.
+ [on_i3618.txt](https://github.com/tidyverse/ggplot2/files/3928206/on_i3618.txt)
+ [on_master.txt](https://github.com/tidyverse/ggplot2/files/3928207/on_master.txt)

the pull request for #3506 looks to have had some build issues as well. Should I be concerned ?
As the results are the same, think I'm going to wrap this and submit a PR; will deal with any additional issues there.

**Comment by carywreams** [comment]
looking for a little help with automated code coverage checks in pr #3657

**Comment by clauswilke** [comment]
You can ignore them.

**Comment by carywreams** [comment]
```.ignored```

Thanks
