### ISSUE TITLE
https://ggplot2.tidyverse.org news links not updated to include 3.2.0

### ISSUE THREAD

**Issue by StefanBRas** [tidyverse/ggplot2#3622]
Brief description of the problem:

See title. Probably somewhat related to issue #3482

**Comment by batpigandme** [comment]
Just adding as a note: The post is linked in the pkgdown YAML (and it's in the devel site https://ggplot2.tidyverse.org/dev/), so it looks like the whole site is behind the actual released version.

**Comment by yutannihilation** [comment]
IMO, this is a separate issue than #3482 and seems difficult with the current workflow of pkgdown; the stable site is build against release tags, but the corresponding blog post will be published after the release so it's a bit difficult to include the URL at the time of release.

I think we can create a "tweaked version" of the release branch to tweak the site as I did in https://github.com/tidyverse/ggplot2/commit/c6160350c1b1376f0dcf01ae35ae0d3305e71a82, but I'm a bit hesitant to do that...

**Comment by yutannihilation** [comment]
We'll try to do nicer on the release of v3.3.0. Closing this now.
