### ISSUE TITLE
Needle plots

### ISSUE THREAD

**Issue by ggrothendieck** [tidyverse/ggplot2#3627]
It seems there is no nice way to create needle plots in ggplot2 whereas it is very easy in classic graphics.  `geom_linerange` can work but seems too involved and non-obvious.  A `geom_needle` wrapper around `geom_linerange` would be nice.

```
x <- 1:6
y <- x * c(1, -1)

plot(y ~ x, type = "h")

ggplot(data.frame(x, y), aes(x = x, ymax=pmax(0, y), ymin = pmin(0, y))) + 
  geom_linerange()
```

**Comment by clauswilke** [comment]
Reprex with output:
``` r
library(ggplot2)
x <- 1:6
y <- x * c(1, -1)

plot(y ~ x, type = "h")
```

![](https://i.imgur.com/E4W5fVp.png)

``` r

ggplot(data.frame(x, y), aes(x = x, ymax=pmax(0, y), ymin = pmin(0, y))) + 
  geom_linerange()
```

![](https://i.imgur.com/3Jl910N.png)

<sup>Created on 2019-11-16 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by clauswilke** [comment]
How exactly is a needle plot defined? Would `geom_col()` fit the bill?

``` r
library(ggplot2)
x <- 1:6
y <- x * c(1, -1)

ggplot(data.frame(x, y), aes(x = x, y = y)) + 
  geom_col()
```

![](https://i.imgur.com/p82o9M1.png)

``` r

ggplot(data.frame(x, y), aes(x = x, y = y)) + 
  geom_col(width = 0.05)
```

![](https://i.imgur.com/zSg0BWC.png)

<sup>Created on 2019-11-16 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by ggrothendieck** [comment]
It should act identically to `type = "h"`  and should be as simple to use as in classic graphics and lattice.  I don't really think `geom_linerange` and `geom_col` are sufficient.

**Comment by ggrothendieck** [comment]
By the way, I did some further googling and there are several questions on SO about this in relation to ggplot2 so it seems a number of people have found this confusing.  One answer came up with `geom_linerange` but they implemented it only partially assuming non-negative numbers.

https://stackoverflow.com/questions/26139878/needle-plot-in-ggplot2
https://stackoverflow.com/questions/25952270/code-for-type-h-in-ggplot2

Also with regards to lattice in addition to `type = "h"` the caret package defines `panel.needle` which is like `type = "h"` except it is rotated 90 degrees and there is a dot at the end of each needle.
https://rdrr.io/cran/caret/man/panel.needle.html

For example, try 

```
library(caret)
library(lattice)
xyplot(demand ~ Time, BOD, panel = panel.needle)
```

**Comment by thomasp85** [comment]
`ggalt::geom_lollipop()` seems to fit the bill. If you don’t want the terminal point you can just set size to zero

**Comment by yutannihilation** [comment]
> `geom_col` requires that you specify the width which seems problematic if you are generating reports automatically and don't know the range of the data.

If `width` is the only problem, you can set it to zero.  But, I agree it's nice if we can draw this without this kinds of workaround. I'm not yet sure if ggplot2 should have the dedicated geom for this, though....

``` r
library(ggplot2)
x <- 1:6
y <- x * c(1, -1)

ggplot(data.frame(x, y), aes(x = x, y = y)) + 
  geom_col(width = 0, colour = "black")
```

![](https://i.imgur.com/6o3vmJi.png)

<sup>Created on 2019-11-18 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by clauswilke** [comment]
We could implement a `geom_needle()` that works just like `geom_col()` but uses line segments instead of rectangles for drawing. The use of `geom_col(width = 0)` may have unintended consequences, since it draws two lines (one up, one down) per column. Also, it doesn't apply the alpha setting to the lines.

**Comment by ggrothendieck** [comment]
Regarding the idea of using `geom_col(width = 0)` it seems that `lwd` does work with it so one has a range independent way of making it wider, if needed:

```
library(ggplot2)
x <- 1:6
y <- x * c(1, -1)

ggplot(data.frame(x, y), aes(x = x, y = y)) + 
  geom_col(width = 0, colour = "black", lwd = 3)
```

**Comment by yutannihilation** [comment]
> uses line segments instead of rectangles for drawing.

Agreed. I guess a naive implementation would be like this:

``` r
library(ggplot2)

x <- 1:6
y <- x * c(1, -1)

GeomNeedle <- ggproto("GeomNeedle", GeomBar,
  # derived from GeomLinerange
  default_aes = aes(colour = "black", size = 0.5, linetype = 1, alpha = NA),
  
  draw_panel = function(self, data, panel_params, coord, width = NULL, flipped_aes = FALSE) {
    GeomLinerange$draw_panel(data, panel_params, coord)
  }
)

geom_needle <- function(...) {
  l <- geom_col(...)
  l$geom <- GeomNeedle
  l
}

ggplot(data.frame(x, y), aes(x = x, y = y)) + 
  geom_needle(alpha = 0.5)
```

![](https://i.imgur.com/OSTt9uH.png)

<sup>Created on 2019-11-18 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

I think this is fine. What I was wondering is that if what `GeomBar`'s `setup_data()` does can be generalized as something like `StatDistanceFromZero` so that we can use `geom_linerange(stat = "distance_from_zero")` instead of implementing a new one...

https://github.com/tidyverse/ggplot2/blob/cb0eaa0e16063517e7c8f8453bb2a10641d2f0d1/R/geom-bar.r#L136-L146

**Comment by clauswilke** [comment]
@ggrothendieck FYI, ggplot2 uses `size` instead of `lwd`, so making the lines thicker does work. However, I think this is only a workaround, not a proper solution, if only due to the `alpha` issue I pointed out.

``` r
library(ggplot2)
x <- 1:6
y <- x * c(1, -1)

ggplot(data.frame(x, y), aes(x = x, y = y)) + 
  geom_col(width = 0, colour = "black", size = 3)
```

![](https://i.imgur.com/pv61w9N.png)

<sup>Created on 2019-11-18 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by thomasp85** [comment]
If we end up adding it (and I’m not convinced it is warranted) we should not implement it through a stat. As long as stats are not composable reserving the stat slot for something as simple as setting `ymin` to zero is needlessly limiting the use. Rather, it should just subclass `GeomLinerange` and set `ymin` in `setup_data()` A’s is done in `GeomArea` etc

**Comment by yutannihilation** [comment]
Thanks, makes sense.
