### ISSUE TITLE
enhancement request:  identity observations suppressed from `check_overlap = TRUE`

### ISSUE THREAD

**Issue by mlamias** [tidyverse/ggplot2#3633]
I would like to see an enhancement request to be able to identity those observations that are suppressed from having their labels printed when the `check_overlap = TRUE` option is provided on `geom_text.`  This would be useful so that the suppressed observations could be called by the `data` argument in the `geom_label_repel` option of the `ggrepel` package.  See the following post for a reproducible example of why this would be useful:

Thank you!

**Comment by thomasp85** [comment]
The checks_overlap functionality is implemented in grid and resolved at rendering time so it is not possible for ggplot2 to access this information
