### ISSUE TITLE
Aligning geoms with preserve = "single": appears not to work with several factors  

### ISSUE THREAD

**Issue by adrowe1** [tidyverse/ggplot2#3647]
Hi,

I discovered issue #2712 when looking for a solution to the misalignment of boxplots with overlaid points. While the solution shown works in the example, it does not seem to generalise to cases with a greater number of factors.

Ideally it would be possible to achieve the same thing with `position_jitterdodge()`, but I guess that is beyond the scope of this issue.

```r
library(ggplot2)

ggplot(mtcars, aes(factor(am), mpg, fill = factor(carb))) + 
  geom_boxplot(position = position_dodge2(0.75, preserve = 'single')) +
  geom_point(position = position_dodge(0.75, preserve = 'total'))
```

![image](https://user-images.githubusercontent.com/4489859/69873894-e5179880-12b9-11ea-9aa2-0a2b97ff8cfc.png)

**Comment by thomasp85** [comment]
@karawoo do you have any insight here?

**Comment by karawoo** [comment]
I think there are a couple of issues here that are recurring themes with dodging. One is that `position_dodge2()` doesn't work for point geoms at all, so every time you combine a box plot with points you have to combine completely different dodging algorithms, which is predictably error prone. The other is that layers don't know about the position of elements in other layers, so it's generally hard to align geoms across layers. It's been suggested in the past that maybe the solution would be a dodging aesthetic (this has come up in #3022 and #3988). Unfortunately I don't think there is an easy solution without a major refactor.

**Comment by thomasp85** [comment]
So, in your head this is not something we can aim to solve surgically (i.e. without a huge rewrite)..?

**Comment by karawoo** [comment]
Yeah I think that's right, unfortunately
