### ISSUE TITLE
Robust estimators for stat_ellipse()

### ISSUE THREAD

**Issue by privefl** [tidyverse/ggplot2#3650]
I would like to use more robust estimators for `stat_ellipse()` provided by function `robust::covRob()`.

Looking at the code https://github.com/tidyverse/ggplot2/blob/master/R/stat-ellipse.R, I think it would be easy to integrate these new features.
Are you interested in having this in the package? I could make a PR.

**Comment by hadley** [comment]
I think this is out of scope for ggplot2, but would be great in an extension package.
