### ISSUE TITLE
Wrong output in geom_bar when using position='stack' and scale_y_log10 together ?

### ISSUE THREAD

**Issue by now2014** [tidyverse/ggplot2#3671]
---

I got a wrong output in geom_bar when using position='stack' and scale_y_log10 together.

In the test code below,  the total value of y-axis for the two stacked bars should be **1.01e5** (1e3+1e5), **NOT** 1e8.  

```r
ggplot(data.frame(grp=c('A', 'B'),
                  x=c('x1', 'x1'),
                  y=c(1e3, 1e5))) +
  scale_y_log10() +
  geom_bar(aes(x=x, y=y, fill=grp), stat='identity', position='stack') +
  theme(text=element_text(size=18))
```

_**sessionInfo()**_
R version 3.5.1 (2018-07-02)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS  10.15

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods  
[7] base     

other attached packages:
[1] ggplot2_3.2.1

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.2       digest_0.6.20    withr_2.1.2     
 [4] assertthat_0.2.1 crayon_1.3.4     dplyr_0.8.3     
 [7] R6_2.4.0         grid_3.5.1       gtable_0.3.0    
[10] magrittr_1.5     scales_1.0.0     pillar_1.4.2    
[13] rlang_0.4.0      lazyeval_0.2.2   rstudioapi_0.7  
[16] tools_3.5.1      glue_1.3.1       purrr_0.3.2     
[19] munsell_0.5.0    yaml_2.2.0       compiler_3.5.1  
[22] pkgconfig_2.0.2  colorspace_1.4-1 tidyselect_0.2.5
[25] tibble_2.1.3

**Comment by yutannihilation** [comment]
The rendered version of the reprex:

``` r
library(ggplot2)

d <- data.frame(grp = c("A", "B"), x = c("x1", "x1"), y = c(1e3, 1e5))
p <- ggplot(d) +
  geom_col(aes(x = x, y = y, fill = grp), position = "stack") +
  theme(text = element_text(size = 18))

patchwork::wrap_plots(p, p + scale_y_log10())
```

![](https://i.imgur.com/c3fo4uv.png)

<sup>Created on 2019-12-18 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by thomasp85** [comment]
I don't think there are any way around this (without massive rewrite)... you are transforming at the scale level, which gets applied before position adjustment. one should use a coord transformation instead

**Comment by yutannihilation** [comment]
Agreed. I think this is at most a documentation issue.

**Comment by lambdamoses** [comment]
```
library(ggplot2)

d <- data.frame(grp = c("A", "B"), x = c("x1", "x1"), y = c(1e3, 1e5))
p <- ggplot(d) +
  geom_col(aes(x = x, y = y, fill = grp), position = "stack") +
  theme(text = element_text(size = 18))
p + coord_trans(y = "log10")
```

gives this:

```
Warning messages:
1: Transformation introduced infinite values in y-axis 
2: Transformation introduced infinite values in y-axis 
```

and an empty plot:

![image](https://user-images.githubusercontent.com/32186361/73588320-8cf94000-447c-11ea-925b-888c46cf2824.png)

That makes sense since the bar starts at 0, which is `-Inf` after log transformation.

**Comment by clauswilke** [comment]
I think this was addressed with #3769. Don't use transformations and stacked bars at the same time.

**Comment by ChristianRohde** [comment]
seriously? where is your statement "Don't use transformations and stacked bars at the same time." documented? I really try to read and understand the manuals in case things do not work out. But here I fail for quite some time and did not find any warning in scale_continuous or geom_bar. I also try to plot some geom_bar(position="stack", stat="identity") + scale_y_continuous(trans='log10') which results in a mess...

**Comment by teunbrand** [comment]
Adressed in a recent-ish PR, but not on CRAN version yet:

https://github.com/tidyverse/ggplot2/blob/c9e6304272a2c76af2c4146f8ce97afd0e537684/R/position-stack.r#L30-L34

**Comment by ChristianRohde** [comment]
@teunbrand Thank you so much. It was a relief to find out that I should stop to search for a "solution" and thinking I am just doing it wrong :-)

**Comment by twest820** [comment]
As an add on, I've hit this as well and locating this issue proved difficult—I, at least, didn't have luck in the docs or with several different queries. In the interests of increasing search discoverability, it looks to me like the recommendation for `coord_trans()` here also covers

- `geom_col()`
- `scale_x_log10()`, `scale_x_sqrt()`, and `scale_y_sqrt()`.
- Likely any nonlinear axis transform from scales, such as `transform_log()`, `transform_log10()`, `transform_pseudo_log()`, and so on.

FWIW, most of the ggplot materials I'm aware of (including [R for Data Science](https://r4ds.hadley.nz/)) teach use of `scale_{x, y}_<whatever>` rather than `coord_trans()`. Considering discussion above, that's maybe a little awkward.
