### ISSUE TITLE
scale_x_date fails if limits' minimum = NA (but not maximum = NA)

### ISSUE THREAD

**Issue by jokorn** [tidyverse/ggplot2#3675]
From the documentation for scale_x_date:

> A numeric vector of length two providing limits of the scale. Use NA to refer to the existing minimum or maximum

This works when using NA for setting the max limits of the x-axis but fails when I use NA when setting the min limits of the x-axis:

``` r
library(tibble)
library(lubridate)
#> 
#> Vedhæfter pakke: 'lubridate'
#> Det følgende objekt er maskeret fra 'package:base':
#> 
#>     date
library(ggplot2)
library(magrittr)

test_df <- tribble(
  ~date_start,   ~value,
  today() - 30,  1,
  today(),       30)

test_df %>% 
  ggplot(aes(x = date_start,
             y = value)) + 
  geom_point() + 
  scale_x_date(limits = c(ymd("2012-12-12"), NA))
```

![](https://i.imgur.com/2NwUr6j.png)

``` r

test_df %>% 
  ggplot(aes(x = date_start,
             y = value)) + 
  geom_point() + 
  scale_x_date(limits = c(NA, ymd("2021-12-12")))
#> Error: Invalid input: date_trans works with objects of class Date only
```

<sup>Created on 2019-12-17 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by clauswilke** [comment]
This happens because the leading `NA` in the `c()` statement confuses `c()` about the type of vector it should generate. You'll have to swap `c()` and `ymd()` to be successful.

``` r
library(lubridate)
#> 
#> Attaching package: 'lubridate'
#> The following object is masked from 'package:base':
#> 
#>     date

c(ymd("2012-12-12"), NA)
#> [1] "2012-12-12" NA
c(NA, ymd("2012-12-12"))
#> [1]    NA 15686
ymd(c(NA, "2012-12-12"))
#> [1] NA           "2012-12-12"
```

<sup>Created on 2019-12-17 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
