### ISSUE TITLE
Add default theme separately from currently active theme

### ISSUE THREAD

**Issue by clauswilke** [tidyverse/ggplot2#3677]
As discussed here:
https://github.com/hadley/ggplot2-book/issues/172#issuecomment-567048728

In the current code, the currently active theme set with `theme_set()` etc. acts as the fallback if some element is missing from the theme provided with the plot. This is fine, except in cases where an element is missing from the currently active theme, which may happen when extension packages have added their own elements. A solution can be to add a second-level true default that is not intended to be changed by the user but that extension package could add their own elements to.

This is easy to implement, we just need to figure out the API. Do we need a full second set of functions `theme_set()`, `theme_get()`, `theme_update()`, `theme_replace()`? Or should we just provide the equivalent to `theme_replace()`, e.g. `theme_default_replace()`, which gives extension package authors all they need but will be sufficiently obscure that most users may never see it?

**Comment by thomasp85** [comment]
Could it be something that marks it for use for extensions and not really user friendly? i.e. `register_theme_element()` or something?

**Comment by clauswilke** [comment]
@thomasp85 Sure. It would probably work like %+replace%, but the name you suggest works for me. (Though, should it be plural, `register_theme_elements()`, since we'll probably allow more than one?)

@hadley Could you chime in? Does my description of the issue make sense?

**Comment by clauswilke** [comment]
I've created a PR (#3678). Examples are shown there.
