### ISSUE TITLE
Lines with transparency not showing when margins are 0 (windows only!)

### ISSUE THREAD

**Issue by vankesteren** [tidyverse/ggplot2#3679]
### Problem description
Lines with transparency do not show when the right margin is 0. Changing the margins to a little over 0 fixes the problem and removing the transparency as well. This seems to happen only on windows (does not reproduce on Ubuntu or macOS).

__NB: I want the margins to be 0 because we are embedding these plots in an application.__

### Reprex
``` r
library(ggplot2)
df <- data.frame(
  time = rep(1:10, 100), 
  val  = rnorm(1000), 
  id   = rep(1:100, each = 10)
)
ggplot(df, aes(x = time, y = val, group = id)) + 
  geom_point() +
  geom_line(alpha = 0.1) +
  theme(plot.margin = margin())
```
![image](https://user-images.githubusercontent.com/11596858/71161746-3b894e80-224a-11ea-8a57-d02e61122340.png)

### How the plot should look
Changing the right margin to a little over 0 fixes this:
```r
ggplot(df, aes(x = time, y = val, group = id)) + 
  geom_point() +
  geom_line(alpha = 0.1) +
  theme(plot.margin = margin(0, .1, 0, 0))
```
![image](https://user-images.githubusercontent.com/11596858/71162086-d550fb80-224a-11ea-96e1-59da787dc8b9.png)

**Comment by thomasp85** [comment]
Can I gett you to test this with another device, eg `ragg::agg_png()`. The default windows device is horrible and most windows-only rendering problems are due to it (and we can’t do anything about it)

**Comment by yutannihilation** [comment]
In addition, if you are using RStudio, could you test with Rterm? I suspect this might be an issue of RStudio's Windows device.

https://github.com/rstudio/rstudio/issues/2196

**Comment by vankesteren** [comment]
@yutannihilation you are absolutely correct! this seems to be an RStudio issue. In `ragg::agg_png()` and Rterm the 0 margin works fine.

**Comment by yutannihilation** [comment]
Oh..., thanks for confirming quickly. Then, we can't do anything on ggplot2's side. Would you mind filing this on rstudio/rstudio? (though it seems the bug is unlikely to be fixed, guessing from the discussion on rstudio/rstudio#2196...)

**Comment by vankesteren** [comment]
I've left a comment there, but it's a minor issue that has an easy workaround, so I'll close this now.

**Comment by yutannihilation** [comment]
Ah, I missed your comment on the issue. Thanks!
