### ISSUE TITLE
PROJ.6 warning in test and example

### ISSUE THREAD

**Issue by yutannihilation** [tidyverse/ggplot2#3686]
I see this warning with PROJ 6.

```
──────────────────────────────────────────────────
test-geom-sf.R:162: warning: geom_sf_text() and geom_sf_label() draws correctly
GDAL Message 1: +init=epsg:XXXX syntax is deprecated. It might return a CRS with a non-EPSG compliant axis order.
──────────────────────────────────────────────────
```

c.f. https://proj.org/development/migration.html#backward-incompatibilities

**Comment by clauswilke** [comment]
I suspect it would be sufficient to replace this line:
https://github.com/tidyverse/ggplot2/blob/e6cbcc1b52d3627e21922d2ee297ce3900ac096f/tests/testthat/test-geom-sf.R#L162
with the following:
nc_3857 <- sf::st_transform(nc, 3857)

**Comment by yutannihilation** [comment]
Thanks, confirmed.
