### ISSUE TITLE
Warn on `stat()` and `..var..`-notation?

### ISSUE THREAD

**Issue by yutannihilation** [tidyverse/ggplot2#3693]
After #3534, now we have 3 different ways to access the calculated variables:

* `after_stat(var)`
* `stat(var)`
* `..var..`

Though it seems very difficult to remove other syntax than `after_stat()`, I think we should promote the most proper one a bit more eagerly to avoid confusion. Can we warn on the usage of `stat()` and `..var..`-notation?

**Comment by thomasp85** [comment]
I think we should (promote it more aggressively), but I also think instantly deprecating the other flavours upon release is a bit too agressive. It will be mentioned in the release post, and all docs have been updated to use it (and `stat()` has been removed from the doc)

I think we should begin warning sometime after this release

**Comment by yutannihilation** [comment]
Thanks, fair enough. But, I'm a bit pessimistic about the impact of docs as I see many people even don't know the existence of `stat()` after 1.5 years passed since the release (version 3.0.0)...

Anyway, I agree with you it's not the time to add warnings in the upcoming release. Let's wait for a while.
