### ISSUE TITLE
Inconsistent geom_errorbar and geom_errorbarh warnings

### ISSUE THREAD

**Issue by Ilia-Kosenkov** [tidyverse/ggplot2#3696]
When plotting the vertical and horizontal errorbars separately, `geom_errorbarh` produces an additional warning `Ignoring unknown aesthetics: x` when both `x` and `y` aesthetics are passed.
At the same time, `geom_errorbar` accepting `x` and `y` does not generate respective `y`-aesthetic warning.
I believe, due to similar nature of these functions, either both should produce warnings, or none.
``` r
library(ggplot2)
data <- data.frame(x = 0, y = 0, err = 1)
p <- ggplot() +
    geom_errorbar(
        aes(x = x, y = y, ymin = y - err, ymax = y + err),
        data = data,
        inherit.aes = FALSE,
        width = 0.1) +
    geom_errorbarh(
        aes(x = x, y = y, xmin = x - err, xmax = x + err),
        data = data,
        inherit.aes = FALSE,
        height = 0.1)
#> Warning: Ignoring unknown aesthetics: x

print(packageVersion("ggplot2"))
#> [1] '3.2.1.9000'
print(packageDescription("ggplot2")$RemoteSha)
#> [1] "9fdf452d34be3986c778c9f4306ce96c7c14af8e"
print(p)
```

![](https://i.imgur.com/mrMHsEB.png)

<sup>Created on 2020-01-07 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by thomasp85** [comment]
geom_errorbarh will be soft deprecated from the next release as it has been superseded by the bidirectional geom implementation. We are unlikely to change anything in geom_errorbarh for this reason
