### ISSUE TITLE
Reversed letter order in axis text (Hebrew)

### ISSUE THREAD

**Issue by isteves** [tidyverse/ggplot2#3699]
I am seeing Hebrew (right-to-left / RTL) text getting reversed in the axes label. I _suspect_ it is related to the MacOS somehow because I was able to reproduce the problem on several co-workers' Macs, but the results don't match [this StackOverflow post](https://stackoverflow.com/questions/53915070/change-axis-text-direction-to-right-to-left) (on PC I believe) or the plot outputs in RStudio Cloud. I also tried older versions of ggplot2 (3.0.0, 2.2.0), which produce the same result.

I also found [this StackOverflow post](https://stackoverflow.com/questions/53802593/ggplot-with-hebrew-labels) in which the author only experiences letter reversal in Shiny.

``` r
library(ggplot2)
library(tibble)

example1 <- tribble(
  ~item,
  "האם יורד גשם?"
)

ggplot(example1, aes(item)) + 
  geom_bar() +
  theme(axis.text.x = element_text(size = 25))
```

![](https://i.imgur.com/l4UAFuC.png)

<sup>Created on 2020-01-07 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

Let me know if there's something else I should try on my end!

**Comment by clauswilke** [comment]
We're using grid functions to draw text, so you should investigate at that level. Is the example below correct or incorrect? In any case, it's not something to be fixed in the ggplot2 code.

``` r
library(grid)

grid.newpage()
grid.text("האם יורד גשם?")
```

![](https://i.imgur.com/fuBNH9Q.png)

<sup>Created on 2020-01-07 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by thomasp85** [comment]
This is almost 100% certainly a device "issue". It is up to the graphic device to decide how to lay out text. Most only support left-to-right text shaping, while some may support correct right-to-left shaping for some scripts. This will also explain the system-specificity as the default device varies between systems.

There is not much to do on either ggplot2 or grid's end

**Comment by isteves** [comment]
Ok, bummer, but thank you both for your responses!!  @clauswilke your reprex produced the reversed result.  I'll see if I can figure anything out on the device end.  Closing this issue since it seems like the problems are elsewhere.
