### ISSUE TITLE
Codecov broken?

### ISSUE THREAD

**Issue by yutannihilation** [tidyverse/ggplot2#3702]
It seems the commits in this 3 weeks keep failing to execute `covr::codecov()`; The last commit appears on https://codecov.io/gh/tidyverse/ggplot2/commits is https://github.com/tidyverse/ggplot2/commit/ee3cf495ea0c5ee84aa129e30173d8845acdb4fe, and the next is this one:

Move error signalling to rlang::abort() (https://github.com/tidyverse/ggplot2/commit/660aad2db2b3495ae0d8040915a40d247133ffc0)

I don't know what's happening, but something seems wrong...

```
Error: Failure in `/tmp/RtmpETm8ET/R_LIBS3d5b9a93f8b/ggplot2/ggplot2-tests/testthat.Rout.fail`
ot2.rdb:2:1: unexpected input
1: 
2: 
   ^
Backtrace:
 1. base::vapply(...)
 2. ggplot2:::FUN(X[[i]], ...)
 4. base::parse(f, keep.source = TRUE)
── 2. Error: do not use warning() (@test-conditions.R#19)  ─────────────────────
../../R/ggplot2.rdb:2:1: unexpected input
1: 
2: 
   ^
Backtrace:
 1. base::vapply(...)
 2. ggplot2:::FUN(X[[i]], ...)
 4. base::parse(f, keep.source = TRUE)
══ testthat results  ═══════════════════════════════════════════════════════════
[ OK: 1433 | SKIPPED: 218 | WARNINGS: 0 | FAILED: 2 ]
1. Error: do not use stop() (@test-conditions.R#14) 
2. Error: do not use warning() (@test-conditions.R#19) 
Error: testthat unit tests failed
Execution halted
Execution halted
```
(https://travis-ci.org/tidyverse/ggplot2/jobs/634113868#L1288)

**Comment by thomasp85** [comment]
Hmm... appears to be some encoding issue. I’ll look into it

**Comment by yutannihilation** [comment]
https://github.com/tidyverse/dplyr/issues/4686 might be related (I don't fully understand, but using `abort()` prints some multibyte characters?), but the difference is that the dev version of covr doesn't work as well...

**Comment by yutannihilation** [comment]
I think I've figured out the problem. The error occurs when `get_n_stop()` and `get_n_warning()` try to parse a non-R-script file `ggplot2.rdb`, which seems created by covr.
