### ISSUE TITLE
Should level from stat_contour() be numeric

### ISSUE THREAD

**Issue by thomasp85** [tidyverse/ggplot2#3706]
Currently, the level information calculated by stat_contour is passed along as a numeric. This makes intuitive sense, but from a user perspective it results in a legend with tick marks that do not match the different levels (since it is treated as a continuous variable)

I wonder if we should change that? `level` from stat_contour_filled()` is already a factor...

cc @clauswilke

**Comment by thomasp85** [comment]
I guess the user can always just do `colour = after_stat(factor(level))` manually if they wish...

**Comment by clauswilke** [comment]
I think `level` from `stat_contour()` and from `stat_contour_filled()` should be the same. Otherwise it's too confusing. What type of data is it in the current ggplot2 release?

**Comment by thomasp85** [comment]
Pretty sure that it is numeric like it is now

**Comment by thomasp85** [comment]
Also, they cannot be the same as it is a range for filled, and a single value for lines. The `(<lower>, <upper>]` notation will not make sense for the lines

**Comment by clauswilke** [comment]
I see. And for `stat_contour_filled()` it's a factor because it represents numeric ranges, not just values, correct? Maybe then we should just leave things as they currently are. Your call.

**Comment by thomasp85** [comment]
I think I’ll leave it as is. It is relatively more cumbersome to turn a factor into a numeric than vice versa
