### ISSUE TITLE
Examples fail with the new version of farver

### ISSUE THREAD

**Issue by yutannihilation** [tidyverse/ggplot2#3712]
My recent commit (https://github.com/tidyverse/ggplot2/commit/320cf274f3492654f70691fbd15ac324c5708027) failed on v3.3.0-rc branch, but the failure doesn't seem related to the change. This is probably due to the recent update of farver on CRAN.

I guess the fix would be very simple as replacing `"NA"` with `NA`, but I'm afraid the CRAN check will fail as well if this example is not skipped (I don't remember if the CRAN CI installs suggested dependencies). If so, we might need to do a patch release?

```
* checking examples ... ERROR
Running examples in â€˜ggplot2-Ex.Râ€™ failed
The error most likely occurred in:

> base::assign(".ptime", proc.time(), pos = "CheckExEnv")
> ### Name: annotation_map
> ### Title: Annotation: a maps
> ### Aliases: annotation_map
> 
> ### ** Examples
> 
> if (require("maps")) {
+ usamap <- map_data("state")
+ 
+ seal.sub <- subset(seals, long > -130 & lat < 45 & lat > 40)
+ ggplot(seal.sub, aes(x = long, y = lat)) +
+   annotation_map(usamap, fill = "NA", colour = "grey50") +
+   geom_segment(aes(xend = long + delta_long, yend = lat + delta_lat))
+ }
Loading required package: maps
Error: Unknown colour name: NA
Execution halted
** found \donttest examples: check also with --run-donttest
* checking for unstated dependencies in â€˜testsâ€™ ... OK
* checking tests ...
  Running â€˜testthat.Râ€™ [56s/56s]
 OK
* checking for unstated dependencies in vignettes ... OK
* checking package vignettes in â€˜inst/docâ€™ ... OK
* checking re-building of vignette outputs ... OK
* checking PDF version of manual ... OK
* checking for detritus in the temp directory ... OK
* DONE

Status: 1 ERROR, 1 NOTE
See
  â€˜/home/travis/build/tidyverse/ggplot2/ggplot2.Rcheck/00check.logâ€™
for details.
```
(https://api.travis-ci.org/v3/job/634672782/log.txt)

**Comment by QuLogic** [comment]
The [automated rebuild](https://koschei.fedoraproject.org/build/7560558) in Fedora also picked this up. I tested locally and it's definitely `farver` 2.0.1 -> 2.0.2 that causes it. The news mentions:

* `decode_colour()` now allows you to specify how `NA` should get interpreted

which may be related.

**Comment by yutannihilation** [comment]
Ah, thanks for the information, but this is already fixed by #3713!

**Comment by yutannihilation** [comment]
@thomasp85 
Let me confirm. The CRAN check is now broken with this error. Is it that CRAN is tolerant for this and we don't need to prepare a patch release?

https://cran.r-project.org/web/checks/check_results_ggplot2.html

**Comment by thomasp85** [comment]
I think it would be easier to prepare a patch release of farver that treats `"NA"` as `NA`... But it was def an error in ggplot2's example code that surfaced...

Haven't heard from CRAN about it. I hope they will be lenient as we are already in the release process

**Comment by yutannihilation** [comment]
I see. I believe in CRAN's leniency :)
