### ISSUE TITLE
Extend the plot range of geom_density() nicely

### ISSUE THREAD

**Issue by yutannihilation** [tidyverse/ggplot2#3716]
(See https://github.com/tidyverse/ggplot2/pull/3708#issuecomment-572472931)

Compared to the base R's density plot, `geom_density()` draws in a narrower range. As a result, the line doesn't touch the X-axis. Though it needs a lot of care to extrapolate the data correctly, it's nice if `geom_density()` can draw the bottom right one below.

``` r
plot(density(diamonds$carat, adjust = 5))
```

![](https://i.imgur.com/esNW094.png)

``` r
p <- ggplot(diamonds, aes(carat)) +
  geom_density(adjust = 5)

patchwork::wrap_plots(
  p + ggtitle("(default)"),
  p + ggtitle("(expanded)") + expand_limits(x = -0.5)
)
```

![](https://i.imgur.com/aaQC5t3.png)

**Comment by teunbrand** [comment]
@yutannihilation Do you feel strongly that this should be a setting in `geom_density()`? I think expanding the limits is an adequate solution to this problem, or am I missing something?

**Comment by yutannihilation** [comment]
Hmm, thanks for pinging. Now I don't have a strong opinion. The problem I worried was simply that a different behavior than base R might be confusing to users. So, in my opinion, "hey, you can do the same thing as base R if you know how to do it!" is not the solution.

However, as I haven't seen such a complain, probably I was wrong. I'm fine to close this issue.

**Comment by teunbrand** [comment]
In the development version of ggplot2 the `bounds` argument can also contribute in expanding the range (probably as side-effect of #5642). This is just to say that there is some extra tooling we can use to achieve this.

``` r
devtools::load_all("~/packages/ggplot2/")
#> ℹ Loading ggplot2
ggplot(diamonds, aes(carat)) + geom_density(adjust = 5, bounds = c(-1, Inf))
```

![](https://i.imgur.com/IYPfIQU.png)

<sup>Created on 2024-12-05 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

I think this falls in line with https://github.com/tidyverse/ggplot2/pull/3708#issuecomment-572474394 'willful extrapolation' notion, so unless there is a strong opinion to the contrary, I'll lay this issue to rest for now.

**Comment by yutannihilation** [comment]
> the `bounds` argument can also contribute in expanding the range (probably as side-effect of [#5642](https://github.com/tidyverse/ggplot2/pull/5642)).

Oh, good to know. Thanks!

> I'll lay this issue to rest for now.

👍
