### ISSUE TITLE
No help page for `scale_color_discrete()`

### ISSUE THREAD

**Issue by behrman** [tidyverse/ggplot2#3723]
There is no help page for `scale_color_discrete()`, and it doesn't appear on [ggplot2.tidyverse.org](https://ggplot2.tidyverse.org/reference/index.html).

**Comment by yutannihilation** [comment]
I think this is intentional to hide `scale_colour_discrete()` as it's just an alias to `scale_colour_hue()`, until ggplot2 lets users choose the default other than `hue` (c.f. #2691).
