### ISSUE TITLE
Secondary axis doesn't show axis ticks or labels with coord_trans 

### ISSUE THREAD

**Issue by RS-eco** [tidyverse/ggplot2#3726]
I might be missing something, but I am still experiencing the same issue as #2072 & #2990, although I am using R 3.6.2 & ggplot2 v3.2.1.

The secondary axis ticks and labels do not show up when coord_trans is present, while the axis label ("name") parameter does still appear.

For example: 
```
ggplot(mtcars, aes(cyl, mpg)) + geom_point()  +
    scale_y_continuous(sec.axis = sec_axis(~.+10, name='mpg + 10')) +
    coord_trans()
```

**Comment by yutannihilation** [comment]
Please wait for the next release. The fix for #2990 (#3380) is not included in the current release.
