### ISSUE TITLE
coloring by numbers: release ggplot2 3.2.1 does not recognize color=1 as color="black"

### ISSUE THREAD

**Issue by faltinl** [tidyverse/ggplot2#3731]
Updating ggplot2 from v3.0.0 to v3.2.1 I encountered the problem within a previously working programme, that the grammar of specifying colors apparently has changed: the expression 

```
...+ geom_text(aes(x=x, y=y label="text"), color=1) +...
```

simply suppressed the text completely without error message. After changing the color attribute to `color="black"` the label reappeared again in black as before. A few (though not exhaustive) tests with other numbers showed the same behavior.

**Comment by thomasp85** [comment]
This was an unexpected regression due to scales beginning to use farver for colour handling. A new release of farver is being prepared that should solve your issue. You can install the development version with `devtools::install_github(“thomasp85/farver”)` which should fix your issue

**Comment by faltinl** [comment]
Tnx for prompt reply! Well, I have solved this problem by changing the color declaration as outlined above everywhere in my program, which is no problem once I had the error recognized - but recognizing it was the problem proper. Nevertheless, I appreciate that the issue will be fixed!
