### ISSUE TITLE
Random duplication of outlier points when plotting with qplot

### ISSUE THREAD

**Issue by redwoodmusic46** [tidyverse/ggplot2#3736]
Extreme values are sometimes being duplicated when I use the qplot command. Here's a reprex:

```{r}
library(readxl)
library(ggplot2)
x <- c("a","a","a","a","a","b","b","b","b","b","c","c","c","c","c")
y <- c(1,2,1,3,10,15,13,16,12,25,30,32,35,33,45)
qplot( x=x , y=y, geom=c("boxplot","jitter"))
```
![image](https://user-images.githubusercontent.com/53239611/72465623-817ff680-37a5-11ea-9884-856d49123f6b.png)

Thanks in advance for helping to solve this problem.

**Comment by clauswilke** [comment]
One dot comes from `geom_boxplot()`, and one from `geom_jitter()`. The correct approach is to disable the outlier in `geom_boxplot()`, but there's no good way to do this in the `qplot()` framework (you'll get a warning). In general, we now discourage use of `qplot()`, as its seemingly simpler approach in practice makes many things more complicated and confusing.

``` r
library(ggplot2)
x <- c("a","a","a","a","a","b","b","b","b","b","c","c","c","c","c")
y <- c(1,2,1,3,10,15,13,16,12,25,30,32,35,33,45)

# this works but is not recommended
qplot(x=x , y=y, geom=c("boxplot","jitter"), outlier.shape = NA)
#> Warning: Ignoring unknown parameters: outlier.shape
```

![](https://i.imgur.com/cnlqJgJ.png)

``` r

# do it this way
df <- data.frame(x, y)
ggplot(df, aes(x, y)) +
  geom_boxplot(outlier.shape = NA) +
  geom_jitter()
```

![](https://i.imgur.com/fkmHtOt.png)

<sup>Created on 2020-01-15 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by redwoodmusic46** [comment]
Thanks so much! That fixed it.
