### ISSUE TITLE
Conditional axis.text to change font size and font face creates unwanted margin

### ISSUE THREAD

**Issue by tjebo** [tidyverse/ggplot2#3739]
This issue was raised yesterday in [this Stackoverflow thread](https://stackoverflow.com/questions/59757585/conditional-change-of-axis-text-font-family-and-font-size-creates-unwanted-gap/59759697#59759697)

This happens not only when using `ifelse()`, but also when manually changing the fonts, e.g. with a named vector. 

In my reprex, I used `coord_flip`, because this was originally shown by the OP in SO, but the same applies without `coord_flip` (albeit not that obvious), and also with `axis.text.x`

The weird thing to me is that this indeed seems only to happen with font size and font family.
``` r
library(ggplot2)

ggplot(iris, aes(Species, Petal.Length)) + 
  theme(axis.text.y = element_text(family = ifelse(levels(iris$Species)=="setosa","sans","mono"))) +
  coord_flip()
```

![](https://i.imgur.com/VcpXRGB.png)

This also happens without `ifelse`
``` r
library(tidyverse)

ggplot(iris, aes(Species, Petal.Length)) + 
  theme(axis.text.y = element_text(size = c(setosa = 10, virginica = 20, versicolor = 20))) +
  coord_flip()
```

![](https://i.imgur.com/jmhDmRA.png)

Adding `margin` helps, but only with specified units:
``` r

ggplot(iris, aes(Species, Petal.Length)) + 
  theme(axis.text.y = element_text(family = ifelse(levels(iris$Species)=="setosa","sans","mono"),
                                   margin = margin(r = -2, l = 0.8, unit = 'in'))) +
  coord_flip()
```

![](https://i.imgur.com/F9tN6Gb.png)

<sup>Created on 2020-01-16 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by yutannihilation** [comment]
Vectorized input to `element_text()` is not officially supported. Though this is already fixed in the next release, I recommend you not to rely on the current behaviour. See #3492 for more details.

``` r
library(ggplot2)

ggplot(iris, aes(Species, Petal.Length)) + 
  theme(axis.text.y = element_text(family = ifelse(levels(iris$Species)=="setosa","sans","mono"))) +
  coord_flip()
#> Warning: Vectorized input to `element_text()` is not officially supported.
#> Results may be unexpected or may change in future versions of ggplot2.
```

![](https://i.imgur.com/hgRHppK.png)

<sup>Created on 2020-01-16 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
