### ISSUE TITLE
Unrecognised aesthetic text changes geom_violin grouping

### ISSUE THREAD

**Issue by THargreaves** [tidyverse/ggplot2#3749]
I'm not sure whether this is a bug or a feature but I thought I would point it out anyway. I wanted to create a Plotly graph using `ggplotly()` with custom tooltip text. The way to do this is to set the `text` aesthetic of the ggplot and then specify to use this as the tooltip content when calling `ggplotly()`. My initial approach to this gave the following error:

```
Warning in max(data$density) :
  no non-missing arguments to max; returning -Inf
Error in order(data[["y"]], decreasing = TRUE) : 
  argument 1 is not a vector
```

After some debugging, I realised that setting the `text` aesthetic for my plot (even though this is not recognised by `geom_violin()`) was affecting the `group` aesthetic. Since each value of `text` was unique, I was then trying to create a violin plot for each individual data point which is obviously impossible. Manually specifying the group fixed this but it seems like a strange thing to have to do. Below is a reprex to illustrate my point.

```r
library(dplyr)
library(ggplot2)
library(magrittr)
library(plotly)

example_data <- tibble(
  target = factor(rep(LETTERS[1:2], each = 4)),
  error = runif(8, -1, 1),
  model = factor(rep(c('Model 1', 'Model 2'), times = 4)),
  type = factor(rep(rep(c('Type 1', 'Type 2'), each = 2), times = 2))
)

p <- example_data %>%
  mutate(label = paste0(model, ' (', type, ')')) %>%
  ggplot(aes(x = target, y = error, text = label)) +  # only works if we add `group = target`
    geom_violin() +
    geom_jitter(width = 0.1) +
    coord_flip()
  
ggplotly(p, tooltip=c('text'))
```

Is this intended behaviour?

**Comment by thomasp85** [comment]
This is intentional, yes. If the group aesthetic is not given directly it is deduced from the interaction of all discrete aesthetics. This is the reason why you don’t have to specify grouping if you e.g provide a discrete fill aesthetic
