### ISSUE TITLE
minor_breaks in date/date_time scale

### ISSUE THREAD

**Issue by kohske** [tidyverse/ggplot2#375]
``` R
df <- data.frame(
  day30  = seq(Sys.Date(), length = 10, by = "5 day"),
  y = runif(10)
)

p <- ggplot(df, aes(day30, y)) + geom_line()
p + scale_x_date(breaks = "2 month", minor_breaks = "week")
```

incudes an error.

```
Error in Ops.Date((x - from[1]), diff(from)) : 
  / not defined for Date objects
```

Maybe this is because,
1. data are transformed into `numeric` by `scales:::from_date` in `date_trans`
2. `minor_breaks` are calculated on the original data space (i.e., `date`).
3. some arithmetic operation combines `numeric` and `date`.

Anyway it need to be reconsidered...

**Comment by ptoche** [comment]
Is the following expected behaviour? (scroll down to the last example, which fails)

        df <- data.frame(
            x_date  = seq(as.Date("1952-01-01"), as.Date("2013-12-01"), by = "1 month"),
            y = runif(12*62)
        )
        library('ggplot2')
        library('scales')
        p <- ggplot(df, aes(x_date, y)) + geom_point()

        # version 1: automatic selection of start/end 'major' breaks
        p + scale_x_date(labels = date_format("%Y"), 
                         breaks = "5 years", 
                         minor_breaks = "1 year")

        # version 2: manual selection of start/end 'major' breaks
        p + scale_x_date(labels = date_format("%Y"), 
                         breaks = seq(as.Date("1950-01-01"), 
                                      as.Date("2015-01-01"), 
                                      by = "5 years"),
                         minor_breaks = "1 year")

        # version 3: manual selection of start/end 'minor' breaks: FAIL
        p + scale_x_date(labels = date_format("%Y"), 
                         breaks = seq(as.Date("1950-01-01"), 
                                      as.Date("2015-01-01"), 
                                      by = "5 years"),
                         minor_breaks = seq(as.Date("1975-01-01"), 
                                      as.Date("1995-01-01"), 
                                      by = "1 year"))
        ## Error in Ops.Date((x - from[1]), diff(from)) : 
        ##  / not defined for "Date" objects

**Comment by hadley** [comment]
@ptoche please file a new issue. This was closed 3 years ago
