### ISSUE TITLE
Build on GitHub Actions

### ISSUE THREAD

**Issue by jimhester** [tidyverse/ggplot2#3760]
Enable [GitHub Actions](https://github.com/features/actions) for this project. You will need to install the development version of usethis (`remotes::install_dev("usethis")`. For more details see [GitHub Actions for R](https://github.com/r-lib/actions/tree/master/examples).

- [ ] run `usethis::use_github_actions_tidy()`
  - [ ] Add badges in your clipboard to [README.md](../blob/master/README.md)
    - If `README.Rmd` exists add badges to that instead and run `devtools::build_readme()`.
- [ ] look at existing [.travis.yml](../blob/master/.travis.yml) and see if there is extra logic that needs to be included.
  - If `.travis.yml` builds a pkgdown site 
    - [ ] run `usethis::use_github_action("pkgdown.yaml")`
    - [ ] ping @jimhester to add `DEPLOY_PAT` to the repository secrets. 
- [ ] look at existing [appveyor.yml](../blob/master/appveyor.yml) and see if there is extra logic from `.travis.yml` and `appveyor.yml` that needs to be included.
- [ ] modify [R-CMD-check.yaml](../blob/.github/workflows/R-CMD-check.yaml) with extra logic if needed.
- [ ] ping @jimhester to add codecov.io token `CODECOV_TOKEN` to the repository secrets.

**Comment by malcolmbarrett** [comment]
Still working on this one post dev day 😅😇
