### ISSUE TITLE
Utility function to strip plot_env to keep only items that are used

### ISSUE THREAD

**Issue by kendonB** [tidyverse/ggplot2#3765]
There is an ongoing problem of ggplot objects saving superfluous items when being written to disc as it saves its calling environment. See:

https://github.com/ropensci/drake/issues/882
https://stat.ethz.ch/pipermail/r-devel/2016-July/072925.html
https://github.com/tidyverse/ggplot2/issues/3619
https://github.com/traversc/qs/issues/31

This comment (https://github.com/tidyverse/ggplot2/issues/3619#issuecomment-552340703) suggests that there is nothing that can be done but surely something can be done.

My proposal is to create a utility function that will look through a ggplot function for dependencies then strip the superfluous items out of `plot_env`. Users (or the `drake`/`qs` authors) could run this immediately before saving a ggplot object. Perhaps ggplot could even overwrite `saveRDS` to make this automatic.

It would work something like this:

``` r
library(ggplot2)
save_size_rds <- function (object) {
  tf <- tempfile(fileext = ".rds")
  on.exit(unlink(tf))
  saveRDS(object, file = tf)
  file.size(tf)
}

normal_ggplot <- function(){
  junk <- rnorm(1e+06)
  input <- iris
  ggplot(input) + 
    geom_point(aes(x = Sepal.Width, y = Sepal.Length))
}

strip_junk_from_environment <- function(ggplot_object){
  # Code here to scan the ggplot call
  used_objects <- c("input")
  
  rm(list = setdiff(names(ggplot_object$plot_env), used_objects), 
     envir = ggplot_object$plot_env)
  ggplot_object
}

save_size_rds(normal_ggplot())
#> [1] 7709833

save_size_rds(strip_junk_from_environment(normal_ggplot()))
#> [1] 30763
```

<sup>Created on 2020-01-31 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by yutannihilation** [comment]
I understand your frustration, but I don't see a good reason that ggplot2 should and can have this feature.

> ggplot function for dependencies then strip the superfluous items out of `plot_env`

You might feel that ggplot2 can 100% recognize its dependencies, but I think it's not true. We can't know the dependencies' dependencies and how extension packages work. It's out of our control.

BTW, I'm curious how you handle R6 objects. Are there any tricks to avoid this problem?

**Comment by clauswilke** [comment]
> You might feel that ggplot2 can 100% recognize its dependencies, but I think it's not true. We can't know the dependencies' dependencies and how extension packages work. It's out of our control.

Considering that we're using closure, quosures, and non-standard evaluation all over the place, it's almost certainly impossible to reliably determine which parts of various environments can be discarded and which need to be retained. I think it's akin to Turing's halting problem, and the proof is similar. (I can just write a geom that depends on specifically the pieces of the environment that the junk remover removes.)

In general, I would say that having to rely on saved ggplot2 objects almost always indicates a structural problem in the analysis. Recreating the objects should be cheap, and if it is not then some data processing should be taken out of the plot build process and handled separately. And if this is absolutely not possible, then you can always extract the processed data via `layer_data()` and save that.
