### ISSUE TITLE
Change default lineheight 

### ISSUE THREAD

**Issue by hadley** [tidyverse/ggplot2#3766]
Since as @clauswilke points out, 0.9 is too small

**Comment by clauswilke** [comment]
Not sure. 0.9 actually looks Ok for `grid::textGrob()`. I don't know how exactly grid calculates line heights, but they seem rather large, and the 0.9 probably corrects for that. Arguably I should modify gridtext to better match the grid line heights, but again I don't know where they're coming from.

``` r
library(tidyverse)

p <- iris %>% 
  mutate(
    Species = glue::glue("{Species}\nIris")
  ) %>%
  ggplot(aes(Species, Sepal.Length)) + 
  geom_boxplot() +
  theme(axis.text.x = element_text(size = 11))

p
```

![](https://i.imgur.com/WpglrSq.png)

``` r
p + theme(axis.text.x = element_text(lineheight = 1))
```

![](https://i.imgur.com/lC8MhgX.png)

``` r
p + theme(axis.text.x = element_text(lineheight = 1.1))
```

![](https://i.imgur.com/l00kR6n.png)

<sup>Created on 2020-01-30 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by thomasp85** [comment]
line heights are actually used in the graphic engine, not in grid itself, and is interpreted as a multiplier on the pointsize for text.

The graphic engine splits up text strings into lines and pass them in one by one into the graphic device, and it is thus impossible to circumvent this.

**Comment by clauswilke** [comment]
Thomas, we're talking about the `lineheight` parameter in the themes:
https://github.com/tidyverse/ggplot2/blob/0cbb078d330cb1b1adff69af8e51bb9045e4ef0d/R/theme-defaults.r#L128
It is 0.9 by default, which seems strange. 1.0 would be a more natural choice.

If the graphic engine uses point size as line height then it's doing the typographically correct thing, and the gridtext results should match it. I'll look into this later today.

**Comment by thomasp85** [comment]
yeah, I know... I just wanted to point out that grid itself didn't do any interpretation of this parameter but leaves it to the graphic engine.

**Comment by clauswilke** [comment]
So here's a reprex. As far as I can tell, the line spacing produced by the graphics engine is slightly too large, and the factor of 0.9 corrects for that.

``` r
library(grid)

g1 <- textGrob(
  "hello\nworld",
  x = 0.2, y = unit(0.5, "npc"),
  hjust = 0, vjust = 0,
  gp = gpar(fontsize = 12, lineheight = 1)
)
g2 <- textGrob(
  c("hello", "world"),
  x = 0.2, y = unit(c(0.5, 0.5), "npc") + unit(c(12, 0), "pt"),
  hjust = 0, vjust = 0,
  gp = gpar(fontsize = 12, lineheight = 1, col = "blue")
)

grid.newpage()
grid.draw(g1)
grid.draw(g2)
```

![](https://i.imgur.com/vn6cRHK.png)

``` r

g1 <- textGrob(
  "hello\nworld",
  x = 0.2, y = unit(0.5, "npc"),
  hjust = 0, vjust = 0,
  gp = gpar(fontsize = 12, lineheight = 0.9)
)


grid.newpage()
grid.draw(g1)
grid.draw(g2)
```

![](https://i.imgur.com/qG8M3wC.png)

<sup>Created on 2020-02-03 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by thomasp85** [comment]
Closing this as it appears we are doing what we can. The default of the graphic engine is likely not going to change
