### ISSUE TITLE
fill argument does not reference the current color palette

### ISSUE THREAD

**Issue by gordocabron** [tidyverse/ggplot2#3793]
In my example below `fill` and `color` reference different color palettes. I guess this is unwanted behaviour. Might also be related to #3743.

```r
library(ggplot2)
library(RColorBrewer)

mypalette <- brewer.pal(7,"Greens")
palette(mypalette)

data.frame(x = 1:10) %>% 
  ggplot(aes(x = x)) +
  geom_bar(fill = 1:10, color = 1:10, size = 2)
```

**Comment by thomasp85** [comment]
There's a couple of things here: First, you should not pass multiple values when setting aesthetics (as opposed to mapping them). Second, please use colour names instead of integers to reference colours. Using integers and custom palettes is not supported in ggplot2

**Comment by thomasp85** [comment]
that being said, despite it being unsupported practice, fill and colour should probably behave equivalently

**Comment by yutannihilation** [comment]
I see `colour` is consistent with `fill` if it's non-polygon geom. Maybe this is just a behaviour of grid? ggplot2 seems to do nothing but to pass the original value as they are. I think this is out of our control.

``` r
library(ggplot2)
library(RColorBrewer)

mypalette <- brewer.pal(7,"Greens")
palette(mypalette)

d <- data.frame(x = 1:10) 

p <- ggplot(d, aes(x, x)) +
  geom_col(colour = 1:10, fill = 1:10, size = 2) +
  geom_point(colour = 1:10, size = 4)

p
```

![](https://i.imgur.com/c84MBtb.png)

``` r
head(layer_data(p, 1), 3)
#>   x y PANEL group flipped_aes ymin ymax xmin xmax colour fill size linetype
#> 1 1 1     1    -1       FALSE    0    1 0.55 1.45      1    1    2        1
#> 2 2 2     1    -1       FALSE    0    2 1.55 2.45      2    2    2        1
#> 3 3 3     1    -1       FALSE    0    3 2.55 3.45      3    3    2        1
#>   alpha
#> 1    NA
#> 2    NA
#> 3    NA
head(layer_data(p, 2), 3)
#>   x y PANEL group shape colour size fill alpha stroke
#> 1 1 1     1    -1    19      1    4   NA    NA    0.5
#> 2 2 2     1    -1    19      2    4   NA    NA    0.5
#> 3 3 3     1    -1    19      3    4   NA    NA    0.5
```

<sup>Created on 2020-02-04 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by thomasp85** [comment]
No, this is because fill gets pulled through `alpha()` before passing it into `gpar()`. This means it goes through farver which only knows about the default palette (for performance reasons).

In any way, using colours in this way is a ggplot2 anti-pattern that should be avoided

**Comment by yutannihilation** [comment]
Ah, thanks. I see what's happening now... Sorry for the noise.

I totally agree this is anti-pattern.

**Comment by gordocabron** [comment]
Ok, thanks for looking into this. I didn't know that this is anti-pattern and will change my apps accordingly. It used to work and was broken recently.

I will close this ticket.

**Comment by thomasp85** [comment]
To put you on the right track: This is kinda the idiomatic way of creating your plot

``` r
library(ggplot2)
library(RColorBrewer)

mypalette <- brewer.pal(7,"Greens")

d <- data.frame(x = 1:10, 
                col = rep_len(mypalette, 10))

p <- ggplot(d, aes(x, x)) +
  geom_col(aes(colour = col, fill = col), size = 2) +
  geom_point(aes(colour = col), size = 4) + 
  scale_colour_identity() +
  scale_fill_identity()

p
```

![](https://i.imgur.com/GtHJptm.png)

<sup>Created on 2020-02-04 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by thomasp85** [comment]
or, use the brewer palettes directly with `scale_colour_brewer()` etc
