### ISSUE TITLE
Warning with development version of tibble

### ISSUE THREAD

**Issue by DavisVaughan** [tidyverse/ggplot2#3795]
New warning that pops up with the development version of tibble (it seems to be an OOB warning of some kind). Not sure if this is tibble or ggplot2 that is at fault. It seems to be related to the faceting part of the code, and what happens when you can't find facet variables in the data (we can't find `f` in the data frame generated by `geom_abline()` which will only have columns for `slope` and `intercept`).

Found in:
https://github.com/tidymodels/yardstick/pull/138

tibble function throwing the warning:
https://github.com/tidyverse/tibble/blob/5cc3c3205eed17bfcd7cf8358c6138ffa75cca72/R/subsetting.R#L302

``` r
library(ggplot2)
library(tibble) # devtools::install_github("tidyverse/tibble")

df <- tibble(f = c("x", "y"), x = 1:2, y = 1:2)

ggplot(df, aes(x = x, y = y)) +
  geom_abline() +
  facet_wrap(~f)
#> Warning: Row indexes must be between 0 and the number of rows (0). Use `NA` as row index to obtain a row full of `NA` values.
#> This warning is displayed once per session.
```

![](https://i.imgur.com/9Xw0C4Y.png)

<sup>Created on 2020-02-04 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9000)</sup>

My rudimentary debugging skills with ggplot2 can provide this traceback. The `facet_vals` in traceback line 13 is a 0 row 0 column tibble (coming from `eval_facets()`) when `facet_vals[data_rep, , drop = FALSE]` is run. `data_rep` is `c(1, 1)`. So we end up running:

``` r
library(tibble)
x <- tibble()
x[c(1, 1), , drop = FALSE]
#> Warning: Row indexes must be between 0 and the number of rows (0). Use `NA` as row index to obtain a row full of `NA` values.
#> This warning is displayed once per session.
#> # A tibble: 2 x 0
```

```r
UseMethod("print"))(x)
 2: print.ggplot(x)
 3: ggplot_build(x)
 4: ggplot_build.ggplot(x)
 5: layout$setup(data, plot$data, plot$plot_env)
 6: f(..., self = self)
 7: lapply(data[-1], self$facet$map_data, layout = self$layout, params = self$facet_params)
 8: FUN(X[[i]], ...)
 9: f(...)
10: unrowname(cbind(facet_vals[data_rep, , drop = FALSE], to_add[facet_rep, , drop = FALSE]))
11: is.data.frame(x)
12: cbind(facet_vals[data_rep, , drop = FALSE], to_add[facet_rep, , drop = FALSE])
13: facet_vals[data_rep, , drop = FALSE]
14: `[.tbl_df`(facet_vals, data_rep, , drop = FALSE)
15: tbl_subset_row(xo, i = i)
16: vectbl_as_row_index(i, x)
17: fix_oob(i, nr)
18: fix_oob_positive(i, n, warn)
19: warn_oob(oob, n)
20: warn_deprecated(paste0("Row indexes must be between 0 and the number of rows (", n, "). ", "Use `NA` as row index to obta
21: signal(msg = msg)
22: warning(warningCondition(msg, old = old, new = new, package = package, class = "deprecatedWarning"))
23: withRestarts({
    .Internal(.signalCondition(cond, message, call))
    .Internal(.dfltWarn(message, call))
}, muffleWarn
24: withOneRestart(expr, restarts[[1]])
25: doWithOneRestart(return(expr), restart)
```

**Comment by clauswilke** [comment]
Could you check this against the 3.3.0 release candidate and see if the problem is still present?
https://github.com/tidyverse/ggplot2/tree/v3.3.0-rc

**Comment by DavisVaughan** [comment]
Seems to work! My guess is that this commit fixes it https://github.com/tidyverse/ggplot2/commit/5e6b1e5daa1599661bf5841353a067e9eee88161

`eval_facets()` returns the following, rather than the 0 row 0 col tibble from before

```r
Browse[2]> new_data_frame(tibble::as_tibble(vars))
  f
1 x
2 y
```
