### ISSUE TITLE
Line-shaded polygons in ggplot2

### ISSUE THREAD

**Issue by RS-eco** [tidyverse/ggplot2#3796]
The polygon function of the graphics package allows to plot line-shaded polygons:

```r
plot(c(1, 9), 1:2, type = "n")
polygon(1:9, c(2,1,2,1,NA,2,1,2,1), density = c(10, 20), angle = c(-45, 45))
```

Would it be possible to implement this in the geom_polygon() function, or is there already a way to do that using ggplot2?

**Comment by thomasp85** [comment]
There is no direct equivalent since this is a feature of the base graphic system not implemented in grid (the underlying system powering ggplot2). There are currently no plans to add this but future changes to grid may change that
