### ISSUE TITLE
Direction argument in scale_color_discrete breaking colors

### ISSUE THREAD

**Issue by tjebo** [tidyverse/ggplot2#3797]
[Related thread on Stackoverflow](https://stackoverflow.com/questions/60062827/change-direction-of-fill-color-aesthetic-of-default-palette)

I tried to add `direction = -1` in `scale_fill/scale_color` ("`_discrete`" and "`_hue`"), and was stunned by the weird result below.

As SO user user12728748 suggests, this may be a problem with `scales::hue_pal`?

``` r
library(ggplot2)

ggplot(iris, aes(x = Sepal.Length, y = Sepal.Width, color = Species)) +
  geom_point() + 
  scale_color_discrete(direction = -1)
```

![](https://i.imgur.com/SN33owj.png)

<sup>Created on 2020-02-05 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

<details>

<summary>Session info</summary>

``` r
devtools::session_info()
#> ─ Session info          
#>  version  R version 3.6.2 (2019-12-12)
#>  ggplot2     * 3.2.1   2019-08-10 [1] CRAN (R 3.6.0)
#>  scales        1.1.0   2019-11-18 [1] CRAN (R 3.6.0)
```

**Comment by dpseidel** [comment]
This is an issue with changes made to hue_pal in scales 1.1.0 and reported yesterday at https://github.com/r-lib/scales/issues/252.

**Comment by dpseidel** [comment]
Looks like this relates to the switch to using `farver::encode_colour` in `scales::hue_pal` in scales 1.1.0. Regardless this bug lies outside ggplot2, so I am closing the thread here. Discussion will continue on https://github.com/r-lib/scales/issues/252
