### ISSUE TITLE
Add fontsize aesthetic to geom_text

### ISSUE THREAD

**Issue by thomasp85** [tidyverse/ggplot2#3799]
A common source of confusion is the scaling of text in layers and how to match sizing between that and theme element text. This is mainly due to `size` being interpreted as `cm` to make it in line with the sizing of other geoms.

Would it make sense to introduce an alternative aesthetic to geom_text that was interpreted as 'pts' instead which, if given, would take precedence?

Maybe it shouldn't even be an aesthetic, but a switch, I dunno... But this comes up often enough that we should discuss how to address it...

**Comment by teunbrand** [comment]
I think having a switch is more lightweight than a separate aesthetic. Should the only option be centimeters/points or should also other grid units be supported? `size_metric = "cm"/"pts"` might be a good name for the switch.
