### ISSUE TITLE
circles change to diamond-like shapes when geom_point(size=2)

### ISSUE THREAD

**Issue by samd1993** [tidyverse/ggplot2#3805]
Hi,

I have a weird issue where whenever I set geom_point(size=2) I get a weird circle shape that almost looks like a diamond. When I set it to about 4 or higher it starts to look more like a circle. I've attached two images to compare. Is this normal?
Also hate to throw in another question but is there a reason the resolution looks crummy in Rstudio?
Thanks!

```r
``` r
library(ggplot2)
library(gridExtra)
car1=ggplot(cars,aes(x=speed,y=dist))
c1=car1+geom_point(size=2)

car2=ggplot(cars,aes(x=speed,y=dist))
c2=car2+geom_point(size=4)

grid.arrange(c1,c2)
```

![](https://i.imgur.com/SBG6ttx.png)

<sup>Created on 2020-02-06 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

```
![image](https://user-images.githubusercontent.com/22188081/73999934-29a75c00-491b-11ea-8f4d-56b411c84fc7.png)

**Comment by yutannihilation** [comment]
> I get a weird circle shape that almost looks like a diamond.

> Also hate to throw in another question but is there a reason the resolution looks crummy in Rstudio?

Both are just a problem of resolution of graphic device (I guess you are using Windows, right?). You might find [ragg](https://ragg.r-lib.org/) package useful. For this kind of questions, please ask on https://community.rstudio.com, where you can get more helpful answers. Thanks!

``` r
library(ggplot2)
library(gridExtra)

car1=ggplot(cars,aes(x=speed,y=dist))
c1=car1+geom_point(size=2)

car2=ggplot(cars,aes(x=speed,y=dist))
c2=car2+geom_point(size=4)

grid.arrange(c1,c2)
```

![](https://i.imgur.com/g0D609S.png)

<sup>Created on 2020-02-07 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
