### ISSUE TITLE
Warning about binwidth given with geom_bar and stat = bin

### ISSUE THREAD

**Issue by mdlama** [tidyverse/ggplot2#3809]
I've posted this possible issue before at RStudio Community [here](https://community.rstudio.com/t/warning-about-binwidth-given-with-geom-bar-and-stat-bin/51095?u=mdlama) and was encouraged to post this as an issue as it might be a possible bug.  I will replicate my initial question here.

Based on the documentation, I can see that `binwidth` is deprecated as an argument for `geom_bar` with the default stat of count. However, my understanding is that `geom_bar` with `stat = bin` is essentially equivalent to `geom_histogram`. If so, then why is there a warning about using `binwidth` with `geom_bar` and `stat = bin`?

``` r
library(ggplot2)
ggplot(iris, aes(x = Sepal.Length)) +
    geom_bar(stat = "bin", binwidth = 0.1)
#> Warning: `geom_bar()` no longer has a `binwidth` parameter. Please use
#> `geom_histogram()` instead.
```

![](https://i.imgur.com/Xcs4baf.png)

<sup>Created on 2020-02-07 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by clauswilke** [comment]
The warning is there so people hopefully transition away from code that uses outdated patterns. Why would you want to use `geom_bar()` with `stat = "bin"` if you can use `geom_histogram()` instead?

**Comment by mdlama** [comment]
Good question.  I like that there is more than one way to create plots in ggplot2.  In particular, I feel like one of the powers of the grammar of graphics is the ability to use "primitives" (lines, points, bars, etc.) to construct plots.  As examples:

- `geom_freqpoly` is essentially a `geom_line` with `StatBin` (with `pad = TRUE`)
- `geom_smooth` is a `geom_line` with `StatSmooth` + a `geom_ribbon` with `StatSmooth`
- `geom_col` is a `geom_bar` with `StatIdentity`
- `geom_count` is a `geom_point` with `StatSum` (and aesthetic `size` set to `stat(n)`)
- `geom_histogram` is a `geom_bar` with `StatBin`
- `geom_boxplot` is a combination of `geom_crossbar` + `geom_linerange` + `geom_point`

I can see why these "non-primitive" geoms (`geom_freqpoly`, `geom_boxplot`, etc) would be useful, in particular to have well-known plot names that can be used and make things easier (and more readable!) for users.  I just really like the ability to construct them with primitive geoms as well. 

As for why I thought this might be a bug:  I can understand why `binwidth` would be deprecated as an argument to `geom_bar`, since that argument only really makes sense with `StatBin`, but the default stat is `StatCount`.  In fact, current functionality overrides the specified stat (including the default) to `StatBin` when `binwidth` is given as an argument to `geom_bar`.  The following reprex shows this:

``` r
library(ggplot2)
(ggobj <- ggplot(iris, aes(x = Sepal.Length)) +
  geom_bar(stat = "count", binwidth = 0.1))
#> Warning: `geom_bar()` no longer has a `binwidth` parameter. Please use
#> `geom_histogram()` instead.
```

![](https://i.imgur.com/v8142PZ.png)

``` r
ggobj$layers[[1]]
#> geom_bar: na.rm = FALSE, width = NULL
#> stat_bin: binwidth = 0.1, bins = NULL, na.rm = FALSE, pad = FALSE, width = NULL
#> position_stack
```

<sup>Created on 2020-02-08 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

So, for any other stat besides `StatBin`, giving that warning that `binwidth` isn't an argument anymore to `geom_bar` makes sense - but it _does_ make sense when `StatBin` is specified.

**Comment by yutannihilation** [comment]
This warning was added about 4 years ago by this commit: https://github.com/tidyverse/ggplot2/commit/39274b4c8045b76c2b75211eb9ce924dcf21fae6, before version 2.0.0, and it hasn't been changed so far.

On the other hand, `stat_bin()` got a argument `binwidth` as of version 3.0.0 by this PR: https://github.com/tidyverse/ggplot2/pull/1890. So, we might reconsider about the strategy of where to check if the parameters are valid (I feel `binwidth` should be rejected in `StatCount`).

**Comment by clauswilke** [comment]
If we remove the custom warning, then there'll be the standard warning about an unknown parameter (see example, with misspelling to trigger the warning). I think that's reasonable.

``` r
library(ggplot2)

ggplot(mtcars, aes(factor(gear))) +
  geom_bar(bnwidth = 0.1)
#> Warning: Ignoring unknown parameters: bnwidth
```

![](https://i.imgur.com/p0qtCJ7.png)

<sup>Created on 2020-02-11 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by yutannihilation** [comment]
Wow, simple enough. Sounds good to me.

**Comment by clauswilke** [comment]
Ok, here you go: #3819

I like that this PR consists entirely of deleted lines.
