### ISSUE TITLE
adding tracking/letter spacing to element_text?

### ISSUE THREAD

**Issue by Athanasiamo** [tidyverse/ggplot2#3812]
I was wondering if there was at all any possibility of adding tracking (letter spacing).

I find myself in the situation where I'd like to increase the space between letters, but I can't find anything that might control that in the graphics devices.  From looking at the elements, I think I understand that they are connected to base-R graphical functions, where I cannot find anything that would alter the letter-spacing in any way. I just thought I'd double check that I was not missing something.

![](https://www.indesignskills.com/wp-content/uploads/2017/11/track2.jpg)

**Comment by thomasp85** [comment]
This is not currently possible but I’m working on a shaping engine that does per-letter shaping and would allow this

**Comment by Athanasiamo** [comment]
great! That would be a very neat addition.
