### ISSUE TITLE
geom_polygon fill gets blank

### ISSUE THREAD

**Issue by artidata** [tidyverse/ggplot2#3821]
To be precised, when there are holes within the polygons, with transparency (alpha<1), and the plot is zoomed using coord_cartesian, the clipped polygons fill become blank.

```r
ids <- factor(c("1.1", "2.1", "1.2", "2.2", "1.3", "2.3"))

values <- data.frame(
  id = ids,
  value = c(3, 3.1, 3.1, 3.2, 3.15, 3.5)
)

positions <- data.frame(
  id = rep(ids, each = 4),
  x = c(2, 1, 1.1, 2.2, 1, 0, 0.3, 1.1, 2.2, 1.1, 1.2, 2.5, 1.1, 0.3,
        0.5, 1.2, 2.5, 1.2, 1.3, 2.7, 1.2, 0.5, 0.6, 1.3),
  y = c(-0.5, 0, 1, 0.5, 0, 0.5, 1.5, 1, 0.5, 1, 2.1, 1.7, 1, 1.5,
        2.2, 2.1, 1.7, 2.1, 3.2, 2.8, 2.1, 2.2, 3.3, 3.2)
)
datapoly <- merge(values, positions, by = c("id"))

holes <- do.call(rbind, lapply(split(datapoly, datapoly$id), function(df) {
  df$x <- df$x + 0.5 * (mean(df$x) - df$x)
  df$y <- df$y + 0.5 * (mean(df$y) - df$y)
  df
}))

datapoly$subid <- 1L
holes$subid <- 2L
datapoly <- rbind(datapoly, holes)
```
Without the clipping:
```r
(p <- ggplot(datapoly, aes(x = x, y = y)) +
geom_polygon(aes(fill = value, group = id, subgroup = subid),alpha=.5,color="black"))
```
![image](https://user-images.githubusercontent.com/20266094/74594935-d9e13700-5076-11ea-8f7e-afab5f618ea1.png)

When clipped:
```r
(p + coord_cartesian(xlim=c(0,1.5),ylim=c(0,3)))
```
![image](https://user-images.githubusercontent.com/20266094/74594977-3cd2ce00-5077-11ea-9600-bf1e7cfb9471.png)

I found that the polygons with no holes do not become blank:
![image](https://user-images.githubusercontent.com/20266094/74595032-c387ab00-5077-11ea-9b40-c37664daaa2e.png)

Also when alpha is set to 1 (no transparency) do not become blank:
![image](https://user-images.githubusercontent.com/20266094/74595047-ee71ff00-5077-11ea-8c06-c402493bdc17.png)

Any help will be greatly appreciated. :)

**Comment by thomasp85** [comment]
This is a known bug with the default windows device (which I assume you use). Use the devices from the ragg package to avoid this
