### ISSUE TITLE
annotation-logticks.r

### ISSUE THREAD

**Issue by mgood2** [tidyverse/ggplot2#3822]
Brief description of the problem
I am using a plot that has y-axis fliped.
My logticks are upside down. There is no option for reversing log ticks.

```r
plt + annotation_logticks(side="l") # maybe reverse = TRUE option would be good.
```

Thank you.

**Comment by clauswilke** [comment]
Please provide a reprex.

**Comment by teunbrand** [comment]
Might also be neat, at some point, to implement the `annotation_logticks` as an `guide_axis_logticks()` with the new extendible guide system in v3.3.

**Comment by clauswilke** [comment]
I'm closing this issue for lack of detail and reprex. Feel free to reopen with improved issue title and full demonstration of the problem.
