### ISSUE TITLE
Changing the blending formula for alphas

### ISSUE THREAD

**Issue by lrnv** [tidyverse/ggplot2#3823]
Hi, 

I want to plot a bunch of (weighted) rectangles using geom_rect and i decided to use the `alphas` as the weights, so see more weighted rectangles in darker colors. Since my rectangles sometimes overlap, i wanted the `alphas` values i passed in to **just add up** instead of using the blending formula, as described there : https://stackoverflow.com/questions/57394946/control-alpha-blending-opacity-of-n-overlapping-areas

Since re-working my data to insert propper weights seems far more complicated, i thought i'll just change the alpha blending formula into a ggplot2 fork to make it right. 

Could you point me out to the file where this alpha blending is done ? The formula should be something like what is described in https://en.wikipedia.org/wiki/Alpha_compositing#Alpha_blending

**Comment by thomasp85** [comment]
This is not something controlled by ggplot2 but implemented by the graphic devices. All of these uses multiplicative blending AFAIK which is also the “correct” blending. You’d have to implement something very custom to circumvent this
