### ISSUE TITLE
stat_summary_bin gives 1 bin more than specified.

### ISSUE THREAD

**Issue by JoFAM** [tidyverse/ggplot2#3824]
stat_summary_bin() consistently gives one more bin than specified in the function call

```r
ggplot(data=mtcars, aes(y=mpg,x=wt)) +
  stat_summary_bin(fun.y = "mean", geom = "point",
                   bins = 3)
```

This shows 4 points. If you change bins to 4, it'll show 5 points and so on.

**Comment by yutannihilation** [comment]
Maybe the same issue? At least, I feel this needs some better documentation

https://github.com/tidyverse/ggplot2/issues/1739#issuecomment-247318595

**Comment by JoFAM** [comment]
I highly doubt that floating point errors are a reason for a consistent off-by-one error. Especially since this is specific to that function and doesn't occur with `hist`, `cut`, ...

**Comment by thomasp85** [comment]
This is a bug in `bin2d_breaks` and basically boils down to how we choose binwidth from a range that is closed in both ends

**Comment by thomasp85** [comment]
we need to extend the range before we calculate the bin width but it is not obvious to me what the best approach is...

Or maybe we should just add a small padding to the last bin so it includes the last data points?

**Comment by JoFAM** [comment]
@thomasp85 thx for the pointer, didn't have time to dig deeper yet (the stack of function calls to weed through is massive to be honest...). fwiw, `cut` adds a small padding like this:

```
rx <- range(x)
dx <- diff(rx)
breaks <- seq.int(rx[1L], rx[2L], length.out = nb)
breaks[c(1L, nb)] <- c(rx[1L] - dx/1000, rx[2L] + dx/1000)
```
Judging from the code of `bin2d_breaks`, adding a similar approach is pretty trivial.

**Comment by yutannihilation** [comment]
Thanks, I didn't notice this is such a problem... Here's a rendered version of reprex from #1739

``` r
library(ggplot2)

x <- seq(0, 1, length = 1e4)
y <- x + rnorm(length(x))
dt <- data.frame(x, y)

# NOT OK
ggplot(dt, aes(x, y)) +
  geom_point(colour = "grey80") +
  stat_summary_bin(fun = mean, bins = 10, geom = "point", colour = "red")
```

![](https://i.imgur.com/4rxV0wJ.png)

<sup>Created on 2020-02-21 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by tjebo** [comment]
Possibly related ? 
https://stackoverflow.com/questions/61817440/follow-up-to-stat-contour-2d-bins-interpretation?noredirect=1#comment109344762_61817440
