### ISSUE TITLE
Incorrect labeling using tunneling

### ISSUE THREAD

**Issue by rjb5** [tidyverse/ggplot2#3830]
@lionel-
Original Question on Stackoverflow.  

SO link: https://stackoverflow.com/questions/60309482/reference-tunnel-variable-within-a-chain?noredirect=1#comment106697561_60309482

---

ggplot2 doesn't correctly label the x axis, value in the function. 

``` r
library(tidyverse)
# Variables to pass into function
params <-  setdiff(colnames(mtcars) ,"mpg") %>% head(2)

graph_by <- function(data, by, var, prefix = "avg") {
  data %>%
    group_by({{ by }}) %>%
    summarise(mean_value := mean({{ var }}, na.rm = TRUE)) %>%
    ggplot(aes(mean_value, {{ by }})) +
    geom_line() +
    geom_point() 
}

#labels should be cyl instead of .data[["cyl"]]
purrr::walk(params, ~ graph_by(mtcars, by = .data[[.x]], var = mpg))
```

<sup>Created on 2020-02-20 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by thomasp85** [comment]
I am pretty sure this has been fixed in the release candidate. Will check later

**Comment by yutannihilation** [comment]
Yeah, already fixed by https://github.com/tidyverse/ggplot2/pull/3746.

@rjb5 
FYI, you need to use `print()` inside `graph_by()` if you use `walk()`.

``` r
library(tidyverse)
packageVersion("ggplot2")
#> [1] '3.3.0'

params <-  setdiff(colnames(mtcars) ,"mpg") %>% head(2)

graph_by <- function(data, by, var, prefix = "avg") {
  data %>%
    group_by({{ by }}) %>%
    summarise(mean_value := mean({{ var }}, na.rm = TRUE)) %>%
    ggplot(aes(mean_value, {{ by }})) +
    geom_line() +
    geom_point()
}

#labels should be cyl instead of .data[["cyl"]]
p <- purrr::map(params, ~ graph_by(mtcars, by = .data[[.x]], var = mpg))
patchwork::wrap_plots(p)
```

![](https://i.imgur.com/Ql1LqpZ.png)

<sup>Created on 2020-02-21 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
