### ISSUE TITLE
not sure if right place, but problem in example for plotting shapefile

### ISSUE THREAD

**Issue by RafaRafa** [tidyverse/ggplot2#3831]
In this linke: https://github.com/tidyverse/ggplot2/wiki/plotting-polygon-shapefiles

```
  utah = readOGR(dsn=".", layer="eco_l3_ut")
  utah@data$id = rownames(utah@data)
  utah.points = fortify(utah, region="id")
  utah.df = join(utah.points, utah@data, by="id")
```

It joins by "id" however the column "id" in utah.points goes starts at 0 and row.names start at 1, so either have to add 1 to the first or subtract 1 from latter. 

I know that page is no longer maintained but would be good to fix that example as it's still a top result from Google.

**Comment by yutannihilation** [comment]
Thanks, that wiki seems incorrect. But, I don't think it's worth fixing as `geom_map()` is almost superseded by `geom_sf()`.

``` r
library(sf)
#> Linking to GEOS 3.8.0, GDAL 3.0.4, PROJ 6.2.1
library(ggplot2)

utah.df <- read_sf("~/Downloads/ecoregion_design/", layer = "eco_l3_ut")
ggplot(utah.df) +
  geom_sf(aes(fill = LEVEL3_NAM), colour = "white") +
  scale_fill_brewer("Utah Ecoregion", type = "qual")
```

![](https://i.imgur.com/qCI3bGL.png)

<sup>Created on 2020-02-24 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
