### ISSUE TITLE
aspect ratio of plot not working with of space = "free" in facet_grid 

### ISSUE THREAD

**Issue by dvaiman** [tidyverse/ggplot2#3834]
Hi, in ggplot I want to set the aspect ratio of the plot to a certain number.
`space = "free"`in `facet_grid` does not seem to work with ` theme(aspect.ratio = 1)`. Is there a workaround for this. Also I use `coord_flip` which hinders the use of `coord_fixed.` This is what I get:

![Rplot09](https://user-images.githubusercontent.com/61005947/75222142-d26f0b80-57a3-11ea-92d4-492e04212da2.png)

```r
library(ggplot2)

ggplot(mtcars, aes(hp, mpg)) +
  geom_point(aes()) +
  coord_flip()+
  theme(aspect.ratio = 1)+
  facet_grid(vars(cyl), space = "free")
```

**Comment by yutannihilation** [comment]
`space = "free"` has no effect unless the scales also vary, so probably the bellow example is more appropriate? In my understanding, there's no workaround and specifying `aspect.ratio = 1` should be errored as specifying `coord_fixed()` does.

``` r
library(ggplot2)

p <- ggplot(mtcars, aes(hp, mpg)) +
  geom_point(aes()) +
  facet_grid(vars(cyl), scales = "free", space = "free")

# works
p
```

![](https://i.imgur.com/qtsHTT6.png)

``` r
# fails properly
p + coord_fixed()
#> Error: coord_fixed doesn't support free scales

# do not fail, but the plot is strange
p + theme(aspect.ratio = 1)
```

![](https://i.imgur.com/tRuPiUo.png)

<sup>Created on 2020-02-29 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by dvaiman** [comment]
Thanks for the input,  I think your example more correctly describes the problem!

**Comment by FaizanKhalidMohsin** [comment]
I was just wondering is it possible to have this properly fixed?

**Comment by baderstine** [comment]
as in, restore the previous functionality when the x and y axes are discrete or what?

**Comment by Gsmith535** [comment]
Yes, please!

**Comment by FaizanKhalidMohsin** [comment]
@baderstine @Gsmith535 
Yes, please, can space = "free" correctly work for facet_grid() as it correctly works for facet_wrap().

**Comment by baderstine** [comment]
Yep it's a bummer that a plot is possible to render but instead we get an error message.

**Comment by yutannihilation** [comment]
> restore the previous functionality when the x and y axes are discrete

I'm getting to feel this might sound right, though I'm still in confusion what's the appropriate behavior... Anyway, it's not a good idea to keep discussing on a closed issue. Could you file a new issue describing what's the problem and what would be the "fix", with a minimal reprex?

The rendered version of https://github.com/tidyverse/ggplot2/issues/3834#issuecomment-948966404 at `v3.3.3` tag.

``` r
y <- factor(x = c(1:6), labels = letters[1:6])
x <- c("cat", "dog", "house", "farm", "road", "tree")
xgrp <- c("animal", "animal", "building", "building", "infrastructure", "nature")
xval <- rnorm(6)

dat <- data.frame(y, x, xgrp, stringsAsFactors = F)

devtools::load_all("~/GitHub/ggplot2/")
#> ℹ Loading ggplot2

# this plot has the correct aspect ratio, but it includes every single x category in every facet, regardless of whether a value is actually present:
ggplot(dat, aes(y = y, x = x)) +
  geom_tile(width = .8, height = .8) +
  theme(aspect.ratio = 1) +
  facet_grid(cols = vars(xgrp, x), drop = T) # , scales="free_x", space="free_x")
```

![](https://i.imgur.com/7LRyhUi.png)

``` r

# this plot drops the irrelevant x categories in each facet, however my tiles are no longer guaranteed to be square:
ggplot(dat, aes(y = y, x = x)) +
  geom_tile(width = .8, height = .8) +
  # theme(aspect.ratio = 1) +
  facet_grid(cols = vars(xgrp, x), drop = T, scales = "free_x", space = "free_x")
```

![](https://i.imgur.com/C6xgpKs.png)

``` r
# this plot is perfect (in a previous version of ggplot2), but now I'm not allowed to make it:
ggplot(dat, aes(y = y, x = x)) +
  geom_tile(width = .8, height = .8) +
  theme(aspect.ratio = 1) +
  facet_grid(cols = vars(xgrp, x), drop = T, scales = "free_x", space = "free_x")
```

![](https://i.imgur.com/worEZGh.png)

<sup>Created on 2022-06-24 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by FaizanKhalidMohsin** [comment]
@baderstine @yutannihilation I was just wondering why is this issue closed? Is the proper thing to reopen this issue or to open a new issue. Thank you.

**Comment by clauswilke** [comment]
I think the real issue is that we (maybe just me) have confused `coord_fixed()` with the `aspect.ratio` setting in the theme at some places in the code. I thought they did the same, but they do not.

``` r
library(tidyverse)

df <- tibble(
  x = 1:3,
  y = 2*(1:3),
  z = 3*(1:3)
)

ggplot(df, aes(x, y)) +
  geom_point() +
  theme(aspect.ratio = 1)
```

![](https://i.imgur.com/1IWBBn3.png)

``` r
ggplot(df, aes(x, y)) +
  geom_point() +
  coord_fixed()
```

![](https://i.imgur.com/2zlwsdE.png)

<sup>Created on 2022-06-24 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

Allowing `coord_fixed()` with free scales is not possible, because it creates facets of all different shapes and sizes and then we don't know how to tile them. But allowing a fixed aspect ratio for all facets should always be possible.

The new issue should focus on this point specifically.

**Comment by yutannihilation** [comment]
> But allowing a fixed aspect ratio for all facets should always be possible.

In my understanding, `aspect.ratio` is applied per panel, so it should conflict with `scales = "free"` because it varies the aspect ratios, at least the scale is continuous, isn't it...?

**Comment by yutannihilation** [comment]
Are you suggesting

``` r
ggplot(mtcars, aes(hp, mpg)) +
  geom_point() +
  theme(aspect.ratio = 1) +
  facet_grid(vars(cyl), scales = "free", space = "free")
```

should draw something like this?

``` r
library(ggplot2)

l <- split(mtcars, mtcars$cyl)

plots <- purrr::imap(unname(l), \(x, i) {
  ggplot(x, aes(hp, mpg)) +
    theme(aspect.ratio = 1) +
    geom_point() +
    facet_grid(vars(cyl)) +
    if (i != 3L) theme(axis.text.x = element_blank(), axis.title.x = element_blank())
})

patchwork::wrap_plots(plots, ncol = 1)
```

![](https://i.imgur.com/Lm7CUUQ.png)

<sup>Created on 2022-06-25 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by clauswilke** [comment]
@yutannihilation I think that's the request, yes, and it would be consistent with what `theme(aspect.ratio = 1)` does for a plot with a single panel.

And then this should also be properly documented, because right now if you read the documentation for `aspect.ratio` in `theme()` and for `ratio` in `coord_fixed()` they basically use the same language but apparently do entirely different things. There may also be other places in the code where this has been confused.

**Comment by baderstine** [comment]
@yutannihilation better version of the reprex: 

``` devtools::install_version("ggplot2", "3.3.3")
library(ggplot2)

y <- factor(x = c(1:6), labels = letters[1:6])
x <- c("cat", "dog", "house", "farm", "road", "tree")
xgrp <- c("animal", "animal", "building", "building", "infrastructure", "nature")
xval <- rnorm(6)
dat <- data.frame(y, x, xgrp, stringsAsFactors = F)


# this plot has the correct aspect ratio, but it includes every single x category in every facet, regardless of whether a value is actually present:

ggplot(dat, aes(y = y, x = x)) +
  geom_tile(width = .8, height = .8) +
  theme(aspect.ratio = 1) +
  facet_grid(cols = vars(xgrp, x), drop = T) # , scales="free_x", space="free_x")

# this plot drops the irrelevant x categories in each facet, however my tiles are no longer guaranteed to be square:
ggplot(dat, aes(y = y, x = x)) +
  geom_tile(width = .8, height = .8) +
  # theme(aspect.ratio = 1) +
  facet_grid(cols = vars(xgrp, x), drop = T, scales = "free_x", space = "free_x")


# this plot is perfect (in ggplot2 v <=3.3.3), but now I'm not allowed to make it:
# I am allowed to supply a custom aspect ratio, so that I can make square tiles, and therefore makes a rather nice heatmap plot.

my.aspect.ratio = length(unique(dat$y))
ggplot(dat, aes(y = y, x = x)) +
  geom_tile(width = .8, height = .8) +
  theme(aspect.ratio = my.aspect.ratio) +
  facet_grid(cols = vars(xgrp, x), drop = T, scales = "free_x", space = "free_x")
  
```

**Comment by yutannihilation** [comment]
@clauswilke 
Sorry, I edited the comment above. Then, I found we can just remove `space = "free"`.

``` r
library(ggplot2)

ggplot(mtcars, aes(hp, mpg)) +
  geom_point() +
  theme(aspect.ratio = 1) +
  facet_grid(vars(cyl), scales = "free")
```

![](https://i.imgur.com/zFA6u8c.png)

<sup>Created on 2022-06-25 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

@baderstine 
Would you mind rendering the reprex by yourself?

**Comment by clauswilke** [comment]
@yutannihilation Wait, does @baderstine just have to remove  `space = "free_x"` to get the plot he wants?

**Comment by yutannihilation** [comment]
@baderstine 
Is this what you want?

``` r
library(ggplot2)

y <- factor(x = c(1:6), labels = letters[1:6])
x <- c("cat", "dog", "house", "farm", "road", "tree")
xgrp <- c("animal", "animal", "building", "building", "infrastructure", "nature")
xval <- rnorm(6)
dat <- data.frame(y, x, xgrp, stringsAsFactors = F)

my.aspect.ratio <- length(unique(dat$y))
ggplot(dat, aes(y = y, x = x)) +
  geom_tile(width = .8, height = .8) +
  theme(aspect.ratio = my.aspect.ratio) +
  facet_grid(cols = vars(xgrp, x), drop = T, scales = "free_x")
```

![](https://i.imgur.com/Ku9G3f8.png)

<sup>Created on 2022-06-25 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by clauswilke** [comment]
I think he wants the individual facets square rather than the overall plot.

**Comment by baderstine** [comment]
Yep, it's about the shape of the individual plotted elements within each facet, not about the shape of the overall plot.

**Comment by baderstine** [comment]
I guess i don't have a good enough reprex to demonstrate the issue. If I remove the space = "free_x" then individual facets that contain multiple x values are squished. I'll work on a new example.

**Comment by yutannihilation** [comment]
Thanks, now I understand your intention, but I don't feel `aspect.ratio` works as intended (again, I believe it should be reflected to the ratios of each panel). I agree it's nice if ggplot2 can provide some way to do it.

@clauswilke 
Do you think what the last example shows is the correct use of `aspect.ratio` and `space = "free*"`?

**Comment by clauswilke** [comment]
Re-reading the documentation of everything, I think `aspect.ratio` should set the overall aspect ratio of the plot and `space = "free*"` should work as shown. So no, the example output does not look right. I don't think the aspect ratio for the overall plot is correct. I think it's awkward to apply the aspect ratio to individual facets, in particular if there's an option `space = "free*"` that we also expect to work.

We also have to accept that sometimes we have to carefully calculate the width and height of a plot such that individual facets come out just right, and this can't always be the job of ggplot2, sometimes it's on the user. That's what I did for example to make sure that all the individual squares came out right in this chapter of my book: https://clauswilke.com/dataviz/directory-of-visualizations.html

**Comment by yutannihilation** [comment]
Hmm. thanks. I don't agree with the idea of the overall aspect ratio of the plot at the moment, but it might be just that I don't read the documentation enough. As it turned out we all have different opinions on this topic, probably a closed issue is too small for the discussion. But let me clarify before filing a new issue. Do you mean both of the following results are wrong as `aspect.ratio` sets the aspect ratio of the individual facets, not that of the whole plot? Or, are you discussing only about the cases with `space = "free*"`?

``` r
library(ggplot2)

d <- data.frame(
  x = c(1, 2, 3, 1, 1, 2),
  y = c(1, 2, 3, 2, 3, 2),
  g = rep(c("a", "b", "c"), times = c(3, 1, 2))
)

p <- ggplot(d, aes(x, y)) +
  geom_point() +
  theme(aspect.ratio = 1)

p + facet_wrap(vars(g))
```

![](https://i.imgur.com/uISxtC1.png)

``` r
p + facet_grid(vars(g))
```

![](https://i.imgur.com/45YhSTT.png)

<sup>Created on 2022-06-25 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by clauswilke** [comment]
Oh, sorry, maybe I misunderstood and was wrong about the aspect ratio. Are you saying it currently applies consistently to individual facets? Maybe that's fine then, except I don't know what it would/should do when the axis ranges are different in different facets.

**Comment by yutannihilation** [comment]
> Are you saying it currently applies consistently to individual facets?

Yes, I believe that's the current behavior.

> what it would/should do when the axis ranges are different in different facets.

In my understanding, as you commented on https://github.com/tidyverse/ggplot2/issues/3834#issuecomment-1165656653, the aspect ratio is about the frame of the plot and irrelevant to the actual values inside. So, I think the same rule applies to `scales = "free"` without any problems (while it might not be a good idea to use it especially when the scale is continuous).

**Comment by clauswilke** [comment]
Ok, that seems reasonable to me, but it would probably not produce the plot @baderstine was hoping for.

**Comment by yutannihilation** [comment]
Thanks. Yeah, let's think about what option is needed to make it possible again next...

**Comment by yutannihilation** [comment]
I was about to file a new issue, but it seems #4584 is the one.

**Comment by Bigsealion** [comment]
> # this plot is perfect (in ggplot2 v <=3.3.3), but now I'm not allowed to make it:
> # I supply a custom aspect ratio, so that I can change the shape (aspect ratio) of my resulting tiles.
> 
> ggplot(dat, aes(y = y, x = var, color=xval)) +
>   geom_tile(width = .8, height = .8) +
>   theme(aspect.ratio = my.aspect.ratio) +
>   facet_grid(cols = vars(vargrp, varunt), drop = T, scales="free_x", space="free_x")
> Plot 4: drops irrelevant x categories and allows the size of each x facet to vary based on how many categories are in it, and with a specific aspect ratio applied, i can now make nice little squarish boxes.

Is there any way to get the same plot as plot4 in the new version of ggplot2 (e.g., 3.4.0)? Thanks!

**Comment by smouksassi** [comment]
have you tried ggforce ?
library(ggforce)
ggplot(dat, aes(y = y, x = x)) +
  geom_tile(width = .8, height = .8) +
  theme(aspect.ratio = 1) +
  facet_row(~ xgrp+ x, drop = T, scales="free_x")+
  theme(aspect.ratio = 6)

**Comment by venkmurthy** [comment]
I believe `ggh4x` solves this problem if you use `ggh4x::facet_grid2` with options `space=free` and `scale=free` along with `theme(aspect.ratio=1`
