### ISSUE TITLE
geom_bar: some Y axis breaks change the width of the bars/the plot

### ISSUE THREAD

**Issue by francoiskroll** [tidyverse/ggplot2#3836]
The bars of a barplot where the maximum Y axis label is two digits (eg. 20, 40, 60) will be wider than the bars of a barplot where the maximum Y axis label is three digits (eg. 20, 40, 60, 100), regardless of `geom_bar(size=)` parameter. Does this have a good reason to be the case? This makes aligning barplots vertically quite challenging.

```r

# creating an example dataframe
scrap <- as.data.frame(cbind(seq(1, 100, 10), seq(1, 100, 10)))
colnames(scrap) <- c('x', 'y')

# plotting barplot without setting breaks (i.e. will automatically put a break at 100)
plot_nobreaks <- ggplot (data = scrap, aes (x=x, y=y)) +
  geom_bar (stat = 'identity', size=0.5) + # note that size of the bars is set
  theme_minimal() +
  coord_cartesian(ylim=c(0, 100))

# plotting barplot with set breaks (i.e. will not put a break at 100)
plot_breaks <- ggplot (data = scrap, aes (x=x, y=y)) +
  geom_bar (stat = 'identity', size=0.5) + # note that size of the bars is set
  theme_minimal() +
  coord_cartesian(ylim=c(0, 100)) +
  scale_y_continuous(breaks=c(20, 40, 60))

# exporting
ggsave('nobreaks.pdf', plot=plot_nobreaks, width=50, height=50, unit='mm')
ggsave('breaks.pdf', plot=plot_breaks, width=50, height=50, unit='mm')

```

Now, here is how the two plots look aligned in Illustrator. Notice how the width of the bars is inconsistent, even though `geom_bar(size=)` was set. This makes it very difficult to align barplots vertically, even when they have the same number of bars.

<img width="429" alt="Screenshot 2020-02-25 at 23 57 16" src="https://user-images.githubusercontent.com/26249001/75298497-9206a080-582a-11ea-9acb-91575e90cc4f.png">

**Comment by thomasp85** [comment]
This is simply because the axis text takes up more space, thus squeezing the plotting area slightly... use the patchwork package to align the plotting area if you need to

**Comment by francoiskroll** [comment]
Ok thanks for the recommendation @thomasp85
