### ISSUE TITLE
Strange behavior of "group" aesthetic in geom_dotplot

### ISSUE THREAD

**Issue by gael-millot** [tidyverse/ggplot2#3839]
Is this behavior expected?
```r
# conversion of the vs and am columns of mtcars data frame into factors
mtcars$vs <- factor(mtcars$vs, labels = c("A", "B"))
mtcars$am <- factor(mtcars$am, labels = c("G", "H"))

# test of geom_dotplot using vs, mpg and am columns of mtcars
ggplot2::ggplot()+ggplot2::geom_dotplot(
    data = mtcars, 
    mapping = ggplot2::aes(x = vs, y = mpg, group = am), 
    position = ggplot2::position_dodge(), 
    binaxis = "y", 
    stackdir = "center",
    show.legend = TRUE
)
```
![1](https://user-images.githubusercontent.com/61543802/75440031-3be54a80-595b-11ea-91d4-9014c2b27c40.png)

Because other aesthetics gives the appropriate result, for instance when ```group``` is replaced by ```fill```:
```r
ggplot2::ggplot()+ggplot2::geom_dotplot(
    data = mtcars, 
    mapping = ggplot2::aes(x = vs, y = mpg, fill= am), 
    position = ggplot2::position_dodge(), 
    binaxis = "y", 
    stackdir = "center",
    show.legend = TRUE
)
```
![2](https://user-images.githubusercontent.com/61543802/75439883-ee68dd80-595a-11ea-9642-45d3c0c5ecaa.png)

The legend does not appear with ```group``` aesthetic, as expected, but the dot positions seem totally incoherent. It would be great if I could use ```group``` with the correct dot positioning.

Thanks for your help !

Best.

**Comment by gael-millot** [comment]
Of note, ```group``` works fine when replacing the ```am``` category by ```vs``` (a single qualitative variable plotted instead of two):

```r
ggplot2::ggplot()+ggplot2::geom_dotplot(
    data = mtcars, 
    mapping = ggplot2::aes(x = vs, y = mpg, group = vs), 
    position = ggplot2::position_dodge(), 
    binaxis = "y", 
    stackdir = "center", 
    show.legend = TRUE
)
```
![3](https://user-images.githubusercontent.com/61543802/75441684-6389e200-595e-11ea-8dcd-3c3b12bd819f.png)

As if, with two categories, ```group``` takes the "average" position of ```A``` and ```B``` and then separates correctly between ```G``` and ```H```...

**Comment by yutannihilation** [comment]
> Is this behavior expected?

Yes, this is an expected behaviour. My previous comment might be helpful to understand how the grouping works.

https://github.com/tidyverse/ggplot2/issues/3486#issuecomment-522210017

**Comment by gael-millot** [comment]
Many thanks for the answer ! It indeed indicates that the best is to create a new categorical colum:

```{r}
# nothing changed in the code, compared to the 1st example, except the group aesthetic
ggplot2::ggplot()+ggplot2::geom_dotplot(
    data = mtcars, 
    mapping = ggplot2::aes(x = vs, y = mpg, group = paste(vs, am, sep = ".")), 
    position = ggplot2::position_dodge(), 
    binaxis = "y", 
    stackdir = "center",
    show.legend = TRUE
)
```
![4](https://user-images.githubusercontent.com/61543802/75690605-6f014400-5ca3-11ea-9ed9-73bb6b1c3df8.png)

It is also interesting to mention that `group` presents different behaviors, depending on the function used:

```{r}
# test of geom_point using vs, mpg and am columns of mtcars
ggplot2::ggplot()+ggplot2::geom_point(
    data = mtcars, 
    mapping = ggplot2::aes(x = vs, y = mpg, group = am),
)
```
![1](https://user-images.githubusercontent.com/61543802/75690635-7fb1ba00-5ca3-11ea-9dbe-4268ec8bb988.png)

```{r}
# test of geom_dotplot in the same situation
ggplot2::ggplot()+ggplot2::geom_dotplot(
    data = mtcars, 
    mapping = ggplot2::aes(x = vs, y = mpg, group = am),
    binaxis = "y"
)
```
![2](https://user-images.githubusercontent.com/61543802/75690730-a40d9680-5ca3-11ea-872b-739d544d108e.png)

Thus, it could be worth to make a special section mentioning some particularities of `group`  in the ggplot2 documentation... here for instance ?
https://ggplot2.tidyverse.org/reference/aes_group_order.html

Thanks !

**Comment by yutannihilation** [comment]
Ah, it might be a bit clearer if `aes_group_order` doc shows an example case when both `group` and other discrete variables are mapped. Feel free to contribute :)
