### ISSUE TITLE
axis.title.x overrides axis.title in theme()

### ISSUE THREAD

**Issue by mfherman** [tidyverse/ggplot2#3841]
This appears to be new behavior in 3.3.0, where if you add a "more specific/child" theme element to a plot, and then also modify the "parent" theme element, the "child" element theme setting is used. This seems like something related to #3039, and I'm not sure if the old behavior was just a bug (that I happened to make use of!).

As an example, the below code returns the same plot with 3.3.0, but in older versions, the first code would remove the x-axis title.

``` r
library(ggplot2)

ggplot(iris, aes(Sepal.Length, Sepal.Width)) +
  geom_point() +
  theme(axis.title.x = element_text(size = 16)) +
  theme(axis.title = element_blank())
```

![](https://i.imgur.com/9YdYcqj.png)

``` r

ggplot(iris, aes(Sepal.Length, Sepal.Width)) +
  geom_point() +
  theme(axis.title = element_blank()) +
  theme(axis.title.x = element_text(size = 16))
```

![](https://i.imgur.com/uPGc30o.png)

<sup>Created on 2020-02-27 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by clauswilke** [comment]
The old behavior was broken. If you want to inherit from blank elements, you have to explicitly turn this on. (The assumption is that if you're explicitly setting a child element, you actually want it set, not removed.)

``` r
library(ggplot2)

ggplot(iris, aes(Sepal.Length, Sepal.Width)) +
  geom_point() +
  theme(axis.title.x = element_text(size = 16, inherit.blank = TRUE)) +
  theme(axis.title = element_blank())
```

![](https://i.imgur.com/OeRHseB.png)

<sup>Created on 2020-02-27 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by mfherman** [comment]
Thanks for the clarification and all your work on ggplot and other amazing packages!
