### ISSUE TITLE
geom_bar()/geom_col() should provide clearer warning when dropping data due to axis limits and column width

### ISSUE THREAD

**Issue by mkoohafkan** [tidyverse/ggplot2#3843]
Consider the following plot:

```r
library(ggplot2)

ggplot(mtcars, aes(x = carb)) + 
  geom_bar(stat = "count") +
  scale_x_continuous(limits = c(2, 4))
```

![image](https://user-images.githubusercontent.com/4790348/75587164-ba5ced80-5a2a-11ea-93d4-e294e2639037.png)

The bars centered at `2` and `4` are dropped. As documented in https://github.com/tidyverse/ggplot2/issues/2887, this is because the limits are not adjusted for the `width` of the bars. The bar centered on `2` actually extends back to ~`1.5`, and the bar centered on `4` actually extends to `4.5`. Users do get some warnings:
>Warning messages:
1: Removed 9 rows containing non-finite values (stat_count). 
2: Removed 2 rows containing missing values (geom_bar). 

The second warning alludes to the bars being dropped because they extend outside the specified axis limits. However, this isn't a sufficient explanation of what is happening because users may be specifying limits because they *want* bars outside of the axis limits to be dropped (and thus they expect to see the warnings), but don't understand why columns that appear to be *inside* the axis limits are also dropped.

**suggestion**: Improve the error message to note when columns are dropped because the column *width* is outside of the range (e.g. the column centered on `2`), as opposed to when the *entire column* is outside of the range (e.g. the column centered on `1`).

Finally, consider this solution to the issue:
```r

ggplot(mtcars, aes(x = carb)) + 
  geom_bar(stat = "count") +
  # expand axis limits to accommodate column width
  scale_x_continuous(limits = c(1.5, 4.5))
```
> Warning message:
Removed 9 rows containing non-finite values (stat_count). 

![image](https://user-images.githubusercontent.com/4790348/75587890-576c5600-5a2c-11ea-8299-29192f90731e.png)

Is this solution the *preferred* approach to resolving the issue, or is this relying on undocumented/unreliable behavior?

**Comment by yutannihilation** [comment]
I've filed a similar issue (#2887) before. I agree it's nice if we can show more clearer warning, which probably recommends to use `coord_cartesian(xlim = , ylim = )`.

**Comment by mkoohafkan** [comment]
I don't think the warning needs to even specify the solution---the unclear part is that columns are removed based on the column **edges** rather than the column **centers**. Adding something to the warning message like
> Columns with width that extends beyond the specified axis limits were dropped.

Would cue users in to *why* it's happening, and would easily be able to identify the best solution for their use case (e.g. using `coord_cartesian()` or simply expanding their specified limits).

**Comment by mkoohafkan** [comment]
Also, here's an example of why I think the behavior is inconsistent, although it was discussed at length in #2887:

```r
library(ggplot2)
 ggplot(mtcars) + aes(x =carb, y = mpg) + geom_point(size = 40) + xlim(c(3,4))
```
![image](https://user-images.githubusercontent.com/4790348/76175704-0f0b1180-616b-11ea-83f5-a444c76df8db.png)

The points are clearly wide enough to extend past the axis limits, but they are not removed.

**Comment by yutannihilation** [comment]
Your example makes me think that we might need some custom grob that is represented in 2D (i.e. `x`, `ymin`, `ymax` and `width`)...

**Comment by teunbrand** [comment]
The warning is now clearer:

> Removed 2 rows containing missing values or values outside the scale range (`geom_bar()`). 

Throwing a more specific warning for `geom_bar()` is hard with the current setup. The scales who handle out-of-bounds values are agnostic of layers. Building a layer awareness in scales is not straightforward and I don't think it is worth it for just this one message.

A second option would be to always add this suggestions to the warning, regardless of whether out-of-bounds censoring happened. This might raise a bunch of false positives, so I think we shouldn't go this route either.

With the situation improved by a clearer message, no viable paths (that I can see) to further the specificity of the message and this issue being dormant for the past 4 years, I think we should close this issue, and consider reopening it when a reasonable path has been laid out.
