### ISSUE TITLE
Error when using geom_vline() with facet_grid()

### ISSUE THREAD

**Issue by m1kejay** [tidyverse/ggplot2#3848]
If data is not defined within the `ggplot()` call (but in subsequent geom calls) , using `geom_vline()` throws an error but only if used with `facet_grid()` (Example 1 in reprex). If the call to `facet_grid()` is removed, there is no error and it works fine (example 2). Alternatively, if we define data within the `geom_vline()`, it works fine (example 3). 

This seems inconsistent to me. I would expect either 1 and 2 to both work or both throw an error, so I think this might be a bug?

```r
library(ggplot2)

# 1. Breaks
ggplot() +
  geom_point(data = mtcars, aes(x = mpg, y = cyl)) +
  geom_vline(aes(xintercept = 0)) +
  facet_grid(. ~ cyl)
#> Error in if (empty(data)) {: missing value where TRUE/FALSE needed

# 2. Works
ggplot() +
  geom_point(data = mtcars, aes(x = mpg, y = cyl)) +
  geom_vline(aes(xintercept = 0))

# 3. Works
ggplot() +
  geom_point(data = mtcars, aes(x = mpg, y = cyl)) +
  geom_vline(data = mtcars, aes(xintercept = 0)) +
  facet_grid(. ~ cyl)
```

**Comment by yutannihilation** [comment]
If you want to use `mtcars` on all the layers, you need to specify it in `ggplot()` (but this code is wrong for the following reason).

``` r
ggplot(data = mtcars) +
  geom_point(aes(x = mpg, y = cyl)) +
  geom_vline(aes(xintercept = 0)) +
  facet_grid(. ~ cyl)
```

The correct code is below; you should specify `xintercept` outside `aes()` as you don't need to map `xintercept` on `mtcars`, but just want a fixed value.

``` r
ggplot() +
  geom_point(data = mtcars, aes(x = mpg, y = cyl)) +
  geom_vline(xintercept = 0) +
  facet_grid(. ~ cyl)
```

**Comment by yutannihilation** [comment]
(Just for notice) I found this is a bug in facet. Will be fixed by https://github.com/tidyverse/ggplot2/pull/3868
