### ISSUE TITLE
Warning filter component in ggplot2

### ISSUE THREAD

**Issue by YoannPa** [tidyverse/ggplot2#3851]
I recently created a plot using ggplot2 within a function, and this plot generates warnings when being printed.  
Currently to suppress all warning on a ggplot2 plot you have to do something like this:
```r
suppressWarnings(print(my_ggplot2_plot))
```

I recently made a function which allow R users to filter warnings returned by a function they use:
```r
warn.handle <- function(pattern, ...){
  withCallingHandlers(..., warning = function(warning){
    condition <- conditionMessage(warning)
    if(grepl(pattern, condition)){ invokeRestart("muffleWarning") }
  })
}
```
Example:
```r
warn.handle(pattern = "a character string that will match in a warning", function_that_returns_warnings())
```

So I can use it on a ggplot2 plot when printing it (see 1st chunck of code), but if my plot is part of a plotting function I create, and that I add additionnal ggplot2 components to it, warnings will be displayed anyway:

```r
function_to_make_plot(){
  #create a plot
  my_ggplot2_plot<-ggplot() + <additionnal stuff...>
  #return
  return(
    warn.handle(pattern = "a character string that will match in a warning",
                         print(my_ggplot2_plot))
  )
}

function_to_make_plot() #Filtering warnings works.
function_to_make_plot() + xlab("My X-Axis Title") # All warnings will be printed.  
```

So my question is more like, is their any plan to create a ggplot2 component that would be able to do such thing ?
Something like that for example:

```r
my_ggplot2_plot<- ggplot() +
  <additionnal stuff...> +
  filter.warnings(pattern = "a character string that will match in a warning", ...)
```
`filter.warnings()` could be stored in `my_ggplot2_plot` so that if new components are added afterward, printing the final plot will still filter the unnecessary warnings.
It is just an idea, but I think it would helpful for some of us.

**Comment by yutannihilation** [comment]
> filter the unnecessary warnings.

Though you might feel the warning unnecessary, they are displayed because we think they are necessary. So, in general, you should not ignore warnings. If you feel some particular warning is inappropriate or unfriendly, please file an separate issue with a reprex.

I don't think ggplot2 will have such a function, but it might fit into an extension package.

**Comment by YoannPa** [comment]
I agree, I think warnings returned when printing plots are useful, but there will always be specific cases, where a warning will just be annoying.
Unfortunately, I don't have enough time to work on a ggplot2 extension package dedicated to warning management within gg object, but it would have been nice to have such thing.
Thank you for your answer.

**Comment by yutannihilation** [comment]
Yeah, I understand there's some cases that we want to hide warnings... I don't really recommend, but overwriting `print.ggplot()` might be a choice.

**Comment by YoannPa** [comment]
Yes sounds like something possible ! I will keep that in mind, and if I found the time I will try to play with `print.ggplot()`.
Thanks for the tip !
