### ISSUE TITLE
Install of ggplot2 fails when pathname contains non-ASCII characters

### ISSUE THREAD

**Issue by larsvilhuber** [tidyverse/ggplot2#3870]
When installing ggplot2 on 2020-03-07 on a virgin R install on a French-language Windows 10 system, installation fails when username (pathname) contains non-ASCII characters (in this case, contains "ë").

Error message:
```
* installing *source* package 'ggplot2' ...
** package 'ggplot2' correctement décompressé et sommes MD5 vérifiées
** using staged installation
Warning in file(file, if (append) "a" else "w") :
  impossible d'ouvrir le fichier 'C:/Users/Raphaklle/Documents/R/win-library/3.6/00LOCK-ggplot2/00new/ggplot2/DESCRIPTION' : No such file or directory
Error in file(file, if (append) "a" else "w") :
  impossible d'ouvrir la connexion
ERROR: installing package DESCRIPTION failed for package 'ggplot2'
* removing 'C:/Users/Raphaëlle/Documents/R/win-library/3.6/ggplot2'
Warning in install.packages :
  installation of package ‘ggplot2’ had non-zero exit status
```
(note difference between "`removing`" line and "`impossible d'ouvrir`" line).

Important: install works perfectly when user account (pathname) contains only ASCII characters, on the exact same system.

## Minimal reprex:
- buy brand-new Windows 10 laptop (probably irrelevant)
- switch OS to French (Canada) language (probably irrelevant)
- install all updates as of 2020-03-07 (probably irrelevant)
- create user account with non-ASCII (non-US) characters (in this case: "Raphaëlle", not tested with other characters), create second (admin) account with ASCII-only name (here: "Lars")
- install latest R from CRAN (here: 3.6.3) (using Admin privileges)
- type `install.packages("ggplot2")` using user-level privileges (installs into user's home directory)

## Full log file

See [this gist](https://gist.github.com/larsvilhuber/c67aea6e1340cd62ad44abb527f215cd) for full log file from installation attempt.

**Comment by thomasp85** [comment]
Is this problem singular to ggplot2? Can every other package be installed?

Also, did it work before the last release?

**Comment by clauswilke** [comment]
This is not a ggplot2 bug. My best guess is it's somewhere in `install.packages()` or in the functions it uses, so you'd have to report it to the R core developers.

You can see that it's not a ggplot2 bug because the problem arises first in your log when R tries to install "lifecycle".  In fact, I predict you can't install any packages using `install.packages()`.

**Comment by clauswilke** [comment]
Sorry, crossed the wire here with Thomas, but I'm pretty certain this is not ggplot2. If I'm wrong, please provide further info, and we can reopen.

**Comment by clauswilke** [comment]
Actually, reading the log more carefully, it seems that *source* packages can't be installed. To test for this specifically, if there are any packages you can install with `install.packages()`, try if it still works if you use `install.packages(..., type = "source")`.

**Comment by larsvilhuber** [comment]
Not sure what further info to provide. As you correctly point out, looks like it also happens in other dependencies of `tidyverse`. I'm reporting it here since it materially affects the ability of this particular user (and presumably others) to use `ggplot2`. 

I cannot speak to the fact of whether it happened before the last release - the system this failed on is not my system, and it's a brand new system (it is a novice student's system, whom I'm trying to convince of the merits of `ggplot2` - and patently failing due to this bug...)

I am not a R developer, so I do not know how to trace this to its ultimate source. I would argue that (i) I tried to install `ggplot2` and failed, and reported as much as I could find (ii) you as `ggplot2` developers in turn know how to identify the source, and can in turn report it (with much better information) to the actual maintainers of the root problem package. If you think that is better served by me making a non-informative bug report to the core maintainers, so be it. But I feel you would make a better job of doing that.

**Comment by clauswilke** [comment]
If I'm correct that the problem is installation of source packages, then you can suppress this by first running:
``` r
options(install.packages.check.source = "no")
```
It may also be possible to use `install.packages(..., type = "win.binary")` to force installation of binary packages only.

Note that the reason this is triggered by ggplot2 is that version 3.3.0 was just released and binaries aren't available yet. In a few days, binaries for 3.3.0 will be available and other packages may be the ones causing the problems then.

**Comment by larsvilhuber** [comment]
@clauswilke Thanks for the tip, which I will convey to the student (it will at least get her started). Are you, or should I, report this to the core maintainers? (see my prior note)

**Comment by clauswilke** [comment]
If my suggestions help, please update here so a workaround to the problem is recorded. Unfortunately I don't have the capacity right now to report this to the core developers, so if you could do it that would be great.

**Comment by larsvilhuber** [comment]
I will provide the workaround (once the person with the actual system has executed the relevant commands). I have also requested a login to the R Core Bugzilla, and will file it there once authorized. I suspect the bug is related to this one: https://bugs.r-project.org/bugzilla/show_bug.cgi?id=17709 (i.e., has the same root cause).
