### ISSUE TITLE
`geom_col` mishandles x-axis `Date` with decimals

### ISSUE THREAD

**Issue by thibautjombart** [tidyverse/ggplot2#3873]
`geom_col` does not handle `Date` on the x-axis when these contain decimals. Note that the input is still a valid `Date` object. This currently breaks `incidence::plot.incidence` as reported in [this issue](https://github.com/reconhub/incidence/issues/119).

``` r
library(ggplot2)
x <- data.frame(date = Sys.Date() + 1:10, 
                y = 1:10)


## this works
ggplot(x) + geom_col(aes(x = date, y = y))
```

![](https://i.imgur.com/WJNWrKa.png)

``` r

## this does not
ggplot(x) + geom_col(aes(x = date + 0.5, y = y))
```

![](https://i.imgur.com/hue4lYa.png)

``` r


## not sure if it affects other geoms; geom_point is fine:
ggplot(x) + geom_point(aes(x = date + 0.5, y = y))
```

![](https://i.imgur.com/LEZ00QB.png)

<sup>Created on 2020-03-09 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by thomasp85** [comment]
This is potentially a fallout from the bidirectional geom detection. We will look into a fix

**Comment by zkamvar** [comment]
Hello, this issue should not have been closed. It is still alive and kicking with ggplot2 3.3.1:

``` r
library(ggplot2)
x <- data.frame(date = Sys.Date() + 1:10, y = 1:10)
## This works
ggplot(x) + geom_col(aes(x = date, y = y))
```

![](https://i.imgur.com/dgDYJ6b.png)

``` r
ggplot(x) + geom_col(aes(date + 0.5, y = y))
```

![](https://i.imgur.com/jV9TPp8.png)

<sup>Created on 2020-06-06 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by yutannihilation** [comment]
You need to wait 3.3.2.

**Comment by zkamvar** [comment]
Can this issue be re-opened?

**Comment by thomasp85** [comment]
No, because it is already fixed in master
