### ISSUE TITLE
even.steps = FALSE does not work when binning is done outside of scale_binned

### ISSUE THREAD

**Issue by pasipasi123** [tidyverse/ggplot2#3877]
`even.steps = FALSE` should produce a stretched `guide_colorsteps()` bar when the variable has uneven breaks. This works when binning is done inside scale_binned.

``` r
library(tidyverse)

mtcars %>% 
  mutate(mpg_cut = cut(mpg, c(seq(10, 25, 5), 35))) %>% 
  ggplot(aes(hp, mpg, color = mpg_cut)) +
  geom_point() +
  guides(color = guide_colorsteps(show.limits = TRUE, even.steps = FALSE))
```

![](https://i.imgur.com/eJzKDoE.png)

<sup>Created on 2020-03-09 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by pasipasi123** [comment]
Here's an example of uneven binning inside scale_binned.

``` r
library(tidyverse)

mtcars %>% 
  ggplot(aes(hp, mpg, color = mpg)) + 
  geom_point() + 
  scale_color_binned(breaks = c(seq(10, 25, 5), 35)) +
  guides(color = guide_colorsteps(even.steps = FALSE, show.limits = TRUE))
```

![](https://i.imgur.com/KY9zn6P.png)

<sup>Created on 2020-03-09 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by thomasp85** [comment]
Looking into it again, I can now remember why this behaviour is unsupported. Proper support will have to wait for a full guide rewrite I'm afraid, but I'll add a warning explaining the missing ness of this feature
