### ISSUE TITLE
changing plot.title color overwrites plot.title.position = 'plot'

### ISSUE THREAD

**Issue by delabj** [tidyverse/ggplot2#3878]
I'm having an issue when creating a custom theme where the title reverts back to the center if I've specified plot.title = element_text(color= "some Color") 

I've played around with the order, and adding that theme option as a separate command, but the title remains in the center. I could be missing something obvious, so I'd love to find a solution. 

I expect the title to be aligned with the plot, but instead the title is aligned in the center. 

``` r
library(ggplot2)

extrafont::font_import(paths = "fonts/",prompt = F)
#> Scanning ttf files in fonts/ ...
#> Extracting .afm files from .ttf files...
#> Error in data.frame(fontfile = ttfiles, FontName = "", stringsAsFactors = FALSE): arguments imply differing number of rows: 0, 1
extrafont::loadfonts(device = "win")
#> Registering font with R using windowsFonts(): Source Code Pro Black
#> Registering font with R using windowsFonts(): Source Code Pro
#> Registering font with R using windowsFonts(): Source Code Pro ExtraLight
#> Registering font with R using windowsFonts(): Source Code Pro Light
#> Registering font with R using windowsFonts(): Source Code Pro Medium
#> Registering font with R using windowsFonts(): Source Code Pro Semibold
#> Registering font with R using windowsFonts(): Poppins Black
#> Registering font with R using windowsFonts(): Poppins
#> Registering font with R using windowsFonts(): Poppins ExtraBold
#> Registering font with R using windowsFonts(): Poppins ExtraLight
#> Registering font with R using windowsFonts(): Poppins Light
#> Registering font with R using windowsFonts(): Poppins Medium
#> Registering font with R using windowsFonts(): Poppins SemiBold
#> Registering font with R using windowsFonts(): Poppins Thin

theme_delabj <- function(){
  ggplot2::theme_minimal(base_size=12, base_family = "Poppins",
                         base_line_size = .5, base_rect_size = .5 ) %+replace%
    theme(
      plot.title.position = "plot",
      legend.position = "bottom",
      plot.background = element_rect(fill="#F9F1F1", color = "#F9F1F1"),
      panel.grid.major = element_line(color="#D6D6D6",
                                      size=0.5,
                                      linetype = "solid",
                                      lineend = "butt"),
      panel.grid.minor = element_line(color="#F3F3F3",
                                      size=0.5,
                                      linetype = "solid",
                                      lineend = "butt")
      
      
    )
}

theme_delabj_dark <- function(){
  ggplot2::theme_minimal(base_size=12, base_family = "Poppins") %+replace%
    theme(
      
      plot.title = element_text(color="#D6D6D6"),
      axis.title = element_text(color="#D6D6D6"),
      legend.text = element_text(color="#D6D6D6"),
      legend.title = element_text(color="#D6D6D6"),
      legend.position = "bottom",
      plot.background = element_rect(fill="#343E48", color = "#343E48"),
      
      panel.grid.major = element_line(color="#495866",
                                      size=0.5,
                                      linetype = "solid",
                                      lineend = "butt"),
      panel.grid.minor = element_line(color="#3f4b57",
                                      size=0.5,
                                      linetype = "solid",
                                      lineend = "butt"),
    )+
    theme(      plot.title.position = "plot")
}



df <- data.frame(x = factor(rep(letters[1:5], each = 10)), y = rnorm(50), color=(rep(c("A", "B", "C", "B", "A"), each=10)))
plot <- ggplot(df, aes(x = x, y = y, color=color)) + geom_jitter()



plot2 <- ggplot(df, aes(x=color, fill= x))+
  geom_bar()


plot2 +
  ggtitle("No Theme")
```

![](https://i.imgur.com/3JHz19u.png)

``` r

plot2 + 
  ggtitle("theme_delabj( )")+
  theme_delabj()
```

![](https://i.imgur.com/TLW1iAE.png)

``` r

plot2 + 
  ggtitle("theme_delabj_dark( )")+
  theme_delabj_dark()
```

![](https://i.imgur.com/HI51fzD.png)

<sup>Created on 2020-03-09 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by delabj** [comment]
Per some help on twitter, I can move the position manually using hjust, but would like to allow for realignment using built in functionality if possible

**Comment by thomasp85** [comment]
You are setting `plot.title = element_text(colour = "#D6D6D6")`, i.e., you are using the default `hjust` value of `0.5`, thus entering the title. This has nothing to do with `plot.title.position`

**Comment by delabj** [comment]
Thanks! 

I was just expecting that plot.title.position would then be able to adjust. I had also posted on twitter and got some help there, and was about to come and add that workaround/solution to this issue. They identified the same source of the issue, as well. 

I was expecting that having plot.title.position would overwrite the default theme settings, as using

 '''plot+theme(plot.title = element_text(colour = "#D6D6D6"))+ theme plot.title.position = "plot"``` produced the desired result when I was not using a custom theme, and I had assumed having both in my theme definition would create a similar result. 


For anyone in the future having a similar issue, 
```
plot.title = element_text(size = rel(1.2), hjust = 0, 
                                vjust = 1, margin = margin(b=half_line), colour ="#D6D6D6") 
```
gives a similar effect to ```plot.title.position = "plot"```  Where half_line is defined as base_size/2

**Comment by thomasp85** [comment]
I think you are misunderstanding the intent of `plot.title.position` it does not specify the alignment of the titles (left, right, center, etc), but rather the area to which it is aligned. You can see in the last plot above that it is getting applied because the title is no longer centred over the panel, but centred over the total plot area

**Comment by delabj** [comment]
That explains a lot! I had almost exclusively been using it to align the title to the edge of the labels.
