### ISSUE TITLE
Number of bins off by one in geom_contour()

### ISSUE THREAD

**Issue by clauswilke** [tidyverse/ggplot2#3879]
If we explicitly provide a number of bins, we get one too few. This is particularly striking if we set `bins = 2`, since that removes all contouring. This example of an empty plot is currently on the ggplot2 website (scroll down to 4th example):
https://ggplot2.tidyverse.org/reference/geom_contour.html#examples

I assume this is a regression introduced in 3.3.0.

``` r
library(ggplot2)

p <- ggplot(faithfuld, aes(waiting, eruptions, z = density))

p + geom_contour(bins = 3)
```

![](https://i.imgur.com/Y3nniga.png)

``` r
p + geom_contour_filled(bins = 3, aes(fill = after_stat(ordered(piece)))) + 
  scale_fill_viridis_d()
```

![](https://i.imgur.com/MsCjae7.png)

``` r
p + geom_contour(bins = 6)
```

![](https://i.imgur.com/4fj81YO.png)

``` r
p + geom_contour_filled(bins = 6, aes(fill = after_stat(ordered(piece)))) + 
  scale_fill_viridis_d()
```

![](https://i.imgur.com/TsxTR3A.png)

<sup>Created on 2020-03-09 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by clauswilke** [comment]
Ok, this appears to be dataset dependent, so it's likely a bug in `scales::fullseq()`.

``` r
library(tidyverse)

volcano %>%
  as_tibble() %>%
  rowid_to_column(var = "x") %>%
  gather(key = "y", value = "z", -1) %>%
  mutate(y = as.numeric(gsub("V", "", y))) %>%
  ggplot(aes(x, y, z = z)) + 
  geom_contour_filled(bins = 5, aes(fill = after_stat(ordered(piece)))) + 
  scale_fill_viridis_d()
```

![](https://i.imgur.com/NgQ4w3S.png)

<sup>Created on 2020-03-10 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by clauswilke** [comment]
At a minimum, though, the example with `bins = 2` needs to be changed.

**Comment by thomasp85** [comment]
have you dug deeper into this? should an issue in scales be opened?

**Comment by clauswilke** [comment]
> should an issue in scales be opened?

I think so. I gave up because I didn't immediately understand what data input causes it to work or not, but `scales::fullseq()` is definitely not behaving quite right.

**Comment by thomasp85** [comment]
Can I get you to do that and close this issue?

**Comment by clauswilke** [comment]
Actually, looking over everything one more time, it's not clear to me that we can just blame `scales::fullseq()`. We may not be using it correctly. It does what it promises to do. Because it takes a range and a binwidth as input, it doesn't guarantee a specific number of bins.

In the following reprex, the function `make_breaks()` encapsulates the logic used by ggplot2. We see that `scales::fullseq()` does what it is asked to do, but the results aren't necessarily what we want, depending on how the boundaries of the range line up with the binwidth.

``` r
library(tidyverse)

volcano_tbl <- volcano %>%
  as_tibble() %>%
  rowid_to_column(var = "x") %>%
  gather(key = "y", value = "z", -1) %>%
  mutate(y = as.numeric(gsub("V", "", y))) 

make_breaks <- function(data, bins) {
  z_range <- range(data, na.rm = TRUE, finite = TRUE)
  binwidth <- diff(z_range) / (bins - 1)
  breaks <- scales::fullseq(z_range, binwidth)
  cat("Range:", z_range, "\n")
  cat("Binwidth", binwidth, "\n")
  cat("Breaks:", breaks, "\n")
  invisible(breaks)
}

# one bin too few
make_breaks(faithfuld$density, 3)  
#> Range: 1.25925e-24 0.0369878 
#> Binwidth 0.0184939 
#> Breaks: 0 0.0184939 0.0369878
make_breaks(faithfuld$density, 5)  
#> Range: 1.25925e-24 0.0369878 
#> Binwidth 0.00924695 
#> Breaks: 0 0.00924695 0.0184939 0.02774085 0.0369878

# shifting the data creates the desired number of bins
make_breaks(faithfuld$density + .01, 3)  
#> Range: 0.01 0.0469878 
#> Binwidth 0.0184939 
#> Breaks: 0 0.0184939 0.0369878 0.0554817
make_breaks(faithfuld$density + .01, 5)  
#> Range: 0.01 0.0469878 
#> Binwidth 0.00924695 
#> Breaks: 0.00924695 0.0184939 0.02774085 0.0369878 0.04623475 0.0554817

# also correct number of bins
make_breaks(volcano_tbl$z, 3)
#> Range: 94 195 
#> Binwidth 50.5 
#> Breaks: 50.5 101 151.5 202
make_breaks(volcano_tbl$z, 5)
#> Range: 94 195 
#> Binwidth 25.25 
#> Breaks: 75.75 101 126.25 151.5 176.75 202
```

<sup>Created on 2020-04-30 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by thomasp85** [comment]
👍 we’ll fix it in ggplot2 then

**Comment by clauswilke** [comment]
The question is fundamentally whether we should divide by `bins - 1` or `bins` in this line:
https://github.com/tidyverse/ggplot2/blob/53815f82c82e36a3011b2a97861e916c513f9404/R/stat-contour.r#L158

A lazy fix would be to divide by `bins - 1`, calculate the breaks, check them out, and if it's one too few rerun the calculation but divide by `bins`.

**Comment by thomasp85** [comment]
I remember fiddling with that in the bin scale as well. I think your suggestion is pragmatic and good

**Comment by clauswilke** [comment]
Ok. I'll prepare a PR.
