### ISSUE TITLE
Installing ggplot2 gives a long sequence of "rd warning"

### ISSUE THREAD

**Issue by babaji-india** [tidyverse/ggplot2#3885]
I get a long sequence of Rd warnings since the ggplot2 updated a few days back. It was fine before that.

**Comment by clauswilke** [comment]
What exactly do you do? What is your setup? What are the warnings?

**Comment by yutannihilation** [comment]
Probably this one? An Windows-only issue.

https://github.com/r-lib/roxygen2/issues/707#issuecomment-520132365

**Comment by babaji-india** [comment]
All I do is 
`install.packages("ggplot2")`

And I get the following Rd warnings
Rd:16: file link 'as.list.environment' in package 'base' does not exist and so has been treated as a topic
Rd:51: file link 'extended_breaks' in package 'scales' does not exist and so has been treated as a topic
Rd:49: file link 'extended_breaks' in package 'scales' does not exist and so has been treated as a topic

There are many more similar Rd warnings.

**Comment by yutannihilation** [comment]
Yeah, that's the issue I referred to above. The bad news is that it's hard to fix and all you can do is just ignoring them (except for moving away from Windows), and the good news is that they are harmless, false-positive warnings.

Note that, you won't see the warnings anymore once the binary package of v3.3.0 become available on [CRAN](https://cran.r-project.org/web/packages/ggplot2/index.html).

![Screenshot from 2020-03-11 18-53-07](https://user-images.githubusercontent.com/1978793/76404302-9786ed80-63c9-11ea-8a0f-76c7e6dba0b9.png)

(I don't know why the binary is not built for Windows r-release yet, though...)

**Comment by clauswilke** [comment]
I'm reopening. We're now seeing this in our CI builds. If R core continues to insists on triggering these warnings we'll have to rethink our cross-linking approach.
 
```
checking Rd line widths ... OK
* checking Rd cross-references ... WARNING
package ‘grid’ exists but was not installed under R >= 2.10.0 so xrefs cannot be checked
package ‘grDevices’ exists but was not installed under R >= 2.10.0 so xrefs cannot be checked
Missing link or links in documentation object 'aes_.Rd':
  ‘substitute’
Missing link or links in documentation object 'as.list.ggproto.Rd':
  ‘[base:as.list.environment]{base::as.list.environment}’
Missing link or links in documentation object 'cut_interval.Rd':
  ‘[base:cut.default]{base::cut.default}’
Missing link or links in documentation object 'faithfuld.Rd':
  ‘faithful’
Missing link or links in documentation object 'fortify.lm.Rd':
  ‘cooks.distance’
Missing link or links in documentation object 'geom_boxplot.Rd':
  ‘boxplot’ ‘boxplot.stats’
Missing link or links in documentation object 'geom_contour.Rd':
  ‘pretty’
Missing link or links in documentation object 'geom_density.Rd':
  ‘[stats:bw.nrd]{stats::bw.nrd()}’ ‘density’
Missing link or links in documentation object 'geom_smooth.Rd':
  ‘predict’ ‘lm’ ‘glm’ ‘loess’
Missing link or links in documentation object 'geom_violin.Rd':
  ‘[stats:bw.nrd]{stats::bw.nrd()}’ ‘density’
Missing link or links in documentation object 'ggsave.Rd':
  ‘png’
Missing link or links in documentation object 'labellers.Rd':
  ‘bquote’
Missing link or links in documentation object 'luv_colours.Rd':
  ‘colors’
Missing link or links in documentation object 'qplot.Rd':
  ‘plot’
Missing link or links in documentation object 'scale_colour_continuous.Rd':
  ‘options’
Missing link or links in documentation object 'scale_date.Rd':
  ‘strftime’
Missing link or links in documentation object 'scale_grey.Rd':
  ‘gray.colors’
See section 'Cross-references' in the 'Writing R Extensions' manual.
* checking for missing documentation entries ... OK
* checking for code/documentation mismatches ... OK
* checking Rd \usage sections ... OK
* checking Rd contents ... OK
* checking for unstated dependencies in examples ... OK
* checking contents of ‘data’ directory ... OK
* checking data for non-ASCII characters ... OK
* checking data for ASCII and uncompressed saves ... OK
* checking installed files from ‘inst/doc’ ... OK
* checking files in ‘vignettes’ ... OK
* checking examples ... OK
** found \donttest examples: check also with --run-donttest
* checking for unstated dependencies in ‘tests’ ... OK
* checking tests ...
  Running ‘testthat.R’ [53s/53s]
 OK
* checking for unstated dependencies in vignettes ... OK
* checking package vignettes in ‘inst/doc’ ... OK
* checking re-building of vignette outputs ... OK
* checking PDF version of manual ... OK
* checking for non-standard things in the check directory ... OK
* checking for detritus in the temp directory ... OK
* DONE
Status: 1 WARNING
See
  ‘/home/travis/build/tidyverse/ggplot2/ggplot2.Rcheck/00check.log’
for details.
```

**Comment by yutannihilation** [comment]
Hmm, do you still think we can fix this after you've read the issue I referred to above?

**Comment by clauswilke** [comment]
Not sure. I also see that the latest CI run passes again, so I don't quite understand what's going on. I suggest we leave this issue open for now to collect more information.

**Comment by yutannihilation** [comment]
Sorry, I misunderstood your comment. I have 3+ years of experience of being annoyed by this warning on Windows, but I think I've never seen that warning in `R CMD check`. Let's see what was (is?) happening.

**Comment by yutannihilation** [comment]
By the way, which build was failed? AppVeyor or Travis CI? I don't find it on the build histories...

**Comment by clauswilke** [comment]
Check out this build:
https://travis-ci.org/github/tidyverse/ggplot2/jobs/661643070?utm_medium=notification&utm_source=github_status
I don't know why the very next one I did passed.

**Comment by yutannihilation** [comment]
Thanks, curious... The revision is the same, but the results are different.

failed one: https://travis-ci.org/github/tidyverse/ggplot2/jobs/661643070#L1277
the next one: https://travis-ci.org/github/tidyverse/ggplot2/jobs/661643070#L1277

**Comment by yutannihilation** [comment]
Sorry, I pasted a wrong link. The revision is different (`r77932` vs `r77934`) so probably something was changed between them.

**Comment by yutannihilation** [comment]
The diff between `r77933` and `r77934` is this one. Seems irrelevant...

https://github.com/wch/r-source/commit/4c5029b2d5149d3596eced57d8e233bde444f8da

**Comment by yutannihilation** [comment]
Hmm, I've given up. The check log indicates something was wrong with the setup of grid or grDevices, but I don't think the change above fix this. Anyway, this seems not what we can fix on ggplot2's side, if something is wrong with the installation of other packages.

```
package ‘grid’ exists but was not installed under R >= 2.10.0 so xrefs cannot be checked
package ‘grDevices’ exists but was not installed under R >= 2.10.0 so xrefs cannot be checked
```

**Comment by yutannihilation** [comment]
It seems the issue no more exists on the current master. I bet something was wrong with the setup of grid or grDevices on Travis CI. 

https://travis-ci.org/github/tidyverse/ggplot2/jobs/677218033
