### ISSUE TITLE
Some problem of crawler on WOS database

### ISSUE THREAD

**Issue by wushibuzhi** [tidyverse/ggplot2#3890]
---
I want to download all cited and citing data of all papers in specific journal, but there is some problem when it works.
Tip: it works with docker and VNC viewer.
(The first time issue a problem)

```r
# insert reprex here
[R code .zip](https://github.com/tidyverse/ggplot2/files/4325487/R.code.zip)

```

**Comment by clauswilke** [comment]
Please only submit issues regarding ggplot2 here.
