### ISSUE TITLE
ggplot sec.axis does not transform all corresponding values when transforming logit to prob

### ISSUE THREAD

**Issue by imkumar** [tidyverse/ggplot2#3892]
---

I am trying to transform the logit value on primary y axis into probability in sec axis using formula=exp(.)/(1+exp(.)) The transformed value should be between 0 to 1. The plot I am getting show the label at the middle of the sec axis only, but I want to show the label opposite to each corresponding value of primary y axis.

```r
data.frame(logit=runif(100,-10,10),x=1:100)%>%
  ggplot(aes(x=x,y=logit))+
  geom_point()+
  scale_y_continuous(sec.axis=sec_axis(trans=(~exp(.)/(1+exp(.))),
                                       name="prob"))+
  theme_bw()
```

**Comment by thomasp85** [comment]
It is quite difficult to automatically come up with sensible breaks for all sorts of non-linear transformations. I'd suggest you simply pass in a vector of break values manually
