### ISSUE TITLE
coord_polar() documentation: make clear 'start' depends on 'direction'?

### ISSUE THREAD

**Issue by david-romano** [tidyverse/ggplot2#3893]
The current documentation simply states that `start` is measured in radians from 12 o'clock, but it doesn't say that 'start' is measured relative to the direction chosen -- could that be added in the documentation.

**Comment by thomasp85** [comment]
Sure... would you be interested in submitting a PR?

**Comment by brianrice2** [comment]
I submitted a pull request since this was simple and inactive for a while, and agree seemed good for a first issue. Feedback welcome. Thanks.
