### ISSUE TITLE
arrow in geom_segment misoriented for length-zero segments

### ISSUE THREAD

**Issue by kuriwaki** [tidyverse/ggplot2#3894]
The expected behavior when `geom_segment()` is given a segment of __length 0__ (`xend == x`) is probably not to draw anything at all. But when an `arrow` is specified, the arrowhead is fixed so that it points left. See the "C" arrow below.  

I want it to  produce no arrowhead at all just for" C", or at least it should draw it so that it is oriented towards the aesthetic given (either pointing from `x` to `xend`, or pointing from `y` to `yend`, depending on what is specified).

``` r
library(ggplot2)
library(tibble)
library(patchwork)

dat <- tribble(
  ~letter, ~start, ~end,
  "A", 0.0, 0.10, 
  "B", 0.0, 0.01, 
  "C", 0.0, 0.0,   # this segment will have length 0
)


# expected behavior 
g0 <- ggplot(dat, aes(y = letter)) +
  geom_segment(aes(x = start, xend = end, yend = letter))

# unexpected behavior, arrow drawn but going left
g1 <- ggplot(dat, aes(y = letter)) +
  geom_segment(aes(x = start, xend = end, yend = letter), arrow = arrow())

# arrow goes left, regardless of orientation of the segment itself
g2 <- ggplot(dat, aes(x = letter)) +
  geom_segment(aes(y = start, yend = end, xend = letter), arrow = arrow())


g0 + g1 + g2
```

![](https://i.imgur.com/yWrZhpC.png)

<sup>Created on 2020-03-14 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by thomasp85** [comment]
This is unlikely to be fixed in ggplot2 as it is basically a grid issue. Arrow specifications are not very easy to work with as it is
