### ISSUE TITLE
Increase the font size of the track in the grpah

### ISSUE THREAD

**Issue by Aitor91** [tidyverse/ggplot2#3897]
Hello,

I am trying to increase the font of the text that is inside the arrow. If it is possible I would like to increase both,  the arrow and the text, but if not, I would be happy to increase just the text size.

I would appreciate any help or idea. Thank you very much for your time and help.

Best,

Aitor

![Rplot](https://user-images.githubusercontent.com/61357098/76792423-6af01e80-6799-11ea-95d6-3f113abe53b4.png)

**Comment by clauswilke** [comment]
Hello,

the ggplot2 issue tracker is to report bugs or limitations of the software, not to ask for user support. You can ask for user support over at the [RStudio Community](https://community.rstudio.com/) or at [Stackoverflow.](https://stackoverflow.com/)
