### ISSUE TITLE
dplyr 1.0.0

### ISSUE THREAD

**Issue by romainfrancois** [tidyverse/ggplot2#3900]
This seems overall unrelated, but we are seeing these issues when rev dev testing `dplyr`: 

```
[master* ↓] 286.1 MiB ❯ revdepcheck::revdep_details(revdep = "ggplot2")
══ Reverse dependency check ═══════════════════════════════════ ggplot2 3.3.0 ══

Status: BROKEN

── Fixed

✔ checking dependencies in R code ... NOTE

── Still failing

✖ checking installed package size ... NOTE

── Newly failing

✖ checking dependencies in R code ... WARNING

── Before ──────────────────────────────────────────────────────────────────────
❯ checking installed package size ... NOTE
    installed size is  5.8Mb
    sub-directories of 1Mb or more:
      R     2.1Mb
      doc   1.9Mb

❯ checking dependencies in R code ... NOTE
  Namespace in Imports field not imported from: ‘mgcv’
    All declared Imports should be used.

0 errors ✔ | 0 warnings ✔ | 2 notes ✖

── After ───────────────────────────────────────────────────────────────────────
❯ checking dependencies in R code ... WARNING
  '::' or ':::' import not declared from: ‘lifecycle’
  Namespace in Imports field not imported from: ‘mgcv’
    All declared Imports should be used.

❯ checking installed package size ... NOTE
    installed size is  5.8Mb
    sub-directories of 1Mb or more:
      R     2.0Mb
      doc   1.9Mb

0 errors ✔ | 1 warning ✖ | 1 note ✖
```

**Comment by yutannihilation** [comment]
Thanks.

This is so cryptic. I think ggplot2 doesn't use lifecyle package (yet)...

```
  '::' or ':::' import not declared from: ‘lifecycle’
```

**Comment by yutannihilation** [comment]
Hmm, confirmed on my local. With the dev version of dplyr, `devtools::check()` on ggplot2 invokes the warning, while it doesn't with the CRAN version.

**Comment by clauswilke** [comment]
ggplot2 reexports `dplyr::vars()` when available:
https://github.com/tidyverse/ggplot2/blob/e9b9946786dae861dea1c352f2ac7b2a837b5f82/R/zzz.r#L56-L58

And `dplyr::vars()` calls `lifecycle::signal_superseded()`:
https://github.com/tidyverse/dplyr/blob/ce81e7541795203d2b103a6075386d11935379d6/R/colwise.R#L109-L112

I assume that's what causes the warning. But even if not, I think it's a problem that we're reexporting a dplyr function that is labeled as superseded, so we'll have to find a solution to this.

**Comment by clauswilke** [comment]
If dplyr has superseded `vars()`, can we just go ahead and stop reexporting `dplyr::vars()` from ggplot2?

**Comment by thomasp85** [comment]
This was for the tidy eval support in facets that @lionel- implemented. I agree we have to consider its fate but it is probably a bit problematic as it’s use has been promoted in facets

**Comment by clauswilke** [comment]
Thomas, I think you misunderstood my intention: I meant we stop reexporting `dplyr::vars()` but we continue exporting our own `vars()`. If dplyr's intent is to deprecate `vars()` then there's not name clash with our own `vars()`.

**Comment by clauswilke** [comment]
We're currently defining our own `vars()` here:
https://github.com/tidyverse/ggplot2/blob/e9b9946786dae861dea1c352f2ac7b2a837b5f82/R/facet-.r#L228-L230

**Comment by lionel-** [comment]
Exporting ggplot2's own `vars()` alias seems the way to go.

ggplot2 doesn't have any defusing functions. Instead it relies on external defusing with `aes()`, `~`, and `vars()`. I don't expect we will switch to tidyselect arguments.

**Comment by clauswilke** [comment]
Closed via #3902.

**Comment by lionel-** [comment]
Now that I've seen the PR, I think this will cause clashes when attaching both packages. Removing the superseded signal in `dplyr::vars()` and reverting #3902 seems the best solution.

**Comment by clauswilke** [comment]
This works for me. Does this mean `vars()` is not going to be in "superseded" status in dplyr any longer? I think we need to have a log-term strategy for this. Either `vars()` is fully supported by both dplyr and ggplot2, or it should go away in dplyr and only be used in ggplot2, or it should go away in ggplot2 also. I don't like the last option, because I feel we're changing the API a lot lately already, and we should restrict such changes to when they are absolutely necessary.

**Comment by clauswilke** [comment]
(To add to my previous comment: Even if we imported lifecycle at some point for ggplot2, it wouldn't be good to have two functions with the same name in two packages, where one package declares the function as superseded and the other doesn't.)

**Comment by lionel-** [comment]
It's more like `vars()` is only used in dplyr by superseded functions. I don't think it should be considered superseded.

**Comment by clauswilke** [comment]
I've created a PR that reverts #3902: #3904
@lionel- Could you approve?

**Comment by clauswilke** [comment]
I've also filed an issue in dplyr (https://github.com/tidyverse/dplyr/issues/5015) regarding the documentation of `vars()`, which essentially states that this function is not useful anymore. At a minimum, I think the superseded label should be removed. Even better would be to state that the function can be used for faceting with ggplot2.

**Comment by romainfrancois** [comment]
This is n ow dealt with on the `dplyr` end.
