### ISSUE TITLE
Confusing error message when autogenerated aesthetic is also manually provided

### ISSUE THREAD

**Issue by clauswilke** [tidyverse/ggplot2#3901]
This issue was first reported for ggridges (https://github.com/wilkelab/ggridges/issues/56), but it can be reproduced with plain ggplot2. If I set an aesthetic (here `y`) that would normally be calculated by the stat, then the error message is that that aesthetic is missing. This is confusing, because the user has explicitly provided that aesthetic. A better error message would be useful. I haven't investigated yet why this happens.

``` r
library(ggplot2)

df <- data.frame(x = 1:100, y = (1:100)^2)

ggplot(df, aes(x, y)) +
  geom_density()
#> Error: geom_density requires the following missing aesthetics: y
```

<sup>Created on 2020-03-19 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by teunbrand** [comment]
I'm closing this in favour of #4776
