### ISSUE TITLE
Geom_point looses legend fill color when shape >20 is defined in scale

### ISSUE THREAD

**Issue by dernesa** [tidyverse/ggplot2#3903]
I loose the the fill color information in the legend, when I define shape = pch >20 in geom_point with `scale_shape_manual`. 

## Expected behaviour
In geom_point the shape is defined as `shape =21` with color and fill in the aesthetic mapping. The fill color is displayed in the legend

```{r}
library(tidyverse)
tibble(x=factor(1:4), y=rev(x)) %>% 
  ggplot(aes(x=x, y=y))+
  geom_point(aes(fill=y,color =x), size=4, shape=21)
```

![Expected](https://user-images.githubusercontent.com/24799198/77257054-35a07080-6c72-11ea-9f46-57e608caef01.png)

## Unexpected behaviour

However, when I use `scale_shape_manual` to use multiple shapes, or alternatively `scale_shape_manual(values=rep(21,4))` the fill color only shows black in the legend. 

```{r}
library(tidyverse)
tibble(x=factor(1:4), y=rev(x))  %>% 
  ggplot(aes(x=x, y=y))+
  geom_point(aes( fill=y,color =x, shape=x), size=4)+
  scale_shape_manual(values=21:24) 
```
![Unexpected](https://user-images.githubusercontent.com/24799198/77257059-3d601500-6c72-11ea-9356-fa6f3bbe313a.png)

**Comment by yutannihilation** [comment]
The problem is legends can be drawn over only one variable at once. In your example, `shape` belongs to `x` so shapes are not reflected to the legends of `y`. We eventually have more better mechanism to merge multiple variables (c.f. #3648), but this is what it is at the moment.

``` r
library(tidyverse)
tibble(x=factor(1:4), y=rev(x))  %>% 
  ggplot(aes(x=x, y=y))+
  geom_point(aes(fill = y, color = y, shape = y), size=4)+
  scale_shape_manual(values=21:24) 
```

![](https://i.imgur.com/mW2qJYS.png)

<sup>Created on 2020-04-22 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by aito123** [comment]
Hello, problem persists if you want to plot another variable in the shape aes. Let me show:

`tibble(x=factor(1:4), y=rev(x))  %>% 
     ggplot(aes(x=x, y=y))+
    geom_point(aes(fill = y, shape = x), size=4)+
    scale_shape_manual(values=21:24) `

The points in y legend turn black again. Help please.

![image](https://user-images.githubusercontent.com/53672503/151675275-3f1a8819-0fa0-453b-aebd-c2b480eb7b31.png)

**Comment by aito123** [comment]
Hello, problem persists if you want to plot another variable in the shape aes. Let me show:

`tibble(x=factor(1:4), y=rev(x))  %>% 
     ggplot(aes(x=x, y=y))+
    geom_point(aes(fill = y, shape = x), size=4)+
    scale_shape_manual(values=21:24) `

The points in y legend turn black again. Help please.

![image](https://user-images.githubusercontent.com/53672503/151675275-3f1a8819-0fa0-453b-aebd-c2b480eb7b31.png)

**Comment by yutannihilation** [comment]
I think it's the same problem. You can override the legend's shape to the one that has fill.

``` r
library(ggplot2)

d <- tibble::tibble(x = factor(1:4), y = rev(x))
ggplot(d, aes(x = x, y = y)) +
  geom_point(aes(fill = y, shape = x), size = 4) +
  scale_shape_manual(values = 21:24) +
  guides(fill = guide_legend(override.aes = list(shape = 21)))
```

![](https://i.imgur.com/iOYfusY.png)

<sup>Created on 2022-01-30 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
