### ISSUE TITLE
stat_function disregards log and possibly other scale

### ISSUE THREAD

**Issue by arwarw** [tidyverse/ggplot2#3905]
stat_function() seems to disregard scale_y_log10() and similar. There has been a PR #1011 that is (as far as I understand) supposed to have fixed this issue, merged in 2015 and released in 1.0.1.9000.

However, I can observe the following behavior in ggplot2 3.2.1 and 3.3.0 (did not test others):

``` r
library(tidyverse)
fn <- function(x) {exp(x)}
data <- tibble(x = c(1:10), y=exp(x))
data %>% ggplot(aes(x, y)) + geom_point() + stat_function(fun=fn)
```

![](https://i.imgur.com/Muzqyqj.png)

This (above) looks as expected, nothing was rescaled, the function matches the data points.

``` r
data %>% ggplot(aes(x, y)) + geom_point() + stat_function(fun=fn) + scale_y_log10()
```

![](https://i.imgur.com/TGEPs1Q.png)

The problem can be observed here, while the data points were adapted to a logscale y axis, the function wasn't. 

``` r
data %>% ggplot(aes(x, y)) + geom_point() + stat_function(fun=function(x){log10(fn(x))}) + scale_y_log10()
```

![](https://i.imgur.com/nsK9acX.png)

This is what I would the plot to look like (just without the workaround of applying the extra log10()).

<sup>Created on 2020-03-21 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by clauswilke** [comment]
I vaguely recall that this also has bothered me in the past. Let's see if we can figure out a way to fix this.

**Comment by clauswilke** [comment]
Looking at the code, it seems to me that transformations along the x axis are handled correctly but transformations along y are not:
https://github.com/tidyverse/ggplot2/blob/da2388eb4b9bf54c09728381d0130a98712862d5/R/stat-function.r#L109-L111

Reprex:
``` r
library(tidyverse)
fn <- function(x) {exp(x)}
data <- tibble(x = c(1:10), y=exp(x))
data %>% ggplot(aes(x, y)) + geom_point() + stat_function(fun=fn)
```

![](https://i.imgur.com/JkjhMgi.png)

``` r
data %>% ggplot(aes(x, y)) + geom_point() + stat_function(fun=fn) +
  scale_x_log10()
```

![](https://i.imgur.com/yv5jkuP.png)

<sup>Created on 2020-03-21 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by clauswilke** [comment]
I've prepared a PR that fixes this. #3908
