### ISSUE TITLE
geom_contour incompatible with scale_x_log10 and scale_y_log10

### ISSUE THREAD

**Issue by marcpaterno** [tidyverse/ggplot2#3906]
`geom_contour` seems to be incompatible with log scales, generated with `scale_x_log10` or `scale_y_log10` (or both).

```r
library(ggplot)
v <- ggplot(faithfuld, aes(waiting, eruptions, z = density))
v + geom_contour() + scale_x_log10()
```

This produces a warning message, below, and an empty plot.

```
Warning message:
Computation failed in `stat_contour()`:
Number of x coordinates must match number of columns in density matrix.
```

Use of `scale_y_log10` yields a similar result, with the warning message about `y` coordinates.

**Comment by clauswilke** [comment]
The error is generated by the isoband package, which means the input data is not properly being converted into something isoband can understand. I suspect the problem lives in this function:

https://github.com/tidyverse/ggplot2/blob/da2388eb4b9bf54c09728381d0130a98712862d5/R/stat-contour.r#L207-L219

However, I don't quite understand it. It looks much more complicated than I would have written it, so I suspect it's trying to cover a case that I'm not thinking about.

@paleolimbot Could you take a look?

**Comment by clauswilke** [comment]
Lines 209 and 210 create nice evenly spaced integers if the data is in a regular grid, but they leave large gaps when the data is not evenly spaced. I think that's what creates a z matrix of the wrong dimensions.

``` r
data <- data.frame(x = 0.2*(1:10))
data$logx <- log(data$x)

as.integer((data$x - min(data$x)) / ggplot2:::resolution(data$x, FALSE)) 
#>  [1] 0 1 2 3 4 5 6 7 8 9
as.integer((data$logx - min(data$logx)) / ggplot2:::resolution(data$logx, FALSE)) 
#>  [1]  0  6 10 13 15 17 18 19 20 21
```

<sup>Created on 2020-03-21 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by clauswilke** [comment]
Maybe what we want is something like `as.integer(factor(data$x, levels = sort(unique(data$x))))`?

``` r
data <- data.frame(x = 0.2*c(1:10, 1:10))
data$logx <- log(data$x)

as.integer(factor(data$x, levels = sort(unique(data$x))))
#>  [1]  1  2  3  4  5  6  7  8  9 10  1  2  3  4  5  6  7  8  9 10
as.integer(factor(data$logx, levels = sort(unique(data$logx))))
#>  [1]  1  2  3  4  5  6  7  8  9 10  1  2  3  4  5  6  7  8  9 10
```

<sup>Created on 2020-03-21 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by clauswilke** [comment]
This works now in GitHub master. Will be in the next release, which should come pretty soon.

``` r
library(ggplot2)
v <- ggplot(faithfuld, aes(waiting, eruptions, z = density))
v + geom_contour() + scale_x_log10()
```

![](https://i.imgur.com/uGuJXDI.png)

<sup>Created on 2020-03-22 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by marcpaterno** [comment]
Thank you very much for such quick action.
