### ISSUE TITLE
geom_rect rectangle disappears when used together with coord_sf in R

### ISSUE THREAD

**Issue by KaanOzgencil** [tidyverse/ggplot2#3909]
I am plotting a map with `ggplot2` and would like to have a rectangle surrounding it. I have tried to create the rectangle using `geom_rect` function, but whenever I include `coord_sf` function in the code chunk, the rectangle disappears. Below are the maps I got with the following codes. Classes of zone_map and ecoregion_polygon objects are "sf" and both are read in using `st_read` function. 

    ggplot() + 
      geom_sf(data = zone_map, color = "black", fill = gray62_transparent) +
      geom_sf(data = ecoregion_polygon, color = "black", fill = burlywood1_transparent) +
      geom_rect(aes(xmin = 20, xmax = 50, ymin = 33, ymax = 47), color = "black", fill = NA)
[![enter image description here][1]][1]

    ggplot() + 
      geom_sf(data = zone_map, color = "black", fill = gray62_transparent) +
      geom_sf(data = ecoregion_polygon, color = "black", fill = burlywood1_transparent) +
      geom_rect(aes(xmin = 20, xmax = 50, ymin = 33, ymax = 47), color = "black", fill = NA) +
      coord_sf(crs = "+proj=laea +lat_0=38 +lon_0=35")
[![enter image description here][2]][2]

  [1]: https://i.stack.imgur.com/5dcJA.png
  [2]: https://i.stack.imgur.com/dRt0z.png

As you see in the second map, the `geom_rect` rectangle disappears upon addition of `coord_sf` line. **How can I solve this issue?** I have tried to create another polygon using `st_polygon` function, but I obtained the same results. I also tried setting both objects' crs as the azimuthal `"+proj=laea +lat_0=38 +lon_0=35"` projection, which I want to plot my map in, and I got the same results. Below are the `st_crs` outputs of zone_map and ecoregion_polygon objects.

    > st_crs(zone_map); st_crs(ecoregion_polygon)
    Coordinate Reference System:
      EPSG: 4326 
      proj4string: "+proj=longlat +datum=WGS84 +no_defs"
    Coordinate Reference System:
      EPSG: 4326 
      proj4string: "+proj=longlat +datum=WGS84 +no_defs"

**Comment by clauswilke** [comment]
We have a solution but it's going to be a while until it can be released: https://github.com/tidyverse/ggplot2/pull/3659

In the mean time, you can use the trick described here:
https://wilkelab.org/practicalgg/articles/goode.html
