### ISSUE TITLE
coord_cartesian() fails without reversed limits with scale_y_reverse()

### ISSUE THREAD

**Issue by JWiley** [tidyverse/ggplot2#3910]
In 3.3.0 (including latest dev version), there is odd behavior when combining `coord_cartesian()` with `scale_y_reverse()`.

This is fine:

```r
ggplot(mtcars, aes(mpg, hp)) + 
  geom_point() + 
  coord_cartesian(xlim = c(10, 35), ylim = c(50, 350))
```
![image](https://user-images.githubusercontent.com/322716/77412129-9619e400-6e11-11ea-9be7-9348aa44036d.png)

This also is fine:

```r
ggplot(mtcars, aes(mpg, hp)) + 
  geom_point() + 
  scale_y_reverse() + 
  coord_cartesian(xlim = c(10, 35))
```
![image](https://user-images.githubusercontent.com/322716/77412213-af229500-6e11-11ea-9e6e-08b2a3517541.png)

This breaks. I'm inclined to see it as a bug, because even if you think I *should* reverse the lower and upper limit of `ylim` given the use of `scale_y_reverse()`, why should that error make the axis ticks, etc. disappear altogether for the y axis?

```r
ggplot(mtcars, aes(mpg, hp)) + 
  geom_point() + 
  scale_y_reverse() + 
  coord_cartesian(xlim = c(10, 35), ylim = c(50, 350))
```
![image](https://user-images.githubusercontent.com/322716/77412247-bb0e5700-6e11-11ea-88ec-77b0beeaf3de.png)

Interestingly, this is fine again.

```r
ggplot(mtcars, aes(mpg, hp)) + 
  geom_point() + 
  scale_y_reverse() + 
  coord_cartesian(xlim = c(10, 35), ylim = c(350, 50))
```
![image](https://user-images.githubusercontent.com/322716/77412410-f4df5d80-6e11-11ea-98c2-308ffacb52cb.png)

**Comment by yutannihilation** [comment]
Sorry, I didn't notice this issue... Let me close this in favor of #3952.
