### ISSUE TITLE
Export 'binned_scale'

### ISSUE THREAD

**Issue by coolbutuseless** [tidyverse/ggplot2#3913]
'discrete_scale' and 'continuous_scale' are both exported.  For consistency and ease of extending ggplot2, can 'binned_scale' be exported as well?

Tiny PR: https://github.com/tidyverse/ggplot2/pull/3912

**Comment by yutannihilation** [comment]
Sounds good to me, but, as `binned_scale` is a very new one, we might want to wait for a while until we're sure we don't need to introduce some (internal) breaking change. Once it's exported, it gets harder for us to make some change on it.

@thomasp85 Any thoughts?

**Comment by thomasp85** [comment]
I think we should just export it. It is very unlikely that there will be any major changes to it
