### ISSUE TITLE
ggupset breaks with version 3.3.0

### ISSUE THREAD

**Issue by const-ae** [tidyverse/ggplot2#3914]
Hi,

I noticed yesterday that with the new version of ggplot, my extension [ggupset](https://github.com/const-ae/ggupset) breaks when I add a `scale_x_mergelist()`.
On the positive side, the main functionality of the package is still intact and my replacement combination matrix axis still works. 

However, I have a helper function `scale_x_mergelist()` that converts a list column into a character vector with `paste(..., collapse = "-")`.  Previously, the collapsed string was shown on the x-axis, now it is blank:

``` r
library(ggplot2)
library(ggupset)
ggplot(tidy_movies, aes(x = Genres)) +
  geom_bar() +
  scale_x_mergelist(sep = "-")
```

![](https://i.imgur.com/tSWbxhw.png)

<sup>Created on 2020-03-29 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Before the change the plot looked like this:

![](https://github.com/const-ae/ggupset/blob/03b4788a1868e9cac5783b0313ea47e5622b5231/man/figures/README-unnamed-chunk-9-1.png?raw=true)

From my preliminary investigations, I think the issue might be related to https://github.com/tidyverse/ggplot2/pull/3398. However, I cannot figure out how to adapt the code of my package to make it work again.

**Comment by clauswilke** [comment]
I assume this will help: https://github.com/haleyjeppson/ggmosaic/issues/41#issuecomment-600863695
See also: https://github.com/haleyjeppson/ggmosaic/pull/42
(Though I would probably just bump the version requirement for ggplot2 and not bother with fixing things for older version of ggplot2.)

**Comment by const-ae** [comment]
Thank you for the quick reply. Adding `guide = ggplot2::waiver()` fixed the issue :)
