### ISSUE TITLE
geom_text add option for coordinate related angle ('slope') rotation 

### ISSUE THREAD

**Issue by ChHaeni** [tidyverse/ggplot2#3915]
It would be helpful to have the option to rotate text (when using e.g. geom_text) providing a 'slope', so that you can annotate a 1:1 line with 1:1 correctly rotated.
The following example should indicate the issue:
```r
library(ggplot2)

df <- data.frame(f = rep(letters[1:4], 10), x = rnorm(40), y = rnorm(40))

ggplot(df, aes(x = x, y = y)) +
	geom_abline(intercept = 0, slope = 1) + 
	geom_point() +
	facet_wrap(~ f, scales = "free_x") +
	geom_text(x = 0, y = 0, label = "1:1", angle = 45)
```

**Comment by ChHaeni** [comment]
I'm sorry for spam. Was not aware of the function ggplot_build...

**Comment by smouksassi** [comment]
duplicate of https://github.com/tidyverse/ggplot2/issues/2852
