### ISSUE TITLE
Too much space reserved for axis labels when using facets

### ISSUE THREAD

**Issue by Darxor** [tidyverse/ggplot2#3923]
ggplot2 seems to reserve too much space for axis labels in non-english languages (non-ASCII characters?) when using facets.

Problem seems to be locale dependent as it appears with default "Russian_Russia.1251" locale and does not appear with "en_US.UTF-8".

---

``` r
library(ggplot2)

set.seed(1L)
test_df <- data.frame(
  cat = sprintf("cat%s", rep(1:3, each = 3)),
  subcat = sprintf("subcat_subcat_subcat_subcat%s", rep(1:3, times = 3)),
  subcat_ru = sprintf("субкат_субкат_субкат%s", rep(1:3, times = 3)),
  amount = runif(3*3, 25, 40)
)

ggplot(test_df, aes(y = subcat, x = amount)) +
  geom_col() +
  facet_wrap(cat ~ .)
```
Plot renders fine with english characters.

![test_plot_en](https://user-images.githubusercontent.com/1351765/78250083-01da0c00-74f8-11ea-9e2e-f8c808b16751.png)

``` r

ggplot(test_df, aes(y = subcat_ru, x = amount)) +
  geom_col() +
  facet_wrap(cat ~ .)
```
But breaks when using russian.

![test_plot_ru](https://user-images.githubusercontent.com/1351765/78250287-4fef0f80-74f8-11ea-841c-6a99cf13cd71.png)

**Comment by thomasp85** [comment]
My guess is that the graphic device reports the wrong string width with non-latin characters. While I'm not sure if it will work, can you try to run it with `ragg::agg_png()` instead of the default device, and see if it resolves the issue?

**Comment by Darxor** [comment]
Yes, it does fix it. Moreover, it worked fine when I used `grDevices::png()`.
Plots above were saved through "Export > Save as Image..." in RStudio.

It seems weird to me, that it works fine without facets, so I'm not sure if this is only a graphic device issue.

**Comment by thomasp85** [comment]
if it is fixed by changing the graphic device, then it is a graphic device issue... weird that it works with `grDevices::png()` as I believe the RStudio device is a shim over the default png device. @kevinushey can you think of a reason?

**Comment by clauswilke** [comment]
I've seen this before, in ggtext: https://github.com/wilkelab/ggtext/issues/19 (but it wasn't a ggtext issue). I think what happens is that some graphics devices in some locales treat each byte in a multi-byte symbol as a separate characters when calculating the width of a string. But then, when they render, they interpret the byte sequence correctly.

**Comment by thomasp85** [comment]
That was what I was expecting, but I am surprised about the difference between `png()` and the RStudio device

**Comment by Darxor** [comment]
I've tried to experiment further, it seems to break on `ragg::agg_png()` too (as well as `png()`), when plots are combined with `gridExtra::grid.arrange()`

```
library(ggplot2)

set.seed(1L)
test_df <- data.frame(
  cat = sprintf("cat%s", rep(1:3, each = 3)),
  subcat = sprintf("subcat_subcat_subcat_subcat%s", rep(1:3, times = 3)),
  subcat_ru = sprintf("субкат_субкат_субкат%s", rep(1:3, times = 3)),
  amount = runif(3*3, 25, 40)
)

ggp <- ggplot(test_df, aes(y = subcat_ru, x = amount)) +
  geom_col() +
  facet_wrap(cat ~ .)

ggp_grid <- gridExtra::grid.arrange(ggp, ggp, nrow = 1)
```

![Rplot001](https://user-images.githubusercontent.com/1351765/78263736-065bf000-750b-11ea-8ae5-e79cc797e5c5.png)

**Comment by thomasp85** [comment]
I can only assume that gridExtra calculates the widths before rendering. Nothing to do about that... use patchwork for combining plots instead
