### ISSUE TITLE
Error message when joining a sf and a tibble

### ISSUE THREAD

**Issue by hansronald** [tidyverse/ggplot2#3927]
I want to join a sf with a tibble, but running the code below produced the error I show in the bottom of my message. I have used this code before and it worked. I had just updated all packages, R and R studio and it stopped working.

This seems to be a similar error message like this one:
https://github.com/tidyverse/ggplot2/issues/3453

```r
country_data = structure(list(iso3_code = c("AFG", "AFG", "ALB", "ALB", "DZA", "ASM"),
                              country = c("Afghanistan", "Afghanistan", "Albania", "Albania", "Algeria", "American Samoa"),
                              item = c("Maize", "Sugar cane", "Maize", "Soybeans", "Maize", "Sugar cane"),
                             value = c(106670, 25421, 391104, 744, 4142, 30)),
                         row.names = c(NA, -6L), class = c("tbl_df", "tbl", "data.frame"))
library(sf)
library(rgeos)
library(dplyr)
library(rnaturalearth)
world <- ne_countries(scale = "small", returnclass = "sf")  
world_filtered = world %>% 
  select(country = name_long, iso3_code = iso_a3, geometry) %>%
  filter(!is.na(iso3_code)) %>% 
  filter(country != "Antarctica") 

map = full_join(world_filtered, country_data, by = "iso3_code") 
```

I get the following error message:
```r
> map = full_join(world_filtered, country_data, by = "iso3_code") 
Error: All columns in a tibble must be vectors.
x Column `geometry` is a `sfc_MULTIPOLYGON/sfc` object.
Run `rlang::last_error()` to see where the error occurred.
```

**Comment by clauswilke** [comment]
This is not a ggplot2 issue. It looks like an issue between dplyr and sf, so you'd have to report it for one of these packages. Though I suspect that things will work if you install the latest development version of dplyr.

**Comment by gregmacfarlane** [comment]
I'm seeing the same issues. I think the issue is in the new `tibble` library.

**Comment by brendentaylor22** [comment]
@hansronald I've got the same problem after I've just updated my R packages. Did you ever find a solution to this?

**Comment by Jonkman1** [comment]
I have also this problem  "All columns in a tibble must be vectors. x Column `geometry` is a `sfc_MULTIPOLYGON/sfc` object.' after updating the packages. What to do?

**Comment by donovanrichardson** [comment]
> I'm seeing the same issues. I think the issue is in the new `tibble` library.

Installing tibble 2.1.3 resolved this issue for me.
