### ISSUE TITLE
# Guides are integrated where possible but ...

### ISSUE THREAD

**Issue by iago-pssjd** [tidyverse/ggplot2#3928]
In `guides` help is claimed that `# Guides are integrated where possible` with the corresponding example. I would expect that for the next one is it possible integrate the 2 guides as an interaction:

```
p <- mtcars %>% 
        ggplot(aes(x = mpg, y = disp, color = factor(cyl), shape = factor(vs))) + 
        geom_point()
p + guides(color = guide_legend("title"), shape = guide_legend("title"))
```

But it has no effect.

If I am not reporting a bug but an expected behaviour, can suggest it an interesting feature request?

Thank you!

**Comment by thomasp85** [comment]
How do you expect a guide for two different mappings to look

**Comment by iago-pssjd** [comment]
I will try to explain better as possible. Following the example 

```p + guides(colour = guide_legend("title"), size = guide_legend("title"), shape = guide_legend("title"))``` 

in the cited help, in my case I would have 6 categories with 3 repeated colours and 2 repeated shapes combined and the default legend would be result of the `interaction` of color and shape aesthetics (something like a `paste`? I do not know and maybe it's not so important, since I would expect having the possibility of changing it through `breaks` and `labels`).

If you want more detail, tell me please.

Thank you!

**Comment by smouksassi** [comment]
As Thomas pointed out , you cannot merge legends that do not have all the same keys. cyl and vs have different levels (values).
The merging works if you map color and shape to the same variable and you can decide to merge or not the guides by having the same title and order or not.

``` r
library(ggplot2)
p <- ggplot(mtcars, aes(x = mpg, y = disp, color = factor(cyl), shape = factor(cyl))) + 
  geom_point()
p + guides(color = guide_legend("title"), shape = guide_legend("title"))
```
![](https://i.imgur.com/KyerUoD.png)

``` r
p <-  ggplot(mtcars, aes(x = mpg, y = disp, color = factor(cyl), shape = factor(cyl))) + 
  geom_point()
p + guides(color = guide_legend("title"), shape = guide_legend("title", order = 2))
```
![](https://i.imgur.com/Blt460C.png)

<sup>Created on 2020-04-07 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by iago-pssjd** [comment]
I know that I can do this with the same variable, or even with variables with the same values as in the example in https://ggplot2.tidyverse.org/reference/guides.html, but I am asking if is it not possible to create some kind of abstract variable which gives interaction keys between two or more factors.

Meanwhile, I also know I can create my interaction variable before asking for it to ggplot and give manually repeated colours and shapes or whatever. But I expected a ggplot option for it.

Thank you!

**Comment by smouksassi** [comment]
ok so for reference you want this automatically  without having to take care of the interaction and manual mappings:
``` r
library(ggplot2)
p <- ggplot(mtcars, aes(x = mpg, y = disp,
                        color = paste(vs,cyl,sep=" / "),
                        shape = paste(vs,cyl,sep=" / "))) + 
  geom_point(size=4)
p +
scale_color_manual(values=c("blue","red","green","blue","red")) +
scale_shape_manual(values=c(1,1,1,2,2)) +
  guides(colour = guide_legend("vs/cyl"),
           shape = guide_legend("vs/cyl"))
```

![](https://i.imgur.com/rPhCdjM.png)

<sup>Created on 2020-04-07 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by iago-pssjd** [comment]
That's it!

**Comment by yutannihilation** [comment]
Thanks @smouksassi!
