### ISSUE TITLE
Incorrect attribution name for Munsell colour system - Albert not Alfred

### ISSUE THREAD

**Issue by mentat10191** [tidyverse/ggplot2#3929]
In the ggplot2 vignette:

vignette("ggplot2-specs")

The attribution for the Munsell colour system is incorrectly given to:
"Alfred Munsell"

It should of course be:
"Albert Munsell"

Or:
"Albert H. Munsell"

Incorrect vignette quote (my emphasis):
"The munsell package, by Charlotte Wickham, makes it easy to choose specific colours using a system designed by _Alfred Munsell_. If you invest a little in learning the system, it provides a convenient way of specifying aesthetically pleasing colours."

**Comment by clauswilke** [comment]
I confirm that the correct name is "Albert H. Munsell": https://en.wikipedia.org/wiki/Albert_Henry_Munsell

**Comment by yutannihilation** [comment]
@mentat10191 Would you like to contribute a PR?

**Comment by mentat10191** [comment]
> @mentat10191 Would you like to contribute a PR?

Sorry, no clue what a PR is..

**Comment by yutannihilation** [comment]
Sorry, I meant a *pull request*. No worries, I'll do it this time :)

c.f. https://help.github.com/en/github/managing-files-in-a-repository/editing-files-in-your-repository

**Comment by mentat10191** [comment]
> Sorry, I meant a _pull request_. No worries, I'll do it this time :)
> 
> c.f. https://help.github.com/en/github/managing-files-in-a-repository/editing-files-in-your-repository

You're a star, thank you! I'm new to all this, so tips like this are very welcome!
