### ISSUE TITLE
Ghost points when overlaying boxplot with geom_point

### ISSUE THREAD

**Issue by ckr123tw** [tidyverse/ggplot2#3930]
When overlaying points on boxplots, ghost points appeared. As shown in the following plots, the boxplot on the right has an additional point.

![image](https://user-images.githubusercontent.com/12422582/78709978-8e167580-78e2-11ea-8b42-bf9b9f68b41b.png)

```r
b = data.frame(cnt = c(8,15,10,5,4,2,22,13,28,13,24,8,10,13,7,16,27,10,16,7),
               grp = c('U','E','U','U','U','E','E','U','U','U','U','E','U','E','U','E','U','U','E','E'))
ggplot(b,aes(x=grp,y=cnt))+
    geom_boxplot()+
    geom_point(position=position_jitter(w = 0.2, h = 0))
ggplot(b,aes(x=grp,y=cnt))+
    geom_point(position=position_jitter(w = 0.2, h = 0))
```

**Comment by thomasp85** [comment]
that is because the box plot shows outlier points, thus any outlier point will be shown twice (one jittered, one not)
