### ISSUE TITLE
Unexpected (?) orientation with geom_col

### ISSUE THREAD

**Issue by m1kejay** [tidyverse/ggplot2#3932]
I'm using ggplot2 v3.3.0.9000. The orientation of the `geom_col` bars is not correct when values of x are numeric and less than 1. Specifying `orientation = "x"` does what I would expect should be default behaviour. From reading the documentation (https://ggplot2.tidyverse.org/reference/geom_bar.html), it does state `x` is the default oreintation but that doesn't seem to be the case here.

``` r
library(tidyverse)

df <-
data.frame(
           x = c(0.1, 0.2, 0.3),
           y = c(10L, 20L, 30L)
      )
  
ggplot(df) +
  geom_col(aes(x = x, y = y))
```

![](https://i.imgur.com/1cqdzTG.png)

``` r


ggplot(df) +
  geom_col(aes(x = x * 10, y = y))
```

![](https://i.imgur.com/nP5TQIO.png)

``` r

ggplot(df) +
  geom_col(aes(x, y), orientation = "x")
```

![](https://i.imgur.com/GZmMZvx.png)

**Comment by yutannihilation** [comment]
Thanks, confirmed. This is because `c(10, 20, 30)` is considered more "discrete-like" than `c(0.1, 0.2, 0.3)` in our current logic. But, I'm not immediately sure if this should be flipped or not...

https://github.com/tidyverse/ggplot2/blob/bca610524b6ccc47e76aa7471b67d7335e18d9f4/R/utilities.r#L600-L602

**Comment by m1kejay** [comment]
Hmm interesting, thanks for the insight. I don't really have strong feelings either way (after writing the below.... maybe I do :) ).  I'm not sure why `10, 20, 30` should be prioritised over `0.1, 0.2, 0.3`. Here's a small sample of data that I was orignally trying to plot when I ran into this issue:

```r
tibble::tribble(
    ~x,   ~y,
  0.05, 303L,
   0.1, 202L,
  0.15, 134L,
   0.2,  67L,
  0.25,  29L,
   0.3,  10L
  )
```

In this instance while `x` is not an integer it is an evenly spaced set unlike `y`. To me, it seems obvious what the orientation should be or at the very least, I think this should return an ambiguous result.

In fact, having looked at the source code you just linked, it seems the following lines do try to figure this out:

https://github.com/tidyverse/ggplot2/blob/bca610524b6ccc47e76aa7471b67d7335e18d9f4/R/utilities.r#L631-L632

This seems to fail though with non-integer numbers (like mine):

``` r
x <- seq(0.05, 0.3, 0.05)
x_diff <- diff(sort(x))
x_diff <- x_diff[x_diff != 0]

all((x_diff / min(x_diff)) %% 1 < .Machine$double.eps)
#> [1] FALSE

# Integers
x <- seq(1, 6, 1)
x_diff <- diff(sort(x))
x_diff <- x_diff[x_diff != 0]

all((x_diff / min(x_diff)) %% 1 < .Machine$double.eps)
#> [1] TRUE
```

Could this be fixed by introducing some tolerance similiar to `near()` (https://dplyr.tidyverse.org/reference/near.html)?

``` r
x <- seq(0.05, 0.3, 0.05)

x_diff <- diff(sort(x))
x_diff <- x_diff[x_diff != 0]

all((x_diff / min(x_diff)) %% 1 < .Machine$double.eps^0.5)
#> [1] TRUE
```

**Comment by dmurdoch** [comment]
This example on SO seems to choose non-deterministically:  https://stackoverflow.com/q/61235860/2554330.  I saw both of the plots in `ggplot2` 3.3.0; the only difference was what code I had run before.    I can't reliably reproduce the desired plot (`orientation = "x"`), I usually get the other.

**Comment by m1kejay** [comment]
Is that SO yours? I have just tried executing/knitting that code many times and I consistently only get the incorrect orientiation (the output matched the second figure) or the correct orientiation if I add `orientation = "x"`.  But you see both orientations without modifying `orientation`?

From what I can tell, it seems that the example in the SO post suffers the same problem as my code above:

``` r
x <- c(-9.4, -9.3, -9.2, -9, -8.9, -8.8, -8.7, -8.5, -8.4, -8.3, 0)

x_diff <- diff(sort(x))
x_diff <- x_diff[x_diff != 0]

(x_diff / min(x_diff)) %% 1
#>  [1] 0.000000e+00 1.776357e-14 0.000000e+00 0.000000e+00 0.000000e+00
#>  [6] 1.776357e-14 0.000000e+00 0.000000e+00 0.000000e+00 2.984279e-13

all((x_diff / min(x_diff)) %% 1 < .Machine$double.eps)
#> [1] FALSE

all((x_diff / min(x_diff)) %% 1 < .Machine$double.eps^0.5)
#> [1] TRUE
```

**Comment by dmurdoch** [comment]
I thought I did see both, but now when I re-run it, I can't get the "x" orientation again.  What might have happened is that I accidentally edited the data to contain non-integer `y` values, then undid my edit.

My taste would run to a much simpler rule:  if one axis is a factor, that determines orientation.  If not, default to "x".

**Comment by yutannihilation** [comment]
The SO says

> I have noticed that after loading the tidyverse package, some versions are different. For example, in the first one ggplot is 3.2.1, while in the later it is 3.3.0. 

So, I'm not sure if this is the same issue as you encountered.

> My taste would run to a much simpler rule: if one axis is a factor, that determines orientation. If not, default to "x".

Yeah, true. The difficulty is that the current logic determines the orientation at the stage where there's no information about the type of axis...

**Comment by titaniumtroop** [comment]
It appears that repeated values of y will trigger `orientation = "y"` behavior (i.e., geom_col produces horizontal bars, rather than vertical), even if y is numeric. Reprex:

``` r
df <- data.frame(
  x = seq(from = 100, to = 300, length.out = 20), 
  y = (rep(6.5:10.5, 4)), 
  z = factor(c(rep(1, 5), rep(2, 5), rep(3, 5), rep(4, 5)))
)

ggplot2::ggplot(df, ggplot2::aes(x, y, fill = z)) +
  ggplot2::geom_col(position = "dodge")
```

![](https://i.imgur.com/9BUr0mE.png)

<sup>Created on 2020-04-24 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

According to the documentation for geom_col, this appears to be one of the rare events where determining orientation from aesthetic mapping fails.
