### ISSUE TITLE
`stat_qq` might be broken; specifying `x` doesn't work

### ISSUE THREAD

**Issue by CGMossa** [tidyverse/ggplot2#3934]
My goal was to compare the empirical distribution of two vectors, and for that I wanted a quick plot to illustrate this: That's the use-case for `qqplot` in base r, and I assumed the same for `ggplot2::stat_qq`. In the help files for `stat_qq`, under `distribution parameter it says:

> Distribution function to use, if x not specified

But I am specifying `x`.

``` r

library(ggplot2)
ggplot(iris, aes(sample = Sepal.Length)) +
  stat_qq()
```

![](https://i.imgur.com/0si71Ag.png)

``` r

ggplot(iris, aes(x = Sepal.Width, sample = Sepal.Length))+
  stat_qq()
#> Error: geom_point requires the following missing aesthetics: x
```

``` r

#expected something similar to this:
qqplot(iris$Sepal.Width, iris$Sepal.Length)
abline(0, 1)
```

![](https://i.imgur.com/CMfiwvt.png)

<sup>Created on 2020-04-08 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by clauswilke** [comment]
Seems related: #3901

**Comment by smouksassi** [comment]
A workaround can be found here: https://stats.stackexchange.com/questions/12392/how-to-compare-two-datasets-with-q-q-plot-using-ggplot2

**Comment by clauswilke** [comment]
Right now `stat_qq()` doesn't have the functionality to take two data vectors as input. I'm not sure whether this is actually reasonably possible within the ggplot2 framework or whether we'd have to define a separate stat that works on two data vectors. It's conceptually somewhat different so having a separate stat may be preferable.

Having said that, I don't like the behavior of `qqplot()`. In the following two examples, it doesn't make sense to me that there's always five points. One of the two examples should show ten points.

``` r
qqplot(1:5, 1:10)
```

![](https://i.imgur.com/IWJkB11.png)

``` r
qqplot(1:10, 1:5)
```

![](https://i.imgur.com/6VAbXAp.png)

<sup>Created on 2020-04-08 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

The way to implement or simulate this with `stat_qq()` is to implement a function that turns a vector into an empirical quantile function.

``` r
library(ggplot2)

qemp <- function(x) {
  z <- sort(na.omit(x))
  n <- length(z)
  function(p) {
    approxfun(0:(n-1)/(n-1), z)(p)
  }
}

ggplot(iris, aes(sample = Sepal.Length))+
  stat_qq(distribution = qemp(iris$Sepal.Width))
```

![](https://i.imgur.com/yK2807f.png)

``` r

ggplot(data.frame(), aes(sample = 1:5))+
  stat_qq(distribution = qemp(1:10))
```

![](https://i.imgur.com/KGiy1GX.png)

``` r

ggplot(data.frame(), aes(sample = 1:10))+
  stat_qq(distribution = qemp(1:5))
```

![](https://i.imgur.com/JmKQVcA.png)

<sup>Created on 2020-04-08 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by clauswilke** [comment]
Also, there's different ways in which you an convert a data vector into a quantile function (you can interpolate, as I do here, or you can fit a normal distribution to the data, etc.), and maybe a stat that supports this feature should offer different alternatives (like the `method` argument in `stat_smooth()`).

**Comment by thomasp85** [comment]
This functionality is unlikely to be adapted into ggplot2. I'd suggest creating a request in an extension package where it might fit
