### ISSUE TITLE
geom_raster ignores color

### ISSUE THREAD

**Issue by bhogan-mitre** [tidyverse/ggplot2#3935]
Color is listed as a parameter in the documentation for `geom_tile`/`geom_rect`/`geom_raster`, but is ignored for `geom_raster`.  Based on the documentation and the behavior of other geoms, I would expect that color would be applied for `geom_raster`.

```r
library(ggplot2)
df <- expand.grid(x = 0:5, y = 0:5)
df$z <- runif(nrow(df))
ggplot(df, aes(x, y, fill = z)) + geom_raster(color = "black")
```
<img width="471" alt="Screen Shot 2020-04-08 at 6 51 51 AM" src="https://user-images.githubusercontent.com/32336739/78776191-73d1ab80-7965-11ea-99db-dbf592ff4261.png">

**Comment by thomasp85** [comment]
Yeah, the documentation is not very clear on this as it only lists the possible mappings for `geom_tile()`. We should fix this

**Comment by yutannihilation** [comment]
@bhogan-mitre 
You can just use `geom_tile()`.

``` r
library(ggplot2)

df <- expand.grid(x = 0:5, y = 0:5)
df$z <- runif(nrow(df))
ggplot(df, aes(x, y, fill = z)) + geom_tile(colour = "black")
```

![](https://i.imgur.com/1Z4edGR.png)

<sup>Created on 2020-04-08 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by bhogan-mitre** [comment]
Indeed, that is my workaround @yutannihilation, thanks.  It look me a little while to figure out what was happening though.

@thomasp85, I'm curious when you say to fix it are you thinking to clarify this behavior in the documentation or to support color from `geom_raster`?  Is there something fundamental blocking color here?

**Comment by thomasp85** [comment]
A fix would be to clarify the documentation. geom_raster is intended to draw tiles as "pixels" which doesn't have a border by their very nature

**Comment by bhogan-mitre** [comment]
Got it, thanks.
