### ISSUE TITLE
geom_dotplot() overflows

### ISSUE THREAD

**Issue by Bisaloo** [tidyverse/ggplot2#3937]
Reprex:

``` r
library(ggplot2)

ggplot(diamonds, aes(x = cut)) + 
  geom_dotplot()
#> `stat_bindot()` using `bins = 30`. Pick better value with `binwidth`.
```

![](https://i.imgur.com/QSZG4zK.png)

<sup>Created on 2020-04-08 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

The y-axis doesn't expand enough to include all dots and no amount of `expand_limits()` can fix it.

I have checked other issues on `geom_dotplot()`, including those on displaying the count on the y-axis, and I believe this is a different issue.

**Comment by ptoche** [comment]
``geom_dotplot`` doesn't work in a very intuitive way...

**Comment by thomasp85** [comment]
This is expected behaviour. The issue is basically that any dot plot requires a certain aspect ratio to be contained in the plot, but that any resizing can mess that up
