### ISSUE TITLE
Legend keys from geom_sf() change upon repeat printing of the same plot

### ISSUE THREAD

**Issue by francisko-rezende** [tidyverse/ggplot2#3941]
I'm having a super weird issue with `ggsave` and, after [sharing it at RStudio community](https://community.rstudio.com/t/legend-keys-from-geom-sf-in-pdfs-created-using-ggsave-dont-match-what-is-displayed-in-the-plots-window-nor-the-output-from-rstudios-export/60722/4), Mara Averick suggested I open an issue here. So here I am 😅 

Basically, the legends of plots I generate using `ggsave` do not match what is displayed in RStudio's "Plots" window nor the legends of plots I generate using RStudio's "Export" option. This is happening for maps created using `geom_sf`.

Here's an example:

``` r
library(rnaturalearth)
library(ggplot2)

world <-
  rnaturalearth::ne_countries(scale = "medium", returnclass = "sf") # creates a r object  called "world" with spatial data

ggplot2::ggplot(data = world) + #starts plot with "world" as its data
  geom_sf(aes(color = continent), show.legend = "point") # draws map with colored continent outlines
```

![](https://i.imgur.com/ViGt452.png)

<sup>Created on 2020-04-10 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

As you can see, the map above has points as its legend key. That is the output I wanted to get, however, when I use `ggsave("ggsave_test.pdf")` to save the map as a pdf file this is what I get:
![image](https://user-images.githubusercontent.com/39991049/79004721-a3470a80-7b55-11ea-8af3-7185905ef36b.png)

The weird thing is that this problem seems to be exclusive to ggsave since saving the plot using RStudio's "Export" functionality or knitting a Rmarkdown document result in the plot having points as its legend key.

This happens for .ps, .pdf, .jpeg, .tiff, .png, .bmp, and .svg files both when leaving `ggsave()`'s plot argument  blank (e.g., when it uses `last_plot()` like in the reprex above), and when using the saved map as the argument for plot. There's an exception though I used `purrr::walk` to test the different file formats and the .eps file that was generated using the named map as ggsave()'s "plot" argument has the points as its key ! The plots generated using ggsave(filename = here::here("ggsave_no_loop.eps"), plot = map), and `purrr::walk` without the named map as plot's argument have the squares as their keys though.

I think this might be a macOS-specific issue (or even something that is happening only in my computer) because this problem doesn't happen in rstudio.cloud.

Cheers and thanks for your amazing work!

**Comment by clauswilke** [comment]
I can confirm this problem.

**Comment by clauswilke** [comment]
It looks like the problem is the use of the `last_plot()` function, not `ggsave()`. I suspect the `show.legend` parameter is dropped when the plot is cloned.

``` r
library(rnaturalearth)
library(ggplot2)

world <-
  rnaturalearth::ne_countries(scale = "medium", returnclass = "sf") # creates a r object  called "world" with spatial data

ggplot(data = world) + 
  geom_sf(aes(color = continent), show.legend = "point")
```

![](https://i.imgur.com/SCCdXNI.png)

``` r

last_plot()
```

![](https://i.imgur.com/b1gZE0r.png)

<sup>Created on 2020-04-10 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by clauswilke** [comment]
Simpler reprex. Just printing the same plot twice triggers the problem.

``` r
library(ggplot2)

nc <- sf::st_read(system.file("shape/nc.shp", package = "sf"), quiet = TRUE)
p <- ggplot(nc[1:3, ]) +
  geom_sf(aes(color = NAME), show.legend = "point")

p
```

![](https://i.imgur.com/0b0QxcR.png)

``` r
p
```

![](https://i.imgur.com/8VYmotU.png)

<sup>Created on 2020-04-10 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by clauswilke** [comment]
The problem is in this line:
https://github.com/tidyverse/ggplot2/blob/b41e1b93504402b7fdb56e28c83efab144d40654/R/layer-sf.R#L53

When we added it, we got confused about when it is executed. It is only executed when the plot is built, not when it is originally constructed. As a consequence, the legend type changes to the default after one printing.

``` r
library(ggplot2)

nc <- sf::st_read(system.file("shape/nc.shp", package = "sf"), quiet = TRUE)
p <- ggplot(nc[1:3, ]) +
  geom_sf(aes(color = NAME), show.legend = "point")
p$layers[[1]]$show.legend
#> [1] "point"
invisible(ggplot_build(p))
p$layers[[1]]$show.legend
#> [1] TRUE
```

<sup>Created on 2020-04-10 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by FriGruner** [comment]
Hi Claus, I am experiencing exactly the same issue with geom_ribbon_pattern. Is there a chance that you could fix this, too? Thanks a lot!

**Comment by clauswilke** [comment]
@FriGruner Please open a new issue and provide a complete, reproducible example. Refer to this issue here for reference.

**Comment by clauswilke** [comment]
Also, I'm not aware that `geom_ribbon_pattern()` even exists, so you may want to check that this is even a ggplot2 problem.
