### ISSUE TITLE
Problems with axis limits?

### ISSUE THREAD

**Issue by gael-millot** [tidyverse/ggplot2#3948]
I believe I have some trouble when setting axis limits. The first is with `scale_y_continuous()`:

```r
# data
library(ggplot2)
ylim <- c(6, 30)
obs1 <- data.frame(
Time = 1:20, 
Group1 = rep(c("G", "H"), times = 10), 
Group2 = rep(c("A", "B"), each = 10)
)

obs1
```
![image](https://user-images.githubusercontent.com/61543802/79367720-a0ca2380-7f4e-11ea-8f61-7c7414811a79.png)

```r
# bars not displayed if 0 is not in the ylim range (test ylim = c(-1, 30))
# The problem is reported with a warning: all the values are removed when 0 is not in the range
p <- ggplot(data = obs1, mapping = aes(y = Time, x = Group2, fill = Group1)) 
p +
geom_bar(stat = "identity", position = position_dodge()) + 
scale_y_continuous(limits = sort(ylim))
```
![image](https://user-images.githubusercontent.com/61543802/79366450-80996500-7f4c-11ea-9aea-e7818ed5e3b1.png)

```r
# bars displayed whatever the ylim range
p + 
geom_bar(stat = "identity", position = position_dodge()) + 
coord_cartesian(ylim = sort(ylim))
```
![image](https://user-images.githubusercontent.com/61543802/79366467-88f1a000-7f4c-11ea-9bad-70d2034b38f0.png)

The reason why I use `coord_cartesian(ylim = sort(ylim))` in most of my functions. However, I encountered a new problem:
```r
# y-axis disappearing
p + 
geom_point() + 
coord_cartesian(ylim = sort(ylim)) + 
scale_y_reverse()
```
![image](https://user-images.githubusercontent.com/61543802/79366530-a6266e80-7f4c-11ea-8361-ba218e25d895.png)

```r
# y-axis not disappearing
p + 
geom_point() + 
scale_y_continuous(limits = sort(ylim)) + 
scale_y_reverse()
```
![image](https://user-images.githubusercontent.com/61543802/79366557-ade61300-7f4c-11ea-9f22-0d92bf18a0ec.png)

Are all these expected ?

Many thanks for your help.

Best.

**Comment by yutannihilation** [comment]
> Are all these expected ?

For the first one (bar chart), yes. For the second one, you need to reverse the range.

``` r
library(ggplot2)

ylim <- c(6, 30)
obs1 <- data.frame(
  Time = 1:20,
  Group1 = rep(c("G", "H"), times = 10),
  Group2 = rep(c("A", "B"), times = 10)
)

p <- ggplot(obs1, aes(Group2, Time, fill = Group2))

p +
  geom_point() +
  coord_cartesian(ylim = rev(ylim)) +
  scale_y_reverse()
```

![](https://i.imgur.com/RRZOPXv.png)

<sup>Created on 2020-04-16 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by gael-millot** [comment]
Many thanks for the feedback.

To make things clear:
1) the `limits` argument of `scale_._continuous()` and derivatives, like `scale_._reverse()`, `lims()`, etc., remove data outside the `limits` settings, which generates no bars using `geom_bar()` except if zero is in the axis range.

2) It is possible to prevent the data removal action of `scale_._continuous()` and derivatives, using a function from the `scales` package:
```r
library(scales)
p <- ggplot(data = obs1, mapping = aes(y = Time, x = Group2, fill = Group1)) 
p +
geom_bar(stat = "identity", position = position_dodge()) + 
scale_y_continuous(limits = sort(ylim), oob = scales::rescale_none)
```
![image](https://user-images.githubusercontent.com/61543802/79472671-69b64980-8004-11ea-9429-48ed2ee16bc8.png)

3) the `coord_cartesian()` function does not remove data, but performs a zoom. However, its `xlim` and `ylim` arguments must be in the same orientation than `scale_._continuous()` and derivatives. Otherwise no axis is drawn.

Is that correct ?

Thanks.

**Comment by yutannihilation** [comment]
> Is that correct ?

Yes, I think your understanding is correct. That said, 

> Otherwise no axis is drawn.

I'm not sure if this is the desired behaviour (Should this be errored? Or, is this a bug?). Let me file a new issue for this.

**Comment by gael-millot** [comment]
Thanks a lot !

**Comment by urlrequestedgar40** [comment]
@gael-millot https://python-collections699.github.io/X8Qm7PR6N5LOLBbXUpU8WtQrRGoJi7Qia-DIlVBRoqztkPhw82yAHe1AJDmA_JNnBeI/
