### ISSUE TITLE
Possible bug in coord_sf reprojection of vector data (Natural Earth coastline to Robinson projection)

### ISSUE THREAD

**Issue by AndrewCunliffe** [tidyverse/ggplot2#3949]
Reprojection of the small scale Natural Earth coastline dataset to a Robinson projection returns an erroneous line feature on the plot. (Apologies if this is the wrong place to report, but it appears to be an issue with coord_sf rather than the Natural Earth vector dataset).

Medium-scale coastlines reproject okay to a World Robinson projection (EPSG:54030)
`coastlines <- ne_coastline(scale = "medium", returnclass = "sf")`
`ggplot(data = coastlines) +
            geom_sf(colour = "black") +
            coord_sf(crs = st_crs(54030)) +
            theme_bw()`
![Global map from R 1](https://user-images.githubusercontent.com/25197948/79444912-bc2b4200-7fd3-11ea-9080-03ebe186531c.png)

Small-scale coastlines display okay at the default projection
`coastlines <- ne_coastline(scale = "small", returnclass = "sf")`
`ggplot(data = coastlines) +
          geom_sf(colour = "black") +
          theme_bw()`
![Global map from R 3](https://user-images.githubusercontent.com/25197948/79444961-cd744e80-7fd3-11ea-89b7-90550a7e1527.png)

Small-scale coastlines reprojected to the World Robinson projection (EPSG:54030) include the erroneous line feature at ca. 70 degrees north
`coastlines <- ne_coastline(scale = "small", returnclass = "sf")`
`ggplot(data = coastlines) + geom_sf(colour = "black") +  coord_sf(crs = st_crs(54030)) + theme_bw()`
![Global map from R 2](https://user-images.githubusercontent.com/25197948/79444953-c8af9a80-7fd3-11ea-9399-62856dabe2f9.png)

**Comment by AndrewCunliffe** [comment]
![Global map from R 1](https://user-images.githubusercontent.com/25197948/79444878-afa6e980-7fd3-11ea-9134-82e9999718dd.png)
![Global map from R 2](https://user-images.githubusercontent.com/25197948/79444883-b03f8000-7fd3-11ea-9b1c-35a7001c6ce8.png)
![Global map from R 3](https://user-images.githubusercontent.com/25197948/79444884-b0d81680-7fd3-11ea-9fe8-398c8c3b0d25.png)

**Comment by clauswilke** [comment]
Such bugs are almost always due to the underlying projection library, not to ggplot2. At a minimum, I think you should report this to the sf project: https://github.com/r-spatial/sf Most likely though they won't be able to do anything about this either, because it happens at an even lower level.

**Comment by AndrewCunliffe** [comment]
Thanks Claus, as suggested I've reported this to the SF project ([issue 1372](https://github.com/r-spatial/sf/issues/1372))
