### ISSUE TITLE
Suggestion: `rel`-class can inherit value from `unit`-class theme elements

### ISSUE THREAD

**Issue by teunbrand** [tidyverse/ggplot2#3951]
I know `rel` objects are not really supported as theme elements on their own, but since the `size` argument in `element_line/rect/text()` can take a `rel` object and inherit the (modified) value from the parent, it doesn't seem like too far a stretch to have child `rel` theme elements.

Suppose you'd like your legend keys to be half as tall as usual, it would be neat if you could do the following:

``` r
library(ggplot2)

ggplot(iris, aes(Sepal.Length, Sepal.Width)) +
  geom_point(aes(colour = Species)) +
  theme(legend.key.height = rel(0.5))
#> Error: Theme element `legend.key.height` must be an `unit` object.
```
<sup>Created on 2020-04-18 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

I think it would require changes at these locations.

* This check would have to allow `rel` classes for `unit` elements

https://github.com/tidyverse/ggplot2/blob/7e6d1259237d9a2b48b8156e62ada2c47c411f31/R/theme.r#L530-L533

* This might need an extra logical branch for `rel`-`rel` and `rel`-`unit` elements  

https://github.com/tidyverse/ggplot2/blob/7e6d1259237d9a2b48b8156e62ada2c47c411f31/R/theme.r#L665-L668

* Don't allow `rel` objects as 'root'-nodes in the element tree. I think the most appropriate spot to do this would be in `validate_element()`.

https://github.com/tidyverse/ggplot2/blob/40f67518a8d0ee8d7b6a1d1851c206656864fac8/R/theme-elements.r#L508

Thanks for considering!

**Comment by thomasp85** [comment]
I don't see any problem in allowing this, though I can not say when we will add it
