### ISSUE TITLE
No ticks when the limit of Coord is in the opposite order to the Scale

### ISSUE THREAD

**Issue by yutannihilation** [tidyverse/ggplot2#3952]
(Originally reported at #3948)

Should the `p1` below be errored? Or, should the ticks be drawn?

``` r
library(ggplot2)
library(patchwork)

d <- data.frame(
  x = 1:4,
  y = 1:4
)

p <- ggplot(d, aes(x, y)) +
  geom_point() +
  scale_y_reverse()

p1 <- p + coord_cartesian(ylim = c(1, 10))
p2 <- p + coord_cartesian(ylim = c(10, 1))
p1 / p2
```

![](https://i.imgur.com/uCdvaFf.png)

<sup>Created on 2020-04-19 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by clauswilke** [comment]
I think axis ticks should be drawn. Note that the problem exists even without `scale_y_reverse()`.

``` r
library(ggplot2)
library(patchwork)

d <- data.frame(
  x = 1:4,
  y = 1:4
)

p <- ggplot(d, aes(x, y)) +
  geom_point()

p1 <- p + coord_cartesian(ylim = c(1, 10))
p2 <- p + coord_cartesian(ylim = c(10, 1))
p1 / p2
```

![](https://i.imgur.com/qbR5q69.png)

<sup>Created on 2020-04-18 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by yutannihilation** [comment]
Oh, I didn't notice it... Thanks.

**Comment by yutannihilation** [comment]
Under the hood, this seems a problem of scale. Here, `scale$get_breaks(continuous_range)` returns `NA`s if the `continuous_range` is in the opposite order.

https://github.com/tidyverse/ggplot2/blob/d3d47be055055ebf328aeed0bebb990a635c49ab/R/scale-view.r#L19

``` r
library(ggplot2)

scale <- scale_x_continuous()
scale$train(c(1, 3, 5))
scale$get_breaks(c(1, 5))
#> [1] 1 2 3 4 5
scale$get_breaks(c(5, 1))
#> [1] NA NA NA NA NA
```

In addition, I don't have no idea what is the expected behaviour in the case below. Should this be errored...?

``` r
d <- base::data.frame(
  x = 1:4,
  y = 1:4
)

p <- ggplot(d, aes(x, y)) +
  geom_point()

p + scale_y_continuous(limits = c(10, 1))
#> Warning: Removed 4 rows containing missing values (geom_point).
```

![](https://i.imgur.com/Or9hiic.png)

<sup>Created on 2020-04-22 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
