### ISSUE TITLE
Remove stat and position arguments from qplot() and formaly deprecate the function

### ISSUE THREAD

**Issue by yutannihilation** [tidyverse/ggplot2#3956]
`stat` and `position` were deprecated 4.5 years ago ([v2.0.0](https://ggplot2.tidyverse.org/news/index.html#deprecated-features)), so I think it's time to remove them. I think we have no development bandwidth to fix such tricky bugs like https://github.com/tidyverse/ggplot2/issues/3670.

Also, can we agree on deprecating `qplot()` itself? Though we've never discussed this formally, I believe the use of `qplot()` is discouraged, which virtually means it's deprecated.

**Comment by clauswilke** [comment]
I think this is a great idea.

**Comment by etiennebr** [comment]
I won't win a popularity contest I guess, but I must say I use `qplot` quite often when doing interactive analysis and before deciding to use the whole ggplot scaffold. However, I reorder the arguments to make it pipeable:
``` r
#' Create quick and tidy plots
qtplot <- function(data = data, ...) ggplot2::qplot(..., data = data)

mtcars %>% qtplot(mpg, cyl)
```
This is not the battle I will die for, but I wanted to bring another voice.

**Comment by yutannihilation** [comment]
In my understanding, though we're deprecating `qplot()`, it's not that `qplot()` is totally useless, but it's just inconsistent to include the function outside of Grammar of Graphics in ggplot2. We sometimes want a shortcut for common usages and it's fine to use it as long as you know when you shouldn't. But, it's not the case for most of the ggplot2 beginners. Personally, I hope some nicer version of `qplot()` will be born as an extension package...

**Comment by dcgerard** [comment]
Just wanted to add that I really like `qplot()`! When I teach a non-R course (like regression) and have very little time to teach R, it's very easy to teach students `qplot()`, and this gives them most of what they need, without having to go through full ggplot.

**Comment by bwiernik** [comment]
> Just wanted to add that I really like `qplot()`! When I teach a non-R course (like regression) and have very little time to teach R, it's very easy to teach students `qplot()`, and this gives them most of what they need, without having to go through full ggplot.

For this sort of context, you might consider using a package that let's you skip having to specifically teach *ggplot2* entirely by providing automatic plots for common uses. For example, the *easystats* packages can produce automatic diagnostic and predictions plots for regression without needing to teach the nuances of ggplot2: https://easystats.github.io/easystats/

**Comment by fab4ap** [comment]
I find qplot to be extremely useful for multiple uses since it provides a simple intuitive format. Wonder why there is need to deprecate it. If somebody wants a richer and more complicated version, they can always use ggplot!

**Comment by thomasp85** [comment]
Because maintaining the function is more trouble than it is worth and it can hinder users in learning to use the more powerful grammar API.

**Comment by fab4ap** [comment]
I get the first part but not how it can hinder users (if they want to learn the more powerful API, they can!) :)

**Comment by thomasp85** [comment]
You can easily get trapped in a constrained API for longer than needed. The existence of two orthogonal APIs where one of them is severely constrained will def keep some users in the constrained one longer than is good
