### ISSUE TITLE
geom_boxplot() on continuous x-axis is flipped unexpectedly(?)

### ISSUE THREAD

**Issue by yutannihilation** [tidyverse/ggplot2#3957]
Still not sure if this should be flipped or not, but let me file this issue here.

``` r
library(ggplot2)

d <- dplyr::filter(diamonds, carat < 3)
ggplot(d, aes(x = carat, y = price)) +
  geom_boxplot(aes(group = cut_width(carat, 0.1)))
```

![](https://i.imgur.com/sHVJoVV.png)

<sup>Created on 2020-04-22 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by thomasp85** [comment]
hmm... I wonder why it does that. I think we have agreed that in any form of ambiguity it should not flip

**Comment by yutannihilation** [comment]
> I think we have agreed that in any form of ambiguity it should not flip

Ah, yes. Thanks.
