### ISSUE TITLE
ggplot extensions gallery link dead

### ISSUE THREAD

**Issue by robincrlee** [tidyverse/ggplot2#3968]
When I tried to access https://www.ggplot2-exts.org/gallery/, the browser shows an error message of The requested URL was not found on this server. 

Not sure if this site is down for others.

**Comment by robincrlee** [comment]
Should the link be updated to https://exts.ggplot2.tidyverse.org/gallery/ instead?

**Comment by yutannihilation** [comment]
Yeah, it's already fixed on the dev site, but not on the stable site, unfortunately.

https://ggplot2.tidyverse.org/dev/
