### ISSUE TITLE
Hint to where to alter within ggplot (for extension)

### ISSUE THREAD

**Issue by Athanasiamo** [tidyverse/ggplot2#3985]
Hi.

I've been trying to figure this out for quite some time now and am still not getting anywhere. Every time i seem to _almost_ get there, and then that turns out to be a dead end. So I'm biting the bullet and asking for some tips. 

I'm trying to make an sf-extension geom. the geom itself is more or less working as I want, but I'm struggling to figure out where to alter something within the proto itself. 

The change is seemingly simple, since the graticule in this setting bears no meaning, I want to replace it with information calculated from the data. It needs to be based on the data as prepared by the proto, not as given to the ggplot function ( i.e. the data frame with x, y, fill etc. columns). 

I can achieve what I'm after by using scales:

``` r
library(ggplot2)
nc <- sf::st_read(system.file("shape/nc.shp", package = "sf"), quiet = TRUE)
ggplot(nc) +
  geom_sf(aes(fill = AREA)) +
  scale_x_continuous(breaks = c(-82, -78),
                     labels = c("string1", "string2")) +
  scale_y_continuous(breaks = c(34, 36),
                     labels = c("string3", "string4"))
```

![](https://i.imgur.com/n5YlhiR.png)

<sup>Created on 2020-05-04 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

But I am after this happening within the geom call itself, not as something extra. but that would be overwritten by someone using the scales of course. 

I was looking into `coord$fixup_graticule_labels` but within coord it self I could not find a way to call the actual data to create a new graticule based on it.

Not looking for a solution, but rather an idea of where I should be looking. 

Thanks for any advice!

**Comment by thomasp85** [comment]
Can you describe more clearly what it is you want your geom extension to do? Do you want it to take control of the graticule? If so then your geom will begin to venture outside of its jurisdiction which will begin to break down the grammar

**Comment by Athanasiamo** [comment]
Thanks for getting back to me. 

Background: I have a geom working which creates brain atlases as geom_sf (rather than polygons I had before, its easier to create the sf's than polygons). The geom merges data with another object of class brain- atlas (sub-class of data.frame with a geometry column), then plots the atlas.

```r
> glimpse(dk)
Rows: 90
Columns: 9
$ atlas    <chr> "dk", "dk", "dk", "dk", "dk", "dk", "dk", "dk", "dk", "dk", "dk", "dk", "dk",…
$ type     <chr> "cortical", "cortical", "cortical", "cortical", "cortical", "cortical", "cort…
$ hemi     <chr> "left", "left", "left", "left", "left", "left", "left", "left", "left", "left…
$ side     <chr> "lateral", "lateral", "lateral", "lateral", "lateral", "lateral", "lateral", …
$ region   <chr> NA, "bankssts", "caudal middle frontal", "fusiform", "inferior parietal", "in…
$ label    <chr> NA, "lh_bankssts", "lh_caudalmiddlefrontal", "lh_fusiform", "lh_inferiorparie…
$ roi      <chr> "0001", "0002", "0004", "0008", "0009", "0010", "0012", "0013", "0016", "0019…
$ geometry <MULTIPOLYGON> MULTIPOLYGON (((84.32563 34..., MULTIPOLYGON (((214.8215 10..., MULT…
$ ggseg    <list> [<tbl_df[12 x 6]>, <tbl_df[23 x 6]>, <tbl_df[29 x 6]>, <tbl_df[19 x 6]>, <tb…
```
in this case, since there is no data supplied, the whole plot is only based on values in the atlas it self.

```r
ggplot() +
  geom_brain(atlas = dk, aes(fill = region),
             # position = position_brain(hemi + side ~ .),
             show.legend = FALSE) +
  scale_fill_brain()
```

![Screenshot 2020-08-31 at 15 12 46](https://user-images.githubusercontent.com/14014329/91723790-9c6c7300-eb9c-11ea-9cdf-913e3b5676ac.png)

By default the axis ticks gives coordinates, which makes sense when your coordinates have meaning. In our case, the coordinates actually have no true meaning, and we'd rather it displayed information regarding what people are seeing. And this can be inferred from the atlas data, because I designed it so.

![image](https://user-images.githubusercontent.com/14014329/91724148-287e9a80-eb9d-11ea-90e4-3ee5197be108.png)


But I definitely do not want to break the grammar, that is a type of mess I want to avoid.  I was just hoping there was a way to emulate what I can manage to do with the `scale_x/y_continuous` functions from within the geom it self. It can be quite  tricky to distinguish left and right in these plots if one is not used to them (and there are also other variants that can be inferred from the data), so I really wanted to give that aid.

**Comment by clauswilke** [comment]
I think the best solution for you is to just make your `geom_brain()` function call add scales also. Just like `geom_sf()` adds a coord:
https://github.com/tidyverse/ggplot2/blob/813d0bd8c7d4df3b3cba170de54233076b346c1c/R/geom-sf.R#L213-L232

**Comment by thomasp85** [comment]
Was going to suggest something along those lines as well.

The best will probably be to make a dedicated coord and add that since users are likely to replace the scales quite often.

**Comment by Athanasiamo** [comment]
if I understand correctly, I would add my custom scales right below the coord call? I've never really understood how that works, but I can play around and see if I can figure it out. 

if I did that to geom_sf (just as an example), it would look something like:

```r
 geom_sf <- function(mapping = aes(), data = NULL, stat = "sf", 
                     position = "identity", na.rm = FALSE, show.legend = NA, 
                     inherit.aes = TRUE, ...) { 
   c( 
     layer_sf( 
       geom = GeomSf, 
       data = data, 
       mapping = mapping, 
       stat = stat, 
       position = position, 
       show.legend = show.legend, 
       inherit.aes = inherit.aes, 
       params = list( 
         na.rm = na.rm, 
         ... 
       ) 
     ), 
     coord_sf(default = TRUE) ,
     scales_sf(),
   ) 
 } 
```

**Comment by Athanasiamo** [comment]
sorry, I got the message from @thomasp85  a little lagged here. You're suggesting creating another coord, which I have tried unsuccessfully. But a break like I've had on this also usually helps me get further, so maybe I can manage this time.

**Comment by thomasp85** [comment]
To be clear I think that the best solution is the one that works and if that means adding scales I would do that. But I would suggest looking into a coord that draws the correct background grid and leave the scales to the users

**Comment by clauswilke** [comment]
To write a new coord you'd derive from the `CoordSf` ggproto object and only change what needs changing. A minimal implementation wouldn't change anything.

Having said that, if it were me I'd probably add scales.

**Comment by Athanasiamo** [comment]
After some more painful attempts in both scales and coord, I'm starting to be afraid what I am after might not actually be possible. And I believe the problem comes mainly from me having made a special position, and I am not able to capture the data _after_ the position has been applied. 

## Details  
as default, the brain data sf-polygons are in one row

```r
ggplot() +
  geom_brain(atlas = dk, aes(fill = region),
             show.legend = FALSE) +
  scale_fill_brain()
````
![image](https://user-images.githubusercontent.com/14014329/92559601-32755d00-f271-11ea-88b1-e87d32bbad92.png)

But, people often like rearranging it, according to needs and journal space, so I also made a position that will alter this set-up.

```r
ggplot() +
  geom_brain(atlas = dk, aes(fill = region),
             position = position_brain(hemi ~ side),
             show.legend = FALSE) +
  scale_fill_brain()
```

![image](https://user-images.githubusercontent.com/14014329/92559709-63559200-f271-11ea-9bdc-2deac716a279.png)

```r
ggplot() +
  geom_brain(atlas = dk, aes(fill = region),
             position = position_brain(hemi + side ~ .),
             show.legend = FALSE) +
  scale_fill_brain()
````
![image](https://user-images.githubusercontent.com/14014329/92560147-29d15680-f272-11ea-91a0-5223b15eb4e6.png)

In a coord, I can't seem to capture the data in the form _after_ the position has been applied before the `transform`, and the graticule has already been set at this point. Trying to override the graticule from within transform has not been successful. 

I was hoping to be able to fix it in setup_panel_params, but I can't seem to access the data that function, and have failed at trying to get the data accessible there.

This problem is similar in scales, where I can't seem to get a hold of the data in order to calculate the grid and axis marks and have them assigned to the right spot.

**Comment by thomasp85** [comment]
Ny suggestion would be to avoid the position adjustment and use faceting for this instead

**Comment by Athanasiamo** [comment]
Thanks. 

I'll take a look if I can make something like that work, that would also still be able to facet on other grouping variables in the data.

**Comment by thomasp85** [comment]
Ah - I can see how you may need faceting for other purposes as well... Still, I don't see how you could consistently label each brain slice using axis labels while still being able to move them around with position adjustments

**Comment by Athanasiamo** [comment]
I'd also still need to make a custom coord though, since I need to override the fact that coord-sf does not allow free scales, which I would need.  Perhaps even a custom facet, because I really would need to move them a little. 

```r
ggplot() +
  geom_brain(atlas = dk, aes(fill = region),
             show.legend = FALSE) +
  scale_fill_brain() + 
  facet_wrap(~ side, ncol = 1)
```
![image](https://user-images.githubusercontent.com/14014329/92562250-f1337c00-f275-11ea-92a5-41a1b2c0323e.png)


At this point I am becoming mostly happy that this is indeed not easily solved and that my fumbling around not managing is because it is actually really hard (impossible?). 

I'm very happy with the general way the geom works, even without the labels. It's more flexible than the solution we have currently. So I might just call it, and write a decent tutorial on how to adjust the labels manually.

**Comment by thomasp85** [comment]
What about keeping the current setup but provide some easy means of adding labels directly to the plot instead of relying on axis labels?

**Comment by Athanasiamo** [comment]
Can you elaborate on that a little?

**Comment by thomasp85** [comment]
I mean, simply provide some sort of `annotate_hemisphere()` function that added some text to the plot area... it will probably require that the axis gets expanded a bit to make room for it but it will be much more flexible

**Comment by Athanasiamo** [comment]
oh, that's a thought. I'll give that a go, sounds like a good solution.

**Comment by clauswilke** [comment]
If you turn clipping off in the coord, you can also write annotations outside of the plot panel, though that can require some fiddling to get the position right.

**Comment by Athanasiamo** [comment]
Thank you both for very valuable input. I believe we have come as far as I could ever expect with this, and I'll give annotations a go.
