### ISSUE TITLE
Feature request - be able to justify key and label section within legend

### ISSUE THREAD

**Issue by py9mrg** [tidyverse/ggplot2#3989]
I'm trying to justify *everything* within a legend, but there appears to be no way to do it.

Using a bastardised example from the documentation, I want everything below the legend title "Transmission" to be right justified.

``` r
p2 <- ggplot(mtcars, aes(wt, mpg)) +
  geom_point(aes(shape = factor(vs))) +
  labs(
    x = "Weight (1000 lbs)",
    y = "Fuel economy (mpg)",
    shape = "Transmission"
  )
p2 
```

![](https://i.imgur.com/Xnl9wWX.png)

<sup>Created on 2020-05-07 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

I've tried all the various theme and guide justification and positioning options, but none of them will shift the actual key section over to the right.

**Comment by smouksassi** [comment]
it is not clear from above what you tried and what final look you are after see below 
you can also change where the legend text appear
``` r
library(ggplot2)
p2 <- ggplot(mtcars, aes(wt, mpg)) +
  geom_point(aes(shape = factor(vs))) +
  labs(
    x = "Weight (1000 lbs)",
    y = "Fuel economy (mpg)",
    shape = "Transmission"
  )
p2 +
  scale_shape_discrete(labels=c("zero","one long long"))+
  guides(shape=guide_legend(label.hjust = 0.5))+
theme(legend.title.align = 1,
      legend.justification = c("center","bottom"))  
```

![](https://i.imgur.com/0qPmPUz.png)

<sup>Created on 2020-05-08 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by py9mrg** [comment]
Ok so in a bit more detail...

I'm aware that we can position the legend using `legend.position` and justify the legend with respect to that position using `legend.justification`. I'm also aware that we can justify the legend title using `legend.title.align`, and that we can justify the legend labels using `guide_legend` and `label.hjust` - so we can justify them, but only within the little space they occupy, not within the whole legend. 

But what I don't see is a way to position/justify the entire (key + label) section underneath the legend title. In my original example, what I want is the 0 and 1 to be positioned just below the "n" of the "transmission" and the triangle and circle to move across with them, they'd be underneath the "ss" of "transmission". I want to be able to justify that entire section within the legend box.

If there is a then either I'm being an idiot or it's a bit complicated (I thought `legend.box.just` might do it, but it doesn't). So I'm proposing a single command in `theme` or `guide_legend` that allows you to justify the whole (key + label) section underneath the legend title, within the legend. Is that clearer?

**Comment by thomasp85** [comment]
You can force the behaviour you are after by setting the width of the key to zero

```r 
p2 + theme(legend.key.width = unit(0, 'mm'))
```

**Comment by py9mrg** [comment]
That doesn't seem to quite do what I want - what I'm looking for is this (notice how the whole key section is right justified under the title):

![Rplot02](https://user-images.githubusercontent.com/12600721/92610770-fd3c2f80-f2af-11ea-8159-e5020b281f22.png)

**Comment by thomasp85** [comment]
I see - I misunderstood you. That is currently not possible...

**Comment by py9mrg** [comment]
No worries, at least I know it's not me being an idiot and missing some obvious option! Cheers.

**Comment by clauswilke** [comment]
I've got a little helper function that can do this. I've been pondering to add this to the cowplot package. Maybe I should just do this.

    align_legend <- function(p, hjust = 0.5)
    {
      # extract legend
      g <- cowplot::plot_to_gtable(p)
      grobs <- g$grobs
      legend_index <- which(sapply(grobs, function(x) x$name) == "guide-box")
      legend <- grobs[[legend_index]]
      
      # extract guides table
      guides_index <- which(sapply(legend$grobs, function(x) x$name) == "layout")
      
      # there can be multiple guides within one legend box  
      for (gi in guides_index) {
        guides <- legend$grobs[[gi]]
        
        # add extra column for spacing
        # guides$width[5] is the extra spacing from the end of the legend text
        # to the end of the legend title. If we instead distribute it by `hjust:(1-hjust)` on
        # both sides, we get an aligned legend
        spacing <- guides$width[5]
        guides <- gtable::gtable_add_cols(guides, hjust*spacing, 1)
        guides$widths[6] <- (1-hjust)*spacing
        title_index <- guides$layout$name == "title"
        guides$layout$l[title_index] <- 2
        
        # reconstruct guides and write back
        legend$grobs[[gi]] <- guides
      }
      
      # reconstruct legend and write back
      g$grobs[[legend_index]] <- legend
      g
    }

    library(ggplot2)
    library(cowplot)

    p <- ggplot(mtcars, aes(wt, mpg)) +
      geom_point(aes(shape = factor(vs))) +
      labs(
        x = "Weight (1000 lbs)",
        y = "Fuel economy (mpg)",
        shape = "Transmission"
      )

    ggdraw(align_legend(p, hjust = 1))

![](https://i.imgur.com/YWgf2UI.png)

<sup>Created on 2020-09-09 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by py9mrg** [comment]
Wow, great - thanks very much!
