### ISSUE TITLE
decimal places in geom_contour2 plot

### ISSUE THREAD

**Issue by IssamHu** [tidyverse/ggplot2#3990]
Dear Sir,
How can I reduce the decimal places in the geom_contour2 plot
my codes:

okl<- ggplot() +
  geom_contour_fill(data=vol, aes(x=Date, y=Depth, z= Temperature)) +
  
  scale_fill_distiller(palette="Spectral", name="°C") +
  geom_contour2(data=vol,aes(x=Date,y=Depth,z=Salinity, color=..level..)) + 
  
  theme_bw() + geom_text_contour(data=vol,aes(x=Date,y=Depth,
                                              z=Salinity)) +
  
  scale_y_continuous(trans = "reverse") +
  
  scale_x_date(date_breaks = "1 month") +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        
        axis.title.x=element_blank()) +
  guides(color=guide_legend("PPT")) 
okl

That what i get:

![Rplot](https://user-images.githubusercontent.com/62583812/81493216-83d5f700-9253-11ea-9454-bbb78a1eb28f.png)

I have rounded my data in the csv file but still can't solve the problem:

[ocean_raster_contour_2019_New.txt](https://github.com/tidyverse/ggplot2/files/4605283/ocean_raster_contour_2019_New.txt)

Thanks

**Comment by clauswilke** [comment]
It looks like you're using the metR package, so you'll have to report the issue there:
https://github.com/eliocamp/metR/issues
