### ISSUE TITLE
geom_boxplot throws error when all y are 0 and an NA exists

### ISSUE THREAD

**Issue by yogat3ch** [tidyverse/ggplot2#3991]
`Error in if (all(y == 0)) { : missing value where TRUE/FALSE needed`

Followed the error down with browser:
 `geom_boxplot` [line 136](https://github.com/tidyverse/ggplot2/blob/660aad2db2b3495ae0d8040915a40d247133ffc0/R/geom-boxplot.r#L136) >
 `layer`  [line 134](https://github.com/tidyverse/ggplot2/blob/e9b9946786dae861dea1c352f2ac7b2a837b5f82/R/layer.r#L134) > ggproto
I'm not sure where the offending line implicated by the error is as that as far as I could follow it with `debug`.
Most of the other `geom_*` seem to effectively omit NA values, and so I thought that it might be helpful to report this exception.
```r
library(ggplot2)
df <- data.frame(d = c(0, 0, NA, 0), dt = seq(Sys.Date() - 3, Sys.Date(), by = "1 days"))
ggplot(df, aes(x = dt)) +
  geom_boxplot(aes(y = d))
```

**Comment by karawoo** [comment]
Thanks for reporting, it looks like this is coming from the code that detects the direction of the layer here: 

https://github.com/tidyverse/ggplot2/blob/1d4c5732c97b4d8309224262209ff9e87e00aa7a/R/utilities.r#L610-L612

**Comment by yogat3ch** [comment]
No problem, thanks for finding that so quickly!
