### ISSUE TITLE
HACKED: PORN PAGE at  https://www.ggplot2-exts.org/gallery/

### ISSUE THREAD

**Issue by andhherson** [tidyverse/ggplot2#3993]
Dont enter in this link, there are a porn page.

**Comment by clauswilke** [comment]
I'm pretty certain this is not the official link anymore. This site is fine as far as i can tell:
https://exts.ggplot2.tidyverse.org/

**Comment by yutannihilation** [comment]
Yeah, but the stable site still links to the old URL... l need some time to find a tweak to rebuild the site, sorry. Anyway thanks for the notice.

**Comment by yutannihilation** [comment]
Done!

* Github Action run: https://github.com/tidyverse/ggplot2/runs/670746120
* Tweaks added: https://github.com/tidyverse/ggplot2/compare/v3.3.0...v3.3.0-rebuild-site

BTW, it's not that the website is hacked, but the domain simply got expired so someone acquired it. We can do nothing except for advertising the new website...

**Comment by clauswilke** [comment]
I just tweeted the new link. Maybe we should all do so.
https://twitter.com/ClausWilke/status/1260634974052659200?s=20

**Comment by quiocarbajal** [comment]
Sorry, for those who are new at github and coding, could you elaborate on how to get to the ggplot2 gallery? Thank you!
PS: this link took me to the porn site
 https://www.ggplot2-exts.org/gallery/

**Comment by clauswilke** [comment]
This issue now seems to be attracting comments made in bad faith, so I'm going to lock it. I don't think more needs to be said.
