### ISSUE TITLE
scale_alpha_binned not exported

### ISSUE THREAD

**Issue by mdhall272** [tidyverse/ggplot2#3995]
It looks like scale_alpha_binned is missing from the NAMESPACE despite being documented:

```
> library(ggplot2)
> scale_alpha_binned()
Error in scale_alpha_binned() : 
  could not find function "scale_alpha_binned"
> ?scale_alpha_binned
```

**Comment by clauswilke** [comment]
Yes, it's missing an `@export`.

https://github.com/tidyverse/ggplot2/blob/660aad2db2b3495ae0d8040915a40d247133ffc0/R/scale-alpha.r#L29-L39
