### ISSUE TITLE
using weights with stat_summary()

### ISSUE THREAD

**Issue by larmarange** [tidyverse/ggplot2#4000]
Currently, a variable mapped to `weight` aesthetic is not taken into account by `stat_summary()`. In such a situation, maybe a warning should be displayed as some users will expect that these weights will be taken into account in the computation.

In addition, considering a version of `stat_summary()` able to deal with weights could be relevant.

Regards

**Comment by thomasp85** [comment]
As with any stat and geom, the aesthetics that `stat_summary()` understands is documented. I think it is a slippery slope to begin warning about use of specific aesthetics that we deem user may want to use.

A weighted version of `stat_summary()` would fit well in an extensions package
