### ISSUE TITLE
Zero length breaks no longer work with discrete positional scales

### ISSUE THREAD

**Issue by cpsievert** [tidyverse/ggplot2#4008]
With current CRAN version, this code produces:

```r
ggplot(PlantGrowth, aes(x = group, y = weight)) + 
  geom_boxplot() + 
  scale_x_discrete(breaks = NULL)
```

![image](https://user-images.githubusercontent.com/1365941/82269725-1fdcbe00-9938-11ea-85ed-df8d4cc0fbbe.png)

With GH version (likely introduced by 7e5ff921c50fb0beb203b115397ea33fee410a54, cc @thomasp85), this code produces an error:

```r
Error: `mapped_discrete` objects can only be created from numeric vectors
```

**Comment by clauswilke** [comment]
I suggest adding a unit test for this case, so the problem won’t reoccur at some point in the future.

**Comment by thomasp85** [comment]
yeah - you're probably right
