### ISSUE TITLE
Issue with `geom_rect` and `alpha` on faceting

### ISSUE THREAD

**Issue by tvedebrink** [tidyverse/ggplot2#4011]
If using `geom_rect` in connection with faceting, not all manual controls are used across panels.
In order to avoid expansion of the plotting region, the use of `geom_rect` with manually specified coordinates (`xmin`, `xmax`, `ymin` and `ymax`) and appearance parameters (e.g. `fill` or `alpha`) is useful. However, I have experienced that changing `alpha` only affects one of the panels. 

```r
mtcars %>% 
  ggplot(aes(y = mpg, x = wt)) + 
  geom_point() + facet_wrap(~gear) + 
  geom_rect(xmin = 2, xmax = 4, ymin = 15, ymax = 30, alpha = 0.1, fill = "#004400")
```

The opacity only applies to a single panel:
![Rplot](https://user-images.githubusercontent.com/8102518/82296939-3c1d4100-99b2-11ea-9e59-8474a348e9f7.png)

**Comment by smouksassi** [comment]
have you considered ? 
```r
mtcars %>% 
  ggplot(aes(y = mpg, x = wt)) + 
  geom_point() + facet_wrap(~gear) + 
  geom_rect(data=data.frame(
            xmin = 2, xmax = 4, ymin = 15, ymax = 30),
            aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax),
            alpha = 0.1, fill = "#004400",
            inherit.aes = FALSE)
```
or using annotate ? by default you will be plotting multiple rectangles and the opacity will change depending on how many are overlaid

**Comment by tvedebrink** [comment]
Thanks for the suggestion - my problem was actually caused by wanting highlight the lower left rectangle of a plot. One may was to set `xmin = -2`, which is a point outside the original plotting region of the data. By adding a data argument to `geom_rect` the limits of the plot reacts to that. 

```{r}
mtcars %>% 
  ggplot(aes(y = mpg, x = wt)) + 
  geom_point() + facet_wrap(~gear) + 
  geom_rect(data=data.frame(
            xmin = -2, xmax = 4, ymin = 15, ymax = 30),
            aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax),
            alpha = 0.1, fill = "#004400",
            inherit.aes = FALSE)
```

![Rplot_2](https://user-images.githubusercontent.com/8102518/82300487-36762a00-99b7-11ea-97cb-e016ddf90d94.png)

**Comment by smouksassi** [comment]
Try using  xmin=-Inf

**Comment by tvedebrink** [comment]
Perfect! Thanks.. It works
