### ISSUE TITLE
Add 'reverse' option to scale_y_date?

### ISSUE THREAD

**Issue by SimonDedman** [tidyverse/ggplot2#4014]
---

Hi folks. It seems various people have been confounded by trying to reverse the order of date scales in ggplot2. The scale_x_date family of functions is great, but their presence seems to have made reversing scales even less intuitive/possible.

By way of example, I convert dates into yeardays (1:366) and project on the Y axis, with values going from bottom to top, Jan to Dec (various irrelevant code lines removed e.g. theme, title etc):

```r
mydata %<>% mutate(Day = yday(Date))
ggplot(mydata, aes(x = toppid, y = as.Date(Day, origin = as.Date("2018-01-01")))) +
  geom_point(aes(colour = MarineArea), size = 0.25) +
  facet_wrap(.~Stock, scales = "free") +
  scale_y_date(date_breaks = "1 month", date_labels = "%b")
```
![MarineAreaEntryYDayStock](https://user-images.githubusercontent.com/4599748/82375323-456bd500-99d5-11ea-80c1-1bc2cb696d02.png)

It occurred to me that I could reverse the data themselves for Day:

`mydata$Day2 <- 367 - mydata$Day`

But this only affects the plotted points, not the scale.
Given the [existing solutions](https://github.com/tidyverse/ggplot2/issues/956) to this issue seem hacky, if applicable to the above formulation at all, is there any chance that a future release could see a `reverse` or `trans` parameter added into `scale_x/y_date`?

Thanks in advance.

**Comment by meenurajapandian** [comment]
This would be great! It seems like this has been around for a while but there are no non-hacky solutions for it till now.

**Comment by ACalleros** [comment]
Why hasn't this been implemented? Hadley posted a solution for this 10 years ago 

https://groups.google.com/g/ggplot2/c/qrcvqy6TdzI

**Comment by clauswilke** [comment]
> Why hasn't this been implemented?

Because the difficult bit is not chaining two transformations together. The difficult bit is developing a coherent and consistent framework for scale reversal. See #4021.

**Comment by yutannihilation** [comment]
I guess this is now possible in theory because the latest version of scale can composite multiple transformers https://github.com/r-lib/scales/pull/335

**Comment by teunbrand** [comment]
> I guess this is now possible

Indeed, though the reverse transformation has some quirks that it cannot apply the `-` operation to `"Date"` objects. That is circumventable though. 

``` r
library(ggplot2)
library(scales)

reverse2_trans <- function() {
  trans_new(
    "reverse2",
    function(x) -1 * as.numeric(x), # Force values to be numeric for Date objects
    function(x) -1 * as.numeric(x)
  )
}

ggplot(economics, aes(date, unemploy)) +
  geom_line() +
  scale_x_continuous(
    trans = c("date", "reverse2")
  )
```

![](https://i.imgur.com/cqcklzf.png)

<sup>Created on 2022-04-26 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by yutannihilation** [comment]
Oh, thanks. So, is this still something that needs to be resolved on scales' side? Anyway it seems we are getting closer!

**Comment by competulix** [comment]
any updates on this?

**Comment by rafalopespx** [comment]
Any updates on this? [2]

**Comment by teunbrand** [comment]
Custom transformations is still the recommended route. No consensus yet about the optimal implementation of scale reversal.
My proposal is opening up the `rescaler` argument as described [here](https://github.com/tidyverse/ggplot2/issues/4021#issuecomment-911895926).

**Comment by rafalopespx** [comment]
Thank you, it worked!

**Comment by teunbrand** [comment]
I'm not exactly sure what change made this possible, but this appears to work now without any problems:

``` r
library(ggplot2)

ggplot(economics, aes(date, unemploy)) +
  geom_line() +
  scale_x_continuous(
    trans = c("date", "reverse")
  )
```

![](https://i.imgur.com/fEv1ltT.png)

<sup>Created on 2024-06-03 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>
