### ISSUE TITLE
Issues in "geom_bar" in ggplot2_3.3.0

### ISSUE THREAD

**Issue by jianhaizhang** [tidyverse/ggplot2#4015]
# Brief description of the problem: Bars plotted by "geom_bar" in ggplot2_3.3.0 are overlapping, and axis labels are not expected. How to resolve it?

```r
# In  ggplot2_3.3.0, bars are overlapping, and axis labels are not expected.
library(ggplot2) 
df <- data.frame(x=c(22.00000, 22.06006, 22.12012), y=1)
ggplot(data=df, aes(x=x, y=y))+geom_bar(stat = "identity")

# In ggplot2_3.2.1, the plot is expected.
library(ggplot2) 
df <- data.frame(x=c(22.00000, 22.06006, 22.12012), y=1)
ggplot(data=df, aes(x=x, y=y))+geom_bar(stat = "identity")
```

**Comment by karawoo** [comment]
This was due to how orientation is detected in 3.3.0 and has been fixed in the development version. Rendered reprex with current master branch:

``` r
library(ggplot2)
packageVersion("ggplot2")
#> [1] '3.3.0.9000'
df <- data.frame(x=c(22.00000, 22.06006, 22.12012), y=1)
ggplot(data=df, aes(x=x, y=y))+geom_bar(stat = "identity")
```

![](https://i.imgur.com/5ygo946.png)

<sup>Created on 2020-05-19 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

**Comment by karawoo** [comment]
@jianhaizhang if you don't want to upgrade to the development version of ggplot2, you can also use `orientation = "x"`:
```
ggplot(data = df, aes(x = x, y = y)) +
  geom_bar(stat = "identity", orientation = "x")
```

**Comment by jianhaizhang** [comment]
Thanks!
