### ISSUE TITLE
[Feature request] Setting axis intervals with automatic range 

### ISSUE THREAD

**Issue by Sibojang9** [tidyverse/ggplot2#4017]
Right now, the breaks of an axis can be set up using breaks. e.g. 
`scale_x_continuous(breaks = seq(0, 100, by=20)) `

However, this is tedious as the range of the breaks are always requried. Is it possible to have:
`scale_x_continuous(interval=20) `? Then let ggplot automatically calculate the breaks from the range of the data. e.g. `scale_y_continuous(interval=20) ` outputs the breaks 0, 20, 40, 60, 80, and 100,  if the x-axis variable ranges from 0 to 100. 

This feature can be very helpful in piping into ggplot. Right now, we have to use this code to specify the interval to plot a processed dataframe:

`df <- df %>% fun(.)   ; df %> ggplot()+scale_x_continuous (breaks=seq(min(df$x), max(df$x), by=20))
`

Once that feature becomes available, the code can be simplified to:

`df %>% fun(.) %>% ggplot()+scale_x_continuous(interval=20)`

Thanks.

**Comment by teunbrand** [comment]
This is just a suggestion, but it seems like `scales::breaks_width()` might be what you are looking for. Usage as below:

``` r
library(ggplot2)

ggplot(iris, aes(Sepal.Width, Sepal.Length)) +
  geom_point(aes(colour = Species)) +
  scale_x_continuous(breaks = scales::breaks_width(0.2))
```

![](https://i.imgur.com/dzdJE5N.png)

<sup>Created on 2020-05-21 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by Sibojang9** [comment]
Hi Teun, 

Your suggestion is tremendously helpful. I am closing this thread.

SJ
