### ISSUE TITLE
Stacked Area charts

### ISSUE THREAD

**Issue by nergiszaim** [tidyverse/ggplot2#4018]
In Plotly when we double click on a grouped variable on a stacked area chart, the y axis rescales. in ggplotly, the re-scaling doesn't happen. Is there a way around this?

![Screen Shot 2020-05-21 at 1 44 55 PM](https://user-images.githubusercontent.com/58089236/82630240-ffff0180-9ba6-11ea-9642-5c29c6dba74b.png)
![Screen Shot 2020-05-21 at 1 45 17 PM](https://user-images.githubusercontent.com/58089236/82630241-01c8c500-9ba7-11ea-9b1b-d0d0841a7cd3.png)

**Comment by yutannihilation** [comment]
Please ask on plotly's repo or RStudio Community
