### ISSUE TITLE
scale_fill_steps produces unevenly spaced legend when limits are set

### ISSUE THREAD

**Issue by Shians** [tidyverse/ggplot2#4019]
When setting the limits of `scale_fill_steps()`, the fill brackets in the legend becomes unevenly spaced. It's not clear why or how this happens.

``` r
library(tidyverse)

df <- tibble(
    crossing(
        tibble(sample = paste("sample", 1:4)),
        tibble(pos = 1:4)
    ),
    val = runif(16)
)

ggplot(df, aes(x = pos, y = sample)) +
    geom_line() +
    geom_point(aes(fill = val), pch = 21, size = 7) +
    scale_fill_steps(low = "white", high = "black")
```

![](https://i.imgur.com/6zoByUA.png)

``` r

ggplot(df, aes(x = pos, y = sample)) +
    geom_line() +
    geom_point(aes(fill = val), pch = 21, size = 7) +
    scale_fill_steps(low = "white", high = "black", limits = c(0, 1))
```

![](https://i.imgur.com/M0LWbjX.png)

<sup>Created on 2020-05-22 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by yutannihilation** [comment]
Thanks, confirmed. This seems a bug that `scale_fill_steps()` doesn't limit the `fill` scale. I think the first and last circle below should be grayed out.

``` r
library(ggplot2)
library(patchwork)

df <- data.frame(x = 0:4)

p <- ggplot(df, aes(x, 0)) +
  geom_point(aes(fill = x), pch = 21, size = 80)

p1 <- p +
  scale_fill_steps(low = "white", high = "red", limits = c(1, 3)) +
  ggtitle("step")
p2 <- p +
  scale_fill_gradient(low = "white", high = "red", limits = c(1, 3)) +
  ggtitle("gradient")

p1 / p2
```

![](https://i.imgur.com/ZptP5Rl.png)

<sup>Created on 2020-06-13 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by thomasp85** [comment]
This is intentional. Binning scales squashes out of bounds values by default, whereas continuous scales censor them

**Comment by yutannihilation** [comment]
Aw, I see. Sorry, I misunderstood the behaviour.

``` r
library(ggplot2)

df <- data.frame(x = 0:4)

ggplot(df, aes(x, 0)) +
  geom_point(aes(fill = x), pch = 21, size = 80) +
  scale_fill_steps(low = "white", high = "red", limits = c(1, 3), oob = scales::censor)
```

![](https://i.imgur.com/tZT0hEK.png)

<sup>Created on 2020-06-13 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Do you think this issue is something that we should fix? I'm wondering if we need some tweaks like what #4006 did for contours.

**Comment by Shians** [comment]
The oob behaviour is easily changeable. But the spacing in the binned scale legend is unexpected and the fix is not intuitive. I've found that setting the limits to slightly offset from my desired limits fixes this. Still, it's not clear why the binned legend spaces itself in this strange way.

``` r
library(ggplot2)

df <- data.frame(x = 0:4)

ggplot(df, aes(x, 0)) +
  geom_point(aes(fill = x), pch = 21, size = 80) +
  scale_fill_steps(low = "white", high = "red", limits = c(1.001, 2.999))
```

![](https://i.imgur.com/obb7xj0.png)

<sup>Created on 2020-06-14 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
