### ISSUE TITLE
Continuous values don't work with scale_shape_identity

### ISSUE THREAD

**Issue by wch** [tidyverse/ggplot2#402]
Commit f175bbb1b99f38e583fbbd9d0d71de488d5d448d broke `R CMD check`:

``` R
df2 <- data.frame(x = 1:5 , y = 1:25, z = 1:25)
s <- ggplot(df2, aes(x = x, y = y))
s + geom_point(aes(shape = z), size = 4) + scale_shape_identity()
# Error: Continuous value supplied to discrete scale
```

**Comment by jmccreight** [comment]
df2 <- data.frame(x = 1:5 , y = 1:25, z = 1:25)
s <- ggplot(df2, aes(x = x, y = y))
s + geom_point(aes(shape = z), size = 4) + scale_shape_identity()
s + geom_point(aes(shape = z, color=z), size = 4) + scale_shape_identity() + scale_color_discrete() 
# Error: Continuous value supplied to discrete scale
This time it's for scale_color_discrete. Integer is a discrete variable. Same complaint, different scale.
Thanks!

**Comment by hadley** [comment]
@jmccreight can you please open a new issue rather than commenting on a very old issue.
