### ISSUE TITLE
default xlim and ylim in qplot are not supportd when non missing

### ISSUE THREAD

**Issue by moodymudskipper** [tidyverse/ggplot2#4027]
See below. I think it's against the principles laid out in the tidyverse principle book, it can be fixed by using `c(NA_real_, NA_real_)` as a default. 

The issue arose as I was writing a wrapper around `qplot` and it choked when passing  the parameters `xlim = xlim, ylim = ylim`.

``` r
library(ggplot2)

# works
qplot(Sepal.Width, Sepal.Length, data = iris)
```

![](https://i.imgur.com/xXi72Ao.png)

``` r

# doesn't work
qplot(Sepal.Width, Sepal.Length, data = iris, xlim = c(NA,NA))
#> Error in UseMethod("limits"): no applicable method for 'limits' applied to an object of class "logical"

# works
qplot(Sepal.Width, Sepal.Length, data = iris, xlim = c(NA_real_,NA_real_))
```

![](https://i.imgur.com/G7ZwWYw.png)

<sup>Created on 2020-05-25 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by clauswilke** [comment]
You are correct, though we tend to discourage use of `qplot()` as much as possible. In any case, feel free to create a PR to fix this.
