### ISSUE TITLE
ggplot (geom_sf) not filling polygons if drawing extension is modified

### ISSUE THREAD

**Issue by RMRubert** [tidyverse/ggplot2#4029]
---
ggplot will consistenly not fill one polygon if those are cutted by the xlim, ylim parameter on coord_sf. However, it will draw the outline.

To reproduce this problem you need a shapefile polygon layer with several polygons that are NOT connected to each other. Like islands. I have been able to reproduce it with a free shapefile from [here](http://download.geofabrik.de/europe/great-britain/scotland.html).  gis_osm_natural_a_free_1.shp

You can see if one keeps modifying the xlim value, how the unfilled polygon keeps changing to another one.
This is for values: xlim = c(-7.3897,-7.2248), ylim = c(57.47,57.5488)
![Rplot_1](https://user-images.githubusercontent.com/11463633/82923946-8d5d9f80-9f73-11ea-8a8b-112f772a8636.png)

This is for values: xlim = c(-7.45,-7.2248), ylim = c(57.47,57.5488)
![Rplot](https://user-images.githubusercontent.com/11463633/82924245-f8a77180-9f73-11ea-8d7f-f94ad91e19b9.png)

I am not sure why it happens, and not always happens. Looks like if the Gravity center of polygon (or a differente variable) is outside of the plotting area, the polygon isn't filled. 

```r
#shapefile can be downloaded from here: http://download.geofabrik.de/europe/great-britain/scotland.html
shp = st_read("C:/Users/user/Downloads/scotland-latest-free.shp/gis_osm_natural_a_free_1.shp", 
ggplot() +
  geom_sf(data = shp,
          fill = "orange",
          alpha = 0.75)+
  coord_sf(xlim = c(-7.3897,-7.2248), ylim = c(57.47,57.5488))
```

**Comment by clauswilke** [comment]
Are you using Windows? I'm pretty sure this is a known limitation of the Windows graphics device. Try ragg. https://cran.r-project.org/web/packages/ragg/index.html

**Comment by RMRubert** [comment]
Yes I was using Windows, that solved my problem. Thank you.
