### ISSUE TITLE
facet labellers not calling default

### ISSUE THREAD

**Issue by waltersom** [tidyverse/ggplot2#4031]
I have a plot using facet_grid, that I want to set the facet labels with.
The faceting variables are stored as integers, and I am trying to use lookup tables to specify some expressions, and then pass those to label_parsed.

As I read the docs for labeller(), the lookup table should be passed to .default.

`.default  Default labeller for variables not specified. Also used with lookup tables or non-labeller functions.`

However, this doesn't seem to be happening (note labels on rows.)

I'm not sure if this is a documentation problem, me misunderstanding something, or a problem with the labeller.

---

``` r
library(ggplot2)
tdf <- data.frame(x=c(1,2,3,4), y=c(4,3,2,1), a=c(0,1,0,1), b=c(1, 2, 2, 1))
ggplot(tdf, aes(x, y))+geom_point()+
  facet_grid(a~b, labeller=labeller(a=c(`0`="a^2", `1`="a[2]"), b=c(`1`="One", `2`="Two"), .default=label_parsed))
```

![](https://i.imgur.com/oy3YHWL.png)

<sup>Created on 2020-05-27 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

---

If I instead use `.rows` and `.cols` to name the arguments to labeller, I get the expected result.
(The labels on the rows are now passed to label_parsed)

``` r

library(ggplot2)
tdf <- data.frame(x=c(1,2,3,4), y=c(4,3,2,1), a=c(0,1,0,1), b=c(1, 2, 2, 1))
ggplot(tdf, aes(x, y))+geom_point()+
  facet_grid(a~b, labeller=labeller(.rows=c(`0`="a^2", `1`="a[2]"), .cols=c(`1`="One", `2`="Two"), .default=label_parsed))
```

![](https://i.imgur.com/Y3L3xav.png)

<sup>Created on 2020-05-27 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by clauswilke** [comment]
You're correct. The code doesn't reflect the documentation. If you check out line 440 below, the `.default` argument is not forwarded to `as_labeller()`, whereas in line 442 it is. Line 440 is run in your first example, line 442 in your second one.

https://github.com/tidyverse/ggplot2/blob/3e35c7a928c202669edf135f197d91bccd6f9b02/R/labeller.r#L439-L443
