### ISSUE TITLE
Incorrect link on CRAN README

### ISSUE THREAD

**Issue by Yue-J** [tidyverse/ggplot2#4033]
I'm not sure if an issue request is the correct way to bring this to your attention, as it's of a different nature than most (if not all?) others posted here.

The link to the community-maintained ggplot2 extension gallery on the README file on the CRAN repository does not seem to be maintained, and in fact links to a Russian porn website. The CRAN README file itself may be found [here](https://cran.r-project.org/web/packages/ggplot2/readme/README.html), and the outdated link to the extension gallery is under the "Lifecycle" heading.

**Comment by Yue-J** [comment]
EDIT: I do notice that the extension gallery was moved on March 31st - should I be contacting CRAN instead?

**Comment by thomasp85** [comment]
It will be fixed when ggplot2 is updated in 2 weeks time. There’s not much else we can do unfortunately

**Comment by Yue-J** [comment]
Ah, thanks for the speedy response!
