### ISSUE TITLE
geom_text alignment with large text block

### ISSUE THREAD

**Issue by bhive01** [tidyverse/ggplot2#4035]
I'm trying to align the outputs of geom_text at the bottom of my plot. Here is a reprex. 

```
library(ggplot2)

text_df <- data.frame(Species = c("versicolor", "virginica", "setosa"),  labels = c("n = 15\nCoV = 0.5214%", "this is longer text\nand another line\nn = 15\nCoV = 0.5214%","n = 15\nCoV = 0.5214%"))

ggplot() +
geom_point(data = iris, aes(x = Species, y = Sepal.Width)) +
geom_text(data = text_df, aes(x = Species, y = -Inf, label = labels), vjust = -0.5)
```
![example](https://user-images.githubusercontent.com/394973/83043008-271a6080-9ff7-11ea-9196-c286ace3f5ab.jpg)

The vjust appears to affect the larger block of text more than the smaller blocks of text. I can set it to 0 and it works, but the text butts right up against the axis and I don't like the look of that. Smaller fractions look better but the alignment affects the blocks differently and I don't expect that. Is this the expected behavior?

**Comment by clauswilke** [comment]
Yes, that's how it works. You can set an explicit y value if you know your axis range. Otherwise, you'll have to use the ggtext package and set a defined margin around your text labels.

``` r
library(ggplot2)

text_df <- data.frame(Species = c("versicolor", "virginica", "setosa"),  labels = c("n = 15\nCoV = 0.5214%", "this is longer text\nand another line\nn = 15\nCoV = 0.5214%","n = 15\nCoV = 0.5214%"))

ggplot() +
  geom_point(data = iris, aes(x = Species, y = Sepal.Width)) +
  geom_text(data = text_df, aes(x = Species, y = 2, label = labels), vjust = 0)
```

![](https://i.imgur.com/xCIpRke.png)

<sup>Created on 2020-05-27 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by bhive01** [comment]
Ok, thanks Claus.
