### ISSUE TITLE
graphical data from scale_color_gradientn is altered/incorrect, following facet_grid

### ISSUE THREAD

**Issue by CNicholasMDA** [tidyverse/ggplot2#4038]
Apologies - I tried to understand and generate reprex but was unable. Will continue trying/learning.  Instead, a sample of my script is below.

Excerpt is from a script used to analyze biological data through unsupervised clustering called tSNE (WorkFlow, Nowicka et al 2017). I am not inquiring about tSNE per se, but I am trying to generate graphs showing a gradient of protein expression (CD8 protein, for example; red is high, blue is low/zero). I can generate *correct* graphs without faceting, and with facet_wrap(~condition) or (~condition2) which are timepoint and drug response, respectively.  

However, when I try to facet_wrap or facet_grid by _both_ conditions, the CD8 expression is incorrect - the patterns of dk. blue and red are altered. Am I missing something or is there nothing to be done? With thanks...sample pictures also included below.

[GitHub inquiry WorkFlow.pptx](https://github.com/tidyverse/ggplot2/files/4696871/GitHub.inquiry.WorkFlow.ppt

## Plot t-SNE colored by specific marker
dr <- data.frame(tSNE1 = tsne_out$Y[, 1], tSNE2 = tsne_out$Y[, 2], 
                 expr[tsne_inds, lineage_markers])
dr$sample_id <- sample_ids[tsne_inds]
mm <- match(dr$sample_id, md$sample_id)
dr$condition <- md$condition[mm]
dr$condition2 <- md$condition2[mm]
dr$cell_clustering1 <- factor(cell_clustering1[tsne_inds], levels = 1:nmc)

## tSNE all markers separately (select only numeric data)
pdf(glue("./{out_dir}/tsne_by_markers.pdf"))
for (i in lineage_markers){
  tsne_intensity<- ggplot(dr,  aes(x = tSNE1, y = tSNE2, color = dr[,i])) +
    geom_point(size = 1.0) +
    theme_bw() +
    scale_color_gradientn(i, 
                          colours = colorRampPalette(rev(brewer.pal(n = 11, name = "Spectral")))(50))
  print(tsne_intensity)
}
dev.off()

## tSNE all markers by condition and condition2
pdf(glue("./{out_dir}/tsne_by_markers_by_condition2.pdf"))
for (i in lineage_markers){
  tsne_intensity<- ggplot(dr,  aes(x = tSNE1, y = tSNE2, color = dr[,i])) +
    facet_wrap(~ condition2) +
    geom_point(size = 1.0) +
    theme_bw() +
    scale_color_gradientn(i, 
                          colours = colorRampPalette(rev(brewer.pal(n = 11, name = "Spectral")))(50))
  print(tsne_intensity)
}
dev.off()

## tSNE all markers by condition2
pdf(glue("./{out_dir}/tsne_by_markers_by_condition_and_condition2.pdf"))
for (i in lineage_markers){
  tsne_intensity<- ggplot(dr,  aes(x = tSNE1, y = tSNE2, color = dr[,i])) +
        facet_grid(condition ~ condition2) +
    geom_point(size = 1.0) +
    theme_bw() +
    scale_color_gradientn(i, 
                          colours = colorRampPalette(rev(brewer.pal(n = 11, name = "Spectral")))(50))
  print(tsne_intensity)
}
dev.off()

---

Brief description of the problem

```r
# insert reprex here
```

**Comment by clauswilke** [comment]
Hello,

the ggplot2 issue track is meant for reporting bona-fide bugs or feature requests. User-support questions should be directed elsewhere, such as the RStudio Community (https://community.rstudio.com/).

On first glance, your problem is most likely related to `color = dr[,i]` in the `aes()` statement, which is an incorrect use of the ggplot2 API.

**Comment by CNicholasMDA** [comment]
In the event that someone else was having the same issue as I, I found that updating ggplot2 and dplyr packages completely solved my issues. Good luck.
