### ISSUE TITLE
`ggsave()` produces aliased png files on Windows

### ISSUE THREAD

**Issue by thomas-neitmann** [tidyverse/ggplot2#4040]
When using `ggsave()` to save a plot as `png` on Windows the resulting image is quite aliased (zoom in to see the ragged line).

```r
library(ggplot2)
data(gapminder, package = "gapminder")
china <- gapminder[gapminder$country == "China", ]

ggplot(china, aes(year, lifeExp)) + geom_line()
ggsave("test.png")
```
![test](https://user-images.githubusercontent.com/11788080/83419300-2afa1880-a425-11ea-91bc-6e5610b81485.png)

This is a [known issue](https://github.com/rstudio/rstudio/issues/2142) of the `png()` graphics device on Windows. To mitigate this one has to use `cairo` and set the `antialias` argument like so.
```r
ggsave("test2.png", type = "cairo-png", antialias = "subpixel")
```
![test2](https://user-images.githubusercontent.com/11788080/83419312-2f263600-a425-11ea-9ba0-1f71068daba9.png)

This is easy enough *if* you know this trick. I'd suggest to automatically set `type = 'cairo-png'` and `antialias = 'subpixel'` on Windows if these arguments have not been explicitly set. I've recently implemented something along those line in the `{hexSticker}` package which uses `ggsave()`. Have a look [here](https://github.com/GuangchuangYu/hexSticker/blob/bc9330a5f6a20d72de98c7d6ace49f0074c984c2/R/sticker.R#L323-L330).

I'd be happy to create a pull request.

**Comment by yutannihilation** [comment]
Thanks. I agree to change the default, but we tend to recommend [ragg](https://github.com/r-lib/ragg) package for high quality plots.

**Comment by thomasp85** [comment]
I'm closing this for now, since we need to have a broader discussion about whether to force certain devices (ragg) on the user
