### ISSUE TITLE
Axis labels with geom_sf & ggmap

### ISSUE THREAD

**Issue by teaguescott** [tidyverse/ggplot2#4044]
I'm trying to create a map using a basemap pulled in using ggmap (get_stamenmap) with some shapefiles plopped on top (geom_sf). I want to change axis labels! Why's it so difficult!

1. When I only plot my basemap, I get axes labeled with lat/lon and NO characters - i.e. **-19**

2. When I add in the shapefiles using ```geom_sf``` I get axes labeled with lat/lon AND characters - i.e. **19°S**

3. When I try change axis labels with ```scale_x_discrete``` along with ```sf_coord(expand = F)``` I can get what I want

4. When I add ```scale_y_discrete``` with label text as I want them I keep getting this error:

```Error: Breaks and labels along y direction are different lengths```

What is going on here? Are there invisible breaks on the y axis that I'm missing?

This works:
```r
ggmap(SA) +
  geom_sf(data = traj_outSF, alpha = 0.4, inherit.aes = F) +
  coord_sf(expand = FALSE) +
  xlab(expression(paste("Longitude (", degree,"E)"))) +
  ylab(expression(paste("Latitude (", degree,"S)"))) +
  scale_x_discrete(breaks = c(33.5, 34, 34.5, 35, 35.5), labels = c("33.5", "34", "34.5", "35", "35.5"))
```
and gets me this:
[correct x axis][1]

As soon as I add in ```scale_y_discrete``` I get the error message

```r
ggmap(SA) +
  geom_sf(data = traj_outSF, alpha = 0.4, inherit.aes = F) +
  coord_sf(expand = FALSE) +
  xlab(expression(paste("Longitude (", degree,"E)"))) +
  ylab(expression(paste("Latitude (", degree,"S)"))) +
  scale_x_discrete(breaks = c(33.5, 34, 34.5, 35, 35.5),
                   labels = c("33.5", "34", "34.5", "35", "35.5"))
  scale_y_discrete(breaks = c(20, 19.5, 19, 18.5, 18,17.5),
                   labels = c("20","19.5","19","18.5","18","17.5"))
```

Heres a reprex:

```r
g = st_sfc(st_point(c(34,-19)))
st_crs(g) <- 4326

SA <- get_stamenmap(bbox = c(33.18, -20.3, 35.8, -17.3), maptype = "toner-lite", zoom = 11)

ggmap(SA) +
  geom_sf(data = g) +
  coord_sf(expand = F) +
  scale_x_discrete(breaks = c(33.5, 34, 34.5, 35, 35.5),
                   labels = c("33.5", "34", "34.5", "35", "35.5")) +
  scale_y_discrete(breaks = c(20, 19.5, 19, 18.5, 18,17.5),
                   labels = c("20","19.5","19","18.5","18","17.5"))
```

Thanks!

  [1]: https://i.stack.imgur.com/U6bdX.png

**Comment by karawoo** [comment]
All of your breaks are outside the range of the map you are trying to plot. Because they're S, they should be -20, -19.5, etc. rather than 20, 19.5, etc.

For future reference, this type of question would be a better fit for [RStudio Community](https://community.rstudio.com/). The ggplot2 issue tracker is intended for bug reports and feature requests.
