### ISSUE TITLE
CI tests failing

### ISSUE THREAD

**Issue by clauswilke** [tidyverse/ggplot2#4045]
Since the last two commits, various integration tests are failing. However, it's somewhat random, with (for example) on Travis three succeeding and four failing. 

<img width="484" alt="Screen Shot 2020-06-05 at 3 34 39 PM" src="https://user-images.githubusercontent.com/4210929/83920583-2a71c280-a742-11ea-995d-59d1e6507627.png">

The most common error is the following:
```
* creating vignettes ... ERROR
Error: processing vignette 'extending-ggplot2.Rmd' failed with diagnostics:
'vignetteInfo' is not an exported object from 'namespace:tools'
Execution halted
```

Not sure if any of the two most recent commits have actually messed anything up. I don't quite see how.

@yutannihilation Any ideas?

**Comment by yutannihilation** [comment]
This is not our fault.

https://github.com/rstudio/rmarkdown/issues/1831

**Comment by yutannihilation** [comment]
But I have no idea about the failure on macOS-latest (devel)...

**Comment by yutannihilation** [comment]
Seems we need to clear cache. #4046

**Comment by yutannihilation** [comment]
While I fixed the problem, it seems we need to wait for the binary version of systemfonts as it seems `remotes::install_deps(dependencies = TRUE)` fails to resolve the dependencies properly (systemfonts should be installed before vdiffr, but it seems not)...

```
 ** byte-compile and prepare package for lazy loading
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
ERROR: lazy loading failed for package ‘vdiffr’
  there is no package called ‘systemfonts’
Calls: <Anonymous> ... loadNamespace -> withRestarts -> withOneRestart -> doWithOneRestart
* removing ‘/Users/runner/runners/2.263.0/work/_temp/Library/vdiffr’
Execution halted
```
