### ISSUE TITLE
Inf is evaluated relative to the panel rather than the scales

### ISSUE THREAD

**Issue by nacnudus** [tidyverse/ggplot2#4051]
Infinite values `Inf` and `-Inf` seem to be evaluated relative to the panel rather than the scale.  When the scales aren't the same, this can have surprising effects.

```r
library(tidyverse)

# Different angles either side of x = 0
ggplot() +
  geom_line(data = tibble(x = c(-Inf, 0, Inf), y = x),
            mapping = aes(x, y)) +
  xlim(c(-1, 1)) +
  ylim(c(-1, 2))
```

![Line graph](https://user-images.githubusercontent.com/3522552/84057895-4aa6b900-a9b0-11ea-908a-3d38436df042.png)

Originally discovered by @catatk.

**Comment by yutannihilation** [comment]
In ggplot2, `Inf` is a special value that refers to the edges of the plot.

> That said, there is one special thing to note in this code: the use of -Inf and Inf as positions. These refer to the top and bottom (or left and right) limits of the plot. (https://ggplot2-book.org/annotations.html#custom-annotations)
