### ISSUE TITLE
coord_fixed doesn't trigger warning when clipping data

### ISSUE THREAD

**Issue by brianlandry1e9** [tidyverse/ggplot2#4052]
When coord_fixed sets the scale limits a warning is not generated when points are removed from the plot. This can lead to clipping of data without the user knowing.

Maybe this has something to do with the "clip" option in coord_fixed causing unwanted behavior?

```r
library(tidyverse)

# Warning generated with scale_y_continous
#
#>Warning message:
#>  Removed 1 rows containing missing values (geom_point). 
data.frame(x = c(1,10), y = c(1,10)) %>%
  ggplot(aes(x,y)) +
  geom_point() +
  scale_y_continuous(limits = c(0,2))



# Warning not generated, datapoint silently clipped
data.frame(x = c(1,10), y = c(1,10)) %>%
  ggplot(aes(x,y)) +
  geom_point() +
  coord_fixed(ylim = c(0,2))
```

This was performed with ggplot2 3.3.0

**Comment by yutannihilation** [comment]
This works as intended. The differences between the limits of a Scale and that of a Coord can be found here:

https://ggplot2-book.org/coord.html#cartesian
