### ISSUE TITLE
scale_fill_viridis_d associated to hang and 100% CPU

### ISSUE THREAD

**Issue by thatchermo** [tidyverse/ggplot2#4054]
I'm running R 4.0.0 and ggplot 3.3.0 on Ubuntu 20.04. When executing the code shown below to create a stacked bar graph with the viridis palette, I get different results depending on how I run it:

(1) From R Studio, it runs fine in the console.
(2) From R alone, running in a terminal, an empty graphics window pops up, the process appears to hang, and the CPU sits at 100%.
(3) When knitting to various output formats, either from inside RStudio or from the command line, (I've tried beamer and ioslides), I get a hang as well.
(4) If I remove the scale_fill_viridis_d line, it runs fine everywhere, creating a bar graph as expected.

I've verified that this example code works on R 3.6.1 and ggplot2 3.2.0, and this example was based on an actual document that used to compile just fine on previous Linux, R and RStudio versions.

I didn't see a similar report, but I apologize if this is a duplicate.

```r
library(tidyverse)
set.seed(1234)
example.data <- data.frame(
  cat.x = sample(1:2, 50, replace=TRUE),
  cat.y = as.factor(sample(1:5, 50, replace=TRUE))
)
ggplot(example.data) + 
  geom_bar(aes(x=cat.x, fill=cat.y), position="fill") + 
  scale_fill_viridis_d()
```

**Comment by yutannihilation** [comment]
Curious. I cannot reproduce this on my Manjaro Linux (with the same version of R and ggplot2). Is this still reproducible if you use some other graphic device (e.g. [ragg](https://github.com/r-lib/ragg))? Did you try reinstalling viridisLite?

**Comment by thatchermo** [comment]
I've now tried updating ggplot (which went to 3.3.1) and viridisLite. I've installed ragg, and run the following code:

```r
library(ragg)
library(tidyverse)
agg_png(file="testplot.png", width=1000, height=600, res=144)
set.seed(1234)
example.data <- data.frame(
  cat.x = sample(1:2, 50, replace=TRUE),
  cat.y = as.factor(sample(1:5, 50, replace=TRUE))
)
ggplot(example.data) +
  geom_bar(aes(x=cat.x, fill=cat.y), position="fill") +
  scale_fill_viridis_d()
dev.off()
```
This code works correctly when copied into the console in RStudio (it creates a file with the graphic in it), but the same code hangs when I execute it from R running within a terminal window. This surprises me, since I assumed it might be a problem with graphic device, and I thought maybe RStudio console used a different graphics device to display within RStudio, compared to R in a terminal.

I'm executing the code in the same working directory, so it isn't a permission problem.

If I remove the viridis line, the code works in both places.

I'm glad you can't replicate it, in the sense that it seems like an annoying bug if it were to hit everyone. I can't ask you to figure out what's wrong on my system, but if you have any other ideas of where to look or what might be different between the RStudio console environment on one hand and R in a terminal or through knitr on the other hand, I'd be happy for suggestions.

**Comment by yutannihilation** [comment]
> I assumed it might be a problem with graphic device

Yeah, I suspected it, too...

Hmm, then I have almost no idea... Could you try the previous version of ggplot2? (e.g. `remotes::install_version("ggplot2", "3.2.1")`). If the version of ggplot2 matters, some cause might be on ggplot2's side.

Btw, I think your question is more likely to be answered properly on [RStudio Community](https://community.rstudio.com/) than here. If you didn't try it yet, it might be worth trying.

**Comment by thatchermo** [comment]
Thanks, I'll try RStudio Community, and from all I can tell, whatever this bug is is not a bug in ggplot, so feel free to close it. But I'm parking this information here, since it still seems to me that someone encountering this bug might find it in the same way I did (with the scale_color_viridis_c command or similar).

- Observation 1: This bug doesn't happen on a clean Ubuntu 20.04 install that I have on VirtualBox. My real system is an upgrade from 19.04 to 19.10 to 20.04, for what that's worth.

- Observation 2: Completely uninstalling/reinstalling R and RStudio on my real system, purging all config files, etc. doesn't seem to solve the problem.

- Workaround: `colorspace::scale_color_continuous_sequential` with the `Viridis` palette.

- I've tracked it to the viridisLite package, and a minimal set of commands to trigger the bug are

`library(viridisLite); viridis(10)` from R running in a terminal window.

- Those commands work for me when executed from RStudio's console on the same computer.

- Looking at the code for the `viridis` command from that package, if I type the code in manually as shown below, it hangs at the invocation of `fn_cols`. Doesn't matter if I replace `spline` with `linear` in the `colorRamp` command. Some code works fine on a fresh install.

```
library(viridisLite)
n=10; alpha = 1; begin = 0; end = 1; direction = 1; option = "D"
if (begin < 0 | begin > 1 | end < 0 | end > 1) {
        stop("begin and end must be in [0,1]")
}
if (abs(direction) != 1) {
    stop("direction must be 1 or -1")
}
if (direction == -1) {
    tmp <- begin
    begin <- end
    end <- tmp
}
option <- switch(EXPR = option, A = "A", magma = "A", B = "B",
    inferno = "B", C = "C", plasma = "C", D = "D", viridis = "D",
    E = "E", cividis = "E", {
        warning(paste0("Option '", option, "' does not exist. Defaulting to 'viridis'."))
        "D"
    })
map <- viridisLite::viridis.map[viridisLite::viridis.map$opt ==
    option, ]
map_cols <- grDevices::rgb(map$R, map$G, map$B)
fn_cols <- grDevices::colorRamp(map_cols, space = "Lab",
    interpolate = "spline")
# Hangs at the next line!
cols <- fn_cols(seq(begin, end, length.out = n))/255
grDevices::rgb(cols[, 1], cols[, 2], cols[, 3], alpha = alpha)
```
- Replacing the `space="Lab"` option with `space="rgb"` option yields code that runs and (oddly?) produces the same output as `viridis(10)` on a system where that command works.

- So function `fn_cols` seems to be created OK, but that function itself hangs when called. And that's as far as I've had energy to trace it at the moment. Next step would be to look at how the conversion to Lab and the interpolation breaks down?

- It wouldn't be so bad if I didn't use the viridis scales all the time! Will I reinstall the whole operating system to see if it will fix this problem? Just maybe, but I'd rather figure it out.
