### ISSUE TITLE
Installing tex fonts messes up plots

### ISSUE THREAD

**Issue by JorisGoosen** [tidyverse/ggplot2#4055]
If one is working on Ubuntu 20.04 and one installs certain tex fonts, for instance "texmaker" and its related pkgs. ggplot2 no longer seems to render plots properly.

```r
library(GGally)
ggpairs(mtcars[, c('mpg', 'cyl')])
```

Results in:
![afbeelding](https://user-images.githubusercontent.com/29062713/84178329-81e69a00-aa84-11ea-9703-91b5615b199a.png)

If I remove all tex related stuff from Ubuntu I get this:
![afbeelding](https://user-images.githubusercontent.com/29062713/84178746-3a144280-aa85-11ea-910f-2cd25199822d.png)

Im guessing the fonts shouldn't stop working after installing tex but maybe im missing something.

This mostly came up for us at JASP through this issue: https://github.com/jasp-stats/jasp-issues/issues/780 and there we can work around the problem by uninstalling "tex-gyre" but I don't understand why ggplot starts using these fonts, or getting messed up by it.

**Comment by thomasp85** [comment]
This an issue with the png device and how it interprets mono fonts. There is nothing we can do from the ggplot2 side, but I know the issue has been raised. You can use the devices from ragg instead to avoid it, though it doesn't provide a windowed device, only file devices

**Comment by JorisGoosen** [comment]
Ah thank you for the response!

Ok, I guess we will try that then. Luckily we don't need windowed devices.
