### ISSUE TITLE
ggsave should use plot theme for default background

### ISSUE THREAD

**Issue by hadley** [tidyverse/ggplot2#4057]
I think @djnavarro tweeted about this recently, and I hit it too. It seems like in a situation like this:

```R
plot %>%
  ...
  theme(
   plot.background = element_rect(fill = NA, colour = NA)
  )

ggsave("ratios.png", width = 8, height = 4.5, bg = NA)
```

`ggsave()` could automatically figure out what `bg` should be and pass it along to the graphics device.

**Comment by mcanouil** [comment]
Hi,

i have been using a customised ggsave for that purpose, although it might not be the best approach to handle that.
Here it is (initially from https://github.com/mcanouil/mctemplates/blob/8a42d07300841ab2e3936ab63fe92a25a0781bff/R/theme_black.R#L277)
``` r
ggsave <- function(
  filename,
  plot = ggplot2::last_plot(),
  device = NULL,
  path = NULL,
  scale = 1,
  width = NA,
  height = NA,
  units = c("in", "cm", "mm"),
  dpi = 300,
  limitsize = TRUE,
  ...
) {
  if (is.null(plot$theme$plot.background$colour)) {
    bc <- ggplot2::theme_get()$plot.background$colour
    .theme <- ggplot2::theme_get()
  } else {
    bc <- plot$theme$plot.background$colour
    .theme <- plot$theme
  }

  ggplot2::ggsave(
    filename = filename,
    plot = plot,
    device = device,
    path = path,
    scale = scale,
    width = width,
    height = height,
    units = units,
    dpi = dpi,
    limitsize = limitsize,
    bg = bc,
    ...
  )
}
```
I did the same tweak for the print method https://github.com/mcanouil/mctemplates/blob/8a42d07300841ab2e3936ab63fe92a25a0781bff/R/theme_black.R#L231

I'll probably make my first PR to ggplot2 in the next few days.

**Comment by clauswilke** [comment]
@mcanouil I'm not sure this is the right approach, as it short-circuits the regular ggplot theme calculations.

In general, this is a tricky problem that I expect will require us to separately call `ggplot_build()` and `ggplot_gtable()` to be able to extract the theme without generating any grobs before the graphics device is set up.

**Comment by thomasp85** [comment]
@Clauswilke which other places could the plot background be calculated? I think it is fair to expect it to either be set on the plot theme or get it from the default theme in lieu of having to implement yet another rendering routine

**Comment by clauswilke** [comment]
Most importantly, I think it's a matter of keeping the code clean. We just spent a lot of effort removing one-off interactions with the theme system and trying to boil all interactions down to a small set of shared functions that are reliably called. This proposed patch would go in the opposite direction.

To your specific question, this is the code the calculates the final theme:
https://github.com/tidyverse/ggplot2/blob/112f960b2cf52257e75e4ee9d2b2a85d4dcc2bb7/R/theme.r#L420-L447

One issue that the current proposed patch doesn't handle is if the global theme does not have a properly defined background element.

**Comment by clauswilke** [comment]
The other issue is that theme elements really should be calculated with `calc_element()` is we want to keep the code maintainable and predictable going forward.
https://github.com/tidyverse/ggplot2/blob/112f960b2cf52257e75e4ee9d2b2a85d4dcc2bb7/R/theme.r#L509

**Comment by thomasp85** [comment]
Those are fair points. I think the path forward should be to provide a utility function that can properly calculate a given theme element and then use that. Splitting up the build process for this seems like the wrong direction to take as well

**Comment by clauswilke** [comment]
If you don't mind that `ggsave()` will duplicate the theme calculation, you could simply do:

``` r
bg <- calc_element("plot.background", plot_theme(plot))
bg_colour <- bg$colour
```

**Comment by thomasp85** [comment]
If that is all it takes then I think we should do that (if background is set to `NULL`)

**Comment by clauswilke** [comment]
Yeah, I think this would work. Note we need `fill`, not `colour`.

``` r
library(ggplot2)

theme_set(theme_gray() + theme(plot.background = element_rect(fill = "cornsilk")))

p1 <- ggplot(mtcars, aes(disp, mpg)) + geom_point()
p2 <- p1 + theme(plot.background = element_rect(fill = "skyblue"))
p3 <- p1 + theme_gray()

calc_element("plot.background", ggplot2:::plot_theme(p1))$fill
#> [1] "cornsilk"
calc_element("plot.background", ggplot2:::plot_theme(p2))$fill
#> [1] "skyblue"
calc_element("plot.background", ggplot2:::plot_theme(p3))$fill
#> [1] "white"
```

<sup>Created on 2020-06-22 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by mcanouil** [comment]
> The other issue is that theme elements really should be calculated with `calc_element()` is we want to keep the code maintainable and predictable going forward.
> https://github.com/tidyverse/ggplot2/blob/112f960b2cf52257e75e4ee9d2b2a85d4dcc2bb7/R/theme.r#L509

At least, now I am aware of those internals (thanks!).
I wrote the tweak/patch with v2.2.0 at that time and did not update that part at all since then.

I wonder, if there is a computational "burden" in ggsave because of the double calculation.
Is it worst or the same within the print/plot method, if we want the "interactive" device (x11/cairo/...) to get the background information as well?
