### ISSUE TITLE
Breaks become identical when range is small and closest int is non-zero

### ISSUE THREAD

**Issue by Alanocallaghan** [tidyverse/ggplot2#4060]
I ran into this breaks issue when plotting some values that are all very close to one. The axis breaks are shown as exactly 1, which is non-informative. If the closest int is zero, breaks are displayed as expected. See reprex.

I realise this is a bit of an edge case so not terribly high priority, but I'm flagging it in case anybody else runs into it. A fix might be to figure out what the closest int is, and then add that to the correctly-formatted values you'd get if zero-centred. eg, `1 + 1e-08` etc in this case.

``` r
library("ggplot2")
set.seed(42)
make_plot <- function(mean = 0, sd = 1e-8, n = 100) {
    ggplot() + aes(rnorm(n, mean = mean, sd = sd)) + geom_histogram()
}
make_plot()
#> `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
```
![](https://i.imgur.com/PcaZrrG.png)

``` r
make_plot(mean = 1)
#> `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
```
![](https://i.imgur.com/UoySAa8.png)

**Comment by clauswilke** [comment]
This is just a fundamental problem with rounding that cannot be addressed in a generic way. If you're adding a very small number to a much larger number then the result is essentially just the much larger number unchanged. In situations like this, the person creating the plot will have to find a way to resolve the issue, e.g. by shifting the x axis to be centered around zero.
