### ISSUE TITLE
plot.caption.position does not work for me

### ISSUE THREAD

**Issue by ymer** [tidyverse/ggplot2#4068]
plot.caption.position = "plot" does not move the caption all the way to the left, like plot.title.position = "plot" does for the title.

reprex:

``` r
library(tidyverse)
packageVersion("ggplot2")
#> [1] '3.3.0'
ggplot(iris, aes(x = Sepal.Length, y = Sepal.Width, col = Species)) +
  labs(caption = "Caption here", title = "Title") +
  geom_point() +
  theme(
    plot.title.position = "plot",
    plot.caption.position = "plot"
  )
```
<sup>Created on 2020-06-18 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by clauswilke** [comment]
That's because the default for the caption is right alignment. You need to set `hjust` appropriately.
