### ISSUE TITLE
group column in built data even when aes(group) absent

### ISSUE THREAD

**Issue by tdhock** [tidyverse/ggplot2#4070]
Hi all. First of all thanks for maintaining ggplot2, it is so useful.

I maintain directlabels::geom_dl which provides a custom geom with a draw_panel method. I was expecting that the built data that I get in the first argument of the draw_panel method should only have a "group" column if I specify aes(group). However I am observing that there is a "group" column even when aes(group) is not specified. Is that normal? 

When aes(group) is not specified by the user I would like to be able to assign a default value for group in my draw_panel method, but I can't do that by testing for presence/absence of the group column (it is always there). Is there another way for me to test whether or not the user has specified aes(group), and assign a default?

Furthermore I observe that group is a vector of -1 if aes(y=numeric_var) but it is a vector with values matching y if aes(y=factor_var). Is that normal? I was expecting that the group column should only depend on aes(group), not aes(y).

Here is a reprex showing what happens when aes(y=numeric_var)
```r
library(ggplot2)
p <- ggplot()+
  geom_text(aes(
    deaths, age, label=sex),
    data=data.frame(
      deaths=1:4,
      age=rep(5:6, each=2),
      sex=rep(c("M", "F"), 2)))
ggplot2::ggplot_build(p)$data[[1]][, c("x", "y", "label", "group")]
#>   x y label group
#> 1 1 5     M    -1
#> 2 2 5     F    -1
#> 3 3 6     M    -1
#> 4 4 6     F    -1
```

Here is a reprex showing what happens when aes(y=factor_var)
```r
library(ggplot2)
p <- ggplot()+
  geom_text(aes(
    deaths, age, label=sex),
    data=data.frame(
      deaths=1:4,
      age=factor(rep(5:6, each=2)),
      sex=rep(c("M", "F"), 2)))
ggplot2::ggplot_build(p)$data[[1]][, c("x", "y", "label", "group")]
#>   x y label group
#> 1 1 1     M     1
#> 2 2 1     F     1
#> 3 3 2     M     2
#> 4 4 2     F     2
```

Thanks in advance for any help you can provide.

**Comment by teunbrand** [comment]
Related to this, I also had to scratch my head trying to circumvent the automatic grouping while trying to make a new stat (details about that in [this SO question](https://stackoverflow.com/questions/62075586/escape-discrete-aesthetic-implies-group-in-custom-stat)). 

Would it be an ok idea to give the layer some control over what aesthetic(s) can trigger automatic grouping?

I could maybe see that the `layer()` function could get an extra argument that controls what goes into the right side of the following `%in%` and which defaults to `c("label", "PANEL")`.

https://github.com/tidyverse/ggplot2/blob/211472ff27b0d72d19dcb08b22f510d8cbbd791c/R/grouping.r#L16

Then, the problem @tdhock is facing can also be controlled at the geom constructor level, as he could then exclude position aesthetics (or/and others) from forming automatic groups. I don't know the constraints on the code well enough to judge whether this seems feasible.

**Comment by yutannihilation** [comment]
At the moment, I'm not sure if this is really useful, but I agree we tend to face this kind of needs when we want to create a new Geom/Stat. The absence of the convention about whether the Geom/Stat is group-wise or not was one of the main difficulties on implementing gghighlight.

One possibility is that ggplot2 might eventually export `Layer` and then you will be able to tweak `compute_aesthetics()`, but I think it won't happen any time soon. 

``` r
library(ggplot2)

`%||%` <- ggplot2:::`%||%`

# Layer is not exported
Layer <- ggplot2:::Layer

LayerNoGroup <- ggproto("LayerNoGroup", Layer,
  compute_aesthetics = function(self, data, plot) {
    data <- ggproto_parent(Layer, self)$compute_aesthetics(data, plot)
    # overwrite group if no group is explicitly mapped
    if (is.null(self$mapping$group)) {
      data$group <- -1
    }
    data
  }
)

geom_text2 <- function(mapping = NULL, data = NULL,
                      stat = "identity", position = "identity",
                      ...,
                      parse = FALSE,
                      nudge_x = 0,
                      nudge_y = 0,
                      check_overlap = FALSE,
                      na.rm = FALSE,
                      show.legend = NA,
                      inherit.aes = TRUE)
{
  if (!missing(nudge_x) || !missing(nudge_y)) {
    if (!missing(position)) {
      abort("You must specify either `position` or `nudge_x`/`nudge_y`.")
    }
    
    position <- position_nudge(nudge_x, nudge_y)
  }
  
  layer(
    data = data,
    mapping = mapping,
    stat = stat,
    geom = GeomText,
    position = position,
    show.legend = show.legend,
    inherit.aes = inherit.aes,
    params = list(
      parse = parse,
      check_overlap = check_overlap,
      na.rm = na.rm,
      ...
    ),
    layer_class = LayerNoGroup
  )
}

p <- ggplot()+
  geom_text2(aes(
    deaths, age, label=sex),
    data=data.frame(
      deaths=1:4,
      age=factor(rep(5:6, each=2)),
      sex=rep(c("M", "F"), 2)))

ggplot_build(p)$data[[1]][, c("x", "y", "label", "group")]
#>   x y label group
#> 1 1 1     M    -1
#> 2 2 1     F    -1
#> 3 3 2     M    -1
#> 4 4 2     F    -1
```

<sup>Created on 2020-06-20 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by thomasp85** [comment]
You can always deduce if a group was explicitly assigned by seeing if the group column is positive... The `-1` is an indicator saying that everything automatically belongs to the same group

`group` and `PANEL` are the two single columns that are enforced to always exist in the layer data and is used extensively during the data preparation pipeline so it is unlikely that we will make their presence optional
