### ISSUE TITLE
geom_violin default adjust value for integers

### ISSUE THREAD

**Issue by SimonDedman** [tidyverse/ggplot2#4071]
If one calls geom_violin on a vector of integers (which is not the intended use, I know), the default plotting style tapers the area towards zero between points, which looks weird. I feel like it would be no less wrong to smooth the lines between the on-integer apexes, and would look better. Be interested to hear your thoughts. Cheers.

![Stock_Month](https://user-images.githubusercontent.com/4599748/85182057-6b86ce00-b23c-11ea-9ba1-cda9eb27815f.png)

**Comment by yutannihilation** [comment]
Use `adjust`. By the way, I couldn't draw such wavy violins with the default `adjust`...

``` r
library(ggplot2)

set.seed(190)
d <- data.frame(
  g = sample(c("a", "b"), 100, TRUE),
  v = sample(6:11, 100, TRUE)
)

ggplot(d, aes(g, v)) +
  geom_violin()
```

![](https://i.imgur.com/RAh2zsd.png)

``` r

ggplot(d, aes(g, v)) +
  geom_violin(adjust = .3)
```

![](https://i.imgur.com/hLxLhkc.png)

<sup>Created on 2020-07-01 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
