### ISSUE TITLE
undefined columns selected with groupS aes in custom geom

### ISSUE THREAD

**Issue by tdhock** [tidyverse/ggplot2#4072]
Hi again. I'm the maintainer of directlabels::geom_dl and I'm trying to figure out a way to let the user optionally specify a grouping variable to use, and to detect when the user specifies that in my draw_panel method. Originally I was trying to use aes(group) for this purpose but that does not work, see #4070.

Now I am considering using another aes for this purpose, like aes(groupS), but I'm observing the following error:
```
Error in `[.data.frame`(data, "group") : undefined columns selected
```
I expected that I could use any custom aes, but this one is not working.

This happens because of a bug in grouping.r, which currently tests for absence of group column via
```
  if (is.null(data$group)) {
```
however that test will not work if there is another column/aes (like groupS) that starts with group. The fix is to change it to 
```
  if (is.null(data[["group"]])) {
```
Here is a reprex using a standard ggplot2 geom 
```
library(ggplot2)
ggplot()+
  geom_point(aes(
    Petal.Length, Petal.Width, groupS=1),
    data=iris)
#> Warning: Ignoring unknown aesthetics: groupS
#> Error in `[.data.frame`(data, "group"): undefined columns selected
```

**Comment by yutannihilation** [comment]
Hmm, partial matching bites... Thanks, good catch.
