### ISSUE TITLE
same argument/param in both stat and geom?

### ISSUE THREAD

**Issue by tdhock** [tidyverse/ggplot2#4073]
Hi again. I'm trying to address this issue https://github.com/tdhock/directlabels/issues/24 which contains a reprex.

Basically, my directlabels::geom_dl has an optional method argument/param, which conflicts with the method argument/param of stat_smooth. Is there any way that the user can write `geom_dl(method="something", stat="smooth")` and then have ggplot2 send the method argument to geom_dl instead of stat_smooth?

I expected that there should be some way to use geom_dl with stat_smooth, and optionally be able to specify a method argument for either or both.

BTW this was working fine in 2013 at the time of my original SO answer https://stackoverflow.com/questions/10065196/how-to-show-directlabels-after-geom-smooth-and-not-after-geom-line/19509557#19509557

**Comment by yutannihilation** [comment]
Hmm, interesting. ggplot2 doesn't have such a mechanism to distinguish the same name of params, and I'm afraid it's hard to implement such a feature...

https://github.com/tidyverse/ggplot2/blob/cb0cfd2aea18ee4ebf671bed52dbd566ebeaf7ea/R/layer.r#L112-L113

Of course you can override the parameter manually, but I don't think this is a usage that is ensured to keep working.

``` r
library("ggplot2")
library(directlabels)
set.seed(124234345)

# Generate data
df.2 <- data.frame(
  "n_gram" = c("word1"),
  "year" = rep(100:199),
  "match_count" = runif(100, min = 1000, max = 2000)
)

df.2 <- rbind(df.2, data.frame(
  "n_gram" = c("word2"),
  "year" = rep(100:199),
  "match_count" = runif(100, min = 1000, max = 2000)
))

# use stat smooth with geom_dl to get matching direct labels.
span <- 0.3
p <- ggplot(df.2, aes(year, match_count, group = n_gram, color = n_gram)) +
  stat_smooth(size = 2, span = span, se = F) +
  geom_dl(aes(label = n_gram), method = "last.qp", stat = "smooth", span = span)

p$layers[[2]]$stat_params$method <- NULL
```

<sup>Created on 2020-06-30 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by thomasp85** [comment]
Yeah, this is not really possible at the moment. We have discussion about how aesthetics/parameters for stat and geom interact and potentially this will all get cleared up at some point, but no promises

**Comment by tdhock** [comment]
keep open? or ref another issue where you "have discussion about how aesthetics/parameters for stat and geom interact" ?
