### ISSUE TITLE
coord_proj is throwing a "Not implemented error"

### ISSUE THREAD

**Issue by colinaverill** [tidyverse/ggplot2#4082]
Below is some simplified code to plot a world map using ggplot2. This code was working fine for me until April, at which point I started getting `Error: not implemented`. Line by line testing links this outcome to the `coord_proj()` line. There was some discussion of this on [stackoverflow](https://stackoverflow.com/questions/61104707/why-does-coord-proj-and-ggplot2-give-me-this-error), but no definitive solution was found. Reproducible example and error messages below.

```r
world <- ggplot2::map_data("world")
world <- world[world$region != "Antarctica",]
gg <- ggplot()
gg <- gg + geom_cartogram(data=world, map=world,
                          aes(x=long, y=lat, map_id=region))
gg <- gg + coord_proj("+proj=wintri")
gg
```

Error messages:
```
Error: Not implemented
Run `rlang::last_error()` to see where the error occurred.
> rlang::last_error()
<error/rlang_error>
Not implemented
Backtrace:
  1. (function (x, ...) ...
  2. ggplot2:::print.ggplot(x)
  4. ggplot2:::ggplot_gtable.ggplot_built(data)
  5. base::Map(...)
  6. base::mapply(FUN = f, ..., SIMPLIFY = FALSE)
  8. l$draw_geom(d, layout)
  9. ggplot2:::f(..., self = self)
 10. self$geom$draw_layer(data, self$geom_params, layout, layout$coord)
 11. ggplot2:::f(..., self = self)
 12. base::lapply(...)
 13. ggplot2:::FUN(X[[i]], ...)
 16. ggalt:::f(...)
 17. ggplot2::coord_munch(coord, map, panel_scales)
 18. coord$backtransform_range(range)
 19. ggplot2:::f(..., self = self)
Run `rlang::last_trace()` to see the full context.
```

**Comment by yutannihilation** [comment]
Could you file this issue on ggalt's repo? At the moment, I'm not sure if this is a bug on ggalt's side or on ggplot2's side, but this sounds ggalt needs to implement `backtransform_range()`.

**Comment by colinaverill** [comment]
Sure thing. Thanks.

**Comment by yutannihilation** [comment]
Ah, this one seems the same issue: https://github.com/hrbrmstr/ggalt/issues/62

**Comment by clauswilke** [comment]
Not sure what `coord_proj()` does but I suspect there'll be little need for it once we merge #3659. I can try to finish this off in the next few days. Just one last issue remaining.

**Comment by clauswilke** [comment]
Sorry, I was overly optimistic. Winkel tripel is not supported by {sf} (due to lack of inverse transformation) and therefore won't be possible with `coord_sf()`. 

If you want to make a map using this projection, I suggest you follow this tutorial:
https://wilkelab.org/practicalgg/articles/Winkel_tripel.html
