### ISSUE TITLE
Cannot override.aes with guide_bins?

### ISSUE THREAD

**Issue by jdsher** [tidyverse/ggplot2#4085]
Controlling the appearance of the geoms within a scale_size_binned legend using `guide_bins()` doesn't seem to operate in the same fashion as `guide_legend()` - or rather, there appears to be no overriding the `aes()` despite the documentation implying no difference. 

To illustrate, this:

```r
ggplot(mtcars, aes(x = drat, y = wt, size = hp, fill = cyl)) + 
geom_point(shape = 21) + 
scale_size_binned(guide = guide_legend(override.aes = list(colour = "red", shape = 21, fill = "blue")))
```
...works as expected, while this:

```r
ggplot(mtcars, aes(x = drat, y = wt, size = hp, fill = cyl)) + 
geom_point(shape = 21) + 
scale_size_binned(guide = guide_bins(override.aes = list(colour = "red", shape = 21, fill = "blue")))
```
...does not.

**Comment by yutannihilation** [comment]
Thanks, confirmed. It seems we just forget to pass `override.aes` to the guide...

https://github.com/tidyverse/ggplot2/blob/cb0cfd2aea18ee4ebf671bed52dbd566ebeaf7ea/R/guide-bins.R#L92-L129

Rendered reprex:

``` r
library(ggplot2)
library(patchwork)

ggplot(mtcars, aes(x = drat, y = wt, size = hp, fill = cyl)) + 
  geom_point(shape = 21) + 
  scale_size_binned(guide = guide_legend(override.aes = list(colour = "red", shape = 21, fill = "blue")))
```

![](https://i.imgur.com/C5SY8ri.png)

``` r

ggplot(mtcars, aes(x = drat, y = wt, size = hp, fill = cyl)) + 
  geom_point(shape = 21) + 
  scale_size_binned(guide = guide_bins(override.aes = list(colour = "red", shape = 21, fill = "blue")))
```

![](https://i.imgur.com/znyyq4N.png)

<sup>Created on 2020-06-30 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
