### ISSUE TITLE
Feature request: Extended palettes for brewer scales

### ISSUE THREAD

**Issue by tjebo** [tidyverse/ggplot2#4088]
I think it would be great to allow an easy extension of the brewer palettes to "more colors" especially for the new binned scales. 

1. The palettes look great
1. They are commonly used and recognised
1. The bins in sequential data may frequently exceed the maximum colors given by the original palettes.

Below one suggestion how this could look like. This is also part of [this thread on Stackoverflow.](https://stackoverflow.com/questions/62543112/how-to-make-discrete-gradient-color-bar-with-geom-contour-filled/62571158#62571158) I have added a warning in order to make the user aware of the "breach" of the original palette.

There may be this option out there already? Note that a gradient creating function such as `colourspace::scale_fill_continuous_sequential` does not work in this example, because it does not result in a binned scale. 

I'd also be happy to create a pull request for this one, if the package maintainer should like this concept :)

``` r
library(ggplot2)

ggplot(mtcars, aes(mpg, disp, fill = hp)) +
  geom_point(shape = 21) +
  scale_fill_craftfermenter(
    breaks = seq(0,520,40),
    limits = c(0,520),
    palette = "Spectral",
    guide=  guide_colorsteps(even.steps = FALSE, # workaround for issues #4019/#4100
                             barheight = 15) 
  )
#> Warning: 13 colours used, but Spectral has only 11 - New palette created based
#> on all colors of Spectral
```

![](https://i.imgur.com/TxsPfuj.png)

<sup>Created on 2020-06-28 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**The modified functions**
```r
# modified brewer_pal()
craftbrewer_pal <- function (type = "seq", palette = 1, direction = 1) {
  pal <- scales:::pal_name(palette, type)
  force(direction)
  function(n) {
    n_max_palette <- RColorBrewer:::maxcolors[names(RColorBrewer:::maxcolors) == palette]
    
    if (n < 3) {
      pal <- suppressWarnings(RColorBrewer::brewer.pal(n, pal))
    } else if (n > n_max_palette){
      rlang::warn(paste(n, "colours used, but", palette, "has only",
                        n_max_palette, "- New palette created based on all colors of", 
                        palette))
      n_palette <- RColorBrewer::brewer.pal(n_max_palette, palette)
      colfunc <- grDevices::colorRampPalette(n_palette)
      pal <- colfunc(n)
    }
    else {
      pal <- RColorBrewer::brewer.pal(n, pal)
    }
    pal <- pal[seq_len(n)]
    if (direction == -1) {
      pal <- rev(pal)
    }
    pal
  }
}

# modified scale_fill_fermenter

scale_fill_craftfermenter <- function(..., type = "seq", palette = 1, direction = -1, na.value = "grey50", guide = "coloursteps", aesthetics = "fill") {
  type <- match.arg(type, c("seq", "div", "qual"))
  if (type == "qual") {
    warn("Using a discrete colour palette in a binned scale.\n  Consider using type = \"seq\" or type = \"div\" instead")
  }
  ggplot2:::binned_scale(aesthetics, "craftfermenter", ggplot2:::binned_pal(craftbrewer_pal(type, palette, direction)), na.value = na.value, guide = guide, ...)
}
```

**Comment by tjebo** [comment]
I'd be also happy to create a pull request for this one, if the package maintainer should like this concept :)

**Comment by thomasp85** [comment]
This is definitely useful to some people but I think this would be best suited for an extension package. The brewer palettes has been designed with a maximum number of colours to make sure that everthing is visually distinguishable so I think t best if the basic brewer scale honoured that constraint

**Comment by tjebo** [comment]
Thanks @thomasp85 . For the future reader who comes across this - if it helps, I have an early implementation of this in https://github.com/tjebo/ggtrail
I am not sure if this package will ever find the way to CRAN, so it may remain a bit unstable.
