### ISSUE TITLE
geom_col flips coordinates and displays totally incomprehensible data

### ISSUE THREAD

**Issue by FredrikWartenberg** [tidyverse/ggplot2#4089]
When using geom_col if sometimes encounter that the plot is flipped and the  display is totally incomprehensible. It has happened to me in Windows and Linux. The data is generated using 'hist(fspd,breaks=breaksV,plot = FALSE)', and using mids, densities and counts. The error has only occurred using counts.

In addition to reprex I have included the code and data to reproduce the problem
[ggplotBug.zip](https://github.com/tidyverse/ggplot2/files/4832003/ggplotBug.zip)

``` r
library(ggplot2)
#> Warning: package 'ggplot2' was built under R version 3.6.3
library(data.table)
#> Warning: package 'data.table' was built under R version 3.6.3
exData <- fread("c:/Users/viking/repos/ggplotBug/data.csv")

## Showing counts, graph is flipped and makes no sense
windows()
pNOK <- (ggplot(exData) + geom_col(aes(y=counts,x=hMids*60)) + labs(title="Not OK"))
print(pNOK)
```

![](https://i.imgur.com/SjJJWZc.png)

``` r

## Showing densities, graph is OK
windows()
pOK <- (ggplot(exData) + geom_col(aes(y=dens,x=hMids*60)) + labs(title="OK"))
print(pOK)
```

![](https://i.imgur.com/bILRGyj.png)

<sup>Created on 2020-06-25 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by karawoo** [comment]
This has been fixed in the latest version of ggplot2. If you upgrade, it should work as you expect. If you upgrade and still have problems, could you please open an issue with a fully self-contained reprex (i.e. defining a minimal amount of data inline, rather than loading an external file)?
