### ISSUE TITLE
Use sf_project() in function sf_transform_xy()

### ISSUE THREAD

**Issue by clauswilke** [tidyverse/ggplot2#4090]
Per @edzer (https://twitter.com/edzerpebesma/status/1276159543152705543?s=20), `sf::sf_project()` should do what we need and should be faster than the method currently implemented in `sf_transform_xy()` (which generates a list of separate points and then transforms them one by one).

**Comment by beroe** [comment]
Hi @clauswilke The new spatial plotting looks great. I've been able to replicate some of the examples you posted on twitter, but I hit a block when trying to add points to particular projections. I've been unable to get `sf_transform_xy` or `sf_project to work`. 
Would it be possible to post an example showing both an alternative projection and plotting points of converted coordinates? This is my most common workflow.

For example, this works:
```
ndf = data.frame(lat=35.8, long=-78.6,name="Raleigh")
# nc defined as in your tweet

ggplot(ndf,aes(x=long,y=lat)) + 
	annotation_map(map_data("state"),fill="antiquewhite",colour="darkgrey") + 
	geom_sf(data=nc,size=0.1,fill="white",inherit.aes=FALSE) + 
	geom_point() + 
	geom_text(aes(label=name))

```
But if I add ` + coord_sf(crs=2264)` to the end, then the point ends up in the lower left corner of the map.

![withcoordsf](https://user-images.githubusercontent.com/871533/86322564-12ca1480-bbf0-11ea-8e92-112af80703d1.png)

Similarly, if I do this (below, specifying x and y limits) then the point appears to be plotted correctly, but the axis labels are all wrong.

```ggplot(ndf,aes(x=long,y=lat)) + 
	annotation_map(map_data("state"),fill="antiquewhite",colour="darkgrey") + 
	geom_sf(data=nc,size=0.1,fill="white",inherit.aes=FALSE) + 
	geom_point() + 
	geom_text(aes(label=name)) + 
	coord_sf(crs=2264, xlim=c(-82,-76),ylim=c(34,37))
```
![withlimits](https://user-images.githubusercontent.com/871533/86322599-22e1f400-bbf0-11ea-812b-9fe13ef561b9.png)
