### ISSUE TITLE
Code style in examples hard to read in reference docs

### ISSUE THREAD

**Issue by rjake** [tidyverse/ggplot2#4092]
---
Really minor but the code could be easier to read in some of the examples. 

In the [sec_axis() example](https://ggplot2.tidyverse.org/reference/sec_axis.html#examples
) it looks ok if I copy and paste the code but in the help menu and the ref docs, it's hard to see where the parentheses start and end and the piping of the plot elements

<img src="https://user-images.githubusercontent.com/14003618/85776761-037a3100-b6ef-11ea-84cb-f3bd9bad0e2f.png" height="125"/>

When copied, it's easier to read:
```r
ggplot(df, aes(x = dx, y = price)) + geom_line() +
  scale_x_datetime("Date", date_labels = "%b %d",
                   date_breaks = "6 hour",
                   sec.axis = dup_axis(name = "Time of Day",
                                       labels = scales::time_format("%I %p")))
```
I'd like for it to look like this:
```r
ggplot(df, aes(x = dx, y = price)) +
  geom_line() +
  scale_x_datetime(
    name = "Date",
    date_labels = "%b %d",
    date_breaks = "6 hour",
    sec.axis = dup_axis(
      name = "Time of Day",
      labels = scales::time_format("%I %p")
    )
  )

```

**Comment by karawoo** [comment]
I agree and it should be updated to follow tidyverse style. Would you be interested in opening a pull request? The relevant lines are here:

https://github.com/tidyverse/ggplot2/blob/ccd94e14847b64342df01432a1489e86c9d19a8e/R/axis-secondary.R#L71-L82

**Comment by rjake** [comment]
Yes. I'll take it

**Comment by rjake** [comment]
@karawoo Should I go through all the examples? When done, do I rebuild the site? I've seen some repos ask contributors not to.

**Comment by yutannihilation** [comment]
> Should I go through all the examples?

You don't need to (though it would be really appreciated if you do so). ggplot2 has so massive amount of examples that we probably cannot check if your pull request is comprehensive or not. I personally think we should automatically style all the code by using styler at some point... Anyway you can pick only the examples that you want to fix.

> When done, do I rebuild the site?

You don't need to rebuild the pkgdown site as it is automatically built by GitHub Actions CI after your pull request is merged. (If you meant "regenerate the docs," please do.)

Note that you need to install the specific branch of roxygen2 by `devtools::install_github("r-lib/roxygen2#1109")` to generate the docs for now. c.f. https://github.com/r-lib/roxygen2/issues/1108
