### ISSUE TITLE
Stop AppVeyor

### ISSUE THREAD

**Issue by yutannihilation** [tidyverse/ggplot2#4102]
@thomasp85 @hadley (or anyone who has control over AppVayor)
Sorry to bother you, could you disable AppVeyor integration? This repo switched to use only GitHub Actions CI by https://github.com/tidyverse/ggplot2/pull/4053. I deleted `appveyor.yml` and `.travis.yml`, but its CI check keeps running and failing. I guess we need to change some setting either on GitHub's side or on AppVeyor's side to actually stop the integration, but it seems I don't have such a permission...

This is not a big problem and not the one in a hurry, but it's nice if you take a look when you have time.

![image](https://user-images.githubusercontent.com/1978793/86119476-7cbdbd80-bb0d-11ea-922d-993d098b9284.png)

**Comment by hadley** [comment]
Done!

**Comment by yutannihilation** [comment]
Thanks so much!!!

**Comment by yutannihilation** [comment]
@hadley 
Sorry, it seems AppVeyor is still working hard for us... I found the failing AppVayor is on hadley/ggplot2, maybe you stopped tidyverse/ggplot2...?

![image](https://user-images.githubusercontent.com/1978793/86199314-c00f3f00-bb94-11ea-8cf9-007b7b4f0a5f.png)

**Comment by hadley** [comment]
It is so hard to get rid of appyveyor 😭 I killed another runner, but please ping me again if that wasn't enough.

**Comment by yutannihilation** [comment]
Thanks! Looking at a pull request I just created (#4109), there's no AppVayor running! :tada:
