### ISSUE TITLE
Allowing guide_colorbar to draw guides with custom aesthetics.

### ISSUE THREAD

**Issue by jtlandis** [tidyverse/ggplot2#4105]
This is more of a feature request than an issue and is related to [#2345](https://github.com/tidyverse/ggplot2/issues/2345). Currently `guide_colorbar()` defines `available_aes = c("colour", "color", "fill")`. This restricts the drawing of a guide to these aesthetics when using a continuous color scale. @clauswilke first noting this issue in reference to `ggridges`. For example with the definition `scale_point_fill_gradient`, no color bar guide is drawn because `scale_point_color_gradient` defaults to `guide = "none"`.

```r
library(ggplot2)
library(ggridges)
ggplot(iris, aes(x = Sepal.Length, y = Species)) +
  geom_density_ridges(
    aes(point_color = Sepal.Width, point_shape = Species),
    alpha = .2, point_alpha = 1, jittered_points = TRUE
  ) +
  scale_point_color_gradient(low = "#FF0000", high = "#0000FF")
```
![NoGuideggriges](https://user-images.githubusercontent.com/30324172/86160371-a8bf4b80-bad9-11ea-90cf-ce1fbbeadc1e.png)

If we set `guide = "colorbar"` we get an error.

```r
ggplot(iris, aes(x = Sepal.Length, y = Species)) +
  geom_density_ridges(
    aes(point_color = Sepal.Width, point_shape = Species),
    alpha = .2, point_alpha = 1, jittered_points = TRUE
  ) +
  scale_point_color_gradient(low = "#FF0000", high = "#0000FF", guide = "colorbar")

#Error: Guide 'colorbar' cannot be used for 'point_colour'
```
However if the following lines of code were changed in `ggplot2`

![Screen Shot 2020-06-30 at 1 57 01 PM](https://user-images.githubusercontent.com/30324172/86160444-c1c7fc80-bad9-11ea-8e95-5069c88d7e6f.png)

Then `guide = "colorbar"` works as you would expect

```r
ggplot(iris, aes(x = Sepal.Length, y = Species)) +
  geom_density_ridges(
    aes(point_color = Sepal.Width, point_shape = Species),
    alpha = .2, point_alpha = 1, jittered_points = TRUE
  ) +
  scale_point_color_gradient(low = "#FF0000", high = "#0000FF", guide = "colorbar")
```

![Guideggriges](https://user-images.githubusercontent.com/30324172/86161636-88908c00-badb-11ea-8eb1-3ee414bfdd4e.png)

The two lines of code that were modified was in `guide-colorbar.r` and `guides-.r`, each within `guide_train.colorbar` and `guide_train` functions respectively. The condition would depend on a partial match of the predefined `required_aes = c("color", "colour", "fill")`, so as long as the developer's custom aesthetics contains either `color`, `colour` or `fill`, then the guide is drawn.

**Comment by teunbrand** [comment]
The following works:

``` r
library(ggplot2)
#> Warning: package 'ggplot2' was built under R version 4.0.2
library(ggridges)
#> Warning: package 'ggridges' was built under R version 4.0.2
ggplot(iris, aes(x = Sepal.Length, y = Species)) +
  geom_density_ridges(
    aes(point_color = Sepal.Width, point_shape = Species),
    alpha = .2, point_alpha = 1, jittered_points = TRUE
  ) +
  scale_point_color_gradient(low = "#FF0000", high = "#0000FF",
                             guide = guide_colorbar(available_aes = "point_colour"))
#> Picking joint bandwidth of 0.181
```

![](https://i.imgur.com/xcLIZLJ.png)

<sup>Created on 2020-06-30 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

However related to this, I think it would be very nice to have an automatic way that guides get their available aes from their parent scales. I think inheriting this might be doable (maybe at the guide_train level), but then the problem would be prohibiting using guide_axis in a colour scale for example.

**Comment by clauswilke** [comment]
You just need to set `available_aes` appropriately.

``` r
library(ggplot2)
library(ggridges)

ggplot(iris, aes(x = Sepal.Length, y = Species)) +
  geom_density_ridges(
    aes(point_color = Sepal.Width, point_shape = Species),
    alpha = .2, point_alpha = 1, jittered_points = TRUE
  ) +
  scale_point_color_gradient(
    low = "#FF0000", high = "#0000FF",
    guide = guide_colourbar(available_aes = "point_colour")
  )
#> Picking joint bandwidth of 0.181
```

![](https://i.imgur.com/wWWI6v0.png)

<sup>Created on 2020-06-30 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by clauswilke** [comment]
@teunbrand Note that the `available_aes` argument is just a check so you don't try to draw a color bar for some aesthetic that can't be represented by a color gradient (e.g., a shape). We could remove that check but then might get other random errors if its used inappropriately. Creating some sort of classification system for aesthetics to check whether a given aesthetic is mapped to a scale that works with a given guide seems overkill.

**Comment by teunbrand** [comment]
@clauswilke That makes total sense to me and it definitely falls in the category nice to have but not necessary. Thanks for giving it a thought anyway!

**Comment by jtlandis** [comment]
@clauswilke @teunbrand, It never occurred to me that you could pass the `guide_colorbar` function to the `guide` argument. Thanks for the timely reply.
