### ISSUE TITLE
ggplot2 does not use globally set palette when using indices for colors  

### ISSUE THREAD

**Issue by tjebo** [tidyverse/ggplot2#4106]
May be completely intentional, but I was wondering about the following behaviour: 

ggplot2 doesn't change the default palette when setting it with `palette()`. 

It's also not really a big issue, and I personally would probably rather not use indices for colors, [but some people seem to](https://stackoverflow.com/questions/62665407/single-integer-color-input-what-color-space-how-to-enter-greyscale/62665969#62665969).
``` r
library(ggplot2)

palette()
#> [1] "black"   "#DF536B" "#61D04F" "#2297E6" "#28E2E5" "#CD0BBC" "#F5C710"
#> [8] "gray62"
plot(1:8, col = 1:8, pch = 16)
```

![](https://i.imgur.com/zCCOogB.png)

``` r
#change the palette to "Reds"
palette(RColorBrewer::brewer.pal(8, "Reds"))
plot(1:8, col = 1:8, pch = 16)
```

![](https://i.imgur.com/iQRHZ5t.png)

``` r
# ggplot2 does not change, still the original palette ... 
# (I guess it does not scope for the palette in the global environment?)
ggplot(data.frame(x = 1:8, y = 1), aes(x,y, color = x)) +
  geom_point() +
  scale_color_identity()
```

![](https://i.imgur.com/LQC0Iax.png)

**Comment by thomasp85** [comment]
This is not intended but a known result of using farver for colour conversion. Relying on integers to index into the currently set palette is really antithetical to ggplot2 so it is unlikely that we would ever do anything about it

**Comment by tjebo** [comment]
@thomasp85 cheers for answering, that's very interesting :)
