### ISSUE TITLE
No axes showing

### ISSUE THREAD

**Issue by luciclar** [tidyverse/ggplot2#4107]
With the new version of ggplot2, anytime I plot something I have no axes showing. I have no idea why this is happening. Do you have any idea of how to solve this problem?

This is just a basic example 

x <- seq(0,1,length.out=100)
y <- sin(x)
data <- data.frame(x,y)
plot <- ggplot(data=data) + geom_line(aes(x,y)) + theme_bw() 

![Example](https://user-images.githubusercontent.com/28349640/86227158-ee891c00-bb8c-11ea-9b83-8fa2b554bede.png)

**Comment by teunbrand** [comment]
The problem probably disappears if you don't load ggtern.

**Comment by luciclar** [comment]
Thank you so much, you're right!

**Comment by yutannihilation** [comment]
Thanks @teunbrand!
