### ISSUE TITLE
Connecting points jittered by position_jitterdodge

### ISSUE THREAD

**Issue by richardbeare** [tidyverse/ggplot2#4108]
Hello,
I am attempting to combine boxplots and points, and connect points together. There are some old discussions saying that the input data needs to be sorted to ensure that geom_line and geom_point receive the same jittering, but this does not seem to work when there is a nested grouping:

```r
library(tidyverse)
set.seed(77)
a1 <- tibble(ID=factor(letters[1:10]), y=runif(10), TP="A", Grp=rep(c("C","P"), 5))
a2 <- tibble(ID=factor(letters[1:10]), y=runif(10), TP="B", Grp=rep(c("C","P"), 5))
a1 <- bind_rows(a1, a2)
a1 <- mutate(a1, TP=factor(TP), Grp=factor(Grp))
a1 <- arrange(a1, ID, TP)

pj <- position_jitter(width=0.2, seed=9)
ggplot(a1, aes(x=TP, y=y, fill=Grp)) +
  geom_boxplot(alpha=0.2, outlier.colour = NA) +
  geom_point(position=pj, aes(colour=Grp, group=ID)) +
  geom_line(position=pj, aes(group = ID, colour=Grp))
```
![p1](https://user-images.githubusercontent.com/780449/86237911-f58d4a00-bbdf-11ea-87ba-0e2997648c06.png)

This is performing as expected. However the jittering is not separated per group (i.e pink points are not lined up with the pink boxplot). Lets use jitterdodge to achieve that.

```r
pj <- position_jitterdodge(jitter.width=0.4, seed=9)
ggplot(a1, aes(x=TP, y=y, fill=Grp)) +
  geom_boxplot(alpha=0.2, outlier.colour = NA) +
  geom_point(position=pj, aes(colour=Grp, group=Grp))
```
![p2](https://user-images.githubusercontent.com/780449/86238287-954ad800-bbe0-11ea-9e63-f52370f53cfe.png)

Now the colours are lined up, attempt to connect together.

```r
ggplot(a1, aes(x=TP, y=y, fill=Grp)) +
  geom_boxplot(alpha=0.2, outlier.colour = NA) +
  geom_point(position=pj, aes(colour=Grp, group=Grp)) +
  geom_line(position=pj, aes(group = ID, colour=Grp), alpha=0.3)
```
![p3](https://user-images.githubusercontent.com/780449/86238458-df33be00-bbe0-11ea-8f8e-03e4d3a5f134.png)

As far as I can tell, none of the following combinations of sorting the input data fix the problem of lines being connected to the points:

```r
a1 <- arrange(a1, ID, TP, Grp)
a1 <- arrange(a1, ID, Grp, TP)
a1 <- arrange(a1, Grp, ID, TP)
a1 <- arrange(a1, Grp, TP, ID)
a1 <- arrange(a1, TP, ID, Grp)
a1 <- arrange(a1, TP, Grp, ID)

```

**Comment by smouksassi** [comment]
try a geom that combine point and line see below:
``` r
library(tidyverse)
library(lemon)
set.seed(77)
a1 <- bind_rows(tibble(ID=factor(letters[1:10]), y=runif(10), TP="A", Grp=rep(c("C","P"), 5)),
                tibble(ID=factor(letters[1:10]), y=runif(10), TP="B", Grp=rep(c("C","P"), 5))) %>%
  mutate(TP=factor(TP), Grp=factor(Grp)) %>% 
  arrange(ID, TP)

pj <- position_jitterdodge(jitter.width=0.2, seed=9,
                           jitter.height = 0,
                           dodge.width = 0.75)
ggplot(a1, aes(x=TP, y=y, fill=Grp)) +
  geom_boxplot(alpha=0.2, outlier.colour = NA, width =0.75) +
  lemon::geom_pointpath(aes(colour=Grp, group=interaction(ID,Grp)),
                        position = pj)
```

![](https://i.imgur.com/F4zjNs7.png)

<sup>Created on 2020-07-01 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by richardbeare** [comment]
Nice work-around!

**Comment by thomasp85** [comment]
I think the best way forward is to make geom_pointpath work correctly. There is a lot going on when trying to ensure that jittering is reproducible across layers and I'm not sure we can solve it correctly for all cases

**Comment by Syutenjyo** [comment]
```
a1 <- bind_rows(tibble(ID=factor(letters[1:10]), y=runif(10), TP="A", Grp=rep(c("C","P"), 5)), tibble(ID=factor(letters[1:10]), y=runif(10), TP="B", Grp=rep(c("C","P"), 5))) %>% mutate(TP=factor(TP), Grp=factor(Grp))

pjd <- position_jitterdodge(jitter.width=0.4, seed=9)
a2 <- a1 %>% arrange(ID, TP)

pp3 <- ggplot(mapping = aes(x=TP, y=y, fill=Grp)) +
  geom_boxplot(data=a1, alpha=0.2, outlier.colour = NA) +
  geom_point(data=a2, position=pjd, aes(colour=Grp, group=ID)) +
  geom_line(data=a1, position=pjd, aes(colour=Grp, group=ID))

pp3 %>% ggplot_build() %>% .$data
```
![image](https://github.com/user-attachments/assets/411b5684-2e51-443c-a904-11565861fb2d)
