### ISSUE TITLE
No warning in stat_ydensity when dropping groups

### ISSUE THREAD

**Issue by andrewwbutler** [tidyverse/ggplot2#4111]
Hi,

I noticed the following behavior in `geom_violin` when there are fewer than three data points in a given violin. In this scenario, one of the violins gets dropped without a warning. 

``` r

library(ggplot2)
table(mtcars$cyl, mtcars$am)
#>    
#>      0  1
#>   4  3  8
#>   6  4  3
#>   8 12  2
ggplot(mtcars, aes(x = factor(cyl), y = mpg)) + 
  geom_violin(scale = "width", aes(fill = factor(am))) 
```

![](https://i.imgur.com/ocdl3XP.png)

<sup>Created on 2020-07-01 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

It seems a related issue was addressed in `stat_density` in https://github.com/tidyverse/ggplot2/pull/2142 . I would propose that `stat_ydensity` be updated similarly here https://github.com/tidyverse/ggplot2/blob/cb0cfd2aea18ee4ebf671bed52dbd566ebeaf7ea/R/stat-ydensity.r#L74  Happy to put together a small PR for this if people agree.

**Comment by clauswilke** [comment]
That seems reasonable.
