### ISSUE TITLE
stat_density_2d() and geom_density_2d() output differs between ggplot2 v. 3.2.1 and v. 3.3.2

### ISSUE THREAD

**Issue by AEgit** [tidyverse/ggplot2#4114]
Some changes introduced between ggplot2 version 3.2.1 and version 3.3.2 (I did not check version 3.3.0, but I reckon it has the same problem) have lead to weird outputs when using stat_density_2d() and geom_density_2d().

I have asked this question before (https://github.com/tidyverse/ggplot2/issues/4110), but I have been asked to provide a standard reprex using the reprex package. Here I report a standard reprex, that allows reproducing this issue.

My questions are:
1) Are the differences in output between ggplot2 v. 3.2.1 and v. 3.3.2 when using `stat_density_2d(aes(fill = stat(nlevel)), geom = "polygon")` or `geom_density_2d(aes(colour = cut))` intended? Or is this a bug?
2) If they are intended: Is there a way to generate a figure using v. 3.3.2 that is similar to what v. 3.2.1 produced when using `stat_density_2d(aes(fill = stat(nlevel)), geom = "polygon")`? For more details see the reprex below.

**Output generated using ggplot2 version 3.2.1:**

``` r
# #Reprex example of geom_density_2d() and stat_density_2d() issue
# #Note, that the example code is nearly identical to the one found
# #in the help file of ggplot2 v. 3.2.1
library(ggplot2)


set.seed(4393)
dsmall <- diamonds[sample(nrow(diamonds), 1000), ]
d <- ggplot(dsmall, aes(x, y))
# #If you map an aesthetic to a categorical variable, you will get a
# #set of contours for each value of that variable
d + geom_density_2d(aes(colour = cut)) 
```

![](https://i.imgur.com/UQCwcKd.png)

``` r

# #We can do the same but use a facet plot
d + geom_density_2d(aes(colour = cut)) + facet_grid(. ~ cut)
```

![](https://i.imgur.com/RpN8S7l.png)

``` r


# #stat_density_2d() example of a facet plot taken from the help file of ggplot2 v. 3.2.1
# #To better visualize the density within each facet) we use stat(nlevel)
d + stat_density_2d(aes(fill = stat(nlevel)), geom = "polygon") +  
  facet_wrap(vars(cut), nrow = 1) + 
  scale_fill_viridis_c()
```

![](https://i.imgur.com/yOJyJBM.png)

``` r
# #Note, how the output differs between ggplot2 v. 3.2.1 and ggplot2 v. 3.3.2.
# #Is this difference intended or a bug?
```

<sup>Created on 2020-07-02 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Output generated using ggplot2 version 3.3.2:**
``` r
# #Reprex example of geom_density_2d() and stat_density_2d() issue
# #Note, that the example code is nearly identical to the one found
# #in the help file of ggplot2 v. 3.2.1
library(ggplot2)


set.seed(4393)
dsmall <- diamonds[sample(nrow(diamonds), 1000), ]
d <- ggplot(dsmall, aes(x, y))
# #If you map an aesthetic to a categorical variable, you will get a
# #set of contours for each value of that variable
d + geom_density_2d(aes(colour = cut)) 
```

![](https://i.imgur.com/oOBfTwF.png)

``` r

# #We can do the same but use a facet plot
d + geom_density_2d(aes(colour = cut)) + facet_grid(. ~ cut)
```

![](https://i.imgur.com/Cjx2rGE.png)

``` r


# #stat_density_2d() example of a facet plot taken from the help file of ggplot2 v. 3.2.1
# #To better visualize the density within each facet) we use stat(nlevel)
d + stat_density_2d(aes(fill = stat(nlevel)), geom = "polygon") +  
  facet_wrap(vars(cut), nrow = 1) + 
  scale_fill_viridis_c()
```

![](https://i.imgur.com/kfnlL4f.png)

``` r
# #Note, how the output differs between ggplot2 v. 3.2.1 and ggplot2 v. 3.3.2.
# #Is this difference intended or a bug?

# #THE FOLLOWING CODE DOES NOT WORK WITH ggplot2 v. 3.2.1 OR OLDER!
# #Note, that the help examples in the current ggplot2 v. 3.3.2 have changed and now use
# #geom_density_2d_filled() instead, which gives a somewhat similar plot - the most 
# #obvious difference is that lowest level density is now also coloured, providing a dark blue
# #"floor" colour to the individual facets.
# #Furthermore, the colour scale is no longer continuous but discrete
d + geom_density_2d_filled(contour_var = "ndensity") + facet_wrap(vars(cut), nrow = 1)
```

![](https://i.imgur.com/xX4t8X5.png)

``` r
# # #We get the same output if we use stat_density_2d_filled()
# d + stat_density_2d_filled(contour_var = "ndensity") + facet_wrap(vars(cut), nrow = 1)

# #To recreate a figure, that resembles the figures produced using 
# #stat_density_2d(aes(fill = stat(nlevel)), geom = "polygon")
# #with the old ggplot2 version 3.2.1, it now appears to be necessary to use 
# #geom_density_2d_filled(contour_var = "ndensity")
# #when using ggplot2 version 3.3.2. Then the respective plot is exported as a vector file and
# #level (0.0-0.1] can be manually removed (by, e.g., using Inkscape) from the scale and the
# #facet plots, i. e. the dark blue "floor" colour is removed.

# #QUESTIONS:
# #1) Are the differences in output between ggplot2 v. 3.2.1 and v. 3.3.2 when using
# #stat_density_2d(aes(fill = stat(nlevel)), geom = "polygon") intended? Or is this a bug?
# #2) If this is intended behaviour: Is there a way to recreate the figure similar to what
# #v. 3.2.1 produced, without having to manually modify the figure during postprocessing?
# #Just changing the levels will not do the job. Basically I am just trying to get a figure,
# #that does not have the weird dark blue "floor" colour, but at the same still looks similar
# #in terms of peaks/colour breaks to what version 3.2.1 delivered.
```

<sup>Created on 2020-07-02 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by clauswilke** [comment]
The differences between 3.2.1 and 3.3.2 are intentional. `stat_density_2d()` had numerous bugs and the only way to fix them was to change its behavior in some cases. In particular, `stat_density_2d(aes(fill = stat(nlevel)), geom = "polygon")` was completely broken and should never have been used. (You can see the fraying of the contour bands at the bottom left in your example. That's a bug.)

If you don't like the strong dark color for the lowest level, the best solution is probably to use a different color scale. Alternatively, you can map the level onto `alpha` as well to gently blend out the lower levels.

``` r
library(ggplot2)

set.seed(4393)
dsmall <- diamonds[sample(nrow(diamonds), 1000), ]
d <- ggplot(dsmall, aes(x, y, alpha = after_stat(level))) +
  geom_density_2d_filled(contour_var = "ndensity") + 
  facet_wrap(vars(cut), nrow = 1)

d
```

![](https://i.imgur.com/zk6Swzd.png)

If you want to just remove the lowest level, you can use an alpha scale that just sets that one value to transparent.

``` r

# only remove the lowest level
d + scale_discrete_manual("alpha", values = c(0, rep(1, 9)))
```

![](https://i.imgur.com/g0kf49f.png)

<sup>Created on 2020-07-02 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by AEgit** [comment]
Thank you very much for the information and the trick with the alpha scale. I will probably set one value to transparent. If there is more demand for such a functionality, maybe at some point this could become an option in the `geom_density_2d_filled()` function (?). But I myself am happy with this solution.
