### ISSUE TITLE
Option to turn strip clipping off

### ISSUE THREAD

**Issue by teunbrand** [tidyverse/ggplot2#4118]
Hi everyone,

I recently found the need to turn the clipping off, but I can't easily do that without either (1) writing a new facet function that builds strips as I want or (2) edit the strips in the gtable.

I found a similar question [here on so](https://stackoverflow.com/questions/49740215/ggplot-facet-grid-label-cut-off/49744051#49744051).
A while back, there was a move to make clipping more configurable (#2536), but this has not been extended to strips. Also there was an issue with strip clipping (#2772), which turned it on for all strips; however my intention would be to make this configurable from e.g. the theme.

One reason besides turning off label clipping is to make the strips flush with either axis lines, panel backgrounds and panel borders (the latter two when the coord clipping is turned off).

An example of the behaviour I love to see configurable is below. The intersection between the strip and the axis line is not ideal, and the `size` parameter appears halved for the strip.

``` r
library(ggplot2)

ggplot(mpg, aes(displ, hwy)) +
  geom_point() +
  facet_wrap(~ drv) +
  theme(
    strip.background = element_rect(colour = "red", size = 5),
    axis.line.y.left = element_line(colour = "blue", size = 5)
  )
```

![](https://i.imgur.com/96k25Fk.png)

<sup>Created on 2020-07-04 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Thanks for considering!

**Comment by teunbrand** [comment]
Is this idea fundamentally flawed or would it be OK if I were to draft a PR on this subject and discuss from there?

**Comment by clauswilke** [comment]
I don't think it's fundamentally flawed. Could you put together a PR so we can see what would be required?

**Comment by teunbrand** [comment]
Sure thing!

**Comment by stemangiola** [comment]
Thanks for this feature request. Is there an ETA for this feature to be merged?
