### ISSUE TITLE
Legend is too wide when cyrillic is used

### ISSUE THREAD

**Issue by erydit** [tidyverse/ggplot2#4123]
If I add any cyrillic character into a legend, an ugly extra space appears.
The bug appears if you work in Rstudio. So, maybe its Rstudio`s bug.
The plots looks normal if save them using ggsave().
But this behaviour is still preserved when I try to use other packages like ggpubr, attempting to plot only a legend etc.

```r
library(ggplot2)
data(mtcars)

plt <- ggplot(mtcars) +
  geom_point(aes(x = mpg, y = qsec, col = cyl, size=hp)) + 
  theme(legend.background = element_rect(color = "red", fill = NA),
        legend.box.background = element_rect(color = "darkgreen", fill = NA),
        plot.background = element_rect(color = "black", fill = NA))
  
plt + labs(col = "English1", size = "En2")

plt + labs(col = "Русский1", size = "Ру2")
```
![Rplot1](https://user-images.githubusercontent.com/25078871/86927234-23c0db80-c144-11ea-864e-c8b0575cb732.png)
![Rplot2](https://user-images.githubusercontent.com/25078871/86927239-24f20880-c144-11ea-8319-b3271401bcb8.png)

R version 4.0.0 (2020-04-24)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

Matrix products: default

locale:
[1] LC_COLLATE=Russian_Russia.1251  LC_CTYPE=Russian_Russia.1251    LC_MONETARY=Russian_Russia.1251 LC_NUMERIC=C                   
[5] LC_TIME=Russian_Russia.1251    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] ggplot2_3.3.1 magrittr_1.5 

IDE: Rstudio 1.3.959

**Comment by clauswilke** [comment]
It's actually a bug in the default windows graphics device. It reports incorrect font metrics when strings contain multi-byte unicode characters. Nothing we can do about on our end. You can report a bug with RStudio, though I think they're already working on phasing out the default windows graphics device. Maybe @thomasp85 knows details.

**Comment by erydit** [comment]
OK, thank you.
I dived deeper in that problem, and found out that the possible crutch-solution is to use Cairo graphic device instead of default windows device: https://github.com/rstudio/rstudio/issues/2142
