### ISSUE TITLE
Bug in setting fill of horizontal boxplots

### ISSUE THREAD

**Issue by markpayneatwork** [tidyverse/ggplot2#4124]
I suspect I have found a bug in `geom_boxplot()` when trying to set the color of the box to be a computed variable. ie.

```r
> library(ggplot2)

> #Horizontal boxes with fill doesn't work with computed variables 
> ggplot(iris)+  geom_boxplot(aes(y=Species,x=Petal.Width,fill=..middle..)) 
Error in FUN(X[[i]], ...) : object 'middle' not found 
> ggplot(iris)+   geom_boxplot(aes(y=Species,x=Petal.Width,fill=..lower..))
 Error in FUN(X[[i]], ...) : object 'lower' not found
>
```
Other related variants on this theme seem to work ok

````r
library(ggplot2)
#Vertical boxes with fill works with computed variables
ggplot(iris)+
  geom_boxplot(aes(x=Species,y=Petal.Width,fill=..middle..))

#Horizontal boxes without fill works
ggplot(iris)+
  geom_boxplot(aes(y=Species,x=Petal.Width))

#Horizontal boxes with categorical variables works
ggplot(iris)+
  geom_boxplot(aes(y=Species,x=Petal.Width,fill=Species))
````
Running ggplot Version: 3.3.2.9000 on Windows, built from the master branch on Github 2020-07-09 16:14:23 UTC

**Comment by yutannihilation** [comment]
Thanks. This seems a documentation problem. You need `x` prefix for some of the computed variables if you draw `geom_boxplot()` horizontally (note that the latest recommended way to refer to computed variables is `after_stat(var)` instead of `..var..`):

``` r
library(ggplot2)

ggplot(iris) +
  geom_boxplot(aes(y = Species, x = Petal.Width, group = Species, fill = after_stat(xmiddle)))
```

![](https://i.imgur.com/chG1pOy.png)

<sup>Created on 2020-07-10 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by clauswilke** [comment]
This is the first I hear of this feature, so yes, definitely a documentation problem. :-)

Is this documented anywhere currently? Do we also have `ymiddle` for regular orientation?

**Comment by yutannihilation** [comment]
We have `middle` (and `lower` and `upper`) for x aesthetics, which feels a bit tricky.

``` r
knitr::kable(
  data.frame(
    x = ggplot2:::ggplot_global$x_aes,
    y = ggplot2:::ggplot_global$y_aes
  )
)
```

<table>
<thead>
<tr class="header">
<th style="text-align: left;">x</th>
<th style="text-align: left;">y</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">x</td>
<td style="text-align: left;">y</td>
</tr>
<tr class="even">
<td style="text-align: left;">xmin</td>
<td style="text-align: left;">ymin</td>
</tr>
<tr class="odd">
<td style="text-align: left;">xmax</td>
<td style="text-align: left;">ymax</td>
</tr>
<tr class="even">
<td style="text-align: left;">xend</td>
<td style="text-align: left;">yend</td>
</tr>
<tr class="odd">
<td style="text-align: left;">xintercept</td>
<td style="text-align: left;">yintercept</td>
</tr>
<tr class="even">
<td style="text-align: left;">xmin_final</td>
<td style="text-align: left;">ymin_final</td>
</tr>
<tr class="odd">
<td style="text-align: left;">xmax_final</td>
<td style="text-align: left;">ymax_final</td>
</tr>
<tr class="even">
<td style="text-align: left;">xlower</td>
<td style="text-align: left;">lower</td>
</tr>
<tr class="odd">
<td style="text-align: left;">xmiddle</td>
<td style="text-align: left;">middle</td>
</tr>
<tr class="even">
<td style="text-align: left;">xupper</td>
<td style="text-align: left;">upper</td>
</tr>
<tr class="odd">
<td style="text-align: left;">x0</td>
<td style="text-align: left;">y0</td>
</tr>
</tbody>
</table>

<sup>Created on 2020-07-11 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by yutannihilation** [comment]
I created a quick pull request for this (#4128). Honestly, I feel there would be some smarter way to fix this, but I think this is better than nothing for now...
