### ISSUE TITLE
improve geom_bar() and geom_col()'s linetype aesthetic's default behaviour

### ISSUE THREAD

**Issue by stragu** [tidyverse/ggplot2#4126]
Using the `fill` aesthetic with a categorical variable works as expected in `geom_col()` and `geom_bar()`, but `linetype` with the same variable gives a results that looks like it is fails.

The reason why it looks like it is failing is that the bar chart border is by default invisible (is that accurate?). To make the change visible, one has to change the `colour` value for the bar/col geometry.

The second issue is that the area surrounded by the line is not what might be expected by most users when using `stat = "identity"` (`geom_col()`'s default). The `fill` aesthetic will make each colour look like one single block, but using the `linetype` aesthetic will draw each case's border separately.

Seeing this result, one might try to find a different `stat_*()` function to use, and logically might try `stat_sum()`, to end up with a sum of all values that have the same categorical level (i.e. ending up with one single case, and one single area to draw a border for). However, `stat_sum()` is used for something completely different: mainly to draw an alternative to a scatterplot when there is exact overlap. Using it for a bar chart results in an interestingly glitchy plot.

I have to admit I haven't thought much of the potential drawbacks and side-effects of (1) improving the default `colour` of the bar/col geometries when the `linetype` aesthetic is used, and (2) the modification of the default behaviour of the border drawing when `linetype` is used with `stat_identity()`, but is there maybe some room for improvement?

``` r
library(ggplot2)
## (1) linetype aes looks like it does not work
# using linetype looks like it fails
ggplot(data = as.data.frame(Titanic),
       aes(x = Class, linetype = Survived)) +
  geom_bar()
```

![](https://i.imgur.com/aZXAk2g.png)

``` r
# one has to change the colour to see the effect
ggplot(data = as.data.frame(Titanic),
       aes(x = Class, linetype = Survived)) +
  geom_bar(colour = "black")
```

![](https://i.imgur.com/AkO7jmx.png)

``` r

## (2) linetype aes with identity stat won't group cases
# count stat (default for bar chart): the whole area is bordered
ggplot(data = as.data.frame(Titanic),
       aes(x = Class, linetype = Survived)) +
  geom_bar(stat = "count", colour = "black")
```

![](https://i.imgur.com/fZk02Vd.png)

``` r
# identity stat (geom_col()'s default): each case has a separate border 
ggplot(data = as.data.frame(Titanic),
       aes(x = Class, y = Freq, linetype = Survived)) +
  geom_bar(stat = "identity", colour = "black")
```

![](https://i.imgur.com/N9CNUat.png)

``` r
# ...whereas identity stat + fill aesthetic works out fine visually
ggplot(data = as.data.frame(Titanic),
       aes(x = Class, y = Freq, fill = Survived)) +
  geom_bar(stat = "identity")
```

![](https://i.imgur.com/pv1Jjj6.png)

``` r
# sum stat, maybe? No, it is used for something else.
ggplot(data = as.data.frame(Titanic),
       aes(x = Class, y = Freq, linetype = Survived)) +
  geom_bar(stat = "sum", colour = "black")
```

![](https://i.imgur.com/1g1sGh6.png)

<sup>Created on 2020-07-10 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Using R 4.0.2 and ggplot2 3.3.2

**Comment by yutannihilation** [comment]
Hmm, it's a kind of unfortunate that `size`, which is the aesthetic that the computed variable is mapped to by default, can have multiple meanings depending on the context; the thickness of lines, the area (or radius) of points, etc. While I agree this is confusing, I don't feel it's less confusing that the behaviour would differ by whether or not `linetype` is mapped or not.

**Comment by stragu** [comment]
Sorry, closing this because I misunderstood a big chunk of the issue: with `stat_identity()` and several `y` values for one single `fill` or `linetype` level, the areas are layered (i.e. superimposed). 

I might open a different issue.
