### ISSUE TITLE
multiple arrows in geom_path if color specified, but only one arrow otherwise

### ISSUE THREAD

**Issue by bob-carpenter** [tidyverse/ggplot2#4133]
### Summary

When using `geom_path` I find that

* if I use only `geom_path(arrow = arrow())`, the result is a single arrow at the end of the path, but
* if I add a colour aesthetic, `geom_path(aes(colour = t, arrow = arrow()))`, the result is an arrow on each segment.

### Minimal reproducible example

To reproduce, I set up some points on a circle and used a `geom_path` with and without a `colour` aesthetic.  

```
library('ggplot2')

t <- seq(0, 2 * pi, by = pi / 12)
x <- cos(t)
y <- sin(t)
df <- data.frame(t = t, x = x, y = y)

plot1 <-
  ggplot(df, aes(x = x, y = y)) +
  geom_point() +
  geom_path(arrow = arrow())
plot1 

plot2 <-
  ggplot(df, aes(x = x, y = y)) +
  geom_point() +
  geom_path(aes(colour = t), arrow = arrow())
plot2 
```

Here's `plot1`.

![plot1](https://user-images.githubusercontent.com/3383807/87227337-52b79700-c368-11ea-9e7e-99fee2f93df9.jpg)

Here's `plot2`:

![plot2](https://user-images.githubusercontent.com/3383807/87227348-5f3bef80-c368-11ea-9747-059659535781.jpg)

### Related issue

This is related to #2280 (geom_path should support intermediate arrows), which was marked won't fix because of difficulty.

**Comment by JTC-R** [comment]
I think the difference is that in the first section, you're applying `arrow=arrow()` as an attribute without an aesthetic so it just puts one arrow on. Whereas in the second gplot, you're applying a color as an aesthetic which is putting color over each segment which is then read as different segments, so then the arrow still is applied as an attribute but as an attribute over each segment, thus giving multiple arrows.

**Comment by yutannihilation** [comment]
Thanks. I think this can be fixed somehow. For now, you can tweak the arrow like this (I don't recommend this as nothing ensures the `arrow` is the same length as data, though...):

``` r
library('ggplot2')

t <- seq(0, 2 * pi, by = pi / 12)
x <- cos(t)
y <- sin(t)
df <- data.frame(t = t, x = x, y = y)

ggplot(df, aes(x = x, y = y)) +
  geom_point() +
  geom_path(
    aes(colour = t),
    arrow = arrow(length = unit(c(rep(0, nrow(df) - 2), 0.25), "inches"))
  )
```

![](https://i.imgur.com/J9KW28I.png)

<sup>Created on 2020-07-12 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by JTC-R** [comment]
I think a more simple review would be calling `geom_path()` twice. Try this

`plot3<- 
  ggplot(df, aes(x=x, y=y)) +  
  geom_point() +   
  geom_path(aes(color=t)) +  
  geom_path(arrow=arrow())  
<img width="770" alt="Screen Shot 2020-07-11 at 11 40 32 PM" src="https://user-images.githubusercontent.com/68164990/87238384-ea040500-c3cf-11ea-8fda-2d4a91bdb462.png">

`

**Comment by JTC-R** [comment]
Try: 

`plot3<- 
  ggplot(df, aes(x=x, y=y)) + 
  geom_point() + 
  geom_path(arrow=arrow())+
  geom_path(aes(color=t))

<img width="776" alt="Screen Shot 2020-07-11 at 11 43 23 PM" src="https://user-images.githubusercontent.com/68164990/87238418-50892300-c3d0-11ea-9a59-2cdc6a40009d.png">
`

Applying two `geom_paths()` helps differentiate the aesthetic from the attribute. But the two paths will over-ride eachother to only show which one is computer last; so the `aes(color=t)` should come last.

**Comment by yutannihilation** [comment]
Here's an implementation. Still not sure if this should be supported or not, though...

https://github.com/tidyverse/ggplot2/commit/5035e31658b5beba6a93d9e8c8e25dd0615b4cde

``` r
t <- seq(0, 2 * pi, by = pi / 12)
x <- cos(t)
y <- sin(t)
df <- data.frame(
  t = t,
  x = x,
  y = y,
  g = rep(c("a", "b", "c", "d"), times = c(2, 4, 6, 13))
)

devtools::load_all("~/repo/ggplot2")
#> Loading ggplot2

do_plot <- function(ends) {
  ggplot(df, aes(x = x, y = y, group = g)) +
    geom_point() +
    geom_path(
      aes(colour = t),
      arrow = arrow(ends = ends)
    )
}

do_plot("last")
```

![](https://i.imgur.com/Br9d5V0.png)

``` r
do_plot("first")
```

![](https://i.imgur.com/nNKh58r.png)

``` r
do_plot("both")
```

![](https://i.imgur.com/qrEnJxH.png)

<sup>Created on 2020-07-12 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by bob-carpenter** [comment]
Thanks, @JTC-R and @yutannihilation for the explanation and alternatives.  

Someone else will need to close as I don't have permission.
