### ISSUE TITLE
ggsave with png and type = "windows" produces incorrect size

### ISSUE THREAD

**Issue by jarauh** [tidyverse/ggplot2#4136]
Consider the following code:
```r
library(ggplot2)
ggsave("test10.png",
       qplot(mtcars$hp, mtcars$cyl),
       device = png,
       type = "windows", width = 10, height = 10, units = "in")
ggsave("test50.png",
       qplot(mtcars$hp, mtcars$cyl),
       device = png,
       type = "windows", width = 50, height = 50, units = "in")
```

The first `ggsave` produces a plot that is 10px (instead of 10in) in width and height.
The second `ggsave` stops with an error message:

> Fehler:   Dimensions exceed 50 inches (height and width are specified in 'in' not pixels).
  If you're sure you want a plot that big, use `limitsize = FALSE`.
> Run `rlang::last_error()` to see where the error occurred.

I'm running R-4.0.2 with ggplot2-3.3.2.

**Comment by karawoo** [comment]
I can't reproduce your example as `"windows"` is not an allowable argument to the png device function:

``` r
library(ggplot2)
ggsave("test10.png",
       qplot(mtcars$hp, mtcars$cyl),
       device = png,
       type = "windows", width = 10, height = 10, units = "in")
#> Error in match.arg(type): 'arg' should be one of "cairo", "cairo-png", "Xlib", "quartz"
```

<sup>Created on 2020-07-14 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

However your call to `ggsave()` should use either `device = "png"` or `device = png()`, not `device = png`. If I use one of those and remove `type = "windows"` I get a 10"x10" plot.

The error for the 50x50 plot is expected and the message contains the instructions for how to address it.

**Comment by jarauh** [comment]
Thanks for your reply, @karawoo. I guess the option `type = "windows"` is only available on Windows.  The help page on `grDevices::png` gives me the following signature of the function:
```r
png(filename = "Rplot%03d.png",
    width = 480, height = 480, units = "px", pointsize = 12,
    bg = "white", res = NA, family = "", restoreConsole = TRUE,
    type = c("windows", "cairo", "cairo-png"), antialias,
    symbolfamily="default")
```

**Comment by karawoo** [comment]
You're right, the options for `type` are defined differently on [unix](https://github.com/wch/r-source/blob/1156fd5e5430ce375f847bf4f40ce627ddfba2e8/src/library/grDevices/R/unix/png.R#L40) and [windows](https://github.com/wch/r-source/blob/1156fd5e5430ce375f847bf4f40ce627ddfba2e8/src/library/grDevices/R/windows/png.R#L41). Regardless, if you provide the `device` correctly then the `type` argument should get passed along.

**Comment by jarauh** [comment]
Dear @karawoo , why is `device = png` not correct?  The documentation tells me: "Can either be a function ..." But `png()` is not a function - it is a call (or, if evaluated, it will be `NULL`).
