### ISSUE TITLE
**GGPLOT NOT PLOTTING**

### ISSUE THREAD

**Issue by pedogski** [tidyverse/ggplot2#4139]
I am having issues running **ggplot2** and its associated packages. It is installed on my system but refuses to load when I call it:
`library(ggplot2)
library(GGally)
`

it gives me error messages. Also when I manually load it from the package pane it will not plot.
Brief description of the problem

below is an example of code that produced the output below:

`attach(mtcars)
ggally_na(data = mtcars, mapping = NULL, size = 10, color = "grey20", ...)
ggally_naDiag(...)
`

```r 
![Rplot01mtcars](https://user-images.githubusercontent.com/19455677/87844709-c51ffe00-c8b7-11ea-917b-725302223d6e.png)
```

```r
![Rplot01ggplot](https://user-images.githubusercontent.com/19455677/87844642-e8967900-c8b6-11ea-8fa3-35533610db5c.png)

```
This challenge has been on for a while now. I had to do package update to be sure the packages on my Rstudio are not outdated. But still, the challenge persists. Below are my version details:

` R.Version()
$platform
[1] "x86_64-w64-mingw32"

$arch
[1] "x86_64"

$os
[1] "mingw32"

$system
[1] "x86_64, mingw32"

$status
[1] ""

$major
[1] "3"

$minor
[1] "6.1"

$year
[1] "2019"

$month
[1] "07"

$day
[1] "05"

$`svn rev`
[1] "76782"

$language
[1] "R"

$version.string
[1] "R version 3.6.1 (2019-07-05)"

$nickname
[1] "Action of the Toes"
`

Please what can I do to salvage this situation?****

**Comment by yutannihilation** [comment]
This sort of question is a better fit for [RStudio Community](https://community.rstudio.com). Please ask there. We use this issue tracker for bug reports and feature requests.

I think it might be helpful to describe the detail of how it "refuses to load" (e.g. error messages) when you post there.

**Comment by pedogski** [comment]
> This sort of question is a better fit for [RStudio Community](https://community.rstudio.com). Please ask there. We use this issue tracker for bug reports and feature requests.
> 
> I think it might be helpful to describe the detail of how it "refuses to load" (e.g. error messages) when you post there.

Thank you.
