### ISSUE TITLE
Use of length 1 numeric vector for expand gives confusing error message

### ISSUE THREAD

**Issue by Alanocallaghan** [tidyverse/ggplot2#4140]
The error message when you supply a single numeric value to expand says that a single numeric value is okay, which seems a bit kafkaesque*

```r
library("ggplot2")
ggplot(mtcars) +
  aes(mpg, cyl) +
  geom_point() +
  scale_y_continuous(expand=0)
# Error: `expand` must be a numeric vector with 1 or 2 elements
is.vector(0)
# [1] TRUE
is.numeric(0)
# [1] TRUE
length(0)
# [1] 1
```

*I confess, I've not read kafka so that's probably wrong, but it reminds me of [that Asterix & Obelix cartoon with the forms](https://en.wikipedia.org/wiki/The_Twelve_Tasks_of_Asterix)

**Comment by clauswilke** [comment]
Yes, the code checks for length 2 or 4 and then produces the error message:
https://github.com/tidyverse/ggplot2/blob/885c3c1556f87fc751030759caec2fff1dfcae8c/R/scale-expansion.r#L67-L70

**Comment by Alanocallaghan** [comment]
My understanding based on the docs a few years ago was that expand is multiplicative (ie 0.05 expands by 5%), and if length 1 it expands both sides equally, length 2 each value controls one of left/right or top/bottom. I guess length 2 for each side could mean that each pair is passed to `expansion`, which seems to be the way things are handled based on some quick testing.

Either way this isn't really clear in the argument documentation - there's no indication of how long the vector should be or what each value corresponds to
