### ISSUE TITLE
Bug: Unexpected fill guides with multiple geom_density layers

### ISSUE THREAD

**Issue by jtlandis** [tidyverse/ggplot2#4143]
EDIT: After reviewing some of the older issues it seems that this is related to #3804
This seems to be a very special case, as in I haven't been able to determine if it happens with more geometries or aesthetics, but if you have multiple geom_density calls but only assign the fill aesthetic in the second layer, the guide will make a new legend. 
```r
#Produces an extra legend guide with a title of "fill"
ggplot(mpg, aes(displ, hwy, colour = class)) + 
  geom_point() +
  geom_density(aes(y = after_stat(density)), position = "stack") +
  geom_density(aes(x = after_stat(density), fill = class), orientation = "y", position = "stack") +
  scale_fill_manual(values = RColorBrewer::brewer.pal(7, "Set1"))
```
![Extra_guide](https://user-images.githubusercontent.com/30324172/88143079-9d38df00-cbc4-11ea-953b-f2140e0a9c87.png)

```r
#Fill aesthetic guide will be placed with the "class" legend
#This is what I assume the intended result is supposed to look like
ggplot(mpg, aes(displ, hwy, colour = class)) + 
  geom_point() +
  geom_density(aes(y = after_stat(density), fill = class), position = "stack") +
  geom_density(aes(x = after_stat(density)), orientation = "y", position = "stack") +
  scale_fill_manual(values = RColorBrewer::brewer.pal(7, "Set1"))
```

![Expected_result](https://user-images.githubusercontent.com/30324172/88143093-a45fed00-cbc4-11ea-8ebf-030c92579581.png)

**Comment by yutannihilation** [comment]
Thanks, seems a similar issue as #3804. Let's discuss there.
