### ISSUE TITLE
scale_y_log10  produces reverse image

### ISSUE THREAD

**Issue by minor6th** [tidyverse/ggplot2#4144]
geom_col will output the expected graph without scale_y_log10.
But the output image gets reversed when I add scale_y_log10.

```r
require(tidyverse)
df <- tibble(
  x = 1:10,
  y = seq(0.1, 1, 0.1)
)

ggplot(df, aes(x, y)) +
  geom_col() +
  scale_y_log10()
```

**Comment by clauswilke** [comment]
That's because 1 is the natural reference value for a log scale.
https://serialmentor.com/dataviz/proportional-ink.html#visualizations-along-logarithmic-axes
