### ISSUE TITLE
axis.text.x margins are not applied with scale_x_discrete position set to "top"

### ISSUE THREAD

**Issue by RichPollock** [tidyverse/ggplot2#4146]
The closed issue [here](https://github.com/tidyverse/ggplot2/issues/2425) (#2425) includes a simple reprex and the issue is still present in 3.3.2. Here's another reprex for reference:

```R
data <- data.frame(category = c("1", "2", "3"), value = c(10, 5, 15))

ggplot(data, aes(x = category, y = value)) +
	geom_bar(stat = "identity") +
	scale_x_discrete(position = "top") +
	theme(axis.text.x = element_text(margin = margin(t = 50, b = 50), debug = TRUE))
```

If you run the above and then switch `scale_x_discrete(position = "top")` to `scale_x_discrete(position = "bottom")`, you can immediately see the issue.

I'm also not convinced that #1502 (margins not being applied to the legend) was actually the same issue as was suspected in the discussion on #2425. The legend margin issue appears to have been fixed in #2556, but this axis text margin bug is still very much present as of 3.3.2.

**Comment by teunbrand** [comment]
I don't think this is a bug. The `axis.text.x.top` element inherits from `axis.text.x`, but has a custom margin that will not be inherited. The solution to this would be to use the former element instead.

``` r
library(ggplot2)

data <- data.frame(category = c("1", "2", "3"), value = c(10, 5, 15))

ggplot(data, aes(x = category, y = value)) +
  geom_bar(stat = "identity") +
  scale_x_discrete(position = "top") +
  theme(axis.text.x.top = element_text(margin = margin(t = 50, b = 50)))
```

![](https://i.imgur.com/nHuDsEk.png)

<sup>Created on 2020-07-24 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by smouksassi** [comment]
you will have to use  'axis.text.x.top'
``` r
library(ggplot2)
library(patchwork)
data <- data.frame(category = c("1", "2", "3"), value = c(10, 5, 15))

a<- ggplot(data, aes(x = category, y = value)) +
  geom_bar(stat = "identity") +
  scale_x_discrete(position = "top") +
  theme(axis.text.x = element_text(margin = margin(t = 50, b = 50), debug = TRUE))
b <- ggplot(data, aes(x = category, y = value)) +
  geom_bar(stat = "identity") +
  scale_x_discrete(position = "top") +
  theme(axis.text.x.top = element_text(margin = margin(t = 50, b = 50), debug = TRUE))
c <- ggplot(data, aes(x = category, y = value)) +
  geom_bar(stat = "identity") +
  scale_x_discrete(position = "bottom") +
  theme(axis.text.x = element_text(margin = margin(t = 50, b = 50), debug = TRUE))
a+b+c
```

![](https://i.imgur.com/Q23RIo8.png)

<sup>Created on 2020-07-24 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by RichPollock** [comment]
Many thanks for your quick feedback on this. Certainly setting the margin on `axis.text.x.top` gives the desired result, but wouldn't the expected behaviour be for the margin set on `axis.text.x` to be applied regardless of whether the `scale_x_discrete` position is set to top or bottom? (Or alternately, that the margin on the bottom should be set through `axis.text.x.bottom` such that it's consistent?)

**Comment by smouksassi** [comment]
maybe because it has a different default it wont automatically inherit:
https://github.com/tidyverse/ggplot2/blob/3aa29375167946b970692e42241e9aabaee3ae03/R/theme-defaults.r#L139

**Comment by clauswilke** [comment]
That's exactly the issue. The `axis.text.x.top` element has its own margin, so it won't take it from `axis.text.x`. By contrast, `axis.text.x.bottom` is just `NULL`, so it takes everything from `axis.text.x`.
