### ISSUE TITLE
Setting `options(ggplot2.discrete.fill)` overrides for aes(colour) with bad colourmap

### ISSUE THREAD

**Issue by apoorvalal** [tidyverse/ggplot2#4149]
I know the option to set colour palette is in its early stages, so wanted to flag an error I noticed.

Looks like setting `ggplot2.discrete.fill` overwrites the colourmap for `colour` (which should be unchanged based on the documentation?) with a cmap that is both ugly and unintelligible (and it hides the legend too for some reason).

```r
``` r
library(ggplot2)
(p1 = ggplot(mpg, aes(class)) + geom_bar(aes(fill = drv)))
```

![](https://i.imgur.com/MgFayHj.png)

``` r
# unrelated plot 
(p2 = ggplot(mtcars, aes(x = wt,  y = mpg)) +
  geom_point(aes(colour = as.factor(cyl))))
```

![](https://i.imgur.com/k2z7IRB.png)

``` r
# this should only apply to p1
options(ggplot2.discrete.fill    = function() scale_fill_viridis_d())
# as it does
p1
```

![](https://i.imgur.com/uJwnRtD.png)

``` r
# but it also mysteriously overrides p2's colourmap 
p2
```

![](https://i.imgur.com/wxdrvUa.png)

I'm running ggplot 3.3.2 in R 3.6.3 on a machine running ubuntu 18.04 LTS.

**Comment by yutannihilation** [comment]
Thanks, confirmed. Overriding is for convenience and it works perfectly when a vector of colors is supplied (or specifying `aesthetics = c("colour", "fill") in the scale function`. But, it also leads us to unexpected behaviours like the one you encountered. here's another bad example. I agree this needs to be improved somehow.

``` r
library(ggplot2)

p <- ggplot(mpg, aes(class)) + geom_bar(aes(fill = drv))

# Correct, and works as expected
withr::with_options(
  list(ggplot2.discrete.fill = function() scale_fill_viridis_d()),
  print(p)
)
```

![](https://i.imgur.com/uCm4bNC.png)

``` r

# Incorrect, and fails with a cryptic error
withr::with_options(
  list(ggplot2.discrete.fill = function() scale_colour_viridis_d()),
  print(p)
)
#> Error: Unknown colour name: f
```

**Comment by thomasp85** [comment]
@yutannihilation do you have any thoughts on how to best approach this?

**Comment by yutannihilation** [comment]
I was thinking if it's possible to check `aesthetics` of the scale and tweak it (with some warning). For example:

``` r
scale_colour_discrete <- function(..., type = getOption("ggplot2.discrete.colour", getOption("ggplot2.discrete.fill"))) {
  # TODO: eventually `type` should default to a set of colour-blind safe color codes (e.g. Okabe-Ito)
  type <- type %||% scale_colour_hue
  if (is.function(type)) {
    scale <- type(...)
    if (!"colour" %in% scale$aesthetics) {
      warn("...some nice warning...")
      scale$aesthetics <- c(scale$aesthetics, "colour")
      scale
    }
  } else {
    scale_colour_qualitative(..., type = type)
  }
}
```

**Comment by thomasp85** [comment]
@cpsievert are you relying on the colour->fill (or reverse) fallback in your theming packages? I'm very tempted to remove it to get it in line with how defaults are handled for continuous scales

**Comment by cpsievert** [comment]
@thomasp85 pretty sure I set both of them directly, so feel free to separate them
