### ISSUE TITLE
Discrete example in stat_summary doesn't work after 3.3.2

### ISSUE THREAD

**Issue by margoal1** [tidyverse/ggplot2#4150]
The example "Orientation follows the discrete axis" in stat_summary (lines 55 to 58) doesn't demonstrate what it claims to after the ggplot2 update to v3.3.2 (it did work in 3.3.0). The example doesn't actually follow the discrete axis. In order for it to demonstrate what it claims to, cyl should be replaced with factor(cyl) or a similar discrete datatype. See details below.

```r
# install / load ggplot2 v 3.3.0
# run below example

# Orientation follows the discrete axis
ggplot(mtcars, aes(mpg, cyl)) +
 geom_point() +
 stat_summary(fun.data = "mean_cl_boot", colour = "red", size = 2)
```
You will get a plot that summarizes mpg by groups of cyl, this is the presumed desired behavior based on the title of the example
![image](https://user-images.githubusercontent.com/44787126/88719754-c6d89580-d0f1-11ea-9e4e-3760a386b6f9.png)

```r
# install / load ggplot2 v 3.3.2
# run below example

# Orientation follows the discrete axis
ggplot(mtcars, aes(mpg, cyl)) +
 geom_point() +
 stat_summary(fun.data = "mean_cl_boot", colour = "red", size = 2)
```
Now you will get a plot that summarizes cyl by mpg, 
but this doesn't match the behavior implied by the title for the example "Orientation follows the discrete axis"
![image](https://user-images.githubusercontent.com/44787126/88719587-85e08100-d0f1-11ea-8d79-2eae993cb175.png)

In order for this example to work with v 3.3.2, the y-mapped variable has to result in a mapped_discrete datatype
For example, you could update the example as follows (replacing cyl with factor(cyl)):
```r
# Orientation follows the discrete axis
ggplot(mtcars, aes(mpg, factor(cyl))) +
 geom_point() +
 stat_summary(fun.data = "mean_cl_boot", colour = "red", size = 2) 
```
![image](https://user-images.githubusercontent.com/44787126/88719935-0f904e80-d0f2-11ea-9875-5b3f31844db4.png)

**Comment by yutannihilation** [comment]
> cyl should be replaced with factor(cyl)

Thanks, agreed. Would you like to contribute a pull request?
