### ISSUE TITLE
ggproto docs about Geom are wrong?

### ISSUE THREAD

**Issue by burchill** [tidyverse/ggplot2#4158]
From #3509, it seems that `setup_params()` has been added to the Geom object, but the docs (i.e., for `ggplot2-ggproto`) explicitly say that the Geom doesn't have this method.

**Comment by yutannihilation** [comment]
Thanks, the docs seem incorrect. Would you like to contribute a pull request?

**Comment by burchill** [comment]
I can do it, but I don't think I know enough about Geoms/ggproto to do it well. Should I just delete the whole paragraph?

**Comment by yutannihilation** [comment]
Yes, I think you can just delete it. Until https://github.com/tidyverse/ggplot2/pull/3506, we haven't found a nice usage of `setup_params()` on Geom objects, but now we know we actually need the method.

**Comment by yutannihilation** [comment]
Fixed by #4161
