### ISSUE TITLE
3.3.2: h.start in scale_colour_hue ignored

### ISSUE THREAD

**Issue by sebschub** [tidyverse/ggplot2#4163]
It seems that in ggplot 3.3.2, the h.start of scale_colour_hue is ignored (example below). ggplot 3.2.0 behaves as expected (by me). Sorry if the new behaviour is expected but I did not find any information about that.

``` r
library(ggplot2)
dsamp <- diamonds[sample(nrow(diamonds), 1000), ]
d <- ggplot(dsamp, aes(carat, price)) + 
  geom_point(aes(colour = clarity))
d + scale_colour_hue(h.start = 0)
```

![](https://i.imgur.com/yKJvAaw.png)

``` r
d + scale_colour_hue(h.start = 180)
```

![](https://i.imgur.com/fPITmkX.png)

<sup>Created on 2020-08-06 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by clauswilke** [comment]
Related?
https://github.com/r-lib/scales/issues/288

**Comment by sebschub** [comment]
@clauswilke Indeed, downgrading to scales 1.1.0 solves this issue.

**Comment by clauswilke** [comment]
Then I'll close this here. It needs to be addressed by the scales package.
