### ISSUE TITLE
Inconsistent color of overlapped objects

### ISSUE THREAD

**Issue by kamingfung** [tidyverse/ggplot2#4165]
Hi, I tried to show two sets of overlapping histograms and found that the color of the overlapped regions are different when the order of the color assignment is changed, even if the same set of color is used. 

Since I was expecting the color of two overlapped colors would be the same (similar to the mixed color of two colored lights?) and independent of the "order" of their appearance, I wonder if this is a bug or an intended design.

---

```r
library(tidyverse)

# sample data
df = data.frame(class = c("A", "B", "A", "B"),
                x = c(0, 0, 1, 1),
                y = c(10, 1, 2, 13))
```

This now it looks if the data is plotted with order: A, B (the overlapped region is dark green-ish)
```r
df %>%
  ggplot(aes(x = x, y = y, fill = class)) +
  geom_histogram(stat = "identity", position = "identity", alpha = 0.5)
```
![31c20739-3a9f-4ddc-adca-30257712c4f0](https://user-images.githubusercontent.com/25496979/89593225-96dd7080-d81c-11ea-86cf-b059e7b05a1a.png)

This now it looks if the data is plotted with the reversed order: A, B (the overlapped region is now dark pink-ish)
```r
df %>%
  ggplot(aes(x = x, y = y, fill = rev(class))) +
  geom_histogram(stat = "identity", position = "identity", alpha = 0.5)
```
![c9bee206-f68b-4985-b243-46779411ac22](https://user-images.githubusercontent.com/25496979/89593230-9a70f780-d81c-11ea-8c32-8c89e7e40477.png)

Please note that color at the overlapping areas is different.

---

Thank you for your attention to this issue and your time in developing this very useful package. I am looking forward to your reply.

**Comment by clauswilke** [comment]
Yes, that's how alpha blending of colors works. The order matters.
