### ISSUE TITLE
geom_line with data parameter has high memory usage, apparently unfreed after usage

### ISSUE THREAD

**Issue by JBuursma** [tidyverse/ggplot2#4167]
After running the following code:

```r
library(ggplot2)
df <- data.frame( x1 = runif(1e6))
df$y = df$x1

ggplot() + geom_hline( data = df, mapping = aes( yintercept = 1))

gc()
```
...Windows Task Manager shows 1.2 GB of memory usage on my machine. I would expect the ```gc()``` call to make this go down to something around 200 MB. But no amount of calling ```gc()``` or clearing objects from memory (e.g., ```rm( list = ls())```) will get that number down. Restarting R does: ```.rs.restartR()```. So I worry that this memory will never get freed up & might contribute to out of memory errors in other situations. Less-focused related discussion [here](https://stackoverflow.com/questions/63236265/r-geom-smooth-geom-hline-makes-memory-usage-explode).

Similar behavior is observed with ```geom_vline``` & ```geom_abline```. Using ggplot2 version 3.3.2, R version 4.0.2, Windows 10.

Thank you for all of your work.

**Comment by clauswilke** [comment]
See: https://stackoverflow.com/a/63344046/4975218

If there is a memory leak somewhere, I'd expect it to be in the graphics device, maybe in the display list, so this is entirely outside of the ggplot2 codebase.

**Comment by clauswilke** [comment]
Looking into this a bit more, my comment about the graphics device is probably wrong, since this type of code doesn't produce a million lines anymore (in the past it did). In any case, the SO answer I linked to describes the issue and potential solutions accurately.

**Comment by JBuursma** [comment]
Thank you. Yes, it's nice to have a workaround (not using the data parameter at all, or making sure it is as small as possible). The apparently memory leak is still odd to me, though.
