### ISSUE TITLE
ggsave to check validity of path to avoid obscure error message ?

### ISSUE THREAD

**Issue by moodymudskipper** [tidyverse/ggplot2#4168]
``` r
library(ggplot2)
#> Warning: le package 'ggplot2' a été compilé avec la version R 3.6.3
p <- ggplot()
ggsave("test?.pdf", p, device = cairo_pdf)
#> Saving 7 x 5 in image
#> Warning in dev(filename = filename, width = dim[1], height = dim[2], ...):
#> cairo error 'error while writing to output stream'
#> Error in dev(filename = filename, width = dim[1], height = dim[2], ...): unable to start device 'cairo_pdf'

```

<sup>Created on 2020-08-11 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

*unable to start device 'cairo_pdf'* made me think there was an issue with cairo_pdf when it I just have an invalid path, not obvious to debug!

For standard png output the error message is more helpful (pardon the french) :

```
ggsave("test?.png", p)
#> Saving 7 x 5 in image
#> Warning in grDevices::png(..., res = dpi, units = "in"): impossible
#> d'ouvrir le fichier 'test?.png' pour écriture
#> Warning in grDevices::png(..., res = dpi, units = "in"): opening device
#> failed
#> Error in grDevices::png(..., res = dpi, units = "in"): impossible de démarrer le périphérique png()

```

**Comment by yutannihilation** [comment]
Agreed, but I don't think `ggsave()` can check the validity because it's only the backend functions that know what filename is valid to them. All we can do is to hope these devices will get improved to issue friendly error messages...

**Comment by drtoche** [comment]
Oh wow, so grateful for this discussion: wrong path it was.
