### ISSUE TITLE
qplot() with empty labels now display as <empty>

### ISSUE THREAD

**Issue by cpsievert** [tidyverse/ggplot2#4170]
After the recent change in https://github.com/tidyverse/ggplot2/pull/4076, `qplot()`s that don't generate any axis labels now display `<empty>`, for example:

```r
qplot(1:10)
```

<img width="797" alt="Screen Shot 2020-08-13 at 12 45 34 PM" src="https://user-images.githubusercontent.com/1365941/90168655-07c3e180-dd63-11ea-9346-5d7a8aa88d17.png">

**Comment by yutannihilation** [comment]
Thanks, confirmed. Though we are going to deprecate `qplot()` (#4079), this can be fixed easily by checking if `expr$x` or `expr$y` is empty (`is_missing()`).

https://github.com/tidyverse/ggplot2/blob/6d91349ad4c9ca5d06886f3f8d5a6643b9371389/R/quick-plot.r#L91-L96

**Comment by thomasp85** [comment]
let us fix it still... It is going to remain in perpetuity – @yutannihilation will you provide a PR?

**Comment by yutannihilation** [comment]
Sure. I might not be able to work on this soon, but I will. Feel free to ping me.
