### ISSUE TITLE
Add error message for when `ggplot2()` is used instead of `ggplot()`

### ISSUE THREAD

**Issue by KartikSoneji** [tidyverse/ggplot2#4172]
I have seen a lot of people, especially those who are starting out with R/`ggplot` use `ggplot2` as the function name and then get confused at the (somewhat cryptic) error message
```
Error in ggplot2(...) : 
  could not find function "ggplot2"
```

Can we add a dummy function (maybe to [`R/plot.r`](https://github.com/tidyverse/ggplot2/blob/master/R/plot.r)) to show a more helpful error message to the user?
```r
ggplot2 <- function(...) {
  # Show a helpful error message if ggplot2 is used accidentally
  abort(glue("
    You have accidentally called `ggplot2` instead of `gglot`.
    Please note that while the name of the package is `ggplot2`, the function itself is called `ggplot`.
  "))
}
```

I will be happy to submit a Pull Request to implement this.

---

Reprex
```r
library(ggplot2)
ggplot2()
```

**Comment by yutannihilation** [comment]
Thanks, but this means `ggplot2` appears in the completion list when you type `ggplot`, right...? I don't think it's a good idea.

**Comment by KartikSoneji** [comment]
@yutannihilation Hmm, good point.
Can't we hide the method from autocomplete?

**Comment by yutannihilation** [comment]
Some IDE might provide such an option, but I don't think it's possible in general (I hoped marking the function as internal might hide it, but it doesn't seem to work, at least on RStudio).

**Comment by KartikSoneji** [comment]
@yutannihilation Is this helpful?
https://stackoverflow.com/questions/45516088/r-hide-internal-objects-in-package-from-autocomplete

I am not familiar with the internal workings of R studio, so I can't help here.

**Comment by yutannihilation** [comment]
No, that SO is discussing about a different topic.

**Comment by yutannihilation** [comment]
To be clear, what I meant by "marking the function as internal" means adding `@keywords internal` to its documentation (see `Package` section of this https://cran.r-project.org/web/packages/roxygen2/vignettes/rd.html). Sorry if this was confusing.

**Comment by KartikSoneji** [comment]
@yutannihilation Thanks for the clarification.
Sorry if this is obvious, but what happens if you don't add any roxygen comments at all?
(No `@export`, no `#'` comments.)

**Comment by yutannihilation** [comment]
If you don't export the function, users cannot call it without `ggplot2:::` prefix, which means the users keep seeing the current error message :)

**Comment by KartikSoneji** [comment]
@yutannihilation What about the `@noRd` tag? https://style.tidyverse.org/documentation.html#internal-functions
Maybe in combination with `@keywords internal`?

**Comment by yutannihilation** [comment]
I don't think it works. It doesn't matter whether or not the function has Rd on whether or not to include it in the completion list. I'm closing this as I see no way to let `ggplot2()` make sense at the moment... Thanks for the idea anyway.
