### ISSUE TITLE
Allow passing arguments to the custom labelling functions

### ISSUE THREAD

**Issue by netique** [tidyverse/ggplot2#4173]
In the discrete scales (e.g. `scale_y_discrete()`), we are allowed to specify a vector of values, NULL, `waiver()` or any function that takes the breaks and returns the labels desired. The last option is especially neat as it gives the user plenty of possibilities. However, the breaks are passed only as the first argument of the function. When I want to gain any control, I have to "wrap" my function with `function(x) my_function(arg_1, arg_2)`. In other words, labels argument of a scale layer can only handle function "name/object" and not a function call.

Another and quite a similar issue concerns `facet_wrap` and `facet_grid` layers; this time, a special `labeller `function is introduced for labelling and there is even documented `as_labeller` function. This works great, but again, when I construct `my_function` labeller, it cannot be specified as a function call with arguments. Again, when wrapped with `as_labeller(function(x) my_function(arg_1, arg_2))` it does the job as intended.

Is there any workaround that I am missing? If not, I would highly appreciate the option to pass additional arguments to my labelling function. Maybe it could be accomplished with some `labs_args` list user can specify within a scale/facet layer or possibly, it would be even nicer to have `purrr `style recipe, like `~ my_function(.x, arg_1, arg_2)`.

Thanks a lot!

**Comment by thomasp85** [comment]
purrr style lambda function should work everywhere and if they are not it is an oversight that should get fixed. A PR is very welcome

**Comment by netique** [comment]
@thomasp85 Solution proposed in PR #4187.

**Comment by teunbrand** [comment]
Are lambda functions also going to be supported in continuous and binned scales? (I don't think they are currently.) Additionally, if the `label` argument can accept lambda functions, it would seem natural that also the `limits`, `breaks` and `minor_breaks` arguments  would accept these too. You could probably even make a case to also allow the `rescaler` and `oob` arguments to be lambda functions.
