### ISSUE TITLE
Unable to plot in RStudio: Error in default + theme : non-numeric argument to binary operator

### ISSUE THREAD

**Issue by marymlucas** [tidyverse/ggplot2#4177]
When attempting to plot a simple dataframe with two variables using ggplot2 I get this error message in RStudio: "Error in default + theme : non-numeric argument to binary operator"

Two points to note:
- I have been plotting similar data using the same script for weeks now but suddenly it won't work.  I tried updating ggplot2 and my other installed packages but no joy.  
- This is happening both in RStudio and the default R console, I get the same error.

Environment:
R version: 3.6.3
R Studio Version: 1.2.5042
ggplot2 version 3.3.2

Reprex:

```r
library(ggplot2)

my_agegrp <- c("first", "second", "third", "fourth", "fifth")
my_count <- c(6567, 3164, 1035, 734, 706)
df <- data.frame(my_agegrp, my_count)
ggplot(df, aes(my_agegrp, my_count)) + geom_col()
```

**Comment by marymlucas** [comment]
Just verified that this is happening both in RStudio and in the default R console with a different but similar dataset.

**Comment by marymlucas** [comment]
Just updated RStudio to the latest version (Version 1.3.1073) to see if that would make a difference but no go.

**Comment by yutannihilation** [comment]
This sort of question is a better fit for [RStudio Community](https://community.rstudio.com). Please ask there with a minimal reproducible example. We use this issue tracker for bug reports and feature requests.

One possibility is that you might set a invalid default theme in your `.Rprofile`, but I'm not sure...

**Comment by marymlucas** [comment]
Thank you for the comment, but this error is there even when using the default R console, not just in RStudio. Hence I think it might be a ggplot2 issue.

**Comment by marymlucas** [comment]
Thank you for the comment, but this error is there even when using the default R console, not just in RStudio. Hence I think it might be a ggplot2 issue.



> This sort of question is a better fit for [RStudio Community](https://community.rstudio.com). Please ask there with a minimal reproducible example. We use this issue tracker for bug reports and feature requests.
> 
> One possibility is that you might set a invalid default theme in your `.Rprofile`, but I'm not sure...

**Comment by marymlucas** [comment]
> One possibility is that you might set a invalid default theme in your `.Rprofile`, but I'm not sure...

@yutannihilation  Thank you! Your suggestion helped me solve my problem.

**Comment by AleksandarMedarevic** [comment]
I have a same problem when I write:
plot + theme(text = element_text(family = "Times New Roman"))
