### ISSUE TITLE
Suggestion: fatten parameter for geom_point

### ISSUE THREAD

**Issue by jonathan-g** [tidyverse/ggplot2#4182]
In `geom_pointrange()`, the `fatten` parameter allows scaling the point to some factor larger than the line. Several other geometries, such as `geom_linerange()` also use a `fatten` parameter. An issue that has come up in several contexts (e.g., https://stackoverflow.com/questions/34893760/how-to-scale-the-size-of-line-and-point-separately-in-ggplot2) is the desire to set the proportionality between point size and line size in plots where the point and line sizes are mapped to a continuous or discrete (factor) variable.

Fatten would be a nice way to address this and would have consistency in nomenclature with other geometries.

    library(tidyverse)

    # You can't see the points because they're the same size as the lines
    mtcars %>% 
      mutate(cyl = ordered(str_c(cyl, " cylinders"))) %>% 
      ggplot(aes(x = disp, y = mpg, size = cyl, color = cyl)) + 
      geom_line() + 
      geom_point() + 
      scale_size_manual(values = c(0.5, 1.0, 1.5))

![](https://i.imgur.com/8KkU4z6.png)

    # Kludge to make pointrange only plot a point.
    # Use fatten to make points twice as fat as the lines so they can be
    # seen easily.
    mtcars %>% 
      mutate(cyl = ordered(str_c(cyl, " cylinders"))) %>% 
      ggplot(aes(x = disp, y = mpg, size = cyl, color = cyl)) + 
      geom_line() + 
      geom_pointrange(aes(ymin = mpg, ymax = mpg), fatten = 2) + 
      scale_size_manual(values = c(0.5, 1.0, 1.5))

![](https://i.imgur.com/DYax5VR.png)

<sup>Created on 2020-08-25 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

I find the second chart, the one created with `geom_pointrange()` easier to read, and it would be nice to have a `fatten` parameter for `geom_point` to make it possible to generate this kind of geometry without the kludge.

    xfun::session_info()
    #> R version 4.0.2 (2020-06-22)
    #> Platform: x86_64-w64-mingw32/x64 (64-bit)
    #> Running under: Windows 10 x64 (build 18363)
    #> 
    #> Locale:
    #>   LC_COLLATE=English_United States.1252 
    #>   LC_CTYPE=English_United States.1252   
    #>   LC_MONETARY=English_United States.1252
    #>   LC_NUMERIC=C                          
    #>   LC_TIME=English_United States.1252    
    #> 
    #> Package version:
    #>   askpass_1.1            assertthat_0.2.1       backports_1.1.8       
    #>   base64enc_0.1.3        BH_1.72.0.3            blob_1.2.1            
    #>   broom_0.7.0.9001       callr_3.4.3            cellranger_1.1.0      
    #>   cli_2.0.2              clipr_0.7.0            colorspace_1.4.1      
    #>   cpp11_0.2.1            crayon_1.3.4           curl_4.3              
    #>   DBI_1.1.0              dbplyr_1.4.4           desc_1.2.0            
    #>   digest_0.6.25          dplyr_1.0.2            ellipsis_0.3.1        
    #>   evaluate_0.14          fansi_0.4.1            farver_2.0.3          
    #>   forcats_0.5.0          fs_1.5.0               generics_0.0.2        
    #>   ggplot2_3.3.2          glue_1.4.1             graphics_4.0.2        
    #>   grDevices_4.0.2        grid_4.0.2             gtable_0.3.0          
    #>   haven_2.3.1            highr_0.8              hms_0.5.3             
    #>   htmltools_0.5.0        httr_1.4.2             isoband_0.2.2         
    #>   jsonlite_1.7.0         knitr_1.29             labeling_0.3          
    #>   lattice_0.20.41        lifecycle_0.2.0        lubridate_1.7.9       
    #>   magrittr_1.5           markdown_1.1           MASS_7.3.52           
    #>   Matrix_1.2.18          methods_4.0.2          mgcv_1.8.32           
    #>   mime_0.9               modelr_0.1.8           munsell_0.5.0         
    #>   nlme_3.1.148           openssl_1.4.2          pillar_1.4.6          
    #>   pkgbuild_1.1.0         pkgconfig_2.0.3        pkgload_1.1.0         
    #>   praise_1.0.0           prettyunits_1.1.1      processx_3.4.3        
    #>   progress_1.2.2         ps_1.3.4               purrr_0.3.4           
    #>   R6_2.4.1               RColorBrewer_1.1.2     Rcpp_1.0.5            
    #>   readr_1.3.1            readxl_1.3.1           rematch_1.0.1         
    #>   reprex_0.3.0           rlang_0.4.7            rmarkdown_2.3.3.9000  
    #>   rprojroot_1.3.2        rstudioapi_0.11.0.9000 rvest_0.3.6           
    #>   scales_1.1.1           selectr_0.4.2          splines_4.0.2         
    #>   stats_4.0.2            stringi_1.4.6          stringr_1.4.0         
    #>   sys_3.4                testthat_2.3.2         tibble_3.0.3          
    #>   tidyr_1.1.1            tidyselect_1.1.0       tidyverse_1.3.0       
    #>   tinytex_0.25           tools_4.0.2            utf8_1.1.4            
    #>   utils_4.0.2            vctrs_0.3.2            viridisLite_0.3.0     
    #>   whisker_0.4            withr_2.2.0            xfun_0.16             
    #>   xml2_1.3.2             yaml_2.2.1

<sup>Created on 2020-08-25 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by thomasp85** [comment]
We plan to decouple size and line width which will eventually fix this

**Comment by jonathan-g** [comment]
That sounds like the best solution. Thank you for your response.
