### ISSUE TITLE
`print.ggplot2` for loops and functions

### ISSUE THREAD

**Issue by llrs** [tidyverse/ggplot2#4186]
I don't understand how the print system works, and I couldn't find anywhere if this is explained in detail. I [found](https://stackoverflow.com/a/27201707/2886003) gpplot2 overloads the print method, but I'm not sure what it means and how does it affect to not working on a loop or function. Could be possible to avoid using explicitly `print` on a loop? Maybe calling `NextMethod` or `UseMethod`?.

I'm sure I'm missing a lot, but I would appreciate your comments. Thanks

I found this "surprising" effect of pipetting and printing, not sure if related, but it actually prints/shows the plot. 

```r
library("ggplot2")
library("magrittr")
{ggplot(mpg, aes(displ, hwy)) +
     geom_point() %>% 
     print()}
```

Upon further reading I found it is mentioned on the [R FAQs](https://cran.r-project.org/doc/FAQ/R-FAQ.html#Why-do-lattice_002ftrellis-graphics-not-work_003f):
 
> The most likely reason is that you forgot to tell R to display the graph. Lattice functions such as xyplot() create a graph object, but do not display it (the same is true of ggplot2 graphics, and Trellis graphics in S-PLUS). The print() method for the graph object produces the actual display. When you use these functions interactively at the command line, the result is automatically printed, but in source() or inside your own functions you will need an explicit print() statement.

**Comment by karawoo** [comment]
I'm not sure exactly what you are trying to achieve, but if the FAQ and the [print documentation](https://ggplot2.tidyverse.org/reference/print.ggplot.html) don't address your question, I would recommend asking on [RStudio Community](https://community.rstudio.com/). The ggplot2 issue tracker is more for bug reports and feature requests.

**Comment by llrs** [comment]
I want that the print method for ggplot objects to work inside loops and functions. I think it is a feature request that might not be possible. But will ask there. Thanks for replying

**Comment by thomasp85** [comment]
`print()` works fine inside for loops - you just have to call it explicitly... that is not different from any other object in R. The automatic printing is a feature of the REPL and simply calls `print()` automatically on the result of the last evaluated expression

**Comment by llrs** [comment]
Thanks for the clarifications. So,when I run the above code and I see printed:

```
library("ggplot2")
library("magrittr")
{ggplot(mpg, aes(displ, hwy)) +
     geom_point() %>% 
     print()}
# geom_point: na.rm = FALSE
# stat_identity: na.rm = FALSE
# position_identity 
```
![ggplot_print](https://user-images.githubusercontent.com/6818218/92155781-3267fe00-ee28-11ea-9f47-db2afbeea788.png)

is everything correct? If I understand correctly the REPL calls the last expression and evaluates it (`geom_point`) and prints it (the `#  geom_point:...`) plus trigger the print of the plot (`ggplot(mpg, aes(displ, hwy))`), but as we have already evaluated the last expression, it doesn't draw the points on the plot?

BTW this is magrittr 1.5.0.9000, not sure if I should test it with the old magrittr or it doesn't matter.

**Comment by thomasp85** [comment]
well, there's a lot going on in that expression. The main issue is that the pipe operator has a higher operator precedence than `+`, so rolling it all out you get:

```
ggplot(mpg, aes(displ, hwy)) +
     print(geom_point())
```

The return value of the `print()` is `NULL` which gets added to the `ggplot(mpg, aes(displ, hwy))` call resulting in a blank plot which, because it is the last expression gets printed. Further the `print(geom_point())` call will show the description of the point layer in the console

**Comment by llrs** [comment]
Oh, so I need to find a better replacement to print ggplot inside {}. Thanks

**Comment by thomasp85** [comment]
Just assign the plot to a variable and print that

**Comment by llrs** [comment]
The other solution to keep using the pipe and which works everywhere is:
```r
ggplot(mpg, aes(displ, hwy)) %>% `+`(geom_point()) %>% print()
```
Anyway thanks, let's see how the precedence of the base pipe for R 4 or 5 will be (if it finally comes).

**Comment by thomasp85** [comment]
I would honestly avoid that style as it leads to very foreign code and kinda defeats both the point of the pipe and the +. To each their own of course
