### ISSUE TITLE
Axis label on 0 disappears on scale_*_sqrt()

### ISSUE THREAD

**Issue by yutannihilation** [tidyverse/ggplot2#4193]
(Originally found https://github.com/tidyverse/ggplot2/issues/4155#issuecomment-674361287)

Probably something is wrong with backtransformation...? (I guess this is somehow related to the fact that the limits are expanded to the negative value, which doesn't exist in sqrt scale. But, still not sure why it also disappears when only the max is expanded.)

    library(ggplot2)
    library(patchwork)

    d <- data.frame(value = 16)

    f <- function(expand) {
      ggplot(d) +
        geom_point(aes(value, 0), colour = "red", size = 10) +
        scale_x_sqrt(limits = c(0, 16), breaks = c(0, 4, 16), expand = expand)
    }

    p1 <- f(c(0.1, 0.1)) + ggtitle("expand both (label disappears)")
    p2 <- f(c(0, 0.1)) + ggtitle("expand max (label disappears)")
    p3 <- f(c(0, 0)) + ggtitle("no expand (ok)")
    p1 / p2 / p3

![](https://i.imgur.com/LOwaQum.png)

<sup>Created on 2020-09-06 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by clauswilke** [comment]
This is a longstanding problem, I believe: #980

**Comment by yutannihilation** [comment]
Oh, I didn't notice it, sorry...
