### ISSUE TITLE
Warning when using library(ggplot2)

### ISSUE THREAD

**Issue by hbaniecki** [tidyverse/ggplot2#4195]
Warning when using `library(ggplot2)` : 
Warning message: replacing previous import ‘vctrs::data_frame’ by ‘tibble::data_frame’ when loading ‘dplyr’ 

![image](https://user-images.githubusercontent.com/32574004/92581272-bdfde680-f28f-11ea-951e-fe10b61af489.png)

**Comment by yutannihilation** [comment]
Try updating dplyr.
