### ISSUE TITLE
documentation: values list for legend.box.just appears incomplete

### ISSUE THREAD

**Issue by twest820** [tidyverse/ggplot2#4196]
The current documentation for [`theme()`](https://ggplot2.tidyverse.org/reference/theme.html) states

**legend.box.just** justification of each legend within the overall bounding box, when there are multiple legends ("top", "bottom", "left", or "right")

I happened to need `theme(legend.box.just = "center")` so I tried it anyway and found it behaved as expected when centering two legends (an alpha legend and a merged color plus linetype legend) within a bottom legend box.

So life is good. But it would be useful to know if this just signals the documentation is a bit out of date or if I'm relying on a behavior that's formally unsupported.

Version; ggplot 3.3.2

**Comment by clauswilke** [comment]
The value of `legend.box.just` is converted into numerical justification parameters using the function `grid::valid.just()`:
https://github.com/tidyverse/ggplot2/blob/a11e0983f2bd3065f3aeb5cdc1b3bcf87fa3cc78/R/guides-.r#L277
So you can set `legend.box.just` to whatever values `valid.just()` understands. Unfortunately that function isn't well documented either. The documentation literally says `e.g., "left" becomes 0, "right" becomes 1, etc, ...`.

The value `"center"` is supported, though, and the theme documentation should say so.
