### ISSUE TITLE
Title is placed at the bottom of the plot when coord_fixed and scale_y_reverse both is used

### ISSUE THREAD

**Issue by henrikmidtiby** [tidyverse/ggplot2#4198]
When using `coord_fixed` in the code below, the title of the plot is placed in an (for me) unexpected position at the bottom of the plot.

The issue vanishes if I remove either `coord_fixed` or `scale_y_reverse`.

I used a similar code a year ago (where `coord_equal` was used), where the plot title was placed as expected (in the top part of the plot).
Therefore I assume that something has changed since then.

``` r
library(tidyverse)
diamonds %>%
  ggplot() + 
  scale_y_reverse() + 
  aes(x = carat) + 
  aes(y = carat) + 
  geom_point() + 
  coord_fixed(xlim=c(0, 6), 
              ylim=c(0, 3)) + 
  labs(title = 'Carat and price of diamonds')
```

![](https://i.imgur.com/tKCAYuP.png)

<sup>Created on 2020-09-11 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by yutannihilation** [comment]
Not sure what was wrong, but this is already fixed in the dev version (confirmed this issue is reproducible with the CRAN version of ggplot2)

    devtools::load_all("~/repo/ggplot2")
    #> Loading ggplot2

    ggplot(diamonds) + 
      scale_y_reverse() + 
      aes(x = carat) + 
      aes(y = carat) + 
      geom_point() + 
      coord_fixed(xlim=c(0, 6), 
                  ylim=c(0, 3)) + 
      labs(title = 'Carat and price of diamonds')

![](https://i.imgur.com/af550ww.png)

<sup>Created on 2020-10-11 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
