### ISSUE TITLE
Datetime scales don't support out of bounds (oob) arguments

### ISSUE THREAD

**Issue by teunbrand** [tidyverse/ggplot2#4199]
I've noticed that date/time scales do not support the `oob` argument that the continuous scales have, while I do think this might be a useful feature.

Let's say I have the following graph, of which I would want the x-axis labelling:

``` r
library(ggplot2)

ggplot(economics, aes(date, unemploy)) +
  geom_line() +
  scale_x_date(limits = as.Date(c("1970-01-01", "2010-01-01")))
#> Warning: Removed 93 row(s) containing missing values (geom_path).
```

![](https://i.imgur.com/ZvMoD55.png)

But I'd like the line to look like the following:

``` r


ggplot(economics, aes(as.numeric(date), unemploy)) +
  geom_line() +
  scale_x_continuous(
    limits = as.numeric(as.Date(c("1970-01-01", "2010-01-01"))),
    oob = scales::oob_squish
  )
```

![](https://i.imgur.com/hVvdVde.png)

<sup>Created on 2020-09-11 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

This does not currently seem possible. However, as the `ggplot2:::datetime_scale()` function passes the `...` to `continuous_scale()` (which *does* use `oob`), it would seem most of the infrastructure for `oob` arguments is already there.

Thanks for considering!

**Comment by yutannihilation** [comment]
This sounds good to me. Datetime scales lost `...` on this commit https://github.com/tidyverse/ggplot2/commit/4870fb09fa93918d8a83a19a1523920e8b5f67f3#diff-053b14c802505a7a11aeffaefe971dd4R57, and there seems no intention. Would you mind creating a pull request for this?
