### ISSUE TITLE
geom_histogram() warns about removed rows but all rows are present in the plot

### ISSUE THREAD

**Issue by mundl** [tidyverse/ggplot2#4200]
Using `geom_histogram()` together with `scale_x_continuous(limits = c(-100, 100))` and one of the limits being different from `NA` ggplot warns about having removed 2 rows with missing values. Even when all the data is within the limits specified. 

```
`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
Warning message:
Removed 2 rows containing missing values (geom_bar). 
```

Summing up the height of the bars (counts) gives the number of observations in the dataset. So I assume no values have been removed and the warning message is just wrong.

```r
library(ggplot2)

# sample 10 values between 1 and 10
set.seed(31415)
d <- data.frame(x = sample(1:10, size = 10, replace = TRUE))

# no warning about removed rows
ggplot(d) + geom_histogram(aes(x))

# specifying limits manually but all data is within the limits
# warns about 2 rows being removed but the bar height is 10
ggplot(d) + 
  geom_histogram(aes(x)) + 
  scale_x_continuous(limits = c(-100, 100))

# no warning about removed rows
ggplot(d) + 
  geom_histogram(aes(x)) + 
  scale_x_continuous(limits = c(NA, NA))

```

using R version 4.0.2 (2020-06-22) and ggplot2 3.3.2  ( 2020-06-19)

**Comment by yutannihilation** [comment]
Just because you don't see it, doesn't mean it isn't there :)

I agree the warning is a bit confusing, but we concluded that this issue is too complex and not worth fixing (c.f. https://github.com/tidyverse/ggplot2/issues/2887#issuecomment-485721611). The discussions on #4083 might help.

    library(ggplot2)

    set.seed(31415)
    d <- data.frame(x = sample(1:10, size = 10, replace = TRUE))

    ggplot(d) + 
      geom_histogram(aes(x), colour = "red") + 
      scale_x_continuous(limits = c(-100, 100))
    #> `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
    #> Warning: Removed 1 rows containing missing values (geom_bar).

![](https://i.imgur.com/jXH8Zo0.png)

<sup>Created on 2020-09-11 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by mundl** [comment]
Thanks for the clarification! I can completely understand your decision, indeed the warning is a little bit confusing. ;-)
