### ISSUE TITLE
scale_fill_manual not working with stat_function in loops

### ISSUE THREAD

**Issue by chaomacau** [tidyverse/ggplot2#4203]
Hi, 

I am having issue making scale_fill_manual to work with stat_function in loops:
###Dummy Dataset:
x<-seq<-seq(-200, 200, by=2)
means<-c(50, 100, -100)
sds<-c(70, 50, 40)
lamdas<-c(35, 35, 30)
colors<-c("red", "blue", "green")
data<-rnorm(300, mean=0, sd=50)

###Example1: No legend is outputted in this case:
p1<-ggplot(data.frame(data), aes(x=data))+geom_histogram(aes(x=data, y=..density..))
for (i in 1:length(means)){
  p1<-p1+stat_function(fun=dnorm, n=1000, args=list(means[i], sds[i]), aes(color=colors[i]), color=colors[i], geom="area", fill=colors[i], alpha = .2)
}
p1+ggtitle("Test Adding Legend")+theme(plot.title=element_text(hjust = 0.5))+
  scale_fill_manual(c("test1", "test2", "test3"))
print(p1)

###Example2: legend not matching color in loop
p1<-ggplot(data.frame(data), aes(x=data))+geom_histogram(aes(x=data, y=..density..))
for (i in 1:length(means)){
  p1<-p1+stat_function(fun=dnorm, n=1000, args=list(means[i], sds[i]), aes(color=colors[i]), geom="area", fill=colors[i], alpha = .2)
}
p1+ggtitle("Test Adding Legend")+theme(plot.title=element_text(hjust = 0.5))+
  scale_fill_manual(c("test1", "test2", "test3"))
print(p1)

###Example3: Line color not matching shade color and legend not filled
p1<-ggplot(datadf, aes(x=datadup, color=factor(meansdup), fill=factor(meansdup)))
for (i in 1:length(means)){
    sdf<-datadf[datadf$meansdup == means[i],]
    p1<-p1+geom_histogram(aes(x=sdf$datadup, y=..density..), fill=NA, color="black")+
        stat_function(fun=dnorm, n=1000, args=list(means[i], sds[i]), geom="area", fill=colors[i], alpha = .2)
}
p1+ggtitle("Test Adding Legend")+theme(plot.title=element_text(hjust = 0.5))+
scale_fill_manual(values=colors, c("test1", "test2", "test3"))

Ideally we want the legend to match the shade and line colors of the distributions. Is there a way to do so? Thank you!

**Comment by clauswilke** [comment]
Yes, this doesn't work, because of R's lazy evaluation of function arguments. Please post a question on the RStudio Forums or on Stackoverflow to ask what an appropriate code pattern would look like to get the result you want. Actually, you should probably first do a search for "for loop" and "ggplot" as similar questions get asked all the time. See e.g. [here.](https://stackoverflow.com/questions/26235825/for-loop-only-adds-the-final-ggplot-layer)
