### ISSUE TITLE
ggsave inproperly rendering geom_line with factored y-variable

### ISSUE THREAD

**Issue by MartinEarle** [tidyverse/ggplot2#4204]
Hi,

I have come across a strange issue with `ggsave()` where it does not properly render a line if the y-variable is factored. It looks to me like it is ignoring the factoring, and plotting as if it was unfactored. It looks like this behavior does not occur when factoring the x-variable. When I use graphic devices like `png()` I do not have the issue. I did not include `ggsave()` or `png()` in the reprex because there is nowhere for the files to save, of course, but I have attached the output of each method below it.

``` r
library(tidyverse)

mtcars %>% 
  mutate(mpg = factor(mpg)) %>% 
  ggplot(aes(disp, mpg)) +
    geom_line(group = 1)
```

![](https://i.imgur.com/94CuLjk.png)

<sup>Created on 2020-09-19 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

`ggsave()`:
![ggplot_output](https://user-images.githubusercontent.com/56650235/93668189-61ee4b80-fa61-11ea-9a42-583921f4d381.png)

`png()`:
![png_output](https://user-images.githubusercontent.com/56650235/93668194-661a6900-fa61-11ea-88c3-a2a6534fb217.png)

**Comment by yutannihilation** [comment]
Thanks, seems reproducible. Curious...

<details>

    library(tidyverse)

    mtcars %>% 
      mutate(mpg = factor(mpg)) %>% 
      ggplot(aes(disp, mpg)) +
      geom_line(group = 1)

![](https://i.imgur.com/8CQWZn2.png)


    ggsave("tmp.png")
    #> Saving 7 x 5 in image
    knitr::include_graphics("tmp.png")

<img src="https://i.imgur.com/cRXQDZl.png" width="2100" />

<sup>Created on 2020-09-19 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

</details>

**Comment by thomasp85** [comment]
The issue is somehow located in `last_plot()`, not ggsave... if you pass the plot object to ggsave it does what it should
