### ISSUE TITLE
geom_sf() does not support scale_y_reverse()

### ISSUE THREAD

**Issue by toobiwankenobi** [tidyverse/ggplot2#4206]
---

As the title describes, `geom_sf()` does not support `scale_y_reverse()`. The problem was initially described [here](https://stackoverflow.com/questions/53620768/how-to-flip-y-axis-in-geom-sf). I don't know if this behavior is intended or if this would be something to improve. 

```r
# for reprex: see link above
```
Thank you for your amazing work!

**Comment by yutannihilation** [comment]
This is because we don't even know what does "reverse" means on `coord_sf()`. See https://github.com/tidyverse/ggplot2/issues/4021#issuecomment-650787582
