### ISSUE TITLE
is scale_x_binned() supposed to not play with geom_boxplot() ?

### ISSUE THREAD

**Issue by JanaJarecki** [tidyverse/ggplot2#4211]
Hi,

is this desired in `scale_x_binned()`? I would have expected several boxplots (one per bin).

    ggplot(mtcars, aes(x=wt)) +
      geom_boxplot(aes(y=mpg)) +
      scale_x_binned()

![image](https://user-images.githubusercontent.com/9809311/94308489-e61b6400-ff76-11ea-98a4-b456962d0377.png)

-  R version 4.0.2 (2020-06-22)                                                             
-  Windows 10
-  Dev version of ggplot2

**Comment by yutannihilation** [comment]
I understand the intention of your code, but this is the expected behaviour. Since `x` is continuous, even after it's binned, it cannot be a grouping variable. (`geom_bar()` works fine because its transformation works without `group` aesthetics)
