### ISSUE TITLE
ggsave to svg fails for certain themes

### ISSUE THREAD

**Issue by geotheory** [tidyverse/ggplot2#4212]
ggsave to svg operation is failing when certain themes are used:

```r
require(ggplot2)
#> Loading required package: ggplot2
p = qplot(Sepal.Length, data=iris, geom='density') + theme_void()
ggsave(p, filename = 'test.svg', w=8, h=6)
#> Error in svglite_(file, bg, width, height, pointsize, standalone, aliases): Expecting a single string value: [type=NULL; extent=0].
```

I've tested {ggplot} and {ggthemes} and the following show this error:
- ggplot::theme_void
- ggplot::theme_minimal
- ggthemes::theme_map
- ggthemes::theme_tufte
- ggthemes::theme_solid

I'm running macOS 10.15.5, R 4.0.2, ggplot 3.3.2.9000.

**Comment by karawoo** [comment]
Thanks for filing, this looks like a consequence of #4164. I guess our approach to that feature needs a bit more nuance to handle themes whose background is null or blank

```r
theme_void()$plot.background
#> NULL
theme_minimal()$plot.background
#> list()
#> - attr(*, "class")= chr [1:2] "element_blank" "element"
```

**Comment by geotheory** [comment]
Thanks @karawoo :)
