### ISSUE TITLE
Feature request: ggsave takes multiple filenames

### ISSUE THREAD

**Issue by swo** [tidyverse/ggplot2#4214]
I often make one plot with ggplot and then want to save it as a .png (for dropping into Google Docs) and as a .pdf (for dropping into Word documents or email attachments). Saving with default dimensions isn't hard:

```
ggsave("fig.png", plot = plot)
ggsave("fig.pdf", plot = plot)
```

But things become a bit of a copy-paste pain when I have more keywords:

```
ggsave("fig.png", plot = plot, height = 4, width = 4, units = "cm")
ggsave("fig.pdf", plot = plot, height = 4, width = 4, units = "cm")
```

I sometimes define a function to handle this case:

```
ggsave_multiple <- function(fns, ...) map(fns, function(x) ggsave(x, ...))
ggsave_multiple(c("fig.png", "fig.pdf"), plot = plot, height = 4, width = 4, units = "cm")
```

But it would be nice if ggplot did this by default, but currently this throws an error:

```
ggsave(c("fig.png", "fig.pdf"), plot = plot)
# Error: `device` must be NULL, a string or a function.
```

**Comment by yutannihilation** [comment]
Sounds nice, but I'm a bit afraid this would be complex when we consider corner cases (e.g. how to handle different options that different devices might require?)

**Comment by swo** [comment]
Fair: I just realized, for example, that including the useDingbats option
when the device is not pdf throws an error.
