### ISSUE TITLE
Plot annotation outside plot region in a shiny app 

### ISSUE THREAD

**Issue by dancelestini** [tidyverse/ggplot2#4219]
How can I show the name of the dotted red line underneath the x axis ? I would like to put the name of this vertical line at the same level of the date or maybe lower. Maybe the annotate element is not the right one but with "geom_text" it's even worst. Here is the shiny app in question where I just don't put the names of this line. 
[https://dancelestini.shinyapps.io/Swiss-COVID19/](url) 

<img width="582" alt="image" src="https://user-images.githubusercontent.com/71639864/95111885-72c8dd80-0740-11eb-82ea-f98f5edc77e1.png">

```r
library(tidyverse)
library(readxl)
library(plotly)
library(ggplot2)

df = read_excel("covid-19.3.xlsx", sheet = 1)

df$Date = as.Date(df$Date,format = "%Y-%m-%d")

p = ggplot(data = df, aes(Date, `Nombre de cas`))+
  geom_col(size = 0.1)+
  labs(title = "Swiss COVID-19 cases per day",y="New observation per day", x = "Date")+
  theme(plot.title = element_text(hjust = 0.5, color = "red", size =14, face="bold.italic"),
        axis.title = element_text(face = "bold"),
        plot.margin = margin(20,20,20,20, unit = "pt"))+
  geom_vline(xintercept = as.numeric(as.Date("2020-05-11")), color = "red", linetype = "dotted", size = 0.5)+
  annotate("text",x=as.Date("2020-05-11"),y = -100,label = "name",color = "black",size = 5)+
  coord_cartesian(clip = "off")
  
ggplotly(p)
```

**Comment by smouksassi** [comment]
not clear what is your issue below see how you can get ggplot to show the label below the axis but getting ggplotly to work with this is not a ggplot issue.
```r
library(ggplot2)
p <- ggplot(data = mtcars, aes(cyl, mpg ))+
  geom_col(size = 0.1)+
  theme(plot.margin = margin(20,20,20,20, unit = "pt"))+
  geom_vline(xintercept = 6.5, color = "red", linetype = "dotted", size = 2)+
coord_cartesian(clip = "off",ylim = c(0,300))+
annotate("text",x=6.5,y = -30,label = "name",
         color = "blue",size = 5)
p
```

**Comment by yutannihilation** [comment]
Thanks @smouksassi, I too feel this is not a ggplot2's issue.

@dancelestini 
In general, this sort of question is a better fit for [RStudio Community](https://community.rstudio.com). Please ask there with a minimal reproducible example. We use this issue tracker for bug reports and feature requests. That said, filing an issue on plotly's repo might be a choice for this one.
