### ISSUE TITLE
geom_qq Argument geom Does Not Work With GeomLabel

### ISSUE THREAD

**Issue by AustinNar** [tidyverse/ggplot2#4220]
## Issue Description

When creating a qq plot using geom_qq, I would like to pass `geom=GeomLabel` to label the points, but the function does not properly pass through the `label` aesthetic. Other geoms, like `GeomLine`, that do not require extra aesthetics, work fine. This issue also applies to `GeomText`.

## Example

`GeomLine` works

```r
library(ggplot2)

test_data <- data.frame(x = rnorm(10), label = LETTERS[1:10])

ggplot(test_data) +
  geom_qq(aes(sample=x), geom = GeomLine) 

```
![image](https://user-images.githubusercontent.com/28735601/95112467-f79b0380-070e-11eb-8cb4-e5860fae7646.png)

`GeomLabel` doesn't
### 
```r
ggplot(test_data) + 
  geom_qq(aes(sample = x, label = label), geom = GeomLabel)
#> Error: geom_label requires the following missing aesthetics: label
```

**Comment by yutannihilation** [comment]
In general, stat transformation provides only the aesthetics it's supposed to provide, and `label` is not included.

c.f. https://ggplot2.tidyverse.org/reference/geom_qq.html#computed-variables
