### ISSUE TITLE
all plots without labels and axis

### ISSUE THREAD

**Issue by Maraikep** [tidyverse/ggplot2#4225]
Hello,
First of all: Many, many thanks for this wonderful package. For quite a long time now I enjoy the vast number of options of beautiful visualizations! Thanks!
Lately, all axis and axis labels vanished from my plots. Even from older scripts that originally produced nice plots, the plot is there and the graphic is fine and looks normal, except that there are no axis and labels anymore. This is independent of using a boxplot, a scatter plot, a barplot, and so on. 
As I had no idea why and I suspected there might be any compatibility issues, I loaded only ggplot2. No success. Then, I updated R (now R 4.0.2) and updated all packages. The issue persisted. In a last attempt, I removed ggplot2 completely and installed it from the scratch (install.packages("ggplot2")). Now I am running ggplot2 3.3.2. I am still having the same issue. Even if I try to draw the axis and labels using theme(), they are not displayed. I am wondering, what is wrong?!
I even installed and reproduced everything, old scripts included, on my second laptop without any success.
Please find an easy code example for reproduction purposes below. I am attaching the figure, which is produced for me.
I very much appreciate any help. Thanks a thousands in advance!

```r
x <- 1:10
y <- 1:10
ggplot(data.frame(x,y), aes(x = x, y = y)) + geom_point()
ggplot(data.frame(x,y), aes(x = x, y = y)) + geom_point() + theme_bw()
ggplot(data.frame(x,y), aes(x = x, y = y)) + geom_point() + theme(axis.line = element_line(colour = "black")) 
```
![ggplot_issue](https://user-images.githubusercontent.com/65903556/95566463-dfcec280-0a21-11eb-8111-30b0e804a3bd.png)

**Comment by clauswilke** [comment]
It sounds like there's something broken with your local install. The code you use works (see below). Unfortunately the ggplot2 issue tracker is not the right forum for installation problems. You could try to ask for help at the RStudio Community (https://community.rstudio.com/).


    library(ggplot2)

    x <- 1:10
    y <- 1:10
    ggplot(data.frame(x,y), aes(x = x, y = y)) + geom_point()

![](https://i.imgur.com/FMkkqs4.png)

<sup>Created on 2020-10-09 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
