### ISSUE TITLE
geom_dotplot don't put dots at proper locations.

### ISSUE THREAD

**Issue by spz1st** [tidyverse/ggplot2#4226]
I'm not sure if I'm trying to do something not meant to, but suspect there may be a bug in the function.  Instead of describing the issue, I just post the script in its entirety so you can run it and see what I meant.  This script will create one pdf file (attached) with three pages.  The first one and third one have plots with dots placed at expected locations, but the second one has plots with dots placed incorrectly (at least not as expected).  The only difference between codes for the first page and codes for the second page is the value for x in aes(), x=dose vs. x=supp. I may have missed some options that should correct the problem, but I've searched around and found no solutions.  Thanks.
[violin.pdf](https://github.com/tidyverse/ggplot2/files/5357648/violin.pdf)

```
#!/usr/bin/env Rscript

library(ggplot2)

plotit <- function(p)
{
    p <- p +
      geom_violin(width=0.7, alpha=0.8, position=dodge) +
      geom_dotplot(binaxis='y', stackdir='center', dotsize=0.2) +
      geom_boxplot(width = 0.1, alpha = 0.2, color= "black", outlier.size=0.5, position=dodge) +
      stat_summary(fun=mean, colour='red', geom="point", size=2, position=dodge) +
      labs(fill="dose") +
      ylim(0, 40) +
      ggtitle('Tooth Growth') + theme(plot.title = element_text(hjust = 0.5)) +
      scale_fill_hue()+scale_color_hue()

    print(p)
}

d <- ToothGrowth
d$dose <- as.factor(d$dose)
dodge <- position_dodge(width=0.7)

file <- 'violin.pdf'
unlink(file)
pdf(file)

p <- ggplot(d, aes(x=dose, y=len, fill=factor(dose, levels=c('0.5', '1', '2'))))

plotit(p)

p <- ggplot(d, aes(x=supp, y=len, fill=factor(dose, levels=c('0.5', '1', '2'))))

plotit(p)

p <- ggplot(d, aes(x=supp, y=len, fill=factor(dose, levels=c('0.5', '1', '2')))) +
    geom_violin(width=0.7, alpha=0.8, position=dodge) +
    geom_jitter(alpha=0.4, size=0.7, color="red", position=dodge) +
    geom_boxplot(width = 0.1, alpha = 0.2, color= "black", outlier.size=0.5, position=dodge) +
    stat_summary(fun=mean, colour='red', geom="point", size=2, position=dodge) +
    labs(fill="dose") +
    ylim(0, 40) +
    ggtitle('Tooth Growth') + theme(plot.title = element_text(hjust = 0.5)) +
    scale_fill_hue()+scale_color_hue()

print(p)

dev.off()
```

**Comment by clauswilke** [comment]
See #3620, #1745.

Please always search open existing issues for similar problems before creating a new one.

**Comment by spz1st** [comment]
Sorry I did google around and missed it.  Thanks.
