### ISSUE TITLE
geom_label + summary: after_stat but before scale

### ISSUE THREAD

**Issue by gregleleu** [tidyverse/ggplot2#4235]
I'm using stat summary to compute statistics directly in the graph and show a label for it, for example showing the 90% percentile.
The computed value is passed to the label aesthetic using `after_stat` and that works fine when there are no axis transformations, but with a log10 transformation the label is in the right place but the text is after the transformation and but before the transformation. 
From the documentation I would expect after_stat to be before any scale transformation.

Works fine with regular scale:
```r
library(ggplot2)

ggplot(cars) +
  geom_step(aes(x = speed), stat = "ecdf") +
  geom_label(aes(x = speed, y = 0.9, label = after_stat(x)),
             orientation = "y", stat = "summary", fun = quantile, fun.args = list(probs = 0.9))
```
<img width="699" alt="image" src="https://user-images.githubusercontent.com/33321678/95924274-4b4bc380-0d85-11eb-9cab-fc303e634143.png">

Wrong text with log10 transformation:
```r
library(ggplot2)

ggplot(cars) +
  geom_step(aes(x = speed), stat = "ecdf") +
  geom_label(aes(x = speed, y = 0.9, label = after_stat(x)),
             orientation = "y", stat = "summary", fun = quantile, fun.args = list(probs = 0.9)) + 
  scale_x_log10()
```
<img width="694" alt="image" src="https://user-images.githubusercontent.com/33321678/95924311-5dc5fd00-0d85-11eb-81eb-ce513acde051.png">

**Comment by clauswilke** [comment]
Is this the same as #4155?

**Comment by gregleleu** [comment]
Looks like it, yes. I has searched at "label" and "after_stat"; didn't think the issue affected other mappings (it doesn't in my example for some reason)

**Comment by clauswilke** [comment]
Ok, I'll close this then in favor of the issue we have already open.
