### ISSUE TITLE
Add an option to pass a labeller function through `guide_legend()`

### ISSUE THREAD

**Issue by larmarange** [tidyverse/ggplot2#4238]
It would be great to have a way to pass a labeller function to the items of the legend.

For example: `guide_legend(label.format = scales::label_wrap(30))`

I know that the best would be to change the original levels before computing the plot. However, when using some high-level functions who produce computation and then generate a ggplot2 plot, it is not possible, customization having to be done afterwards.

**Comment by clauswilke** [comment]
Isn't this possible through the corresponding scales functions?

**Comment by larmarange** [comment]
You are right !!! Simply overriding the scales.
Sorry.
