### ISSUE TITLE
On an error message when using scales

### ISSUE THREAD

**Issue by iago-pssjd** [tidyverse/ggplot2#4241]
I was using `scale_x_date(labels=label_date("%d/%m/%Y"))` for a data of class `POSIXct` so I got the error:
```r
Error: Invalid input: date_trans works with objects of class Date only
```
Later I found [the way to solve the error](https://stackoverflow.com/questions/20736819/error-with-scale-x-labels-in-ggplot2). The problem is that the message induces to think that the error is due to `scales` function `label_date` and not due to `scale_x_date`. I am not sure of this being the place to post this issue or the `scales` github or other place.

Minimal example:
```r
last_month <- Sys.time() - 0:29
df <- data.frame(
  date = last_month,
  price = runif(30)
)
base <- ggplot(df, aes(date, price)) +
  geom_line()
base + scale_x_datetime(labels = label_date("%D")) # it works
base + scale_x_date(labels = label_date("%D")) # it does not work
Error: Invalid input: date_trans works with objects of class Date only
```

Thank you!

**Comment by clauswilke** [comment]
Closing this in favor of #4258.
