### ISSUE TITLE
Integer data might get non-integer breaks

### ISSUE THREAD

**Issue by msberends** [tidyverse/ggplot2#4245]
This is related to #3222. I agree with @thomasp85 that he said:
> _I think the fact that few users are aware of integer/numeric difference and whether their data is one or the other will make adding this a source of confusion..._

But for analyses with values that are really not divisible like the number of patients, plants or buildings, this is sometimes a problem (even if you set the column to be `integer`):

```r
df
#> # A tibble: 90 x 4
#>    age_group location group   n_patient
#>    <ord>     <chr>    <chr>       <int>
#>  1 0-17      A        Group 1         0
#>  2 0-17      A        Group 2         0
#>  3 0-17      M        Group 1         0
#>  4 0-17      M        Group 2         0
#>  5 0-17      M        Group 1         0
#>  6 0-17      M        Group 2         0
#>  7 0-17      N        Group 1         0
#>  8 0-17      N        Group 2         0
#>  9 0-17      O        Group 1         0
#> 10 0-17      O        Group 2         0

ggplot(df) + 
  geom_col(aes(x = age_group, y = n_patient, fill = group)) + 
  facet_wrap("location", scales = "free")
```

![image](https://user-images.githubusercontent.com/31037261/96688546-95ced080-1381-11eb-8ed0-d0bacb151af3.png)

As you can see, the `n_patient` column is of class `integer`, but still locations N and O have decimal breaks. In #3222 the question was to basically to let `waiver()` check if all values are equal to `floor(values)` in all cases, but I am wondering if `waiver()` could be edited so that if the data contains true integer values, the breaks will never be non-integer.

What do you think?

**Comment by clauswilke** [comment]
The correct solution to this problem is to write a breaks function that only generates integer breaks. Such a function would probably live in the scales package, so I suggest you file your feature request there.

**Comment by msberends** [comment]
I kindly disagree 🙂 

The breaks are now generated with the assumption that the underlying numbers are not all whole numbers. And that assumption is incorrect for a class integer, just as it is incorrect for a class Date. So I strongly believe that this is a design flaw and that a vector of integers should never generate breaks for another type of numbers (numeric, double).

**Comment by clauswilke** [comment]
What you're asking is, in effect, that ggplot should auto-detect whether a scale should be discrete numerical or continuous numerical. My perspective from the maintainer side is that this is fraught with error and will lead to numerous bug reports and headaches, for example when people plot discrete and continuous numbers on the same axis, when they think they have discrete data but use the default R numeric datatype, or when they for some reason have integer numbers but think of them as continuous.

Under my proposed solution, users need to spend 5 min. thinking about whether they want integer breaks or not, and then can simply write something like `breaks = breaks_integer()` and things work as expected.

In any case, before we can talk about auto-detecting whether to turn on a feature we need the feature to exist. So for sure, it needs to start with implementing an integer breaks function.

**Comment by msberends** [comment]
Thanks for your explanation. I do agree that probably some (most?) users would find it confusing to differentiate between numeric and integer values and its consequences in ggplot2. 

I still think it’s weird to plot decimals for an integer class in any case, but I also agree that your solution will suffice.
