### ISSUE TITLE
``

### ISSUE THREAD

**Issue by TimTeaFan** [tidyverse/ggplot2#4248]
Please briefly describe your problem and what output you expect. If you have a question, please don't use this form, but instead ask on the mailing list <https://groups.google.com/forum/#!forum/ggplot2> or stackoverflow <http://stackoverflow.com>.

Please include a minimal reprex. The goal of a reprex is to make it as easy as possible for me to recreate your problem so that I can fix it. If you've never heard of a reprex before, start by reading <https://www.tidyverse.org/help/#reprex>, and follow the advice further down the page. Do NOT include session info unless it's explicitly asked for, or you've used `reprex::reprex(..., si = TRUE)` to hide it away.  

Delete these instructions once you have read them.

---

Brief description of the problem

```r
# insert reprex here
```

**Comment by karawoo** [comment]
Hi @TimTeaFan, just to follow up with an explanation here: theme elements only inherit from higher-level elements if they're not explicitly set themselves. The particular theme you're using, `theme_grey()`, sets `axis.text.y.right` explicitly, which overrides `axis.text.y`. Therefore you must `axis.text.y.right` as you've seen.

**Comment by TimTeaFan** [comment]
Thank you very much for this explanation!
