### ISSUE TITLE
Should `position_identity()` get a new option to control the ordering of geoms?

### ISSUE THREAD

**Issue by zenggyu** [tidyverse/ggplot2#4249]
I was making a bar plot (with different fill colors) using `position_identity()`, and was wondering how to change the order of colored bars rendered on the plot. However, I couldn't find any parameters in `position_identity()` for the purpose. After some googling, it seems that the only way to change the order is to reorder the data set (see reprex below). Will it make sense to add an option to `position_identity()` to control the order so that I don't have to use `dplyr::arrange()`?

``` r
library(tibble)
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
library(ggplot2)

dat <- tibble(x = c("a", "a", "b", "b", "c", "c"),
              y = c(T, F, T, F, T, F),
              z = c(1363, 1500, 1255, 257, 1205, 164))

p1 <- dat %>%
  ggplot() +
  geom_col(aes(x, z, fill = y), position = position_identity())

print(p1)

p2 <- dat %>%
  arrange(y) %>% # note the difference that results from this step
  ggplot() +
  geom_col(aes(x, z, fill = y), position = position_identity())

print(p2)
```

<sup>Created on 2020-10-27 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by smouksassi** [comment]
Hi, to control the order as you wish, use factors with the order that you want as demoed below :

``` r
library(patchwork)
library(ggplot2)
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union

dat <- data.frame(x = c("a", "a", "a", "b", "c", "c"),
              y = c("cat3", "cat2","cat1", "cat2", "cat1", "cat3"),
              z = c(1363, 1500, 1255, 257, 1205, 164))

p1 <- dat %>%
  ggplot() +
  geom_col(aes(x, z, fill = y), position = position_identity())


dat$y <- factor(dat$y,levels=c("cat3","cat1","cat2"))
p2 <- dat %>%
  ggplot() +
  geom_col(aes(x, z, fill = y), position = position_identity())

dat$x <- factor(dat$x,levels=c("c","a","b"))
p3 <- dat %>%
  ggplot() +
  geom_col(aes(x, z, fill = y), position = position_identity())
p1+p2+p3
```

![](https://i.imgur.com/I07Q6Sd.png)

<sup>Created on 2020-10-27 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by zenggyu** [comment]
Sorry if I didn't make myself clear, but I think you missed the point. Your solution just changed the color of the bars, but not the order in which the bars are rendered on the plot.

Since I can't include a plot because of network restriction so let me just use your plot for illustration.

Note that in all of the three plots, the bars that represent "cat1" are plotted **above** those that represent "cat2". What would you do if you want to change the order so that the bars that represent "cat1" are plotted **below** those that represent "cat2"?

**Comment by smouksassi** [comment]
yes now I get you.  I think these kind of questions are to be asked on the Rstudio community:
https://community.rstudio.com/tag/ggplot2 
The only way to control the order of plotting within a layer is order the data itself:
https://stackoverflow.com/questions/15706281/controlling-order-of-points-in-ggplot2-in-r 

added transparency to realize the over plotting
``` r
library(ggplot2)
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
library(tibble)
#> Warning: package 'tibble' was built under R version 4.0.3
library(dplyr)
library(patchwork)

dat <- tibble(x = c("a", "a", "b", "b", "c", "c"),
              y = c(T, F, T, F, T, F),
              z = c(1363, 1500, 1255, 257, 1205, 164))

p1 <- dat %>%
  ggplot() +
  geom_col(aes(x, z, fill = y), position = position_identity(), alpha=0.5)


p2 <- dat %>%
  arrange(y) %>% # note the difference that results from this step
  ggplot() +
  geom_col(aes(x, z, fill = y), position = position_identity(), alpha=0.5)

p1 + p2
```

![](https://i.imgur.com/egWfa0y.png)

<sup>Created on 2020-10-27 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by yutannihilation** [comment]
> Will it make sense to add an option to `position_identity()` to control the order so that I don't have to use `dplyr::arrange()`?

I agree it might be nice if there's some option to control over this, but I don't feel it makes sense to do this with Position (in my understanding, its role is to adjust the positions if the object would be overlapped otherwise). Besides, as @smouksassi's example shows, you'll need to order the data or convert them to factors anyway, in order to work with ggplot2 comfortably. So, I don't think it's terribly bad to use `dplyr::arrange()`.

In general, if the data are highly likely to overlap, you should use other positions such as `position_dodge()`.
