### ISSUE TITLE
Geoms switch locations on dodged chart when color set in aes()

### ISSUE THREAD

**Issue by dhmontgomery** [tidyverse/ggplot2#4251]
So this is a weird and very specific bug that I've noticed for quite some time. 

The issue occurs when I create a bar chart using `geom_col(position = "dodge")`, create a second geom like `geom_text(..., position = position_dodge(width = .9)`, and in that second geom define a color or fill inside of `aes`.

As I said, very specific!

Some examples. Here's a simple chart with two dodged geoms that works exactly as intended:

```r
mtcars %>%
	group_by(cyl) %>%
	summarize(mpg = mean(mpg), hp = mean(hp)) %>%
	pivot_longer(-cyl) %>%
	ggplot(aes(x = as.character(cyl), y = value, fill = name)) +
	geom_col(position = "dodge") +
	geom_text(aes(label = name), position = position_dodge(width = .9), vjust = -0.1)
```

But if you add `color` to the aesthetics of the geom_text, the text switches horizontal locations across the dodge!

```r
mtcars %>%
	group_by(cyl) %>%
	summarize(mpg = mean(mpg), hp = mean(hp)) %>%
	pivot_longer(-cyl) %>%
	ggplot(aes(x = as.character(cyl), y = value, fill = name)) +
	geom_col(position = "dodge") +
	geom_text(aes(label = name,
				  color = case_when(value < 30 ~ "black", TRUE ~ "blue")), 
			  position = position_dodge(width = .9), vjust = -0.1) +
	scale_color_identity()
```

This does NOT hold true if you change other aesthetics in `aes()`, like `vjust`. Only `color` (and `fill`) that I've noticed. It's not specific to `geom_text()`, either — you can change it to `geom_point()` and the same thing happens, the dots switch sides.

I encounter this in my work semi-regularly, when I'm trying to combine direct labels with a complex graph. I can work around it, by switching to a faceted graph or applying direct annotations, but it'd be nice if this worked, or if I knew what I needed to do to prevent this from happening.

**Comment by smouksassi** [comment]
unless you control the order of your newly created color names ( which are alphabetical by default you need to do it yourself see below:

``` r
library(tidyverse)
#> Warning: package 'tibble' was built under R version 4.0.3
#> Warning: package 'tidyr' was built under R version 4.0.3
#> Warning: package 'readr' was built under R version 4.0.3
mtcars %>%
  group_by(cyl) %>%
  summarize(mpg = mean(mpg), hp = mean(hp)) %>%
  pivot_longer(-cyl) %>%
  ggplot(aes(x = as.character(cyl), y = value, fill = name))  +
  geom_label(aes(label = name,
                fill = name), 
            position = position_dodge(width = .9), vjust = -0.1)+
  geom_col(position = "dodge") +
  geom_text(aes(label = name,
                color = factor(case_when(value < 30 ~ "black", TRUE ~ "white"),
                               levels = c("white","black")
                               ) ), 
            position = position_dodge(width = .9), vjust = "inward") +
  scale_colour_identity()
#> `summarise()` ungrouping output (override with `.groups` argument)
```

![](https://i.imgur.com/7ZemKdz.png)

<sup>Created on 2020-10-30 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
