### ISSUE TITLE
how to plot the geom_point adding with density

### ISSUE THREAD

**Issue by honghh2018** [tidyverse/ggplot2#4252]
Hi @All,
    The correlation point adding density showing below,
![image](https://user-images.githubusercontent.com/41668708/97527616-b1bc1d00-19e6-11eb-80a4-5606b8b4a81f.png)
    I can not remove the background with the plot, and  the density showing weird tiny line on it.
    How can i remove the background and how to plot the picture like below,
    
   ![image](https://user-images.githubusercontent.com/41668708/97527779-1aa39500-19e7-11eb-8b02-363914829cd2.png)
    The code i post using draw above first plot showing below,
     commonTheme = list(labs(color="Density",fill="Density",
                        x="ScRNA-seq(UMI)",
                        y="Bulk mRNA-seq (FPKM)"),
                   theme_classic())
p<-ggplot(data=merge2_log, aes(x=ex_scrna, y=ex_bulk))+
  geom_point(colour = 'grey',size=0.5)+
  stat_density_2d(aes(alpha = ..density..),geom='tile',contour = F)+
  stat_cor(data=merge2_log, method = "pearson")+
  geom_smooth(data = merge2_log, aes(ex_scrna,ex_bulk),method = 'lm',formula = y~x,linetype=2,colour="red",se=F) +
  commonTheme
p

 Best,
 hanhuihong

**Comment by karawoo** [comment]
Hi @honghh2018, this type of question is a better fit for RStudio Community (https://community.rstudio.com/). I'd recommend asking there with a minimal reproducible example ([reprex](https://reprex.tidyverse.org/index.html)). We use the ggplot2 issue tracker for bug reports and feature requests.
