### ISSUE TITLE
[Feature Request] Add options "ggplot.ordinal.color" and "ggplot.ordinal.fill" scales defaults

### ISSUE THREAD

**Issue by dgkf** [tidyverse/ggplot2#4253]
`ggplot` exposes options for [setting default scales](https://github.com/tidyverse/ggplot2/blob/95ba60bd9c70cdcada44ad805728fff9b54596db/R/scale-colour.r#L43-L54), but but this mechanism of setting a default scales function [isn't available for ordinal scales](https://github.com/tidyverse/ggplot2/blob/2bc493e20556a40a4adb46a05e36f7d671c810d4/R/scale-viridis.r#L58-L66) (which is a direct alias for the viridis scales). 

When using [`thematic`](https://github.com/rstudio/thematic) to automatically set color schemes, this means that plots with ordinal color scales will always revert to a viridis color pallet, contrasting with other plots in the same theme. This has been raised in [thematic#59](https://github.com/rstudio/thematic/issues/59) and [thematic#62](https://github.com/rstudio/thematic/issues/62)

It would be wonderful if these ordinal scales got the same default color scales treatment so that they can be themed consistently without needing any uncouth `ggplot` namespace modifications to inject this behavior.

**Comment by yutannihilation** [comment]
Thanks, we are talking about adding this option on https://github.com/tidyverse/ggplot2/issues/4148#issuecomment-665733978. Could you join there if you have any comments?
