### ISSUE TITLE
Having trouble installing ggplot2

### ISSUE THREAD

**Issue by Savannankvm** [tidyverse/ggplot2#4255]
Hello!  I am currently unable to properly install ggplot2 on RStudio on my computer.  I've tried a number of 'fixes' suggested in similar threads, but I'm getting nowhere and I'd really appreciate some help, please.

As far as I know, I have other parts of tidyverse, just not ggplot2 specifically.

Here is my error message (plus additional details) when I try and install ggplot2:

* installing *source* package 'ggplot2' ...
** package 'ggplot2' successfully unpacked and MD5 sums checked
** R
** data
*** moving datasets to lazyload DB
** inst
** preparing package for lazy loading
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called 'pillar'
ERROR: lazy loading failed for package 'ggplot2'
* removing 'C:/Users/Savanna/Documents/R/win-library/3.4/ggplot2'
Warning in install.packages :
  running command '"C:/PROGRA~1/R/R-34~1.2/bin/x64/R" CMD INSTALL -l "C:\Users\Savanna\Documents\R\win-library\3.4" C:\Users\Savanna\AppData\Local\Temp\RtmpQv78Cn/downloaded_packages/ggplot2_3.3.2.tar.gz' had status 1
Warning in install.packages :
  installation of package ‘ggplot2’ had non-zero exit status

Many thanks, Savannankvm.

**Comment by yutannihilation** [comment]
Hi, this sort of question is a better fit for [RStudio Community](https://community.rstudio.com). Please ask there with the error message you get when installing pillar package (`there is no package called 'pillar'` seems the core of this problem). We use this issue tracker for bug reports and feature requests.
