### ISSUE TITLE
No US-alias for scale_colour_viridis_b()

### ISSUE THREAD

**Issue by mkiang** [tidyverse/ggplot2#4257]
Most (all?) `ggplot2` functions allow for both US and British spelling. For example, `scale_colour_viridis_c()` and `scale_colour_viridis_d()` both have US-aliases `scale_color_viridis_c()` and `scale_color_viridis_d()`, respectively. This is not true for `scale_colour_viridis_b()`. See screenshot. Using `ggplot2 3.3.2`.

```r
> ?scale_colour_viridis_b
> ?scale_color_viridis_b
No documentation for ‘scale_color_viridis_b’ in specified packages and libraries:
you could try ‘??scale_color_viridis_b’
```
<img width="402" alt="Screen Shot 2020-11-03 at 10 52 46 AM" src="https://user-images.githubusercontent.com/3435045/98028456-fc60df00-1dc2-11eb-9ec1-0e744c8cbffb.png">

**Comment by imagejan** [comment]
See https://github.com/tidyverse/ggplot2/pull/4048.

**Comment by mkiang** [comment]
Ah. Sorry. Searched the issues but not the PRs.
