### ISSUE TITLE
geom_polygon() is different on windows vs. linux

### ISSUE THREAD

**Issue by MartinMSPedersen** [tidyverse/ggplot2#4259]
While producing some generative art using R and ggplot2, I discovered a problem with geom_polygon().

---
When I run the code on Linux usingR 4.0.3 and ggplot2 version 3.3.2.9000:
[Linux version](https://20dage.dk/bug/linux.png)

When I run the same code on Windows also using R 4.0.3 and ggplot2 version 3.3.2.9000:
[Windows version](https://20dage.dk/bug/windows.png)

I expect the code to generate the same picture and I think the Windows version is the correct.

```r
library(tidyverse)
png("linux.png") 
#png("windows.png")
n <- 100
tibble(x = accumulate(1:n, ~.x+((0.98)^.y)*cos(.y*(2*pi/1.6)^1.04), .init=0), y = accumulate(1:n, ~.x+((0.98)^.y)*sin(.y*(2*pi/1.6)^1.04), .init=0)) %>% 
	   ggplot(aes(x,y)) + 
	   geom_polygon(fill = "black") + 
	   coord_equal() +
	   theme_void()
dev.off()
```

**Comment by clauswilke** [comment]
This is almost certainly a problem with the windows graphics device. Try `agg_png()` from the ragg library.

    library(tidyverse)
    library(ragg)

    agg_png("agg.png") 

    n <- 100
    tibble(x = accumulate(1:n, ~.x+((0.98)^.y)*cos(.y*(2*pi/1.6)^1.04), .init=0), y = accumulate(1:n, ~.x+((0.98)^.y)*sin(.y*(2*pi/1.6)^1.04), .init=0)) %>% 
      ggplot(aes(x,y)) + 
      geom_polygon(fill = "black") + 
      coord_equal() +
      theme_void()
    dev.off()
    #> quartz_off_screen 
    #>                 2

<sup>Created on 2020-11-04 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

File `agg.png`:

![agg](https://user-images.githubusercontent.com/4210929/98191466-dc264280-1ede-11eb-9400-63d84bafa90a.png)
