### ISSUE TITLE
Change the order of multiple legends also modify the colorbar

### ISSUE THREAD

**Issue by ShixiangWang** [tidyverse/ggplot2#4262]
```r
library(ggplot2)
df <- expand.grid(X1 = 1:10, X2 = 1:10)
df$value <- df$X1 * df$X2

p1 <- ggplot(df, aes(X1, X2)) + geom_tile(aes(fill = value))
p2 <- p1 + geom_point(aes(size = value))
p2
p2+guides(fill=guide_legend(order = 2),size=guide_legend(order=1))
```

![image](https://user-images.githubusercontent.com/25057508/98631580-b4a8fd00-2358-11eb-93f0-cba11fd0d4de.png)

I expect the colorbar below keep same as the plot above.

![image](https://user-images.githubusercontent.com/25057508/98631613-c25e8280-2358-11eb-8425-9f753287567f.png)

A related issue: https://github.com/tidyverse/ggplot2/issues/1353

**Comment by clauswilke** [comment]
That's because you changed both the order and the legend type.

    library(ggplot2)
    df <- expand.grid(X1 = 1:10, X2 = 1:10)
    df$value <- df$X1 * df$X2

    p1 <- ggplot(df, aes(X1, X2)) + geom_tile(aes(fill = value))
    p2 <- p1 + geom_point(aes(size = value))
    p2

![](https://i.imgur.com/dQn9kgg.png)

    p2+guides(fill=guide_colorbar(order = 2),size=guide_legend(order=1))

![](https://i.imgur.com/noqRPQK.png)

<sup>Created on 2020-11-09 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by ShixiangWang** [comment]
@clauswilke Thanks :)
