### ISSUE TITLE
geom_hex with stat='identity' is not drawing correctly

### ISSUE THREAD

**Issue by beerda** [tidyverse/ggplot2#4263]
Sometimes, geom_hex draws strange fragments under (or over) the figure:

```r
library(ggplot2)
d <- data.frame(y=rep(1:5, times=5),
                x=rep(1:5, each=5) + c(0.5, 0, 0.5, 0, 0.5),
                m='g')
d[7, 3] <- 'b'

g <- ggplot() +
    geom_hex(data=d,
             aes(x=x, y=y, fill=m),
             stat='identity') 
plot(g)
```
![2566da88-dd04-4421-9e54-394c735e6287](https://user-images.githubusercontent.com/26056018/98928829-8eab6600-24da-11eb-8125-475489467a61.png)

Interestingly, the behaviour is even worse if setting d[7,3] <- 'X':

```r
library(ggplot2)
d <- data.frame(y=rep(1:5, times=5),
                x=rep(1:5, each=5) + c(0.5, 0, 0.5, 0, 0.5),
                m='g')
d[7, 3] <- 'X'

g <- ggplot() +
    geom_hex(data=d,
             aes(x=x, y=y, fill=m),
             stat='identity') 
plot(g)
```

![7fffb004-8695-4fb8-a53c-04a542c46903](https://user-images.githubusercontent.com/26056018/98928826-8e12cf80-24da-11eb-82a3-b1bcaf3e9b36.png)

The correct behaviour is IMHO all cells cyan except the one, which should be red.

**Comment by yutannihilation** [comment]
I've never seen `geom_hex()` is used with `stat = "identity"`, so I don't know the expected behavior. But, it seems you need to specify a `group = <whatever static value>` to prevent the data from getting split by `m`.

``` r
library(ggplot2)
d <- data.frame(
  y = rep(1:5, times = 5),
  x = rep(1:5, each = 5) + c(0.5, 0, 0.5, 0, 0.5),
  m = "g"
)
d[7, 3] <- "b"


p <- ggplot(d, aes(x = x, y = y, fill = m)) +
  geom_point() +
  geom_hex(alpha = 0.3, stat = "identity")

p
```

![](https://i.imgur.com/NENogry.png)

``` r
p + facet_wrap(~m)
```

![](https://i.imgur.com/dqhaSBi.png)

``` r
ggplot(d, aes(x = x, y = y, fill = m, group = 1)) +
  geom_point() +
  geom_hex(alpha = 0.3, stat = "identity")
```

![](https://i.imgur.com/f9XS7Ud.png)

<sup>Created on 2020-11-12 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by beerda** [comment]
The expected behaviour of geom_hex(stat="identity") is IMHO not to perform any aggregations on data but simply draw the given value in the hex (e.g. as a fill color) to produce a raster image with hexagonal "pixels", similarly as geom_raster() produces raster with rectangular "pixels". It seems that specifying the group argument solves the problem, thank you.
