### ISSUE TITLE
curves produced with geom_line and geom_path breaks after the 100th point on Mac OS

### ISSUE THREAD

**Issue by maximiliense** [tidyverse/ggplot2#4270]
When plotting a curve with geom_line or geom_path, the line breaks between point 100 and 101. The breaks seems to be placed elsewhere when the plot is exported in PDF. The problem seems to be only present on Mac OS and not linux nor windows. The break becomes visible when size is increased and alpha decreased.

Mac OS 11, R 4.0.2, ggplot 3.3.2 === DOES NOT WORK !
Mac OS 10.14.6, R 3.6.2, ggplot 3.3.2 === DOES NOT WORK !
Windows Server 2019 , R 3.6.3, ggplot 3.3.2 === WORKS !
Ubuntu 20.04 , R 3.6.3, ggplot 3.2.1 === WORKS !

```r
library(ggplot2)
# example of code but it breaks with all tested curves
x=head(seq(0, 3*pi, 0.02), 101)
data = data.frame(x=x, y=sin(20*x))
ggplot(data=data, mapping=aes(x=x, y=y)) +
  geom_path(lwd=4, alpha=0.5)
# check the curve at around x=2
```

![](https://i.imgur.com/WljjsOW.png)
```

**Comment by karawoo** [comment]
I think this is an issue with the graphics device. Switching to ragg works on my mac:

``` r
library(ggplot2)
library(ragg)

agg_png("agg.png") 

x=head(seq(0, 3*pi, 0.02), 101)
data = data.frame(x=x, y=sin(20*x))
ggplot(data=data, mapping=aes(x=x, y=y)) +
  geom_path(lwd=4, alpha=0.5)

dev.off()
#> quartz_off_screen 
#>                 2
```

<sup>Created on 2020-11-19 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

![agg](https://user-images.githubusercontent.com/4452678/99711820-194e1100-2a57-11eb-977a-8a6de0dca7d4.png)

**Comment by maximiliense** [comment]
Thanks, that is indeed the problem and I can reproduce the bug with "plot" only !
