### ISSUE TITLE
user-defined transformation results in "NAs not allowed" error

### ISSUE THREAD

**Issue by BertrandSim** [tidyverse/ggplot2#4273]
The article mentioned in [this link](https://rpubs.com/huanfaChen/squash_remove_y_axix_ggplot) describes how to squash a part of a (positional) axis with a user-defined transformation. 

In it, one uses `scales::trans_new` with appropriate `transform` and `inverse` arguments to do so.

However, running the code results in 
```
# Error in x[isq] <- from + (x[isq] - from) * factor :
#   NAs are not allowed in subscripted assignments
```

The article contains output without errors, thus it may have worked in an older version.

Here is the full code

```r
library(ggplot2)
library(scales)

dat <- data.frame(group=rep(c('A', 'B', 'C', 'D'), each = 10), 
                 value=c(rnorm(10), rnorm(10)+100)
                 )

squash_axis <- function(from, to, factor) { 
    # A transformation function that squashes the range of [from, to] by factor on a given axis 

    # Args:
    #   from: left end of the axis
    #   to: right end of the axis
    #   factor: the compression factor of the range [from, to]
    #
    # Returns:
    #   A transformation called "squash_axis", which is capsulated by trans_new() function

  trans <- function(x) {    
      # get indices for the relevant regions
      isq <- x > from & x < to
      ito <- x >= to

      # apply transformation
      x[isq] <- from + (x[isq] - from)/factor
      x[ito] <- from + (to - from)/factor + (x[ito] - to)

      return(x)
  }

  inv <- function(x) {

      # get indices for the relevant regions
      isq <- x > from & x < from + (to - from)/factor
      ito <- x >= from + (to - from)/factor

      # apply transformation
      x[isq] <- from + (x[isq] - from) * factor
      x[ito] <- to + (x[ito] - (from + (to - from)/factor))

      return(x)
  }

# return the transformation
  return(trans_new("squash_axis", trans, inv))
}

ggplot(dat,aes(x=group,y=value)) +
  geom_point() +
  scale_y_continuous(trans = squash_axis(5, 95, 10))

```

**Comment by smouksassi** [comment]
looking at this post might help you adapt the code: http://freerangestats.info/blog/2020/04/06/crazy-fox-y-axis

**Comment by teunbrand** [comment]
I think that you might want to guard against `NA`s in your code at the assignment of `isq` and `ito` by adding `& !is.na(x)` to the logical operations. I can imagine some `NA`s being passed to the transformation function when scale limits aren't defined by the user and are taken as the natural limits of the data, in which case they would be `c(NA, NA)`. A logical operation on a `NA` is still `NA`, so that is how the indices end up with invalid subsetting indices. I would propose the following modifications:

```
squash_axis <- function(from, to, factor) { 
  # A transformation function that squashes the range of [from, to] by factor on a given axis 
  
  # Args:
  #   from: left end of the axis
  #   to: right end of the axis
  #   factor: the compression factor of the range [from, to]
  #
  # Returns:
  #   A transformation called "squash_axis", which is capsulated by trans_new() function
  
  trans <- function(x) { 

    # get indices for the relevant regions
    isq <- x > from & x < to & !is.na(x)
    ito <- x >= to & !is.na(x)
    
    # apply transformation
    x[isq] <- from + (x[isq] - from)/factor
    x[ito] <- from + (to - from)/factor + (x[ito] - to)
    
    return(x)
  }
  
  inv <- function(x) {
    
    # get indices for the relevant regions
    isq <- x > from & x < from + (to - from)/factor & !is.na(x)
    ito <- x >= from + (to - from)/factor & !is.na(x)
    
    # apply transformation
    x[isq] <- from + (x[isq] - from) * factor
    x[ito] <- to + (x[ito] - (from + (to - from)/factor))
    
    return(x)
  }
  
  # return the transformation
  return(trans_new("squash_axis", trans, inv))
}
```

**Comment by BertrandSim** [comment]
@teunbrand Thanks! The suggested additions of `!is.na(x)` works well.

However, I still have two problems.

The first follows from your comment:
>  I can imagine some NAs being passed to the transformation function when scale limits aren't defined by the user and are taken as the natural limits of the data, in which case they would be c(NA, NA)

I manually specified the limits, and used the original transformation (the transformation without `!is.na(x)` additions), but the same error still results:

```r
ggplot(dat,aes(x=group,y=value)) +
  geom_point() +
  scale_y_continuous(trans = squash_axis(5, 95, 10), limits=c(-5, 105))
# Error in x[isq] <- from + (x[isq] - from) * factor :
#   NAs are not allowed in subscripted assignments
```

Perhaps there are still NAs being passed around, even with user-specified limits.

The second is that the code I used was taken directly from [here](https://rpubs.com/huanfaChen/squash_remove_y_axix_ggplot) and [here](https://stackoverflow.com/a/47236348). They used to run without errors, (perhaps in an earlier version,) but not anymore.

**Comment by thomasp85** [comment]
We do not guarantee no breaking changes during the development of ggplot2, and especially we are not checking new releases against code stubs on SO or elsewhere. It is very likely that some internals have changed which breaks the example and you now need to guard against NA's
