### ISSUE TITLE
Relicensing ggplot2 (wrap up)

### ISSUE THREAD

**Issue by hadley** [tidyverse/ggplot2#4281]
We are systematically re-licensing tidyverse and r-lib packages to use the MIT license, to make our package licenses as clear and permissive as possible. To do so, we need the approval of all copyright holders, which I have found by reviewing contributions from all all non-RStudio [contributors](https://github.com/tidyverse/ggplot2/graphs/contributors). 
​
Due to the maximum number of users who can be tagged in a post on GitHub, there were three issues (#4231, #4232, #4233) used to track re-licensing for ggplot2. This issue combines the remaining contributors who have not yet responded.

@dkahle, @JoFrhwld, @jonathan-g, @kelseymoty, @lselzer, @noamross, @pkq, @slowkow, @sowla, @steveharoz,  @tdmcarthur, @thiyangt, would you permit us to re-license ggplot2 with the MIT license? If so, please comment "I agree" below.
​
* [x] [@dkahle](https://github.com/tidyverse/ggplot2/commits?author=dkahle)  
* [x] [@JoFrhwld](https://github.com/tidyverse/ggplot2/commits?author=JoFrhwld)  
* [x] [@jonathan-g](https://github.com/tidyverse/ggplot2/commits?author=jonathan-g)  
* [x] [@kelseymoty](https://github.com/tidyverse/ggplot2/commits?author=kelseymoty)  
* [x] [@lselzer](https://github.com/tidyverse/ggplot2/commits?author=lselzer)  
* [x] [@noamross](https://github.com/tidyverse/ggplot2/commits?author=noamross)  
* [x] [@pkq](https://github.com/tidyverse/ggplot2/commits?author=pkq)  
* [x] [@slowkow](https://github.com/tidyverse/ggplot2/commits?author=slowkow)  
* [x] [@sowla](https://github.com/tidyverse/ggplot2/commits?author=sowla)  
* [x] [@steveharoz](https://github.com/tidyverse/ggplot2/commits?author=steveharoz)  
* [ ] [@tdmcarthur](https://github.com/tidyverse/ggplot2/commits?author=tdmcarthur)  
* [x] [@thiyangt](https://github.com/tidyverse/ggplot2/commits?author=thiyangt)
* [x] [@mdlama](https://github.com/tidyverse/ggplot2/commits?author=mdlama)
* [x] [@llrs](https://github.com/tidyverse/ggplot2/commits?author=llrs)

**Comment by steveharoz** [comment]
Yes, I agree.

**Comment by JoFrhwld** [comment]
I agree!

**Comment by pkq** [comment]
I agree!

**Comment by dkahle** [comment]
I agree.

**Comment by kelseymoty** [comment]
Yes, I agree

**Comment by thiyangt** [comment]
Yes, I agree

**Comment by jonathan-g** [comment]
I agree

**Comment by lselzer** [comment]
I agree.

**Comment by noamross** [comment]
I agree

**Comment by sowla** [comment]
I agree

**Comment by thiyangt** [comment]
Yes I agree

**Comment by mdlama** [comment]
I agree!

**Comment by hadley** [comment]
@slowkow approved via email.

**Comment by hadley** [comment]
We have made a good-faith attempt to get consent from all contributor to the package under the previous license. This has included reviewing contributions to the package for non-trivial changes, seeking agreement to re-license with GitHub issues, sending a reminding after two weeks, and reaching out by e-mail (where possible).

Unfortunately, we have not received a response from @tdmcarthur. We have carefully reviewed their contributions. Given that the contributions are relatively small, and no one has objected to re-licensing across all tidyverse and r-lib repos, we are going to move ahead with the re-licensing. Of course, if we later discover that contributors are not happy with the re-licensing, we'll re-implement their changes.

**Comment by llrs** [comment]
I agree (PR #4215 )
