### ISSUE TITLE
remove_missings(..., finite = TRUE) removes everything if there is a character column

### ISSUE THREAD

**Issue by jarauh** [tidyverse/ggplot2#4284]
In base-R, character values are not "finite" (i.e. `is.finite("a")` is `FALSE`).  Therefore, if `remove_missings()` with `finite = TRUE` encounters a character column, it throws away everything. Thus, the first of the following two lines raises a warning and returns an empty data.frame, while the second line preserves the input data.frame:
```r
remove_missing(data.frame(foo = "bar", stringsAsFactors = FALSE), finite = TRUE)
remove_missing(data.frame(foo = "bar", stringsAsFactors = TRUE), finite = TRUE)
```

For me, this led to the following problem that I found extremely difficult to debug: I had a custom `stat` with `required_aes = c("x", "colour")`.  If the colour-aesthetic was mapped to a factor column, everything worked as expected - non-NA-values of factor variables are finite.  If the colour-aesthetic was mapped to a character column, the layer was dropped.

Minimal example:
```r
StatXMean <- ggplot2::ggproto(
  "StatXMean", Stat,
  compute_group = function(data, scales, params, na.rm = FALSE) {
    dplyr::summarize(dplyr::group_by(data, colour),
                     xintercept = mean(x, na.rm = TRUE))
  },  required_aes = c("x", "colour")
)

stat_x_mean <- function(mapping = NULL, data = NULL, geom = "vline",
                        position = "identity", na.rm = FALSE, show.legend = NA,
                        inherit.aes = TRUE, ...) {
  ggplot2::layer(
    stat = StatXMean, data = data, mapping = mapping, geom = geom,
    position = position, show.legend = show.legend, inherit.aes = inherit.aes,
    params = list(na.rm = na.rm, ...),
  )
}

ggplot(mpg, aes(displ, hwy, colour = drv)) +
  geom_point() + stat_x_mean()

ggplot(mpg, aes(displ, hwy, colour = as.factor(drv))) +
  geom_point() + stat_x_mean()
```

**Comment by teunbrand** [comment]
I too had this problem for the "label" aesthetic. I ended up with a [workaround](https://github.com/teunbrand/ggh4x/blob/0edf54804d849fead73a0d508abbbe7bf29cb510/R/stat_rle.R#L170), wrapping the column in a vctrs-class with alternative `is.finite()` methods, but it isn't pretty. There was mention of an `is_finite()` generic to handle special cases here: https://github.com/tidyverse/ggplot2/issues/4189#issuecomment-706634749.
