### ISSUE TITLE
fill and colour legends do not automatically merge in legend when two separate data sources are used

### ISSUE THREAD

**Issue by japhir** [tidyverse/ggplot2#4290]
When a plot is created from two separate data sources, the fill and colour legends do not automatically converge into one legend!

``` r
library(tidyverse)

dat <- tibble(x = 1:10, y = 11:20, z = rnorm(10))
dat2 <- dat %>% mutate(z = rnorm(10, z, .01))

ggplot(dat, aes(x = x, y = y, colour = z)) +
  geom_point() +
  geom_raster(aes(fill = z), data = dat2)
```

![](https://i.imgur.com/C9tH25c.png)

<sup>Created on 2020-12-08 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

My desired outcome would be that they do merge into one legend, as happens when you don't provide a non-identical dat in the geom_raster data argument.

**Comment by karawoo** [comment]
In your plot, fill and color are two separate scales that correspond to different variables and different data values. You can see the same behavior with a single dataset:

``` r
library("tidyverse")
set.seed(2021)

dat <- tibble(x = 1:10, y = 11:20, z = rnorm(10, mean = 1)) %>%
  mutate(z2 = -z)

ggplot(dat, aes(x = x, y = y, colour = z, fill = z2)) +
  geom_raster() +
  geom_point()
```

![](https://i.imgur.com/2bwMinx.png)

This is usually the desired behavior if you're basing color and fill on different variables. But you can also choose to combine them. This would work for your two data frames too:

``` r
ggplot(dat, aes(x = x, y = y, colour = z, fill = z2)) +
  geom_raster() +
  geom_point() +
  scale_colour_continuous(
    guide = guide_colourbar(title = "z"),
    aesthetics = c("colour", "fill")
  )
```

![](https://i.imgur.com/lOdFSp4.png)

<sup>Created on 2020-12-30 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>
FYI, in the future this type of question would be a better fit for [RStudio Community](https://community.rstudio.com/).

**Comment by japhir** [comment]
Thank you for helping me understand the issue. I thought it was a bug in the software, as the normal way of making shared legends is to simply give them the same name. That's why I didn't ask the question there. Cheers! :)
