### ISSUE TITLE
Default scales for non-standad computed aes. 

### ISSUE THREAD

**Issue by eliocamp** [tidyverse/ggplot2#4291]
metR's geom_vector/geom_arrow can draw arrows based either on dx and dy or magnitude and angle. If the user supplies dx and dy, then mag is a computed aesthetic.  The package also has a `scale_mag_continuous()` with it's own guide. ggplot2 adds the relevant scale if the mag aesthetic is supplied by the user, but not if it's computed by the stat:

``` r
library(metR) 
library(ggplot2)
data(seals)
ggplot(seals, aes(long, lat)) +
    geom_vector(aes(mag = sqrt(delta_long^2 + delta_lat^2), angle = atan2(delta_lat, delta_long)*180/pi)) 
```

![](https://i.imgur.com/DBfQE24.png)

``` r
   
ggplot(seals, aes(long, lat)) +
    geom_vector(aes(dx = delta_long, dy = delta_lat))
```

![](https://i.imgur.com/hXXu7a4.png)

<sup>Created on 2020-12-08 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

What should I do so that scale_mag_continuous() is added automatically even when the mag aesthetic is computed?

**Comment by thomasp85** [comment]
I don't think that is possible currently 😔

Maybe the best would be to provide a simple helper function, e.g. `magnitude <- function(dx, dy) sqrt(dx^2 + dy^2)` and remove that calculation from the stat. If you do that then the last example would become:

```r
ggplot(seals, aes(long, lat)) +
    geom_vector(aes(mag = magnitude(delta_long, delta_lat)))
```

and everything should work...

That being said I understand your request but I fear it will be long before we can support it (if at all)

**Comment by eliocamp** [comment]
Oh, ok. That's a bummer. I'll see what I can do, then. Thanks!
