### ISSUE TITLE
Use vdiffr conditionally

### ISSUE THREAD

**Issue by yutannihilation** [tidyverse/ggplot2#4293]
I also got this email as I'm the maintainer of a package that uses vdiffr. It says we need to fix this until 2021-01-12. On master, the use of vdiffr is already made conditional by #4192, so it's just patching this commit to the released version.

> Suggested packages should be used conditionally: see §1.1.3.1 of
'Writing R Extensions'.  Some of the requirements of vdiffr are hard to
install on a platform without X11 such as M1 Macs: see the logs at
https://www.stats.ox.ac.uk/pub/bdr/M1mac/.

> In some cases there are other suggested packages not used conditionally:
you can check all of them by setting environment variable
`_R_CHECK_DEPENDS_ONLY_=true`  -- see
https://cran.r-project.org/doc/manuals/r-devel/R-ints.html#Tools .

> Please correct ASAP and before 2021-01-12 to safely retain the package
on CRAN.

@thomasp85 @hadley 
Are you already planning a patch release for this? Please let me know if there's anything I can help.

**Comment by hadley** [comment]
@thomasp85 is out sick for the next few days, but we'll make this a priority when he's back.

**Comment by yutannihilation** [comment]
Oh, take care. I see. We have 1 month and this is easy to fix, I don't worry so much.

**Comment by yutannihilation** [comment]
It seems we also need to tweak some tests to address the change of `all.equal()` on R-devel.

https://github.com/tidyverse/ggplot2/pull/4294
