### ISSUE TITLE
req: delay "unknown aesthetic" warnings until plot

### ISSUE THREAD

**Issue by r2evans** [tidyverse/ggplot2#4295]
`ggplot2` extensions may introduce new aesthetics to the grammar. One such topic I'm considering is the breakout of `color` to support `hue`, `saturation`, `lightness` (for various reasons, not just for "two color scales" as supported by several extension packages).

If I start building a grob and include the aesthetic before it is properly handled by any custom extension function:

```lang-r
gg <- ggplot(mtcars, aes(x = disp, y = hp)) +
  geom_path(aes(lightness = hp))
# Warning: Ignoring unknown aesthetics: lightness
```

It is obvious that I can suppress the warnings individually, but if this is going into a package, I'd rather not suggest the users must do that every time they want the extension. The premise of the warning is correct, but I suggest that the timing of it is not.

Is it feasible to delay the unk-aesthetic warning until the plot rendering? That way, iteratively-built grobs don't warn about missing aesthetics until all processing has been completed?

**Comment by clauswilke** [comment]
I think you need to provide a fully worked minimal example demonstrating how you're planning to have `geom_path()` deal with an aesthetic it doesn't know. Normally, aesthetics and geoms go together. Each geom has a list of aesthetics it knows.

**Comment by r2evans** [comment]
I'll confess that I don't know how to write the extension yet. I'm hoping to adapt something like `ggnewscale` or your `relayer` extensions into this use, though the inner details are yet-unrealized in my head.

My HSL thought is that the colors used by other geoms and layers could be altered by HSL scales. This may not be possible. I do recognize that `geom_path` (and other geoms) don't know about `aes(lightness=.)`, I was hoping to combine relayering or newscaling to adjust (behind-the-scenes) the aesthetics that the geoms *do* know.

The HSL details aside, is there a way to delay the warning until later?

---

Do you think it's better to ask for an augmented color mapping? Perhaps I should adapt (or submit new) my request to be:

> In addition to `aes(color=disp)`, also allow `aes(color=hsl_helper(hue=gear, lightness=disp))`. There is precedence to multi-dispatch arguments and helper functions (e.g., `expand=` and `expansion()`)

(Ultimately, this is what I'm trying to effect.)

**Comment by clauswilke** [comment]
I'm going to close this issue. You're welcome to build the extension you envision, but you'll have to study existing extension packages to figure out a path to get this done.

**Comment by r2evans** [comment]
My question wasn't about how to build the extension, my question was about when warnings are triggered. Are the two topics to intertwined?

**Comment by yutannihilation** [comment]
> my question was about when warnings are triggered

I think we understand your question, and it's just your example is not convincing enough to change the existing mechanism at the risk of potential breakage of existing extensions. You can tweak `GeomPath` (or create a new subclass of it) to accept the non-standard mappings you want and demonstrate how you would success to build your extension in the world where `GeomPath` doesn't reject these, so that we can see how it matters to bypass the validation of the mappings on layer creation.

I roughly feel this isn't the main difficulty to prevent you from building the new extension (I mean, tweaking the mechanism of Scale is not very easy), but feel free to file a new issue when you figure out the problem. The idea sounds interesting.

**Comment by smouksassi** [comment]
Hi you will need to define a new geom that understands the new aesthetic with possibly a new stat that is used as the default stat. You cannot make the default geom path understand new aesthetic unless you override it in you extension but I think better to have a new name e.g. geom_path_hsl that has extra aes defined and then you take care of how these end up being mapped to the color good luck with your efforts !
