### ISSUE TITLE
tag position inside plot borders

### ISSUE THREAD

**Issue by Aariq** [tidyverse/ggplot2#4297]
Some peer-reviewed journals (e.g. Oecologia) require figure panel labels to be _inside_ of plot borders (although they seem to enforce these requirements inconsistently).  It would be nice if there were an option like `theme(plot.tag.position = "topleftinner")` to place a label at the upper left corner of the inside of plot borders.  Currently, I think I have to kludge this by tweaking `theme(plot.tag = element_text(vjust = , hjust = )`, but it's inconsistent, so I have to do this tweaking for every panel individually.  Maybe there's an easier way that I don't know about?

Related to: https://github.com/thomasp85/patchwork/issues/222

``` r
library(ggplot2)
p1 <- ggplot(mtcars) + geom_point(aes(mpg, disp)) + labs(tag = "a)")
p1 + theme(plot.tag.position = c(0,1),
           plot.tag = element_text(vjust = 1.5, hjust = -2.85))
```

![](https://i.imgur.com/qWKrEqC.png)

``` r
# left of "a" just touching plot border

p3 <- ggplot(mtcars) + geom_smooth(aes(disp, qsec)) + labs(tag = "b)")
p3 + theme(plot.tag.position = c(0,1),
           plot.tag = element_text(vjust = 1.5, hjust = -2.85))
#> `geom_smooth()` using method = 'loess' and formula 'y ~ x'
```

![](https://i.imgur.com/jZHfEyH.png)

``` r
# "b)" is slightly further in with same theme()
```

<sup>Created on 2020-12-15 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by teunbrand** [comment]
If you wrap a text annotation, it's not that cumbersome to achieve similar effects. The `-Inf` and `Inf` positions place it in the corner.

``` r
library(ggplot2)

place_label <- function(label, size = 5, ...) {
  annotate("text", label = label, x = -Inf, y = Inf, 
           hjust = 0, vjust = 1, size = size, ...)
}

p1 <- ggplot(mtcars) + geom_point(aes(mpg, disp))
p1 + place_label("a)")
```

![](https://i.imgur.com/RQhBsrK.png)

<sup>Created on 2021-01-09 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by Aariq** [comment]
Wow, thank you!  I had no clue you could pass `Inf` as a position like that.

**Comment by eliocamp** [comment]
I also came into this issue and made a package: [tagger](https://github.com/eliocamp/tagger). It's not perfect, but it might be useful!

```r
library(tagger)
library(ggplot2)

ggplot(mtcars, aes(hp, mpg)) +
   geom_point() +
   facet_grid(cyl ~ vs) +
   tag_facets()
```

![image](https://user-images.githubusercontent.com/8617595/104364718-c42df900-54f5-11eb-9578-9762540dc37b.png)

**Comment by thomasp85** [comment]
I think the main benefit of having it as a proper part of the tag element is that it will allow patchwork to use the position for auto tagging

**Comment by thomasp85** [comment]
I think adding a setting such as `plot.tag.position` would be nicely aligned with how positioning of titles currently work
