### ISSUE TITLE
Repeated value shown in y axis ticks with geom_smooth

### ISSUE THREAD

**Issue by hughjonesd** [tidyverse/ggplot2#4300]
---

I ran a graph and got an unusual error: the y axis tick marks were labeled 1.8, 1.8 and 1.8.

```r
tmp <- data.frame(foo = rnorm(10000))
tmp$bar <- 1.8 -0.005*tmp$foo^2 + rnorm(10000)/5
ggplot(tmp, aes(foo, bar)) + geom_smooth(formula = y ~ x)
```

![image](https://user-images.githubusercontent.com/5818871/102617186-afe22080-4130-11eb-8b3a-df8330a7237c.png)

Package version: ggplot2 3.3.2; R 4.0.2; using Rstudio.

**Comment by karawoo** [comment]
Have you customized the number of significant digits R prints in your .Rprofile or similar? The axis labels look fine to me unless I set `options(digits = 2)`:

``` r
library("ggplot2")

set.seed(15)
tmp <- data.frame(foo = rnorm(10000))
tmp$bar <- 1.8 -0.005*tmp$foo^2 + rnorm(10000)/5
ggplot(tmp, aes(foo, bar)) + geom_smooth(formula = y ~ x)
#> `geom_smooth()` using method = 'gam'
```

![](https://i.imgur.com/HcOSIn4.png)

``` r

options(digits = 2)
ggplot(tmp, aes(foo, bar)) + geom_smooth(formula = y ~ x)
#> `geom_smooth()` using method = 'gam'
```

![](https://i.imgur.com/tE8X6uc.png)

<sup>Created on 2020-12-18 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

**Comment by hughjonesd** [comment]
Yup, that's gotta be it.
