### ISSUE TITLE
coord_flip should support something other than axis-mirroring

### ISSUE THREAD

**Issue by arencambre** [tidyverse/ggplot2#4301]
`coord_flip()` causes axes to be mirrored across a diagonal that intersects (0,0).

This is undesirable behavior in a lot of cases. An example is where the original x axis was a categorical variable whose left-to-right order was meaningful. When we do `coord_flip()`, the new y axis--the former x axis--would need to reflect the old x-axis's left-to-right order in a top-to-bottom order to maintain the same meaning. Instead, its default is bottom-to-top.

It would be helpful if an argument was present that permitted the new y axis to maintain an expected order, which means its top-to-bottom order is the same as the original x axis's left-to-right order.

Reproduceable example:

Note the order of the x-axis:
```
ggplot(mpg, aes(x = class)) + 
  geom_bar()
```

Now note the order of the y-axis appears to be flipped:
```
ggplot(mpg, aes(x = class)) + 
  geom_bar() + coord_flip()
```

A Google search on this issue shows tons of hacky workarounds.

**Comment by clauswilke** [comment]
What are the hacky workarounds? Maybe people don't know how to approach this from the right angle? When you're using a categorical scale, you'll almost always have to make sure the order is correct anyways. It's rare that alphabetic order is appropriate, and if you want it alphabetic but the other way round then all you need is a simple `fct_rev()` call. Also, we generally now try to avoid `coord_flip()` since it makes it more difficult to reason about the plot.

    library(ggplot2)
    library(forcats)

    ggplot(mpg, aes(x = class)) + 
      geom_bar()

![](https://i.imgur.com/Zac3Zza.png)


    ggplot(mpg, aes(y = class)) + 
      geom_bar()

![](https://i.imgur.com/YIYcPRb.png)


    ggplot(mpg, aes(y = fct_rev(class))) + 
      geom_bar()

![](https://i.imgur.com/vyhb4Hg.png)


    ggplot(mpg, aes(y = fct_infreq(class))) + 
      geom_bar()

![](https://i.imgur.com/D2xXdhf.png)


    ggplot(mpg, aes(y = fct_rev(fct_infreq(class)))) + 
      geom_bar()

![](https://i.imgur.com/8ufgPTL.png)

<sup>Created on 2020-12-23 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by arencambre** [comment]
Thank you for the response. The hacky workarounds involve conversion to and/or manipulation of factors. Search google on `coord_flip reverse order` for lots of examples of this challenge, going back years.

Flipping the coordinates could be a mirror image, and it could also be a lift and shift (e.g., lift the x axis, rotate 90 degrees clockwise, and plop it down on the y axis). The latter is unsupported by `coord_flip()` without the workarounds.

Alpha sort is a red herring. The bigger point is "my x axis was sorted as I wanted, and when I started to use `coord_flip()`, its order got reversed when it was put on the y axis".

This could easily be solved by an argument on the `coord_flip` function.

**Comment by karawoo** [comment]
The flipped axis keeps the same order relative to the origin, so I think the default behavior makes sense. And as @clauswilke said, we generally avoid `coord_flip()` now -- the introduction of bidirectional geoms/stats has made it easier to create plots with the desired aesthetics without needing to flip the coordinate system. So I'm not sure it makes sense to add more options to `coord_flip()`.

That said, if you're attached to using `coord_flip()` and don't want to set the order with `fct_*()` functions in the call to `aes()` as Claus suggested, there's still the following which I don't think is that hacky. 

``` r
library("ggplot2")
ggplot(mpg, aes(x = class)) + 
  geom_bar() +
  coord_flip() +
  scale_x_discrete(limits = rev)
```

![](https://i.imgur.com/9zeeYWC.png)

<sup>Created on 2020-12-23 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

**Comment by arencambre** [comment]
@karawoo thank you for your response.

Here's my thoughts:

- `coord_flip()` is the universal solution that Google searches dredge up to this problem. If that function is no longer preferred or is being misused, documentation needs revision to let us know. Currently, there is nothing in `coord_flip()`'s documentation that would cause a reasonable person to believe it is not the universal solution that Google searches make it out to be.
- Searching for the "bidirectional geoms/stats" functionality you mention dredges up https://ggplot2.tidyverse.org/articles/extending-ggplot2.html#geoms-and-stats-with-multiple-orientation-1. Its first paragraph makes it sound like the `orientation` parameter of the layer is what we're supposed to use? If so, removing `coord_flip()` and adding `orientation = "y"` to a `geom_col()` creates a bizarre plot.
- My data was fine "as is". This is an example of where the software is making an incorrect assumption about my data. When I have a categorical axis, I do not want a coordinate flip to mirror-image that categorical axis along the diagonal. My left-to-right ordering on the x-axis was meaningful, and I want that maintained in a top-to-bottom order on the y-axis. Because my data was fine, it is unintuitive that I need to fix or clarify my data. The most intuitive way this should be handled is I inform the transformation function, with an argument, that it is not to reverse that axis.

**Comment by karawoo** [comment]
Given the existing options for controlling the scales and the added complexity a new `coord_flip()` option would introduce, I think it is unlikely we will implement this feature.

**Comment by bhagwataditya** [comment]
Hey guys, I've hit a use case where `coord_flip` rotation into the other direction is what seems to be needed. I am trying to coord_flip a `geom_density_ridges` plot (which doesnt allow aes flipping like geom_density does):
https://github.com/wilkelab/ggridges/issues/4#issuecomment-1208072064
