### ISSUE TITLE
geom_sf, fill missing when xlim, ylim set in coord_sf in windows (follow-up to #3283)

### ISSUE THREAD

**Issue by k6adams** [tidyverse/ggplot2#4306]
This is a follow-up to issue #3238.

The fill is missing for my polygon when it goes beyond the xlim and ylim limits set in coord_sf.

The previous solution suggest that the problem is with the default Windows graphics device, and that this is not an issue on on Mac.

The work around provided was to save as a .png.

However, I am not sure how to make this work in my situation as I am making a video.

Any suggestions?

Thanks!
```r
library(tidyverse)
library(sf)
library(av)

tracts <- read_sf("https://opendata.arcgis.com/datasets/230f9d23f6874be983901876cd600c4e_0.geojson") %>% 
  select(
    geometry,
    ALAND10,
    GEOID10
    )
st_crs(tracts)

set.seed(264)

v1 <- runif(1:dim(tracts)[1], .7, 1.25)

tracts2 <- cbind(tracts, v1)

tracts_2017 <- tracts2 %>%
  mutate(season=2017)

tracts_2018 <- tracts2 %>%
  mutate(
    season=2018,
    ALAND10 = ALAND10*v1
    )
tracts3 <- rbind(tracts_2017, tracts_2018) 
  st_crs(tracts3)

makeplot1 <- function(){
  datalist1 <- split(
    tracts3,
    tracts3$season
  )
  datalist2 <- split(
    tracts3,
    tracts3$season
  )
  mapply(function(data1, data2){
    p1 <- ggplot() + 
      geom_sf(
        data = data1,
        aes(fill = ALAND10)
      ) +
      geom_sf(
        data = data2 %>% st_union(),
        fill = alpha("red", 0.4),
        color = alpha("red", 0.4)
      ) +
      coord_sf(
        ylim = c( 43.04, 43.07),
        xlim = c(-76.14,-76.10),
        clip = "on",
        expand = F
      )
    print(p1)
    
    },
    datalist1, datalist2
  ) 
}

makeplot2 <- function(){
  datalist1 <- split(
    tracts3,
    tracts3$season
  )
  datalist2 <- split(
    tracts3,
    tracts3$season
  )
  mapply(function(data1, data2){
    p2 <- ggplot() + 
      geom_sf(
        data = data1,
        aes(fill = ALAND10)
      ) +
      geom_sf(
        data = data2 %>% st_union(),
        fill = alpha("red", 0.4),
        color = alpha("red", 0.4)
      ) 
    print(p2)
    
  },
  datalist1, datalist2
  ) 
}

video_file1 <- file.path(tempdir(), 'Tracts1.mp4')
av::av_capture_graphics(makeplot1(), video_file1, vfilter='framerate=fps=10')
av::av_media_info(video_file1)
utils::browseURL(video_file1)

video_file2 <- file.path(tempdir(), 'Tracts2.mp4')
av::av_capture_graphics(makeplot2(), video_file2, vfilter='framerate=fps=10')
av::av_media_info(video_file2)
utils::browseURL(video_file2)

```

https://user-images.githubusercontent.com/7235297/103311881-1bee3f80-49e1-11eb-8675-6d178f45ddd9.mp4

https://user-images.githubusercontent.com/7235297/103311906-27da0180-49e1-11eb-9430-9ec85c70ada9.mp4

https://user-images.githubusercontent.com/7235297/103311923-2f99a600-49e1-11eb-86df-7104deda3e2e.mp4

**Comment by clauswilke** [comment]
This type of question is more appropriate for the RStudio Community or for Stackoverflow. One approach would be to save each frame as a png and then stitch together into a movie.

**Comment by k6adams** [comment]
@clauswilke
 thought about doing that. However, I feel that this should be reopened as a ggplot2 issue. Since there is no syntax error, and no geom_sf documentation (I am aware of) that addressing this, I think it is reasonable for users to assume that they should be able to produce the same results across operating systems.

I spent several hours trying debug my hurricane track data manipulation. It was not until I changed my options from “color=NA” to “color=‘red’” that I realized it was not a data manipulation issue, but a geom_sf() issue.

Moreover, in my particular use case, I would need to write and stitch together about 1,000 .png files.  I suppose I could figure out how to do that (If I must), but that is kind of besides the point.

I guess I am suggesting that this is a reproducibility issue, and not just ageneral question.

Also, I am not suggesting that there is a solution to this problem. But if there is not one, I think it should be documented that there is a difference between Windows and Mac.

Would you consider reopening this issue?

Thank you for your time.

**Comment by k6adams** [comment]
I updated my original question to link to issue #3283, instead of issue #3238. My bad.
