### ISSUE TITLE
Colourbar tick and frame linewidths

### ISSUE THREAD

**Issue by teunbrand** [tidyverse/ggplot2#4314]
Hello there,

This is just a minor inconsistency, but in case this wasn't noticed yet, here it is. Apparently, `guide_colourbar()` uses the `ticks.linewidth` and `frame.linewidth` parameter as-is, while in the rest of ggplot2 (as far as I can tell), almost every parameter for linewidth is calculated as below:

```
# Right before handing `supplied_value` to grid
lwd = supplied_value * .pt
```

Here is a reprex with exaggerated line sizes. You can notice when comparing the width of `geom_line()` versus the colourbar guide ticks. The lines appear of the same width when you adjust `ticks.linewidth = 5 * .pt`.

``` r

library(ggplot2)

df <- data.frame(x = c(0, 1), y = c(0.5, 0.5))

ggplot(df, aes(x, y)) +
  geom_point(aes(colour = x)) +
  geom_line(size = 5) +
  scale_colour_gradientn(
    colours = c("white", "white"),
    guide = guide_colourbar(ticks.colour = "black", ticks.linewidth = 5)
  )
```

![](https://i.imgur.com/tkrddYa.png)

<sup>Created on 2021-01-12 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Thanks for reading!

**Comment by clauswilke** [comment]
The correct comparison is with theme elements. I believe they don't multiply by `.pt`, but I could misremember.

**Comment by teunbrand** [comment]
That indeed would be a fairer comparison, though also the theme elements appear to use the `* .pt`. It appears for `element_grob.element_line()` here:

https://github.com/tidyverse/ggplot2/blob/37eb64de719c6f60c9f467f5530d59d2a477ee07/R/theme-elements.r#L248-L256

**Comment by clauswilke** [comment]
Then it probably should do so in the color bar also.

**Comment by teunbrand** [comment]
Thanks so I thought as well, should I leave a PR for you to consider?

**Comment by clauswilke** [comment]
Yes, please go ahead.
