### ISSUE TITLE
Meridians end before the pole when using polar stereographic crs in coord_sf and asymmetric limits

### ISSUE THREAD

**Issue by MikkoVihtakari** [tidyverse/ggplot2#4316]
I found unexpected behavior of `coord_sf()`. Not sure whether this has been reported already. Any solution available?

``` r
library(ggplot2)

ggplot() + 
  coord_sf( xlim = c(-4500000 , 4500000), ylim = c(-4500000, 4500000), crs = 3995) # as expected
```

![](https://i.imgur.com/0zpDWzp.png)

``` r

ggplot() + 
  coord_sf( xlim = c(-4500000 , 4500000), ylim = c(-2500000, 4500000), crs = 3995) # meridians end before the pole
```

![](https://i.imgur.com/YY7anIU.png)

<sup>Created on 2021-01-13 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by clauswilke** [comment]
If I recall correctly, the graticule is generated by sf. So you may want to check what you get if you just generate a graticule with sf directly. Workaround is to draw the graticule lines yourself.

**Comment by thomasp85** [comment]
This is an sf issue, so I'm closing it here
