### ISSUE TITLE
guide_axis(n.dodge) 

### ISSUE THREAD

**Issue by sbaross** [tidyverse/ggplot2#4317]
When using `guide_axis(n.dodge)` in a faceted plot, the first label of each facet always starts in the top line, instead of the dodging being continuous across the facets. Depending on the number of axis labels, this can cause labels to be next to each other & overlap instead of on alternating lines.

Example:
```r
df <- tibble(x = rep(c("a long axis label", "another long axis label", "the third long axis label"), 2),
             y = c(1, 2, 3, 3, 2, 1),
             z = rep(c("A", "B"), each = 3))

ggplot(df, aes(x = x, y = y)) +
  geom_col() +
  scale_x_discrete(guide = guide_axis(n.dodge = 2)) +
  facet_wrap(vars(z))
```
![Rplot01](https://user-images.githubusercontent.com/41447413/104823746-5d397880-5844-11eb-89b3-7121b6aca9d0.png)

**Comment by yutannihilation** [comment]
I'm not sure how this should be solved, but I feel a facet should not know (or depend on) the status of other facets.

**Comment by thomasp85** [comment]
Yeah - I can understand why this is annoying and undesirable but due to the technical challenge of achieving this I'm saying this is a wontfix issue
