### ISSUE TITLE
Boxenplots

### ISSUE THREAD

**Issue by nateGeorge** [tidyverse/ggplot2#4326]
This is a feature request to include boxenplots as a new layer or as an extension. I assume it would be a function like `geom_boxenplot()`. Boxenplots were introduced by a trio of authors (Heike Hofmann and Karen Kafadar and Hadley Wickham) in 2011 and were created to improve boxplots for modern (bigger) data. [The paper](https://vita.had.co.nz/papers/letter-value-plot.html) describes the mathematical definition, and it's implemented in [seaborn](https://seaborn.pydata.org/generated/seaborn.boxenplot.html) for Python.

Unfortunately, it doesn't look like there are any results for a boxenplot function anywhere in the R ecosystem.
![image](https://user-images.githubusercontent.com/10804060/105781296-9605db80-5f2f-11eb-82a7-2addd7190874.png)

I also did not see anything in the ggplot extensions for boxenplots. It seems like ggplot2 would be the place to have this, although an extension would work too.

**Comment by smouksassi** [comment]
https://cran.r-project.org/web/packages/lvplot/index.html

See here

**Comment by nateGeorge** [comment]
I didn't think to look for "letter value" plots, thanks. I figured Hadley must've made a package to do this since he co-wrote the paper on it.
