### ISSUE TITLE
Cannot specify quantiles in custom summary statistic

### ISSUE THREAD

**Issue by jmbh** [tidyverse/ggplot2#4333]
Reproducible example:

This works:

`df <- data.frame(x=rnorm(100), y=as.factor(c(rep("A", 50), rep('B',  50))))

data_summary <- function(x) {
  m <- mean(x)
  ymin <- m-sd(x)
  ymax <- m+sd(x)
  
  return(c(y=m,
           ymin=ymin,
           ymax=ymax))
}

ggplot(df, aes(x=y, y=x)) +
  geom_violin() +
  stat_summary(fun.data=data_summary)`

But this doesn't:

`
data_summary <- function(x) {
  m <- mean(x)
  qu <- quantile(x, probs = c(0.25, .75), na.rm=T)

  ymin <- qu[1]
  ymax <- qu[2]

  return(c(y=m,
           ymin=ymin,
           ymax=ymax))
}

ggplot(df, aes(x=y, y=x)) +
  geom_violin() +
  stat_summary(fun.data=data_summary)
`

There seems to be some ggplot2 bug, because the function above with the quantile seems to be fine.

Thanks!

Jonas

**Comment by clauswilke** [comment]
The bug is in your modified data summary function. (Admittedly, somewhat of an unexpected behavior.) You need to make sure the values are named correctly.

``` r
data_summary1 <- function(x) {
  m <- mean(x)
  ymin <- m-sd(x)
  ymax <- m+sd(x)
  
  return(c(y=m,
           ymin=ymin,
           ymax=ymax))
}

data_summary2 <- function(x) {
  m <- mean(x)
  qu <- quantile(x, probs = c(0.25, .75), na.rm=T)
  
  ymin <- qu[1]
  ymax <- qu[2]
  
  return(c(y=m,
           ymin=ymin,
           ymax=ymax))
}

x <- rnorm(100)
data_summary1(x)
#>          y       ymin       ymax 
#>  0.2036900 -0.7194713  1.1268512
data_summary2(x)
#>          y   ymin.25%   ymax.75% 
#>  0.2036900 -0.3787736  0.8737546
```

<sup>Created on 2021-01-28 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
