### ISSUE TITLE
stat_function aes(color= ...)

### ISSUE THREAD

**Issue by gabriben** [tidyverse/ggplot2#4338]
I found this [stackoverflow post](https://stackoverflow.com/questions/19950219/using-legend-with-stat-function-in-ggplot2) and wanted to implement something similar with a loop (for another bigger problem). I know I could precompute the ouput of the function in a dataframe and plot the dataframe, but I wanted to try to do it this way. 

However, I cannot make the colouring work when I write things in a loop. Here is the original stackoverflow without the loop

```r
library(ggplot)

MyFun <- function(x, p) {
  res <- x^(1 / p)
  return(res)
}

my.df = data_frame(x = -5:5)

ggplot(my.df, aes(x=x)) +
  stat_function(fun = MyFun, n = 1000, args = list(p = 10), aes(colour = "line1")) +
  stat_function(fun = MyFun, n = 1000, args = list(p = 3), aes(colour = "line2")) +
  stat_function(fun = MyFun, n = 1000, args = list(p = 2), aes(colour = "line3")) +
  stat_function(fun = MyFun, n = 1000, args = list(p = 1), aes(colour = "line4")) +
  scale_colour_manual("Lgend title", values = c("red", "blue", "green", "orange"))
```

With the loop:

```r

library(ggplot)

MyFun <- function(x, p) {
  res <- x^(1 / p)
  return(res)
}

my.df = data_frame(x = -5:5)

p = ggplot(d, aes(x=x))
P = c(10, 3, 2, 1)
cols = c("line1", "line2", "line3", "line4")

for (i in 1:4) {
  p <- p + stat_function(fun = MyFun, n = 1000, args = list(p = P[i]), aes(color = cols[i]))
  print(cols[i])
}

p + scale_colour_manual("Lgend title", values = c("red", "blue", "green", "orange"))
```

All lines are red. I also tried using `geom_line(stat = "function", ...)` instead, as recommended [here](https://stackoverflow.com/questions/61505199/warning-message-mapping-is-not-used-by-stat-function-in-r), but to no avail.

Thank you in advance

**Comment by clauswilke** [comment]
This type of question is better asked on stackoverflow or the RStudio Community. In brief, this has nothing to do with ggplot2. You need to read up on closures and promises. There are many related questions on stackoverflow, as this is a common problem people run into.

**Comment by clauswilke** [comment]
E.g.: https://stackoverflow.com/q/48948586/4975218
