### ISSUE TITLE
Filtering data by layer loses factor information

### ISSUE THREAD

**Issue by davidchall** [tidyverse/ggplot2#4339]
I'd like to use different layers to visualize different parts of my data set, but when I use the `data = ~ filter(.x, ...)` syntax I find that the order of factor levels is lost. I'm not sure if this is intended behavior or not?

``` r
options(tidyverse.quiet = TRUE)
library(tidyverse)

dat <- data.frame(
    x = as_factor(c("C", "B", "A")),
    y = c(1, 2, 3)
)

# preserves order of factor levels
ggplot(dat, aes(x, y)) +
    geom_point()
```

![](https://i.imgur.com/a59sHQH.png)

``` r
# loses order of factor levels
ggplot(dat, aes(x, y)) +
    geom_point(data = ~ filter(.x, y >= 2)) +
    geom_point(data = ~ filter(.x, y < 2))
```

![](https://i.imgur.com/Ee10zPv.png)

<sup>Created on 2021-02-01 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by davidchall** [comment]
In fact, I found this happens even if the data filtering is done outside of ggplot:

``` r
options(tidyverse.quiet = TRUE)
library(tidyverse)

dat <- data.frame(
    x = as_factor(c("C", "B", "A")),
    y = c(1, 2, 3)
)

# loses order of factor levels
ggplot(dat, aes(x, y)) +
    geom_point(data = filter(dat, y >= 2)) +
    geom_point(data = filter(dat, y < 2))
```

![](https://i.imgur.com/3B7yep2.png)

<sup>Created on 2021-02-02 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by teunbrand** [comment]
It's because unused factor levels are dropped in discrete position scales if `drop = TRUE`. Subsequently, when confronted with 2 different factors (because levels have been dropped), the result is interpreted as a character. The following works as expected:

``` r
library(tidyverse)

dat <- data.frame(
  x = as_factor(c("C", "B", "A")),
  y = c(1, 2, 3)
)

ggplot(dat, aes(x, y)) +
  geom_point(data = ~ filter(.x, y >= 2)) +
  geom_point(data = ~ filter(.x, y < 2)) +
  scale_x_discrete(drop = FALSE)
```

![](https://i.imgur.com/Mf4C4TM.png)

<sup>Created on 2021-02-02 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by davidchall** [comment]
Aha! I wasn't aware of this feature - thanks for educating me! 😅
