### ISSUE TITLE
setting x and y axis title margins fails when scale_x_...(position = "top") or scale_y_...(position = "right"), respectively

### ISSUE THREAD

**Issue by tjebo** [tidyverse/ggplot2#4343]
This is a request to reopen issue #2425 - which was closed, but the issue still remains. The linked issues do not refer to the axis title, but rather to legends (#1502. #2556)

Here as requested a self contained example. The desire is to increase the distance of the axis title to the axis. Setting margins to the titles fails when changing the axis position. 

Fails
``` r
library(ggplot2)
ggplot(mpg, aes(cty, hwy)) +
  scale_x_continuous(position = "top") +
  theme(axis.title.x = element_text(margin = margin(b = 1, unit = "in")))
```

![](https://i.imgur.com/pwbBmqY.png)

Fails
``` r
ggplot(mpg, aes(cty, hwy)) +
  scale_y_continuous(position = "right") +
  theme(axis.title.y = element_text(margin = margin(l = 1, unit = "in")))
```

![](https://i.imgur.com/MpHU00w.png)

Desired effect would be something like: (figure width has been set small, but the effect can be seen)
``` r
ggplot(mpg, aes(cty, hwy)) +
  scale_x_continuous() +
  theme(axis.title.x = element_text(margin = margin(t = 1, unit = "in")))
```

![](https://i.imgur.com/V27NAht.png)

or
``` r
ggplot(mpg, aes(cty, hwy)) +
  scale_y_continuous() +
  theme(axis.title.y = element_text(margin = margin(r = 1, unit = "in")))
```

![](https://i.imgur.com/GQfnsD3.png)

<sup>Created on 2021-02-07 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by tjebo** [comment]
For further reference, an obvious, but somewhat dumb workaround for this particular case (increased distance between axis title and axis) is to add a line break to the axis title.

**Comment by clauswilke** [comment]
Could you make this current issue self-contained? What specifically is the problem, what is the desired solution, etc.? Also please change the issue title to be more informative. Finally, could you use the reprex package to generate your example, so we see the output of the code as well?

In a nutshell, I should be able to pull up this issue and figure out what the problem is, without having to read a series of previous issues first.

**Comment by tjebo** [comment]
sure. apologies.

**Comment by tjebo** [comment]
@clauswilke I have updated the issue accordingly

**Comment by clauswilke** [comment]
Not a bug. Please watch this talk by @karawoo: https://resources.rstudio.com/resources/rstudioglobal-2021/always-look-on-the-bright-side-of-plots/

``` r
library(ggplot2)

# doesn't work, because a more specific theme setting exists
ggplot(mpg, aes(cty, hwy)) +
  scale_x_continuous(position = "top") +
  theme(axis.title.x = element_text(margin = margin(b = 1, unit = "in")))
```

![](https://i.imgur.com/pvdEzQa.png)

``` r
theme_gray()$axis.title.x.top$margin
#> [1] 0points    0points    2.75points 0points

# works
ggplot(mpg, aes(cty, hwy)) +
  scale_x_continuous(position = "top") +
  theme(axis.title.x.top = element_text(margin = margin(b = 1, unit = "in")))
```

![](https://i.imgur.com/HVIWfyz.png)

<sup>Created on 2021-02-07 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by tjebo** [comment]
@clauswilke as so often many thanks  for your very prompt help. thanks also for the tip with this talk, I'll check it out.
