### ISSUE TITLE
theme_update - Error: No method for merging x into y

### ISSUE THREAD

**Issue by dereckdemezquita** [tidyverse/ggplot2#4345]
I'm trying to reproduce the example shown here: https://community.rstudio.com/t/custom-ggplot2-theme-that-capitalizes-title/39688

The goal being to create a ggplot2 theme that would capitalise all desired texts. 

The original example I linked to above uses: `update_theme()`, but since I think the name has been changed, I changed it to `theme_update()`.

This produced the issue which I traced the issue in the debugger to the function: 

```r
> ggplot(mtcars, aes(mpg, hp)) +
+   geom_point() +
+   labs(
+     title = "My plot title"
+   ) +
+   new_theme()
Error: No method for merging list into element_line
Run `rlang::last_error()` to see where the error occurred.
```

Since it's request I include a minimal example here it is:

```r
library(ggplot2)

ggplot_add.my_theme <- function(object, plot, object_name){
  plot$theme <- ggplot2:::theme_update(plot$theme, object)
  plot$labels$title <- stringr::str_to_upper(plot$labels$title)
  plot
}

new_theme <- function(){
  out <- theme_bw()

  out <- out %+replace% theme(plot.title = element_text(face = "bold"))

  class(out) <- c("my_theme", class(out))

  return(out)
}


# works
ggplot(mtcars, aes(mpg, hp)) +
  geom_point() +
  labs(
    title = "My plot title"
  ) +
  new_theme()
```

I was testing around and the use of `theme_replace()` works ONCE. This I believe because it is replacing the `theme_bw()` function. This does not work on subsequent executions. 

To be honest this is reaching the limits of my R knowledge. I don't really fully grasp the chunk above; maybe I'm not understanding something which could easily be fixed.

Could someone be so kind as to explain this chunk as well please?

**Comment by clauswilke** [comment]
The right way to do what you want to do is to write a new theme element that modifies the strings right before rendering. See here for an example: https://stackoverflow.com/a/60345086/4975218
