### ISSUE TITLE
Old bug resurfaced - annotate does not work when x axis is date

### ISSUE THREAD

**Issue by katherinelauck** [tidyverse/ggplot2#4349]
When using annotate on plot with date x axis, annotate throws `Error: Invalid input: date_trans works with objects of class Date only`. Both the data for x axis and the x coord for annotate are supplied as lubridate `Date` objects. The same goes for if both objects are supplied as `POSIXct` objects, but the error asks for `POSIXct`. If the x axis data is `Date` and x coord is `POSIXct`, the error asks for `Date` and vice versa.

My ggplot2 version is 3.3.2, the latest on CRAN.

In trawling the internet for answers, I found this: https://stackoverflow.com/questions/18796386/how-to-use-ggplot2s-annotate-with-dates-in-x-axis and this: https://github.com/tidyverse/ggplot2/issues/859 both referencing an old, similar bug. Perhaps it is back?

```r
library(ggplot2)
library(lubridate)
library(tidyverse)

df <- tibble(
  date = sample(seq(as_date('2020-05-01'), as_date('2020-10-08'), by="day"), 100),
  sample = runif(100, min = 0, max = 100)
)

ggplot(df, aes(date,sample)) + geom_line() + annotate('text',x = c(as_date('2020-07-24'), as_date('2020-08-07')), y = c(50,70),c('hey!','listen!'))
```

**Comment by yutannihilation** [comment]
`c('hey!','listen!')` positionally matches `xmin`. You need to specify `label = `.

**Comment by katherinelauck** [comment]
Embarrassing, thank you
