### ISSUE TITLE
Colors don't appear in legend when specifying alpha with lines

### ISSUE THREAD

**Issue by evanmorier** [tidyverse/ggplot2#4351]
The colors in the legend disappear when specifying line transparency (alpha) within geom_line, geom_path, etc. The colors in the legend do show up if you either 1) remove the alpha specification, or 2) use alpha with a different geom (like geom_point).

```r
library(ggplot2)

ggplot(mtcars, aes(x=wt, y=mpg, color=factor(cyl))) +
  geom_line(alpha=.5)

ggplot(mtcars, aes(x=wt, y=mpg, color=factor(cyl))) +
  geom_line()

ggplot(mtcars, aes(x=wt, y=mpg, color=factor(cyl))) +
  geom_point(alpha=.5)
```

**Comment by yutannihilation** [comment]
I guess you are using Windows, right? This is a known issue on Windows' graphic device (https://github.com/rstudio/rstudio/issues/2196), but now you can avoid this by using AGG.

c.f. https://blog.rstudio.com/2020/12/02/rstudio-v1-4-preview-little-things/

``` r
library(ggplot2)

ggplot(mtcars, aes(x=wt, y=mpg, color=factor(cyl))) +
  geom_line(alpha=.5)
```

![](https://i.imgur.com/4aH5RcE.png)

``` r
ggplot(mtcars, aes(x=wt, y=mpg, color=factor(cyl))) +
  geom_line()
```

![](https://i.imgur.com/3FHHBzQ.png)

``` r
ggplot(mtcars, aes(x=wt, y=mpg, color=factor(cyl))) +
  geom_point(alpha=.5)
```

![](https://i.imgur.com/T2eZAeL.png)

<sup>Created on 2021-02-21 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>
