### ISSUE TITLE
Add vertical lines to log transformed axes

### ISSUE THREAD

**Issue by Cynthial0l** [tidyverse/ggplot2#4355]
Thanks for your amazing package!

I tried to add a vertical line to the log transformed x-axis using `geom_vline()`, but it kept reporting warnings like "Removed 1 rows containing missing values (geom_vline)".
The code I used as follows:
`ggplot(df)+
theme_bw()+scale_x_continuous(limits=c(2.5,6.5),breaks=c(3,4,5,6),labels=c(expression(10^3),expression(10^4),expression(10^5),expression(10^6)))+
  xlab("Time")+ylab("Size")+
  scale_y_continuous(expand = c(0, 0), limits=c(2.5,6.5),breaks=c(3,4,5,6),labels=c(expression(10^3),expression(10^4),expression(10^5),expression(10^6)))+
  annotation_logticks()`

I don't know how to add a vertical line at x=18000. Any help would be appreciated!

Best!

**Comment by yutannihilation** [comment]
Hi, this sort of question is a better fit for [RStudio Community](https://community.rstudio.com). Please ask there with a minimal reproducible example. We use this issue tracker for bug reports and feature requests.

**Comment by Cynthial0l** [comment]
Thank you for telling me.
