### ISSUE TITLE
Poor compatibility with R 4.1 pipe |>

### ISSUE THREAD

**Issue by bwiernik** [tidyverse/ggplot2#4357]
The planned native R pipe `|>` in R 4.1 currently interacts poorly with `ggplot()`. `|>` prohibits any symbols with special parsing rules on the RHS of the pipe, including `+`, `(`, and `{`. That makes it really hard to work with `\>` and `ggplot()` in a way that feels natural. See reprex below for some approaches that fail and work. 

Enabling a more natural workflow would require either an update to the ggplot2 API to make it pipeable or a change in the `|>` parsing rules to permit, for example, `(` or `{` on the RHS of `|>`. Do you have some connections with the R development team to raise this issue? 

```r
stopifnot(R.version$major == "4" & R.version$minor == "1.0")
library(ggplot2)

# Drop-in replacement of %>% with |>
## Doesn't work
mtcars |>
  ggplot() + 
      aes(x = as.factor(cyl), y = mpg, color = as.factor(cyl)) +
      geom_jitter(height = 0, width = .2) + 
      stat_summary(fun.data = mean_se, size = 1, color = "black") +
      theme_classic()

# Wrapping ggplot() chain in parentheses
## Doesn't work
mtcars |>
  (ggplot() + 
      aes(x = as.factor(cyl), y = mpg, color = as.factor(cyl)) +
      geom_jitter(height = 0, width = .2) + 
      stat_summary(fun.data = mean_se, size = 1, color = "black") +
      theme_classic()
  )

# Wrapping ggplot() chain in squiggly brackets
## Doesn't work
mtcars |>
  {ggplot() + 
      aes(x = as.factor(cyl), y = mpg, color = as.factor(cyl)) +
      geom_jitter(height = 0, width = .2) + 
      stat_summary(fun.data = mean_se, size = 1, color = "black") +
      theme_classic()
  }

# Wrap pipe chain and initial ggplot() in parentheses
## Works, but confusing
(mtcars |>
  ggplot()) + 
      aes(x = as.factor(cyl), y = mpg, color = as.factor(cyl)) +
      geom_jitter(height = 0, width = .2) + 
      stat_summary(fun.data = mean_se, size = 1, color = "black") +
      theme_classic()

# Write ggplot call as an anonymous function
## Works, but confusing
mtcars |>
  dplyr::mutate(cyl = as.factor(cyl)) |>
  (\(d) ggplot(d) + 
      aes(x = cyl, y = mpg, color = cyl) +
      geom_jitter(height = 0, width = .2) + 
      stat_summary(fun.data = mean_cl_normal, size = 1, color = "black") +
      geom_density() +
      theme_classic() )()
```

**Comment by bwiernik** [comment]
One other potential workaround would be to export `magrittr::add()`, which permits:

```
mtcars |>
  dplyr::mutate(cyl = as.factor(cyl)) |>
  ggplot() |>
      add(aes(x = cyl, y = mpg, color = cyl)) |>
      add(geom_jitter(height = 0, width = .2)) |>
      add(stat_summary(fun.data = mean_cl_normal, size = 1, color = "black")) |>
      add(geom_density()) |>
      add(theme_classic()) 
```

**Comment by bwiernik** [comment]
One other potential workaround would be to export `magrittr::add()`, which permits:

```
mtcars |>
  dplyr::mutate(cyl = as.factor(cyl)) |>
  ggplot() |>
      magrittr::add(aes(x = cyl, y = mpg, color = cyl)) |>
      magrittr::add(geom_jitter(height = 0, width = .2)) |>
      magrittr::add(stat_summary(fun.data = mean_cl_normal, size = 1, color = "black")) |>
      magrittr::add(geom_density()) |>
      magrittr::add(theme_classic()) 
```

**Comment by clauswilke** [comment]
That's very frustrating. None of the currently available options look good.

@yutannihilation has expressed doubts about the usefulness of the pipe with ggplot2, but I use it all the time in teaching. In my opinion, the use case is quick data manipulation before the plot. It just makes so much more sense to pipe than to create a new, intermediate data table. (Also saves real estate on slides.) See for example [this lecture](https://wilkelab.org/SDS375/slides/getting-things-in-order.html#1) from which I've taken this example:

``` r
library(tidyverse)
library(gapminder)

gapminder %>%
  filter(year == 2007, continent == "Americas") %>%
  mutate(country = fct_reorder(country, lifeExp)) %>%
  ggplot(aes(lifeExp, country)) + 
  geom_point()
```

![](https://i.imgur.com/mziMQSr.png)

<sup>Created on 2021-03-03 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by thomasp85** [comment]
We have a hope that this will be resolved in base R so let's wait with any mitigation in ggplot2 for now

**Comment by yutannihilation** [comment]
@clauswilke 
No, I don't doubt the usefulness of the pipe and actually I use it with ggplot2; I'm just doubting if the usage has ever been guaranteed (and just felt none of the two pull requests is convincing).

Anyway, I think we can just place a `%` operator just before ggplot2. This isn't very cool, but just works. None of the current options looks better than this to me.

``` r
gapminder |>
  filter(year == 2007, continent == "Americas") |>
  mutate(country = fct_reorder(country, lifeExp)) %>%
  ggplot(aes(lifeExp, country)) + 
  geom_point()
```

I agree we should wait for now, or join the discussion on R-devel mailing list.

**Comment by MyKo101** [comment]
It would be really nice for the changes to be implemented in R-devel, but it would then bring into question the large elephant of operator precedence. 

Obvioulsy ggplot would require the |> to be evaluated before Maths ops, and it does make more sense to have it this way round rather than the other. If you're doing any kind of functional operations, then you can always wrap them in a bracket, e.g. `x |> (f + g)()`.

I honestly think the best solution would be a re-write of ggplot to be a pipeable format (ggplot3), but that seems unlikely any time soon, which is why I posed my `%+%` solution since it would not ruin older code (`%+%` can be a drop-in for `+` anywhere already), and can handle both the `|>` and `%>%` operators.

**Comment by bwiernik** [comment]
If a change isn't made in r-devel (hopefully it is!), the %+% solution seems fairly compelling given that the function already exists and for a similar reason (working around R precedence issues).

**Comment by yutannihilation** [comment]
Fixed in r-devel.
https://github.com/wch/r-source/commit/e9f7b6c363a97fff6c41fa2d6e206dce0002edc8#diff-ba804d7fa3fa053c1f57d46369f4432cb55c9c4f69f46ae6510d0d1fcc59f382R403
