### ISSUE TITLE
Issue a message when fill aesthetic is used with GeomPoint and shape is not "filled"

### ISSUE THREAD

**Issue by netique** [tidyverse/ggplot2#4358]
I've spend an hour or so of `ggplot2` debugging to find out that `fill` aesthetics is simply ignored when `shape` of the point is not 21:25, i.e., not "filled". `grid::grid.point`, which is used, documents this case quite well, but `ggplot2` gives a hint only through the example that could be "hidden" from the user that struggles with, e.g., boxplot ouliers fill modification (as in my case).

I would hugely appreciate to get warning/message that inform the user he or she is demanding something that won't work as intended, like it is the case when I use `scale_alpha_*` with continuous variable.

**Comment by teunbrand** [comment]
While I empathise with the problem, I don't think a check like this is suitable for scatterplots that have in the millions of points as such a check slows down plotting quite a bit. I've argued against input validation [here](https://github.com/tidyverse/ggplot2/issues/5864#issuecomment-2078068175) but I think the documentation could be a bit more explicit.

**Comment by netique** [comment]
OK, makes sense to me.
