### ISSUE TITLE
geom_sf does not project spatial data correctly if sf::sfc is supplied to geometry aesthetic

### ISSUE THREAD

**Issue by MilesMcBain** [tidyverse/ggplot2#4361]
``` r
library(spData)
#> To access larger datasets in this package, install the spDataLarge
#> package with: `install.packages('spDataLarge',
#> repos='https://nowosad.github.io/drat/', type='source')`
library(ggplot2)
library(sf)
#> Linking to GEOS 3.8.0, GDAL 3.0.4, PROJ 6.3.1

seine_3857 <- st_transform(seine, 3857)

ggplot() +
  geom_sf(data = seine, color = "green") +
  geom_sf(data = seine_3857, color = "red")
```

![](https://i.imgur.com/OGkzzzG.png)

``` r
# Perfectly aligned in correct position

geometry_3857 <- st_geometry(seine_3857)
ggplot() +
  geom_sf(data = seine, color = "green") +
  geom_sf(mapping = aes(geometry = geometry_3857), color = "red")
```

![](https://i.imgur.com/A6ljxsE.png)

``` r
# Out of alignment
```

<sup>Created on 2021-03-03 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

So in example 1 the two spatial data sets end up in the same projection. I assume `geom_sf` has detected the projection of existing data and applied that projection to its data.

In example 2 the data for `geom_sf` end up in some unknown projection. It's almost like a reprojection has been attempted by messed up somehow. In my local example where I first hit this issue the longitude was correct but the latitude was wrong.

edit: more minimal reprex taking {ggspatial} out of loop.

**Comment by MilesMcBain** [comment]
This was R 4.0.4 and:

```
[ins] r$> packageVersion("ggplot2")
          packageVersion("sf")
          packageVersion("spData")
[1] '3.3.3'
[1] '0.9.7'
[1] '0.3.8'
```

**Comment by clauswilke** [comment]
Honestly, that's not an appropriate use of the ggplot2 API. We have never promised that you can feed data into the `aes()` function and get reliable results. In fact, we constantly tell people to not feed data into the `aes()` function.

**Comment by clauswilke** [comment]
This works just fine.

``` r
library(spData)
#> To access larger datasets in this package, install the spDataLarge
#> package with: `install.packages('spDataLarge',
#> repos='https://nowosad.github.io/drat/', type='source')`
library(ggplot2)
library(sf)
#> Linking to GEOS 3.8.1, GDAL 3.1.4, PROJ 6.3.1

seine_3857 <- st_transform(seine, 3857)
geometry_3857 <- st_geometry(seine_3857)

ggplot() +
  geom_sf(data = seine, color = "green") +
  geom_sf(data = st_sf(geometry_3857), color = "red")
```

![](https://i.imgur.com/FNSGgi3.png)

<sup>Created on 2021-03-02 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by MilesMcBain** [comment]
Yeah cool. I've actually never done this either, but a user of {snapbox} was doing it and they seemed to think it was supported behaviour.

**Comment by clauswilke** [comment]
The user may have misunderstood this sentence in the documentation:
> Supply your own using `aes(geometry = my_column)`

Though honestly, I would have thought the following would work, and it doesn't, so maybe there's a bug here after all.

``` r
library(spData)
#> To access larger datasets in this package, install the spDataLarge
#> package with: `install.packages('spDataLarge',
#> repos='https://nowosad.github.io/drat/', type='source')`
library(ggplot2)
library(sf)
#> Linking to GEOS 3.8.1, GDAL 3.1.4, PROJ 6.3.1

seine_3857 <- st_transform(seine, 3857)

data <- st_sf(
  1:3, # dummy, needed for some reason
  seine = st_geometry(seine),
  seine_3857 = st_geometry(seine_3857)
)

ggplot(data) +
  geom_sf(aes(geometry = seine), color = "green") +
  geom_sf(aes(geometry = seine_3857), color = "red")
```

![](https://i.imgur.com/YAX5Yg8.png)

<sup>Created on 2021-03-02 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by clauswilke** [comment]
I have opened a new issue about this. #4362
