### ISSUE TITLE
Add error to `direction` argument of guide_*()

### ISSUE THREAD

**Issue by charliejhadley** [tidyverse/ggplot2#4364]
The `direction` argument of `guide_*()` functions can only be "horizontal" or "vertical". At present an unhelpful error message is returned in case of error:

```r
library("ggplot2")

ggplot(quakes,
       aes(x = long,
           y = lat,
           colour = mag)) +
  geom_point() +
  guides(colour = guide_colorbar(direction = "horiz"))
#> Error in if (!g$title.position %in% c("top", "bottom", "left", "right")) {: argument is of length zero
```

In line with the tidyverse style guide an error like this would be more suitable:

```r
library("ggplot2")

ggplot(quakes,
       aes(x = long,
           y = lat,
           colour = mag)) +
  geom_point() +
  guides(colour = guide_colorbar(direction = "horiz"))
#> Error: The direction argument of guide_colorbar() must be either "vertical" or "horizontal"  
```

**Comment by teunbrand** [comment]
Thanks, that is indeed an inelegant error message. After #4879 gets merged, this will return the following error message:

> Error in `guide_colorbar()`:
! `direction` must be one of "horizontal" or
  "vertical", not "horiz".
ℹ Did you mean "horizontal"?
