### ISSUE TITLE
Layer orders with differing fill Aesthetic Mappings on Density Geometries affect resulting legend

### ISSUE THREAD

**Issue by jtlandis** [tidyverse/ggplot2#4365]
EDIT: This is again related to #3804 
EDIT2: feel free to delete as this is completely redundant to an issue I posted back in July 2020 (Amazing how you can forget about bugs you discover).

I happened upon a strange behavior in ggplot2 today.
If you add two `geom_density` layers to a `ggplot`, one with `fill` assigned and one with `fill` left as default, the order in which these layers are called will produce different results. Consider this reproducible example.

``` r
library(ggplot2)

#global fine
ggplot(mpg, aes(displ, hwy, colour = class, fill = class)) +
  geom_point(size = 2) +
  geom_density(aes(y = after_stat(density))) +
  geom_density(aes(x = after_stat(scaled))) 
```

![](https://i.imgur.com/WHMCixK.png)

``` r

#fill only assigned to last layer - unexpected behavior - an additional guide appears
ggplot(mpg, aes(displ, hwy, colour = class)) +
  geom_point(size = 2) +
  geom_density(aes(x = after_stat(scaled))) +
  geom_density(aes(y = after_stat(density), fill = class))
```

![](https://i.imgur.com/lB3IV7N.png)

``` r

#fill assigned before last
ggplot(mpg, aes(displ, hwy, colour = class)) +
  geom_point(size = 2) +
  geom_density(aes(y = after_stat(density), fill = class)) +
  geom_density(aes(x = after_stat(scaled))) 
```

![](https://i.imgur.com/KOvy20q.png)

``` r

ggplot(mpg, aes(displ, hwy, colour = class)) +
  geom_point(size = 2) +
  geom_density(aes(y = after_stat(density), fill = class)) +
  geom_density(aes(x = after_stat(scaled), fill = class))
```

![](https://i.imgur.com/CdcFthd.png)

<sup>Created on 2021-03-04 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

I would assume this is a bug and the issue only pertains to the case when the second `geom_density` has a `fill` aesthetic assigned where as previous ones are using `default_aes`.

I haven't been able to reproduce this in other geometries, although I have not tested all of them.

**Comment by smouksassi** [comment]
are you concerned about the legend and why/when the color legend get merged with the  points ?

**Comment by jtlandis** [comment]
> are you concerned about the legend and why/when the color legend get merged with the points ?

Specifically I am trying to bring attention to the second plot, the fact that suddenly there is an additional guide present.

**Comment by smouksassi** [comment]
you can re-enable the merging of guides by specifying the name for fill guide the same as the other the default name = "fill" was preventing the merge

``` r
library(ggplot2)
ggplot(mpg, aes(displ, hwy)) +
  geom_density(aes(x = after_stat(scaled), colour = class), alpha=0.1) +
  geom_density(aes(y = after_stat(density), colour = class , fill = class), alpha=0.1)+
  geom_point(aes(colour = class),size = 2) +
  labs(fill="class")
```

![](https://i.imgur.com/rRgfmT8.png)

<sup>Created on 2021-03-05 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by yutannihilation** [comment]
>  EDIT2: feel free to delete as this is completely redundant to an issue I posted back in July 2020 (Amazing how you can forget about bugs you discover).

Do you mean #4143, right? Closing this then, thanks.
