### ISSUE TITLE
legend box border thickness inconsistencies for legend.box = "horizontal"

### ISSUE THREAD

**Issue by cmaimone** [tidyverse/ggplot2#4366]
When there are guides for two scales, and they are placed horizontally (`legend.box = "horizontal"`), the border around the two guides together has inconsistent width.  This appears to be the result of one guide being smaller than the other, and the individual guides overlapping the joint bounding box border in some but not all places due to the size inconsistency.  Even if the legends are the same size, if there is a gap/margin between them, the border is thicker for this region.

* I've set the size to 2 below to exaggerate the effect, but it occurs whether or not the size is explicitly set. 
* I've also explicitly set the fill to red below to highlight what might be the underlying issue, but removing this doesn't change the thickness issue.
* Moving the legend does not seem to change this

```r
library(dplyr)
library(ggplot2)
library(gapminder)

gapminder %>% 
  filter(year == 1982) %>% 
  ggplot(aes(x = lifeExp, y = gdpPercap)) +
  geom_point(aes(size = pop, color = continent)) +
  theme(legend.box = "horizontal",
        legend.box.background = element_rect(color="black", size=2, fill="red")
  )
```

**Comment by karawoo** [comment]
Adjusting the legend box margin might help: 

``` r
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
library(ggplot2)
library(gapminder)

gapminder %>% 
  filter(year == 1982) %>% 
  ggplot(aes(x = lifeExp, y = gdpPercap)) +
  geom_point(aes(size = pop, color = continent)) +
  theme(
    legend.box = "horizontal",
    legend.box.background = element_rect(color = "black", size = 2, fill = "red"),
    legend.box.margin = margin(3, 3, 3, 3)
  )
```

![](https://i.imgur.com/iqZ9De9.png)

<sup>Created on 2021-03-08 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

**Comment by cmaimone** [comment]
Thank you!
