### ISSUE TITLE
scale_y_continuous() 'sec.axis' and Warning min(x) max(x)

### ISSUE THREAD

**Issue by YoannPa** [tidyverse/ggplot2#4368]
In a ggplot I am using a secondary Y-axis to display additionnal labels to my plot.
I use it like this :
```
scale_y_continuous(
      expand = c(0, 0),
      breaks = seq(0, N.rows, length.out = n.grad),
      labels = function(x) format(x, digits = 2, scientific = TRUE),
      sec.axis = sec_axis(
        trans = ~.,
        breaks = dt.data[right.y.hiden == FALSE]$right.y.label.pos,
        labels = dt.data[right.y.hiden == FALSE]$sample.string))
```
in `sec_axis()` breaks and labels are queried in a data.table `dt.data`:

- If multiple breaks and labels are selected from the data.table -> no problems.
- If there is only 1 break and 1 label queried from the data.table, displaying the plot returns this warning (I guess this is the matching translation from the language I use):
```
Warning messages:
1: In min(x) : no non-missing arguments to min; returning Inf
2: In max(x) : no non-missing arguments to max; returning -Inf
```
The plot returned is fine : it totally matches my expectation.
But I don't understand why these warnings are printed.

So I basically have to questions:
1. Why those warnings are printed when there is only 1 break & label ?
2. Is there something I should mention in `sec_axis()` or elsewhere to get rid of these warnings ?

I don't know if it is reproducible, but from what I experienced, if you give just a single value to `breaks` and `labels` in `sec_axis()` such has:
`sec.axis = sec_axis(trans = ~., breaks = 125, labels = "awesome single label")`
This should trigger the warnings.

**Comment by yutannihilation** [comment]
Could you provide a minimal reprex?

**Comment by YoannPa** [comment]
Sorry I though what I wrote would be enough to reproduce the issue.
Here is a reproducible example:

```
library(data.table)
library(ggplot2)

dt.data <- data.table(
  "data.covered" = c(10, 15, 50, 40),
  "sample.amount" = c(1, 2, 3, 4))

ggplot() + theme_gray() +
  theme(legend.title.align = 0.5,
        legend.text = element_text(size = 12),
        legend.position = "bottom") +
  geom_bar(data = dt.data,
           mapping = aes(x = 0, y = data.covered, fill = sample.amount),
           stat = "identity") +
  scale_y_continuous(
    expand = c(0, 0),
    breaks = seq(0, 120, length.out = 15),
    labels = function(x) format(x, digits = 2, scientific = TRUE),
    sec.axis = sec_axis(
      trans = ~.,
      breaks = 35,
      labels = "label test")) +
  scale_x_continuous(expand = c(0, 0))
```

Executing this chuck of code will produce the warning I describe (and it comes from sec_axis() as I provide only 1 single break and label to it).

**Comment by yutannihilation** [comment]
Thanks. It seems it came from `range(old_val_minor_trans)` here when there are no minor breaks (i.e. `range(numeric(0))` emits the warning). Probablye this should be skipped in the case.

https://github.com/tidyverse/ggplot2/blob/4555055ce6e23e5b0630122fd9cc2aaf8cb1f91a/R/axis-secondary.R#L235

**Comment by YoannPa** [comment]
I don't understand the context of the line you quote. How should I use it in the reprex ?

**Comment by yutannihilation** [comment]
It was just a quick note about how to fix this issue.

**Comment by YoannPa** [comment]
So contributors for ggplot2 will fix it ? (Sorry I am not so much used to issue process here).

**Comment by yutannihilation** [comment]
Yes, I wrote it just in case someone might get motivated to fix this. Feel free to contribute :)
