### ISSUE TITLE
geom_smooth doesn't allow user input of ymin & ymax 

### ISSUE THREAD

**Issue by lizzyagibson** [tidyverse/ggplot2#4369]
Docs say that ymin and ymax are optional aesthetics of geom_smooth. Actually specifying ymin and yman does not change the plotted confidence band size. Users should be able to set ymin and ymax based on their model of interest, right?

Below example should have drastically different confidence intervals, but doesn't.

```r
library(tidyverse)

x = tibble(x = rpois(100, lambda = 5)) %>% 
  mutate(y = 5*x + rnorm(100, 0, 10) )

x %>% ggplot(aes(x=x, y=y)) +
  geom_smooth(aes(ymin = y-100, ymax = y+100), method = "lm")

x %>% ggplot(aes(x=x, y=y)) +
  geom_smooth(method = "lm")
```

**Comment by yutannihilation** [comment]
I guess what you want on `ymin` is not `y`, the original values, but `after_stat(y)`, the result values of the statistical calculation by `StatSmooth`.

``` r
library(tidyverse)

x <- tibble(x = rpois(100, lambda = 5)) %>%
  mutate(y = 5 * x + rnorm(100, 0, 10))

x %>% ggplot(aes(x = x, y = y)) +
  geom_smooth(aes(ymin = after_stat(y) - 100, ymax = after_stat(y) + 100), method = "lm")
```

**Comment by lizzyagibson** [comment]
YES! Thank you!

**Comment by lizzyagibson** [comment]
But what if the added term is a variable in your dataframe? This doesn't work:

```{r}
library(tidyverse)

x <- tibble(x = rpois(100, lambda = 5)) %>%
  mutate(y = 5 * x + rnorm(100, 0, 10),
         z = rnorm(100))

x %>% ggplot(aes(x = x, y = y)) +
  geom_smooth(aes(ymin = after_stat(y) - z, ymax = after_stat(y) + z), method = "lm")
```

**Comment by yutannihilation** [comment]
This sort of question is a better fit for [RStudio Community](https://community.rstudio.com). Please ask there with a minimal reproducible example. We use this issue tracker for bug reports and feature requests.
