### ISSUE TITLE
Using rlang::check_installed() 

### ISSUE THREAD

**Issue by malcolmbarrett** [tidyverse/ggplot2#4370]
rlang 0.4.10 introduced `check_installed()` to both check that a suggested package is installed and, if not, offer to the user to do so for them. I have found this to be very ergonomic so far and suspect it would be a boon to R newcomers to use this function in ggplot2 (after having some students trip on hexbin just this week). 

I'd be happy to prepare a PR. It would require a bump in the rlang dependency, so I'm not sure if that's an issue for you all.

**Comment by yutannihilation** [comment]
Thanks, as we keep seeing similar requests (e.g. #4344) on improving the error, this sounds reasonable to me. ggplot2 already requires R >= 3.3, so I think it's fine to require rlang 0.4.10.
