### ISSUE TITLE
page misbehaving at https://ggplot2.tidyverse.org/reference/stat.html

### ISSUE THREAD

**Issue by david-romano** [tidyverse/ggplot2#4373]
The title of [the reference page for `stat()`](https://ggplot2.tidyverse.org/reference/stat.html) is obscured by a banner-like element at the top.

**Comment by yutannihilation** [comment]
`stat()` is deprecated and what you see is an abandoned page. Here's the equivalent page of the latest version:

https://ggplot2.tidyverse.org/reference/aes_eval.html

**Comment by david-romano** [comment]
Thank you, Hiroaki -- I appreciate it.

**Comment by yutannihilation** [comment]
I removed the outdated page. Thanks for reporting!
