### ISSUE TITLE
New feature request: ticks for minor breaks

### ISSUE THREAD

**Issue by larmarange** [tidyverse/ggplot2#4387]
On some graphs, in particular when grids are not drawn, it would be relevant to add ticks for minor breaks.

 Similar to `annotation_logticks()`, it could be relevant to have a function `annotation_minorticks()` to draw such minor ticks, or something similar.

**Comment by smouksassi** [comment]
Are you aware of this 
https://teunbrand.github.io/ggh4x/articles/PositionGuides.html#minor-ticks

**Comment by larmarange** [comment]
I didn't know that but this exactly that.

**Comment by teunbrand** [comment]
I'd be happy to contribute that code for minor ticks in axis guides, however I think it makes more sense to implement https://github.com/tidyverse/ggplot2/issues/3329 first.
