### ISSUE TITLE
geom_jitter documentation for width and height arguments is misleading

### ISSUE THREAD

**Issue by svigneau** [tidyverse/ggplot2#4393]
The width and height arguments have distinct, yet identical definitions in the geom_jitter documentation, as follows:

> width Amount of vertical and horizontal jitter. [...] so a width or height [...]
> height Amount of vertical and horizontal jitter. [...] so a width or height [...]

This is misleading as it sounds that width is used to specify the amount of both vertical and horizontal jitter, and so is height.

These definitions are inherited from the position_jitter documentation where the two arguments are defined together, in which case the wording makes sense.

I suppose the issue could be addressed by providing distinct definitions for width and height in position_jitter, but this solution would have the inconvenience of duplicating text and increasing wordiness. Alternatively, the behavior of Roxygen when building the geom_jitter definition could be altered so that width and height share the same definition, similar to the position_jitter documentation, but I am not sure how this can be achieved.

**Comment by teunbrand** [comment]
This has meanwhile been fixed in roxygen.
