### ISSUE TITLE
How to separate `boxplot` and `dotplot` when plot both at same time?

### ISSUE THREAD

**Issue by yuw444** [tidyverse/ggplot2#4398]
I am working on a project and trying to reproduce [following plot][1].

  [1]: https://i.stack.imgur.com/zoJAq.png

Here is my attempt. 

```
test<-data.frame(
  x=factor(rep(1:3, each=20)),
  y=runif(60)
)
p<-ggplot(test, aes(x=x, y=y,fill=x)) +
  geom_boxplot(width=0.2) +
  geom_dotplot(binaxis = "y")
p
```

But boxplot and dotplot are crowded together in my attempt. Any advice is appreciated. 

Thanks.

**Comment by clauswilke** [comment]
These types of questions (for help or advice with making a specific plot) should be directed to the RStudio Community or to Stackoverflow.

**Comment by yuw444** [comment]
Got it. Thanks. The problem is resolved.
