### ISSUE TITLE
Warning message: no loop for break/next, jumping to top level

### ISSUE THREAD

**Issue by nk2000-collab** [tidyverse/ggplot2#4400]
Trying to make a visualization of map representing all the flight routes. And the loop does not run and I get the error listed in the title. When I run the codes individually I do get one flight route however when I run the entire code it never outputs anything and runs forever basically.
[DATA (1).zip](https://github.com/tidyverse/ggplot2/files/6266468/DATA.1.zip)

`
for(i in 1:nrow(unique(direct_flights))){
    node1 <- airports[airports$AirportID==direct_flights$SourceAirportID[i],]
    node2 <- airports[airports$AirportID==direct_flights$`Desination AirportID`[i],]
    Nodes_together<-cbind(node1,node2)
    colnames(Nodes_together)<-c("Start_AirportID","lat.x","lon.x","Dest_AirportID","lat.y","lon.y")
    worldmap <- borders("world", colour="#efede1", fill="blue") # create a layer of borders
map_overall <- ggplot() + worldmap +
  geom_curve(data=Nodes_together, aes(x = lon.x, y = lat.x, xend = lon.y, yend = lat.y), col = "red", size = 1, curvature = .2) 
  map_overall
}
`
This is the traceback error I get: "no loop for break/next, jumping to top level"
6.exists(name, envir = x, inherits = FALSE)
5.fetch_ggproto(x, name)
4.$.ggproto(geom, "parameters")
3.geom$parameters
2.layer(data = data, mapping = mapping, stat = stat, geom = GeomCurve, position = position, show.legend = show.legend, inherit.aes = inherit.aes, params = list(arrow = arrow, arrow.fill = arrow.fill, curvature = curvature, angle = angle, ncp = ncp, lineend = lineend, na.rm = na.rm, ...
1.geom_curve(data = Nodes_together, aes(x = lon.x, y = lat.x, xend = lon.y, yend = lat.y), col = "red", size = 1, curvature = 0.2)

**Comment by clauswilke** [comment]
This looks like a question that would be more appropriate for the RStudio Community or for Stackoverflow. The ggplot2 issue tracker is not meant for general user support.
