### ISSUE TITLE
alpha in geom_label() only works correctly if data.frame is provided

### ISSUE THREAD

**Issue by RS-eco** [tidyverse/ggplot2#4402]
Creating a plot with geom_label and specifying alpha works if the label is specified in a separate data.frame:

``` r
library(ggplot2)

# Working example
df <- data.frame(
    x = 1.75,
    y = 32,
    text = c("(a)")
  )

ggplot(data = mtcars) +
  geom_point(mapping = aes(wt, mpg)) +
  geom_label(data = df, aes(x = x, y = y, label = text), colour="white", alpha=0.25)
```

![](https://i.imgur.com/xl4e9uN.png)

However, the plot looks different, if the label is added directly (without aes() specifications):

``` r
# This does not work
ggplot(data = mtcars) +
  geom_point(mapping = aes(wt, mpg)) +
  geom_label(x=1.75, y=32, label="(a)", colour="white", alpha = 0.25) 
```

![](https://i.imgur.com/DRQqhRj.png)

A work-around is setting the alpha-value lower:

``` r
# but works with different alpha setting
ggplot(data = mtcars) +
  geom_point(mapping = aes(wt, mpg)) +
  geom_label(x=1.75, y=32, label="(a)", colour="white", alpha = 0.05) 
```

![](https://i.imgur.com/b6txjvy.png)
```
But, I guess this a small bug in ggplot2::GeomLabel(), which is easy to fix.

**Comment by teunbrand** [comment]
In your second example, one textbox for every row in the `mtcars` dataset is drawn, effectively stacking a bunch of semitransparent labels that then appear solid. For these type of use cases there is the `annotate()` function. Also note that the `alpha` applies to the fill, if you want to apply it to the colour you can do `scales::alpha("blue", 0.25)`.

``` r
library(ggplot2)

# Coloured in blue because white is hard to see
ggplot(data = mtcars) +
  geom_point(mapping = aes(wt, mpg)) +
  annotate(geom = "label", x = 1.75, y =32, label = "(a)", colour = "blue", 
           alpha = 0.25)
```

![](https://i.imgur.com/qTvl2ta.png)

**Comment by yutannihilation** [comment]
Thanks @teunbrand!

For the original issue (https://github.com/aphalo/ggpmisc/issues/2), you can use `annotate()` like this.

``` r
library(ggpmisc)
#> Loading required package: ggplot2
#> 
#> Attaching package: 'ggpmisc'
#> The following object is masked from 'package:ggplot2':
#> 
#>     annotate

ggplot(data = mtcars) +
  geom_point(mapping = aes(wt, mpg)) +
  annotate("label_npc", npcx=0.04, npcy=0.95, label="(a)", colour="white", alpha = 0.5) 
```

![](https://i.imgur.com/4pCzvtW.png)

<sup>Created on 2021-04-07 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by smouksassi** [comment]
this is because many labels are being overplotted on top of each other.
try just telling it to use the first row of mtcars  the behavior is different from geom_vline where if data and hard coded mapping are provided the data is completely ignored

``` r
library(ggplot2)

# Working example
df <- data.frame(
  x = 1.75,
  y = 32,
  text = c("(a)")
)

ggplot(data = mtcars) +
  geom_point(mapping = aes(wt, mpg)) +
  geom_label(data = df, aes(x = x, y = y, label = text),
             fill="red", alpha=0.25)+
  geom_vline(data=df,
             aes(xintercept = x),
             colour="red", alpha = 0.25, size=2)   
```

![](https://i.imgur.com/fsCMnn1.png)

``` r
ggplot(data = mtcars) +
  geom_point(mapping = aes(wt, mpg)) +
  geom_label(x=1.75, y=32, label="(a)", 
             fill="red", alpha = 0.25)+
  geom_label(data=mtcars[1,],
             x=1.75, y=20, label="(a)", 
             fill="red", alpha = 0.25)+
  geom_vline(xintercept = 1.75,
             colour="red", alpha = 0.25, size=2) +
  geom_vline(data=data.frame(),
             xintercept = 2 , 
             colour="red", alpha = 0.25, size=2)   
#> Warning: geom_vline(): Ignoring `data` because `xintercept` was provided.
```

![](https://i.imgur.com/JZRVZNN.png)

<sup>Created on 2021-04-07 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by yutannihilation** [comment]
Thanks @smouksassi! Sorry I closed this a bit too early... :smile:
