### ISSUE TITLE
Unexpected behavior in `geom_errorbarh()` when data are identical

### ISSUE THREAD

**Issue by skent259** [tidyverse/ggplot2#4410]
At the end of the day, I'm just trying to add verticals lines corresponding to the mean on a scatter plot of points (where categories are on the y axis).  

I have been using `geom_errorbarh()` for this, with `stat = "summary"` and pushing the minimum and maximum to be the same thing.  However, when data in one of the groups are identical, this fails with a weird error about aesthetics.  It works when the data aren't all identical.  

I realize this might not be expected usage of `geom_errorbarh()`, or common data, but I've yet to find a better way to add the desired lines. 

``` r
library(tibble)
#> Warning: package 'tibble' was built under R version 4.0.2
library(ggplot2)
tmp_data <- tibble(
  y = factor(rep(1:2, each = 10)),
  x = c(rep(0.1, 10), rnorm(10, mean = 0.1))
)

(p <- ggplot(tmp_data, aes(x, y, color = y)) +
  geom_point())
```

![](https://i.imgur.com/5teyzw6.png)

``` r

# try to add vertical lines at the mean 
(p + geom_errorbarh(aes(xmin = x, xmax = x),
                    stat = "summary",
                    fun.min = mean, fun.max = mean))
#> Error: geom_errorbarh requires the following missing aesthetics: xmin and xmax

# this works when as long as the data isn't all identical
tmp_data2 <- tmp_data %>% add_row(y = factor(1), x = 0.2)
(p + geom_errorbarh(aes(xmin = x, xmax = x),
                   stat = "summary",
                   fun.min = mean, fun.max = mean,
                   data = tmp_data2))
```

![](https://i.imgur.com/7vqVAeW.png)

``` r

print(packageVersion("ggplot2"))
#> [1] '3.3.2'
```

<sup>Created on 2021-04-09 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by thomasp85** [comment]
This is definitely off-label use of `geom_errorbarh()`. Your issue, however, is the way you use `stat_summary()`. It is calculating min and max values and should thus not have them mapped as it messes up the calculations. Simply avoid any additional mapping and you get what you want

``` r
p +
  geom_errorbarh(stat = "summary",fun.min = mean, fun.max = mean)
```

![](https://i.imgur.com/yP24K8H.png)
