### ISSUE TITLE
scale_color_manual not working properly

### ISSUE THREAD

**Issue by ChiaraH23** [tidyverse/ggplot2#4421]
Hi everyone,

I am currently struggling with scale_color_manual in ggplot2, although this has never been a problem. I keep getting the error message: "Error: Insufficient values in manual scale. 9 needed but only 0 provided." However, I have clearly provided enough colors, so it just doesn't seem to be registering. Does anyone know what is going on/how I can fix this? 

My ggplot2 package version is: 3.3.3. 
Phyloseq Version is 1.30.0

```r
library(phyloseq)
library(ggplot2)

data("GlobalPatterns")
GP <- prune_species(speciesSums(GlobalPatterns) > 0, GlobalPatterns)

cohortcol<- c("#70AD47","orange", "blue", "green","red","yellow","purple","black","grey") #this usually works to assign colors below

a<-plot_richness(GP, x="SampleType", color="SampleType", measures=c("Chao1", "Shannon"))+ scale_color_manual(values=alpha(cohortcol, 0.7))#+theme(axis.title.x=element_blank(), axis.text.x=element_blank(),legend.position="none", axis.title.y = element_blank())
print(a)

```
It then doesn't print a and gives me my error message. I get the same message if I were to remove cohortcol and just add colors as a vector instead instead. 

GP is a phyloseq object. 

Restarting R used to do the trick, however, even this has stopped working now.

Thanks for your help!

**Comment by ptoche** [comment]
you need to give code that can be run. See the ``reprex`` package for that. Right now ``could not find function "plot_richness"`` and ``Error: object 'a' not found`` so it won't be easy to help you.

**Comment by ChiaraH23** [comment]
Yes, sorry! I realize that now, so I now have another example that should be accessible that still won't change the colors for me.

**Comment by ChiaraH23** [comment]
After updating R, RStudio, RTools and all packages it works!

**Comment by ChiaraH23** [comment]
Same issue as before, despite updating it now no longer works

**Comment by clauswilke** [comment]
Hello, this doesn't look like a question that is appropriate for the ggplot2 issue tracker. Please consider asking on the RStudio Community or on Stackoverflow. There are thousands of packages that build on top of ggplot2 and when things go wrong while using one of them it's rarely that the problem is with ggplot2 itself.
