### ISSUE TITLE
pkgdown CI error

### ISSUE THREAD

**Issue by yutannihilation** [tidyverse/ggplot2#4424]
https://github.com/tidyverse/ggplot2/runs/2360094189#step:9:464
```
-- RMarkdown error -------------------------------------------------------------
Quitting from lines 372-382 (faq-axes.Rmd) 
Error: Error in loadNamespace(name) : there is no package called 'ggtext'
--------------------------------------------------------------------------------
Error: Error: Failed to render RMarkdown
```

**Comment by thomasp85** [comment]
Yeah, I'm investigating what needs to be changed for the action to honour the new Config in the DESCRIPTION file

**Comment by yutannihilation** [comment]
It seems we need to explicitly install these.

e.g. https://github.com/tidyverse/tidyverse/blob/8bad0dd3568e24c4365b639222f7b36ee187fcdc/.github/workflows/pkgdown.yaml#L48
