### ISSUE TITLE
Non-deterministic behavior regarding legend order

### ISSUE THREAD

**Issue by elbersb** [tidyverse/ggplot2#4452]
While preparing a teaching example, I noticed that the legend order changes when I supply a different labeling function. To me it seems that the labeling of the values should not affect the order of the different legends. In the first two plots below, see how the "continent" and "Population" guides change order, although the only difference is the labeling of the population values. Of course, it's easy enough to fix the order, but possibly the example is still of interest. I wasn't able to narrow down the exact details of why this happens, but if there's interest in fixing this I'd dig deeper.

``` r
library("ggplot2")
library("gapminder")
million <- function(x) paste0(scales::comma(x / 1000000), "m")

p <- ggplot(gapminder, aes(x = gdpPercap, y = lifeExp, color = continent, size = pop)) + 
    geom_point()

p + scale_size(name = "Population", labels = scales::comma)
```

![](https://i.imgur.com/AToySwT.png)

``` r
p + scale_size(name = "Population", labels = million)
```

![](https://i.imgur.com/fOVH2Ts.png)

<sup>Created on 2021-04-27 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by smouksassi** [comment]
consider the help entry for guide_legend:
order	
positive integer less than 99 that specifies the order of this guide among multiple guides. This controls the order in which multiple guides are displayed, not the contents of the guide itself. If 0 (default), the order is determined by a secret algorithm.

think of it is on "auto" mode without guarantee of the order unless you take ownership of it:


``` r
library("ggplot2")
library("gapminder")
million <- function(x) paste0(scales::comma(x / 1000000), "m")


p1 <- ggplot(gapminder, aes(x = gdpPercap, y = lifeExp,
                      color = continent, size = pop)) + 
  geom_point()+
  scale_size(name = "Population", labels = scales::comma)

p2 <- ggplot(gapminder, aes(x = gdpPercap, y = lifeExp,
                            color = continent, size = pop)) + 
  geom_point()+
  scale_color_hue(guide = guide_legend(order = 1))+
  scale_size(name = "Population", labels = million,
             guide = guide_legend(order = 2)
             )
p1
```

![](https://i.imgur.com/haZ9bvn.png)

``` r
p2
```

![](https://i.imgur.com/afec0P5.png)

<sup>Created on 2021-04-27 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>
