### ISSUE TITLE
geom_smooth shows wrong slope on plots with log10 y-axis

### ISSUE THREAD

**Issue by EV201** [tidyverse/ggplot2#4457]
Please briefly describe your problem and what output you expect. If you have a question, please don't use this form, but instead ask on the mailing list <https://groups.google.com/forum/#!forum/ggplot2> or stackoverflow <http://stackoverflow.com>.

Please include a minimal reprex. The goal of a reprex is to make it as easy as possible for me to recreate your problem so that I can fix it. If you've never heard of a reprex before, start by reading <https://www.tidyverse.org/help/#reprex>, and follow the advice further down the page. Do NOT include session info unless it's explicitly asked for, or you've used `reprex::reprex(..., si = TRUE)` to hide it away.  

Delete these instructions once you have read them.

---

using lm in the geom_smooth on a log10 y-axis seems to give the wrong slope. Compare linear with log10 to see the differences. It actually changed one of my plots(see below) from a downward(linear) to an upward slope(log10)

```r
 mcyto <- data.frame(Time=c(51, 60, 86, 109, 140, 156, 245, 275, 298, 329, 354, 245, 275, 298, 329, 354, 74, 88, 104, 129, 152, 74, 85, 104, 128, 152, 80, 128, 146, 66, 87, 106, 126, 65, 87, 106, 126, 74, 93, 110, 128, 146, 74, 93, 110, 128, 146, 100, 115, 130, 142, 154, 106), Cytokine=c(4504.022, 529.19, 1573.416, 837.9, 4873.84, 1033.73, 4527.126, 3720.459, 1284, 3292.621, 1019.35, 2410.528, 1491.157, 861, 2988.829, 1382, 2049.956, 1384.1, 2402.415, 473.4, 1855.943, 2161.097, 305.53, 905.4501, 254.85, 1591.839, 5615.881, 416.2376, 330.4489, 305.2234, 1519, 3179.697, 4480.496, 9692.308, 1161, 680.8719, 781.4976, 2201.025, 430.37, 917.3285, 256.8, 287.9962, 2406.826, 1004.37, 1771.013, 1676.28, 3813.154, 6632.449, 3759.7, 1790.147, 995.17, 1427.511, 3871.059))
maxX <- max(mcyto$Time)
ggplot() + geom_point(data=mcyto, aes(x=Time, y=Cytokine))+ xlim(0, maxX) + scale_y_log10(limits=c(0.1, 100000), breaks=c(1, 10, 100, 1000, 10000, 100000)) + geom_smooth(data=mcyto, aes(x=Time, y=Cytokine), method="lm",  se=T, col="black") 
ggplot() + geom_point(data=mcyto, aes(x=Time, y=Cytokine))+ xlim(0, maxX) + scale_y_continuous(limits=c(0.1, 10000), breaks=c(1, 10, 100, 1000, 10000, 10000)) + geom_smooth(data=mcyto, aes(x=Time, y=Cytokine), method="lm",  se=T, col="black") 

```

**Comment by clauswilke** [comment]
Sorry to be bearer of bad news, but the log10 plot looks more appropriate to me. I suggest you read up on  heteroscedasticity and variable transformations in linear regression.

https://en.wikipedia.org/wiki/Heteroscedasticity
