### ISSUE TITLE
Build in support for brailleR

### ISSUE THREAD

**Issue by hadley** [tidyverse/ggplot2#4459]
Need to add this to the appropriate place in plot/print methods:

```
if (is_installed("BrailleR") && isTRUE(getOption("BrailleR.VI")) {  
  BrailleR::VI(graph)
}
```

**Comment by yutannihilation** [comment]
This looks a good idea to me, but brailleR was removed from CRAN last year, so this issue needs to wait for the return.

Related discussion: #4256

**Comment by hadley** [comment]
Rather than waiting we can use some hack to prevent CRAN seeing the `::`; then it'll work when BrailleR returns.

**Comment by thomasp85** [comment]
Is the output of `BrailleR::VI()` meant to be returned or should it just be printed?

**Comment by hadley** [comment]
Just printed
