### ISSUE TITLE
geom_density2d stopped working properly

### ISSUE THREAD

**Issue by ap-github-q** [tidyverse/ggplot2#4465]
I just noticed that geom_density2d is no longer working properly when the data being plotted has multiple groups. The attached figure [geom_density2d.pdf](https://github.com/tidyverse/ggplot2/files/6426285/geom_density2d.pdf) illustrates the problem using the attached dataset [test.csv](https://github.com/tidyverse/ggplot2/files/6426291/test.csv) that has 3 groups. Panel A shows the plot I am now getting, and as you can see, the density lines are incorrect for the second (green) and third (blue) group. This was not always the case, as before I was getting the plot shown in Panel B, where the density lines are correct for all 3 groups. The problem persists if I split the plot using facet_wrap so that there is only one group per facet (please see Panel C), but the problem goes away if I plot the 3 groups separately one at a time (please see Panels D-F). I am not sure what is causing this problem, so I uninstalled R from my MacBook Pro (macOS Catalina 10.15.6) and then reinstalled R (4.0.5) and ggplot2, but the problem persists. Can you please help, and let me know how I can reproduce Panel B?

**Comment by clauswilke** [comment]
Please provide a self-contained fully reproducible example. Use either a built-in dataset or one that is made up. Your example code should not be more than 10-15 lines, including generating the dataset (if necessary).

You can adapt one of the examples provided if that helps: 
https://ggplot2.tidyverse.org/reference/geom_density_2d.html#examples

**Comment by clauswilke** [comment]
Chances are, though, that you just need to read the documentation for `geom_density_2d()`. It was never actually fully working until the last ggplot2 release, and chances are your code relies on old and partially broken behavior.

**Comment by ap-github-q** [comment]
> Please provide a self-contained fully reproducible example. Use either a built-in dataset or one that is made up. Your example code should not be more than 10-15 lines, including generating the dataset (if necessary).

Please see the example below. In this dataset with 3 groups, when I plot one group at a time, everything works fine. But when I plot all 3 groups together (bottom right plot), the density lines are incorrect for the green and blue groups, as you can see by comparing the top right plot vs the bottom right plot and the bottom left plot vs the bottom right plot (respectively).

``` r
library(gridExtra); library(ggplot2)
dat <- read.csv(url("https://github.com/tidyverse/ggplot2/files/6426291/test.csv"))
p1 <- ggplot(dat[dat$Type=="type1",],aes(x=dim1,y=dim2,col=Type))+geom_density2d()+scale_color_manual(values="#F8766D")+theme_classic()+theme(legend.position="top")+scale_x_continuous(limits=c(-50,50))+scale_y_continuous(limits=c(-50,50))
p2 <- ggplot(dat[dat$Type=="type2",],aes(x=dim1,y=dim2,col=Type))+geom_density2d()+scale_color_manual(values="#00BA38")+theme_classic()+theme(legend.position="top")+scale_x_continuous(limits=c(-50,50))+scale_y_continuous(limits=c(-50,50))
p3 <- ggplot(dat[dat$Type=="type3",],aes(x=dim1,y=dim2,col=Type))+geom_density2d()+scale_color_manual(values="#619CFF")+theme_classic()+theme(legend.position="top")+scale_x_continuous(limits=c(-50,50))+scale_y_continuous(limits=c(-50,50))
p4 <- ggplot(dat,aes(x=dim1,y=dim2,col=Type))+geom_density2d()+theme_classic()+theme(legend.position="top")+scale_x_continuous(limits=c(-50,50))+scale_y_continuous(limits=c(-50,50))
grid.arrange(p1,p2,p3,p4,nrow=2)
```

![](https://i.imgur.com/XhxzaS6.png)

<sup>Created on 2021-05-09 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by clauswilke** [comment]
As I said: You need to read the documentation.

``` r
library(gridExtra); library(ggplot2)
dat <- read.csv(url("https://github.com/tidyverse/ggplot2/files/6426291/test.csv"))
p1 <- ggplot(dat[dat$Type=="type1",],aes(x=dim1,y=dim2,col=Type))+geom_density2d()+scale_color_manual(values="#F8766D")+theme_classic()+theme(legend.position="top")+scale_x_continuous(limits=c(-50,50))+scale_y_continuous(limits=c(-50,50))
p2 <- ggplot(dat[dat$Type=="type2",],aes(x=dim1,y=dim2,col=Type))+geom_density2d()+scale_color_manual(values="#00BA38")+theme_classic()+theme(legend.position="top")+scale_x_continuous(limits=c(-50,50))+scale_y_continuous(limits=c(-50,50))
p3 <- ggplot(dat[dat$Type=="type3",],aes(x=dim1,y=dim2,col=Type))+geom_density2d()+scale_color_manual(values="#619CFF")+theme_classic()+theme(legend.position="top")+scale_x_continuous(limits=c(-50,50))+scale_y_continuous(limits=c(-50,50))
p4 <- ggplot(dat,aes(x=dim1,y=dim2,col=Type))+geom_density2d(contour_var="ndensity")+theme_classic()+theme(legend.position="top")+scale_x_continuous(limits=c(-50,50))+scale_y_continuous(limits=c(-50,50))
grid.arrange(p1,p2,p3,p4,nrow=2)
```

![](https://i.imgur.com/p51TaE5.png)

<sup>Created on 2021-05-09 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>
