### ISSUE TITLE
geom_boxplot incorrect boxplot statistics

### ISSUE THREAD

**Issue by toothpicky** [tidyverse/ggplot2#4469]
I have found several instances where the geom_boxplot is incorrect. Example below shows two different boxplots and only the base R version is correct.

```r
x<- structure(list(DOSE01A = c(60, 60, 60, 60), CONC = c(4.11070615161627, 
2.49620372709774, 4.00556108112744, 4.40830466646852)), row.names = c(NA, 
-4L), class = "data.frame")

ggplot(data=x, aes(x=factor(DOSE01A), y=CONC)) +
  geom_boxplot()

boxplot(CONC ~ DOSE01A, data = x)

```
![image](https://user-images.githubusercontent.com/25786204/117416989-c534cd00-aece-11eb-9d43-96b5ad764f36.png)
![image](https://user-images.githubusercontent.com/25786204/117417019-cbc34480-aece-11eb-95c8-c4e87c7c1a7c.png)

**Comment by toothpicky** [comment]
Another example:

```{r}
x<-structure(list(CONC = c(16.428, 10.285, 11.642, 17.085, 10.35, 
13.893, 8.5187, 13.575, 10.616, 40.62, 14.738, 13.767, 19.559, 
20.004, 29.591, 14.21, 19.809, 12.626, 5.8871, 18.183, 10.563, 
14.645, 27.849, 13.881, 8.8525, 12.913, 7.4847, 11.113, 9.0577, 
12.904, 16.313, 17.948), MG.round1 = c(90, 90, 90, 90, 90, 90, 
90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 
90, 90, 90, 90, 90, 90, 90, 90, 90, 90)), row.names = c(NA, -32L
), class = "data.frame")

boxplot(CONC~ MG.round1, data=x1)

ggplot(data=x1, aes(x=factor(MG.round1), y=CONC)) +
  geom_boxplot() 

```

![image](https://user-images.githubusercontent.com/25786204/117418297-198c7c80-aed0-11eb-8fc8-cc386746ee45.png)
![image](https://user-images.githubusercontent.com/25786204/117418395-3923a500-aed0-11eb-989d-1a25a2417c73.png)

**Comment by ptoche** [comment]
This comes up periodically. As far as I remember, ``ggplot2`` and base do not use the same stats to produce the boxplots. It can make a difference in corner cases, where you have very little data. You can peruse the code to see the difference. Also I remember a similar issue from 4 or 5 years ago, you might find it among the "closed" issues.

**Comment by teunbrand** [comment]
Might have found the mentioned issue: #3204

**Comment by ptoche** [comment]
Also, have a loot at:

    library("ggplot2")    
    ?geom_boxplot

versus: 

    ?boxplot.stats

**Comment by ptoche** [comment]
vaguely related: [https://stackoverflow.com/questions/21793715/why-geom-boxplot-identify-more-outliers-than-base-boxplot](https://stackoverflow.com/questions/21793715/)

**Comment by smouksassi** [comment]
boxplot.stats states that the hinges are not exactly equal the IQR ( it uses stats::fivenum)
The two ‘hinges’ are versions of the first and third quartile, i.e., close to quantile(x, c(1,3)/4). The hinges equal the quartiles for odd n (where n <- length(x)) and differ for even n. Whereas the quartiles only equal observations for n %% 4 == 1 (n = 1 mod 4), the hinges do so additionally for n %% 4 == 2 (n = 2 mod 4), and are in the middle of two observations otherwise.

maybe if you need the base R behavior you can just precompute the stats and plug it in to ggplot


``` r
library(stats)
x<- 1:100
c(min(x),quantile(x,0.25),median(x),quantile(x,0.75),max(x))
#>           25%           75%        
#>   1.00  25.75  50.50  75.25 100.00
IQR(x)
#> [1] 49.5
stats <- fivenum(x, na.rm = TRUE)
diff(stats[c(2, 4)])
#> [1] 50
```

<sup>Created on 2021-05-07 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by karawoo** [comment]
This is often a source of confusion, but the comments here are correct that it is [expected behavior](https://ggplot2.tidyverse.org/reference/geom_boxplot.html?q=box#summary-statistics) and not a bug.
