### ISSUE TITLE
Add "alt" label

### ISSUE THREAD

**Issue by hadley** [tidyverse/ggplot2#4477]
e.g.

```R
plot + labs(
  alt = "This is a plot of diamonds data showing the price increases non-linearly with carat"
)
```

For now, it would just store the label in an attribute, but the goal would be to plumb it up with knitr so that the plot text automatically made it way to the `alt` attribute of the html image.

**Comment by thomasp85** [comment]
This is already sorta possible:

```r
p <- ggplot() + labs(alt = 'this is a test')
p$labels$alt
#> [1] "this is a test"
```

I think what we should provide is a function that takes a plot object and returns the alt-text. This would make it easy for us to iterate and improve upon it without breaking knitr etc since the interface was unchanged
