### ISSUE TITLE
n.breaks for sec_axis

### ISSUE THREAD

**Issue by SHogenboom** [tidyverse/ggplot2#4483]
Suggestion for improvement:

When using a continuous scale I find the `n.breaks` argument very useful and intuitive to use. However, when using the `sec.axis` argument to simply duplicate the existing axis I run into the issue that:

1. The labels/ticks of the original axis are not actually duplicated, rather the labels prior to any manipulations are duplicated.
2. The `sec_axis` function does not have a similar `n.breaks` argument.

I believe it would be very useful if the secondary axis could have the `n.breaks` argument and/or duplicate the primary axis that utilised this argument.

**Comment by clauswilke** [comment]
Could you provide a minimal reproducible example, please?

**Comment by SHogenboom** [comment]
```
# load tidyverse (loads ggplot2)
library(tidyverse)

# Simulate Data
dat <-
    data.frame("x" = 1:10,
               "y" = sample(x = 1:1000,
                            size = 50,
                            replace = TRUE))

# PLOT 1: 
# no adjustments
ggplot(data = dat,
       aes(x = x,
           y = y)) +
    geom_point()

# Outcome: as expected

# PLOT 2
# n.breaks adjustments primary y-axis
ggplot(data = dat,
       aes(x = x,
           y = y)) +
    geom_point() +
    scale_y_continuous(n.breaks = 20)

# Outcome: as expected

# PLOT 3
# n.breaks adjustments primary y-axis
# add secondary axis
ggplot(data = dat,
       aes(x = x,
           y = y)) +
    geom_point() +
    scale_y_continuous(n.breaks = 20,
                       sec.axis = sec_axis(trans = ~.))

# Outcome: not expected
# Expectations is that the secondary y-axis duplicates the tickmarks of
# ... the primary y-axis. Instead. It duplicates the tickmarks as if we 
# ... duplicated the axis of plot 1
```
