### ISSUE TITLE
Accreditation of Author in `stat_ellipse()` Documentation

### ISSUE THREAD

**Issue by benyamindsmith** [tidyverse/ggplot2#4490]
Hello everyone, 

I hope this finds you well.

I noticed that the authors mentioned in the `stat_ellipse()` function are  the authors of the `car` package and not specifically not those who made the function it was inspired from (`car::dataEllipse())`

I have attached a screenshot of the documentation below.

![image](https://user-images.githubusercontent.com/46410142/119870690-a2a33c00-beef-11eb-9889-2e5027dd976f.png)

The other two authors of the given function (besides for John Fox) are [Georges Monette](https://github.com/gmonette) and [Michael Friendly](https://github.com/friendly) who were the ones together with Fox help develop the idea and the function. 

Attached is the relevant documentation from the `car` package showing their contributions:

![image](https://user-images.githubusercontent.com/46410142/119871641-a71c2480-bef0-11eb-8d39-34d8e55d735c.png)

As a student of Georges I think it would be appropriate to give him as well as Dr. Friendly a mention in the `stat_ellipse()` documentation as they both together with Fox founded and elucidated the idea of data ellipses (besides for being developers for the `dataEllipse()` function).

The relevant paper on the concept of data ellipses written by Monette, Fox and Friendly is [here
](https://projecteuclid.org/journals/statistical-science/volume-28/issue-1/Elliptical-Insights-Understanding-Statistical-Methods-through-Elliptical-Geometry/10.1214/12-STS402.full)

I understand that you may just want to attribute the package authors and not the relevant contributors but I thought it would be worthwhile trying to get them both mentioned in the documentation as well. 

Looking forward to hearing back.

**Comment by clauswilke** [comment]
You're welcome to prepare a PR. One issue I see though is that probably nobody has access to the 1990 paper cited in the car package, so there's no way for us to verify that the reference actually makes sense. We're citing the materials that we have access to and have looked at.

**Comment by benyamindsmith** [comment]
While I can't say anything about the 1990 paper I do know of a more recent paper (circa 2013) which highlights the relevant insights buy Fox, Friendly and Monette [here](https://projecteuclid.org/journals/statistical-science/volume-28/issue-1/Elliptical-Insights-Understanding-Statistical-Methods-through-Elliptical-Geometry/10.1214/12-STS402.full).

A brief search on google scholar seems to indicate that the 1990 is one of those things that is probably lost in the web or never made it there.

**Comment by clauswilke** [comment]
The Fox et al paper definitely looks appropriate to me. Feel free to prepare a PR that adds this reference.

**Comment by hadley** [comment]
Here's the original contribution: https://github.com/tidyverse/ggplot2/commit/008018cce9a5063efb2eaa9cb917850a3ee762ea.

We look forward to your PR.

**Comment by benyamindsmith** [comment]
@hadley just forked and made a PR. Hope I did this right.

**Comment by teunbrand** [comment]
This is fixed by #4803
