### ISSUE TITLE
line in geom_smooth

### ISSUE THREAD

**Issue by AlirezaShokrollahi** [tidyverse/ggplot2#4493]
Hello
I wrote this code:
ggplot(mpg, aes(displ, hwy)) + geom_point() + geom_smooth(method = lm, se = FALSE)
and this is the plot:
![ggplot](https://user-images.githubusercontent.com/71460276/120021140-eab18400-bfff-11eb-9147-2f9acf0d7f90.jpeg)

I expected that the line in that plot is like this plot:
![geom_smooth-4](https://user-images.githubusercontent.com/71460276/120021514-66abcc00-c000-11eb-8270-2add71b3b11d.png)

The line is Zigzag. Why does this happen? 

Thank you.

**Comment by clauswilke** [comment]
It looks like that because you're generating a low-resolution bitmap graphic as output. Increase the resolution and the line will be smooth.

**Comment by ptoche** [comment]
If you can, save as a PDF. Use ``ggsave`` and make sure the extension is `.pdf`.

**Comment by AlirezaShokrollahi** [comment]
Thank you.
