### ISSUE TITLE
ggplot labs is capitalizing 'i'

### ISSUE THREAD

**Issue by piyushjo15** [tidyverse/ggplot2#4497]
Hi,

I am using ggplot2 (ggplot2_3.3.0) and when I use small 'i' in labels (x or y) it is getting capitalized. Just wanted to see if there is a bug?

```
tiff("SN195_Intronic_frac_Plot.tiff", width = 4, height = 3, units ="in", res=300)

ggplot(mdfr2, aes(x=Rank, y=frac, color=Cells)) +
  geom_point(size=0.1, alpha=0.5)+
  scale_color_manual(values = c("grey77", "red"))+
  theme_classic()+ xlab("Rank barcodes") + ylab ("Fraction of Intronic reads") +
  theme(axis.line = element_line(colour = 'black',size=0.2),
        axis.ticks = element_line(colour = 'black',size=0.2),
        axis.text = element_text(face="bold",colour = "black",size=5),
        axis.title=element_text(face="bold",colour="black",size = 5),
        panel.grid.major = element_line(colour = "grey97"),
        panel.border =element_rect(fill=NA, colour = 'black',size=0.4))+
  scale_y_continuous(expand = c(0, 0), limits = c(0, 1))+
  scale_x_continuous(expand = c(0, 0))+
  guides(color=FALSE)

dev.off()
```

**Comment by karawoo** [comment]
Could you please include a reproducible example with the [reprex](https://reprex.tidyverse.org/) package? It should be as minimal as possible, using only a small amount of data that you can define in the code, and leaving out any lines of the ggplot call that aren't necessary to reproduce the issue.

**Comment by piyushjo15** [comment]
I realized that it seemed to be a issue with font size and resolution. With font size 5, the dot seems to get merged upon saving as tiff. Sorry for not investigating this properly before posting. When trying to make an example I changed the font and I caught this issue.
