### ISSUE TITLE
Segfault on install

### ISSUE THREAD

**Issue by wallingTACC** [tidyverse/ggplot2#4499]
I have several users reporting issues with installing ggplot2 and other tidyverse related packages.  I suspect our linux environment is somewhat dated, but would like to locate the root issue to hopefully figure out a work around.  Below is example output of the segfault when the package is loaded as part of the install process.

---

Brief description of the problem

```r
$ R CMD INSTALL ggplot2_3.3.3.tar.gz 
* installing to library ‘/home1/00157/redacted/R/x86_64-pc-linux-gnu-library/4.0’
* installing *source* package ‘ggplot2’ ...
** package ‘ggplot2’ successfully unpacked and MD5 sums checked
** using staged installation
** R
** data
*** moving datasets to lazyload DB
** inst
** byte-compile and prepare package for lazy loading
sh: line 1: 50502 Segmentation fault      R_TESTS= '/opt/apps/intel18/impi18_0/Rstats/4.0.3/lib64/R/bin/R' --no-save --no-restore --no-echo 2>&1 < '/tmp/RtmppTPFtr/filec5213e60555e'
sh: $'\001': command not found

 *** caught segfault ***
address 0x7f00, cause 'memory not mapped'

Traceback:
 1: FUN(X[[i]], ...)
 2: lapply(.x, .f, ...)
 3: map(syms, function(sym) {    if (!is_symbol(sym)) {        abort("Inputs to capture must be argument names")    }    if (identical(sym, dots_sym)) {        splice_dots <<- TRUE        splice(dot_call(capture_dots, frame_env = frame_env,             named = named, ignore_empty = ignore_empty, unquote_names = unquote_names,             homonyms = homonyms, check_assign = check_assign))    }    else {        dot_call(capture_arg, sym, frame_env)    }})
 4: endots(call = sys.call(), frame_env = parent.frame(), capture_arg = rlang_enquo,     capture_dots = rlang_quos_interp, named = .named, ignore_empty = .ignore_empty,     unquote_names = .unquote_names, homonyms = .homonyms, check_assign = .check_assign)
 5: enquos(x = x, y = y, ..., .ignore_empty = "all")
 6: aes()
 7: ggproto("Geom", required_aes = character(), non_missing_aes = character(),     optional_aes = character(), default_aes = aes(), draw_key = draw_key_point,     handle_na = function(self, data, params) {        remove_missing(data, params$na.rm, c(self$required_aes,             self$non_missing_aes), snake_class(self))    }, draw_layer = function(self, data, params, layout, coord) {        if (empty(data)) {            n <- if (is.factor(data$PANEL))                 nlevels(data$PANEL)            else 1L            return(rep(list(zeroGrob()), n))        }        params <- params[intersect(names(params), self$parameters())]        args <- c(list(quote(data), quote(panel_params), quote(coord)),             params)        lapply(split(data, data$PANEL), function(data) {            if (empty(data))                 return(zeroGrob())            panel_params <- layout$panel_params[[data$PANEL[1]]]            do.call(self$draw_panel, args)        })    }, draw_panel = function(self, data, panel_params, coord,         ...) {        groups <- split(data, factor(data$group))        grobs <- lapply(groups, function(group) {            self$draw_group(group, panel_params, coord, ...)        })        ggname(snake_class(self), gTree(children = do.call("gList",             grobs)))    }, draw_group = function(self, data, panel_params, coord) {        abort("Not implemented")    }, setup_params = function(data, params) params, setup_data = function(data,         params) data, use_defaults = function(self, data, params = list(),         modifiers = aes()) {        missing_aes <- setdiff(names(self$default_aes), names(data))        missing_eval <- lapply(self$default_aes[missing_aes],             eval_tidy)        missing_eval <- compact(missing_eval)        if (empty(data)) {            data <- as_gg_data_frame(missing_eval)        }        else {            data[names(missing_eval)] <- missing_eval        }        if (length(modifiers) != 0) {            env <- child_env(baseenv(), after_scale = after_scale)            stage_mask <- child_env(emptyenv(), stage = stage_scaled)            mask <- new_data_mask(as_environment(data, stage_mask),                 stage_mask)            mask$.data <- as_data_pronoun(mask)            modified_aes <- lapply(substitute_aes(modifiers),                 eval_tidy, mask, env)            nondata_modified <- check_nondata_cols(modified_aes)            if (length(nondata_modified) > 0) {                msg <- glue("Modifiers must return valid values. Problematic aesthetic(s): ",                   glue_collapse(vapply(nondata_modified, function(x) glue("{x} = {as_label(modifiers[[x]])}"),                     character(1)), ", ", last = " and "), ". \nDid you map your mod in the wrong layer?")                abort(msg)            }            names(modified_aes) <- rename_aes(names(modifiers))            modified_aes <- new_data_frame(compact(modified_aes))            data <- cunion(modified_aes, data)        }        aes_params <- intersect(self$aesthetics(), names(params))        check_aesthetics(params[aes_params], nrow(data))        data[aes_params] <- params[aes_params]        data    }, extra_params = c("na.rm"), parameters = function(self,         extra = FALSE) {        panel_args <- names(ggproto_formals(self$draw_panel))        group_args <- names(ggproto_formals(self$draw_group))        args <- if ("..." %in% panel_args)             group_args        else panel_args        args <- setdiff(args, names(ggproto_formals(Geom$draw_group)))        if (extra) {            args <- union(args, self$extra_params)        }        args    }, aesthetics = function(self) {        if (is.null(self$required_aes)) {            required_aes <- NULL        }        else {            required_aes <- unlist(strsplit(self$required_aes,                 "|", fixed = TRUE))        }        c(union(required_aes, names(self$default_aes)), self$optional_aes,             "group")    })
 8: eval(exprs[i], envir)
 9: eval(exprs[i], envir)
10: sys.source(codeFile, env, keep.source = keep.source, keep.parse.data = keep.parse.data)
11: doTryCatch(return(expr), name, parentenv, handler)
12: tryCatchOne(expr, names, parentenv, handlers[[1L]])
13: tryCatchList(expr, classes, parentenv, handlers)
14: tryCatch(expr, error = function(e) {    call <- conditionCall(e)    if (!is.null(call)) {        if (identical(call[[1L]], quote(doTryCatch)))             call <- sys.call(-4L)        dcall <- deparse(call)[1L]        prefix <- paste("Error in", dcall, ": ")        LONG <- 75L        sm <- strsplit(conditionMessage(e), "\n")[[1L]]        w <- 14L + nchar(dcall, type = "w") + nchar(sm[1L], type = "w")        if (is.na(w))             w <- 14L + nchar(dcall, type = "b") + nchar(sm[1L],                 type = "b")        if (w > LONG)             prefix <- paste0(prefix, "\n  ")    }    else prefix <- "Error : "    msg <- paste0(prefix, conditionMessage(e), "\n")    .Internal(seterrmessage(msg[1L]))    if (!silent && isTRUE(getOption("show.error.messages"))) {        cat(msg, file = outFile)        .Internal(printDeferredWarnings())    }    invisible(structure(msg, class = "try-error", condition = e))})
15: try(sys.source(codeFile, env, keep.source = keep.source, keep.parse.data = keep.parse.data))
16: loadNamespace(package = package, lib.loc = lib.loc, keep.source = keep.source,     keep.parse.data = keep.parse.data, partial = TRUE)
17: withCallingHandlers(expr, packageStartupMessage = function(c) tryInvokeRestart("muffleMessage"))
18: suppressPackageStartupMessages(loadNamespace(package = package,     lib.loc = lib.loc, keep.source = keep.source, keep.parse.data = keep.parse.data,     partial = TRUE))
19: code2LazyLoadDB(package, lib.loc = lib.loc, keep.source = keep.source,     keep.parse.data = keep.parse.data, compress = compress, set.install.dir = set.install.dir)
20: tools:::makeLazyLoading("ggplot2", "/home1/00157/redacted/R/x86_64-pc-linux-gnu-library/4.0/00LOCK-ggplot2/00new",     keep.source = FALSE, keep.parse.data = FALSE, set.install.dir = "/home1/00157/redacted/R/x86_64-pc-linux-gnu-library/4.0/ggplot2")
An irrecoverable exception occurred. R is aborting now ...
ERROR: lazy loading failed for package ‘ggplot2’
* removing ‘/home/redacted/R/x86_64-pc-linux-gnu-library/4.0/ggplot2’

```

Some additional information on the environment:

```
$ uname -a
Linux redacted.edu 3.10.0-957.5.1.el7.x86_64 #1 SMP

$ cat /etc/centos-release
CentOS Linux release 7.6.1810 (Core) 

R> sessionInfo()
R version 4.0.3 (2020-10-10)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

Matrix products: default
BLAS/LAPACK: /opt/intel/compilers_and_libraries_2018.2.199/linux/mkl/lib/intel64_lin/libmkl_intel_lp64.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       


```

**Comment by thomasp85** [comment]
Since there is not any compiled code in ggplot2 it is probably due to an outdated dependency. My money are on rlang

**Comment by wallingTACC** [comment]
I can't figure out how to get the install process to save the file '/tmp/RtmppTPFtr/filec5213e60555e' so that I can investigate further.  None of the flags like --no-test-load or --no-clean-on-error seem to have an effect.

**Comment by wallingTACC** [comment]
I believe this is a related issue: https://github.com/r-dbi/RSQLite/issues/371

**Comment by hsbadr** [comment]
@wallingTACC Are you able to run `ragg` examples on your system? I get segfaults and I build R with Intel compilers + MKL too.

**Comment by wallingTACC** [comment]
I was able to install and run the following ragg code without issue.

` 
library(ragg)
cap <- agg_capture(width = 1000, height = 500, res = 144)
plot(1:10, 1:10)
scatter <- cap()
invisible(dev.off())
# Remove margins from raster plotting
par(mai = c(0, 0, 0, 0))
plot(as.raster(scatter))
dev.off()
`

**Comment by hsbadr** [comment]
> I was able to install and run the following ragg code without issue.

@wallingTACC Thanks for testing!

**Comment by wallingTACC** [comment]
fwiw, this same error message occurs when attempting to install other packages on a node with virtual memory limits that are maxing out.  However, for ggplot2, it still happens on a node with what should be plenty of memory.

Specifically this type of output:

sh: line 1: 50502 Segmentation fault      R_TESTS= '/opt/apps/intel18/impi18_0/Rstats/4.0.3/lib64/R/bin/R' --no-save --no-restore --no-echo 2>&1 < '/tmp/RtmppTPFtr/filec5213e60555e'
sh: $'\001': command not found

 *** caught segfault ***
address 0x7f00, cause 'memory not mapped'

**Comment by thomasp85** [comment]
Have you tried to update all the dependencies of ggplot2, specifically those that needs compilation such as rlang and farver (and probably some others) as I suggested?

There is no compiled code in ggplot2 so it is not able to trigger any segfaults directly. Only through calls to functions in other packages

**Comment by wallingTACC** [comment]
Yes, I re-installed all the libraries from the Imports: line in cran.  Is there a way to save the output of the R_TESTS script that is ran?

R_TESTS= '/path/R/4.0.3/lib64/R/bin/R' --no-save --no-restore --no-echo 2>&1 < '/tmp/Rtmp0
OowxG/filee30a6b95b9a9'

**Comment by thomasp85** [comment]
I don't know about that but it doesn't ever get to run any tests. But based on the trace back it is an issue in rlang, so you might have more success asking there

**Comment by wallingTACC** [comment]
I am able to install ggplot2 v2.2.1 fine with the latest rlang 0.4.11.  All versions 3.0+ fail with the above message.

**Comment by thomasp85** [comment]
That just means that the old version of ggplot2 doesn't trigger the same bug in rlang (I presume)

**Comment by thomasp85** [comment]
I'm actually not sure that rlang is used in ggplot2 prior to v3.0.0

**Comment by hsbadr** [comment]
@wallingTACC Have you tried to skip test of loading installed package?
```bash
R CMD INSTALL --no-test-load ggplot2_*.tar.gz
```
It seems that it fails when calling `rlang::enquos()` from `tools:::makeLazyLoading()`. You may also try to install the development (or a different) version of `rlang`.

**Comment by wallingTACC** [comment]
--no-test-load does not appear to have any effect, same error.

ggplot2 v3+ has a hard requirement for rlang > 0.4.10

Unfortunately trying to install devtools hits a similar bug with the roxygen2 package.

sh: line 1: 72039 Segmentation fault      R_TESTS= '/opt/apps/intel18/impi18_0/Rstats/4.0.3/lib64/R/bin/R' --no-save --no-restore --no-echo 2>&1 < '/tmp/RtmpP7mwmq/file1181e6a3a8bad'
sh: $'\001': command not found

 *** caught segfault ***
address 0x7f04, cause 'memory not mapped'

Traceback:
 1: arg_match(.dir, c("forward", "backward"))
 2: purrr::detect_index(body, ~is_call(.x, "<-", 2) && is_symbol(.x[[2]],     "TWOARG"))
 3: make_as_character_rd()
 4: fun(libname, pkgname)
 5: doTryCatch(return(expr), name, parentenv, handler)
 6: tryCatchOne(expr, names, parentenv, handlers[[1L]])
 7: tryCatchList(expr, classes, parentenv, handlers)
 8: tryCatch(fun(libname, pkgname), error = identity)
 9: runHook(".onLoad", env, package.lib, package)
10: loadNamespace(package, lib.loc)
11: doTryCatch(return(expr), name, parentenv, handler)
12: tryCatchOne(expr, names, parentenv, handlers[[1L]])
13: tryCatchList(expr, classes, parentenv, handlers)
14: tryCatch({    attr(package, "LibPath") <- which.lib.loc    ns <- loadNamespace(package, lib.loc)    env <- attachNamespace(ns, pos = pos, deps, exclude, include.only)}, error = function(e) {    P <- if (!is.null(cc <- conditionCall(e)))         paste(" in", deparse(cc)[1L])    else ""    msg <- gettextf("package or namespace load failed for %s%s:\n %s",         sQuote(package), P, conditionMessage(e))    if (logical.return)         message(paste("Error:", msg), domain = NA)    else stop(msg, call. = FALSE, domain = NA)})
15: library(pkg_name, lib.loc = lib, character.only = TRUE, logical.return = TRUE)
16: withCallingHandlers(expr, packageStartupMessage = function(c) tryInvokeRestart("muffleMessage"))
17: suppressPackageStartupMessages(library(pkg_name, lib.loc = lib,     character.only = TRUE, logical.return = TRUE))
18: doTryCatch(return(expr), name, parentenv, handler)
19: tryCatchOne(expr, names, parentenv, handlers[[1L]])
20: tryCatchList(expr, classes, parentenv, handlers)
21: tryCatch(expr, error = function(e) {    call <- conditionCall(e)    if (!is.null(call)) {        if (identical(call[[1L]], quote(doTryCatch)))             call <- sys.call(-4L)        dcall <- deparse(call)[1L]        prefix <- paste("Error in", dcall, ": ")        LONG <- 75L        sm <- strsplit(conditionMessage(e), "\n")[[1L]]        w <- 14L + nchar(dcall, type = "w") + nchar(sm[1L], type = "w")        if (is.na(w))             w <- 14L + nchar(dcall, type = "b") + nchar(sm[1L],                 type = "b")        if (w > LONG)             prefix <- paste0(prefix, "\n  ")    }    else prefix <- "Error : "    msg <- paste0(prefix, conditionMessage(e), "\n")    .Internal(seterrmessage(msg[1L]))    if (!silent && isTRUE(getOption("show.error.messages"))) {        cat(msg, file = outFile)        .Internal(printDeferredWarnings())    }    invisible(structure(msg, class = "try-error", condition = e))})
22: try(suppressPackageStartupMessages(library(pkg_name, lib.loc = lib,     character.only = TRUE, logical.return = TRUE)))
23: tools:::.test_load_package("roxygen2", "/home1/00157/walling/R/x86_64-pc-linux-gnu-library/4.0/00LOCK-roxygen2/00new")
An irrecoverable exception occurred. R is aborting now ...
ERROR: loading failed
* removing ‘/home1/00157/walling/R/x86_64-pc-linux-gnu-library/4.0/roxygen2
________________________________

**Comment by hsbadr** [comment]
This confirms that it isn't a `ggplot2` issue. Try to install the development version of `rlang` using `pak`:
```r
install.packages("pak", repos = "https://r-lib.github.io/p/pak/dev/")
pak::pkg_install("r-lib/rlang")
```
 or `remotes`:
 ```r
 install.packages("remotes")
 remotes::install_github("r-lib/rlang")
 ```

**Comment by wallingTACC** [comment]
Wow, that seemed to work.  I was even able to install latest roxygen2 now with rlang 0.4.11.9000!

**Comment by hsbadr** [comment]
Great! I was expecting that after your last trace which points at `rlang::arg_match()`. Note that you may have to reinstall other packages that depend on `rlang`. I know that some of them may fail after the upgrade (e.g., `vctrs`).

**Comment by wallingTACC** [comment]
Thanks so much for you help!

**Comment by lionel-** [comment]
One explanation might be that you have a binary of rlang compiled for a version of R older than the one you are now running. Packages should generally be reinstalled after updating R.

Instead of installing the dev version of rlang from source, I'd try to install the CRAN version from source, especially if you have multiple users working in production. This is likely to fix the problem as well.
