### ISSUE TITLE
`ggsave()`: Optionally switch between `ragg` and `grDevices`

### ISSUE THREAD

**Issue by hsbadr** [tidyverse/ggplot2#4501]
Currently, `ragg` doesn't catch segmentation faults due to invalid `res`, `width`, `height`, `units`, ... etc. (see https://github.com/r-lib/ragg/issues/82). So, would it make sense to add sanity checks before calling the device or give an option to switch between `ragg` and `grDevices` by default (without specifying the `device` argument), even if `ragg` is available?
https://github.com/tidyverse/ggplot2/blob/6d94f0d6366c86147d3409a4b6e7e046d5b7e5b0/R/save.r#L180-L188

**Comment by yutannihilation** [comment]
If you are complaining about the compatibility with ragg, it's already fixed. Did you try the dev version?

https://github.com/tidyverse/ggplot2/pull/4388

**Comment by hsbadr** [comment]
> Did you try the dev version?

Yes. I'm not complaining; I'm just reporting that `ragg` causes segmentation fault with some devices (e.g., `png`) if any of `res`, `width`, `height`, or `units` is invalid. So, I'm requesting to add sanity checks before calling the device or give an option to disable `ragg` even if it's installed.
https://github.com/tidyverse/ggplot2/blob/6d94f0d6366c86147d3409a4b6e7e046d5b7e5b0/R/save.r#L180-L188

**Comment by clauswilke** [comment]
Please provide a reproducible example that triggers a segmentation fault.

**Comment by hsbadr** [comment]
@clauswilke I'm getting segmentation fault with the development version of `ggplot` when calling the `png` device, if `ragg` is installed. I'm on R-devel.

Here's the simple `ggplot` example:
```r
> library(ggplot2)
> p <- ggplot(mtcars, aes(mpg, wt)) + geom_point()
> ggsave("mtcars.png", plot = p)
Saving 7 x 7 in image

 *** caught segfault ***
address 0x38, cause 'memory not mapped'
```
<details>
<summary>Traceback:</summary>

```r
 1: grid.Call(C_stringMetric, as.graphicsAnnot(x$label))
 2: descentDetails.text(list(label = "gjpqyQ", x = 0.5, y = 0.5,     just = "centre", hjust = NULL, vjust = NULL, rot = 0, check.overlap = FALSE,     name = "GRID.text.19", gp = list(fontsize = 8.8, fontfamily = "",         fontface = NULL), vp = NULL))
 3: (function (x) {    UseMethod("descentDetails", x)})(list(label = "gjpqyQ", x = 0.5, y = 0.5, just = "centre",     hjust = NULL, vjust = NULL, rot = 0, check.overlap = FALSE,     name = "GRID.text.19", gp = list(fontsize = 8.8, fontfamily = "",         fontface = NULL), vp = NULL))
 4: grid.Call(C_convert, x, as.integer(whatfrom), as.integer(whatto),     valid.units(unitTo))
 5: convertUnit(x, unitTo, "y", "dimension", "y", "dimension", valueOnly = valueOnly)
 6: convertHeight(grobDescent(textGrob(label = "gjpqyQ", gp = gpar(fontsize = size,     cex = cex, fontfamily = family, fontface = face))), "inches")
 7: font_descent(gp$fontfamily, gp$fontface, gp$fontsize, gp$cex)
 8: title_spec(label, x = x, y = y, hjust = hjust, vjust = vjust,     angle = angle, gp = gp, debug = debug, check.overlap = check.overlap)
 9: titleGrob(label, x, y, hjust = hj, vjust = vj, angle = angle,     gp = modify_list(element_gp, gp), margin = margin, margin_x = margin_x,     margin_y = margin_y, debug = element$debug, ...)
10: element_grob.element_text(list(family = "", face = "plain", colour = "grey30",     size = 8.8, hjust = 0.5, vjust = 1, angle = 0, lineheight = 0.9,     margin = c(2.2, 0, 0, 0), debug = FALSE, inherit.blank = TRUE),     x = c(0.0299806576402321, 0.223404255319149, 0.416827852998066,     0.610251450676983, 0.8036750483559, 0.997098646034816), margin_y = TRUE,     label = c("10", "15", "20", "25", "30", "35"), check.overlap = FALSE)
11: (function (element, ...) {    UseMethod("element_grob")})(list(family = "", face = "plain", colour = "grey30", size = 8.8,     hjust = 0.5, vjust = 1, angle = 0, lineheight = 0.9, margin = c(2.2,     0, 0, 0), debug = FALSE, inherit.blank = TRUE), x = c(0.0299806576402321, 0.223404255319149, 0.416827852998066, 0.610251450676983, 0.8036750483559, 0.997098646034816), margin_y = TRUE, label = c("10", "15", "20", "25", "30", "35"), check.overlap = FALSE)
12: exec(element_grob, label_element, `:=`(!!position_dim, break_positions),     `:=`(!!label_margin_name, TRUE), label = break_labels, check.overlap = check.overlap)
13: draw_axis_labels(break_positions = break_positions[indices],     break_labels = break_labels[indices], label_element = label_element,     is_vertical = is_vertical, check.overlap = check.overlap)
14: FUN(X[[i]], ...)
15: lapply(dodge_indices, function(indices) {    draw_axis_labels(break_positions = break_positions[indices],         break_labels = break_labels[indices], label_element = label_element,         is_vertical = is_vertical, check.overlap = check.overlap)})
16: draw_axis(break_positions = guide$key[[aesthetic]], break_labels = guide$key$.label,     axis_position = guide$position, theme = theme, check.overlap = guide$check.overlap,     angle = guide$angle, n.dodge = guide$n.dodge)
17: guide_gengrob.axis(guide, theme)
18: guide_gengrob(guide, theme)
19: panel_guides_grob(panel_params$guides, position = "bottom", theme = theme)
20: f(...)
21: coord$render_axis_h(range, theme)
22: f(...)
23: self$facet$draw_panels(panels, self$layout, self$panel_scales_x,     self$panel_scales_y, self$panel_params, self$coord, data,     theme, self$facet_params)
24: f(..., self = self)
25: layout$render(geom_grobs, data, theme, plot$labels)
26: ggplot_gtable.ggplot_built(data)
27: ggplot_gtable(data)
28: print.ggplot(x)
29: print(x)
30: grid.draw.ggplot(plot)
31: grid.draw(plot)
32: ggsave("mtcars.png", plot = p)

Possible actions:
1: abort (with core dump, if enabled)
2: normal R exit
3: exit R without saving workspace
4: exit R saving workspace
```

</details>

Uninstalling `ragg` fixes the problem because it switches to `grDevices`.
https://github.com/tidyverse/ggplot2/blob/6d94f0d6366c86147d3409a4b6e7e046d5b7e5b0/R/save.r#L180-L188

Can you make the switch between `ragg` and `grDevices` optional? i.e., replacing `if (requireNamespace('ragg', quietly = TRUE))`.

**Comment by yutannihilation** [comment]
> So, I'm requesting to add sanity checks before calling the device or give an option to disable `ragg` even if it's installed.

Ah, OK. Sorry, I failed to see the context.

But I cannot reproduce your issue on R 4.1.0. Maybe it's somehow related to your installation of ragg package?

``` r
library(ggplot2)
p <- ggplot(mtcars, aes(mpg, wt)) + geom_point()
ggsave("mtcars.png", plot = p)
#> Saving 7 x 5 in image
```

<sup>Created on 2021-06-05 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by hsbadr** [comment]
> Maybe it's somehow related to your installation of ragg package?

Yes, I think it's related to the system libraries or the R options. I'm using `Cairo` with `x11` devices on a HPC server). Disabling my R profile fixes the problem too.

**Comment by hsbadr** [comment]
@clauswilke @yutannihilation Here's exactly why it fails with my R profile:
```r
# Set the default type of X11 devices to cairo
if (Sys.info()["sysname"] != "Windows") {
  setHook(
    packageEvent("grDevices", "onLoad"),
    function(...)
      grDevices::X11.options(type = 'cairo')
  )
}
```

**Comment by clauswilke** [comment]
I think we still need somebody else to reproduce this problem and/or have a concrete explanation of what is going wrong. The bug report started out with talking about invalid parameter inputs for the ragg devices, but I don't see how use of `ggsave()` with default parameters could lead to invalid parameter inputs.

I see two possibilities here:

1. It's something else that is going wrong
2. There is indeed some obscure situation under which `ggsave()` produces invalid parameter inputs. But it most likely depends on some other factor that we haven't identified yet. For example, does this only happen when using R devel?

**Comment by hsbadr** [comment]
@clauswilke Thanks you! With running into the same issue with simple cases, I think it's an `ragg` issue on some systems or R-devel (possibility # 1). Would it be possible to let the users decide if they want to use `ragg` by default? or maybe defaulting to `grDevices` while fully supporting the `ragg` devices?

That'd mean changing:
https://github.com/tidyverse/ggplot2/blob/6d94f0d6366c86147d3409a4b6e7e046d5b7e5b0/R/save.r#L180-L188

to:
```r
  png_dev <- grDevices::png
  jpeg_dev <- grDevices::jpeg
  tiff_dev <- grDevices::tiff
```

Then, `ragg` devices can be used with the `device` argument. Alternatively, a global option to prefer the default would do it.

**Comment by hsbadr** [comment]
> does this only happen when using R devel?

Yes, but I think it could be a combination of system libs (e.g., `libpng`) too since `ragg` passes the R-CMD-check on R-devel.

**Comment by hsbadr** [comment]
> have a concrete explanation of what is going wrong.

I'll let you know when I find the culprit.

**Comment by hsbadr** [comment]
@clauswilke FYI. The common thing between my environment and #4499 is building R with Intel compilers and MKL.

**Comment by yutannihilation** [comment]
Just curious. It seems ragg doesn't work at all on your environment. Why do you still want to keep it installed?

**Comment by hsbadr** [comment]
> Just curious. It seems ragg doesn't work at all on your environment. Why do you still want to keep it installed?

Good question. Other packages import/suggest it so it gets installed.

You're right; the problem here is `ragg` on my system, but this issue requests that at least it isn't used by default with `ggplot2::ggsave()`. I can specify the `device` to fix the problem, but that isn't an option when other packages call it.

**Comment by yutannihilation** [comment]
> Other packages import/suggest it so it gets installed.

Hmm, thanks. I'm not sure providing an option is the right way to fix this problem, but now I get your point.

**Comment by clauswilke** [comment]
We're using ragg by default now when available because other graphics devices have problems and generate a never-ending stream of bug reports, in particular for Windows users. If ragg doesn't compile/run on some platforms, then it's a ragg bug that needs to be fixed there. Also, if ragg doesn't work at all on your platform, then uninstalling it seems an appropriate action.

The only widely used package that imports (rather than suggests) ragg is pkgdown. So it might be worthwhile to file an issue there requesting they make it an optional dependency.

**Comment by hsbadr** [comment]
I see. Sounds good. Yes, it's a `ragg` issue, which is, I think, related to the system libs or permissions when accessing the graphics device. I didn't have enough time to debug it.

It's ok to close this issue if you wish. But, I'd prefer to check if `ragg` is *working* not just *available* before using it.

**Comment by hsbadr** [comment]
> other graphics devices have problems and generate a never-ending stream of bug reports, in particular for Windows users.

Maybe, use `ragg` if `requireNamespace('ragg', quietly = TRUE) & Sys.info()["sysname"] == "Windows"`? This would address the Windows-related issues and default to `grDevices` for the other systems.

**Comment by thomasp85** [comment]
No, ragg is the default if installed. While I can emphasise with your situation we will not roll back to a worse graphic device to address an issue of a single user when you have the option of passing in `png` as the device argument.

I'll be happy to investigate why ragg is failing on your system if you can somehow replicate the issue in a docker container or in some other way that makes it debuggable

**Comment by thomasp85** [comment]
If you do find a way to reproduce the issue outside of your system please open an issue in the ragg repo and we can take it from there

**Comment by hsbadr** [comment]
@clauswilke  @yutannihilation @thomasp85 FYI. I've been able to fix the segfault with `ragg` by cleanly building and **relinking** all packages, starting with a clean R-devel installation (empty `$R_HOME/library` directory). While I do upgrade all packages after building a new revision of R source, it seems that the version check (e.g., by `CheckBuilt = TRUE`) is not enough with a moving target (R-devel) that can introduce breaking changes at any time. Also, I think R doesn't properly and recursively relink library dependencies. So, if a package A links to B that links to C, R may need to relink A and B if C is upgraded.

@wallingTACC That might address #4499 too.

**Comment by mschnetzer** [comment]
Hi, please excuse that I comment on a closed issue. As @thomasp85 asked @hsbadr to reproduce the issue outside his system: I have similar problems with `ggsave()` and ragg. When I plot a figure with a custom font, `ggsave()` won't export the font into a PNG until i uninstall ragg. (When I manually export a PNG from the RStudio "Plots" window, it works, however). I just wanted to let you know that @hsbadr is not the only one with problems, but I am much less experienced with the technical backgrounds. Thank you!
