### ISSUE TITLE
How to add non-scientific p values on ggplot2 ?

### ISSUE THREAD

**Issue by DawnEve** [tidyverse/ggplot2#4505]
This works when using base R plot:
```
transPvalue=function(p0){
  #p0=1.2e-52; p0
  if(p0<0.01){
    p0=formatC(p0, format="e", digits=2);#p0 #"1.2e-52"
    # split by e
    p0=strsplit(p0, "e")[[1]]; #p0 #[1] "1.2" "-52"
    # plot
    label = bquote(italic(P)~"=" ~ .(p0[1]) ~ "\u00d7" ~ 10^.(p0[2]) )
  }else{
    p0=round(p0,3); #p0
    label = bquote(italic(P)~"=" ~ .(p0) )
  }
  return(label)
}
plot(1:3)
text(x=2, y=1.8, labels=transPvalue(1.56464e-26))
text(x=2, y=2.5, labels=transPvalue(0.0215466))
```

But this triggers a warning, and leaves a colorful blur around the p value when using ggplot2
```
library(ggplot2)
g=ggplot(iris, aes(Sepal.Length, Sepal.Width, color=Species))+
  geom_point(size=0.8)+theme_bw();g

g+annotate(geom="text", x=5, y=4.2, label=transPvalue(1.5e-26), color="black")



# I explored more, perhaps these three FALSE  makes p value draw 3 times at the same place, but how can I avoid it?

> is.na(transPvalue(1.5e-26))
[1] FALSE FALSE FALSE
Warning message:
In is.na(transPvalue(1.5e-26)) :
  is.na() applied to non-(list or vector) of type 'language'
```

I want to know how to proper add p value using non-scientific format to a ggplot2 figure?
Whether or not depend on method mentioned above is OK.
Thank you!
![ggplot2](https://user-images.githubusercontent.com/5974903/121329552-e4000680-c947-11eb-82ab-0672638e8505.png)

**Comment by DawnEve** [comment]
p.s.: No other reasons, but boss favors the non-scientific format of p value on figures.

**Comment by yutannihilation** [comment]
You cannot pass language to `label` aesthetic (you should have seen a warning for this). Instead, you can pass a text and specify `parse = TRUE`.

``` r
library(ggplot2)

g <- ggplot(iris, aes(Sepal.Length, Sepal.Width, color = Species)) +
  geom_point(size = 0.8) +
  theme_bw()

g + annotate(geom = "text", x = 5, y = 4.2, label = 'italic(P) ~ "=" ~ "1.50" ~ "×" ~ 10^"-26"', color = "black", parse = TRUE)
```
![](https://i.imgur.com/huISLhS.png)

<sup>Created on 2021-06-09 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

For future reference, this sort of question is a better fit for [RStudio Community](https://community.rstudio.com). Please ask there with a minimal reproducible example. We use this issue tracker for bug reports and feature requests. Thanks!

**Comment by DawnEve** [comment]
thank you very much. 
I'll record the new URL for future questions.
