### ISSUE TITLE
Cannot detect geom orientation in draw_key anymore

### ISSUE THREAD

**Issue by mjskay** [tidyverse/ggplot2#4506]
In {ggdist} I have been detecting the orientation of the geom when drawing legends inside `draw_key()`. I do this by checking the value of `params$orientation`, which has been working fine. However, I was just testing with the dev version of ggplot2 and this no longer works; `params$orientation` is now returning `NA` inside `draw_key()` unless it is set explicitly by the user.

## Expected output

Specifically, here is the github version of {ggdist} (`remotes::install_github("mjskay/ggdist")`) with the CRAN version of {ggplot2} (3.3.3):

``` r
library(ggdist)    # CRAN version or remotes::install_github("mjskay/ggdist")
library(ggplot2)   # CRAN version

ggplot(
  data.frame(g = c("a","b"), x = rnorm(1000, c(1,2))),
  aes(y = g, x = x, color = g)
) + 
  stat_pointinterval()
```

![](https://i.imgur.com/Xqkk2la.png)

<sup>Created on 2021-06-09 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

Note the orientation of the intervals in the legend matches the auto-detected orientation of the intervals in the geom.

## incorrect output on dev version of ggplot2 

Here is the output on the dev version of ggplot2, which appears to be because `params$orientation` is `NA` inside the key function (even though it is detected correctly in `setup_params()`):

``` r
library(ggdist)    # remotes::install_github("mjskay/ggdist")
library(ggplot2)   # remotes::install_github("tidyverse/ggplot2")

ggplot(
  data.frame(g = c("a","b"), x = rnorm(1000, c(1,2))),
  aes(y = g, x = x, color = g)
) + 
  stat_pointinterval()
```

![](https://i.imgur.com/pW3TmhO.png)

<sup>Created on 2021-06-09 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

## workaround

It is possible to work around this by manually setting the orientation:

``` r
library(ggdist)    # remotes::install_github("mjskay/ggdist")
library(ggplot2)   # remotes::install_github("tidyverse/ggplot2")

ggplot(
  data.frame(g = c("a","b"), x = rnorm(1000, c(1,2))),
  aes(y = g, x = x, color = g)
) + 
  stat_pointinterval(orientation = "y")
```

![](https://i.imgur.com/t2w9RE9.png)

<sup>Created on 2021-06-09 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

Is there another (more correct) way to detect geom orientation in `draw_key`? Or is this not a thing that should be done in the first place?

**Comment by smouksassi** [comment]
this also concerns ggplot geoms lacking a horizontal legend and no auto-detection e.g geom_boxplot:
(the geom_boxploth from ggstance had its own draw_key:
``` r
library(ggplot2)
library(ggstance)
#> 
#> Attaching package: 'ggstance'
#> The following objects are masked from 'package:ggplot2':
#> 
#>     geom_errorbarh, GeomErrorbarh
library(patchwork)

set.seed(9008)
plotdata <-   data.frame(g = c("a","b"), x = rnorm(1000, c(1,2)))
p1 <- ggplot(plotdata,
  aes(y = g, x = x, color = g)
) + 
  geom_boxplot()

p2 <- ggplot(
  plotdata,
  aes(y = x, x = g, color = g)
) + 
  geom_boxplot()

p3 <- ggplot(
  plotdata,
  aes(y = g, x = x, color = g)
) + 
  geom_boxploth()
p2+p1+p3
```

![](https://i.imgur.com/r5N4EYc.png)

<sup>Created on 2021-06-09 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by thomasp85** [comment]
Can you check against the v3.3.4-rc branch. I think I touched some of that during revdepcheck fixing...

**Comment by mjskay** [comment]
ah great, that works, thanks!

(seeing some other things changed though I'll have to investigate...)

**Comment by thomasp85** [comment]
Phew😅
