### ISSUE TITLE
Add filter param within aes()

### ISSUE THREAD

**Issue by rjake** [tidyverse/ggplot2#4508]
`ggforce` has a filtering param in the `aes()` mapping that I find really helpful. ([examples](https://ggforce.data-imaginist.com/reference/geom_mark_rect.html#examples), [source code](https://github.com/thomasp85/ggforce/blob/1f17eb3cdb0ef54a6ed5dcb77ef5fecb195c90e4/R/mark_ellipse.R#L83-L89)) With 4.1, I'm trying to phase out `%>%` in as many places as possible. 

I can use the `magrittr` pipe like this
`geom_text(data = . %>% filter(a == b))`
but I can't use this
`geom_text(data = filter(., a == b))`
or 
`geom_text(data = . |> filter(a == b))`  -- I know this is expected this to fail
<br>
Would it be possible to add a filter param so that I could write
`geom_text(aes(filter = (a == b)))` 
<br>
This is a common workflow that lets me avoid adding objects to my global environment. I use `. %>% filter()` to keep the factor levels and aggregations that I established
```r
library(tidyverse)

mpg |> 
  count(class) |> 
  mutate(class = fct_reorder(class, n)) |> 
  ggplot(aes(n, class, label = n)) +
  geom_col(fill = "lightblue") +
  geom_text(data = . %>% filter(n %in% range(n)))

```
![image](https://user-images.githubusercontent.com/14003618/121685332-cb9a0400-ca8d-11eb-8425-50881f504fcd.png)

With `ggforce`, filtering looks like this:
```r
ggplot(mpg, aes(cty, hwy)) +
  ggforce::geom_mark_rect(aes(filter = hwy > 40)) +
  geom_point()
```
![image](https://user-images.githubusercontent.com/14003618/121687082-ee2d1c80-ca8f-11eb-9f40-30b9eca45a20.png)

**Comment by rjake** [comment]
I just realized that formulas are supported. Great job y'all 🏆🥇 
I'll leave this open in case you want to add anything before closing the issue.
```r
library(tidyverse)

mpg |> 
  count(class) |> 
  mutate(class = fct_reorder(class, n)) |> 
  ggplot(aes(n, class, label = n)) +
  geom_col(fill = "grey80") +
  geom_text(data = ~filter(.x, n %in% range(n)))
  #               |-----------|

**Comment by bwiernik** [comment]
You can also use base R anonymous function (`function(...)` or `\(...)`):

``` r
library(tidyverse)
mpg |> 
    count(class) |> 
    mutate(class = fct_reorder(class, n)) |> 
    ggplot() +
    aes(x = n, y = class, label = n) +
    geom_col(fill = "grey80") +
    geom_text(data = \(x) filter(x, n %in% range(n)))
```

![](https://i.imgur.com/Hi0JR1D.png)

<sup>Created on 2021-06-28 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by yutannihilation** [comment]
We might need a better documentation about where we can use the `~` lambda notation. Honestly, I forgot `data` accepts `~` while this is the feature I added (c.f. #3245)... :sweat_smile:

**Comment by bwiernik** [comment]
With the advent of convenient lambda functions in base R, it might be worthwhile to describe in the docs as simply "a function transforming the original data frame", perhaps with examples with the `~` and `\(...)` syntaxes

**Comment by yutannihilation** [comment]
Thanks, I too want to push native lambda syntax, but I think, unfortunately, tidyverse cannot be that modern to use the syntax because it's committed to providing support for older R versions before 4.1.

**Comment by bwiernik** [comment]
`function(...)` is also a possibility

**Comment by hadley** [comment]
The documentation already has:

> A function will be called with a single argument, the plot data. The return value must be a data.frame, and will be used as the layer data. A function can be created from a formula (e.g. `~ head(.x, 10`)).

Given the specialised nature of this usage, I think this is probably adequate.
