### ISSUE TITLE
Odd behavior when grouping values for geom_ribbon

### ISSUE THREAD

**Issue by mcooper** [tidyverse/ggplot2#4512]
I've accidentally discovered some odd behavior with grouping variables with geom_ribbon.  

I am graphing regression outputs, where the value of y varies based on two different factor variables.  I'm visualizing these effects with lines, using a `color` aesthetic for one variable (`var1`), and a `linetype` aesthetic for the other variable (`var2`).  

I also have error bands that I am visualizing with `geom_ribbon`, and I want these error bands to be colored by `var1`, but have a separate error band for both `var1` and `var2`.

The problem is, only adding a `fill` aesthetic for `var1` makes a bad graph.  So I added a `group` aesthetic corresponding to `var2`, except I made a typo and only wrote "`grou`".  This somehow worked and only threw a warning.  But then, when I fixed the typo, it failed with an "Aesthetics can not vary with a ribbon" error!

I guess since the code works with a typo, this isnt an issue for me, but I figured it was something you all should know about!

I have ggplot 3.3.2.  Below should be a suitable reprex.

```r
library(tidyverse)

df <- expand.grid(var1=c("A", "B", "C"), var2=c("a", "b", "c"), x=seq(1, 100))

df <- df %>%
  mutate(y = x*case_when(var1 == 'A' ~ 1,
                        var1 == 'B' ~ 2,
                        var1 == 'C' ~ 3) + 
             x*case_when(var2 == 'a' ~ 10,
                        var2 == 'b' ~ 20,
                        var2 == 'c' ~ 30),
         ymax = y + y*0.01,
         ymin = y - y*0.01)

#This makes a bad ribbon
ggplot(df) + 
  geom_line(aes(x=x, y=y, color=var1, linetype=var2)) + 
  geom_ribbon(aes(x=x, ymin=ymin, ymax=ymax, fill=var1), alpha=0.2)

#This fails with "Error: Aesthetics can not vary with a ribbon"
ggplot(df) + 
  geom_line(aes(x=x, y=y, color=var1, linetype=var2)) + 
  geom_ribbon(aes(x=x, ymin=ymin, ymax=ymax, fill=var1, group=var2), alpha=0.2)

#This works (!?), but gives a warning for unknown aesthetic 'grou'
ggplot(df) + 
  geom_line(aes(x=x, y=y, color=var1, linetype=var2)) + 
  geom_ribbon(aes(x=x, ymin=ymin, ymax=ymax, fill=var1, grou=var2), alpha=0.2)

```

**Comment by yutannihilation** [comment]
Not sure what result you want, but you should specify the combination of `var1` and `var2` (e.g., `paste(var1, var2)`) to `group`. As the error suggests, a group cannot have multiple `fill` values.

When you don't specify, the group is implicitly determined by using all discrete variables. This is why the last typo code works.

**Comment by twest820** [comment]
I hit this earlier today, without making typos, and it seemed worth mentioning the error message can get cryptic.
```R
# works fine even though fill varies "within" several ribbons
ggplot() + geom_ribbon(aes(x = x, y = y, fill = groupingDimension1)) 
# fails with Error: Aesthetics can not vary with a ribbon even though the call above works just fine with fill varying "within" a ribbon due to the implicit group construction @yutannihilation mentions that's transparent to the user
ggplot() + geom_ribbon(aes(x = x, y = y, fill = groupingDimension1, group = groupingDimension2)) 
```

I think there's maybe two underlying issues here.

1. Using `geom_ribbon()` with grouping dimensions is probably drawing several separate ribbons on the plot. The error refers to this as variation within ribbons when, from a user perspective, it's variation across the different ribbons being drawn (especially if the ribbons are in distinct parts of the plot and don't touch each other). The error text would probably be clearer if it dispensed with the within ribbon concept and just indicated `geom_ribbon()` with `group` requires the `fill` dimension also be included within `group`.
2. Other geoms don't have this requirement that I've noticed, so it seems odd `geom_ribbon()` imposes it. A more desirable change could be to remove the error condition by creating more consistent behavior.
