### ISSUE TITLE
Error: Can't add `ggplot2::ggsave(...)` to a ggplot object

### ISSUE THREAD

**Issue by richelbilderbeek** [tidyverse/ggplot2#4517]
Dear ggplot2 maintainer,

I just updated my version of the ggplot2 master branch ([this version](https://github.com/tidyverse/ggplot2/commit/de5d63f7eba06e507187f34780bea071cb31fee4)), after which I cannot save plots anymore.

For example, this code ...

```r
# Create trivial data
t <- tibble::tibble(x = 1, y = 2)

# Plot and save
ggplot2::ggplot(t, ggplot2::aes(x, y)) + ggplot2::geom_point() + ggplot2::ggsave("temp.png", width = 7, height = 7)
```

gives the error:

```
Error: Can't add `ggplot2::ggsave("temp.png", width = 7, height = 7)` to a ggplot object.
```

I expected my plot to be saved to a file.

Cheers, Richel

**Comment by clauswilke** [comment]
This code is not valid and only worked in the past by accident. See #4513.

**Comment by richelbilderbeek** [comment]
Ah, thanks so much @clauswilke, I will use the other way of writing now :-)
