### ISSUE TITLE
ggsave error with type="cairo" or type="cairo-png"

### ISSUE THREAD

**Issue by martin-a-wade** [tidyverse/ggplot2#4524]
ggsave produces an error when including  type="cairo" or type="cairo-png", which worked in ggplot2 <=3.3.3.
(R4.0.3, Windows 10)

```r
library(ggplot2)
p <- ggplot(mpg, aes(cty, hwy)) + geom_point()
ggsave("test.png", type = "cairo")
# also error for:
# ggsave("test.png", type = "cairo-png")
```
Error in png_dev(..., res = dpi, units = "in") :
  unused argument (type = "cairo")

**Comment by tungmilan** [comment]
I am having the same problem. Pretty much all of my scripts have `cairo` inside `ggsave` and now return errors

**Comment by clauswilke** [comment]
Should already be fixed. Please reinstall ggplot2 from CRAN and try again.

**Comment by thomasp85** [comment]
No, this has not been fixed as it really isn't a bug (I do understand the inconvenience)

**Comment by clauswilke** [comment]
I thought you turned the error into a warning? Am I confused?

https://github.com/tidyverse/ggplot2/pull/4525/commits/05f63cd79756be41d965eeb8a02cde555dde0a28

**Comment by thomasp85** [comment]
Oh yeah, sorry. Confused myself

**Comment by clauswilke** [comment]
@martin-a-wade and @tungmilan Could you update your ggplot to 3.3.5 and let us know whether your scripts now work (except a warning that is issued)?

**Comment by martin-a-wade** [comment]
Thanks, the update works for me.

**Comment by tungmilan** [comment]
Confirmed! Thank you guys!
