### ISSUE TITLE
Feature request: tune bins in geom_density_2d() by strata in case facet_wrap is specified

### ISSUE THREAD

**Issue by aloboa** [tidyverse/ggplot2#4529]
Please see https://stackoverflow.com/questions/68099068/weird-result-of-facet-wrap-with-geom-density-2d/68102454#68102454

**Comment by clauswilke** [comment]
See #4465.

**Comment by aloboa** [comment]
I understand the use of grid.arrange() suggested in #4465 is a workaround, but why not accepting the feature request that the same result could be achieved using facet_warp(), which is the standard way of addressing these issues in ggplot?

**Comment by clauswilke** [comment]
The feature you're requesting has already been implemented, it is described and demonstrated in the documentation, and it is also demonstrated in #4465.

**Comment by aloboa** [comment]
> The feature you're requesting has already been implemented, it is described and demonstrated in the documentation, and it is also demonstrated in #4465.

True. Thank you and apologies.  I overlooked the `contour_var="ndensity"` in p4.  
Regarding the help page, I find the information on this parameter insufficient and obscure in the text, although the example clarifies its use.
