### ISSUE TITLE
I can't use ggtern to draw graph after updated the new vision of ggplot2

### ISSUE THREAD

**Issue by Skywings96** [tidyverse/ggplot2#4531]
I updated the latest version of ggplot2 today. I find that I cannot draw graph use ggtern package. The wrong message is :"geom_point requires the following missing aesthetics: x and y.'' But I have defined x and y variables , I don't know how to fix it.

**Comment by thomasp85** [comment]
You'll need to talk to the ggtern developer about this. It not a ggplot2 issue

**Comment by Skywings96** [comment]
> d

Thanks very much, I will some way to contact with them.
