### ISSUE TITLE
I find my Macbook Air M1 cannot install ggplot2

### ISSUE THREAD

**Issue by Skywings96** [tidyverse/ggplot2#4532]
I cannot install ggplot2 on my Macbook Air M1,the wrong message is as follow:

Error in library.dynam(lib, package, package.lib) : 
  共享目标对象‘colorspace.so’不存在
Calls: <Anonymous> ... loadNamespace -> namespaceImport -> loadNamespace -> library.dynam
停止执行"

**Comment by Skywings96** [comment]
My colorspace package seems have some faults :
>library(colorspace)
错误: package or namespace load failed for ‘colorspace’ in library.dynam(lib, package, package.lib):
 共享目标对象‘colorspace.so’不存在

**Comment by yutannihilation** [comment]
Hi, it doesn't seem an issue on ggplot2's side. Did you try reinstalling colorspace package, because the problem is probably that there's something wrong with the package?

**Comment by Skywings96** [comment]
> Hi, it doesn't seem an issue on ggplot2's side. Did you try reinstalling colorspace package, because the problem is probably that there's something wrong with the package?

**Comment by Skywings96** [comment]
> Hi, it doesn't seem an issue on ggplot2's side. Did you try reinstalling colorspace package, because the problem is probably that there's something wrong with the package?
This problem has been fixed, because I install the wrong vision of R language on my M1computer. After I installed the right vision ,the problem has been solved, thanks for your comment！

**Comment by Skywings96** [comment]
This problem has been fixed, because I install the wrong vision of R language on my M1computer. After I installed the right vision ,the problem has been solved, thanks for your comment！

**Comment by Skywings96** [comment]
This problem has been fixed, because I install the wrong vision of R language on my M1computer. After I installed the right vision ,the problem has been solved, thanks for your comment！

**Comment by yutannihilation** [comment]
Glad you fixed it! :tada:
