### ISSUE TITLE
.theme pronoun for accessing theme elements (e.g., colors)

### ISSUE THREAD

**Issue by bwiernik** [tidyverse/ggplot2#4535]
In a package I'm developing, I would occasionally like to set geom parameters, such as colors, to have the same values as theme elements. For example, to use the same color for geom_line() as for the axis lines or the panel background. I would like to be able to set this while still allowing the theme to be changed later, with the geom parameters changing to match. It would be really helpful to have a `.theme` pronoun that could refer to whatever theme is set for a plot. 

Example:

``` r
library(ggplot2)

# set line colors to match panel backgound
ggplot(mtcars) +
  aes(x = mpg) +
  geom_histogram(
    color = .theme$panel.background$fill
    # currently must be:
    # color = theme_bw()$panel.background$fill
  ) +
  theme_bw()
#> `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
```

![](https://i.imgur.com/SRSY8J3.png)

``` r
# set line color to match theme line colors
ggplot(mtcars) +
  aes(x = disp, y = mpg) +
  geom_point() +
  geom_smooth(
    se = FALSE, 
    color = .theme$line$colour
    # currently must be:
    # color = ggthemes::theme_economist()$line$colour
  ) +
  ggthemes::theme_economist()
#> `geom_smooth()` using method = 'loess' and formula 'y ~ x'
```

![](https://i.imgur.com/NGrxNs7.png)

Potentially related to https://github.com/tidyverse/ggplot2/issues/2691

**Comment by clauswilke** [comment]
There's a longstanding PR (#2749) that I believe would provide the features you need (though using a somewhat different approach). It was never completed because there are some difficult technical issues that we couldn't resolve and where any resolution we could think of would cause a breaking change. Hopefully some day we can get this done.

**Comment by bwiernik** [comment]
That would get most the way there, but wouldn't for example, permit the first example there (make the lines of the histogram bars the same color as the panel background)

**Comment by hadley** [comment]
Closing because I don't think there's much point thinking about it until the first upgrade to `theme()` is implemented.
