### ISSUE TITLE
Error in FUN(X[[i]], ...) : objet 'Traitement' introuvable

### ISSUE THREAD

**Issue by Hraelsveg** [tidyverse/ggplot2#4538]
Hi everyone, 
I have a terrible error message with ggplot2 in Rstudio and i need you to solve it.

The code is here :

> library(multcompView)
> library(multcomp)
> library(ggplot2)
> library(Hmisc)

> data=read.table("Hyphae_density.txt",header=T)

#Comparer 2 à 2
> Ttest=pairwise.t.test(data$Density, data$Traitement, p.adjust.method ="bonferroni") #y-x, BH pour FDR en p.adjust.method
> Ttest

> #Fonction
> tri.to.squ<-function(x)
> {
>   rn <- row.names(x)
>   cn <- colnames(x)
>   an <- unique(c(cn,rn))
>   myval <-  x[!is.na(x)]
>   mymat <-  matrix(1,nrow=length(an),ncol=length(an),dimnames=list(an,an))
>   for(ext in 1:length(cn))
>   {
>     for(int in 1:length(rn))
>     {
>       if(is.na(x[row.names(x)==rn[int],colnames(x)==cn[ext]])) next
>       mymat[row.names(mymat)==rn[int],colnames(mymat)==cn[ext]]<-x[row.names(x)==rn[int],colnames(x)==cn[ext]]
>       mymat[row.names(mymat)==cn[ext],colnames(mymat)==rn[int]]<-x[row.names(x)==rn[int],colnames(x)==cn[ext]]
>     }
>     
>   }
>   return(mymat)
> }

# transformation de la matrice triangulaire de p-values en une matrice rectangulaire
> mymat <-tri.to.squ(Ttest$p.value)
> mymat
# création des lettres correspondant à chaque moyenne
> myletters <- multcompLetters(mymat,compare="<=",threshold=0.05,Letters=letters)
> myletters
# conserver les lettre dans un data.frame
> myletters_df <- data.frame(group=names(myletters$Letters),letter = myletters$Letters )
> myletters_df

#Visualisation des donnees:
> ggplot(data, aes(x=`Traitement`, y=Density,colour=Traitement,fill=Traitement)) +
>   geom_boxplot(alpha=0.5, outlier.alpha=0) +
>   scale_fill_manual(values=c("orange","blue","darkolivegreen3")) +
>   scale_colour_manual(values=c("orange","blue","darkolivegreen3")) +
>   geom_jitter(size=2.5,width=0.25)+
>   theme_classic(base_size = 25) +
>   labs(title="Densité des hyphes",x ="", y = "Densité (µm/µm²) ") +       
>   scale_x_discrete(labels=c("Ac" = "Acétate", "M" = "M","Myr" = "Myristate")) +  
>   theme(legend.position = "none") +
>   geom_text(data = myletters_df, aes(label = letters, y = 0.03 ), colour="black", size=8) +
> stat_summary(fun.data=mean_sdl, fun.args = list(mult = 0.5),geom="pointrange", color= "red",alpha=1)

**The error is : Error in FUN(X[[i]], ...) : objet 'Traitement' introuvable**

**Comment by yutannihilation** [comment]
This sort of question is a better fit for [RStudio Community](https://community.rstudio.com). Please ask there with a minimal reproducible example. We use this issue tracker for bug reports and feature requests.

(I guess the problem is that `myletters_df` doesn't contain `Traitement` and you probably need to provide `x` for that `geom_text()` layer)
