### ISSUE TITLE
margin-reference: Page not found (404)

### ISSUE THREAD

**Issue by thuettel** [tidyverse/ggplot2#4540]
I'm frequently visiting the [reference for ggplot2 theme options](https://ggplot2.tidyverse.org/reference/theme.html). For a couple of days already the link to the [margin reference](https://ggplot2.tidyverse.org/reference/margin.html) which sits behind components like `element_text()` or `element_rect()` is not working any more and just showing the error message `Page not found (404)`.

I tried different OS (Windows/Mac), different Browsers (Firefox/Opera) and also deleting the Browser Cache.

**Comment by yutannihilation** [comment]
The correct page is here:

https://ggplot2.tidyverse.org/reference/element.html

The `rdname` of `margin` has been `element` from 5 years ago. So, there should be some change on pkgdown's side...?

https://github.com/tidyverse/ggplot2/blob/acaa98e4cfcd922a737f35c16ec3dd6079aab3dc/R/margins.R#L4

As the page is linked correctly from the reference page, let me close this issue. Thanks for reporting!

**Comment by yutannihilation** [comment]
Ah, sorry. I misunderstood your point. Those cross reference links are broken, which is a bit annoying. Anyway all we can do is just to wait for the fix on the pkgdown's side, but let's reopen.

![image](https://user-images.githubusercontent.com/1978793/124339300-a14ce980-dbe8-11eb-8513-74290f735955.png)

**Comment by yutannihilation** [comment]
Seems this one.

https://github.com/r-lib/pkgdown/issues/1730

**Comment by maelle** [comment]
I think it's a different issue, will open another one (the issue linked is about linking vignettes not topics).
