### ISSUE TITLE
theme(axis.text, ...) does not inherit from theme(text, ...).

### ISSUE THREAD

**Issue by davidhodge931** [tidyverse/ggplot2#4544]
Documentation says that theme(axis.text, ...) inherits from theme(text, ...).

![image](https://user-images.githubusercontent.com/55065152/124525032-a95b9200-de51-11eb-84c8-2d539de46659.png)

But it doesn't seem to...

```r
library(ggplot2)
library(palmerpenguins)

ggplot(penguins) +
  geom_point(aes(bill_length_mm, body_mass_g, col = species)) +
  ggtitle("hello") +
  theme(text = element_text(colour = "red")) 
```
![image](https://user-images.githubusercontent.com/55065152/124525068-d8720380-de51-11eb-9664-2cdee6c7db9d.png)

**Comment by clauswilke** [comment]
The axis text color in the default theme is set explicitly (to a dark gray), that's why it doesn't inherit. The documentation is correct.

``` r
library(ggplot2)

theme_gray()$axis.text$colour
#> [1] "grey30"
```

<sup>Created on 2021-07-05 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by clauswilke** [comment]
To elaborate: if you create a theme that doesn't have this color setting then it behaves as you (I assume) expected.

``` r
library(ggplot2)
library(palmerpenguins)

mytheme <- theme_gray() %+replace%
  theme(axis.text = element_text(size = rel(0.8)))

ggplot(penguins) +
  geom_point(aes(bill_length_mm, body_mass_g, col = species)) +
  ggtitle("hello") +
  mytheme +
  theme(text = element_text(colour = "red")) 
#> Warning: Removed 2 rows containing missing values (geom_point).
```

![](https://i.imgur.com/ZF02mk9.png)

<sup>Created on 2021-07-05 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by davidhodge931** [comment]
Thanks for the explanation
