### ISSUE TITLE
`ggsave` returning filename string breaks unintended usage with `+`

### ISSUE THREAD

**Issue by hesscl** [tidyverse/ggplot2#4549]
There previously was an unintended or undocumented usage of `ggsave()` where it could be added to a `ggplot()` using `+`. This depended on `ggsave()` returning `NULL`, which appears to have been changed in #3379 to where it now returns the filepath of the saved graphic. This matter is discussed some [here](https://stackoverflow.com/questions/68003633/error-cant-add-ggsave-to-a-ggplot-object) on StackOverflow and I thought I would mention it here since it appeared no one had yet. 

The #3379 discussion suggested some ambivalence about needing ggsave() to return filepaths, so to the extent that it is breaking some folks code I wondered if reverting might be worth consideration, even if this usage was not intended to begin with. From my experience the below code actually works and saves the image still, though it provides an error `Error: Can't add `ggsave(filename = "./blah.png")` to a ggplot object.`. Either breaking this functionality completely or reverting to it being OK despite being unorthodox seems like it would help clarify acceptable ways of using this function.

```r
library(ggplot2)

ggplot(iris, aes(x = Sepal.Length, y = Petal.Length)) +
  geom_point() +
  ggsave(filename = "./blah.png")
```

**Comment by clauswilke** [comment]
See #4513, #4517, and this blog post: https://www.tidyverse.org/blog/2021/06/off-label-uses-in-ggplot2/
