### ISSUE TITLE
English/American spelling of centre/center in geom_histogram

### ISSUE THREAD

**Issue by woodwards** [tidyverse/ggplot2#4554]
I notice that geom_histogram only accepts the American spelling of center. I like that tidyverse generally accepts both American and English spellings, and wondered whether "centre" can be added as an alias for "center"? Thanks.

**Comment by jdonland** [comment]
The use of "center" as an argument has proliferated somewhat across the tidyverse since this issue was opened. Any chance of revisiting it? It strikes me as odd that the tidyverse works with both Commonwealth and American spellings, except for "centre".

**Comment by hadley** [comment]
I don't think it's worth it, sorry. Working with multiple spellings was a mistake that we don't want to replicate elsewhere.
