### ISSUE TITLE
facet_grid(switch) disables strip text angle control

### ISSUE THREAD

**Issue by jonspring** [tidyverse/ggplot2#4557]
I expect to be able to adjust the angle of my strip text even if I have switched its position. 

Without the `switch` parameter, the theme call works as expected, with red text and horizontal alignment.
```
library(ggplot2)
ggplot(mtcars, aes(wt, mpg)) +
  geom_point() +
  facet_grid(cyl~.) +
  theme(strip.text.y = element_text(color = "red", angle = 0)) 
```
![Rplot212](https://user-images.githubusercontent.com/18709859/126006676-7c2a25f5-0587-403d-99a1-1df51d607c82.png)

The `switch` parameter successfully brings the strip to the left side of the plot, but only the color part of the theme call is working; the angle is no longer updated.

```
ggplot(mtcars, aes(wt, mpg)) +
  geom_point() +
  facet_grid(cyl~., switch = "y") +
  theme(strip.text.y = element_text(color = "red", angle = 0)) 
```
![Rplot213](https://user-images.githubusercontent.com/18709859/126006684-c8c8e100-f65c-4136-ad8f-0f08e24e3b72.png)

Using ggplot 3.3.5

**Comment by clauswilke** [comment]
Please watch:
https://resources.rstudio.com/resources/rstudioglobal-2021/always-look-on-the-bright-side-of-plots/

**Comment by karawoo** [comment]
tl;dw the theme you are using sets `strip.text.y.left` explicitly, so you need to override that, not `strip.text.y`.

**Comment by jonspring** [comment]
Aha, that rings a bell. Thanks so much!
