### ISSUE TITLE
scaling at two levels grouping in ggplot?

### ISSUE THREAD

**Issue by marwa38** [tidyverse/ggplot2#4568]
I have three different phases (challenge, intermediate, and stimulus) and four different parts (distal, middle, and pyloric for the challenge; distal for the intermediate; whole for the stimulus) so I have two levels (treatment and part) which I need to appear in my ggplot The problem is that the distal appears in ggplot but doesn't mention if it is distal of intermediate or challenge, I think it merges both together.

ggplot(ps_phylum, aes(x = part, y=Abundance, color = Phlyum, group = Phylum)) +
stat_smooth(method = "loess") +
ylab("Relative Abundance") +
geom_point(size = 1.25, alpha = 0.4)

Could you please advise me on this? have tried facet_wrap and scaling funcitons without help. 

![image](https://user-images.githubusercontent.com/68851733/127496390-52f2d2dd-c19a-496b-84ec-d40b7c58bc7b.png)

**Comment by karawoo** [comment]
This type of question is a better fit for [RStudio Community](https://community.rstudio.com/). I'd suggest asking there with a [reproducible example](https://reprex.tidyverse.org/). This issue tracker is intended for bug reports and feature requests.
