### ISSUE TITLE
NA "fill" through scale_fill_manual produces a gray fill instead of blank/transparent "color"

### ISSUE THREAD

**Issue by RViking** [tidyverse/ggplot2#4569]
I've recently updated ggplot2 (3.3.5  - way behind the curve, I know) so I have not seen this before. Sometimes, it's useful to use "NA" to generate a blank color for some geom, like this:

``` r
library(ggplot2)
ggplot(mpg) + 
  geom_bar(
    aes(x = drv, colour = stage(start = drv, after_scale = alpha(colour, 0.5))), 
    fill = NA, size = 4)
```

![](https://i.imgur.com/h5mWLzq.png)

<sup>Created on 2021-07-29 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

However, when I specify the fill color for the specific categories using scale_fill_manual, I now get this:

``` r
library(ggplot2)
ggplot(mpg) + 
  geom_bar(data = mpg,
    aes(
      x = drv, fill = drv,
      colour = stage(start = drv, after_scale = alpha(colour, 0.5))
    ),  size = 4
  ) + scale_fill_manual(values = c("4" = NA, "f" = NA, "r" = NA))
```

![](https://i.imgur.com/bpDFONy.png)

<sup>Created on 2021-07-29 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

What is the problem here? Is this the intended functionality? I could workaround this by specifying the alpha for each category, but this would require some major code renovations.

**Comment by RViking** [comment]
So, perhaps this was updated recently, but apparently `scale_fill_manual` has a parameter for the `na.value`. It looks like it set to "grey50" by default. Setting it to `NA`, has the desired effect: 

``` r
library(ggplot2)
ggplot(mpg) + 
  geom_bar(data = mpg,
    aes(
      x = drv, fill = drv,
      colour = stage(start = drv, after_scale = alpha(colour, 0.5))
    ),  size = 4
  ) + scale_fill_manual(values = c("4" = NA, "f" = NA, "r" = NA), na.value = NA)
```

![](https://i.imgur.com/TMMZpsI.png)

<sup>Created on 2021-07-29 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by tdhock** [comment]
another work-around is to use "transparent" instead of NA as the color specification,
```r
ggplot(mpg) + 
  geom_bar(
    aes(x = drv, colour = stage(start = drv, after_scale = alpha(colour, 0.5))), 
    fill = "transparent", size = 4)
```
