### ISSUE TITLE
Can't control x-axis/longitude labeling with geom_sf

### ISSUE THREAD

**Issue by mbrousil** [tidyverse/ggplot2#4571]
I have a map built on `geom_sf()`. It recently started plotting differently, and I'm no longer able to control the labeling of the x-axis (longitude). Latitude seems to work as expected. The plot I'm expecting looks like this:
<img src="https://community.rstudio.com/uploads/default/original/3X/f/0/f0b1eb645a8027372b10ec5cf411209b7f7a5745.png"  width="600"/>

But in the reprex below you can see that longitude isn't being labeled correctly.

Based on responses to my [Community](https://community.rstudio.com/t/difficulty-labeling-longitude-with-geom-sf/111099) post I tried reinstalling `sf`, `tidyverse`, `ggplot2` and switching from R `4.1.0` to `4.0.2`, but could not solve the issue. Thanks in advance for any insight!

``` r
library(tidyverse)
library(sf)
#> Linking to GEOS 3.9.0, GDAL 3.2.1, PROJ 7.2.1
library(rnaturalearth)

ggplot() +
  geom_sf(data = ne_countries(returnclass = "sf"),
          fill = "gray90", color = NA) +
  geom_sf(data = ne_coastline(returnclass = "sf")) +
  ylab("") +
  xlab("") +
  theme_bw() +
  coord_sf(expand = FALSE) +
  scale_x_continuous(breaks = seq(from = -180, to = 180, by = 60))
```

![](https://i.imgur.com/nL4IR7g.png)

``` r
ggplot() +
  geom_sf(data = ne_countries(returnclass = "sf"),
          fill = "gray90", color = NA) +
  geom_sf(data = ne_coastline(returnclass = "sf")) +
  ylab("") +
  xlab("") +
  theme_bw() +
  coord_sf(expand = FALSE)
```

![](https://i.imgur.com/MtpwjBI.png)

<sup>Created on 2021-07-30 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by clauswilke** [comment]
I can confirm this. Something has happened to the graticule. 

The x-axis ticks reappear when I decrease the y axis range, but the graticule is still missing.
``` r
library(tidyverse)
library(sf)
#> Linking to GEOS 3.8.1, GDAL 3.2.1, PROJ 7.2.1
library(rnaturalearth)

ggplot() +
  geom_sf(data = ne_countries(returnclass = "sf")) +
  coord_sf(expand = FALSE)
```

![](https://i.imgur.com/usDTsG8.png)

``` r
  
ggplot() +
  geom_sf(data = ne_countries(returnclass = "sf")) +
  coord_sf(expand = FALSE) +
  scale_y_continuous(limits = c(-79, 79))
```

![](https://i.imgur.com/BwfpTC6.png)

<sup>Created on 2021-07-31 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

@edzer Have there been any recent changes in sf to the graticule code that could cause this? The graticule doesn't look right to me:

``` r
library(tidyverse)
library(sf)
#> Linking to GEOS 3.8.1, GDAL 3.2.1, PROJ 7.2.1
library(rnaturalearth)

p <- ggplot() +
  geom_sf(data = ne_countries(returnclass = "sf")) +
  coord_sf(expand = FALSE)

b <- ggplot_build(p)
b$layout$panel_params[[1]]$graticule
#> Simple feature collection with 8 features and 10 fields
#> Geometry type: LINESTRING
#> Dimension:     XY
#> Bounding box:  xmin: -7.894919e-17 ymin: 0.0005182984 xmax: 1 ymax: 1
#> CRS:           NA
#>      degree type      degree_label                       geometry       x_start
#> 1      -180    E    "180" * degree LINESTRING (-7.894919e-17 0... -7.894919e-17
#> 7       180    E    "180" * degree LINESTRING (1 0.0005182984,...  1.000000e+00
#> 8       -50    N "50" * degree * S LINESTRING (-7.894919e-17 0... -7.894919e-17
#> 8.1     -50    N "50" * degree * S LINESTRING (0.9995 0.230339...  9.995000e-01
#> 9         0    N     " 0" * degree LINESTRING (-7.894919e-17 0... -7.894919e-17
#> 9.1       0    N     " 0" * degree LINESTRING (0.9995 0.518298...  9.995000e-01
#> 10       50    N "50" * degree * N LINESTRING (-7.894919e-17 0... -7.894919e-17
#> 10.1     50    N "50" * degree * N LINESTRING (0.9995 0.806257...  9.995000e-01
#>           y_start         x_end     y_end angle_start  angle_end plot12
#> 1    0.0005182984 -7.894919e-17 1.0000000  90.0000000 90.0000000   TRUE
#> 7    0.0005182984  1.000000e+00 1.0000000  90.0000000 90.0000000   TRUE
#> 8    0.2303548622  5.000000e-04 0.2303395  -0.8511527 -0.8511527   TRUE
#> 8.1  0.2303394620  1.000000e+00 0.2303549   0.8511527  0.8511527  FALSE
#> 9    0.5182984400  5.000000e-04 0.5182984   0.0000000  0.0000000   TRUE
#> 9.1  0.5182984400  1.000000e+00 0.5182984   0.0000000  0.0000000  FALSE
#> 10   0.8062420178  5.000000e-04 0.8062574   0.8511527  0.8511527   TRUE
#> 10.1 0.8062574181  1.000000e+00 0.8062420  -0.8511527 -0.8511527  FALSE
```

<sup>Created on 2021-07-31 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by edzer** [comment]
Not in `graticule`, but a side-effect of switching the GEOS geometry engine with `s2geometry` when you work with ellipsoidal coordinates. You can get the old behaviour back by
```r
sf_use_s2(FALSE)
```

**Comment by clauswilke** [comment]
Thanks @edzer. Reprex with this setting follows below.

``` r
library(tidyverse)
library(sf)
#> Linking to GEOS 3.8.1, GDAL 3.2.1, PROJ 7.2.1
library(rnaturalearth)

sf_use_s2(FALSE)
#> Spherical geometry (s2) switched off

ggplot() +
  geom_sf(data = ne_countries(returnclass = "sf")) +
  coord_sf(expand = FALSE)
```

![](https://i.imgur.com/dqmnkLi.png)

<sup>Created on 2021-07-31 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by clauswilke** [comment]
In principle, this issue can be closed, as this is not a problem in ggplot2 itself. However, I'll leave the issue open for now as others may run into the same problem.

**Comment by mbrousil** [comment]
Thanks for your help!

**Comment by PanfengZhang** [comment]
Can this problem be solved without the command "sf_use_s2(FALSE)"?
There may be many people who encounter this problem without knowing where the cause is.
@edzer

**Comment by hadley** [comment]
Do we need to document this? Are ellipsoidal coordinates common?

**Comment by edzer** [comment]
Gives us this back:
```r
library(tidyverse)
library(sf)
library(rnaturalearth)

ggplot() +
  geom_sf(data = ne_countries(returnclass = "sf"),
          fill = "gray90", color = NA) +
  geom_sf(data = ne_coastline(returnclass = "sf")) +
  ylab("") +
  xlab("") +
  theme_bw() +
  coord_sf(expand = FALSE) +
  scale_x_continuous(breaks = seq(from = -180, to = 180, by = 60))
```
![x](https://user-images.githubusercontent.com/520851/158782133-3860dc75-6804-4589-b057-83012b6e4141.png)

**Comment by hadley** [comment]
Thanks @edzer!
