### ISSUE TITLE
Box around legends not drawn correctly

### ISSUE THREAD

**Issue by trekonom** [tidyverse/ggplot2#4572]
I stumbled over this issue when trying to add a box around two legends via `legend.box.background`. As the reprex shows when doing so some pieces of the box outline are drawn with a larger size:

``` r
library(ggplot2)

p <- ggplot(mtcars, aes(hp, mpg, color = cyl, shape = factor(cyl))) +
  geom_point()

p + theme(legend.box.background = element_rect(color = "black", size = 5))
```

![](https://i.imgur.com/0UWB87L.png)

<sup>Created on 2021-08-01 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by ptoche** [comment]
A quick workaround would be to play around with the margins, e.g. `legend.box.margin = unit(c(1,1,1,1),"cm")`

**Comment by clauswilke** [comment]
This is not a bug, it's white background boxes from the legend contents drawn on top of the outlines. You can turn those off with theme settings.

In general, this type of question is more suited to the R Studio Community or stackoverflow.

**Comment by clauswilke** [comment]
See e.g. what happens if you use a theme that doesn't have these white backgrounds.

``` r
library(ggplot2)

p <- ggplot(mtcars, aes(hp, mpg, color = cyl, shape = factor(cyl))) +
  geom_point()

p + 
  cowplot::theme_half_open() +
  theme(legend.box.background = element_rect(color = "black", size = 5))
```

![](https://i.imgur.com/QLPaGZd.png)

<sup>Created on 2021-08-02 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by trekonom** [comment]
Thanks for clarifying. Will keep your advise in mind and ask a question on SO next time before raising an issue.
