### ISSUE TITLE
frame.color argument of guide_colorbar() does not create color bar frame

### ISSUE THREAD

**Issue by FlukeAndFeather** [tidyverse/ggplot2#4573]
Hi folks. It's possible I'm using `guide_colorbar()` wrong, so please correct me if that's the case.

I would expect the following to draw a black border around the legend's colorbar, but I don't see anything. 

```r
library(ggplot2)
ggplot(iris, aes(Sepal.Length, Sepal.Width, color = Sepal.Length)) +
  geom_point() +
  scale_fill_continuous(guide = guide_colorbar(frame.color = "black"))
```

<img width="405" alt="no_border" src="https://user-images.githubusercontent.com/47009796/128227641-1c3f4b85-c5db-4851-b288-d7f734fa70ea.png">

Session info below.

> session_info()
─ Session info ───────────────────────────────────────────────────────────────
 setting  value                       
 version  R version 4.0.4 (2021-02-15)
 os       macOS Catalina 10.15.7      
 system   x86_64, darwin17.0          
 ui       RStudio                     
 language (EN)                        
 collate  en_US.UTF-8                 
 ctype    en_US.UTF-8                 
 tz       America/Los_Angeles         
 date     2021-08-04                  

─ Packages ───────────────────────────────────────────────────────────────────
 package     * version date       lib source        
 assertthat    0.2.1   2019-03-21 [1] CRAN (R 4.0.2)
 cachem        1.0.5   2021-05-15 [1] CRAN (R 4.0.2)
 callr         3.7.0   2021-04-20 [1] CRAN (R 4.0.2)
 cli           2.5.0   2021-04-26 [1] CRAN (R 4.0.2)
 colorspace    2.0-1   2021-05-04 [1] CRAN (R 4.0.2)
 crayon        1.4.1   2021-02-08 [1] CRAN (R 4.0.2)
 DBI           1.1.1   2021-01-15 [1] CRAN (R 4.0.2)
 desc          1.3.0   2021-03-05 [1] CRAN (R 4.0.2)
 devtools    * 2.4.1   2021-05-05 [1] CRAN (R 4.0.2)
 digest        0.6.27  2020-10-24 [1] CRAN (R 4.0.2)
 dplyr         1.0.6   2021-05-05 [1] CRAN (R 4.0.2)
 ellipsis      0.3.2   2021-04-29 [1] CRAN (R 4.0.2)
 fansi         0.5.0   2021-05-25 [1] CRAN (R 4.0.4)
 farver        2.1.0   2021-02-28 [1] CRAN (R 4.0.2)
 fastmap       1.1.0   2021-01-25 [1] CRAN (R 4.0.2)
 fs            1.5.0   2020-07-31 [1] CRAN (R 4.0.2)
 generics      0.1.0   2020-10-31 [1] CRAN (R 4.0.2)
 ggplot2     * 3.3.3   2020-12-30 [1] CRAN (R 4.0.2)
 glue          1.4.2   2020-08-27 [1] CRAN (R 4.0.2)
 gtable        0.3.0   2019-03-25 [1] CRAN (R 4.0.2)
 labeling      0.4.2   2020-10-20 [1] CRAN (R 4.0.2)
 lifecycle     1.0.0   2021-02-15 [1] CRAN (R 4.0.2)
 magrittr      2.0.1   2020-11-17 [1] CRAN (R 4.0.2)
 memoise       2.0.0   2021-01-26 [1] CRAN (R 4.0.2)
 munsell       0.5.0   2018-06-12 [1] CRAN (R 4.0.2)
 pillar        1.6.1   2021-05-16 [1] CRAN (R 4.0.4)
 pkgbuild      1.2.0   2020-12-15 [1] CRAN (R 4.0.2)
 pkgconfig     2.0.3   2019-09-22 [1] CRAN (R 4.0.2)
 pkgload       1.2.1   2021-04-06 [1] CRAN (R 4.0.2)
 prettyunits   1.1.1   2020-01-24 [1] CRAN (R 4.0.2)
 processx      3.5.2   2021-04-30 [1] CRAN (R 4.0.2)
 ps            1.6.0   2021-02-28 [1] CRAN (R 4.0.2)
 purrr         0.3.4   2020-04-17 [1] CRAN (R 4.0.2)
 R6            2.5.0   2020-10-28 [1] CRAN (R 4.0.2)
 remotes       2.3.0   2021-04-01 [1] CRAN (R 4.0.2)
 rlang         0.4.11  2021-04-30 [1] CRAN (R 4.0.2)
 rprojroot     2.0.2   2020-11-15 [1] CRAN (R 4.0.2)
 scales        1.1.1   2020-05-11 [1] CRAN (R 4.0.2)
 sessioninfo   1.1.1   2018-11-05 [1] CRAN (R 4.0.2)
 testthat    * 3.0.2   2021-02-14 [1] CRAN (R 4.0.2)
 tibble        3.1.2   2021-05-16 [1] CRAN (R 4.0.4)
 tidyselect    1.1.1   2021-04-30 [1] CRAN (R 4.0.2)
 usethis     * 2.0.1   2021-02-10 [1] CRAN (R 4.0.2)
 utf8          1.2.1   2021-03-12 [1] CRAN (R 4.0.2)
 vctrs         0.3.8   2021-04-29 [1] CRAN (R 4.0.2)
 withr         2.4.2   2021-04-18 [1] CRAN (R 4.0.4)

[1] /Library/Frameworks/R.framework/Versions/4.0/Resources/library

**Comment by clauswilke** [comment]
Yeah, I'm pretty sure this used to work. Not sure what happened there. I can reproduce the issue.

**Comment by clauswilke** [comment]
Note the spelling: It's `frame.colour`. But the problem remains nonetheless.

``` r
library(ggplot2)

ggplot(iris, aes(Sepal.Length, Sepal.Width, color = Sepal.Length)) +
  geom_point() +
  scale_fill_continuous(guide = guide_colorbar(frame.colour = "black"))
```

![](https://i.imgur.com/8k7WY4X.png)

<sup>Created on 2021-08-04 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by clauswilke** [comment]
Sorry, rookie mistake. The scale color needs to match the aesthetic.

``` r
library(ggplot2)

ggplot(iris, aes(Sepal.Length, Sepal.Width, color = Sepal.Length)) +
  geom_point() +
  scale_color_continuous(guide = guide_colourbar(frame.colour = "black"))
```

![](https://i.imgur.com/06B7AgU.png)

<sup>Created on 2021-08-04 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by FlukeAndFeather** [comment]
So it does, apologies for the distraction!
