### ISSUE TITLE
Error in opts(legend.position = "none") : could not find function "opts"

### ISSUE THREAD

**Issue by OmarMouss92** [tidyverse/ggplot2#4577]
Hello, 

I'm using ggplot2 to draw a histogram, and when using opts function, I'm receiving this error in the console:

Error in opts(legend.position = "none") : could not find function "opts"

This is my full code: 

hist.day1 <- ggplot(dlf, aes(day1)) + opts (legend.position = "none") + geom_histogram(aes(y = ..density..), colour = "black", fill = "white") + labs(x = "Hygiene score on day 1", y = "Density")

Thanks for your help.

**Comment by ptoche** [comment]
This is super old code. `opts()` has given way to `theme()`. Please head to the [docs](https://ggplot2.tidyverse.org/reference/) to see how things are done nowadays.
