### ISSUE TITLE
scale_fill_manual is only filling in legend values and not graph values

### ISSUE THREAD

**Issue by PinkAppleFlower** [tidyverse/ggplot2#4578]
scale_fill_manual is only filling in legend values and not values in the graph itself.  As you can see from the reprex below, instead of matching with the palette colors, the values in the graph end up matching with nothing and therefore default to the na color.  This code was taken from an example that works on a Ubuntu version of R 3.5.3.  I am running a Windows 10 with a 4.1.0 version of R.

```r
library(datasets)

mtcars$fam <- factor(mtcars$am)
mtcars$fcyl <- factor(mtcars$cyl)

palette <- c(automatic = "#377EB8", manual = "#E41A1C")

ggplot(mtcars, aes(fcyl, fill = fam)) +
  geom_bar() +
  labs(x = "Number of Cylinders", y = "Count") +
  # Set the fill color scale
  scale_fill_manual("Transmission", values = palette, na.value = "orange")
```

**Comment by clauswilke** [comment]
In your example, the palette names don't match the factor levels.

These kinds of questions are better suited for the R Studio Community or Stackoverflow.

**Comment by PinkAppleFlower** [comment]
code is not mine and works on a previous version of R...so I did not do a check to see for something as simple as that.  Glad it was not a bigger problem.
