### ISSUE TITLE
geom_tile should not reverse the y axis by default

### ISSUE THREAD

**Issue by davidhodge931** [tidyverse/ggplot2#4579]
```
library(ggplot2)
library(dplyr)
library(palmerpenguins)

plot_data <- penguins %>% 
  group_by(species, sex) %>% 
  summarise(bill_length_mm = mean(bill_length_mm, na.rm = TRUE))

ggplot(plot_data) +
  geom_tile(aes(sex, species, fill = bill_length_mm))
```
![image](https://user-images.githubusercontent.com/55065152/128659594-3934c0ca-9fb4-41fc-b8a8-79a3d63673be.png)

**Comment by clauswilke** [comment]
The origin is in the bottom left corner. That's true for continuous scales and for discrete scales. It's worked like this since forever and it's unlikely we would change this. You can always reverse the levels of your categorical variable with `fct_rev()`.

**Comment by davidhodge931** [comment]
Good to know, thanks @clauswilke
