### ISSUE TITLE
geom_hex ignores binwidth argument when sample size is small

### ISSUE THREAD

**Issue by sieste** [tidyverse/ggplot2#4580]
`geom_hex` ignores the binwidth argument when there are only few data points:

```r
library(ggplot2)
n = 1
ggplot(tibble(x=rnorm(n), y=rnorm(n))) + 
  geom_hex(aes(x=x, y=y), binwidth=c(.1,.1)) + 
  xlim(-3, 3) + ylim(-3,3)
```

For small values of `n` (below 10) the bin widths are not 0.1. For larger `n` (try 100), the problem goes away and the bin width is 0.1 as specified.

**Comment by thomasp85** [comment]
The issue here is when only a single bin exist in either dimension. The geom code calculates the resolution of the binning from the data itself and if there is only one bin it defaults to 1... we'll need to think about how to make this more sensible
