### ISSUE TITLE
`geom_smooth()` lacks support for `lineend`

### ISSUE THREAD

**Issue by msberends** [tidyverse/ggplot2#4581]
Please support the `lineend` argument for `geom_smooth()`, as it just draws a line.

```r
library(ggplot2)
ggplot(mtcars, aes(x = mpg, y = vs)) +
  geom_smooth(size = 4, lineend = "round")
#> Warning message:
#> Ignoring unknown parameters: lineend 
```

![image](https://user-images.githubusercontent.com/31037261/129081925-9efc051b-ac6f-44f9-b911-ba53beea895b.png)

Using `stat_smooth()` works, as [was also pointed out by others](https://stackoverflow.com/a/64103999/4575331):

```r
ggplot(mtcars, aes(x = mpg, y = vs)) +
  stat_smooth(size = 4, geom = "line", lineend = "round")
```

![image](https://user-images.githubusercontent.com/31037261/129081882-3fe6c609-66c3-431c-a693-97459e0ae7c7.png)

**Comment by javlon** [comment]
@thomasp85 
It seems like your commit 6704ea1fd01369445e7d28946edb8312c133691d fixed this issue.

**Comment by msberends** [comment]
Yes it did ✅
Many thanks!
