### ISSUE TITLE
position_jitterdodge() does not recognize 'group' as an aesthetic to dodge by

### ISSUE THREAD

**Issue by dansmith01** [tidyverse/ggplot2#4582]
I'd like to separate jittered points into multiple columns without making them different colors or shapes. I thought that setting the 'group' parameter would do just that, but I get an error message instead.

```r
library(ggplot2)
ggplot(CO2) + geom_jitter(aes(Type, uptake, group = Treatment), position = position_jitterdodge())
#> Error: `position_jitterdodge()` requires at least one aesthetic to dodge by
```

Replacing `group` with `color`, `fill`, or `shape` works as expected.

**Comment by karawoo** [comment]
Thanks for reporting, I believe this is a duplicate of #3656. I'm going to close this issue in favor of that one which has more discussion.
