### ISSUE TITLE
Cannot replace xlab when set with scale_x_continuous

### ISSUE THREAD

**Issue by eheinzen** [tidyverse/ggplot2#4586]
I've tried to search for this problem in the other issues but couldn't find anything.

In short, I cannot replace the x-label when using `scale_x_continuous()`:

```r
p <- ggplot(data.frame(x = 1:10, y = 1:10), aes(x = x, y = y)) +
  geom_point() +
  scale_x_continuous(name = "hi")
p # has label
p + xlab(NULL) # still has label
p + xlab("bye") # still has old label
```

**Comment by teunbrand** [comment]
There is a hierarchy in which labels are passed on to become guide titles, and I don't think ggplot2 is doing anything wrong in your example. As far as I know, the hierarchy is roughly this:

guide title > scale name > labs > labels inferred from mapping

Accordingly, you can override the scale name label by setting the title in the guide.

``` r
library(ggplot2)

p <- ggplot(data.frame(x = 1:10, y = 1:10), aes(x = x, y = y)) +
  geom_point() +
  scale_x_continuous(name = "hi")

p + guides(x = guide_axis(title = "Not hi"))
```

![](https://i.imgur.com/hHIF9VA.png)

<sup>Created on 2021-08-17 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by eheinzen** [comment]
Got it.  I guess I was perplexed because `p + ggtitle("hi") + ggtitle(NULL)` gives no title.  I guess that fits with the hierarchy, though, since both are labs.  Thanks for the solution 👍
