### ISSUE TITLE
The axis labels does not display properly at the specified breaks.

### ISSUE THREAD

**Issue by PanfengZhang** [tidyverse/ggplot2#4589]
---

When I draw a world map using the ggplot2 package of new version, the axis label does not display properly; the vector world map is come from the sf package.

```r
library(rnaturalearth)
library(ggplot2)
library(sf)
wld <- ne_coastline(returnclass = "sf")
ggplot() + 
  geom_sf(data = wld) + 
  coord_sf(expand = FALSE) +
  scale_x_continuous(breaks = seq(-120, 120, 60)) +
  scale_y_continuous(breaks = seq(-45, 45, 45)) +
  theme_bw()
```

---
Here, the x-axis labels does not display at the breaks 120W, 60W, 0, 60E, 120E; and the y-axis labels also does not display at the breaks 45S, 0, 45N
![test_world_map](https://user-images.githubusercontent.com/20354811/130168836-c7db17be-0699-4c50-a422-b6b819d95a2e.png)

**Comment by clauswilke** [comment]
See #4571.

**Comment by PanfengZhang** [comment]
Thanks.
