### ISSUE TITLE
link to ggplot cheatsheet failing from https://ggplot2.tidyverse.org/

### ISSUE THREAD

**Issue by andysouth** [tidyverse/ggplot2#4591]
The link to the ggplot cheatsheet is 404 ing, from a number of locations. 
e.g. https://ggplot2.tidyverse.org/
 
Failing:
https://github.com/rstudio/cheatsheets/blob/master/data-visualization-2.1.pdf

Seems it should instead be : 
https://github.com/rstudio/cheatsheets/blob/master/data-visualization.pdf

**Comment by yutannihilation** [comment]
Thanks for your report! If possible, could you create a pull request to fix this? You can edit `README.Rmd` and run `devtools::build_readme()`.

**Comment by teunbrand** [comment]
There is an open PR(#4585) to fix the link already.

**Comment by yutannihilation** [comment]
Oh, I didn't notice it, sorry...
