### ISSUE TITLE
loess across groups and subgroups?

### ISSUE THREAD

**Issue by marwa38** [tidyverse/ggplot2#4593]
I have three phases (groups) with different subgroups
Stim --> Veg1wk, Veg2wk, marine
Interm --> vegetable, marine
Challenge --> vegetable, marine
The stimulus phase has Veg1wk and Veg2wk but the vegetable is only found in intermediate and challenge phases.

I used this code:
ggplot(vegetableC, aes(x = diet, y = Abundance, color = Class, group = Class)) +
facet_wrap(~phase) +
stat_smooth(method = "loess") +
xlab("Vegetable samples") +
ylab("Relative Abundance") +
labs(title = "Relative Abundance in Vegetable samples across phases at Class Level") +
geom_point(size = 1.25, alpha = 0.4)

which showed this figure
![image](https://user-images.githubusercontent.com/68851733/130624023-386f4699-acba-4746-a515-f9cd4e064391.png)

but I want to see something like this but where each group have its own subgroups (not all the subgroups I have)
![image](https://user-images.githubusercontent.com/68851733/130624111-337e5496-cfc7-4ba9-8156-1b0a142199f4.png)
The problem with the facet_grid or facet_wrap is that they include all subgroups under each group like the first figure.

**Comment by clauswilke** [comment]
This type of question is more appropriate for the RStudio Community or Stackoverflow. The ggplot2 issue tracker is meant for bona-fide bugs or feature requests.

**Comment by marwa38** [comment]
Thanks clauswilke,

I will submit this here it might be of any help to others as I found a way around;

vegnew <- psmelt(NAME OF PHYLOSEQ OBJECT)

vegnew$newvar <- paste(vegnew$phase, vegnew$diet, sep = "_")
vegnew$newvar <- factor(vegnew$newvar)
levels(vegnew$newvar)

vegnew$newvar <- factor(vegnew$newvar, levels = c("", "", "", ""))   ///use this line if you need to change the order of the labels, put the name within each set of ""
levels(vegnew$newvar)

ggplot (data=vegnew, aes(x=newvar, y=Abundance, fill=Class)) + options
