### ISSUE TITLE
Permit guide_axis() angle heuristics in guide_legend(), etc.

### ISSUE THREAD

**Issue by bwiernik** [tidyverse/ggplot2#4594]
cf. https://stackoverflow.com/questions/68925483/overlapping-labels-in-legend-in-ggplot

The `guide_axis()` function has helpful heuristics in the `angle` function to automatically set the `hjust` and `vjust` parameters. It would be really nice if these heuristics were also available in `guide_legend()`, `guide_colorbar()`, etc. to rotate legend labels. These could be provided with a `label.angle` argument to accompany the existing `label.theme`, `label.vjust`, and `label.hjust` arguments.

Example:
```r
library(ggplot2)
df <- expand.grid(X1 = 1:10, X2 = 1:10)
df$value <- df$X1 * df$X2

ggplot(df, aes(X1, X2)) + geom_tile(aes(fill = value)) +
    scale_fill_continuous(guide = guide_colourbar(direction = "horizontal", label.angle = 30))
```

**Comment by teunbrand** [comment]
I think this makes sense for most guides, except `guide_legend()`. AFAIK `guide_legend()` is the only guide where label alignment is to size-based rather than anchored to a point.
