### ISSUE TITLE
intercept free natural spline not working as expected

### ISSUE THREAD

**Issue by RGWeemhoff** [tidyverse/ggplot2#4597]
Because a Natural Spline without interior knots is a linear regression line
and I specified Intercept Free, both in lm and ns, I absolutely do not understand the result, 
the red dotted line should be the same as the solid green:
![image](https://user-images.githubusercontent.com/65539578/131473593-20f41cbf-6858-44fe-b9de-5cf6d7665697.png)

```r
install.packages("ggplot2") 
  library(ggplot2)
  grafiek <- data.frame(
    OL = c (2,7),
    TT = c (2,4)
  )
  ggplot(grafiek,mapping=aes(x=OL))+
    xlim(0,NA)+
    geom_point(aes(y=TT), size=5, shape=8)+
    # Expected: No intercept + intercept=False = Intercept Free, but result is unexpected
    geom_smooth(aes(y=TT),method = "lm", fullrange=TRUE, linetype="dotted", size=4, col="RED"  ,formula=y~0+splines::ns(x,df=1,intercept=FALSE), se=F)+
    # here the MRE ends. 
    # The rest is context
    # blue for lm default, green for lm 0+
    # dotted for ns intercept=F, dashed and longdash for ns intercept=T, solid for no spline
    # intercept + intercept=False = Intercept (apparently any intercept takes precedence)
    geom_smooth(aes(y=TT),method = "lm", fullrange=TRUE, linetype="dotted", size=4, col="BLUE",formula=y~splines::ns(x,df=1,intercept=FALSE), se=F)+
    # intercept + intercept=True = Intercept (of course)
    geom_smooth(aes(y=TT),method = "lm", fullrange=TRUE, linetype="dashed", size=3, col="BLUE", formula=y~splines::ns(x,df=2,intercept=TRUE), se=F)+
    # no intercept, intercept=True = intercept (apparently any intercept takes precedence)
    geom_smooth(aes(y=TT),method = "lm", fullrange=TRUE, linetype="longdash", size=2, col="GREEN", formula=y~0+splines::ns(x,df=2,intercept=TRUE), se=F)+
    # intercept, no spline = intercept
    geom_smooth(aes(y=TT),method = "lm", fullrange=TRUE,linetype="solid", size=1, col="BLUE", se=F, formula = y ~ x)+
    # no intercept, no spline = intercept free
    geom_smooth(aes(y=TT),method = "lm", fullrange=TRUE,linetype="solid", size=1, col="GREEN",se=F, formula = y ~ 0+x)  
```

**Comment by RGWeemhoff** [comment]
Interestingly, a first-degree orthogonal polynomial is also clearly wrong. But raw=T fixes that. Is a spline in some way also orthogonal?

**Comment by teunbrand** [comment]
Base R graphics give similar results with equivalent models. I'm not seeing how ggplot2 is doing the wrong or unexpected thing here.

``` r
grafiek <- data.frame(
  OL = c (2,7),
  TT = c (2,4)
)

fit1 <- lm(TT ~ 0 + splines::ns(OL, df = 1, intercept = FALSE), data = grafiek)
fit2 <- lm(TT ~ splines::ns(OL, df = 1, intercept = FALSE), data = grafiek)
fit3 <- lm(TT ~ splines::ns(OL, df = 2, intercept = TRUE), data = grafiek)
fit4 <- lm(TT ~ 0 + splines::ns(OL, df = 2, intercept = TRUE), data = grafiek)
fit5 <- lm(TT ~ OL, data = grafiek)
fit6 <- lm(TT ~ 0 + OL, data = grafiek)

xseq <- data.frame(OL = seq(0, 7, length.out = 100))

make_line <- function(fit, ...) {
  lines(xseq$OL, predict(fit, xseq), ...)
}

plot(NULL, xlim = c(0, 7), ylim = c(-1.6, 5))
points(grafiek, pch = 8, cex = 3)
make_line(fit1, col = "red",   lty = 3, lwd = 4)
make_line(fit2, col = "blue",  lty = 3, lwd = 4)
make_line(fit3, col = "blue",  lty = 2, lwd = 3)
#> Warning in predict.lm(fit, xseq): prediction from a rank-deficient fit may be
#> misleading
make_line(fit4, col = "green", lty = 4, lwd = 2)
make_line(fit5, col = "blue",  lty = 1, lwd = 1)
make_line(fit6, col = "green", lty = 1, lwd = 1)
```

![](https://i.imgur.com/QOjMdJ2.png)

<sup>Created on 2021-09-06 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by RGWeemhoff** [comment]
Imho, the red dotted line is not an intercept-free regression line, as the green line is.

**Comment by RGWeemhoff** [comment]
FYI, this is part of the original EDA I am investigating:
![image](https://user-images.githubusercontent.com/65539578/132410903-22363b62-2fe6-47da-84ac-635fce1c6c25.png)

**Comment by RGWeemhoff** [comment]
a reproducible example with only a few datapoints:
![image](https://user-images.githubusercontent.com/65539578/132502402-5a797506-12c5-448b-8fbf-845c19e2afdb.png)

library(ggplot2)
#grafiek<-subset(sagitas,species=="minutus" & Location=="Noordzee" )
grafiek <- data.frame(
  OL = c (2,5,7,9),
  OT = c (2,3,4,5)
)
ggplot(grafiek,mapping=aes(x=OL))+
  xlim(0,10)+ylim(-4,6)+
  geom_point(aes(y=OT), size=1, shape=16)+
  # spline
  geom_smooth(aes(y=OT, color="spline", linetype="FALSE", size="FALSE"),method = "lm", fullrange=TRUE, formula=y~0+splines::ns(x,df=2,intercept=FALSE), se=F)+
  geom_smooth(aes(y=OT, color="spline", linetype="TRUE", size="TRUE"),method = "lm", fullrange=TRUE, formula=y~splines::ns(x,df=3,intercept=TRUE), se=F)+
  #  poly
  geom_smooth(aes(y=OT, color="poly",linetype="TRUE", size="FALSE"),method = "lm", fullrange=TRUE,se=F, formula = y ~ 0+poly(x,3,raw=T) )+
  geom_smooth(aes(y=OT, color="poly",linetype="TRUE", size="TRUE"),method = "lm", fullrange=TRUE,se=F, formula = y ~ poly(x,3,raw=T))+
 geom_smooth(aes(y=OT, color="poly",linetype="FALSE", size="FALSE"),method = "lm", fullrange=TRUE,se=F, formula = y ~ 0+poly(x,3,raw=F) )+
  geom_smooth(aes(y=OT, color="poly",linetype="FALSE", size="TRUE2"),method = "lm", fullrange=TRUE,  se=F, formula = y ~ poly(x,3, raw=F))+
  scale_color_manual(name = "color=lm",
                     breaks = c("poly", "spline"),
                     values = c("poly" = "blue", "spline" = "red", "Intercept free" = "green") )  +
  scale_linetype_manual(name = "line type=ns intercept or poly raw",
                        breaks = c("FALSE", "TRUE"),
                        values = c("FALSE" = "dotted", "TRUE" = "dashed") )  +
  scale_size_manual(name = "line thicknes=Intercept",
                        breaks = c("FALSE", "TRUE", "TRUE2"),
                        values = c("FALSE" = 3, "TRUE" = 1, "TRUE2"= 2) )
#
