### ISSUE TITLE
Border lines not affected by alpha in stat_summary_hex (geom hex)

### ISSUE THREAD

**Issue by dnebdal** [tidyverse/ggplot2#4598]
I'm trying to make the border and fill color on a stat_summary_hex the same. I understand that having a border on a hex will obviously lead to overplotting on the borders between the hexes - but even where they do not border another hex, the lines appear to entirely ignore the alpha.  

Most alpha-related bugs seem to be caused by actually drawing the line/object multiple times, but I don't _think_ this is one of those - unless it's an artifact of how the hex drawing code works?

(I'm also perfectly fine with the answer being "then don't do that".)

```r
library(ggplot2)

(df <- data.frame(x=1:10, y=1:10, z=1:10*1:10))
ggplot(df, aes(x=x, y=y, z=z)) + 
  stat_summary_hex(aes(color=..value.., alpha=..value..),
    fun=mean, bins=2, size=2)

```
![hextest](https://user-images.githubusercontent.com/3057949/131357851-4d79ff0f-2781-45d1-9a4e-bcc73c58cba4.png)

**Comment by clauswilke** [comment]
Setting transparency to outlines creates horrible drawing artifacts. You can explore this by using a color scale that has an alpha component, and/or calculating colors manually and using `scale_color_identity()`.

``` r
library(ggplot2)

df <- data.frame(x=1:10, y=1:10, z=1:10*1:10)
ggplot(df, aes(x=x, y=y, z=z)) + 
  stat_summary_hex(aes(color=..value.., alpha=..value..),
                   fun=mean, bins=2, size=2) +
  scale_color_gradient(low = "#132B4310", high = "#56B1F7C0")
```

![](https://i.imgur.com/K1avY4G.png)

<sup>Created on 2021-08-30 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by dnebdal** [comment]
Right, I take it that's the fill and outline also overlapping - which makes sense when you point it out. I'll take that as an argument for the "don't do that" solution.

**Comment by dnebdal** [comment]
You know, let's close this. While I still think it would be less surprising if the borders were affected by the alpha, it seems like the situations where it would actually be useful are so few that it's not worth digging into.
