### ISSUE TITLE
Please provide C++ interface

### ISSUE THREAD

**Issue by libaineu2004** [tidyverse/ggplot2#4611]
---

Brief description of the problem

```r
Hi! Can the related geometric calculation methods provide C++ interface?
Let us C++ developers also participate. thanks
```

**Comment by yutannihilation** [comment]
Hi, ggplot2 doesn't have any C++ implementation itself, so there will be no C++ interface. If you mean you want to write geometric calculation in your package in C++, you can do it with Rcpp or cpp11 package; write C++ code and call it in R code. For example, [ggrepel package](https://github.com/slowkow/ggrepel/) uses C++ code to calculate the label positions. Hope this helps!
