### ISSUE TITLE
alpha aesthetic not plotting consistently with geom_tile()

### ISSUE THREAD

**Issue by benbellman** [tidyverse/ggplot2#4618]
I am trying to use geom_tile() to shade frequency cells in a matrix that tracks category changes between two time points. This has worked effectively when doing a single plot with a single dataframe, but I've discovered inconsistencies in the alpha aesthetic when combining multiple plots with patchwork.

In this example, I want to combine the plot below with four others, keeping the transparency scale consistent across them all. In my previous efforts, I created a "wt" column that scaled each tile's alpha value to the max frequency in the matrix (which gets alpha= 1). In this case, my max frequency across all plots is 8, so values of 1 should plot with an alpha of 0.125. But I get different results when I feed this value in using that column (the transparency is much darker than it should be) versus specifying 0.125 as a constant outside the aes() function within geom_tile(). I have no idea why there would be this discrepancy, or how to change my code to make sure 1-8 gets mapped to 0.125-1 consistently.

If requested, I'm happy to include more reprex for the other plots, which also are not consistently plotting the alpha values contained in the "wt" column. This was just the simplest example in the 5 plots.

```r
library(dplyr)
library(ggplot2)

# Data
reprex('d <- tibble(
  dim1 = factor(c("R", "S", "S"), levels = c("Q","R","S","T")),
  dim2 = factor(c("Q", "R", "T"), levels = c("Q","R","S","T")),
  chg = factor(c("Lower", "Lower", "Higher"), levels = c("Lower","Higher")),
  n = 1
) %>% 
  mutate(wt = n/8)')

# See data, all 3 values of "wt" are 0.125
d
#> # A tibble: 3 x 5
#>   dim1  dim2  chg        n    wt
#>   <fct> <fct> <fct>  <dbl> <dbl>
#> 1 R     Q     Lower      1 0.125
#> 2 S     R     Lower      1 0.125
#> 3 S     T     Higher     1 0.125

# Example 1 (fail, alpha in plot is not actually 0.125)
ggplot(d, aes(x = dim1, y = dim2)) +
  geom_tile(aes(fill = chg, alpha = wt)) +
  geom_text(aes(label = n)) +
  scale_fill_manual(values = c("#B50A2AFF", "#0E84B4FF")) +
  scale_x_discrete(drop=FALSE) +
  scale_y_discrete(drop=FALSE) +
  theme(legend.position = "none")
```

![image](https://user-images.githubusercontent.com/18623829/133366260-ed78aead-4fd7-46e5-bc76-16a219038735.png)

```r
# Example 1 (correct result)
ggplot(d, aes(x = dim1, y = dim2)) +
  geom_tile(aes(fill = chg), alpha = 0.125) +
  geom_text(aes(label = n)) +
  scale_fill_manual(values = c("#B50A2AFF", "#0E84B4FF")) +
  scale_x_discrete(drop=FALSE) +
  scale_y_discrete(drop=FALSE) +
  theme(legend.position = "none")
```

![image](https://user-images.githubusercontent.com/18623829/133366304-e53e8c4a-dc1f-434d-a829-eac68188eb69.png)

```

**Comment by smouksassi** [comment]
since your are mapping alpha in aes the values are not taken as is,
if you want your data to be represented as is in the scale you need to use ' scale_alpha_identity()'

``` r
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
library(ggplot2)

# Data
d <- tibble(
  dim1 = factor(c("R", "S", "S"), levels = c("Q","R","S","T")),
  dim2 = factor(c("Q", "R", "T"), levels = c("Q","R","S","T")),
  chg = factor(c("Lower", "Lower", "Higher"), levels = c("Lower","Higher")),
  n = 1
) %>% 
  mutate(wt = n/8)


# Example 1 (fail, alpha in plot is not actually 0.125)
ggplot(d, aes(x = dim1, y = dim2)) +
  geom_tile(aes(fill = chg, alpha = wt)) +
  geom_text(aes(label = n)) +
  scale_fill_manual(values = c("#B50A2AFF", "#0E84B4FF")) +
  scale_alpha_identity()+
  scale_x_discrete(drop=FALSE) +
  scale_y_discrete(drop=FALSE) +
  theme(legend.position = "none")
```

![](https://i.imgur.com/uRV9sBN.png)

<sup>Created on 2021-09-15 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by benbellman** [comment]
Ah, I completely forgot about the identity scale functions. This is exactly the solution, thank you!
