### ISSUE TITLE
"Introduction to ggplot2" vignette

### ISSUE THREAD

**Issue by yutannihilation** [tidyverse/ggplot2#4620]
I've been wondering why ggplot2 doesn't have getting started vignette. AFAIK, there had been no discussion about this. I know it's probably going to be a huge work to summarise the concept of ggplot2 into one vignette, and it might be better to encourage users to read ggplot2-book, which is available online for free and is comprehensive. Still, I feel ggplot2 should have such a vignette like other tidyverse packages unless there's some convincing reason.

**Comment by GarrettDaniel** [comment]
Is there still a need for this vignette?  I'd be happy to help with it, but it seems like this section of the main README https://github.com/tidyverse/ggplot2/blob/main/README.md#learning-ggplot2 already has most of this information.

**Comment by teunbrand** [comment]
There is a PR over at #5159 that aims to add an introduction vignette, so it is still up in the air. If you have any suggestions for the vignette, now is a good time :)

**Comment by GarrettDaniel** [comment]
Thanks for letting me know @teunbrand!  Taking a look at it now and adding comments for review.
