### ISSUE TITLE
geom_point(): when stroke=NA, cannot change size of the point

### ISSUE THREAD

**Issue by themeo** [tidyverse/ggplot2#4624]
I'm trying to generate a plot with points with no border displayed, just fill and to be able to change their size. However, once `stroke=NA`, I cannot change the size of the points. 

``` r
library(ggplot2)

df = data.frame(x=rnorm(100), y=rnorm(100))
ggplot(df, aes(x, y)) + geom_point(shape=21, stroke=NA, fill="black", size=5)
```

![](https://i.imgur.com/9cGR1KP.png)

``` r
ggplot(df, aes(x, y)) + geom_point(shape=21, stroke=NA, fill="black", size=0.5)
```

![](https://i.imgur.com/wA13xay.png)

<sup>Created on 2021-09-20 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by yutannihilation** [comment]
Thanks, confirmed. Here's another version of the reprex. Curious...

``` r
library(ggplot2)

df = data.frame(x = rnorm(100), y = rnorm(100))

f <- function(stroke) {
  ggplot(df, aes(x, y)) +
    geom_point(shape = 21, stroke = stroke, colour = "red", fill = "black", size = 50) +
    ggtitle(paste("stroke:", rlang::as_label(stroke)))
}

patchwork::wrap_plots(f(1), f(NA))
```

![](https://i.imgur.com/5mn3z4g.png)

<sup>Created on 2021-09-20 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by clauswilke** [comment]
I think it's this line:
https://github.com/tidyverse/ggplot2/blob/759c63c2fd9e00ba3322c1b74b227f63c98d2e06/R/geom-point.r#L133

The `NA` poisons the calculation. I would always set `stroke = 0` to get rid of it.

``` r
library(ggplot2)

size <- 20
stroke <- 0
size * .pt + stroke * .stroke / 2
#> [1] 56.90551

stroke <- NA
size * .pt + stroke * .stroke / 2
#> [1] NA
```

<sup>Created on 2021-09-20 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by themeo** [comment]
The reason why I set `stroke = NA` was that `stroke = 0` does not eliminate the border:

``` r
library(ggplot2)
df = data.frame(x=rnorm(100), y=rnorm(100))
ggplot2::ggplot(df, aes(x, y)) + geom_point(shape=21, stroke=0, fill="orange", color="blue", size=3)
```

![](https://i.imgur.com/p6OMmEy.png)

<sup>Created on 2021-09-20 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by clauswilke** [comment]
Ah, apparently graphics devices interpret 0 as "smallest possible visible line thickness". You can always set the color to transparent though, to get rid of the stroke entirely.

``` r
library(ggplot2)
df <- data.frame(
  x=rnorm(100), y=rnorm(100)
)

ggplot(df, aes(x, y)) + 
  geom_point(
    shape=21, stroke=0, fill="orange",
    color="transparent", size=3
  )
```

![](https://i.imgur.com/Oqcespf.png)

<sup>Created on 2021-09-20 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by yutannihilation** [comment]
Thanks. So, I guess the line should be something like

``` r
stroke <- coords$stroke
stroke[is.na(stroke)] <- 0
...
  fontsize = coords$size * .pt + stroke * .stroke / 2, 
```

**Comment by clauswilke** [comment]
Not sure entirely. That would still leave the thin outline, but getting rid of it is kind of tricky (we can't just set `color = "transparent"`, as that will make points disappear for most point shapes). So maybe this is the way to go.
