### ISSUE TITLE
add AmE spelling for ggplot2.discrete.colour

### ISSUE THREAD

**Issue by lotard** [tidyverse/ggplot2#4626]
Only `options(ggplot2.discrete.colour=c("red", "blue", "green"))` works now (colour - BrE), not `options(ggplot2.discrete.color=c("red", "blue", "green"))` (color - AmE).

I believe that needs to be done in `R/scale-hue.r`. Not sure how to implement it properly, hence no PR (what if both options are defined?).

**Comment by yutannihilation** [comment]
I forgot we have discussed this before, but I guess the rationale not to provide the option would be that it's unclear what should happen when both are specified unlike the case of `scale_colour_*()` and `scale_color_*()`; the scale is simply overwritten by the newer one. Also, the code would be a bit complicated to support multiple defaults. So, I feel this won't be implemented, but I'm not sure.

**Comment by lotard** [comment]
I thought about it a bit more:
1. It would be unusual for a user to try to set both `ggplot2.discrete.color` and `ggplot2.discrete.colour`.
2. It's not unusual for a user to set just one, then wonder why it didn't work (my case).
3. It's easy to find out which of the two (color/colour) was set _second_ in `.Options` object.
4. Ergo, best default to the last of the two in `.Options`
5. If user decides to set one, then the other, then reset the first one again, then I guess we've reached the end of that tether, too bad.

I can take a stab at re-writing the relevant part of `R/scale-hue.R` if that sounds reasonable.

**Comment by karawoo** [comment]
One other case we might want to consider is if a package sets one of the options in `.onLoad()`. The user might set one spelling of the option, then load the package that sets the other spelling and be confused why the setting they requested hasn't taken effect.

**Comment by clauswilke** [comment]
All of this just reinforces to me that we desperately need theme support for color choices. The options mechanism is not great, even without the added complication of color vs colour.

**Comment by lotard** [comment]
@karawoo Well spotted! Currently, one of these spellings would be 'wrong', so either of the settings would never kick in anyway. Under 'pick second' scenario I'm suggesting, both options would have an effect, with the one to be declared later replacing the first one - silently. Of course, it'd be more complicated if user/package then resets the first option - I don't think we can detect that.

@clauswilke Theme support sounds good. 

To make color settings always work correctly with `options`, we would essentially need to overload that function to detect and combine color/colour options, possibly with a warning message when that happens, akin to `function masked` warnings. Which doesn't seem ideal.

**Comment by hadley** [comment]
I think it's better to not implement this and instead wait for theme support for scale defaults.
