### ISSUE TITLE
Weights unaccounted for in geom_violin when scale = "counts"

### ISSUE THREAD

**Issue by jw5** [tidyverse/ggplot2#4628]
Current ggplot geom_violin fails to account for weighting when scaling violins by counts. Currently the scale = "counts" only uses the vector length of the values, rather than a normalized values*weights measure.

```r
# Test geom_violin

library(tidyverse)
library(ggplot2)

df <- tibble(name = factor(rep(c("a", "b"), 10)), value = runif(20), weights = rep(c(1, 10), 10))
print(df)

base_w <- ggplot(data = df,
       mapping = aes(x = name, y = value, weights = weights, color = name))

print(base_w +  geom_violin()                + ggtitle("Weighted 10x, scale = ''"))
print(base_w +  geom_violin(scale = "area")  + ggtitle("Weighted 10x, scale = 'area'"))
print(base_w +  geom_violin(scale = "width") + ggtitle("Weighted 10x, scale = 'width'"))
print(base_w +  geom_violin(scale = "count") + ggtitle("Weighted 10x, scale = 'count'", "Fails to account for weighted counts!"))

# Convert to unweighted form by replicating weighted "b" data
# Not when weights are in the millions :-(

dfa <- df %>% filter(name == "a")
dfb <- df %>% filter(name == "b")

df_replicated <- bind_rows(dfa, dfb, dfb, dfb, dfb, dfb, dfb, dfb, dfb, dfb, dfb)
df_replicated$weights <- NULL
print(df_replicated)

base_r <- ggplot(data = df_replicated,
               mapping = aes(x = name, y = value, color = name))

print(base_r +  geom_violin()                + ggtitle("Replicated 10X Unweighted, scale = ''"))
print(base_r +  geom_violin(scale = "area")  + ggtitle("Replicated 10X Unweighted, scale = 'area'"))
print(base_r +  geom_violin(scale = "width") + ggtitle("Replicated 10X Unweighted, scale = 'width'"))
print(base_r +  geom_violin(scale = "count") + ggtitle("Replicated 10X Unweighted, scale = 'count'", "Works correctly"))

```

**Comment by thomasp85** [comment]
hmm I think there is a need for both behaviours, no? You might want to scale by the absolute count or a weighted count, and currently only the former is possible. @clauswilke do you have any opinion on whether we should offer a fourth scaling option? It makes sense to me but I very rarely use these geoms anymore...

**Comment by clauswilke** [comment]
I'm not sure a fourth scaling option is needed. To scale by count without weights, wouldn't you simply not specify weights? I can't imagine a scenario where one would explicitly define weights and then choose an option that discards them.

I personally never use weights, but I've seen so many requests for them in various contexts that I believe they are important for many people.

**Comment by thomasp85** [comment]
Well, my thinking was that you might want the density estimation to be based on weighted points, but the relative sizing of the violins to be based on absolute count... maybe it is a stretch to think that is useful to someone..?

**Comment by jw5** [comment]
Sorry for the delayed response.

I think I understand your concern in breaking the underlying assumption that weights := f(counts), which I suppose could confuse some users. My perhaps unorthodox application of violin plots violates that assumption in order to "cram in" another independent variable that the data is dependent on. 

Background:
I am typically looking at data sets starting with anywhere from a million, to several hundred billion records with 5 to 500 fields. Needless to say, no direct mapping to ggplot aesthetics  is viable. So all my data goes through a sequence of pipelines that perform aggregation across various dimensions in an attempt to reduce the overall volume of data to something more manageable. Finally, I attempt to find a visual representation of the data that maximizes the information displayed with geometries, scale, shape and color mappings that highlight the critical differences i'm attempting to expose n the underlying data. Needless to say, I'm always short on "visual dimensions" when it comes to this final mapping. 

Breaking the assumption that weights is restricted to a function of counts is one way of obtaining another visual dimension. If you look at the above set of eight plots it is clearly visible that plot #8 is dramatically different than the other seven. For my use case, weights provide the overall shape of the internal distributions while count provides the scale that emphasizes the relative importance. While I could obtain plot #8 through replication, the replication factor is not in the 10x range, but rather the 1000X-100000X range. Infeasible with current ggplot performance. Further, this would not be a natural transformation of the data, as the counts and weights came from separate aggregation metrics and bloating the data via count replication would yield a very large data set (1000x-100000x) that was useful for only this one plot.

Now it may be there there is an alternate aesthetic mapping that could get me my desired goal of independent control of shape (weight) and size (count), but I couldn't find one. So perhaps if "overloading" count as the width scaling.

Note that I did try to find alternate mappings. One that seemed promising was:

`print(base_w +  geom_violin(aes(width = weights / 10), scale = "width") + ggtitle("Replicated 10X Unweighted, scale = 'width'"))
`
Note that the width must be normalized as no underlying scaling is currently performed!

Which produces the desired visual representation, but with the following message:

> Warning message:
> Ignoring unknown aesthetics: width 

Perhaps something along these lines would be a more appropriate solution?

**Comment by hadley** [comment]
Just to be clear about what the problem is: `StatYdensity`, which does the computation here, does support weights in the density estimation, but when rescaling it uses the number of data points rather than the sum of the weights. Whether or not this is the correct behaviour depends on the type of weights you are using. So I don't think it would be 100% correct to adjust the behaviour of `scale = "count"`, but it would be fine to add `scale = "weighted_count"` say. 

But this feels like a very niche use case, and given the other development priorities I think it's unlikely we'll ever implement this in ggplot2 (even just understand this issue has been fairly expensive). I think this would be more appropriate for a more specialised package, maybe ggdist.
