### ISSUE TITLE
coord_cartesian and geom_text vjust side effects

### ISSUE THREAD

**Issue by Salatbesteck** [tidyverse/ggplot2#4629]
When using coord_cartesian together with geom_text(vjust) labels positioned outside the plot range are added to the graph. See the example below:

```r
library(ggplot2)
p <- ggplot(mtcars, aes(wt, mpg, label = rownames(mtcars))) 
p1 <- p + geom_text(vjust = 0) + geom_hline(yintercept = 30, color = "red") 
p2 <- p + geom_text(vjust = 0) + 
  geom_hline(yintercept = 30, color = "red") + 
  coord_cartesian(ylim = c(30,300), expand = FALSE)
```
The original plot p1:
![image](https://user-images.githubusercontent.com/37980361/135118820-fc476f69-88e4-40ac-939c-8a95493e67d3.png)

The zoomed plot - p2:
![image](https://user-images.githubusercontent.com/37980361/135118724-5bad5dea-c638-4aa2-9546-1fe799fd9c30.png)

Here the label of the point _Fiat X1-9_ is visible on the chart, which should be the case as it is outside the optical zoom area.

**Comment by clauswilke** [comment]
Yes, it works like this by design. Set limits via scale functions if you want elements outside the limits to be removed.

**Comment by Salatbesteck** [comment]
For my clarification, why should the label Fiat X1-9 visible. It's outside the zooming area, so in my understanding when applying an optical zoom only datapoints within the zooming should be presented. I don't see a reason why suddenly points outside the area are moved into the zooming area
