### ISSUE TITLE
Potential segfault with saveRDS of list of empty ggplot()

### ISSUE THREAD

**Issue by bersbersbers** [tidyverse/ggplot2#4635]
I am investigating the segfaults I see in https://github.com/rstudio/rmarkdown/issues/2229. I have spent a few hours(!) minimizing my code to a few hundred lines which I cannot yet share. I did notice, though, that the stack traces now consistently point towards a chunk at the end of a `.Rmd` file - specifically, the `saveRDS` line.

```r
plotlist <- list()
plotlist[[1]] <- ggplot()
names(plotlist) <- c("plot")
saveRDS(c(plotlist), file.path("plot.rds")) # <--
```
(This is code minimized over and over again - there is much more happening in between in the full code.)

This `.Rmd`, when run via `rmarkdown`, `shiny` and `shinytest`, segfaults when rendered a second time, after being rendered once and after one `renderPlot(plot(NULL))`.

While this alone is not enough to repro the segfault, I guess, I do wonder if anyone sees some potential error right away.

**Comment by thomasp85** [comment]
There is no code in ggplot2 itself that can cause a segfault as it does not contain any compiled code. Which layers do the plot contain - it might be related to some extension geoms or a dependency of ggplot2

**Comment by bersbersbers** [comment]
> There is no code in ggplot2 itself that can cause a segfault as it does not contain any compiled code.

Thanks for confirming - one less package to care about.

> Which layers do the plot contain

None - this is the crazy part. While the snippet does not originate as such from the full code, it is part of the minimized example code, and the stack trace indicates `saveRDS` as the problematic line. I don't have much experience with segfaults - does this a potential bug has to be in these four lines, or can other code lines play a role as well?

**Comment by clauswilke** [comment]
ggplot objects contain the current environment and saving that could cause a segfault. In general, we advise against saving ggplot objects with `saveRDS()`. It is not reliable (though it shouldn't normally crash your session).

**Comment by bersbersbers** [comment]
> ggplot objects contain the current environment

Oh, I see. So ggplot() serves as some kind of canary, but I might/should now look which other variable from the environment (completely unrelated to the above snippet) may be corrupted. Thanks for that, that may help a lot actually.
