### ISSUE TITLE
geom_contour fails, but succeeds when the x and y values are rounded to five digits

### ISSUE THREAD

**Issue by alex-l-m** [tidyverse/ggplot2#4639]
plot_table %>%
      ggplot(aes(x = Comp.1, y = Comp.2, z = density)) + 
     geom_contour()

Fails with warning "Computation failed in `stat_contour()`: factor level [2] is duplicated"

After several hours of trying random things I found it works fine if I round the input values:

    plot_table %>%
      dplyr::mutate(Comp.1 = round(Comp.1, 5), Comp.2 = round(Comp.2, 5)) %>%
      ggplot(aes(x = Comp.1, y = Comp.2, z = density)) + 
      geom_contour()

I assume this cannot possibly be the intended of behavior, so there must be some bug.

I have no idea how to create synthetic data which reproduces this, so I'm putting my code and data in [a gist](https://gist.github.com/alex-l-m/3c6ccaeba5149df77b5a118d79da3aaf). It must be cursed in some way but not anything I can identify.

This is with ggplot2 version 3.3.5.

Another strange observation: I tried downgrading to version 3.2.0. I still got a warning, but it was "Computation failed in `stat_contour()`: dimensions of 'x', 'y' and 'z' do not match".

**Comment by clauswilke** [comment]
From the documentation:

> To specify a valid surface, the data must contain x, y, and z coordinates, and each unique combination of x and y can appear at most once. Contouring requires that the points can be rearranged so that the z values form a matrix, with rows corresponding to unique x values, and columns corresponding to unique y values. Missing entries are allowed, but contouring will only be done on cells of the grid with all four z values present. If your data is irregular, you can interpolate to a grid before visualising using the `interp::interp()` function from the interp package (or one of the interpolating functions from the akima package.)

**Comment by alex-l-m** [comment]
I see. It looks like there's very slight deviations from the grid, and rounding gets rid of them.

Is the change in error message intentional? Shouldn't it still display the "dimensions do not match" error?

**Comment by alex-l-m** [comment]
Ah, yeah, that's it:

    > factor(plot_table$Comp.1, levels = unique(plot_table$Comp.1))
    Error in `levels<-`(`*tmp*`, value = as.character(levels)) : 
      factor level [2] is duplicated

And the underlying reason is that converting to character results in fewer unique values:

    > length(unique(plot_table$Comp.1))
    [1] 123
    > length(unique(as.character(plot_table$Comp.1)))
    [1] 37

That's why factor isn't getting unique levels, despite including "unique" in the line.

I guess strange behaviors are inevitable when checking for equality of floating point values. I'll just remember to round input to geom_contour. But yes, neither this nor the previous error message were ideal. This was not an intuitive problem to check for, especially because print.tbl_df automatically rounds values so they "looked" like they were on a grid.

**Comment by clauswilke** [comment]
If you have any ideas to make the function more robust or produce better errors, feel free to let us know or submit a PR.
