### ISSUE TITLE
annote() generate unexpected X-axis order

### ISSUE THREAD

**Issue by limin321** [tidyverse/ggplot2#4645]
Please briefly describe your problem and what output you expect. If you have a question, please don't use this form, but instead ask on the mailing list <https://groups.google.com/forum/#!forum/ggplot2> or stackoverflow <http://stackoverflow.com>.

Please include a minimal reprex. The goal of a reprex is to make it as easy as possible for me to recreate your problem so that I can fix it. If you've never heard of a reprex before, start by reading <https://www.tidyverse.org/help/#reprex>, and follow the advice further down the page. Do NOT include session info unless it's explicitly asked for, or you've used `reprex::reprex(..., si = TRUE)` to hide it away.  

Delete these instructions once you have read them.

---
Brief description of the problem:
I want to plot a series of genes from 24 chromosomes. I want to use the start position of each gene as X-axis, log2 ratio as Y-axis, but label the X-axis with chromosome numbers. To do that, I add the max gene start position of one chromosome to the following chromosome. For example, chromosome 2 gene start position all become its original postion plus the max start postion of chromsome 1, chromosome 3 start positions all become their original position plus the max start position of chromosome2, and so on. In this way, all gene start positions are in order of smallest to greatest. They are then used as X-axis for plotting. 
The problem is feeling like the plot didn't plot out data as I expected, I want it to plot out from chr1, chr2, chr3 ...chr24.
Here is the output I got:
<img width="330" alt="Screen Shot 2021-10-18 at 2 35 28 PM" src="https://user-images.githubusercontent.com/42760669/137810008-102daa00-e603-4cca-a963-3348022bd45d.png">

you see chr12 is after chr1, instead of chr2 after chr1. I also checked the start postions of chr12, which are greater than chr2, not sure why they are plot before chr2 with smaller start gene positions.

```r
pos <- df1 %>% 
  group_by(chromosome) %>% 
  summarize(avg = round(mean(start))) %>% pull(avg)

t1 <- df1 %>% group_by(chromosome) %>% summarize(avg=max(start)) %>% pull(avg)
ggplot(df1) +
  annotate("point", x=df1$start, y=df1$log2, size=0.5, color=df1$chromosome) +
  annotate("segment", x=0, xend=max(df1$start), y=-0, yend=0,color="black")+
  annotate("segment", x=t1, xend=t1, y=-4, yend = 2, color = "grey")+
  scale_x_discrete(limits = pos, labels=unique(df1$chromosome) +
  labs(x = "chromosome") +
  ylim(c(-30,3))
# insert reprex here
```
Can anyone have any suggestions what may go wrong with my codes?

Your help is greatly appreciated.

Best,
Lim

**Comment by clauswilke** [comment]
Hello, questions for user support can be posted on the RStudio Community or on Stackoverflow. The github issue tracker is for bona-fide bug reports and feature requests.
