### ISSUE TITLE
Width argument to geom_errorbar not passed on when using stat_summary_bin

### ISSUE THREAD

**Issue by hummuscience** [tidyverse/ggplot2#4647]
When using `stat_summary_bin` and `geom = "errorbar"` the `width` argument used to set the width of the errorbars in `geom_errorbar` does not work.

The below code produces the same plots with different setting for width

Related to follwing StackOverflow issue: https://stackoverflow.com/questions/42418746/how-to-adjust-width-of-errorbar-created-with-stat-summary-bin

``` r
library(tidyverse)

iris %>%
  ggplot(aes(x = Sepal.Length, y = Sepal.Width, color = Species)) +
  stat_summary_bin(geom = "errorbar")
#> No summary function supplied, defaulting to `mean_se()`
#> No summary function supplied, defaulting to `mean_se()`
#> No summary function supplied, defaulting to `mean_se()`
```

![](https://i.imgur.com/GLVQXUz.png)

``` r
iris %>%
  ggplot(aes(x = Sepal.Length, y = Sepal.Width, color = Species)) +
  stat_summary_bin(geom = "errorbar", width = 0.1)
#> No summary function supplied, defaulting to `mean_se()`
#> No summary function supplied, defaulting to `mean_se()`
#> No summary function supplied, defaulting to `mean_se()`
```

![](https://i.imgur.com/5pjBOnL.png)

``` r
iris %>%
  ggplot(aes(x = Sepal.Length, y = Sepal.Width, color = Species)) +
  stat_summary_bin(geom = "errorbar", width = 2)
#> No summary function supplied, defaulting to `mean_se()`
#> No summary function supplied, defaulting to `mean_se()`
#> No summary function supplied, defaulting to `mean_se()`
```

![](https://i.imgur.com/2WPQLqN.png)

<sup>Created on 2021-10-20 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by thomasp85** [comment]
Ah, I can see where things run into each other. `stat_summary_bin` does not take a `width` paramater or aesthetic, but it does calculate one based on the given `bins`/`binwidth` argument (or its default). Since that is now present in the data given to `geom_errorbar` it takes precedence over the provided `width` parameter...

So, my initial hunch was correct, it was just a bit more complicated. I'm afraid we don't have a great solution for this at the moment. I'll keep this issue open to remind us to think about it

**Comment by teunbrand** [comment]
You can use `after_stat()` to work around this limitation.

``` r
library(ggplot2)

iris |>
  ggplot(aes(x = Sepal.Length, y = Sepal.Width, color = Species)) +
  stat_summary_bin(
    aes(width = after_stat(1)),
    geom = "errorbar"
  )
#> No summary function supplied, defaulting to `mean_se()`
#> No summary function supplied, defaulting to `mean_se()`
#> No summary function supplied, defaulting to `mean_se()`
```

![](https://i.imgur.com/didWkcp.png)

<sup>Created on 2024-03-28 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by teunbrand** [comment]
Should a parameter `width` override the `width` column in the data? For basically any other aesthetic given as a parameter, say `colour = "red"`, we override any `color` variable passed through `aes()` or computed by the stat.
