### ISSUE TITLE
`geom_contour()` documentation states false precedence of bin and binwidth parameters

### ISSUE THREAD

**Issue by eliocamp** [tidyverse/ggplot2#4651]
Right now the documentation for `geom_contour()` and friends states that the `bin` argument is overridden by the `binwidth` parameter. However, this seems not to be the case. 

``` r
library(ggplot2)


v <- ggplot(faithfuld, aes(waiting, eruptions, z = density)) 

# Defining bins
v + geom_contour(bins = 5)
```

![](https://i.imgur.com/1JuSkdp.png)

``` r
# Defining binwidth
v + geom_contour(binwidth = 0.001)
```

![](https://i.imgur.com/ab0NaMK.png)

``` r
# Defining both. Per documentation, binwidth should 
# take precedence and this should be the same as the second plot
v + geom_contour(binwidth = 0.001, bins = 5)
```

![](https://i.imgur.com/RiWyFc9.png)

<sup>Created on 2021-10-28 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

The issue lays on the `contour_breaks()` function, which computes the binwidth from the bins if bins is not NULL: 

https://github.com/tidyverse/ggplot2/blob/759c63c2fd9e00ba3322c1b74b227f63c98d2e06/R/stat-contour.r#L158-L170 

I believe that previous versions of `geom_contour()` did respect the documentation. Should the documentation be changed to reflect the new precedence or should the code be changed to reflect the documentation?

**Comment by thomasp85** [comment]
@clauswilke is this a leftover bug from the contour rewrite?

**Comment by clauswilke** [comment]
Possibly, though it's also possible it was never right. There's no technical reason I can see why the contour rewrite would have touched this part.

In any case, I have no strong opinion about the order of precedence, but I agree we should fix this. I'd vote for fixing the documentation. Let's not touch the code unless there's a good reason to do so.
