### ISSUE TITLE
Is it possible to make the width of geom_boxplot and binwidth in geom_density, and position "mapable" in aes()?

### ISSUE THREAD

**Issue by hugesingleton** [tidyverse/ggplot2#4658]
I wanted to draw histograms using the count scale overlapped with a density plot and add a boxplot below, and I want to repeat this over all faceted sub-graphs.

To calculate the proper height of the density, I need to multiply the ..count.. * appropriate binwidth for each sub-plot, which differs per each graph. There's no a universal common value valid for all histograms. I use the Freedman-Diaconis usually, but sometimes I want to provide my own choice. Similarly, to calculate the position and width of the boxplot, I need to know the maximum value of each chart (e.g. to put the boxplot at -10% of max with same width). But, again, this is different for each sub-plot (unless I use fixed Y scale with same limits per all graphs...)

Naively, I thought, that I could pre-calculate necessary values, store them in a data.frame and then map them in aes(). But the binwidth, width and position aren't supposed to be mapped.

One is allowed to provide only constants, but cannot take them from the corresponding dataset.

The only way was to split the dataset by the grouping columns, calculate the necessary values, make a list of per-group ggplots and then combine them via either patchwork (but this doesn't work with faceting and the author doesn't plan to fix it soon: https://github.com/thomasp85/patchwork/issues/277) or cowplot (this one works, but requires some additional coding).

My work could be much simplified, if only the binwidth and width could be parameterised, and the ..count..*column_from_dataset could be mapped.

Is there any chance to add it in future?

Below I show the exemplary code and the effect I wanted to achieve, but made "manually", step by step. Which is very tricky, because when I resize the plot, the layout changes (cowplot) by using relative scaling. I'd love to not have to doing this.

```
binwidth_diaconis_freedman <- function(x) {
    if(length(x) < 2) return(x/10)
    return(2 * IQR(x, na.rm = TRUE) / (length(x)^(1/3)))
}

graphs <- lapply(split(df, list(df$gr1, df$gr2)), function(l) {
    
    #l <- split(df, list(df$gr1, df$gr2))[[1]]
    bw <- binwidth_diaconis_freedman(l$values)

    ghist <- ggplot_build(ggplot(l, aes(x = values)) + geom_histogram(binwidth = bw)) 
    
    max_height <- max(ghist$data[[1]]$y)
    perc_height <- 0.1*max_height

    ggplot(l, aes(x = values)) + 
        facet_wrap(gr1~gr2, 
                   scales="free") + 
        geom_histogram(binwidth = bw, 
                       fill="white", 
                       col="black") + 
        geom_density(aes(y=..count.. * bw), 
                     fill="darkorchid1", 
                     alpha=0.2, 
                     col="darkorchid1") + 
        scale_y_continuous(name = "Count", 
                           labels = scales::label_comma(accuracy = 1)) + 
        geom_boxplot(aes(y = -1 * perc_height),
                     outlier.color = "gray50", 
                     width= perc_height, 
                     col="gray20",
                     size=.5, 
                     position=position_dodge(width=2*perc_height)) +
        
        geom_rug() +
        theme_bw() + 
        theme(axis.title.x=element_blank(),
              axis.title.y=element_blank(),
              plot.margin = unit(c(0,-.2,-1,-.2), "cm"))
})

grs <- cowplot::plot_grid(plotlist = graphs,scale=0.8, labels = rep("", 6), align = "hv") +
    theme(plot.margin = unit(c(0,0,1,1), "cm")) +
    draw_label("Value", x=0.5, y=  0, vjust=2, angle= 0) +
    draw_label("Count", x=  0, y=0.5, vjust= -0.5, angle=90)

title <- ggdraw() + 
              draw_label("Distribution of the vital signs at baseline", x = 0.05, hjust = 0)
cowplot::plot_grid(title, grs, ncol = 1, rel_heights = c(0.1, 1))
    
```
![obraz](https://user-images.githubusercontent.com/47183766/140260050-381d282f-e72b-4c6a-bde4-30c4121e23b5.png)

Not to mention, that this looks very weird using facet_grid...

![obraz](https://user-images.githubusercontent.com/47183766/140260155-00939284-1577-4642-9317-8ec647104c2c.png)

I'd love to keep my graphs consistent with the default ggplot2 styling when using facets.
To achieve this, all values in the aes() should come from the dataset, not from external single-value variable or hardcoded:

```
ggplot( my_dataset, aes(x = values)) + 

        facet_wrap(gr1~gr2, 
                   scales="free") + 

        geom_histogram(aes(binwidth = bw)) + 

        geom_density(aes(y=..count.. * bw)) +
 
        geom_boxplot(aes(y = -1 * perc_height, 
                               width = perc_height, 
                               position=position_dodge(width=2*perc_height))
       
```

This would be so simple and visually consistent.

**Comment by clauswilke** [comment]
Please provide a minimal reproducible example that distills your issue to its essence. There's way too much irrelevant detail in your post.

**Comment by hugesingleton** [comment]
@clauswilke I'm not sure how to add a working example of what is missing, if it's missing, but let me try:

The data:
```
df <- structure(list(gr1 = structure(c(1L, 1L, 1L, 1L, 1L, 1L, 1L, 
1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
1L, 1L, 1L, 1L, 1L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 
2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 
2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 
2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 
2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 3L, 3L, 3L, 3L, 3L, 
3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 
3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 
3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 
3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 
3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L), .Label = c("X", 
"Y", "Z"), class = "factor"), gr2 = structure(c(1L, 1L, 1L, 1L, 
1L, 1L, 1L, 1L, 1L, 1L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 
2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 
2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 
2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 2L, 2L, 2L, 2L, 
2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 
2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 
2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 1L, 1L, 
1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 2L, 2L, 2L, 2L, 
2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 
2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 
2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L), .Label = c("A", 
"B"), class = "factor"), values = c(0.0733973712533799, 0.0697293613698934, 
0.102683448520189, 0.0487695487000943, 0.205106181363666, 0.159035669118421, 
0.110351620037494, 0.0207292925346905, 0.122259659231185, 0.0157066562864822, 
20.6750305935923, 20.0211213093838, 21.5655302430046, 18.4686023060052, 
22.5519338159154, 20.6244801007123, 20.2377072788982, 21.0945842728043, 
21.0837569341144, 18.246170253159, 21.8998013820506, 19.8326093541378, 
22.8584324418656, 18.9870412985307, 20.5554146255417, 19.6616242054847, 
20.0645558668059, 19.977088359113, 20.6064224164085, 18.9858379303864, 
18.99757813783, 18.5918291396209, 20.4995137555724, 20.093389352048, 
20.8483901246638, 19.486806111397, 20.7315744596987, 19.6626914142884, 
21.8591557348387, 20.7655072981502, 20.0088549392756, 19.4422159666346, 
20.2623958487828, 19.4230244300043, 20.4993081847435, 19.9022757785227, 
21.8347008802671, 19.5528243103281, 18.843507077629, 19.5168636944089, 
19.0941453739455, 20.1644101924037, 20.8090812610125, 20.0642456513667, 
18.7417147036915, 21.8379750592094, 18.7956131342515, 19.4596665429375, 
20.1320596410178, 21.4942931079937, 0.966106388027121, 0.996760491050068, 
0.975193757126021, 0.842183554889353, 0.920954022234184, 0.996860243963798, 
0.993181045214292, 0.967845910173358, 0.961024249452834, 0.954234365703608, 
0.979584761329404, 0.933994014564882, 0.974768239386591, 0.823362961711481, 
0.970504933710197, 0.916560359119345, 0.824099224773592, 0.968771424560041, 
0.8209014244639, 0.956891611057596, 1.59537556253065, 2.79151824812018, 
2.42885067042269, 0.477939359567825, 3.15056024101998, 1.82328746022852, 
3.20053735027025, 4.12394583654091, 2.2267019347004, 4.46532087442173, 
3.03136546783142, 2.79784086622059, 5.19422412696102, 2.35544383014069, 
1.14709252312651, 2.76429604393493, 3.11770204196736, 2.16718216814166, 
4.29157857182692, 1.66836580769552, 2.13247155869466, 1.47291489822319, 
2.69524434581336, 2.84919918532188, 4.48684350571098, 1.69811881368391, 
4.20994015555533, 0.86778643464153, 1.09801254522142, 2.53009188487143, 
3.00918287459958, 3.76218716765246, 4.464804861343, 3.81914074504281, 
2.52772302512912, 3.67693672393175, 2.14637396208292, 4.15827785104216, 
3.97983730127652, 2.72993650482531, 2.6948785926973, 3.28505975356107, 
4.75533339676977, 4.00170335669257, 4.2258284874958, 3.5314843016917, 
2.38510941179217, 0.985428402819221, 2.13999393171482, 1.91288694078206, 
0.71561905668791, 0.592393928107901, 0.629527643341252, 0.617854930321108, 
0.87506516435019, 0.791854297242051, 0.332521936957495, 0.841609563654414, 
0.681772775205482, 0.434331063107759, 0.719450173095495, 0.720436836886541, 
0.622322089941363, 0.691545289403829, 0.455973993098666, 0.628320902907914, 
0.457608871032543, 0.721230412894615, 0.417057518846836, 0.69458044037249, 
0.765582755187692, 0.856733333215553, 0.683545967477748, 0.615720048630509, 
0.784685721699002, 0.698676185147128, 0.687591332948515, 0.704901878485528, 
0.64450759836378, 0.690443458144281, 9.56236849193277, 9.08460922991192, 
10.7865281388757, 9.14881285573863, 10.2133640739734, 12.4520771280063, 
8.25882515861193, 9.68657722793995, 9.93427438384345, 10.1890515290523, 
9.62857474580041, 9.2075167992164, 12.2250844490148, 10.6309780789267, 
9.47031397398847, 9.39455907829025, 10.9594544101093, 7.80151480129669, 
10.0172448650331, 9.86399684586222, 9.51269765795659, 11.294471320787, 
11.1168433605057, 11.3584526520635, 8.73321204505872, 9.24776507408582, 
10.307811956138, 10.6395236166973, 9.73090863879671, 11.9321854496828, 
9.91140233650066, 9.376413693499, 9.85269304375105, 10.1705533698205, 
9.95305954421127, 11.3053949849572, 8.19327015169982, 10.8194641845065, 
9.76104444040051, 9.25165956157164, 8.46836333862509, 10.6952969739684, 
9.89765727830814, 10.2705774419072, 9.6939327820413, 10.6231654213364, 
10.4718698926015, 8.61688449391942, 9.98800744560889, 11.7892698968548
)), row.names = c(NA, -210L), class = "data.frame")
```

The minimal code, which will not work, because the stuff I need is missing:
```
# Extend the source data by adding certain parameters to be used later to properly overlay histogram with density
# here it's only binwidth, for simplicity:

df %>% 
   group_by(gr1, gr2) %>% 
   mutate(binwidth = (2 * IQR(values, na.rm = TRUE) / (length(values)^(1/3)))) %>% 
   ungroup() -> df_ext

# Now use it, map the binwidth in the aes() of geom_density and geom_histogram

ggplot(df_ext, aes(x = values)) + 
   ggplot(df_ext, aes(x = values)) + 
   facet_wrap(gr1 ~ gr2, scales="free") + 
   geom_histogram(aes(binwidth = binwidth)) + 
   geom_density(aes(y=..count.. * binwidth))

`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
Error in FUN(X[[i]], ...) : object 'binwidth' not found
In addition: Warning message:
Ignoring unknown aesthetics: binwidth 
```

As we can see, geom_density cannot see the "binwidth", even if it's part of the dataset it is working with.
And geom_histogram doesn't understand mapping of "bindwidth" - it's just not implemented to be used here.

Instead, "binwidth" parameter has to be provided outside the aes(), as a constant. But the constant is different for each group. That's why I needed to iterate through the groups and calculate the needed parameters respectively, then generate a single ggplot2 and finally combine them.

The essence is:  would you consider adding to aes() mapping:
- "binwidth" in geom_histogram
- y=..count.. * something (here: ..count.. * binwidth) in geom_density
- "width" and "position" in geom_boxplot?

**Comment by hadley** [comment]
Thanks for filing this issue! Unfortunately, I think it's out of scope for this package: developing good software requires relentless focus, which means that we have to say no to many good ideas. Even though I'm closing this issue, I really appreciate the feedback, and hope you'll continue to contribute in the future 😄

**Comment by hugesingleton** [comment]
Dear @hadley ,
Thank you for your explanation. If I wanted to created own versions of geom_histogram, geom_boxplot and geom_denisty, that would implement the mentioned variables in aes(), could you guide me on there starting point that I should begin with? I mean some certain source file, some function, or manual or is this too scattered across files? I need only the three changes, so I could try implementing them and keep them for my own use (I don't even need a package for that, just some helpers.r overriding the current implementation). ggpplot2 itself is too huge for me, so I'm a bit lost where to start.

**Comment by teunbrand** [comment]
@hugesingleton 
The [extending ggplot2](https://ggplot2.tidyverse.org/articles/extending-ggplot2.html) article gives a brief overview.
The ggplot2 [book](https://ggplot2-book.org/) has chapters 19-22 discussing extensions.

**Comment by hugesingleton** [comment]
@teunbrand Thank you very much for the resources! I will also search for the references to these functions in the source code using GitHub website capabilities and check how others implemented their extensions (e.g. gghalves or ggalluvial). My clients truly loved the above presented combinations of histograms and boxplots + density plots (with counts rather than densities), so I am doubly motivated to make it more visually consistent with the default facetting in ggplot2.
