### ISSUE TITLE
na.rm is ignored with geom_area

### ISSUE THREAD

**Issue by billdenney** [tidyverse/ggplot2#4660]
The `na.rm` argument appears to be ignored with `geom_area()`.  The warning below should not show up when `na.rm` is `TRUE`.

``` r
library(ggplot2)

d <- data.frame(x=1:3, y=c(1, NA, NA))
ggplot(d, aes(x=x, y=y)) +
  geom_area(na.rm=TRUE)
#> Warning: Removed 2 rows containing missing values (position_stack).
```

![](https://i.imgur.com/r2wslkr.png)

<sup>Created on 2021-11-05 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by clauswilke** [comment]
The warning is generated by the position function, and it's not clear if and how the `na.rm` argument should be propagated to it. Having said that, I agree it's confusing.

**Comment by thomasp85** [comment]
I think we had a similar issue a while back - we ended up not finding any great solution at that point in time

**Comment by billdenney** [comment]
Thanks for thinking about/looking into this issue.

If it is infeasible to propagate `na.rm` to the position function correctly, a helpful change would be to add a class to all `na.rm=FALSE` warning messages so that they can be suppressed when generating the figure.

**Comment by clauswilke** [comment]
Another option would be to add an `na.rm` argument to the position functions.

**Comment by billdenney** [comment]
> Another option would be to add an `na.rm` argument to the position functions.

That sounds preferable to me, if it is a reasonable option.

**Comment by hadley** [comment]
While I agree it would be nice if the positions had their own `na.rm` arguments that you could use to suppress this warning, implementing that is unlikely to ever make it to the top of our to do list, so I'm going to close this issue. Even though I'm closing this issue, I really appreciate the feedback, and hope you'll continue to contribute in the future 😄
