### ISSUE TITLE
coord_cartesian breaking a geom_area with an alpha channel causes the fill to be dropped

### ISSUE THREAD

**Issue by billdenney** [tidyverse/ggplot2#4661]
When combining `coord_cartesian()` where it breaks in the middle of a `geom_area()` fill, the fill does not show up.

Specifically, a gray (more precisely, black with 20% alpha) trapezoid should show up in the bottom figure.

``` r
library(ggplot2)

d <- data.frame(x=1:4, y=1:4)
# no alpha channel, no coord_cartesian, works as expected
ggplot(d, aes(x=x, y=y)) +
  geom_area(na.rm=TRUE)
```

![](https://i.imgur.com/4YPWiXt.png)

``` r
# with alpha channel, no coord_cartesian, works as expected
ggplot(d, aes(x=x, y=y)) +
  geom_area(na.rm=TRUE, alpha=0.2)
```

![](https://i.imgur.com/Bp1AF0g.png)

``` r
# with alpha channel, with coord_cartesian not breaking in the middle, works as expected
ggplot(d, aes(x=x, y=y)) +
  geom_area(na.rm=TRUE, alpha=0.2) +
  coord_cartesian(xlim=c(0.5, 6.5))
```

![](https://i.imgur.com/FM0h5qM.png)

``` r
# with alpha channel, with coord_cartesian breaking in the middle,
# does not work as expected (nothing shows up)
ggplot(d, aes(x=x, y=y)) +
  geom_area(na.rm=TRUE, alpha=0.2) +
  coord_cartesian(xlim=c(2, 3.5))
```

![](https://i.imgur.com/5MtzkgJ.png)

<sup>Created on 2021-11-05 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by yutannihilation** [comment]
This should be the same issue as #4498 (I think you are using Windows, right?), which is a problem on R's side. An workaround (until the upcoming real fix, https://github.com/tidyverse/ggplot2/issues/4498#issuecomment-955787535) is to use AGG as the graphic backend of RStudio.

I cannot reproduce this on my Linux laptop.

``` r
library(ggplot2)

d <- data.frame(x=1:4, y=1:4)

ggplot(d, aes(x=x, y=y)) +
  geom_area(na.rm=TRUE, alpha=0.2) +
  coord_cartesian(xlim=c(2, 3.5))
```

![](https://i.imgur.com/O4cQknE.png)

<sup>Created on 2021-11-07 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by billdenney** [comment]
Thanks for pointing me to the duplicate.  Yes, I am using Windows.
