### ISSUE TITLE
Error: geom_density requires the following missing aesthetics: y

### ISSUE THREAD

**Issue by chrismahony** [tidyverse/ggplot2#4665]
When I run:

ggplot(subset(Kdm2acoverage.plot2.data,group %in% c("0_Infla", "0_Persis", "0_resolved", "0_rest")),aes(x=position,y=coverage,fill=group,colour=group))+geom_line()
[New Microsoft PowerPoint Presentation (2).pdf](https://github.com/tidyverse/ggplot2/files/7513145/New.Microsoft.PowerPoint.Presentation.2.pdf)

I get the attahced graph. But I would like to shade in the plots and show anoverlay.

When I try:

ggplot(subset(Kdm2acoverage.plot2.data,group %in% c("0_Infla", "0_Persis", "0_resolved", "0_rest")),aes(x=position,y=coverage,fill=group,colour=group))+geom_line()+geom_density() 

I get;
Error: geom_density requires the following missing aesthetics: y

Even why I try to add 
geom_density(aes(x=position,y=coverage))

Thanks for your help,
Chris

**Comment by karawoo** [comment]
This type of question is a better fit for [RStudio Community](https://community.rstudio.com/). Please try asking there with a [minimal reproducible example](https://reprex.tidyverse.org/). The ggplot2 issue tracker is intended for bug reports and feature requests.
