### ISSUE TITLE
discarded breaks in scale_x_continuous(trans="log10") w/ min(x)==0

### ISSUE THREAD

**Issue by WillForan** [tidyverse/ggplot2#4668]
`scale_x_continuous(trans="log10",...)` discards `breaks=` for values below first valid `log10` but within original data range. 

Despite the warning message
> Transformation introduced infinite values in continuous x-axis 

It's hard to debug/discover because the line or points still show a value at x=0.

Is it reasonable to have the default/unspecified limits when trans=log10 to include the min break?
Or warn that the breaks will not be shown because they are outside the plot's limits?

```r
library(ggplot2)
# generic line plot
explt <- function(d)
  ggplot(d) + 
   aes(x=x, y=y) + geom_line() + 
   ggtitle(paste0(min(d$x),'-1000'))

# generate data. i sets min x value
mkdata <- function(i) data.frame(x=seq(0, 1000, 100) + i, y=0:10)

# x axis break label for "1" is MIA
explt(mkdata(0)) + scale_x_continuous(breaks=c(1,1000),trans="log10") 

# 1 is labeled b/c log10(min(x)) is within plot
explt(mkdata(1)) + scale_x_continuous(breaks=c(1,1000),trans="log10") 

# 1 is labeled b/c limits explicitly set
explt(mkdata(0)) + scale_x_continuous(breaks=c(1,1000),trans="log10", limits=c(1,NA)) 
```

![image](https://user-images.githubusercontent.com/680742/141337231-66def0e1-7def-4bb0-b12b-8bf009590ec1.png)
![image](https://user-images.githubusercontent.com/680742/141339333-20a468de-9e55-4933-8f53-1e6a7d5df6e1.png)

**Comment by hadley** [comment]
We've tried to do better automatically here, but have unfortunately never managed to come up with a strategy that works generally, so for now you'll just need to tweak manually.
