### ISSUE TITLE
log transform in scale_y_continuous unnecessarily drops negative values

### ISSUE THREAD

**Issue by halidaee** [tidyverse/ggplot2#4678]
Using log transformations for scale_y_continuous (ditto scale_x_continuous but less common a need) unnecessarily drops negative values. Using log(abs(y)) * sign(y) would avoid this issue. Not sure if this is intentional to bring people's attention to what log transformation does, but seems like it will just cause unnecessary extra labor of manually transforming y via dplyr::mutate in many use cases. Apologies if this is an intentional choice!

**Comment by thomasp85** [comment]
This is definitely intentional - a log transformation does not make sense for negative values and thus have to drop them. What you describe is another type of tranformation altogether
