### ISSUE TITLE
Dataset licenses

### ISSUE THREAD

**Issue by bkmgit** [tidyverse/ggplot2#4681]
Typically datasets are released under different licenses than software. It may be helpful to add license information to the data in https://github.com/tidyverse/ggplot2/tree/main/data-raw

**Comment by hadley** [comment]
Basically, my position is that under US copyright law, datasets are not copyrightable, so the software licenses don't apply anyway. But I don't think it's worth the time to clearly articulate or communicate this position and the status quo is fine for 99.999% of users.
