### ISSUE TITLE
Tear down geom_dotplot and start over

### ISSUE THREAD

**Issue by higgi13425** [tidyverse/ggplot2#4688]
geom_dotplot() is the neglected, autistic, red-headed stepchild of {ggplot2}.
It does not really work.

It could be a really useful geom for actually representing counts, and more visually accurate than a histogram, which **_appears_** to be continuous. 

The y-axis does not make sense (0-1??, it should be a count)
The y-axis does not scale properly
There is poor control of color
Grouping does not work
coord_flip does not work

But it is currently severely neglected, as issues #2203, #2868, and #3563 (and several others) have been met with a shrug and auto-closed. 

It might be better to deprecate it if everyone on the maintenance team hates it so much. 
Or tear it down and start over. 
I think it is time to make it useful or kill it off.

It looks kind of pathetic next to the other well-tended geoms.

Peter

**Comment by ptoche** [comment]
You can tweak your own `geom_dotplot`, with a bit of effort, as I attempted [here](https://stackoverflow.com/questions/53697235/ggplot-dotplot-what-is-the-proper-use-of-geom-dotplot). 

I would vote to deprecate `geom_dotplot`, as it really only serves to waste users' time and generate frustration.

**Comment by thomasp85** [comment]
Please refrain from using derogatory language in our issues.

There are issues with geom_dotplot, but certainly not enough to deprecate it and cause noise and issues for all those that use it. The extension system is there for you to make something that fits your needs better, if our development speed and priorities does not suit you.

**Comment by ptoche** [comment]
Oh Gosh! Apologies. It wasn't my intention to offend. I thought it was a well established view that `geom_dotplot()` does not produce what most people expect. There are viable alternatives to `geom_dotplot` based on extension packages (see tjebo's answer linked above). Since `geom_dotplot` is a rather specialized `geom` that falls outside immediate priorities (I haven't needed to use it in over five years myself) and since existing discussions on github point to confusion about the code behind `geom_dotplot` (to quote  yutannihilation  "The code in question is almost 10-years old. I attempted to dive into the history, but couldn't figure out what's the right thing here..."): not just the [meaningless axis](https://github.com/tidyverse/ggplot2/issues/2203) but also the [strange grouping](https://github.com/tidyverse/ggplot2/issues/4614), I thought it was a constructive suggestion to take it out of the main `ggplot2` and leave it to extension packages.

**Comment by higgi13425** [comment]
Thomas is right/edits made above.But Thomas' suggestion to redirect to extensions may be the way to go.
Compared to the many amazing components of ggplot2, geom_dotplot is aged.I think modern data journalism has changed people's expectations, and many are disappointed by geom_dotplot because they expect something different.Something like the median age plot at the end of this article: More than 278,000 students have experienced gun violence at school since Columbine

| 
| 
| 
|  |  |

 |

 |
| 
|  | 
More than 278,000 students have experienced gun violence at school since...

The Washington Post spent months determining how many children have been exposed to gun violence during school h...
 |

 |

 |


Maybe it would make sense to put a statement at the top of the geom_dotplot documentation to address these expectations - something like
"This geom is based on the dotplot introduced by Cleveland (reference Graphical Perception: Theory, Experimentation, and Application to the Development of Graphical Methods on JSTOR  1984). If you are hoping to make discrete count plots or pictograms, you may be better served by the {waffle} package found [here](https://github.com/hrbrmstr/waffle)"

| 
| 
| 
|  |  |

 |

 |
| 
|  | 
Graphical Perception: Theory, Experimentation, and Application to the De...

The subject of graphical methods for data analysis and for data presentation needs a scientific foundation. In t...
 |

 |

 |



I don't know if this helps, but a suggestion.



    On Friday, December 3, 2021, 09:24:43 PM EST, Patrick Toche ***@***.***> wrote:  
 
 


Oh Gosh! Apologies. It wasn't my intention to offend. I thought it was a well established view that geom_dotplot() does not produce what most people expect. There are viable alternatives to geom_dotplot based on extension packages (see tjebo's answer linked above). Since geom_dotplot is a rather specialized geom that falls outside immediate priorities (I haven't needed to use it in over five years myself) and since existing discussions on github point to confusion about the code behind geom_dotplot (to quote yutannihilation "The code in question is almost 10-years old. I attempted to dive into the history, but couldn't figure out what's the right thing here..."): not just the meaningless axis but also the strange grouping, I thought it was a constructive suggestion to take it out of the main ggplot2 and leave it to extension packages.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
