### ISSUE TITLE
Confidence intervals missing in geom_smooth with limits in the coordinates.

### ISSUE THREAD

**Issue by rpouillot** [tidyverse/ggplot2#4689]
The se fill from `geom_plot` drops when `xlim` is set in `coord_cartesian`. 
The behavior is even stranger when faceting: the se fill drops only on some of the facets.    

  ```
library(ggplot2)
#set.seed(1234)
Data <- data.frame(x = rep(1:25, 2),
                   y = runif(50),
                   z = rep(c("a","b"), each=25))

ggplot(Data, aes(x=x, y=y)) +
  geom_smooth() +
  coord_cartesian(xlim = c(5,NA)) 

ggplot(Data, aes(x=x, y=y)) +
  facet_wrap(~z) +
  geom_smooth() +
  coord_cartesian(xlim = c(5,NA)) 
  ```
![image](https://user-images.githubusercontent.com/29258335/144854943-bccef349-87f3-49e2-beeb-abf3a75957c5.png)

![image](https://user-images.githubusercontent.com/29258335/144855098-8318094d-eada-42de-a0af-896c4dd2df84.png)

**Comment by teunbrand** [comment]
I managed to reproduce this with a (un)lucky seed in the windows graphics device only (worked fine with ragg device). Might be related to #4498?

**Comment by thomasp85** [comment]
Yeah, this is most definitely related to transparent polygons outside of the device region - we cannot do anything about the state of the default windows device - please use ragg instead for a modern and better graphic device

**Comment by rpouillot** [comment]
Thank you very much and sorry for the duplicate. Using ragg now!

**Comment by thomasp85** [comment]
No worries - you are not the first to get bitten by this :-)
