### ISSUE TITLE
should legend styling elements within guide_* instead be within theme?

### ISSUE THREAD

**Issue by davidhodge931** [tidyverse/ggplot2#4693]
I've noticed that legends are not able to be styled completely within a theme, and instead need arguments provided to a guide_* layer.

This seems sub-optimal, as you are unable to have all styling aspects of a plot within 1 theme.

For example, say you wanted to always have black frame and black ticks around plots with colorbar legends, you then need to always add a guide_colorbar layer. It would preferable that if in theme, you could add colourbar.frame and colourbar.ticks arguments etc. in the same way that you would do for axis.line or axis.ticks. 

Is it possible to move legend styling aspects from guide_* to theme*? Or to have them in both? 

```{r}
library(ggplot2)
library(palmerpenguins)

custom_theme <- theme_minimal()

p <- ggplot(penguins) +
  geom_point(aes(x = bill_length_mm, y = body_mass_g, col = flipper_length_mm)) +
  custom_theme

p +
  guides(col = guide_colorbar(frame.colour = "#323232", ticks.colour = "#323232"))
```

**Comment by hadley** [comment]
In principle yes, but the way these argument interact is complex and a lot of people depend on the details, so it's not worth the risk of changing unless there's the potential for a very large payoff.
