### ISSUE TITLE
Provide filled counter-part for geom_step

### ISSUE THREAD

**Issue by holgerbrandl** [tidyverse/ggplot2#4695]
To visualize discrete state change progressions, it would be great if `geom_step` could be extended to also provide a filled counter-part (similar to `geom_area`).

For a discussion ( including some rather tedious workarounds) see https://stackoverflow.com/questions/21887088/generate-a-filled-geom-step

Currently, with geom_area we get 
![image](https://user-images.githubusercontent.com/200952/145805739-ecfa7d6b-6b3a-4e98-9eeb-58b7202ce1d2.png)

Because of the way geom_area works there are linear interpolations between subsequent points, which are incorrect as they are not reflected in the step-wise nature of the data.

Since the state changes are discrete in nature, geom_step gives a more precise (but visually flawed) picture
![image](https://user-images.githubusercontent.com/200952/145805850-06abb349-55d7-4d5f-9744-8aa785ac3e16.png)

Example data:
[filled_step_data.csv](https://github.com/tidyverse/ggplot2/files/7703479/filled_step_data.csv)

Example code:
```r
require(tidyverse)

read_csv("filled_step_data.csv") %>%
      ggplot(aes(timestamp, accu_moves)) +
     # geom_step() +
     geom_area()
```

**Comment by smouksassi** [comment]
you might want to look at :
https://adibender.github.io/pammtools/reference/geom_stepribbon.html

ggalt:
https://github.com/hrbrmstr/ggalt/blob/master/R/stat-stepribbon.r

and change it to be like filled areas where the bottom is zero
apply stairstepn only to the y instead of ymax and ymin

**Comment by holgerbrandl** [comment]
Thanks @smouksassi  for the pointer. Indeed 
```r
read_csv("~/filled_step_data.csv") %>%
  ggplot(aes(timestamp)) +
  geom_ribbon(aes(ymin = 0, ymax = accu_moves), stat = "stepribbon")
```
produces a filled geom_step chart (wich has the same shape as geom_step) 
![image](https://user-images.githubusercontent.com/200952/145882198-730d5aa2-2b48-4be2-90c8-b2087d0d43da.png)

**Comment by holgerbrandl** [comment]
Was it fixed or rejected @thomasp85 ? I still think this would complement ggplot2 in an often-needed manner.

**Comment by thomasp85** [comment]
It was closed because a solution already exists in an extension. We aim to avoid adding new geoms to ggplot2 if at all possible since the maintenance burden is already quite high as is

**Comment by holgerbrandl** [comment]
I understand. Thanks for the update.

**Comment by jan-glx** [comment]
`ggalt::GeomStepribbon` does not seem to work with `position="stack"`; that me wonder if the ability to play Tetris is considered "within the scope of ggplot2"?

**Comment by teunbrand** [comment]
@jan-glx Having a compatible implementation between `ggalt::stat_stepribbon()` and `position = 'stack'` is in scope of {ggalt}, not {ggplot2}.
