### ISSUE TITLE
Export `datetime_scale`

### ISSUE THREAD

**Issue by coolbutuseless** [tidyverse/ggplot2#4701]
`datetime_scale()` is not currently exported, but may be required when writing extensions to ggplot.  E.g. Writing new sclaes for custom geoms etc.

All other scales are exported. i.e. `continuous_scale()`, `discrete_scale()` and `binned_scale()`

Could `datetime_scale` also be exported?

**Comment by hadley** [comment]
Sure. Do you want to do a PR?
