### ISSUE TITLE
Shall `NextMethod` be used in `$<-.uneval`

### ISSUE THREAD

**Issue by elong0527** [tidyverse/ggplot2#4704]
Current package require R >= 3.3 in DESCRIPTION file. 

Shall the code below be replaced to `new_aes(NextMethod())` for consistency? 

https://github.com/tidyverse/ggplot2/blob/c89c265a57fd71f8a0288ce81037296aadc0a012/R/aes.r#L139-L143

**Comment by hadley** [comment]
That's likely to work, but I don't think it's important enough to spend our limited development time on (especially since this is a rarely used function).
