### ISSUE TITLE
Greek Symbol appears to be a white square box

### ISSUE THREAD

**Issue by NQKhanh0504** [tidyverse/ggplot2#4706]
---

Hi,

I am currently having the issue with the greek symbols in ggplot2, it returned a white square box for every greek symbol I tried. I am using macOS (Monterey) with the latest RStudio. 

![image](https://user-images.githubusercontent.com/90165260/147599252-1852d540-3069-4369-9e57-6591f9c7b3fe.png)

```r
library(ggplot2)

ggplot() +
  labs(subtitle = parse(text = "omega==2"))
ggplot2
```

**Comment by thomasp85** [comment]
This is a graphics device issue, not something to do with ggplot2. Please open an issue in the appropriate place for the graphic device showing this problem

**Comment by IndrajeetPatil** [comment]
For future reference:
https://github.com/IndrajeetPatil/ggstatsplot/issues/685#issuecomment-1031681279
