### ISSUE TITLE
Problem with horizontal lines in geom_bar

### ISSUE THREAD

**Issue by VitorBSP** [tidyverse/ggplot2#4708]
Hello Everybody!
I'm developing an R markdown document with geom_bar graphs, but I have a little problem, with horizontal lines, like blocks, in my graphs design.

I have a df like this:
| Grupo        | Valor |
|--------------|-------|
| Documentação | 275   |
| Documentação | 56    |
| Documentação | 275   |
| Documentação | 56    |
| Documentação | 350   |

And my code is:
```r
bar_g2<-function(data, y, x,category, manual_fill){
  data %>% 
  ggplot() + 
  geom_bar(aes(y={{y}}, x = {{x}}, fill = {{category}}), stat='identity') + scale_fill_manual(values={{manual_fill}})
}
bar_g2(Des_Grupo, Valor, Grupo, Grupo, gt)
```

So, the graphs is like this

  <p align="center"><img align="center" src="https://i.imgur.com/rWD4CIb.png" height="210px" width="350" /></p>

But I want the graphs is like this: (without horizontal lines)

  <p align="center"><img align="center" src="https://plotnine.readthedocs.io/en/stable/_images/tutorials_miscellaneous-show-counts-and-percentages-for-bar-plots_3_0.png" height="210px" width="350" /></p>

**Comment by VitorBSP** [comment]
I noticed I have one graph without this horizontal lines
 <p align="center"><img align="center" src="https://i.imgur.com/XWNx2rm.png" height="210px" width="350" /></p>

But for this graphs I used group_by, so I tested for the other plor and it works too

 <p align="center"><img align="center" src="https://i.imgur.com/tmJz0wv.png" height="210px" width="350" /></p>

Have a more simple way?

**Comment by clauswilke** [comment]
Hello, please ask your question over on the RStudio Community or on Stackoverflow. The ggplot2 issue tracker is not meant for user support. It's only for genuine bugs in the code and for feature requests.
