### ISSUE TITLE
scale_x_datetime limits with histogram/stat_bin: warning message about missing values

### ISSUE THREAD

**Issue by cmaimone** [tidyverse/ggplot2#4710]
When using scale_x_datetime to set limits on the axis with a histogram, a warning message is produced:

```r
d1 <- lubridate::now()
tibble(date = d1) %>% 
    ggplot(aes(date)) + 
    geom_histogram() + 
    scale_x_datetime(limits = c(d1-1, d1+1))
```

produces:

```
Warning message:
Removed 2 rows containing missing values (geom_bar).
```

There is only 1 row of data.  Often with geom_histogram() this warning happens when a bin/bar is excluded from the plot (not a row from the original data).  But in this case, there should only be one bin/bar.  What are the extra bars/values that are missing?  The plot appears normal: there is one bar as there should be.  Initially I thought it was because bins is set to the default of 30.  

The warning message changes if you explicitly set bins=1 

```r
d1 <- lubridate::now()
tibble(date = d1) %>% 
    ggplot(aes(date)) + 
    geom_histogram(bins = 1) + 
    scale_x_datetime(limits = c(d1-1, d1+1))
```

produces:

```
Warning message:
Removed 1 rows containing missing values (geom_bar).
```

And if the limits are increased enough, the warning message goes away:

```r
d1 <- lubridate::now()
tibble(date = d1) %>% 
    ggplot(aes(date)) + 
    geom_histogram(bins = 1) + 
    scale_x_datetime(limits = c(d1-10, d1+10))
```

This happens with more observations as well, and you get the same warning message whether or not bars are actually excluded:

```r
d1 <- seq(lubridate::now(), by=1, length.out=10)
tibble(date = d1) %>% 
    ggplot(aes(date)) + 
    geom_histogram() + 
    scale_x_datetime(limits = c(min(d1), max(d1)))  # limits too small - min and max bars not drawn
```

```r
d1 <- seq(lubridate::now(), by=1, length.out=10)
tibble(date = d1) %>% 
    ggplot(aes(date)) + 
    geom_histogram() + 
    scale_x_datetime(limits = c(min(d1)-1, max(d1)+1))  # larger limits - all bars show
```

This seems to be misleading and inconsistent.  With real data, the warning about 2 missing values appears regardless of the limits I set.

I tried to track this through stat_bin, but I couldn't find a point where it seemed like this would be caused.

**Comment by ptoche** [comment]
Not idea, but you're creating a histogram with one observation. If you call `geom_bar()` instead, you don't get a warning.

I used this followed by our code. 

```
library("lubridate")
library("ggplot2")
library("tibble")
```

Using `data.frame` instead of `tibble` produced the same warning.

You may want to make a reprex next time, for convenience.

**Comment by hadley** [comment]
Could you please rework your reproducible example to use the [reprex package](http://reprex.tidyverse.org) ? That makes it easier to see both the input and the output, formatted in such a way that I can easily re-run in a local session.

**Comment by yutannihilation** [comment]
> There is only 1 row of data

The calculated data has 30 bins and the right-most and left-most ones are always removed because they are over the limits, unfortunately. See https://github.com/tidyverse/ggplot2/issues/2887#issuecomment-485721611 and https://github.com/tidyverse/ggplot2/issues/4083 for more details.

``` r
library(ggplot2)
library(tibble)

d1 <- lubridate::now()
tibble(date = d1) |> 
  ggplot(aes(date)) + 
  geom_histogram(colour = "red") + 
  scale_x_datetime(limits = c(d1-1, d1+1))
#> `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
#> Warning: Removed 2 rows containing missing values (`geom_bar()`).
```

![](https://i.imgur.com/0SbKoFf.png)

Use `coord_cartesian()` instead if your intention is to zoom.

``` r
tibble(date = d1) |> 
  ggplot(aes(date)) + 
  geom_histogram(colour = "red") + 
  coord_cartesian(xlim = c(d1-1, d1+1))
#> `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
```

![](https://i.imgur.com/HPZv3Am.png)
