### ISSUE TITLE
Default behaviour of geom_col renders bars inconsistently in graph with many x values

### ISSUE THREAD

**Issue by ReedMerrill** [tidyverse/ggplot2#4712]
When trying to use geom_col to plot count data, certain bars in the graph output are missing. I would expect every bar to show up in the graph, even with the amount of x values I am using. When the fill and color are manually set to the same value the problem is resolved, however the bars are thickened and the resulting plot looks sloppy. The actual use case is plotting daily COVID case counts.

## Reprex

The only I'm loading for this is ggplot2.

``` r
library(ggplot2)
x <- 1:600
y <- rnorm(600, mean = 500, sd = 100)
data <- data.frame(x, y)
ggplot(data, aes(x, y)) +
  geom_col()
```

![](https://i.imgur.com/kmDrzMJ.png)

``` r
ggplot(data, aes(x, y)) +
  geom_col(color = 'blue', fill = 'blue')
```

![](https://i.imgur.com/OWGsMAG.png)

<sup>Created on 2022-01-07 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

Of course, I should probably just to get rid of the borders around the bars, but it would still be nice if the default geom_col arguments produced representative graphs.

**Comment by ptoche** [comment]
This is not a reprex: you did not list the packages you used. Can you make a proper reprex, with the reprex package? Moreover, what is your expected output? What output do you get?

**Comment by karawoo** [comment]
None of the bars are missing, this is an artifact of having so many bars so close together. You'll have to adjust the resolution and/or width of your plot to see the bars individually with space in between, or set the column width to 1 if you don't want space in between.

**Comment by ReedMerrill** [comment]
@karawoo Thanks for clarifying! I still find that this is a bit of an issue though, as another graphing package I tried rendered the same example perfectly. Don't get me wrong, I think ggplot2 is the best, but this issue with its default `geom_col` output for data with many x values is still a bummer.

Thanks again!

**Comment by karawoo** [comment]
It's really more to do with the graphics device than ggplot2. [ragg](https://ragg.r-lib.org/)`s default output looks better, so that's an option too:

``` r
library("ggplot2")
x <- 1:600
y <- rnorm(600, mean = 500, sd = 100)
data <- data.frame(x, y)

file <- knitr::fig_path(".png")
ragg::agg_png(file)
ggplot(data, aes(x, y)) +
  geom_col()
invisible(dev.off())
knitr::include_graphics(file)
```

![](https://i.imgur.com/NeHNoOU.png)

<sup>Created on 2022-01-07 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by ReedMerrill** [comment]
Great, thanks for the recommendation!
