### ISSUE TITLE
Reversed legend order when geoms are horizontal

### ISSUE THREAD

**Issue by willgearty** [tidyverse/ggplot2#4715]
When flipping the orientation of a geom (e.g., geom_bar or geom_errorbar), the order of the color/fill/etc groups are flipped, but not the order of those groups within the legend. The ideal behavior would be that by default the legend order always matches the order in the plot.

```r
ggplot(mpg, aes(y = class)) +
  geom_bar(aes(fill = drv)) +
  theme(legend.position = "top")
```
![image](https://user-images.githubusercontent.com/7232514/150391472-a3d67122-6db0-4043-b9ef-03c4d424b126.png)

I [now] understand that you can flip the order in the plot using `reverse = TRUE` in the `position` argument or in the `guide_legend` function, but shouldn't this just be the default when the orientation of these geoms is flipped?

**Comment by hadley** [comment]
@mjskay do you see an obvious way to fix this?

**Comment by mjskay** [comment]
I don't see an obvious fix. Beyond this one example, I think the layout order of factors is somewhat inconsistent across different parts of ggplot. 

After a bit of experimentation I put together a table showing some of the inconsistencies. Each entry is where the first level of a factor is placed:

|   | horizontal orientation<br>(or an x mapping)| vertical orientation<br>(or a y mapping)|
|--|---------|--------|
|**mapping to x/y aes**| left| bottom |
|**position = stack**| right | top |
|**position = dodge**| left |bottom|
|**legend**| left | top |

So, for example, a factor mapped to the x axis is laid out left-to-right, but bars stacked horizontally are laid out right-to-left. Unless I've missed something, a comprehensive solution would require every cell in the same column of this table to be equal. To do that at least two rows have to change (and I have probably missed some rows...).

One particular snag is that legends lay out factors top-to-bottom and the y axis goes bottom-to-top, arguably for good reasons in both cases, at least when considered separately.

**Comment by hadley** [comment]
So this is probably a situation which each default makes sense in the context it was made, but the overall picture becomes inconsistent. I think it's unlikely that resolving this will be worth the effort since it will just shift the pain around in a way that mostly affects current users.

**Comment by Ramsas88** [comment]
I would like to reverse the order of the legend for a horizontal bar chart. When adding guides(fill = guide_legend(reverse = TRUE))
to the ggplot it works fine . However, after applying ggplotly() the legend is again in the default order. please suggest
