### ISSUE TITLE
na.rm=TRUE not suppress warnings in geom_violin

### ISSUE THREAD

**Issue by jayoung** [tidyverse/ggplot2#4716]
hi there,

I think this is related to issues [3532](https://github.com/tidyverse/ggplot2/issues/3532) and [4660](https://github.com/tidyverse/ggplot2/issues/4660).

If I understand right, the `na.rm=TRUE` I'm using in the `geom_violin` code below should be suppressing the warning about small groups, but it's not.   

I'm getting a lot of warnings from a facetted geom_violin when I knit - these are expected given the data, but I want to suppress them so that I can be sure I'm paying attention to other warnings I might care more about. `suppressWarnings()` helps to some extent, but the warnings still appear in the R Markdown window of Rstudio, and I'm trying to be good about paying attention to stuff in there.

I'm using `ggplot2_3.3.5` and `R version 4.1.2 (2021-11-01)`

thanks, and all the best,

Janet Young

``` r
library(ggplot2)
library(reprex)

ggplot(mtcars, aes(factor(cyl), mpg)) + 
    geom_violin(aes(fill = factor(vs)), na.rm=TRUE)
#> Warning: Groups with fewer than two data points have been dropped.
```

![](https://i.imgur.com/2EibDYR.png)

<sup>Created on 2022-01-20 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by karawoo** [comment]
In this case the warning you are seeing is not related to the `na.rm` argument. There are no `NA` values in the data, but there is only one row that has 4 cylinders and a V-shaped engine. One data point is not enough to draw a violin, so we have to discard that observation. The warning is given since we are removing a real data point. Unfortunately there isn't an argument to `geom_violin()` that will control this, your best bet is using `suppressWarnings()` as you mentioned.

**Comment by jayoung** [comment]
ah - I see. thanks, @karawoo.

But there is something weird about this warning from `geom_violin` that means it's not behaving like a generic warning when I am in a markdown document - it does not get fully suppressed by `suppressWarnings()`.

This example should should you what I mean if you knit it (although I apologize - I am having a hard time properly inserting Rmarkdown code into a github issue that is already in markdown. I had to add backslashes before the delimiters for each chunk that you'll have to remove to run it. There must be a better way.)


```
---
title: "test"
output: 
  html_document:
    number_sections: true
---

# test suppressWarnings using a basic warning function

suppressWarnings() always seems to work, whether the code chunk has warning=TRUE or  warning=FALSE. I don't see the warnings in the knitted doc, and I don't see them appear in the 'R markdown' window/console area when I knit. 

##  warning=TRUE
\```{r warnings code 1, warning=TRUE}
testit1 <- function() warning("testit1")
suppressWarnings(testit1())
\```

##  warning=FALSE
\```{r warnings code 2, warning=FALSE}
testit2 <- function() warning("testit2")
suppressWarnings(testit2())
\```

# suppressWarnings behaves differently when the warning comes from geom_violin

suppressWarnings() doesn't fully work on geom_violin like it did on the testit functions.  If the code chunk has warning=TRUE then I see the warning appear in the knitted doc. 

##  warning=TRUE
\```{r warnings code 3, warning=TRUE}
library(ggplot2)
suppressWarnings(ggplot(mtcars, aes(factor(cyl), mpg)) + 
    geom_violin(aes(fill = factor(vs)), na.rm=TRUE))
\```

##  warning=FALSE
If the code chunk has warning=FALSE then I see the warning appear in the 'R markdown' window/console area when I knit. 
\```{r warnings code 4, warning=FALSE}
suppressWarnings(ggplot(mtcars, aes(factor(cyl), mpg)) + 
    geom_violin(aes(fill = factor(vs)), na.rm=TRUE))
\```

```

**Comment by karawoo** [comment]
The warning comes from the `print()` method that displays the plot and not from the `ggplot(...) + geom_violin(...)` code that creates it. You could suppress it with something like 

```r
library(ggplot2)
p <- ggplot(mtcars, aes(factor(cyl), mpg)) + 
    geom_violin(aes(fill = factor(vs)), na.rm=TRUE)
suppressWarnings(print(p))
```

If you have further questions I'd recommend asking the folks over on [RStudio Community](https://community.rstudio.com/)

**Comment by jayoung** [comment]
got it - thanks again. I'm glad to have squished those warnings - I just couldn't seem to let this one go.

Confusing - there's some hidden ggplot magic I'm not understanding. If anyone else stumbles on the same question and finds this thread, note that 
```
suppressWarnings(print(p))
```
gets rid of the warnings, but this:
```
suppressWarnings(p)
```
does not.  The `print` has to be explicitly called, not implied by use of `p`.  I've gotten a little too used to `p` and `print(p)` behaving identically in other contexts.
