### ISSUE TITLE
non-uniform 'Rounding' sampler used

### ISSUE THREAD

**Issue by blosloos** [tidyverse/ggplot2#4718]
On latest R version 4.1.2, ggplot2 version 3.3.5.9000 gives the following warning message when loading the package:

```
> library(ggplot2)
...
Warning message:
In (function (kind = NULL, normal.kind = NULL, sample.kind = NULL)  :
  non-uniform 'Rounding' sampler used
```

No idea if this results from ggplot2 itself, of from any of its dependencies. Thank you for maintaining ggplot2!

**Comment by karawoo** [comment]
This isn't coming from ggplot, most likely you changed the sampling method either earlier in your code or in a previous session whose workspace was restored:

``` r
library("ggplot2") # no warning
detach("package:ggplot2")
set.seed(123, sample.kind = "Rounding")
#> Warning in set.seed(123, sample.kind = "Rounding"): non-uniform 'Rounding'
#> sampler used
library("ggplot2")
#> Warning in (function (kind = NULL, normal.kind = NULL, sample.kind = NULL) :
#> non-uniform 'Rounding' sampler used
```

<sup>Created on 2022-01-24 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by blosloos** [comment]
Thanks for checking so quickly ... I will have another look at my side
