### ISSUE TITLE
Axis ticks reserve space, even when absent

### ISSUE THREAD

**Issue by teunbrand** [tidyverse/ggplot2#4722]
Hi there,

I've come across a few cases on SO where some confusion was created by axis ticks creating whitespace around the plot, even when `axis.ticks = element_blank()` ([example 1](https://stackoverflow.com/q/70945828/11374827), [example 2](https://stackoverflow.com/a/70924084/11374827)). I'm not sure whether this is intentional or not, but I found it to be a bit counterintuitive. To illustrate:

``` r
library(ggplot2)

p <- ggplot(mpg, aes(displ, cty)) +
  geom_point()

p +
  theme(
    axis.ticks = element_blank(),
    axis.ticks.length = unit(2, "cm") # exaggerated for clarity
  )
```

![](https://i.imgur.com/PZHWcsX.png)

There are other ways to arrive at the same plot without the involvement of axis tick length, so it doesn't seem like the axis tick lengths are a necessary part for this purpose.

``` r
p +
  theme(
    axis.ticks = element_blank(),
    axis.text.x.bottom = element_text(margin = margin(t = 2, unit = "cm")),
    axis.text.y.left   = element_text(margin = margin(r = 2, unit = "cm"))
  )
```

![](https://i.imgur.com/348b1SQ.png)

<sup>Created on 2022-02-01 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

If the ggplot2 maintainers agree with me, I could draft a PR to remove the empty space when the axis ticks are blank.

**Comment by smouksassi** [comment]
setting length to negative value is a workaround but agree that this is a weird unexpected behavior and not consistent with other places where we use element blank to suppress the reserved space

``` r
library(ggplot2)
library(gridExtra)
p <- ggplot(mpg, aes(displ, cty)) +
  geom_point()

grid.arrange(p,
             p +theme(axis.text = element_blank()),
             p +theme(axis.text = element_blank(),axis.title = element_blank()) ,
             p +theme(axis.text = element_blank(),axis.title = element_blank(),axis.ticks = element_blank() ),
             p +theme(axis.text = element_blank(),axis.title = element_blank(),axis.ticks = element_blank(),
                               axis.ticks.length = unit(0.1, "npc")),
             p +theme(axis.text = element_blank(),axis.title = element_blank(),axis.ticks = element_blank(),
                      axis.ticks.length = - unit(0.1, "npc"))
                      
                      
                  ,ncol =1)  
```

![](https://i.imgur.com/PVu6ZJ6.png)

<sup>Created on 2022-02-01 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by hadley** [comment]
Axes are parameterised differently to other geoms since their length is not supplied by the element, but instead but a separate theme option. So I think the current behaviour, while a little surprising, is consistent and not worth changing.
