### ISSUE TITLE
cannot orient facet label text after switch 

### ISSUE THREAD

**Issue by fBedecarrats** [tidyverse/ggplot2#4725]
The function `element_text( )` applied to `theme(strip.text.y)` enables to rotate facet labels in plots. But it doesn't work after switching.
```r
library(ggplot2)
# In this example facet labels rotate correctly
ggplot(mtcars, aes(disp, mpg)) + 
  geom_point() +
  facet_grid(cyl ~ gear) + 
  theme(strip.text.y = element_text(angle = 0))
# In this example facet rotation does not work, whatever the angle specified
ggplot(mtcars, aes(disp, mpg)) + 
  geom_point() +
  facet_grid(cyl ~ gear, switch = "y") + 
  theme(strip.text.y = element_text(angle = 0))
```
(And a million thanks to the package maintainers for this beauty!)

**Comment by smouksassi** [comment]
#response_container_BBPPID{font-family: initial; font-size:initial; color: initial;}  Try:+                                                                                                                                       theme(strip.text.y.left = element_text(angle = 0))                                                                                                                                                                                 From: ***@***.***: February 5, 2022 17:17To: ***@***.***: ***@***.***: ***@***.***: [tidyverse/ggplot2] cannot orient facet label text after switch (Issue #4725)  
The function element_text( ) applied to theme(strip.text.y) enables to rotate facet labels in plots. But it doesn't work after switching.
library(ggplot2)
# In this example facet labels rotate correctly
ggplot(mtcars, aes(disp, mpg)) + 
  geom_point() +
  facet_grid(cyl ~ gear) + 
  theme(strip.text.y = element_text(angle = 0))
# In this example facet rotation does not work, whatever the angle specified
ggplot(mtcars, aes(disp, mpg)) + 
  geom_point() +
  facet_grid(cyl ~ gear, switch = "y") + 
  theme(strip.text.y = element_text(angle = 0))
(And a million thanks to the package maintainers for this beauty!)

**Comment by fBedecarrats** [comment]
Thank you very much, it works indeed.
