### ISSUE TITLE
Feature Request: Excel-Like "Display Units" functionality

### ISSUE THREAD

**Issue by eutwt** [tidyverse/ggplot2#4727]
In Excel, there is an option to choose the units when making a plot. For example, if you select "Millions", the axis tick values are all divided by 1 million and the word "Millions" appears next to the axis indicating the units. This is very useful because the units are indicated and the plot looks better without ,000,000 at the end of all the y-axis numbers.

![image](https://user-images.githubusercontent.com/11261404/152703925-81af29a7-5fdf-4d97-b4b0-a623e8a73c39.png)

I can get there in ggplot2 by working out the right `x` and `y` position for annotate so that the label is in the top left and not obstructing anything, and then giving the right function to labels in `scale_y_continuous`. But, it would be nice to have a ggplot function for this. The label ("Millions") and function (./1e6) can be user-supplied, the big pain is just figuring out the right x and y values for each plot and each time you resize a plot.

```{r}
df <- 
  structure(list(date = structure(c(18628, 18659, 18687, 18718, 
  18748, 18779, 18809, 18840, 18871, 18901, 18932, 18962), class = "Date"), 
      y = c(6105750.57579939, 6119933.22024793, 4020995.18830257, 
      6935125.38889255, 12647068.2650316, 6810926.72861688, 10050003.3378196, 
      12234936.8401193, 9163733.44758565, 11271291.6355059, 7451434.07531243, 
      8564463.78746752)), row.names = c(NA, -12L), class = "data.frame")
 
ggplot(df, aes(x = date, y = y)) +
  theme_minimal() +
  geom_line(size = 1.2) +
  annotate("text",
    x = min(df$date) - 36, max(df$y) - 1e6, label = "Millions", hjust = 0, vjust = 1,
    angle = 90, color = "grey40"
  ) +
  coord_cartesian(xlim = range(df$date), clip = "off") +
  scale_y_continuous(labels = function(x) x / 1e6)
```
![image](https://user-images.githubusercontent.com/11261404/152699153-0ccc5534-469b-4786-9c1e-0df44aa89e69.png)

**Comment by clauswilke** [comment]
This exists through various functions provided by the scales package. For example:
https://scales.r-lib.org/reference/label_number.html

If there are functions you think are missing, please report there.

**Comment by eutwt** [comment]
@clauswilke The label_number functions change the y-axis labels, sure. The functionality being described in this issue is to add a label, e.g. "Millions" to the top left of the plot outside the axis. This is not something that should be done in scales, because it's altering the plot, not taking a vector and outputting another vector. Perhaps this is not a worthwhile feature for ggplot, but certainly it is not possible with the scales package.
