### ISSUE TITLE
ggsave, %>% mash together

### ISSUE THREAD

**Issue by petyaracz** [tidyverse/ggplot2#4729]
You expect to be able to pipe a plot into ggsave. But you can't!

```
library(tidyverse)

# this works:

p = iris %>% 
  ggplot(aes(Sepal.Length,Sepal.Width)) +
  geom_point()

p %>% ggsave(filename = 'iris.png')

# this doesn't:

iris %>% 
  ggplot(aes(Sepal.Length,Sepal.Width)) +
  geom_point() %>% 
  ggsave(filename = 'iris.png')

> Error in UseMethod("grid.draw") : no applicable method for 'grid.draw' applied to an object of class "c('LayerInstance', 'Layer', 'ggproto', 'gg')"

```

R version 4.1.2 (2021-11-01)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Big Sur 11.4

tidyverse_1.3.1

**Comment by karawoo** [comment]
The issue here is operator precedence. Something like this would work if you don't want to store the plot object separately.

``` r
library("ggplot2")
library("magrittr")

(iris %>% 
 ggplot(aes(Sepal.Length,Sepal.Width)) +
 geom_point()) %>%
  ggsave(filename = 'iris.png')
#> Saving 7 x 5 in image
```

<sup>Created on 2022-02-08 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by agilebean** [comment]
I think curly brackets would allow better readability:

library("ggplot2")
library("magrittr")

```
{
    iris %>% 
        ggplot(aes(Sepal.Length,Sepal.Width)) +
        geom_point()
} %>%
  ggsave(filename = 'iris.png')
```
