### ISSUE TITLE
Legend glyphs for geom_pointrange do not follow their plotted direction

### ISSUE THREAD

**Issue by andrewheiss** [tidyverse/ggplot2#4732]
*(This is super similar to this past issue https://github.com/tidyverse/ggplot2/issues/1389, but the addition of bidirectional geoms in v3.3.0 have changed the circumstances of that original issue)*

---
 
Since ggplot2 3.3.0, geoms like `geom_boxplot()` and `geom_pointrange()` work with either the x or the y aesthetic, thus eliminating the need for packages like {ggstance} for horizontal point ranges:

```r
library(ggplot2)

df <- data.frame(x = 1:3, y = 1:3)

ggplot(df, aes(x = x, y = y, color = factor(x))) +
  geom_pointrange(aes(xmin = x - 1, xmax = x + 1))
```

![](https://i.imgur.com/Rba1ANw.png)

Currently, however, the legend keys for point ranges show vertical lines regardless of the direction of the actual point range. There are ways to adjust the legend keys by either [modifying some of the underlying grid grobs](https://stackoverflow.com/a/41475858/120898), or by adding an empty `stat_summary()` layer in combination with `geom_point()` and `geom_line()` ([example](https://stackoverflow.com/a/40229390/120898)), but these are fairly hacky.

In a previous issue #1389, [the official recommendation from Hadley was to use **ggstance**](https://github.com/tidyverse/ggplot2/issues/1389#issuecomment-336525032), but now that `geom_pointrange()` can go an any direction now since v3.3.0, it would be neat if the legend glyphs matched the direction of the geoms for things like point ranges and box plots. I have no idea how feasible or difficult that would be though.

Thanks!

**Comment by mjskay** [comment]
(looking up how I solved this in ggdist) It should be possible to check `params$orientation` inside `draw_key_pointrange()` and then use either `draw_key_path()` or `draw_key_vpath()` on this line depending on the current orientation:

https://github.com/tidyverse/ggplot2/blob/c89c265a57fd71f8a0288ce81037296aadc0a012/R/legend-draw.r#L184

**Comment by smouksassi** [comment]
we also need this for horizontal boxplots legend
 also not sure how to communicate the fatten setting to geom pointrange legend

**Comment by hadley** [comment]
@mjskay any interests in doing a PR for this?
