### ISSUE TITLE
Multiple median midpoints with scale colour gradient

### ISSUE THREAD

**Issue by ThomasDelSantoONeill** [tidyverse/ggplot2#4733]
Hi, say I built a plot where the Y axis maps a numerical variable and the X axis a factor variable of 4 levels (i.e. 4 groups). Then I decide to map the data with a geom_jitter and colour the plot with a divergent gradient. My question is: is there a way for the midpoint of the divergent scale colour to start exactly at the median of each level (for this of course the legend would not make sense but as a way of visualising medians with colours).

![image](https://user-images.githubusercontent.com/43112803/153599871-b0451549-f23c-4ca4-ae27-6ba18c6a3852.png)

**Comment by clauswilke** [comment]
Honestly the right way to do this is to write a few lines of code that create a data column which gives you the distance from the median, and then you use that to color. I don't see that we would add a feature like this to the ggplot2 code base directly, it doesn't make much sense. The API overhead way exceeds the benefits, given that what you want is easily doable.
