### ISSUE TITLE
scatter plot labels low resolution

### ISSUE THREAD

**Issue by muliv02** [tidyverse/ggplot2#4738]
hey everyone,
im working on my first  football scatter plot on R using ggplot2.
my current code:
plot<-ggplot(dbn, aes(distpc, poctofthird, label=Player)) +
  geom_point() +
  geom_text(data=subset(dbn,poctofthird>0.06|distpc>4 |Player=="Junior Firpo"),color="black",size=2,check_overlap = TRUE,hjust = 0.1, nudge_x = 0.05,vjust=0)
plot+theme_solid(fill="gray")

but, the labels look on very low resolution (like in the attached photo). how can i fix it?
thanks

![image](https://user-images.githubusercontent.com/95971231/154963171-21073337-3a9e-4261-a18c-abd13610da06.png)

**Comment by yutannihilation** [comment]
Hi, this sort of question is a better fit for [RStudio Community](https://community.rstudio.com). Please ask there with a minimal reproducible example (your code is not reproducible because we don't know what `dbn` is). We use this issue tracker for bug reports and feature requests.

**Comment by lilbigdee240** [comment]
@$lilbigdee@cashapp.com

**Comment by lilbigdee240** [comment]
-open cash app android on google dribe
 [ ] 


- [ ] 

- [ ] 

- [ ] 

- [ ] 

- [ ] 

- [ ] 

- [ ] 

- [ ] 

- [ ] 

- [ ]
