### ISSUE TITLE
Encoding error with path argument in ggsave

### ISSUE THREAD

**Issue by Morais14** [tidyverse/ggplot2#4740]
---

When I try to export a graph with the `ggsave` function and the `path` argument has characters from the Portuguese alphabet like "ç" and accent "´" I get the error message **"Error: cannot open stream"**. The function's path argument with `path = "Apresentação/gráficos/OUVIDORIA/"` does not work, however, with  `path = "Apresentacao/graficos/OUVIDORIA/"` works. Other functions that use the `path` argument work normally, only the `ggsave` function is showing this error.

```r
library(ggplot2)


ouvidoria_numeros <- data.frame(Item = rep("Ouvidoria IFB",12),
                                Unidade = c("CBRA","CCEI","CEST","CGAM","CPLA","CREM",
                                            "CRFI","CSAM","CSSB","CTAG","Reitoria","IFB"),
        `Quantidade.Manifestações` = c(40,13,11,12,20,5,8,6,4,12,41,70))


ouvidoria1 <- ggplot(data = ouvidoria_numeros, 
                     aes(x = Unidade, y = `Quantidade.Manifestações`)) +
  geom_bar(stat = "identity", color = "#018c34", fill = "white",size = 1) +
  ggtitle("Ouvidoria IFB 2021") +
  geom_text(aes(label=`Quantidade.Manifestações`,
                y=`Quantidade.Manifestações` + 0.1),
            position = position_dodge(width = 0.9), 
            vjust=-0.25,
            color = "#018c34",
            show.legend = F) +
  theme(text = element_text(size=10,  family="open",colour = "#018c34"),
        axis.title.x=element_blank(),
        axis.title.y = element_text(margin = margin(t = 0, r = 5, b = 0, l = 0)),
        axis.text.x=element_text(colour="#018c34"),
        axis.text.y=element_text(colour="#018c34"),
        panel.background = element_rect(fill = "white",
                                        colour = "white"
        ),
        plot.title = element_text(hjust = 0.5,
                                  family = "open",
                                  colour = "#018c34",
                                  face = "bold",
                                  size = 10),
        legend.title = element_blank()
  ) +
  expand_limits(y = 200)


ouvidoria1


ggsave(filename = "ouvidoria.svg",device = "svg",
       path = "Apresentação/gráficos/OUVIDORIA/")

ggsave(filename = "ouvidoria.svg",device = "svg",
       path = "Apresentacao/graficos/OUVIDORIA/")

```

**Comment by yutannihilation** [comment]
> only the `ggsave` function

`ggsave()` passes the `path` to the backend functions, `svg()` in your case, so probably there are not much that ggplot2 can do, unfortunately. I guess you have the same problem without ggplot2 e.g.

``` r
svg(filename = "Apresentação/gráficos/OUVIDORIA/ouvidoria.svg")
plot(0)
dev.off()
```

The chances are

* If you are on Windows, non-ASCII characters (e.g. `"ç"`) get transliterated (e.g. `"c"`) on console. You might need to use unicode escaped character (e.g. `"\u00e7"`).
* The graphics device (`svg()`) fails to handle the non-ASCII filepath. In this case, you can try different graphics devices (e.g. `ragg::agg_png()` or `svglite::svglite()`).
* Simply the base R functions fail to handle the non-ASCII filepaths. In this case, probably there's no hope. You might have to wait for R 4.2.0.

Anyway, this sort of question is a better fit for [RStudio Community](https://community.rstudio.com). Please ask there with a minimal reproducible example. If you find ggplot2 is responsible for this problem, feel free to open another issue. Thanks!
