### ISSUE TITLE
Reduction of elements in vector graphics by removing/merging invisible objects

### ISSUE THREAD

**Issue by w2felix** [tidyverse/ggplot2#4742]
Dear team,
I love that it is possible to create vector graphics with ggplot2.
But plotting scatter plots or other plots with many elements will lead to files with MANY objects, which I would love to avoid.
I could export them into png, but would lose the vectors or I could merge points using e.g. geom_hex.
But I would love to include only visible points into the final vector graphics and remove all hidden elements. Is there a way to do this?

Thank you very much!
Best
Felix

**Comment by yutannihilation** [comment]
Hi, this sort of question is a better fit for [RStudio Community](https://community.rstudio.com). Please ask there with a minimal reproducible example. We use this issue tracker for bug reports and feature requests.
