### ISSUE TITLE
Support `rlang` dynamic dots 

### ISSUE THREAD

**Issue by mone27** [tidyverse/ggplot2#4752]
At the moment ggplot is using base `...`, and `rlang` dynamic dots are not supported [https://rlang.r-lib.org/reference/dyn-dots.html](https://rlang.r-lib.org/reference/dyn-dots.html).

I think this could be a good addition to ggplot as it add the support of:
 - splice arguments 
 -  name injection 
 - ignoring trailing commands. 
 At the same time it should not change the current features of ggplot.

The implantation should also be quite straightforward: replace `list(...)` with `list2(...)`

At the moment I can find that dynamic dots is supported only in [`guides`](https://github.com/tidyverse/ggplot2/blob/759c63c2fd9e00ba3322c1b74b227f63c98d2e06/R/guides-.r#L66).

If there is no reason in not having this feature I can try to make a PR for it.

**Comment by hadley** [comment]
This seems like a good idea to me. A PR would be great just to see how much code this would affect.
