### ISSUE TITLE
text rendered incorrrectly when size and justification parameters are supplied to geom_label()

### ISSUE THREAD

**Issue by david-romano** [tidyverse/ggplot2#4753]
I posted about this in [the RStudio Discourse forum](https://community.rstudio.com/t/strange-effect-of-justification-parameters-on-geom-label-rendering/131047?u=dromano), but didn't explicitly point out the effect of supplying the `size` parameter.  Have received no responses so am posting here.

The problem appears to be an interaction between the `size` parameter of `geom_label()` and how the justification parameter values are applied to the text itself, but is not apparent unless off-center justification is supplied.

``` r
library(tidyverse)

tibble() %>% 
  ggplot() +
  geom_label(aes(0, 0, label = 'text'), 
             hjust = 0,
             size = 20,
             )
```

![](https://i.imgur.com/fSUWZ6n.png)

<sup>Created on 2022-03-11 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by hadley** [comment]
Slightly more minimal reprex:

``` r
library(ggplot2)

ggplot() +
  annotate("label",
    x = 0, 
    y = 0, 
    label = "text",
    hjust = c(0, 1),
    size = 20,
  )
```

![](https://i.imgur.com/k26uDO1.png)

<sup>Created on 2022-03-14 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by javlon** [comment]
Text renders correctly if you rewrite the default label.padding unit. The problem occurs with units "lines" and "char", other units seem to be working fine.

```
library(ggplot2)

ggplot() +
  annotate("label",
           x = 0, 
           y = 0, 
           label = "text",
           hjust = c(0, 1),
           size = 20,
           label.padding=unit(0.5, "cm")
  )
```
![image](https://user-images.githubusercontent.com/5397821/183534496-1b193a0c-ad82-4055-869c-960a74879e55.png)
