### ISSUE TITLE
stat_summary with geom_vline: Improve documentation?

### ISSUE THREAD

**Issue by jarauh** [tidyverse/ggplot2#4761]
I find that the documentation of `stat_summary` is very much tailored to the default case of `geom = "pointrange"`. However, `stat_summary` is also useful with other geoms.

In my application, would like to mark quantiles in a density plot using vertical lines.  I figured out one way to do it within ggplot2 (and without generating a separate data.frame containing the quantiles) using stat_summary as follows:

```r
ggplot(mtcars, aes(mpg)) + geom_density() +
  stat_summary(aes(x = 0, y = mpg),
               fun.data = function(x) data.frame(xintercept = quantile(x, c(0.1, 0.5, 0.9))),
               geom = "vline")
```

Now a couple of questions occurred to me: First, is this a legitimate use of `stat_summary`? I am asking because the documentation of `stat_summary` is very much tailored to the default case of `geom = "pointrange"`. For example, the documentation of the argument `fun.data` explains:

> fun.data A function that is given the complete data and should return a data frame with variables ymin, y, and ymax.

This seems to be wrong: In my example, it suffices if `fun.data` returns a data.frame with all required aesthetics.

If my example is a legitimate use of `stat_summary`, I would suggest that the documentation should be updated. I would be glad to contribute to this, but before that I would like to make sure that I understand the philosophy behind `stat_summary`. Is it correct to say the following?

1. `stat_summary` computes summary statistics of the values of `y` stratified according to the value of `x`.
2. To explain the argument `fun.data`: A function that is given the complete data (for a single value of `x`) and should return a data.frame that contains all aesthetics that are needed by `geom`. For example, when `geom = "pointrange"`, `fun.data` should have variables `ymin`, `y`, and `ymax`.
3. I find the section about the argument `orientation` a little misleading and not precise enough.  In any case, one could add: `orientation` does not affect the computation of the summary statistics, which will always be done on values of `y`.

One could also add the above example to the documentation.

Finally, it is a little unfortunate that in this example, `stat_summary` has to be given two aesthetics, including the "dummy aesthetics"; however, at the moment, I don't have any idea how to simplify this.

**Comment by hadley** [comment]
This is an ok way to combine `stat_summary()` and `geom_vline()`, but I generally wouldn't recommend it so I don't think it needs to be documented. Instead, I think you'd be better off computing the summary outside of ggplot2 with dplyr or similar.

**Comment by jarauh** [comment]
Ok. Could you please add a reason why you generally recommend to compute summaries outside of ggplot2?

The problem with doing things outside of ggplot and using a separate data.frame is that it does not play along well with facetting etc. (unless I know beforehand which facets I will need).

**Comment by hadley** [comment]
It's a little dangerous because you have no way to see what you're actually calculating.

**Comment by jarauh** [comment]
That might well be a general warning against using R, but okay. Thanks for your time!
