### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by Codezy99** [tidyverse/ggplot2#4771]
The `bin` parameter in the `geom_histogram` function creat some double counted bins. With the example below, we should see a equal high histogram. But we will actually see some peaks in between. Besides with the `binwidth`, this issue is not presented anymore

```r
df <- data.frame(position = rep(-200:200,5))
## with parameter bins it generate the wrong plot
ggplot(df, aes(x = position)) +
  geom_histogram(bins = 50)
## With parameter binwidth it generate the right plot
ggplot(df, aes(x = position)) +
  geom_histogram(binwidth = 50)
```

**Comment by yutannihilation** [comment]
This might look a bit tricky, but this isn't a bug. If you look at the histogram carefully (or use `layer_data()`), you'll notice that there are fewer bins than 50. This typically means the breaks are calculated for 50 bins, but one of them is empty.
