### ISSUE TITLE
Feature request: Set theta limits in `coord_polar()` for partial plots

### ISSUE THREAD

**Issue by mattansb** [tidyverse/ggplot2#4772]
Currently, the control of the polar axis (theta) is controlled in two ways:
- The alignment of the axis is set by the `coord_polar(start = )` argument.
- The range of the values on the theta-axis is controlled by the underlying data / geoms / etc.

Currently, when plotting polar plots, the resulting plot gives the full "circle".
It would be nice if the "range" or "limit" (not which terminology fits here) of theta could be controlled to allow for partial plots.

For example to allow the following plots:

1. Half plot
![image](https://user-images.githubusercontent.com/35330040/159720398-0d790a33-1c63-426e-af87-97a297bcb09c.png)

2. Horizon plot
![image](https://user-images.githubusercontent.com/35330040/159720469-fbde32da-7953-4d55-a8aa-ef84aab9beb3.png)

Etc....

---

The user facing mechanism for this would probably be to specify the range -- along theta -- the underlying plot should be mapped onto, defaulting to `c(0, 2*pi)` for the full circle.

Under this mechanism, the above plots would have the following values:
1. `c(0, pi)`
2. `c(325, 35)*pi/180`

Thanks!

**Comment by alperyilmaz** [comment]
Sorry for posting on closed issue, didn't want to open a duplicate issue and just wanted to know if this feature is now available in ggplot or not. 
I checked github repo of ggplot2 and couldn't find changes related to this issue (# 4772). Also, [current manual](https://ggplot2.tidyverse.org/reference/coord_polar.html) (v3.3.5) for `coord_polar` does no  include feature requested by OP

**Comment by yutannihilation** [comment]
This issue is closed not because it got fixed but because this was a duplicate of https://github.com/tidyverse/ggplot2/issues/4462, so you can track https://github.com/tidyverse/ggplot2/issues/4462 for the updates.
