### ISSUE TITLE
"Error : unknown white reference" when using fill or col

### ISSUE THREAD

**Issue by SamuelAllain** [tidyverse/ggplot2#4778]
I cannot make a simple ggplot graph when using fill or col aesthetics. I use Windows 10 pro, R 4.0.3 and ggplot2 3.3.5. It returns "Error : unknown white reference" which is quite difficult to understanding. [Similar problem](https://github.com/johnbaums/hues/issues/6), unresolved

```{r}
library("ggplot2")
n <- 10
prov <- data.frame(p1 = runif(n), OR = runif(n), ecart = runif(n))

ggplot(prov, aes(x = p1, y = OR))
# no problem

ggplot(prov, aes(x = p1, y = OR, fill = ecart))
# Error : unknown white reference
```

Thanks a lot !

**Comment by SamuelAllain** [comment]
A new installation of both R 4.1.3 and ggplot2 did not solve the issue. On another computer (R 4.0.2) and same ggplot2 version, I can't reproduce the bug.

**Comment by SamuelAllain** [comment]
Thanks for the reply ! Farver is up to date (2.1.0). I tried to start on a brand new installation to no avail.  I'll try to investigate

**Comment by lenient7** [comment]
Did you find a solution to this issue? I found that this happens when dplyr (v. 1.0.8) is loaded. I am using R 4.1.3. As a workaround, I separated data wrangling and plotting. It is cumbersome but at least I can produce plots.

**Comment by SamuelAllain** [comment]
I haven't understood the issue. I made several re-installations (erasing all related repertories) and eventually the bug disappeared. I noticed that it only happened with RStudio (not with Rgui).

**Comment by lenient7** [comment]
Thanks for the reply. It is interesting to learn that it happened with RStudio only for you. In my case, this error happens with ess on emacs.

**Comment by lenient7** [comment]
I found that the culprit was scipen option. In my particular case, the 'Unknown white reference' error arises when scipen is equal to or less than -5. A ggplot prints without an error with options(scipen >= -4). When options(scipen <= -5) and if I only use shape, 'valid.charjust(just) : invalid horizontal justification' error arose. It seems that this has something to do with the axis scale.

**Comment by yutannihilation** [comment]
Thanks for the detail. So, this is the reprex:

``` r
library("ggplot2")

n <- 10
prov <- data.frame(p1 = runif(n), OR = runif(n), ecart = runif(n))
p <- ggplot(prov, aes(x = p1, y = OR, fill = ecart))

# works
withr::with_options(list(scipen = -4), invisible(ggplot_build(p)))

# error
withr::with_options(list(scipen = -5), invisible(ggplot_build(p)))
```


`rlang::last_error()` indicates it comes from 

```
> rlang::last_error()
<error/rlang_error>
Error in `geom_blank()` at ggplot2/R/plot-build.r:31:4:
! Problem while computing aesthetics.
ℹ Error occurred in the 1th layer.
Caused by error:
! Unknown white reference
---
Backtrace:
     1. withr::with_options(list(scipen = -5), invisible(ggplot_build(p)))
     4. ggplot2:::ggplot_build.ggplot(p)
          at ggplot2/R/plot-build.r:24:2
     5. ggplot2:::by_layer(...)
          at ggplot2/R/plot-build.r:50:2
    12. ggplot2 (local) f(l = layers[[i]], d = data[[i]])
          at ggplot2/R/plot-build.r:421:6
    13. l$compute_aesthetics(d, plot)
          at ggplot2/R/plot-build.r:50:2
    14. ggplot2 (local) compute_aesthetics(..., self = self)
          at ggplot2/R/ggproto.r:182:16
    15. ggplot2:::scales_add_defaults(...)
          at ggplot2/R/layer.r:268:4
    18. ggplot2:::find_scale(aes, datacols[[aes]], env)
          at ggplot2/R/scales-.r:140:4
    19. ggplot2 (local) scale_f()
          at ggplot2/R/scale-type.R:14:4
 2e+01. ggplot2::scale_fill_gradient(...)
          at ggplot2/R/scale-colour.r:103:4
    24. scales::seq_gradient_pal(low, high, space)
          at ggplot2/R/scale-gradient.r:86:2
    25. scales::gradient_n_pal(c(low, high), space = space)
    26. scales::colour_ramp(colours)
    27. farver::decode_colour(...)
    28. farver::as_white_ref(white)
    29. base::stop("Unknown white reference", call. = FALSE)
Run `rlang::last_trace()` to see the full context.
```

It seems the problem is `as.character(2)` is not `"2"` when the `scipen` option is -5 or less.

https://github.com/thomasp85/farver/blob/9c8ad57e74f59c891221da4c8f7e62034a89f3e8/R/aaa.R#L157
