### ISSUE TITLE
`geom_rect()`'s `alpha` behaves differently depending on if `data` has value

### ISSUE THREAD

**Issue by stragu** [tidyverse/ggplot2#4780]
---

Using the same code, with the only difference between the two being if there is a set dataset or not, the transparency of `geom_rect()`'s fill seems to be lost. Using an extremely low value for `alpha` shows that it is actually still possible to make the fill transparent, but the measure seems completely off and non-linear.

``` r
library(ggplot2)
# no dataset
ggplot() +
  geom_rect(aes(xmin = 2007, xmax = 2010,
                ymin = 0, ymax = Inf),
            alpha = 0.5)
```

![](https://i.imgur.com/YdWPPqo.png)

``` r
# with dataset
ggplot(txhousing) +
  geom_rect(aes(xmin = 2007, xmax = 2010,
                ymin = 0, ymax = Inf),
            alpha = 0.5)
```

![](https://i.imgur.com/slfq0aH.png)

``` r
# only an extremely low value will start to look transparent
ggplot(txhousing) +
  geom_rect(aes(xmin = 2007, xmax = 2010,
                ymin = 0, ymax = Inf),
            alpha = 0.002)
```

![](https://i.imgur.com/TtXlk0A.png)

<sup>Created on 2022-03-29 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

Using:

```
R version 4.1.3 (2022-03-10)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.6 LTS
RStudio 2022.02.1 Build 461
```

**Comment by thomasp85** [comment]
This is because a layer inherits the global data. In your case it means that it will draw a rect for each row in your data and the transparency will be lost due to overdrawing. Either be very mindful to set `data = NULL` in the layer to stop inheriting the global data, or, probably more appropriate, use `annotate("rect", ...)` to draw a layer without using mapping

**Comment by stragu** [comment]
Thank you Thomas for the explanation, it makes more sense now. Time to get familiar with `annotate()`.
