### ISSUE TITLE
editing ggplot2-generated graphics in Adobe Illustrater / Affinity Photo

### ISSUE THREAD

**Issue by hroetsc** [tidyverse/ggplot2#4781]
Dear Support Team,

I am frequently generating graphics using ggplot2 in R. These graphics are then being edited using either Adobe Illustrator or Affinity Photo.
When importing those figures, they show white lines through the middle of a bar, violin or dot, which seem to mark the boundaries of adjacent objects. Another problem is that text is often grouped in non-intuitive ways. It becomes basically impossible to edit the figures / export them in a way so that the original graphic is being maintained.
This problem is especially daunting when dealing with scatterplots or barplots with many elements. Do you know a way with which I can reduce the amount of complexity/layers when exporting a ggplot to a postscript?

---

When opening ggplot-generated postscripts in a graphics editor, the plots show a lot of layers that destroy the image.

```r
ggsave(filename = "plot.ps,
         plot = my_plot, device = cairo_ps,
         dpi = "retina", height = 3.5*5, width = 3.5*5, units = "cm")
```

**Comment by hadley** [comment]
There's nothing we can do about this, sorry.
