### ISSUE TITLE
ggplot2 - stat_density2d heatmap issue

### ISSUE THREAD

**Issue by Matheus14m** [tidyverse/ggplot2#4788]
Hey guys! I've been facing an issue to create a heatmap using ggplot2 library. I have to say that I'm not a very experienced person with R language. 

I'm trying to create a map like this one below:

![image](https://user-images.githubusercontent.com/94150055/161132971-db6d6190-8d99-4ea5-a5bd-0f258630103a.png)

My dataset has these columns. I'm trying to use the column named "Result_Value" for my levels values. But it isn't working. I don't even know where the actual levels values are coming from. Could you help me?

![image](https://user-images.githubusercontent.com/94150055/161133282-4356e7cb-bbea-4d8c-80ee-3e3fc42e4746.png)

![image](https://user-images.githubusercontent.com/94150055/161133374-caf22481-bfda-475c-b609-cb7117293479.png)

```
map <- ggmap(get_googlemap(center = c(lon = -99.1683, lat = 19.50335), zoom = 19, maptype = "satellite", color = "color")) +
stat_density2d(data = dataset, aes(x = lon, y = lat, fill = ..level..),
alpha = .4,
bins = 6, geom = "polygon") +
labs(fill = "Teste") +
scale_fill_viridis_c(option = "plasma") + #Cor
theme(axis.text.x = element_blank(), #Títulos
axis.text.y = element_blank(),
axis.ticks = element_blank(),
axis.title.x = element_blank(),
axis.title.y = element_blank())

ggplotly(map)
```

**Comment by hadley** [comment]
This sort of question is a better fit for <https://community.rstudio.com>. Do you mind asking it over there? (You might want to read <https://www.tidyverse.org/help/> first to maximise your chances of getting a good answer)
