### ISSUE TITLE
Feature requests: Composable mappings

### ISSUE THREAD

**Issue by teunbrand** [tidyverse/ggplot2#4789]
Hi ggplot2 team,

In brief: I think it would be neat if it was possible to do `aes(x = 1, y = 2) + aes(colour = class)`, and get the equivalent of `aes(x = 1, y = 2, colour = class)`. In effect, I'm suggesting that the `aes()` mappings might be composed, much like the layers of a plot.

Why might this be neat? I'm probably not the only one who writes out small novels in most `aes()` calls. Most of them are pretty repetitive among layers or plots, but not exactly repetitive enough to warrant assigning the mapping to a variable for reuse. 

Consider the example below, wherein we might want to recycle the `colour` mapping to other plots/layers as well. For instance, another dataset with different column names, which renders the `fill` part invalid, or another layer with similar but not duplicated mappings.

``` r
library(ggplot2)

ggplot(mtcars, aes(mpg, disp)) +
  geom_point(
    aes(fill   = factor(cyl),
        colour = after_scale(colorspace::darken(fill, 0.3))),
    shape = 21, size = 3
  )
```

![](https://i.imgur.com/Ek9WJUn.png)

What I'm suggesting is to write some mechanism wherein parts of mappings can be easily combined. For example:

``` r
`+.uneval` <- function(e1, e2) {
  if (!inherits(e2, "uneval")) {
    rlang::abort("Appropriate message here")
  }
  ans <- ggplot2:::defaults(e2, e1)
  class(ans) <- class(e1)
  ans
}
```

This then allows you to set the `colour` outside of the plot, combine it with the mapping of the layer, and reuse it elsewhere at a later point.

```
dark_outline <- aes(colour = after_scale(colorspace::darken(fill, 0.3)))

ggplot(mtcars, aes(mpg, disp)) +
  geom_point(
    aes(fill = factor(cyl)) + dark_outline,
    shape = 21, size = 3
  )
```

![](https://i.imgur.com/9deSk3Q.png)

<sup>Created on 2022-03-31 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

Thank you for your work and consideration of this FR!

**Comment by thomasp85** [comment]
Alternative api that behaves more like classic vectors:

```r
col_aes <- aes(col = gear)

ggplot(mtcars) + geom_point(aes(x = mpg, y = disp, col_aes))
```

**Comment by teunbrand** [comment]
That also seems like a nice way to combine them. Might also be able to do `c(aes(x = mpg), aes(y = disp)`. I'm not married to the `+`-operator.

**Comment by yutannihilation** [comment]
Ah, true. Sorry, I forgot the problem. I think there is some open issue related to this behaviour, but I couldn't find it.

**Comment by teunbrand** [comment]
I think I may have found it in #2675. I suppose if that issue can be solved, this feature request is redundant, so feel free to close this in favour of the other issue.

**Comment by yutannihilation** [comment]
Thanks, yes, that one. I hope so, but, considering I've failed to solve #2675, maybe we need some fresh approach. Let's keep this issue open.

**Comment by hadley** [comment]
Yeah, you only need to get past the first two arguments for it to work:

``` r
library(ggplot2)

col_aes <- aes(colour = gear)
aes(,,!!!col_aes)
#> Aesthetic mapping: 
#> * `colour` -> `gear`
```

<sup>Created on 2022-04-14 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

I'd rather support `!!!` fully than add some new feature, and I'm worried that adding more `+` methods will have unintended consequences due to the challenge of correctly implementing double-dispatch generics in S3.
