### ISSUE TITLE
suggested tweak to the error message in validate_mapping()

### ISSUE THREAD

**Issue by nicholasjhorton** [tidyverse/ggplot2#4792]
It's been *very* helpful to trap the use of pipe rather than `+`.
I'm not sure if it's possible to tell whether the base pipe operator is used instead of the magrittr version.

Perhaps it might be better to say:

`Did you use %>% or |> instead of +?`

``` r
suppressWarnings(library(tidyverse))
mtcars |>
  ggplot(aes(x = mpg)) |> geom_histogram(bins = 10)
#> Error in `validate_mapping()`:
#> ! `mapping` must be created by `aes()`
#> Did you use %>% instead of +?
```

<sup>Created on 2022-04-01 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

Thanks as always for your efforts.

**Comment by yutannihilation** [comment]
Thanks, sounds good to me. Would you like to contribute a pull request?

The pull request should fix these two places and the snapshots for testing.

https://github.com/tidyverse/ggplot2/blob/ae7fb41d33fd629cddbea484fc37b5f02dea3c41/R/layer.r#L156

https://github.com/tidyverse/ggplot2/blob/ae7fb41d33fd629cddbea484fc37b5f02dea3c41/R/facet-grid-.r#L164

**Comment by yutannihilation** [comment]
True. Thanks for catching!
