### ISSUE TITLE
ggplot is not showing until window is resized.

### ISSUE THREAD

**Issue by dBaliukynas** [tidyverse/ggplot2#4793]
Some ggplot2 plots are not displaying in RStudio. When RStudio is resized, plots are then being shown. Although, Base R plots are always displaying.

Video link: https://www.youtube.com/watch?v=a41CyLy7KeM

gplot2 version: 3.3.5.
R version: 4.1.3.
RStudio version: 2022.02.1 Build 461.
OS: Windows 11.

**Comment by yutannihilation** [comment]
This sounds a problem on RStudio's side (if there's any). Anyway, this sort of question is a better fit for [RStudio Community](https://community.rstudio.com). Could you ask there? Thanks.
