### ISSUE TITLE
element_textbox : how to change line weight and colour?

### ISSUE THREAD

**Issue by AKuepfer123** [tidyverse/ggplot2#4794]
@ [paleolimbot](https://github.com/paleolimbot) in relation to Issue https://github.com/tidyverse/ggplot2/issues/2344 

This is very helpful. Is there a way to control for line weight of the text box, as well as box fill/ line colour?

Thank.

---

Brief description of the problem

```r
# insert reprex here
```

**Comment by yutannihilation** [comment]
This sort of question is a better fit for [RStudio Community](https://community.rstudio.com). Please ask there with a minimal reproducible example. We use this issue tracker for bug reports and feature requests.
