### ISSUE TITLE
Unexported (until v1.0.0) rlang functions used

### ISSUE THREAD

**Issue by billybarc** [tidyverse/ggplot2#4797]
The dev version of `ggplot2` uses `on_load()`/`run_on_load()` from `rlang`, but these functions are not exported for `rlang` versions < 1.0.0. I think the `ggplot2` DESCRIPTION dependency needs to be upgraded to `rlang` >= 1.0.0.

I noticed this after getting the following error when trying to install the dev version of `ggplot2` while only having `rlang` version 0.4.10:

```
* installing *source* package 'ggplot2' ...
** using staged installation
** R
** data
*** moving datasets to lazyload DB
** inst
** byte-compile and prepare package for lazy loading
Error in on_load({ : could not find function "on_load"
Error: unable to load R code in package 'ggplot2'
Execution halted
ERROR: lazy loading failed for package 'ggplot2'
Warning in install.packages :
  installation of package 'ggplot2' had non-zero exit status
```

Not sure what the reprex would be here other than installing specific versions of these packages with `devtools::install_version()`; can provide if needed.

Crosspost from [stackoverflow](https://stackoverflow.com/questions/71799966/should-ggplot2-dev-version-depend-on-rlang-1-0-0-due-to-exported-on-load-fun?noredirect=1#comment126884142_71799966).

**Comment by hadley** [comment]
Do you want to do a PR to fix this?
