### ISSUE TITLE
Why not ggplot2:::fortify.SpatialLines

### ISSUE THREAD

**Issue by tingtingzhan** [tidyverse/ggplot2#4798]
I see that you have `ggplot2:::fortify.SpatialLinesDataFrame`.

I'm wondering why don't you just name it `fortify.SpatialLines` without changing any actual code?    I simply defined (illegally)

`fortify.SpatialLines <- ggplot2:::fortify.SpatialLinesDataFrame`

and never experienced any error in practice

**Comment by hadley** [comment]
It's probably just an accidental omission, but since few people seem to suffer for it, and we now generally recommend `geom_sf()`, we're unlikely to fix it.
