### ISSUE TITLE
Error in match.arg(antialias, aa.win) :    'arg' should be one of “default”, “none”, “cleartype”, “gray”

### ISSUE THREAD

**Issue by drag05** [tidyverse/ggplot2#4804]
Lately I get this error when running `ggplot` in code chunks in R Studio. However, kneading the document outputs the plot correctly

```r
if dt is a data.frame/data.table with 2 columns  named "Mass" and "Area"
# setting the device gives this error
ggplot(dt, aes(x = Mass, y = Area))

Error in match.arg(antialias, aa.win) : 
  'arg' should be one of “default”, “none”, “cleartype”, “gray”
```
The error seems to be propagating to other packages which depend on `ggplot2` - the reason for posting the issue here. 

For example running `ggVennDiagram` from `ggVennDiagram` package:

```r
if vList is a list of categories

ggVennDiagram(vList, label_alpha = 0L, label = 'count')

Error in match.arg(antialias, aa.win) : 
  'arg' should be one of “default”, “none”, “cleartype”, “gray”
```
Again, the error does not impact negatively document kneading. Thank you!

**Comment by yutannihilation** [comment]
It seems the error comes from `grDevices::png()`.

https://github.com/wch/r-source/blob/79298c499218846d14500255efd622b5021c10ec/src/library/grDevices/R/windows/png.R#L63

But, I cannot reproduce your issue, so I feel this isn't a problem of ggplot2. Could you provide a reproducible example? It might be better to ask on [RStudio Community](https://community.rstudio.com).

``` r
library(ggplot2)

dt <- data.frame(
  Mass = 1:2,
  Area = 3:4
)

ggplot(dt, aes(x = Mass, y = Area))
```

![](https://i.imgur.com/IPyjLcc.png)

<sup>Created on 2022-04-23 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by drag05** [comment]
@yutannihilation  Thank you for the hint! Checked R Studio graphics and found antialiasing set on "subpixel". Once I turned it back on "default" the error went away.

**Comment by yutannihilation** [comment]
Oh, great!

JFYI, I quickly checked the code of RStudio, and it seems it's already fixed (I might be wrong) two years ago.

https://github.com/rstudio/rstudio/blob/edd144e6c64f765f62716e57a31808597e92ab7e/src/cpp/r/session/graphics/RGraphicsUtils.cpp#L206-L208

So, updating your RStudio might fix the problem. Actually, I don't see the problem on my RStudio if I switch the setting to "subpixel".

**Comment by drag05** [comment]
@yutannihilation : 
With backend = "default" and antialiasing = "default" on R Studio global settings and dev = 'cairo_pdf" on opts_chunk$set() things seem to be back to normal. Thank you!
