### ISSUE TITLE
update code of conduct links

### ISSUE THREAD

**Issue by nickreich** [tidyverse/ggplot2#4807]
The "code of conduct" file linked to in the [Governance](https://github.com/tidyverse/ggplot2/blob/main/GOVERNANCE.md) and [Contributing](https://github.com/tidyverse/ggplot2/blob/main/CONTRIBUTING.md) files is not present in the main repo. The links should be fixed. This appears to be related to https://github.com/tidyverse/ggplot2/pull/3288.

**Comment by yutannihilation** [comment]
Thanks for catching. Would you mind creating a pull request to fix this?
