### ISSUE TITLE
ggplot graphs inconsistency display in shiny application

### ISSUE THREAD

**Issue by meeuuu** [tidyverse/ggplot2#4808]
have an R shiny application deployed in web..It somestimes displays the graphs in the panel of shiny app but when i run it again using the same setting eveything it is not able to display..There is no bug in the code because once it is able to display..I have also used different browsers but nothing worked..Any suggestions are welcome..I used ggplot2 for displaying graphs..But the same code worked in different linux server and able to produce the graphs persistenly..Any suggestions would be helpful..Thanks

**Comment by thomasp85** [comment]
My guess is that this question is better answered by shiny developers. If the ggplot2 code doesn't provide any errors and seem to work fine it is unlikely that it is an issue in ggplot2

**Comment by meeuuu** [comment]
Hi @thomasp85 thanks a lot for ur suggestion..is there any forum that u know so i could look for it..I thought here it will be a right place too

**Comment by meeuuu** [comment]
Basically the reason i posted here is i doesn't know is there any incompatibility between shiny version and ggplot ..

**Comment by thomasp85** [comment]
I would ask in https://community.rstudio.com
