### ISSUE TITLE
geom_boxplot: lower, upper and middle aesthetic names

### ISSUE THREAD

**Issue by davidhodge931** [tidyverse/ggplot2#4810]
I was wondering if the lower, upper and middle aesthetic names in geom_boxplot could be changed to ylower, yupper and ymiddle?

I think this is more consistent with how other aesthetics are named, and would help users as would be more intuitive and specific about what the aesthetic actually is.

<img width="195" alt="image" src="https://user-images.githubusercontent.com/55065152/164837897-fd5baf2e-2ddd-493f-b0d5-dfa52151b038.png">

**Comment by thomasp85** [comment]
this is somewhat of a relic from when geoms where uni-directional and `lower` implicitly referred to the y axis due to the orientation of the geometri. Changing this now will unfortunately break too much code to be worthwhile
