### ISSUE TITLE
Bug with position = "fill" and setting scale limits

### ISSUE THREAD

**Issue by davidhodge931** [tidyverse/ggplot2#4811]
I think this is a bug...

```
library(tidyverse)

p <- storms %>% 
  group_by(year, status) %>% 
  summarise(wind = mean(wind, na.rm = T)) %>% 
  ungroup()  %>% 
  ggplot() +
  geom_col(aes(x = year, y = wind, col = status, fill = status),  position = "fill") 

p
```
<img width="460" alt="image" src="https://user-images.githubusercontent.com/55065152/164887221-1794bdfe-8446-4911-a168-676a3093a8d4.png">

But then when I add limits in, it no longer works..
```
p +
  scale_y_continuous(limits = c(0, 1))
```

<img width="470" alt="image" src="https://user-images.githubusercontent.com/55065152/164887275-67b4e627-c607-4e75-b9a4-c9d21aefdbd9.png">

**Comment by yutannihilation** [comment]
Hi, this isn't a bug. I think you can use `coord_cartesian()` instead. See [the FAQ](https://ggplot2.tidyverse.org/articles/faq-bars.html#why-do-the-bars-on-my-plot-disappear-when-i-specify-an-axis-range-with-ylim-how-can-i-get-the-bars-to-show-up-within-a-given-axis-range) for more details. Thanks!

``` r
library(tidyverse)

p <- storms %>% 
  group_by(year, status) %>% 
  summarise(wind = mean(wind, na.rm = T)) %>% 
  ungroup()  %>% 
  ggplot() +
  geom_col(aes(x = year, y = wind, col = status, fill = status),  position = "fill") 
#> `summarise()` has grouped output by 'year'. You can override using the
#> `.groups` argument.

p +
  scale_y_continuous(limits = c(0, 1))
#> Warning: Removed 138 rows containing missing values (position_stack).
```

![](https://i.imgur.com/eQKu2Gu.png)

``` r
p +
  coord_cartesian(ylim = c(0, 1))
```

![](https://i.imgur.com/7WZgCvJ.png)

<sup>Created on 2022-04-23 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by davidhodge931** [comment]
Thanks :)
