### ISSUE TITLE
[question] Adding rasterGrobs to specific facets systematically

### ISSUE THREAD

**Issue by exaexa** [tidyverse/ggplot2#4813]
Hi everyone,

I'm opening this mostly as a "question issue", hoping to get some directions that would help me to solve another issue efficiently (see https://github.com/exaexa/scattermore/issues/8).

In short, we've got a package called `scattermore` that helps in certain very specific plotting workflows (mostly scatterplots with millions of points combined with Shiny) by being able to plot simple stuff very quickly. Internally, it processes points to a raster bitmap using some simple C code, and then just pastes the raster bitmap (created by `as.raster`) to the plotting area.

We have added some adaptors that allow using the functionality also from ggplot (instead of the base R), which has gained some attention and usage (the method is now used e.g. in [seurat](https://github.com/satijalab/seurat/)), despite the current implementation ss a bit of a quick hack (seen at https://github.com/exaexa/scattermore/blob/master/R/scattermore.R#L160 and briefed at https://github.com/exaexa/scattermore#quick-how-to).

Naturally, I'd love this to cooperate better with the rest of ggplot. One of the open issues is how to guess a "correct" raster or point size (in raster pixels) for plotting of the bitmap; but that can be "fixed" on the user side using a bit of guesswork. Recently, we found another issue (https://github.com/exaexa/scattermore/issues/8) with plotting data that do not go through the ggplot "data system" into the facets. The main question here is whether there would be a way to systematically use the faceting machinery of a given plot to split "external" data used by `geom_scattermost()` into facets, and add individual rasters into the right facets. In particular:

- is it possible to somehow access the computed facet dimensions during the plotting process, or is there functionality to compute per-facet minima and maxima for "fake data" as done here? https://github.com/exaexa/scattermore/blob/master/R/scattermore.R#L257-L261
- how do I put a `rasterGrob` to a specific facet? i.e., if I'm able to extract data for a given facet and I know what facet it is, how do I assign my bitmap to that asset in a code like this? https://github.com/exaexa/scattermore/blob/master/R/scattermore.R#L296

Many thanks for any help/opinions/hints :]
-mk

(cc: @garciamikep @teri934)

**Comment by thomasp85** [comment]
There is a lot to unpack here and I'll probably miss a lot. Basically, it is not possible to do what you do in a general way. You should pass in data as data to allow the ggplot2 machinery to train scales on it, split it into facets and groups and whatnot...

As for the second question, when using `draw_panel()` the rasterGrob is automatically placed in the assigned facet so that comes for free

**Comment by exaexa** [comment]
I managed to circumvent the issue by grouping everything manually. Will update here if I find a more ggplot-ish way. Thanks!
