### ISSUE TITLE
Legend mis-alignement for parsing greek letters using scale::parse_format

### ISSUE THREAD

**Issue by Sibojang9** [tidyverse/ggplot2#4814]
In the first figure, the right-hand side legend is correctly aligned with the regular ggplot code. However, the greek characters were mis-aligned when `labels=parse_format()` is used to parse "microgram" in the second figure, as indicated by the gap (white space) next to the legend "1 ug". The erratic alignment behavior sounds like a bug to me.

 ``` r
library(ggplot2)
library(scales)
data <- data.frame(x=c(1,2),y=c(1,2),c= c("10000~mu*g","1~mu*g"))
ggplot(data,aes(x=x,y=y,color=c)) + geom_point()
```

![](https://i.imgur.com/cWnuk6s.png)

``` r
ggplot(data,aes(x=x,y=y,color=c)) + geom_point()+ scale_colour_discrete(labels=parse_format()) 
```

![](https://i.imgur.com/n0w1iGh.png)

<sup>Created on 2022-04-25 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by thomasp85** [comment]
While poorly documented, the default justification for expressions in labels has always been right-aligned. This can of course be overwritten in the guide. I can't comment on the reason for this decision as it predates my time with ggplot2 (meaning it is ancient 🙂). This also means that it is probably too late to change as others may likely rely on the default behaviour...

**Comment by Sibojang9** [comment]
This is a typical sunk cost fallacy.

**Comment by thomasp85** [comment]
Well, it's not really a bug so there is nothing to fix later. It was a poorly documented behaviour that is now properly documented.

**Comment by Sibojang9** [comment]
Do you have the link to the docu?

**Comment by thomasp85** [comment]
https://github.com/tidyverse/ggplot2/blob/eb0010e0ede79690a70e4487e07037c307ffd5bc/R/guide-legend.r#L34-L36

**Comment by Sibojang9** [comment]
Thank you so much for sharing.
