### ISSUE TITLE
geom_hex() doesn't work

### ISSUE THREAD

**Issue by dax44** [tidyverse/ggplot2#4819]
After updating to r 4.2.0 geom_hex() doesn't work for me :(

```r
d <- ggplot(diamonds, aes(carat, price))
d + geom_hex()
```

```
Warning message:
Computation failed in `stat_binhex()`:
```

and in plots I have this
![image](https://user-images.githubusercontent.com/8738353/165468802-140836f3-423e-402d-831e-ac2ab4702f07.png)

**Comment by yutannihilation** [comment]
You need to install hexbin package. Sorry that the error message is cryptic. See https://github.com/tidyverse/ggplot2/issues/4736.
