### ISSUE TITLE
Feature Request: Monotonically Ordered Positions For Points

### ISSUE THREAD

**Issue by DarioS** [tidyverse/ggplot2#4829]
It would be nice to be able to specify one keyword and get ordered dots, e.g. `geom_point(position = "ordered")`. I know this can be achieved with hacks like ordering the sample names' factor levels on the x-axis by increasing y-axis values and using facetting, but this proposed option would greatly simplify the goal. Example figure from _Science_ journal.

![image](https://user-images.githubusercontent.com/631218/166630774-227cf721-9952-49a3-b40c-e8f986d26c29.png)

It could become as simple as:

```r
mtcars$cyl <- factor(mtcars$cyl)
ggplot(mtcars, aes(cyl, mpg)) + geom_point(position = "ordered")
```

and be a cleaner alternative to jittering, which doesn't have a 100% guarantee that two points will not overlap after jittering.

**Comment by teunbrand** [comment]
A rough draft of a position adjustment like the one proposed above can be found here: https://stackoverflow.com/a/65185390/11374827

**Comment by DarioS** [comment]
Thanks, Teun. I didn't see that question before. But, I still hope there can be a one-liner incoroporated into ggplot2 itself.

**Comment by thomasp85** [comment]
There will not be a one-liner in ggplot2 for this niche case. A new position adjustment such as this is better provided by an extension package to give it the development bandwidth needed
