### ISSUE TITLE
Add position_beeswarm

### ISSUE THREAD

**Issue by mkuhn** [tidyverse/ggplot2#483]
Using jitter is nice for many points. Sometimes I have datasets with differing number of points, and jitter looks strange when there are only few points. I would prefer them to be centered, like in the [beeswarm](http://cran.r-project.org/web/packages/beeswarm/index.html) plot. 

There exists a solution to use the [output of beeswarm for ggplot](http://denishaine.wordpress.com/2011/09/16/beeswarm-plot-with-ggplot2/), but this breaks down when I want to use facet_grid. 

Thus, my feature request is to add a position_beeswarm option or something similar that works well for few and lots of points.

**Comment by smsaladi** [comment]
Many months later, but check out: https://github.com/eclarke/ggbeeswarm
