### ISSUE TITLE
Add support for avif device format output to ggsave

### ISSUE THREAD

**Issue by brianmsm** [tidyverse/ggplot2#4833]
Since the release of AVIF, it has been shown that it can maintain good image quality and reduce its weight considerably. 

According to this (https://www.finally.agency/blog/what-is-avif-image-format), AVIF has the following features:

- High dynamic range
- 8, 10, 12 bit colour depth
- Lossless compression
- Lossy compression
- Monochrome (alpha/depth) or multi components
- Any colour space including: wide color gamut, ISO/IEC CICP and ICC profiles
- 4:2:0, 4:2:2, 4:4:4 chroma subsampling
- Film grain

**Comment by thomasp85** [comment]
using avif from R would require support from a graphics device. This is not the realm of ggplot2 but for a dedicated package. Once such a package exist you can pass the relevant function to open the device into `ggsave()`
