### ISSUE TITLE
Feature request: Support variable strip height

### ISSUE THREAD

**Issue by netique** [tidyverse/ggplot2#4839]
I use `facet_wrap` with `ncol = 1` to present many barplots of likert-type data from a survey. The survey topic usually embraces several items that are too wide to be used as simple axis labels. This approach works well generally and in the case of item labels being too wide even for a facet label, I wrap them with `stringr::str_wrap()` or by using `strip.text = ggtext::element_textbox_simple()` in the `theme()` call. However, one single facet label spanning two lines makes the rest of the facet labels taller, resulting in the waste of space. AFAIK, this was not always the case in ggplot2 (I've seen plots from `{likert}` that accomplished that exactly, but the package seems broken).

Maybe it is more suitable for some ggplot2 extension, but my thoughts are that even ggplot2 itself could provide some argument enabling this behaviour. It makes sense to me only for single-column faceting, but it can be generally done for any layout.

The implementation seems straightforward as only `assemble_strips` requires the edits, starting with: https://github.com/tidyverse/ggplot2/blob/21df8dc88e9b736a136bc39362defe2943008767/R/labeller.r#L570

What do you think about it? Are you familiar with any existing solution to this problem?

Here is some reprex for illustration:

``` r
library(ggplot2)

data.frame(x = c("a", "b")) |>
  ggplot() +
  facet_wrap(~ x, ncol = 1)
```

![](https://i.imgur.com/tBigtCq.png)

``` r

data.frame(x = c("a", "a\nb")) |>
  ggplot() +
  facet_wrap(~ x, ncol = 1)
```

![](https://i.imgur.com/vSSkhIb.png)

<sup>Created on 2022-05-12 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by hadley** [comment]
Thanks for filing this issue! Unfortunately, I think the benefit is unlikely to justify the amount of effort required to implement it — the facet drawing code is already one of the most complicated pieces of ggplot2, and intersects with many existing options. Even though I'm closing this issue, I really appreciate the feedback, and hope you'll continue to contribute in the future 😄
