### ISSUE TITLE
Incorrect plot of geom_bar() for factor variables when using ..prop.. (+ workaround)

### ISSUE THREAD

**Issue by DISOhda** [tidyverse/ggplot2#4842]
When I was trying to produce a grouped barplot using `geom_bar()` with proportions on the Y axis (`aes(y = ..prop.., fill = ...)`), I got a totally weird output (see example). With or without faceting, (the latter using `position = "dodge"`), every factor level of each group has a bar of 100%.

As a workaround, I converted the factor to numerical data and used the factor levels as limits in `scale_x_discrete(limits = levels(...))`.

```r
#### EXAMPLE DATA ####

library(tidyverse)
set.seed(1)

# table
dat <- tibble(Gender = sample(c("female", "male"), 1000, TRUE), 
              Musicality = ordered(sample(c("none", "low", "moderate", "much"), 
                                          1000, TRUE, c(0.3, 0.1, 0.4, 0.2)),
                                   c("none", "low", "moderate", "much")))

#### INCORRECT BEHAVIOUR FOR FACTOR DATA (+ WORKAROUND) ####

# plot overall distribution (as proportions) of Musicality, using 'dodge'
ggplot(dat, aes(x = Musicality, fill = Gender)) + 
  geom_bar(aes(y = ..prop..), position = "dodge")
```
![geom_bar bug 1](https://user-images.githubusercontent.com/85945308/168257113-f6dfefa5-9450-4734-b346-20b7964a76fd.png)
```r
# Obviously a bug! Expected to look like this (but with percentages on the Y axis):
ggplot(dat, aes(x = Musicality, fill = Gender)) + 
  geom_bar(position = "dodge")
```
![geom_bar bug 1 expected like](https://user-images.githubusercontent.com/85945308/168257106-4a93dcc9-08cd-4d9b-88fb-2eb39812f2da.png)
```r
# Workaround:
ggplot(dat, aes(x = as.numeric(Musicality), fill = Gender)) + 
  geom_bar(aes(y = ..prop..), position = "dodge") + 
  scale_x_discrete(limits = levels(dat$Musicality))
```
![geom_bar bug 1 workaround](https://user-images.githubusercontent.com/85945308/168257111-699739b3-fdfa-4b75-b927-4cea844ac21a.png)
```r
# plot gender-wise distribution (proportions) of Musicality with faceting
ggplot(dat, aes(x = Musicality, fill = Gender)) + 
  geom_bar(aes(y = ..prop..)) +
  facet_grid(~Gender)
```
![geom_bar bug 2](https://user-images.githubusercontent.com/85945308/168257120-2f7d21a9-a5a5-46ef-91c4-76ccf4dc8944.png)
```r
# Obviously a similar bug! Workaround:
ggplot(dat, aes(x = as.numeric(Musicality), fill = Gender)) + 
  geom_bar(aes(y = ..prop..)) +
  facet_grid(~Gender) + 
  scale_x_discrete(limits = levels(dat$Musicality))
```
![geom_bar bug 2 workaround](https://user-images.githubusercontent.com/85945308/168257115-04ed4528-973f-45b6-92e2-7f9562b32554.png)

**Comment by yutannihilation** [comment]
This is an expected behavior. `prop` (or any other computed variables) are calculated per group, which is determined by the combination of all the discrete variables in case you don't supply `group` aesthetic explicitly. So, the correct way to achieve what you want is to specify `group`.

``` r
library(tidyverse)
set.seed(1)

# table
dat <- tibble(Gender = sample(c("female", "male"), 1000, TRUE), 
              Musicality = ordered(sample(c("none", "low", "moderate", "much"), 
                                          1000, TRUE, c(0.3, 0.1, 0.4, 0.2)),
                                   c("none", "low", "moderate", "much")))

ggplot(dat, aes(x = Musicality, fill = Gender, group = Gender)) + 
  geom_bar(aes(y = stat(prop)), position = "dodge")
```

![](https://i.imgur.com/g9YA0Nl.png)

<sup>Created on 2022-05-14 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
