### ISSUE TITLE
Feature request: silence `ggplot2:::plot_dim`

### ISSUE THREAD

**Issue by bersbersbers** [tidyverse/ggplot2#4847]
I'd like to silence `ggsave` without suppressing *all* messages - just the standard "Saving 7 x 7 in image". I know I can pass dimensions myself, but I find the mechanism inside `plot_dim` actually useful. However, I'd not like to duplicate that piece of code (and since it's private, I cannot reliable call it, either).

```r
ggplot2::ggsave("tmp.pdf")
```

> Saving 7 x 7 in image

Related: https://stackoverflow.com/questions/39153723/how-can-i-call-ggsave-without-producing-any-output-like-saving-7-x-7-in-image

**Comment by hadley** [comment]
Thanks for filing this issue! Unfortunately, we don't plan to implement it — you already have two ways to suppress the messages and I don't think adding a 3rd is likely to help many people. Even though I'm closing this issue, I really appreciate the feedback, and hope you'll continue to contribute in the future 😄
