### ISSUE TITLE
Helper stat for `geom_area()`

### ISSUE THREAD

**Issue by hadley** [tidyverse/ggplot2#4850]
I realised it would be pretty easy for us to automatically handle non-aligned data. Sketch of approach below

``` r
library(ggplot2)

df <- tibble::tribble(
  ~g, ~x, ~y,
  "a", 1, 2,
  "a", 3, 5,
  "a", 5, 1,
  "b", 2, 3,
  "b", 4, 6,
  "b", 6, 7
)
ggplot(df, aes(x, y, colour = g)) + geom_line()
```

![](https://i.imgur.com/vWEA4py.png)

``` r
ggplot(df, aes(x, y, fill = g)) + geom_area()
```

![](https://i.imgur.com/5fyFn0r.png)

``` r

all_x <- sort(unique(df$x))

completed <- df |> 
  split(df$g) |> 
  lapply(function(grp) {
    y_fun <- approxfun(grp$x, grp$y, yleft = 0, yright = 0)
    
    data.frame(
      g = grp$g[[1]],
      x = all_x,
      y = y_fun(all_x))
  }) |> 
  dplyr::bind_rows()

ggplot(completed, aes(x, y, fill = g)) + geom_area()
```

![](https://i.imgur.com/CHOom2N.png)

<sup>Created on 2022-05-17 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by yutannihilation** [comment]
I too feel `geom_area()` really needs something like this.

A related (but a bit different) issue was https://github.com/tidyverse/ggplot2/issues/2883, and here's my attempt at that time: https://gist.github.com/yutannihilation/2d3851adc874a02f42914f1655329c71 (it seems this won't work now)

**Comment by teunbrand** [comment]
Also spotted in the wild today: https://stackoverflow.com/q/72663399

**Comment by thomasp85** [comment]
yeah, I feel we have discussed this before and I'm in favour too... I have a hard time believing this has any drawbacks at all
