### ISSUE TITLE
 geom_jitter()  added extra points in my fig

### ISSUE THREAD

**Issue by dhrhzz** [tidyverse/ggplot2#4855]
or geom_point() added extra point, i don't known，When jitter, it appeared.
use geom_point(positon='jitter') or
geom_point(position=  position = position_jitter(width = 0.3, height = 0))
you can also see that extra point.

**Comment by yutannihilation** [comment]
Hi, I think your data contains many points in the same location. `geom_jitter()` is useful for such a case. Anyway, this sort of question is a better fit for [RStudio Community](https://community.rstudio.com). Please ask there with a minimal reproducible example. We use this issue tracker for bug reports and feature requests. Thanks!

(If you are sure this is a problem that ggplot2 have to fix, feel free to file a new issue with the reproducible example.)
