### ISSUE TITLE
Lines with alpha values disappear in legend in some situations.

### ISSUE THREAD

**Issue by jfunction** [tidyverse/ggplot2#4861]
---

When I make a lineplot with colour groupings and some alpha value I noticed the legend lines would disappear when plotted in RStudio, though when I make a reprex they still show up:

``` r
library(ggplot2)
    ggplot(data.frame(x=c(1,2,1,2), y=c(3,2,1,2), z=c("A","A","B","B"))) +
        aes(x=x, y=y, colour=z) +
        geom_line(size=2L, alpha=0.6)
```

![](https://i.imgur.com/jM3Xdmv.png)

<sup>Created on 2022-05-29 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

This is what I see inside RStudio however:

![](https://i.imgur.com/8snXzSU.png)

So I investigated how to add the lines again using `guides()`. I found that setting `alpha=1` brings the lines back for me, and so does `alpha=0.999`, but `alpha=0.9` hides them again. I then went down a rabbit hole of doing a "does work/doesn't work" sort of binary search on each digit to learn that the threshold seems to be `0.99803921568627457230` which I noted has an interesting floating point representation. Curiously, `0.9980392156862745723` (without the 0 at the end) doesn't show lines in the legend, nor will anything lower, but anything higher will show them. This is again *not* reflected in the image in the following reprex:

``` r
library(ggplot2) 
    ggplot(data.frame(x=c(1,2,1,2), y=c(3,2,1,2), z=c("A","A","B","B"))) +
        aes(x=x, y=y, colour=z) +
        geom_line(size=2L, alpha=0.6) +
        guides(colour = guide_legend(override.aes = list(alpha = 0.9980392156862745723)))
```

![](https://i.imgur.com/WJScVI2.png)

<sup>Created on 2022-05-29 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

Versus anything higher (including for some reason concatenating a 0) which *is* reflected in the following reprex:

``` r
library(ggplot2) 
    ggplot(data.frame(x=c(1,2,1,2), y=c(3,2,1,2), z=c("A","A","B","B"))) +
        aes(x=x, y=y, colour=z) +
        geom_line(size=2L, alpha=0.6) +
        guides(colour = guide_legend(override.aes = list(alpha = 0.99803921568627457230)))
```

![](https://i.imgur.com/XVRMNKc.png)

<sup>Created on 2022-05-29 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

I'm not really sure what to make of this. I suspect someone with a deeper understanding of R's internal number representation could figure it out. Let me know if you want more information from me.

**Comment by yutannihilation** [comment]
I cannot reproduce this on my RStudio (I'm on Windows). I guess this is the same issue of RStudio's graphics device as https://github.com/rstudio/rstudio/issues/2196, which happens on Windows with R < 4.2. So, if you are on Windows, you can either upgrade the R version or install ragg package and use "AGG" option which you can find on `Global options > General > Graphics > Backend`. Otherwise, this should be a new problem, so you should file an issue on RStudio's repo.

![image](https://user-images.githubusercontent.com/1978793/170871080-e2bd3be8-470d-4c9c-a63e-e358e15744b2.png)
