### ISSUE TITLE
Expand documentation for coord_flip

### ISSUE THREAD

**Issue by wmacnair** [tidyverse/ggplot2#4863]
Hello

First of all, I have used `ggplot` pretty much every working day for I don't know how many years now, so I should use this opportunity to say thank you for the essential package / nice community / responsive authors / all the things that make it great 🤗 

In general I find the documentation of `ggplot` functions good, with good conceptual background and pretty thorough examples. However whenever I try to understand the tricksy bits of `coord_flip`, I find myself consistently frustrated by the pretty thin coverage. Questions I have wished were answered:

- How does `coord_flip` interact with `facet`s? i.e. does the `facet` x match to the flipped or unflipped x `aes`?
- How does `coord_flip` interact with `scale`s? i.e. does the `scale` x match to the flipped or unflipped x `aes`?
- How does `coord_flip` interact with axis-related params in `theme`?
- Do the `xlim` and `ylim` parameters in `coord_flip` refer to the axes before or after the flipping?
- I'm sure there are others...

It would be great to have an expanded **Details** section for the `coord_flip` documentation, going over the concepts here. Maybe even a little diagram! It could also be an opportunity to describe some cases where `coord_flip` doesn't work so well, or common pitfalls.

Thanks again!
Will

**Comment by thomasp85** [comment]
Thanks - you are right that there are a lot of questions around `coord_flip()` that could be answered better. One of the reasons for adding support for bidirectional gems was exactly that `coord_flip()` introduced these ambiguities and we generally advise to simply use the reverse mapping in the geom rather than flipping the coordinate system.

However since we still provide `coord_flip()` and will continue to do so for a long time we should improve the docs

**Comment by teunbrand** [comment]
Since we've decided to supersede `coord_flip()` in favour of bidirectional geoms in #5123, do you still think it is worth polishing the docs?

**Comment by slowkow** [comment]
@teunbrand  In ggplot2 extensions, how can a Geom "know" if the coords have been flipped with `coord_flip()`?

After studying the ggplot2 code, I am not seeing any way to figure this out. The reason I ask is because this is causing issues for users of ggrepel.

**Comment by slowkow** [comment]
Nevermind! Sorry for the bother. As I continued to search through old ggplot2 issues, I found one that helps me, thanks to the discussion in the related commit:

- https://github.com/tidyverse/ggplot2/pull/4431/commits/2a46b3a6e3b35384f51d880ae4b4bf25e3214685

```r
flipped <- inherits(coord, "CoordFlip")
```
