### ISSUE TITLE
Manual scales: not dropping and need exact order to merge with other aesthetics

### ISSUE THREAD

**Issue by llrs** [tidyverse/ggplot2#4864]
Setting a manual color scale via `scale_color_manual` doesn't drop unused factors (this could be a feature and not a bug but it is not documented on the help page), and unless they are in the same exact order as other aesthetics the legends are not merged.

I wish there were some kind of check and reorder the scales to see if they match. I'm not sure how easy is to do this, but I think it would make ggplot2 slightly more user friendly.

I didn't find this mentioned previously on any other issue but I might have missed them. 

``` r
library("ggplot2")
packageVersion("ggplot2")
#> [1] '3.3.6'
p <- ggplot(iris) +
  geom_point(aes(Petal.Length, Petal.Width, col = Species, shape = Species))
```

# Manual scale

``` r
p + scale_color_manual(values = c("setosa" = "red", "versicolor" = "green", "virginica" = "blue"))
```

![](https://i.imgur.com/YXh1WFF.png)

# Manual scale with extra values

``` r
p + scale_color_manual(values = c("setosa" = "red", "versicolor" = "green", "virginica" = "blue", "Other" = "black"))
```

![](https://i.imgur.com/qeziiKs.png)

drop doesn’t seem to work with manual values

``` r
p + scale_color_manual(values = c("setosa" = "red", "versicolor" = "green", "virginica" = "blue", "Other" = "black"),
                     drop = TRUE)
```

![](https://i.imgur.com/7LREmEn.png)

# Manual scale with different order

``` r
p + scale_color_manual(values = c("versicolor" = "green", "virginica" = "blue", "setosa" = "red"))
```

![](https://i.imgur.com/yyUXKzg.png)

The legends are not merged into a single one.

<sup>Created on 2022-06-03 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by yutannihilation** [comment]
I forgot which change solved this, but the current dev version's behavior looks fine to me.

``` r
library("ggplot2")
packageVersion("ggplot2")
#> [1] '3.3.6.9000'

p <- ggplot(iris) +
  geom_point(aes(Petal.Length, Petal.Width, col = Species, shape = Species))

p + scale_color_manual(values = c("setosa" = "red", "versicolor" = "green", "virginica" = "blue"))
```

![](https://i.imgur.com/wyg5QRV.png)

``` r
p + scale_color_manual(values = c("setosa" = "red", "versicolor" = "green", "virginica" = "blue", "Other" = "black"))
```

![](https://i.imgur.com/EqIF7xg.png)

``` r
p + scale_color_manual(values = c("setosa" = "red", "versicolor" = "green", "virginica" = "blue", "Other" = "black"), drop = TRUE)
```

![](https://i.imgur.com/IbpF0jH.png)

``` r
p + scale_color_manual(values = c("versicolor" = "green", "virginica" = "blue", "setosa" = "red"))
```

![](https://i.imgur.com/mRGcjUQ.png)

<sup>Created on 2022-06-04 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by yutannihilation** [comment]
https://github.com/tidyverse/ggplot2/pull/4619
