### ISSUE TITLE
Error in grid.Call.graphics(C_upviewport, as.integer(n))

### ISSUE THREAD

**Issue by paupaiz** [tidyverse/ggplot2#4867]
---

Thanks for supporting ggplot2! 
I am plotting 20K+ plots using a for loop everything worked fine until I got to iteration 11892. I tried again and got the same error at another iteration so can confirm it happens sporadically. Due to this nature I unfortunately cannot provide a reprex but here is the message:
`Error in grid.Call.graphics(C_upviewport, as.integer(n)) : 
  cannot pop the top-level viewport ('grid' and 'graphics' output mixed?)
Called from: grid.Call.graphics(C_upviewport, as.integer(n))`

**Comment by thomasp85** [comment]
This is a well known issue with grid that has been hard to fix due to the stochastic nature of it. Unfortunately there is nothing we can do on the ggplot2 side to fix it.
