### ISSUE TITLE
function to save the data frame used to make a plot

### ISSUE THREAD

**Issue by makrez** [tidyverse/ggplot2#4869]
I often send results to customers in the form of plots. The customers themselves are familiar with R and would like to change some stylistic aspects. It would be very handy to send the (minimal) data that was used for creating the plot along with the plot. The original data is often in a much larger data frame which has gone through a few steps of manipulation before it is ready for passing to a `ggplot` function.

Thus, it would be very useful to have something like this:

```
g <- ggplot() + ...
ggsave(g, filename = "plot1.png")
ggdatasave(g, filename="plot1.RDS")
```

Does such a function already exist? I am aware that this can be achieved in different ways, but I thought this could be a nice feature.

**Comment by smouksassi** [comment]
you can always organize your workflow like this:

data_with_many_columns
minimaldatatoproduce_the_plot <- datawithmanycolumns [,c("xname","anytotherusedmappingname","...")]

ggplot(data= minimaldatatoproduce )

there is ways to extract the data from ggplot object but then you cannot just re run the plot using that data

you can always output in editable powerpoint to let the user on the other end change the stylistic aspects  ( color, font, font size etc.)
#based on rvg
#https://davidgohel.github.io/rvg/
#https://github.com/tomwenseleers/export
library(export)
graph2ppt(ggplotobject,
          file = "Reditableplot.pptx", vector.graphic = TRUE )

**Comment by thomasp85** [comment]
This is outside the scope of ggplot2 - data can be passed in in a lot of ways and it would be hard to make sure that any conceivable code would work with whatever data we can deduce.

It is much better to either decouple the data preparation from the plotting as suggested by @smouksassi or simply provide the full script along with the raw data
