### ISSUE TITLE
drop = FALSE is not working properly (enforcing empty space for some missing levels in a boxplot)

### ISSUE THREAD

**Issue by LuisLauM** [tidyverse/ggplot2#4877]
In the following example (using the iris dataset), I am creating a factor class variable in which one of the species does not contain values of level C. When I make the plot, I cannot find a way to make ggplot not drop the empty level (virginica-C). It suppose that the argument `drop = FALSE` do that, but it does not.

```r
require(dplyr)
require(ggplot2)

iris %>% 
  
  mutate(fct_x = factor(x = sample(x = c("A", "B", "C"), size = nrow(.), replace = TRUE), 
                        levels = c("A", "B", "C"))) %>% 
  
  filter(!(Species == "virginica" & fct_x == "C")) %>% 
  
  ggplot(aes(x = Species, y = Sepal.Length, fill = fct_x)) +
  
  geom_boxplot() +
  
  scale_fill_discrete(drop = FALSE)
```

In other words, as you can see in the figure that I am attaching, the virginica group does NOT show an empty space for group C (because there are no elements of type virginica-C) and that is exactly what I want to achieve: to show that empty space in the figure.

![Rplot](https://user-images.githubusercontent.com/8452334/174020272-199cd275-0673-436a-b41c-269bedc0a4e7.png)

**Comment by smouksassi** [comment]
can you elaborate on what expected behavior you are looking at see below for how things differ when playing with
scale_x_discrete(drop=TRUE) vs scale_fill_discrete(drop=TRUE)

``` r
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
library(ggplot2)
library(patchwork)

set.seed( 123456)
a <- iris %>%
  mutate(fct_x = factor(
    x = sample(
      x = c("A", "B", "C",NA),
      size = nrow(.),
      replace = TRUE
    ),
    levels = c("A", "B", "C")
  )) %>%
  filter(!(Species == "virginica"),! fct_x=="C") %>%
  ggplot(aes(x = Species, y = Sepal.Length, fill = fct_x)) +
  geom_boxplot(position = position_dodge(preserve = "single"))+
  scale_x_discrete(drop=FALSE)+
  scale_fill_discrete(drop=FALSE)

b <- a +
  scale_x_discrete(drop=FALSE)+
  scale_fill_discrete(drop=TRUE)
#> Scale for 'x' is already present. Adding another scale for 'x', which will
#> replace the existing scale.
#> Scale for 'fill' is already present. Adding another scale for 'fill', which
#> will replace the existing scale.

c <- a +
  scale_x_discrete(drop=TRUE)+
  scale_fill_discrete(drop=FALSE)
#> Scale for 'x' is already present. Adding another scale for 'x', which will
#> replace the existing scale.
#> Scale for 'fill' is already present. Adding another scale for 'fill', which
#> will replace the existing scale.

d<- a +
  scale_x_discrete(drop=TRUE)+
  scale_fill_discrete(drop=TRUE)
#> Scale for 'x' is already present. Adding another scale for 'x', which will
#> replace the existing scale.
#> Scale for 'fill' is already present. Adding another scale for 'fill', which
#> will replace the existing scale.

(a | b) /
  (c | d)
```

![](https://i.imgur.com/uPAtUZg.png)

<sup>Created on 2022-06-16 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by LuisLauM** [comment]
> can you elaborate on what expected behavior you are looking at see below for how things differ when playing with scale_x_discrete(drop=TRUE) vs scale_fill_discrete(drop=TRUE)
> 
> ```r
> library(dplyr)
> #> 
> #> Attaching package: 'dplyr'
> #> The following objects are masked from 'package:stats':
> #> 
> #>     filter, lag
> #> The following objects are masked from 'package:base':
> #> 
> #>     intersect, setdiff, setequal, union
> library(ggplot2)
> library(patchwork)
> 
> set.seed( 123456)
> a <- iris %>%
>   mutate(fct_x = factor(
>     x = sample(
>       x = c("A", "B", "C",NA),
>       size = nrow(.),
>       replace = TRUE
>     ),
>     levels = c("A", "B", "C")
>   )) %>%
>   filter(!(Species == "virginica"),! fct_x=="C") %>%
>   ggplot(aes(x = Species, y = Sepal.Length, fill = fct_x)) +
>   geom_boxplot(position = position_dodge(preserve = "single"))+
>   scale_x_discrete(drop=FALSE)+
>   scale_fill_discrete(drop=FALSE)
> 
> b <- a +
>   scale_x_discrete(drop=FALSE)+
>   scale_fill_discrete(drop=TRUE)
> #> Scale for 'x' is already present. Adding another scale for 'x', which will
> #> replace the existing scale.
> #> Scale for 'fill' is already present. Adding another scale for 'fill', which
> #> will replace the existing scale.
> 
> c <- a +
>   scale_x_discrete(drop=TRUE)+
>   scale_fill_discrete(drop=FALSE)
> #> Scale for 'x' is already present. Adding another scale for 'x', which will
> #> replace the existing scale.
> #> Scale for 'fill' is already present. Adding another scale for 'fill', which
> #> will replace the existing scale.
> 
> d<- a +
>   scale_x_discrete(drop=TRUE)+
>   scale_fill_discrete(drop=TRUE)
> #> Scale for 'x' is already present. Adding another scale for 'x', which will
> #> replace the existing scale.
> #> Scale for 'fill' is already present. Adding another scale for 'fill', which
> #> will replace the existing scale.
> 
> (a | b) /
>   (c | d)
> ```
> 
> ![](https://camo.githubusercontent.com/fdc094e01573a913f5c13576876e5066b7a84bdb90b28d0f58928e97b5153538/68747470733a2f2f692e696d6775722e636f6d2f75504174555a672e706e67)
> 
> Created on 2022-06-16 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)

I expected that scale_fill_discrete(drop = FALSE) will produce something like this:

![expected](https://user-images.githubusercontent.com/8452334/174033566-5b9aff8d-6a9d-4caf-b588-530ad161c3d6.png)

As you can see, the (empty) space for veriginica-C is left, that is what I understand `drop = FALSE` means, as `scale_x_discrete(drop = FALSE)` does.

PS: This last figure was created in MS Paint (so I crop-paste some parts of the figure itself in order to show my point).

**Comment by smouksassi** [comment]
this is not how ggplot2 is designed to work scale_fill_discrete(drop = FALSE)  will affect the fill scale so you keep or not the missing level color  it won't affect the positioning on the x-axis

**Comment by LuisLauM** [comment]
> this is not how ggplot2 is designed to work scale_fill_discrete(drop = FALSE) will affect the fill scale so you keep or not the missing level color it won't affect the positioning on the x-axis

So, there is no way to preserve empty space for a missing level, is that right?

**Comment by LuisLauM** [comment]
> geom_boxplot(position = position_dodge(preserve = "single"))

I am talking about to a real leaving of space of a missing level.

If you run this piece of code, you will notice that the output figure is smashing together the groups A and C and omiting the space for B:

require(dplyr)
require(ggplot2)

```
iris %>% 
  
  mutate(fct_x = factor(x = sample(x = c("A", "B", "C"), size = nrow(.), replace = TRUE), 
                        levels = c("A", "B", "C"))) %>% 
  
  filter(!(Species == "virginica" & fct_x == "B")) %>% 
  
  ggplot(aes(x = Species, y = Sepal.Length, fill = fct_x)) +
  
  geom_boxplot(position = position_dodge(preserve = "single"))
```
![Rplot01](https://user-images.githubusercontent.com/8452334/174041603-5102ceae-cebb-42ea-b348-0dec8f332bb4.png)

So it is not a matter of preserving widths, but spaces for missing levels.

**Comment by smouksassi** [comment]
A way to do it is below 

``` r
require(dplyr)
require(ggplot2)
set.seed(666)
 plotdata <- iris %>% 
  mutate(fct_x = factor(x = sample(x = c("A", "B", "C"),
                                   size = nrow(.), replace = TRUE), 
                        levels = c("A", "B", "C"))) %>% 
  filter(!(Species == "virginica" & fct_x == "B")) 

  ggplot(plotdata,aes(x = fct_x, y = Sepal.Length, fill =fct_x   )) +
  geom_boxplot(position = position_dodge2(preserve = "single"))+
    facet_grid(~Species,switch = "x")+
    theme(strip.placement = "outside",
          axis.title.x.bottom = element_blank())
```

![](https://i.imgur.com/GAXFcQG.png)

<sup>Created on 2022-06-16 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by LuisLauM** [comment]
> A way to do it is below
> 
> ```r
> require(dplyr)
> require(ggplot2)
> set.seed(666)
>  plotdata <- iris %>% 
>   mutate(fct_x = factor(x = sample(x = c("A", "B", "C"),
>                                    size = nrow(.), replace = TRUE), 
>                         levels = c("A", "B", "C"))) %>% 
>   filter(!(Species == "virginica" & fct_x == "B")) 
> 
>   ggplot(plotdata,aes(x = fct_x, y = Sepal.Length, fill =fct_x   )) +
>   geom_boxplot(position = position_dodge2(preserve = "single"))+
>     facet_grid(~Species,switch = "x")+
>     theme(strip.placement = "outside",
>           axis.title.x.bottom = element_blank())
> ```
> 
> ![](https://camo.githubusercontent.com/2d7cd5372876f414c67171ad6e3fcd756adbe5ab63cda590dcd64ead275ea00a/68747470733a2f2f692e696d6775722e636f6d2f474158466351472e706e67)
> 
> Created on 2022-06-16 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)

Yes, I got the [same suggestion](https://stackoverflow.com/questions/72641842/ggplot2-enforcing-empty-space-for-some-missing-levels-in-a-plot/72643917#72643917) from people in Stackoverflow. I am using that way by now, but I hope ggplot team could end up with a more elegant solution. Now, I know that it is an [open issue](https://github.com/tidyverse/ggplot2/issues/3345) but it seems it has a not-easy solution.

**Comment by danbebber** [comment]
It's 2 years since the last comment here. This functionality really should be support (maintaining correct position of second category boxes)

**Comment by teunbrand** [comment]
The issue is tracked in #3345, let's keep the discussion in one place.
