### ISSUE TITLE
scale_*_brewer: allow larger n (interpolate like distiller)

### ISSUE THREAD

**Issue by jessexknight** [tidyverse/ggplot2#4885]
I understand that the specific discrete colours in `scale_*_brewer` were "[carefully designed and tested on discrete data](https://github.com/tidyverse/ggplot2/blob/main/R/scale-brewer.r#L15)". Yet, `scale_*_distiller` discards this reverence and helpfully allows interpolation for continuous data (at our own peril, apparently). But why is this feature only available for continuous data? Requesting a reasonable number of levels (10) throws an error ...

## MWE
```r
library(ggplot2)
df = expand.grid(x=seq(10),y=seq(10))
df$grp = factor(seq(10))
g = ggplot(df,aes(x=x,y=0,color=grp)) +
  geom_line() +
  scale_color_brewer()
print(g)
```
... throws:
```r
1: In RColorBrewer::brewer.pal(n, pal) :
  n too large, allowed maximum for palette Blues is 9
Returning the palette you asked for with that many colors
```

**Comment by thomasp85** [comment]
there is a difference in using discrete colours and gradients. With discrete colours we need to be sure that each colour is uniquely identifiable for making a correct mapping. With a continuous scale we only need to identify the approximate area of the scale a data-point belongs to
