### ISSUE TITLE
whisker limits on geom_boxplot do not accord with documentation

### ISSUE THREAD

**Issue by stargorg** [tidyverse/ggplot2#4891]
---

Box plot doc states "The upper whisker extends from the hinge to the largest value no further than 1.5 * IQR from the hinge (where IQR is the inter-quartile range, or distance between the first and third quartiles). The lower whisker extends from the hinge to the smallest value at most 1.5 * IQR of the hinge. Data beyond the end of the whiskers are called "outlying" points and are plotted individually." 

When you run the ggplot the red and green lines are at the whisker limits stated in the documentation they are not where ggplot boxplot draws the pictures.

Can the documentation be brought up to date to align with the ggplot boxplot?

```r

library(ggplot2)
library(triangle)

myTriangle <- data.frame(y=(rtriangle(1000,.5)-.5)^4)

myTriangle[1,1] <- -.1  # make own outliers
myTriangle[2,1] <- .1



quantile(myTriangle$y,c(.24,.5,.75,.95,.99))

IQR <- quantile(myTriangle$y,.75)-quantile(myTriangle$y,.25)
low <- quantile(myTriangle$y,.25) - IQR*1.5
high <- quantile(myTriangle$y,.75) + IQR*1.5


#doc
# The upper whisker extends from the hinge to the largest value no further than 1.5 * IQR from the hinge (where IQR is the inter-quartile range, or distance between the first and third quartiles). The lower whisker extends from the hinge to the smallest value at most 1.5 * IQR of the hinge. Data beyond the end of the whiskers are called "outlying" points and are plotted individually.

myTriangle %>%
  ggplot(aes(y=y)) +
  geom_boxplot() +
  geom_hline(aes(yintercept=low),color="green")+
  geom_hline(aes(yintercept=high),color="red")


```

**Comment by clauswilke** [comment]
I think you're mis-understanding what the documentation says. Pay attention to the highlighted part. This is how all boxplots are commonly drawn.

> The lower whisker extends from the hinge to the smallest value **at most** 1.5 * IQR of the hinge.

See also: https://clauswilke.com/dataviz/boxplots-violins.html#fig:boxplot-schematic

**Comment by stargorg** [comment]
Thanks for getting back so quickly, this shows the ambiguity I was referring to, the smallest value is at - .1 yet the whisker has not extended to this smallest value by a distance of 1.5 IQR

 

You might consider  “The lower whisker extends from the hinge to the smallest value within  1.5 * IQR of the hinge.”

 

Or perhaps “The lower whisker extends from the hinge to the smallest value located within  1.5 * IQR of the hinge.”
