### ISSUE TITLE
arrows are (mis-)plotted using geom_line()'s linetype styling

### ISSUE THREAD

**Issue by nkehrein** [tidyverse/ggplot2#4893]
Plotting arrows with `geom_line()` creates weird or broken looking arrowheads when `linetype` is non-solid and `size` is increased. It seems, arrowheads are plotted by re-using the line's linetype, e.g. a dashed line, which can result in arrowheads that look like they have pieces missing. The issue does not appear when using `linetype="solid"`.

``` r
library(ggplot2)
ggplot() +
  geom_line(aes(x, y), data = data.frame(x = c(0, 1), y = c(3)), linetype = "solid", size = 1.0, arrow = arrow()) +
  geom_line(aes(x, y), data = data.frame(x = c(0, 1), y = c(2)), linetype = "dashed", size = 1.0, arrow = arrow()) +
  geom_line(aes(x, y), data = data.frame(x = c(0, 1), y = c(1)), linetype = "dashed", size = 1.0, arrow = arrow(type = "closed"))
#> size aesthetic has been deprecated for use with lines as of ggplot2 3.4.0
#> ℹ Please use linewidth aesthetic instead
#> This message is displayed once every 8 hours.
```

![](https://i.imgur.com/oqtLzDu.png)

<sup>Created on 2022-07-03 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by yutannihilation** [comment]
While these are visually unsound, I think it's just how `arrow()`, which is provided by grid package, is drawn. There can be better alternatives, but it's probably out of scope of ggplot2.

**Comment by yutannihilation** [comment]
It seems the conclusion is this is not what we can fix, sorry. Closing.

https://github.com/tidyverse/ggplot2/issues/2442#issuecomment-364212940
