### ISSUE TITLE
scale_color_manual: breaks no longer works as it used to

### ISSUE THREAD

**Issue by drtoche** [tidyverse/ggplot2#4895]
Setting values of colors manually:

``` r
library(ggplot2)
ggplot(mtcars, aes(mpg, wt)) +
  geom_point(aes(colour = factor(cyl))) +
  scale_colour_manual(values = c("red", "blue", "green"))
```

![](https://i.imgur.com/TSB5Kvm.png)

<sup>Created on 2022-07-03 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

Setting new names in the legend with `breaks` no longer works like it used to:
``` r
library(ggplot2)
ggplot(mtcars, aes(mpg, wt)) +
  geom_point(aes(colour = factor(cyl))) +
  scale_colour_manual(values = c("red", "blue", "green"), breaks=c("Red", "Blue", "Green"))
```

How does one change the legend names? Thanks. 

![](https://i.imgur.com/d0RoVcH.png)

<sup>Created on 2022-07-03 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by yutannihilation** [comment]
> works like it used to:

I quickly tried versions between the latest and v3.2.0, but I couldn't find the version where this used to work as you expected...

I think you can just use `labels`.

``` r
library(ggplot2)

ggplot(mtcars, aes(mpg, wt)) +
  geom_point(aes(colour = factor(cyl))) +
  scale_colour_manual(values = c("red", "blue", "green"), labels = c("Red", "Blue", "Green"))
```

![](https://i.imgur.com/Iqd8Igg.png)

<sup>Created on 2022-07-03 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by drtoche** [comment]
I see, thanks!

I missed `labels` because it wasn't listed under **Usage** at the top of the manual's page. It is, however, listed under **Arguments** further down, which I'd missed. 

https://ggplot2.tidyverse.org/reference/scale_manual.html

The code worked back on 17 April 2016, but I do not have a record of the package version.

**Comment by yutannihilation** [comment]
I think you can easily recall `labels` with positional scales, i.e. `scale_{x|y}_*`, but it might take some time in the case of non-positional ones. (confession: actually, I too couldn't come up with the `labels` argument immediately)

> 17 April 2016

Thanks for the detail. I wish we could maintain the backward-compatibility such a long period, but it seems a lot of things has been changed since then.

**Comment by ptoche** [comment]
Time flies!

Thanks again !
