### ISSUE TITLE
Vignette for aesthetic specifications has "font face" heading twice

### ISSUE THREAD

**Issue by jdonland** [tidyverse/ggplot2#4897]
In the vignette for aesthetic specifications ([ggplot2/vignettes/ggplot2-specs.Rmd](https://github.com/tidyverse/ggplot2/blob/HEAD/vignettes/ggplot2-specs.Rmd)), the first instance of the "Font face" subheading should read "Font family" instead.

**Comment by yutannihilation** [comment]
Closed via #4898
