### ISSUE TITLE
Remove random ggplot2 startup messages

### ISSUE THREAD

**Issue by KasperThystrup** [tidyverse/ggplot2#4900]
I might be a little conservative in my opinions, but generating unnecessary messages upon loading packages is bad practice. While I understand the intentions behind these messages, I for one, would hate if multiple future packages would print their own tips, every time I would start a new session.

```r
library(ggplot2)
```

Maybe consider generating a function that enables user to selectively add these tips to their sessions - perhaps upon loading `tidyverse`.
One might consider to generate a tips package that enable the user to select whether or not to receive tips e.g. `tips::tip_of_the_day(enable = TRUE)`, or alternately integrate into existing packages e.g. `usethis::tip_of_the_day(enable = TRUE)`

**Comment by KasperThystrup** [comment]
Boy, this is apparently a really old feat and weirdly enough the first time I encounter this in more than 5+ years of daily R use...
[039abc0 ](https://github.com/tidyverse/ggplot2/commit/039abc0535575d381062a7b3870e21f98abec314) :-o

**Comment by hadley** [comment]
As you have discovered this is very old and we have no plan to change it at the moment.
