### ISSUE TITLE
Issues with arrow heads of geom_segment

### ISSUE THREAD

**Issue by tfjaeger** [tidyverse/ggplot2#4905]
The issue is described here https://github.com/tidyverse/ggplot2/issues/2442#issue-295306201 and still unresolved: arrow heads render poorly when the linetype of a geom_segment is not solid. Is there a way to alert developers of the grid package to this issue? Arrows are a rather common feature in advanced data visualizations. They way the currently render is rather unappealing, and requires users to develop 'hacks' for their specific needs. So I just wanted to check in whether this is on someone's 'radar'.

**Comment by yutannihilation** [comment]
> Is there a way to alert developers of the grid package to this issue?

As grid is a part of the R distribution, you should report it to the R core. I quickly searched "grid arrow" on https://bugs.r-project.org/, but it seems there's no report yet. I've filed one or two bug reports there, but honestly I don't know what's the best way to do such a feature request, sorry. [R-devel Slack](https://contributor.r-project.org/slack) might help. I too hope this will be resolved properly...

**Comment by tfjaeger** [comment]
Thanks for the quick response!

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Hiroaki Yutani ***@***.***>
Sent: Sunday, July 10, 2022 7:40:41 PM
To: tidyverse/ggplot2 ***@***.***>
Cc: Jaeger, Florian ***@***.***>; Author ***@***.***>
Subject: [EXT] Re: [tidyverse/ggplot2] Issues with arrow heads of geom_segment (Issue #4905)


Is there a way to alert developers of the grid package to this issue?

As grid is a part of the R distribution, you should report it to the R core. I quickly searched "grid arrow" on https://bugs.r-project.org/<https://urldefense.com/v3/__https://bugs.r-project.org/__;!!CGUSO5OYRnA7CQ!b4Glrs5yUZekj7bdVHANVlAeXGAawByUaLJVjvS0M_-1hknHgbOj7iuo_Dd9fOgjOLdmkT8Gw-PU53wcSeW44UcW7TnP6g$>, but it seems there's no report yet. I've filed one or two bug reports there, but honestly I don't know what's the best way to do such a feature request, sorry. R-devel Slack<https://urldefense.com/v3/__https://contributor.r-project.org/slack__;!!CGUSO5OYRnA7CQ!b4Glrs5yUZekj7bdVHANVlAeXGAawByUaLJVjvS0M_-1hknHgbOj7iuo_Dd9fOgjOLdmkT8Gw-PU53wcSeW44UcB6ksZFA$> might help. I too hope this will be resolved properly...
