### ISSUE TITLE
Infinite values with `geom_histogram()` and `scale_y_log10()`

### ISSUE THREAD

**Issue by jpquast** [tidyverse/ggplot2#4918]
Dear package maintainer,

I am trying to generate a histogram plot containing two groups with a log10 transformed y-axis. I would expect that missing values would just be ignored for the counting. However, if values are missing from one of the groups or there are bins missing completely infinite values are introduced. Is this a bug or on purpose like this? Is there a way around this problem?

If I do not use a log10 transformed y-axis the plot looks as expected.

``` r
library(ggplot2)

test <- data.frame(a = c(rep(1, 20), rep(2, 10), rep(4,2), c(rep(1, 10), rep(2, 2))), b = c(rep("A", 32), rep("B", 12)))

ggplot(test, aes(x = a, fill = b)) +
  geom_histogram(position = "identity")
#> `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
```

![](https://i.imgur.com/TdqgAoW.png)

However, with a log10 transformed axis it has infinite values wherever values are missing.

``` r
ggplot(test, aes(a, fill = b)) +
  geom_histogram(position = "identity") +
  scale_y_log10()
#> `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
#> Warning: Transformation introduced infinite values in continuous y-axis
```

![](https://i.imgur.com/WPUeBur.png)

I would really appreciate some help! 
Thanks in advance!

**Comment by yutannihilation** [comment]
> a histogram plot containing two groups with a log10 transformed y-axis.

I cannot see any valid use cases when a log-scale bar chart can be useful... What plot did you expect?

**Comment by jpquast** [comment]
In my data the counts for each bin can be orders of magnitude different. Maybe I did not chose the best example for that above. In that case visualizing the histogram with a log10 transformed axis allows one to be able to assess these differences visually. I would expect that for the log10 transformed y-axis bins with a count of `0` are dropped and not log10 transformed, which results in `-Inf` and therefore causes the weird looking plot.

This is a better example of what the data would look like when not plotted with a log10 y-axis:

```r
library(ggplot2)

test <- data.frame(a = c(rep(1, 200000), rep(2, 100), rep(4,2), c(rep(1, 100), rep(2, 20))), b = c(rep("A", 200102), rep("B", 120)))

ggplot(test, aes(x = a, fill = b)) +
  geom_histogram(position = "identity")
```

**Comment by yutannihilation** [comment]
Thanks. While I'm not sure if this can be fixed, it makes sense to some extent. Btw, could you please render your example with the reprex package? (c.f. https://www.tidyverse.org/help/)

**Comment by teunbrand** [comment]
I think current behaviour of ggplot2 makes sense: there are 0 counts for a bin and `log10(0)` evaluates to `-Inf`. If this is not the desired behaviour, you can set the out-of-bounds handling parameter in the scale to drop infinites:

``` r
library(ggplot2)

test <- data.frame(a = c(rep(1, 200000), rep(2, 100), 
                         rep(4,2), c(rep(1, 100), rep(2, 20))), 
                   b = c(rep("A", 200102), rep("B", 120)))

ggplot(test, aes(x = a, fill = b)) +
  geom_histogram(position = "dodge")+
  scale_y_log10(oob = scales::oob_censor_any)
#> `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
#> Warning: Transformation introduced infinite values in continuous y-axis
#> Warning: Removed 55 rows containing missing values (`geom_bar()`).
```

![](https://i.imgur.com/9NfNokZ.png)

<sup>Created on 2022-12-03 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by jpquast** [comment]
@teunbrand Thanks for the answer! That works nicely! I did not know about the `oob` argument!
