### ISSUE TITLE
`geom_line/hline/abline` won't add a line if X-axis is a single value and `expand = FALSE`

### ISSUE THREAD

**Issue by basille** [tidyverse/ggplot2#4920]
This might be sort of a corner case: adding an horizontal line on a graph with a single X value. Simple example here that works:

```r
library("ggplot2")

dd <- data.frame(
    x = 1,
    y = 0.3
)

ggplot(dd, aes(x = x, y = y)) +
    geom_point() +
    geom_hline(yintercept = 0.75) +
    coord_cartesian(ylim = c(0, 1))

```
![works1](https://user-images.githubusercontent.com/4000337/180976353-f53bf558-5aac-450b-8150-a67682d9dc5b.png)

Now, if we restrict the coordinates strictly to our definitions, using `expand = FALSE`, this does not work anymore:

```r
ggplot(dd, aes(x = x, y = y)) +
    geom_point() +
    geom_hline(yintercept = 0.75) +
    coord_cartesian(ylim = c(0, 1), expand = FALSE)
```
![does-not-work1](https://user-images.githubusercontent.com/4000337/180976674-4ef77deb-d902-4c37-95b3-f78b74dd8a8c.png)

Variations with `geom_line()` or `geom_abline()` behave in the same way:

```r
ggplot(dd, aes(x = x, y = y)) +
    geom_point() +
    geom_hline(yintercept = 0.75) +
    geom_abline(slope = 0, intercept = 0.75) +
    coord_cartesian(ylim = c(0, 1), expand = FALSE) # Does not work

ll <- data.frame(x = c(-Inf, Inf), y = 0.75)
ggplot(dd, aes(x = x, y = y)) +
    geom_point() +
    geom_line(data =  ll, aes(x, y)) +
    coord_cartesian(ylim = c(0, 1), expand = FALSE) # Does not work
```

One solution I found was to set limits on the X-axis explicitly:

```r

ggplot(dd, aes(x = x, y = y)) +
    geom_point() +
    geom_hline(yintercept = 0.75) +
    coord_cartesian(ylim = c(0, 1), xlim = c(0.95, 1.05), expand = FALSE)
```
![works2](https://user-images.githubusercontent.com/4000337/180976981-f8064877-3e22-4a80-9339-13ea23a50e94.png)

But it's not as elegant: the drawback is that we don't have a nice X-axis with a single value anymore. 

I can see why `geom_line/hline/abline` don't like this (and can't see a line on non-continuous and virtually non-existent X-axis), but I wonder if there's a way to circumvent it, as all I want is to draw this line!

**Comment by thomasp85** [comment]
There is no way around this. I can see the argument for having `geom_hline()` work, but conceptually it wouldn't make sense for for either `geom_line()` or `geom_abline()` since the x-axis has no dimensions and thus any slope would both be correct and wrong.

My advise is to take proper control of the x-axis and then only draw the label you want

**Comment by basille** [comment]
Very true! That is why I focused on `geom_hline()` to start with. I can understand the reasons behind it, and why it's not going to change. Admittedly, it might be a bit of a corner case here using `expand = FALSE`, but it took me a whole lot of time to figure out what was going on… (maybe an example in the doc of `coord_cartesian()` would be worth it? Again, maybe too much of a corner case)
