### ISSUE TITLE
GeomBar should use rename_size = TRUE

### ISSUE THREAD

**Issue by yutannihilation** [tidyverse/ggplot2#4923]
During comparing `GeomBar` and `GeomCol` on #4921, I found `GeomBar` doesn't have `rename_size = TRUE` specified.

I think we can just add `rename_size = TRUE` to `GeomBar` and replace `GeomCol` with `GeomCol <- ggproto("GeomCol", GeomBar)` as a first step towards https://github.com/tidyverse/ggplot2/issues/3798

**Comment by thomasp85** [comment]
good catch - do you want to take this?

**Comment by yutannihilation** [comment]
Yes, I'll make a PR after #4921 gets merged.
