### ISSUE TITLE
Using categorical fill with many categories in geom_hex results in oversized hexagons 

### ISSUE THREAD

**Issue by artuurC** [tidyverse/ggplot2#4926]
Hi,

I am currently trying to add a categorical fill to geom_hex. The problem is that when using too much categories the hexagons get big and obscure the rest of the plot. Attached dataset and reprex should illustrate the problem.

Thanks in advance

![image](https://user-images.githubusercontent.com/58510375/181761401-642b2584-0e98-4c2d-8ac7-aa5ae658379c.png)

[dataset.csv](https://github.com/tidyverse/ggplot2/files/9219918/dataset.csv)

```r
test <- as.data.frame(read.csv("./dataset.csv"))
test$colors <- as.factor(test$colors)
ggplot(test) +
  geom_hex(aes(x = dimred_1, y = dimred_2, fill = colors), bins = 200, size = 2) +
  theme_minimal() +
  coord_fixed()
 
test2 <- test
levels(test2$colors) <- rep(1:15, 2)
ggplot(test2) +
  geom_hex(aes(x = dimred_1, y = dimred_2, fill = colors), bins = 200, size = 2) +
  theme_minimal() +
  coord_fixed()

test3 <- test
levels(test3$colors) <- rep(1:10, 3)
ggplot(test3) +
  geom_hex(aes(x = dimred_1, y = dimred_2, fill = colors), bins = 200, size = 2) +
  theme_minimal() +
  coord_fixed()
```

**Comment by yutannihilation** [comment]
Sorry, I cannot reproduce your issue. This sort of question is a better fit for [RStudio Community](https://community.rstudio.com). Please ask there with a minimal reproducible example (I mean, without the need to download your CSV file). We use this issue tracker for bug reports and feature requests.
