### ISSUE TITLE
failure in passing arguments to `discrete_scale`

### ISSUE THREAD

**Issue by olobiolo** [tidyverse/ggplot2#4931]
Passing down arguments to multiple functions with `...` causes error from `*_scale`.
This happens under `ggplot2` versions 3.3.5, 3.3.6, and 3.3.6.9000.
```r
# plotting function
fooPlot <- function(data, varX, varY, ...) {
  p <- ggplot(data, aes_string(x = varX, y = varY, color = "Species")) +geom_point()
  return(p)
}

fooPlot(iris, "Sepal.Length", "Sepal.Width")


# higher function that calls the plotting function
fooMother <- function(x, ...) {
  p <- fooPlot(x, ...)
  return(p)
}

fooMother(iris, varX = "Sepal.Length", varY = "Sepal.Width")


# another higher function that calls the plotting function
# also allows to modify legend labels
fooFather <- function(x, ...) {
  p <- fooPlot(x, ...)
  p <- p + scale_color_manual(values = c("indianred1", "springgreen2", "cornflowerblue"), ...)
  return(p)
}

fooFather(iris, varX = "Sepal.Length", varY = "Sepal.Width", labels = LETTERS[1:3])

```
It can be rectified by adding a `...` argument to `discrete_scale`.

**Comment by yutannihilation** [comment]
I think there's no simple way to do this. I would probably do something like below, but anyway this sort of question is a better fit for [RStudio Community](https://community.rstudio.com). Please ask there with a minimal reproducible example. We use this issue tracker for bug reports and feature requests. Thanks!

``` r
fooFather <- function(x, ...) {
  # categorize dots
  args <- list(...)
  args <- split(args, names(args) %in% names(formals(fooPlot)))
  
  p <- rlang::inject(fooPlot(x, !!!args[["TRUE"]]))
  p <- p + rlang::inject(scale_color_manual(values = c("indianred1", "springgreen2", "cornflowerblue"), !!!args[["FALSE"]]))
  return(p)
}
```

**Comment by olobiolo** [comment]
Perhaps I was not clear. 
I was not asking how to do it, I had a workaround similar to what you proposed, but that is not the issue. 
I was pointing out how this problem can be avoided. 

Adding `...` as an argument to `discrete_scale` makes it ignore unmatched named arguments. I tested it and it does the trick.

**Comment by yutannihilation** [comment]
Ah, sorry. I mean we don't want to add `...`. It might look useful to you, but, on the other hand, it makes it hard to find your mistakes when you mistype the args. It's a trade-off.

**Comment by olobiolo** [comment]
Fair enough, I'll make do with capturing arguments in parent function calls.
