### ISSUE TITLE
weird shading in the lowest bin of stat_density_2d

### ISSUE THREAD

**Issue by nfancy** [tidyverse/ggplot2#4946]
Hi,

Thank you very much for this awesome plotting package. I'm trying to generate some density_2d plots but I get weird shading in the lowest bin (highlighted in the image pdf). My data to reproduce the plot and the scripts are as follows. I am using ggplot2 v. 3.3.3.
[Rplot.pdf](https://github.com/tidyverse/ggplot2/files/9337324/Rplot.pdf)
[data.zip](https://github.com/tidyverse/ggplot2/files/9337327/data.zip)

Another question is, to calculate a scaled density (to normalize the number of observation across the faceting groups) I am using ndensity and nevel, is it the correct usage?

```r
ggplot(dt, aes(x = UMAP_1, y = UMAP_2)) +
  xlab("UMAP 1") +
  ylab("UMAP 2") +
  geom_point() +
  stat_density_2d(aes(
    fill = ..nlevel..),
    geom = "polygon",
    contour = TRUE,
    contour_var = "ndensity")+
  scale_fill_gradientn(colours=c("#FFFFFF",
                                 rev(RColorBrewer::brewer.pal(n = 11,
                                                              name = "RdYlBu")))
  )+
  theme_bw() +
  ggplot2::theme(
    panel.grid = ggplot2::element_blank(),
    axis.text.x = element_text(size = 16, color = "black"),
    axis.text.y = element_text(size = 16, color = "black"),
    axis.title = ggplot2::element_text(size = 18, color = "black"),
    legend.text = ggplot2::element_text(size = 16, color = "black"),
    legend.title = ggplot2::element_text(size = 16, color = "black"),
    strip.text = ggplot2::element_text(size = 16, color = "black"),
    rect = element_blank(),
    axis.line = element_line(color = "black"),
    panel.background = element_rect(fill = "transparent"),
    plot.background = element_rect(fill = "transparent"),
    legend.background = element_rect(fill = "transparent"),
    plot.title = element_text(hjust = 0.5),
    plot.subtitle = element_text(hjust = 0.5)
  ) +
  facet_grid( ~ trem2)
```
Thanks in advance for your help.

Best wishes
Nurun

**Comment by smouksassi** [comment]
any reason why not using geom_density_2d_filled ?
`ggplot(dt,aes(x = UMAP_1, y = UMAP_2)) +
  xlab("UMAP 1") +
  ylab("UMAP 2") +
  facet_grid( ~ trem2) +
  geom_density_2d_filled(aes(
    fill = ..nlevel..),
    contour_var = "ndensity")+
  geom_point(size=1,alpha=0.2) +
  scale_fill_gradientn(colours=c("#FFFFFF",
                                 rev(RColorBrewer::brewer.pal(n = 11, name = "RdYlBu")))
  `

**Comment by nfancy** [comment]
That's awesome! Thank you very much. It worked perfectly.
