### ISSUE TITLE
geom_col should have a `stat = "identity"` argument within it

### ISSUE THREAD

**Issue by davidhodge931** [tidyverse/ggplot2#4948]
For consistency with how all other geom's work

**Comment by yutannihilation** [comment]
`geom_col()` is meant to be a shortcut to `geom_bar(stat = "identity")`. In my understanding, that's why `geom_col()` doesn't expose `stat`. Please use `geom_bar()` if you want to specify `stat`.

**Comment by davidhodge931** [comment]
Lots of people are only familiar with geom_col. 

This is an easy change. I could make a pull request @yutannihilation ?
