### ISSUE TITLE
Feature request: Could `guide_colourbar` have a `show.limits` argument like `guide_coloursteps` has?

### ISSUE THREAD

**Issue by davidhodge931** [tidyverse/ggplot2#4949]

**Comment by teunbrand** [comment]
Hi David,

What exactly is your intended use case? I think most of this suggestion can already be implemented by simply excluding the limits from the `breaks` with a function.

``` r
library(ggplot2)
library(scales)

df <- data.frame(x = 0:10)

ggplot(df, aes(x, x, colour = x)) +
  geom_point() +
  scale_colour_continuous(
    breaks = ~ setdiff(extended_breaks()(.x), .x)
  )
```

![](https://i.imgur.com/3v7DYQs.png)

<sup>Created on 2023-01-07 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by davidhodge931** [comment]
Kind of weird `guide_colour_bar` has `draw.ulim` and `draw.llim`, whereas `guide_steps` has `show.limits`

**Comment by davidhodge931** [comment]
It seems not super consistent, but I'll just close as not that important
