### ISSUE TITLE
Computed variable docs should suggest `after_stat()`

### ISSUE THREAD

**Issue by hadley** [tidyverse/ggplot2#4951]
e.g. `geom_freqpoly()` lists `count`, `density`, etc. Should mention that you need `after_stat()` somewhere.

**Comment by yutannihilation** [comment]
What about just adding some simple notice like "Please see `?after_stat` for the details of how to access these special variables"?

**Comment by hadley** [comment]
Yeah. And/or maybe wrap each in `after_stat()`?

**Comment by yutannihilation** [comment]
Sounds good. Maybe it should be a vignette rather than just a help page of `?after_stat`? I think the topic is worth it.

**Comment by hadley** [comment]
Or maybe just make `?after_stat` longer? Since roxygen2 now supports code blocks, there's a lot more we could do in that doc topic.

**Comment by yutannihilation** [comment]
I see, but I meant a vignette can catch more users' eyes. Since computed variables is often what users feel "I didn't know I needed," a help page might not be the best place. No strong opinion.

**Comment by hadley** [comment]
@yutannihilation ah I see. My sense is that people are as unlikely to discover a new vignette as anything else, and all else better equal putting everything in one place (i.e. `?after_stat`) is easier than two.

**Comment by yutannihilation** [comment]
Thanks. Not immediately sure which is better, but I'm fine with your strategy.
