### ISSUE TITLE
Should element_rect() and element_line() also use `linewidth` instead of `size`?

### ISSUE THREAD

**Issue by yutannihilation** [tidyverse/ggplot2#4953]
#3672 introduced `linewidth` to Geoms. On the other hand, `element_rect()` and `element_line()` still uses `size`. Do we need to rename them for consistency?

Currently, this doesn't work.

``` r
library(ggplot2)

ggplot(mpg, aes(x = hwy, y = cty, color = drv)) +
  geom_point() +
  theme(
    legend.key = element_rect(linewidth = 3, colour = "red")
  )
#> Error in element_rect(linewidth = 3, colour = "red"): unused argument (linewidth = 3)
```

<sup>Created on 2022-08-22 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by thomasp85** [comment]
I think we should, but we should be careful to properly deprecate the size argument... I can take a stab at this
