### ISSUE TITLE
Bug: for colorbars, there is a error when one tries to have the limits as breaks, and not plot tickmarks

### ISSUE THREAD

**Issue by davidhodge931** [tidyverse/ggplot2#4954]
For colorbars, there is a error when one tries to have the limits as breaks, and not plot tickmarks
```
library(tidyverse)
library(palmerpenguins)

penguins %>% 
  ggplot() +
  geom_point(aes(flipper_length_mm, bill_depth_mm, col = body_mass_g)) +
    ggplot2::scale_colour_gradientn(
      colors = viridis::viridis(10),
      breaks = function(x) x,
      guide = ggplot2::guide_colourbar(
        draw.ulim = FALSE,
        draw.llim = FALSE,
      ))
```

**Comment by teunbrand** [comment]
I'm not sure whether I'm considering the scope of the issue right, but wouldn't setting `guide_colourbar(ticks = FALSE)` make more sense in this case? If you need to hide the labels as well you could set `label = FALSE` too.

**Comment by davidhodge931** [comment]
This works fine now :)
