### ISSUE TITLE
strip.switch.pad.* modifies plot when facet labels are not switched, if strip.placement = "outside"	

### ISSUE THREAD

**Issue by davidhodge931** [tidyverse/ggplot2#4973]
I think that strip.switch.pad.grid or strip.switch.pad.wrap are intended to only modify the plot where facet labels are switched.

<img width="323" alt="image" src="https://user-images.githubusercontent.com/55065152/187787732-5f28c3b1-1865-4753-b9b5-7fa049e58dea.png">

However if strip.placement = "outside", the position of the labels is modifed by strip.switch.pad.* 

```
library(tidyverse)
library(palmerpenguins)

p <- penguins  %>% 
  ggplot() +
  geom_point(aes(flipper_length_mm, body_mass_g)) +
  facet_grid(vars(sex), vars(species)) 

p
```
<img width="344" alt="image" src="https://user-images.githubusercontent.com/55065152/187788001-14af323f-f456-4d6a-9f7b-cf30f9f5a149.png">

```
p +
  theme(strip.placement = "outside") +
  theme(strip.switch.pad.grid = unit(7.5, "pt"))
```
<img width="347" alt="image" src="https://user-images.githubusercontent.com/55065152/187788099-26308993-db38-4211-bc4b-43abe453df2b.png">

**Comment by teunbrand** [comment]
Hey David, it seems that this behaviour has changed since ggplot2 3.4.0, most likely in https://github.com/tidyverse/ggplot2/pull/4669.
