### ISSUE TITLE
gtable will not install

### ISSUE THREAD

**Issue by AlgaeKat** [tidyverse/ggplot2#4975]
hi, 

I am teaching a class using R and I am running into a problem installing ggplot2 that I have never  encountered before. It seems that gtable is not installing.

Is anyone else having this issue?

Thanks

**Comment by thomasp85** [comment]
What happens if you try to install gtable?

**Comment by AlgaeKat** [comment]
it won't install either.

**Comment by thomasp85** [comment]
Cam you share what the issue is. Otherwise it is very hard to help. What does it say when it fails to install?

**Comment by AlgaeKat** [comment]
Yes, sorry. 
Unfortunately it is on the private computers of students. (Most of them are having this issue.) I am meeting with a few today and will ask for the error message code. 
Thanks

**Comment by AlgaeKat** [comment]
Thanks for chatting with me @thomasp85. I have been meeting with students and the issue seems to have resolved itself. I am not sure what has change, but appreciate your time.
