### ISSUE TITLE
`scale_colour_manual()` does not drop factor levels missing in data

### ISSUE THREAD

**Issue by aphalo** [tidyverse/ggplot2#4978]
Argument passed to formal parameter `drop` is ignored, and unused factor levels are not dropped from the legend as indicated in the documentation. This used to work in the past. 3.3.6, 3.3.5, 3.3.4 are broken, 3.3.3 is good. 

Reprex for version 3.3.6 (3.3.5, 3.3.4). `drop = TRUE` ignored in the manual scale, but obeyed by the default scale.

``` r
library(ggplot2)
packageVersion("ggplot2")
#> [1] '3.3.6'

my.df <- data.frame(x = rnorm(50),
                    y = rnorm(50),
                    outcome = factor(sample(letters[1:3], 50, replace = TRUE), 
                                     levels = letters[1:4]))

# level "d" is dropped
ggplot(my.df, aes(x, y, colour = outcome)) +
  geom_point()
```

![](https://i.imgur.com/CjlzYqs.png)

``` r

# level "d" is not dropped
ggplot(my.df, aes(x, y, colour = outcome)) +
  geom_point() +
  scale_colour_manual(values = c(a = "red", b = "green", c = "blue", d = "orange"),
                      drop = TRUE)
```

![](https://i.imgur.com/Gw3Lvzs.png)

<sup>Created on 2022-09-04 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

Reprex for version 3.3.3. `drop = TRUE` obeyed consistently.

``` r
library(ggplot2)
packageVersion("ggplot2")
#> [1] '3.3.3'

my.df <- data.frame(x = rnorm(50),
                    y = rnorm(50),
                    outcome = factor(sample(letters[1:3], 50, replace = TRUE), 
                                     levels = letters[1:4]))

# level "d" is dropped
ggplot(my.df, aes(x, y, colour = outcome)) +
  geom_point()
```

![](https://i.imgur.com/no8C0Jd.png)

``` r

# level "d" is dropped as expected
ggplot(my.df, aes(x, y, colour = outcome)) +
  geom_point() +
  scale_colour_manual(values = c(a = "red", b = "green", c = "blue", d = "orange"),
                      drop = TRUE)
```

![](https://i.imgur.com/0YSuu6i.png)

<sup>Created on 2022-09-04 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by smouksassi** [comment]
I think this has been fixed in the dev version:


``` r
library(ggplot2)

set.seed(13465)
my.df <- data.frame(x = rnorm(50),
                    y = rnorm(50),
                    outcome = factor(sample(letters[1:3], 50,
                                            replace = TRUE), 
                                     levels = letters[1:4]))


ggplot(my.df, aes(x, y, colour = outcome)) +
  geom_point() +
  scale_colour_manual(values = c(a = "red" , b = "green",
                                 c = "blue", d = "orange"),
                      drop = TRUE)
```

![](https://i.imgur.com/bKBQDQV.png)

``` r
packageVersion("ggplot2")
#> [1] '3.3.6.9000'
```

<sup>Created on 2022-09-04 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by yutannihilation** [comment]
Yes, I think so, too. Please wait for the next release.

**Comment by aphalo** [comment]
o.k., great! I tried to install the development version before reporting, but the installation of one of the dependencies not yet in CRAN failed repeatedly. I should not have given up so quickly!
