### ISSUE TITLE
view facet label text

### ISSUE THREAD

**Issue by bergsmat** [tidyverse/ggplot2#4979]
```labeller()``` and related functionality give huge flexibility for controlling strips, thanks!  But I've been asked to write an extension that programmatically modifies strip text font size in the event that a strip has many lines. At present it is hard to examine strip text in advance.  Apparently ```labeller()``` is called once during ```build_strip()``` and the result is immediately rendered as grobs.  Stealing ideas from https://github.com/yjunechoe/ggtrace I can do ```invisible(ggplotGrob(x))``` while running ```trace()``` on ```build_strip()```, but the latter is not exported so there is going to be a package check warning that will probably keep the solution from ever posting on CRAN.

I completely understand if you do not want to export ```build_strip()```.  Is there an alternative way, existing or otherwise (feature request), to view the facet label text of a ggplot object before rendering?

```r
debug(ggplot2:::build_strip) # labels near line 12
ggplot(mtcars, aes(wt, mpg)) + geom_point() + facet_grid(cyl ~ am + gear)
```

**Comment by teunbrand** [comment]
You can intercept the text rendering at the element drawing stage. You can wrap `element_text()` with a class of your own, make an S3 method for `element_grob.your_class()` and in there, tweak text rendering as you see fit. Example below:

``` r
library(ggplot2)
library(rlang)

# Subclass element_text
element_text_refit <- function(...) {
  elem <- element_text(...)
  class(elem) <- c("element_text_refit", class(elem))
  elem
}

# S3 method for `element_grob()`
element_grob.element_text_refit <- function(
    element, label = "", size = NULL, ...
) {
  n_lines <- stringr::str_count(label, pattern = "\n") + 1
  size <- rep_len(size %||% element$size, length(n_lines)) / n_lines
  class(element) <- setdiff(class(element), "element_text_refit")
  element_grob(element, label = label, size = size, ...)
}

# Example data with various number of lines on the strip
df <- iris
levels(df$Species) <- c("Setosa", "Iris\nversicolor", "The plant\nIris\nvirginica")

ggplot(df, aes(Sepal.Width, Sepal.Length)) +
  geom_point() +
  facet_wrap(~ Species) +
  theme(
    strip.text = element_text_refit(size = 36)
  )
```

![](https://i.imgur.com/RbGrlhH.png)

<sup>Created on 2022-09-06 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by bergsmat** [comment]
@teunbrand Very nice, thanks!  I was able to implement your solution and it does indeed avoid reliance on non-exported functions.  I have the remaining problem, though, that element-wise rescaling does not let me accommodate the case where one margin has multiple facets, such as the column facets in the example below (trivial here, but a real problem for certain facet_wrap cases).  Viewing the labels in totality (as seen in ```build_strip()``` allows me to anticipate -- not just that individual strips have multiple lines, but also -- that there may be multiple strips on a margin.  Perhaps ```facet_grid(cyl ~ paste(sep = '\n', am, gear))``` but that feels strained.  Suggestions welcome.

``` r
library(ggplot2)
ggplot(mtcars, aes(wt, mpg)) + 
  geom_point() + 
  facet_grid(
    cyl ~ am + gear, 
    labeller = label_both
  ) +
  theme_bw()
```

![](https://i.imgur.com/kESGknn.png)

<sup>Created on 2022-09-06 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
