### ISSUE TITLE
Feature request: could the `scale_colour_gradientn` `values` argument allow the user to supply a function?

### ISSUE THREAD

**Issue by davidhodge931** [tidyverse/ggplot2#4980]
It'd be cool if scale_colour_gradientn and scale_colour_stepsn values argument would accept a function like breaks does, as it would enable less hardcoding..

<img width="385" alt="image" src="https://user-images.githubusercontent.com/55065152/188767865-587dd26e-6130-489e-b850-7b9e6a8dee09.png">

**Comment by davidhodge931** [comment]
Oh ok, I'm not aware of how the underlying code works. If this is technically impossible, it can be closed. I just thought that this would be a super useful feature

**Comment by teunbrand** [comment]
Well it is technically challenging, I wouldn't say impossible. Is there a specific use-case that you have in mind for this that would be annoying to solve with the current options? I'm still not quite sure what should theoretically be used as input to the function.
