### ISSUE TITLE
Feature request: could colouring of date, datetime and time variables be supported more completely?

### ISSUE THREAD

**Issue by davidhodge931** [tidyverse/ggplot2#4982]
At present, there are only scale_colour_date and scale_colour_datetime functions available for modifying date, datetime and time colours. These appear to be equivalent to `scale_colour_gradient`.

This means that it is not possible to create colour steps with date, datetime or time variables. 

Not is it possible to use the methods and colours/values arguments of the scale_colour_gradientn function.

It would be awesome if date, datetime and time colouring were supported more completely in this way!

**Comment by davidhodge931** [comment]
Thanks @teunbrand. I was not aware that you could do this. Yes, that would allow you to do most things other than apply another trans to the date or time colour variable

**Comment by teunbrand** [comment]
Due to #5103 having been merged, I think there are now a sufficient amount of options to use date/time variables in non-position scales. Therefore, I'll thank you for this suggestion and hope you have enough tools to make this work.
