### ISSUE TITLE
`ggplot_add()` modifies the original plot

### ISSUE THREAD

**Issue by billdenney** [tidyverse/ggplot2#4983]
When using `ggplot_add()`, it modifies the original plot object in addition to returning the updated plot.  The issue is illustrated by the fact that `my_plot` at the end has a semi-log-y axis even though it never was assigned the addition of `scale_y_log10()`.

``` r
library(ggplot2)

my_data <- data.frame(x=1:5, y=1:5)
my_plot <- ggplot(my_data, aes(x=x, y=y)) + geom_point()
my_plot
```

![](https://i.imgur.com/9zkTvcX.png)

``` r
my_plot_semilog_1 <- my_plot + scale_y_log10()
# my_plot is not modified with "+"
my_plot
```

![](https://i.imgur.com/hsJ2ioo.png)

``` r
my_plot_semilog_2 <- ggplot_add(object = scale_y_log10(), plot = my_plot)
# my_plot is modified with ggplot_add
my_plot
```

![](https://i.imgur.com/jdG25kP.png)

<sup>Created on 2022-09-13 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by yutannihilation** [comment]
`ggplot_add()` is not designed to be called directly by the user. It's intended to be called inside `+.gg`.

https://github.com/tidyverse/ggplot2/blob/e0d54f6d2be6452bbab61a5018abc231a3172ca6/R/plot-construction.r#L55
https://github.com/tidyverse/ggplot2/blob/e0d54f6d2be6452bbab61a5018abc231a3172ca6/R/plot-construction.r#L69-L76

**Comment by billdenney** [comment]
@yutannihilation, in that case, could the documentation be updated to make that clearer and to also clarify that the original plot object will be updated?

**Comment by yutannihilation** [comment]
Hmm, I'm not sure, sorry. I agree with you in that some better documentation could have helped you, but I think we don't have any official documentation about how to use `ggplot_add()`. Currently it seems it's an "expert-only" function.

**Comment by billdenney** [comment]
@yutannihilation Thanks!
