### ISSUE TITLE
changing linetype of one geom_line() conditional on the data

### ISSUE THREAD

**Issue by andreaskuepfer** [tidyverse/ggplot2#4986]
This is a feature request. What I would like to do is **having a geom_line changing its linetype depending on a value in the data** (in the example below `group`).  What I receive instead is the following error:
```
Error in `f()`:
! geom_path: If you are using dotted or dashed lines, colour, size and linetype must be constant over the line
```
Is there any way to achieve this?

Code to reproduce:
```r
  df_t <- tribble(
    ~group,       ~year,   ~value,  
    "group1",     "2010",       70,
    "group1",     "2011",       75,
    "group1",     "2012",       72,
    "group2",     "2013",       77,
    "group2",     "2014",       74,
    "group2",     "2015",       79,
    "group1",     "2016",       76,
    "group1",     "2017",       81)
  
  plot <- ggplot(
    df_t, aes(x = year, y = value, group = 1)
  ) +
    geom_point() +
    geom_line(aes(linetype = ifelse(group == "group1", "dashed", "solid")))
```

**Comment by smouksassi** [comment]
when you want your data values to represent scales value you need to tell it that using
scale_xx_identity()
also you need to group by group for the line 

``` r
library(ggplot2)
df_t <- tribble(
  ~group,       ~year,   ~value,  
  "group1",     "2010",       70,
  "group1",     "2011",       75,
  "group1",     "2012",       72,
  "group2",     "2013",       77,
  "group2",     "2014",       74,
  "group2",     "2015",       79,
  "group1",     "2016",       76,
  "group1",     "2017",       81)
#> Error in tribble(~group, ~year, ~value, "group1", "2010", 70, "group1", : could not find function "tribble"

ggplot(df_t, aes(x = year, y = value)) +
  geom_point() +
  geom_line(aes(linetype = ifelse(group == "group1", "dashed", "solid"),
                group = group))+
  scale_linetype_identity()
#> Error in ggplot(df_t, aes(x = year, y = value)): object 'df_t' not found
```

<sup>Created on 2022-09-14 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by andreaskuepfer** [comment]
Thanks for the quick reply! However, what I would like to have is **one** connected line changing it's linetype as it goes from point to point (conditional on the the `group` column). So when I group `geom_line()` ggplot plots two independent lines.

**Comment by thomasp85** [comment]
Not directly, no. You'd either have to split your data into segments of equal linetype yourself before plotting or rolling your own extension geom that does it for you

**Comment by smouksassi** [comment]
just so you are aware there is  https://ggforce.data-imaginist.com/reference/geom_link.html which interpolates colors along a gradient 
but not sure how a linetype would "transition"  so the most reliable solution is to have a transition point that split into segments (even if the slope of your line does not change)
