### ISSUE TITLE
Geom suggestion: geom_idline() == geom_abline(intercept = 0, slope = 1)

### ISSUE THREAD

**Issue by leonjessen** [tidyverse/ggplot2#4987]
Thanks for a indescribable important framework. Personally, I often find myself writing `geom_abline(intercept = 0, slope = 1)`, so here I merely suggest a shorthand `geom_idline()`

**Comment by yutannihilation** [comment]
Maybe `geom_abline()` can set the default values of `intercept` and `slope` as such?

**Comment by yutannihilation** [comment]
I think you don't have to write it. Could you provide an example of the cases when `geom_abline()` won't work without providing these arguments?

``` r
library(ggplot2)

d <- data.frame(x = runif(40), y = runif(40))
ggplot(d, aes(x, y)) + geom_point() + geom_abline()
```

![](https://i.imgur.com/Ycb5bdK.png)

<sup>Created on 2022-09-15 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
