### ISSUE TITLE
`coord_sf`: ylabel disappear

### ISSUE THREAD

**Issue by kongdd** [tidyverse/ggplot2#4995]
It seems that `coord_sf` eats `ylabel`. Any idea how to solve this?

system: win10
R: v4.2.1
ggplot2: v3.3.6

```r
library(rnaturalearthdata)
library(sf)
library(ggplot2)

shp = st_as_sf(countries50)

p = ggplot(shp) +
  geom_sf() +
  coord_sf(xlim = c(-180, 180), ylim = c(-60, 90))
p
```
![image](https://user-images.githubusercontent.com/9815742/192083111-34ec65e6-6554-41f8-8128-275d0b9cbfc0.png)

**Comment by yutannihilation** [comment]
I guess this is the same problem as https://github.com/tidyverse/ggplot2/issues/4820, which we found is hard to fix. You need to specify `expand = FALSE` to avoid the issue (by default, `expand` is `TRUE`, so the X axis goes beyond the possible range of `[-180, 180]`).

``` r
library(rnaturalearthdata)
library(sf)
#> Linking to GEOS 3.9.1, GDAL 3.3.2, PROJ 7.2.1; sf_use_s2() is TRUE
library(ggplot2)

shp <- st_as_sf(countries50)

ggplot(shp) +
  geom_sf() +
  coord_sf(xlim = c(-180, 180), ylim = c(-60, 90), expand = FALSE)
```

![](https://i.imgur.com/hJUirHG.png)

<sup>Created on 2022-09-25 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by kongdd** [comment]
Got it. Thank u.
