### ISSUE TITLE
Document code-breaking changes

### ISSUE THREAD

**Issue by aphalo** [tidyverse/ggplot2#4996]
Some changes in 'ggplot2' that may at first sight appear as internal can anyway break code in packages extending 'ggplot2'. Package 'ggpp' was affected by two such changes:

Renaming of class `"mapped_discrete"` as `"ggplot2_mapped_discrete"` (not very recently, I think, but only identified today).
I am using in the code of a position function a call to `inherits()` to detect if a variable is a mapped factor or not. Fix was extremely simple, but finding the cause of the problem took some effort.

Renaming of `size` aesthetic as `linewidth`.           
A case not contemplated in the blog post is that code in an extension package can call panel and group functions defined in 'ggplot2', which means that layer functions in extension packages in such case must be revised to remain usable with the upcoming 'ggplot2' 3.3.7.

I suggest that information these issues potentially affect other extension pacakges is added to the blog post to help those maintaining extension packages.

**Comment by thomasp85** [comment]
Thanks for your message. I am currently in the process of going through all the affected reverse dependencies, which is a process that takes some time. I'll reach out to package maintainers if there is something they need to change well in advance of the next release

**Comment by aphalo** [comment]
Yes, indeed. Some of the changes affect the rendered plots without triggering a failure of CRAN checks, so I try to be pro-active.

**Comment by thomasp85** [comment]
That is much appreciated and any silent "failures" reported will be valued. In some situations changes in ggplot2 can alleviate these

**Comment by teunbrand** [comment]
In the last release, changes to the internals were documented under a separate header. I think we should continue to do this.
