### ISSUE TITLE
Inconsistent behavior for facet_grid and facet_wrap

### ISSUE THREAD

**Issue by steveharoz** [tidyverse/ggplot2#5000]
A function that optionally allows specification of facets with `facet_grid()` works as expected when no facet variables are specified:

```r
foo_row_col <- function(x = NULL) {
    ggplot(mtcars) +
        aes(x = mpg, y = disp) +
        geom_point() +
        facet_grid(rows = NULL, cols = vars({{ x }}))
}
foo_row_col()
```
![image](https://user-images.githubusercontent.com/2257540/192878521-83156aff-0058-4864-bc02-89079a6aa5fd.png)

But if you try to implement a similar function with `facet_wrap()`, you get a weird "(all)" label that isn't expected.

```r
foo_wrap <- function(x = NULL) {
  ggplot(mtcars) +
    aes(x = mpg, y = disp) +
    geom_point() +
    facet_wrap(vars({{ x }}))
}
foo_wrap() # how to get rid of "(all)"?
```

![image](https://user-images.githubusercontent.com/2257540/192878665-5ba7cb81-469e-4b4b-9e4a-74450a47a86b.png)

The [workaround](https://stackoverflow.com/a/73886859/529799) seems to be pretty cumbersome, or at least, it's not consistent with how simply `facet_grid()` works:

```r
foo_wrap <- function(x = NULL) {
  # not exactly readable
  facet_layer <- if (!rlang::quo_is_null(rlang::enquo(x))) facet_wrap(vars({{ x }})) 
  ggplot(mtcars) +
    aes(x = mpg, y = disp) +
    geom_point() +
    facet_layer
}
foo_wrap(cyl)
```

**Comment by yutannihilation** [comment]
I understand your argument to some extent, but I'd say the current behaviour is consistent. In my understanding, the general rule is that a facet has a strip. In `facet_grid()`'s case, it doesn't have a strip for a row or col when there's no variable for the row or col.

**Comment by steveharoz** [comment]
Hmm, but what is the equivalent of "there's no variable for the row or col" with `facet_wrap()`? If it's possible for there to be a call to `facet_grid()` that results in no strip, shouldn't there be some sort of equivalent call for `facet_wrap()`?

**Comment by thomasp85** [comment]
I don't think you should expect these two functions to have parallel behaviour in edge cases. I can understand your reason for wanting that but I don't think it is feasible to change the behaviour now. The underlying reason is, as @yutannihilation pointed out, that `facet_grid()` has the concept of a "catch all" (the `.` in formula notation, or `NULL` using `vars()`), while `facet_wrap()` does not
