### ISSUE TITLE
Dropped cases are taken into account for the dodging of geom_boxplot but not geom_violin

### ISSUE THREAD

**Issue by JacobElder** [tidyverse/ggplot2#5002]
Dropped cases are taken into account for dropped groups are still taken into account for the dodging of geom_boxplot but not geom_violin

The issue is detailed with reproducible code, a diagnosis, and solution from a commenter on StackOverflow. It appears there may be an inconsistency between geom_violinn and geom_boxplot.

https://stackoverflow.com/questions/73900036/boxplot-and-violin-plot-misaligned-in-ggplot2-for-only-one-level-of-the-x-axis/73900343#73900343

**Comment by teunbrand** [comment]
Here is a slightly more minimal reprex:

``` r
library(ggplot2)

df <- data.frame(
  x = factor(rep(1:2, each = 4)),
  y = rep(1:2, 4),
  g = rep(c("A", "A", "B", 'B'), 2)
)

p <- ggplot(df, aes(x, y, fill = g)) +
  geom_violin(position = position_dodge(0.9)) +
  geom_boxplot(position = position_dodge(0.9))

p %+% head(df, -1)
#> Warning: Groups with fewer than two data points have been dropped.
```

![](https://i.imgur.com/BMUfgXz.png)

<sup>Created on 2023-01-04 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
