### ISSUE TITLE
Possible bug in main branch code.

### ISSUE THREAD

**Issue by aphalo** [tidyverse/ggplot2#5003]
This code used to work up to the current CRAN release, but triggers an error with current GitHub code (main branch at [commit](https://github.com/tidyverse/ggplot2/commit/a58b48c961cb391b8646bf072b6620a0c9f3d999)). 

``` r
packageVersion("ggplot2")
#> [1] '3.3.6.9000'
library(ggplot2)
ggplot(mpg, aes(cyl, hwy, colour = factor(cyl))) +
  stat_summary(fun.data = "mean_se")
#> Error in (function (..., row.names = NULL, check.rows = FALSE, check.names = TRUE, : arguments imply differing number of rows: 1, 0
```

<sup>Created on 2022-10-01 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

``` r
packageVersion("ggplot2")
#> [1] '3.3.6'
library(ggplot2)
ggplot(mpg, aes(cyl, hwy, colour = factor(cyl))) +
  stat_summary(fun.data = "mean_se")
```

![](https://i.imgur.com/OJE6sKF.png)

<sup>Created on 2022-10-01 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

This change triggers errors in the documentation of 'gginnards'.

**Comment by teunbrand** [comment]
I think the following comment might be relevant here: https://github.com/tidyverse/ggplot2/pull/4988#issuecomment-1247118328

**Comment by thomasp85** [comment]
Yes, this has been fixed in the release candidate branch. I hope the next release will be out by the end of October

**Comment by yutannihilation** [comment]
Confirmed this is already fixed in the latest CRAN release.

``` r
packageVersion("ggplot2")
#> [1] '3.4.0'
library(ggplot2)
ggplot(mpg, aes(cyl, hwy, colour = factor(cyl))) +
  stat_summary(fun.data = "mean_se")
```

![](https://i.imgur.com/itxNsQJ.png)

<sup>Created on 2022-11-05 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
