### ISSUE TITLE
could geom_contour_filled and geom_density_2d_filled use a colour gradient scale by default?

### ISSUE THREAD

**Issue by davidhodge931** [tidyverse/ggplot2#5005]
This seems inconsistent with the way the rest of ggplot works when a numeric variable is coloured.

```
library(tidyverse)
ggplot(faithful, aes(x = eruptions, y = waiting)) +
  geom_density_2d(aes(col = after_stat(level)))
```
<img width="293" alt="image" src="https://user-images.githubusercontent.com/55065152/193517681-f515a3c2-3539-4faa-86d3-d58bc5644347.png">

```
ggplot(faithful, aes(x = eruptions, y = waiting)) +
  geom_density_2d_filled(aes(fill = after_stat(level)))
```

<img width="306" alt="image" src="https://user-images.githubusercontent.com/55065152/193517820-7d446a70-4ae9-4baa-851f-b8d1d71bd5f0.png">

**Comment by eliocamp** [comment]
In the filled geoms the level aesthetic is an ordered categorical, for which the default scale is the discrete version of viridis.

**Comment by teunbrand** [comment]
I can see why someone might be surprised by this behaviour. In the first case, the level are continuous points on the scale whereas in the second case the fill represents a range of values so the colour scales make sense in these optics. I don't think ggplot2 should make exceptions for specific geoms, dispite this making sense for this particular case. 

If you're interested in wrapping ggplot2 functionality in other functions in a package of your own, you might wrap the `fill` aesthetic in a class that sets a different default scale. For example:

``` r
library(ggplot2)

as_viridis <- function(x) {
  class(x) <- unique.default(c("setviridis", class(x)))
  x
}

scale_type.setviridis <- function(x) "viridis_c"

p <- ggplot(faithful, aes(x = eruptions, y = waiting)) +
  geom_density_2d(aes(col = after_stat(as_viridis(level))))
p
```

![](https://i.imgur.com/iHnulj4.png)

To show that the default scale can still be overridden:

``` r
p + scale_colour_distiller(palette = "Reds")
```

![](https://i.imgur.com/Qzn1joO.png)

<sup>Created on 2023-01-14 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

Despite this being unlikely to change in ggplot2, I would like to thank you anyway for taking care to report the issue with reproducible code!
