### ISSUE TITLE
geom_smooth computation error

### ISSUE THREAD

**Issue by Hugh-Mungo** [tidyverse/ggplot2#5008]
Hi and thanks for a great package!

There is a computation error in geom_smooth: NA/NaN/Inf in foreign function call (arg 3)
This error is only present when trying to plot two specific variables (that have only zero values), and stops a fitted line being plotted for the other variables in the dataframe. 
The other variables are still visable when using geom_point.

Is there anyway to plot these values using geom_smooth anyway?

Thanks,
Hugh

**Comment by aphalo** [comment]
@Hugh-Mungo  Can you provide a reprex? Just a small artificial data set and R code demonstrating the problem? It would make it easier to answer your question. I am almost sure a work-around can be found.

**Comment by yutannihilation** [comment]
This sort of question is a better fit for [RStudio Community](https://community.rstudio.com). Please ask there with a minimal reproducible example. We use this issue tracker for bug reports and feature requests.
