### ISSUE TITLE
Using `after_stat()` in packages extending 'ggplot2'. How to avoid a CRAN check NOTE?

### ISSUE THREAD

**Issue by aphalo** [tidyverse/ggplot2#5012]
I have updated my packages 'ggpp', 'ggpmisc', and 'gginnards' to make them compatible with 'ggplot2' 3.4.0-rc but I am stuck with my package 'ggspectra'. The problem I face appears when replacing `aes_()` with `aes()` used together with `after_stat()` as  `.data` does not seem to work in this case. I have updated the definition of function `decoration()` replacing `aes_()` by `aes()` so that it now works just fine but these edits trigger a NOTE in CRAN check.

```
❯ checking R code for possible problems ... NOTE
  decoration: no visible binding for global variable 'BW.color'
  decoration: no visible binding for global variable 'wb.name'
  decoration: no visible binding for global variable 'y.label'
  Undefined global functions or variables:
    BW.color wb.name y.label

0 errors ✔ | 0 warnings ✔ | 1 note ✖
```

 `decoration()` is an internal function that is called by several `autoplot()` methods defined in package 'ggspectra'. 

I need to protect:
```
aes(color = after_stat(BW.color))
```
when building a `list` of layers returned by function `decoration()`. The retuned list is subsequently added to a ggplot in the code of the different `autoplot()` methods.

I'll apprreciate some help with this. Thanks in advance.

**Comment by teunbrand** [comment]
A typical strategy for this note is declaring global variables in the package, like so:

```{r}
utils::globalVariables(c("BW.color", "wb.name", "y.label"))
```

ggplot2's does the same thing, for example here:

https://github.com/tidyverse/ggplot2/blob/5141ef58442114a40c733a0ab387710c8f9cc1ec/R/labeller.r#L225

**Comment by aphalo** [comment]
Thanks! So, if ggplot2 does this, I guess there is no other cleaner way to get around this problem.
