### ISSUE TITLE
R will be randomly interrupted by signal 11: SIGSEGV in PyCharm 2022.2.2 on M1 Pro Mac

### ISSUE THREAD

**Issue by Enterprise-J** [tidyverse/ggplot2#5014]
R will be randomly terminated when plotting any graph using PyCharm after moving from R 4.1.3 (Intel) to R 4.2.1 (Apple Silicon). Same problem won't happen in RStudio or VSCode.

This issue occurs 7 times in a ten-time trial. I initially encountered with it in package Seurat, but finally the clue points to the ggplot2.

R version 4.2.1 (2022-06-23)
Platform: aarch64-apple-darwin20 (64-bit)
Running under: macOS Ventura 13.0
PyCharm 2022.2.2 (Professional Edition)
ggplot2_3.3.6

```r
library(ggplot2)
data <- data.frame(
  name=c(rep("A",500), rep("B",500), rep("B",500), rep("C",20), rep('D', 100)),
  value=c(rnorm(500, 10, 5), rnorm(500, 13, 1), rnorm(500, 18, 1), rnorm(20, 25, 4), rnorm(100, 12, 1)))
ggplot(data, aes(x=name, y=value, fill=name)) + geom_violin()
```
```
Process was terminated

Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)
```

Thank you,
Jiachen

**Comment by yutannihilation** [comment]
This sounds like a problem related to R's graphics device on PyCharm, so there's probably nothing we can do on ggplot2's side. Maybe you can ask for help on the support forum of PyCharm? We use this issue tracker for bug reports and feature requests, sorry.

**Comment by Enterprise-J** [comment]
> This sounds like a problem related to R's graphics device on PyCharm, so there's probably nothing we can do on ggplot2's side. Maybe you can ask for help on the support forum of PyCharm? We use this issue tracker for bug reports and feature requests, sorry.

Thanks. I reported this to JetBrains earlier.
[https://youtrack.jetbrains.com/issue/R-1453/R-will-be-randomly-interrupted-by-signal-11-SIGSEGV-in-PyCharm-202222-on-M1-Pro-Mac](url)
