### ISSUE TITLE
ggplot2 3.4.0 depends on vctrs 0.5.0

### ISSUE THREAD

**Issue by davidchall** [tidyverse/ggplot2#5019]
While updating my package for ggplot2 3.4.0, I discovered that it relies upon a feature of vctrs 0.5.0. However, this dependency is not yet reflected in the DESCRIPTION.

Specifically, the `vec_rbind0()` function uses the `.error_call` argument of `vctrs::vec_rbind()`.

https://github.com/tidyverse/ggplot2/blob/6425de8ea3ecefc4ddd2b1b6b0ac984501fb2154/R/utilities.r#L705

**Comment by thomasp85** [comment]
Thanks - vctrs is on CRAN now so I'm closing. It was on me to not add the correct temporary version dependency in the release candidate

**Comment by thomasp85** [comment]
it should, yes - that will happen
