### ISSUE TITLE
ggplot can't plot picture in other function

### ISSUE THREAD

**Issue by skyroam** [tidyverse/ggplot2#5020]
In command line, ggplot(...) can plot a picture and show it in Rstudio, but when put the ggplot(...) in  other function such as follows:
```R
test_fun <- function() {
ggplot(...)
}
```
It will not show the plot in Rstudio.
but as shown in following:
```r
plot_f <- ggplot(...)
test_fun <- function(plot_name) {
plot_name
}
test_fun(plot_f)
```
it could plot the image.  why? Is it a bug?

**Comment by smouksassi** [comment]
you need to "print" your plot 
https://stackoverflow.com/questions/46586855/generate-ggplot-and-return-output-from-function-call

please submit these kind of questions to the 
https://community.rstudio.com/
