### ISSUE TITLE
Binned gradient scale with bins labelled

### ISSUE THREAD

**Issue by willgearty** [tidyverse/ggplot2#5021]
I'm trying to use `scale_color_stepsn`, but I'd like to label the bins themselves, not the breaks. Is this possible? Right now I keep getting the following error:
```r
`breaks and `labels` must have the same length
```

Here's an example of what I'd like to do:
```r
ggplot(mtcars, aes(hp, mpg, color = mpg)) +
    geom_point() +
    scale_color_stepsn(colors = terrain.colors(10), breaks = c(15, 20, 25),
                       labels = c("<15", "15 - 20", "20 - 25", ">25"))
```

**Comment by thomasp85** [comment]
This is not possible with binned scales as those are specifically designed to focus on the cut points. However, you can do this by `cut()`ing your colour variable when mapping:

``` r
breaks <- c(-Inf, 15, 20, 25, Inf)
labels <- c("<15", "15 - 20", "20 - 25", ">25")

ggplot(mtcars, aes(hp, mpg, color = cut(mpg, breaks, labels, ordered_result = TRUE))) +
  geom_point() + 
  scale_colour_manual("mpg", values = terrain.colors(5))
```

![](https://i.imgur.com/TGk4jIr.png)
