### ISSUE TITLE
Mismatch linewidth and documentation

### ISSUE THREAD

**Issue by teunbrand** [tidyverse/ggplot2#5022]
Hi ggplot2 team,

The documentation in the aesthetics vignette reads:

https://github.com/tidyverse/ggplot2/blob/a58b48c961cb391b8646bf072b6620a0c9f3d999/vignettes/ggplot2-specs.Rmd#L94

However, I think it isn't really the case. In many line-based geoms, the `linewidth` aesthetic is transformed from millimetres to points using the `.pt` variable. For example in `GeomPath` over here:

https://github.com/tidyverse/ggplot2/blob/a58b48c961cb391b8646bf072b6620a0c9f3d999/R/geom-path.r#L196

When we replicate that step (in grid for simplicity), we can see that the line doesn't reach the desired width.

``` r
library(grid)
library(ggplot2)

# Reference rectangle that is 10 mm wide
ref <- rectGrob(width = unit(10, "mm"), height = 0.6) 

# Line that *should* be 10 mm thick
path_pt <- segmentsGrob(
  x0 = 0.5, x1 = 0.5, y0 = 0.2, y1 = 0.8,
  gp = gpar(lwd = 10 * .pt, col = alpha(3, 0.5))
)

grid.newpage() 
grid.draw(ref)
grid.draw(path_pt)
```

![](https://i.imgur.com/v2nKMnN.png)

Instead, I think the linewidth should be multiplied by `.stroke` to have the documentation match what is outputted on screen.

``` r
# Line that is 10 mm thick
path_stroke <- editGrob(
  path_pt, gp = gpar(lwd = 10 * .stroke, col = alpha(4, 0.5))
)

grid.newpage()
grid.draw(ref)
grid.draw(path_stroke)
```

![](https://i.imgur.com/qDrbpRF.png)

<sup>Created on 2022-10-25 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

While I'm aware that changing linewidths to be multiplied by `.stroke` instead would lead to a bunch of visual changes, I do feel the current documentation / output mismatch is resolvable.

Thanks for considering!

**Comment by teunbrand** [comment]
> My gut tells me to change this at the eleventh hour for this release since we are already messing with lines so much.

Yeah I do realise that the timing of this is a bit unfortunate and wish I noticed this a few months ago.

**Comment by thomasp85** [comment]
ah, well - that is not on you 🙂

**Comment by hadley** [comment]
Yeah, I think it's probably ok to squeeze this in since it mostly shouldn't affect the visual display, and does make everything more consistent.

**Comment by thomasp85** [comment]
This is the new look

``` r
ggplot(airquality) + 
    geom_line(aes(Day, Temp, group = Month))
```

![](https://i.imgur.com/EGgf6HF.png)

vs old

*Local `.Rprofile` detected at `/Users/thomas/Dropbox/GitHub/tidyverse.org/.Rprofile`*

``` r
ggplot(airquality) + 
    geom_line(aes(Day, Temp, group = Month))
```

![](https://i.imgur.com/X3Fvhgm.png)

**Comment by thomasp85** [comment]
There is no denying that it does look a bit more heavy... However, I'm hard pressed to judge whether it is worse than before

**Comment by hadley** [comment]
Regardless of better or worse, it is noticeably different, which I think will cause concern for folks. So it might be better to just fix the documentation.

**Comment by thomasp85** [comment]
yeah, hmm...

>The `linewidth` of a line is _almost_ its width in mm.

**Comment by teunbrand** [comment]
As a compromise, there is also the option to multiply by `.stroke`, but change the default aes of geoms such that they effectively stay the same. That way, the change only affects custom linewidths and not every plot (which might be less of a surprise).

**Comment by hadley** [comment]
I think you could say something like "due to a historical error, the unit of linewidth is ??? mm. Making it exactly 1 mm would change a very large number of existing plots, so we're stuck with this mistake"

**Comment by thomasp85** [comment]
I don't want to go that way as that would lead to some horribly incongruent defaults in themes and geoms

**Comment by clauswilke** [comment]
Yeah, I feel it's better to lock in these historical annoyances rather than routinely tinkering with defaults. If I understand correctly, the unit of linewidth is ~0.75 mm, which is not too bad. It could almost be intentional.

**Comment by hadley** [comment]
"One unit of linewidth obviously equals 0.7528125mm. We leave the straightforward derivation of this constant to the reader."

**Comment by teunbrand** [comment]
A small clarification in the docs sounds good to me. It might also be possible to export a `.mm <- .stroke / .pt` so that the true linewidth afficionados can do `geom_line(linewidth = 1 * .mm)` for example. I could prep a PR if you'd like.

**Comment by hadley** [comment]
I think it would need to be `.linewidth_mm` or something more specific.

**Comment by teunbrand** [comment]
This issue has been dealt with in a38f2eeff779de917bfecae8a29e03e53c55c494
