### ISSUE TITLE
scale_fill_stepsn() colors error 

### ISSUE THREAD

**Issue by user241276** [tidyverse/ggplot2#5024]
I am using `scale_fill_stepsn()` because I would like tailored breaks and colors in my plot.

The problem is that the function does not allocate correctly the colors specified.

Here a sample [dataset](https://www.dropbox.com/s/ad7g65vxtnzt4v1/test.rds?dl=0).

And here my `ggplot2` call:

```
plot_1 = ggplot() +
  geom_tile(data=test, aes(x=lon, y=lat, fill = median)) +
  scale_fill_stepsn(name = "", colors =c("#2171b5", "#6baed6", "#bdd7e7", "#fcae91", "#fb6a4a", "#cb181d"),     
                                breaks = c(-25, -10, 0, 10, 50),
                                values = scales::rescale(c(-25, -10, 0, 10, 50)))

print(plot_1)
```

![Screenshot 2022-10-30 at 11 36 04](https://user-images.githubusercontent.com/31700697/198874227-82626900-63bb-4933-b7e1-db3da3516588.png)

Why the color `#fcae91` is shown as grey instead of as the [following](https://www.colorhexa.com/fcae91) ?

I also opened a question on [StackOverflow](https://stackoverflow.com/questions/74224130/r-scale-fill-stepsn-error-in-breaks-and-colors).

Thanks for any help.

**Comment by karawoo** [comment]
Looks like you got an answer on StackOverflow, which in general is the right place for this type of question, so I'll close the issue here.

**Comment by user241276** [comment]
the answer I got on stackoverflow is not correct unfortunately. good to know about your support
