### ISSUE TITLE
Potential regression with filled areas in ggplot2 3.4.0

### ISSUE THREAD

**Issue by cpsievert** [tidyverse/ggplot2#5026]
I'm not entirely sure if this should be considered a regression, but I noticed this new surprising behavior with `geom_area()` in the 3.4.0 release candidate:

```r
library(ggplot2)

df <- aggregate(price ~ cut + carat, data = diamonds, FUN = length)
names(df)[3] <- "n"
temp <- aggregate(n ~ carat, data = df, FUN = sum)
names(temp)[2] <- "sum.n"
df <- merge(x = df, y = temp, all.x = TRUE)
df$freq <- df$n / df$sum.n
p <- ggplot(data = df, aes(x = carat, y = freq, fill = cut)) + 
  geom_area()
```

![image](https://user-images.githubusercontent.com/1365941/199606680-831cd206-b916-4835-a6f4-61e5edfc500b.png)

Whereas the ggplot2 3.3.6 release yields:

![image](https://user-images.githubusercontent.com/1365941/199606414-20f9ff56-2b90-4d2a-b4bc-d053c541720d.png)

**Comment by teunbrand** [comment]
Just as a potential workaround, the 3.3.6 behaviour can be restored by using `stat = "identity"`.

**Comment by yutannihilation** [comment]
This change is intentional. As of v3.4.0, the default `stat` for `geom_area()` is `align`, one of the major new features in the release. So, as @teunbrand suggested, you can explicitly specify `stat = "identity"`, which was the previous default. That said, we could include some explanation about the breakage like this in the NEWS. Thanks for catching.

In this particular case, I'm not sure if the latter plot is the correct one, btw (e.g. is it right that the range from around 3.5 to 4.0 is drawn 100% "Premium"?)

**Comment by roelvanklink** [comment]
Thanks, this was bugging me for two weeks. A warning message in the help or in the code might also be helpful. 
Here's what i got before adding 'stat = "identity"': 
![image](https://user-images.githubusercontent.com/34058915/203728012-ff37e4e4-4022-4166-8fd9-1441e170872c.png)

**Comment by yutannihilation** [comment]
@roelvanklink 
I think your one is different problem; what you need is `position = "identity"`. By default, the areas stack, and the only reason you could accidentally get the unstacked result is your data didn't contain the same X values by chance. But, I sympathize with your surprise.

**Comment by teunbrand** [comment]
Perhaps we can simply add an example to the `geom_area()` docs on how to turn off the alignment?

From the existing example:

```r
df <- data.frame(
  g = c("a", "a", "a", "b", "b", "b"),
  x = c(1, 3, 5, 2, 4, 6),
  y = c(2, 5, 1, 3, 6, 7)
)
a <- ggplot(df, aes(x, y, fill = g)) +
  geom_area()

# Two groups have points on different X values.
a + geom_point(size = 8) + facet_grid(g ~ .)

# stat_align() interpolates and aligns the value so that the areas can stack
# properly.
a + geom_point(stat = "align", position = "stack", size = 8)
```

We might add:

```r
# To turn off this alignment, the stat can be set to "identity"
ggplot(df, aes(x, y, fill = g)) + geom_area(stat = "identity")
```

**Comment by yutannihilation** [comment]
Sounds good to me!

**Comment by thomasp85** [comment]
same - an example and perhaps a note in the docs should be sufficient
