### ISSUE TITLE
geom_bar plotting depends on the order of the data 

### ISSUE THREAD

**Issue by roi-meir** [tidyverse/ggplot2#5027]
Hi, 

I encountered an expected behaviour when using `geom_bar` in a stack mode. 
I'm trying to plot a columns graph with a proportion of each type for each sample. 
For some reason the order of the rows of the data frame matter.

I'm attaching a reprex that create a random proportions and then plot the data frame twice.
Once ordered by the proportion of one of the type in an increasing manner and another plot ordered in a decreasing manner. 

```r
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
library(ggplot2)
library(cowplot)

k <-  3
n <- 1000
set.seed(2)
types <-  c("1", "2", "3")
prop <-  matrix(runif(n*k), nrow = n)
prop <- t(apply(prop, 1, function(x)(x/sum(x))))
prop <- prop[order(prop[,1]),]
data <- data.frame(sample = rep(1:n, times = k), type = rep(factor(types), 
                                                            each = n), prop = c(prop))
lapply(c(rev, identity), function(f)  {
  data <- data[f(rownames(data)),]
  ggplot(data, aes(sample, prop, color=type, fill=type)) + 
    geom_bar(stat="identity") + 
    theme(axis.text.x = element_blank())
}) %>% plot_grid(plotlist = .,  ncol=2)
```

![](https://i.imgur.com/dAszQ1G.png)

<sup>Created on 2022-11-03 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by teunbrand** [comment]
This seems like a overplotting/drawing order issue. Because you've specified a 'colour' aesthetic, the strokes on top overlap the fills on the bottom. If you remove `colour = type` or set `n = 10`,  the plots should look similar.

**Comment by yutannihilation** [comment]
This sort of question is a better fit for [RStudio Community](https://community.rstudio.com). Please ask there with a minimal reproducible example. We use this issue tracker for bug reports and feature requests.
