### ISSUE TITLE
hexbin is broken

### ISSUE THREAD

**Issue by mgrabovsky** [tidyverse/ggplot2#5037]
It looks like since at least the latest release (3.4.0) `geom_hex` is broken in some way. For an example, see [the documentation](https://ggplot2.tidyverse.org/reference/geom_hex.html#ref-examples):

![image](https://user-images.githubusercontent.com/134321/200396468-482dfbb4-5675-46ab-a743-c6c018c2c798.png)

(Current state on left, expected output on the right.)

**Comment by yutannihilation** [comment]
Thanks, confirmed. I'm yet to figure out what's happening here, but it seems https://github.com/tidyverse/ggplot2/pull/4671 makes this difference.

**Comment by micans** [comment]
I experienced the same, with very large artefacts -- high density called where density is in fact very low for my actual data of interest.

Applying geom_hex to a simple uniform object shows big differences between version 3.4.0 and 3.3.5:

```
v <- expand.grid(1:100,1:100)
myscale2 <- scale_fill_gradientn(name = "count",
              trans = "log",
                values=c(0.0,0.4,0.6,0.8,1.0),
                  colors=c("darkblue", "lightblue", "yellow", "orange", "red"),
                    breaks=c(2,4,8,16), labels=c(2,4,8,16))
mybins <- 20
pdf("ggplot340sq100bin20hex.pdf")
ggplot(v, aes(Var1,Var2)) + ggplot2::geom_hex(bins=mybins) + myscale2 + ggtitle("hex")
dev.off()
```

yields

<img width="570" alt="Screenshot 2022-11-23 at 14 12 37" src="https://user-images.githubusercontent.com/3369968/203568210-2a84ca2e-b5f6-4995-ab51-6af047115944.png">

Whereas for version 335 this gives

<img width="570" alt="Screenshot 2022-11-23 at 14 13 18" src="https://user-images.githubusercontent.com/3369968/203568357-338815cc-6af9-49f7-a0c4-1ac0991a5fa7.png">
