### ISSUE TITLE
Weird behavior of stat_summary_bin when there are multiple aesthetics and when specifying number of bins

### ISSUE THREAD

**Issue by cchikis** [tidyverse/ggplot2#5038]
I am trying to generate binscatter plots with a best fit line using stat_summary_bin and geom_smooth, respectively, where I am specifying color and shape aesthetics for two separate series I am plotting. When I specify I want 20 bins, I get fewer than 20 bins for the series with less coverage over the x-axis (this is not specific to 20, by the way, but for any fixed number of bins that I specify). 

If I plot the two aesthetics separately, I get 20 + 1 bins for each, as expected. 

My expectation is that each series in p1 should have 20 bins. Instead one has 11, and the other has the full 21.

Nothing special about geom_smooth, by the way. This was my original use case, but I commented it out for clarity. 

```r
library(tidyverse)
set.seed(123)
df = tibble(e = c(rnorm(1e4), rnorm(1e4)),
            X = c(runif(1e4, 1, 100), 0.5*runif(1e4, 1, 100)),
            label = c(rep("series1", 1e4), rep("series2", 1e4)),
            Y = X + e)
p1 = ggplot(data = df, mapping = aes(y = Y, x = X, color = label, shape = label)) + 
    # geom_smooth(se = FALSE) + 
    stat_summary_bin(bins = 20, fun = "mean")

p2 = ggplot(data = df %>% filter(label == "series1"), mapping = aes(y = Y, x = X, color = label, shape = label)) + 
    # geom_smooth(se = FALSE) + 
    stat_summary_bin(bins = 20, fun = "mean")

p3 = ggplot(data = df %>% filter(label == "series2"), mapping = aes(y = Y, x = X, color = label, shape = label)) + 
   #  geom_smooth(se = FALSE) + 
    stat_summary_bin(bins = 20, fun = "mean")

```

**Comment by yutannihilation** [comment]
The rendered version here.

> My expectation is that each series in p1 should have 20 bins.

Shouldn't the bins be shared between series 1 and series 2...? Otherwise, you cannot compare them. This might not fit your use case, but I think this is what it is.

``` r
library(tidyverse)
set.seed(123)
df <- tibble(e = c(rnorm(1e4), rnorm(1e4)),
             X = c(runif(1e4, 1, 100), 0.5*runif(1e4, 1, 100)),
             label = c(rep("series1", 1e4), rep("series2", 1e4)),
             Y = X + e)
p <- ggplot(data = df, mapping = aes(y = Y, x = X, color = label, shape = label))

p + stat_summary_bin(bins = 20, fun = "mean")
#> Warning: Removed 32 rows containing missing values (`geom_segment()`).
```

![](https://i.imgur.com/aLGAOLb.png)

``` r
p + stat_summary_bin(bins = 20, fun = "mean", data = \(x) filter(x, label == "series1"))
#> Warning: Removed 21 rows containing missing values (`geom_segment()`).
```

![](https://i.imgur.com/b6bFy3t.png)

``` r
p + stat_summary_bin(bins = 20, fun = "mean", data = \(x) filter(x, label == "series2"))
#> Warning: Removed 21 rows containing missing values (`geom_segment()`).
```

![](https://i.imgur.com/v2dbnvV.png)

<sup>Created on 2022-11-13 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
