### ISSUE TITLE
Some docs for ... argument still refer to size rather than linewidth

### ISSUE THREAD

**Issue by gregrs-uk** [tidyverse/ggplot2#5040]
The documentation for functions such as `geom_line` describes the parameter `...` as follows (my emphasis):

> Other arguments passed on to [layer()]. These are often aesthetics, used to set an aesthetic to a fixed value, like `colour = "red"` or **`size = 3`**. They may also be parameters to the paired geom/stat.

Now that the `linetype` aesthetic has replaced `size` for `geom_line` and others, this might be slightly misleading (although the relevant aesthetics are listed under the 'Aesthetics' heading). Might it be better to remove the reference to `size = 3`, for example?

This parameter's documentation seems to be inherited from the `geom_point` documentation using `@inheritParams geom_point`.

**Comment by yutannihilation** [comment]
`size = 3` is just an example of tens of possibly-available aesthetics; it doesn't imply all Geoms have `size` aesthetic. So, I feel this is okay.

**Comment by gregrs-uk** [comment]
To those familiar with ggplot it makes sense, especially when you know that it's common to other `geom_*` functions. (A more experienced user would check the list of aesthetics for a particular geom.)

However, I do feel that mentioning the `size` aesthetic in the documentation for `geom_line` (as an example) does somewhat imply it's relevant to this geom.

Removing the `size` example and just keeping `colour` would presumably allow it to apply to the vast majority of geom functions which inherit this parameter.
