### ISSUE TITLE
Should x or y infinite values be filtered out rather than plotted at the max of the panel?

### ISSUE THREAD

**Issue by davidhodge931** [tidyverse/ggplot2#5042]
I am wondering if it is misleading to plot infinite values as the max of the panel, and whether it'd be more accurate to just filter them out of the plot?

```
library(tidyverse)
tibble(x = 0:10, y = 1:11) %>% 
  mutate(z = y / x) %>%
  mutate(infinite = is.infinite(z)) %>% 
  ggplot() +
  geom_point(aes(x, z, col = infinite)) +
  coord_cartesian(clip = "off")
```
<img width="364" alt="image" src="https://user-images.githubusercontent.com/55065152/201062493-3aaa4a86-6dc6-46b3-ad7e-99e4116e7778.png">

**Comment by teunbrand** [comment]
It's the default behaviour of `scales::oob_censor()` that is the default out-of-bounds handling method of continuous scales. You can change `scale_y_continuous(oob = scales::oob_censor_any)` to filter out the infinites. I don't think changing the default `oob` argument makes sense in terms of backward compatibility. Some people (myself included) often use `x = Inf, y = Inf` to place text in a corner of the plot, for example.

**Comment by yutannihilation** [comment]
I agree with @teunbrand. In ggplot2, infinite is a special value to represent the edge of the plot, not outside of the range. I too don't think we can change the behavior.

**Comment by davidhodge931** [comment]
What about just converting infinite values in aesthetics to NAs, @yutannihilation ?

**Comment by yutannihilation** [comment]
I understand there are definitely the cases where the user want to treat infinite values as the outside of the range, instead of the edge of the range. But, it's probably impossible to guess the user's intention automatically. 

`scale_y_continuous(oob = scales::oob_censor_any)` should be the easiest solution.
