### ISSUE TITLE
Parsing plotmath() strings with punctuation (':')

### ISSUE THREAD

**Issue by wrpearson** [tidyverse/ggplot2#5043]
---
Parsing of plotmath() strings in facet labeling is "broken" if there is a ":" in the string (it is broken for other punctuation characters as well).  The script below works as expected, putting **BOLD** and == math characters in the facet title.    But inclusion of a punctuation character produces an error.  Perhaps plotmath() could be documented to only work with alphanumeric characters and math symbols (which constrains what can be put in a facet title).
```r

library(ggplot2)

f_vals = c(0.5, 0.8, 1.2, 1.5)
labs = c("A","B","C","D")

all_data=NULL

for (ix in 1:length(f_vals)) {
    dat <- data.frame(x=rnorm(20,mean=0,sd=f_vals[ix]), facet=f_vals[ix])
    all_data <- rbind(all_data,dat)
}

## the colon causes an error, with or without ~ instead of space
## f_labs = sprintf("bold(%s)~~~the~sd: ==~%.2f",labs, f_vals)

f_labs = sprintf("bold(%s)~~~the~sd ==~%.2f",labs, f_vals)
names(f_labs) = f_vals

facet_labeller = as_labeller(f_labs, label_parsed)

ggplot(all_data, aes(x, x)) +
  geom_point() +
  theme(strip.text=element_text(hjust=0)) +
  facet_wrap(~facet, labeller = facet_labeller)

```
Including a ':' produces an error message:
```
Error in parse(text = as.character(values)) : 
  <text>:1:19: unexpected '=='
1: bold(A)~~~the~sd: ==
                     ^
Calls: <Anonymous> ... labeller -> default -> lapply -> FUN -> FUN -> parse
Execution halted
```

**Comment by yutannihilation** [comment]
`plotmath()` comes from the base R (the grDevices package). I'm not familiar with proposing a documentation improvement to the R core team, but the resources on [R Contribution Working Group](https://contributor.r-project.org/working-group) might help. Probably you can ask on their Slack channel. Wish you luck!
