### ISSUE TITLE
can't make line within line plot in ggplot

### ISSUE THREAD

**Issue by adiperdana23** [tidyverse/ggplot2#5046]
Hello I can't draw a line on line plot with tooltip, thank [you](URL), but when I make without tooltip, the line could be shown

wsdm_for_registration <-readRDS("wsdm_for_registration.RDS")

wsdm_for_registration_plotly <- wsdm_for_registration  %>%
  head(14) %>%
  ggplot( aes(x=year_registration, y=number.of.subscriber,text=paste0("years :" ,year_registration,"<br>",
                                                                      "number of subscriber: ", scales::comma(`number.of.subscriber`, 1)))) +
  geom_line() +
  geom_point(color="#69b3a2", size=4) +
  scale_y_continuous(labels = scales::comma)  +
  ggtitle("Subscriber Growth year to year") +
  ylab("number of subscriber") +
  theme_ipsum()

ggplotly(wsdm_for_registration_plotly, tooltip = "text")

[http://localhost:17303/session/extra-bass_reprex_preview.html](url)

**Comment by clauswilke** [comment]
This question does not seem appropriate for the ggplot2 issue tracker. You could try the RStudio Community (https://community.rstudio.com/) or stackoverflow.
