### ISSUE TITLE
Would `scale_linewidth_discrete()` be developed to set values manually like other `scale_size_manual()`

### ISSUE THREAD

**Issue by ZhangSR-kolar** [tidyverse/ggplot2#5050]
Hi~

I'd like to ask, would the `scale_linewidth()` be developed to `scale_linewidth_manual()`, so that I can set the specific value to different levels when I use a factor variable to constrain linewidth, just as `scale_size_manual()`? 

Thanks!

**Comment by MatthewHeun** [comment]
> ```r
> ```r
> library(tidyverse)
> 
> data.frame(x = 1:10, y = 11:20, which = c(rep("a", 5), rep("b", 5))) %>% 
>   ggplot() + 
>   geom_line(aes(x, y, colour = which, linewidth = which)) + 
>   scale_discrete_manual(aesthetic = "linewidth", values = c(a = 0.5, b = 5))
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> 
> Created on 2022-11-20 by the reprex package (v2.0.1)
> Note that I'm generally in favor of having manual scales for all aesthetics. When I wanted to add some a few years ago it was vetoed and the accepted solution was scale_discrete_manual().
> ```

This worked. I was unaware of `scale_discrete_manual()`. Thanks!

**Comment by teunbrand** [comment]
> Note that I'm generally in favor of having manual scales for all aesthetics.

I agree that that would make sense, but I can't find the counterarguments. I've seen a few times on SO that people were expected `scale_linewidth_manual()` to exists.

**Comment by teunbrand** [comment]
In addition, `scale_linewidth_identity()` also doesn't exist.

**Comment by clauswilke** [comment]
@teunbrand This is the relevant discussion:
https://github.com/tidyverse/ggplot2/pull/2555#discussion_r187195653

I think it was mostly a "let's defer this decision" rather than "let's not do this". It's probably time to revisit this.

**Comment by thomasp85** [comment]
Both `scale_linewidth_manual()` and `scale_linewidth_identity()` has been omitted in error and should be added

**Comment by MatthewHeun** [comment]
> Both `scale_linewidth_manual()` and `scale_linewidth_identity()` has been omitted in error and should be added

Thanks! That will be a big help to everyone.
