### ISSUE TITLE
Using `lwd` parameter in geom_line() produces `size` warning

### ISSUE THREAD

**Issue by sarmapar** [tidyverse/ggplot2#5051]
I recently updated ggplot and found I am getting the "Using `size` aesthetic for lines was deprecated in ggplot2 3.4.0." warning for my lines of code where I use the `lwd` parameter. Is `lwd` also being deprecated? I think a more clear/informative warning would be helpful, because it took me a while to find the source since I didn't explicitly use `size` anywhere. 

Simplified example that produces the warning:

```r
library(ggplot2)

ggplot(economics, aes(date, unemploy)) + 
   geom_line(lwd = 0.25)

```

**Comment by clauswilke** [comment]
Good point. I think it's an oversight, `lwd` should be mapped onto the new `linewidth` aesthetic, and not onto `size`. This happens here:
https://github.com/tidyverse/ggplot2/blob/759c63c2fd9e00ba3322c1b74b227f63c98d2e06/R/ggplot-global.R#L37

In general, though, I think it's better to not use these base-R terms at all but rather use the correct ggplot2 aesthetic.

**Comment by thomasp85** [comment]
Agree with @clauswilke on all accounts. This was an oversight by me
