### ISSUE TITLE
Add simple function for plotting histograms when `qplot` will be deprecated

### ISSUE THREAD

**Issue by frederikziebell** [tidyverse/ggplot2#5055]
Using `qplot()`, plotting a histogram of a numeric vector, say
```r
x <- rnorm(1000)
```
can be simply done via
```r
qplot(x)
```
Without it, the two shortest solutions I know,
```r
ggplot() + aes(x) + geom_histogram()
```
or
```r
tibble(x = x) %>%
  ggplot(aes(x)) +
    geom_histogram()
```
are both more than three times longer. When `qplot` will be deprecated in ggplot2 3.4.0, please add a function to easily plot histograms, e.g.

```r
gghist <- function(x) {
  tibble(x = x) %>%
    ggplot(aes(x)) +
      geom_histogram()
}
```

**Comment by clauswilke** [comment]
I don't think this belongs into the ggplot2 package. Anybody can define such a function and put it into their convenience package of choice.

Having said that, I'm not even convinced of the argument for such a function, though. If you're after efficiency, `hist(x)` is even shorter and doesn't require you to load any library.

**Comment by yutannihilation** [comment]
I totally agree with @clauswilke. I don't deny such a function can be useful for some use cases, I believe it will never be added to the ggplot2 package itself.

**Comment by frederikziebell** [comment]
FWIW, I created [gghist](https://github.com/frederikziebell/gghist) for that purpose.
