### ISSUE TITLE
Factor levels in legend, if a level is dropped because of NA values

### ISSUE THREAD

**Issue by stamats** [tidyverse/ggplot2#5057]
I use R 4.2.2 Patched (2022-11-12 r83339), ggplot2 version 3.4.0 (2022-11-04)

There seems to be an issue with the legend, if a factor level is "empty" due to NA values. 

In the first example below the level is "shown" in the plot, but not in the legend.

In the second example below the level is "shown" in the plot and in the legend, but the levels are reordered in the legend (no longer in the original order).

Best Matthias
``` r
library(ggplot2)

## some dummy data
DF <- data.frame(y = c(rnorm(20), NA),
                 group = factor(c(rep(c("a","b"), each = 10), "c"),
                                levels = c("c", "b", "a")))

## label c does not appear in the legend
ggplot(DF, aes(x = group, y = y, fill = group)) +
  geom_boxplot()
#> Warning: Removed 1 rows containing non-finite values (`stat_boxplot()`).
```

![](https://i.imgur.com/PxrPyYK.png)

``` r

## levels are reordered in the legend
ggplot(DF, aes(x = group, y = y, fill = group)) +
  geom_boxplot() + geom_jitter(height = 0, width = 0.1, alpha = 0.4)
#> Warning: Removed 1 rows containing non-finite values (`stat_boxplot()`).
#> Warning: Removed 1 rows containing missing values (`geom_point()`).
```

![](https://i.imgur.com/oKHxvcn.png)

<sup>Created on 2022-11-24 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by teunbrand** [comment]
This is likely because non-position scales are trained after applying the stat-transformation. In the first plot, the boxplot drops the `NA` observation, causing the scale to never 'see' the 'c' level. In the second plot, the scale observes the 'c' level because the identity stat of `geom_jitter()` doesn't drop the `NA` observation (that happens later in the build process). What would be the expected outcome here?

**Comment by stamats** [comment]
First of all, my preference would be to keep category c in the data, i.e. show all categories of a factor. Then, I would say, if the plot shows c, then the legend should also show c (first plot). Furthermore, the legend should not reorder the levels of a factor (second plot).
Just my 2 cents ...

**Comment by yutannihilation** [comment]
> keep category c in the data

You can specify `scale_fill_discrete(drop = FALSE)`

``` r
library(ggplot2)

DF <- data.frame(y = c(rnorm(20), NA),
                 group = factor(c(rep(c("a","b"), each = 10), "c"),
                                levels = c("c", "b", "a")))

ggplot(DF, aes(x = group, y = y, fill = group)) +
  geom_boxplot() +
  scale_fill_discrete(drop = FALSE)
#> Warning: Removed 1 rows containing non-finite values (`stat_boxplot()`).
```

![](https://i.imgur.com/VhGZ7i0.png)

<sup>Created on 2022-12-11 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by teunbrand** [comment]
There have been some changes in {scales} that make factor levels more stable. Aside from that, I think the `drop = FALSE` suggestion is the way to go, and you could include `show.legend = TRUE` to include a glyph for the unobserved level.
