### ISSUE TITLE
facet histogram

### ISSUE THREAD

**Issue by tanipapazisi** [tidyverse/ggplot2#5060]
I am trying to get a chart using facet wrap for a set a histograms created within ggplot2 functions.

I can create only in "counts" and I don't find a way to do frequency per each group/histogram.

Is any code sb can help?

**Comment by yutannihilation** [comment]
Hi, this sort of question is a better fit for [RStudio Community](https://community.rstudio.com). Please ask there with a minimal reproducible example. We use this issue tracker for bug reports and feature requests. Thanks!
