### ISSUE TITLE
scale_color_manual, legend Error when specifying both `values=vec` and `labels=names(vec)` for named vector of colors

### ISSUE THREAD

**Issue by dan11mcguire** [tidyverse/ggplot2#5070]
Before recently updating ggplot2, I am able to specify a named vector of colors in `scale_color_manual`.  For my own comfort, I usually say

`scale_color_manual(values=cols,labels=names(cols))`

This no longer sets the correct values in the legend. 
Please see the legend difference in small reprex below

```r
library(data.table)
library(ggplot2)
set.seed(123)
n <- 1000
plot_d <- data.table(lets = letters[1:4], x_mn = 1:4, y_mn = 1:4)
plot_d <- plot_d[,.(x=rnorm(100,x_mn),y=rnorm(100,y_mn)),by=.(lets,x_mn,y_mn)]
cols <- c("red", "yellow", "blue", "brown")
names(cols) <- c("d", "c", "a", "b")
basep <- 
ggplot(plot_d, aes(x, y, color=lets)) + 
  geom_point()  
basep + 
  scale_color_manual(values=cols) + labs(title = "correct")## works

basep + 
  scale_color_manual(values=cols,labels=names(cols)) + labs(title = "wrong")## DOESNT WORK!! 
```

![image](https://user-images.githubusercontent.com/49620432/204892232-589cf2e0-09d4-41c0-82da-dcae8e2f8502.png)

![image](https://user-images.githubusercontent.com/49620432/204892171-df20da2b-2378-485d-b6ac-5af484d59bfb.png)

**Comment by dan11mcguire** [comment]
It looks like the color vector is sorted according to the order of 
`lets`.  But the the labels are not sorted

**Comment by clauswilke** [comment]
I don't really understand what you're trying to achieve with `labels=names(cols)`, so I'm not sure what exactly your concern is. In your example, `labels=names(cols)` doesn't achieve anything useful, and the code without it works. So why would you ever add it?

In general, I will say that it is dangerous to set labels without also explicitly setting breaks. You should never assume that the breaks are going to be in any specific order.

**Comment by clauswilke** [comment]
In fact, thinking some more about it, the breaks are exactly in the right order (alphabetic, which is the default if not set explicitly) and you're just mislabeling them. The code works exactly as it should.

**Comment by dan11mcguire** [comment]
thanks @clauswilke .  I had been confusing 'values' with 'breaks'.
