### ISSUE TITLE
ggplot2 error 

### ISSUE THREAD

**Issue by xin77yuu** [tidyverse/ggplot2#5073]
mtcars %>% 
  rownames_to_column("type") %>% 
  gather(var, val, -type) %>% 
		ggplot(aes(x = type ,y = val)) +
	geom_point() +
	geom_line() +
		facet_wrap(~ var, scales = "free") 

error message: 
**Error in sanitise_dim(nrow) : could not find function "sanitise_dim"**

**Comment by teunbrand** [comment]
I'm unable to reproduce this with ggplot2 3.4.0. What version of ggplot2 gave you this error? It seems like your code calls a function that was recently-ish removed (`sanitise_dim()`).

**Comment by xin77yuu** [comment]
I uninstalled ggplot2 and reinstalled; now it works. 
thanks you!
