### ISSUE TITLE
geom_hex bug introduced by the latest 3.4.0 release

### ISSUE THREAD

**Issue by mikejiang** [tidyverse/ggplot2#5076]
```
d <- ggplot(diamonds, aes(carat, price))
d + geom_hex()
```
Here is the plot before
![image](https://user-images.githubusercontent.com/1385649/205223879-8c2a404c-977f-4b86-ac59-7d435321bea3.png)
Here is to plot now, apparently something is wrong
![image](https://user-images.githubusercontent.com/1385649/205223958-b1d724e5-c77b-4735-84cf-0e3e7abb6b19.png)

**Comment by mikejiang** [comment]
It's affecting the downstream package that depends on ggplot

here is before 3.4
![image](https://user-images.githubusercontent.com/1385649/205224690-34b2ba68-4f6a-4944-911f-f5b6ba382bef.png)

Here is after
![image](https://user-images.githubusercontent.com/1385649/205224786-960055c9-dbbc-4ef3-b816-68cdea50cd47.png)

**Comment by teunbrand** [comment]
This is a regression in ggplot2 3.4.0 which has been reported as well in #5037 and #5044. A fix has been proposed in #5045.

**Comment by mikejiang** [comment]
Good to know, thank you!
