### ISSUE TITLE
Feature request: support sixel and/or iTerm2 graphics protocol for terminal inline charts

### ISSUE THREAD

**Issue by lucabol** [tidyverse/ggplot2#5084]
It might be an R feature request, not ggplot2 specific, but I'm not sure where to log those.

Newer terminals support inline image displays with 3 protocols (at least): [Sixel](https://en.wikipedia.org/wiki/Sixel), [iTerm2](https://iterm2.com/documentation-images.html) or [Kitty](https://sw.kovidgoyal.net/kitty/graphics-protocol/).

The only way I have found to print inline charts with ggplo2 is through my function below (btw for R wizards: is there a way to simplify the calling site??).

```r
# Plot to console by saving the plot as image file and displaying using the 'display' utility
# Needs the terminal to support the xterm image protocol, could be changed to use img2six for sixels
pl <- function(aplot = last_plot()) {
  sink(nullfile())
  filename <- "___aplot___.png"
  suppressMessages(ggsave(filename = filename, plot = aplot))
  system(paste("display -r -W 90% -H 90% ", filename))
  file.remove(filename)
  sink()
}
```

Called as:
```r
(ggplot(gl,aes(weight)) + geom_density()) |> pl()
```

**Comment by yutannihilation** [comment]
Interesting, but this isn't the function that ggplot2 can provide. You need a graphics device that translates the low-level drawing instructions into the graphics protocols. If you have no idea what a graphics device is, the documents of this package might be helpful: https://coolbutuseless.github.io/package/devout/.

**Comment by lucabol** [comment]
For those stumbling on this issue, this code in my `Rprofile` seems to do the trick. I am an R novice, so YMMV. The main thing is that you can override `print.ggplot` to do whatever you wish.

```R
# Plot to console by saving the plot as image file and displaying using the 'display' utility
# Needs the terminal to support the xterm image protocol, could be changed to use img2six for sixels
inlinePlot <- function(aplot = last_plot()) {
  sink(nullfile())
  filename <- "___aplot___.png"
  suppressMessages(ggsave(filename = filename, plot = aplot))
  system(paste("display -r -W 90% -H 90% ", filename))
  file.remove(filename)
  sink()
}

plotInline <- function() {
  .GlobalEnv$print.ggplot <- inlinePlot
}

plotPopup <- function() {
  if(exists("print.ggplot")) {
    remove("print.ggplot", pos = ".GlobalEnv")
  }
}

plotInline()
```
