### ISSUE TITLE
Different log coordinate transforms are not producing different scales on axes

### ISSUE THREAD

**Issue by toddyoder** [tidyverse/ggplot2#5089]
`coord_trans` with different log transformations gives plots that look identical.
```r
library(ggplot2)
library(patchwork)

p10 <- ggplot(diamonds, aes(carat, price)) +
  geom_point() +
  coord_trans(x = "log10", y = "log10")

p2 <- ggplot(diamonds, aes(carat, price)) +
  geom_point() +
  coord_trans(x = "log2", y = "log2")

p10 + p2
```
![Screenshot 2022-12-05 at 10 28 26 PM](https://user-images.githubusercontent.com/40072046/205805976-1d984406-7279-4e56-9ae5-ccb757c591ad.png)

**Comment by teunbrand** [comment]
Isn't that what one would expect? It shouldn't really matter what base the log has for how the points end up being displayed in the plot. 

``` r
library(scales)

x <- 10^seq(1, 10)

all.equal(
  rescale(log10(x)),
  rescale(log2(x))
)
#> [1] TRUE
```

<sup>Created on 2022-12-06 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
