### ISSUE TITLE
The 'right' option on scale_x_binned works opposite to that in the docs

### ISSUE THREAD

**Issue by danatemple** [tidyverse/ggplot2#5094]
I am using geom_bar() and scale_x_binned() to make a histogram with the ticks between the bars. 

R 3.6.2, ggplot2 3.3.5. Reproduced on R4.2.2 ggplot2 3.4.0 in this [SO case](https://stackoverflow.com/questions/74715943/r-histogram-scale-x-binned-gets-an-empty-last-bin-and-right-option-appears).

I tried the 'right' option [in the docs](https://ggplot2.tidyverse.org/reference/scale_binned.html) that allows you to choose whether a value on the border between bins goes in the left or right bins. But it appears to be working with inverse logic from expected, which is also odd.

```r
rm(list=ls())
library(ggplot2)
library(Hmisc, warn.conflicts = FALSE)

Time = c(17, 14, 21, 19, 18, 24, 25, 14, 17, 19, 20, 17, 21, 20, 23, 27, 25, 25, 27, 29, 24, 22, 26, 29)

# Note there are the following counts:
# 14: 2, 15: 0, 16: 0, 17: 3, 18: 1, 19: 2 ... 
#
# The 16-18 bin should either get 3 or 4 depending on where the '18' lands.

data = data.frame(Time)

ggplot(data, aes(x = Time))+
geom_bar()+
scale_x_binned(right = TRUE, show.limits = TRUE)
```

But with right = TRUE (as above) the 16-18 bin gets a count of 4. That seems wrong - the 18 should have fallen in the 18-20 bin?

Problem in https://ggplot2.tidyverse.org/reference/scale_binned.html ?

**Comment by teunbrand** [comment]
Is this the same issue as #5092?

**Comment by danatemple** [comment]
@teunbrand yes sorry, we had a SO case and I hadn't seen the responder had opened an issue. This is a duplicate!

**Comment by danatemple** [comment]
Duplicate of #5092
