### ISSUE TITLE
`stat_summary_hex()` brings values or bins out of order

### ISSUE THREAD

**Issue by aricht** [tidyverse/ggplot2#5101]
Hi all,
plotting with `stat_summary_hex()` the resulting plot does not look as expected and seems to not represent the underlying data. The difference to a plot generated with `stat_summary_2d()` is striking, when I would expect them to look very similar.
I observed this problem in `ggplot2_3.4.0` but not `ggplot2_3.3.5`.

The problem can be seen on the example data:
```r
library(ggplot2)
d <- ggplot(diamonds, aes(carat, depth, z = price))

d + stat_summary_2d()

d + stat_summary_hex()
```
Thanks a lot in advance for looking into this!

![Screenshot 2022-12-09 at 15 39 41](https://user-images.githubusercontent.com/38692323/206726496-82a23e06-d1b2-4743-9b4f-2cdf1406ff8c.png)
![Screenshot 2022-12-09 at 15 39 15](https://user-images.githubusercontent.com/38692323/206726500-27a949d5-b780-4648-b461-3892b5358ee3.png)

**Comment by yutannihilation** [comment]
Thanks for reporting, this is already fixed in the dev version (#5045).

``` r
library(ggplot2)

d <- ggplot(diamonds, aes(carat, depth, z = price))

d + stat_summary_2d()
```

![](https://i.imgur.com/HtYcOVw.png)

``` r

d + stat_summary_hex()
```

![](https://i.imgur.com/ZxmGCVC.png)

<sup>Created on 2022-12-10 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
