### ISSUE TITLE
set_linewidth_manual does not exist

### ISSUE THREAD

**Issue by tkpmep** [tidyverse/ggplot2#5102]
---

Following the guidance given by a warning message, I changed `size` to `linewidth` in an existing ggplot, expecting that `scale_size_manual` would translate to `scale_linewidth_manual`. Unfortunately, it appears that `scale_linewidth_manual` does not exist in ggplot2 3.4 (though a number of other scale_linewidths can be found on page 247 of the manual, and I finally reverted to  `scale_size_manual`. Is `scale_linewidth_manual` something that will be added soon, and will  `scale_size_manual`  be replaced?

**Comment by teunbrand** [comment]
This seems to be very much related to #5050

**Comment by tkpmep** [comment]
Indeed it is, as was pointed out to me by a responder to my question on StackExchange. Not clear why, but #5050 did not show up in all the Google searches I ran. Thank you very much for your prompt response. I will use scale_discrete_manual going forward (I had no idea that scale_linewidth_manual had been both suggested and vetoed!)
