### ISSUE TITLE
side effect errors since 3.4.0 : scale_x_continuous() with user provided trans object now explicitly calls the transform function with domain edges as input

### ISSUE THREAD

**Issue by phauchamps** [tidyverse/ggplot2#5105]
Hi,

Since 3.4.0 I am getting error messages from some extensions of scale_x_continuous() that are implemented in third parties packages. For the record, the 3rd party package I am using is ggcyto and the function I am using is scale_x_logicle() which just provides a specific transformation function to scale_x_continuous using trans = scales::trans_new(_ggcyto_object_). 

Digging into the issue, I found that when displaying the plot, ggplot2 now calls, among the numerous calls to the transformation function or its inverse, the transformation function explicitely with the domain edges as input, which is by default c(-Inf, +Inf). This has as side effect that the transformation functions that are not robust for extreme values, may crash or raise an error message. This explicit call to the transform function, with the domain edges values as input, was not done in version 3.3.6, so I don't get why this might now be necessary.

Herebelow is a minimal reprex, using a dummy transformation function, which just implements the identity function, but raises an error when extreme values are passed. This example works without any concern with ggplot2 version 3.3.6, but raises the error message "extreme value passed => convergence problem!" with ggplot2 version 3.4.0

Could you possibly have a look and advise ? 

Thx,

Philippe

```r
# reprex
library(ggplot2)

myDummyTrans <- function(x) {
    if (any(x < -1.0e99 | x > 1.0e99, na.rm = TRUE))
        stop("extreme value passed => convergence problem!")
    return(x)    
}

myDummyInverseTrans <- function(x) {
    return(x)
}

myTrans <- scales::trans_new("myDummy",
                             transform = myDummyTrans,
                             inverse = myDummyInverseTrans)

set.seed(1)
values <- rnorm(10000, mean = 0, sd = 1)
myData <- data.frame(value = values)

p <- ggplot(data = myData,
            aes(x = value)) + 
    geom_density()

#debug(myDummyTrans)

sc <- scale_x_continuous(limits = c(-6, 6),
                         trans = myTrans)

p + sc
```

**Comment by clauswilke** [comment]
Do you happen to know where in the ggplot2 code this additional call was inserted? It may help us figure out why this change was introduced.

**Comment by phauchamps** [comment]
I found it here: 

https://github.com/tidyverse/ggplot2/blob/63125db184b6e7d5516007574b5d15acbfd8f470/R/scale-.r#L644

**Comment by teunbrand** [comment]
This was done as part of #4775, to ensure break calculations can be performed when expanded limits exceeded the domain. I think if a transformation has known limits, e.g. [-1.0e99, 1.0e99], than that should be the domain of the transformation. However, I don't whether the logicle transformation has known limits.

**Comment by phauchamps** [comment]
The domain of the logicle transformation is ]-Inf, +Inf[ 
I don't think that calling the transformation explicitly on the edges of the domain is good practice as, in many cases, the transformation will not be defined on the edges themselves. For example, the log() transformation has ]0, +Inf[ as domain, but log(0) will potentially fail, and the result of calling the transformation object is likely to be implementation dependent. If the transformtion returns NA, then you are ready to go, but if it complains you will be stuck.

**Comment by clauswilke** [comment]
I think it's reasonable to expect transformations to be able to transform their domain. Inf values are allowed, so the log transformation for example should return -Inf, Inf when asked to transform its domain.

I can't think of any mathematical situation where a transformation wouldn't be able to handle its domain edges, under the condition that infinite values are possible as return values.

Maybe this should be adopted as a formal position and added to the documentation in the scales package.

**Comment by phauchamps** [comment]
Issue closed and replaced by: https://github.com/r-lib/scales/pull/375

Specific problem with ggcyto was handled in: https://github.com/RGLab/ggcyto/issues/88

Thanks @clauswilke and @teunbrand for your help !
