### ISSUE TITLE
Ggplot is not working when I plot in a pdf then use 'source'

### ISSUE THREAD

**Issue by RocaboisAudrey** [tidyverse/ggplot2#5107]
Hi everyone,

I want to plot graphs with ggplot in a pdf in a script called 'my_script.R' and then run this script in a script called 'run_all.R' by using 'source()'. This works when I use plot() but not ggplot(). When I use ggplot, a pdf is created but cannot be opened because there is no page in it.

Do you know if this could be ameliorated?

---

Brief description of the problem:

In my first script called 'my_script.R', I have:

```r
pdf("plot_results.pdf")
#Plot the graph
ggplot(data=df, aes(x=x, y=y)) +
  geom_bar(stat="identity", color="black", position=position_dodge(.9))
dev.off()
```

Then, in the script 'run_all.R', I call several scripts including the script above, I have:

```r
source('my_script.R')
```

**Comment by clauswilke** [comment]
You need to print the plot.

Please be aware that the ggplot2 issue tracker is not meant for user support. In the future, please direct such questions to appropriate venues, such as the Posit Community (formerly RStudio Community) or stackoverflow.com.
