### ISSUE TITLE
Combine multiple plots

### ISSUE THREAD

**Issue by waynelapierre** [tidyverse/ggplot2#5108]
Will there be a ggplot2 function that combines multiple plots? I have been resorting to other packages for this common task for several years.

**Comment by teunbrand** [comment]
Have you tried the {patchwork} package? ggplot2 doesn't offer any plot composition other than small multiples through the facet system.

**Comment by waynelapierre** [comment]
Yes, patchwork, grid, gridExtra, and ggpubr are alternatives out there.

**Comment by clauswilke** [comment]
Patchwork is the officially supported solution, written and maintained by the maintainer of ggplot2. If there are any specific issues you experience with patchwork, you're welcome to file bug reports or feature requests there.

**Comment by waynelapierre** [comment]
Why not put patchwork under the umbrella of Tidyverse if it is official?
