### ISSUE TITLE
Can't combine ordered factors in a facet_grid

### ISSUE THREAD

**Issue by DOSull** [tidyverse/ggplot2#5109]
When I use two ordered factors in a `facet_grid`, with `as.table = FALSE` in an attempt to get the plot to arrange the facets in a conventional increasing left-to-right, bottom-to-top grid, I get a warning and an error 
```
Error:
! Can't combine `..1$B` <factor<0715c>> and `..2$B` <ordered<08921>>.
Run `rlang::last_error()` to see where the error occurred.
Warning message:
Combining variables of class <ordered> and <ordered> was deprecated in ggplot2 3.4.0.
ℹ Please ensure your variables are compatible before plotting (location: `join_keys()`)
This warning is displayed once every 8 hours.
Call `lifecycle::last_lifecycle_warnings()` to see where this warning was generated. ```
```
Here's a reprex
```r
library(ggplot2)
library(tidyr)

data <- data.frame(
  x = rnorm(100), y = rnorm(100),
  A = factor(sample(c("tall", "grande", "venti"), 100, replace = TRUE), 
             levels = c("tall", "grande", "venti"), ordered = TRUE),
  B = factor(sample(c("L", "M", "S"), 100, replace = TRUE),
             levels = c("S", "M", "L"), ordered = TRUE))

ggplot(data) + 
  geom_point(aes(x = x, y = y)) +
  facet_grid(B ~ A, as.table = TRUE)

# FAILS
ggplot(data) + 
  geom_point(aes(x = x, y = y)) +
  facet_grid(B ~ A, as.table = FALSE)
```

This seems like a regression in this particular context, since it gives a lot less control over the appearance of the arrangement of the grid of small multiples, even when I am 'doing the right thing' and ordering my factors to get specific effects. Perhaps it was introduced to fix some other problem, but I can't see what it accomplishes in this context.

The error message seems to be from the function `utilities::with_ordered_restart` here 

https://github.com/tidyverse/ggplot2/blob/63125db184b6e7d5516007574b5d15acbfd8f470/R/utilities.r#L664

 but it's not clear to me why it should be treated as an error in what is surely a common use-case.

Possibly related to #4180

**Comment by yutannihilation** [comment]
Thanks,  confirmed. Looking at this comment on the function, maybe this behavior is not intended...?

https://github.com/tidyverse/ggplot2/blob/63125db184b6e7d5516007574b5d15acbfd8f470/R/utilities.r#L617-L619

**Comment by thomasp85** [comment]
In general there is no meaningful way to combine two ordered vectors that doesn't share the same levels since an ordering of the two sets of levels cannot be deduced. That being said I thought we would have just thrown a warning and not an error for now

**Comment by yutannihilation** [comment]
> That being said I thought we would have just thrown a warning and not an error for now

To me, that was the intention, considering the comment says "Ordered is coerced to factor" and there's actually a warning:

```
Warning message:
Combining variables of class <ordered> and <ordered> was deprecated in ggplot2 3.4.0.
ℹ Please ensure your variables are compatible before plotting (location: `join_keys()`)
This warning is displayed once every 8 hours.
Call `lifecycle::last_lifecycle_warnings()` to see where this warning was generated. 
```

The problem is that the actual code fail to coerce; it converts one of the ordered to a factor, but not both, which ends up with the vctrs error (`! Can't combine `..1$B` <factor<0715c>> and `..2$B` <ordered<08921>>.`).

https://github.com/tidyverse/ggplot2/blob/63125db184b6e7d5516007574b5d15acbfd8f470/R/utilities.r#L632-L638

Am I wrong...? Sorry, it might be just I'm reading the code wrong.

**Comment by clauswilke** [comment]
To be clear, whether a factor is ordered or not has no bearing on how ggplot2 treats it when plotting. It uses the order of the levels regardless, even for unordered factors. Therefore, ordering should probably just stripped from the factor during data processing, and maybe even issuing a warning is not necessary.

And yes, the current code is clearly wrong, as it ignores the possibility that both factors are ordered.

``` r
library(ggplot2)
library(tidyr)

data <- data.frame(
  x = rnorm(100), y = rnorm(100),
  A = factor(sample(c("tall", "grande", "venti"), 100, replace = TRUE), 
             levels = c("tall", "grande", "venti"), ordered = FALSE),
  B = factor(sample(c("L", "M", "S"), 100, replace = TRUE),
             levels = c("S", "M", "L"), ordered = FALSE))

# works as expected
ggplot(data) + 
  geom_point(aes(x = x, y = y)) +
  facet_grid(B ~ A, as.table = TRUE)
```

![](https://i.imgur.com/BvNulDZ.png)

``` r

# works as expected
ggplot(data) + 
  geom_point(aes(x = x, y = y)) +
  facet_grid(B ~ A, as.table = FALSE)
```

![](https://i.imgur.com/839WWK3.png)

<sup>Created on 2022-12-14 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by DOSull** [comment]
So will this get fixed in the next release?

**Comment by teunbrand** [comment]
Hi @DOSull, are you perhaps interested in submitting a PR for this? I think you already figured out the code in https://github.com/tidyverse/ggplot2/issues/5109#issuecomment-1352019201. No worries if you're not interested, then we'll fix it at some point.

**Comment by DOSull** [comment]
I don't know how the whole business of PRs and so on works, and I don't have familiarity with the code base---my suggested fix just follows @yutannihilation's identification of the issue! Thanks for thinking of me (!) but I should probably leave it to the experts.

**Comment by teunbrand** [comment]
Well if you would have been curious about it, you can find some (slightly outdated) contributing guidelines [here](https://ggplot2.tidyverse.org/CONTRIBUTING.html#pull-requests). There are also a bunch of helper functions in the {usethis} package, and they have a good [article](https://usethis.r-lib.org/articles/pr-functions.html) detailing how submit a PR.

**Comment by teunbrand** [comment]
This turned out to be slightly more complicated than I'd anticipated. With the proposed changed, we get:

``` r
devtools::load_all("~/packages/ggplot2/")
#> ℹ Loading ggplot2

vec_rbind0(
  data_frame0(a = factor(c("A", "B"), ordered = TRUE)), 
  data_frame0(a = factor(c("B", "C"), ordered = TRUE))
)
#> Warning: Combining variables of class <ordered> and <ordered> was deprecated in ggplot2
#> 3.4.0.
#> ℹ Please ensure your variables are compatible before plotting (location: )
#> Warning: Combining variables of class <ordered> and <factor> was deprecated in ggplot2
#> 3.4.0.
#> ℹ Please ensure your variables are compatible before plotting (location: )
#>   a
#> 1 A
#> 2 B
#> 3 B
#> 4 C
```

<sup>Created on 2022-12-27 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

Where the output is correct and no error is thrown. However, there are *two* warnings. One for the `vec_ptype2()` part, and one for the `vec_cast()` part. I wouldn't know how to elegantly solve the two warning bit.
