### ISSUE TITLE
Error using ggsave with purrr::map; Working in release 3.3.3, but not >= 3.3.4

### ISSUE THREAD

**Issue by phdjsep** [tidyverse/ggplot2#5114]
---

I'm using purrr::map and ggsave to write out multiple plots to disk and the following code works in ggplot2 release `= 3.3.3`, but not `>= 3.3.4`. Can't pinpoint what's changed that prevents this from working.

## ggplot2 v3.3.3 (working)

```r
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
library(ggplot2)
library(purrr)

# Working with ggplot 3.3.3, but not 3.3.4
diamonds %>%
  group_by(cut) %>%
  group_split() %>%
  purrr::map(~ ggsave(filename = paste("diamonds", .x$cut, .x$color, sep = "_"),
                      plot = ggplot(.x, aes(x = carat, y = depth)) +
                        geom_point(),
                      device = 'jpeg',
                      path = "~/Desktop/empty/"))
#> Saving 7 x 5 in image
#> Saving 7 x 5 in image
#> Saving 7 x 5 in image
#> Saving 7 x 5 in image
#> Saving 7 x 5 in image
#> [[1]]
#> NULL
#> 
#> [[2]]
#> NULL
#> 
#> [[3]]
#> NULL
#> 
#> [[4]]
#> NULL
#> 
#> [[5]]
#> NULL
```

## ggplot2 v3.3.4 (broken)

```r
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
library(ggplot2)
library(purrr)

# Working with ggplot 3.3.3, but not 3.3.4
diamonds %>%
  group_by(cut) %>%
  group_split() %>%
  purrr::map(~ ggsave(filename = paste("diamonds", .x$cut, .x$color, sep = "_"),
                      plot = ggplot(.x, aes(x = carat, y = depth)) +
                        geom_point(),
                      device = 'jpeg',
                      path = "~/Desktop/empty/"))
#> Saving 7 x 5 in image
#> Error in if (!dir.exists(dir)) {: the condition has length > 1

```

**Comment by teunbrand** [comment]
As far as I can tell, you're giving multiple filenames to `ggsave()`. Giving just a single filename per plot should help run the code again, e.g. `filename = paste("diamonds", .x$cut[1], .x$color[1], sep = "_")`. Maybe `ggsave()` should throw a warning when multiple filenames are given?

**Comment by phdjsep** [comment]
Thanks for the reply @teunbrand. Unfortunately that would defeat the purpose of what I'm after. I don't want to write 30+ `ggsave` calls to name files individually. Also, the code above works with `ggplot2 v3.3.3`, but not `ggplot2 v3.3.4 or greater` so it wasn't an issue with `ggsave` previously.

**Comment by teunbrand** [comment]
Yes I understand that this used to work, but I'm trying to find out whether this issue is a true regression or [off-label use](https://www.tidyverse.org/blog/2021/06/off-label-uses-in-ggplot2/) that has broken.

Perhaps I have caused a little bit of confusion. In every `purrr::map()` iteration, the `ggsave()` function receives a vector of however many rows were in that group as the `filename` argument. In this case, every plot that you'd want to save has multiple filenames associated with it.  

I'd agree with you that the error is quite uninstructive, so perhaps that could be improved.

**Comment by phdjsep** [comment]
Ah. I see. That’s a helpful link, thank you. I will try and dig in more
then. 🙏🏻

**Comment by phdjsep** [comment]
Thank you for your helpful advice @teunbrand! I think this was a combination of the "off-label" issue you indicated as well as my oversight of that `filename` parameter. You were correct in that I was passing in more than one filename, so `ggsave` was choking on that (as the error indicated). 

So the `3.3.4` release did change things in that it was previously lenient with my passing it multiple filenames, but also happy to say that it was an easier fix and I can still use the purrr approach to generating the plots using `ggsave`.

For those interested, here's the updated example which works with `ggplot 3.4.0`. The changes are in using the `unique()` function to pull a single value from the `df` as well as removing the `.x$color` as that results in multiple values again since I'm not grouping by it, only `cut`.

```
library(dplyr)
library(ggplot2)
library(purrr)

diamonds %>%
  group_by(cut) %>%
  group_split() %>%
  purrr::map(~ ggsave(filename = paste("diamonds", unique(.x$cut), sep = "_"), 
                      plot = ggplot(.x, aes(x = carat, y = depth)) +
                        geom_point(),
                      device = 'jpeg',
                      path = "~/Desktop/empty/"))
```
