### ISSUE TITLE
Saving svg plots using `ggsave()` makes `geom_rect` disappear, but not with `svg()`

### ISSUE THREAD

**Issue by emstruong** [tidyverse/ggplot2#5121]
# Description
When I save plots with `geom_rect()` using either `ggsave()` or `svglite::svglite()` the rectangles disappear, but not when I use 
`grDevices::svg()` or png formats.

# Code
```r
``` r
library(ggplot2)
library(svglite)

set.seed(123)

df <-
  data.frame(
    x = rpois(300, 3),
    y = c(rbinom(100, 1, .3), rbinom(100, 1, .5), rbinom(100, 1, .7)),
    group = factor(rep(c("a", "b", "c"), each = 100)) 
  )

(loghistGraph<-ggplot(df, aes(xmin = x, xmax = x, ymin = rep(0, nrow(df)), ymax = rep(nrow(df)), color = group)) +
    geom_rect(size = 4, position = position_dodge(.3))
)
```

![](https://i.imgur.com/QWYiQYq.png)

``` r

ggsave(plot = loghistGraph, file = "bugGraph.svg") 
#> Saving 7 x 5 in image
ggsave(plot= loghistGraph, file = "OkayGraph.png")
#> Saving 7 x 5 in image

# Works
grDevices::svg("DefaultSvgWorks.svg")
print(loghistGraph)
dev.off()
#> png 
#>   2

# Doesn't work and save as ggsave
svglite("svgliteBug.svg")
print(loghistGraph)
dev.off()
#> png 
#>   2
```

<sup>Created on 2022-12-26 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

Attached are the graphs that did and did not work.

Using ggsave for .svg
![bugGraph](https://user-images.githubusercontent.com/112967876/209587018-c60b80de-9033-48a7-a83d-995843515f84.svg)

Using svg()
![DefaultSvgWorks](https://user-images.githubusercontent.com/112967876/209587019-9650d0c2-2647-4d27-bcb7-3af59676bcb9.svg)

Using ggsave for .png
![OkayGraph](https://user-images.githubusercontent.com/112967876/209587020-c3bd9da3-799c-4cf4-acc9-172d0b6c455d.png)

Using svglite for .svg
![svgliteBug](https://user-images.githubusercontent.com/112967876/209587021-9dc20707-ea8d-41b1-be1c-a29645a1cd64.svg)

**Comment by teunbrand** [comment]
As far as I can tell, {svglite} exports the rectangles as `rect`s, while `svg()` exports them as 'path's. The rectangles are still there in the text output of {svglite}, but I think they might not get rendered because they have 0-width.

From the SVG docs [here](https://www.w3.org/TR/SVG/shapes.html#RectElement):
> The [width](https://www.w3.org/TR/SVG/geometry.html#Sizing) and [height](https://www.w3.org/TR/SVG/geometry.html#Sizing) properties define the overall width and height of the rectangle. A negative value for either property is illegal and [must be ignored as a parsing error](https://www.w3.org/TR/CSS21/syndata.html#parsing-errors). A computed value of zero for either dimension disables rendering of the element.

So I think everything is working as it should; it is just a difference in interpretation of what is output to the file (a 'rect' vs 'path').

**Comment by teunbrand** [comment]
Giving this another thought, I don't think there is anything to fix here at ggplot2's side, as this relates to how graphics are translated between R and devices. If you do insist on this plot working, either give the rectangles a small width or use a line to represent the data. Despite that this is unlikely to change in ggplot2, I do want to thank you for preparing the examples, and hope to hear from you again when you find new issues.
