### ISSUE TITLE
Open circles representing degrees became squares using geom_sf()

### ISSUE THREAD

**Issue by barbosawf** [tidyverse/ggplot2#5147]
I am using the following code:

library(geobr)
library(ggplot2)

MG1 <- read_state(code_state = "MG", year = 2020)

ggplot(MG1) +
  geom_sf()

![image](https://user-images.githubusercontent.com/105462541/211913172-928f7700-94da-45ef-924b-7108e19a30c2.png)

Open circles representing degrees became squares.

The R version is 4.2.2 and R studio, and packages are the latest.

**Comment by thomasp85** [comment]
I've just went down a long winding path in ragg with this issue. I'm almost 100% certain this is because you are using the default windows device which somehow got broken in 4.2.2 when it comes to rendering of certain glyphs. Let me know if my guess about your OS and graphic device is correct

**Comment by raymondben** [comment]
Just noting that this issue still exists. Yes, I believe it's the Windows default graphics device. Issue doesn't occur on Linux, doesn't occur on Windows with pdf device. Replacing the "*degree" in the label with the Unicode degree symbol "\ub0" might be an option.

**Comment by thomasp85** [comment]
It will get fixed in the next version of R
