### ISSUE TITLE
How to replace the deprecated ggplot2 function aes_string?

### ISSUE THREAD

**Issue by ricmedveterinario** [tidyverse/ggplot2#5155]
I am using the following function, suggested in the post: 

#https://stackoverflow.com/questions/52747802/how-to-remove-very-thin-bar-plot-outline-#border/75194438?noredirect=1#comment132690525_75194438

plot_bar_2 <- function (physeq, x = "Sample", y = "Abundance", fill = NULL, title = NULL, facet_grid = NULL, border_color = NA)
{
mdf = psmelt(physeq)
p = ggplot(mdf, aes_string(x = x, y = y, fill = fill))
p = p + geom_bar(stat = "identity", position = "stack", color = border_color)
p = p + theme(axis.text.x = element_text(angle = -90, hjust = 0))
if (!is.null(facet_grid)) {
p <- p + facet_grid(facet_grid)
}
if (!is.null(title)) {
p <- p + ggtitle(title)
}
return(p)
}

#However, I am getting the following message when I follow the steps:

library(phyloseq)
data("GlobalPatterns")
gp.ch <- subset_rate(GlobalPatterns, Phylum == "Spirochaetes")
p <- plot_bar_2(gp.ch, fill = "Phylum")
p + geom_bar(stat = "identity") + scale_fill_manual(values = cbPalette)

#or with any other border color if you want
p <- plot_bar_2(gp.ch, fill = "Phylum", border_color = "red")

#Error message":
#Warning message:
aes_string() was deprecated in ggplot2 3.0.0.
information_source Please use tidy evaluation ideoms with aes()
This warning is displayed once every 8 hours.
Call lifecycle::last_lifecycle_warnings() to see where this warning was generated.

#It would be something reported here at:
#https://stackoverflow.com/questions/74414272/how-to-replace-the-deprecated-ggplot2-function-aes-#string-accepting-an-arbitrar

But I don't know how to fix it.

I would like to no longer receive this message, because I believe that this script will no longer #work for some time.
Thanks.

**Comment by clauswilke** [comment]
You need to use the embrace operator: https://rlang.r-lib.org/reference/topic-inject.html#embracing-with-

**Comment by ricmedveterinario** [comment]
@clauswilke, Thank you very much,

This topic has been resolved at: https://github.com/joey711/phyloseq/issues/1654
