### ISSUE TITLE
Y axis on polar plots is always expanded beyond set limits, even with expand c(0,0)

### ISSUE THREAD

**Issue by KlausBrunner** [tidyverse/ggplot2#5156]
It seems impossible to prevent expansion of the y (radial) axis in polar plots. Despite limiting the range to 90 and an expand of c(0,0), the y axis is expanded to 100. Without polar coordinates, output looks as expected, i.e. axes are clipped exactly.

[This SO question](https://stackoverflow.com/questions/72005238/scale-y-axis-on-a-polar-plot-in-ggplot) has a good description of the issue, and I'm also stealing most of the reprex from there. 

```r
library(tidyverse)

foo <- tibble(theta = c(0, 10, 20), r = c(10, 30, 90))

foo |> ggplot() +
  geom_point(aes(x = theta, y = r)) +
  coord_polar() +
  scale_y_continuous(limits = c(0, 90),
                     expand = c(0, 0),
                     breaks = 90) +
  scale_x_continuous(
    limits = c(0, 360),
    expand = c(0, 0),
    breaks = c(0, 90, 180, 270)
  )

```

**Comment by teunbrand** [comment]
Hi thanks for reporting the issue. It seems to me that this issue is intertwined with #4815, so it would make sense to continue discussing there. I think technically the radial axis isn't expanded, but it seems that way because an extra grid line is drawn at the position of the labels.
