### ISSUE TITLE
Adding multiple geom_segment layers only shows the last layer added

### ISSUE THREAD

**Issue by danbraswell** [tidyverse/ggplot2#5157]
Adding multiple geom_segment layers only shows the last layer added. I'm seeing this in the latest stable release of rstudio and in daily `2023.03.0-daily+79 (2023.03.0-daily+79)`
In the plot below there should be three vertical lines extending from the x-axis. Only the last one is getting added.

```
library(ggplot2)
library(dplyr)

df <- mtcars
p <- df %>%
  ggplot(aes(x=wt,y=mpg)) +
  geom_point()

vec <- c(2.5,3.5,4.5)
for (i in vec) {
  p <- p + geom_segment(aes(x=i,xend=i,y=0,yend=10))
}

p
```
![image](https://user-images.githubusercontent.com/101535213/214092307-264760d9-fe94-4a1a-87c0-e81ea28a83c9.png)

**Comment by clauswilke** [comment]
This is just R lazy evaluation. You're adding three layers in the same location, for i = 4.5.
