### ISSUE TITLE
Part of plot missing when open in Adobe Illustrator

### ISSUE THREAD

**Issue by Fclef** [tidyverse/ggplot2#5163]
---

Hi,

I saved a curve plot in PDF and when I opened the figure in AI, the latter half of the curve is gone. I tried both default device and cairo but it seems not working. 

Best,
Tim

In illustrator
![image](https://user-images.githubusercontent.com/50245970/214964433-4daa645d-ea8e-435c-ae43-8b3a5fd154e5.png)

In R or PDF reader
![image](https://user-images.githubusercontent.com/50245970/214964539-1f9317b2-e2f9-41fa-9f45-a25fc10d8f90.png)

```r
library(ggplot2)

## tj is the data i use
ggplot() + geom_path(data = tj, aes(x = curv_1, y = curv_2), size = 4)
ggsave('~/test.pdf',width = 12, height = 8, units = 'in')

```
[test_data.csv](https://github.com/tidyverse/ggplot2/files/10513935/test_data.csv)

**Comment by teunbrand** [comment]
[This post](https://community.adobe.com/t5/illustrator-discussions/maximum-anchor-points-on-a-path/td-p/10163260) seems to suggest that illustrator truncates paths with >32,000 points. Your data has 100,000 rows, so it gets truncated upon import. My suggestion would be to simplify your path before exporting. There isn't anything I can see that ggplot2 can do in this case.

**Comment by Fclef** [comment]
> [This post](https://community.adobe.com/t5/illustrator-discussions/maximum-anchor-points-on-a-path/td-p/10163260) seems to suggest that illustrator truncates paths with >32,000 points. Your data has 100,000 rows, so it gets truncated upon import. My suggestion would be to simplify your path before exporting. There isn't anything I can see that ggplot2 can do in this case.

I didn't know AI has 32000 point limitation. Thank you so much!!

**Comment by clauswilke** [comment]
Wow, the responses on that site are insane. "We're the premiere makers of graphics software, but we also truncate your paths at 32,000 points and there is nothing anybody can do about it, least of all us."
