### ISSUE TITLE
SuppressWarnings

### ISSUE THREAD

**Issue by flde** [tidyverse/ggplot2#5173]
Hello tidyverse team, 

many thanks for your great work! I tried to find a solution to suppress ggplot2 warnings e.g. `Scale for 'colour' is already present. Adding another scale for 'colour', which will replace the existing scale.` because it crowds my notebooks. I tried option(warn=-1) and putting the print() in SuppressWarnings() but nothing helps. 

It is just a minor issue but I somhow find no solution. 

Many thanks! 
Flo

**Comment by teunbrand** [comment]
These are messages, not warnings, so `suppressMessages()` should do the trick.

Please note that the ggplot2 issue tracker is not meant for user support. In the future, you can direct such questions to other venues, such as the Posit Community or stackoverflow.
