### ISSUE TITLE
coord_sf() doesn't adjust line size for graticule lines

### ISSUE THREAD

**Issue by MikkoVihtakari** [tidyverse/ggplot2#5179]
Seems like [this](https://github.com/tidyverse/ggplot2/issues/2991) issue has reoccurred with the change from size to linewidth?

``` r
library(ggplot2)
ggplot(data.frame(x=1,y=1),aes(x,y)) + 
  theme_bw() + 
  theme(panel.grid = element_line(linewidth = 5))
```

![](https://i.imgur.com/lGfOX2R.png)

``` r

ggplot(data.frame(x=1,y=1),aes(x,y)) + 
  coord_sf() + 
  theme_bw() + 
  theme(panel.grid = element_line(linewidth = 5))
```

![](https://i.imgur.com/mNB5SD5.png)

<sup>Created on 2023-02-07 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by MikkoVihtakari** [comment]
typo in the code

**Comment by teunbrand** [comment]
Thanks for catching! Yes, this indeed seems to be a regression from 3.4.0.
