### ISSUE TITLE
stat_summary_hex no longer responds to z aesthetic whereas stat_summary_2d does

### ISSUE THREAD

**Issue by ingewortel** [tidyverse/ggplot2#5184]
Since updating to the new ggplot2 version (v3.4.0), `stat_summary_hex` no longer responds to the z aesthetic when plotting, and yields a completely different output when compared to `stat_summary_2d` (which does respond to the z value properly). 
I did not have this issue in my previous version (v3.3.6).

The following example illustrates the problem:

``` r
library( ggplot2 )

# generate example data: 
# - x and y randomly sampled between 0 and 4
# - z is a noisy version of the distance to point (2,2)
d <- data.frame(
    x = 4*runif( 5000 ),
    y = 4*runif( 5000 )
)
val <- function( row ) { 
    x <- row[1]; y <- row[2]; 
    return( sqrt( ( x - 2)^2 + (y - 2 )^2 ) + rnorm(1, sd=0.2) ) }
d$z <- apply( d, 1, val )

# plot using stat_summary_hex does not properly show z-value..
ggplot(d, aes( x = x, y = y ) ) + stat_summary_hex( aes( z = z ) ) 
```

![](https://i.imgur.com/74IB3ym.png)

``` r

# ...whereas stat_summary_2d does provide the expected behavior
ggplot(d, aes( x = x, y = y ) ) + stat_summary_2d( aes( z = z ) )
```

![](https://i.imgur.com/5JI7Ygx.png)

<sup>Created on 2023-02-08 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by clauswilke** [comment]
Is this the same as #5165? If yes then it has been fixed and will be in the next ggplot2 release.
