### ISSUE TITLE
Floating axes

### ISSUE THREAD

**Issue by grantmcdermott** [tidyverse/ggplot2#5190]
The base `plot` method allows you to pass a `frame.plot = FALSE` argument, which removes the outline box. Because `plot` draws non-intersecting axes by default, this provides an easy way to achieve the (in my view) aesthetically pleasing effect of floating axes.

``` r
plot(
  dist ~ speed, 
  data = cars,
  frame.plot = FALSE
  )
```

![](https://i.imgur.com/VyTfgxL.png)

<sup>Created on 2023-02-16 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

Of course, some other base plotting functions---most obviously `hist`---do this automatically.

To the best of my knowledge, there is no direct way to achieve the same floating effect of non-intersecting axes in **ggplot2**. The workarounds that I've seen generally involve some hacks with `segment`. For example, see this [SO answer](https://stackoverflow.com/a/25327902/4115816) and I believe that this is also what **ggthemes** does behind the scenes with its [`geom_rangeframe`](https://jrnold.github.io/ggthemes/reference/geom_rangeframe.html) function. Unfortunately, I've found these workarounds to be quite brittle/unreliable, producing ugly artefacts with certain datasets or more complex plot constructions like faceting (ticks not lining up with the axis ends, etc.)

It would be great if we could disable axes intersection (but not turn them off completely) as part of a regular theme argument.

Thanks for considering and for maintaining this essential package.

**Comment by teunbrand** [comment]
Hi there, this looks like the same request as #4907, so it would seem best to keep discussion in one place over there.

**Comment by grantmcdermott** [comment]
Ah, sorry missed it. Thanks and will follow there.
