### ISSUE TITLE
export `translate_shape_string()`

### ISSUE THREAD

**Issue by aphalo** [tidyverse/ggplot2#5191]
Function `translate_shape_string()` or a replacement of it is needed in packages extending 'ggplot2' with geoms that accept the shape aesthetic, such as my package 'ggpp'. I have copied the definition of `translate_shape_string()` from 'ggplot2' into 'ggpp' but this could lead to inconsistencies in the future, for example in error handling and messages.

It would be convenient if 'ggplot2' would export this function, although the workaround of redefining it when needed is obviously fully functional.

**Comment by smouksassi** [comment]
yes, this would be very useful.
I also think it can be useful to have a blank shape similar to "blank" linetype

**Comment by teunbrand** [comment]
I must admit: I also would have needed this at some point, but then went the lazy route and not translating point shapes.

@smouksassi there is #5143 that introduces "blank" and "dot" as new shape names
