### ISSUE TITLE
Width argument not accepting a vector anymore

### ISSUE THREAD

**Issue by yannk-lm** [tidyverse/ggplot2#5192]
Hello,

I've been trying to run some old code with ggplot2 3.4 and it appears that the width argument in the `geom_jitter` function doesn't accept a vector of width anymore.

Here is a reproductive example :
```r
set.seed(123)
df <- data.frame(
  group = rep(c("A", "B"), each = 50),
  y = rnorm(100))

widths <- c(A = 0.2, B = 0.4)

df$width_size <- widths[df$group]

ggplot(df, aes(x = group, y = y) +
  geom_jitter(width = df$width_size) +
  theme_minimal()
```
Is it intended? And if it is, how can I make it work again?

Thank you for your help.

Best,
Yannick

**Comment by teunbrand** [comment]
I think it has to do with the R version rather than ggplot2. From the 'Changes in R 4.2.0' news:

> Calling if() or while() with a condition of length greater than one gives an error rather than a warning. [...]

I can run the reprex with ggplot2 version 3.4.1 on R3.5.0 with the intended effect (with warnings):

``` r
library(ggplot2)
packageVersion("ggplot2")
#> [1] '3.4.1'

set.seed(123)
df <- data.frame(
  group = rep(c("A", "B"), each = 50),
  y = rnorm(100))

widths <- c(A = 0.2, B = 0.4)

df$width_size <- widths[df$group]

ggplot(df, aes(x = group, y = y)) +
         geom_jitter(width = df$width_size) +
         theme_minimal()
#> Warning in if (params$width > 0) function(x) jitter(x, amount =
#> params$width): the condition has length > 1 and only the first element will
#> be used
#> Warning in if (amount == 0) amount <- factor * (z/50): the condition has
#> length > 1 and only the first element will be used
```

![](https://i.imgur.com/jWa3ugw.png)

<sup>Created on 2023-02-20 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

However, that raises a new question: should ggplot2 support vectorised input to the `width` argument in `geom_jitter()`?

**Comment by yannk-lm** [comment]
Thank you for your answer.

I indeed use R 4.2, any idea how to circumvent this issue, besides using R 3.5.0?

**Comment by teunbrand** [comment]
Well from the way I read the code in the lines below, this was never intended as a use case, so you'll be in unsupported territory for now.  I don't know of any reasonable circumventions to this issue that are within the grammar, but you may of course add variable-width jitter manually. 

https://github.com/tidyverse/ggplot2/blob/f84ee7e000159ea176cb3b630c0edf97a5fa82c7/R/position-jitter.r#L78-L79

The thing that probably needs to happen is for ggplot2 to take a stance on this issue, and either properly throw an error about what is going wrong, or more fully support a vectorised `width`/`height` parameter to the position adjustment. A similar discussion about passing vectorised parameters to a layer occurred [here](https://github.com/tidyverse/ggplot2/issues/4821), and most maintainers seemed to express some discomfort in allowing such vectorised input.

**Comment by teunbrand** [comment]
I'm going to close this, as the code's intention was never to vectorise a width argument in positions.
