### ISSUE TITLE
Requested Feature: Throw an error when there is an unrecognized argument

### ISSUE THREAD

**Issue by mcwayrm** [tidyverse/ggplot2#5195]
We were working on some plots, unable to figure out why the graph was not varying by the bin size. We found that our mistake was using the `bin` (an unrecognized argument) rather than `bins` (the correct argument). Because `ggplot()` did not throw an error it made troubleshooting a lot longer and difficult. 

There would be a lot of utility in adding a feature that threw an error when an argument is unrecognized. Otherwise, I believe that simple mistakes will accumulate into poor conclusions and misinterpretations of the visual results (simply because an intended argument is not being used).

**Comment by clauswilke** [comment]
I think you have to be more specific with what exactly you want flagged, because in my experience ggplot issues a warning when it sees arguments it doesn't know.

``` r
library(tidyverse)

ggplot(mpg, aes(displ, cty)) +
  geom_point(abc = 5)
#> Warning in geom_point(abc = 5): Ignoring unknown parameters: `abc`
```

![](https://i.imgur.com/4GnxrkL.png)

<sup>Created on 2023-02-21 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by mcwayrm** [comment]
Thank you, I must have missed this. You are correct. Somehow in .rmd it was not providing warning messages. I will need to look into our defaults to see why that was.
