### ISSUE TITLE
fill= rev(factor.column) with position_stack() does not update legend colors or text

### ISSUE THREAD

**Issue by s-elsheikh** [tidyverse/ggplot2#5207]
I found a problem with ...

when trying to reverse the order of a stacked column, when using fill = factor.column, I noticed the following:

1. using rev() reverses the position of the stacked column, but the legend ist not updated. Adding geom_text() would then show wrong data.
2. using fct_rev() reverses the position of the geom_col, behaves as expected

I expected ...
Warning or error, that wrong data may be shown in geom_text()

I understand the rev does not reverse the ordering of the factor, but I find this behaviour could lead to errors.

Thanks

Here is the code to reproduce the bug:

``` r
library(tidyverse)
#> Warning: Paket 'tidyverse' wurde unter R Version 4.1.3 erstellt
#> Warning: Paket 'ggplot2' wurde unter R Version 4.1.3 erstellt
#> Warning: Paket 'tibble' wurde unter R Version 4.1.3 erstellt
#> Warning: Paket 'tidyr' wurde unter R Version 4.1.3 erstellt
#> Warning: Paket 'readr' wurde unter R Version 4.1.3 erstellt
dat <- 
mpg %>% 
    #(year == 1999) %>%  
    count(year, manufacturer) %>% 
    mutate(manufacturer = factor(manufacturer)) %>% 
    slice(1:2)

print(dat)
#> # A tibble: 2 x 3
#>    year manufacturer     n
#>   <int> <fct>        <int>
#> 1  1999 audi             9
#> 2  1999 chevrolet        7

dat %>% 
    ggplot(aes(year, n, fill = manufacturer))+
    geom_col()+
    #geom_text(aes(label = n), position = position_stack(vjust = 0.5))+
    ggtitle("baseline")
```

![](https://i.imgur.com/RG9QKpo.png)

``` r

dat %>% 
    ggplot(aes(year, n, fill = rev(manufacturer)))+
    geom_col()+
    #geom_text(aes(label = n), position = position_stack(vjust = 0.5))+
    ggtitle("using rev wrong data on the plot")
```

![](https://i.imgur.com/aS47wEB.png)

``` r

dat %>% 
    ggplot(aes(year, n, fill = fct_rev(manufacturer)))+
    geom_col()+
    #geom_text(aes(label = n), position = position_stack(vjust = 0.5))+
    ggtitle("using fct_rev updates legend text to match text labels")
```

![](https://i.imgur.com/3p7IxWQ.png)

<sup>Created on 2023-02-27 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

<details style="margin-bottom:10px;">
<summary>
Standard output and standard error
</summary>

``` sh
[31mx[39m Install the [34mstyler[39m package in order to use `style = TRUE`.
```

</details>

**Comment by teunbrand** [comment]
Unless I'm misunderstanding something: I'm don't think this is an error ggplot2's behalf. The `rev()` function reverse the order of its input, so that there would be a disconnect between the reversed data and the rest makes sense.
If you want to reverse the order of stacking, you may also try `position = position_stack(reverse = TRUE)` in a layer.
