### ISSUE TITLE
different widths in bar plot when using undropped factor levels

### ISSUE THREAD

**Issue by bsgerber** [tidyverse/ggplot2#5211]
I found a potential problem with the widths of bars using `geom_bar` when using factor levels, and keeping unused levels with `drop = F` argument in `scale_x_discrete`. This can be overcome by setting the `width` in aesthetic but thought the variable nature of widths in plotting might be an issue.

Here is the code to reproduce the bug:

``` r
library(ggplot2)

df <- data.frame(
  x = factor(c('A', 'D'), levels = LETTERS[1:5])
)

ggplot(df, aes(x)) +
  geom_bar() +
  scale_x_discrete(drop = F)
```

![](https://i.imgur.com/uaYLUK6.png)

``` r

df <- data.frame(
  x = factor(c('B', 'D'), levels = LETTERS[1:5])
)

ggplot(df, aes(x)) +
  geom_bar() +
  scale_x_discrete(drop = F)
```

![](https://i.imgur.com/MkJE8jd.png)

<sup>Created on 2023-02-28 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by teunbrand** [comment]
This is indeed unfortunate. Given that `resolution()`, which determines the default width, makes a special case for integers; should it also use that case for the `"mapped_discrete"` class? See: https://github.com/tidyverse/ggplot2/blob/5141ef58442114a40c733a0ab387710c8f9cc1ec/R/utilities-resolution.r#L21-L22

**Comment by thomasp85** [comment]
Yes, I think that is sensible
