### ISSUE TITLE
position_dodge() not dodging, even with `group` or `color` set

### ISSUE THREAD

**Issue by bwiernik** [tidyverse/ggplot2#5219]
When I use `position_dodge()` with the current development version, `position_dodge()` is not dodging geoms, even when `color` or `group` aesthetics are set. `position_dodge2()` works as expected.

``` r
library(tidyverse)

data_condition <- 
  tibble(
    group = rep(1:3, each = 4),
    effect = rnorm(12, mean = group / 15, sd = .05)
  ) |> 
  mutate(
    group = paste("Condition", group),
    se = .05,
    CI_low = effect - 2 * se,
    CI_high = effect + 2 * se
  )

ggplot(data_condition) + 
  aes(x = group, y = effect, ymin = CI_low, ymax = CI_high, color = group, group = group) +
  geom_linerange(position = position_dodge(width = .3)) +
  geom_point(position = position_dodge(width = .3))
```

![](https://i.imgur.com/SVD6ayK.png)

``` r

ggplot(data_condition) + 
  aes(x = group, y = effect, ymin = CI_low, ymax = CI_high, color = group, group = group) +
  geom_linerange(position = position_dodge2(width = .3)) +
  geom_point(position = position_dodge2(width = .3))
```

![](https://i.imgur.com/QegNMOJ.png)

<sup>Created on 2023-03-06 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by teunbrand** [comment]
I think you might have to give every row its own group in this case in order for the dodging to work. Did this used to work in a previous version of ggplot2?

``` r
library(tidyverse)

data_condition <- 
  tibble(
    group = rep(1:3, each = 4),
    effect = rnorm(12, mean = group / 15, sd = .05)
  ) |> 
  mutate(
    group = paste("Condition", group),
    se = .05,
    CI_low = effect - 2 * se,
    CI_high = effect + 2 * se
  )

ggplot(data_condition) + 
  aes(x = group, y = effect, ymin = CI_low, ymax = CI_high, 
      color = group, group = seq_along(group)) +
  geom_linerange(position = position_dodge(width = .3)) +
  geom_point(position = position_dodge(width = .3))
```

![](https://i.imgur.com/odMB0TC.png)

<sup>Created on 2023-03-06 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by bwiernik** [comment]
Yes, it used to work, and my understanding was that this was the whole point of position_dodge(), it dodged based on the grouping variable. 

It doesn't make any sense me to to have each row be its own group--my understanding was that the purpose of position_dodge() (vs position_dodge2()) was that it dodged values at the same coordinate thay belonged to same group.

**Comment by teunbrand** [comment]
I've tried a few older versions, and I didn't get it to work. I think `position_dodge()` is primarily used to dodge different groups at the same x-position. If you'd dodge within-groups, a dodged violin plot would get scrambled. Perhaps the docs could be clearer on what exactly is being dodged?

**Comment by bwiernik** [comment]
But position_dodge() isn't dodging things at the same x position--it isn't dodging anything at all as far as I can see

**Comment by smouksassi** [comment]
dodging works as intended it need to be able to know what are the group ids to dodge by if all x are the same you want to dodge based on what ? row number within  unique x values ? see example below
mapping shape is optional but if you do so then ggplot can figure out the grouping automatically otherwise you need to specify the wanted grouping.


``` r
library(tidyverse)
set.seed(34654)
data_condition <-
  tibble(group = rep(1:3, each = 4),
         effect = rnorm(12, mean = group / 15, sd = .05)) |>
  mutate(
    xvalue = paste("xvalue", group),
    se = .05,
    CI_low = effect - 2 * se,
    CI_high = effect + 2 * se,
  ) |>
  group_by(xvalue) |>
  mutate(group = 1:n())

ggplot(data_condition) +
  geom_linerange(
    aes(
      x = xvalue,
      y = effect,
      ymin = CI_low,
      ymax = CI_high,
      color = xvalue,
      group = group
    ),
    position = position_dodge(width = .3)
  ) +
  geom_point(
    aes(x = xvalue, y = effect, group = group,
        shape = as.factor(group)
        ),
    position = position_dodge(width = .3))
```

![](https://i.imgur.com/gagVvdv.png)

<sup>Created on 2023-03-16 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by teunbrand** [comment]
I'm going to agree that dodging here works as intended.
