### ISSUE TITLE
Missing values can cause factor level order to be ignored

### ISSUE THREAD

**Issue by banbh** [tidyverse/ggplot2#5224]
If a factor with missing values is used in a geom which is not first it can cause the ordering of factor levels to be ignored.

For example, in the code below the first plot is as expected (with factor levels appearing in order) but the second plot ignores the order of the levels and switches to alphabetic ordering. I expect both charts to be the same. (The third chart is a "fix" which drops NAs.)

```r
library(tidyverse) # ggplot2_3.4.0 
  
Z_factor <- tibble(x = as_factor(c(month.name[1:3], NA)))

# Good and as expected (includes NA since na.translate = TRUE by default)
ggplot() + # January, February, March, NA
  geom_point(aes(x, y = 2), data = Z_factor) +
  geom_point(aes(x, y = 1), data = Z_factor |> filter(!is.na(x)))

# Bad? Switches to alphabetical ordering
ggplot() + # February, January, March
  geom_point(aes(x, y = 1), data = Z_factor |> filter(!is.na(x))) + 
  geom_point(aes(x, y = 2), data = Z_factor)

# Good and as expected (but drops NA)
ggplot() + # January, February, March
  geom_point(aes(x, y = 1), data = Z_factor |> filter(!is.na(x))) + 
  geom_point(aes(x, y = 2), data = Z_factor) +
  scale_x_discrete(na.translate = FALSE)
```

**Comment by teunbrand** [comment]
This seems in principle the same issue as #5057, but it seems that in this case cannot be ameliorated by setting `scale_x_discrete(drop = FALSE)`. As a workaround, I can suggest setting the limits manually, e.g. `scale_x_discrete(limits = levels(Z_factor$x))`.
