### ISSUE TITLE
geom_abline ... parameter documentation includes size in the example 

### ISSUE THREAD

**Issue by jmuhlenkamp** [tidyverse/ggplot2#5225]
This is relatively minor, but hopefully an easy fix for someone quite familiar with the package internals.  This is in the version 3.4.1 and I see it in the source code still, too.

```
?geom_abline
```
includes

<html>
<body>

... | Other arguments passed on to layer(). These are often aesthetics, used to set an aesthetic to a fixed value, like colour = "red" or size = 3. They may also be parameters to the paired geom/stat.
-- | --

</body>
</html>

This could potentially frustrate end users who would get a warning from following this example
```
library(ggplot2); ggplot(mtcars, aes(wt, mpg)) + geom_point() + geom_abline(slope = 10, size = 3)
# > ggplot(mtcars, aes(wt, mpg)) + geom_point() + geom_abline(slope = 10, size = 3)
# Warning message:
# Using `size` aesthetic for lines was deprecated in ggplot2 3.4.0.
# ℹ Please use `linewidth` instead.
# This warning is displayed once every 8 hours.
# Call `lifecycle::last_lifecycle_warnings()` to see where this warning was generated. 
```

I believe the misleading `...` documentation is coming from:
 
* `#' @inheritParams geom_point` in https://github.com/tidyverse/ggplot2/blob/main/R/geom-abline.R#L35
* https://github.com/tidyverse/ggplot2/blob/main/R/geom-point.R#L34-L37

I was going to submit a fix for this, but realized the inherits here make it a bit more nuanced (see below).  Happy to submit a PR for this if given some guidance about the best way to resolve it.

**Comment by teunbrand** [comment]
Thanks for the report. The issue is already being tracked in #5040, so it would be best to keep al the discussion in one place over there. The PR #5127 aims to address this (and other) point(s).
