### ISSUE TITLE
ggplot2 

### ISSUE THREAD

**Issue by jpeasari** [tidyverse/ggplot2#5236]
> library("tidyverse")
> library("dplyr")
> library("readxl")
> library("reshape2")
> library("ggplot2")
> library("rlang")
> library("reprex")
> 
> riskallmarks <- read_excel("mmo7risk.xlsx")
> riskallmarks.m <- melt(riskallmarks, id.var = "risk")  
> riskallmarks.m <- as.data.frame(riskallmarks.m)
> head(riskallmarks.m)
      risk variable value
1 highrisk     cd19  43.7
2 highrisk     cd19  30.2
3 highrisk     cd19   2.7
4 highrisk     cd19  13.1
5 highrisk     cd19   2.1
6 highrisk     cd19   2.8
> 
> ggplot(riskallmarks.m, aes(variable,value))
Error in .standalone_types_check_dot_call(ffi_standalone_check_number_1.0.7,  : 
  object 'ffi_standalone_check_number_1.0.7' not found

I found a  bug with the ggplot2 library. I have not seen this type of error throughout the internet.
![ggplot2](https://user-images.githubusercontent.com/55759107/226031233-ff8d17ca-92f0-43ec-8b3c-8abc25de57b7.png)

**Comment by OliverFishCode** [comment]
I am having the same issue

**Comment by teunbrand** [comment]
This has been reported in #5235 as well, so let's keep all the discussion in one place.

**Comment by ashaarul1904** [comment]
Same error here as well, when using the ggplot2. Please let me know how to fix this error?

"Error in .standalone_types_check_dot_call(ffi_standalone_check_number_1.0.7,  : object 'ffi_standalone_check_number_1.0.7' not found"

**Comment by OliverFishCode** [comment]
I updated rlang to version 1.1 and it fixed the issue

**Comment by ashaarul1904** [comment]
How did you update rlang?

**Comment by OliverFishCode** [comment]
Install.packages("rlang", version = 1.1.0)

I believe this is correct syntex,, just run it in a r script. Below is a reference to the function.
https://www.rdocumentation.org/packages/utils/versions/3.6.2/topics/install.packages

**Comment by Li-Zhiming26** [comment]
> Install.packages("rlang", version = 1.1.0)
> 
> I believe this is correct syntex,, just run it in a r script. Below is a reference to the function. https://www.rdocumentation.org/packages/utils/versions/3.6.2/topics/install.packages
Thank you so much. I have dissolved the same problem following your way.

**Comment by jpeasari** [comment]
Update the rlang package install.packages("rlang", version = "1.1.0") worked.

**Comment by jingydz** [comment]
> install.packages("rlang", version = "1.1.0")
Warning in install.packages :
  unable to access index for repository https://cran.rstudio.com/src/contrib:
  cannot open URL 'https://cran.rstudio.com/src/contrib/PACKAGES'
Warning in install.packages :
  package ‘rlang’ is not available for this version of R

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages
Warning in install.packages :
  unable to access index for repository https://cran.rstudio.com/bin/windows/contrib/4.2:
  cannot open URL 'https://cran.rstudio.com/bin/windows/contrib/4.2/PACKAGES'

What version of R do you use?

**Comment by Li-Zhiming26** [comment]
> 4.2.1

**Comment by teunbrand** [comment]
gtable 0.3.3 has landed on CRAN. installing this might help.
