### ISSUE TITLE
Inconsistent shades of fill-gray in geom_tile and geom_bar

### ISSUE THREAD

**Issue by holgerbrandl** [tidyverse/ggplot2#5249]
Consider the following snippet
```r
require(ggplot2)

iris %>% ggplot(aes(Species, Species)) + geom_tile()
iris %>% ggplot(aes(Species)) + geom_bar()
```
**Observed**: It is using 2 different shades of gray as fill color irrespective of the rendering device, resulting in an inconsistent result (e.g. when combining both geoms in a report)
![image](https://user-images.githubusercontent.com/200952/227740726-83ea8dde-3664-47f8-a5b8-8ec598c0172f.png)
![image](https://user-images.githubusercontent.com/200952/227740736-0518506d-8e8e-4b27-bbe6-75b3d7f27ce2.png)

**Expected**: The fill color should be identical.

Affected version: 3.4.1

**Comment by teunbrand** [comment]
While I appreciate that this can be somewhat frustrating, if the default is changed, lots of plots are affected by this. Even though it would improve consistency, it is unlikely that these defaults will change, unless these changes are part of a major overhaul. 

In any case, there is always the option to set a fill colour in the layer, or use `update_geom_defaults()` to change the default in an R session.

**Comment by holgerbrandl** [comment]
As it is not very obvious how to tell what the default geom_bar color is, here's for future reference until this visual inconsistency may be addressed, the complete workaround:
```r
## figure what the actual default fill of geom_bar is
ggplot2:::check_subclass("bar", "Geom")$default_aes
# -> this tells us, it's grey35

## update geom_tile defaults in the current session 
update_geom_defaults("tile", list(fill = "grey35"))
```
