### ISSUE TITLE
`geom_violin()` warns that `weight` aesthetic dropped during statistical transformation

### ISSUE THREAD

**Issue by AroneyS** [tidyverse/ggplot2#5263]
Similar to https://github.com/tidyverse/ggplot2/issues/5053, `geom_violin()` also warns that weight is dropped, although it appears to be used as expected.

Reprex: (note that the two `geom_violin()` calls produce different outlines)

```r
library(ggplot2)

ggplot(mtcars, aes(wt, mpg)) +
  geom_point(aes(size = cyl)) +
  geom_violin(aes(weight = cyl)) +
  geom_violin()
```

**Comment by teunbrand** [comment]
Thanks for the report! I can confirm the bug. I really thought I had fixed this for most stats, but this one must've slipped the net.
