### ISSUE TITLE
Breaking change regarding lack of `discrete_range()` function

### ISSUE THREAD

**Issue by pablobernabeu** [tidyverse/ggplot2#5264]
Hello,

I would like to report a breaking change regarding the lack of the `discrete_range()` function. I'm only posting this in case that patching this breaking change is of interest and feasible. Otherwise, please feel free to close the issue. 

The error has appeared to me when trying to open a plot I created using `brms::mcmc_plot()`, which draws on ggplot2. When I created the plot last year, my version of ggplot2 was 3.3.5. The plot can still be opened with that version of ggplot2 loaded but not with the latest version. In the latter case, the following error appears: `Error in discrete_range() : could not find function "discrete_range"`. 

Please find the plot at https://github.com/pablobernabeu/language-sensorimotor-simulation-PhD-thesis/raw/main/lexicaldecision/bayesian_analysis/results/lexicaldecision_posteriordistributions_informativepriors_exgaussian.rds

Thank you very much for your attention

**Comment by thomasp85** [comment]
As a general rule you cannot save plot objects and assume they will work across ggplot2 versions as that would completely tie our hands when it comes to future development and bug fixes. The better approach is to save the code that produced the plot.

**Comment by pablobernabeu** [comment]
Thank you, Thomas. I did save everything possible, but not models that took up 15 GB each. Fortunately, backtracking to the original version of ggplot2 solves my issue. I'll keep in mind that backward compatibility is often impossible. I just didn't know to what extent.
