### ISSUE TITLE
Map graticules don't extend to limits

### ISSUE THREAD

**Issue by willgearty** [tidyverse/ggplot2#5265]
I've been trying to reproduce the [Interrupted Goode homolosine example here](https://wilkelab.org/practicalgg/articles/goode.html). Everything seems to work fine, except that the map graticules (lat and long) don't extend to the limits like they do in the example pictures (this is after following that vignette to the letter):
![image](https://user-images.githubusercontent.com/7232514/231467957-031e9413-97fc-4405-9ead-b9268a5d7e4c.png)

I know that coord_sf() uses sf::st_graticule() to generate the graticules, but something else must be going on here, because when I plot lines generated from st_graticule(), it looks great. So coord_sf() must have a bug in the way it handles/plots the graticule data from st_graticule(). Here's a minimal reprex:

```r
# with built-in graticules, graticules don't extend to plot limits
ggplot() +
    geom_sf(data = st_graticule(crs = "+proj=igh", lon = seq(-180, 180, 30), lat = seq(-90, 90, 30)), color = NA) +
    coord_sf(crs = "+proj=igh") +
    scale_x_continuous(NULL, breaks = c(seq(-180,180,30))) +
    scale_y_continuous(NULL, breaks = c(seq(-90,90,30))) +
    theme(panel.grid.major = element_line(color = "black"))
```
![image](https://user-images.githubusercontent.com/7232514/231468703-e9d02478-0cbc-4a61-837f-d3ae670ef739.png)

```r
# with st_graticule, lines extend to plot limits
ggplot() +
    geom_sf(data = st_graticule(crs = "+proj=igh", lon = seq(-180, 180, 30), lat = seq(-90, 90, 30))) +
    coord_sf(crs = "+proj=igh") +
    theme(panel.grid.major = element_blank())
```
![image](https://user-images.githubusercontent.com/7232514/231468773-5183eac0-b260-47c8-822e-b4e43d4cd9fb.png)

As far as I can tell, these two examples are intended to give the exact same visual output, but they don't.

**Comment by clauswilke** [comment]
I think this is somehow related to the limits of the plot. I'm not sure I understand exactly what's happening and I'd definitely appreciate somebody digging a little more deeply but just empirically the reprex you provided works if I set the limits just barely below the full range.

``` r
library(ggplot2)
library(sf)
#> Linking to GEOS 3.10.2, GDAL 3.4.2, PROJ 8.2.1; sf_use_s2() is TRUE

ggplot() +
  geom_sf(data = st_graticule(crs = "+proj=igh", lon = seq(-180, 180, 30), lat = seq(-90, 90, 30)), color = NA) +
  coord_sf(crs = "+proj=igh") +
  scale_x_continuous(NULL, breaks = c(seq(-180,180,30))) +
  scale_y_continuous(NULL, breaks = c(seq(-90,90,30), limits = c(-89.9, 89.9))) +
  theme(panel.grid.major = element_line(color = "black"))
```

![](https://i.imgur.com/g8LSs5P.png)

<sup>Created on 2023-04-12 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by clauswilke** [comment]
Note thought that this doesn't match with the problem you posted with your first image. Something else may be going on there.

**Comment by teunbrand** [comment]
It's not just the Goode homolosine that has quirks. The picture below from the [online docs](https://ggplot2.tidyverse.org/reference/ggsf.html#ref-examples) also missing a part of the graticule in the New Zealand / Polynesia direction. I very rarely make maps or use {sf}, so I'm struggling to see what causes this bug.

![this picture](https://ggplot2.tidyverse.org/reference/ggsf-2.png)

**Comment by teunbrand** [comment]
> I'm not sure I understand exactly what's happening

Just noticed this now, but I'm afraid that it might be a typo.

```r
breaks = c(seq(-90,90,30), limits = c(-89.9, 89.9)) # 1 vector to `breaks`
```
instead of
```r
breaks = seq(-90,90,30), limits = c(-89.9, 89.9) # 2 arguments
```

As far as I can tell, the limits are interpreted as whatever the CRS has set as the length unit (metres in this case, I think?). This is why the code without the typo produces a tiny, 180m wide slice around the equator.

**Comment by teunbrand** [comment]
Slightly off-topic, I think you might also be able to use `sf::st_intersection()` to get a decent looking goode homolosine.
Adapted from Claus' repo:

``` r
suppressPackageStartupMessages({
  library(sf)        # for manipulation of simple features objects
  library(rworldmap) # for getMap()
  library(ggplot2)
})

world_sf <- st_as_sf(getMap(resolution = "low"))
crs_goode <- "+proj=igh"

lats <- c(
  90, -90,
  -90, 0, 0, -90,
  -90, 0, 0, -90,
  -90, 0, 0, -90,
  -90, 90,
  90, 0, 0, 90,
  90
)

longs <- c(
  180, 180,
  80.01, 80.01, 79.99, 79.99,
  -19.99, -19.99, -20.01, -20.01,
  -99.99, -99.99, -100.01, -100.01,
  -180, -180,
  -40.01, -40.01, -39.99, -39.99,
  180
)

goode_outline <- 
  list(cbind(longs, lats)) |>
  st_polygon() |>
  st_segmentize(1) |>
  st_sfc(crs = "+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs")

sf_use_s2(FALSE)
#> Spherical geometry (s2) switched off
goode <- st_intersection(world_sf, goode_outline)
#> although coordinates are longitude/latitude, st_intersection assumes that they
#> are planar
#> Warning: attribute variables are assumed to be spatially constant throughout
#> all geometries
graticule <- goode_outline |>
  st_graticule(lon = seq(-180, 180, 30), lat = seq(-90, 90, 30)) |>
  st_intersection(goode_outline)
#> although coordinates are longitude/latitude, st_intersection assumes that they
#> are planar
#> Warning: attribute variables are assumed to be spatially constant throughout
#> all geometries

ggplot(goode) + 
  geom_sf(data = goode_outline, fill = NA) +
  geom_sf(data = graticule, colour = "grey80") +
  geom_sf() +
  coord_sf(crs = crs_goode) +
  theme(panel.grid = element_blank())
```

![](https://i.imgur.com/SWOzMbp.png)

<sup>Created on 2023-09-27 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by teunbrand** [comment]
I think the problem is that some breaks are out of bounds due to IGH projection.
I don't think there is something that ggplot2 can do with this, it is just a quirk of the projection I suppose.
We we shoose slightly narrower y-breaks, it renders just fine:

``` r
library(ggplot2)
library(sf)
#> Linking to GEOS 3.12.1, GDAL 3.8.4, PROJ 9.3.1; sf_use_s2() is TRUE

# with built-in graticules, graticules don't extend to plot limits
ggplot() +
  geom_sf(data = st_graticule(crs = "+proj=igh", lon = seq(-180, 180, 30), lat = seq(-90, 90, 30)), color = "transparent") +
  coord_sf(crs = "+proj=igh") +
  scale_x_continuous(NULL, breaks = c(seq(-180,180,30))) +
  scale_y_continuous(breaks = c(-89.1, seq(-60,60,30), 89.1)) +
  theme(panel.grid.major = element_line(color = "black"))
```

![](https://i.imgur.com/rwhHyEe.png)

<sup>Created on 2024-12-11 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>
