### ISSUE TITLE
Drawing error with geom_boxplot when logarithmic conversion of Y-axis

### ISSUE THREAD

**Issue by reallzg** [tidyverse/ggplot2#5276]
I found a problem, when I do the logarithmic axis conversion at the end of the code, the boxplot graph has an error, I think we should calculate the drawing data points of the boxplot before the logarithmic conversion。

I expected to improve the logarithmic axis conversion function, in addition to similar problems such as the calculation of the T test value added through the ggpubr package also has bugs.

Here is the code to reproduce the bug:

```r
library(ggplot2)

data <- data.frame(x='x',y=c(0.58,0.11,0.08,0.023,0.16,0.25,0.045,0.13,0.0063,0.4700))

pic <- ggplot(data,aes(x,y))+
  stat_boxplot(geom = 'errorbar',width=0.25)+
  geom_boxplot(outlier.shape = NA)+
  geom_point()
pic

pic + scale_y_log10()
```
![image](https://user-images.githubusercontent.com/42767622/233020324-16d27ece-ae87-4125-8e56-5c3cea7b9619.png)
![image](https://user-images.githubusercontent.com/42767622/233020461-78873d72-f67d-4e49-ba56-a0bb759f1f21.png)

**Comment by reallzg** [comment]
It can be found that the maximum value before the logarithmic conversion is an outlier, and there is no outlier after the logarithmic conversion.

**Comment by clauswilke** [comment]
Scale transformations are applied before statistical computations, and coordinate transformations are applied after. It looks like what you want is a coordinate transformation (though I would question why, it's not statistically sound in the case of a boxplot).

This is explained in detail in the book by Wilkinson: https://www.amazon.com/Grammar-Graphics-Statistics-Computing/dp/0387245448
