### ISSUE TITLE
No longer able to control the color of a hidden category on a legend

### ISSUE THREAD

**Issue by melissagwolf** [tidyverse/ggplot2#5280]
It is possible to hide a category from a legend by omitting it from the `breaks` argument within `scale_fill_manual`. In the past, it was possible to control the color of that hidden category by simply adding the color to the `values` argument. However, that no longer works. The category is hidden from the legend (expected action), but the color of the hidden category defaults to grey (unexpected action).

Here is the code to reproduce the bug:

```r
iris %>% 
  mutate(col=ifelse(Species=="setosa","Red","Hide")) %>% 
  ggplot(aes(x=Species,y=Sepal.Length,fill=col))+
  geom_boxplot()+
  scale_fill_manual(breaks = c("Red"),   #hide category "Hide" from the legend by omitting it from the breaks argument
                    values = c("red","white"))    #make the fill for the "Red" category red, and the "Hide" category white 

```

![image](https://user-images.githubusercontent.com/47953444/233530247-8e11a6fc-c323-4a09-8c6a-84da485576a4.png)

**Comment by smouksassi** [comment]
you can specify the value for na.value 
``` r
library(dplyr)
#> Warning: package 'dplyr' was built under R version 4.2.3
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
library(ggplot2)

iris %>% 
  mutate(col=ifelse(Species=="setosa","Red","Hide")) %>% 
  ggplot(aes(x=Species,y=Sepal.Length,fill=col))+
  geom_boxplot()+
  scale_fill_manual(breaks = c("Red"),   #hide category "Hide" from the legend by omitting it from the breaks argument
                    values = c("red","white"),
                    na.value ="white")    #make the fill for the "Red" category red, and the "Hide" category white 
```

![](https://i.imgur.com/Ug9RyE7.png)

<sup>Created on 2023-04-25 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by melissagwolf** [comment]
Thank you @smouksassi! This solved my issue.
