### ISSUE TITLE
How to use coord_cartesian() method instead of coord_sf() 

### ISSUE THREAD

**Issue by Nh-code** [tidyverse/ggplot2#5291]
Is there a way to use coord_cartesian method instead of coord_sf, so that the x, y axes can be freely stretched instead of fixed proportions?

I tried to use coord_cartesian() directly, but failed
![image](https://user-images.githubusercontent.com/79830573/234756834-f5da70f0-0df9-472d-ad9a-8991d1ea4214.png)

**Comment by teunbrand** [comment]
We try to use this issue tracker purely for bug reports and feature requests. This seems more like a question better suited to the 
[RStudio communit](https://community.rstudio.com/) or StackOverflow.

That said; officially: no. There is no way to have free aspect ratios with `coord_sf()`.

Unofficially, here are two ways:

``` r
library(ggplot2)
library(sf)
#> Linking to GEOS 3.9.3, GDAL 3.5.2, PROJ 8.2.1; sf_use_s2() is TRUE
library(grid)

nc <- sf::st_read(system.file("shape/nc.shp", package = "sf"), quiet = TRUE)
p <- ggplot(nc) +
  geom_sf(aes(fill = AREA))

# Option 1: edit gtable
gt <- ggplotGrob(p)
gt$respect <- FALSE
grid.newpage(); grid.draw(gt)
```

![](https://i.imgur.com/hZULYio.png)

``` r
# Option 2: subclass CoordSf
p + ggproto(NULL, coord_sf(), aspect = function(...) NULL)
```

![](https://i.imgur.com/i3SC5JA.png)

<sup>Created on 2023-05-08 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
