### ISSUE TITLE
size is used in annotation_logticks() instead of linewidth

### ISSUE THREAD

**Issue by slowkow** [tidyverse/ggplot2#5292]
I noticed ggplot2 is now producing warning messages:

```
Warning messages:
1: The `size` argument of `element_line()` is deprecated as of ggplot2 3.4.0.
ℹ Please use the `linewidth` argument instead.
This warning is displayed once every 8 hours.
Call `lifecycle::last_lifecycle_warnings()` to see where this warning was generated.
```

`annotation_logticks()` still uses `size` instead of `linewidth`:

https://github.com/tidyverse/ggplot2/blob/e0efd7b26531ffcc7437d9b9f4af9fa7ce504a16/R/annotation-logticks.R#L106

**Comment by teunbrand** [comment]
Thanks for the report: it indeed looks like an oversight on ggplot2's part.
