### ISSUE TITLE
Unchangeable x-axis text vertical adjustment when using scale_x_discrete(position = "top")

### ISSUE THREAD

**Issue by jsacerot** [tidyverse/ggplot2#5295]
I found a problem with the x-axis text vertical adjustment when using ```scale_x_discrete(position = "top")```. Changing ```vjust```/```margin``` in ```theme()``` does not work. 

Function code:
```
        plot.tile3 <- function(data, xorder, xlabels, yorder, axes, axtxtsize, title){
          ggplot(data = data, mapping = aes(x = factor(x = metric, levels = xorder, labels = xlabels), y = factor(x = parameter, levels = yorder), fill = values)) +
            geom_tile(colour = "white", size=0.25, alpha = 0.6) +
            coord_cartesian(clip = "off") +
            scale_x_discrete(position = "top") +
            scale_fill_gradient(low = "red", high = "darkgreen") +
            xlab(axes[1]) +
            ylab(axes[2]) +
            ggtitle(title) +
            theme_ipsum(base_size = axtxtsize) +
            theme(plot.margin = unit(c(2, 2, 2, 2), "mm"),
                  axis.text.x = element_text(size = axtxtsize, angle = 45, margin = margin(b = 10), debug = TRUE),
                  axis.title.x = element_text(size = axtxtsize),
                  axis.text.y = element_text(size = axtxtsize),
                  axis.title.y = element_text(size = axtxtsize),
                  plot.title = element_blank(),
                  plot.subtitle = element_blank(),
                  legend.position = "none")
        }
```
Function result:

![image](https://user-images.githubusercontent.com/57607681/235754170-473dc71c-b5ed-47ba-a426-0182a83ce7e5.png)

If I increase or decrease the bottom margin or the vjust value (or even both), the result is exactly the same.

Any suggestions on how to fix this?

Thank you!

**Comment by karawoo** [comment]
Change `axis.text.x ` to `axis.text.x.top` in your code. You can check out this talk for more info on how theme inheritance works, that's what's causing your issue. https://resources.rstudio.com/resources/rstudioglobal-2021/always-look-on-the-bright-side-of-plots/

**Comment by jsacerot** [comment]
Thank you, @karawoo I appreciate it.

**Comment by jsacerot** [comment]
@karawoo A quick question. Is it possible to set x-axis values on the top but keep the x-axis title on the bottom? Thanks!
