### ISSUE TITLE
`coord_cartesian()` should probably throw an error is `xlim` or `ylim` is length 1

### ISSUE THREAD

**Issue by DavisVaughan** [tidyverse/ggplot2#5297]
I accidentally ran this, and was rather confused for awhile until I realized I hadn't supplied an upper limit in `xlim`:

``` r
library(ggplot2)

df <- data.frame(
  x = 1:5,
  y = 2:6
)

ggplot(df, aes(x, y)) +
  geom_line() +
  coord_cartesian(xlim = 2)
#> Error in if (all(is.finite(continuous_range_coord)) && diff(continuous_range_coord) < : missing value where TRUE/FALSE needed
```

Could `coord_cartesian()`, or possibly something later on, throw an error if it doesn't get a length 2 `xlim` / `ylim`?

**Comment by teunbrand** [comment]
Thanks Davis! A similar suggestion was made here: https://github.com/tidyverse/ggplot2/pull/4894#issuecomment-1489037895, so hopefully this PR will fix this.

**Comment by teunbrand** [comment]
You're right, might be simplified to `vctrs::vec_check_size()` perhaps.

**Comment by teunbrand** [comment]
I'm gonna mark this as completed in #4894.
