### ISSUE TITLE
ggsave append new pages to pdf

### ISSUE THREAD

**Issue by wbvguo** [tidyverse/ggplot2#5303]
Hi, 

I want to use `ggsave` to save multiple plots into a single pdf file (a plot per page, and the size of each plot can be adjusted individually).  Currently, `ggsave` don't allow appending new pages, instead, it will overwrite if the file already exists. Is it possible to add an option `append=TRUE/FALSE` to `ggsave` when the device is set to be "pdf"? 

For example:
```
ggsave(filename = "test.pdf", plot = p1, device = "pdf", width = 8, height = 6)
ggsave(filename = "test.pdf", plot = p2, device = "pdf", width = 10, height = 10, append= TRUE)
```

Thanks,
Wenbin

**Comment by teunbrand** [comment]
Hi Wenbin,

It seems people agree with you: there is already a feature request to saved to paged pdf in #5093.
We'd like to keep all discussion in a single place, so I'm gonna close this issue, and we can continue discussion over there.
