### ISSUE TITLE
Testthat::expect_error seems to ignore ggplot errors

### ISSUE THREAD

**Issue by cjvanlissa** [tidyverse/ggplot2#5306]
I found a problem with error handling.

I expected `ggplot2` errors to be detected by `testthat::expect_error`, but they are not.

Here is the code to reproduce the bug:

```r
library(ggplot2)
library(testthat)
expect_error(ggplot(data = iris, aes(x = x, y = y)) + geom_point())
```

**Comment by thomasp85** [comment]
The error will only appear when rendered so you'd need to wrap the plot code in a `print()` call to trigger the error
