### ISSUE TITLE
horizontal justification with `label_wrap_gen()`

### ISSUE THREAD

**Issue by mps9506** [tidyverse/ggplot2#5309]
Hi,
I'm running into an issue with horizontal justification while using `label_wrap_gen()` to create line breaks in facet labels. In the example below, the facet label that is broken into multiple lines is not justified consistently with the other two facets. This appears similar to the fixed issue: https://github.com/tidyverse/ggplot2/issues/2478.

I recognize I can manually specify the line break. However, the `label_wrap_gen()` function is handy for iterating plots.

``` r
library(ggplot2)
library(dplyr)

df <- mtcars |> 
  mutate(labels = case_when(
    cyl == 8 ~ paste0(rep("This is a long label",5), collapse = ""),
    cyl == 6 ~ "This is a shorter label",
    cyl == 4 ~ "Even shorter"
  ))

ggplot(df) +
  geom_histogram(aes(mpg)) +
  facet_wrap(~labels,
             ncol = 1,
             labeller = labeller(labels = label_wrap_gen(50))) +
  theme(strip.text = element_text(hjust = 0.05))
#> `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
```

![](https://i.imgur.com/W2Msxcr.png)

<sup>Created on 2023-05-15 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by teunbrand** [comment]
If you'd want to offset the text a little bit to the right of the edge, I think it is preferable to use the `margin` argument and completely left-justify the text, e.g. `element_text(hjust = 0, margin = margin(4.4, 4.4, 4.4, 20))`.

**Comment by mps9506** [comment]
Thanks, completely forgot about `margin`. That works for my needs.
