### ISSUE TITLE
Cant make use of tidy context in scale_x/y_

### ISSUE THREAD

**Issue by Yann-C-INN** [tidyverse/ggplot2#5314]
Hello. I want to point out three ggplot-related issues that dont correspond with the tidy-philosophy:

**1 + 2: Cant make use of modified data**
```
library(tidyverse)
# Get a vertical interecept at the maximum point of filtered data
mtcars %>% filter(cyl > 4) %>% 
  ggplot(aes(x = mpg, y = qsec)) + geom_point()+
  geom_vline(xintercept = max(.data$mpg))

# Scale y-axis breaks according to filtered data
mtcars %>% filter(cyl > 4) %>%
  ggplot(aes(x = mpg, y = qsec)) + geom_point() + 
  scale_y_continuous(breaks = seq(min(.data$qsec),max(.data$qsec), length = 5)))
```
This code doesn't work (error below). In both cases I think there could be a recognition, even without the `.data$` that I am refering in a tidy way to my already assigned data (that is, a filtered mtcars)
```
Error:
! Can't subset `.data` outside of a data mask context.
Run `rlang::last_trace()` to see where the error occurred.
```
Why can't we simply pass the data frame (after we modified it for ggplot) as an argument and have R recognizing the variables in a tidy fashion?

**3: facet_wrap could be wayyy simpler**

```
mtcars %>% ggplot(aes(x = mpg, y = qsec)) + geom_point() +
  facet_wrap(~)
```

This is more of an improvement suggestion, when implementing facets, I would expect R to recognize the columns in my dataset, and offering them to me on top of the different args the function can take.
The '~' or using `vars()` is really redundent, the use-case of most users (all?) is very simple. to use a grouping feature to divide the plots.
<img width="247" alt="image" src="https://github.com/tidyverse/ggplot2/assets/130037694/e650434b-3c05-4400-ab83-1c2507596183">

I hope my issues are clear :)

**Comment by teunbrand** [comment]
You can make use of the data piped into ggplot2 if you use curly braces and insert `.` at the appropriate spots. This will cost you four symbols of extra typing, but you don't have to write `.data`, so it's a net neutral on code length in your example.

``` r
library(tidyverse)
mtcars %>% filter(cyl > 4) %>% {
  ggplot(., aes(x = mpg, y = qsec)) + geom_point() +
    geom_vline(xintercept = max(.$mpg))
}
```

The facet syntax is as clunky as it is due to historical choices. It seems it can't be improved without breaking a lot of people's plotting code.

**Comment by Yann-C-INN** [comment]
> 

Oh that's something I wasnt aware of. putting curly bracets outside of the entire plot. thanks

**Comment by teunbrand** [comment]
I realised this issue had been discussed in the past in for example #3268 and was decided against, so I'm going to close this issue for the same reason (requiring a breaking rewrite).

**Comment by Yann-C-INN** [comment]
One last thing. the {} methos works only with magritrr pipes (%>%) but not the base-R pipes (|>). Is it worth to ask to include base r pipes as well to work with this method? I switched to use them automatically with Ctrl + Shift + M
