### ISSUE TITLE
inconsistent line width of `geom_segment`

### ISSUE THREAD

**Issue by wbvguo** [tidyverse/ggplot2#5318]
Hi, 

Thanks for maintaining ggplot2. I used `geom_segment` to create customized ticks. However, I found some lines are thicker than others for some mysterious unknown reasons.

![image](https://github.com/tidyverse/ggplot2/assets/31968837/29ca57f3-62a6-49f4-b20d-759c7ce34a2d)

Could you please check this issue, or could you provide some hints about why such a strange phenomenon should happen? A simple reproducible example using the `iris` dataset can be found below:

```
ggplot(iris %>% mutate(group = as.factor(Sepal.Length))) +
  aes(x = group, y = Sepal.Width) +
  geom_boxplot(color = "blue", outlier.shape = NA) +
  geom_segment(aes(x = group, xend = group, 
                   y = 2, yend = 1), 
               color = "black")
```

Thanks,
Wenbin

**Comment by teunbrand** [comment]
These are anti-aliasing artefacts that occur because multiple lines are drawn on top on one another. If you deduplicate the datapoints the artefacts disappear. 

``` r
library(ggplot2)
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union

ggplot(iris %>% mutate(group = as.factor(Sepal.Length))) +
  aes(x = group, y = Sepal.Width) +
  geom_boxplot(color = "blue", outlier.shape = NA) +
  geom_segment(
    data = ~ subset(.x, !duplicated(group)),
    aes(x = group, xend = group, 
        y = 2, yend = 1), 
    color = "black"
  )
```

![](https://i.imgur.com/zhGownB.png)

<sup>Created on 2023-06-04 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by wbvguo** [comment]
Thank you, Teun!
