### ISSUE TITLE
adding a caption to labs results in an error (ggplot version 3.4.2)

### ISSUE THREAD

**Issue by UliSchopp** [tidyverse/ggplot2#5322]
In former versions it was prossible to add a caption to a plot. With version 3.4.2 this results in the following error
`Error in titleGrob(label, x, y, hjust = hj, vjust = vj, angle = angle,  : 
  unused argument (expand_y = TRUE)`

```
library(ggplot2)
basic <- ggplot(mtcars, aes(wt, mpg, colour = factor(cyl), shape = factor(vs) )) +
  geom_point() +
  labs(title = "A",
       caption = "Caption") 
basic
```

This is the result from ggplot2 version 3.4.1:
![Rplot](https://github.com/tidyverse/ggplot2/assets/91598443/b6395471-544d-4a56-bb6e-c443ccb36ad8)

**Comment by teunbrand** [comment]
I'm sorry I can't reproduce this with either version 3.4.2 or the current dev branch. Does this happens if you execute the code example in a new R session?

**Comment by UliSchopp** [comment]
Dear Teun, there’s no problem on an second machine with a different versions’ status of (many) packages. Perhaps this is not a problem of ggplot2 but of some packages used?

Well, I will not use the caption option on this machine …

Thanks
Uli



Dr. Ulrich Schoppmeier
Data Scientist
Institut für Medizinische Mikrobiologie und Hygiene
________________________________
***@***.******@***.***
Elfriede-Aulhorn-Str.6 | 72076 Tübingen
Tel. +49 (0)7071/29-69002
***@***.******@***.***>

Von: Teun van den Brand ***@***.***>
Gesendet: Mittwoch, 7. Juni 2023 18:24
An: tidyverse/ggplot2 ***@***.***>
Cc: Dr. Ulrich Schoppmeier ***@***.***>; Author ***@***.***>
Betreff: Re: [tidyverse/ggplot2] adding a caption to labs results in an error (ggplot version 3.4.2) (Issue #5322)


I'm sorry I can't reproduce this with either version 3.4.2 or the current dev branch. Does this happens if you execute the code example in a new R session?

**Comment by UliSchopp** [comment]
Dear Teun, with the latest R release (4.3.0) all works fine.

Thanks
Uli

Dr. Ulrich Schoppmeier
Data Scientist
Institut für Medizinische Mikrobiologie und Hygiene
________________________________
***@***.******@***.***
Elfriede-Aulhorn-Str.6 | 72076 Tübingen
Tel. +49 (0)7071/29-69002
***@***.******@***.***>

Von: Teun van den Brand ***@***.***>
Gesendet: Mittwoch, 7. Juni 2023 18:24
An: tidyverse/ggplot2 ***@***.***>
Cc: Dr. Ulrich Schoppmeier ***@***.***>; Author ***@***.***>
Betreff: Re: [tidyverse/ggplot2] adding a caption to labs results in an error (ggplot version 3.4.2) (Issue #5322)


I'm sorry I can't reproduce this with either version 3.4.2 or the current dev branch. Does this happens if you execute the code example in a new R session?

**Comment by teunbrand** [comment]
Thanks for checking!
