### ISSUE TITLE
geom_raster drops legend when col and fill aesthetics added

### ISSUE THREAD

**Issue by davidhodge931** [tidyverse/ggplot2#5324]
legend works with geom_tile when col then fill aesthetics added 

``` r
library(tidyverse)

#legend works with geom_tile
ggplot2::faithfuld |>
  head(10) |> 
  ggplot() +
  geom_tile(aes(x = waiting, y = eruptions, col = density, fill = density)) 
```

![](https://i.imgur.com/4KrzXrm.png)

legend does not work with geom_raster when col then fill aesthetics added 

``` r

#legend does not work with geom_raster
ggplot2::faithfuld |>
  head(10) |> 
  ggplot() +
  geom_raster(aes(x = waiting, y = eruptions, col = density, fill = density))
#> Warning in geom_raster(aes(x = waiting, y = eruptions, col = density, fill =
#> density)): Ignoring unknown aesthetics: colour
```

![](https://i.imgur.com/qMId3nf.png)

<sup>Created on 2023-06-15 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by davidhodge931** [comment]
Works if the order of aesthetics is fill then col, but not the other way around 
``` r
library(tidyverse)

#legend works if aesthetic order is fill then col
ggplot2::faithfuld |>
  head(10) |>
  ggplot() +
  geom_raster(aes(x = waiting, y = eruptions, fill = density, col = density))
#> Warning in geom_raster(aes(x = waiting, y = eruptions, fill = density, col =
#> density)): Ignoring unknown aesthetics: colour
```

![](https://i.imgur.com/JKx4enC.png)

<sup>Created on 2023-06-15 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by teunbrand** [comment]
Good catch! From some brief experimentation, it seems to be dropped due to the legend key data has `colour` as the aesthetics name after merging fill and colour guides, which then is discarded by the `guide_geom()`/`GuideColourbar$get_layer_key()`. I think this should be fixed in the `guide_merge()`/`GuideColourbar$merge()` step.
