### ISSUE TITLE
stat_ecdf() not currently working on provided examples on Ubuntu run RStudio server

### ISSUE THREAD

**Issue by mariadelmarq** [tidyverse/ggplot2#5336]
I found a problem with stat_ecdf().

I expected the provided examples to work, however I get the error: 
```
Warning: Computation failed in `stat_ecdf()`
Caused by error:
! attempt to apply non-function
```

Here is the code to reproduce the bug:

```r
# copy your code to the clipboard and run:
library(ggplot2)
set.seed(1)
df <- data.frame(
  x = c(rnorm(100, 0, 3), rnorm(100, 0, 10)),
  g = gl(2, 100)
)
ggplot(df, aes(x)) +
  stat_ecdf(geom = "step")
```
If I put it into reprex::reprex(), then it works, but if I try to run it in my RStudio server console, or within an RMarkdown file, I get the error described above. Is it possible I'm missing some Ubuntu library?

**Comment by teunbrand** [comment]
Hi there,

It seems unlikely that you'd need additional system libraries, calculating eCDFs should work. Does the problem occur when you run this code in a new R session or knit a very minimal Rmarkdown file?

**Comment by mariadelmarq** [comment]
Thanks for your response, @teunbrand . Yesterday it didn't work in the console, in a minimal Rmarkdown file, or even by clicking on "Run examples" in the help at the bottom right. Today it works! I have no idea what happened, so sorry to waste your time.
