### ISSUE TITLE
Documentation typo: `ymin` mentioned twice

### ISSUE THREAD

**Issue by fkohrt** [tidyverse/ggplot2#5339]
The documentation currently says:

https://github.com/tidyverse/ggplot2/blob/23508b321357502d014e52b8118ed1b0f9c5c164/R/position-stack.R#L259

But probably the second field has to be `ymax`?

**Comment by teunbrand** [comment]
Yeah that looks like a typo to me and the second should be `ymax`. If you're interested in preparing a PR, it would be welcome. If not, we'll fix it at some point.
