### ISSUE TITLE
Strip text on the same column as the axis text

### ISSUE THREAD

**Issue by oliviercailloux** [tidyverse/ggplot2#5344]
It is well known that long strip text can be a problem. Displaying them vertically hurts readability (if at all feasible). Displaying them horizontally _next to_ the axis text may make the figure too wide: horizontal space is usually much restricted, especially in publications.

One solution to this conundrum is to display the strip text on top of the axis text, rather than on the side of it. As in the following figure for example ([source](https://thorax.bmj.com/content/75/9/735#F3)).
![thoraxjnl-2020-September-75-9-735-F3 large](https://github.com/tidyverse/ggplot2/assets/1244880/4a63c713-5433-49cc-8fdb-820b6f9628b9)
What I mean here with "strip text" is "Yearly excacerbations", "Onset time", ... and by "axis text" is "One", "Two", "Three", "5 min", ...

Here is my closest attempt so far ([thanks](https://stackoverflow.com/a/76604269)) (I do not care at this stage about the colors or other aesthetic details, nor about the data, just about reproducing the overall layout).

```r
library(tidyverse)

df <- tribble(
  ~group, ~level, ~value, ~attribute,
  "g1", "some reference level", 1, "some long strip text",
  "g1", "another level", 2, "some long strip text",
  "g1", "zero units", 0, "another long strip text",
  "g1", "many units", 3, "another long strip text",
  "g1", "even more units", 4, "another long strip text",
  "g2", "some reference level", 3, "some long strip text",
  "g2", "another level", 1, "some long strip text",
  "g2", "zero units", 0, "another long strip text",
  "g2", "many units", 2, "another long strip text",
  "g2", "even more units", 3, "another long strip text"
)

ggplot(df, aes(x = value, y = factor(level))) +
  geom_col() +
  ggtitle("Title") +
  facet_grid(attribute~group, scales = "free_y", switch ="y") +
  ylab("") +
  xlab("Marginal utility") +
  theme_minimal() +
  theme(strip.placement = "outside",
        strip.text.y.left = element_text(angle = 0, face = "bold", vjust = 1, hjust = 1))
```
![result](https://github.com/tidyverse/ggplot2/assets/1244880/e8064b4b-5f6f-4874-ba9b-f43143e4ba55)

I would like to display "some long strip text" and "another long strip text" closer to the Y axis, on top of the axis text instead of to the left of it.

Considering the numerous discussions about this kind of situations (such as [here](https://github.com/tidyverse/ggplot2/issues/1231)), I have come to believe that it is currently not possible with ggplot2. Hence this feature request.

**Comment by teunbrand** [comment]
I do sympathise with the idea, but I think this might be better suited for an extension package that implements custom facets. 
I left a comment [here](https://stackoverflow.com/a/76632672/11374827) to not leave you entirely emptyhanded.
