### ISSUE TITLE
gradient scale is converted to discrete scale when changing scale order

### ISSUE THREAD

**Issue by BartJanvanRossum** [tidyverse/ggplot2#5360]
When changing the legend of a legend item with a gradient scale, the gradient scale is converted to a discrete scale. The example below shows this behavior for _colour_gradient2, but it also happens for other gradient scales. 

If a plot has multiple scales, i.e. when reordering becomes relevant, just specifying the order of non-gradient scales, leaves the scale intact, but specifying the order of the gradient scale causes the behavior in the example below. 

``` r
library(ggplot2)

set.seed(1)
df <- data.frame(
  x = runif(100),
  y = runif(100),
  z1 = rnorm(100)
)

ggplot(df, aes(x, y)) +
  geom_point(aes(colour = z1)) +
  scale_colour_gradient2()
```

![](https://i.imgur.com/4maLcRp.png)

``` r

ggplot(df, aes(x, y)) +
  geom_point(aes(colour = z1)) +
  scale_colour_gradient2() +
  guides(colour = guide_legend(order = 1))
```

![](https://i.imgur.com/xh8K64o.png)

<sup>Created on 2023-07-21 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

```

**Comment by smouksassi** [comment]
use guide_colorbar
``` r
library(ggplot2)
set.seed(1)
df <- data.frame(
  x = runif(100),
  y = runif(100),
  z1 = rnorm(100)
  )
ggplot(df, aes(x, y)) +
  geom_point(aes(colour = z1,shape="A")) +
  scale_colour_gradient2() +
  guides(colour = guide_colorbar(order = 1))
```

![](https://i.imgur.com/bbKblc7.png)

<sup>Created on 2023-07-22 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by teunbrand** [comment]
Indeed, as @smouksassi indicates. This is not really a bug as the scale remains continuous but displays a discrete legend. I can see how this is surprising if you're unfamiliar with different guide types though.
