### ISSUE TITLE
geom_line does not work with a text aesthetic

### ISSUE THREAD

**Issue by davidhodge931** [tidyverse/ggplot2#5373]
``` r
library(tidyverse)

ggplot2::economics |>
  mutate(text = glue::glue("Unemployment: {unemploy}")) |>
  ggplot(aes(x = date,y = unemploy)) +
  geom_line(aes(text = text))
#> Warning in geom_line(aes(text = text)): Ignoring unknown aesthetics: text
```

![](https://i.imgur.com/WMmXpaK.png)

<sup>Created on 2023-07-28 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by davidhodge931** [comment]
Requires group = 1 within the aes to work if a text aesthetic is added. Is fine without it, if a text aesthetic is not added

**Comment by teunbrand** [comment]
The warning tells you that `geom_line()` isn't supposed to work with a `text` aesthetic. Is this in any way related to how {plotly} uses such an aesthetic? Perhaps the larger issue here is that unrecognised aesthetics may influence the grouping even if they're not part of the proper geom. Mind that `?aes_group_order` mentions 'all discrete variables in the plot', not 'all discrete mappings used in a layer' in the context of default groups.

**Comment by davidhodge931** [comment]
Ah, grouping issue - thanks @teunbrand 

```
library(tidyverse)

p <- ggplot2::economics |>
  mutate(text = glue::glue("Unemployment: {unemploy}")) |>
  ggplot(aes(x = date,y = unemploy)) +
  geom_line(aes(text = text, group = 1))

plotly::ggplotly(p, tooltip = "text")
```
