### ISSUE TITLE
`linewidth` of `panel.border` is smaller than expect

### ISSUE THREAD

**Issue by bakerwm** [tidyverse/ggplot2#5382]
I found the `linewidth` of `panel.border` is not correctly displayed. It might be clipped.

Here is the code to reproduce the bug:

```r
> library(ggplot2)
> packageVersion("ggplot2")
[1] ‘3.4.2’
> ggplot(mtcars, aes(mpg, cyl)) + 
  geom_point(color = "black") +
  # theme_bw() +
  geom_vline(xintercept = 20, linewidth = 2, color = "orange") +
  geom_hline(yintercept = 6,  linewidth = 1, color = "black") +
  theme(
    panel.border = element_rect(linewidth = 2, fill = NA, color = "red"),
    axis.line.x  = element_line(linewidth = 2, color = "blue"),
    axis.ticks.y = element_line(linewidth = 2, color = "darkgreen")
  )
```

![ggplot2 panel border linwidth](https://github.com/tidyverse/ggplot2/assets/1317927/ba8ed417-1ed2-4b6c-b99b-b0ebfeae1167)

**Comment by teunbrand** [comment]
The border linewidth is indeed clipped to the panel. You can turn this off by using `coord_cartesian(clip = "off")`.

**Comment by bakerwm** [comment]
> The border linewidth is indeed clipped to the panel. You can turn this off by using `coord_cartesian(clip = "off")`.

Thanks for you reply, the `panel.border` displays correctly, when setting the `clip=off`. 

I got another problem when I want to plot some slop lines, the end of the line extended the `panel.border` if setting `clip=off` option.

It appears that half of the border line was clipped when setting `clip=on`.

Here are the codes:

```
df <- data.frame(x = 1:3, y = 1:3)

p1 <- ggplot(df, aes(x, y)) + 
  geom_point(color = "black") +
  geom_abline(slope = 1, intercept = c(log10(2), -log10(2)), linewidth = 1) +
  coord_cartesian(clip = "off") + 
  ggtitle("clip=off") +
  theme(
    panel.border = element_rect(linewidth = 2, fill = NA, color = "red"),
    axis.line.x  = element_line(linewidth = 2, color = "blue")
  )


p2 <- ggplot(df, aes(x, y)) + 
  geom_point(color = "black") +
  geom_abline(slope = 1, intercept = c(log10(2), -log10(2)), linewidth = 1) +
  coord_cartesian(clip = "on") +
  ggtitle("clip=on") +
  theme(
    panel.border = element_rect(linewidth = 2, fill = NA, color = "red"),
    axis.line.x  = element_line(linewidth = 2, color = "blue")
  )

patchwork::wrap_plots(p1, p2)
```

![image](https://github.com/tidyverse/ggplot2/assets/1317927/68e23cf2-f664-492e-9a38-c4b029bc0ad7)

**Comment by clauswilke** [comment]
You can leave clipping on and just double the linewidth.

**Comment by bakerwm** [comment]
> You can leave clipping on and just double the linewidth.

Thanks. This solution is fine anyway.
