### ISSUE TITLE
`facet_grid(scales = "free")` not working

### ISSUE THREAD

**Issue by jromanowska** [tidyverse/ggplot2#5384]
I found a problem with `facet_grid` when setting `scales` argument to `"free"`.

I expected both, x and y, vary between the panels of the plot, but only one of them vary.

Here is the code to reproduce the bug (using the code from examples in documentation of `facet_grid`):

```r
mt <- ggplot(mtcars, aes(mpg, wt, colour = factor(cyl))) +
   geom_point()
# first - checking the fixed scales:
mt + facet_grid(vars(cyl), scales = "fixed") # all fine
# checking other 'free' options:
mt + facet_grid(vars(cyl), scales = "free_y") # all fine
mt + facet_grid(vars(cyl), scales = "free_x") # not working
mt + facet_grid(vars(cyl), scales = "free")  # not working
```

**Comment by smouksassi** [comment]
try using facet_wrap
mt + facet_wrap(vars(cyl), scales = "free",ncol=1)  #

**Comment by jromanowska** [comment]
Thank you, but I actually need the grid - in my work, I want to stratify by two variables and I would like to see varying x and y scales in each of the small panels.

**Comment by smouksassi** [comment]
this is not how facet_grid is designed as it is no longer a grid if you vary both
hard to help you without understanding fully what you are really trying to do.

**Comment by jromanowska** [comment]
OK, I understand, I will try another way to achieve my goal. Thank you for your time!
