### ISSUE TITLE
Unicode characters between U+20C0 and U+214F inclusive do not render (Windows, R v4.3.1, ggplot2 v3.4.2)

### ISSUE THREAD

**Issue by GMSL1** [tidyverse/ggplot2#5386]
When using the `\uxxxx` command in strings to label axes, I noticed a range of unicode characters that render as squares instead of the desired symbol. These characters are in the range U+20C0 and U+214F inclusive (ie. the previous character that works is U+20BF and the next that works is U+2150). This is occurring on Windows 10 with R v4.3.1 and ggplot2 v3.4.2. I also tried R v4.2.3 with ggplot2 v3.4.1 and even R v3.6.1 with ggplot2 v3.3.0 and the issue was the same with all of them.

As a reproducible example:
```r
testplot <- ggplot() +
  labs(x = "\u20c0")
```

This produces a blank plot where, for me, the x-axis label is simply a square, not the symbol for the Kyrgyz som which is expected.

**Comment by teunbrand** [comment]
The typesetting of text is mostly under control of the graphics device. These squares are substitutes for glyphs that are missing in a fontfile. I can recommend giving the {ragg} device a try, but ultimately ggplot2 doesn't do any font handling, so I'm going to close this issue for that reason.
