### ISSUE TITLE
theme_classic axis texts

### ISSUE THREAD

**Issue by MjelleLab** [tidyverse/ggplot2#5387]
I wonder if there's is bug in the latest ggplot2 causing axis labels to not show when using theme_classic() ?

**Comment by teunbrand** [comment]
Axis labels seems to show up just fine.

``` r
library(ggplot2)

ggplot(mpg, aes(displ, hwy)) +
  geom_point() +
  theme_classic()
```

![](https://i.imgur.com/ntsTUeD.png)

<sup>Created on 2023-08-15 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by MjelleLab** [comment]
Solved by R restart an machine restart.
