### ISSUE TITLE
Throw an error or warning when mapping to a variable not in `data` (if length > 1)

### ISSUE THREAD

**Issue by eliocamp** [tidyverse/ggplot2#5391]
Would it be possible/desirable to make this kind of usage a warning or an error?

``` r
library(ggplot2)

cylinders <- mtcars$cyl

ggplot(mtcars, aes(cylinders)) +
  geom_density()
```

I've seen many beginner write this mistake. They create a new variable outside the data.frame and then use it as data. It would be very helpful if ggplot2 could detect it and issue a warning. 

I'm not sure if this would break a lot of existing code. In case there are legitimate uses, maybe ggplot2 could export a particular function to let users explicitly use external variables along these lines:

```r
ggplot(mtcars, aes(external(cylinders))) +
  geom_density()
```

Something like this could allow advanced usages that might not be possible otherwise and guard regular users against this common issue.

**Comment by mjskay** [comment]
Can I vehemently vote against this? In the modern tidyverse version of aes(), it is consistent that expressions in aes() follow the same rules as other functions that use data masking. Having aes() be different would be surprising. 

Plus this would add syntactic noise to valid constructions (eg any expressions involving a data column and an external variable, like a constant).

**Comment by eliocamp** [comment]
I'd be fine if constants (length 1 vectors) are allowed, since that's a natural use case. 

I don't understand what you mean by `aes()` being consistent with data masking, though.

**Comment by teunbrand** [comment]
I think the trade-off here isn't worth it. There are valid use-cases for using orphan variables that don't exist in a data.frame in the mapping. I'd also argue that the beginners aren't wrong per se; there are just cleaner ways that are recommended.

**Comment by teunbrand** [comment]
Just to give a brief example of a valid use-case:

```r
ggplot(mtcars, aes(disp, mpg)) +
  geom_text(aes(label = rownames(mtcars)))
```

Arguably one should make the rownames a proper column in the data, but we don't live in a perfect world, so it is convenient to make it slightly less of a struggle.

**Comment by teunbrand** [comment]
Sorry Elio I'm going to close this issue as it is unlikely that ggplot2 is going to change this behaviour. Thanks for your ideas though!
