### ISSUE TITLE
`warn_for_aes_extract_usage()` fails if data has rownames

### ISSUE THREAD

**Issue by eliocamp** [tidyverse/ggplot2#5392]
This should raise a warning, but it doesn't. 

``` r
library(ggplot2)

ggplot(mtcars, aes(mtcars$cyl)) +
  geom_density() 
```

![](https://i.imgur.com/807OuVu.png)

It actually works if we remove rownames

``` r
rownames(mtcars) <- NULL
ggplot(mtcars, aes(mtcars$cyl)) +
  geom_density() 
#> Warning: Use of `mtcars$cyl` is discouraged.
#> ℹ Use `cyl` instead.
```

![](https://i.imgur.com/hiMBUBS.png)

<sup>Created on 2023-08-15 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

The issue, I think, is here:

https://github.com/tidyverse/ggplot2/blob/8af03a9ed95cd2299afc4354090597aa59080f1c/R/aes.R#L437-L440

where `data_eval` and `data` have different row names so `identical(data_eval, data)` returns `FALSE`.

**Comment by teunbrand** [comment]
Thanks for the report, it indeed seems weird.
