### ISSUE TITLE
variables in package function didn't work properly with {{}}

### ISSUE THREAD

**Issue by gaospecial** [tidyverse/ggplot2#5393]
I have wrote three functions as according to the official guidelines in [Using ggplot2 in packages](https://ggplot2.tidyverse.org/articles/ggplot2-in-packages.html).

```r
#' @importFrom ggplot2 ggplot geom_boxplot aes
myplot1 = function(data, x = "group", y = "weight"){
  ggplot(data, aes({{ x }}, {{ y }})) +
    geom_boxplot()
}

#' @importFrom ggplot2 ggplot geom_boxplot aes_string
myplot2 = function(data, x = "group", y = "weight"){
  ggplot(data, aes_string(x, y)) +
    geom_boxplot()
}

#' @importFrom ggplot2 ggplot geom_boxplot aes
#' @importFrom rlang .data
myplot3 = function(data, x = "group", y = "weight"){
  ggplot(data, aes(.data[[x]], .data[[y]])) +
    geom_boxplot()
}
```

All these functions are designed to have identical results. However, they don't.

```r
data("PlantGrowth")
myplot1(PlantGrowth)
myplot2(PlantGrowth)
myplot3(PlantGrowth)
```

![image](https://github.com/tidyverse/ggplot2/assets/107597/a6a6e500-502f-4b35-916d-caecafe04f89)

I'am wondering whether I am wrong with coding of `myplot1()`. Please give me some feedback.

**Comment by thomasp85** [comment]
In the first case you are passing in strings which makes the call equivalent to 

```r
ggplot(data, aes("group", "weight")) +
    geom_boxplot()
```

which is not correct code

You should not pass in the aesthetics as strings but as unquoted expressions (i.e. how you would write them inside `aes()`)

**Comment by gaospecial** [comment]
> In the first case you are passing in strings which makes the call equivalent to
> 
> ```r
> ggplot(data, aes("group", "weight")) +
>     geom_boxplot()
> ```
> 
> which is not correct code
> 
> You should not pass in the aesthetics as strings but as **unquoted expressions (i.e. how you would write them inside `aes()`)**

Yes, you are right. `myplot1(PlantGrowth, x = group, y = weight)` works for me.

Thanks for your immediate response!
