### ISSUE TITLE
Layered violin plot

### ISSUE THREAD

**Issue by chipsin87** [tidyverse/ggplot2#5395]
Recently the SHAP for python team has released layered violin plots which are fantastic. I would like to use similar plots in R.

Below is an image and link to the sort of plots they are producing

![Screenshot_20230820-221841.png](https://github.com/tidyverse/ggplot2/assets/86592890/bad2d23a-a6da-4dff-9a61-8e7714668b64)

https://shap.readthedocs.io/en/latest/example_notebooks/api_examples/plots/violin.html

**Comment by yutannihilation** [comment]
Thanks for sharing. As the name suggests, I believe "layered violin plot" is what you can draw by layering multiple violin plots. So, I think there's no feature that needs to be added to ggplot2 in order to support this plot. I'm closing this, but feel free to correct me if I'm wrong!

**Comment by chipsin87** [comment]
The purpose of the violin plot for SHAP is to display both the SHAP value on the x-axis, coloured by the feature value which may be a combination of positive and negative values (irrespective of the sign of the SHAP values)

In the example graphic, there appears to be continuous colouring within the violin plots reflecting the feature values within in the violin plot (so this appears to be more than just using multiple violin plots for different positive/ negative thresholded value ranges).

**Comment by thomasp85** [comment]
You are right that it appears to be more than just violin plots placed on top of each other. However, the plot type seems intimately linked to the interpretation of model output and thus not really fitting for ggplot2. Such a geom should be made available in an extension package

**Comment by yutannihilation** [comment]
> there appears to be continuous colouring within the violin plots

Thanks for the details. It seems I was wrong in that ggplot2 doesn't have the functionality to draw gradient fill. But, anyway I also think this should be implemented in an extension package.

**Comment by chipsin87** [comment]
I will definitely be hitting extension packages up. In saying this, I can think of a lot of use cases for colouring a violin plot by a secondary variable in the form of a gradient. For example, when doing exploratory data analysis it can be really useful to colour input variables by a target variable.
