### ISSUE TITLE
geom_point() with size < 0.5 have same area

### ISSUE THREAD

**Issue by DasHammett** [tidyverse/ggplot2#5397]
I found a problem with `geom_point()` when trying to plot points with sizes smaller than 0.5. No matter what size I choose, the area of the plotted point looks like the same size as 0.5. This is problematic when plotting points into a map, where sometimes you need very small points.

I have tried several shapes, but the same issue is present for all the shapes.

In the reprex, if you look at the points below 0.5, they all have the same area.

I expected the area of the points to scale accordingly

Here is the code to reproduce the bug:

```r
library(ggplot2)
ggplot(data.frame(x = seq(0, 2, length.out = 30))) +
geom_point(aes(x = x, y = 0, size = x), stroke = 0,   shape = 21, fill = "black") +
scale_size_identity() 
```

**Comment by teunbrand** [comment]
I understand the frustration, but it seems like this is a limitation in the {grid} package that ggplot2 uses to draw the graphics.
In other words, I don't think there is much that ggplot2 can do to resolve this issue.

If it is of any help, you can set `shape = "."` to draw the smallest point available.

To reproduce in {grid}:

``` r
library(grid)

pts <- pointsGrob(
  x = unit(seq(0.1, 0.9, length.out = 30), "npc"),
  y = unit(rep(0.5, 30), "npc"),
  size = unit(seq(0, 2, length.out = 30), "mm"),
  pch = 21,
  gp = gpar(lwd = 0, fill = "black")
)
grid.newpage()
grid.draw(pts)
```

![](https://i.imgur.com/wxJnZJR.png)

<sup>Created on 2023-08-23 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by DasHammett** [comment]
Hi, 
Thanks for the explanation, I guess there little to be done. But for example you can draw lines thinner than 0.5 with `linewidth`, so it should be "feasible" to also draw points that small?

**Comment by clauswilke** [comment]
@DasHammett Are you rendering to postscript or pdf? I believe those drivers set minimum point sizes and line widths.

**Comment by DasHammett** [comment]
Hi @clauswilke 
I am rendering to pdf using Cairo_pdf. (Windows OS, I can try Linux as well later on).

This reprex show the difference between line and point:
```
library(ggplot2)
ggplot(data.frame(x = seq(0, 2, length.out = 30), y = 10)) + 
    geom_line(aes(x = x, y = 10), linewidth = 0.15) + 
    geom_point(x = 2, y = 10, size = 0.15)
````
![image](https://github.com/tidyverse/ggplot2/assets/13760961/a83fb781-7ad2-47fc-8055-62f1ee068306)

**Comment by clauswilke** [comment]
Try varying the line width and you'll similarly see there's a lower bound below which lines don't get any thinner.

**Comment by DasHammett** [comment]
Hi all, 

I have been able to solve the issue by using the `ragg` graphics device (https://github.com/r-lib/ragg). Now when I export to pdf, *without the cairo option*, the points are the correct size.
