### ISSUE TITLE
Multiple Y-axis text and facet labels rendered as single objects in PDF

### ISSUE THREAD

**Issue by mattgalbraith** [tidyverse/ggplot2#5398]
When saving a plot as PDF using ggsave, 
eg `ggsave(filename = "plot.pdf", device = cairo_pdf, width = 15, height = 5, units = "in")`
the Y-axis text labels are rendered as a single object with spacing between characters used to align with tick marks.
![image](https://github.com/tidyverse/ggplot2/assets/46791232/a7ceecfd-9fd4-437a-8240-493dfb9a43a1)

This sometimes, but not always, happens with facet labels, linking the labels for multiple facets into a single text object.
![image](https://github.com/tidyverse/ggplot2/assets/46791232/165bbadc-4821-4851-959e-00f84b265cf1)

This is a pain when needing to change font sizes in external editors as the spacing changes, requiring manual creation of separate text objects.
Is there any way to force these to render as individual objects?

**Comment by teunbrand** [comment]
I also had this problem at some point, which I (mostly) fixed by using svgs/{svglite} instead of pdf.
In any case, this is not something that ggplot2 has direct control over.

**Comment by mattgalbraith** [comment]
Thanks for the suggestion, the svgs indeed have each label rendered as a separate text object.
Unfortunately there are clipping masks all over the place which also hampers post-processing.

**Comment by teunbrand** [comment]
I agree that some devices are too zealous with clipping masks, but that is a device decision that ggplot2 doesn't control, so I'll close this issue as we cannot fix this in ggplot2.
