### ISSUE TITLE
update_geom_defaults of size parameter for line stopped working with a recent version

### ISSUE THREAD

**Issue by fredcallaway** [tidyverse/ggplot2#5399]
I unfortunately don't know which version I had before, but previously I was able to use this to set a default line width:
```
update_geom_defaults("line", list(size = 2))
```

After updating to 3.4.3, this doesn't have any effect on geom_line. Using `linewidth = 2` works fine, so it's not really a usability issue—but I can imagine the change confusing other people.

Full example
```
library(ggplot2)
update_geom_defaults("line", list(size = 2))
ggplot(cars, aes(speed, dist)) + geom_line()
```

**Comment by teunbrand** [comment]
Indeed, in line-based geoms, `size` as an aesthetic has been superseded by the `linewidth` aesthetic. See also the news entry:

https://github.com/tidyverse/ggplot2/blob/c76b9aeda648e9b6022b7169021e854c3d3890cb/NEWS.md?plain=1#L233-L239

This is all working as intended, so it is just a matter of people getting used to this I suppose.
