### ISSUE TITLE
Error in loadNamespace(i, c(lib.loc, .libPaths())) :    there is no package called ‘munsell’

### ISSUE THREAD

**Issue by cfranko** [tidyverse/ggplot2#540]
I updated the ggplot2 package in RStudio from the CRAN repo and loading the library gives the following error.  This is the first time I've had an issue loading the library.

Error in loadNamespace(i, c(lib.loc, .libPaths())) : 
  there is no package called ‘munsell’
Error: package/namespace load failed for ‘ggplot2’

**Comment by shwetamrit** [comment]
Hi,i am also not able to load swirl,plz  help me.

 install.packages("swirl", dependencies=TRUE)
Installing package into ‘C:/Users/Shweta/Documents/R/win-library/3.2’
(as ‘lib’ is unspecified)
trying URL 'http://ftp.iitm.ac.in/cran/bin/windows/contrib/3.2/swirl_2.2.21.zip'
Content type 'application/zip' length 132378 bytes (129 KB)
downloaded 129 KB

package ‘swirl’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
        C:\Users\Shweta\AppData\Local\Temp\Rtmpsngb6l\downloaded_packages
> library(swirl)
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called ‘R6’
Error: package or namespace load failed for ‘swirl’
> install.packages("evaluate")
Installing package into ‘C:/Users/Shweta/Documents/R/win-library/3.2’
(as ‘lib’ is unspecified)

**Comment by hadley** [comment]
@shwetamrit please ask for help at the swirl site

**Comment by msusplugas** [comment]
Is it possible to add the package munsell as a dependency in the DESCRIPTION file? It's a dependency because we need it to use ggplot2. Thanks

**Comment by thomasp85** [comment]
Munsell is not a dependency of ggplot2 and should therefore not be placed under Depends. The package is imported by scales which is in turn imported by ggplot2. Unless something has gone wrong during installation all nested imports should be installed when installing ggplot2.

**Comment by sahanb** [comment]
I am trying to load the library "DiagrammeR". But gettinng the below error.
install.packages("DiagrammeR", dependencies = TRUE)
library('DiagrammeR')
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  there is no package called 噌ML・Error: package or namespace load failed for 船iagrammeR・

**Comment by Y0Landa** [comment]
I am trying to run this code 
....
....
```
library(rminer)

df[which(df$CO.GT.==-200),]$CO.GT. <- NA
length(which(is.na(df$CO.GT.)))

M <- mean(na.omit(df$CO.GT.))
df <- imputation ("value",df,"CO.GT.",value=M)
print(summary(df$CO.GT.))
```

but I am getting the error below, I already tried install dependencies, but he always return about the "strucchange" and "method imputation not found"





**Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  there is no package called ‘strucchange’**
In addition: Warning message:
package ‘rminer’ was built under R version 3.3.3 
Error: package or namespace load failed for ‘rminer’
> 
> df[which(df$CO.GT.==-200),]$CO.GT. <- NA
Error in `$<-.data.frame`(`*tmp*`, "CO.GT.", value = NA) : 
  replacement has 1 row, data has 0
> length(which(is.na(df$CO.GT.)))
[1] 1797
> M <- mean(na.omit(df$CO.GT.))
> df <- imputation ("value",df,"CO.GT.",value=M)
**Error: could not find function "imputation"**

**Comment by seymakalay** [comment]
‘broom’ in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):
Does anyone know the solution for this?
many thanks in advance
