### ISSUE TITLE
Inconsistent "missing values" warning for geom_line()

### ISSUE THREAD

**Issue by jonspring** [tidyverse/ggplot2#5405]
```
library(ggplot2) # using v3.4.2 or 3.4.3
ggplot(data.frame(x = 1:5, y = c(1, 2, -10, 4, 5)), aes(x, y)) +
  geom_point() +
  geom_line() +
  scale_y_continuous(limits = c(0, 10))
```
![Rplot230](https://github.com/tidyverse/ggplot2/assets/18709859/d1c77d62-dc51-4c29-9b8e-46b1ec9fe69c)
```
Warning message:
Removed 1 rows containing missing values (`geom_point()`). 
```
The `geom_point` warning makes sense since the middle point is excluded from the range. But two of the four segments of `geom_line` that an unsuspecting user might expect are missing, with no warning. I'm not sure what the proper behavior here should be, but one row of data (and its two related segments) was excluded from the `geom_line` layer.

(Inspired by this SO post with much larger example data and unexpectedly low number of reported missing values for their geom_line layer.  https://stackoverflow.com/questions/77023161/ggplot2removed-xx-rows-containing-missing-values-lower-value-than-expected#comment135785599_77023161)

**Comment by yutannihilation** [comment]
> I'm not sure what the proper behavior here should be

This is the supposed behavior. For zooming purpose, `coord_cartesian()` is what you want.

``` r
library(ggplot2)
ggplot(data.frame(x = 1:5, y = c(1, 2, -10, 4, 5)), aes(x, y)) +
  geom_point() +
  geom_line() +
  coord_cartesian(ylim = c(0, 10))
```

![](https://i.imgur.com/sm593Kx.png)

<sup>Created on 2023-09-03 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by jonspring** [comment]
To clarify, I was raising a question about the "warning" reporting being inconsistent for `geom_line`, unrelated to the well-documented difference between setting limits in coord_cartesian vs. scale_y_continuous.

**Comment by yutannihilation** [comment]
Ah, yes. Probably, what you didn't notice is that splitting the line by `NA` is definitely the intended usage? I think there's no way to distinguish `NA`s intentionally embedded in the data and ones that are introduced by such an internal processing like scale.

**Comment by jonspring** [comment]
Is there a reason the warning for geom_line should work differently?

Here's a variation
```
ggplot(data.frame(x = 1:5, y = c(1, 2, -10, 4, NA)), aes(x, y)) +
  geom_point() +
  geom_line() +
  scale_y_continuous(limits = c(0, 10))
```

This results in the warning below. The geom_point warning notes the missing data from the out-of-range -10 point and from the NA point. The `geom_line` warning only notes the missing NA point. Is this intentional?
```
Warning messages:
1: Removed 2 rows containing missing values (`geom_point()`). 
2: Removed 1 row containing missing values (`geom_line()`).
```

**Comment by yutannihilation** [comment]
Sorry, I misunderstood a bit. Let me clarify.

> Is there a reason

I believe the reason is that `NA` is the sentinel value to split the line. As I described above, `NA`s are not distinguished whether it comes from the original data or from some internal transformation.

``` r
library(ggplot2)

ggplot(data.frame(x = 1:5, y = c(1, 2, NA, 4, 5)), aes(x, y)) +
  geom_point() +
  geom_line()
#> Warning: Removed 1 row containing missing values or values outside the scale range
#> (`geom_point()`).
```

![](https://i.imgur.com/gCQj6DD.png)

The warning of `geom_line()` you showed is because the `NA` is tail of the group, which should be meaningless in terms of splitting the line.

``` r
ggplot(data.frame(x = 1:3, y = c(1, 2, NA)), aes(x, y)) +
  geom_point() +
  geom_line()
#> Warning: Removed 1 row containing missing values or values outside the scale range
#> (`geom_point()`).
#> Warning: Removed 1 row containing missing values or values outside the scale range
#> (`geom_line()`).
```

![](https://i.imgur.com/aTlTgvY.png)

<sup>Created on 2023-09-03 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by jonspring** [comment]
I think I am understanding that. I still have my original observation, which is that `geom_line` often warns of fewer missing observations than it excludes. As best I can tell, it only reports missing rows when they correspond to a contiguous set of missing rows (either due to being NA or created for out-of-range points) at either end of the line, but does not report on missing rows that are bookmarked by non-missing rows. I would think it would be more consistent and helpful to report the number of rows that are excluded.

For instance, if we had data like these in `y` in my example, it would result in the following warnings. These first two are what I'd expect:

```
c(1,2,3,2,1)  # no warning
c(NA,2,3,NA,NA)
Warning messages:
1: Removed 3 rows containing missing values (`geom_point()`). 
2: Removed 3 rows containing missing values (`geom_line()`). 
```

But in these next two examples, it's not obvious to me what end is served by using a warning count for geom_line that only respects the missing values at the bookends. Curious to understand the use cases where this would be the desired behavior.

```
c(1, NA, NA, NA, 1) 
Warning messages:
# Removed 3 rows containing missing values (`geom_point()`). 

c(NA,2,NA,NA,1)
Warning messages:
1: Removed 3 rows containing missing values (`geom_point()`). 
2: Removed 1 row containing missing values (`geom_line()`).
```
