### ISSUE TITLE
Using stage with non-scaled aesthetics

### ISSUE THREAD

**Issue by thomasp85** [tidyverse/ggplot2#5408]
Somewhat contrived example but able to solve real issues in gganimate:

```r
data <- data.frame(test=1:3, x = 0, y = 0)
ggplot(data, aes(x=x, y=y)) +
    geom_text(aes(label=stage(test, after_scale = format(label, digits = 3))))
# Error in `geom_text()`:
# ! Problem while mapping stat to aesthetics.
# ℹ Error occurred in the 1st layer.
# Caused by error in `stage()`:
# ! object 'test' not found
```

This surprisingly happens while looking for a default scale for `label` in `layer$map_statistic()`

**Comment by teunbrand** [comment]
Appears to be that `eval_tidy()` is called on the staged expression at a point where the `test` column in the original data is no longer available. Would it be safe to skip adding default scales for staged expressions that do not have an `after_stat` argument?

**Comment by thomasp85** [comment]
See #5409 

`add_default()` is overly complicated
