### ISSUE TITLE
Relaxing requirement for >=rlang-1.1.0 to 1.0.6

### ISSUE THREAD

**Issue by mmokrejs** [tidyverse/ggplot2#5421]
Hi,
  when trying to install some app on `R-3.4.4` I cannot install `ggplot2` because at the best I manually managed to install `rlang-1.06`. But, `ggplot2-3.4.3` requires `>=rlang-1.1.1` which in turn requires `>=R-3.5.0`. If possible, please try to relax the requirement.

  Seems I might succeed with `ggplot2-2.2.1` from 2016-12-30 (which seems unnecessarily old) if I install dependencies ‘plyr’ and ‘reshape2’. With `reshape2` I am failing during loading of the package, it has compiled fine but  loading the module fails.

Thank you,
Martin

**Comment by teunbrand** [comment]
Hi Martin,

The tidyverse packages, which include ggplot2, have the policy to support up to 4 previous versions of R.
The current minimal version that is supported is R 3.6.0, so R 3.4.4 falls outside the supported versions. 
For more information on the supported version, see [here](https://www.tidyverse.org/blog/2019/04/r-version-support/).

The {rlang} package is an important dependency of ggplot2 and newer features introduced in rlang 1.1.0 are used as well.
In brief, we have reasons for this requirement and are not ambitious to support older R versions.
I understand this can be frustrating, but it is unlikely that we'll fulfil this request.

Best,
Teun

**Comment by yutannihilation** [comment]
So, maybe it's time to bump the R version requirement?

https://github.com/tidyverse/ggplot2/blob/954924b87bc7d8524745bcf742ef79e39d528e19/DESCRIPTION#L31

**Comment by teunbrand** [comment]
@yutannihilation yeah that is a good point.

**Comment by mmokrejs** [comment]
Hi @teunbrand ,
  thank you for your answer. I understand if you really use the new features, it is fine. Would you mind telling which is the last ggplot2 version working on R-3.4 series?
Thnaks.

**Comment by yutannihilation** [comment]
@mmokrejs 
v3.3.6 was the latest version in the R 4.1 era, which means R 3.4 was within the "4 previous versions" rule, so I guess this should work at least. Note that, this doesn't mean it works with all the dependencies at the latest versions.

https://github.com/tidyverse/ggplot2/releases/tag/v3.3.6

Anyway, thanks for letting us know ggplot2 doesn't work on R 3.4.
