### ISSUE TITLE
Map_data needs an update with country names

### ISSUE THREAD

**Issue by pardisaci** [tidyverse/ggplot2#5433]
in map_data feature of ggplot, Türkiye is still Turkey. Could we please update this? as I produce maps for a company, it does not make turkish people happy to still see the old name of country on the maps

**Comment by teunbrand** [comment]
Thank you for raising this consideration. The `map_data()` function is a wrapper around `maps::map()`, so ggplot2 has very little control over the data that is returned as it is provided by the {maps} package. If you'd like to propose a change in the output that {maps} produces, it is probably best to re-file this issue in that package.
