### ISSUE TITLE
geom_bar() not respecting factor levels created by fct_na_value_to_level()

### ISSUE THREAD

**Issue by jtr13** [tidyverse/ggplot2#5439]
I am trying to replicate this behavior produced by the deprecated function `forcats::fct_explict_na()` in which factor levels are made explicit (values --> levels) in order to control their order:

``` r
library(tidyverse)
df <- data.frame(animal = factor(c(NA, "ant", "ant", NA, "bee", "cat", NA)))
df |> 
  mutate(animal = fct_explicit_na(animal, "NA")) |> 
  ggplot(aes(y = fct_relevel(animal, "NA"))) +
           geom_bar()
#> Warning: There was 1 warning in `mutate()`.
#> ℹ In argument: `animal = fct_explicit_na(animal, "NA")`.
#> Caused by warning:
#> ! `fct_explicit_na()` was deprecated in forcats 1.0.0.
#> ℹ Please use `fct_na_value_to_level()` instead.
```

![](https://i.imgur.com/TxFQPBa.png)

<sup>Created on 2023-09-26 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

A similar formulation with `forcats::fct_na_value_to_level()` doesn't work:

``` r
library(tidyverse)
df <- data.frame(animal = factor(c(NA, "ant", "ant", NA, "bee", "cat", NA)))
df |> 
  mutate(animal = fct_na_value_to_level(animal)) |> 
  ggplot(aes(y = fct_relevel(animal, NA))) +
  geom_bar()
```

![](https://i.imgur.com/tpXrG7c.png)

<sup>Created on 2023-09-26 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

Not sure if this is a **ggplot2** or **forcats** issue but guessing the former since `fct_na_value_to_level()` does appear to work correctly:

``` r
library(forcats)
df <- data.frame(animal = factor(c(NA, "ant", "ant", NA, "bee", "cat", NA)))
fct_relevel(fct_na_value_to_level(df$animal), NA)
#> [1] <NA> ant  ant  <NA> bee  cat  <NA>
#> Levels: <NA> ant bee cat
```

<sup>Created on 2023-09-26 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

I'm using **ggplot2** 3.4.3 and **forcats** 1.0.0.

**Comment by teunbrand** [comment]
I think NA levels/values are dropped by default. You can keep the dropped levels with `scale_y_discrete(drop = FALSE)` in your example.

**Comment by jtr13** [comment]
@teunbrand That's not true. As you can see in the examples, the NA level was not dropped. NAs are dropped by default for continuous data, not discrete.

**Comment by jtr13** [comment]
Got it, thanks for the clarification. It seems that the source of the issue is that `fct_na_value_to_level()` creates a true `NA` factor level whereas `fct_explicit_na()` doesn't, so with the latter the new faux NA level isn't dropped:

``` r
library(forcats)
df <- data.frame(animal = factor(c(NA, "ant", "ant", NA, "bee", "cat", NA)))
fct_relevel(fct_na_value_to_level(df$animal), NA)
#> [1] <NA> ant  ant  <NA> bee  cat  <NA>
#> Levels: <NA> ant bee cat
fct_relevel(fct_explicit_na(df$animal, "NA"), "NA")
#> Warning: `fct_explicit_na()` was deprecated in forcats 1.0.0.
#> ℹ Please use `fct_na_value_to_level()` instead.
#> This warning is displayed once every 8 hours.
#> Call `lifecycle::last_lifecycle_warnings()` to see where this warning was
#> generated.
#> [1] NA  ant ant NA  bee cat NA 
#> Levels: NA ant bee cat
```

<sup>Created on 2023-09-27 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by teunbrand** [comment]
I'm going to close this issue, as this behaviour does not seem to depend on ggplot2, but on scales/forcats.
