### ISSUE TITLE
`is.atomic(NULL)` now returns `FALSE` on R-devel

### ISSUE THREAD

**Issue by yutannihilation** [tidyverse/ggplot2#5447]
I found the CI with R-devel runner started to fail with a real error, not the timeout. Actually, [the CRAN check](https://cran.r-project.org/web/checks/check_results_ggplot2.html) now fails with the same error:

```
     ══ Failed tests ════════════════════════════════════════════════════════════════
     ── Failure ('test-aes-calculated.R:50:3'): make_labels() deprases mappings properly ──
     make_labels(aes(x = NULL)) (`actual`) not identical to list(x = "x") (`expected`).
    
     `actual$x`: "NULL"
     `expected$x`: "x"
     ── Error ('test-aes.R:29:3'): aes_q() & aes_string() preserve explicit NULLs ───
     Error in `FUN(X[[i]], ...)`: Aesthetic must be a one-sided formula, call, name, or constant.
     Backtrace:
     ▆
     1. ├─base::suppressWarnings(expect_equal(aes_q(NULL), aes(NULL))) at test-aes.R:29:2
     2. │ └─base::withCallingHandlers(...)
     3. ├─testthat::expect_equal(aes_q(NULL), aes(NULL))
     4. │ └─testthat::quasi_label(enquo(object), label, arg = "object")
     5. │ └─rlang::eval_bare(expr, quo_get_env(quo))
     6. └─ggplot2::aes_q(NULL)
     7. └─base::lapply(mapping, as_quosure_aes)
     8. └─ggplot2 (local) FUN(X[[i]], ...)
     9. └─cli::cli_abort("Aesthetic must be a one-sided formula, call, name, or constant.")
     10. └─rlang::abort(...)
     ── Failure ('test-aes.R:102:3'): labelling doesn't cause error if aesthetic is NULL ──
     p$labels$x (`actual`) not identical to "x" (`expected`).
    
     `actual`: "NULL"
     `expected`: "x" 
```

I'm not sure, but I'm suspecting this breaking change [NEWS](https://cran.r-project.org/doc/manuals/r-devel/NEWS.html) is somehow related.

> `is.atomic(NULL)` now returns `FALSE`, as `NULL` is not an atomic vector. Strict back compatibility would replace `is.atomic(foo)` by `(is.null(foo) || is.atomic(foo))` but should happen sparingly only.

This seems commit:

https://github.com/wch/r-source/commit/c97dbd1444c917e0e633794bc1f4f1e6fc0b3297

**Comment by teunbrand** [comment]
Thanks for posting this! Thomas was informed that this would change soon in R-devel, so that we can release a hotfix to patch this (see https://github.com/tidyverse/ggplot2/issues/5437#issuecomment-1735574531).  Now that it is implemented, we can start testing solutions.

**Comment by yutannihilation** [comment]
Oh, sorry, this was the very reason for the patch release! Sorry, I overlooked the comment (and the announcement on the R-devel mailing list). Then, I'm closing this issue in favor of it.
