### ISSUE TITLE
geom_* functions do not allow for specific messages/warnings to be suppressed

### ISSUE THREAD

**Issue by davidhodge931** [tidyverse/ggplot2#5460]
``` r
library(tidyverse)
#> Warning: package 'ggplot2' was built under R version 4.3.1
#> Warning: package 'purrr' was built under R version 4.3.1
#> Warning: package 'dplyr' was built under R version 4.3.1
#> Warning: package 'lubridate' was built under R version 4.3.1
library(palmerpenguins)

p <- penguins |> 
  ggplot() +
  geom_smooth(aes(flipper_length_mm, body_mass_g))

p
#> `geom_smooth()` using method = 'loess' and formula = 'y ~ x'
#> Warning: Removed 2 rows containing non-finite values (`stat_smooth()`).
```

![](https://i.imgur.com/In0rnGq.png)

``` r
suppressMessages(p)
#> `geom_smooth()` using method = 'loess' and formula = 'y ~ x'
#> Warning: Removed 2 rows containing non-finite values (`stat_smooth()`).
```

![](https://i.imgur.com/TH9R7zk.png)

``` r
suppressWarnings(p)
#> `geom_smooth()` using method = 'loess' and formula = 'y ~ x'
#> Warning: Removed 2 rows containing non-finite values (`stat_smooth()`).
```

![](https://i.imgur.com/1DWEx5v.png)

``` r

p <- penguins |> 
  ggplot() +
  geom_histogram(aes(flipper_length_mm))

suppressMessages(p)
#> `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
#> Warning: Removed 2 rows containing non-finite values (`stat_bin()`).
```

![](https://i.imgur.com/zzZxvOb.png)

``` r
suppressWarnings(p)
#> `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
#> Warning: Removed 2 rows containing non-finite values (`stat_bin()`).
```

![](https://i.imgur.com/pvTpDRE.png)

``` r

p <- penguins |> 
  ggplot() +
  geom_point(aes(flipper_length_mm, body_mass_g))

suppressWarnings(p)
#> Warning: Removed 2 rows containing missing values (`geom_point()`).
```

![](https://i.imgur.com/oktJL0M.png)

<sup>Created on 2023-10-08 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by teunbrand** [comment]
The messages/warnings are able to be suppressed, just not in the way you've build the examples.
If you use the following in the console:
```r
suppressMessages(p)
```
What is essentially happening off-screen is the following:
```r
result <- suppressMessages(p)
print(result)
```
Since no message was generated during the assignment of `p` to `result`, there is nothing to suppress. Instead, the messages are being generated at the `print(result)` step. To suppress these, use the following:
```
suppressMessages(print(p))
```

**Comment by davidhodge931** [comment]
Oh okay, so it is only possible to suppress *all* messages related to the plot when you print it?

You cannot suppress a specific message related to the geom (e.g. the bins = 30 message) where printing a plot might produce multiple other messages?

**Comment by teunbrand** [comment]
To my knowledge: yes, but I also know that there are details that may or may not conflict with this that aren't covered by my knowledge.

**Comment by davidhodge931** [comment]
Cool, thanks @teunbrand - makes sense. This seems like it is unlikely to be able to be fixed easily, so I'll close - but feel free to reopen if you think

**Comment by davidhodge931** [comment]
It's strange because the scale functions act differently in that they print messages/warnings when the code is compiled rather than when the plot is rendered

``` r
library(tidyverse)
#> Warning: package 'ggplot2' was built under R version 4.3.1
#> Warning: package 'purrr' was built under R version 4.3.1
#> Warning: package 'dplyr' was built under R version 4.3.1
#> Warning: package 'lubridate' was built under R version 4.3.1
library(palmerpenguins)

p <- penguins |> 
  ggplot() +
  geom_smooth(aes(flipper_length_mm, body_mass_g)) +
  scale_x_continuous() +
  scale_x_continuous() 
#> Scale for x is already present.
#> Adding another scale for x, which will replace the existing scale.

p 
#> `geom_smooth()` using method = 'loess' and formula = 'y ~ x'
#> Warning: Removed 2 rows containing non-finite values (`stat_smooth()`).
```

![](https://i.imgur.com/JXsFK6e.png)

``` r

suppressMessages(p)
#> `geom_smooth()` using method = 'loess' and formula = 'y ~ x'
#> Warning: Removed 2 rows containing non-finite values (`stat_smooth()`).
```

![](https://i.imgur.com/GFJ3Dzz.png)

<sup>Created on 2023-10-08 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by teunbrand** [comment]
Yes, some conditions can be known from the input that is given, like when `breaks` and `labels` are of different length. On the other hand, some conditions are data-dependent, such as the model choice in `geom_smooth()`.

**Comment by davidhodge931** [comment]
Thanks, it'd seem like the smooth and histogram messages are not specific to the data.

I think it'd be better if messages and warnings were provided during compiling if possible.

Feel free to close if you think this is not fixable or worth fixing

**Comment by teunbrand** [comment]
> Thanks, it'd seem like the smooth and histogram messages are not specific to the data.

The smooth message depends on the number of rows in the data. The histogram message can only be thrown in `stat_bins()` because `geom_histogram()` doesn't control those parameters, hence they're checked during the building of the plot (agreed it is not necessarily data dependent, but availability of parameters dependent).

> I think it'd be better if messages and warnings were provided during compiling if possible.

I disagree, messages and warnings should be thrown as soon as they can be so people don't always need to go through the printing process to find out they've mis-specified something.

> Feel free to close if you think this is not fixable or not worth fixing

Yeah I think everything is working as intended, so I don't think there is anything to fix here.
