### ISSUE TITLE
Putting up `fortify()` methods for adoption?

### ISSUE THREAD

**Issue by teunbrand** [tidyverse/ggplot2#5469]
Currently, ggplot2 hosts some `fortify()` methods for objects from packages that do not come with the standard R distribution.
Examples of these include the fortify methods that live in `fortify-spatial.R`, `fortify-multcomp.R` and `fortify-map.R`.
To my understanding, these methods exist in ggplot2 because before the advent of extension packages, these *had* to live in ggplot2. However, ggplot2 has become highly extensible now, which means that specialised functionality could live elsewhere.
Therefore, it might be worth exploring whether we should put these methods up for adoption into extension packages.

It might be a good idea to include @terrytangyuan in the conversation for his thoughts and maybe probe if {ggfortify} has any interest in hosting these methods.

**Comment by terrytangyuan** [comment]
Thanks for the mention. Those fortify methods look suitable in {ggfortify} if their implementations do not involve using any {ggplot2} internal methods. It would be great if anyone would like to contribute these to {ggfortify}.
