### ISSUE TITLE
`[[.ggproto` has atypical argument names

### ISSUE THREAD

**Issue by teunbrand** [tidyverse/ggplot2#5474]
This is really a minor thing, but the `[[.ggproto()` function has `name` as the index argument instead of `i`.
This is fine for everyday use of `[[`-indexing, but becomes a mild annoyance when trying to programmatically extract something from a list of ggproto objects.

``` r
library(ggplot2)

# Simple function for extracting the same thing from a list of things
extract <- function(x, what) {
  lapply(x, `[[`, i = what)
}

# Works fine
x <- list(list(limits = c(NA, NA)), list(limits = c("A", "B")))
extract(x, "limits")
#> [[1]]
#> [1] NA NA
#> 
#> [[2]]
#> [1] "A" "B"

x <- list(
  scale_x_continuous(limits = c(NA, NA)), 
  scale_color_brewer(limits = c("A", "B"))
)
extract(x, "limits")
#> Error in `[[.ggproto`(X[[i]], ...): unused argument (i = "limits")

# Can fix this by changing `i` to `name`
lapply(x, `[[`, name = "limits")
#> [[1]]
#> [1] NA NA
#> 
#> [[2]]
#> [1] "A" "B"
```

<sup>Created on 2023-10-11 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by mjskay** [comment]
Since the `[[` primitive ignores the names of arguments and only considers position, I'd think the correct idiom in both cases would be <code>lapply(x, \`[[\`, what)</code>?

```r
> x = list("a")
> `[[`(x, 1)
[1] "a"
> `[[`(x, i = 1)
[1] "a"
> `[[`(x, name = 1)
[1] "a"
> `[[`(i = 1, x)
Error in 1[[x]] : invalid subscript type 'list'
```

**Comment by teunbrand** [comment]
Yeah you make a fair point, let's just close this.
