### ISSUE TITLE
Version 3.4.4 NEWS Typo

### ISSUE THREAD

**Issue by matthewjnield** [tidyverse/ggplot2#5478]
The NEWS entry for the release of version 3.4.4 at [https://cran.rstudio.com/web/packages/ggplot2/news/news.html](https://cran.rstudio.com/web/packages/ggplot2/news/news.html) and [https://cran.r-project.org/web/packages/ggplot2/news/news.html](https://cran.r-project.org/web/packages/ggplot2/news/news.html) includes the following:

"the upcoming retirement of rproj, rgeos, and maptools"

I believe that this was meant to say:

"the upcoming retirement of rgdal, rgeos, and maptools"

I do not see a place to change this in the "NEWS.md" file in this repository, so rather than submitting a pull request I am noting it here in this issue so that it can be corrected in the relevant place.

**Comment by matthewjnield** [comment]
@teunbrand I realized that the place to fix this is simply on a separate branch of this repository, not in some separate repository that I couldn't see, so I have submitted pull request #5479 to fix it; feel free to close it if someone has already taken care of this.

**Comment by teunbrand** [comment]
I'm closing this issue as fixed by #5479.
