### ISSUE TITLE
Faint lines through colour steps guide segments when `even.steps = FALSE`

### ISSUE THREAD

**Issue by jimjam-slam** [tidyverse/ggplot2#5481]
This reprex actually comes from the current ggplot2 3.4.4 docs for `guide_colorsteps`, where it is visible:

```r
df <- expand.grid(X1 = 1:10, X2 = 1:10)
df$value <- df$X1 * df$X2

  p <- ggplot(df, aes(X1, X2)) + geom_tile(aes(fill = value))
```

```r
# By default each bin in the guide is the same size irrespectively of how
# their sizes relate in data space
p + scale_fill_binned(breaks = c(10, 25, 50))
```

![image](https://github.com/tidyverse/ggplot2/assets/6520659/ad05158b-d2cb-4b33-81df-66dc18c7a9b8)

```r
# This can be changed with the `even.steps` argument
p + scale_fill_binned(
  breaks = c(10, 25, 50),
  guide = guide_coloursteps(even.steps = FALSE))
```

![image](https://github.com/tidyverse/ggplot2/assets/6520659/10fba36e-d04c-4ffa-8409-42e732a13e87)

When I run this code on ggplot 3.4.4, I can't see the faint lines at low-resolution outputs, but if I run, ggsave at, say, `width = 1920, height = 1080, units = 'px'`, or with SVG output, they're definitely visible. Mapping `colour` to the same variable as `fill` hides the lines from the tiles themselves but not from the colour bar (unless there's a way to merge the fill and colour guides rather than hiding one?).

**Comment by teunbrand** [comment]
The lines in the coloursteps guide (and rectangles in the main panel) appear to be anti-aliasing artifacts from drawing the guide as a series of small rectangles. Anti-aliasing settings depends on the device, so there isn't a lot ggplot2 can do on that front. 

However, I don't see why `guide_coloursteps()` couldn't just draw a single rectangle between limits/breaks, so I'm going to consider this issue a feature request for an option like this.
