### ISSUE TITLE
cut_number(m, n) : Insufficient data values to produce bins.

### ISSUE THREAD

**Issue by garyzhubc** [tidyverse/ggplot2#5487]
What is the logic behind cut_number? Is it possible when I have 6 unique datapoints but still cannot produce the respective number of cuts? What is a more robust way of doing this?

**Comment by teunbrand** [comment]
Hi there, we use the issue tracker to keep tabs on bugs and feature requests. If you have a question, you'd get a better chance of getting an answer on <https://stackoverflow.com/> or <https://community.rstudio.com/>.

**Comment by smouksassi** [comment]
refer to the source code to read the logic:
https://github.com/tidyverse/ggplot2/blob/bf0c64faabb962fc9d8f0426fe434c903a28ffdd/R/utilities-break.R#L32
https://github.com/tidyverse/ggplot2/blob/bf0c64faabb962fc9d8f0426fe434c903a28ffdd/R/utilities-break.R#L95
