### ISSUE TITLE
geom_line with mapped linewidth has ugly line joins

### ISSUE THREAD

**Issue by banbh** [tidyverse/ggplot2#5491]
When a `geom_line` has a variable linewidth the joins between the individual line segments are either ugly or nonexistent. The problem can be observed by running the code below: the blue line (which has constant linewidth) looks as expected (and good), while the red line (which has a linewidth that varies slightly) does not look as expected (and looks ugly).

By the way, I suspect the problem is that joining rectangles of varying widths is tricky. Indeed, should they even be rectangles or trapezoids? So perhaps this is actually a feature a request.

```r
library(ggplot2) # ggplot2_3.4.2

data.frame(x = seq(0, 15, len = 50)) |> 
  ggplot(aes(x)) +
  geom_line(aes(y = sin(x), linewidth = 10 + 1e-6*x), alpha = .5, color = 'red') +
  geom_line(aes(y = sin(x) + 1, linewidth = 10 + 0*x), alpha = .5, color = 'blue') +
  scale_linewidth_identity()
```
![image](https://github.com/tidyverse/ggplot2/assets/5741/7cb7c602-560a-4690-ae0e-6252c7afc25c)

**Comment by clauswilke** [comment]
This is a limitation of the grid graphics library. It cannot draw lines that change in width or color along the way. Unfortunately there's nothing that can be done at the ggplot2 level.

**Comment by smouksassi** [comment]
you might want to have a look at:
https://www.stat.auckland.ac.nz/~paul/Reports/VWline/vwline-intro/power-curve.html
https://cran.r-project.org/web/packages/vwline/
https://github.com/Hy4m/ggvwline

**Comment by banbh** [comment]
> you might want to have a look at: https://www.stat.auckland.ac.nz/~paul/Reports/VWline/vwline-intro/power-curve.html https://cran.r-project.org/web/packages/vwline/ https://github.com/Hy4m/ggvwline

Thank you! I was literally experimenting with `ggvwline`! As an example this package produces the grey line in the plot below.

```r
tibble(x = seq(0, 15, len = 50), y = sin(x)) |> 
  ggplot(aes(x, alpha = .5)) +
  geom_line(aes(y = y, linewidth = 10 + 1e-6*x, color = 'variable')) +
  geom_line(aes(y = y + 1, linewidth = 10 + 0*x, color = 'constant')) +
  geom_vwline(aes(y = y + 2, width = (10 + 1*x)/2), color = NA) +
  scale_linewidth_identity() +
  scale_alpha_identity()
```

![image](https://github.com/tidyverse/ggplot2/assets/5741/5b679545-ce10-48b6-acfa-8ee7d3e60404)
