### ISSUE TITLE
 A question about `theme_xx()` and `theme()`

### ISSUE THREAD

**Issue by Rong-Zh** [tidyverse/ggplot2#5501]
> `library(tidyverse)`
> platform : Windows 10 x64 build 19045
> ggplot2: 3.4.4

> the title of the figure is correctly displayed in center with the following code
```r 
iris %>% ggplot(aes(Sepal.Width, Petal.Length, color = Species)) +
  geom_point() +
  labs(title = "Test") +
  theme_test() +
  theme(plot.title = element_text(hjust = 0.5))
```
> `theme_test()` is used after the `theme()`, the title of the figure incorrectly appears on the left.
> the title of the figure should be centered. 

``` r 
iris %>% ggplot(aes(Sepal.Width, Petal.Length, color = Species)) +
  geom_point() +
  labs(title = "Test") +
  theme(plot.title = element_text(hjust = 0.5)) +
  theme_test()
```
<img src="https://github.com/tidyverse/ggplot2/assets/74701628/9f73e4d6-4b74-4637-90bc-a688bff3eb8c" alt="appendix" width="500" height="700" >

**Comment by teunbrand** [comment]
The order of operations matter, so in your second plot, `theme_test()` is overriding anything you might have declared in `theme()` before. In any case, this issue tracker is to report bugs or request features. For questions or help, try the [community](https://community.rstudio.com/) or [stackoverflow](https://stackoverflow.com/).
