### ISSUE TITLE
Should `geom_raster()` fall back  to `geom_rect()` under non-linear coordinates?

### ISSUE THREAD

**Issue by teunbrand** [tidyverse/ggplot2#5503]
The following code fails:

``` r
library(ggplot2)
#> Warning: package 'ggplot2' was built under R version 4.3.1

ggplot(faithfuld, aes(eruptions, waiting, fill = density)) +
  geom_raster() +
  coord_polar()
#> Error in `geom_raster()`:
#> ! Problem while converting geom to grob.
#> ℹ Error occurred in the 1st layer.
#> Caused by error in `draw_panel()`:
#> ! `geom_raster()` only works with `coord_cartesian()`
```

<sup>Created on 2023-10-30 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

While it shouldn't be too far-fetched to use `geom_rect()`'s drawing method to render this under non-linear coordinate systems. We could throw an informative message saying that we cannot render the data as a raster.

**Comment by dieghernan** [comment]
Hi @teunbrand, could it be possible to make `geom_raster` still work with `coord_sf`? Just asking since it would break a lot of **tidyterra** (and possibly **ggspatial**) functionalities. 

See https://github.com/dieghernan/tidyterra/issues/179

Just asking

**Comment by teunbrand** [comment]
I think it does work with `geom_sf()` through a fallback to `geom_rect()`, doesn't it? Do you have an example of what should work but currently doesn't with the dev version?

**Comment by Breeze-Hu** [comment]
Like a culprit, I raised several pertinent questions that led to the confusion. 🤣 They're all problems I've had. 

https://github.com/tidyverse/ggplot2/issues/6382 (**Plotting spatial rasters from tabular data**)

and https://github.com/dieghernan/tidyterra/issues/179  (**geom_spatraster plots raster data directly from `terra`**)

**Comment by teunbrand** [comment]
So what is the preferred solution then? Should or shouldn't we try to convert pixels to rectangles in `coord_sf()`? If we don't convert, should we still attempt to draw a raster or throw an error instead? If we still want to draw a raster, how valid is that approach for weird projections?
