### ISSUE TITLE
Computed `prop` is hard to use.

### ISSUE THREAD

**Issue by teunbrand** [tidyverse/ggplot2#5505]
This issue was first brought to my attention by @yjunechoe a while back, and thought it was salient enough to merit an issue.
In `stat_count()` there is a computed variable `prop` that is basically the count divided by the total count in the group.
Because the default group is the interaction between all discrete variables, this makes vanilla-use of `prop` a bit pointless:

``` r
library(ggplot2)
#> Warning: package 'ggplot2' was built under R version 4.3.1
p <- ggplot(diamonds, aes(cut, fill = color)) +
  geom_bar(aes(y = after_stat(prop)), position = "dodge")
p
```

![](https://i.imgur.com/rgEKwZz.png)

It only starts making sense if you manually set groups:

``` r
p + aes(group = color)
```

![](https://i.imgur.com/uZLRS2l.png)

However, you cannot compute the proportion within a position:

``` r
p + aes(group = cut)
#> Warning: The following aesthetics were dropped during statistical transformation: fill
#> ℹ This can happen when ggplot fails to infer the correct grouping structure in
#>   the data.
#> ℹ Did you forget to specify a `group` aesthetic or to convert a numerical
#>   variable into a factor?
```

![](https://i.imgur.com/Vgzfksd.png)

<sup>Created on 2023-11-02 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

And there are variants of `prop` one might be interested in:

* ~~Group-wise proportion~~ (basically current `prop`)
* Position-wise proportion (difficult to compute as user)
* Panel-wise proportion (difficult to compute as user)
* Proportion of total (can easily be computed by `aes(y = after_stat(count / sum(count)))`)

So the suggestion here is to add the last 3 variants as `prop_position`, `prop_panel` and `prop_total` (or `prop_layer`) as new computed variables to `stat_count()`.

**Comment by larmarange** [comment]
Just for the history of the discussion, a similar was raised in the past: #3369 

`stat_prop()` is an alternative proposition, implemented in `ggstats`: https://larmarange.github.io/ggstats/articles/stat_prop.html and https://larmarange.github.io/ggstats/reference/stat_prop.html

Denominators are here defined according to a `by` aesthetic

**Comment by teunbrand** [comment]
Thanks for the history @larmarange! I hadn't realised this has been discussed several times before.
I'll guess I'll just leave some solutions to find for the next people to raise this issue:

```r
library(ggplot2)
p <- ggplot(diamonds, aes(cut, fill = color)) +
  geom_bar(position = "dodge")

# Proportion per group
p + aes(y = after_stat(prop), group = color)

# Proportion of total
p + aes(y = after_stat(count / sum(count)))

# Proportion per x-position
p + aes(y = after_stat(count / ave(count, x, FUN = sum)))

# Proportion per panel
p + aes(y = after_stat(count / ave(count, PANEL, FUN = sum))) +
  facet_wrap(~ carat > 0.7)

# Proportion per panel and x position
p + aes(y = after_stat(count / ave(count, x, PANEL, FUN = sum))) +
  facet_wrap(~ carat > 0.7)

# Proportion per panel and fill
p + aes(y = after_stat(count / ave(count, fill, PANEL, FUN = sum))) +
  facet_wrap(~ carat > 0.7)
```

**Comment by teunbrand** [comment]
Or with some extra rlang spice:

``` r
library(ggplot2)
#> Warning: package 'ggplot2' was built under R version 4.3.1

as.prop <- function(what, ...) {
  what / ave(what, ..., FUN = function(x) sum(abs(x)))
}

prop_by <- function(...) {
  dots <- rlang::enquos(...)
  if (length(dots) == 0) {
    expr <- rlang::expr(after_stat(count / sum(count)))
    return(expr)
  }
  expr <- lapply(dots, rlang::quo_get_expr)
  rlang::expr(after_stat(as.prop(count, !!!expr)))
}

p <- ggplot(diamonds, aes(cut, fill = color)) +
  geom_bar(position = "dodge")

# Proportion of total
p + aes(y = !!prop_by())
```

![](https://i.imgur.com/ZmZf3mq.png)

``` r
# Proportion by x and panel
p + aes(y = !!prop_by(x, PANEL)) +
  facet_wrap(~ carat > 0.7)
```

![](https://i.imgur.com/b33Ucoh.png)

<sup>Created on 2023-11-02 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by yjunechoe** [comment]
Speaking of abusing delayed aesthetic evaluation, you can also call `prop_by()` inside of `after_stat()` and kidnap the computed `count` variable from the after-stat context, then proceed to do stuff with it with just standard evaluation (I won't pollute the closed issue further I promise 😅):

``` r
library(ggplot2)

prop_by <- function(...) {
  count <- evalq(count, parent.frame())
  if (length(list(...)) == 0) {
    count / sum(count)
  } else {
    count / ave(count, ..., FUN = function(x) sum(abs(x)))
  }
}

p <- ggplot(diamonds, aes(cut, fill = color)) +
  geom_bar(position = "dodge")

# Proportion of total
p + aes(y = after_stat(prop_by()))
```

![](https://i.imgur.com/tiMR2yH.png)

``` r

# Proportion by x and panel
p + aes(y = after_stat(prop_by(x, PANEL))) +
  facet_wrap(~ carat > 0.7)
```

![](https://i.imgur.com/R6lrWtX.png)

<sup>Created on 2023-11-02 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by teunbrand** [comment]
I was today years old when I learned about the `evalq()` function ^_^
