### ISSUE TITLE
Ggplot2 cannot display ∈ in title, regardless of the method and chosen font.

### ISSUE THREAD

**Issue by Generalized** [tidyverse/ggplot2#5509]
I'd like to display ∈ in the plot title. 
Whatever way I provide it, either directly, ∈ or via unicode \U2208 it displays just a little rectangle.

RStudio can handle it normally:
![obraz](https://github.com/tidyverse/ggplot2/assets/60151643/7a3bfc55-e12c-44b1-96a3-c78436cee316)

so why cannot ggplot2 do the same?

Reproducible example
```{r}
library(ggplot2)
ggplot(data.frame()) + labs(title = "My title \U2208")
ggplot(data.frame()) + labs(title = "My title ∈")
```
![obraz](https://github.com/tidyverse/ggplot2/assets/60151643/a98cd389-6600-41a8-b89d-dad738a7b116)

I thought that maybe changing the font will help, but it didn't:
```{r}
> ggplot(data.frame()) + labs(title = "My title ∈") + theme(text = element_text(family = "Arial"))
> ggplot(data.frame()) + labs(title = "My title ∈") + theme(text = element_text(family = "Courier"))
> ggplot(data.frame()) + labs(title = "My title ∈") + theme(text = element_text(family = "Calibri"))
```
![obraz](https://github.com/tidyverse/ggplot2/assets/60151643/775689b3-e9ed-4c86-821f-362f253f769d)

R version 4.2.0 (2022-04-22 ucrt)
`> packageVersion("ggplot2") [1] ‘3.4.4’`

**Comment by yutannihilation** [comment]
This is a problem in the graphics device, not in ggplot2. If you are using RStudio, you can install ragg package and use the AGG device.

https://ragg.r-lib.org/#use-ragg-in-rstudio

> changing the font will help

This should also help, but I'm afraid fonts like Arial contains only ASCII glyphs.

**Comment by Generalized** [comment]
Thank you for the response.

Unfortunately, changing the rendering device to rAGG didn't help, but setting a different font - did.
I had to use the Windows character map to find the font that works here.

I put the solution for others, who struggle with same issue under Windows:

**This one works under AGG but NOT Cairo!**
```{r}
ggplot(data.frame()) + labs(title = 'Score ∈ [0, 10]') + theme(text = element_text(family = "Symbol"))
```

![obraz](https://github.com/tidyverse/ggplot2/assets/60151643/7fe80909-3bae-420f-af08-5b7835e1702a)

Under Cairo and Cairo PNG
![obraz](https://github.com/tidyverse/ggplot2/assets/60151643/a55683ff-bd0c-4686-b8e6-8feb3957cce1)

But THIS one works under Cairo! It uses the ggtext package and HTML formatting. Works like a charm!

```{r}
ggplot(data.frame()) + labs(title = "ABCDEF <span style='font-family:Symbol;'>&#xCE;</span> [0 ; 20]") + theme(plot.title =  ggtext::element_markdown())
```
![obraz](https://github.com/tidyverse/ggplot2/assets/60151643/4a26885b-95ca-4dc6-856e-9b128c7a8ed1)

**It (the entire ggtext!) doesn't work under AGG, so I won't use it at all in my projects.**
![obraz](https://github.com/tidyverse/ggplot2/assets/60151643/ead3d8d8-bc1c-4226-ba58-437573e4eb35)

**Comment by thomasp85** [comment]
As far as I can gather, ragg does the right thing. Capital I with circumflex is mapped to `&#xCE;` https://www.compart.com/en/unicode/U+00CE

Anyway, use the graphics device that works for you. Nothing in this is related to ggplot2
