### ISSUE TITLE
Different behaviour of scales param `na.value = NA` in `geom_tile()` and `geom_raster()

### ISSUE THREAD

**Issue by dieghernan** [tidyverse/ggplot2#5523]
HI:

Following an issue on `tidyterra` (https://github.com/dieghernan/tidyterra/issues/120, see also https://stackoverflow.com/questions/77474839/ggplot-of-raster-maps-horizontal-vertical-grid-cells-distortion/77486091#77486091) I think the root cause may be on how `ggplot2` handles the param `na.value = NA` on `geom_raster()` (note that `geom_spatraster()` is leveraging on this `ggplot2` function). See the different behaviour compared with `geom_tile()`:

``` r
ex <- tibble::tribble(
  ~x, ~y, ~ExampleMap2,
  4415000L, 2865000L, 1L,
  4425000L, 2865000L, NA,
  4435000L, 2865000L, NA,
  4445000L, 2865000L, NA,
  4415000L, 2855000L, NA,
  4425000L, 2855000L, NA,
  4435000L, 2855000L, NA,
  4445000L, 2855000L, NA,
  4415000L, 2845000L, 1L,
  4425000L, 2845000L, NA,
  4435000L, 2845000L, NA,
  4445000L, 2845000L, NA,
  4415000L, 2835000L, NA,
  4425000L, 2835000L, NA,
  4435000L, 2835000L, NA,
  4445000L, 2835000L, NA,
  4415000L, 2825000L, 1L,
  4425000L, 2825000L, NA,
  4435000L, 2825000L, NA,
  4445000L, 2825000L, 1L
)

library(ggplot2)

p_raster <- ggplot(ex, aes(x, y)) +
  geom_raster(aes(fill = ExampleMap2)) +
  coord_equal()

# As expected
p_raster
```

![](https://i.imgur.com/Q8hfEM5.png)

``` r

# With na.value = NA extra cells are filled
p_raster +
  scale_fill_viridis_c(na.value = NA)
#> Warning: Removed 16 rows containing missing values (`geom_raster()`).
```

![](https://i.imgur.com/4I6kZb3.png)

``` r

# Not happening with geom_tile
ggplot(ex, aes(x, y)) +
  geom_tile(aes(fill = ExampleMap2)) +
  coord_equal() +
  scale_fill_viridis_c(na.value = NA)
```

![](https://i.imgur.com/VrFCo8j.png)

<sup>Created on 2023-11-15 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by teunbrand** [comment]
Is this the same as #3025?
In any case, I think this particular example may also be solved by setting `na.value = "transparent"`.
The `fill` is a non-missing aesthetic in `geom_raster()`, meaning that rows that have `NA` fills will be removed. Subsequently, there are too few cells to reconstruct the resolution of the data.

**Comment by dieghernan** [comment]
Hi,

Yes, it seems to be the same case, thanks for pointing out. `transparent` would do the trick:

``` r
ex <- tibble::tribble(
  ~x, ~y, ~ExampleMap2,
  4415000L, 2865000L, 1L,
  4425000L, 2865000L, NA,
  4435000L, 2865000L, NA,
  4445000L, 2865000L, NA,
  4415000L, 2855000L, NA,
  4425000L, 2855000L, NA,
  4435000L, 2855000L, NA,
  4445000L, 2855000L, NA,
  4415000L, 2845000L, 1L,
  4425000L, 2845000L, NA,
  4435000L, 2845000L, NA,
  4445000L, 2845000L, NA,
  4415000L, 2835000L, NA,
  4425000L, 2835000L, NA,
  4435000L, 2835000L, NA,
  4445000L, 2835000L, NA,
  4415000L, 2825000L, 1L,
  4425000L, 2825000L, NA,
  4435000L, 2825000L, NA,
  4445000L, 2825000L, 1L
)

library(ggplot2)

p_raster <- ggplot(ex, aes(x, y)) +
  geom_raster(aes(fill = ExampleMap2)) +
  coord_equal()

# As expected
p_raster
```

![](https://i.imgur.com/zqJMa0n.png)

``` r

# Filling extra cells
p_raster +
  scale_fill_viridis_c(na.value = NA)
#> Warning: Removed 16 rows containing missing values (`geom_raster()`).
```

![](https://i.imgur.com/hngUSZE.png)

``` r

# Not happening with transparent
p_raster +
  scale_fill_viridis_c(na.value = "transparent")
```

![](https://i.imgur.com/TF61DSm.png)

<sup>Created on 2023-11-15 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
