### ISSUE TITLE
geom_line: size is deprecated,  but  is recommended  in ?geom_line docs

### ISSUE THREAD

**Issue by tbates** [tidyverse/ggplot2#5524]
I was using `geom_line(size=)` and got this error:
> Using `size` aesthetic for lines was deprecated in ggplot2 3.4.0.
ℹ Please use `linewidth` instead.

Seeking to learn about line width, I navigate to ?geom_line. The generic/multifunction doc page doesn't mention `linewidth` but does mention size, recommending it for ... parameter  passed into `layer()` 

Probably `size` should not be mentioned for passing into layer?
Probably `linewidth` should be documented.

regarding #4770, having one doc page for a whole family of distinct functions it part of what makes it harder than necessary  to use the documentation/drives people to bard for help :-)

**Comment by teunbrand** [comment]
I think #5040 pretty much covers the same issue, so I'll close this as a duplicate to keep all conversion around this in one place.
