### ISSUE TITLE
How to shorten grid lines in coord_polar

### ISSUE THREAD

**Issue by paulatn240** [tidyverse/ggplot2#5525]
Hi!

I have created the following graph with the following code but I would like to remove the extra grey line that shows over the black circle. How could I achieve this? 

ggplot(df, aes(variable, mean, fill = variable, label =variable)) +
  geom_bar(width = 1, stat = "identity", color = "white") +
  coord_polar()+
  theme(axis.ticks = element_blank(),
        axis.text.y = element_blank(),
        axis.text.x = element_blank(),
        axis.title = element_blank(),
        axis.line = element_blank(),
        panel.background = element_blank(),
        legend.position = "none",
        panel.grid = element_line("lightgrey"),
        panel.grid.major.y = element_line(colour = c( NA, "lightgrey", "black"))
  ) + 
  scale_y_continuous(limits = c(0,1),breaks = seq(0, 1, by = 0.5))

![Rplot05](https://github.com/tidyverse/ggplot2/assets/109674626/76805eca-cc41-4835-a4e2-1474190ab79b)

Thanks in advance!

**Comment by teunbrand** [comment]
The answer probably involves drawing the gridlines manually, but this issue tracker is intended for bugs and feature requests. Questions and requests for help might have a better home in the [community](https://community.rstudio.com/) or on [stackoverflow](https://stackoverflow.com/).
