### ISSUE TITLE
Feature request: support shortcuts of `"t"`, `"b"`, `"r"` and `"l"` in `theme`

### ISSUE THREAD

**Issue by davidhodge931** [tidyverse/ggplot2#5526]
so instead of `theme(legend.position = "bottom")`, be able to use `theme(legend.position = "b")`

This applies to `legend.position`, but also many other theme elements

``` r
library(palmerpenguins)
library(tidyverse)
#> Warning: package 'ggplot2' was built under R version 4.3.2
#> Warning: package 'purrr' was built under R version 4.3.1
#> Warning: package 'dplyr' was built under R version 4.3.1
#> Warning: package 'forcats' was built under R version 4.3.2
#> Warning: package 'lubridate' was built under R version 4.3.1

p <- penguins |> 
  ggplot() +
  geom_point(aes(x = flipper_length_mm,
                 y = body_mass_g,
                 colour = species)) 

#currently you have to do this
p +
  theme(legend.position = "bottom") 
#> Warning: Removed 2 rows containing missing values (`geom_point()`).
```

![](https://i.imgur.com/nPFBFkQ.png)

``` r

#I would like this to work
p +
  theme(legend.position = "b")
#> Warning: Removed 2 rows containing missing values (`geom_point()`).
```

![](https://i.imgur.com/hIxXF9Y.png)

<sup>Created on 2023-11-17 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by teunbrand** [comment]
I don't think ggplot2 allows for abbreviated options elsewhere, so it'd be a little bit out of place to allow it for these particular arguments.

**Comment by davidhodge931** [comment]
A bit different, but related...

`ggplot2::margin(t = 0, r = 0, b = 0, l = 0, unit = "pt")`

**Comment by davidhodge931** [comment]
Prob not worth it on reflection
