### ISSUE TITLE
How do I set different widths and boundaries for each bin of `cut_width` function?

### ISSUE THREAD

**Issue by danli349** [tidyverse/ggplot2#5527]
Hi,
My data is the remission times of patients 

```
remission <- structure(list(time = c(1, 1, 2, 2, 3, 4, 4, 5, 5, 8, 8, 8, 8, 
11, 11, 12, 12, 15, 17, 22, 23, 6, 6, 6, 6, 7, 9, 10, 10, 11, 
13, 16, 17, 19, 20, 22, 23, 25, 32, 32, 34, 35), group = c("C", 
"C", "C", "C", "C", "C", "C", "C", "C", "C", "C", "C", "C", "C", 
"C", "C", "C", "C", "C", "C", "C", "T", "T", "T", "T", "T", "T", 
"T", "T", "T", "T", "T", "T", "T", "T", "T", "T", "T", "T", "T", 
"T", "T"), censored = c(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 
1, 0, 0, 1, 1, 1, 1, 1)), class = c("tbl_df", "tbl", "data.frame"
), row.names = c(NA, -42L))
```
![image](https://github.com/tidyverse/ggplot2/assets/33963919/9239e7ec-7969-4e21-857f-a30f7475b114)

I want to change the `time` column to categorical by binning, and I want to customize the bin width for each bin.
This is the expected result for the `treatment` group:
![image](https://github.com/tidyverse/ggplot2/assets/33963919/b50c4c28-38da-4c54-9f7f-0d8a4e4ab7b7)

How should I use `cut_width` to achieve this?
Thanks

**Comment by teunbrand** [comment]
You can use `base::cut()` for arbitrary bin sizes. This issue tracker is meant to keep an eye on bugs and feature requests. For questions or requests for help, the [community](https://community.rstudio.com/) or [stackoverflow](https://stackoverflow.com/) are more appropriate channels.
