### ISSUE TITLE
Bug with reversed global colour & fill aesthetic, and fixed colour in geom

### ISSUE THREAD

**Issue by davidhodge931** [tidyverse/ggplot2#5531]
Not sure if this is fixable at ggplot2 or scales ends. So raised at both places
https://github.com/r-lib/scales/issues/411

In the latest DEV version of scales, there seems to be a bug where ggplot is not able to over-ride a reversed global colour aesthetic with a fixed colour in a subsequent layer. This same code works perfectly with the current CRAN version of scales. Whether I used the DEV or CRAN version of ggplot2 had no effect on this.

``` r
library(tidyverse)
#> Warning: package 'ggplot2' was built under R version 4.3.2
#> Warning: package 'purrr' was built under R version 4.3.1
#> Warning: package 'dplyr' was built under R version 4.3.1
#> Warning: package 'forcats' was built under R version 4.3.2
#> Warning: package 'lubridate' was built under R version 4.3.1
library(patchwork)

palmerpenguins::penguins |>
  drop_na() |> 
  group_by(species) |>
  summarise(body_mass_g = mean(body_mass_g)) |>
  mutate(lower = body_mass_g * 0.95) |> 
  mutate(upper = body_mass_g * 1.2)|>
  ggplot(aes(x = body_mass_g,
             y = species,
             col = fct_rev(species),
             fill = fct_rev(species))) +
  geom_col(
    width = 0.75,
    alpha = 0.5
  ) +
  geom_errorbar(
    aes(xmin = lower, xmax = upper),
    colour = "black",
    width = 0.1
  )
```

![](https://i.imgur.com/eq5dWdJ.png)

<sup>Created on 2023-11-21 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by teunbrand** [comment]
I think this might be a consequence of fixing https://github.com/r-lib/scales/issues/383, but if dev or CRAN ggplot2 doesn't make a difference, I'm reasonably confident it is a {scales} issue.

**Comment by teunbrand** [comment]
More minimal reprex(es).

This is fine:

``` r
library(scales) # dev version
library(ggplot2) # 3.4.4

fct <- factor(LETTERS[1:3], LETTERS[3:1])
df <- data.frame(x = 1:3, f = fct)

p <- ggplot(df, aes(x, x, fill = f, colour = f)) +
  geom_col(alpha = 0.5)

p
```

![](https://i.imgur.com/50AggzK.png)

This re-sorts the levels:

``` r
p + geom_point()
```

![](https://i.imgur.com/wATC1ls.png)

This de-syncs fill and colour:

``` r
p + geom_point(colour = "black")
```

![](https://i.imgur.com/OFEEbN1.png)

<sup>Created on 2023-11-21 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by thomasp85** [comment]
Thanks - this will get fixed in scales. Apparently making it work as advertised is harder than it looked 😅
