### ISSUE TITLE
Feature request: `legend.key.spacing` argument(s) added to `theme`

### ISSUE THREAD

**Issue by davidhodge931** [tidyverse/ggplot2#5539]
The new reworked legend spacing will allow the spacing between legend key/label elements to be controlled with `guide_legend(key.spacing = ...)`

It'd be great if you could allow this to be modified through the theme argument as well.

Otherwise, users cannot incorporate their desired legend key spacing up in a theme function.  They have to instead use the guides each time they make a plot to adjust it how they want. 

Thanks, and great work with the ggplot2 development!

**Comment by teunbrand** [comment]
Thank that is a good argument. The reason it wasn't done this way is because the key spacing doesn't apply universally to every non-position guide but only to legends, but I can see the merit in setting this in the theme.

**Comment by teunbrand** [comment]
Probably makes most sense to implement this after #5512 is merged.

**Comment by teunbrand** [comment]
It currently does that implicitly, but might indeed be better to do this explicitly.
