### ISSUE TITLE
Contours fail with `options(OutDec= ",")`

### ISSUE THREAD

**Issue by eliocamp** [tidyverse/ggplot2#5555]
This probably hast o do with how ggplot2 is deriving the level variable from isoband's names. 

Reprex:

``` r
library(ggplot2)

options(OutDec= ".")
ggplot(faithfuld, aes(waiting, eruptions, z = density)) +
  geom_contour_filled()
```

![](https://i.imgur.com/lHP4I5u.png)

``` r

ggplot(faithfuld, aes(waiting, eruptions, z = density)) +
  geom_contour(aes(color = after_stat(factor(level))))
```

![](https://i.imgur.com/s5NLeVb.png)

``` r

options(OutDec= ",")
ggplot(faithfuld, aes(waiting, eruptions, z = density)) +
  geom_contour_filled()
#> Warning in pretty_isoband_levels(names(isobands)): NAs introduced by coercion

#> Warning in pretty_isoband_levels(names(isobands)): NAs introduced by coercion
#> Warning: Computation failed in `stat_contour_filled()`
#> Caused by error in `levels<-`:
#> ! factor level [3] is duplicated
```

![](https://i.imgur.com/68XMLUH.png)

``` r

ggplot(faithfuld, aes(waiting, eruptions, z = density)) +
  geom_contour(aes(color = after_stat(factor(level))))
#> Warning in compute_group(...): NAs introduced by coercion
#> Warning in min(x): no non-missing arguments to min; returning Inf
#> Warning in max(x): no non-missing arguments to max; returning -Inf
#> Error: Must request at least one colour from a hue palette.
```

<sup>Created on 2023-12-01 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by teunbrand** [comment]
Thanks for the report Elio! Can confirm this on my end.
I think it might just be a matter of adding `withr::local_options(list(OutDec = "."))` to `xyz_to_isobands()`.

**Comment by eliocamp** [comment]
Ah, good catch. I was trying  hacky `gsub` stuff. I think it's `withr::with_options()` , though. I can submit a PR.

**Comment by teunbrand** [comment]
A PR would be welcome 🙏 ! The `local_options()` applies to the current evaluation environment (i.e. the `xyz_to_isobands()` function), whereas `with_options()` applies to the code executed in the `code` argument. Both should work in this case.
