### ISSUE TITLE
Should the `trans` argument in `scale_*_continuous` etc be renamed to `transform`? 

### ISSUE THREAD

**Issue by davidhodge931** [tidyverse/ggplot2#5558]
Given that the scales functions will be changing from `scales::*_trans` to `scales::transform_*`

**Comment by teunbrand** [comment]
I'm not sure whether that kerfuffle associated with changing argument names is worth the small increase in consistency.

**Comment by davidhodge931** [comment]
There must have been a reason for using `scales::transform_*` rather than `scales::trans_*`.

Presumably the same reason holds? Consistency makes things easier

**Comment by thomasp85** [comment]
The main reason for the scales change was indeed to streamline the naming conventions in the package to have the common name in front to make tab-completion easier. However, as we were already renaming things we decided to also use a more descriptive and inclusive naming.

Let's keep this open but it is unlikely to be included in the upcoming release

**Comment by eliocamp** [comment]
I like the trans argument name  🏳️‍⚧️

**Comment by yutannihilation** [comment]
Just curious, should `coord_trans()` also be renamed for consistency?

**Comment by teunbrand** [comment]
I like the consistency argument, and I think in a perfect world that would be ideal. However, spending some time with untangling the latest reverse depency checks, I am usure we should even rename the `Scale$trans` field to `Scale$transform`. Probably the deprecation of the old arguments should happen in a more gradual fashion than the RC branch brings now. However, it would be  easy to code `coord_transform()` as an alias for `coord_trans()`, so I can get behind this.

**Comment by yutannihilation** [comment]
Thanks. I have no intention to push `coord_transform()`. I too am not sure if the renaming is worth. If there's no strong reason, maybe we can just leave `coord_trans()` as it is.
