### ISSUE TITLE
Stack imbalance warnings on CI/CD

### ISSUE THREAD

**Issue by krlmlr** [tidyverse/ggplot2#5563]
```
Warning: Warning: stack imbalance in '{', 73 then 71
```

https://github.com/tidyverse/ggplot2/actions/runs/7079443010/job/19266080754#step:6:204

I did not try reproducing locally.

**Comment by thomasp85** [comment]
Hmm, maybe a problem in the code of ragg and svglite. Will have a look

**Comment by teunbrand** [comment]
The message doesn't appear anymore in the CI and {ragg} and {svglite} report in their respective NEWS.md files that stack imbalance bugs have been fixed, so I'll consider this issue resolved.
