### ISSUE TITLE
geom_dotplot() shows no points if all values are the same

### ISSUE THREAD

**Issue by retodomax** [tidyverse/ggplot2#5564]
I found a problem with `geom_dotplot()` if all x values are equal

```r
library(ggplot2)
data.frame(x = rep(10, 30)) |> 
  ggplot(aes(x = x)) +
  geom_density()
```
![image](https://github.com/tidyverse/ggplot2/assets/36004669/de6663ce-ebee-423d-84e2-7da1d5d642ac)

The resulting plot is empty (no points are drawn). This behavior is inconsistent with comparable geoms like `geom_histogram()` or `geom_freqpoly()`.

I would expect something like this

![image](https://github.com/tidyverse/ggplot2/assets/36004669/07e0882c-3e6a-440d-9172-62cdcdd97e84)

**Comment by teunbrand** [comment]
The default `geom_dotplot(method)` is `"dotdensity"`. You cannot really have a density over a zero-range interval as it cannot sum up to 1. As such, I don't think this is a bug that needs fixing as it is just undefined behaviour.

To resolve the situation with `method = "dotdensity"`, you should manually set the `binwidth` argument. To mirror histograms more closely, you can use `method = "histodot"`.
