### ISSUE TITLE
Color expansion of `geom_contour_filled` 

### ISSUE THREAD

**Issue by wbvguo** [tidyverse/ggplot2#5574]
Dear ggplot2 developer, 

I was browsing the official documentation of `geom_contour_filled` (https://ggplot2.tidyverse.org/reference/geom_contour.html), and wonder if it would be possible to add a `expand` parameter (similar to what we did in `scale_x_continous`) that can be used to expand the colored region outwards. This might be helpful in situation where the contour data only capture a part of the full spectrum (the rest part are with low frequency/level, likely not presented in observed data, but they are still important to display on the figure)

Specifically, in the documentation example
![image](https://github.com/tidyverse/ggplot2/assets/31968837/5365c158-c673-457f-9e28-b7051bed5132)

Thanks,
Wenbin

**Comment by teunbrand** [comment]
Hi Wenbin,

If the input data is a grid of values, as is the case for `geom_contour_filled()`, I think the correct approach would be to ensure that the relevant values are present in the input data. If the input data are individual x/y observations, the `geom_density_2d()` function can compute density values outside the bounds of the input data. I don't think it makes sense to extrapolate in the case of `geom_contour_filled()`, but it is fine to compute density in `geom_density_2d()`.

For `geom_density_2d()`, you can just use the x-scale limits to expand the region:

``` r
library(ggplot2)

ggplot(faithful, aes(waiting, eruptions)) +
  geom_density2d_filled(n = 75, h = c(10, 1)) +
  xlim(NA, 120)
```

![](https://i.imgur.com/mgIFQqO.png)

<sup>Created on 2023-12-11 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by teunbrand** [comment]
I'm closing this issue as there appears to be a reasonable path to the desired outcome without the need for changing anything in ggplot2. If I have misunderstood the issue, please clarify and we can reopen the issue.
