### ISSUE TITLE
Inaccurate test for monotonic function causes ecdf to be an invalid transformation in second x axis

### ISSUE THREAD

**Issue by f2il-kieranmace** [tidyverse/ggplot2#5579]
I found a problem with sec.axis, where the monotonic test triggers, despite me supplying a monotonic transformation function. 

# Reprex: 
```
library(tidyverse)

dat = starwars %>% filter(mass < 500)
my_ecdf = ecdf(dat$mass)


ggplot(dat, aes(x = mass, y = height)) +
  geom_point() +
  scale_x_continuous(name = "Weight (kg)",
                     sec.axis = sec_axis(~my_ecdf(.), name = "percentile"))
```

**Comment by f2il-kieranmace** [comment]
Here to answer my own question. I guess ECDF is a step function, which I guess to some folks means it is not monotonic. This is not the strict definition which is: "(of a function or quantity) varying in such a way that it either never decreases or never increases."

An `ecdf` is monotonic, but the tests in ggplot do not respect functions that are flat. Here's a fix (albeit inaccurate)

```
library(tidyverse)

dat = starwars %>% filter(mass < 500)
my_ecdf = ecdf(dat$mass)

my_never_flat_ecdf = function(x){
  epsilon = x / 1000
  epsilon + my_ecdf(x)
}


ggplot(dat, aes(x = mass, y = height)) +
  geom_point() +
  scale_x_continuous(name = "Weight (kg)",
                     sec.axis = sec_axis(~my_smooth_ecdf(.), name = "percentile"))
```

I still think this warrants a fix in ggplot2, so I will not mark as closed.

**Comment by teunbrand** [comment]
This is a simpler reprex of the issue:

``` r
library(ggplot2)

df <- data.frame(x = c(1, 2))

f <- ecdf(1:2)

ggplot(df, aes(x, x)) +
  geom_point() +
  scale_x_continuous(
    sec.axis = sec_axis(f),
    breaks = 0.5
  )
#> Error in `mono_test()`:
#> ! Transformation for secondary axes must be monotonic.
```

<sup>Created on 2023-12-12 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

Where would you expect the break in the example above to show up?
Anywhere between 1 and 2 is 'valid', but we cannot put a tickmark on a range.

**Comment by thomasp85** [comment]
I think the fix is to say in the doc's that the function should be _strictly_ monotonic. I can't see how flat functions would work for this
