### ISSUE TITLE
position_dodge2 reverse=TRUE not working with geom_label

### ISSUE THREAD

**Issue by giadasp** [tidyverse/ggplot2#5581]
I found an issue with the position_dodge2 functionality when reverse=TRUE. It works well with geom_text but it does not reverse the labels if I use geom_label.
I won't reproduce the bug here because it is really easy to test with a simple case.

**Comment by teunbrand** [comment]
> I won't reproduce the bug here because it is really easy to test with a simple case.

Would you please provide a minimal reproducible example regardless of whether the case is simple?

**Comment by giadasp** [comment]
I tried to reproduce the issue with a simple case, even with facet_grid but actually it seems working.
I do not know why it does not work in my case...
