### ISSUE TITLE
legend key does not respect `scale_fill_manual(..., drop = FALSE)`

### ISSUE THREAD

**Issue by davidhodge931** [tidyverse/ggplot2#5586]
In the below example, the legend key for female should be red with a black border. 

I'm using the latest DEV version of ggplot2. It works correctly in 3.4.4.

``` r
library(tidyverse)
library(palmerpenguins)

penguins |>
  mutate(sex = factor(sex)) |>
  filter(sex == "male") |>
  ggplot() +
  geom_violin(aes(
    x = sex,
    y = body_mass_g,
    fill = sex,
  )) +
  scale_fill_manual(values = c("red", "blue"), drop = FALSE)
```

![](https://i.imgur.com/EFFdB8r.png)

<sup>Created on 2023-12-15 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by thomasp85** [comment]
This is due to a new feature where layers only contribute legends to the data that is shown in the layer. You can reinstate the old behaviour by setting `show.legend = TRUE` in the layer

**Comment by teunbrand** [comment]
Yeah this is intended behaviour from #5502, which you can indeed revert by using `show.legend` as Thomas says.
