### ISSUE TITLE
`annotate()` resets factor ordering 

### ISSUE THREAD

**Issue by ashgreat** [tidyverse/ggplot2#5591]
The problem is reproduced in the reprex below. I want to create a plot in which the X-axis is a factor with values like week_1, week_2,... I have to treat it as a factor because alphabetically they won't be ordered in the correct format. They will be week_1, week_10, week_11,... The first plot below correctly shows up.

``` r
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
library(tidyverse)

dt = tibble::tribble(
           ~term, ~estimate, ~std.error,
        "week_1",        -1,        0.2,
        "week_2",     -0.75,        0.2,
        "week_3",      -0.5,        0.2,
        "week_4",     -0.25,        0.2,
        "week_5",         0,        0.2,
        "week_6",      0.25,        0.2,
        "week_7",       0.5,        0.2,
        "week_8",      0.75,        0.2,
        "week_9",         1,        0.2,
       "week_10",      1.25,        0.2,
       "week_11",       1.5,        0.2,
       "week_12",      1.75,        0.2
       ) |> 
  mutate(term = factor(term, levels = paste0("week_", 1:12)),
         ci_lower = estimate - 1.96*std.error,
         ci_upper = estimate + 1.96*std.error)

ggplot(dt, aes(x = term, y = estimate)) +
  geom_errorbar(aes(ymin = ci_lower, ymax = ci_upper,  width = 0.2)) +
  geom_point(shape = 21, fill = "#f82267", color = "#bd2e38", size = 2)
```

![](https://i.imgur.com/wM2Kv5K.png)

Next, I want to add a colored box underneath the points and error bars pertaining to observations from week_6 to week_12. This means `annotate()` has to be before `geom_point` and `geom_errobar`. But this resets the ordering of the factor.

``` r


ggplot(dt, aes(x = term, y = estimate)) +
  annotate(geom = "rect", xmin = "week_6", xmax = "week_12", ymin = -Inf, ymax = Inf,
           fill = "#5cc9f5", alpha = 0.5) +
  geom_errorbar(aes(ymin = ci_lower, ymax = ci_upper,  width = 0.2)) +
  geom_point(shape = 21, fill = "#f82267", color = "#bd2e38", size = 2)
```

![](https://i.imgur.com/2Uper1b.png)

Following the solution in this issue: https://github.com/tidyverse/ggplot2/issues/3197, I added `drop = FALSE` inside `scale_x_dicrete` but it did not work.

``` r


ggplot(dt, aes(x = term, y = estimate)) +
  annotate(geom = "rect", xmin = "week_6", xmax = "week_12", ymin = -Inf, ymax = Inf,
           fill = "#5cc9f5", alpha = 0.5) +
  geom_errorbar(aes(ymin = ci_lower, ymax = ci_upper,  width = 0.2)) +
  geom_point(shape = 21, fill = "#f82267", color = "#bd2e38", size = 2) +
  scale_x_discrete(drop = FALSE)
```

![](https://i.imgur.com/L8qvQSI.png)

Am I missing something obvious?

<sup>Created on 2023-12-16 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by teunbrand** [comment]
I think this might simply be case of updating the {scales} package. What version do you have and if less than 1.3.0, does updating to 1.3.0 help the issue?

**Comment by ashgreat** [comment]
Thanks @teunbrand. That fixed it!

**Comment by ashgreat** [comment]
After I updated `scales` package to the latest version, this problem went away.
