### ISSUE TITLE
Make nudge_x/y argument respect outward/inward justification

### ISSUE THREAD

**Issue by jttoivon** [tidyverse/ggplot2#5611]
To avoid overlapping of point and its label it is sometimes necessary to use the `nudge_x`
argument in `geom_text()`. However, when justifying outward and using `nudge_x=0.1`, I would 
expect the label to move outward. But instead the labels are still moved right. Same problem with inward justification.
This makes it hard to avoid overlapping.

Could this be changed in the `geom_text()` or is there some way around it?

``` r
library(tidyverse)
df <- tribble(
  ~x, ~y, ~label,
  1, 2, "first",
  -1, 1, "second"
)
df %>% ggplot(aes(x=x, y=y, label=label)) + geom_point() + geom_text(hjust="outward", nudge_x = 0.1)
```

![](https://i.imgur.com/oo9PMTI.png)

<sup>Created on 2023-12-22 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by teunbrand** [comment]
I don't think this can be implemented in a straightforward way. `position_nudge()` doesn't know about justification settings. Even if it was made aware, the `"outward"` / `"inward"` settings are not resolved until the very last moment, so it wouldn't have access to the values they become. The position adjustment uses 'data values' for the nudges, whereas resolving the settings uses 'relative values' for the justification, which are only computed in the last step of drawing a layer.

**Comment by jttoivon** [comment]
Ok, thanks for the reply! I think I will try ggrepel instead to avoid overlaps.

**Comment by teunbrand** [comment]
Yes that is a good suggestion. I'll close this over here then.
