### ISSUE TITLE
Package tests fail with ggplot2 3.5.0

### ISSUE THREAD

**Issue by vnijs** [tidyverse/ggplot2#5612]
I was getting errors testing several of my packages with devtools::check_win_dev(). See example message below.

```
 > clt("Uniform", 100, 100, unif_min = 10, unif_max = 20) %>% plot()
  Error in Ops.data.frame(guide_loc, panel_loc) : 
    ‘==’ only defined for equally-sized data frames
  Calls: <Anonymous> ... plot_table.ggplot -> add_guides -> unlist -> Ops.data.frame
  Execution halted
```

I tracked it down to the example below. This works fine with the previous version of ggplot2 and the current version of patchwork. However, with the development version of ggplot2 I'm seeing the same error as above. Not clear exactly where this is coming from but it seems to be a breaking change ggplot2 since I'm using the same version of patchwork. If this should be posted to patchwork, please let me know.

``` r
remotes::install_github("tidyverse/ggplot2")
library(ggplot2)
library(patchwork)
plot_list <- list()
plot_list[[1]] <- ggplot(mtcars, aes(x = mpg)) + geom_histogram(binwidth = 1)
wrap_plots(plot_list, ncol = 1)
#> Error in Ops.data.frame(guide_loc, panel_loc): '==' only defined for equally-sized data frames
```

<sup>Created on 2023-12-22 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by teunbrand** [comment]
Thanks for the report! It already has an issue in patchwork, see https://github.com/thomasp85/patchwork/issues/342. It also has a PR that would fix the behaviour: https://github.com/thomasp85/patchwork/pull/339. To test your package against the current release candidate and patchwork with that PR, you can use:

```r
remotes::install_github("thomasp85/patchwork", ref = remotes::github_pull("339"))
remotes::install_github("tidyverse/ggplot2", ref = remotes::github_pull("5592"))
```

We're currently working through reverse dependency checks to avoid unecessarily breaking packages, but there are probably some that'd need updates. If you find something unbecoming, like bugs, please let us know.

I'll leave this issue open for now so that other developers might stumble upon it.

**Comment by vnijs** [comment]
Thanks @teunbrand. I can confirm that pr you mentioned fixes the issue I was seeing.

```r
remotes::install_github("thomasp85/patchwork", ref = remotes::github_pull("339"))
```

**Comment by aphalo** [comment]
@teunbrand This is just to clarify that the code triggering the error I reported in #5619 did not involve 'patchwork', only 'ggplot2'.

**Comment by aphalo** [comment]
@teunbrand Indeed, I can confrim that the error I reported in #5619 is resolved by installing 'patchwork' pull 339 as mentioned above.

**Comment by teunbrand** [comment]
I'm closing this now, as the patched patchwork was landed on CRAN and this should not be an issue any longer.

**Comment by bakillersky** [comment]
I had the following problem when running the vlnplot and dimplot functions in the Seurat package：
`VlnPlot(scRNAlist[[i]], features = c("nFeature_RNA"))`
Error in Ops.data.frame(guide_loc, panel_loc) : 
  ‘==’ only defined for equally-sized data frames
  But I use this line of code, restart the session and it works, finally! Thank you guys！！！
`remotes::install_github("thomasp85/patchwork")`
