### ISSUE TITLE
Feature request: could `stat = "sf_coordinates"` have x and y scale labels the same as `stat = "sf"`

### ISSUE THREAD

**Issue by davidhodge931** [tidyverse/ggplot2#5613]
It'd be nice if where a stat of sf_coordinates is selected that the x and y labels could be the same as when a stat of sf is used. 

``` r
library(tidyverse)

sf::st_read(system.file("shape/nc.shp", package = "sf")) |>
  ggplot() +
  geom_errorbar(
    aes(
      geometry = geometry,
      xmin = after_stat(x) - 0.1,
      xmax = after_stat(x) + 0.1,
      y = after_stat(y),
      height = 0.04
    ),
    stat = "sf_coordinates",
  )
#> Reading layer `nc' from data source 
#>   `C:\Users\david\AppData\Local\R\win-library\4.3\sf\shape\nc.shp' 
#>   using driver `ESRI Shapefile'
#> Simple feature collection with 100 features and 14 fields
#> Geometry type: MULTIPOLYGON
#> Dimension:     XY
#> Bounding box:  xmin: -84.32385 ymin: 33.88199 xmax: -75.45698 ymax: 36.58965
#> Geodetic CRS:  NAD27
#> Warning in geom_errorbar(aes(geometry = geometry, xmin = after_stat(x) - :
#> Ignoring unknown aesthetics: height
#> Warning in st_point_on_surface.sfc(sf::st_zm(x)): st_point_on_surface may not
#> give correct results for longitude/latitude data
```

![](https://i.imgur.com/mPrACtW.png)

``` r

sf::st_read(system.file("shape/nc.shp", package = "sf")) |>
  ggplot() +
  geom_sf(
    aes(col = AREA),
  )
#> Reading layer `nc' from data source 
#>   `C:\Users\david\AppData\Local\R\win-library\4.3\sf\shape\nc.shp' 
#>   using driver `ESRI Shapefile'
#> Simple feature collection with 100 features and 14 fields
#> Geometry type: MULTIPOLYGON
#> Dimension:     XY
#> Bounding box:  xmin: -84.32385 ymin: 33.88199 xmax: -75.45698 ymax: 36.58965
#> Geodetic CRS:  NAD27
```

![](https://i.imgur.com/Mt1Ojhx.png)

<sup>Created on 2023-12-24 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

(Also, it'd be cool if however it labels positionsal scales in sf, that function could be added to scales package as a `label_sf` or `label_geometry` function.)

**Comment by teunbrand** [comment]
I'm going for a disagree here. Layers and scales should only communicate through data. `geom_sf()` is an exception in that it also adds the coordinate system, which in turns intervenes in scale labelling.

**Comment by davidhodge931** [comment]
Ah okay, so it's the geom rather than the stat that makes sf act differently.

Maybe it should be the stat that does this, and then you could catch stat = sf_coordinates as well? 

If it's too difficult or not practical, feel free to close

**Comment by teunbrand** [comment]
> Ah okay, so it's the geom rather than the stat that makes sf act differently.

Not really, if you print `geom_sf()`, you can see it is a (specialty) layer and a coord. The `coord_sf()` is what makes `geom_sf()` special not only in terms of projecting everything to a common coordinate reference system (CRS) but also in terms of labelling axes and such. 

To illustrate; you can get long/lat labelling without any sf layers:

``` r
library(ggplot2)

df <- data.frame(x = -50:50, y = -50:50)

ggplot(df, aes(x, y)) +
  geom_point() +
  coord_sf(crs = 4326)
```

![](https://i.imgur.com/spyEX2t.png)

<sup>Created on 2023-12-26 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by davidhodge931** [comment]
Awesome thanks, that's interesting.

So if someone makes a graph using sf_coordinates, would they not want it to be projected etc? 

Ie should coord_sf be triggered if someone uses sf_coordinates?

**Comment by teunbrand** [comment]
> So if someone makes a graph using sf_coordinates, would they not want it to be projected etc?

They can by adding `coord_sf()` to their plot. 

> Ie should coord_sf be triggered if someone uses sf_coordinates?

I don't think it should be triggered even when `geom_sf()` is called, but I think it is too late now to change that behaviour. I think bundling up `geom_sf()` with `coord_sf()` muddies the grammar of graphics in some sense by blending these otherwise separate concepts of layers and coordinate systems. While I get the convenience of this bundling, I don't think the solution is to muddy the grammar in more places.
