### ISSUE TITLE
`Error in Ops.data.frame(guide_loc, panel_loc): '==' only defined for equally-sized data frames`

### ISSUE THREAD

**Issue by aphalo** [tidyverse/ggplot2#5619]
@teunbrand  I get this error with current version 3.4.4.9000 installed from GitHub but not with 3.4.4 from CRAN.

I will add a reprex soon. I got this error with a fairly complex plot that I need to simplify to prepare the reprex.

**Comment by teunbrand** [comment]
Thanks Pedro for the report! I believe this is the same as #5612, so that solution might work for you as well.
I'll close this here to keep discussion in one place.

**Comment by Nh-code** [comment]
i have solved it by downgrad: `remotes::install_version("ggplot2", version = "3.4.4", repos = "http://cran.us.r-project.org")`

**Comment by vnijs** [comment]
Thanks for the suggestion @teunbrand. However, I'm getting the same issue in an app that doesn't use patchwork so this doesn't seem like that it is the same issue as https://github.com/tidyverse/ggplot2/issues/5612. The issue went away after downgrading to 3.4.4 just like @Nh-code

**Comment by teunbrand** [comment]
@vnijs if that is reproducible without patchwork, could you post it as a separate issue?
