### ISSUE TITLE
Warning in `geom_col()` when panel has 0 rows

### ISSUE THREAD

**Issue by teunbrand** [tidyverse/ggplot2#5632]
This is a slightly contrived example, but the bar's width calculation can be chatty when there is a factor level in the `PANEL` that has 0 rows in the data.

``` r
library(ggplot2)

df <- mpg
df$drv <- factor(df$drv, c("4", "f", "r"))

ggplot(subset(df, drv != "4"), aes(cyl, cty)) +
  geom_col() +
  facet_wrap(~ drv, drop = FALSE)
#> Warning in min(x): no non-missing arguments to min; returning Inf
#> Warning in max(x): no non-missing arguments to max; returning -Inf
#> Warning in min(d[d > tolerance]): no non-missing arguments to min; returning
#> Inf
```

![](https://i.imgur.com/mGf1N4S.png)

<sup>Created on 2024-01-05 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by teunbrand** [comment]
Considered closed by #5633.

**Comment by averissimo** [comment]
~There has been a regreesion and this error is still present on `4.0.1` when running the reprex I get the exact same warnings.~

edit: nevermind, it's not present on the development branch so it must've been fixed.

**Comment by teunbrand** [comment]
Yes #6759 took care of this :)
