### ISSUE TITLE
`geom_quantile(method = "rqss")` does not seem to work with DEV version

### ISSUE THREAD

**Issue by davidhodge931** [tidyverse/ggplot2#5646]
``` r
library(tidyverse)
library(palmerpenguins)

penguins |>
  ggplot(aes(x = flipper_length_mm,
             y = body_mass_g)) +
  geom_quantile(method = "rqss")
#> Warning: Removed 2 rows containing non-finite outside the scale range
#> (`stat_quantile()`).
#> Smoothing formula not specified. Using: y ~ qss(x, lambda = 1)
#> Warning: Computation failed in `stat_quantile()`.
#> Caused by error in `validObject()`:
#> ! invalid class "dsparseModelMatrix" object: superclass "xMatrix" not defined in the environment of the object's class
```

![](https://i.imgur.com/TLppM7D.png)

<sup>Created on 2024-01-16 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by teunbrand** [comment]
Thanks for the report, David! I don't seem to be able to replicate the issue, it appears to work when I run that plot.

``` r
library(ggplot2)
packageVersion("ggplot2")
#> [1] '3.5.0'
library(palmerpenguins)

penguins |>
  ggplot(aes(x = flipper_length_mm,
             y = body_mass_g)) +
  geom_quantile(method = "rqss")
#> Warning: Removed 2 rows containing non-finite outside the scale range
#> (`stat_quantile()`).
#> Smoothing formula not specified. Using: y ~ qss(x, lambda = 1)
#> Warning in rq.fit.sfn(x, y, tau = tau, rhs = rhs, control = control, ...): tiny diagonals replaced with Inf when calling blkfct
```

![](https://i.imgur.com/kSYR1dg.png)

<sup>Created on 2024-01-16 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by davidhodge931** [comment]
Thanks @teunbrand 

I googled and stackoverflow said to reinstall MatrixModels library, and that seemed to work :)

**Comment by aphalo** [comment]
@teunbrand I this problem resurfacing in the on-line ['ggplot2' documentation for geom quantile](https://ggplot2.tidyverse.org/reference/geom_quantile.html). The solution remains the same as discussed above, reinstalling 'MatrixModels'.

**Comment by teunbrand** [comment]
This is resolved in the dev version, see https://ggplot2.tidyverse.org/dev/reference/geom_quantile.html
