### ISSUE TITLE
`geom_function` does not produce a x axis title where no data is added

### ISSUE THREAD

**Issue by davidhodge931** [tidyverse/ggplot2#5647]
``` r
library(tidyverse)

p <- ggplot() +
  geom_function(
    fun = \(x) dnorm(x),
  )

#currently produces this
p
```

![](https://i.imgur.com/4ZZn7hS.png)

``` r

#I think it should produce this
p +
  labs(x = "x")
```

![](https://i.imgur.com/e4GBPFc.png)

<sup>Created on 2024-01-16 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by davidhodge931** [comment]
But there is no y aesthetic, but that axis gets a title?? It doesn't seem consistent

**Comment by davidhodge931** [comment]
A function graph is used to show how x relates to y. So I think regardless of the internals that it should have a title

**Comment by teunbrand** [comment]
I think the required change would be in this line:

https://github.com/tidyverse/ggplot2/blob/a4be39dee07010c67c31ace059b1f0a24129fc65/R/stat-function.R#L53

We may just add `x = NULL` to have `x` automatically pop up as the default label.
