### ISSUE TITLE
Should the defaults of ggproto Coord objects allow these to be directly added to plots?

### ISSUE THREAD

**Issue by davidhodge931** [tidyverse/ggplot2#5651]
It feels like the defaults of the Coord* ggproto objects should allow me to add these directly to a plot, given that I could do likewise for the equivalent Geom, Stat, and Position ggproto objects.

Is this possible? Or even desirable? Just noticed it wasn't consistent, and thought I'd check..

``` r
library(tidyverse)
library(palmerpenguins)
  
penguins |>
  ggplot() +
  geom_point(aes(x = flipper_length_mm, y = body_mass_g)) +
  CoordCartesian
#> Error in !expand: invalid argument type
```

<sup>Created on 2024-01-19 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by thomasp85** [comment]
I'm not sure I follow you? Adding a Geom directly is not possible:

```r
> ggplot(mtcars) + GeomPoint
Error in `ggplot_add()` at ggplot2/R/plot-construction.R:73:3:
! Can't add `GeomPoint` to a <ggplot> object.
Run `rlang::last_trace()` to see where the error occurred.
```

In any way this is not a use we want to encourage so the answer is likely "no"

**Comment by davidhodge931** [comment]
You can do this with the other types of ggproto objects as follows, but not Coord

``` r
library(tidyverse)
library(palmerpenguins)

penguins |>
  ggplot() +
  layer(
    geom = GeomPoint,
    stat = StatIdentity,
    position = PositionIdentity,
    mapping = aes(x = flipper_length_mm, y = body_mass_g)
  )
#> Warning: Removed 2 rows containing missing values or values outside the scale range
#> (`geom_point()`).
```

![](https://i.imgur.com/AJgZuJQ.png)

<sup>Created on 2024-01-19 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by clauswilke** [comment]
@davidhodge931 I think you're confused about what you're doing in different circumstances. In your code example you're not adding a `GeomPoint` object, you're adding a `layer_class` object and `layer()` is the constructor for that object. You always have to call a constructor function so that the different instances are separate from each other. (If you actually added `GeomPoint` you'd get the exact same geom in all your plots and changes in one plot would result in changes in another.)

See also how `geom_sf()` adds `coord_sf()` to the plot: https://github.com/tidyverse/ggplot2/blob/a4be39dee07010c67c31ace059b1f0a24129fc65/R/geom-sf.R#L228-L247

**Comment by davidhodge931** [comment]
The help suggests that adding a ggproto object directly is what the `geom` and `stat` arguments of `layer` (or `geom_*`) want though.

<img width="364" alt="image" src="https://github.com/tidyverse/ggplot2/assets/55065152/56577c27-6004-4639-a6f6-dc72e4c24e34">

The help for position doesn't allude to using the ggproto object directly, but it works.

For Coord, it doesn't work using the ggproto object directly.

Maybe I have misunderstood, as I'm a new to this. But I feel a little confused by the inconsistency.

If in general, ggplot thinks people shouldn't interact directly with ggproto objects, then the help for geom and stat should be updated to remove reference to this? 

Otherwise if ggplot thinks this is a useful thing to do, then the position argument help should be updated - and ideally Coord should work as a ggproto object to without defaults??

**Comment by clauswilke** [comment]
I still don't see anything that is wrong. I get that it's confusing, in particular the relationship between layer objects and geoms and stats.

In any case, if you wanted to use `CoordCartesian` directly the code would look like this:

``` r
library(tidyverse)
library(palmerpenguins)

penguins |>
  ggplot() +
  geom_point(aes(x = flipper_length_mm, y = body_mass_g)) +
  ggproto(NULL, CoordCartesian,
    limits = list(x = c(160, 240), y = c(4000, 6500)),
    expand = TRUE,
    default = FALSE,
    clip = "on"
  )
#> Warning: Removed 2 rows containing missing values (`geom_point()`).
```

![](https://i.imgur.com/D4hnyKp.png)

<sup>Created on 2024-01-18 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by davidhodge931** [comment]
The structure of it is not what I would expect, given how the Geom, Stat and Position ggproto objects act.

I assume there is a reason why the Coord ggproto objects cannot be like this.. 

``` r
library(tidyverse)
library(palmerpenguins)

CoordCartesian2 <- ggproto(NULL, CoordCartesian, expand = TRUE)
  
penguins |>
  ggplot() +
  geom_point(aes(x = flipper_length_mm, y = body_mass_g)) + 
  CoordCartesian2
#> Warning: Removed 2 rows containing missing values or values outside the scale range
#> (`geom_point()`).
```

![](https://i.imgur.com/QVPTF2F.png)

<sup>Created on 2024-01-19 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by thomasp85** [comment]
I think you are operating under the assumption that ggproto objects all behaves in the same way. ggproto is merely a class system powering ggplot2, nothing more.

Still, there is no place in the API where you can add bare ggproto objects (as they are provided by ggplot2) to a ggplot object - they all require a constructor. For Coord objects it is the accompanying `coord_*()` function. For a collection of Geom, Stat, and Position objects it is the `layer()` function (with shortcuts provided in the form of numerous `geom_*()` and `stat_*()` functions. What you are referring to in the documentation is the arguments to the `layer()` constructor. I fail to see how that implies that every other ggproto can be added without construction to a ggplot object..?

**Comment by davidhodge931** [comment]
Ah okay, thanks for the explanation @thomasp85 and @clauswilke 

Will close now - feel free to reopen, if you want to do anything with this
