### ISSUE TITLE
`binned_scale` defaults to `oob = squish` though the documentation suggests `oob = censor`

### ISSUE THREAD

**Issue by trekonom** [tidyverse/ggplot2#5655]
I was today years old when I learned that binned scales use `oob = squish` as default

https://github.com/tidyverse/ggplot2/blob/a4be39dee07010c67c31ace059b1f0a24129fc65/R/scale-.R#L269

though the documentation suggests that it is `oob = censor`

https://github.com/tidyverse/ggplot2/blob/a4be39dee07010c67c31ace059b1f0a24129fc65/man/binned_scale.Rd#L94-L95

The same holds for the documenation of "all" binned scales which inherit (the documentation of parameters) from `binned_scale`.

The issue seems to be that `binned_scale` itself inherits the documentation of `oob` from `continuous_scale`:

https://github.com/tidyverse/ggplot2/blob/a4be39dee07010c67c31ace059b1f0a24129fc65/R/scale-.R#L252

Feel free to ping me if I should prepare a PR though I guess this could be easily fixed.

**Comment by teunbrand** [comment]
Considered fixed by #5691.
