### ISSUE TITLE
widths/heights in facet_grid

### ISSUE THREAD

**Issue by kohske** [tidyverse/ggplot2#566]
see this commit: b19ff3fd75dd009744670a6527fd4e4a98938f40

**Comment by DarioS** [comment]
Any hope of it being released in version 1.1.0 ?

**Comment by hadley** [comment]
No. It's now too late in the release process.

**Comment by GuangchuangYu** [comment]
Is this feature will be included in future release?

As aligning plots is not an easy task, faceting is a good choice. Allowing width/height adjustment will be a good feature for dummy faceting ( as in [this example](https://github.com/GuangchuangYu/plotTree-ggtree/blob/master/README.md#plot-tree-with-data)).

**Comment by thomasp85** [comment]
@hadley do you want it in `facet_grid` or should we/others make another facetting function that allows for more direct control of sizes?

**Comment by hadley** [comment]
It just doesn't seem that useful to me. Someone can implement in another package if they want.

**Comment by thomasp85** [comment]
Agree that this is not a perfect fit for the semantics of facet_grid. Will probably add something along the lines to ggforce...
