### ISSUE TITLE
Bad behaviour of `coord_polar()` in version RC 3.5.0 compared to 3.4.4

### ISSUE THREAD

**Issue by aphalo** [tidyverse/ggplot2#5660]
@teunbrand Caught another bug at the last minute... Hopefully, not too late. I am using the data from 'learnrbook' for the reprex to avoid any delay in reporting this. With `geom_bar()` there is no problem, but with `geom_polygon()` a big hole appears using RC 3.5.0.

All the best, Pedro.

First the reprex on 3.5.0

``` r
library(learnrbook)
library(ggplot2)
packageVersion("ggplot2")
#> [1] '3.5.0'

p.base <-
  ggplot(data = viikki_d29.dat,
         mapping = aes(x = WindDir_D1_WVT)) +
  coord_polar() +
  scale_x_continuous(breaks = c(0, 90, 180, 270),
                     labels = c("N", "E", "S", "W"),
                     limits = c(0, 360),
                     expand = c(0, 0),
                     name = "Wind direction")

p.base +
  stat_bin(colour = "black", fill = "gray50", geom = "bar",
           binwidth = 30, na.rm = TRUE) +
  labs(y = "Frequency (min/d)")
```

![](https://i.imgur.com/shcnaMP.png)

``` r

p.base +
  stat_density(colour = "black", fill = "gray50",
               geom = "polygon", linewidth = 1) +
  labs(y = "Density (/1)")
```

![](https://i.imgur.com/771xLvU.png)

<sup>Created on 2024-01-23 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

And the correct behaviour with 3.4.4

``` r
library(learnrbook)
library(ggplot2)
packageVersion("ggplot2")
#> [1] '3.4.4'

p.base <-
  ggplot(data = viikki_d29.dat,
         mapping = aes(x = WindDir_D1_WVT)) +
  coord_polar() +
  scale_x_continuous(breaks = c(0, 90, 180, 270),
                     labels = c("N", "E", "S", "W"),
                     limits = c(0, 360),
                     expand = c(0, 0),
                     name = "Wind direction")

p.base +
  stat_bin(colour = "black", fill = "gray50", geom = "bar",
           binwidth = 30, na.rm = TRUE) +
  labs(y = "Frequency (min/d)")
```

![](https://i.imgur.com/ihnep8H.png)

``` r

p.base +
  stat_density(colour = "black", fill = "gray50",
               geom = "polygon", linewidth = 1) +
  labs(y = "Density (/1)")
```

![](https://i.imgur.com/GFXEEQT.png)

<sup>Created on 2024-01-23 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by teunbrand** [comment]
The difference is that ggplot2 3.5.0 now properly closes polygon, so that he line from the last point to the first point of a polygon is also subject to coord transformations. Argueably, this is the correct behaviour and the think that goes wrong is already apparent in cartesian coordinates.

In the plot below, we can see that the density is missing a part along the x-axis.

``` r
library(learnrbook)
library(ggplot2)

p.base <-
  ggplot(data = viikki_d29.dat,
         mapping = aes(x = WindDir_D1_WVT)) +
  scale_x_continuous(breaks = c(0, 90, 180, 270),
                     labels = c("N", "E", "S", "W"),
                     limits = c(0, 360),
                     expand = c(0, 0),
                     name = "Wind direction")

p.base +
  stat_density(colour = "black", fill = "gray50",
               geom = "polygon", linewidth = 1) +
  labs(y = "Density (/1)")
```

![](https://i.imgur.com/hW6In1k.png)

That part remains missing after polar transformation:

``` r
last_plot() + coord_polar()
```

![](https://i.imgur.com/g370mgT.png)

The way to fix this is to not use a polygon geom, but an area geom, see plots below:

``` r
p.base +
  stat_density(colour = "black", fill = "gray50",
               geom = "area", linewidth = 1) +
  labs(y = "Density (/1)")
```

![](https://i.imgur.com/6YqlTrz.png)

``` r
last_plot() + coord_polar()
```

![](https://i.imgur.com/dPrw4Gc.png)

<sup>Created on 2024-01-23 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by aphalo** [comment]
Many thanks for the clarification! My bad.
