### ISSUE TITLE
geom_contour throwing a warning as if `fill` has been "dropped"

### ISSUE THREAD

**Issue by bnicenboim** [tidyverse/ggplot2#5664]
I found a problem with `geom_contour`, it throws a warning as if `fill` declared in the previous `aes` has been dropped, but it as available and used by `geom_raster`.

Here is the code to reproduce the bug and compare it with the second call of ggplot that doesn't throw a warning:

``` r
library(dplyr)
library(ggplot2)
set.seed(123)
#warning:
df <- as.data.frame(expand.grid(x=1:4, y=1:4)) %>%
  mutate(z = rnorm(n()))
ggplot(df, aes(x,y,z = z, fill = z)) + 
  geom_raster() + 
  geom_contour()
#> Warning: The following aesthetics were dropped during statistical transformation: fill.
#> ℹ This can happen when ggplot fails to infer the correct grouping structure in
#>   the data.
#> ℹ Did you forget to specify a `group` aesthetic or to convert a numerical
#>   variable into a factor?
```

![](https://i.imgur.com/i2juBVf.png)

I found a workaround including `fill` in `geom_raster`, but I believe that the previous example shouldn't throw a warning:

``` r
#no warning:
ggplot(df, aes(x,y,z = z)) + 
  geom_raster(aes(fill = z)) + 
  geom_contour()
```

![](https://i.imgur.com/hqknHKy.png)

<sup>Created on 2024-01-25 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by teunbrand** [comment]
I think the decision to throw a warning is correct, as `geom_contour()` indeed drops the `fill` aesthetic during computation of the contours. Perhaps it could be a bit clearer that this warning came from the contour layer rather than the raster layer.

**Comment by bnicenboim** [comment]
Waw, thanks for the fast answer!

I'm sorry, I still don't get why it throws a warning, as if `fill` is no longer there:

``` r
p <- ggplot(df, aes(x,y,z = z, fill = z)) + 
   geom_contour()
p
#> Warning: The following aesthetics were dropped during statistical transformation: fill.
#> ℹ This can happen when ggplot fails to infer the correct grouping structure in
#>   the data.
#> ℹ Did you forget to specify a `group` aesthetic or to convert a numerical
#>   variable into a factor?
```

![](https://i.imgur.com/NOadquo.png)

Here, I get a warning with the right output:
``` r

p + geom_raster(alpha=.5)
#> Warning: The following aesthetics were dropped during statistical transformation: fill.
#> ℹ This can happen when ggplot fails to infer the correct grouping structure in
#>   the data.
#> ℹ Did you forget to specify a `group` aesthetic or to convert a numerical
#>   variable into a factor?
```

![](https://i.imgur.com/qwftVbE.png)

And `fill` is definitely being used, since the output is identical here, but I don't get the warning:

``` r
ggplot(df, aes(x,y,z = z)) + 
  geom_contour() + 
  geom_raster(aes(fill = z), alpha=.5)
```

![](https://i.imgur.com/eYZPjYK.png)


So what exactly is being dropped?

**Comment by clauswilke** [comment]
In `geom_contour()` the `fill` aesthetic is being dropped, as you can see from the fact that the contours are not filled. If you want the `fill` mapping to only apply to `geom_raster()` you should not specify it as a global aesthetic.

``` r
library(dplyr)
library(ggplot2)

set.seed(123)
df <- as.data.frame(expand.grid(x=1:4, y=1:4)) %>%
  mutate(z = rnorm(n()))

ggplot(df, aes(x,y,z = z)) + 
  geom_raster(aes(fill = z)) + 
  geom_contour()
```

![](https://i.imgur.com/FfL4Iey.png)

<sup>Created on 2024-01-25 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by teunbrand** [comment]
I can see two things that might potentially contribute to some confusion.

The first; if an aesthetic is declared in the mapping in `ggplot()`, it will apply  to every layer that doesn't set `inherit.aes = FALSE`. So the data for the contour layer will contain the fill, regardless of whether that data is used or not. You can set `aes(..., foobar = z)` and it will warn about the foobar aesthetic being dropped, even though `foobar` is not an aesthetic.

The second is that some stat parts of layers warn you when aesthetics that are not uniform within groups are being dropped. For example, if you set `aes(fill = "A")` (a constant) you will not get this warning as it is uniform within the one group that `geom_contour()` uses. But because `z` contains multiple values, the stat part will not know how to summarise this for the one group.

**Comment by bnicenboim** [comment]
ok, so the aesthetic is not accessible to the `geom_contour` because it doesn't know how to summarize it. Right? 
But this warning appears in a situation where the aesthetic is not relevant to that geom, another situation is the following one:

``` r
library(dplyr)
library(ggplot2)
set.seed(123)

df <- as.data.frame(expand.grid(x=1:4, y=1:4)) %>%
  mutate(z = rnorm(n())) %>%
  mutate(text = ifelse(x==2 & y==2, "2",""))
ggplot(df, aes(x,y,z = z, label = text)) + 
  geom_contour() +
  geom_text()
#> Warning: The following aesthetics were dropped during statistical transformation: label.
#> ℹ This can happen when ggplot fails to infer the correct grouping structure in
#>   the data.
#> ℹ Did you forget to specify a `group` aesthetic or to convert a numerical
#>   variable into a factor?
```

![](https://i.imgur.com/2yo13zp.png)

Is there a way to set these aesthetics that are irrelevant to `geom_contour`, but will be relevant for other `geoms` globally?

**Comment by clauswilke** [comment]
In `geom_contour()`, you can set `inherit.aes = FALSE` to turn of global `aes()` settings. However, when you do that you will have to explicitly provide the aesthetics you do need.

**Comment by bnicenboim** [comment]
ok, thanks! That's a workaround that I can use! Thanks for responding so quickly.

I would have preferred that the warning would only appear for aesthetics that are relevant to `geom_contour`, but if you think this is the way it should work, feel free to close the issue.

**Comment by clauswilke** [comment]
It's working as expected, because it catches any aesthetic that gets dropped but isn't constant, and that leads to very obscure problems when it happens silently. So it's better to warn a bit too eagerly than not enough.
