### ISSUE TITLE
Nothing plotted or lines and dots are Grey with manual_scale when a named vector is used as the input.

### ISSUE THREAD

**Issue by AlexanderCasper** [tidyverse/ggplot2#5669]
Ref to: https://github.com/tidyverse/ggplot2/issues/4087

Try:

```
colors_named_vector <- c(
  red = "red",
  blue = "blue",
  green = "green"
)


library(ggplot2)

ggplot(iris, aes(x=Sepal.Length, y=Sepal.Width, color=Species)) +
  geom_point() %>% 
  scale_color_manual(values=colors_named_vector)
```

it seems as if it has not been fixed

**Comment by thomasp85** [comment]
As stated in the documentation, if the input to `values` is a named vector the names will be used to match the values to the levels of the scale. Since `iris$Species` doesn't contain any values matching the names of your vector they will all be set to `na.value`

**Comment by thomasp85** [comment]
Also, you are using `%>%` instead of `+` when adding the scale. This is a working version of your code 

``` r
colors_named_vector <- c(
    setosa = "red",
    versicolor = "blue",
    virginica = "green"
)


library(ggplot2)

ggplot(iris, aes(x=Sepal.Length, y=Sepal.Width, color=Species)) +
    geom_point() +
    scale_color_manual(values=colors_named_vector)
```

![](https://i.imgur.com/AwC1VZy.png)
