### ISSUE TITLE
using `geom_abline` with faceting and multiple linetypes

### ISSUE THREAD

**Issue by istvankleijn** [tidyverse/ggplot2#5672]
When I added faceting to a plot that made use of both solid and dashed `geom_abline`s, I ran into the following.

Without faceting, it works fine:
``` r
library(ggplot2)

ggplot(mpg) +
  geom_abline(
    slope = 1,
    intercept = c(0, 10, 20),
    linetype = c("solid", "dashed", "dashed")
  ) +
  geom_point(aes(x = cty, y = hwy))
```

![](https://i.imgur.com/H8waQaY.png)

I would expect adding a `facet_wrap` call would work, but instead it results in an error that is hard to interpret:
``` r
ggplot(mpg) +
  geom_abline(
    slope = 1,
    intercept = c(0, 10, 20),
    linetype = c("solid", "dashed", "dashed")
  ) +
  geom_point(aes(x = cty, y = hwy)) +
  facet_wrap(~drv)
#> Error in `geom_abline()`:
#> ! Problem while setting up geom aesthetics.
#> ℹ Error occurred in the 1st layer.
#> Caused by error in `check_aesthetics()`:
#> ! Aesthetics must be either length 1 or the same as the data (9)
#> ✖ Fix the following mappings: `linetype`
```
It is possible to get my intended result by specifying the dashed and solid lines separately:
``` r
ggplot(mpg) +
  geom_abline(
    slope = 1,
    intercept = 0,
    linetype = "solid"
  ) +
  geom_abline(
    slope = 1,
    intercept = c(10, 20),
    linetype = "dashed"
  ) +
  geom_point(aes(x = cty, y = hwy)) +
  facet_wrap(~drv)
```

![](https://i.imgur.com/H32C3a6.png)

<sup>Created on 2024-01-31 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

Do you agree that the second piece of code should have worked? If not, could the error message be clarified, or the documentation expanded? Or, if the code without `facet_wrap` is not a good idea to start with, perhaps this should have already thrown a warning?

This equally applies to `geom_hline` and `geom_vline`.

**Comment by JoaoSchneidersGit** [comment]
Using `scale_linetype_identity()` the following code works with and without faceting:

```
library(ggplot2)

df_lines <- data.frame(intercept = c(0, 10, 20),
                       slope = 1,
                       linetype = c("solid", "dashed", "dashed"))

ggplot(mpg) +
  geom_abline(data = df_lines,
              aes(slope = slope, intercept = intercept, linetype = linetype)) +
  scale_linetype_identity() +
  geom_point(aes(x = cty, y = hwy)) +
  facet_wrap(~drv)
```

**Comment by teunbrand** [comment]
Static aesthetic parameters passed outside of `aes()` are not guaranteed to line up with the data in predictable ways. The `...` argument in geoms contains the follow line in the documentation: 'used to set an aesthetic to a fixed value'. In my mind, this is clear in the documentation. That it works with non-fixed values is more of a 'use at your own risk' kind of situation, but we're unlikely to enforce fixed values. More discussion of this topic can be found in #4821. The method @JoaoSchneidersGit suggested is the recommended route.
