### ISSUE TITLE
Referencing labels set with `color =` requires using `$colour`

### ISSUE THREAD

**Issue by a-torgovitsky** [tidyverse/ggplot2#5674]
If I set a label with `color` in the US spelling, I cannot access it later using `color`. This seems like a bug, but I suppose it could be intentional effort to impose UK English hegemony on freedom-loving 'merican folks like myself. If the latter, it would be polite to adjust the behavior :).
```r
p3 <- ggplot(mtcars) +
  geom_point(aes(hp, wt, color = mpg))
p3$labels$color
# NULL
p3$labels$colour
# [1] "mpg"
```

**Comment by teunbrand** [comment]
It is not a bug. Internally all of ggplot2 works with `colour`, not `color`. The `labels` field of a plot is not a user-facing component, so it uses `colour`.
