### ISSUE TITLE
`scale_{x,y}_continuous()` functions do not work inside `do.call()`

### ISSUE THREAD

**Issue by schloerke** [tidyverse/ggplot2#5687]
I found a problem with... `scale_y_continuous()` (and by extension `scale_x_continuous()`) not working when called inside a function executed by `do.call()`.

I expected... the execution location to not have effect on the method.

Here is the code to reproduce the bug:

``` r
library(ggplot2)

plot_fn <- function(data = iris, mapping = aes(Sepal.Length, Sepal.Width)) {
  ggplot(data, mapping) + geom_point() + scale_y_continuous()
}

do.call(plot_fn, list())
#> Error in as.character(call[[1]]): cannot coerce type 'closure' to vector of type 'character'
```

<sup>Created on 2024-02-09 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

> ` ggplot2      * 3.4.4.9000 2024-02-08 [1] Github (tidyverse/ggplot2@a4be39d)`

------------

Related: https://github.com/tidyverse/ggplot2/pull/5443, https://github.com/tidyverse/ggplot2/issues/5436

cc @teunbrand 

-----------

Work around: Use `rlang::inject(plot_fn(!!!args))`; (... But I should not be _required_ to do this)

**Comment by teunbrand** [comment]
Have you tried using the release candidate? It seems like a familiar issue that I might've fixed already. You can install it using:

```r
remotes::install_github("tidyverse/ggplot2", ref = remotes::github_pull("5592"))
```

**Comment by schloerke** [comment]
I can not reprex with latest RC branch. Closing
