### ISSUE TITLE
geom_smooth and stat_smooth need to truncate lines when standard error exceeded

### ISSUE THREAD

**Issue by kramerrs** [tidyverse/ggplot2#5688]
### Tips for a helpful feature request:

I would like to request that the trend lines drawn by geom_smooth or stat_smooth have an option to truncate the line when a standard error threshold is exceeded.  For most plots when there is a strong trend a few outliers lead to aweful looking plots.  Even if we put a standard error on the plot, it doesn't make it look better:

For example in this plot, everyone knows I can't predict those outliers at the beginning and end, I don't need to tell everyone.  Hey, there is a bogus crooked line here with massive standard error.

![image](https://github.com/tidyverse/ggplot2/assets/70400219/9a3449d5-6be4-406a-a709-84ca819e57f6)

**Comment by teunbrand** [comment]
I'm not sure that this is considered good practise. You can always fit the model outside of ggplot2 and plot it however you see fit.

**Comment by teunbrand** [comment]
Also using delayed evaluation, you can clip the fill region by setting either `ymin` or `ymax` to `NA`.

``` r
library(ggplot2)

ggplot(mpg, aes(displ, hwy)) +
  geom_point() +
  geom_smooth(
    aes(ymin = after_stat(ifelse(ymax - ymin > 3, NA, ymin)))
  )
#> `geom_smooth()` using method = 'loess' and formula = 'y ~ x'
```

![](https://i.imgur.com/9apfHmB.png)

<sup>Created on 2024-03-11 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

As this functionality is already available, I'll close this issue.
