### ISSUE TITLE
Feature request: `axis.ticks` argument in `facet_wrap` and `facet_grid`

### ISSUE THREAD

**Issue by davidhodge931** [tidyverse/ggplot2#5689]
In the example below, I'd like to be able to add a `axis.ticks` argument to remove the non-margin axis ticks but keep the non-margin axis lines

``` r
library(tidyverse)
diamonds |>
  ggplot() +
  geom_bar(aes(y = cut), width = 0.75, fill = "steelblue") +
  facet_wrap(~color, axes = "all_y", axis.labels = "margins") +
  theme(axis.line = element_line(colour = "black")) +
  theme(axis.line.x = element_blank()) +
  theme(axis.ticks.x = element_blank())
```

![](https://i.imgur.com/fmPPE9z.png)

<sup>Created on 2024-02-11 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by teunbrand** [comment]
The axis lines are pretty data agnostic. You could just `annotate()` a line segment at the corresponding position:

``` r
library(ggplot2)

diamonds |>
  ggplot() +
  geom_bar(aes(y = cut), width = 0.75, fill = "steelblue") +
  facet_wrap(~color) +
  annotate(
    "segment", 
    x = -Inf, xend = -Inf, y = -Inf, yend = Inf,
    colour = "black", linewidth = 1
  ) +
  theme(axis.line.x = element_blank()) +
  theme(axis.ticks.x = element_blank())
```

![](https://i.imgur.com/6Go6Zhz.png)

<sup>Created on 2024-02-12 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by davidhodge931** [comment]
It's prob fine, thanks :)

**Comment by davidhodge931** [comment]
Thinking on this a bit, I actually think it'd be really useful, and I have an idea of how it could work on the surface. 

`facet_wrap(..., axis.line = NULL, axis.ticks = NULL, ...)`
`facet_grid(..., axis.line = NULL, axis.ticks = NULL, ...)`

Where when NULL, `axis.line` and `axis.ticks` inherits from `axes`

This would enable maximum flexibility in how the internal line/ticks/labels would operate when faceting - i.e. you could do anything without any hacking

**Comment by teunbrand** [comment]
The facet's role in all this is mostly to confer context to axes about where they are drawn.
I don't think it is the right place to offer this kind of customisation, especially as axes now can draw something totally different than `guide_axis()`.

**Comment by sschooler** [comment]
As a frequent user of ggplot, this feature would be super useful. It's quite a pain to have to annotate a line, especially when using a categorical axis.

**Comment by teunbrand** [comment]
Doest the example in https://github.com/tidyverse/ggplot2/issues/5689#issuecomment-1938230226 not work for your case?

**Comment by sschooler** [comment]
It does, I just ended up doing a geom_hline, but I just wanted to add a note of support to @davidhodge931 that I think it would be useful if it were included in the facet_wrap/facet_grid function. I think it makes sense to put it in there, as there already are the axes and axis.labels arguments.
