### ISSUE TITLE
Confusing typo in https://ggplot2.tidyverse.org/reference/annotate.html

### ISSUE THREAD

**Issue by mwibral** [tidyverse/ggplot2#5692]
At https://ggplot2.tidyverse.org/reference/annotate.html under #Unsupported_geoms it says:

"Due to their special nature, reference line geoms [geom_abline()](https://ggplot2.tidyverse.org/reference/geom_abline.html), [geom_hline()](https://ggplot2.tidyverse.org/reference/geom_abline.html), and [geom_vline()](https://ggplot2.tidyverse.org/reference/geom_abline.html) can't be used with annotate(). You can use these geoms **directory** for annotations."

I guess 'directory' is meant to be 'directly'. Just stumbled over it because someone from my course asked which directory was meant.

**Comment by teunbrand** [comment]
Thanks for the report! This typo was fixed in #5490, so the next version will have the correct text.
