### ISSUE TITLE
Recursively set (or remove) a theme element

### ISSUE THREAD

**Issue by jonocarroll** [tidyverse/ggplot2#5694]
Related: #3841 

I understand that amongst the hierarchy of theme elements, "the most specific theme element wins", so if I already have `axis.text.x.top` set to red, setting `axis.text = element_blank()` will do nothing to the top x text.

Is there a way to override this behaviour? If I use a theme from a package that sets `axis.text.x.top` (along with many other elements I wish to preserve, and which did not set `inherit.blank = TRUE`) can I somehow set `axis.text = element_blank()` and have it propagate to all child elements, or do I have to dig through to the exact elements that have been set by the package theme? I had hoped that `theme_update` might have a way to do this but it reverts any unspecified elements to their defaults.

I do seem to be able to get close with an explicit `theme_set` and two `theme_update`s modifying a plot object, but this doesn't match any of the documented examples

``` r
library(ggplot2)
p <- ggplot(mtcars, aes(wt, mpg)) +
  geom_point()

theme_set(theme_classic())

# set the x line to red
pred <- p + theme(axis.line.x = element_line(color = "red"))  
pred
```

![](https://i.imgur.com/fDc4TQU.png)

``` r

# this is less specific, so doesn't remove the red line
pred + theme(axis.line = element_blank())
```

![](https://i.imgur.com/P0LtgEw.png)

``` r

# this isn't sufficient, but it does seem to reset the line
pred + theme_update(axis.line = element_blank())
```

![](https://i.imgur.com/I1hTq4T.png)

``` r

# updating a second time is also insufficient
theme_update(axis.line = element_blank())
pred 
```

![](https://i.imgur.com/OPutkfK.png)

``` r

# using + theme_update this time does work
pred + theme_update(axis.line = element_blank())
```

![](https://i.imgur.com/RDZHnNd.png)

<sup>Created on 2024-02-16 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

It's entirely possible I'm using this feature incorrectly, but in any case, having to set the theme globally interferes with my use-case.

Would there be value in a recursive argument; `theme(axis.line = element_blank(), recursive = TRUE)`? This would change (in this case, remove) `axis.line` and all elements which inherit from it.

**Comment by teunbrand** [comment]
> It's entirely possible I'm using this feature incorrectly

The `theme_update()` function affects the global theme, so adding that to a plot appears like off-label use to me. 

> do I have to dig through to the exact elements that have been set by the package theme?

I'd say that this is currently the canonical way of doing this.

If you're looking to make a recursive helper function, I'd suggest something along the following lines:

``` r
library(ggplot2)

get_children <- function(name, lut) {
  children <- lut[names(lut) == name]
  if (length(children) == 0) {
    return(name)
  }
  lapply(children, get_children, lut = lut)
}

theme_recursive <- function(..., tree = get_element_tree()) {
  
  # Make lookup table
  lut <- lapply(tree, `[[`, i = "inherit")
  lut <- lut[lengths(lut) > 0] # Skip orphans
  lut <- stats::setNames(
    rep(names(lut), lengths(lut)),
    unlist(lut)
  )
  
  theme <- theme(...)
  
  for (element in names(theme)) {
    children <- unlist(get_children(element, lut), recursive = TRUE)
    theme[children] <- theme[element]
  }
  
  theme
}

p <- ggplot(mpg, aes(displ, hwy)) +
  geom_point() +
  theme(axis.line.x.bottom = element_line(colour = "red"))

# Does not work
p + theme(axis.line = element_blank())
```

![](https://i.imgur.com/msj5ca4.png)

``` r
# Works
p + theme_recursive(axis.line = element_blank())
```

![](https://i.imgur.com/yNophWM.png)

<sup>Created on 2024-02-16 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by jonocarroll** [comment]
This is fantastic, thank you! It will find a good home in {ggeasy} if it's not likely to be implemented here. I will take care to explain the subtleties when used, but this will be useful for those less familiar with ggplot2 to make sweeping changes.

**Comment by davidhodge931** [comment]
What's your feeling about adding `theme_recursive` to ggplot2, @teunbrand ? 

It would be super useful a lot of the time when you want to change a theme element but you don't know how specific the complete theme has set it at.

I think I would just always use it instead of `theme` tbh
