### ISSUE TITLE
Could the colourbar support nicer vjust/hjust for when the range is wanted as breaks?

### ISSUE THREAD

**Issue by davidhodge931** [tidyverse/ggplot2#5697]
With colourbars, it's hard to match values from the legend to the plot. Therefore, adding the range in the breaks is often a good thing to do, as it reduces unnecessary clutter. However, the colour bar and title doesn't really work nicely with this. The upper value gets in the way of the title etc. See plot below.

I would like the max label to be able to align neatly with the top of the colourbar, and the bottom of the min label to align neatly with the bottom of the colourbar. Likewise if the colourbar is horiztonal, then this would trigger it to align neatly with the left and right of the colourbar.

I think this is not currently possible to do, as you cannot adjust the vjust/hjust differently for different labels. 

Some ideas of how this could look within a `guide_colourbar`, if it was able to be implemented:
1. a `range = TRUE` argument within `scale_colour_gradientn` that set range breaks and then added this special  vjust/hjust treatment of labels. 
2. a `range_labels_just = TRUE` (or `range_labels_vjust`/`range_labels_hjust` `= TRUE`) argument within `guide_colourbar` to just trigger the special vjust/hjust treatment of labels. 

``` r
library(tidyverse)
library(palmerpenguins)

penguins |>
  ggplot() +
  geom_point(aes(x = flipper_length_mm,
                 y = body_mass_g,
                 col = flipper_length_mm,),) +
  scale_colour_gradientn(colors = viridis::viridis(9),
                         breaks = \(x) range(x))
#> Warning: Removed 2 rows containing missing values or values outside the scale range
#> (`geom_point()`).
```

![](https://i.imgur.com/Cij1FoU.png)

<sup>Created on 2024-02-22 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by davidhodge931** [comment]
From Datawrapper demonstrates what I want for a horizontal colourbar
![image](https://github.com/tidyverse/ggplot2/assets/55065152/18a46192-90d1-4798-9f13-5a1062680775)

**Comment by teunbrand** [comment]
Soon guides become extendable and this will be a quick tweak to `GuideColourbar$build_labels()` to pass along `hjust = key$.value` or `vjust = key$.value` depending on the direction.

**Comment by davidhodge931** [comment]
Fantastic, @teunbrand ! 

Do you see this as a ggplot2 extension feature? Or something ggplot2 might do?

I think it would be a big thing to improve the look and feel of the colourbar plots, and so it'd be great if ggplot2 could support

**Comment by teunbrand** [comment]
I think its a bit too specific for `length(labels) == 2` and labels coinciding with min/max for ggplot2.
A thing I have been wanting to build is a min/max colourbar, but the labels are displayed on top/bottom for vertical bars and left/right for horizontal bars.
So more like:
```
0 [========] 100
```

instead of 

```
[========]
0       100
```


or
```
100
||
||
||
||
0
```

instead of

```
|| 100
||
||
|| 0
```

**Comment by teunbrand** [comment]
WRT:

> The upper value gets in the way of the title etc.

You can adjust the `legend.title` margins to account for half the size of the label.

**Comment by davidhodge931** [comment]
I think both of these range variations for the guides would look great, and would be useful!

[========] 
0              100 

0 [========] 100

But I think I would like the look of the top one the most

**Comment by teunbrand** [comment]
I'm going to go ahead and close this. If you want these sort of customisations, a guide extension is the way to go.
