### ISSUE TITLE
`expand` does not work in `scale_colour_gradientn`

### ISSUE THREAD

**Issue by davidhodge931** [tidyverse/ggplot2#5698]
Likewise, doesn't seem to do anything in `scale_colour_stepsn`

Tested in DEV version and 3.4.4.

``` r
library(tidyverse)
library(palmerpenguins)

p <- penguins |>
  ggplot() +
  geom_point(aes(x = flipper_length_mm,
                 y = body_mass_g,
                 col = bill_length_mm,)) +
  scale_colour_gradientn(colors = viridis::viridis(9))

p
#> Warning: Removed 2 rows containing missing values or values outside the scale range
#> (`geom_point()`).
```

![](https://i.imgur.com/HAL2puP.png)

``` r

p +
  scale_colour_gradientn(colors = viridis::viridis(9), expand = c(0.5, 0.5))
#> Scale for colour is already present.
#> Adding another scale for colour, which will replace the existing scale.
#> Warning: Removed 2 rows containing missing values or values outside the scale range
#> (`geom_point()`).
```

![](https://i.imgur.com/Q6ivrow.png)

<sup>Created on 2024-02-22 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by teunbrand** [comment]
Well the docs state for the `expand` parameter: "For position scales, ...", so I think this isn't intended to be used with colour scales.
We should probably remove the `expand` parameter from the docs of non-position scales.

**Comment by davidhodge931** [comment]
Aha, thanks @teunbrand
