### ISSUE TITLE
Patterned fills don't render segmentsGrobs.

### ISSUE THREAD

**Issue by dansmith01** [tidyverse/ggplot2#5710]
I was excited to read the recent blog post announcing [support for patterned fills](https://www.tidyverse.org/blog/2024/02/ggplot2-3-5-0/#patterns-and-gradients)! However, it doesn't seem to be working with line, segment, or bezier grobs.

Below is some code adapted from the blog post linked above.

```r
library(grid)
library(ggplot2)

# gpar everywhere to rule out an "invisible lines" issue
gp <- gpar(col = "black", fill = "black", lwd = 2, lty = "solid")

checkered <- pattern(
  rectGrob(x = c(0.25, 0.75), y = c(0.25, 0.75), width = 0.5, height = 0.5, gp = gp),
  width = unit(5, "mm"), height = unit(5, "mm"), extend = "repeat", gp = gp )

striped <- pattern(
  segmentsGrob(x0 = c(0, 0.5), y0 = c(0.5, 0), x1 = c(0.5, 1), y1 = c(1, 0.5), gp = gp), 
  width = unit(5, "mm"), height = unit(5, "mm"), extend = "repeat", gp = gp )

ggplot(mpg, aes(factor(cyl), fill = factor(cyl))) +
  geom_bar() +
  scale_fill_manual(values = list(striped, checkered, striped, checkered))
```
![Rplot](https://github.com/tidyverse/ggplot2/assets/2066273/407a33ee-d158-4cc3-a983-e499454c3e17)

The segment grob draws fine on it's own:
```r
grid.newpage()
grid.draw(segmentsGrob(x0 = c(0, 0.5), y0 = c(0.5, 0), x1 = c(0.5, 1), y1 = c(1, 0.5), gp = gp))
```
![Rplot01](https://github.com/tidyverse/ggplot2/assets/2066273/18c84553-0fad-4374-86ef-fe7c0ec413e0)

I'm working with RStudio 2023.12.1 on Windows 10. R 4.3.2, ggplot2 3.5.0, all other packages up to date as well. I've tried switching RStudio to both "Cairo PNG" and "AGG" in the General/Graphics options.

**Comment by yutannihilation** [comment]
It seems it's not that these Grobs don't work, but the parameters are a bit tricky. I'm not familiar with these things, and don't figure out the rule here (I'm also on Windows and use the AGG device, so it's possible the result is different on macOS or Linux). 

``` r
library(grid)
library(ggplot2)

gp <- gpar(col = "black", fill = "black", lwd = 2, lty = "solid")

do_plot <- function(x0, y0, x1, y1) {
  checkered <- pattern(
    rectGrob(x = c(0.25, 0.75), y = c(0.25, 0.75), width = 0.5, height = 0.5, gp = gp),
    width = unit(5, "mm"), height = unit(5, "mm"), extend = "repeat", gp = gp
  )
  
  striped <- pattern(
    segmentsGrob(x0 = x0, y0 = y0, x1 = x1, y1 = y1, gp = gp), 
    width = unit(5, "mm"), height = unit(5, "mm"), extend = "repeat", gp = gp
  )
  
  ggplot(mpg, aes(factor(cyl), fill = factor(cyl))) +
    geom_bar() +
    scale_fill_manual(values = list(striped, checkered, striped, checkered)) +
    ggtitle(glue::glue("({x0}, {y0}) - ({x1}, {y1})"))
}

patchwork::wrap_plots(
  do_plot(0, 0, 1, 1   ),
  do_plot(0, 0, 1, 0.9),
  do_plot(0, 0, 1, 0.8),
  do_plot(0, 0, 1, 0.7)
)
```

![](https://i.imgur.com/K3JaJC5.png)

<sup>Created on 2024-02-24 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

To be clear, ggplot2 does nothing here. You can experiment with grid like this:

```r
library(grid)

gp <- gpar(col = "black", fill = "black", lwd = 2, lty = "solid")


striped <- pattern(
  segmentsGrob(x0 = c(0, 0.5), y0 = c(0.5, 0), x1 = c(0.5, 1), y1 = c(1, 0.5), gp = gp), 
  width = unit(5, "mm"), height = unit(5, "mm"), extend = "repeat", gp = gp )

grid.newpage()
grid.rect(width  = 0.5, height = 0.5, gp = gpar(fill = striped))
```

**Comment by yutannihilation** [comment]
Okay, I think now I understand. `pattern()` clips the pattern from the canvas by specified `x`, `y`, `width`, and `height`. As you specify the box as 5mm x 5mm, it's very small.

``` r
library(grid)

gp <- gpar(col = "black", fill = "black", lwd = 2, lty = "solid")

seg <- segmentsGrob(x0 = c(0, 0.5), y0 = c(0.5, 0), x1 = c(0.5, 1), y1 = c(1, 0.5), gp = gp)

grid.newpage()
grid.draw(seg)
grid.rect(
  x = 0.5, y = 0.5, # default value of pattern()
  width = unit(5, "mm"), height = unit(5, "mm"),
  gp = gpar(col = "red", fill = "transparent")
)
```

![](https://i.imgur.com/CmgzzTC.png)

<sup>Created on 2024-02-24 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

So, if you tweak the position of the segments, the pattern should be drawn.

``` r
library(grid)
library(ggplot2)

# gpar everywhere to rule out an "invisible lines" issue
gp <- gpar(col = "black", fill = "black", lwd = 2, lty = "solid")

checkered <- pattern(
  rectGrob(x = c(0.25, 0.75), y = c(0.25, 0.75), width = 0.5, height = 0.5, gp = gp),
  width = unit(5, "mm"), height = unit(5, "mm"), extend = "repeat", gp = gp )

mm_rel <- function(...) {
  unit(0.5, "npc") + unit((base::c(...) - 0.5) * 5, "mm")
}

striped <- pattern(
  segmentsGrob(x0 = mm_rel(0, 0.5), y0 = mm_rel(0.5, 0), x1 = mm_rel(0.5, 1), y1 = mm_rel(1, 0.5), gp = gp), 
  width = unit(5, "mm"), height = unit(5, "mm"), extend = "repeat", gp = gp )

ggplot(mpg, aes(factor(cyl), fill = factor(cyl))) +
  geom_bar() +
  scale_fill_manual(values = list(striped, checkered, striped, checkered))
```

![](https://i.imgur.com/7XuBBIC.png)

<sup>Created on 2024-02-24 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by dansmith01** [comment]
Wow! Thanks so much for this!

I'd written off those parameters as not the problem since they worked for the checkered pattern, but if I understand correctly, it was clipping to just the center corners of the checkered pattern too?

Thanks again!! 😃

**Comment by yutannihilation** [comment]
Anyway, I'm closing as this is not a problem. I found these resources useful. Hope this helps!

https://www.stat.auckland.ac.nz/~paul/Reports/GraphicsEngine/vecpat/vecpat.html
https://coolbutuseless.github.io/2021/07/01/r-v4.1.0-grid-graphics-new-feature-patterns/

**Comment by dansmith01** [comment]
Yes, it's definitely not any kind of bug with ggplot2.

And thank you so much for the help! It makes a lot more sense to me now how to proceed.

For anyone coming across this post in the future - I found that defining a viewport is another solution:

```r
library(grid)
library(ggplot2)

# Graphics parameters and viewport
gp <- gpar(col = "black", fill = "black", lwd = 2, lty = "solid")
vp <- viewport(width = unit(5, "mm"), height = unit(5, "mm"))

striped <- pattern(
  width = unit(5, "mm"), height = unit(5, "mm"), extend = "repeat",
  segmentsGrob(gp = gp, vp = vp, x0 = 0, y0 = 0, x1 =1, y1 = 1) )

shingle <- pattern(
  width = unit(5, "mm"), height = unit(5, "mm"), extend = "repeat",
  segmentsGrob(gp = gp, vp = vp,
      x0 = c(0, 0, 0, 0.6),  y0 = c(0, 0.5, 0, 0.5),
      x1 = c(1, 1, 0.2, 0.8), y1 = c(0, 0.5, 0.5, 1) ))

fish <- pattern(
  width = unit(5, "mm"), height = unit(5, "mm"), extend = "repeat",
  bezierGrob(gp = gp, vp = vp, id = rep(1:3, each = 4),
    x  = {x <- c(0, .25, .75, 1);         c(x, x - 0.5, x + 0.5) },
    y  = {y <- c(0.5, -0.19, -0.19, 0.5); c(y, y + 0.5, y + 0.5) } ))

checkered <- pattern(
  width = unit(5, "mm"), height = unit(5, "mm"), extend = "repeat", 
  rectGrob(gp = gp, vp = vp, 
    x = c(0.25, 0.75), y = c(0.25, 0.75), width = 0.5, height = 0.5 ))

ggplot(mpg, aes(factor(cyl), fill = factor(cyl))) +
  geom_bar(color = "black") +
  scale_fill_manual(values = list(striped, shingle, fish, checkered))
```
![Rplot](https://github.com/tidyverse/ggplot2/assets/2066273/67743003-a92a-447b-a5a8-6b7a77b0d6d7)

Getting the striped tiles to transition seamlessly is my next challenge.
