### ISSUE TITLE
legend.spacing NOT working in v3.5.0

### ISSUE THREAD

**Issue by zhengxiaoUVic** [tidyverse/ggplot2#5711]
It has come to my notice that latest version 3.5.0 introduces changes, including the deprecation of several theme functions that we frequently use. 

For instance, here's a minimal example where the adjustment of horizontal spacing between legend items no longer works as it did previously:

```r
library(ggplot2)

# Sample plot with adjusted legend spacing along the x-axis
ggplot(mpg, aes(x=displ, y=hwy, color=factor(cyl))) + 
  geom_point() +
  theme(
    # Adjust the horizontal spacing between legend items
    legend.spacing.x = unit(1, "cm") # Adjust the spacing to 1 cm
  )
```

![ggplot2](https://github.com/tidyverse/ggplot2/assets/89574270/bce1c3ad-dfe1-4c23-a570-0e5e4a68890b)

**Comment by teunbrand** [comment]
Hi there, thanks for the report! This is intended behaviour, and not a bug. The `legend.spacing` option now refers to the spacing between legends, as it always has, and `legend.key.spacing` is for spacing apart legend key-label pairs. For spacing apart keys from their labels, you can use the text margins.

``` r
library(ggplot2)

# Sample plot with adjusted legend spacing along the x-axis
ggplot(mpg, aes(x=displ, y=hwy, color=factor(cyl))) + 
  geom_point() +
  theme(
    # Adjust the horizontal spacing between legend items
    legend.text = element_text(margin = margin(0, 0, 0, 1, "cm"))
  )
```

![](https://i.imgur.com/bOMgcuH.png)

<sup>Created on 2024-02-26 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

This is mentioned in the changelog:

https://github.com/tidyverse/ggplot2/blob/e8a388e8c8d837305b14947ff1a82ad4376cbda7/NEWS.md?plain=1#L156-L162

And in this writeup here: https://www.tidyverse.org/blog/2024/02/ggplot2-3-5-0-legends/#spacing-and-margins

**Comment by zhengxiaoUVic** [comment]
Thank you, @teunbrand Teun, for your clarification.
