### ISSUE TITLE
Multiple legends with position="inside"

### ISSUE THREAD

**Issue by MauricioCely** [tidyverse/ggplot2#5712]
I have recently installed the `ggplot2` 3.5.0 release, and after reading the new features added to the Legends [Placement](https://www.tidyverse.org/blog/2024/02/ggplot2-3-5-0-legends/#placement), I was very curious to know if it is possible to have multiple inside legends (`position = "inside"`) at different positions by using the new `legend.position.inside` argument for each guide. For example, `cty` legend at bottom-right and `cyl` at top-right. However, it does not work.

``` r
library(ggplot2) # Create Elegant Data Visualisations Using the Grammar of Graphics CRAN v3.5.0

ggplot(mpg, aes(displ, hwy, shape = drv, colour = cty, size = year)) +
  geom_point(aes(alpha = cyl)) +
  guides(
    colour = guide_colourbar(position = "inside",
                             theme = theme(legend.position.inside = c(1, 0))),
    size   = guide_legend(position = "top"),
    alpha  = guide_legend(position = "inside", 
                          theme = theme(legend.position.inside = c(0, 1))),
    shape  = guide_legend(position = "left")
  )
```

![image](https://github.com/tidyverse/ggplot2/assets/26229943/80395629-15d8-4ca3-bb11-91609bc642d2)

It seems only works by using the global theme’s `legend.position.inside` arguments, grouping both legends at the same position, but for now is not possible to not place them separately.

**Comment by thomasp85** [comment]
This is not possible at this time

**Comment by teunbrand** [comment]
Should this be possible? I cannot think of a compelling use case on top of my head, or at least, more compelling than satisfying curiosity.

**Comment by MauricioCely** [comment]
Some time ago, I saw this issue in Stackoverflow:

[https://stackoverflow.com/questions/21798364/independently-move-2-legends-ggplot2-on-a-map](https://stackoverflow.com/questions/21798364/independently-move-2-legends-ggplot2-on-a-map)

**Comment by botanize** [comment]
I'm running into this as well. The documentation doesn't say anything about which components of theme are respected in `guide_legend`, at the moment there's no warning or error, the plot just doesn't respect the API as documented.

**Comment by twest820** [comment]
I seem to be hitting either a related issue or another manifestation of this, though the use case is a bit different as it's a single legend per figure with multiple figures patchworked together. The deprecation warning tells you to use `legend.position.inside` but changing from `legend.position` to `legend.position.inside` results in legends being shown outside the figures unless `guide_legend(position = "inside")` is also specified. While the OP's question isn't supported it's unclear what interactions with the global theme are currently supported.

It's easy to read the [the blog post](https://www.tidyverse.org/blog/2024/02/ggplot2-3-5-0-legends/) as saying this isn't expected behavior: "To cover such cases, there is now a specialised `legend.position.inside` argument that controls the positioning of legends with `position = "inside"` regardless of whether the position was specified in the theme or in the guide." but it's not entirely clear to which of `position` and `legend.position.inside` it's referring to.

**Comment by teunbrand** [comment]
I understand the confusion this may have caused and it should be made clearer in the documentation which theme elements are used in the legend itself versus which ones are used to compose the legend within the plot.

With regards to positions;
The `position` argument of the guide function determines in which area of the plot it is displayed.
In absence of such argument, the global `theme(legend.position)` argument is used. 
It never uses the local theme for this, as it has an argument that serves this function.
The `theme(legend.position.inside)` argument determines where legends with `position = "inside"` (directly or by defaulting through the global theme) are placed in the plot panel. 

With regards to which theme elements guides respond to;
As a rule of thumb, these are the elements that only affect a single guide, not elements that rule how guides are positioned in the guide box (e.g. `legend.justification`, `legend.location`, `legend.box`, `legend.box.just` and `legend.box.spacing`, `legend.position` and `legend.position.inside`, `legend.spacing`). To get an exact overview of which elements are taken from the theme, you can inspect a guides `elements` field:

``` r
ggplot2::guide_legend()$elements
#> $background
#> [1] "legend.background"
#> 
#> $margin
#> [1] "legend.margin"
#> 
#> $key
#> [1] "legend.key"
#> 
#> $key_height
#> [1] "legend.key.height"
#> 
#> $key_width
#> [1] "legend.key.width"
#> 
#> $text
#> [1] "legend.text"
#> 
#> $theme.title
#> [1] "legend.title"
#> 
#> $spacing_x
#> [1] "legend.key.spacing.x"
#> 
#> $spacing_y
#> [1] "legend.key.spacing.y"
#> 
#> $text_position
#> [1] "legend.text.position"
#> 
#> $title_position
#> [1] "legend.title.position"
#> 
#> $byrow
#> [1] "legend.byrow"
```

<sup>Created on 2024-05-31 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by teunbrand** [comment]
Currently, that is the only way I imagine.
