### ISSUE TITLE
How to avoid warnings when adding a secondary axis without breaks or labels in `ggplot2 3.5.0`?

### ISSUE THREAD

**Issue by IndrajeetPatil** [tidyverse/ggplot2#5713]
Prior to this release, I could use the secondary axis only to display an additional label, and not include breaks or labels. To do so, I could do the following, but, as can be seen, warnings are generated, and I would like to avoid these warnings since the users of my package will also see these warnings.

---

``` r
library(ggplot2)

ggplot(mtcars, aes(wt, mpg)) +
  geom_point() +
  scale_y_continuous(sec.axis = dup_axis(name = "my secondary axis", breaks = NULL)) 
#> Warning in min(x): no non-missing arguments to min; returning Inf
#> Warning in max(x): no non-missing arguments to max; returning -Inf
```

![](https://i.imgur.com/6tW24TN.png)

``` r

ggplot(mtcars, aes(wt, mpg)) +
  geom_point() +
  scale_y_continuous(sec.axis = sec_axis(transform = I, name = "my secondary axis", breaks = NULL)) 
#> Warning in min(x): no non-missing arguments to min; returning Inf

#> Warning in min(x): no non-missing arguments to max; returning -Inf
```

![](https://i.imgur.com/4dKbWnu.png)

<sup>Created on 2024-02-27 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by teunbrand** [comment]
Thanks for the report! This seems like a regression that should be fixed in ggplot2
