### ISSUE TITLE
`scale_fill_manual(drop = FALSE)` results in missing key aesthetics

### ISSUE THREAD

**Issue by kevinwolz** [tidyverse/ggplot2#5728]
This is an issue that popped up for me when updated from version 3.4.4 to 3.5.0. 

```
library(sf)
library(dplyr)
library(ggplot2)

fname <- 
nc <- system.file("shape/nc.shp", package = "sf") |>
  read_sf() |>
  mutate(AREA_F = cut(AREA, 5)) |>
  filter(AREA < 0.122)
```

### VERSION 3.4.4
Both of these functioned as I would expect.
`drop = TRUE` 
```
ggplot() +
  geom_sf(data = nc, aes(fill = AREA_F)) +
  scale_fill_manual(values = rainbow(5), drop = TRUE)
```
![image](https://github.com/tidyverse/ggplot2/assets/11711566/831efacd-0ecb-4606-a873-715761af7769)

`drop = FALSE` 
```
ggplot() +
  geom_sf(data = nc, aes(fill = AREA_F)) +
  scale_fill_manual(values = rainbow(5), drop = FALSE)
```
![image](https://github.com/tidyverse/ggplot2/assets/11711566/35254efa-1b99-4f09-9d9b-87d9f228bdd0)

### VERSION 3.5.0
`drop = TRUE` is the same, as expected.
```
ggplot() +
  geom_sf(data = nc, aes(fill = AREA_F)) +
  scale_fill_manual(values = rainbow(5), drop = TRUE)
```
![image](https://github.com/tidyverse/ggplot2/assets/11711566/4ad46d10-101f-4341-a47c-b22643a467c3)

`drop = FALSE` adds the missing levels to the legend, but the keys are empty.
```
ggplot() +
  geom_sf(data = nc, aes(fill = AREA_F)) +
  scale_fill_manual(values = rainbow(5), drop = FALSE)
```
![image](https://github.com/tidyverse/ggplot2/assets/11711566/26e7960f-026c-4d64-a0d4-1de27a73c6ba)

**Comment by teunbrand** [comment]
Hi there, thanks for the report! This is indended behaviour from the 3.5.0 update: if your data doesn't contain the level, the key isn't rendered for that layer by default. To render the keys, you should set `geom_sf(..., show.legend = TRUE)`. This is documented in the news:

https://github.com/tidyverse/ggplot2/blob/bc3e40144cb971cc1d86a05a171b373b15f54fcf/NEWS.md?plain=1#L36-L38

And communicated in the release blog: https://www.tidyverse.org/blog/2024/02/ggplot2-3-5-0-legends/#awareness

There is a separate issue for making this clearer in the documentation of scales, see #5715.

**Comment by kevinwolz** [comment]
@teunbrand thanks for the help. I agree that improving the documentation would help. 

I have come across some other unexpected (for me at least) behavior that I wanted to ask about. This may be an issue with the package `tidyterra`, but it also potentially warrants additional documentation so I figured I would ask it here as well. 

```
library(sf)
library(terra)
library(tidyterra)
library(ggplot2)

nc <- system.file("shape/nc.shp", package = "sf") |>
  read_sf()

# Generate sf points
sf_points <- nc |>
  st_centroid() |>
  mutate(shp = factor(rep(c(1, 2), length.out = nrow(nc))))

# Generate categorical raster
terra_raster <- nc |>
  vect() |>
  rasterize(rast(nc), background = 2)
```

The following plot works as expected. Some points on top of a raster, with just the legend for the points. 
```
ggplot() +
  tidyterra::geom_spatraster(data = terra_raster, show.legend = FALSE) +
  geom_sf(data = sf_points, aes(shape = shp))
```
![image](https://github.com/tidyverse/ggplot2/assets/11711566/c6442a61-066d-449a-8437-886829259b49)

When I set `show.legend = TRUE` within `tidyterra::geom_spatraster`, I get the raster legend (as expected), but then suddenly the key background in the shape legend is dark grey. It is surprising to me that changing a parameter in `tidyterra::geom_spatraster` would impact the legend of a totally different layer.
```
ggplot() +
  tidyterra::geom_spatraster(data = terra_raster, show.legend = TRUE) +
  geom_sf(data = sf_points, aes(shape = shp))
```
![image](https://github.com/tidyverse/ggplot2/assets/11711566/7c250ef4-4cdc-425c-9b80-7262f8a7e4c1)

**Comment by njudd** [comment]
This is a very unintuitive change, I feel like `show.legend = TRUE` should default `drop = FALSE` or visa versa

**Comment by teunbrand** [comment]
This change is to remove the need for setting very complicated and tailored `guide_legend(override.aes)` argument just to have legend visuals match the plot. In theory, we could let `drop = FALSE` propagate layers where `show.legend = NA`, which would be straightforward if the plot has a single layer. However, this would then apply to all layers regardless of the level occurs in the data or not, thereby losing control.

**Comment by ECarnell** [comment]
I agree with njudd, this seems very counterintuitive. So `drop = F` essentially becomes redundant?

Original code 
`
df <- data.frame(x = runif(n = 50, min = 0, max = 10),
                 y = runif(n = 50, min = 0, max = 10),
                 z = runif(n = 50, min = 0, max = 4))

df$cat <- cut(df$z,
                 breaks = c(0,1,2,3,4,6,8),
                 labels = c("0 - 1","> 1 - 2","> 2 - 3",
                            "> 3 - 4","> 4 - 6","> 6 - 8"))

p <- ggplot()

p <- p + geom_point(data = df, aes(x = x, y = y, colour = cat), size =  5)

p <- p + scale_color_manual(values = c("#38d1ff","#fffc36","#ffa536","#ff2e2e","#f314ff","#9514ff","#C1CDCD"),
                            limits = names(cols),
                            drop = F,
                            bquote(mu*g~NH[3]~m^-3))

p`
![image](https://github.com/tidyverse/ggplot2/assets/16242875/8dea8405-662d-43e2-b7e2-7848451de099)
 
Removing `drop = F` (now redundant) and adding `show.legend = T` produces:
![image](https://github.com/tidyverse/ggplot2/assets/16242875/86790b05-0b66-4c7d-8ccc-f73bb9204213)

**Comment by teunbrand** [comment]
> So drop = F essentially becomes redundant?
You still need it to include unobserved levels.

**Comment by ECarnell** [comment]
> You still need it to include unobserved levels

Would it not make sense to also include the colours associated with those unobserved levels? (especially for consistency with other plots where the levels are observed)

**Comment by teunbrand** [comment]
Yes and no. Yes it makes intuitive sense, but no, it destroys the ability to control this at the geom level.

**Comment by ECarnell** [comment]
I agree controlling this at the geom level makes sense, but currently the behaviour of `drop` in scale_XXX_manual is counterintuitive. I think the drop argument should override `show.legend` (especially when breaks/labels are set explicitly)

**Comment by thomasp85** [comment]
I can emphasise with the annoyance of this change for your particular use cases, but making the requested change would in practice make it impossible to have `show.legend = NA` and `drop = TRUE` at the same time (something that other will find useful), whereas your issues are solvable by setting the right arguments. In that case, not limiting other users win

**Comment by ECarnell** [comment]
Should the help/documentation of scale_XXX_manual be updated to reference this change in behaviour? Noting that the behaviour of `drop` will be depended on `show.legend`

**Comment by teunbrand** [comment]
Alright with 3.5.1 now released and we don't have the intent to change this, I believe it is time to close this issue.
