### ISSUE TITLE
Support for circular/modulo scales 

### ISSUE THREAD

**Issue by eliocamp** [tidyverse/ggplot2#5733]
This has been an issue for some time but today's blog post about `coord_radial()` inspired me to open an issue for discussion. 

Polar/radial coordinates don't treat the coordinate space as periodic, they just wrap around the cartesian coordinates. This means that it is very hard to draw any segment that crosses the "0" line, like a spiral:

``` r
library(ggplot2)

theta <- seq(0, 720*pi/180, by = 0.5*pi/180)
spiral <- data.frame(theta = theta %% (1*pi), 
                     r = theta) 

spiral |> 
  ggplot(aes(theta, r)) +
  geom_path() +
  coord_radial()
```

![](https://i.imgur.com/VNhOZVj.png)

<sup>Created on 2024-03-01 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

I think this might be a scales thing, since it would still make sense to plot the spiral in cartesian coordinates and have the lines close correctly; which they don't: 

``` r
spiral |> 
  ggplot(aes(theta, r)) +
  geom_path() 
```

![](https://i.imgur.com/p5uQEFQ.png)

<sup>Created on 2024-03-01 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

Circular scales should also affect histograms and even density estimates.

Maybe there needs to be a `scale_*_circular()` that defines the * aesthetics to be cyclical/circular with some range/modulo and then do the appropriate transformations (in theory this would also apply to other scales, such as colour, size, etc.)

**Comment by teunbrand** [comment]
You are right that this is a scales thing.
If you set the scales to 1 period with `oob = oob_keep()`, you can draw spirals with `coord_radial()`.

``` r
library(ggplot2)

df <- data.frame(x = 1:75, y = 1:75)

ggplot(df, aes(x, y)) +
  geom_line() +
  scale_x_continuous(limits = c(1, 25), oob = scales::oob_keep) +
  coord_radial(expand = FALSE)
```

![](https://i.imgur.com/foRIKf8.png)

<sup>Created on 2024-03-01 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

There are a few caveats though:

1. If you do not set `expand = FALSE`, it is just plain incorrect.
2. If you do partial polar coordinates by setting the `end` argument, it will just go outside of the plotting region.
3. These are not truly circular scales, so if you want to have say densities for circular distributions, you are out of luck.

I like the idea of circular scales, but I do think it is currently out of scope for ggplot2.  Having only briefly glanced, wouldn't {ggperiodic} be a good fit  for this type of functionality?

**Comment by eliocamp** [comment]
> wouldn't {ggperiodic} be a good fit for this type of functionality?

Maybe. ggperiodic right now is a bit of a hack that repeats data points when needed. It could be expanded to acomodate a more robust handling of circular scales. There's also [ggcircular](https://github.com/marcpabst/ggcircular), which provides specialised stats, but it doesn't look actively maintained and I don't know if I like the specialised stats approach.

**Comment by aphalo** [comment]
A stat for computing densities for circular distributions would be very useful for wind rose plots and for distributions along time when considering one day or one week as a period. But this is, I think, a bit a different problem, as one may well want to fit such a distribution and plot it using either cartesian or polar/radial coordinates. Thanks for the hint about 'ggcircular', I will have a look.

**Comment by eliocamp** [comment]
Yes. The coordinates of the plot are independent from the properties of the scales. 

I'm going to close this since @teunbrand declared it out of scope.
