### ISSUE TITLE
Could the y axis title be moved with the axis when `coord_radial(r_axis_inside = TRUE)`? 

### ISSUE THREAD

**Issue by davidhodge931** [tidyverse/ggplot2#5734]
Currently it stays put at at 3 o clock when `coord_radial(r_axis_inside = TRUE)`. 

Could it be moved with the axis?

``` r
library(tidyverse)
ggplot(mpg, aes(class, displ)) +
  geom_boxplot() +
  coord_radial(r_axis_inside = TRUE) +
  theme_classic()
```

![](https://i.imgur.com/gW4iMKh.png)

<sup>Created on 2024-03-02 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by teunbrand** [comment]
Axis title placement is controlled by the facets, not the axes or coord.
You could extend guides to draw a title, but you'd get double titles.

**Comment by teunbrand** [comment]
I'm just gonna say this is hard to achieve given the way facets/coords and the layout interact to put up axis titles. For this reason, I don't think we should implement this in ggplot2.

When {legendry} is released, hopefully soon-ish, you could do the following to make a title following the radius axis.

``` r
library(legendry)
#> Loading required package: ggplot2

ggplot(mpg, aes(class, displ)) +
  geom_boxplot() +
  guides(r = compose_stack("axis", primitive_title("displ", angle = 90))) +
  coord_radial(start = 0.25 * pi, end = 1.75 * pi)
```

![](https://i.imgur.com/ZNeXYXm.png)

<sup>Created on 2024-10-29 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>
