### ISSUE TITLE
Could the x and y axis position move when `coord_radial` is used?

### ISSUE THREAD

**Issue by davidhodge931** [tidyverse/ggplot2#5735]
Currently only the y axis title moves

``` r
library(tidyverse)

mpg |> 
  ggplot() +
  geom_boxplot(aes(x = class, y = displ)) +
  coord_radial() +
  scale_y_continuous(position = "right")
```

![](https://i.imgur.com/mKH4AhO.png)

<sup>Created on 2024-03-02 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by teunbrand** [comment]
It is a little bit more complicated than just moving the axis.
In particular, if you have start/end settings that don't include a vertical angle, the axis is placed horizontally.
So `position = "right"`, or `position = "left"` for that matter, cannot apply correctly.

``` r
library(ggplot2)

mpg |> 
  ggplot() +
  geom_boxplot(aes(x = class, y = displ)) +
  coord_radial(start = 0.25 * pi, end = 0.75 * pi, r_axis_inside = FALSE)
```

![](https://i.imgur.com/XGSnsMZ.png)

Also if you have a bottom-half circle, the position would be on the right visually even though it is the primary axis.

``` r
mpg |>
  ggplot() +
  geom_boxplot(aes(x = class, y = displ)) +
  coord_radial(start = 0.5 * pi, end = 1.5 * pi)
```

![](https://i.imgur.com/AStBLFX.png)

If you must have a guide on the right, you can use the `r.sec` name in `guides()`.

``` r
mpg |> 
  ggplot() +
  geom_boxplot(aes(x = class, y = displ)) +
  coord_radial() +
  guides(r = "none", r.sec = "axis")
```

![](https://i.imgur.com/wNyVpbv.png)

<sup>Created on 2024-03-04 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by teunbrand** [comment]
There is something to say for this from a consistency standpoint. However, I don't think it makes sense to use a flipping mechanism for the theta axis: that would only work if `inner.radius` allows enough space.
