### ISSUE TITLE
Missing text from guide in 'ggpp' when mapping variable to size

### ISSUE THREAD

**Issue by aphalo** [tidyverse/ggplot2#5736]
@teunbrand 
Dear Teun,
I see this problem happening in 'ggpp' with `geom_text_s()` and `geom_label_s()` while `ggrepel::geom_text_repel()` works as expected. I am not sure in when it started, but I had not noticed before.

You already gave some advice in #5419 some months ago about these geoms. The code in 'ggpp' is adapted from 'ggplot2' to be 3.5.0, but that in 'ggrepel' follows the older approach.

The code in `GeomTextS` uses `draw_key = ggplot2::draw_key_text` and some of the code is adpated/copied from `geom_text()` from 'ggplot' 3.5.0. To make this work also with older versions of 'ggplot2' I copied the file _margins.R_ from 'ggplot2' into 'ggpp' as _ggp2-margins.R_, but deleting function `margin()`, that did not seem to be needed. This is in [issue 50 of 'ggpp'](https://github.com/aphalo/ggpp/issues/50) but I have added the relevant reprex here, as I am not sure if this has to be fixed in 'ggpp' or 'ggplot2'. 

``` r
library(ggpp)
#> Loading required package: ggplot2
#> Registered S3 methods overwritten by 'ggpp':
#>   method                  from   
#>   heightDetails.titleGrob ggplot2
#>   widthDetails.titleGrob  ggplot2
#> 
#> Attaching package: 'ggpp'
#> The following object is masked from 'package:ggplot2':
#> 
#>     annotate

### BUG in geom_text_s and geom_label_x

my.cars <- datasets::mtcars[c(TRUE, FALSE, FALSE, FALSE), ]
my.cars$name <- rownames(my.cars)

p1 <-
  ggplot(my.cars, aes(wt, mpg, label = name)) +
  geom_point() +
  geom_text(aes(size = wt), nudge_x = -0.1, hjust = "right") +
  scale_radius(range = c(3,6)) + # override scale_area()
  expand_limits(x = c(1.8, 5.5))

p1
```

![](https://i.imgur.com/LmL7Rtr.png)

``` r

get_guide_data(p1, aesthetic = "size")
#>       size .value .label
#> 1 3.036458    2.5    2.5
#> 2 3.557292    3.0    3.0
#> 3 4.078125    3.5    3.5
#> 4 4.598958    4.0    4.0
#> 5 5.119792    4.5    4.5
#> 6 5.640625    5.0    5.0
get_guide_data(p1, aesthetic = "colour")
#> NULL
get_guide_data(p1, aesthetic = "alpha")
#> NULL

### text missing from guide

p2 <-
  ggplot(my.cars, aes(wt, mpg, label = name)) +
  geom_point() +
  geom_text_s(aes(size = wt), nudge_x = -0.1, hjust = "right") +
  scale_radius(range = c(3,6)) + # override scale_area()
  expand_limits(x = c(1.8, 5.5))

p2
```

![](https://i.imgur.com/2UQzJbJ.png)

``` r

get_guide_data(p2, aesthetic = "size")
#>       size .value .label
#> 1 3.036458    2.5    2.5
#> 2 3.557292    3.0    3.0
#> 3 4.078125    3.5    3.5
#> 4 4.598958    4.0    4.0
#> 5 5.119792    4.5    4.5
#> 6 5.640625    5.0    5.0
get_guide_data(p2, aesthetic = "colour")
#> NULL
get_guide_data(p2, aesthetic = "alpha")
#> NULL

all.equal(p1$guides, p2$guides)
#> [1] TRUE

all.equal(p1$labels, p2$labels)
#> [1] TRUE
```

<sup>Created on 2024-03-02 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

The whole difference in the unit test is:

![image](https://github.com/tidyverse/ggplot2/assets/2743159/563948bc-eb5c-45cb-be30-f1b9eb92e0a4)

Thanks in advance for any help.

**Comment by aphalo** [comment]
I think I now know where the problem might be. I close this issue until I have implemented new `draw_key` functions that better match the geoms in 'ggpp' and tested if this solves the problem.

**Comment by aphalo** [comment]
@teunbrand Implementing a `draw_key_` function in 'ggpp' does not work, because even if exported by 'ggpp', the function is not found when loading 'ggpp'. So, I am stuck. Do you have any suggestion on how to solve this problem?

```
- C:/Users/aphalo/AppData/Local/R/win-library/4.3
- C:/Program Files/R/R-4.3.2patched/library
* installing to library 'C:/Users/aphalo/AppData/Local/R/win-library/4.3'
* installing *source* package 'ggpp' ...
** using staged installation
** R
** data
*** moving datasets to lazyload DB
** inst
** byte-compile and prepare package for lazy loading
Using libraries at paths:
- C:/Users/aphalo/AppData/Local/R/win-library/4.3/00LOCK-ggpp/00new
- C:/Users/aphalo/AppData/Local/R/win-library/4.3
- C:/Program Files/R/R-4.3.2patched/library
Error in eval(exprs[i], envir) : object 'draw_key_text_s' not found
Error: unable to load R code in package 'ggpp'
Execution halted
ERROR: lazy loading failed for package 'ggpp'
* removing 'C:/Users/aphalo/AppData/Local/R/win-library/4.3/ggpp'
* restoring previous 'C:/Users/aphalo/AppData/Local/R/win-library/4.3/ggpp'

Exited with status 1.
```
even if in NAMESPACE

```
...
export(draw_key_label_s)
export(draw_key_text_s)
...
```

**Comment by teunbrand** [comment]
Hi Pedro,

I'm not quite sure what the issue might be, because the legend text just displays with `geom_text_s()` when executing the relevant bits of the reprex.

``` r
library(ggpp)
#> Loading required package: ggplot2
#> Registered S3 methods overwritten by 'ggpp':
#>   method                  from   
#>   heightDetails.titleGrob ggplot2
#>   widthDetails.titleGrob  ggplot2
#> 
#> Attaching package: 'ggpp'
#> The following object is masked from 'package:ggplot2':
#> 
#>     annotate
packageVersion("ggpp")
#> [1] '0.5.6'

my.cars <- datasets::mtcars[c(TRUE, FALSE, FALSE, FALSE), ]
my.cars$name <- rownames(my.cars)

p2 <-
  ggplot(my.cars, aes(wt, mpg, label = name)) +
  geom_point() +
  geom_text_s(aes(size = wt), nudge_x = -0.1, hjust = "right") +
  scale_radius(range = c(3,6)) + # override scale_area()
  expand_limits(x = c(1.8, 5.5))

p2
```

![](https://i.imgur.com/7MggTOK.png)

<sup>Created on 2024-03-03 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by aphalo** [comment]
Hi Teun,
Many thanks! I will try on a different computer to start with...

**Comment by aphalo** [comment]
I should have known better! The problem with the `draw_key_text` and `draw_key_label` was a missing @include to ensure correct collation order. So, I close this issue while I try to fix the problem on 'ggpp' side as anyway these functions need tweaking in 'ggpp' so that they display the correct mappings.

**Comment by aphalo** [comment]
Hi Teun,
Problem is now solved in 'ggpp' in `draw_key_text_s()` and `draw_key_label_()` by changing `data$alpha` into `data$alpha %||% 1`. I am not sure why this is needed in 'ggpp' and not in 'ggplot2', and even not in your R setup for 'ggpp', but as the functions in `legend-draw.R` are exported, you may want to consider if this same edit is needed in the different functions defined in this source file. Otherwise, this can be closed, and remain as a note in case some other extension package hits the same problem.

**Comment by teunbrand** [comment]
@aphalo as this issue is now solved on the ggpp side, is there a reason we should keep this issue open in ggplot2? I'm not quite sure what you mean by: 'you may want to consider if this same edit is needed in the different functions defined in this source file'.

**Comment by aphalo** [comment]
@teunbrand No need on my side to keep this open. I just wanted to let you know that it seems surprising that in 'ggplot' in `draw_key_text()` and `draw_key_label()` all aesthetic values from `data` are _protected_ with a default value using `%||%` except for `alpha`.  As this was the cause of the problem in 'ggpp', I am not sure if the missing `%||% 1` for `alpha` is intentional or not. 

In 'ggpp' I had to implement the same mechanism using `%||%` for `param` as, surprisingly to me, default arguments for formal parameters in the geom definition, in some cases, are not visible to the `draw_key` functions. This, of course, maybe a problem in 'ggpp' rather than in 'ggplot2'. For the time being, using `%||%`,  gets everything working.

At the moment, everything is working fine in 'ggpp' and 'ggpmisc'. So, I let you decide whether to close this issue or put it on-hold. Or maybe consult with Thomas.

**Comment by clauswilke** [comment]
@aphalo If `alpha` is not overridden by default it's almost certainly intentional, because I spent a lot of time thinking about this code and I wouldn't just accidentally forget to put a default in place.

I don't remember the details, but the more I think about it the more I believe it's something along the following lines: I suspect what's happening is that setting `alpha` to 1 prevents the use of colors that have their own `alpha` values (i.e., RGBA colors), which is something I do a lot. So the logic is that when no `alpha` value is provided then the A channel of the color should just remain unchanged.

**Comment by aphalo** [comment]
Thanks for the explanation! This makes a lot of sense. Best wishes.
