### ISSUE TITLE
Some arguments are in snakecase

### ISSUE THREAD

**Issue by davidhodge931** [tidyverse/ggplot2#5751]
I noticed a few arguments in the newer functions have words separated by _'s instead of .'s
https://ggplot2.tidyverse.org/reference/coord_polar.html
https://ggplot2.tidyverse.org/reference/guide_axis_logticks.html

Not sure if this intentional? It doesn't seem applied consistently.

I'd vote for big breaking changes to make all arguments with words separated by _'s. 

But if ggplot2 is not prepared to do this, then I think it is prob better to just be consistent in the package with words separated by .'s

**Comment by teunbrand** [comment]
@thomasp85 is it still timely to change the underscores to dots?

**Comment by thomasp85** [comment]
ugh, thought we caught them all... yeah, we should change them but we need to go through proper deprecation

**Comment by davidhodge931** [comment]
Also guide_colourbar and guide_coloursteps have available_aes argument

**Comment by davidhodge931** [comment]
Also geom_text/label/sf_text/sf_label have nudge_x and nudge_y.

coord_sf also has some

**Comment by davidhodge931** [comment]
Ah, thats a few.

Assume it'd be too breaking-ish to change everything to snakecase?

Be more tidyverse aligned

**Comment by teunbrand** [comment]
Overview for the 70 functions here: https://github.com/tidyverse/ggplot2/blob/be9db37ad3510f4e8e38b963cb3de4785199cd6f/tests/testthat/_snaps/prohibited-functions.md
