### ISSUE TITLE
scale_color_gradientn errors when using labels

### ISSUE THREAD

**Issue by tvatter** [tidyverse/ggplot2#5753]
---

I found a problem with `scale_color_gradientn`.

I expected to be able to use the `labels` argument to tweak the labels, but I must be doing something wrong.

Here is the code to reproduce what I believe to be a bug:

``` r
library(tidyverse)
library(scales)
#> 
#> Attaching package: 'scales'
#> The following object is masked from 'package:purrr':
#> 
#>     discard
#> The following object is masked from 'package:readr':
#> 
#>     col_factor

set.seed(1)
nyears = 20
df <- tibble( # a toy dataset
  year_idx = rep(1:nyears, each = 12),
  month = rep(1:12, nyears),
  passengers = rnorm(nyears * 12, mean = 10 * rep(1:nyears, each = 12))
)

years <- 1970:(1970 + nyears - 1)

ggplot(df, aes(x = month, y = passengers, color = year_idx, group = year_idx)) +
  geom_line() # works
```

![](https://i.imgur.com/IpysczR.png)

``` r

ggplot(df, aes(x = month, y = passengers, color = year_idx, group = year_idx)) +
  geom_line() +
  scale_color_gradientn(colours = (scales::hue_pal())(9),
                        labels = function(idx) years[idx]) # errors
#> Error in `scale_color_gradientn()`:
#> ! `breaks` and `labels` have different lengths.
```

<sup>Created on 2024-03-06 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by tvatter** [comment]
I forgot to mention, I'm running R 4.3.2 and I think that the same thing was working as expected in a previous R version

**Comment by teunbrand** [comment]
Automatic break calculation includes 0 as a break in your example, which cannot be used to index the `years` variable.
If you're setting the `labels` argument to anything other than a formatting function, it is advised to also set the `breaks` argument.
As this is neither a bug or feature request, I'll close this issue.

**Comment by tvatter** [comment]
@teunbrand Awesome, thanks a lot for the explanation!
