### ISSUE TITLE
An issue when applying ggsave() to JPG files

### ISSUE THREAD

**Issue by taozhou2020** [tidyverse/ggplot2#5755]
When I use the following code to save the figure, even if I specify the dpi = 300, the resolution in the saved JPG file is still 96 dpi. This happens (always 96 dpi) even when I save other figures.
```r
ggsave("plot.jpg", dpi = 300)
```
This seems to be a bug when applying ggsave() to JPG files.

**Comment by clauswilke** [comment]
The output image is of the correct size determined by your dpi settings. What dpi value is stored in your jpg is irrelevant. (And I also believe ggplot2 has no access to it, but that's a separate question.)

``` r
library(ggplot2)
library(jpeg)

p <- ggplot(iris, aes(Sepal.Length, Sepal.Width)) +
  geom_point()

ggsave("plot.jpg", p, width = 5, height = 5, dpi = 300)

# the image is 1500 x 1500, which corresponds to 
# 300 dpi * 5 inch in each dimension 
img <- readJPEG("plot.jpg")
dim(img)
#> [1] 1500 1500    3
```

<sup>Created on 2024-03-06 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by teunbrand** [comment]
Yeah writing properties to files is handled by graphics devices, not by ggplot2. If they don't write the resolution property, there isn't anything ggplot2 can do about it. As Claus points out, the dimensions are correct, so I'll close this issue.
