### ISSUE TITLE
Feature request: expose `palette` in discrete position scales

### ISSUE THREAD

**Issue by teunbrand** [tidyverse/ggplot2#5770]
The idea behind exposing a palette to discrete position scales is that the palette can be used to set custom spacings between discrete variables. Currently the 'palette' of discrete position scales is essentially `seq_along()`, and the ask here is to open this up to other functions that can translate discrete variables to continuous positions.

To give an example, let's say I have the following plot with a fake continuous scale separating groups of clarity:

``` r
library(ggplot2)

clarity_position <- function(x) {
  as.integer(x) + c(0, 1, 1, 2, 2, 3, 3, 4)[match(x, levels(x))] 
}
ggplot(diamonds, aes(clarity_position(clarity), price, group = clarity)) +
  geom_boxplot() +
  scale_x_continuous(
    breaks = c(1, 3, 4, 6, 7, 9, 10, 12),
    labels = levels(diamonds$clarity)
  )
```

![](https://i.imgur.com/tJjQKVQ.png)

<sup>Created on 2024-03-12 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

I'd like to express a similar plot in the following way:

``` r
ggplot(diamonds, aes(clarity, price)) +
  geom_boxplot() +
  scale_x_discrete(
    palette = \(x) c(1, 3, 4, 6, 7, 9, 10, 12)
  )
```

I'd imagine it just uses the discrete expansion rules and not show minor breaks in the panel grid.

**Comment by davidhodge931** [comment]
This looks useful :)

Wondering if this argument could be called `pal` instead of `palette`, so that it aligns with {scales} terminology?

**Comment by teunbrand** [comment]
I don't think it is worth the hassle renaming the `palette` argument for this particular request as `palette` is a pre-existing argument to the scale constructors. But yeah the `pal_*()` functions from {scales} are function factories whose results are valid input for the `palette` arguments in ggplot2.
