### ISSUE TITLE
scale_color_identity - additional NAs in the figure legend

### ISSUE THREAD

**Issue by totajuliusd** [tidyverse/ggplot2#5775]
I found a problem when using the scale_color_identity function with version 3.5 of ggplot2

With previous versions of ggplot2 the plots I have generated have looked like this (see the legend)

![image](https://github.com/tidyverse/ggplot2/assets/106526694/f8102003-f678-4a4c-821a-570dfe5ef8e5)

Now it looks like this:

![image](https://github.com/tidyverse/ggplot2/assets/106526694/921f09de-aaed-406e-b220-d4b17ff51430)

Here is the code to reproduce the latter plot:

```r
library(topr)
m1 <- manhattan(list(CD_UKBB,CD_FINNGEN), show_legend = F)
m1+scale_color_identity(guide = "legend",  name="data", c("darkblue","#E69F00"), labels=c("dat1","dat2"))
```
How can I fix this? Any help with this is much appreciated!

**Comment by teunbrand** [comment]
Hi there, thanks for the report. Can you shop down the example to a more direct reproducible example, preferably with as little additional packages involved? At this point it is unclear whether the `manhattan()` function is doing something wrong, or ggplot2 is.

**Comment by totajuliusd** [comment]
That solves it! Thank you very much for your prompt help!
