### ISSUE TITLE
 To develop a new function gg_barbs to plot wind vectors

### ISSUE THREAD

**Issue by PanfengZhang** [tidyverse/ggplot2#5779]
### Tips for a helpful feature request:

In situations when draw wind vectors (or wind barbs) with python <https://matplotlib.org/stable/plot_types/arrays/barbs.html#sphx-glr-plot-types-arrays-barbs-py>, I would like to be able to draw wind vectors (or wind barbs) using ggplot2 package.  This wind vector is very commonly used in meteorology, and I would like you to develop a new function **gg_barbs** to plot such a graph.

Thank you very, very much.

The wind vector illustration effect is as follows:

![Uploading Figure_1.png…]()

**Comment by teunbrand** [comment]
This feature request seems out of scope for ggplot2 as it appears to be very specific to meteorology. Perhaps this is a better fit for a specialised package like metR.

**Comment by thomasp85** [comment]
Yeah, this kind of feature is better suited for a dedicated package
