### ISSUE TITLE
Allow several simultaneous colour scales

### ISSUE THREAD

**Issue by jiho** [tidyverse/ggplot2#578]
While we think about reorganizing `scale_colour/fill` functions in pull request #439, here is an additional suggestion:

I think it would be worthwhile to have a `variable` argument to the scale functions, which would determine to which variable the scale applies and would therefore enable having several colour (or shape, or ...) scales on the same plot for various variables. Of course this can be a problem perceptually (if the colour scales are too similar) but it can also be efficient and even required to represent complex data sets.

Consider graphs like this: http://ars.els-cdn.com/content/image/1-s2.0-S1053811912001255-gr2.jpg where there are various colour scales for various data sources (regions of the brain in that case).
Or maps like this: http://comlmaps.org/mcintyre/ch11/image_n/nfg003.jpg/image_preview (sorry, quite small) with a blue scale for depth and another scale (green to red) for species abundance.

Here is a practical example

```
library(reshape2) # for melt

# volcano map, which really is the background of the plot
vd <- melt(volcano)
names(vd) <- c("x", "y", "z")

# point measurements of something (abund) at a few locations
d <- data.frame(x=runif(30, 1, 80), y=runif(30, 1, 60), abund=rnorm(30))

# plot the points on top of the map
ggplot(mapping=aes(x=x, y=y)) + geom_tile(aes(fill=z), data=vd) + geom_point(aes(colour=abund), data=d, size=3) + scale_colour_gradient(high="red", low="green")
# this works because I map *fill* in one geom and *colour* in the other

# but this collapses the scales of the background and the points because both use fill
ggplot(mapping=aes(x=x, y=y)) + geom_tile(aes(fill=z), data=vd) + geom_point(aes(fill=abund), data=d, size=3, shape=21) + scale_fill_gradient(high="red", low="green")

# I would like to do
ggplot(mapping=aes(x=x, y=y)) + geom_tile(aes(fill=z), data=vd) + geom_point(aes(fill=abund), data=d, size=3, shape=21) + scale_fill_gradient(variable=abund, high="red", low="green")
# and get a result similar to the first plot above
```

**Comment by t-kalinowski** [comment]
+1. 
My use case: I tried to apply different color scales to geom_point and geom_line layers on a timeseries plot.

**Comment by glorious1** [comment]
I use ggplot2 for mapping with rasters.  First goes a hillshade with gray that gets and scale_alpha for the hillshade value (slope and aspect combined).  Second the map is alpha-tinted slightly for elevation with a scale_fill_gradientn from red at low elevations to yellow and green to white at high elevations.  The combination looks awesome.

![powd_pipu_cgh_gte-50](https://user-images.githubusercontent.com/6004417/28934632-e9f63540-783e-11e7-94d8-c15917ebaf55.png)

But this is just the base of the map.  Now I need to add data.  I have a raster with several data values that only show in portions of the map, each value getting a different color.  I would normally use scale_fill_manual for that, but I can't, and I can't find a workaround that applies here.

Thank you hadley for this unbelievable package.  It's taken me a long time to get this far, but it's worth it.
