### ISSUE TITLE
Trends over time

### ISSUE THREAD

**Issue by mohammad-numan** [tidyverse/ggplot2#5780]
How I can do graphic visualization for prescription trends, the year column has repeated data over 4 years!

**Comment by teunbrand** [comment]
This issue tracker is for bug reports and feature requests. If you need help with your visualisation, please post in the [community](https://community.rstudio.com/) or [stackoverflow](https://stackoverflow.com/) with a [reproducible example](https://www.tidyverse.org/help/#reprex).
