### ISSUE TITLE
`drop = F` works incorrectly  for factors in ggplot2 v3.5.0

### ISSUE THREAD

**Issue by lbenz730** [tidyverse/ggplot2#5785]
Running the following code w/ ggplot2 3.5.0 produces the following incorrect plot

```{r}
library(tidyverse)

iris %>% 
  mutate('Species' = as.factor(Species)) %>% 
  head(50) %>% 
  ggplot(aes(x = Sepal.Length, y = Sepal.Width)) + 
  geom_point(aes(color = Species)) +
  scale_color_discrete(drop = F)
```
<img width="632" alt="Screenshot 2024-03-19 at 4 31 41 PM" src="https://github.com/tidyverse/ggplot2/assets/21962947/b14d0501-9602-4db4-9f1f-51948dfca886">

Re-running the same code with v3.4.4  produces the expected plot, with point colors shown for factor levels not present in the dataset. After experiementing, I noticed the same issues for fill related variables and suspect the problem is larger in scope than what I have shown here. 
<img width="663" alt="Screenshot 2024-03-19 at 4 32 59 PM" src="https://github.com/tidyverse/ggplot2/assets/21962947/30f14241-0305-4698-b998-343b7e373a01">

**Comment by teunbrand** [comment]
Hi there, thanks for your report! This issue seems very similar to #5728, so I'll close this one as a duplicate to keep discussion in one place.
