### ISSUE TITLE
`guide_colorsteps()` missbehaving with discrete values after 3.5.0 

### ISSUE THREAD

**Issue by eliocamp** [tidyverse/ggplot2#5786]
In the previous ggplot2 version (3.4.4) `guide_colorsteps()` would behave reasonably for discrete values:

``` r
library(ggplot2)
levels <- pretty(range(volcano))

volcano2 <- reshape2::melt(volcano) |> 
  transform(value_discrete = cut(value, 
                                 breaks = levels,
                                 ordered_result = TRUE))


ggplot(volcano2,  aes(Var1, Var2)) +
  geom_raster(aes(fill = value_discrete)) +
  guides(fill = guide_colorsteps())
```

![](https://i.imgur.com/0ZkyL2R.png)

<sup>Created on 2024-03-20 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

In ggplot2 3.5.0, the guide is all wonky and in the wrong order: 

``` r
library(ggplot2)
levels <- pretty(range(volcano))

volcano2 <- reshape2::melt(volcano) |> 
  transform(value_discrete = cut(value, 
                                 breaks = levels,
                                 ordered_result = TRUE))


ggplot(volcano2,  aes(Var1, Var2)) +
  geom_raster(aes(fill = value_discrete)) +
  guides(fill = guide_colorsteps())
```

![](https://i.imgur.com/4BayReT.png)

This might be something to do with the new guide system.

**Comment by teunbrand** [comment]
Thanks for the report Elio! This was reported before in #5757 and should be fixed in the development version. We plan on releasing a hotfix for the issues caused by 3.5.0 once we have a good idea what bugs it may have caused for people.

**Comment by eliocamp** [comment]
Oh, my apologies for the duplicate issue. Thanks!
