### ISSUE TITLE
Could a GeomBin2d ggproto object be created?

### ISSUE THREAD

**Issue by davidhodge931** [tidyverse/ggplot2#5791]
It would helpful to have a GeomBin2d ggproto object exported.

This is because for `ggplot2::update_geom_defaults`, it's useful to have different defaults for GeomTile and GeomBin2d.

**Comment by teunbrand** [comment]
There isn't any GeomBin2d ggproto object currently. Is the request here to make one for the sake of `update_geom_defaults()`?

**Comment by davidhodge931** [comment]
Yeah, I'm not sure how hard it would be. But if it was easy, it'd be super useful
