### ISSUE TITLE
Cannot remove outliers

### ISSUE THREAD

**Issue by vivekJax** [tidyverse/ggplot2#5795]
I found a problem with geom_boxplot(outliers = FALSE)

I expected to remove outliers as specified here 
https://ggplot2.tidyverse.org/reference/geom_boxplot.html

Here is the code to reproduce the bug:

```r
df <- data.frame(
Name = rep(c("A","B","C"), 5),
Age = c(1,2,3,4,5,6,7,8,99, 2,3,4,2,3,5)
 )

ggplot(df, aes(x = Name, y = Age)) + geom_boxplot() # works fine

ggplot(df, aes(x = Name, y = Age)) + geom_boxplot(outlier.shape = NA) # works fine

ggplot(df, aes(x = Name, y = Age)) + geom_boxplot(outliers = FALSE)

Warning message:
In geom_boxplot(outliers = FALSE) :
  Ignoring unknown parameters: `outliers`
```

**Comment by teunbrand** [comment]
What version of ggplot2 are you using? The online reference applies to the latest one.

**Comment by vivekJax** [comment]
I was on 3.4.4, it works with the newest version. thx.
