### ISSUE TITLE
errorbar width does not seem able to update with `update_geom_defaults`

### ISSUE THREAD

**Issue by davidhodge931** [tidyverse/ggplot2#5796]
It seems to make the width go to maximum instead of your updated geom default value
``` r
library(tidyverse)

GeomErrorbar$default_aes
#> Aesthetic mapping: 
#> * `colour`    -> "black"
#> * `linewidth` -> 0.5
#> * `linetype`  -> 1
#> * `width`     -> 0.5
#> * `alpha`     -> NA

update_geom_defaults("errorbar", ggplot2::aes(width = 0.2))

data.frame(
  trt = factor(c(1, 1, 2, 2)),
  resp = c(1, 5, 3, 4),
  group = factor(c(1, 2, 1, 2)),
  upper = c(1.1, 5.3, 3.3, 4.2),
  lower = c(0.8, 4.6, 2.4, 3.6)
) |>
  ggplot(aes(
    x = trt,
    ymin = lower,
    ymax = upper,
    col = group
  )) +
  geom_errorbar()
```

![](https://i.imgur.com/3wTIRuq.png)

<sup>Created on 2024-03-23 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by teunbrand** [comment]
Yeah this a little bit tricky. The width you see in your example actually comes from the `GeomErrorbar$setup_data()` method, which  means that by the time the defaults are used, the `width` is already populated so the default doesn't kick in. You can see that in your plot too, the width is 0.9 instead of the 0.5 declared in the default aesthetics (or 0.2 when updated).

**Comment by davidhodge931** [comment]
Ah okay, don't suppose the default could change to be smaller? 

0.5 looks way too big, right? I'd go for 0.1.

Otherwise, feel free to close

**Comment by teunbrand** [comment]
Well changing the `width = 0.5` in `GeomErrorbar$default_aes` is not actually going to change the default. The 'practical default' is 0.9 for discrete data. While for 2 discrete items it indeed does look too big in my eyes, but the current behaviour makes sense if you have many items that require an errorbar.

``` r
library(ggplot2)
ggplot(USArrests, aes(Murder, rownames(USArrests))) +
  geom_errorbar(aes(xmin = Murder - 1, xmax = Murder + 1))
```

![](https://i.imgur.com/ROF7QLy.png)

<sup>Created on 2024-03-25 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>
