### ISSUE TITLE
Persistent warning when using geom_point suggesting to use annotate 

### ISSUE THREAD

**Issue by EA-Ammar** [tidyverse/ggplot2#5797]
Providing `geom_point `with simple x and y parameters now consistently triggers a warning suggesting to use `annotate`.

This warning is also visible several places on the reference page [Position related aesthetics: x, y, xmin, xmax, ymin, ymax, xend, yend](https://ggplot2.tidyverse.org/reference/aes_position.html), so I assume that this is not working as intended. If it is, I don't understand how `annotate `is an alternative.

Reproducible example:

```r
library("tidyverse")

# Sample data
dat <- data.frame(xvar = c(1:100),
                  yvar = c(101:200))

# Chart with geom warning
ggplot(dat,
       aes(x = cap,
           y = maint)) + 
  geom_point(aes(x= 5,
                 y = 125))

```
Resulting in warning:

> Warning message:
In geom_point(aes(x = 5, y = 125)) :
  All aesthetics have length 1, but the data has 100 rows.
ℹ Did you mean to use `annotate()`?

**Comment by teunbrand** [comment]
This issue is very similar to #5762, so I suggest to continue discussion there to keep it all in one place.
