### ISSUE TITLE
Changes in scale_color_manual ggplot 3.5.0

### ISSUE THREAD

**Issue by samuel-marsh** [tidyverse/ggplot2#5812]
Hi ggplot2 Team,

I'm probably just missing something because this feels very obvious but can't figure out the change that happened in 3.5.0 that caused this behavior.

In short I have function in my package (function link [here](https://github.com/samuel-marsh/scCustomize/blob/fc7a282af3bef6e1cb816fac3b9229f536159238/R/Seurat_Plotting.R#L1659)) that returns plot with `geom_point` for the underlying data.  The user can specify to create multiple plots splitting the data by given variable to show multiple conditions side-by-side.  The plot is colored using `scale_color_manual` by another variable in the data.  Sometimes as happens with data when splitting the data some of the levels that used for coloring the plots may not be present in all subsets.

Previously (ggplot 3.4.4) I provided a named vector of colors to `values` and added `drop = FALSE` and then used patchwork to collect the guides so that on legend is provided for all plots in the layout.

However, now with 3.5.0 it is returning multiple guides with the na level present but with no color next to it so that when guides are collected with patchwork it sees multiple guides and returns multiple with the plot.

Example here:
![image](https://github.com/tidyverse/ggplot2/assets/38284410/dd580306-a166-465e-a0f1-14badb9e9c5c)

I hope I explained that ok but please let me know if you have any questions.  Maybe my mind just isn't working today and I'm missing something very basic that has changed (or maybe it is a bug with `drop`?) but any help you can provide would be appreciated!

Best,
Sam

**Comment by clauswilke** [comment]
Could you please create a minimal reproducible example of the exact behavior that is causing you problems? Just draw up a simple plot with one or more legends that don't look the way you'd think they should.

**Comment by teunbrand** [comment]
This all sounds very similar to #5728. TL;DR: This is intended, to include a layer's key glyph in the legend without the data being present, use `show.legend = TRUE`.

**Comment by samuel-marsh** [comment]
@teunbrand @clauswilke 
Thanks both for quick replies!!

Indeed it does sound like that previous issue.  However, in my case the base plot is being returned from another package as ggplot2 object.  So can't pass the `show.legend = TRUE` in original `geom_point` call.  What is the best (or least hacky maybe) was to pass this parameter when modifying that original plot?

Best,
Sam

**Comment by samuel-marsh** [comment]
Hi @clauswilke,

Working on re-creating essential aspects of functions without such heavy package dependencies.  Working on recreating all the modifications that the original package does to the plot correctly and then how my function modifies that returned plot.  Might be tomorrow before I can complete that but working on it.

I realize this isn't exactly minimal example because it's dependency heavy but in case it's help the full issue below does show the issue (requires Seurat; heavy dep).

Uses these two Seurat functions:
[DimPlot](https://github.com/satijalab/seurat/blob/c54e57d3423b3f711ccd463e14965cc8de86c31b/R/visualization.R#L859)
[SingleDimPlot](https://github.com/satijalab/seurat/blob/c54e57d3423b3f711ccd463e14965cc8de86c31b/R/visualization.R#L8185)

Then modified by function in my package scCustomize:
[DimPlot_scCustom](https://github.com/samuel-marsh/scCustomize/blob/fc7a282af3bef6e1cb816fac3b9229f536159238/R/Seurat_Plotting.R#L1659)

This section in particular is modifying the color levels of the plot generated by Seurat:
https://github.com/samuel-marsh/scCustomize/blob/fc7a282af3bef6e1cb816fac3b9229f536159238/R/Seurat_Plotting.R#L1892-L1935

```
# ggplot 3.5.0
install.packages("Seurat")
install.packages("scCustomize")

# plot with all levels present in both plots
DimPlot_scCustom(seurat_object = pbmc, split.by = "treatment")

# create subset without one level
data <- FetchData(object = pbmc, vars = c("treatment", "seurat_annotations"))

cells_remove <- data %>% 
  filter(treatment == "Treatment1" & seurat_annotations == "Naive CD4 T") %>% 
  rownames()


pbmc_subbed <- subset(pbmc, cells = cells_remove, invert = TRUE)

DimPlot_scCustom(seurat_object = pbmc_subbed, split.by = "treatment")
```

![image](https://github.com/tidyverse/ggplot2/assets/38284410/bdfb254d-bcff-4df9-8996-f03ec441a41f)


Running same thing with ggplot2 3.4.4 results in:
![image](https://github.com/tidyverse/ggplot2/assets/38284410/88f086dd-38af-4a1a-8456-a81f0a2ae8ed)


Again I realize this is the heavy version for sure and working on more minimal example that maintains plots correctly.

Thanks so much again for the quick replies!!
Best,
Sam

**Comment by clauswilke** [comment]
You need to learn how to make minimal reproducible examples. Here, I'll give you a starting point, but you'll have to take it from here. I'm not going to read your package code or install your package or look at an example that is more than maybe 30-40 lines of code total.

``` r
library(tidyverse) 

data <- tibble(
  x = 1:3,
  y = 3:1,
  a = factor(c("A", "A", "B"), levels = c("A", "B", "C"))
)

# green dot is missing from legend
ggplot(data, aes(x, y, color = a)) +
  geom_point() +
  scale_color_manual(
    values = c(A = "red", B = "blue", C = "green")
  )
```

![](https://i.imgur.com/L5UxqMb.png)

``` r

# green dot is present
ggplot(data, aes(x, y, color = a)) +
  geom_point(show.legend = TRUE) +
  scale_color_manual(
    values = c(A = "red", B = "blue", C = "green"),
    drop = FALSE
  )
```

![](https://i.imgur.com/TvAOO86.png)

<sup>Created on 2024-03-27 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by teunbrand** [comment]
I'd also like to note that using facetting instead of plot composition might circumvent the issue altoghether.
Another solution might be to 'cut the middleman' and construct plots de novo instead of wrapping plotting functions that wrap ggplot2. I'd find it very strange if Seurat doesn't provide accessors to wrangle the relevant data out of their data structures.

**Comment by clauswilke** [comment]
Would it be a problem to just set `show.legend = TRUE` in the functions that generate `p1` and `p2`?

Alternatively, you could possibly code something like the following. You may have to iterate over all layers and make sure you're actually modifying `geom_point()` layers only.

``` r
library(tidyverse) 

data <- tibble(
  x = 1:3,
  y = 3:1,
  a = factor(c("A", "A", "B"), levels = c("A", "B", "C"))
)

# green dot is missing from legend
p <- ggplot(data, aes(x, y, color = a)) +
  geom_point() +
  scale_color_manual(
    values = c(A = "red", B = "blue", C = "green"),
    drop = FALSE
  )
p
```

![](https://i.imgur.com/NtkvYtR.png)

``` r

# turn on green dot after the fact
p$layers[[1]]$show.legend <- TRUE
p
```

![](https://i.imgur.com/6yFzYlH.png)

<sup>Created on 2024-03-27 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by samuel-marsh** [comment]
Hi @clauswilke,

Yes, I think I will put PR in to Seurat to add that to the base code for the function in question.

Thanks for the example with modifying the layers in output.  I'll play around with that and faceting in the short-term until PR can be approved.

Thank you both @clauswilke and @teunbrand again for your help with this, I really appreciate it!!

Best,
Sam
