### ISSUE TITLE
Problem of hjust in legend.text in ggplot2 v3.5.0

### ISSUE THREAD

**Issue by lcpmgh** [tidyverse/ggplot2#5835]
After updating to version 3.5.0, I attempted to adjust the distance between the legend keys and labels using `hjust`. However, only some of the text shifted, and the movement’s occurrence and scale seemed to be related to the content of the text. I suspect this might be a bug. By the way, I learned from other users that using `margin` can perfectly adjust the distance between keys and labels.

For the problem I mentioned, here is a simplified example:

```r
# Figure 1
dt <- data.frame(x=c("a","b","cc","d"), y=c(1,2,3,4))
ggplot(dt, aes(x, y, fill=x))+
  geom_bar(stat = "identity")+
  theme(legend.text = element_text(hjust = 3))

# Figure 2
dt <- data.frame(x=c("ab","bb","dc","ds"), y=c(1,2,3,4))
ggplot(dt, aes(x, y, fill=x))+
  geom_bar(stat = "identity")+
  theme(legend.text = element_text(hjust = 15))
```
![fig](https://github.com/tidyverse/ggplot2/assets/35483163/31ba3d08-898e-4e9d-97da-3ecc7b08fd0e)

**Comment by teunbrand** [comment]
I don't quite understand why the text is positioned this way in your example, but for increasing the space you should indeed use the `element_text(margin)` setting. The `hjust` setting should typically be between 0 and 1 and while `hjust = 15` is accepted, how it is interpreted might depend on circumstances.

**Comment by teunbrand** [comment]
I'm closing this issue as the problem of spacing text from their keys has a better solution than using `hjust`.
