### ISSUE TITLE
Error using `after_stat(ecdf)` in `geom_ribbon()`

### ISSUE THREAD

**Issue by cgoo4** [tidyverse/ggplot2#5836]
Why does the first example fail, but the second succeed?

``` r
library(ggplot2)

set.seed(1)
df <- data.frame(x = c(rnorm(100, 0, 3), rnorm(100, 0, 10)))

# Fails
ggplot(df, aes(x)) +
  stat_ecdf(geom = "step") +
  geom_ribbon(aes(x, ymin = after_stat(ecdf) - 0.1, ymax = after_stat(ecdf) + 0.1),
    alpha = 0.2
  )
#> Error in `geom_ribbon()`:
#> ! Problem while mapping stat to aesthetics.
#> ℹ Error occurred in the 2nd layer.
#> Caused by error in `after_stat(ecdf) - 0.1`:
#> ! non-numeric argument to binary operator

# Succeeds
p <- ggplot(df, aes(x, ymin = after_stat(ecdf) - 0.1, ymax = after_stat(ecdf) + 0.1)) +
  stat_ecdf(geom = "step")

p + geom_ribbon(aes(x, ymin = ymin, ymax = ymax), alpha = 0.2, data = layer_data(p, 1))
```

![](https://i.imgur.com/5OZjZgJ.png)

<sup>Created on 2024-04-10 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by teunbrand** [comment]
You'd need to add `stat = "ecdf"` to the ribbon layer in the first example. Computed variables, like `ecdf` are computed per layer, so the ribbon layer is unaware of what is happening in the `stat_ecdf()` layer. However, this is not a bug as throwing an error is appropriate in this case. Intercepting this error to give a more informative message is challenging, so there is not much room for improvement.
