### ISSUE TITLE
random mismatches from `join_keys`

### ISSUE THREAD

**Issue by jmbuhr** [tidyverse/ggplot2#5840]
So this is one of the strangest bugs I ever encountered and I'm happy about any pointers.

I am getting errors when using facets, specifically:

```
Error in `scale_apply()`:
! `scale_id` must not contain any "NA".
```
From
```
ggplot2:::scale_apply(layer_data, x_vars, "train", SCALE_X, x_scales)
```

**But**, even though I have an example that can reliably reproduce the issue (see repo with code and example data linked below), the issue only appears

a) randomly (hence the for-loop to plot 100 times, though 10 is usually enough when it appears)
b) on one specific workstation. I have not been able to reproduce it on another workstation, even with the same CPU model, OS (ubuntu 22.04) and home folder (on a network filesystem)

I have further tracked down the issue to

https://github.com/tidyverse/ggplot2/blob/1050f093b974d4a9dcac621e2df79a34d3b0679f/R/compat-plyr.R#L161-L168

where the keys sometimes get scrambled, coming from the `id` function. And there most of the time the result has
`y = 1 2 3 4 5 6 7 8 9 10`, but when the error happens it gets new seemingly random numbers like `y = 1 3 5 7 9 10 11 13 14 15`. This then leads to the mismatch between x and y and the downstream `NA` error.

Here is the code to reproduce the bug:

https://github.com/jmbuhr/ggplot-na-issue

Critical piece from index.qmd:

```R
for (i in 1:100) {
  p <- data |>
    ggplot() +
    aes(x, y) +
    facet_grid(facet_a ~  facet_b)
  print(p)
}
```

Related: https://github.com/tidyverse/ggplot2/issues/5485 has the same error message, but I assume the underlying cause is different.

**Comment by jmbuhr** [comment]
Some more insights:

If I replace the `id` function used in `join_keys` with somewhat heavier dplyr machinery, it works:
https://github.com/jmbuhr/ggplot2/blob/2e4206d99036e62c615da8a69e124832da94716c/R/compat-plyr.R#L128-L140
```R
id_like <- function(.variables, drop = FALSE) {
  unique_rows <- dplyr::distinct(.variables) |>
    dplyr::mutate(id = dplyr::row_number())
  n  <- nrow(unique_rows)
  res <- .variables |>
    dplyr::left_join(unique_rows) |>
    dplyr::pull(id)
  attr(res, "n") <- n
  res
}
```
This would of course break other usecases if the `id` function, so it's not a fix, but it further isolates the problem.

**Comment by teunbrand** [comment]
I've run the example in the repo you linked to, but I'm not confronted with this error on Win10.
If you think something is wrong with `ggplot2:::join_keys()`, you might be able to show what kind of inputs give faulty outputs directly using that function.

**Comment by jmbuhr** [comment]
It's stranger than that. The same input sometimes works and sometimes fails. I expanded https://github.com/jmbuhr/ggplot-na-issue and rendered it on the workstation on which I observe the issue: http://jmbuhr.de/ggplot-na-issue/
And what happens is that when I execute the same function with the same inputs I sometimes get different outputs.

**Comment by jmbuhr** [comment]
Narrowed it down the the matrix multiplication in `id`
```
    res <- c((mat - 1L) %*% combs + 1L)
```

**Comment by teunbrand** [comment]
Non deterministic output of matrix multiplications sounds like a recipe for disaster. I am clueless as to why that would happen on some machines.

**Comment by jmbuhr** [comment]
So it's definitely the matrix multiplication... and the problem happens with `options(matprod = "default")`, but vanishes with `options(matprod = "internal")`: http://jmbuhr.de/ggplot-na-issue/minimal.html

Any idea what could make BLAS behave in such a way? The input matrices don't have any NA, NaN or Infs.

**Comment by jmbuhr** [comment]
I will close this here, as it is certainly not a ggplot issue, but I hope you don't mind if I leave this open just a couple of days in the hopes that someone happens to have an idea.

**Comment by teunbrand** [comment]
I think I'd help to post this on [stackoverflow](https://stackoverflow.com/) or [posit community](https://forum.posit.co/) to reach a wider audience than just those people that read ggplot2 issues.

**Comment by jmbuhr** [comment]
Solved! `sessionInfo()` revealed that the machine in question was using intel's math libraries `libmkl` while all the others are using `openblas`.
For future reference, switching can be done globally under linux with
`sudo update-alternatives --config libblas.so.3-x86_64-linux-gnu` (for blas) and
`sudo update-alternatives --config liblapack.so.3-x86_64-linux-gnu` (for lapack).
I still don't know, why intel's libraries produced the issue, but I'm just happy it works now.

**Comment by jmbuhr** [comment]
Thank you for your hints :)
