### ISSUE TITLE
Could the NA default colour be set for a discrete scale where it is wanted to set colours for multiple levels?

### ISSUE THREAD

**Issue by davidhodge931** [tidyverse/ggplot2#5849]
Hi, 

It'd be great if ggplot2 had functionality to set the default NA colour for a discrete colour/fill scale where one wants to use different colours for different numbers of levels. 

So for example, in the below code, I'd like to be able to also set the default NA colour to "red".

``` r
library(tidyverse)
library(palmerpenguins)
  
options(
    ggplot2.discrete.colour =
      list(
        c('red', "blue"),
        c("green", "yellow", "navy")
      )
  )

penguins |> 
  ggplot() +
  geom_point(aes(x = flipper_length_mm, 
                 y = body_mass_g, 
                 colour = sex))
#> Warning: Removed 2 rows containing missing values or values outside the scale range
#> (`geom_point()`).
```

![](https://i.imgur.com/OCtnEUu.png)

``` r

penguins |> 
  mutate(species = as.character(species)) |> 
  mutate(species = ifelse(flipper_length_mm > 220, NA, species)) |> 
  ggplot() +
  geom_point(aes(x = flipper_length_mm, 
                 y = body_mass_g, 
                 colour = species))
#> Warning: Removed 2 rows containing missing values or values outside the scale range
#> (`geom_point()`).
```

![](https://i.imgur.com/wQRtCO9.png)

<sup>Created on 2024-04-19 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by teunbrand** [comment]
The infrastructure to pass `na.value` via the palette isn't present, so this would be pretty invasive to solve. I'm not saying it can't be done, but it wouldn't be easy.

**Comment by davidhodge931** [comment]
Ah okay, feel free to close if you think @teunbrand
