### ISSUE TITLE
Feature request: reassemble the ggplot object after `ggplot_build`

### ISSUE THREAD

**Issue by wbvguo** [tidyverse/ggplot2#5850]
Hi, thanks for maintaining this tool!

`ggplot_build()` can convert plot object into a ggplot_built list, I was wondering if we could provide a function that converts the ggplot_built class back to the plot object again. e.g. sth like `ggplot_render()`

```r
p = ggplot(mtcars, aes(mpg, wt)) + geom_point()
p_built = ggplot_build(p)
# modify the data/layout in p_built as one might desire
p1= ggplot_render(p_built)
```

Thanks!

**Comment by thomasp85** [comment]
I'm afraid there is no way to do this as it is not necessarily possible that the changes made by a user is compatible with ggplot2 so there may not be a plot object that represents what you are converting back from
