### ISSUE TITLE
partial match (vp$just --> 'justification')

### ISSUE THREAD

**Issue by MichaelChirico** [tidyverse/ggplot2#5851]
The reprex here uses {hexbin}, but I think the error is arising from {ggplot2}, just that I haven't come up with another example.

```r
library(hexbin)
library(ggplot2)
options(warnPartialMatchDollar=TRUE)

DF=data.frame( a=1:5, b=11:50, d=c("A","B","C","D"), f=1:5, grp=1:5 )
p=ggplot(DF) + geom_hex(aes(b, f))
print(p)
# Warning message:
# In vp$just : partial match of 'just' to 'justification'
```

Unfortunately `options(warn=2)` then `browser()` doesn't yield a traceback, so I'm not sure how to proceed.

 - {hexbin} itself [only uses `just` in calls to `grid::viewport()`](https://github.com/search?q=repo%3Aedzer%2Fhexbin+%2F%5B%5Ea-z0-9._%5Djust%5B%5Ea-z0-9._%5D%2F+-path%3A.Rd&type=code), and indeed `"just" %in% names(formals(grid::viewport))`
 - {ggplot2} has many more matches to `just`; stepping through `print.ggplot`, the error happens at this line:

https://github.com/tidyverse/ggplot2/blob/be4b7b8d9821aa19d8cbe22135fcd979978d2035/R/plot.R#L208

And then:

https://github.com/tidyverse/ggplot2/blob/be4b7b8d9821aa19d8cbe22135fcd979978d2035/R/plot-build.R#L191

but I can't debug that call to `plot$guides$assemble`.

 - Searching CRAN generally we do get this match in {gtable}:

https://github.com/search?q=org%3Acran+lang%3AR+%2Fvp%5B%24%5Djust%5B%5Ei%5D%2F&type=code

As well as this match in {grid} itself:

https://github.com/r-devel/r-svn/blob/125ad32d2f936092815062366733b30b1a87d39f/src/library/grid/R/viewport.R#L472

(but debugging `editViewport()` doesn't pick up any calls)

Any ideas where this error might be coming from?

**Comment by teunbrand** [comment]
Hi there, thanks for the report! Is this by any chance the same as #5654? If so, there is already a PR pending in {gtable}: https://github.com/r-lib/gtable/pull/94

**Comment by MichaelChirico** [comment]
100%, great news!
