### ISSUE TITLE
`guide_coloursteps(show.limits = T)` produces strange lower limit

### ISSUE THREAD

**Issue by davidhodge931** [tidyverse/ggplot2#5870]
``` r
library(tidyverse)

ggplot(mpg, aes(displ, hwy, colour = hwy)) +
  geom_point() +
  guides(colour = guide_coloursteps(show.limits = T))
```

![](https://i.imgur.com/LkQpuu0.png)

<sup>Created on 2024-04-29 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by teunbrand** [comment]
The reason for this is that 10 is an out-of-bounds break that for some reason doesn't get censored.
The scale then assigns a colour for 11 (because (10 + 12) / 2 = 11), which is under the lower limit of 12, so it gets na.value.
Out-of-bounds breaks should probably be removed.
