### ISSUE TITLE
Reproducible example for `position_jitter()` not working

### ISSUE THREAD

**Issue by fkohrt** [tidyverse/ggplot2#5875]
It seems to me, the last of the [examples](https://ggplot2.tidyverse.org/reference/position_jitter.html#ref-examples) of `position_jitter()` does not work as intended. In other words: The following code...

https://github.com/tidyverse/ggplot2/blob/8e63882c3c36259785baac0eed5d51525bc40f70/R/position-jitter.R#L43-L47

...does not seem to simply shift the jittered points:

![position_jitter-5](https://github.com/tidyverse/ggplot2/assets/12914806/806de752-b4f4-405f-93e1-813e253cafed)

But maybe I misunderstood what the example is supposed to show?

**Comment by teunbrand** [comment]
Thanks for pointing this out. The position adjustment should be constructed as follows `jitter <- position_jitter(width = 0.1, height = 0.1, seed = 0)` and then it does what it should.
