### ISSUE TITLE
x/ylim Arguments in coord_fixed Don’t Seem to Be Applied to Contours:

### ISSUE THREAD

**Issue by JStorey42** [tidyverse/ggplot2#5883]
I'm unsure if this is actually a feature (perhaps I'm misinterpreting or missing something in the docs) but I've observed that using the x/ylim arguments in coord_fixed (and presumably analogous functions) seem to produce different results than declaring your limits using lims(). Specifically, contours that were originally cut off due to axis limits are no longer cut off using coord_fixed() and lims() with appropriate axis limits. However, passing (the same) appropriate axis limits to the x/ylim arguments within coord_fixed() results in the correct aspect ratio and limits, however, the contours are still cut off in the same place.

Am I missing something or is this a bug? 

Thanks.

A simple contour plot that requires rescaling to accommodate all contours:
```
ggplot(mtcars) +
  stat_density2d(aes(x = mpg, y = wt)) 
```
![image](https://github.com/tidyverse/ggplot2/assets/52438403/88681c98-8a13-4db4-8156-064a4bde0947)

Correcting axis limits to accommodate all contours with lims() and applying coord_fixed() works:
```
ggplot(mtcars) +
  stat_density2d(aes(x = mpg, y = wt)) +
  lims(x = c(5, 45), y = c(-5, 15)) +
  coord_fixed()
```
![image](https://github.com/tidyverse/ggplot2/assets/52438403/fa876f16-45fb-4da2-a166-c005e2807541)

But when correcting axis limits with x/ylim within coord_fixed(), the contours remain cutoff:
```
ggplot(mtcars) +
  stat_density2d(aes(x = mpg, y = wt)) +
  coord_fixed(xlim = c(5, 45), ylim = c(-5, 15))
```
![image](https://github.com/tidyverse/ggplot2/assets/52438403/2494b392-2683-42ec-98c3-61e455559b9c)

**Comment by thomasp85** [comment]
This is expected behaviour though I can see why it may be surprising. The contour stat uses the scale limits (which are set with `lims()`) to figure out the extend of the contouring. The `xlim` and `ylim` arguments in the coords are setting the coordinate limits and act more like a zoom level for the final graphical representation
