### ISSUE TITLE
Adding bootstrap customization for stat_summary(fun.data="mean_cl_boot")

### ISSUE THREAD

**Issue by erinnacland** [tidyverse/ggplot2#5885]
When using `stat_summary(fun.data = "mean_cl_boot")`, bootstrapped means and confidence intervals are produced. The bootstraps are set to 1000, this leads to the means and CIs slightly changing between runs. Below are two runs of the same code, each has slightly different estimates:

[
![Rplot05](https://github.com/tidyverse/ggplot2/assets/149115997/afed3f29-ccff-499e-ae0c-1aa6f24d1446)
![Rplot06](https://github.com/tidyverse/ggplot2/assets/149115997/1901f1bb-af77-4e9b-878e-da5a74c52286)
](url)

Reproducible code:
```
ggplot(iris, aes(x=Species, y=Sepal.Length, fill=Species,)) +
  stat_summary(fun.data="mean_cl_boot") 
```
 This can lead to meaningful changes in estimates depending on the data used and how large the changes are between iterations. 

Is it possible to add a feature where you can edit the number of bootstraps so they can be increased, making results more stable?

**Comment by teunbrand** [comment]
You can already pass additional arguments to the summary function by passing a list to the `fun.args` argument.
As `mean_cl_boot()` is just a wrapper for `Hmisc::smean.cl.boot()`, you can increase `B` to get a more stable estimate like this:
```r
library(ggplot2)
ggplot(iris, aes(x=Species, y=Sepal.Length, fill=Species,)) +
  stat_summary(fun.data = "mean_cl_boot", fun.args = list(B = 10e3)) 
```
Alternatively, you can use `fun.data = ~mean_cl_boot(.x, B = 10e3)` to achieve the same outcome.
In addition, you can use `set.seed()` to fix the effects of the random number generator.

As there are already methods to change the number of bootstraps, I'll close this issue.
