### ISSUE TITLE
Have header font be part of theme specification

### ISSUE THREAD

**Issue by thomasp85** [tidyverse/ggplot2#5886]
Currently the theme constructors takes a base font argument to set the font for the titles/headers.

This ties into #5833 as we should also keep at least two fonts in the geom defaults inside themes

**Comment by teunbrand** [comment]
Is the proposal here to do something like the following:

```r
theme_grey <- function(..., base_family = "", header_family = base_family) {
  theme(
    text = element_text(family = base_family),
    title = element_text(family = header_family),
    ...
  )
}
```
