### ISSUE TITLE
Default labs where geom when the aesthetic is in both the ggplot and geom_* call

### ISSUE THREAD

**Issue by davidhodge931** [tidyverse/ggplot2#5894]
Default labs are not created based on aesthetics in the geom when the aesthetic is in both the ggplot and geom_* call 
``` r
library(tidyverse)
library(palmerpenguins)

penguins |> 
  ggplot(aes(x = flipper_length_mm, y = body_mass_g, colour = sex)) +
  geom_point(aes(x = bill_depth_mm, y = bill_length_mm, colour = species))
#> Warning: Removed 2 rows containing missing values or values outside the scale range
#> (`geom_point()`).
```

![](https://i.imgur.com/WrlQiLl.png)

<sup>Created on 2024-05-20 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by teunbrand** [comment]
Should be fixed in the label refactoring in #5879.
OTOH, some people might expect the global aesthetics to overrule local aesthetics.

``` r
devtools::load_all("~/packages/ggplot2")
#> ℹ Loading ggplot2

palmerpenguins::penguins |> 
  ggplot(aes(x = flipper_length_mm, y = body_mass_g, colour = sex)) +
  geom_point(aes(x = bill_depth_mm, y = bill_length_mm, colour = species))
#> Warning: Removed 2 rows containing missing values or values outside the scale range
#> (`geom_point()`).
```

![](https://i.imgur.com/tHDrOpX.png)

<sup>Created on 2024-05-20 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by yutannihilation** [comment]
@teunbrand 
> OTOH, some people might expect the global aesthetics to overrule local aesthetics.

Sorry for a late question. I, more specifically, the gghighlight package, expected it. So, what's the recommendation for those people? Setting the `label` attribute?

``` r
devtools::load_all("~/GitHub/ggplot2/")
#> ℹ Loading ggplot2
```

``` r
library(gghighlight)

# The original labels should be kept
ggplot(mtcars, aes(wt, mpg, colour = factor(cyl))) +
  geom_point() +
  gghighlight(100 < disp, disp <= 300, use_group_by = FALSE)
```

![](https://i.imgur.com/35F9PyO.png)

<sup>Created on 2024-07-17 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by teunbrand** [comment]
That would work if you use plain symbols in `aes()`, but you could also use any other label setting mechanism like using `labs()` or `scale_{x/y/colour}_*(name)`.

**Comment by teunbrand** [comment]
Sorry if I have been unclear, I meant 'a NSE column name' when I said 'plain symbol'.
Given that the mappings give column names, label-attributes should work.

``` r
library(gghighlight)
#> Loading required package: ggplot2

# The original labels should be kept
p <- ggplot(mtcars, aes(wt, mpg, colour = factor(cyl))) +
  geom_point() +
  gghighlight(100 < disp, disp <= 300, use_group_by = FALSE)

p$layers[[1]]$mapping
#> Aesthetic mapping: 
#> * `x`      -> `highlight..........1`
#> * `y`      -> `highlight..........2`
#> * `colour` -> `highlight..........3`
#> * `fill`   -> NULL
#> * `group`  -> `highlight..........group`
colnames(p$layers[[1]]$data)
#> [1] "highlight..........1"     "highlight..........2"    
#> [3] "highlight..........3"     "highlight..........group"
```

<sup>Created on 2024-07-17 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

**Comment by yutannihilation** [comment]
Ah, I understand what you wrote. I was thinking if I can set the `label` attributes of the plot data, but, in this code for example, `colour` is an expression, not a variable. But, modifying a layer might be an option, thanks for the suggestion.

``` r
library(gghighlight)
#> Loading required package: ggplot2
```

``` r

p <- ggplot(mtcars, aes(wt, mpg, colour = factor(cyl))) +
  geom_point() +
  gghighlight(100 < disp, disp <= 300, use_group_by = FALSE)

p$mapping
#> Aesthetic mapping: 
#> * `x`      -> `wt`
#> * `y`      -> `mpg`
#> * `colour` -> `factor(cyl)`
```

<sup>Created on 2024-07-17 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>
