### ISSUE TITLE
Should the diamonds dataset factor variables be unorderd?

### ISSUE THREAD

**Issue by davidhodge931** [tidyverse/ggplot2#5910]
The diamonds dataset is full of ordered variables
``` r
head(ggplot2::diamonds, 1)
#> # A tibble: 1 × 10
#>   carat cut   color clarity depth table price     x     y     z
#>   <dbl> <ord> <ord> <ord>   <dbl> <dbl> <int> <dbl> <dbl> <dbl>
#> 1  0.23 Ideal E     SI2      61.5    55   326  3.95  3.98  2.43
```

<sup>Created on 2024-05-28 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

R 4 datascience doesn't recommend using these.
![image](https://github.com/tidyverse/ggplot2/assets/55065152/d56cf9ff-326e-4827-b7de-68d20dd9f696)
https://r4ds.hadley.nz/factors

Subsequently, should the diamonds dataset factor variables be unorderd?

**Comment by teunbrand** [comment]
Is there a common case where the orderedness of these factors are giving some kind of issues?

**Comment by thomasp85** [comment]
They are ordered values and should be treated as such. ggplot2 itself has different default scales for ordered vs unordered data.

I don't think you can take the recommendation in R4DS to such an extreme conclusion as to strip the use from all available data

**Comment by davidhodge931** [comment]
Thanks!
