### ISSUE TITLE
`geom_area()` provides unclear error message when discrete x-axis is used

### ISSUE THREAD

**Issue by 83221n4ndr34** [tidyverse/ggplot2#5915]
I encountered an issue when using `geom_area()` in ggplot2:
when the x-axis is discrete, the code either produces an irrelevant warning or fails to plot anything without an informative error message. Here are the details:

### Discrete X-Axis with Specified Colors

When using `geom_area()` with discrete values for x-axis and specifying fill colors using `scale_fill_manual()`, the code produces the following warning:

> Warning message:  
> No shared levels found between `names(values)` of the manual scale and the data's fill values.

### Discrete X-Axis without specified colors

When using `geom_area()` discrete values for x-axis without specifying fill colors, ggplot2 silently fails to plot anything. There is no warning or error message to indicate the issue.

### Suggestion

It would be helpful if the library could provide a more informative error message in these scenarios. For example, a message indicating that `geom_area()` does not support discrete x-axes would be very useful for diagnosing the issue.

### Example code

Below is the demonstration of the problem with the example code.

```r
library(ggplot2)

# example data
df <- data.frame(
  time = rep(1:10, each = 4),
  category = rep(c("A", "B", "C", "D"), times = 10),
  value = c(runif(10, 0, 5), runif(10, 0, 5), runif(10, 0, 5), runif(10, 0, 5))
)

colors <- c("A" = "#ff0000", "B" = "#ff90c7", "C" = "#167b2b", "D" = "#0000ff")
```

#### Plot with Numeric x-Axis (for control)

```r
# time is numeric
p_numeric <- ggplot(df, aes(x = time, y = value, fill = category)) +
  geom_area(position = "stack") +
  scale_fill_manual(values = colors) +
  theme_minimal()

print(p_numeric)
```
![Numeric x-Axis Plot](https://github.com/tidyverse/ggplot2/assets/121315761/f13aba9d-2203-4089-a490-85b31dfd7e0e)

#### Plot with Character x-Axis

```r
# Convert time to character
df$time_chr <- as.character(df$time)

p_character <- ggplot(df, aes(x = time_chr, y = value, fill = category)) +
  geom_area(position = "stack") +
  scale_fill_manual(values = colors) +
  theme_minimal()

print(p_character)
```
> Warning message:
> No shared levels found between `names(values)` of the manual scale and the data's fill values.

![Character x-Axis Plot](https://github.com/tidyverse/ggplot2/assets/121315761/07c22896-555a-4fb6-af7a-41f998472f88)

```r
# Plot without specified colors
p_character_bis <- ggplot(df, aes(x = time_chr, y = value, fill = category)) +
  geom_area(position = "stack") +
  theme_minimal()

print(p_character_bis)
```

![Character x-Axis Plot Without Specified Colors](https://github.com/tidyverse/ggplot2/assets/121315761/9dd3337a-490d-4643-9c1c-1b13cf34b3fd)

Same results with Factor x-Axis

```r
# Convert time to factor
df$time_factor <- as.factor(df$time)

p_factor <- ggplot(df, aes(x = time_factor, y = value, fill = category)) +
  geom_area(position = "stack") +
  scale_fill_manual(values = colors) +
  theme_minimal()

print(p_factor)

# Plot without specified colors
p_factor_bis <- ggplot(df, aes(x = time_chr, y = value, fill = category)) +
  geom_area(position = "stack") +
  theme_minimal()

print(p_factor_bis)
```

![plot_numeric_discrete]

### Bonus: Forcing Discrete x-Axis to the Right Plot

```r
p_numeric <- p_numeric + scale_x_discrete(name = "time_numeric_discrete")

print(p_numeric)
```

This plot renders correctly but without x-axis labels.

![Forced Discrete x-Axis Plot](https://github.com/tidyverse/ggplot2/assets/121315761/5c6c5477-8eb3-4c3f-83d3-329ec584daf9)

**Comment by teunbrand** [comment]
This is case 2 of the details section of `?aes_group_order`. Briefly, your discrete x-axis counts towards grouping. If you manually set the groups correctly, all these issues disappear.

``` r
library(ggplot2)

df <- data.frame(
  time = rep(1:10, each = 4),
  category = rep(c("A", "B", "C", "D"), times = 10),
  value = c(runif(10, 0, 5), runif(10, 0, 5), runif(10, 0, 5), runif(10, 0, 5))
)

colors <- c("A" = "#ff0000", "B" = "#ff90c7", "C" = "#167b2b", "D" = "#0000ff")

ggplot(df, aes(x = as.character(time), y = value, fill = category, group = category)) +
  geom_area(position = "stack") +
  scale_fill_manual(values = colors) +
  theme_minimal()
```

![](https://i.imgur.com/uhQQANO.png)

<sup>Created on 2024-05-29 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>
