### ISSUE TITLE
`position_dodge` not working well with `preserve = "single"` and `geom_text` (or `geom_point`)

### ISSUE THREAD

**Issue by davidhodge931** [tidyverse/ggplot2#5995]
In CRAN version, it doesn't manage to dodge the text correctly...

``` r
library(tidyverse, quietly = TRUE)
#> Warning: package 'ggplot2' was built under R version 4.4.1
```

``` r
library(palmerpenguins, quietly = TRUE)

penguins |>
  count(species, sex) |>
  ggplot(
    aes(x = sex,
        y = n,
        fill = species,
        label = n),
  ) +
  geom_col(
    position = position_dodge(preserve = "single"),
    width = 0.75,
    alpha = 0.9,
  ) +
  geom_text(
    colour = "black",
    position = position_dodge(width = 0.75, preserve = "single"),
    vjust = 1.33,
  )
#> Warning in max(table(panel$xmin)): no non-missing arguments to max; returning
#> -Inf
```

![](https://i.imgur.com/pQowhKF.png)

<sup>Created on 2024-07-12 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

With DEV version downloaded just now, it errors
![image](https://github.com/user-attachments/assets/b93784bc-0d33-4a5c-8424-79eb9270240d)

**Comment by teunbrand** [comment]
Thanks for the report David! I'm surprised that also the old version has buggy dodging, but that might explain why it is missing from the test suite 😅 Not sure if the old version it is the same issue as #3022.
But yeah, should probably get fixed!
