### ISSUE TITLE
Default label is ignored when a mapping is overwritten by a parameter

### ISSUE THREAD

**Issue by yutannihilation** [tidyverse/ggplot2#6003]
Related to https://github.com/tidyverse/ggplot2/pull/5879

In the code below, the legend title is chosen differently depending on whether the same aes variable is specified by a parameter outside of `aes()`. In the second one, I think the title should be either

* `<<< G >>>`, because it's specified by the `label` attribute
* `G`, because the second layer is what the color scale is actually for

``` r
library(ggplot2)

d <- data.frame(x = 1, y = 2, g = 3)
d2 <- d
colnames(d2) <- c("X", "Y", "G")

attr(d[[1L]], "label") <- "<<< X >>>"
attr(d[[2L]], "label") <- "<<< Y >>>"
attr(d[[3L]], "label") <- "<<< G >>>"

ggplot() +
  geom_point(data = d, aes(x, y, colour = g)) +
  geom_point(data = d2, aes(X, Y, colour = G))
```

![](https://i.imgur.com/hMdNVOR.png)

``` r

ggplot() +
  geom_point(data = d, aes(x, y, colour = g), colour = "grey") + 
  #                                           ^^^^^^^^^^^^^^^
  #                                             the difference
  geom_point(data = d2, aes(X, Y, colour = G))
```

![](https://i.imgur.com/1YG3OI9.png)

<sup>Created on 2024-07-17 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by teunbrand** [comment]
Thanks for posting this! I think the label should be `G` in this case.
In the first layer, `colour = "grey"` should rule out any colour-label coming from the first layer.
Thus, the second layer should decide and since `d2$G` has no label-attribute, it should be `G`.
