### ISSUE TITLE
Arrangement of multiple legends inside legend box

### ISSUE THREAD

**Issue by clauswilke** [tidyverse/ggplot2#6014]
Is there an option to control how multiple legends are laid out inside the legend box (horizontal vs vertical)? I wasn't able to find one, but maybe I'm just missing something. The layout direction seems to change based on where the legend is placed. I would like the legend to look like when I place the legend on top of the plot but place it inside, with individual legends laid out vertically but the legends arranged horizontally next to each other. Is this possible?

``` r
library(ggplot2)

ggplot(mtcars) +
  aes(disp, mpg, fill = hp, shape = factor(cyl), size = wt) + 
  geom_point() +
  theme(
    legend.position = "top",
    legend.direction = "vertical"
  )
```

![](https://i.imgur.com/od75zxU.png)

``` r


ggplot(mtcars) +
  aes(disp, mpg, fill = hp, shape = factor(cyl), size = wt) + 
  geom_point() +
  theme(
    legend.position = "inside",
    legend.direction = "vertical"
  )
```

![](https://i.imgur.com/C9wjloh.png)

``` r


ggplot(mtcars) +
  aes(disp, mpg, fill = hp, shape = factor(cyl), size = wt) + 
  geom_point() +
  theme(
    legend.position = "inside",
    legend.direction = "horizontal"
  )
```

![](https://i.imgur.com/14d4Zga.png)

<sup>Created on 2024-07-26 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by teunbrand** [comment]
Hi Claus,

Are you looking for `legend.box = "horizontal"` or is there a missing option in terms of legend layout?

``` r
library(ggplot2)

ggplot(mtcars) +
  aes(disp, mpg, fill = hp, shape = factor(cyl), size = wt) + 
  geom_point() +
  theme(
    legend.position = "inside",
    legend.direction = "vertical",
    legend.box = "horizontal"
  )
```

![](https://i.imgur.com/wyaHbsP.png)

<sup>Created on 2024-07-26 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

**Comment by clauswilke** [comment]
Yes, that's what I'm looking for, thanks! I had looked at all the names of the legend options in `theme()` but didn't match `legend.box` with the layout direction.

**Comment by teunbrand** [comment]
Yeah I agree it is not the most intuitive name for what the setting does.
