### ISSUE TITLE
geom_smooth: Prediction interval and not confidence interval for se in the documentation

### ISSUE THREAD

**Issue by herry23xet** [tidyverse/ggplot2#6025]
Hello,
if I use `geom_smooth()`, then an interval is shown in the standard `se = TRUE`, which does not have a constant width. Especially for linear estimates of slope parameters.
However, the documentation states that `se` is a confidence interval (https://ggplot2.tidyverse.org/reference/geom_smooth.html):

> Display confidence interval around smooth? (`TRUE` by default, see `level` to control.)

However, this cannot be the case, as a confidence interval is always a fixed interval around the slope parameter.
What `geom_smooth()` shows, however, is the prediction interval (https://en.wikipedia.org/wiki/Prediction_interval).

The same for `level`.

Example image (from the documentation), dark grey area:
![](https://ggplot2.tidyverse.org/reference/geom_smooth-9.png)
Or have I made a mistake?

If not, this should be changed.

**Comment by teunbrand** [comment]
I'm not a statistician by training, but I think there might be a misunderstanding here.

You'd only get a constant width around the line if you only would have errors in the intercept. If you have errors in the intercept and slope, you get the shape that the confidence interval around the line indicates.

To illustrate:

``` r
library(ggplot2)

plot_lines <- function(i, s) {
  data.frame(i = i, s = s) |>
    ggplot() +
    geom_abline(aes(slope = s, intercept = i), alpha = 0.01) +
    scale_x_continuous(limits = c(-5, 5)) +
    scale_y_continuous(limits = c(-5, 5))
}

plot_lines(i = 1 + rnorm(1e4, sd = 0.2), s = 1) +
  ggtitle("Variable intercept, fixed slope")
```

![](https://i.imgur.com/czk65yn.png)

``` r
plot_lines(i = 1, s = 1 + rnorm(1e4, sd = 0.2)) +
  ggtitle("Fixed intercept, variable slope")
```

![](https://i.imgur.com/BhjR9v6.png)

``` r
plot_lines(i = 1 + rnorm(1e4, sd = 0.2), s = 1 + rnorm(1e4, sd = 0.2)) +
  ggtitle("Variable intercept and slope")
```

![](https://i.imgur.com/BxS7KBC.png)

<sup>Created on 2024-08-04 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

**Comment by clauswilke** [comment]
It is neither a prediction interval nor a confidence interval. It is a confidence band.
https://en.m.wikipedia.org/wiki/Confidence_and_prediction_bands

You can see some code to manually calculate it here, in case that is of interest. https://wilkelab.org/dataviz_shortcourse/materials/2024-06-27.html

**Comment by teunbrand** [comment]
Conceptual distinction from the wikipedia article:

> Confidence bands are closely related to [confidence intervals](https://en.m.wikipedia.org/wiki/Confidence_intervals), which represent the uncertainty in an estimate of a single numerical value

Should we adjust the wording in ggplot2 to read 'confidence bands' instead of 'confidence intervals'? `stats::predict.lm()` also calls it the relevant argument `interval` and its documentation makes no mention of 'bands'.

**Comment by clauswilke** [comment]
I'm away from my desktop and can't easily check what exactly the documentation says but yes, I'd be in favor of confidence band over confidence interval.
