### ISSUE TITLE
Add feature to give legend items row/column locations to appear.  

### ISSUE THREAD

**Issue by Maschette** [tidyverse/ggplot2#6026]
In situations when we are plotting factors with (in this case points) different types of categories, we would like to be able to have more control on how things appear in the legend. Whilst you can give ggplot the number of rows and columns to use for the legend you cannot (as far as I can find) give it the row/column locations of the factors which would allow you to have empty spaces in the legend like this: 

![image](https://github.com/user-attachments/assets/da98a30e-f7ed-4e40-b874-5bfe07af446f)

I tried to look at the legend source code to suggest a potential implementation but could not work out exactly where the rows and columns are implemented.

**Comment by teunbrand** [comment]
I like this idea, but maybe this is a better fit for a guide extension rather than built into `guide_legend()`.
Out of curiosity, how would you expect to feed the group structure to the legend?

**Comment by smouksassi** [comment]
I was thinking more like a patchwork of individual legend key grobs ? and where user can have complete control of the layout ?
