### ISSUE TITLE
`geom_text()` justification docs are wrong

### ISSUE THREAD

**Issue by willgearty** [tidyverse/ggplot2#6033]
The justification docs [on this page](https://ggplot2.tidyverse.org/reference/geom_text.html#alignment) (`?geom_text`) are wrong (or at least misleading). These state that a value of 0 is right/bottom and a value of 1 is top/left. Whereas the [specs here](https://ggplot2.tidyverse.org/articles/ggplot2-specs.html#justification) rightly state that 0 = bottom/left and 1 = top/right. I think the confusion comes from the fact that left justification moves items to the right and vice versa.

``` r
library(ggplot2)
ggplot(mtcars, aes(wt, mpg, label = rownames(mtcars))) +
    geom_point() +
    geom_text(hjust = 0)
```

![](https://i.imgur.com/FTXZIyq.png)

``` r
ggplot(mtcars, aes(wt, mpg, label = rownames(mtcars))) +
    geom_point() +
    geom_text(hjust = 1)
```

![](https://i.imgur.com/fWUivM4.png)

<sup>Created on 2024-08-08 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

**Comment by teunbrand** [comment]
Thanks for pointing this out! I agree that the docs should be consistent with itself and it is `?geom_text` that is in the wrong here.
