### ISSUE TITLE
Warning messages when printing ggplot

### ISSUE THREAD

**Issue by riemino** [tidyverse/ggplot2#604]
We are interested in reproducing the functionality as noted here: http://stackoverflow.com/questions/11179666/ggplot2-raster-plotting-does-not-work-as-expected-when-setting-alpha-values

We needed to get the latest version of ggplot2 to get this going so we did this:

install.packages("devtools")
library(devtools)
dev_mode(on=T)
install_github("gtable")
install_github("ggplot2")

When running this command:

```
#   Plot DEM layer with ggplot()
p1 <- ggplot()+
  layer(geom="raster",data=ddf,mapping=aes(X,Y,fill=DEM))+
  scale_fill_gradientn(name="Altitude",colours = rainbow(100),breaks=b.dem)+
  scale_x_continuous(name=expression(paste("Longitude (",degree,")")),limits=c(-4,2),expand=c(0,0))+
  scale_y_continuous(name=expression(paste("Latitude (",degree,")")),limits=c(4,12),expand=c(0,0))+
  coord_equal()
print(p1)
```

we get this error/warning messages:

> There were 37 warnings (use warnings() to see them)
> There were 50 or more warnings (use warnings() to see the first 50)
> warning()
> Warning messages:
> 1: In grid.Call(L_textBounds, as.graphicsAnnot(x$label),  ... :
>   Font family not found in Windows font database
> 2: In grid.Call(L_textBounds, as.graphicsAnnot(x$label),  ... :
>   Font family not found in Windows font database
> 3: In grid.Call(L_textBounds, as.graphicsAnnot(x$label),  ... :
>   Font family not found in Windows font database
> 4: In grid.Call(L_textBounds, as.graphicsAnnot(x$label),  ... :
> .....

and get this image as the output: 

https://dl.dropbox.com/u/43697/temp/r_error.jpg

Any insights as to what's going on here?

We've tried this in two different machines and we get the same behavior.

**Comment by timothyslau** [comment]
When I run:
surgeryData <- read.delim("http://www.statisticshell.com/r_files/Cosmetic%20Surgery.dat",  header = TRUE)
ggplot(data = surgeryData, aes(x = Base_QoL, y = Post_QoL)) + theme(title = element_text("a")) + geom_point(aes(colour = Surgery_Text)) + geom_smooth(aes(colour = Surgery_Text), method = "lm", se = F) + facet_wrap(facets = ~Clinic, ncol = 5) + labs(x = "Quality of Life (Baseline)", y = "Quality of Life (After Surgery)")

I get:
Warning messages:
1: In grid.Call(L_textBounds, as.graphicsAnnot(x$label), x$x, x$y,  :
  font family not found in Windows font database
2: In grid.Call(L_textBounds, as.graphicsAnnot(x$label), x$x, x$y,  :
  font family not found in Windows font database
3: In grid.Call.graphics(L_text, as.graphicsAnnot(x$label), x$x, x$y,  :
  font family not found in Windows font database
4: In grid.Call.graphics(L_text, as.graphicsAnnot(x$label), x$x, x$y,  :
  font family not found in Windows font database
5: In grid.Call.graphics(L_text, as.graphicsAnnot(x$label), x$x, x$y,  :
  font family not found in Windows font database

sessionInfo():
R version 3.1.1 (2014-07-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] ggplot2_1.0.0

loaded via a namespace (and not attached):
 [1] colorspace_1.2-4 digest_0.6.8     grid_3.1.1       gtable_0.1.2     labeling_0.3     MASS_7.3-37     
 [7] munsell_0.4.2    plyr_1.8.1       proto_0.3-10     Rcpp_0.11.4      reshape2_1.4.1   scales_0.2.4    
[13] stringr_0.6.2    tools_3.1.1     
Warning messages:
1: In grid.Call(L_textBounds, as.graphicsAnnot(x$label), x$x, x$y,  :
  font family not found in Windows font database
2: In grid.Call.graphics(L_text, as.graphicsAnnot(x$label), x$x, x$y,  :
  font family not found in Windows font database
3: In grid.Call.graphics(L_text, as.graphicsAnnot(x$label), x$x, x$y,  :
  font family not found in Windows font database
4: In grid.Call.graphics(L_text, as.graphicsAnnot(x$label), x$x, x$y,  :
  font family not found in Windows font database
5: In grid.Call(L_textBounds, as.graphicsAnnot(x$label), x$x, x$y,  :
  font family not found in Windows font database
6: In grid.Call.graphics(L_text, as.graphicsAnnot(x$label), x$x, x$y,  :
  font family not found in Windows font database
7: In grid.Call.graphics(L_text, as.graphicsAnnot(x$label), x$x, x$y,  :
  font family not found in Windows font database
8: In grid.Call.graphics(L_text, as.graphicsAnnot(x$label), x$x, x$y,  :
  font family not found in Windows font database
