### ISSUE TITLE
`linewidth` of `panel.border` and `axis.line` not identical

### ISSUE THREAD

**Issue by jpquast** [tidyverse/ggplot2#6057]
I came across an inconsistency in the line thickness of the `panel.border` and `axis.line`. I am not sure if it is a bug or a user error, but I couldn't really make sense of it. 
If I set the line width with the `linewidth` argument the resulting lines are different even if the same value is supplied. The documentation of `element_rect()` and `element_line()` says the unit should be `"mm"`. I am not sure which of the two is correct. 

Help would be really appreciated! Thanks a lot in advance!

``` r
library(ggplot2)

ggplot(data = data.frame(x = 0, y = 0), aes(x = x, y = y)) +
  geom_blank() + 
  theme_minimal() + 
  theme(
    panel.border = element_rect(colour = "black", fill = NA, linewidth = 10),
    axis.line = element_line(colour = "black", linewidth = 10),
    axis.text = element_blank(),
    axis.title = element_blank(),
    panel.grid = element_blank()
  ) 
```

![](https://i.imgur.com/4PigUuS.png)

<sup>Created on 2024-08-25 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

**Comment by clauswilke** [comment]
Half of the panel border is cut off by clipping.

``` r
library(ggplot2)

p <- ggplot(data = data.frame(x = 0, y = 0), aes(x = x, y = y)) +
  geom_blank() + 
  theme_minimal() + 
  theme(
    panel.border = element_rect(colour = "black", fill = NA, linewidth = 10),
    axis.line = element_line(colour = "black", linewidth = 10),
    axis.text = element_blank(),
    axis.title = element_blank(),
    panel.grid = element_blank()
  )

p
```

![](https://i.imgur.com/YoBZWa3.png)

``` r

p + coord_cartesian(clip = "off")
```

![](https://i.imgur.com/Awse6uH.png)

<sup>Created on 2024-08-25 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
