### ISSUE TITLE
ggplot2's Chinese axis label display

### ISSUE THREAD

**Issue by trafficfan** [tidyverse/ggplot2#6058]
I found a problem with ggplot2 Chinese axis label display, the vertical axis of the Chinese axis label font is always larger than the horizontal axis, the following code in the vertical axis and the horizontal axis of the label are ‘测试中文’, please observe the size of the X Y axis label

I expected These two axis labels are displayed the same large

Here is the code to reproduce the bug:

```r
``` r
library(mlr3verse)
#> Loading required package: mlr3
task = tsk("german_credit")
learner = lrn("classif.ranger", predict_type = 'prob')
split = partition(task)
learner$train(task,row_ids = split$train)
pred = learner$predict(task, row_ids = split$test)
measure = msr("classif.auc")
pred$score(measure)
#> classif.auc 
#>    0.810617
library(ggplot2)
autoplot(pred,type = "roc") +
  labs(x = "测试中文", y = "测试中文") 
```

![](https://i.imgur.com/HYaL8PS.png)

<sup>Created on 2024-08-26 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

```

**Comment by clauswilke** [comment]
Minimal reprex:
```r
library(ggplot2)

ggplot() +
  labs(x = "测试中文", y = "测试中文") 
```
<img width="421" alt="Screenshot 2024-08-25 at 9 57 29 PM" src="https://github.com/user-attachments/assets/f3fdf963-451a-4052-bf92-fc051041365a">

I don't see the issue. Probably a bad graphics device. Or, alternatively, bad theme settings in `autoplot()`.

**Comment by teunbrand** [comment]
I also can't discern what is wrong here, neither in the original example or Claus' reprex.
If there is something wrong with the rendering of Chinese characters, it might be the font itself or the graphics device that render incorrectly.
