### ISSUE TITLE
(Potential) bug with `theme` within `guide_*` call

### ISSUE THREAD

**Issue by kylebutts** [tidyverse/ggplot2#6102]
It is very possible that I'm misunderstanding how to use the `theme` object within `guide_*`, but applying themes does not seem to work for me. I am using the most recent development version of ggplot2.

Edit: After some more testing, only the `legend.x` options are not working 

``` r
library(ggplot2)
ggplot() +
  geom_point(
    aes(x = mpg, y = hp, color = as.factor(cyl)),
    data = mtcars
  ) +
  scale_color_manual(
    values = c("red", "blue", "green"),
    guide = guide_legend(
      theme = theme(legend.position = "bottom")
    )
  )
```

![](https://i.imgur.com/QINbRBO.png)

``` r

ggplot() +
  geom_point(
    aes(x = mpg, y = hp, color = as.factor(cyl)),
    data = mtcars
  ) +
  scale_color_manual(
    values = c("red", "blue", "green"),
    guide = guide_legend()
  ) +
  theme(legend.position = "bottom")
```

![](https://i.imgur.com/OZ1hL2y.png)

<sup>Created on 2024-09-12 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by teunbrand** [comment]
Thanks for the report!
The issue mirrors https://github.com/tidyverse/ggplot2/issues/5712#issuecomment-2142574858 very closely, so I'll close the discussion here in favour of that issue.
In any case; it is not a bug, but ggplot2 should probably do a better job at making clear which theme elements are in scope and which ones aren't.
