### ISSUE TITLE
Missing csv files for faithfuld and luv_colours datasets

### ISSUE THREAD

**Issue by tikkss** [tidyverse/ggplot2#6105]
Hi, I'm a contributor to [red-data-tools/red-datasets: A RubyGem that provides common datasets](https://github.com/red-data-tools/red-datasets).

red-datasets currently supports the following [ggplot2 datasets](https://ggplot2.tidyverse.org/reference/#data). Thanks!

* Available datasets
    - [x] diamonds
    - [x] mpg
* Unavailable datasets
    - [ ] economics economics_long
    - [ ] faithfuld
    - [ ] midwest
    - [ ] msleep
    - [ ] presidential
    - [ ] seals
    - [ ] txhousing
    - [ ] luv_colours

By the way, faithfuld and luv_colours csv files seem to be missing. Is this intentional? If not, Could you add them? Thanks!

### Steps to reproduce

Open https://github.com/tidyverse/ggplot2/tree/v3.5.1/data-raw

### Expected result

faithfuld and luv_colours csv files exist.

### Actual result

faithfuld and luv_colours csv files do not exist.

**Comment by yutannihilation** [comment]
I'm afraid you are assuming these CSV files are the outputs generated by the corresponding R script. No, these are the source data that are loaded and tweaked. `faithfuld` and `luv_colours` don't have their CSV files because these two datasets are generated purely from R code.

https://github.com/tidyverse/ggplot2/blob/main/data-raw/faithfuld.R
https://github.com/tidyverse/ggplot2/blob/main/data-raw/luv_colours.R

**Comment by teunbrand** [comment]
From R and with ggplot2 installed, it is not too difficult to export these datasets to csv files.
```r
write.csv(ggplot2::faithfuld, file = "faithfuld.csv", row.names = FALSE)
write.csv(ggplot2::luv_colours, file = "luv_colours.csv", row.names = FALSE)
```

**Comment by teunbrand** [comment]
I'm going to close this, because I see no need within the R ecosystem for ggplot2 to explicitly export these datasets as csv file, and it is straightforward to export them if so needed.

**Comment by tikkss** [comment]
Sorry, for my late response. Thanks for the clarification! That makes sense, and it's nice to know that exporting the datasets using R as csv is easy if needed.

Thanks again!
