### ISSUE TITLE
`Inf` does not maintain annotation within boundaries of plot anymore

### ISSUE THREAD

**Issue by rempsyc** [tidyverse/ggplot2#6111]
When adding an annotation to a plot, `Inf` used to keep the annotation within the frame of the plot. Recently however I noticed that this behaviour has changed with a recent update (of, probably, `ggplot2` or one of its dependencies), such that the text is now almost completely hidden outside the borders of the frame when using this historically common "trick". I noticed this change of behaviour in my `pkdown` website and personal documents (old vs new).

Reprex of the new behaviour:

``` r
packageVersion("ggplot2")
#> [1] '3.5.1'
library(ggplot2)
ggplot(mtcars, aes(wt, mpg)) +
  geom_point() +
    annotate("text", label = "text", size = 15, x = Inf, y = Inf)
```

![](https://i.imgur.com/oXV9VMq.png)

<sup>Created on 2024-09-17 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

Same with `I(1)`:

``` r
library(ggplot2)
ggplot(mtcars, aes(wt, mpg)) +
  geom_point() +
    annotate("text", label = "text", size = 15, x = I(1), y = I(1))
```

![](https://i.imgur.com/epu49Wl.png)

<sup>Created on 2024-09-17 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

`vjust` and `hjust` used not to be necessary for this, or putting them at zero would put them at the edge, but now 0 completly hides:

``` r
library(ggplot2)
ggplot(mtcars, aes(wt, mpg)) +
  geom_point() +
    annotate("text", label = "text", size = 15, x = Inf, y = Inf,
             vjust = 0, hjust = 0)
```

![](https://i.imgur.com/AKOvcRS.png)

<sup>Created on 2024-09-17 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

Whereas the old behaviour can be recovered using `vjust` and `hjust` of 1:

``` r
library(ggplot2)
ggplot(mtcars, aes(wt, mpg)) +
  geom_point() +
    annotate("text", label = "text", size = 15, x = Inf, y = Inf,
             vjust = 1, hjust = 1)
```

![](https://i.imgur.com/ndMpQ4X.png)

<sup>Created on 2024-09-17 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

Or with "inward":

``` r
library(ggplot2)
ggplot(mtcars, aes(wt, mpg)) +
  geom_point() +
    annotate("text", label = "text", size = 15, x = Inf, y = Inf,
             vjust = "inward", hjust = "inward")
```

![](https://i.imgur.com/PJn68Rx.png)

<sup>Created on 2024-09-17 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

Is this a bug or feature introduced by some new changes to `ggplot2`?

**Comment by teunbrand** [comment]
I don't recall the behaviour of automatically adjusting for proximity to the panel boundaries.
AFAIK you would've always needed to use `hjust`/`vjust` to get the positioning right.
When I use 3.4.3, I get the same thing as in 3.5.1:

``` r
library(ggplot2)
packageVersion("ggplot2")
#> [1] '3.4.3'

ggplot(mtcars, aes(wt, mpg)) +
  geom_point() +
  annotate("text", label = "text", size = 15, x = Inf, y = Inf)
```

![](https://i.imgur.com/ZXjVO9z.png)

<sup>Created on 2024-09-17 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

**Comment by rempsyc** [comment]
Thanks. While I have not changed my function `rempsyc::nice_density` over a year, my previous rmarkdown analysis report shows this (as I remember my package website do as well in the examples):

![image](https://github.com/user-attachments/assets/753bb0fa-46e5-46e2-8154-1a853ca5dfca)

But when I run the script again after a few weeks (and updating my packages), I now get:

![image](https://github.com/user-attachments/assets/789742fe-4201-4cb4-8dfd-46ece92ce8d2)

That function relies on `ggrepel`, so... perhaps it was a change there? I tried testing on `ggrepel` first and got the same thing and so tried to see if I could nail it down further down the line to `ggplot2`, thus opening this issue. But perhaps `ggrepel` was adding automatic `hjust` and `vjust` and stopped doing that?

In any case, if that was always the behaviour, I think we can close the issue? Although I would have imagined that it would be sensible to have default values within the boundaries of the plot without having to make custom adjustments, but perhaps this is not easily generalizable to all the possible cases.

**Comment by smouksassi** [comment]
ggrepel geom_text_repel is not the same as geom_text indeed it used to put the inf into the panel a recent bug broke that but I think it was fixed in the last release:
https://github.com/slowkow/ggrepel/issues/252
