### ISSUE TITLE
Documentation for `coord_polar()` and `coord_radial()` has exposed `roxygen2` syntax.

### ISSUE THREAD

**Issue by jdonland** [tidyverse/ggplot2#6122]
For example, there's an exposed "`#'`" above the first example plot and a "`\donttest{`" below it.

**Comment by teunbrand** [comment]
Thanks for the report!
Relevant line can be found here: 
https://github.com/tidyverse/ggplot2/blob/4fbc8575d80e54e1973ac58e979c2300aec21394/R/coord-polar.R#L23
