### ISSUE TITLE
Heatmaps outside geom_ttile

### ISSUE THREAD

**Issue by fwunschel** [tidyverse/ggplot2#6124]
Hi All,

Have loved all things geom_sf has done in advancing ggplot2, and have done some work with the geom_tile() function. I was wondering if there were plans to add a more fluid heat map (thinking a geom_smooth version for points) option or integrate sf objects in geom_tile(). If anyone has any tips or tricks to emulate a less pixelated heat map, sin generating infinitely smaller tile size, that would be great as well.

Thanks for all the work on this!

All the Best,
Frankie

**Comment by teunbrand** [comment]
Hi there, can you point to an example of the thing you'd like to do in ggplot2, but is currently impossible/cumbersome?
I have a hard time imagining what a fluid heat map, or geom_smooth for points would look like.

**Comment by fwunschel** [comment]
Something like this [heatmap](https://www.google.com/search?sca_esv=17288cef834a1941&rlz=1C5CHFA_enUS808US808&sxsrf=ADLYWII6ZKqAxOU-cAIUAYd1BZ3EaB-xIg:1727903603972&q=heatmap&udm=2&fbs=AEQNm0Aa4sjWe7Rqy32pFwRj0UkWd8nbOJfsBGGB5IQQO6L3J_86uWOeqwdnV0yaSF-x2jogM63VUdBhAMVqo6r6ESHkgrvHcjmRFrskBcAKNCdoajwM5EuvYiug4n8BfK_Fr415lhOomCGyddwEft8JCAFvhy7bTcnWo2Kondei1x640ne5A0wtPzCUhBOapGjKxhZXb-LdrVVXQzzWvrJRNxKx42tGwA&sa=X&sqi=2&ved=2ahUKEwijkZXEzvCIAxVTHkQIHYKeKKoQtKgLegQIGhAB&biw=1600&bih=806&dpr=1.8#vhid=XPk2wY4YVsKz4M&vssid=mosaic), rather than this more [pixelized example](https://www.google.com/search?q=heatmap+ggplot+rtile&sca_esv=17288cef834a1941&rlz=1C5CHFA_enUS808US808&udm=2&biw=1600&bih=806&sxsrf=ADLYWIK63DYAHNo6YIsc4fqJT-fuYFeGxw%3A1727903636680&ei=lLf9ZpCnKeGekPIPvJfVuAw&ved=0ahUKEwiQweHTzvCIAxVhD0QIHbxLFccQ4dUDCBA&uact=5&oq=heatmap+ggplot+rtile&gs_lp=Egxnd3Mtd2l6LXNlcnAiFGhlYXRtYXAgZ2dwbG90IHJ0aWxlSPMJUNECWLcIcAF4AJABAJgBaaABkASqAQM1LjG4AQPIAQD4AQGYAgOgAp8BwgIKEAAYgAQYQxiKBcICBRAAGIAEwgIGEAAYBRgewgIGEAAYCBgewgIHEAAYgAQYGMICBBAAGB6YAwCIBgGSBwEzoAfMBA&sclient=gws-wiz-serp#vhid=TNE0DRrLmZv6jM&vssid=mosaic). The difference im seeking is in the fluidity of color transition, the overlap on a map and the use of spatial typed variables - but maybe I just need to decipher a smaller pixel size and use an x y configuration rather than geometry I can achieve something similar?

**Comment by teunbrand** [comment]
For spatial data, it might be more convenient to look into specialised packages for handling raster data, like {terra}.
In terms of colour fluidity, there is `geom_raster(interpolate = TRUE)` that can 'blend' adjacent colours. There are a few more constraints on `geom_raster()` than on `geom_tile()` though.

``` r
library(ggplot2)

p <- ggplot(
  data.frame(
    x = c(1, 2, 1, 2),
    y = c(1, 1, 2, 2),
    g = LETTERS[1:4]
  ),
  aes(x, y, fill = g)
)

p + geom_raster()
```

![](https://i.imgur.com/6JYRvPW.png)

``` r
p + geom_raster(interpolate = TRUE)
```

![](https://i.imgur.com/JVHECtk.png)

<sup>Created on 2024-10-03 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

**Comment by teunbrand** [comment]
I'm going to close this because it doesn't seem like there is something to do in this issue for ggplot2.
For fluid heatmaps you can interpolate data before you plot it.
