### ISSUE TITLE
Using units with ggplot scales and limits

### ISSUE THREAD

**Issue by noejn2** [tidyverse/ggplot2#6129]
Working with data using the `units`  and `ggplot2` package, I found that setting up limits is not straight forward. I do not think this is the intended use, but I may be wrong.

The following should not work, since `ylimit` argument is not set in units.

```r
data.frame(x = c(1,2,3),
           y = units::as_units(c(2,3,1),"km")) |> 
  ggplot(aes(x=x, y=y)) +
  geom_point() +
  xlim(0, NA) +
 ylim(0, NA)
```

So, my initial approach was to set the following just to find out it does not work either

```r
data.frame(x = c(1,2,3),
           y = units::as_units(c(2,3,1),"km")) |> 
  ggplot(aes(x=x, y=y)) +
  geom_point() +
  xlim(0, NA) +
 ylim(units::as_units(0, "km"), units::as_units(0, "km"))
```

Notice that the arguments `units::as_units(0, "km")` and `units::as_units(NA, "km")` do not give an error.  Yet, I get an error when rendering the plot.

The current solution uses `units::scale_y_units()`, but it is not straight forward or documented as a solution to this problem anywhere.

```r
data.frame(x = c(1,2,3),
           y = units::as_units(c(2,3,1),"km")) |> 
  ggplot(aes(x=x, y=y)) +
  geom_point() +
  xlim(0, NA) +
  units::scale_y_units(
    limits = c(0, NA)
  )
```

Is this the intended approach when using units and ggplot scales and limits?

**Comment by teunbrand** [comment]
Hi there, thanks for the report.

It seems like the units package has [recently added support](https://github.com/r-quantities/units/issues/370) for functions like `ylim()` but this hasn't arrived on CRAN yet.
Your second example works with their development version:

``` r
# remotes::install_github("r-quantities/units")
library(ggplot2)
library(units)

data.frame(x = c(1,2,3),
           y = units::as_units(c(2,3,1),"km")) |> 
  ggplot(aes(x=x, y=y)) +
  geom_point() +
  xlim(0, NA) +
  ylim(units::as_units(0, "km"), units::as_units(NA, "km"))
```

![](https://i.imgur.com/DEIrXO5.png)

<sup>Created on 2024-10-03 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

The state of the `scale_y_units()` documentation, or more generally  —the level of units/ggplot2 interoperability— is outside the control of ggplot2 and should be raised with the units authors. As such, I think this issue should be closed.
