### ISSUE TITLE
Adjustment of geom_area

### ISSUE THREAD

**Issue by Breeze-Hu** [tidyverse/ggplot2#6153]
ggplot2 has a very elegant way of plotting graphs, especially statistical graphs. However, I have encountered some difficulties in adjusting the area graph.

I want to plot areas of two colors, red for parts greater than 0, and blue for parts less than 0. After trying a few approaches (see code below), it was possible to approximate the desired result in a large dataset, but there were still some problems.
Is there a suggestion or a better way to present this part of the code?

Some some representations of matplotlib would be more concise and predictable, so I hope there is some reference:
[matplotlib](https://matplotlib.org/stable/gallery/lines_bars_and_markers/fill_betweenx_demo.html
https://matplotlib.org/stable/gallery/lines_bars_and_markers/fill_between_demo.html (**interpolate** parameter))

```
test = tibble(x=1:5,
              y = c(-1,1,3,-4,2)) |> 
  mutate(y_na = ifelse(y<0, y, 0), y_po = ifelse(y>0, y, 0))

ggplot(test)+
  geom_area(aes(x = x, y = y_po),fill='red')+
  geom_area(aes(x = x, y = y_na),fill='blue')
```
![image](https://github.com/user-attachments/assets/38bc69e6-449d-4951-ab48-08b4bf68f36f)

**Comment by teunbrand** [comment]
There are already extensions doing what you indicate:

``` r
library(ggplot2)

test <- data.frame(x = 1:5, y = c(-1, 1, 3, -4, 2))

ggplot(test, aes(x, ymax = y, ymin = 0)) +
  ggh4x::stat_difference()
```

![](https://i.imgur.com/IgZEtCm.png)

``` r
ggplot(test, aes(x, ymax = y, ymin = 0, fill = y < 0)) +
  ggbraid::geom_braid(method = "line")
```

![](https://i.imgur.com/Bv8JYPv.png)

<sup>Created on 2024-10-22 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

**Comment by Breeze-Hu** [comment]
Thank you！ this is exactly the result I was looking for!
