### ISSUE TITLE
typo: `scale_x_continuous`

### ISSUE THREAD

**Issue by eyayaw** [tidyverse/ggplot2#6178]
so we'll use scale_x_~continuous~discrete
https://github.com/tidyverse/ggplot2/blob/e594b49fdd5e4d95bf1031edaf6c7ccfc0cdedb0/vignettes/articles/faq-axes.Rmd#L72

**Comment by teunbrand** [comment]
Thanks, well spotted! Is there any chance you'd be interested in preparing a PR to fix the mistake?
