### ISSUE TITLE
Feature Request: geom_sf-style Visualization Support for Julia

### ISSUE THREAD

**Issue by Jigyasu4indp** [tidyverse/ggplot2#6179]
Hello,

Could you consider developing a geom_sf-style visualization feature for Julia? This would enable sf-style spatial data handling and visualization within the Julia ecosystem. Currently, many users rely on R's sf package for spatial data visualization, and a native Julia equivalent would greatly enhance workflow efficiency, especially for those transitioning from R to Julia.

Thank you for considering this request—such a feature would be highly appreciated by the Julia community!

**Comment by teunbrand** [comment]
This repository implements ggplot2 for R. It has no code for any Julia functionality at all. If you want `geom_sf()`-like functionality in Julia, I recommend requesting this feature in grammar of graphics implementations in Julia, such as TidierPlots.jl. Incidentally, somebody recently openened [an issue](https://github.com/TidierOrg/TidierPlots.jl/issues/131) for this exact request.
