### ISSUE TITLE
Allow axes on top and right

### ISSUE THREAD

**Issue by wch** [tidyverse/ggplot2#619]
Right now, there's code in `guide_axis()` that allows putting the axes on the top and right, but it looks like all the actual calls to that function are hard-coded to use `"left"` and `"bottom"`.

There should also be visual tests of the results.

**Comment by mavam** [comment]
Just wondering: has anything changed in the internal architecture over the past two years which would facilitate the implementation of this feature now?

**Comment by hadley** [comment]
In principle it's not hard just very very fiddly

**Comment by mavam** [comment]
There's [`switch_axis_position`](https://github.com/wilkelab/cowplot/blob/master/R/switch_axis.R) from `cowplot`. Would that essentially be the heavy lifting?

I understand it's slightly different from allowing arbitrary axes positions, but perhaps it's not far from there.

**Comment by talgalili** [comment]
+1 
This would be nice to have.

**Comment by cmohamma** [comment]
+1

**Comment by hobrien** [comment]
This has been sorted in the latest pre-release version: https://blog.rstudio.org/2016/09/30/ggplot2-2-2-0-coming-soon/

**Comment by mavam** [comment]
Great, thanks for announcing this!
