### ISSUE TITLE
Manual fill scale guide issue with unused factor level

### ISSUE THREAD

**Issue by jmgirard** [tidyverse/ggplot2#6201]
I found a problem with the guide for a manual fill scale when a factor level is unused.

I expected the guide tile for group C to be green instead of transparent/grey.

Here is the code to reproduce the bug:

``` r
library(ggplot2)

data <- data.frame(
  x = c(1, 2, 3, 4),
  ymin = c(1, 1, 2, 2),
  ymax = c(2, 2, 3, 3),
  group = factor(c("A", "B", "A", "B"), levels = c("A", "B", "C"))
)

ggplot(data, aes(x = x, ymin = ymin, ymax = ymax, fill = group)) +
  geom_ribbon() +
  scale_fill_manual(
    values = c("A" = "red", "B" = "blue", "C" = "green"),
    limits = c("A", "B", "C"),
    drop = FALSE
  )
```

![](https://i.imgur.com/5jIFvPf.png)

<sup>Created on 2024-11-25 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

**Comment by teunbrand** [comment]
Hi there, thanks for the report! Since ggplot2 3.5.0 we require data to be present to show the key in the legend or to set `geom_*(show.legend = TRUE)` if it should be shown regardless. This issue has been reported before in #5728.

**Comment by jmgirard** [comment]
In case anyone comes back here with the same issue (which seems likely), an effective but inelegant solution is to add some NAs. You get a warning but the desired outcome is achieved relatively easily.

``` r
library(tidyverse)

data <- data.frame(
  x = c(1, 2, 3, 4),
  ymin = c(1, 1, 2, 2),
  ymax = c(2, 2, 3, 3),
  group = factor(c("A", "B", "A", "B"), levels = c("A", "B", "C"))
) %>%
  # New addition
  bind_rows(data.frame(group = levels(.$group)))

ggplot(data, aes(x = x, ymin = ymin, ymax = ymax, fill = group)) +
  geom_ribbon() +
  scale_fill_manual(
    values = c("A" = "red", "B" = "blue", "C" = "green"),
    limits = c("A", "B", "C"),
    drop = FALSE
  )
#> Warning in max(ids, na.rm = TRUE): no non-missing arguments to max; returning
#> -Inf
```

![](https://i.imgur.com/Ue8LP7p.png)

<sup>Created on 2024-11-25 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>
