### ISSUE TITLE
'AsIs' position invalid when setting coord_sf: 'default_crs' parameter

### ISSUE THREAD

**Issue by Breeze-Hu** [tidyverse/ggplot2#6205]
The problem stems from an annotation about adding an out-of-panel position annotate. https://stackoverflow.com/questions/79222655/ggplot2-adds-a-second-image-title-on-the-right-side It has been suggested that ggplot 3.5.0 provides a more convenient location setup : `‘AsIs’ position aesthetics I() `. However, when mapping using `coords_sf`, there are some problems: everything works fine without asserting `default_crs` in it. Once this parameter is supplied, the labeled position changes. It should go back to using the x,y axis coordinates as defined. 
 
```r
library(tidyverse)
library(sf)
library(rnaturalearth)
ne_countries(continent = "africa") |> 
  # st_crs()
  ggplot()+
  geom_sf()+
  ggtitle('left')+
  annotate("text", label = "right", x = I(1), y = I(1), hjust = 1,
           vjust = -1, size = 4) +
  coord_sf(crs ="+proj=laea +y_0=0 +lon_0=155 +lat_0=-90 +ellps=WGS84 +no_defs",
           # default_crs = st_crs(4326),
           clip = "off")
```
Expected results:
![Image](https://github.com/user-attachments/assets/1ccb7d2e-cf91-40b6-b1eb-0bd181372bcd)

```r
library(tidyverse)
library(sf)
library(rnaturalearth)
ne_countries(continent = "africa") |> 
  # st_crs()
  ggplot()+
  geom_sf()+
  ggtitle('left')+
  annotate("text", label = "right", x = I(1), y = I(1), hjust = 1,
           vjust = -1, size = 4) +
  coord_sf(crs ="+proj=laea +y_0=0 +lon_0=155 +lat_0=-90 +ellps=WGS84 +no_defs",
           default_crs = st_crs(4326),
           clip = "off")
```
The position of the labeling has changed and seems to follow the definition of the axes: 
![Image](https://github.com/user-attachments/assets/a6787c5d-cdf4-4b6d-9b54-5ad30eb5f37c)

**Comment by yutannihilation** [comment]
I think the current expectation is that `AsIs` works only with cartesian coordinates. This probably requires some new mechanism like the one proposed in https://github.com/tidyverse/ggplot2/issues/5609. But, probably this needs to be noted on some documentation at least.

**Comment by teunbrand** [comment]
I'm fine with adhering to npc coordinates when `x` and `y` are both 'AsIs' variables. I'm unsure what the 'principle of least surprise'-outcome would be when only one of `x`/`y` is an 'AsIs' variable, and the other is a regular coordinate.
