### ISSUE TITLE
coord_flip is inconsistent between ordered geom and legend.

### ISSUE THREAD

**Issue by carljpearson** [tidyverse/ggplot2#6217]
I found a problem with coord_flip. The legend is in the opposite order of an ordered geom (like geom_bar).

I expected the legend and order to appear in the same vertical order.

This was previously reported here, but closed: https://github.com/tidyverse/ggplot2/issues/704

Here is the code to reproduce the bug:

```r
# Create a sample dataset
df1 <- data.frame(
  category = rep(c("A", "B", "C"), each = 3),
  subcategory = rep(c("X", "Y", "Z"), times = 3),
  value = c(10, 20, 30, 15, 25, 35, 20, 30, 40)
)

# Print the dataset
print(df)

# Create a bar graph using ggplot2 with the fill aesthetic
ggplot(df1, aes(x = category, y = value, fill = subcategory)) +
  geom_bar(stat = "identity", position = "dodge") +
  labs(title = "Bar Graph with Fill Aesthetic",
       x = "Category",
       y = "Value",
       fill = "Subcategory") +
  theme_minimal() +
  coord_flip()

```

**Comment by teunbrand** [comment]
Hi there, thank you for the report! You can use `guides(fill = guide_legend(reverse = TRUE))` to reverse the order of the legend. The order of the legend items is just a default setting that works well 80% of the time, but needs tweaks 20% of the time. Having horizontal orientation of bars falls in the latter category.
