### ISSUE TITLE
Scale manual dummy legend not showing icon

### ISSUE THREAD

**Issue by rfgoldberg** [tidyverse/ggplot2#6223]
Hello, I found a problem with scale_fill_manual.

When running the following code, I expected a second legend icon to appear for test, but it does not. This issue does not occur with an older version of ggplot (3.4.4), only with 3.5.1.

Reprex below:

```r
library(dplyr)
library(ggplot2)

iris |> 
filter(Species == "setosa")  |> 
ggplot() + 
  geom_boxplot(aes(x = Species, y = Petal.Width,fill = Species)) + 
  scale_fill_manual(values = c("red","blue"), limits = c("setosa","test"), labels = c("setosa","test"))
```

![Image](https://github.com/user-attachments/assets/87025d5e-7d8d-44ab-8b6e-6a13ea377577)

**Comment by teunbrand** [comment]
This is intended. You should use `geom_boxplot(show.legend = TRUE)` if you want to display data that isn't in the plot.
