### ISSUE TITLE
NULL `plot.margin` breakdown the shape of the gtable

### ISSUE THREAD

**Issue by Yunuuuu** [tidyverse/ggplot2#6234]
Related to https://github.com/tidyverse/ggplot2/issues/5628

I would like to change this line:
https://github.com/tidyverse/ggplot2/blob/4dedb82e46b0eca3a2e0642216e5c57f7b5926de/R/plot-build.R#L289
```r
 plot_margin <- calc_element("plot.margin", theme)  %||% margin()
```

here is the problem:
# copy your code to the clipboard and run:
``` r
library(ggplot2)
default_margin <- ggplot(mtcars, aes(disp, mpg)) +
    geom_point()
no_margin <- ggplot(mtcars, aes(disp, mpg)) +
    geom_point() +
    theme(plot.margin = NULL)
length(ggplotGrob(default_margin)$widths)
#> [1] 13
length(ggplotGrob(no_margin)$widths)
#> [1] 11
length(ggplotGrob(default_margin)$heights)
#> [1] 16
length(ggplotGrob(no_margin)$heights)
#> [1] 14
```

<sup>Created on 2024-12-12 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>
~                                                        
~                                         
```

**Comment by teunbrand** [comment]
This proposal makes sense to me. Is there any way I can entice you to prepare a PR for this?

**Comment by Yunuuuu** [comment]
Thank you! I’ll go ahead and prepare a PR to move it forward.
