### ISSUE TITLE
Snapshot change in pillar with dev ggplot2

### ISSUE THREAD

**Issue by krlmlr** [tidyverse/ggplot2#6242]
Is this anticipated?

https://github.com/r-lib/pillar/pull/670/files

**Comment by teunbrand** [comment]
Yes, point sizes now change with `theme_*(base_size)` now, so the following line scales them up.

https://github.com/r-lib/pillar/blob/d7fb43ae81d0e3bb9048d2be134ca7aed182f39d/tests/testthat/test-ggplot2.R#L15

**Comment by krlmlr** [comment]
Thanks for the clarification.
