### ISSUE TITLE
Feature request: A new facet system for `CoordRadial` to arrange different facet around a circle

### ISSUE THREAD

**Issue by Yunuuuu** [tidyverse/ggplot2#6262]
Related to [this issue](https://github.com/tidyverse/ggplot2/issues/6261), if such a method could be added to `CoordRadial`, we could also introduce a new facet type to split the circle plot into different radial segments, similar to this figure—though it would be quite challenging:

![Image](https://github.com/user-attachments/assets/2413e4a1-7f5e-499c-95b2-ac6296c4a6c7)

**Comment by teunbrand** [comment]
I share your sense that this is a cool idea, but I feel it is too much of a specialist option be included in ggplot2 and would have a better home in an extension package. One potential issue I foresee is that it is difficult to mix absolute units from e..g the `panel.spacing.x` theme setting with the relative ones describing the panels.
