### ISSUE TITLE
coord_flip() and coord_cartesian() are exclusive

### ISSUE THREAD

**Issue by etiennebr** [tidyverse/ggplot2#647]
It seems like i can't use `coord_cartesian()` with `coord_flip()`. It is one or the other, but can't combine them (always using the last one).

demo:

```
# regular
p <- qplot(disp, wt, data=mtcars) + geom_smooth(method = "loess")

# just flip
p + coord_flip()
# crop then flip (only flip)
p + coord_cartesian(ylim = c(3,5), xlim = c(100, 400)) + coord_flip()

# just crop
p + coord_cartesian(ylim = c(3,5), xlim = c(100, 400))
# flip then crop (only crop)
p + coord_flip() + coord_cartesian(ylim = c(3,5), xlim = c(100, 400))
```

**Comment by SamJake** [comment]
Thank you! I got this issue as well!

**Comment by cuixueqin** [comment]
Thank you. This actually has helped me.

**Comment by uxhub** [comment]
+1

**Comment by uxhub** [comment]
+1

**Comment by map2085** [comment]
+1

**Comment by mmidling** [comment]
+1

**Comment by batpigandme** [comment]
@uxhub, @map2085, @mmidling; just for future reference, feel free to use the reactions (👍 , etc.) in lieu of `+1`, since that ends up pinging maintainers on an already-closed issue.

Thanks!
