### ISSUE TITLE
geom_tile documentation missing width and height

### ISSUE THREAD

**Issue by csgillespie** [tidyverse/ggplot2#674]
The documentation for geom_tile doesn't list width and height as possible aesthetics:

http://docs.ggplot2.org/current/geom_tile.html

**Comment by YukunZhang** [comment]
So as for now, the width and height has been added right? Because code like `ggplot(data = sampledata) +
    geom_tile(aes(x = Time, y = Gender, fill = Grade, height = 0.25))` actually works.
