### ISSUE TITLE
make annotations outside of the plot area possible

### ISSUE THREAD

**Issue by jankatins** [tidyverse/ggplot2#682]
I would like to print some "explanation" next/below the plot. This seems to be really hard:
http://stackoverflow.com/questions/10014187/displaying-text-below-the-plot-generated-by-ggplot2

It would be nice if ggplot would have a call like 

```
p <- ...
p <- p + description(position="below", text="some explanation about the plot", wrap=T)
p
```

which would print the description below the plot (and wraps it, if needed -> see #681).

**Comment by konradedgar** [comment]
I'm currently generating a line chart and I was looking for this functionality. This is good idea and comparable functionalities are available in major statistical packages (i.e. Stata - note and caption). It is a commonly recognised good practice that the chart should be understandable if taken outside the context. The ideal solution is to encapsulate the relevant information with the graph definition.
@rmflight  Putting text in markdown or latex can prove cumbersome in a long run. Let's that I generated the chart that I want to include in a paper but may also include in a presentation or web publication. In addition re-running the chart command I will have to update bits and pieces of the text that maybe scatters across different media. It would be much easier to re-run the command with all the notes and captions and simply replace the graphic.

**Comment by ptoche** [comment]
For a short "explanation", if you do not otherwise need ``xlab`` (if you have dates, you probably don't need to have a label saying "date"), you can hijack it as follows:

      theme(axis.title.x = element_text(hjust=0, vjust=1)) +
      xlab("The shaded vertical bars indicate recessions.") + # hijack xlab!

**Comment by drawar** [comment]
I'm late to the party, but if you still want to make this kind of plot, then it's going to take more effort than just the caption, because you also need to add a second y-axis to the right side. I asked the same question on stackoverflow about making a very similar [chart][chart], and compiled the answers I received into a blogpost [here][here].

[chart]: http://i.imgur.com/OmPandU.png
[here]: http://drawar.github.io/posts/add-borders-annotate-outside-ggplot/

**Comment by ptoche** [comment]
@drawar , I don't see any mention of a second axis in the OP.

**Comment by drawar** [comment]
@ptoche You're right, but in one of his comments he said he wanted to create such a [chart][chart] from [The Economist][economist], which indeed has a second axis.

[chart]: http://media.economist.com/sites/default/files/imagecache/full-width/images/2013/01/blogs/graphic-detail/20130105_woc711_3.png
[economist]: http://www.economist.com/blogs/graphicdetail/2013/01/daily-chart-3
