### ISSUE TITLE
Automatic dodging or position_dodge not enforced on boxplots with missing values

### ISSUE THREAD

**Issue by apontejosea** [tidyverse/ggplot2#688]
I started this issue as a question in StackOverflow:
http://stackoverflow.com/questions/12806260/how-to-enforce-ggplots-position-dodge-on-categories-with-no-data

I'm trying to obtain boxplots of two different signals (ind) sharing the same categories (cat).  When there is a category with data for one signal but not for the other one, the boxplot for the signal with data covers all the horizontal spacing, and does not respect the position_dodge instruction for that particular category.  As you can see on the example below, the signal x has no data for category B, so it loses the space reserved by position_dodge.

Thanks in advance.

```
data<-data.frame(cat=c('A','A','A','A','B','B','A','A','A','A','B','B'), 
                 values=c(3,2,1,4,NA,NA,4,5,6,7,8,9), 
                 ind=c('x','x','x','x','x','x','y','y','y','y','y','y'))

print(ggplot() +
        scale_colour_hue(guide='none') +
      geom_boxplot(
           aes(x=as.factor(cat), y=values, 
               fill=ind), 
           position=position_dodge(width=.60), 
           data=data,
           outlier.size = 1.2,
           na.rm=T))
```

![graph with original problem](http://i.stack.imgur.com/rKbeq.png)

Here is what I have attempted so far:
1.  I first tried to change the color of boxes with missing data.  I couldn't figure out how to directly inject the desired color for a single box, as color information is automatically generated from signals (fill = data$ind in this case).
2.  Since that did not work, I exaggerated the dummy values out of the normal y-axis range (-1000), and I found something interesting happening that looks like a ggplot2 bug:

Here is the example data with a dummy value for the category with missing data:

```
data            <- data.frame(
cat=c('A','A','A','A','B','B','A','A','A','A','B','B','B'), 
values=c(3,2,1,4,NA,NA,4,5,6,7,8,9, -1000), 
ind=c('x','x','x','x','x','x','y','y','y','y','y','y','x'))

p  <- ggplot() +
      scale_colour_hue(guide='none') +
      geom_boxplot(aes(x=as.factor(cat), y=values, fill=ind),
      position=position_dodge(width=.60), 
      data=data,
      outlier.size = 1.2,
      na.rm=T)
```

As shown below, printing the plot as it is without defining y-axis limits, we get the correct behavior on the x-axis.  Of course the undesired dummy boxplot will also show up.

```
print(p)
```

![with no y-axis limits](http://i.stack.imgur.com/M3rXi.png)

But if we add the y limits, we still get the original undesired behavior.

```
print(p + ylim(0, 10))
```

![with y-axis limits](http://i.stack.imgur.com/FldHV.png)

**Comment by larry77** [comment]
Any progress on this? I am not so technically competent to implement this myself, but it would be a nice feature to have!
