### ISSUE TITLE
Feature request: Add a 'step' option to geom_ribbon

### ISSUE THREAD

**Issue by meow9th** [tidyverse/ggplot2#707]
I'm interested in being able to plot confidence intervals/bands for step functions (such as nonparametric estimated survival curves) using geom_ribbon. I've hacked up a solution using geom_rect, but I thought it would be nice if I could use geom_ribbon instead.

Here is an example using geom_rect:

``` R
library(survival)
aml.fit = survfit(Surv(time, status) ~ 1, data = aml)
aml.gg = do.call(data.frame,
                 summary(aml.fit)[c('time', 'surv', 'lower', 'upper')])
aml.rect = aml.gg[-nrow(aml.gg), ]
aml.rect$timemax = aml.gg$time[-1]
ggplot(aml.gg) +
  geom_step(aes(x = time, y = surv)) +
  geom_rect(data = aml.rect,
            aes(xmin = time, xmax = timemax, ymin = lower, ymax = upper),
            alpha = 0.1)
```

Here is how I would hope to use geom_ribbon instead:

``` R
ggplot(aml.gg) +
  geom_step(aes(x = time, y = surv)) +
  geom_ribbon(aes(x = time, ymin = lower, ymax = upper),
              step = T)
```

**Comment by kendonB** [comment]
+1

**Comment by kendonB** [comment]
Would the solution at https://groups.google.com/forum/?fromgroups=#!topic/ggplot2/9cFWHaH1CPs get accepted?
