### ISSUE TITLE
Default when order is not specifiied is not the ordering of the factors

### ISSUE THREAD

**Issue by BrianDiggs** [tidyverse/ggplot2#721]
# Summary

When the order aesthetic is not specified, stacked bar plots are not stacked in the order of the factors which differentiate them (say, fill). This was the case in 0.8.9, but has not been in 0.9.0 onward. I believe it should be the case again.
# Example code

```
DF <- expand.grid(A = c("A","B"), B = c("a", "b"))
DF$y <- seq_len(nrow(DF))
DF$B <- factor(DF$B, levels=rev(levels(DF$B)))

ggplot(DF, aes(x=A, y=y, fill=B)) +
    geom_bar(stat="identity")
```

In this, the bars are stacked with "a" on the bottom. The expected behavior can be achieved with 

```
ggplot(DF, aes(x=A, y=y, fill=B, order=B)) +
  geom_bar(stat="identity")
```

However, in the absence of a defined order, the order of the factor levels should be used.

The commit which changed this behavior is e2291558a6282bbf18c0ef8b70907c7ebd3bd8df

**Comment by bungie2016** [comment]
Thank you for share this one!!! Works very well!!!!
