### ISSUE TITLE
polygon with holes

### ISSUE THREAD

**Issue by kohske** [tidyverse/ggplot2#752]
holes of polygon is handled by `grid.path`, but current implementation of `geom_polygon` only uses `grid.polygon`.
Refer to this article by Paul for details.
http://journal.r-project.org/archive/2012-2/RJournal_2012-2_Murrell2.pdf

Will you provide a `grid.path` version of `geom_polygon`?

Here is a quick implementation and example.
http://rpubs.com/kohske/3522

You can see the "hole" at lat = 35.29 and long = 140.30.
See the bottom panel that indicates the hole by red fill.

kohske

**Comment by nachti** [comment]
Why is it closed?

**Comment by mattflor** [comment]
To anyone arriving here in search of a proper solution for issues with holes in polygons, I can recommend the ggpolypath package: https://cran.r-project.org/package=ggpolypath
It provides the geom `geom_polypath` that you can simply use instead of `geom_polygon`. Works great with shapefiles!
