### ISSUE TITLE
geom_crossbar & fill

### ISSUE THREAD

**Issue by manuelreif** [tidyverse/ggplot2#768]
I have a problem with the combination of geom_crossbar and "fill". 
What I want, is crossbars which are colored (filled) accordingly to the "Group1" variable (see example below) - what is no problem at all. 
The problem is that the legend does not show the fill colors, but black lines. I tried a lot but could not find any workaround to fix this!

Thank you!
Manuel

``` R
# create data
set.seed(907)
means <- rnorm(9,280,20)
sds   <- runif(9,0.5,1.5)
q25   <- means - rnorm(9,30,2)
q75   <- means + rnorm(9,33,2)

CDAT <- data.frame("XA"=rep(c("A","B","C"),each=3),"Group1"=factor(c(1,2,3)), "MEAN"=means, "SE"=sds,"q25"=q25, "q75"=q75)

# plotting
g1 <- ggplot(data=CDAT,aes(x=XA, y=MEAN, ymin=MEAN - 1.96*SE,  ymax=MEAN + 1.96*SE, fill=Group1))
g2 <- g1 + geom_crossbar(position = position_dodge(width = 0.62), alpha=1, width=0.6)
g2
```

![plot1](https://f.cloud.github.com/assets/1880318/200192/8d13ebde-80bc-11e2-984e-f8fff17d8300.png)

**Comment by dmi3kno** [comment]
This is not an issue, but rather I just need some advice: What if I would need to color upper and lower part of the bar differently, how would one go about modifying this geom?
