### ISSUE TITLE
Allow facets to span multiple pages

### ISSUE THREAD

**Issue by hadley** [tidyverse/ggplot2#86]
Proposed syntax: `page.layout = c(rows, cols)`

**Comment by guiastrennec** [comment]
I know this issue has been closed but for people like me who work with hundreds of facets, I have uploaded a ggplot2 wrapper on github that allows to use facet_wrap on multiple page. Check the facet_multiple() function [here](https://github.com/guiastrennec/ggplus). Hope it helps !

**Comment by pmBarlev** [comment]
facet_multiple() works well, thanks!

**Comment by thomasp85** [comment]
ggforce will also have `facet_wrap_paginate()` and `facet_grid_paginate()` once the next version of ggplot2 is released...

**Comment by daattali** [comment]
@thomasp85 would be useful if you provide a link to ggforce in your comment (of course I was able to find it on google). I see the paginate features are in the `facets` branch, will it not work with the current CRAN version of ggplot2?

**Comment by thomasp85** [comment]
It was written from a phone - I've updated the comment with link.

The facet branch requires the GitHub version to work, but the next ggplot2 release is imminent

**Comment by billdenney** [comment]
While the issue is closed, there are two good solutions.  I wonder if either @thomasp85 or @guiastrennec would perhaps suggest a pull request to ggplot that would enable your feature to provide a "page" argument to both `facet_wrap` and `facet_grid`?

**Comment by guiastrennec** [comment]
Thank you for your interest @billdenney. Unfortunately `ggplus::facet_multiple()` is no longer compatible with ggplot in v2.2.0 unlike `ggforce`.

**Comment by smouksassi** [comment]
@guiastrennec how does this ties in to your ggforce modifications in your xpose package ? Thoughts it is good to direct interested users to your edits

**Comment by guiastrennec** [comment]
@smouksassi thanks, I am happy to restart this conversation. @thomasp85 did a great job with `ggforce::facet_wrap_multiple()` and `ggforce_facet_grid_multiple()` and I am not sure that this can/needs to be integrated into the core `ggplot2` package?! 

In [`xpose`](https://uupharmacometrics.github.io/xpose/) I am using a wrapper of `ggplot2/ggforce` where (1) I added a new class to the resulting `ggplot2` plot object and (2) I used a special S3 print method for that class.  This allows the pages to draw to be selected at the time of printing, and the best part is that it automatically allows `ggsave()` to handle multiple pages as well.

``` r
library(ggplot2)
library(ggforce)

# Example plot
p <- ggplot(mtcars, aes(x = wt, y = hp)) +
  geom_point() +
  facet_wrap_paginate(facets = 'cyl', nrow = 1, ncol = 1, page = NULL)

# Here we add our special class
class(p) <- c('gg_multiple', class(p))

# You can now print or save all pages
print(p)
ggsave(p, filename = 'multiple_plot.pdf')
```
By default have all pages are being printed (i.e. `page = NULL`) but with the `print()` function shown below you can do things like `print(p, page = 1:2)`

Here is a minimal working example of the required functions. In [`xpose`](https://uupharmacometrics.github.io/xpose/) I added some more error checks, a progress bar and a paginating function. You can check the vignette [here](https://uupharmacometrics.github.io/xpose/articles/multiple_pages.html).
```r
print.gg_multiple <- function(x, page, ...) {
  # Get total number of pages
  page_tot <- ggforce::n_pages(repair_facet(x))
  
  # Get and check the page number to be drawn
  if (!missing(page)) {
    page_2_draw <- page
  } else {
    page_2_draw <- 1:page_tot
  }
  
  # Prevent issue with repair_facet when page = NULL
  x$facet$params$page <- page_2_draw
  
  # Begin multiple page ploting
  n_page_2_draw <- length(page_2_draw)
  
  # Draw all pages
  for (p in seq_along(page_2_draw)) {
    x$facet$params$page <- page_2_draw[p]
    ggplot2:::print.ggplot(x = repair_facet(x), ...)
    
  }
  
  # Prevent ggforce from droping multiple pages value
  x$facet$params$page <- page_2_draw
}

# Fix for ggforce facet_wrap_paginate
repair_facet <- function(x) {
  if (class(x$facet)[1] == 'FacetWrapPaginate' && 
      !'nrow' %in% names(x$facet$params)) {
    x$facet$params$nrow <- x$facet$params$max_row
  }
  x
}
```
