### ISSUE TITLE
annotation_logticks() and coord_flip() don't seem to get along

### ISSUE THREAD

**Issue by adsteen** [tidyverse/ggplot2#881]
`annotation_logticks()` and `coord_flip()` appear to be mutually incompatible. For instance: 

```
ggplot(mtcars, aes(x=mpg, y=disp)) + 
  geom_line() + 
  annotation_logticks() +
  coord_flip()
```

yields `Error in unit(yticks$y, "native") : 'x' and 'units' must have length > 0`. This plot works fine if either `annotation_logticks()` or `coord_flip()` is removed.

**Comment by jcrada** [comment]
This bug is still present in R 3.3.1 with ggplot2_2.1.0. Shouldn't this issue be opened?
