### ISSUE TITLE
confusing error message for facet_wrap()

### ISSUE THREAD

**Issue by adsteen** [tidyverse/ggplot2#891]
`facet_wrap()` throws a confusing error message when `scales="free"` and one of the factor levels contains only `NA`. For instance:

```
d <- data.frame(x=gl(2, 1, 4), y=c(1, 2, NA, NA), f=gl(2, 2, 4))
ggplot(d, aes(x, y)) +
  geom_point() +
  facet_wrap(~f, scale="free")
```

throws the error message: 

```
Error in seq.default(from = best$lmin, to = best$lmax, by = best$lstep) : 
  'from' must be of length 1 
```

This is pretty hard to diagnose. It would be helpful if this error were trapped by `facet_wrap` & a more explicit error message were provided.

**Comment by coolbutuseless** [comment]
Was about to resubmit this exact issue.  Will have a look into it, but my bandwidth is also low :/
